In [1]:
%load_ext autoreload
%autoreload 2

# Prepare full dataset
import pandas as pd
import pubchempy as pcp
import numpy as np


def get_fingerprint(cid: str):
    code = cid[4:]
    pubchem_compound_data = pcp.Compound.from_cid(int(code))
    fingerprint = bin(int(pubchem_compound_data.fingerprint, 16))
    return fingerprint


def add_row(df, cid, fingerprint):
    new_row = [cid] + list(fingerprint)
    df.loc[len(df)] = new_row
    return df


from SIDER_dataset.libraries.prepare_dataset_library import *

In [2]:
SIDER_dataset = pd.read_csv("datasets/original_datasets/SIDER-4.1/SIDER_dataset.csv")
ADRs = get_ADRs(SIDER_dataset)
print_dataset_info(SIDER_dataset, ADRs)
print("unique CIDs:", SIDER_dataset["CID1"].unique().size)
SIDER_dataset.head()

Number of instances: 1430
Number of CPI features: 0
Number of fingerprint features: 0
Number of features: 1
Number of ADRs: 4251
unique CIDs: 1430

,CID1,se__C0000727,se__C0000731,se__C0000735,se__C0000737,se__C0000768,se__C0000772,se__C0000786,se__C0000814,se__C0000817,...,se__C3665347,se__C3665356,se__C3665418,se__C3665444,se__C3665473,se__C3665624,se__C3665770,se__C3665795,se__C3665818,se__C3665888
0,CID100000085,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,CID100000119,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,CID100000137,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,CID100000143,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,CID100000146,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# No need to redo
# CID100000085 is carnitine according to SIDER/drug_names.tsv
pubchem_compound_data = pcp.Compound.from_cid(int("100000085"))
print(pubchem_compound_data.iupac_name)
print(pubchem_compound_data.synonyms)
pubchem_compound_data = pcp.Compound.from_cid(int("00000085"))
print(pubchem_compound_data.iupac_name)
print(pubchem_compound_data.synonyms)
# need to remove CID1 from codes

ethyl (1R,2S)-1-amino-2-(4-chlorophenyl)sulfonylcyclopropane-1-carboxylate
[]
(3-carboxy-2-hydroxypropyl)-trimethylazanium
['Carnitine', 'carnitinium', 'CHEBI:3424', 'Entomin', '3-carboxy-2-hydroxy-N,N,N-trimethylpropan-1-aminium', 'Carnitinum [INN-Latin]', '1-Propanaminium, 3-carboxy-2-hydroxy-N,N,N-trimethyl-, inner salt', 'Carnitina [INN-Spanish]', '3-carboxy-2-hydroxy-N,N,N-trimethylpropan-1-aminium chloride', '1-Propanaminium, 3-carboxy-2-hydroxy-N,N,N-trimethyl-, chloride', 'gamma-Trimethyl-hydroxybutyrobetaine', '3-hydroxy-4-trimethylammoniobutanoate', 'Spectrum_000067', 'Spectrum2_000009', 'Spectrum3_000576', 'Spectrum4_000388', 'Spectrum5_001473', 'bmse000074', 'bmse000949', 'BSPBio_001992', 'KBioGR_000915', 'KBioSS_000467', 'DivK1c_000470', 'SCHEMBL374454', 'SPBio_000017', 'CHEMBL1620698', 'KBio1_000470', 'KBio2_000467', 'KBio2_003035', 'KBio2_005603', 'KBio3_001492', 'NINDS_000470', 'ALBB-022446', 's5937', 'STL426849', 'AKOS015960448', 'SDCCGMLS-0066567.P001', 'IDI1_000470', 'NCGC00178874-01', 'NCGC00178874-03', 'SBI-0051562.P002', '3-hydroxy-4-(trimethylammonio)butanoic acid', 'NS00101168', 'NS00124347', 'C00487', 'AB00053811_07', 'AB00053811_08', 'BRD-A89594340-003-11-5', 'BRD-A89594340-003-12-3', 'Q27106070']

In [ ]:
# No need to redo
# Create df with fingerprint columns
fingerprint = get_fingerprint("CID100000085")
print(fingerprint)
print(len(fingerprint))
fingerprints_df = pd.DataFrame(
    columns=["CID1"] + [f"f_{i - 12}" for i in range(len(fingerprint))]
)
print(fingerprints_df.head())
# Get fingerprints for all CIDs in de2022interpretable_dataset
for cid in SIDER_dataset["CID1"].unique():
    # time.sleep(1)
    fingerprint = get_fingerprint(cid)
    fingerprints_df = add_row(fingerprints_df, cid, fingerprint)
# ~15m
fingerprints_df.to_csv("full_fingerprints_with_prefixes.csv", index=False)
fingerprints_df.head()

0b1101110001111000000110001000110000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011110000000000000000000001000000000000000000000001000000101001110000110000000000001100000001000001000000000110000000000000010000000000000100000000000000000001001000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000010000100000000000000000000000001000010000000101000000000010000000000000000000010001000000000000000000010100100000000000000001000000000000000000000010010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
900
Empty DataFrame
Columns: [CID, f_-12, f_-11, f_-10, f_-9, f_-8, f_-7, f_-6, f_-5, f_-4, f_-3, f_-2, f_-1, f_0, f_1, f_2, f_3, f_4, f_5, f_6, f_7, f_8, f_9, f_10, f_11, f_12, f_13, f_14, f_15, f_16, f_17, f_18, f_19, f_20, f_21, f_22, f_23, f_24, f_25, f_26, f_27, f_28, f_29, f_30, f_31, f_32, f_33, f_34, f_35, f_36, f_37, f_38, f_39, f_40, f_41, f_42, f_43, f_44, f_45, f_46, f_47, f_48, f_49, f_50, f_51, f_52, f_53, f_54, f_55, f_56, f_57, f_58, f_59, f_60, f_61, f_62, f_63, f_64, f_65, f_66, f_67, f_68, f_69, f_70, f_71, f_72, f_73, f_74, f_75, f_76, f_77, f_78, f_79, f_80, f_81, f_82, f_83, f_84, f_85, f_86, ...]
Index: []

[0 rows x 901 columns]

,CID,f_-12,f_-11,f_-10,f_-9,f_-8,f_-7,f_-6,f_-5,f_-4,...,f_878,f_879,f_880,f_881,f_882,f_883,f_884,f_885,f_886,f_887
0,CID100000085,0,b,1,1,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
1,CID100000119,0,b,1,1,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
2,CID100000137,0,b,1,1,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
3,CID100000143,0,b,1,1,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
4,CID100000146,0,b,1,1,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# No need to redo
fingerprints_df = pd.read_csv("datasets/original_datasets/full_fingerprints_with_prefixes.csv")
for col in fingerprints_df.columns:
    if fingerprints_df[col].nunique() == 1:
        print(f"All values in column {col} are identical.")
    else:
        print(f"Values in column {col} are NOT identical.")

Values in column CID are NOT identical.
All values in column f_-12 are identical.
All values in column f_-11 are identical.
All values in column f_-10 are identical.
All values in column f_-9 are identical.
All values in column f_-8 are identical.
All values in column f_-7 are identical.
All values in column f_-6 are identical.
All values in column f_-5 are identical.
All values in column f_-4 are identical.
All values in column f_-3 are identical.
All values in column f_-2 are identical.
All values in column f_-1 are identical.
Values in column f_0 are NOT identical.
Values in column f_1 are NOT identical.
Values in column f_2 are NOT identical.
Values in column f_3 are NOT identical.
Values in column f_4 are NOT identical.
Values in column f_5 are NOT identical.
Values in column f_6 are NOT identical.
All values in column f_7 are identical.
All values in column f_8 are identical.
Values in column f_9 are NOT identical.
Values in column f_10 are NOT identical.
Values in column f_11 are NOT identical.
Values in column f_12 are NOT identical.
Values in column f_13 are NOT identical.
Values in column f_14 are NOT identical.
Values in column f_15 are NOT identical.
Values in column f_16 are NOT identical.
Values in column f_17 are NOT identical.
Values in column f_18 are NOT identical.
Values in column f_19 are NOT identical.
Values in column f_20 are NOT identical.
Values in column f_21 are NOT identical.
Values in column f_22 are NOT identical.
Values in column f_23 are NOT identical.
Values in column f_24 are NOT identical.
Values in column f_25 are NOT identical.
Values in column f_26 are NOT identical.
Values in column f_27 are NOT identical.
All values in column f_28 are identical.
All values in column f_29 are identical.
Values in column f_30 are NOT identical.
Values in column f_31 are NOT identical.
Values in column f_32 are NOT identical.
Values in column f_33 are NOT identical.
Values in column f_34 are NOT identical.
Values in column f_35 are NOT identical.
Values in column f_36 are NOT identical.
Values in column f_37 are NOT identical.
Values in column f_38 are NOT identical.
Values in column f_39 are NOT identical.
Values in column f_40 are NOT identical.
Values in column f_41 are NOT identical.
Values in column f_42 are NOT identical.
Values in column f_43 are NOT identical.
Values in column f_44 are NOT identical.
Values in column f_45 are NOT identical.
Values in column f_46 are NOT identical.
Values in column f_47 are NOT identical.
Values in column f_48 are NOT identical.
All values in column f_49 are identical.
Values in column f_50 are NOT identical.
All values in column f_51 are identical.
Values in column f_52 are NOT identical.
All values in column f_53 are identical.
All values in column f_54 are identical.
All values in column f_55 are identical.
All values in column f_56 are identical.
Values in column f_57 are NOT identical.
Values in column f_58 are NOT identical.
Values in column f_59 are NOT identical.
All values in column f_60 are identical.
All values in column f_61 are identical.
Values in column f_62 are NOT identical.
Values in column f_63 are NOT identical.
Values in column f_64 are NOT identical.
Values in column f_65 are NOT identical.
Values in column f_66 are NOT identical.
All values in column f_67 are identical.
All values in column f_68 are identical.
Values in column f_69 are NOT identical.
Values in column f_70 are NOT identical.
All values in column f_71 are identical.
All values in column f_72 are identical.
All values in column f_73 are identical.
All values in column f_74 are identical.
All values in column f_75 are identical.
All values in column f_76 are identical.
Values in column f_77 are NOT identical.
All values in column f_78 are identical.
All values in column f_79 are identical.
All values in column f_80 are identical.
All values in column f_81 are identical.
All values in column f_82 are identical.
All values in column f_83 are identical.
All values in column f_84 are identical.
Values in column f_85 are NOT identical.
All values in column f_86 are identical.
All values in column f_87 are identical.
All values in column f_88 are identical.
All values in column f_89 are identical.
All values in column f_90 are identical.
All values in column f_91 are identical.
All values in column f_92 are identical.
Values in column f_93 are NOT identical.
Values in column f_94 are NOT identical.
All values in column f_95 are identical.
Values in column f_96 are NOT identical.
All values in column f_97 are identical.
All values in column f_98 are identical.
Values in column f_99 are NOT identical.
All values in column f_100 are identical.
All values in column f_101 are identical.
All values in column f_102 are identical.
All values in column f_103 are identical.
Values in column f_104 are NOT identical.
All values in column f_105 are identical.
Values in column f_106 are NOT identical.
All values in column f_107 are identical.
All values in column f_108 are identical.
All values in column f_109 are identical.
All values in column f_110 are identical.
All values in column f_111 are identical.
All values in column f_112 are identical.
Values in column f_113 are NOT identical.
All values in column f_114 are identical.
Values in column f_115 are NOT identical.
Values in column f_116 are NOT identical.
Values in column f_117 are NOT identical.
Values in column f_118 are NOT identical.
All values in column f_119 are identical.
All values in column f_120 are identical.
All values in column f_121 are identical.
Values in column f_122 are NOT identical.
Values in column f_123 are NOT identical.
Values in column f_124 are NOT identical.
Values in column f_125 are NOT identical.
All values in column f_126 are identical.
All values in column f_127 are identical.
All values in column f_128 are identical.
Values in column f_129 are NOT identical.
Values in column f_130 are NOT identical.
Values in column f_131 are NOT identical.
Values in column f_132 are NOT identical.
All values in column f_133 are identical.
All values in column f_134 are identical.
All values in column f_135 are identical.
Values in column f_136 are NOT identical.
All values in column f_137 are identical.
Values in column f_138 are NOT identical.
Values in column f_139 are NOT identical.
All values in column f_140 are identical.
All values in column f_141 are identical.
All values in column f_142 are identical.
Values in column f_143 are NOT identical.
Values in column f_144 are NOT identical.
Values in column f_145 are NOT identical.
Values in column f_146 are NOT identical.
All values in column f_147 are identical.
All values in column f_148 are identical.
All values in column f_149 are identical.
Values in column f_150 are NOT identical.
Values in column f_151 are NOT identical.
Values in column f_152 are NOT identical.
Values in column f_153 are NOT identical.
All values in column f_154 are identical.
All values in column f_155 are identical.
All values in column f_156 are identical.
Values in column f_157 are NOT identical.
Values in column f_158 are NOT identical.
Values in column f_159 are NOT identical.
Values in column f_160 are NOT identical.
All values in column f_161 are identical.
All values in column f_162 are identical.
All values in column f_163 are identical.
Values in column f_164 are NOT identical.
All values in column f_165 are identical.
Values in column f_166 are NOT identical.
Values in column f_167 are NOT identical.
All values in column f_168 are identical.
All values in column f_169 are identical.
All values in column f_170 are identical.
Values in column f_171 are NOT identical.
All values in column f_172 are identical.
Values in column f_173 are NOT identical.
Values in column f_174 are NOT identical.
All values in column f_175 are identical.
All values in column f_176 are identical.
All values in column f_177 are identical.
Values in column f_178 are NOT identical.
Values in column f_179 are NOT identical.
Values in column f_180 are NOT identical.
Values in column f_181 are NOT identical.
All values in column f_182 are identical.
All values in column f_183 are identical.
All values in column f_184 are identical.
Values in column f_185 are NOT identical.
Values in column f_186 are NOT identical.
Values in column f_187 are NOT identical.
Values in column f_188 are NOT identical.
All values in column f_189 are identical.
All values in column f_190 are identical.
All values in column f_191 are identical.
Values in column f_192 are NOT identical.
Values in column f_193 are NOT identical.
Values in column f_194 are NOT identical.
Values in column f_195 are NOT identical.
All values in column f_196 are identical.
All values in column f_197 are identical.
All values in column f_198 are identical.
Values in column f_199 are NOT identical.
Values in column f_200 are NOT identical.
Values in column f_201 are NOT identical.
Values in column f_202 are NOT identical.
All values in column f_203 are identical.
All values in column f_204 are identical.
All values in column f_205 are identical.
Values in column f_206 are NOT identical.
Values in column f_207 are NOT identical.
All values in column f_208 are identical.
Values in column f_209 are NOT identical.
All values in column f_210 are identical.
All values in column f_211 are identical.
All values in column f_212 are identical.
Values in column f_213 are NOT identical.
Values in column f_214 are NOT identical.
Values in column f_215 are NOT identical.
Values in column f_216 are NOT identical.
All values in column f_217 are identical.
All values in column f_218 are identical.
All values in column f_219 are identical.
Values in column f_220 are NOT identical.
All values in column f_221 are identical.
Values in column f_222 are NOT identical.
Values in column f_223 are NOT identical.
All values in column f_224 are identical.
All values in column f_225 are identical.
All values in column f_226 are identical.
Values in column f_227 are NOT identical.
Values in column f_228 are NOT identical.
Values in column f_229 are NOT identical.
Values in column f_230 are NOT identical.
All values in column f_231 are identical.
All values in column f_232 are identical.
All values in column f_233 are identical.
Values in column f_234 are NOT identical.
All values in column f_235 are identical.
All values in column f_236 are identical.
All values in column f_237 are identical.
All values in column f_238 are identical.
All values in column f_239 are identical.
All values in column f_240 are identical.
Values in column f_241 are NOT identical.
Values in column f_242 are NOT identical.
Values in column f_243 are NOT identical.
Values in column f_244 are NOT identical.
All values in column f_245 are identical.
All values in column f_246 are identical.
All values in column f_247 are identical.
Values in column f_248 are NOT identical.
Values in column f_249 are NOT identical.
Values in column f_250 are NOT identical.
Values in column f_251 are NOT identical.
All values in column f_252 are identical.
All values in column f_253 are identical.
All values in column f_254 are identical.
Values in column f_255 are NOT identical.
Values in column f_256 are NOT identical.
Values in column f_257 are NOT identical.
Values in column f_258 are NOT identical.
Values in column f_259 are NOT identical.
Values in column f_260 are NOT identical.
Values in column f_261 are NOT identical.
Values in column f_262 are NOT identical.
All values in column f_263 are identical.
All values in column f_264 are identical.
All values in column f_265 are identical.
All values in column f_266 are identical.
All values in column f_267 are identical.
All values in column f_268 are identical.
All values in column f_269 are identical.
All values in column f_270 are identical.
All values in column f_271 are identical.
All values in column f_272 are identical.
All values in column f_273 are identical.
Values in column f_274 are NOT identical.
All values in column f_275 are identical.
Values in column f_276 are NOT identical.
All values in column f_277 are identical.
All values in column f_278 are identical.
All values in column f_279 are identical.
All values in column f_280 are identical.
All values in column f_281 are identical.
All values in column f_282 are identical.
Values in column f_283 are NOT identical.
Values in column f_284 are NOT identical.
Values in column f_285 are NOT identical.
Values in column f_286 are NOT identical.
Values in column f_287 are NOT identical.
All values in column f_288 are identical.
All values in column f_289 are identical.
All values in column f_290 are identical.
All values in column f_291 are identical.
Values in column f_292 are NOT identical.
Values in column f_293 are NOT identical.
Values in column f_294 are NOT identical.
All values in column f_295 are identical.
All values in column f_296 are identical.
Values in column f_297 are NOT identical.
Values in column f_298 are NOT identical.
Values in column f_299 are NOT identical.
Values in column f_300 are NOT identical.
Values in column f_301 are NOT identical.
All values in column f_302 are identical.
All values in column f_303 are identical.
Values in column f_304 are NOT identical.
Values in column f_305 are NOT identical.
All values in column f_306 are identical.
All values in column f_307 are identical.
Values in column f_308 are NOT identical.
Values in column f_309 are NOT identical.
All values in column f_310 are identical.
All values in column f_311 are identical.
All values in column f_312 are identical.
All values in column f_313 are identical.
Values in column f_314 are NOT identical.
All values in column f_315 are identical.
All values in column f_316 are identical.
Values in column f_317 are NOT identical.
All values in column f_318 are identical.
All values in column f_319 are identical.
All values in column f_320 are identical.
All values in column f_321 are identical.
All values in column f_322 are identical.
Values in column f_323 are NOT identical.
All values in column f_324 are identical.
All values in column f_325 are identical.
All values in column f_326 are identical.
Values in column f_327 are NOT identical.
Values in column f_328 are NOT identical.
All values in column f_329 are identical.
Values in column f_330 are NOT identical.
Values in column f_331 are NOT identical.
Values in column f_332 are NOT identical.
Values in column f_333 are NOT identical.
Values in column f_334 are NOT identical.
Values in column f_335 are NOT identical.
Values in column f_336 are NOT identical.
Values in column f_337 are NOT identical.
Values in column f_338 are NOT identical.
Values in column f_339 are NOT identical.
Values in column f_340 are NOT identical.
Values in column f_341 are NOT identical.
Values in column f_342 are NOT identical.
Values in column f_343 are NOT identical.
Values in column f_344 are NOT identical.
Values in column f_345 are NOT identical.
Values in column f_346 are NOT identical.
Values in column f_347 are NOT identical.
Values in column f_348 are NOT identical.
Values in column f_349 are NOT identical.
Values in column f_350 are NOT identical.
Values in column f_351 are NOT identical.
Values in column f_352 are NOT identical.
Values in column f_353 are NOT identical.
All values in column f_354 are identical.
Values in column f_355 are NOT identical.
Values in column f_356 are NOT identical.
Values in column f_357 are NOT identical.
Values in column f_358 are NOT identical.
Values in column f_359 are NOT identical.
Values in column f_360 are NOT identical.
Values in column f_361 are NOT identical.
Values in column f_362 are NOT identical.
Values in column f_363 are NOT identical.
Values in column f_364 are NOT identical.
Values in column f_365 are NOT identical.
Values in column f_366 are NOT identical.
Values in column f_367 are NOT identical.
Values in column f_368 are NOT identical.
All values in column f_369 are identical.
Values in column f_370 are NOT identical.
Values in column f_371 are NOT identical.
Values in column f_372 are NOT identical.
Values in column f_373 are NOT identical.
Values in column f_374 are NOT identical.
Values in column f_375 are NOT identical.
Values in column f_376 are NOT identical.
Values in column f_377 are NOT identical.
Values in column f_378 are NOT identical.
Values in column f_379 are NOT identical.
Values in column f_380 are NOT identical.
Values in column f_381 are NOT identical.
Values in column f_382 are NOT identical.
Values in column f_383 are NOT identical.
Values in column f_384 are NOT identical.
Values in column f_385 are NOT identical.
Values in column f_386 are NOT identical.
Values in column f_387 are NOT identical.
Values in column f_388 are NOT identical.
Values in column f_389 are NOT identical.
Values in column f_390 are NOT identical.
Values in column f_391 are NOT identical.
Values in column f_392 are NOT identical.
Values in column f_393 are NOT identical.
Values in column f_394 are NOT identical.
Values in column f_395 are NOT identical.
Values in column f_396 are NOT identical.
Values in column f_397 are NOT identical.
Values in column f_398 are NOT identical.
Values in column f_399 are NOT identical.
Values in column f_400 are NOT identical.
Values in column f_401 are NOT identical.
All values in column f_402 are identical.
Values in column f_403 are NOT identical.
Values in column f_404 are NOT identical.
Values in column f_405 are NOT identical.
Values in column f_406 are NOT identical.
Values in column f_407 are NOT identical.
Values in column f_408 are NOT identical.
Values in column f_409 are NOT identical.
Values in column f_410 are NOT identical.
Values in column f_411 are NOT identical.
Values in column f_412 are NOT identical.
Values in column f_413 are NOT identical.
Values in column f_414 are NOT identical.
All values in column f_415 are identical.
Values in column f_416 are NOT identical.
Values in column f_417 are NOT identical.
Values in column f_418 are NOT identical.
Values in column f_419 are NOT identical.
Values in column f_420 are NOT identical.
Values in column f_421 are NOT identical.
Values in column f_422 are NOT identical.
Values in column f_423 are NOT identical.
All values in column f_424 are identical.
Values in column f_425 are NOT identical.
All values in column f_426 are identical.
Values in column f_427 are NOT identical.
Values in column f_428 are NOT identical.
Values in column f_429 are NOT identical.
Values in column f_430 are NOT identical.
Values in column f_431 are NOT identical.
Values in column f_432 are NOT identical.
All values in column f_433 are identical.
Values in column f_434 are NOT identical.
Values in column f_435 are NOT identical.
Values in column f_436 are NOT identical.
Values in column f_437 are NOT identical.
Values in column f_438 are NOT identical.
Values in column f_439 are NOT identical.
Values in column f_440 are NOT identical.
Values in column f_441 are NOT identical.
Values in column f_442 are NOT identical.
Values in column f_443 are NOT identical.
All values in column f_444 are identical.
Values in column f_445 are NOT identical.
Values in column f_446 are NOT identical.
Values in column f_447 are NOT identical.
Values in column f_448 are NOT identical.
Values in column f_449 are NOT identical.
Values in column f_450 are NOT identical.
Values in column f_451 are NOT identical.
Values in column f_452 are NOT identical.
Values in column f_453 are NOT identical.
Values in column f_454 are NOT identical.
Values in column f_455 are NOT identical.
Values in column f_456 are NOT identical.
Values in column f_457 are NOT identical.
Values in column f_458 are NOT identical.
Values in column f_459 are NOT identical.
Values in column f_460 are NOT identical.
Values in column f_461 are NOT identical.
Values in column f_462 are NOT identical.
All values in column f_463 are identical.
Values in column f_464 are NOT identical.
Values in column f_465 are NOT identical.

In [ ]:
# No need to redo
# Check that first 12 and last 7 columns have identical values across all instances (prefix+suffix)
# List of columns to check
columns_to_check = [
    "f_-12",
    "f_-11",
    "f_-10",
    "f_-9",
    "f_-8",

    "f_-7",
    "f_-6",
    "f_-5",
    "f_-4",
    "f_-3",
    "f_-2",
    "f_-1",
    "f_881",
    "f_882",
    "f_883",
    "f_884",
    "f_885",
    "f_886",
    "f_887",
]
# Check if the values are identical across all rows for the listed columns
for col in columns_to_check:
    if fingerprints_df[col].nunique() == 1:
        print(f"All values in {col} are identical.")
    else:
        print(f"Values in {col} are NOT identical.")
# Remove prefix/suffix columns
fingerprints_df = fingerprints_df.drop(columns=columns_to_check)
fingerprints_df.to_csv("fingerprints.csv", index=False)

All values in f_-12 are identical.
All values in f_-11 are identical.
All values in f_-10 are identical.
All values in f_-9 are identical.
All values in f_-8 are identical.
All values in f_-7 are identical.
All values in f_-6 are identical.
All values in f_-5 are identical.
All values in f_-4 are identical.
All values in f_-3 are identical.
All values in f_-2 are identical.
All values in f_-1 are identical.
All values in f_881 are identical.
All values in f_882 are identical.
All values in f_883 are identical.
All values in f_884 are identical.
All values in f_885 are identical.
All values in f_886 are identical.
All values in f_887 are identical.

In [ ]:
# TODO - Add CPI features to SIDER dataset
# SIDER_dataset = pd.read_csv("./SIDER-4.1/SIDER_dataset.csv")
# fingerprints_df = pd.read_csv("./fingerprints.csv")
# fingerprint_dataset = pd.merge(left=SIDER_dataset, right=fingerprints_df, on="CID1")
# fingerprint_dataset.to_csv("fingerprint_dataset.csv", index=False)
# ADRs = get_ADRs(fingerprint_dataset)
# print_dataset_info(fingerprint_dataset, ADRs)
# fingerprint_dataset.head()

In [3]:
# Add Fingerprint features to SIDER dataset
SIDER_dataset = pd.read_csv("datasets/original_datasets/SIDER-4.1/SIDER_dataset.csv")
fingerprints_df = pd.read_csv("datasets/original_datasets/fingerprints.csv")
fingerprint_dataset = pd.merge(left=SIDER_dataset, right=fingerprints_df, on="CID1")
fingerprint_dataset.to_csv("fingerprint_dataset.csv", index=False)
ADRs = get_ADRs(fingerprint_dataset)
print_dataset_info(fingerprint_dataset, ADRs)
fingerprint_dataset.head()

Number of instances: 1394
Number of CPI features: 0
Number of fingerprint features: 881
Number of features: 882
Number of ADRs: 4251

,CID1,se__C0000727,se__C0000731,se__C0000735,se__C0000737,se__C0000768,se__C0000772,se__C0000786,se__C0000814,se__C0000817,...,f_871,f_872,f_873,f_874,f_875,f_876,f_877,f_878,f_879,f_880
0,CID100000085,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,CID100000119,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,CID100000137,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,CID100000143,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,CID100000146,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
ADR_cols = fingerprint_dataset[ADRs]
# Sum each column and convert to a new DataFrame
summary_df = ADR_cols.sum().reset_index()
summary_df.columns = ["ADR", "Count"]
summary_df = summary_df.sort_values(by="Count", ascending=False)
summary_df.to_csv("ADR_frequency.csv")
print(summary_df)

               ADR  Count
962   se__C0027497   1179
578   se__C0018681   1092
347   se__C0011603   1070
463   se__C0015230   1062
1451  se__C0042963   1060
...            ...    ...
2750  se__C0423086      0
2833  se__C0473124      0
2829  se__C0458247      0
4211  se__C3160756      0
8     se__C0000817      0

[4251 rows x 2 columns]

In [ ]:
# REFACTORED UNTIL HERE

In [ ]:
# Clean dataset
full_dataset = pd.read_csv("datasets/original_datasets/full_dataset.csv")
clean_dataset = clean_dataset(full_dataset, 10, 10)
clean_dataset.to_csv("full_cleaned_dataset.csv", index=False)
clean_dataset.head()

After removing uninformative cpi features
Number of instances: 1394
Number of drugs: 1394
Number of CPI features: 1610
Number of fingerprint features: 881
Number of features: 2491
Number of ADRs: 1750

After removing uninformative fingerprint features
Number of instances: 1394
Number of drugs: 1394
Number of CPI features: 1610
Number of fingerprint features: 540
Number of features: 2150
Number of ADRs: 1750

After removing where all values are the same
Number of instances: 1394
Number of drugs: 1394
Number of CPI features: 1610
Number of fingerprint features: 540
Number of features: 2150
Number of ADRs: 1750

After removing duplicates - keeping one
Number of instances: 1394
Number of drugs: 1394
Number of CPI features: 1610
Number of fingerprint features: 540
Number of features: 2150
Number of ADRs: 1750

,CID,cpi_9606.ENSP00000000442,cpi_9606.ENSP00000001008,cpi_9606.ENSP00000003084,cpi_9606.ENSP00000003100,cpi_9606.ENSP00000005178,cpi_9606.ENSP00000011292,cpi_9606.ENSP00000011653,cpi_9606.ENSP00000012443,cpi_9606.ENSP00000013034,...,f_831,f_833,f_834,f_836,f_839,f_840,f_845,f_860,f_861,f_866
0,CID100000085,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,CID100000119,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,CID100000137,0,0,0,191,159,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,CID100000143,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,CID100000146,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# Create datasets
full_cleaned_dataset = pd.read_csv("datasets/original_datasets/full_cleaned_dataset.csv")
ADRs = get_ADRs(full_cleaned_dataset)
print_dataset_info(full_cleaned_dataset, ADRs)
full_cleaned_dataset.head()

Number of instances: 1394
Number of drugs: 1394
Number of CPI features: 1610
Number of fingerprint features: 540
Number of features: 2150
Number of ADRs: 1750

,CID,cpi_9606.ENSP00000000442,cpi_9606.ENSP00000001008,cpi_9606.ENSP00000003084,cpi_9606.ENSP00000003100,cpi_9606.ENSP00000005178,cpi_9606.ENSP00000011292,cpi_9606.ENSP00000011653,cpi_9606.ENSP00000012443,cpi_9606.ENSP00000013034,...,f_831,f_833,f_834,f_836,f_839,f_840,f_845,f_860,f_861,f_866
0,CID100000085,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,CID100000119,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,CID100000137,0,0,0,191,159,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,CID100000143,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,CID100000146,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
# Get ADR frequency
ADR_frequency_with_names = get_ADR_frequency(full_cleaned_dataset)
ADR_frequency_with_names.to_csv("./ADR_frequency.csv", index=False)
print(ADR_frequency_with_names.head(6))

full_cleaned_dataset_with_6_labels = keep_6_most_frequent_ADRs(full_cleaned_dataset)
full_cleaned_dataset_with_6_labels.head()

ADRs: 1750
             ADR  count  ADR_code
509  se_C0027497   1179  C0027497
295  se_C0018681   1092  C0018681
169  se_C0011603   1070  C0011603
233  se_C0015230   1062  C0015230
781  se_C0042963   1060  C0042963
UMLS_ids: 49561
total rows: 95912
UMLS_ids: 19973
total rows: 20307
     UMLS_id MedDRA_ADR_level  MedDRA_ADR_id       MedDRA_ADR_name
1   C0000727               PT       10000647         Acute abdomen
12  C0000731               PT       10000060  Abdominal distension
17  C0000734               PT       10000077        Abdominal mass
22  C0000735               PT       10060925    Abdominal neoplasm
27  C0000737               PT       10000081        Abdominal pain
UMLS_ids: 1421
total rows: 1511
UMLS_ids: 1421
total rows: 1421
             ADR  count  ADR_code         names  percentage
468  se_C0027497   1179  C0027497      [Nausea]    0.845768
273  se_C0018681   1092  C0018681    [Headache]    0.783357
157  se_C0011603   1070  C0011603  [Dermatitis]    0.767575
216  se_C0015230   1062  C0015230        [Rash]    0.761836
711  se_C0042963   1060  C0042963    [Vomiting]    0.760402
172  se_C0012833   1014  C0012833   [Dizziness]    0.727403
ADRs: 1750
             ADR  count  ADR_code
509  se_C0027497   1179  C0027497
295  se_C0018681   1092  C0018681
169  se_C0011603   1070  C0011603
233  se_C0015230   1062  C0015230
781  se_C0042963   1060  C0042963
UMLS_ids: 49561
total rows: 95912
UMLS_ids: 19973
total rows: 20307
     UMLS_id MedDRA_ADR_level  MedDRA_ADR_id       MedDRA_ADR_name
1   C0000727               PT       10000647         Acute abdomen
12  C0000731               PT       10000060  Abdominal distension
17  C0000734               PT       10000077        Abdominal mass
22  C0000735               PT       10060925    Abdominal neoplasm
27  C0000737               PT       10000081        Abdominal pain
UMLS_ids: 1421
total rows: 1511
UMLS_ids: 1421
total rows: 1421
Number of instances: 1394
Number of drugs: 1394
Number of CPI features: 1610
Number of fingerprint features: 540
Number of features: 2150
Number of ADRs: 6

,CID,cpi_9606.ENSP00000000442,cpi_9606.ENSP00000001008,cpi_9606.ENSP00000003084,cpi_9606.ENSP00000003100,cpi_9606.ENSP00000005178,cpi_9606.ENSP00000011292,cpi_9606.ENSP00000011653,cpi_9606.ENSP00000012443,cpi_9606.ENSP00000013034,...,f_831,f_833,f_834,f_836,f_839,f_840,f_845,f_860,f_861,f_866
0,CID100000085,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,CID100000119,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,CID100000137,0,0,0,191,159,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,CID100000143,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,CID100000146,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# Save datasets to csv format

# cpi+fingerprint dataset
ADRs = get_ADRs(full_cleaned_dataset_with_6_labels)
cpis = get_cpis(full_cleaned_dataset_with_6_labels)
fs = get_fs(full_cleaned_dataset_with_6_labels)
cpi_fingerprint_dataset = full_cleaned_dataset_with_6_labels[["CID"] + cpis + fs + ADRs]
print("cpi_fingerprint dataset")
ADRs = get_ADRs(cpi_fingerprint_dataset)
print_dataset_info(cpi_fingerprint_dataset, ADRs)
cpi_fingerprint_dataset.to_csv("cpi_fingerprint_dataset.csv", index=False)
print("\n")

# cpi dataset
cpi_dataset = full_cleaned_dataset_with_6_labels[["CID"] + cpis + ADRs]
print("cpi_dataset")
ADRs = get_ADRs(cpi_dataset)
print_dataset_info(cpi_dataset, ADRs)
cpi_dataset.to_csv("cpi_dataset.csv", index=False)
print("\n")

# fingerprint dataset
fingerprint_dataset = full_cleaned_dataset_with_6_labels[["CID"] + fs + ADRs]
print("fingerprint_dataset")
ADRs = get_ADRs(fingerprint_dataset)
print_dataset_info(fingerprint_dataset, ADRs)
fingerprint_dataset.to_csv("fingerprint_dataset.csv", index=False)
print("\n")

cpi_fingerprint dataset
Number of instances: 1394
Number of drugs: 1394
Number of CPI features: 1610
Number of fingerprint features: 540
Number of features: 2150
Number of ADRs: 6


cpi_dataset
Number of instances: 1394
Number of drugs: 1394
Number of CPI features: 1610
Number of fingerprint features: 0
Number of features: 1610
Number of ADRs: 6


fingerprint_dataset
Number of instances: 1394
Number of drugs: 1394
Number of CPI features: 0
Number of fingerprint features: 540
Number of features: 540
Number of ADRs: 6