In [1]:
%load_ext autoreload
%autoreload 2

from library import *
from SIDER_dataset.libraries.XofN_library import *
import itertools

In [2]:
# Test generate_feature_rankings
rows = 1000
features = 10
labels = 1
random_state = 42
ranking_criterion = "AUROC_MDI_MDA"
(
    test_df,
    label_columns,
    feature_columns,
    binary_feature_columns,
    prob_feature_columns,
) = get_test_df(rows, features, labels, random_state)

learn_set, val_set = train_test_split(test_df, test_size=0.2, random_state=random_state)
rankings = generate_feature_rankings(
    learn_set, val_set, label_columns[0], ranking_criterion
)

print(rankings["MDA"].sum())

rankings

TypeError: generate_feature_rankings() takes 2 positional arguments but 4 were given

In [ ]:
# Test generate groupings
rows = 1000
features = 1000
labels = 1
random_state = 42
ranking_criterion = "MDI"
training_algorithm = "DT"
eval_criterion = "roc_auc"
max_size = 5
label = label_columns[0]
dataset_name = "test_df"
include_original_features = False
(
    test_df,
    label_columns,
    feature_columns,
    binary_feature_columns,
    prob_feature_columns,
) = get_test_df(rows, features, labels, random_state)
test_df = test_df[binary_feature_columns + label_columns]
parameters_name = "_".join(
    [
        dataset_name,
        label,
        ranking_criterion,
        training_algorithm,
        eval_criterion,
        str(max_size),
        "with_org" if include_original_features else "no_org",
    ]
)
print(f"Running with parameters: {parameters_name}")

logging_path = f"XofN_datasets/auto_groupings/{parameters_name}_logs.txt"
print(f"Logs can be found in {logging_path}.")
logger = get_logger(logging_path)
logger.info(parameters_name)

learn_set, val_set = train_test_split(test_df, test_size=0.2, random_state=random_state)
rankings = generate_feature_rankings(learn_set, val_set, label, ranking_criterion)

print(f"Generating groupings...")

XofN_groupings, results = generate_XofN_list(
    training_algorithm,
    learn_set,
    val_set,
    rankings,
    eval_criterion,
    max_size,
    label,
    logger,
)

for handler in logging.root.handlers[:]:
    handler.close()
    logging.root.removeHandler(handler)

Running with parameters: test_df_label_1_MDI_DT_roc_auc_5_no_org
Logs can be found in XofN_datasets/auto_groupings/test_df_label_1_MDI_DT_roc_auc_5_no_org_logs.txt.

generate_feature_rankings -> Generating rankings based on ranking_criterion:MDI.

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

train
 Training with: algorithm: DT    instances: 1000   features: 500   labels: 1 ['label_1']
 Training...
Generating groupings...

TypeError: generate_XofN_list() takes 8 positional arguments but 9 were given

In [81]:
# Test group_features
rows = 1000
features = 20
labels = 1
random_state = 42
ranking_criterion = "MDI"
(
    dataset,
    label_columns,
    feature_columns,
    binary_feature_columns,
    prob_feature_columns,
) = get_test_df(rows, features, labels, random_state)

groups = [
    ["b_feature_1"],
    ["b_feature_8", "b_feature_9", "b_feature_10"],
    ["b_feature_3", "b_feature_4", "b_feature_5"],
]

dataset = group_features(dataset, label_columns, groups, True)
dataset

group_features
Number of original features: 20
Number of generated XofN group features: 3
Number of features in XofN groups: 7
Number of features not in XofN groups: 3
Number of XofN group features with a single item: 1

,b_feature_1,b_feature_2,b_feature_3,b_feature_4,b_feature_5,b_feature_6,b_feature_7,b_feature_8,b_feature_9,b_feature_10,...,p_feature_4,p_feature_5,p_feature_6,p_feature_7,p_feature_8,p_feature_9,p_feature_10,f_b_feature_8_b_feature_9_b_feature_10,f_b_feature_3_b_feature_4_b_feature_5,label_1
0,1,1,0,0,0,1,0,0,0,1,...,479,559,18,773,83,154,564,1,0,1
1,1,0,0,0,1,0,1,1,1,0,...,646,442,68,522,142,191,386,2,1,1
2,1,0,1,1,1,1,1,1,1,1,...,692,292,8,270,386,92,965,3,3,0
3,1,0,1,1,1,0,1,0,0,0,...,839,148,888,266,421,839,617,0,3,0
4,1,0,1,1,1,1,1,0,1,1,...,630,525,502,13,777,651,805,2,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1,1,0,0,0,1,0,0,0,1,...,479,559,18,773,83,154,564,1,0,1
996,1,1,0,0,0,1,0,0,0,1,...,479,559,18,773,83,154,564,1,0,1
997,1,1,0,0,0,1,0,0,0,1,...,479,559,18,773,83,154,564,1,0,1
998,1,1,0,0,0,1,0,0,0,1,...,479,559,18,773,83,154,564,1,0,1
999,1,1,0,0,0,1,0,0,0,1,...,479,559,18,773,83,154,564,1,0,1

In [ ]:
# Single label - No CV
rows = 1000
features = 100
labels = 6
random_state = 42
model_type = "RF"
df, label_columns, feature_columns, binary_feature_columns, prob_feature_columns = (
    get_test_df(rows, features, labels, random_state)
)

feature_threshold = round(len(df) * 1 / 100)

df, label_columns, feature_columns, binary_feature_columns, prob_feature_columns = (
    drop_uninformative_features(
        df,
        feature_threshold,
        label_columns,
        binary_feature_columns,
        prob_feature_columns,
    )
)

df = remove_inconsistent_duplicates(df, feature_columns, label_columns)

train_dataset, test_dataset = train_test_split(
    df,
    test_size=0.2,
    random_state=random_state,
)

model, importances = train(
    model_type,
    train_dataset,
    [label_columns[1]],
)

performance = test(model, test_dataset, [label_columns[1]])
performance

drop_uninformative_features
 Removing 0 uninformative binary features. Remaining binary features: 50
 Removing 0 uninformative probability scores features. Remaining probability features: 50
 Removing 2 uninformative features where all values are the same. Remaining features: 98

remove_inconsistent_duplicates
  Dropping 11 duplicate rows (keep first). Remaining rows: 989
  ❌ Deleting 10 inconsistent rows (same values for features but different for labels). Remaining: 979

train
 Training with:
    algorithm: RF
    instances: 783
    features: 103
    labels: 1 ['label_2']
 Training...

         accuracy  precision  recall        f1   roc_auc
label_2   0.52551   0.537634     0.5  0.518135  0.510469

In [ ]:
# Single label - CV
k = 10
model_type = "RF"
rows = 1000
features = 100
labels = 6
random_state = 42
df, label_columns, feature_columns, binary_feature_columns, prob_feature_columns = (
    get_test_df(rows, features, labels, random_state)
)

feature_threshold = round(len(df) * 1 / 100)

df, label_columns, feature_columns, binary_feature_columns, prob_feature_columns = (
    drop_uninformative_features(
        df,
        feature_threshold,
        label_columns,
        binary_feature_columns,
        prob_feature_columns,
    )
)

df = remove_inconsistent_duplicates(df, feature_columns, label_columns)

kf = KFold(n_splits=k, shuffle=True, random_state=random_state)
performance_dfs = []

for fold, (train_idx, test_idx) in enumerate(kf.split(df)):
    print(f"Fold {fold + 1}/{k}")

    train_dataset = df.iloc[train_idx]
    test_dataset = df.iloc[test_idx]

    model, importances = train(model_type, train_dataset, [label_columns[1]])
    performance_df = test(model, test_dataset, [label_columns[1]])
    performance_df["fold"] = fold + 1
    performance_dfs.append(performance_df)
    print(performance_df.to_string())

all_results, mean_results = get_cv_results(performance_dfs)
all_results

drop_uninformative_features
 Removing 0 uninformative binary features. Remaining binary features: 50
 Removing 0 uninformative probability scores features. Remaining probability features: 50
 Removing 2 uninformative features where all values are the same. Remaining features: 98

remove_inconsistent_duplicates
  Dropping 11 duplicate rows (keep first). Remaining rows: 989
  ❌ Deleting 10 inconsistent rows (same values for features but different for labels). Remaining: 979
Fold 1/10

train
 Training with:
    algorithm: RF
    instances: 881
    features: 103
    labels: 1 ['label_2']
 Training...

test
 Testing with:
    instances: 98
         accuracy  precision    recall        f1   roc_auc  fold
label_2  0.602041      0.625  0.510204  0.561798  0.613911     1
Fold 2/10

train
 Training with:
    algorithm: RF
    instances: 881
    features: 103
    labels: 1 ['label_2']
 Training...

test
 Testing with:
    instances: 98
         accuracy  precision    recall        f1   roc_auc  fold
label_2   0.55102   0.577778  0.509804  0.541667  0.488736     2
Fold 3/10

train
 Training with:
    algorithm: RF
    instances: 881
    features: 103
    labels: 1 ['label_2']
 Training...

test
 Testing with:
    instances: 98
         accuracy  precision  recall        f1   roc_auc  fold
label_2  0.540816   0.777778    0.35  0.482759  0.559649     3
Fold 4/10

train
 Training with:
    algorithm: RF
    instances: 881
    features: 103
    labels: 1 ['label_2']
 Training...

test
 Testing with:
    instances: 98
         accuracy  precision    recall        f1  roc_auc  fold
label_2  0.561224   0.560976  0.479167  0.516854   0.5775     4
Fold 5/10

train
 Training with:
    algorithm: RF
    instances: 881
    features: 103
    labels: 1 ['label_2']
 Training...

test
 Testing with:
    instances: 98
         accuracy  precision    recall        f1   roc_auc  fold
label_2  0.530612   0.526316  0.416667  0.465116  0.540625     5
Fold 6/10

train
 Training with:
    algorithm: RF
    instances: 881
    features: 103
    labels: 1 ['label_2']
 Training...

test
 Testing with:
    instances: 98
         accuracy  precision    recall        f1   roc_auc  fold
label_2   0.55102        0.4  0.444444  0.421053  0.484767     6
Fold 7/10

train
 Training with:
    algorithm: RF
    instances: 881
    features: 103
    labels: 1 ['label_2']
 Training...

test
 Testing with:
    instances: 98
         accuracy  precision    recall   f1   roc_auc  fold
label_2  0.571429        0.6  0.428571  0.5  0.595377     7
Fold 8/10

train
 Training with:
    algorithm: RF
    instances: 881
    features: 103
    labels: 1 ['label_2']
 Training...

test
 Testing with:
    instances: 98
         accuracy  precision    recall   f1   roc_auc  fold
label_2  0.530612   0.489362  0.511111  0.5  0.545283     8
Fold 9/10

train
 Training with:
    algorithm: RF
    instances: 881
    features: 103
    labels: 1 ['label_2']
 Training...

test
 Testing with:
    instances: 98
         accuracy  precision    recall    f1   roc_auc  fold
label_2  0.469388     0.4375  0.291667  0.35  0.369583     9
Fold 10/10

train
 Training with:
    algorithm: RF
    instances: 882
    features: 103
    labels: 1 ['label_2']
 Training...

test
 Testing with:
    instances: 97
         accuracy  precision  recall        f1   roc_auc  fold
label_2  0.536082   0.488889     0.5  0.494382  0.536664    10

      index  accuracy  precision    recall        f1   roc_auc  fold
0   label_2  0.602041   0.625000  0.510204  0.561798  0.613911     1
1   label_2  0.551020   0.577778  0.509804  0.541667  0.488736     2
2   label_2  0.540816   0.777778  0.350000  0.482759  0.559649     3
3   label_2  0.561224   0.560976  0.479167  0.516854  0.577500     4
4   label_2  0.530612   0.526316  0.416667  0.465116  0.540625     5
5   label_2  0.551020   0.400000  0.444444  0.421053  0.484767     6
6   label_2  0.571429   0.600000  0.428571  0.500000  0.595377     7
7   label_2  0.530612   0.489362  0.511111  0.500000  0.545283     8
8   label_2  0.469388   0.437500  0.291667  0.350000  0.369583     9
9   label_2  0.536082   0.488889  0.500000  0.494382  0.536664    10
10     mean  0.544425   0.548360  0.444163  0.483363  0.531210  None

In [ ]:
# Multi label - CV
k = 10
model_type = "RF"
rows = 1000
features = 100
labels = 6
random_state = 42
(
    test_df,
    label_columns,
    feature_columns,
    binary_feature_columns,
    prob_feature_columns,
) = get_test_df(rows, features, labels, random_state)
feature_threshold = round(len(df) * 1 / 100)

all_labels_cv_results = []
mean_labels_results = []
for current_label in label_columns:
    print(f"\n--- Processing label: {current_label} ---")
    current_df = test_df.drop(
        columns=[label for label in label_columns if label != current_label]
    )

    (
        current_df,
        current_labels,
        current_features,
        current_binary_features,
        current_prob_features,
    ) = drop_uninformative_features(
        current_df,
        feature_threshold,
        [current_label],
        binary_feature_columns,
        prob_feature_columns,
    )

    current_df = remove_inconsistent_duplicates(
        current_df, current_features, current_labels
    )

    kf = KFold(n_splits=k, shuffle=True, random_state=random_state)
    performance_dfs = []

    for fold, (train_idx, test_idx) in enumerate(kf.split(current_df)):
        print(f"Fold {fold + 1}/{k}")

        train_dataset = current_df.iloc[train_idx]
        test_dataset = current_df.iloc[test_idx]

        model, importances = train(model_type, train_dataset, current_labels)
        performance_df = test(model, test_dataset, current_labels)
        performance_df["fold"] = fold + 1
        performance_dfs.append(performance_df)
        print(performance_df.to_string())

    all_cv_results, mean_results = get_cv_results(performance_dfs)
    print(mean_results.to_string())

    all_labels_cv_results.append(all_cv_results)
    mean_labels_results.append(mean_results)

all_labels_results_df = pd.concat(all_labels_cv_results).reset_index()
mean_labels_results_df = get_macro_results(mean_labels_results)
mean_labels_results_df

--- Processing label: label_1 ---

drop_uninformative_features
 Removing 0 uninformative binary features. Remaining binary features: 50
 Removing 0 uninformative probability scores features. Remaining probability features: 50
 Removing 2 uninformative features where all values are the same. Remaining features: 103

remove_inconsistent_duplicates
  Dropping 11 duplicate rows (keep first). Remaining rows: 989
  ❌ Deleting 4 inconsistent rows (same values for features but different for labels). Remaining: 985
Fold 1/10

train
 Training with: algorithm: RF    instances: 886   features: 103   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision    recall        f1   roc_auc  fold
label_1  0.474747   0.507463  0.641509  0.566667  0.435193     1
Fold 2/10

train
 Training with: algorithm: RF    instances: 886   features: 103   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision  recall        f1   roc_auc  fold
label_1  0.525253   0.519481     0.8  0.629921  0.471633     2
Fold 3/10

train
 Training with: algorithm: RF    instances: 886   features: 103   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision    recall        f1   roc_auc  fold
label_1  0.484848   0.584615  0.612903  0.598425  0.390366     3
Fold 4/10

train
 Training with: algorithm: RF    instances: 886   features: 103   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision    recall        f1   roc_auc  fold
label_1  0.505051   0.482353  0.891304  0.625954  0.445652     4
Fold 5/10

train
 Training with: algorithm: RF    instances: 886   features: 103   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision    recall    f1   roc_auc  fold
label_1  0.444444        0.5  0.636364  0.56  0.460331     5
Fold 6/10

train
 Training with: algorithm: RF    instances: 887   features: 103   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold
label_1  0.520408   0.554054  0.745455  0.635659  0.531501     6
Fold 7/10

train
 Training with: algorithm: RF    instances: 887   features: 103   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold
label_1   0.44898   0.479452  0.686275  0.564516  0.419691     7
Fold 8/10

train
 Training with: algorithm: RF    instances: 887   features: 103   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold
label_1  0.530612   0.506667  0.808511  0.622951  0.569462     8
Fold 9/10

train
 Training with: algorithm: RF    instances: 887   features: 103   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 98
         accuracy  precision    recall     f1   roc_auc  fold
label_1  0.622449   0.619718  0.814815  0.704  0.561869     9
Fold 10/10

train
 Training with: algorithm: RF    instances: 887   features: 103   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 98
         accuracy  precision    recall       f1   roc_auc  fold
label_1   0.55102   0.552632  0.807692  0.65625  0.527174    10
         accuracy  precision    recall        f1   roc_auc
label
label_1  0.510781   0.530643  0.744483  0.616434  0.481287

--- Processing label: label_2 ---

drop_uninformative_features
 Removing 0 uninformative binary features. Remaining binary features: 50
 Removing 0 uninformative probability scores features. Remaining probability features: 50
 Removing 2 uninformative features where all values are the same. Remaining features: 103

remove_inconsistent_duplicates
  Dropping 11 duplicate rows (keep first). Remaining rows: 989
  ❌ Deleting 2 inconsistent rows (same values for features but different for labels). Remaining: 987
Fold 1/10

train
 Training with: algorithm: RF    instances: 888   features: 103   labels: 1 ['label_2']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision    recall        f1   roc_auc  fold
label_2  0.515152   0.536585  0.431373  0.478261  0.477124     1
Fold 2/10

train
 Training with: algorithm: RF    instances: 888   features: 103   labels: 1 ['label_2']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision    recall   f1   roc_auc  fold
label_2  0.515152        0.6  0.428571  0.5  0.616694     2
Fold 3/10

train
 Training with: algorithm: RF    instances: 888   features: 103   labels: 1 ['label_2']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision    recall        f1   roc_auc  fold
label_2  0.565657   0.557692  0.591837  0.574257  0.536735     3
Fold 4/10

train
 Training with: algorithm: RF    instances: 888   features: 103   labels: 1 ['label_2']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision  recall        f1   roc_auc  fold
label_2  0.575758   0.545455     0.4  0.461538  0.603086     4
Fold 5/10

train
 Training with: algorithm: RF    instances: 888   features: 103   labels: 1 ['label_2']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision    recall       f1   roc_auc  fold
label_2  0.525253        0.5  0.446809  0.47191  0.543372     5
Fold 6/10

train
 Training with: algorithm: RF    instances: 888   features: 103   labels: 1 ['label_2']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision    recall        f1   roc_auc  fold
label_2  0.505051   0.413043  0.463415  0.436782  0.550673     6
Fold 7/10

train
 Training with: algorithm: RF    instances: 888   features: 103   labels: 1 ['label_2']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision    recall        f1   roc_auc  fold
label_2  0.525253   0.488889  0.478261  0.483516  0.556604     7
Fold 8/10

train
 Training with: algorithm: RF    instances: 889   features: 103   labels: 1 ['label_2']
 Training...

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold
label_2       0.5        0.6  0.277778  0.379747  0.544402     8
Fold 9/10

train
 Training with: algorithm: RF    instances: 889   features: 103   labels: 1 ['label_2']
 Training...

test
 Testing with:  instances: 98
         accuracy  precision  recall        f1   roc_auc  fold
label_2       0.5   0.483871  0.3125  0.379747  0.428542     9
Fold 10/10

train
 Training with: algorithm: RF    instances: 889   features: 103   labels: 1 ['label_2']
 Training...

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold
label_2  0.469388   0.404762  0.386364  0.395349  0.522727    10
         accuracy  precision    recall        f1   roc_auc
label
label_2  0.519666    0.51303  0.421691  0.456111  0.537996

--- Processing label: label_3 ---

drop_uninformative_features
 Removing 0 uninformative binary features. Remaining binary features: 50
 Removing 0 uninformative probability scores features. Remaining probability features: 50
 Removing 2 uninformative features where all values are the same. Remaining features: 103

remove_inconsistent_duplicates
  Dropping 11 duplicate rows (keep first). Remaining rows: 989
Fold 1/10

train
 Training with: algorithm: RF    instances: 890   features: 103   labels: 1 ['label_3']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision  recall        f1   roc_auc  fold
label_3  0.515152   0.559322     0.6  0.578947  0.482438     1
Fold 2/10

train
 Training with: algorithm: RF    instances: 890   features: 103   labels: 1 ['label_3']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision    recall        f1   roc_auc  fold
label_3  0.484848   0.476923  0.645833  0.548673  0.471814     2
Fold 3/10

train
 Training with: algorithm: RF    instances: 890   features: 103   labels: 1 ['label_3']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision    recall   f1   roc_auc  fold
label_3  0.474747   0.472727  0.530612  0.5  0.445102     3
Fold 4/10

train
 Training with: algorithm: RF    instances: 890   features: 103   labels: 1 ['label_3']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision  recall        f1   roc_auc  fold
label_3  0.505051   0.490909  0.5625  0.524272  0.499387     4
Fold 5/10

train
 Training with: algorithm: RF    instances: 890   features: 103   labels: 1 ['label_3']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision    recall        f1   roc_auc  fold
label_3  0.474747        0.5  0.480769  0.490196  0.493453     5
Fold 6/10

train
 Training with: algorithm: RF    instances: 890   features: 103   labels: 1 ['label_3']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision    recall        f1   roc_auc  fold
label_3  0.505051   0.484375  0.659574  0.558559  0.480974     6
Fold 7/10

train
 Training with: algorithm: RF    instances: 890   features: 103   labels: 1 ['label_3']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision  recall        f1   roc_auc  fold
label_3  0.515152   0.517241     0.6  0.555556  0.493469     7
Fold 8/10

train
 Training with: algorithm: RF    instances: 890   features: 103   labels: 1 ['label_3']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision    recall        f1   roc_auc  fold
label_3  0.515152   0.612245  0.508475  0.555556  0.542373     8
Fold 9/10

train
 Training with: algorithm: RF    instances: 890   features: 103   labels: 1 ['label_3']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision    recall        f1   roc_auc  fold
label_3  0.474747   0.528302  0.509091  0.518519  0.447314     9
Fold 10/10

train
 Training with: algorithm: RF    instances: 891   features: 103   labels: 1 ['label_3']
 Training...

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold
label_3   0.44898    0.42623  0.577778  0.490566  0.504403    10
         accuracy  precision    recall        f1   roc_auc
label
label_3  0.491363   0.506827  0.567463  0.532084  0.486073

--- Processing label: label_4 ---

drop_uninformative_features
 Removing 0 uninformative binary features. Remaining binary features: 50
 Removing 0 uninformative probability scores features. Remaining probability features: 50
 Removing 2 uninformative features where all values are the same. Remaining features: 103

remove_inconsistent_duplicates
  Dropping 11 duplicate rows (keep first). Remaining rows: 989
  ❌ Deleting 4 inconsistent rows (same values for features but different for labels). Remaining: 985
Fold 1/10

train
 Training with: algorithm: RF    instances: 886   features: 103   labels: 1 ['label_4']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision    recall        f1   roc_auc  fold
label_4  0.535354   0.569231  0.672727  0.616667  0.510331     1
Fold 2/10

train
 Training with: algorithm: RF    instances: 886   features: 103   labels: 1 ['label_4']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision    recall        f1  roc_auc  fold
label_4  0.505051   0.515625  0.647059  0.573913  0.49326     2
Fold 3/10

train
 Training with: algorithm: RF    instances: 886   features: 103   labels: 1 ['label_4']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision    recall        f1   roc_auc  fold
label_4  0.494949   0.491228  0.571429  0.528302  0.507959     3
Fold 4/10

train
 Training with: algorithm: RF    instances: 886   features: 103   labels: 1 ['label_4']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision    recall        f1   roc_auc  fold
label_4  0.515152    0.52381  0.647059  0.578947  0.557598     4
Fold 5/10

train
 Training with: algorithm: RF    instances: 886   features: 103   labels: 1 ['label_4']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision    recall        f1   roc_auc  fold
label_4  0.424242   0.428571  0.489796  0.457143  0.447551     5
Fold 6/10

train
 Training with: algorithm: RF    instances: 887   features: 103   labels: 1 ['label_4']
 Training...

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold
label_4  0.510204       0.55  0.611111  0.578947  0.510522     6
Fold 7/10

train
 Training with: algorithm: RF    instances: 887   features: 103   labels: 1 ['label_4']
 Training...

test
 Testing with:  instances: 98
         accuracy  precision  recall        f1   roc_auc  fold
label_4       0.5   0.509804    0.52  0.514851  0.488542     7
Fold 8/10

train
 Training with: algorithm: RF    instances: 887   features: 103   labels: 1 ['label_4']
 Training...

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold
label_4  0.459184   0.508475  0.555556  0.530973  0.381734     8
Fold 9/10

train
 Training with: algorithm: RF    instances: 887   features: 103   labels: 1 ['label_4']
 Training...

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold
label_4  0.520408   0.516129  0.653061  0.576577  0.549979     9
Fold 10/10

train
 Training with: algorithm: RF    instances: 887   features: 103   labels: 1 ['label_4']
 Training...

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold
label_4  0.520408   0.483871  0.666667  0.560748  0.496646    10
         accuracy  precision    recall        f1   roc_auc
label
label_4  0.498495   0.509674  0.603446  0.551707  0.494412

--- Processing label: label_5 ---

drop_uninformative_features
 Removing 0 uninformative binary features. Remaining binary features: 50
 Removing 0 uninformative probability scores features. Remaining probability features: 50
 Removing 2 uninformative features where all values are the same. Remaining features: 103

remove_inconsistent_duplicates
  Dropping 11 duplicate rows (keep first). Remaining rows: 989
Fold 1/10

train
 Training with: algorithm: RF    instances: 890   features: 103   labels: 1 ['label_5']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision   recall        f1   roc_auc  fold
label_5  0.474747   0.526316  0.37037  0.434783  0.510288     1
Fold 2/10

train
 Training with: algorithm: RF    instances: 890   features: 103   labels: 1 ['label_5']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision    recall        f1   roc_auc  fold
label_5  0.525253   0.471698  0.568182  0.515464  0.608678     2
Fold 3/10

train
 Training with: algorithm: RF    instances: 890   features: 103   labels: 1 ['label_5']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision  recall       f1   roc_auc  fold
label_5  0.525253   0.538462    0.42  0.47191  0.563061     3
Fold 4/10

train
 Training with: algorithm: RF    instances: 890   features: 103   labels: 1 ['label_5']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision    recall        f1   roc_auc  fold
label_5  0.666667   0.673913  0.632653  0.652632  0.714898     4
Fold 5/10

train
 Training with: algorithm: RF    instances: 890   features: 103   labels: 1 ['label_5']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision  recall        f1   roc_auc  fold
label_5  0.565657   0.571429    0.56  0.565657  0.526939     5
Fold 6/10

train
 Training with: algorithm: RF    instances: 890   features: 103   labels: 1 ['label_5']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision  recall       f1   roc_auc  fold
label_5  0.454545   0.458333    0.44  0.44898  0.444694     6
Fold 7/10

train
 Training with: algorithm: RF    instances: 890   features: 103   labels: 1 ['label_5']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision    recall        f1   roc_auc  fold
label_5  0.525253       0.45  0.658537  0.534653  0.546678     7
Fold 8/10

train
 Training with: algorithm: RF    instances: 890   features: 103   labels: 1 ['label_5']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision  recall        f1   roc_auc  fold
label_5  0.535354   0.478261     0.5  0.488889  0.560331     8
Fold 9/10

train
 Training with: algorithm: RF    instances: 890   features: 103   labels: 1 ['label_5']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision  recall        f1   roc_auc  fold
label_5  0.515152   0.617647   0.375  0.466667  0.539659     9
Fold 10/10

train
 Training with: algorithm: RF    instances: 891   features: 103   labels: 1 ['label_5']
 Training...

test
 Testing with:  instances: 98
         accuracy  precision    recall   f1   roc_auc  fold
label_5   0.55102   0.611111  0.423077  0.5  0.576296    10
         accuracy  precision    recall        f1   roc_auc
label
label_5   0.53389   0.539717  0.494782  0.507963  0.559152

--- Processing label: label_6 ---

drop_uninformative_features
 Removing 0 uninformative binary features. Remaining binary features: 50
 Removing 0 uninformative probability scores features. Remaining probability features: 50
 Removing 2 uninformative features where all values are the same. Remaining features: 103

remove_inconsistent_duplicates
  Dropping 11 duplicate rows (keep first). Remaining rows: 989
  ❌ Deleting 6 inconsistent rows (same values for features but different for labels). Remaining: 983
Fold 1/10

train
 Training with: algorithm: RF    instances: 884   features: 103   labels: 1 ['label_6']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision    recall        f1   roc_auc  fold
label_6  0.505051   0.464286  0.276596  0.346667  0.538052     1
Fold 2/10

train
 Training with: algorithm: RF    instances: 884   features: 103   labels: 1 ['label_6']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision    recall        f1   roc_auc  fold
label_6  0.575758   0.448276  0.333333  0.382353  0.528632     2
Fold 3/10

train
 Training with: algorithm: RF    instances: 884   features: 103   labels: 1 ['label_6']
 Training...

test
 Testing with:  instances: 99
         accuracy  precision    recall        f1   roc_auc  fold
label_6  0.454545   0.413793  0.244898  0.307692  0.446735     3
Fold 4/10

train
 Training with: algorithm: RF    instances: 885   features: 103   labels: 1 ['label_6']
 Training...

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold
label_6  0.581633   0.421053  0.210526  0.280702  0.513158     4
Fold 5/10

train
 Training with: algorithm: RF    instances: 885   features: 103   labels: 1 ['label_6']
 Training...

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold
label_6  0.540816        0.5  0.222222  0.307692  0.580084     5
Fold 6/10

train
 Training with: algorithm: RF    instances: 885   features: 103   labels: 1 ['label_6']
 Training...

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold
label_6  0.479592   0.411765  0.145833  0.215385  0.532917     6
Fold 7/10

train
 Training with: algorithm: RF    instances: 885   features: 103   labels: 1 ['label_6']
 Training...

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold
label_6  0.530612   0.461538  0.272727  0.342857  0.443182     7
Fold 8/10

train
 Training with: algorithm: RF    instances: 885   features: 103   labels: 1 ['label_6']
 Training...

test
 Testing with:  instances: 98
         accuracy  precision    recall       f1   roc_auc  fold
label_6  0.561224   0.588235  0.217391  0.31746  0.485368     8
Fold 9/10

train
 Training with: algorithm: RF    instances: 885   features: 103   labels: 1 ['label_6']
 Training...

test

     label  accuracy  precision    recall        f1   roc_auc
0  label_1  0.510781   0.530643  0.744483  0.616434  0.481287
1  label_2  0.519666   0.513030  0.421691  0.456111  0.537996
2  label_3  0.491363   0.506827  0.567463  0.532084  0.486073
3  label_4  0.498495   0.509674  0.603446  0.551707  0.494412
4  label_5  0.533890   0.539717  0.494782  0.507963  0.559152
5  label_6  0.530066   0.495895  0.231526  0.309284  0.506297
6    Macro  0.514043   0.515964  0.510565  0.495597  0.510870

In [ ]:
k = 10
model_type = "RF"
rows = 1000
features = 10
labels = 6
random_state = 42
(
    test_df,
    label_columns,
    feature_columns,
    binary_feature_columns,
    prob_feature_columns,
) = get_test_df(rows, features, labels, random_state)
feature_threshold = round(len(test_df) * 1 / 100)
dataset_name = "test_dataset"
params = {
    "label": label_columns[:1],
    "ranking_criterion": ["roc_auc", "MDI"],
    "training_algorithm": ["DT"],
    "eval_criterion": ["roc_auc"],
    "include_original_features": [False, True],
    "max_size": [5],
}
all_labels_cv_results = []
mean_labels_results = []
for combo in itertools.product(*params.values()):
    config = dict(zip(params.keys(), combo))
    current_label = config["label"]
    ranking_criterion = config["ranking_criterion"]
    training_algorithm = config["training_algorithm"]
    eval_criterion = config["eval_criterion"]
    include_original_features = config["include_original_features"]
    max_size = config["max_size"]
    run_config = f"\n--- Running with label:'{current_label}' ranking_criterion:'{ranking_criterion}' training_algorithm:'{training_algorithm}' eval_criterion:'{eval_criterion}' include_original_features:'{include_original_features}' max_size:'{max_size}' ---"
    print(run_config)
    run_config_name = "_".join(
        [
            current_label,
            ranking_criterion,
            training_algorithm,
            eval_criterion,
            "with_org" if include_original_features else "no_org",
            str(max_size),
        ]
    )
    logging_path = f"XofN_datasets/auto_groupings/{run_config_name}_logs.txt"
    print(f"Logs can be found in {logging_path}.")
    logger = get_logger(logging_path)
    logger.info(run_config_name)

    current_df = test_df.drop(
        columns=[label for label in label_columns if label != current_label]
    )
    # current_df = current_df.drop(columns=["CID"])

    (
        current_df,
        current_labels,
        current_features,
        current_binary_features,
        current_prob_features,
    ) = drop_uninformative_features(
        current_df,
        feature_threshold,
        [current_label],
        binary_feature_columns,
    )

    current_df = remove_inconsistent_duplicates(
        current_df, current_features, current_labels
    )

    kf = KFold(n_splits=k, shuffle=True, random_state=random_state)
    performance_dfs = []

    for fold, (train_idx, test_idx) in enumerate(kf.split(current_df)):
        print(f"\nFold {fold + 1}/{k}")

        train_dataset = current_df.iloc[train_idx]
        test_dataset = current_df.iloc[test_idx]
        cache_results_path = f"XofN_datasets/auto_groupings/{dataset_name}_{current_label}_cache_results.json"
        cache_results = get_cache_results(cache_results_path)

        learn_set, val_set = train_test_split(
            train_dataset, test_size=0.2, random_state=42
        )

        rankings = generate_feature_rankings(
            learn_set, val_set, current_label, ranking_criterion
        )

        XofN_groupings, results = generate_XofN_list(
            training_algorithm,
            learn_set,
            val_set,
            rankings,
            eval_criterion,
            max_size,
            current_label,
            cache_results,
            logger,
        )

        train_dataset = group_features(
            train_dataset,
            [current_label],
            XofN_groupings,
            include_original_features,
        )

        test_dataset = group_features(
            test_dataset,
            [current_label],
            XofN_groupings,
            include_original_features,
        )

        with open(cache_results_path, "w") as f:
            json.dump(cache_results, f, indent=4)

        model, importances = train(model_type, train_dataset, current_labels)
        performance_df = test(model, test_dataset, current_labels)
        performance_df["fold"] = fold + 1
        performance_df["ranking_criterion"] = ranking_criterion
        performance_df["training_algorithm"] = training_algorithm
        performance_df["eval_criterion"] = eval_criterion
        performance_df["include_original_features"] = (
            "with_org" if include_original_features else "no_org"
        )
        performance_df["max_size"] = str(max_size)
        performance_dfs.append(performance_df)
        print(performance_df.to_string())

    all_cv_results, mean_results = get_cv_results(performance_dfs)
    print(f"\nCV results: ", mean_results.to_string())

    all_labels_cv_results.append(all_cv_results)
    mean_labels_results.append(mean_results)

for handler in logging.root.handlers[:]:
    handler.close()
    logging.root.removeHandler(handler)

all_labels_cv_results_df = pd.concat(all_labels_cv_results).reset_index()
all_labels_mean_cv_results_df = get_mean_cv_results(all_labels_cv_results_df)
all_labels_mean_cv_results_df
# mean_labels_results_df = get_macro_results(all_labels_cv_results_df)
# mean_labels_results_df

--- Running with label:'label_1' ranking_criterion:'roc_auc' training_algorithm:'DT' eval_criterion:'roc_auc' include_original_features:'False' max_size:'5' ---
Logs can be found in XofN_datasets/auto_groupings/label_1_roc_auc_DT_roc_auc_no_org_5_logs.txt.

drop_uninformative_features
 Removing 0 uninformative binary features. Remaining binary features: 5
 Removing 2 uninformative features where all values are the same. Remaining features: 8

remove_inconsistent_duplicates
  Dropping 19 duplicate rows (keep first). Remaining rows: 981
  ❌ Deleting 2 inconsistent rows (same values for features but different for labels). Remaining: 979

Fold 1/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:roc_auc.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.536723        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.536723        0.0     0.0  0.0  0.511489

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.536723        0.0     0.0  0.0  0.505392

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_5  0.536723        0.0     0.0  0.0  0.515661

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.536723        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_3  0.491525   0.442857  0.378049  0.407895  0.471566

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall     f1   roc_auc
p_feature_4  0.480226   0.435897  0.414634  0.425  0.492234

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_5  0.514124   0.471429  0.402439  0.434211  0.513286

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall        f1   roc_auc       MDI
b_feature_5  0.536723   0.000000  0.000000  0.000000  0.515661  0.020927
p_feature_5  0.514124   0.471429  0.402439  0.434211  0.513286  0.266213
b_feature_3  0.536723   0.000000  0.000000  0.000000  0.511489  0.043020
b_feature_4  0.536723   0.000000  0.000000  0.000000  0.505392  0.032612
b_feature_2  0.536723   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_2  0.536723   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_4  0.480226   0.435897  0.414634  0.425000  0.492234  0.333463
p_feature_3  0.491525   0.442857  0.378049  0.407895  0.471566  0.303765

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
b_feature_5_p_feature_5: 0.47304236200256733
b_feature_5_b_feature_3: 0.5210526315789474
b_feature_5_b_feature_3_b_feature_4: 0.48292682926829267
b_feature_5_b_feature_3_b_feature_2: 0.5210526315789474
b_feature_5_b_feature_3_p_feature_2: 0.5210526315789474
b_feature_5_b_feature_3_p_feature_4: 0.49980744544287553
b_feature_5_b_feature_3_p_feature_3: 0.44987163029525035
p_feature_5_b_feature_4: 0.517201540436457
p_feature_5_b_feature_4_b_feature_2: 0.5238125802310655
p_feature_5_b_feature_4_b_feature_2_p_feature_2: 0.5277278562259308
p_feature_5_b_feature_4_b_feature_2_p_feature_2_p_feature_4: 0.4563543003851091
p_feature_5_b_feature_4_b_feature_2_p_feature_2_p_feature_3: 0.500385109114249
p_feature_4_p_feature_3: 0.4904364569961489
XofN_groups: [['b_feature_5', 'b_feature_3'], ['p_feature_5', 'b_feature_4', 'b_feature_2', 'p_feature_2']]

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 6
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 6
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 4   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1   0.44898   0.414634  0.361702  0.386364  0.460576     1           roc_auc                 DT        roc_auc                    no_org        5

Fold 2/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:roc_auc.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.564972        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.564972        0.0     0.0  0.0  0.417273

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.564972        0.0     0.0  0.0  0.497273

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_5  0.564972        0.0     0.0  0.0  0.549221

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.564972        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_3  0.570621   0.507937  0.415584  0.457143  0.537597

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_4  0.485876   0.402778  0.376623  0.389262  0.487792

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_5  0.519774   0.435484  0.350649  0.388489  0.520714

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall        f1   roc_auc       MDI
b_feature_5  0.564972   0.000000  0.000000  0.000000  0.549221  0.018634
p_feature_3  0.570621   0.507937  0.415584  0.457143  0.537597  0.313026
p_feature_5  0.519774   0.435484  0.350649  0.388489  0.520714  0.338978
b_feature_2  0.564972   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_2  0.564972   0.000000  0.000000  0.000000  0.500000  0.000000
b_feature_4  0.564972   0.000000  0.000000  0.000000  0.497273  0.029845
p_feature_4  0.485876   0.402778  0.376623  0.389262  0.487792  0.274036
b_feature_3  0.564972   0.000000  0.000000  0.000000  0.417273  0.025482

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
b_feature_5_p_feature_3: 0.5016883116883116
b_feature_5_p_feature_5: 0.47304236200256733
b_feature_5_b_feature_2: 0.5492207792207793
b_feature_5_p_feature_2: 0.5492207792207793
b_feature_5_b_feature_4: 0.567987012987013
b_feature_5_b_feature_4_p_feature_4: 0.5407792207792208
b_feature_5_b_feature_4_b_feature_3: 0.5618181818181818
p_feature_3_p_feature_5: 0.5367532467532468
p_feature_3_b_feature_2: 0.5375974025974026
p_feature_3_p_feature_2: 0.5375974025974026
p_feature_3_p_feature_4: 0.4767532467532467
p_feature_3_b_feature_3: 0.555
p_feature_5_b_feature_2: 0.5207142857142857
p_feature_5_p_feature_2: 0.5207142857142857
p_feature_5_p_feature_4: 0.48376623376623373
b_feature_2_p_feature_2: 0.5
b_feature_2_p_feature_4: 0.4877922077922078
p_feature_2_p_feature_4: 0.4877922077922078
XofN_groups: [['b_feature_5', 'b_feature_4'], ['p_feature_3', 'b_feature_3']]

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 4
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 4
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 6   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision    recall   f1   roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1  0.479592        0.5  0.333333  0.4  0.468085     2           roc_auc                 DT        roc_auc                    no_org        5

Fold 3/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:roc_auc.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.531073        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.531073        0.0     0.0  0.0  0.420405

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.531073        0.0     0.0  0.0  0.482825

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
b_feature_5  0.491525   0.462366  0.518072  0.488636  0.493079

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.531073        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall   f1   roc_auc
p_feature_3  0.457627   0.415584  0.385542  0.4  0.471674

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_4  0.502825   0.459016  0.337349  0.388889  0.496219

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision   recall        f1   roc_auc
p_feature_5  0.497175   0.458333  0.39759  0.425806  0.502243

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall        f1   roc_auc       MDI
p_feature_5  0.497175   0.458333  0.397590  0.425806  0.502243  0.254391
b_feature_2  0.531073   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_2  0.531073   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_4  0.502825   0.459016  0.337349  0.388889  0.496219  0.326912
b_feature_5  0.491525   0.462366  0.518072  0.488636  0.493079  0.039029
b_feature_4  0.531073   0.000000  0.000000  0.000000  0.482825  0.039494
p_feature_3  0.457627   0.415584  0.385542  0.400000  0.471674  0.306520
b_feature_3  0.531073   0.000000  0.000000  0.000000  0.420405  0.033655

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
p_feature_5_b_feature_2: 0.5207142857142857
p_feature_5_b_feature_2_p_feature_2: 0.5022430146116381
p_feature_5_b_feature_2_p_feature_4: 0.4835298641374006
p_feature_5_b_feature_2_b_feature_5: 0.4969879518072289
p_feature_5_b_feature_2_b_feature_4: 0.4951294539861574
p_feature_5_b_feature_2_p_feature_3: 0.5349269418097924
p_feature_5_b_feature_2_p_feature_3_b_feature_3: 0.5122404511663676
p_feature_2_p_feature_4: 0.4877922077922078
p_feature_2_b_feature_5: 0.4930786977698026
p_feature_2_b_feature_4: 0.48282491668802874
p_feature_2_b_feature_3: 0.42040502435273003
p_feature_4_b_feature_5: 0.4880799794924378
p_feature_4_b_feature_4: 0.5089079723147911
p_feature_4_b_feature_4_b_feature_3: 0.5415278133811844
XofN_groups: [['p_feature_5', 'b_feature_2', 'p_feature_3'], ['p_feature_4', 'b_feature_4', 'b_feature_3']]

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 6
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 6
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 4   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision    recall   f1   roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1  0.540816   0.454545  0.357143  0.4  0.476828     3           roc_auc                 DT        roc_auc                    no_org        5

Fold 4/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:roc_auc.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.531073        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.531073        0.0     0.0  0.0  0.478211

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.531073        0.0     0.0  0.0  0.436747

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_5  0.531073        0.0     0.0  0.0  0.536337

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.531073        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_3  0.548023   0.520548  0.457831  0.487179  0.525122

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_4  0.497175   0.461538  0.433735  0.447205  0.492374

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_5  0.497175   0.455882  0.373494  0.410596  0.502499

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall        f1   roc_auc       MDI
b_feature_5  0.531073   0.000000  0.000000  0.000000  0.536337  0.013001
p_feature_3  0.548023   0.520548  0.457831  0.487179  0.525122  0.296814
p_feature_5  0.497175   0.455882  0.373494  0.410596  0.502499  0.295881
b_feature_2  0.531073   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_2  0.531073   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_4  0.497175   0.461538  0.433735  0.447205  0.492374  0.327283
b_feature_3  0.531073   0.000000  0.000000  0.000000  0.478211  0.031067
b_feature_4  0.531073   0.000000  0.000000  0.000000  0.436747  0.035954

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
b_feature_5_p_feature_3: 0.5016883116883116
b_feature_5_p_feature_5: 0.47304236200256733
b_feature_5_b_feature_2: 0.5492207792207793
b_feature_5_b_feature_2_p_feature_2: 0.5363368367085363
b_feature_5_b_feature_2_p_feature_4: 0.47667264803896436
b_feature_5_b_feature_2_b_feature_3: 0.5285183286336836
b_feature_5_b_feature_2_b_feature_4: 0.5072417328890029
p_feature_3_p_feature_5: 0.5367532467532468
p_feature_3_p_feature_5_p_feature_2: 0.4335426813637529
p_feature_3_p_feature_5_p_feature_4: 0.4856447064855166
p_feature_3_p_feature_5_b_feature_3: 0.4796206100999744
p_feature_3_p_feature_5_b_feature_4: 0.4835298641374006
p_feature_2_p_feature_4: 0.4877922077922078
p_feature_2_b_feature_3: 0.42040502435273003
p_feature_2_b_feature_4: 0.48282491668802874
p_feature_4_b_feature_3: 0.5
p_feature_4_b_feature_3_b_feature_4: 0.45578056908485
XofN_groups: [['b_feature_5', 'b_feature_2'], ['p_feature_3', 'p_feature_5'], ['p_feature_4', 'b_feature_3']]

group_features
Number of original features: 8
Number of generated XofN group features: 3
Number of features in XofN groups: 6
Number of features not in XofN groups: 3
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 3
Number of features in XofN groups: 6
Number of features not in XofN groups: 3
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 5   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision    recall       f1   roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1  0.520408   0.477273  0.466667  0.47191  0.525367     4           roc_auc                 DT        roc_auc                    no_org        5

Fold 5/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:roc_auc.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.564972        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.564972        0.0     0.0  0.0  0.480779

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.564972        0.0     0.0  0.0  0.507273

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
b_feature_5  0.531073   0.466667  0.545455  0.502994  0.532727

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.564972        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_3  0.508475   0.432432  0.415584  0.423841  0.484805

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_4  0.497175   0.409091  0.350649  0.377622  0.474416

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall      f1   roc_auc
p_feature_5  0.536723    0.46988  0.506494  0.4875  0.534156

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall        f1   roc_auc       MDI
p_feature_5  0.536723   0.469880  0.506494  0.487500  0.534156  0.314335
b_feature_5  0.531073   0.466667  0.545455  0.502994  0.532727  0.012046
b_feature_4  0.564972   0.000000  0.000000  0.000000  0.507273  0.034558
b_feature_2  0.564972   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_2  0.564972   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_3  0.508475   0.432432  0.415584  0.423841  0.484805  0.302082
b_feature_3  0.564972   0.000000  0.000000  0.000000  0.480779  0.041182
p_feature_4  0.497175   0.409091  0.350649  0.377622  0.474416  0.295798

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
p_feature_5_b_feature_5: 0.5123376623376623
p_feature_5_b_feature_4: 0.517201540436457
p_feature_5_b_feature_2: 0.5207142857142857
p_feature_5_p_feature_2: 0.5207142857142857
p_feature_5_p_feature_3: 0.48824675324675326
p_feature_5_b_feature_3: 0.5094155844155844
p_feature_5_p_feature_4: 0.48376623376623373
b_feature_5_b_feature_4: 0.567987012987013
b_feature_5_b_feature_4_b_feature_2: 0.547012987012987
b_feature_5_b_feature_4_p_feature_2: 0.547012987012987
b_feature_5_b_feature_4_p_feature_3: 0.5186363636363636
b_feature_5_b_feature_4_b_feature_3: 0.5618181818181818
b_feature_5_b_feature_4_p_feature_4: 0.5407792207792208
b_feature_2_p_feature_2: 0.5
b_feature_2_p_feature_3: 0.4848051948051948
b_feature_2_b_feature_3: 0.48077922077922075
b_feature_2_p_feature_4: 0.4877922077922078
p_feature_2_p_feature_3: 0.4848051948051948
p_feature_2_b_feature_3: 0.42040502435273003
p_feature_2_p_feature_4: 0.4877922077922078
p_feature_3_b_feature_3: 0.555
p_feature_3_b_feature_3_p_feature_4: 0.46532467532467536
XofN_groups: [['b_feature_5', 'b_feature_4'], ['p_feature_3', 'b_feature_3']]

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 4
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 4
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 6   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1  0.357143   0.302326  0.282609  0.292135  0.329222     5           roc_auc                 DT        roc_auc                    no_org        5

Fold 6/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:roc_auc.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.559322        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.559322        0.0     0.0  0.0  0.432789

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.559322        0.0     0.0  0.0  0.526418

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
b_feature_5  0.491525   0.434783  0.512821  0.470588  0.493784

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.559322        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_3  0.468927   0.397436  0.397436  0.397436  0.462963

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_4  0.519774   0.449275  0.397436  0.421769  0.500324

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_5  0.514124   0.455556  0.525641  0.488095  0.511396

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall        f1   roc_auc       MDI
b_feature_4  0.559322   0.000000  0.000000  0.000000  0.526418  0.040326
p_feature_5  0.514124   0.455556  0.525641  0.488095  0.511396  0.274493
p_feature_4  0.519774   0.449275  0.397436  0.421769  0.500324  0.289433
b_feature_2  0.559322   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_2  0.559322   0.000000  0.000000  0.000000  0.500000  0.000000
b_feature_5  0.491525   0.434783  0.512821  0.470588  0.493784  0.030262
p_feature_3  0.468927   0.397436  0.397436  0.397436  0.462963  0.318377
b_feature_3  0.559322   0.000000  0.000000  0.000000  0.432789  0.047109

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
b_feature_4_p_feature_5: 0.49067599067599066
b_feature_4_p_feature_4: 0.5027195027195027
b_feature_4_b_feature_2: 0.5264180264180265
b_feature_4_p_feature_2: 0.5264180264180265
b_feature_4_b_feature_5: 0.5062160062160062
b_feature_4_p_feature_3: 0.4424371924371924
b_feature_4_b_feature_3: 0.5332167832167831
p_feature_5_p_feature_4: 0.48376623376623373
p_feature_5_b_feature_2: 0.5207142857142857
p_feature_5_b_feature_2_p_feature_2: 0.5022430146116381
p_feature_5_b_feature_2_b_feature_5: 0.4969879518072289
p_feature_5_b_feature_2_p_feature_3: 0.5349269418097924
p_feature_4_p_feature_2: 0.5003237503237503
p_feature_4_b_feature_5: 0.4880799794924378
p_feature_2_b_feature_5: 0.4930786977698026
XofN_groups: [['b_feature_4', 'b_feature_3'], ['p_feature_5', 'b_feature_2', 'p_feature_3']]

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 5
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 5
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 5   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1  0.459184   0.395349  0.386364  0.390805  0.410774     6           roc_auc                 DT        roc_auc                    no_org        5

Fold 7/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:roc_auc.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.581921        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.581921        0.0     0.0  0.0  0.417148

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.581921        0.0     0.0  0.0  0.494818

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_5  0.581921        0.0     0.0  0.0  0.527552

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.581921        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_3  0.491525   0.397436  0.418919  0.407895  0.484978

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall        f1   roc_auc
p_feature_4  0.564972   0.480519     0.5  0.490066  0.551036

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1  roc_auc
p_feature_5  0.548023       0.45  0.364865  0.402985  0.53011

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall        f1   roc_auc       MDI
p_feature_4  0.564972   0.480519  0.500000  0.490066  0.551036  0.356278
p_feature_5  0.548023   0.450000  0.364865  0.402985  0.530110  0.295338
b_feature_5  0.581921   0.000000  0.000000  0.000000  0.527552  0.023704
b_feature_2  0.581921   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_2  0.581921   0.000000  0.000000  0.000000  0.500000  0.000000
b_feature_4  0.581921   0.000000  0.000000  0.000000  0.494818  0.037305
p_feature_3  0.491525   0.397436  0.418919  0.407895  0.484978  0.258570
b_feature_3  0.581921   0.000000  0.000000  0.000000  0.417148  0.028806

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
p_feature_4_p_feature_5: 0.47920493308842826
p_feature_4_b_feature_5: 0.4880799794924378
p_feature_4_b_feature_2: 0.5510364733665705
p_feature_4_p_feature_2: 0.5003237503237503
p_feature_4_b_feature_4: 0.5089079723147911
p_feature_4_p_feature_3: 0.4904364569961489
p_feature_4_b_feature_3: 0.5
p_feature_5_b_feature_5: 0.5123376623376623
p_feature_5_b_feature_2: 0.5207142857142857
p_feature_5_p_feature_2: 0.5207142857142857
p_feature_5_b_feature_4: 0.517201540436457
p_feature_5_p_feature_3: 0.48824675324675326
p_feature_5_b_feature_3: 0.5094155844155844
b_feature_5_b_feature_2: 0.5492207792207793
b_feature_5_b_feature_2_p_feature_2: 0.5363368367085363
b_feature_5_b_feature_2_b_feature_4: 0.5072417328890029
b_feature_5_b_feature_2_p_feature_3: 0.4488323274731042
b_feature_5_b_feature_2_b_feature_3: 0.5285183286336836
p_feature_2_b_feature_4: 0.48282491668802874
p_feature_2_p_feature_3: 0.4848051948051948
p_feature_2_b_feature_3: 0.42040502435273003
b_feature_4_p_feature_3: 0.4424371924371924
b_feature_4_b_feature_3: 0.5332167832167831
XofN_groups: [['b_feature_5', 'b_feature_2'], ['b_feature_4', 'b_feature_3']]

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 4
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 4
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 6   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1  roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1  0.530612    0.47619  0.454545  0.465116  0.51915     7           roc_auc                 DT        roc_auc                    no_org        5

Fold 8/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:roc_auc.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.525424        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.525424        0.0     0.0  0.0  0.454301

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.525424        0.0     0.0  0.0  0.523618

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1  roc_auc
b_feature_5  0.559322   0.535714  0.535714  0.535714  0.55818

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.525424        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_3  0.514124   0.486486  0.428571  0.455696  0.502496

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_4  0.502825   0.472222  0.404762  0.435897  0.477791

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1  roc_auc
p_feature_5  0.525424        0.5  0.404762  0.447368  0.50704

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall        f1   roc_auc       MDI
b_feature_5  0.559322   0.535714  0.535714  0.535714  0.558180  0.008926
b_feature_4  0.525424   0.000000  0.000000  0.000000  0.523618  0.034450
p_feature_5  0.525424   0.500000  0.404762  0.447368  0.507040  0.379312
p_feature_3  0.514124   0.486486  0.428571  0.455696  0.502496  0.242737
p_feature_2  0.525424   0.000000  0.000000  0.000000  0.500000  0.000000
b_feature_2  0.525424   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_4  0.502825   0.472222  0.404762  0.435897  0.477791  0.295863
b_feature_3  0.525424   0.000000  0.000000  0.000000  0.454301  0.038711

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
b_feature_5_b_feature_4: 0.567987012987013
b_feature_5_b_feature_4_p_feature_5: 0.5356502816180235
b_feature_5_b_feature_4_p_feature_3: 0.5186363636363636
b_feature_5_b_feature_4_p_feature_2: 0.547012987012987
b_feature_5_b_feature_4_b_feature_2: 0.547012987012987
b_feature_5_b_feature_4_p_feature_4: 0.5407792207792208
b_feature_5_b_feature_4_b_feature_3: 0.5618181818181818
p_feature_5_p_feature_3: 0.48824675324675326
p_feature_5_p_feature_2: 0.5207142857142857
p_feature_5_p_feature_2_b_feature_2: 0.5070404505888377
p_feature_5_p_feature_2_p_feature_4: 0.5397465437788018
p_feature_5_p_feature_2_p_feature_4_b_feature_3: 0.4539170506912442
p_feature_3_b_feature_2: 0.5375974025974026
p_feature_3_b_feature_2_b_feature_3: 0.5196492575524834
XofN_groups: [['b_feature_5', 'b_feature_4'], ['p_feature_5', 'p_feature_2', 'p_feature_4'], ['p_feature_3', 'b_feature_2']]

group_features
Number of original features: 8
Number of generated XofN group features: 3
Number of features in XofN groups: 7
Number of features not in XofN groups: 3
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 3
Number of features in XofN groups: 7
Number of features not in XofN groups: 3
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 4   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1  0.489796   0.378378  0.341463  0.358974  0.495293     8           roc_auc                 DT        roc_auc                    no_org        5

Fold 9/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:roc_auc.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.548023        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.548023        0.0     0.0  0.0  0.550064

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.548023        0.0     0.0  0.0  0.463982

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_5  0.548023        0.0     0.0  0.0  0.571005

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.548023        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
p_feature_3  0.570621   0.527778   0.475  0.5  0.559729

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall       f1   roc_auc
p_feature_4  0.531073    0.47619   0.375  0.41958  0.490464

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall        f1   roc_auc
p_feature_5  0.508475   0.444444    0.35  0.391608  0.499936

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision  recall        f1   roc_auc       MDI
b_feature_5  0.548023   0.000000   0.000  0.000000  0.571005  0.025280
p_feature_3  0.570621   0.527778   0.475  0.500000  0.559729  0.341532
b_feature_3  0.548023   0.000000   0.000  0.000000  0.550064  0.018590
b_feature_2  0.548023   0.000000   0.000  0.000000  0.500000  0.000000
p_feature_2  0.548023   0.000000   0.000  0.000000  0.500000  0.000000
p_feature_5  0.508475   0.444444   0.350  0.391608  0.499936  0.286832
p_feature_4  0.531073   0.476190   0.375  0.419580  0.490464  0.277317
b_feature_4  0.548023   0.000000   0.000  0.000000  0.463982  0.050448

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
b_feature_5_p_feature_3: 0.5016883116883116
b_feature_5_b_feature_3: 0.5210526315789474
b_feature_5_b_feature_2: 0.5492207792207793
b_feature_5_p_feature_2: 0.5492207792207793
b_feature_5_p_feature_5: 0.47304236200256733
b_feature_5_p_feature_4: 0.48769329896907215
b_feature_5_b_feature_4: 0.567987012987013
p_feature_3_b_feature_3: 0.555
p_feature_3_b_feature_2: 0.5375974025974026
p_feature_3_p_feature_2: 0.5375974025974026
p_feature_3_p_feature_5: 0.5367532467532468
p_feature_3_p_feature_4: 0.4767532467532467
p_feature_3_b_feature_4: 0.5234536082474227
b_feature_3_b_feature_2: 0.5500644329896908
b_feature_3_p_feature_2: 0.5500644329896908
b_feature_3_p_feature_5: 0.5381443298969072
b_feature_3_p_feature_4: 0.5282216494845361
b_feature_3_b_feature_4: 0.4614690721649484
b_feature_2_p_feature_2: 0.5
b_feature_2_p_feature_5: 0.4999355670103093
b_feature_2_p_feature_4: 0.4877922077922078
b_feature_2_b_feature_4: 0.46398195876288656
p_feature_2_p_feature_5: 0.4999355670103093
p_feature_2_p_feature_4: 0.4877922077922078
p_feature_2_b_feature_4: 0.48282491668802874
p_feature_5_p_feature_4: 0.48376623376623373
p_feature_5_b_feature_4: 0.517201540436457
XofN_groups: [['p_feature_5', 'b_feature_4']]

group_features
Number of original features: 8
Number of generated XofN group features: 1
Number of features in XofN groups: 2
Number of features not in XofN groups: 1
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 1
Number of features in XofN groups: 2
Number of features not in XofN groups: 1
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 7   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision    recall     f1   roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1   0.44898   0.351351  0.302326  0.325  0.424313     9           roc_auc                 DT        roc_auc                    no_org        5

Fold 10/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:roc_auc.

train
 Training with: algorithm: DT    instances: 705   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.559322        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 705   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.559322        0.0     0.0  0.0  0.514957

train
 Training with: algorithm: DT    instances: 705   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.559322        0.0     0.0  0.0  0.484266

train
 Training with: algorithm: DT    instances: 705   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_5  0.559322        0.0     0.0  0.0  0.535548

train
 Training with: algorithm: DT    instances: 705   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.559322        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 705   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall       f1   roc_auc
p_feature_3  0.423729       0.35  0.358974  0.35443  0.395688

train
 Training with: algorithm: DT    instances: 705   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall   f1   roc_auc
p_feature_4  0.508475   0.432836  0.371795  0.4  0.472675

train
 Training with: algorithm: DT    instances: 705   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall       f1   roc_auc
p_feature_5  0.491525      0.425  0.435897  0.43038  0.481093

train
 Training with: algorithm: DT    instances: 882   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall       f1   roc_auc       MDI
b_feature_5  0.559322   0.000000  0.000000  0.00000  0.535548  0.028594
b_feature_3  0.559322   0.000000  0.000000  0.00000  0.514957  0.034710
b_feature_2  0.559322   0.000000  0.000000  0.00000  0.500000  0.000000
p_feature_2  0.559322   0.000000  0.000000  0.00000  0.500000  0.000000
b_feature_4  0.559322   0.000000  0.000000  0.00000  0.484266  0.050866
p_feature_5  0.491525   0.425000  0.435897  0.43038  0.481093  0.274270
p_feature_4  0.508475   0.432836  0.371795  0.40000  0.472675  0.269091
p_feature_3  0.423729   0.350000  0.358974  0.35443  0.395688  0.342469

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
b_feature_5_b_feature_3: 0.5210526315789474
b_feature_5_b_feature_2: 0.5492207792207793
b_feature_5_b_feature_2_p_feature_2: 0.5363368367085363
b_feature_5_b_feature_2_b_feature_4: 0.5072417328890029
b_feature_5_b_feature_2_p_feature_5: 0.5067340067340067
b_feature_5_b_feature_2_p_feature_4: 0.47667264803896436
b_feature_5_b_feature_2_p_feature_3: 0.4488323274731042
b_feature_3_p_feature_2: 0.5500644329896908
b_feature_3_p_feature_2_b_feature_4: 0.5192307692307692
b_feature_3_p_feature_2_p_feature_5: 0.5117845117845118
b_feature_3_p_feature_2_p_feature_4: 0.48795648795648794
b_feature_3_p_feature_2_p_feature_3: 0.4311059311059311
b_feature_4_p_feature_5: 0.49067599067599066
b_feature_4_p_feature_5_p_feature_4: 0.4728049728049728
b_feature_4_p_feature_5_p_feature_3: 0.38888888888888884
p_feature_4_p_feature_3: 0.4904364569961489
XofN_groups: [['b_feature_5', 'b_feature_2'], ['b_feature_3', 'p_feature_2'], ['b_feature_4', 'p_feature_5'], ['p_feature_4', 'p_feature_3']]

group_features
Number of original features: 8
Number of generated XofN group features: 4
Number of features in XofN groups: 8
Number of features not in XofN groups: 4
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 4
Number of features in XofN groups: 8
Number of features not in XofN groups: 4
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 882   features: 4   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 97
         accuracy  precision  recall        f1   roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1  0.484536   0.477273  0.4375  0.456522  0.494898    10           roc_auc                 DT        roc_auc                    no_org        5

CV results:           accuracy  precision    recall        f1   roc_auc
label
label_1  0.476005   0.422732  0.372365  0.394683  0.460451

--- Running with label:'label_1' ranking_criterion:'roc_auc' training_algorithm:'DT' eval_criterion:'roc_auc' include_original_features:'True' max_size:'5' ---
Logs can be found in XofN_datasets/auto_groupings/label_1_roc_auc_DT_roc_auc_with_org_5_logs.txt.

drop_uninformative_features
 Removing 0 uninformative binary features. Remaining binary features: 5
 Removing 2 uninformative features where all values are the same. Remaining features: 8

remove_inconsistent_duplicates
  Dropping 19 duplicate rows (keep first). Remaining rows: 981
  ❌ Deleting 2 inconsistent rows (same values for features but different for labels). Remaining: 979

Fold 1/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:roc_auc.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.536723        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.536723        0.0     0.0  0.0  0.511489

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.536723        0.0     0.0  0.0  0.505392

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_5  0.536723        0.0     0.0  0.0  0.515661

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.536723        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_3  0.491525   0.442857  0.378049  0.407895  0.471566

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall     f1   roc_auc
p_feature_4  0.480226   0.435897  0.414634  0.425  0.492234

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_5  0.514124   0.471429  0.402439  0.434211  0.513286

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall        f1   roc_auc       MDI
b_feature_5  0.536723   0.000000  0.000000  0.000000  0.515661  0.020927
p_feature_5  0.514124   0.471429  0.402439  0.434211  0.513286  0.266213
b_feature_3  0.536723   0.000000  0.000000  0.000000  0.511489  0.043020
b_feature_4  0.536723   0.000000  0.000000  0.000000  0.505392  0.032612
b_feature_2  0.536723   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_2  0.536723   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_4  0.480226   0.435897  0.414634  0.425000  0.492234  0.333463
p_feature_3  0.491525   0.442857  0.378049  0.407895  0.471566  0.303765

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
b_feature_5_p_feature_5: 0.47304236200256733
b_feature_5_b_feature_3: 0.5210526315789474
b_feature_5_b_feature_3_b_feature_4: 0.48292682926829267
b_feature_5_b_feature_3_b_feature_2: 0.5210526315789474
b_feature_5_b_feature_3_p_feature_2: 0.5210526315789474
b_feature_5_b_feature_3_p_feature_4: 0.49980744544287553
b_feature_5_b_feature_3_p_feature_3: 0.44987163029525035
p_feature_5_b_feature_4: 0.517201540436457
p_feature_5_b_feature_4_b_feature_2: 0.5238125802310655
p_feature_5_b_feature_4_b_feature_2_p_feature_2: 0.5277278562259308
p_feature_5_b_feature_4_b_feature_2_p_feature_2_p_feature_4: 0.4563543003851091
p_feature_5_b_feature_4_b_feature_2_p_feature_2_p_feature_3: 0.500385109114249
p_feature_4_p_feature_3: 0.4904364569961489
XofN_groups: [['b_feature_5', 'b_feature_3'], ['p_feature_5', 'b_feature_4', 'b_feature_2', 'p_feature_2']]

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 6
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 6
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 10   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision    recall       f1   roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1  0.520408        0.5  0.425532  0.45977  0.525657     1           roc_auc                 DT        roc_auc                  with_org        5

Fold 2/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:roc_auc.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.564972        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.564972        0.0     0.0  0.0  0.417273

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.564972        0.0     0.0  0.0  0.497273

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_5  0.564972        0.0     0.0  0.0  0.549221

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.564972        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_3  0.570621   0.507937  0.415584  0.457143  0.537597

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_4  0.485876   0.402778  0.376623  0.389262  0.487792

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_5  0.519774   0.435484  0.350649  0.388489  0.520714

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall        f1   roc_auc       MDI
b_feature_5  0.564972   0.000000  0.000000  0.000000  0.549221  0.018634
p_feature_3  0.570621   0.507937  0.415584  0.457143  0.537597  0.313026
p_feature_5  0.519774   0.435484  0.350649  0.388489  0.520714  0.338978
b_feature_2  0.564972   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_2  0.564972   0.000000  0.000000  0.000000  0.500000  0.000000
b_feature_4  0.564972   0.000000  0.000000  0.000000  0.497273  0.029845
p_feature_4  0.485876   0.402778  0.376623  0.389262  0.487792  0.274036
b_feature_3  0.564972   0.000000  0.000000  0.000000  0.417273  0.025482

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
b_feature_5_p_feature_3: 0.5016883116883116
b_feature_5_p_feature_5: 0.47304236200256733
b_feature_5_b_feature_2: 0.5492207792207793
b_feature_5_p_feature_2: 0.5492207792207793
b_feature_5_b_feature_4: 0.567987012987013
b_feature_5_b_feature_4_p_feature_4: 0.5407792207792208
b_feature_5_b_feature_4_b_feature_3: 0.5618181818181818
p_feature_3_p_feature_5: 0.5367532467532468
p_feature_3_b_feature_2: 0.5375974025974026
p_feature_3_p_feature_2: 0.5375974025974026
p_feature_3_p_feature_4: 0.4767532467532467
p_feature_3_b_feature_3: 0.555
p_feature_5_b_feature_2: 0.5207142857142857
p_feature_5_p_feature_2: 0.5207142857142857
p_feature_5_p_feature_4: 0.48376623376623373
b_feature_2_p_feature_2: 0.5
b_feature_2_p_feature_4: 0.4877922077922078
p_feature_2_p_feature_4: 0.4877922077922078
XofN_groups: [['b_feature_5', 'b_feature_4'], ['p_feature_3', 'b_feature_3']]

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 4
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 4
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 10   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1   0.44898   0.459459  0.333333  0.386364  0.469754     2           roc_auc                 DT        roc_auc                  with_org        5

Fold 3/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:roc_auc.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.531073        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.531073        0.0     0.0  0.0  0.420405

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.531073        0.0     0.0  0.0  0.482825

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
b_feature_5  0.491525   0.462366  0.518072  0.488636  0.493079

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.531073        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall   f1   roc_auc
p_feature_3  0.457627   0.415584  0.385542  0.4  0.471674

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_4  0.502825   0.459016  0.337349  0.388889  0.496219

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision   recall        f1   roc_auc
p_feature_5  0.497175   0.458333  0.39759  0.425806  0.502243

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall        f1   roc_auc       MDI
p_feature_5  0.497175   0.458333  0.397590  0.425806  0.502243  0.254391
b_feature_2  0.531073   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_2  0.531073   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_4  0.502825   0.459016  0.337349  0.388889  0.496219  0.326912
b_feature_5  0.491525   0.462366  0.518072  0.488636  0.493079  0.039029
b_feature_4  0.531073   0.000000  0.000000  0.000000  0.482825  0.039494
p_feature_3  0.457627   0.415584  0.385542  0.400000  0.471674  0.306520
b_feature_3  0.531073   0.000000  0.000000  0.000000  0.420405  0.033655

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
p_feature_5_b_feature_2: 0.5207142857142857
p_feature_5_b_feature_2_p_feature_2: 0.5022430146116381
p_feature_5_b_feature_2_p_feature_4: 0.4835298641374006
p_feature_5_b_feature_2_b_feature_5: 0.4969879518072289
p_feature_5_b_feature_2_b_feature_4: 0.4951294539861574
p_feature_5_b_feature_2_p_feature_3: 0.5349269418097924
p_feature_5_b_feature_2_p_feature_3_b_feature_3: 0.5122404511663676
p_feature_2_p_feature_4: 0.4877922077922078
p_feature_2_b_feature_5: 0.4930786977698026
p_feature_2_b_feature_4: 0.48282491668802874
p_feature_2_b_feature_3: 0.42040502435273003
p_feature_4_b_feature_5: 0.4880799794924378
p_feature_4_b_feature_4: 0.5089079723147911
p_feature_4_b_feature_4_b_feature_3: 0.5415278133811844
XofN_groups: [['p_feature_5', 'b_feature_2', 'p_feature_3'], ['p_feature_4', 'b_feature_4', 'b_feature_3']]

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 6
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 6
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 10   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1  0.469388   0.352941  0.285714  0.315789  0.466624     3           roc_auc                 DT        roc_auc                  with_org        5

Fold 4/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:roc_auc.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.531073        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.531073        0.0     0.0  0.0  0.478211

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.531073        0.0     0.0  0.0  0.436747

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_5  0.531073        0.0     0.0  0.0  0.536337

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.531073        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_3  0.548023   0.520548  0.457831  0.487179  0.525122

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_4  0.497175   0.461538  0.433735  0.447205  0.492374

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_5  0.497175   0.455882  0.373494  0.410596  0.502499

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall        f1   roc_auc       MDI
b_feature_5  0.531073   0.000000  0.000000  0.000000  0.536337  0.013001
p_feature_3  0.548023   0.520548  0.457831  0.487179  0.525122  0.296814
p_feature_5  0.497175   0.455882  0.373494  0.410596  0.502499  0.295881
b_feature_2  0.531073   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_2  0.531073   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_4  0.497175   0.461538  0.433735  0.447205  0.492374  0.327283
b_feature_3  0.531073   0.000000  0.000000  0.000000  0.478211  0.031067
b_feature_4  0.531073   0.000000  0.000000  0.000000  0.436747  0.035954

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
b_feature_5_p_feature_3: 0.5016883116883116
b_feature_5_p_feature_5: 0.47304236200256733
b_feature_5_b_feature_2: 0.5492207792207793
b_feature_5_b_feature_2_p_feature_2: 0.5363368367085363
b_feature_5_b_feature_2_p_feature_4: 0.47667264803896436
b_feature_5_b_feature_2_b_feature_3: 0.5285183286336836
b_feature_5_b_feature_2_b_feature_4: 0.5072417328890029
p_feature_3_p_feature_5: 0.5367532467532468
p_feature_3_p_feature_5_p_feature_2: 0.4335426813637529
p_feature_3_p_feature_5_p_feature_4: 0.4856447064855166
p_feature_3_p_feature_5_b_feature_3: 0.4796206100999744
p_feature_3_p_feature_5_b_feature_4: 0.4835298641374006
p_feature_2_p_feature_4: 0.4877922077922078
p_feature_2_b_feature_3: 0.42040502435273003
p_feature_2_b_feature_4: 0.48282491668802874
p_feature_4_b_feature_3: 0.5
p_feature_4_b_feature_3_b_feature_4: 0.45578056908485
XofN_groups: [['b_feature_5', 'b_feature_2'], ['p_feature_3', 'p_feature_5'], ['p_feature_4', 'b_feature_3']]

group_features
Number of original features: 8
Number of generated XofN group features: 3
Number of features in XofN groups: 6
Number of features not in XofN groups: 3
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 3
Number of features in XofN groups: 6
Number of features not in XofN groups: 3
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 11   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision  recall        f1   roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1  0.510204   0.461538     0.4  0.428571  0.428092     4           roc_auc                 DT        roc_auc                  with_org        5

Fold 5/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:roc_auc.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.564972        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.564972        0.0     0.0  0.0  0.480779

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.564972        0.0     0.0  0.0  0.507273

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
b_feature_5  0.531073   0.466667  0.545455  0.502994  0.532727

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.564972        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_3  0.508475   0.432432  0.415584  0.423841  0.484805

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_4  0.497175   0.409091  0.350649  0.377622  0.474416

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall      f1   roc_auc
p_feature_5  0.536723    0.46988  0.506494  0.4875  0.534156

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall        f1   roc_auc       MDI
p_feature_5  0.536723   0.469880  0.506494  0.487500  0.534156  0.314335
b_feature_5  0.531073   0.466667  0.545455  0.502994  0.532727  0.012046
b_feature_4  0.564972   0.000000  0.000000  0.000000  0.507273  0.034558
b_feature_2  0.564972   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_2  0.564972   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_3  0.508475   0.432432  0.415584  0.423841  0.484805  0.302082
b_feature_3  0.564972   0.000000  0.000000  0.000000  0.480779  0.041182
p_feature_4  0.497175   0.409091  0.350649  0.377622  0.474416  0.295798

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
p_feature_5_b_feature_5: 0.5123376623376623
p_feature_5_b_feature_4: 0.517201540436457
p_feature_5_b_feature_2: 0.5207142857142857
p_feature_5_p_feature_2: 0.5207142857142857
p_feature_5_p_feature_3: 0.48824675324675326
p_feature_5_b_feature_3: 0.5094155844155844
p_feature_5_p_feature_4: 0.48376623376623373
b_feature_5_b_feature_4: 0.567987012987013
b_feature_5_b_feature_4_b_feature_2: 0.547012987012987
b_feature_5_b_feature_4_p_feature_2: 0.547012987012987
b_feature_5_b_feature_4_p_feature_3: 0.5186363636363636
b_feature_5_b_feature_4_b_feature_3: 0.5618181818181818
b_feature_5_b_feature_4_p_feature_4: 0.5407792207792208
b_feature_2_p_feature_2: 0.5
b_feature_2_p_feature_3: 0.4848051948051948
b_feature_2_b_feature_3: 0.48077922077922075
b_feature_2_p_feature_4: 0.4877922077922078
p_feature_2_p_feature_3: 0.4848051948051948
p_feature_2_b_feature_3: 0.42040502435273003
p_feature_2_p_feature_4: 0.4877922077922078
p_feature_3_b_feature_3: 0.555
p_feature_3_b_feature_3_p_feature_4: 0.46532467532467536
XofN_groups: [['b_feature_5', 'b_feature_4'], ['p_feature_3', 'b_feature_3']]

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 4
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 4
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 10   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1  0.346939   0.263158  0.217391  0.238095  0.313754     5           roc_auc                 DT        roc_auc                  with_org        5

Fold 6/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:roc_auc.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.559322        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.559322        0.0     0.0  0.0  0.432789

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.559322        0.0     0.0  0.0  0.526418

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
b_feature_5  0.491525   0.434783  0.512821  0.470588  0.493784

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.559322        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_3  0.468927   0.397436  0.397436  0.397436  0.462963

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_4  0.519774   0.449275  0.397436  0.421769  0.500324

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_5  0.514124   0.455556  0.525641  0.488095  0.511396

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall        f1   roc_auc       MDI
b_feature_4  0.559322   0.000000  0.000000  0.000000  0.526418  0.040326
p_feature_5  0.514124   0.455556  0.525641  0.488095  0.511396  0.274493
p_feature_4  0.519774   0.449275  0.397436  0.421769  0.500324  0.289433
b_feature_2  0.559322   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_2  0.559322   0.000000  0.000000  0.000000  0.500000  0.000000
b_feature_5  0.491525   0.434783  0.512821  0.470588  0.493784  0.030262
p_feature_3  0.468927   0.397436  0.397436  0.397436  0.462963  0.318377
b_feature_3  0.559322   0.000000  0.000000  0.000000  0.432789  0.047109

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
b_feature_4_p_feature_5: 0.49067599067599066
b_feature_4_p_feature_4: 0.5027195027195027
b_feature_4_b_feature_2: 0.5264180264180265
b_feature_4_p_feature_2: 0.5264180264180265
b_feature_4_b_feature_5: 0.5062160062160062
b_feature_4_p_feature_3: 0.4424371924371924
b_feature_4_b_feature_3: 0.5332167832167831
p_feature_5_p_feature_4: 0.48376623376623373
p_feature_5_b_feature_2: 0.5207142857142857
p_feature_5_b_feature_2_p_feature_2: 0.5022430146116381
p_feature_5_b_feature_2_b_feature_5: 0.4969879518072289
p_feature_5_b_feature_2_p_feature_3: 0.5349269418097924
p_feature_4_p_feature_2: 0.5003237503237503
p_feature_4_b_feature_5: 0.4880799794924378
p_feature_2_b_feature_5: 0.4930786977698026
XofN_groups: [['b_feature_4', 'b_feature_3'], ['p_feature_5', 'b_feature_2', 'p_feature_3']]

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 5
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 5
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 10   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1  0.397959   0.325581  0.318182  0.321839  0.377104     6           roc_auc                 DT        roc_auc                  with_org        5

Fold 7/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:roc_auc.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.581921        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.581921        0.0     0.0  0.0  0.417148

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.581921        0.0     0.0  0.0  0.494818

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_5  0.581921        0.0     0.0  0.0  0.527552

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.581921        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_3  0.491525   0.397436  0.418919  0.407895  0.484978

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall        f1   roc_auc
p_feature_4  0.564972   0.480519     0.5  0.490066  0.551036

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1  roc_auc
p_feature_5  0.548023       0.45  0.364865  0.402985  0.53011

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall        f1   roc_auc       MDI
p_feature_4  0.564972   0.480519  0.500000  0.490066  0.551036  0.356278
p_feature_5  0.548023   0.450000  0.364865  0.402985  0.530110  0.295338
b_feature_5  0.581921   0.000000  0.000000  0.000000  0.527552  0.023704
b_feature_2  0.581921   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_2  0.581921   0.000000  0.000000  0.000000  0.500000  0.000000
b_feature_4  0.581921   0.000000  0.000000  0.000000  0.494818  0.037305
p_feature_3  0.491525   0.397436  0.418919  0.407895  0.484978  0.258570
b_feature_3  0.581921   0.000000  0.000000  0.000000  0.417148  0.028806

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
p_feature_4_p_feature_5: 0.47920493308842826
p_feature_4_b_feature_5: 0.4880799794924378
p_feature_4_b_feature_2: 0.5510364733665705
p_feature_4_p_feature_2: 0.5003237503237503
p_feature_4_b_feature_4: 0.5089079723147911
p_feature_4_p_feature_3: 0.4904364569961489
p_feature_4_b_feature_3: 0.5
p_feature_5_b_feature_5: 0.5123376623376623
p_feature_5_b_feature_2: 0.5207142857142857
p_feature_5_p_feature_2: 0.5207142857142857
p_feature_5_b_feature_4: 0.517201540436457
p_feature_5_p_feature_3: 0.48824675324675326
p_feature_5_b_feature_3: 0.5094155844155844
b_feature_5_b_feature_2: 0.5492207792207793
b_feature_5_b_feature_2_p_feature_2: 0.5363368367085363
b_feature_5_b_feature_2_b_feature_4: 0.5072417328890029
b_feature_5_b_feature_2_p_feature_3: 0.4488323274731042
b_feature_5_b_feature_2_b_feature_3: 0.5285183286336836
p_feature_2_b_feature_4: 0.48282491668802874
p_feature_2_p_feature_3: 0.4848051948051948
p_feature_2_b_feature_3: 0.42040502435273003
b_feature_4_p_feature_3: 0.4424371924371924
b_feature_4_b_feature_3: 0.5332167832167831
XofN_groups: [['b_feature_5', 'b_feature_2'], ['b_feature_4', 'b_feature_3']]

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 4
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 4
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 10   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1       0.5   0.444444  0.454545  0.449438  0.540194     7           roc_auc                 DT        roc_auc                  with_org        5

Fold 8/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:roc_auc.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.525424        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.525424        0.0     0.0  0.0  0.454301

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.525424        0.0     0.0  0.0  0.523618

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1  roc_auc
b_feature_5  0.559322   0.535714  0.535714  0.535714  0.55818

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.525424        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_3  0.514124   0.486486  0.428571  0.455696  0.502496

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_4  0.502825   0.472222  0.404762  0.435897  0.477791

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1  roc_auc
p_feature_5  0.525424        0.5  0.404762  0.447368  0.50704

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall        f1   roc_auc       MDI
b_feature_5  0.559322   0.535714  0.535714  0.535714  0.558180  0.008926
b_feature_4  0.525424   0.000000  0.000000  0.000000  0.523618  0.034450
p_feature_5  0.525424   0.500000  0.404762  0.447368  0.507040  0.379312
p_feature_3  0.514124   0.486486  0.428571  0.455696  0.502496  0.242737
p_feature_2  0.525424   0.000000  0.000000  0.000000  0.500000  0.000000
b_feature_2  0.525424   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_4  0.502825   0.472222  0.404762  0.435897  0.477791  0.295863
b_feature_3  0.525424   0.000000  0.000000  0.000000  0.454301  0.038711

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
b_feature_5_b_feature_4: 0.567987012987013
b_feature_5_b_feature_4_p_feature_5: 0.5356502816180235
b_feature_5_b_feature_4_p_feature_3: 0.5186363636363636
b_feature_5_b_feature_4_p_feature_2: 0.547012987012987
b_feature_5_b_feature_4_b_feature_2: 0.547012987012987
b_feature_5_b_feature_4_p_feature_4: 0.5407792207792208
b_feature_5_b_feature_4_b_feature_3: 0.5618181818181818
p_feature_5_p_feature_3: 0.48824675324675326
p_feature_5_p_feature_2: 0.5207142857142857
p_feature_5_p_feature_2_b_feature_2: 0.5070404505888377
p_feature_5_p_feature_2_p_feature_4: 0.5397465437788018
p_feature_5_p_feature_2_p_feature_4_b_feature_3: 0.4539170506912442
p_feature_3_b_feature_2: 0.5375974025974026
p_feature_3_b_feature_2_b_feature_3: 0.5196492575524834
XofN_groups: [['b_feature_5', 'b_feature_4'], ['p_feature_5', 'p_feature_2', 'p_feature_4'], ['p_feature_3', 'b_feature_2']]

group_features
Number of original features: 8
Number of generated XofN group features: 3
Number of features in XofN groups: 7
Number of features not in XofN groups: 3
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 3
Number of features in XofN groups: 7
Number of features not in XofN groups: 3
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 11   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1  0.469388   0.351351  0.317073  0.333333  0.436243     8           roc_auc                 DT        roc_auc                  with_org        5

Fold 9/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:roc_auc.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.548023        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.548023        0.0     0.0  0.0  0.550064

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.548023        0.0     0.0  0.0  0.463982

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_5  0.548023        0.0     0.0  0.0  0.571005

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.548023        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
p_feature_3  0.570621   0.527778   0.475  0.5  0.559729

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall       f1   roc_auc
p_feature_4  0.531073    0.47619   0.375  0.41958  0.490464

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall        f1   roc_auc
p_feature_5  0.508475   0.444444    0.35  0.391608  0.499936

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision  recall        f1   roc_auc       MDI
b_feature_5  0.548023   0.000000   0.000  0.000000  0.571005  0.025280
p_feature_3  0.570621   0.527778   0.475  0.500000  0.559729  0.341532
b_feature_3  0.548023   0.000000   0.000  0.000000  0.550064  0.018590
b_feature_2  0.548023   0.000000   0.000  0.000000  0.500000  0.000000
p_feature_2  0.548023   0.000000   0.000  0.000000  0.500000  0.000000
p_feature_5  0.508475   0.444444   0.350  0.391608  0.499936  0.286832
p_feature_4  0.531073   0.476190   0.375  0.419580  0.490464  0.277317
b_feature_4  0.548023   0.000000   0.000  0.000000  0.463982  0.050448

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
b_feature_5_p_feature_3: 0.5016883116883116
b_feature_5_b_feature_3: 0.5210526315789474
b_feature_5_b_feature_2: 0.5492207792207793
b_feature_5_p_feature_2: 0.5492207792207793
b_feature_5_p_feature_5: 0.47304236200256733
b_feature_5_p_feature_4: 0.48769329896907215
b_feature_5_b_feature_4: 0.567987012987013
p_feature_3_b_feature_3: 0.555
p_feature_3_b_feature_2: 0.5375974025974026
p_feature_3_p_feature_2: 0.5375974025974026
p_feature_3_p_feature_5: 0.5367532467532468
p_feature_3_p_feature_4: 0.4767532467532467
p_feature_3_b_feature_4: 0.5234536082474227
b_feature_3_b_feature_2: 0.5500644329896908
b_feature_3_p_feature_2: 0.5500644329896908
b_feature_3_p_feature_5: 0.5381443298969072
b_feature_3_p_feature_4: 0.5282216494845361
b_feature_3_b_feature_4: 0.4614690721649484
b_feature_2_p_feature_2: 0.5
b_feature_2_p_feature_5: 0.4999355670103093
b_feature_2_p_feature_4: 0.4877922077922078
b_feature_2_b_feature_4: 0.46398195876288656
p_feature_2_p_feature_5: 0.4999355670103093
p_feature_2_p_feature_4: 0.4877922077922078
p_feature_2_b_feature_4: 0.48282491668802874
p_feature_5_p_feature_4: 0.48376623376623373
p_feature_5_b_feature_4: 0.517201540436457
XofN_groups: [['p_feature_5', 'b_feature_4']]

group_features
Number of original features: 8
Number of generated XofN group features: 1
Number of features in XofN groups: 2
Number of features not in XofN groups: 1
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 1
Number of features in XofN groups: 2
Number of features not in XofN groups: 1
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 9   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1  roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1  0.459184   0.333333  0.232558  0.273973  0.44334     9           roc_auc                 DT        roc_auc                  with_org        5

Fold 10/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:roc_auc.

train
 Training with: algorithm: DT    instances: 705   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.559322        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 705   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.559322        0.0     0.0  0.0  0.514957

train
 Training with: algorithm: DT    instances: 705   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.559322        0.0     0.0  0.0  0.484266

train
 Training with: algorithm: DT    instances: 705   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_5  0.559322        0.0     0.0  0.0  0.535548

train
 Training with: algorithm: DT    instances: 705   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.559322        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 705   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall       f1   roc_auc
p_feature_3  0.423729       0.35  0.358974  0.35443  0.395688

train
 Training with: algorithm: DT    instances: 705   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall   f1   roc_auc
p_feature_4  0.508475   0.432836  0.371795  0.4  0.472675

train
 Training with: algorithm: DT    instances: 705   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall       f1   roc_auc
p_feature_5  0.491525      0.425  0.435897  0.43038  0.481093

train
 Training with: algorithm: DT    instances: 882   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall       f1   roc_auc       MDI
b_feature_5  0.559322   0.000000  0.000000  0.00000  0.535548  0.028594
b_feature_3  0.559322   0.000000  0.000000  0.00000  0.514957  0.034710
b_feature_2  0.559322   0.000000  0.000000  0.00000  0.500000  0.000000
p_feature_2  0.559322   0.000000  0.000000  0.00000  0.500000  0.000000
b_feature_4  0.559322   0.000000  0.000000  0.00000  0.484266  0.050866
p_feature_5  0.491525   0.425000  0.435897  0.43038  0.481093  0.274270
p_feature_4  0.508475   0.432836  0.371795  0.40000  0.472675  0.269091
p_feature_3  0.423729   0.350000  0.358974  0.35443  0.395688  0.342469

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
b_feature_5_b_feature_3: 0.5210526315789474
b_feature_5_b_feature_2: 0.5492207792207793
b_feature_5_b_feature_2_p_feature_2: 0.5363368367085363
b_feature_5_b_feature_2_b_feature_4: 0.5072417328890029
b_feature_5_b_feature_2_p_feature_5: 0.5067340067340067
b_feature_5_b_feature_2_p_feature_4: 0.47667264803896436
b_feature_5_b_feature_2_p_feature_3: 0.4488323274731042
b_feature_3_p_feature_2: 0.5500644329896908
b_feature_3_p_feature_2_b_feature_4: 0.5192307692307692
b_feature_3_p_feature_2_p_feature_5: 0.5117845117845118
b_feature_3_p_feature_2_p_feature_4: 0.48795648795648794
b_feature_3_p_feature_2_p_feature_3: 0.4311059311059311
b_feature_4_p_feature_5: 0.49067599067599066
b_feature_4_p_feature_5_p_feature_4: 0.4728049728049728
b_feature_4_p_feature_5_p_feature_3: 0.38888888888888884
p_feature_4_p_feature_3: 0.4904364569961489
XofN_groups: [['b_feature_5', 'b_feature_2'], ['b_feature_3', 'p_feature_2'], ['b_feature_4', 'p_feature_5'], ['p_feature_4', 'p_feature_3']]

group_features
Number of original features: 8
Number of generated XofN group features: 4
Number of features in XofN groups: 8
Number of features not in XofN groups: 4
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 4
Number of features in XofN groups: 8
Number of features not in XofN groups: 4
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 882   features: 12   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 97
         accuracy  precision    recall        f1   roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1  0.536082   0.540541  0.416667  0.470588  0.534014    10           roc_auc                 DT        roc_auc                  with_org        5

CV results:           accuracy  precision  recall        f1   roc_auc
label
label_1  0.465853   0.403235  0.3401  0.367776  0.453478

--- Running with label:'label_1' ranking_criterion:'MDI' training_algorithm:'DT' eval_criterion:'roc_auc' include_original_features:'False' max_size:'5' ---
Logs can be found in XofN_datasets/auto_groupings/label_1_MDI_DT_roc_auc_no_org_5_logs.txt.

drop_uninformative_features
 Removing 0 uninformative binary features. Remaining binary features: 5
 Removing 2 uninformative features where all values are the same. Remaining features: 8

remove_inconsistent_duplicates
  Dropping 19 duplicate rows (keep first). Remaining rows: 981
  ❌ Deleting 2 inconsistent rows (same values for features but different for labels). Remaining: 979

Fold 1/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:MDI.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.536723        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.536723        0.0     0.0  0.0  0.511489

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.536723        0.0     0.0  0.0  0.505392

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_5  0.536723        0.0     0.0  0.0  0.515661

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.536723        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_3  0.491525   0.442857  0.378049  0.407895  0.471566

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall     f1   roc_auc
p_feature_4  0.480226   0.435897  0.414634  0.425  0.492234

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_5  0.514124   0.471429  0.402439  0.434211  0.513286

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall        f1   roc_auc       MDI
p_feature_4  0.480226   0.435897  0.414634  0.425000  0.492234  0.333463
p_feature_3  0.491525   0.442857  0.378049  0.407895  0.471566  0.303765
p_feature_5  0.514124   0.471429  0.402439  0.434211  0.513286  0.266213
b_feature_3  0.536723   0.000000  0.000000  0.000000  0.511489  0.043020
b_feature_4  0.536723   0.000000  0.000000  0.000000  0.505392  0.032612
b_feature_5  0.536723   0.000000  0.000000  0.000000  0.515661  0.020927
b_feature_2  0.536723   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_2  0.536723   0.000000  0.000000  0.000000  0.500000  0.000000

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
p_feature_4_p_feature_3: 0.4904364569961489
p_feature_4_p_feature_5: 0.47920493308842826
p_feature_4_b_feature_3: 0.5
p_feature_4_b_feature_3_b_feature_4: 0.45578056908485
p_feature_4_b_feature_3_b_feature_5: 0.49980744544287553
p_feature_4_b_feature_3_b_feature_2: 0.48902439024390243
p_feature_4_b_feature_3_p_feature_2: 0.48902439024390243
p_feature_3_p_feature_5: 0.5367532467532468
p_feature_3_p_feature_5_b_feature_4: 0.4835298641374006
p_feature_3_p_feature_5_b_feature_5: 0.5056482670089858
p_feature_3_p_feature_5_b_feature_2: 0.44082156611039797
p_feature_3_p_feature_5_p_feature_2: 0.4335426813637529
b_feature_4_b_feature_5: 0.5062160062160062
b_feature_4_b_feature_5_b_feature_2: 0.4868421052631579
b_feature_4_b_feature_5_p_feature_2: 0.4868421052631579
b_feature_2_p_feature_2: 0.5
XofN_groups: [['p_feature_4', 'b_feature_3'], ['p_feature_3', 'p_feature_5'], ['b_feature_4', 'b_feature_5']]

group_features
Number of original features: 8
Number of generated XofN group features: 3
Number of features in XofN groups: 6
Number of features not in XofN groups: 3
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 3
Number of features in XofN groups: 6
Number of features not in XofN groups: 3
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 5   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1  0.489796   0.463415  0.404255  0.431818  0.489362     1               MDI                 DT        roc_auc                    no_org        5

Fold 2/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:MDI.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.564972        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.564972        0.0     0.0  0.0  0.417273

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.564972        0.0     0.0  0.0  0.497273

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_5  0.564972        0.0     0.0  0.0  0.549221

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.564972        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_3  0.570621   0.507937  0.415584  0.457143  0.537597

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_4  0.485876   0.402778  0.376623  0.389262  0.487792

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_5  0.519774   0.435484  0.350649  0.388489  0.520714

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall        f1   roc_auc       MDI
p_feature_5  0.519774   0.435484  0.350649  0.388489  0.520714  0.338978
p_feature_3  0.570621   0.507937  0.415584  0.457143  0.537597  0.313026
p_feature_4  0.485876   0.402778  0.376623  0.389262  0.487792  0.274036
b_feature_4  0.564972   0.000000  0.000000  0.000000  0.497273  0.029845
b_feature_3  0.564972   0.000000  0.000000  0.000000  0.417273  0.025482
b_feature_5  0.564972   0.000000  0.000000  0.000000  0.549221  0.018634
b_feature_2  0.564972   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_2  0.564972   0.000000  0.000000  0.000000  0.500000  0.000000

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
p_feature_5_p_feature_3: 0.48824675324675326
p_feature_5_p_feature_4: 0.48376623376623373
p_feature_5_b_feature_4: 0.517201540436457
p_feature_5_b_feature_3: 0.5094155844155844
p_feature_5_b_feature_5: 0.5123376623376623
p_feature_5_b_feature_2: 0.5207142857142857
p_feature_5_p_feature_2: 0.5207142857142857
p_feature_3_p_feature_4: 0.4767532467532467
p_feature_3_b_feature_4: 0.5234536082474227
p_feature_3_b_feature_3: 0.555
p_feature_3_b_feature_3_b_feature_5: 0.5393506493506494
p_feature_3_b_feature_3_b_feature_2: 0.5508441558441559
p_feature_3_b_feature_3_p_feature_2: 0.5508441558441559
p_feature_4_b_feature_4: 0.5089079723147911
p_feature_4_b_feature_4_b_feature_5: 0.5407792207792208
p_feature_4_b_feature_4_b_feature_5_b_feature_2: 0.5429220779220779
p_feature_4_b_feature_4_b_feature_5_b_feature_2_p_feature_2: 0.5459090909090909
XofN_groups: [['p_feature_3', 'b_feature_3'], ['p_feature_4', 'b_feature_4', 'b_feature_5', 'b_feature_2', 'p_feature_2']]

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 7
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 7
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 3   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision   recall        f1   roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1  0.408163        0.4  0.27451  0.325581  0.415311     2               MDI                 DT        roc_auc                    no_org        5

Fold 3/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:MDI.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.531073        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.531073        0.0     0.0  0.0  0.420405

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.531073        0.0     0.0  0.0  0.482825

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
b_feature_5  0.491525   0.462366  0.518072  0.488636  0.493079

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.531073        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall   f1   roc_auc
p_feature_3  0.457627   0.415584  0.385542  0.4  0.471674

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_4  0.502825   0.459016  0.337349  0.388889  0.496219

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision   recall        f1   roc_auc
p_feature_5  0.497175   0.458333  0.39759  0.425806  0.502243

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall        f1   roc_auc       MDI
p_feature_4  0.502825   0.459016  0.337349  0.388889  0.496219  0.326912
p_feature_3  0.457627   0.415584  0.385542  0.400000  0.471674  0.306520
p_feature_5  0.497175   0.458333  0.397590  0.425806  0.502243  0.254391
b_feature_4  0.531073   0.000000  0.000000  0.000000  0.482825  0.039494
b_feature_5  0.491525   0.462366  0.518072  0.488636  0.493079  0.039029
b_feature_3  0.531073   0.000000  0.000000  0.000000  0.420405  0.033655
b_feature_2  0.531073   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_2  0.531073   0.000000  0.000000  0.000000  0.500000  0.000000

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
p_feature_4_p_feature_3: 0.4904364569961489
p_feature_4_p_feature_5: 0.47920493308842826
p_feature_4_b_feature_4: 0.5089079723147911
p_feature_4_b_feature_4_b_feature_5: 0.5407792207792208
p_feature_4_b_feature_4_b_feature_5_b_feature_3: 0.5099333504229685
p_feature_4_b_feature_4_b_feature_5_b_feature_2: 0.5429220779220779
p_feature_4_b_feature_4_b_feature_5_b_feature_2_p_feature_2: 0.5459090909090909
p_feature_3_p_feature_5: 0.5367532467532468
p_feature_3_p_feature_5_b_feature_3: 0.4796206100999744
XofN_groups: [['p_feature_4', 'b_feature_4', 'b_feature_5', 'b_feature_2', 'p_feature_2'], ['p_feature_3', 'p_feature_5']]

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 7
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 7
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 3   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1  0.469388      0.375  0.357143  0.365854  0.491709     3               MDI                 DT        roc_auc                    no_org        5

Fold 4/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:MDI.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.531073        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.531073        0.0     0.0  0.0  0.478211

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.531073        0.0     0.0  0.0  0.436747

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_5  0.531073        0.0     0.0  0.0  0.536337

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.531073        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_3  0.548023   0.520548  0.457831  0.487179  0.525122

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_4  0.497175   0.461538  0.433735  0.447205  0.492374

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_5  0.497175   0.455882  0.373494  0.410596  0.502499

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall        f1   roc_auc       MDI
p_feature_4  0.497175   0.461538  0.433735  0.447205  0.492374  0.327283
p_feature_3  0.548023   0.520548  0.457831  0.487179  0.525122  0.296814
p_feature_5  0.497175   0.455882  0.373494  0.410596  0.502499  0.295881
b_feature_4  0.531073   0.000000  0.000000  0.000000  0.436747  0.035954
b_feature_3  0.531073   0.000000  0.000000  0.000000  0.478211  0.031067
b_feature_5  0.531073   0.000000  0.000000  0.000000  0.536337  0.013001
b_feature_2  0.531073   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_2  0.531073   0.000000  0.000000  0.000000  0.500000  0.000000

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
p_feature_4_p_feature_3: 0.4904364569961489
p_feature_4_p_feature_5: 0.47920493308842826
p_feature_4_b_feature_4: 0.5089079723147911
p_feature_4_b_feature_4_b_feature_3: 0.5415278133811844
p_feature_4_b_feature_4_b_feature_3_b_feature_5: 0.431427839015637
p_feature_4_b_feature_4_b_feature_3_b_feature_2: 0.45783132530120485
p_feature_4_b_feature_4_b_feature_3_p_feature_2: 0.45783132530120485
p_feature_3_p_feature_5: 0.5367532467532468
p_feature_3_p_feature_5_b_feature_5: 0.5056482670089858
p_feature_3_p_feature_5_b_feature_2: 0.44082156611039797
p_feature_3_p_feature_5_p_feature_2: 0.4335426813637529
b_feature_5_b_feature_2: 0.5492207792207793
b_feature_5_b_feature_2_p_feature_2: 0.5363368367085363
XofN_groups: [['p_feature_4', 'b_feature_4', 'b_feature_3'], ['p_feature_3', 'p_feature_5'], ['b_feature_5', 'b_feature_2']]

group_features
Number of original features: 8
Number of generated XofN group features: 3
Number of features in XofN groups: 7
Number of features not in XofN groups: 3
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 3
Number of features in XofN groups: 7
Number of features not in XofN groups: 3
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 4   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1  0.530612   0.487805  0.444444  0.465116  0.526834     4               MDI                 DT        roc_auc                    no_org        5

Fold 5/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:MDI.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.564972        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.564972        0.0     0.0  0.0  0.480779

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.564972        0.0     0.0  0.0  0.507273

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
b_feature_5  0.531073   0.466667  0.545455  0.502994  0.532727

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.564972        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_3  0.508475   0.432432  0.415584  0.423841  0.484805

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_4  0.497175   0.409091  0.350649  0.377622  0.474416

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall      f1   roc_auc
p_feature_5  0.536723    0.46988  0.506494  0.4875  0.534156

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall        f1   roc_auc       MDI
p_feature_5  0.536723   0.469880  0.506494  0.487500  0.534156  0.314335
p_feature_3  0.508475   0.432432  0.415584  0.423841  0.484805  0.302082
p_feature_4  0.497175   0.409091  0.350649  0.377622  0.474416  0.295798
b_feature_3  0.564972   0.000000  0.000000  0.000000  0.480779  0.041182
b_feature_4  0.564972   0.000000  0.000000  0.000000  0.507273  0.034558
b_feature_5  0.531073   0.466667  0.545455  0.502994  0.532727  0.012046
b_feature_2  0.564972   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_2  0.564972   0.000000  0.000000  0.000000  0.500000  0.000000

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
p_feature_5_p_feature_3: 0.48824675324675326
p_feature_5_p_feature_4: 0.48376623376623373
p_feature_5_b_feature_3: 0.5094155844155844
p_feature_5_b_feature_4: 0.517201540436457
p_feature_5_b_feature_5: 0.5123376623376623
p_feature_5_b_feature_2: 0.5207142857142857
p_feature_5_p_feature_2: 0.5207142857142857
p_feature_3_p_feature_4: 0.4767532467532467
p_feature_3_b_feature_3: 0.555
p_feature_3_b_feature_3_b_feature_4: 0.44227272727272726
p_feature_3_b_feature_3_b_feature_5: 0.5393506493506494
p_feature_3_b_feature_3_b_feature_2: 0.5508441558441559
p_feature_3_b_feature_3_p_feature_2: 0.5508441558441559
p_feature_4_b_feature_4: 0.5089079723147911
p_feature_4_b_feature_4_b_feature_5: 0.5407792207792208
p_feature_4_b_feature_4_b_feature_5_b_feature_2: 0.5429220779220779
p_feature_4_b_feature_4_b_feature_5_b_feature_2_p_feature_2: 0.5459090909090909
XofN_groups: [['p_feature_3', 'b_feature_3'], ['p_feature_4', 'b_feature_4', 'b_feature_5', 'b_feature_2', 'p_feature_2']]

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 7
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 7
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 3   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1  0.377551   0.352941  0.391304  0.371134  0.336957     5               MDI                 DT        roc_auc                    no_org        5

Fold 6/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:MDI.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.559322        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.559322        0.0     0.0  0.0  0.432789

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.559322        0.0     0.0  0.0  0.526418

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
b_feature_5  0.491525   0.434783  0.512821  0.470588  0.493784

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.559322        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_3  0.468927   0.397436  0.397436  0.397436  0.462963

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_4  0.519774   0.449275  0.397436  0.421769  0.500324

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_5  0.514124   0.455556  0.525641  0.488095  0.511396

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall        f1   roc_auc       MDI
p_feature_3  0.468927   0.397436  0.397436  0.397436  0.462963  0.318377
p_feature_4  0.519774   0.449275  0.397436  0.421769  0.500324  0.289433
p_feature_5  0.514124   0.455556  0.525641  0.488095  0.511396  0.274493
b_feature_3  0.559322   0.000000  0.000000  0.000000  0.432789  0.047109
b_feature_4  0.559322   0.000000  0.000000  0.000000  0.526418  0.040326
b_feature_5  0.491525   0.434783  0.512821  0.470588  0.493784  0.030262
b_feature_2  0.559322   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_2  0.559322   0.000000  0.000000  0.000000  0.500000  0.000000

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
p_feature_3_p_feature_4: 0.4767532467532467
p_feature_3_p_feature_4_p_feature_5: 0.44988344988344986
p_feature_3_p_feature_4_b_feature_3: 0.47377622377622375
p_feature_3_p_feature_4_b_feature_4: 0.5007770007770008
p_feature_3_p_feature_4_b_feature_4_b_feature_5: 0.5301087801087802
p_feature_3_p_feature_4_b_feature_4_b_feature_5_b_feature_2: 0.5301087801087802
p_feature_3_p_feature_4_b_feature_4_b_feature_5_p_feature_2: 0.5301087801087802
p_feature_5_b_feature_3: 0.5094155844155844
p_feature_5_b_feature_2: 0.5207142857142857
p_feature_5_b_feature_2_p_feature_2: 0.5022430146116381
b_feature_3_p_feature_2: 0.5500644329896908
XofN_groups: [['p_feature_3', 'p_feature_4', 'b_feature_4', 'b_feature_5'], ['p_feature_5', 'b_feature_2'], ['b_feature_3', 'p_feature_2']]

group_features
Number of original features: 8
Number of generated XofN group features: 3
Number of features in XofN groups: 8
Number of features not in XofN groups: 3
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 3
Number of features in XofN groups: 8
Number of features not in XofN groups: 3
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 3   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1  0.479592   0.422222  0.431818  0.426966  0.484007     6               MDI                 DT        roc_auc                    no_org        5

Fold 7/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:MDI.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.581921        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.581921        0.0     0.0  0.0  0.417148

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.581921        0.0     0.0  0.0  0.494818

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_5  0.581921        0.0     0.0  0.0  0.527552

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.581921        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_3  0.491525   0.397436  0.418919  0.407895  0.484978

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall        f1   roc_auc
p_feature_4  0.564972   0.480519     0.5  0.490066  0.551036

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1  roc_auc
p_feature_5  0.548023       0.45  0.364865  0.402985  0.53011

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall        f1   roc_auc       MDI
p_feature_4  0.564972   0.480519  0.500000  0.490066  0.551036  0.356278
p_feature_5  0.548023   0.450000  0.364865  0.402985  0.530110  0.295338
p_feature_3  0.491525   0.397436  0.418919  0.407895  0.484978  0.258570
b_feature_4  0.581921   0.000000  0.000000  0.000000  0.494818  0.037305
b_feature_3  0.581921   0.000000  0.000000  0.000000  0.417148  0.028806
b_feature_5  0.581921   0.000000  0.000000  0.000000  0.527552  0.023704
b_feature_2  0.581921   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_2  0.581921   0.000000  0.000000  0.000000  0.500000  0.000000

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
p_feature_4_p_feature_5: 0.47920493308842826
p_feature_4_p_feature_3: 0.4904364569961489
p_feature_4_b_feature_4: 0.5089079723147911
p_feature_4_b_feature_3: 0.5
p_feature_4_b_feature_5: 0.4880799794924378
p_feature_4_b_feature_2: 0.5510364733665705
p_feature_4_p_feature_2: 0.5003237503237503
p_feature_5_p_feature_3: 0.48824675324675326
p_feature_5_b_feature_4: 0.517201540436457
p_feature_5_b_feature_3: 0.5094155844155844
p_feature_5_b_feature_5: 0.5123376623376623
p_feature_5_b_feature_2: 0.5207142857142857
p_feature_5_p_feature_2: 0.5207142857142857
p_feature_3_b_feature_4: 0.5234536082474227
p_feature_3_b_feature_4_b_feature_3: 0.5292574127525583
p_feature_3_b_feature_4_b_feature_3_b_feature_5: 0.46405143007084754
p_feature_3_b_feature_4_b_feature_3_b_feature_2: 0.522828653896615
p_feature_3_b_feature_4_b_feature_3_p_feature_2: 0.522828653896615
b_feature_5_b_feature_2: 0.5492207792207793
b_feature_5_b_feature_2_p_feature_2: 0.5363368367085363
XofN_groups: [['p_feature_3', 'b_feature_4', 'b_feature_3'], ['b_feature_5', 'b_feature_2']]

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 5
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 5
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 5   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1  roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1       0.5   0.444444  0.454545  0.449438  0.49979     7               MDI                 DT        roc_auc                    no_org        5

Fold 8/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:MDI.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.525424        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.525424        0.0     0.0  0.0  0.454301

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.525424        0.0     0.0  0.0  0.523618

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1  roc_auc
b_feature_5  0.559322   0.535714  0.535714  0.535714  0.55818

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.525424        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_3  0.514124   0.486486  0.428571  0.455696  0.502496

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_4  0.502825   0.472222  0.404762  0.435897  0.477791

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1  roc_auc
p_feature_5  0.525424        0.5  0.404762  0.447368  0.50704

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall        f1   roc_auc       MDI
p_feature_5  0.525424   0.500000  0.404762  0.447368  0.507040  0.379312
p_feature_4  0.502825   0.472222  0.404762  0.435897  0.477791  0.295863
p_feature_3  0.514124   0.486486  0.428571  0.455696  0.502496  0.242737
b_feature_3  0.525424   0.000000  0.000000  0.000000  0.454301  0.038711
b_feature_4  0.525424   0.000000  0.000000  0.000000  0.523618  0.034450
b_feature_5  0.559322   0.535714  0.535714  0.535714  0.558180  0.008926
b_feature_2  0.525424   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_2  0.525424   0.000000  0.000000  0.000000  0.500000  0.000000

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
p_feature_5_p_feature_4: 0.48376623376623373
p_feature_5_p_feature_3: 0.48824675324675326
p_feature_5_b_feature_3: 0.5094155844155844
p_feature_5_b_feature_3_b_feature_4: 0.5481310803891448
p_feature_5_b_feature_3_b_feature_4_b_feature_5: 0.5472990271377367
p_feature_5_b_feature_3_b_feature_4_b_feature_2: 0.5431387608806962
p_feature_5_b_feature_3_b_feature_4_p_feature_2: 0.5431387608806962
p_feature_4_p_feature_3: 0.4904364569961489
p_feature_4_p_feature_3_b_feature_5: 0.5276497695852534
p_feature_4_p_feature_3_b_feature_5_b_feature_2: 0.5483870967741935
p_feature_4_p_feature_3_b_feature_5_b_feature_2_p_feature_2: 0.5353302611367128
XofN_groups: [['p_feature_5', 'b_feature_3', 'b_feature_4'], ['p_feature_4', 'p_feature_3', 'b_feature_5', 'b_feature_2']]

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 7
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 7
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 3   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision    recall     f1  roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1  0.571429   0.487179  0.463415  0.475  0.54065     8               MDI                 DT        roc_auc                    no_org        5

Fold 9/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:MDI.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.548023        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.548023        0.0     0.0  0.0  0.550064

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.548023        0.0     0.0  0.0  0.463982

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_5  0.548023        0.0     0.0  0.0  0.571005

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.548023        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
p_feature_3  0.570621   0.527778   0.475  0.5  0.559729

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall       f1   roc_auc
p_feature_4  0.531073    0.47619   0.375  0.41958  0.490464

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall        f1   roc_auc
p_feature_5  0.508475   0.444444    0.35  0.391608  0.499936

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision  recall        f1   roc_auc       MDI
p_feature_3  0.570621   0.527778   0.475  0.500000  0.559729  0.341532
p_feature_5  0.508475   0.444444   0.350  0.391608  0.499936  0.286832
p_feature_4  0.531073   0.476190   0.375  0.419580  0.490464  0.277317
b_feature_4  0.548023   0.000000   0.000  0.000000  0.463982  0.050448
b_feature_5  0.548023   0.000000   0.000  0.000000  0.571005  0.025280
b_feature_3  0.548023   0.000000   0.000  0.000000  0.550064  0.018590
b_feature_2  0.548023   0.000000   0.000  0.000000  0.500000  0.000000
p_feature_2  0.548023   0.000000   0.000  0.000000  0.500000  0.000000

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
p_feature_3_p_feature_5: 0.5367532467532468
p_feature_3_p_feature_4: 0.4767532467532467
p_feature_3_b_feature_4: 0.5234536082474227
p_feature_3_b_feature_5: 0.5106958762886598
p_feature_3_b_feature_3: 0.555
p_feature_3_b_feature_2: 0.5375974025974026
p_feature_3_p_feature_2: 0.5375974025974026
p_feature_5_p_feature_4: 0.48376623376623373
p_feature_5_b_feature_4: 0.517201540436457
p_feature_5_b_feature_4_b_feature_5: 0.5018041237113402
p_feature_5_b_feature_4_b_feature_3: 0.5220360824742268
p_feature_5_b_feature_4_b_feature_3_b_feature_2: 0.5220360824742268
p_feature_5_b_feature_4_b_feature_3_p_feature_2: 0.5220360824742268
p_feature_4_b_feature_5: 0.4880799794924378
p_feature_4_b_feature_2: 0.5510364733665705
p_feature_4_b_feature_2_p_feature_2: 0.49046391752577323
b_feature_5_p_feature_2: 0.5492207792207793
XofN_groups: [['p_feature_5', 'b_feature_4', 'b_feature_3'], ['p_feature_4', 'b_feature_2']]

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 5
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 5
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 5   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1  roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1  0.469388   0.354839  0.255814  0.297297  0.42093     9               MDI                 DT        roc_auc                    no_org        5

Fold 10/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:MDI.

train
 Training with: algorithm: DT    instances: 705   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.559322        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 705   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.559322        0.0     0.0  0.0  0.514957

train
 Training with: algorithm: DT    instances: 705   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.559322        0.0     0.0  0.0  0.484266

train
 Training with: algorithm: DT    instances: 705   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_5  0.559322        0.0     0.0  0.0  0.535548

train
 Training with: algorithm: DT    instances: 705   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.559322        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 705   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall       f1   roc_auc
p_feature_3  0.423729       0.35  0.358974  0.35443  0.395688

train
 Training with: algorithm: DT    instances: 705   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall   f1   roc_auc
p_feature_4  0.508475   0.432836  0.371795  0.4  0.472675

train
 Training with: algorithm: DT    instances: 705   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall       f1   roc_auc
p_feature_5  0.491525      0.425  0.435897  0.43038  0.481093

train
 Training with: algorithm: DT    instances: 882   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall       f1   roc_auc       MDI
p_feature_3  0.423729   0.350000  0.358974  0.35443  0.395688  0.342469
p_feature_5  0.491525   0.425000  0.435897  0.43038  0.481093  0.274270
p_feature_4  0.508475   0.432836  0.371795  0.40000  0.472675  0.269091
b_feature_4  0.559322   0.000000  0.000000  0.00000  0.484266  0.050866
b_feature_3  0.559322   0.000000  0.000000  0.00000  0.514957  0.034710
b_feature_5  0.559322   0.000000  0.000000  0.00000  0.535548  0.028594
b_feature_2  0.559322   0.000000  0.000000  0.00000  0.500000  0.000000
p_feature_2  0.559322   0.000000  0.000000  0.00000  0.500000  0.000000

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
p_feature_3_p_feature_5: 0.5367532467532468
p_feature_3_p_feature_5_p_feature_4: 0.4856447064855166
p_feature_3_p_feature_5_b_feature_4: 0.4835298641374006
p_feature_3_p_feature_5_b_feature_3: 0.4796206100999744
p_feature_3_p_feature_5_b_feature_5: 0.5056482670089858
p_feature_3_p_feature_5_b_feature_2: 0.44082156611039797
p_feature_3_p_feature_5_p_feature_2: 0.4335426813637529
p_feature_4_b_feature_4: 0.5089079723147911
p_feature_4_b_feature_4_b_feature_3: 0.5415278133811844
p_feature_4_b_feature_4_b_feature_3_b_feature_5: 0.431427839015637
p_feature_4_b_feature_4_b_feature_3_b_feature_2: 0.45783132530120485
p_feature_4_b_feature_4_b_feature_3_p_feature_2: 0.45783132530120485
b_feature_5_b_feature_2: 0.5492207792207793
b_feature_5_b_feature_2_p_feature_2: 0.5363368367085363
XofN_groups: [['p_feature_3', 'p_feature_5'], ['p_feature_4', 'b_feature_4', 'b_feature_3'], ['b_feature_5', 'b_feature_2']]

group_features
Number of original features: 8
Number of generated XofN group features: 3
Number of features in XofN groups: 7
Number of features not in XofN groups: 3
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 3
Number of features in XofN groups: 7
Number of features not in XofN groups: 3
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 882   features: 4   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 97
         accuracy  precision  recall       f1   roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1  0.515464   0.512195  0.4375  0.47191  0.479804    10               MDI                 DT        roc_auc                    no_org        5

CV results:           accuracy  precision    recall        f1   roc_auc
label
label_1  0.481138   0.430004  0.391475  0.408012  0.468535

--- Running with label:'label_1' ranking_criterion:'MDI' training_algorithm:'DT' eval_criterion:'roc_auc' include_original_features:'True' max_size:'5' ---
Logs can be found in XofN_datasets/auto_groupings/label_1_MDI_DT_roc_auc_with_org_5_logs.txt.

drop_uninformative_features
 Removing 0 uninformative binary features. Remaining binary features: 5
 Removing 2 uninformative features where all values are the same. Remaining features: 8

remove_inconsistent_duplicates
  Dropping 19 duplicate rows (keep first). Remaining rows: 981
  ❌ Deleting 2 inconsistent rows (same values for features but different for labels). Remaining: 979

Fold 1/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:MDI.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.536723        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.536723        0.0     0.0  0.0  0.511489

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.536723        0.0     0.0  0.0  0.505392

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_5  0.536723        0.0     0.0  0.0  0.515661

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.536723        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_3  0.491525   0.442857  0.378049  0.407895  0.471566

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall     f1   roc_auc
p_feature_4  0.480226   0.435897  0.414634  0.425  0.492234

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_5  0.514124   0.471429  0.402439  0.434211  0.513286

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall        f1   roc_auc       MDI
p_feature_4  0.480226   0.435897  0.414634  0.425000  0.492234  0.333463
p_feature_3  0.491525   0.442857  0.378049  0.407895  0.471566  0.303765
p_feature_5  0.514124   0.471429  0.402439  0.434211  0.513286  0.266213
b_feature_3  0.536723   0.000000  0.000000  0.000000  0.511489  0.043020
b_feature_4  0.536723   0.000000  0.000000  0.000000  0.505392  0.032612
b_feature_5  0.536723   0.000000  0.000000  0.000000  0.515661  0.020927
b_feature_2  0.536723   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_2  0.536723   0.000000  0.000000  0.000000  0.500000  0.000000

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
p_feature_4_p_feature_3: 0.4904364569961489
p_feature_4_p_feature_5: 0.47920493308842826
p_feature_4_b_feature_3: 0.5
p_feature_4_b_feature_3_b_feature_4: 0.45578056908485
p_feature_4_b_feature_3_b_feature_5: 0.49980744544287553
p_feature_4_b_feature_3_b_feature_2: 0.48902439024390243
p_feature_4_b_feature_3_p_feature_2: 0.48902439024390243
p_feature_3_p_feature_5: 0.5367532467532468
p_feature_3_p_feature_5_b_feature_4: 0.4835298641374006
p_feature_3_p_feature_5_b_feature_5: 0.5056482670089858
p_feature_3_p_feature_5_b_feature_2: 0.44082156611039797
p_feature_3_p_feature_5_p_feature_2: 0.4335426813637529
b_feature_4_b_feature_5: 0.5062160062160062
b_feature_4_b_feature_5_b_feature_2: 0.4868421052631579
b_feature_4_b_feature_5_p_feature_2: 0.4868421052631579
b_feature_2_p_feature_2: 0.5
XofN_groups: [['p_feature_4', 'b_feature_3'], ['p_feature_3', 'p_feature_5'], ['b_feature_4', 'b_feature_5']]

group_features
Number of original features: 8
Number of generated XofN group features: 3
Number of features in XofN groups: 6
Number of features not in XofN groups: 3
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 3
Number of features in XofN groups: 6
Number of features not in XofN groups: 3
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 11   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1   0.44898   0.410256  0.340426  0.372093  0.478306     1               MDI                 DT        roc_auc                  with_org        5

Fold 2/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:MDI.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.564972        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.564972        0.0     0.0  0.0  0.417273

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.564972        0.0     0.0  0.0  0.497273

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_5  0.564972        0.0     0.0  0.0  0.549221

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.564972        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_3  0.570621   0.507937  0.415584  0.457143  0.537597

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_4  0.485876   0.402778  0.376623  0.389262  0.487792

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_5  0.519774   0.435484  0.350649  0.388489  0.520714

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall        f1   roc_auc       MDI
p_feature_5  0.519774   0.435484  0.350649  0.388489  0.520714  0.338978
p_feature_3  0.570621   0.507937  0.415584  0.457143  0.537597  0.313026
p_feature_4  0.485876   0.402778  0.376623  0.389262  0.487792  0.274036
b_feature_4  0.564972   0.000000  0.000000  0.000000  0.497273  0.029845
b_feature_3  0.564972   0.000000  0.000000  0.000000  0.417273  0.025482
b_feature_5  0.564972   0.000000  0.000000  0.000000  0.549221  0.018634
b_feature_2  0.564972   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_2  0.564972   0.000000  0.000000  0.000000  0.500000  0.000000

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
p_feature_5_p_feature_3: 0.48824675324675326
p_feature_5_p_feature_4: 0.48376623376623373
p_feature_5_b_feature_4: 0.517201540436457
p_feature_5_b_feature_3: 0.5094155844155844
p_feature_5_b_feature_5: 0.5123376623376623
p_feature_5_b_feature_2: 0.5207142857142857
p_feature_5_p_feature_2: 0.5207142857142857
p_feature_3_p_feature_4: 0.4767532467532467
p_feature_3_b_feature_4: 0.5234536082474227
p_feature_3_b_feature_3: 0.555
p_feature_3_b_feature_3_b_feature_5: 0.5393506493506494
p_feature_3_b_feature_3_b_feature_2: 0.5508441558441559
p_feature_3_b_feature_3_p_feature_2: 0.5508441558441559
p_feature_4_b_feature_4: 0.5089079723147911
p_feature_4_b_feature_4_b_feature_5: 0.5407792207792208
p_feature_4_b_feature_4_b_feature_5_b_feature_2: 0.5429220779220779
p_feature_4_b_feature_4_b_feature_5_b_feature_2_p_feature_2: 0.5459090909090909
XofN_groups: [['p_feature_3', 'b_feature_3'], ['p_feature_4', 'b_feature_4', 'b_feature_5', 'b_feature_2', 'p_feature_2']]

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 7
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 7
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 10   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1  0.428571   0.432432  0.313725  0.363636  0.411973     2               MDI                 DT        roc_auc                  with_org        5

Fold 3/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:MDI.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.531073        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.531073        0.0     0.0  0.0  0.420405

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.531073        0.0     0.0  0.0  0.482825

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
b_feature_5  0.491525   0.462366  0.518072  0.488636  0.493079

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.531073        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall   f1   roc_auc
p_feature_3  0.457627   0.415584  0.385542  0.4  0.471674

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_4  0.502825   0.459016  0.337349  0.388889  0.496219

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision   recall        f1   roc_auc
p_feature_5  0.497175   0.458333  0.39759  0.425806  0.502243

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall        f1   roc_auc       MDI
p_feature_4  0.502825   0.459016  0.337349  0.388889  0.496219  0.326912
p_feature_3  0.457627   0.415584  0.385542  0.400000  0.471674  0.306520
p_feature_5  0.497175   0.458333  0.397590  0.425806  0.502243  0.254391
b_feature_4  0.531073   0.000000  0.000000  0.000000  0.482825  0.039494
b_feature_5  0.491525   0.462366  0.518072  0.488636  0.493079  0.039029
b_feature_3  0.531073   0.000000  0.000000  0.000000  0.420405  0.033655
b_feature_2  0.531073   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_2  0.531073   0.000000  0.000000  0.000000  0.500000  0.000000

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
p_feature_4_p_feature_3: 0.4904364569961489
p_feature_4_p_feature_5: 0.47920493308842826
p_feature_4_b_feature_4: 0.5089079723147911
p_feature_4_b_feature_4_b_feature_5: 0.5407792207792208
p_feature_4_b_feature_4_b_feature_5_b_feature_3: 0.5099333504229685
p_feature_4_b_feature_4_b_feature_5_b_feature_2: 0.5429220779220779
p_feature_4_b_feature_4_b_feature_5_b_feature_2_p_feature_2: 0.5459090909090909
p_feature_3_p_feature_5: 0.5367532467532468
p_feature_3_p_feature_5_b_feature_3: 0.4796206100999744
XofN_groups: [['p_feature_4', 'b_feature_4', 'b_feature_5', 'b_feature_2', 'p_feature_2'], ['p_feature_3', 'p_feature_5']]

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 7
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 7
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 10   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1  0.510204        0.4  0.285714  0.333333  0.462372     3               MDI                 DT        roc_auc                  with_org        5

Fold 4/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:MDI.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.531073        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.531073        0.0     0.0  0.0  0.478211

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.531073        0.0     0.0  0.0  0.436747

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_5  0.531073        0.0     0.0  0.0  0.536337

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.531073        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_3  0.548023   0.520548  0.457831  0.487179  0.525122

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_4  0.497175   0.461538  0.433735  0.447205  0.492374

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_5  0.497175   0.455882  0.373494  0.410596  0.502499

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall        f1   roc_auc       MDI
p_feature_4  0.497175   0.461538  0.433735  0.447205  0.492374  0.327283
p_feature_3  0.548023   0.520548  0.457831  0.487179  0.525122  0.296814
p_feature_5  0.497175   0.455882  0.373494  0.410596  0.502499  0.295881
b_feature_4  0.531073   0.000000  0.000000  0.000000  0.436747  0.035954
b_feature_3  0.531073   0.000000  0.000000  0.000000  0.478211  0.031067
b_feature_5  0.531073   0.000000  0.000000  0.000000  0.536337  0.013001
b_feature_2  0.531073   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_2  0.531073   0.000000  0.000000  0.000000  0.500000  0.000000

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
p_feature_4_p_feature_3: 0.4904364569961489
p_feature_4_p_feature_5: 0.47920493308842826
p_feature_4_b_feature_4: 0.5089079723147911
p_feature_4_b_feature_4_b_feature_3: 0.5415278133811844
p_feature_4_b_feature_4_b_feature_3_b_feature_5: 0.431427839015637
p_feature_4_b_feature_4_b_feature_3_b_feature_2: 0.45783132530120485
p_feature_4_b_feature_4_b_feature_3_p_feature_2: 0.45783132530120485
p_feature_3_p_feature_5: 0.5367532467532468
p_feature_3_p_feature_5_b_feature_5: 0.5056482670089858
p_feature_3_p_feature_5_b_feature_2: 0.44082156611039797
p_feature_3_p_feature_5_p_feature_2: 0.4335426813637529
b_feature_5_b_feature_2: 0.5492207792207793
b_feature_5_b_feature_2_p_feature_2: 0.5363368367085363
XofN_groups: [['p_feature_4', 'b_feature_4', 'b_feature_3'], ['p_feature_3', 'p_feature_5'], ['b_feature_5', 'b_feature_2']]

group_features
Number of original features: 8
Number of generated XofN group features: 3
Number of features in XofN groups: 7
Number of features not in XofN groups: 3
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 3
Number of features in XofN groups: 7
Number of features not in XofN groups: 3
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 11   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1  0.479592   0.421053  0.355556  0.385542  0.448218     4               MDI                 DT        roc_auc                  with_org        5

Fold 5/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:MDI.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.564972        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.564972        0.0     0.0  0.0  0.480779

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.564972        0.0     0.0  0.0  0.507273

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
b_feature_5  0.531073   0.466667  0.545455  0.502994  0.532727

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.564972        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_3  0.508475   0.432432  0.415584  0.423841  0.484805

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_4  0.497175   0.409091  0.350649  0.377622  0.474416

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall      f1   roc_auc
p_feature_5  0.536723    0.46988  0.506494  0.4875  0.534156

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall        f1   roc_auc       MDI
p_feature_5  0.536723   0.469880  0.506494  0.487500  0.534156  0.314335
p_feature_3  0.508475   0.432432  0.415584  0.423841  0.484805  0.302082
p_feature_4  0.497175   0.409091  0.350649  0.377622  0.474416  0.295798
b_feature_3  0.564972   0.000000  0.000000  0.000000  0.480779  0.041182
b_feature_4  0.564972   0.000000  0.000000  0.000000  0.507273  0.034558
b_feature_5  0.531073   0.466667  0.545455  0.502994  0.532727  0.012046
b_feature_2  0.564972   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_2  0.564972   0.000000  0.000000  0.000000  0.500000  0.000000

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
p_feature_5_p_feature_3: 0.48824675324675326
p_feature_5_p_feature_4: 0.48376623376623373
p_feature_5_b_feature_3: 0.5094155844155844
p_feature_5_b_feature_4: 0.517201540436457
p_feature_5_b_feature_5: 0.5123376623376623
p_feature_5_b_feature_2: 0.5207142857142857
p_feature_5_p_feature_2: 0.5207142857142857
p_feature_3_p_feature_4: 0.4767532467532467
p_feature_3_b_feature_3: 0.555
p_feature_3_b_feature_3_b_feature_4: 0.44227272727272726
p_feature_3_b_feature_3_b_feature_5: 0.5393506493506494
p_feature_3_b_feature_3_b_feature_2: 0.5508441558441559
p_feature_3_b_feature_3_p_feature_2: 0.5508441558441559
p_feature_4_b_feature_4: 0.5089079723147911
p_feature_4_b_feature_4_b_feature_5: 0.5407792207792208
p_feature_4_b_feature_4_b_feature_5_b_feature_2: 0.5429220779220779
p_feature_4_b_feature_4_b_feature_5_b_feature_2_p_feature_2: 0.5459090909090909
XofN_groups: [['p_feature_3', 'b_feature_3'], ['p_feature_4', 'b_feature_4', 'b_feature_5', 'b_feature_2', 'p_feature_2']]

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 7
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 7
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 10   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1  roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1  0.387755   0.340909  0.326087  0.333333  0.35138     5               MDI                 DT        roc_auc                  with_org        5

Fold 6/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:MDI.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.559322        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.559322        0.0     0.0  0.0  0.432789

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.559322        0.0     0.0  0.0  0.526418

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
b_feature_5  0.491525   0.434783  0.512821  0.470588  0.493784

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.559322        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_3  0.468927   0.397436  0.397436  0.397436  0.462963

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_4  0.519774   0.449275  0.397436  0.421769  0.500324

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_5  0.514124   0.455556  0.525641  0.488095  0.511396

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall        f1   roc_auc       MDI
p_feature_3  0.468927   0.397436  0.397436  0.397436  0.462963  0.318377
p_feature_4  0.519774   0.449275  0.397436  0.421769  0.500324  0.289433
p_feature_5  0.514124   0.455556  0.525641  0.488095  0.511396  0.274493
b_feature_3  0.559322   0.000000  0.000000  0.000000  0.432789  0.047109
b_feature_4  0.559322   0.000000  0.000000  0.000000  0.526418  0.040326
b_feature_5  0.491525   0.434783  0.512821  0.470588  0.493784  0.030262
b_feature_2  0.559322   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_2  0.559322   0.000000  0.000000  0.000000  0.500000  0.000000

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
p_feature_3_p_feature_4: 0.4767532467532467
p_feature_3_p_feature_4_p_feature_5: 0.44988344988344986
p_feature_3_p_feature_4_b_feature_3: 0.47377622377622375
p_feature_3_p_feature_4_b_feature_4: 0.5007770007770008
p_feature_3_p_feature_4_b_feature_4_b_feature_5: 0.5301087801087802
p_feature_3_p_feature_4_b_feature_4_b_feature_5_b_feature_2: 0.5301087801087802
p_feature_3_p_feature_4_b_feature_4_b_feature_5_p_feature_2: 0.5301087801087802
p_feature_5_b_feature_3: 0.5094155844155844
p_feature_5_b_feature_2: 0.5207142857142857
p_feature_5_b_feature_2_p_feature_2: 0.5022430146116381
b_feature_3_p_feature_2: 0.5500644329896908
XofN_groups: [['p_feature_3', 'p_feature_4', 'b_feature_4', 'b_feature_5'], ['p_feature_5', 'b_feature_2'], ['b_feature_3', 'p_feature_2']]

group_features
Number of original features: 8
Number of generated XofN group features: 3
Number of features in XofN groups: 8
Number of features not in XofN groups: 3
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 3
Number of features in XofN groups: 8
Number of features not in XofN groups: 3
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 11   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1  0.408163   0.333333  0.318182  0.325581  0.363215     6               MDI                 DT        roc_auc                  with_org        5

Fold 7/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:MDI.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.581921        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.581921        0.0     0.0  0.0  0.417148

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.581921        0.0     0.0  0.0  0.494818

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_5  0.581921        0.0     0.0  0.0  0.527552

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.581921        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_3  0.491525   0.397436  0.418919  0.407895  0.484978

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall        f1   roc_auc
p_feature_4  0.564972   0.480519     0.5  0.490066  0.551036

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1  roc_auc
p_feature_5  0.548023       0.45  0.364865  0.402985  0.53011

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall        f1   roc_auc       MDI
p_feature_4  0.564972   0.480519  0.500000  0.490066  0.551036  0.356278
p_feature_5  0.548023   0.450000  0.364865  0.402985  0.530110  0.295338
p_feature_3  0.491525   0.397436  0.418919  0.407895  0.484978  0.258570
b_feature_4  0.581921   0.000000  0.000000  0.000000  0.494818  0.037305
b_feature_3  0.581921   0.000000  0.000000  0.000000  0.417148  0.028806
b_feature_5  0.581921   0.000000  0.000000  0.000000  0.527552  0.023704
b_feature_2  0.581921   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_2  0.581921   0.000000  0.000000  0.000000  0.500000  0.000000

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
p_feature_4_p_feature_5: 0.47920493308842826
p_feature_4_p_feature_3: 0.4904364569961489
p_feature_4_b_feature_4: 0.5089079723147911
p_feature_4_b_feature_3: 0.5
p_feature_4_b_feature_5: 0.4880799794924378
p_feature_4_b_feature_2: 0.5510364733665705
p_feature_4_p_feature_2: 0.5003237503237503
p_feature_5_p_feature_3: 0.48824675324675326
p_feature_5_b_feature_4: 0.517201540436457
p_feature_5_b_feature_3: 0.5094155844155844
p_feature_5_b_feature_5: 0.5123376623376623
p_feature_5_b_feature_2: 0.5207142857142857
p_feature_5_p_feature_2: 0.5207142857142857
p_feature_3_b_feature_4: 0.5234536082474227
p_feature_3_b_feature_4_b_feature_3: 0.5292574127525583
p_feature_3_b_feature_4_b_feature_3_b_feature_5: 0.46405143007084754
p_feature_3_b_feature_4_b_feature_3_b_feature_2: 0.522828653896615
p_feature_3_b_feature_4_b_feature_3_p_feature_2: 0.522828653896615
b_feature_5_b_feature_2: 0.5492207792207793
b_feature_5_b_feature_2_p_feature_2: 0.5363368367085363
XofN_groups: [['p_feature_3', 'b_feature_4', 'b_feature_3'], ['b_feature_5', 'b_feature_2']]

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 5
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 5
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 10   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision    recall       f1   roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1  0.520408   0.465116  0.454545  0.45977  0.496212     7               MDI                 DT        roc_auc                  with_org        5

Fold 8/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:MDI.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.525424        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.525424        0.0     0.0  0.0  0.454301

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.525424        0.0     0.0  0.0  0.523618

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1  roc_auc
b_feature_5  0.559322   0.535714  0.535714  0.535714  0.55818

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.525424        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_3  0.514124   0.486486  0.428571  0.455696  0.502496

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1   roc_auc
p_feature_4  0.502825   0.472222  0.404762  0.435897  0.477791

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall        f1  roc_auc
p_feature_5  0.525424        0.5  0.404762  0.447368  0.50704

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall        f1   roc_auc       MDI
p_feature_5  0.525424   0.500000  0.404762  0.447368  0.507040  0.379312
p_feature_4  0.502825   0.472222  0.404762  0.435897  0.477791  0.295863
p_feature_3  0.514124   0.486486  0.428571  0.455696  0.502496  0.242737
b_feature_3  0.525424   0.000000  0.000000  0.000000  0.454301  0.038711
b_feature_4  0.525424   0.000000  0.000000  0.000000  0.523618  0.034450
b_feature_5  0.559322   0.535714  0.535714  0.535714  0.558180  0.008926
b_feature_2  0.525424   0.000000  0.000000  0.000000  0.500000  0.000000
p_feature_2  0.525424   0.000000  0.000000  0.000000  0.500000  0.000000

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
p_feature_5_p_feature_4: 0.48376623376623373
p_feature_5_p_feature_3: 0.48824675324675326
p_feature_5_b_feature_3: 0.5094155844155844
p_feature_5_b_feature_3_b_feature_4: 0.5481310803891448
p_feature_5_b_feature_3_b_feature_4_b_feature_5: 0.5472990271377367
p_feature_5_b_feature_3_b_feature_4_b_feature_2: 0.5431387608806962
p_feature_5_b_feature_3_b_feature_4_p_feature_2: 0.5431387608806962
p_feature_4_p_feature_3: 0.4904364569961489
p_feature_4_p_feature_3_b_feature_5: 0.5276497695852534
p_feature_4_p_feature_3_b_feature_5_b_feature_2: 0.5483870967741935
p_feature_4_p_feature_3_b_feature_5_b_feature_2_p_feature_2: 0.5353302611367128
XofN_groups: [['p_feature_5', 'b_feature_3', 'b_feature_4'], ['p_feature_4', 'p_feature_3', 'b_feature_5', 'b_feature_2']]

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 7
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 7
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 10   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1  0.520408      0.425  0.414634  0.419753  0.466624     8               MDI                 DT        roc_auc                  with_org        5

Fold 9/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:MDI.

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.548023        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.548023        0.0     0.0  0.0  0.550064

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.548023        0.0     0.0  0.0  0.463982

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_5  0.548023        0.0     0.0  0.0  0.571005

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.548023        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
p_feature_3  0.570621   0.527778   0.475  0.5  0.559729

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall       f1   roc_auc
p_feature_4  0.531073    0.47619   0.375  0.41958  0.490464

train
 Training with: algorithm: DT    instances: 704   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall        f1   roc_auc
p_feature_5  0.508475   0.444444    0.35  0.391608  0.499936

train
 Training with: algorithm: DT    instances: 881   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision  recall        f1   roc_auc       MDI
p_feature_3  0.570621   0.527778   0.475  0.500000  0.559729  0.341532
p_feature_5  0.508475   0.444444   0.350  0.391608  0.499936  0.286832
p_feature_4  0.531073   0.476190   0.375  0.419580  0.490464  0.277317
b_feature_4  0.548023   0.000000   0.000  0.000000  0.463982  0.050448
b_feature_5  0.548023   0.000000   0.000  0.000000  0.571005  0.025280
b_feature_3  0.548023   0.000000   0.000  0.000000  0.550064  0.018590
b_feature_2  0.548023   0.000000   0.000  0.000000  0.500000  0.000000
p_feature_2  0.548023   0.000000   0.000  0.000000  0.500000  0.000000

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
p_feature_3_p_feature_5: 0.5367532467532468
p_feature_3_p_feature_4: 0.4767532467532467
p_feature_3_b_feature_4: 0.5234536082474227
p_feature_3_b_feature_5: 0.5106958762886598
p_feature_3_b_feature_3: 0.555
p_feature_3_b_feature_2: 0.5375974025974026
p_feature_3_p_feature_2: 0.5375974025974026
p_feature_5_p_feature_4: 0.48376623376623373
p_feature_5_b_feature_4: 0.517201540436457
p_feature_5_b_feature_4_b_feature_5: 0.5018041237113402
p_feature_5_b_feature_4_b_feature_3: 0.5220360824742268
p_feature_5_b_feature_4_b_feature_3_b_feature_2: 0.5220360824742268
p_feature_5_b_feature_4_b_feature_3_p_feature_2: 0.5220360824742268
p_feature_4_b_feature_5: 0.4880799794924378
p_feature_4_b_feature_2: 0.5510364733665705
p_feature_4_b_feature_2_p_feature_2: 0.49046391752577323
b_feature_5_p_feature_2: 0.5492207792207793
XofN_groups: [['p_feature_5', 'b_feature_4', 'b_feature_3'], ['p_feature_4', 'b_feature_2']]

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 5
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 2
Number of features in XofN groups: 5
Number of features not in XofN groups: 2
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 881   features: 10   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 98
         accuracy  precision    recall        f1   roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1  0.428571   0.290323  0.209302  0.243243  0.458562     9               MDI                 DT        roc_auc                  with_org        5

Fold 10/10

generate_feature_rankings -> Generating rankings based on ranking_criterion:MDI.

train
 Training with: algorithm: DT    instances: 705   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
b_feature_2  0.559322        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 705   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_3  0.559322        0.0     0.0  0.0  0.514957

train
 Training with: algorithm: DT    instances: 705   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_4  0.559322        0.0     0.0  0.0  0.484266

train
 Training with: algorithm: DT    instances: 705   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1   roc_auc
b_feature_5  0.559322        0.0     0.0  0.0  0.535548

train
 Training with: algorithm: DT    instances: 705   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision  recall   f1  roc_auc
p_feature_2  0.559322        0.0     0.0  0.0      0.5

train
 Training with: algorithm: DT    instances: 705   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall       f1   roc_auc
p_feature_3  0.423729       0.35  0.358974  0.35443  0.395688

train
 Training with: algorithm: DT    instances: 705   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall   f1   roc_auc
p_feature_4  0.508475   0.432836  0.371795  0.4  0.472675

train
 Training with: algorithm: DT    instances: 705   features: 1   labels: 1 ['label_1']
 Training...

test
 Testing with:  instances: 177
             accuracy  precision    recall       f1   roc_auc
p_feature_5  0.491525      0.425  0.435897  0.43038  0.481093

train
 Training with: algorithm: DT    instances: 882   features: 8   labels: 1 ['label_1']
 Training...
             accuracy  precision    recall       f1   roc_auc       MDI
p_feature_3  0.423729   0.350000  0.358974  0.35443  0.395688  0.342469
p_feature_5  0.491525   0.425000  0.435897  0.43038  0.481093  0.274270
p_feature_4  0.508475   0.432836  0.371795  0.40000  0.472675  0.269091
b_feature_4  0.559322   0.000000  0.000000  0.00000  0.484266  0.050866
b_feature_3  0.559322   0.000000  0.000000  0.00000  0.514957  0.034710
b_feature_5  0.559322   0.000000  0.000000  0.00000  0.535548  0.028594
b_feature_2  0.559322   0.000000  0.000000  0.00000  0.500000  0.000000
p_feature_2  0.559322   0.000000  0.000000  0.00000  0.500000  0.000000

generate_XofN_list -> Generating groupings based on eval_criterion:roc_auc.
p_feature_3_p_feature_5: 0.5367532467532468
p_feature_3_p_feature_5_p_feature_4: 0.4856447064855166
p_feature_3_p_feature_5_b_feature_4: 0.4835298641374006
p_feature_3_p_feature_5_b_feature_3: 0.4796206100999744
p_feature_3_p_feature_5_b_feature_5: 0.5056482670089858
p_feature_3_p_feature_5_b_feature_2: 0.44082156611039797
p_feature_3_p_feature_5_p_feature_2: 0.4335426813637529
p_feature_4_b_feature_4: 0.5089079723147911
p_feature_4_b_feature_4_b_feature_3: 0.5415278133811844
p_feature_4_b_feature_4_b_feature_3_b_feature_5: 0.431427839015637
p_feature_4_b_feature_4_b_feature_3_b_feature_2: 0.45783132530120485
p_feature_4_b_feature_4_b_feature_3_p_feature_2: 0.45783132530120485
b_feature_5_b_feature_2: 0.5492207792207793
b_feature_5_b_feature_2_p_feature_2: 0.5363368367085363
XofN_groups: [['p_feature_3', 'p_feature_5'], ['p_feature_4', 'b_feature_4', 'b_feature_3'], ['b_feature_5', 'b_feature_2']]

group_features
Number of original features: 8
Number of generated XofN group features: 3
Number of features in XofN groups: 7
Number of features not in XofN groups: 3
Number of XofN group features with a single item: 0

group_features
Number of original features: 8
Number of generated XofN group features: 3
Number of features in XofN groups: 7
Number of features not in XofN groups: 3
Number of XofN group features with a single item: 0

train
 Training with: algorithm: RF    instances: 882   features: 11   labels: 1 ['label_1']
 Training...

c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\KostasVoror\anaconda3\envs\phd\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

test
 Testing with:  instances: 97
         accuracy  precision    recall        f1   roc_auc  fold ranking_criterion training_algorithm eval_criterion include_original_features max_size
label_1   0.56701   0.578947  0.458333  0.511628  0.557185    10               MDI                 DT        roc_auc                  with_org        5

CV results:           accuracy  precision   recall        f1   roc_auc
label
label_1  0.469966   0.409737  0.34765  0.374791  0.449405

,index,ranking_criterion,training_algorithm,eval_criterion,include_original_features,accuracy,precision,recall,f1,roc_auc
0,label_1,MDI,DT,roc_auc,no_org,0.481138,0.430004,0.391475,0.408012,0.468535
1,label_1,MDI,DT,roc_auc,with_org,0.469966,0.409737,0.347650,0.374791,0.449405
2,label_1,roc_auc,DT,roc_auc,no_org,0.476005,0.422732,0.372365,0.394683,0.460451
3,label_1,roc_auc,DT,roc_auc,with_org,0.465853,0.403235,0.340100,0.367776,0.453478

In [1]:
# exhaustive search example - produced in about 1 minute
# create combinations
import itertools

# Example list
nums = range(1, 100)

all_combinations = [
    list(c)
    for r in range(2, 6)
    for c in itertools.combinations(nums, r)
]

print(len(all_combinations))

75449220

In [2]:
# executed in about 6 secs
x = 0
for comb in all_combinations:
    x = x + 1
print(x)

75449220

In [3]:
print_xofn_groups_stats(generate_XofN_list_1st_fold())

XofN_groups: [['f_20', 'f_771', 'f_390', 'f_299', 'f_645'], ['f_23', 'f_513', 'f_355', 'f_146', 'f_394'], ['f_346', 'f_706', 'f_613', 'f_592'], ['f_308', 'f_815', 'f_582', 'f_578', 'f_257'], ['f_366', 'f_413', 'f_286'], ['f_15', 'f_151', 'f_351', 'f_192', 'f_292'], ['f_451', 'f_343', 'f_416', 'f_656', 'f_430'], ['f_287', 'f_471', 'f_333', 'f_709', 'f_31'], ['f_672', 'f_35', 'f_441', 'f_752', 'f_446'], ['f_406', 'f_361', 'f_556', 'f_616'], ['f_639', 'f_436', 'f_178', 'f_420', 'f_462'], ['f_3', 'f_214', 'f_143', 'f_712', 'f_699'], ['f_37', 'f_839', 'f_819', 'f_1', 'f_708'], ['f_392', 'f_631', 'f_285', 'f_824', 'f_635'], ['f_380', 'f_47', 'f_643', 'f_683', 'f_607'], ['f_452', 'f_328', 'f_340', 'f_255', 'f_545'], ['f_11', 'f_284', 'f_365', 'f_375', 'f_297'], ['f_614', 'f_131', 'f_384', 'f_569', 'f_552'], ['f_571', 'f_118', 'f_696', 'f_181', 'f_339'], ['f_24', 'f_647', 'f_439', 'f_464', 'f_803'], ['f_440', 'f_670', 'f_549', 'f_437', 'f_356'], ['f_617', 'f_729', 'f_14', 'f_585', 'f_454'], ['f_391', 'f_840', 'f_249', 'f_459', 'f_335'], ['f_686', 'f_475', 'f_540', 'f_523', 'f_602'], ['f_338', 'f_834', 'f_628', 'f_758', 'f_558'], ['f_659', 'f_861', 'f_241', 'f_334', 'f_801'], ['f_38', 'f_860', 'f_710'], ['f_681', 'f_500', 'f_679', 'f_689', 'f_750'], ['f_33', 'f_675', 'f_442', 'f_618', 'f_16'], ['f_528', 'f_554', 'f_555', 'f_520', 'f_408'], ['f_332', 'f_10', 'f_349', 'f_188', 'f_657'], ['f_567', 'f_330', 'f_370', 'f_345', 'f_604'], ['f_663', 'f_518', 'f_638', 'f_300', 'f_383'], ['f_21', 'f_115', 'f_688', 'f_480', 'f_467'], ['f_690', 'f_622', 'f_570', 'f_368', 'f_434'], ['f_615', 'f_262', 'f_376', 'f_145', 'f_799'], ['f_642', 'f_792', 'f_418', 'f_598', 'f_227'], ['f_682', 'f_298', 'f_449', 'f_738'], ['f_704', 'f_568', 'f_664', 'f_576', 'f_584'], ['f_553', 'f_827', 'f_599', 'f_640', 'f_327'], ['f_698', 'f_350', 'f_564', 'f_692', 'f_650'], ['f_248', 'f_488', 'f_490', 'f_450', 'f_678'], ['f_537', 'f_551', 'f_660', 'f_680', 'f_179'], ['f_671', 'f_676', 'f_524', 'f_466', 'f_485'], ['f_294', 'f_497', 'f_495', 'f_536', 'f_756'], ['f_637', 'f_46', 'f_633', 'f_470', 'f_377'], ['f_691', 'f_533', 'f_665', 'f_531', 'f_417'], ['f_646', 'f_427', 'f_560', 'f_625', 'f_593'], ['f_353', 'f_707', 'f_668', 'f_655', 'f_30'], ['f_701', 'f_489', 'f_538', 'f_685', 'f_608'], ['f_193', 'f_588', 'f_677', 'f_755', 'f_305'], ['f_797', 'f_508', 'f_595', 'f_256', 'f_502'], ['f_301', 'f_494', 'f_9', 'f_431', 'f_548'], ['f_687', 'f_414', 'f_603', 'f_600', 'f_458'], ['f_597', 'f_460', 'f_530', 'f_213', 'f_371'], ['f_34', 'f_422', 'f_453', 'f_575', 'f_229'], ['f_662', 'f_509', 'f_634', 'f_770', 'f_511'], ['f_798', 'f_547', 'f_546', 'f_129', 'f_385'], ['f_432', 'f_43', 'f_352', 'f_831', 'f_728'], ['f_199', 'f_216', 'f_259', 'f_473', 'f_725'], ['f_711', 'f_609', 'f_719', 'f_845'], ['f_550', 'f_419', 'f_866', 'f_501', 'f_25'], ['f_591', 'f_429', 'f_230', 'f_737', 'f_379'], ['f_623', 'f_759', 'f_456'], ['f_705', 'f_822', 'f_768'], ['f_150', 'f_763', 'f_821', 'f_580', 'f_465'], ['f_695', 'f_363', 'f_629', 'f_778', 'f_493'], ['f_412', 'f_507', 'f_474', 'f_378', 'f_539'], ['f_586', 'f_624'], ['f_779', 'f_242', 'f_144', 'f_461', 'f_740'], ['f_654', 'f_448', 'f_358', 'f_498', 'f_357'], ['f_716', 'f_215', 'f_336'], ['f_735', 'f_152', 'f_736', 'f_153', 'f_791'], ['f_780', 'f_499', 'f_387', 'f_636', 'f_447'], ['f_0', 'f_673', 'f_425', 'f_820', 'f_403'], ['f_734', 'f_543', 'f_542', 'f_27', 'f_526'], ['f_800', 'f_22'], ['f_519', 'f_407', 'f_396', 'f_243', 'f_674'], ['f_700', 'f_421', 'f_517'], ['f_367', 'f_812', 'f_401', 'f_784', 'f_457'], ['f_610', 'f_694', 'f_532', 'f_428'], ['f_283', 'f_258', 'f_515', 'f_395', 'f_438'], ['f_200', 'f_612', 'f_472', 'f_541', 'f_503'], ['f_206', 'f_260', 'f_506', 'f_445', 'f_596'], ['f_157', 'f_116', 'f_187', 'f_484', 'f_658'], ['f_717', 'f_749', 'f_362', 'f_132', 'f_160'], ['f_347', 'f_826', 'f_757', 'f_194', 'f_167'], ['f_397', 'f_159', 'f_482', 'f_373', 'f_398'], ['f_559', 'f_572', 'f_527', 'f_483', 'f_195'], ['f_761', 'f_409', 'f_486', 'f_653', 'f_359'], ['f_364', 'f_813', 'f_386', 'f_522', 'f_514']]
XofN groups with 2 features: 2
XofN groups with 3 features: 6
XofN groups with 4 features: 5
XofN groups with 5 features: 78
91
432
91
Average number of features per XofN attribute: 4.75