In [1]:
from sklearn.model_selection import KFold
from SIDER_dataset.libraries.XofN_library import *
from SIDER_dataset.libraries.PCT_library import run_PCT, remove_PCT_files
from SIDER_dataset.libraries.utils import get_clus_path
%load_ext autoreload
%autoreload 2

In [2]:
# Set ADR to predict and scoring
clus_path = get_clus_path()
paths = get_dataset_paths(verbose=True)
print(len(paths), "datasets")

Processing fingerprint for 6 labels: ['se_C0027497', 'se_C0018681', 'se_C0011603', 'se_C0015230', 'se_C0042963', 'se_C0012833']
fingerprint_frequent
C:\Users\KostasVoror\Projects/SEP/SIDER_dataset/datasets/clean_multi_label_datasets/fingerprint_frequent.csv

Processing CPI for 6 labels: ['se_C0027497', 'se_C0018681', 'se_C0011603', 'se_C0015230', 'se_C0042963', 'se_C0012833']
CPI_frequent
C:\Users\KostasVoror\Projects/SEP/SIDER_dataset/datasets/clean_multi_label_datasets/CPI_frequent.csv

Processing CPI+fingerprint for 6 labels: ['se_C0027497', 'se_C0018681', 'se_C0011603', 'se_C0015230', 'se_C0042963', 'se_C0012833']
CPI+fingerprint_frequent
C:\Users\KostasVoror\Projects/SEP/SIDER_dataset/datasets/clean_multi_label_datasets/CPI+fingerprint_frequent.csv

Processing fingerprint for 6 labels: ['se_C0027769', 'se_C0020580', 'se_C0014457', 'se_C0017181', 'se_C0151763', 'se_C0038358']
fingerprint_diverse
C:\Users\KostasVoror\Projects/SEP/SIDER_dataset/datasets/clean_multi_label_datasets/fingerprint_diverse.csv

Processing CPI for 6 labels: ['se_C0027769', 'se_C0020580', 'se_C0014457', 'se_C0017181', 'se_C0151763', 'se_C0038358']
CPI_diverse
C:\Users\KostasVoror\Projects/SEP/SIDER_dataset/datasets/clean_multi_label_datasets/CPI_diverse.csv

Processing CPI+fingerprint for 6 labels: ['se_C0027769', 'se_C0020580', 'se_C0014457', 'se_C0017181', 'se_C0151763', 'se_C0038358']
CPI+fingerprint_diverse
C:\Users\KostasVoror\Projects/SEP/SIDER_dataset/datasets/clean_multi_label_datasets/CPI+fingerprint_diverse.csv

Processing fingerprint for 12 labels: ['se_C0027497', 'se_C0018681', 'se_C0011603', 'se_C0015230', 'se_C0042963', 'se_C0012833', 'se_C0027769', 'se_C0020580', 'se_C0014457', 'se_C0017181', 'se_C0151763', 'se_C0038358']
fingerprint_all
C:\Users\KostasVoror\Projects/SEP/SIDER_dataset/datasets/clean_multi_label_datasets/fingerprint_all.csv

Processing CPI for 12 labels: ['se_C0027497', 'se_C0018681', 'se_C0011603', 'se_C0015230', 'se_C0042963', 'se_C0012833', 'se_C0027769', 'se_C0020580', 'se_C0014457', 'se_C0017181', 'se_C0151763', 'se_C0038358']
CPI_all
C:\Users\KostasVoror\Projects/SEP/SIDER_dataset/datasets/clean_multi_label_datasets/CPI_all.csv

Processing CPI+fingerprint for 12 labels: ['se_C0027497', 'se_C0018681', 'se_C0011603', 'se_C0015230', 'se_C0042963', 'se_C0012833', 'se_C0027769', 'se_C0020580', 'se_C0014457', 'se_C0017181', 'se_C0151763', 'se_C0038358']
CPI+fingerprint_all
C:\Users\KostasVoror\Projects/SEP/SIDER_dataset/datasets/clean_multi_label_datasets/CPI+fingerprint_all.csv

9 datasets

In [3]:
k = 10
random_state = 42
performances = []
ranking_criteria = ["MDI"]
include_original_features_options = [True, False]
training_algorithm = "PCT"
eval_criteria = ["averageAUROC", "HammingLoss", "SubsetAccuracy"]
max_size = 5
cv_results = []
paths = [paths[6]]  # for wrapper do 1 by 1
for idx, path in enumerate(paths, start=1):
    run_config = f"\n--- Running with label:'{path["label_set"]}' training_algorithm:'{training_algorithm}' eval_criterion:'{eval_criteria}' max_size:'{max_size}' ---"
    print(run_config)
    run_config_name = "_".join(
        [
            path["dataset_name"],
            training_algorithm,
            "_".join(eval_criteria),
            str(max_size),
        ]
    )
    logging_path = f"XofN_wrapper/logs/{run_config_name}_logs.txt"
    print(f"Logs can be found in {logging_path}.")
    logger = get_logger(logging_path)
    logger.info(run_config_name)

    # Load dataset
    current_df = pd.read_csv(path["dataset_path"])
    features = get_features(current_df, path["label_set"])
    # current_df = current_df[features[:100] + path["label_set"]]
    kf = KFold(n_splits=k, shuffle=True, random_state=random_state)
    for fold, (train_idx, test_idx) in enumerate(kf.split(current_df), start=1):
        print(f"\nFold {fold}/{k} ({path["dataset_name"]} {idx}/{len(paths)})")
        train_dataset = current_df.iloc[train_idx]
        test_dataset = current_df.iloc[test_idx]

        feature_rankings = calculate_mdi_multi_rf(train_dataset, path["label_set"])

        XofN_groupings, avg_features, gen_XofN_time = generate_XofN_list_multi(
            train_dataset,
            feature_rankings,
            eval_criteria,
            max_size,
            path["label_set"],
            False,
            logger,
            clus_path,
            "XofN_wrapper/tmp"
        )
        remove_PCT_files("XofN_wrapper/tmp")
        if len(XofN_groupings) == 0:
            print("no XofN groupings were created")
        else:
            for include_original_features in include_original_features_options:
                current_train_dataset = group_features(
                    train_dataset,
                    path["label_set"],
                    XofN_groupings,
                    include_original_features,
                    verbose=True
                )

                current_test_dataset = group_features(
                    test_dataset,
                    path["label_set"],
                    XofN_groupings,
                    include_original_features,
                    verbose=True
                )

                current_train_dataset.to_csv(f"XofN_wrapper/tmp/train_dataset.csv", index=False)
                current_test_dataset.to_csv(f"XofN_wrapper/tmp/test_dataset.csv", index=False)

                original_res, pruned_res, training_time = run_PCT(clus_path,
                                                                  "XofN_wrapper/tmp/train_dataset.csv",
                                                                  path["label_set"],
                                                                  eval_criteria,
                                                                  test_dataset_path=f"XofN_wrapper/tmp/test_dataset.csv")
                pruned_performance = get_fold_results(pruned_res, eval_criteria, True, fold, include_original_features,
                                                      XofN_groupings,
                                                      gen_XofN_time,
                                                      training_time, path["dataset_name"])
                performances.append(pruned_performance)
                performance = get_fold_results(original_res, eval_criteria, False, fold, include_original_features,
                                               XofN_groupings,
                                               gen_XofN_time,
                                               training_time, path["dataset_name"])
                performances.append(performance)

    if len(performances) == 0:
        print("no XofN groupings were created in any fold")
    else:
        final_perf_df = pd.DataFrame(performances)
        averages = final_perf_df.groupby(["pruning", 'include_original_features', 'dataset'])[
            ['averageAUROC', 'HammingLoss', 'SubsetAccuracy', 'nodes', 'leaves', 'groups',
             'avg_group_features', 'gen_XofN_time', 'training_time']].mean().reset_index()
        print(averages)
        (cv_results.append

         (averages))
        performances = []
# paths[0] - features[:10]
# laptop ??m
# desktop 1.34m

--- Running with label:'['se_C0027497', 'se_C0018681', 'se_C0011603', 'se_C0015230', 'se_C0042963', 'se_C0012833', 'se_C0027769', 'se_C0020580', 'se_C0014457', 'se_C0017181', 'se_C0151763', 'se_C0038358']' training_algorithm:'PCT' eval_criterion:'['averageAUROC', 'HammingLoss', 'SubsetAccuracy']' max_size:'5' ---
Logs can be found in XofN_wrapper/logs/fingerprint_all_PCT_averageAUROC_HammingLoss_SubsetAccuracy_5_logs.txt.

Fold 1/10 (fingerprint_all 1/1)

generate_XofN_list -> Generating groupings based on eval_criterion:['averageAUROC', 'HammingLoss', 'SubsetAccuracy'].

🔄 Processing features: 100%|██████████| 540/540 [1:58:14<00:00, 13.14s/feat]

XofN_groups: [['f_374', 'f_398', 'f_20', 'f_715', 'f_284'], ['f_23', 'f_455', 'f_285', 'f_14', 'f_543'], ['f_308', 'f_132', 'f_635', 'f_344', 'f_406'], ['f_346', 'f_343', 'f_752', 'f_333', 'f_441'], ['f_366', 'f_706', 'f_451', 'f_393', 'f_15'], ['f_287', 'f_401', 'f_351', 'f_10', 'f_522'], ['f_2', 'f_413', 'f_443', 'f_420', 'f_332'], ['f_19', 'f_129', 'f_613', 'f_345', 'f_178'], ['f_299', 'f_131', 'f_338', 'f_707', 'f_460'], ['f_571', 'f_422', 'f_815', 'f_696', 'f_143'], ['f_697', 'f_483', 'f_464', 'f_861', 'f_26'], ['f_24', 'f_532', 'f_390', 'f_778', 'f_438'], ['f_452', 'f_216', 'f_9', 'f_768', 'f_440'], ['f_391', 'f_515', 'f_392', 'f_446', 'f_146'], ['f_335', 'f_214', 'f_12', 'f_704', 'f_845'], ['f_339', 'f_625', 'f_535', 'f_579', 'f_729'], ['f_639', 'f_840', 'f_249', 'f_416', 'f_503'], ['f_672', 'f_551', 'f_11', 'f_118', 'f_725'], ['f_380', 'f_511', 'f_0', 'f_388'], ['f_186', 'f_466', 'f_430', 'f_654', 'f_711'], ['f_528', 'f_395', 'f_569', 'f_507', 'f_200'], ['f_656', 'f_394', 'f_21', 'f_647', 'f_365'], ['f_643', 'f_227', 'f_213', 'f_580', 'f_601'], ['f_185', 'f_609', 'f_352', 'f_582'], ['f_566', 'f_510', 'f_536', 'f_592', 'f_866'], ['f_659', 'f_454', 'f_593', 'f_531', 'f_540'], ['f_405', 'f_361', 'f_490', 'f_681', 'f_480'], ['f_614', 'f_568', 'f_683', 'f_370', 'f_167'], ['f_192', 'f_771', 'f_688', 'f_38', 'f_695'], ['f_3', 'f_738', 'f_255', 'f_663', 'f_371'], ['f_181', 'f_408', 'f_1', 'f_587', 'f_682'], ['f_617', 'f_230', 'f_679', 'f_763', 'f_489'], ['f_340', 'f_215', 'f_645', 'f_257', 'f_549'], ['f_180', 'f_159', 'f_646', 'f_16', 'f_457'], ['f_37', 'f_658', 'f_560', 'f_429', 'f_611'], ['f_341', 'f_31', 'f_788', 'f_599'], ['f_712', 'f_791', 'f_442', 'f_860', 'f_150'], ['f_667', 'f_359', 'f_355', 'f_450', 'f_305'], ['f_439', 'f_517', 'f_375', 'f_18', 'f_558'], ['f_638', 'f_474', 'f_602', 'f_383', 'f_588'], ['f_516', 'f_773', 'f_356', 'f_501', 'f_598'], ['f_691', 'f_514', 'f_618', 'f_449', 'f_529'], ['f_698', 'f_300', 'f_513', 'f_556', 'f_292'], ['f_337', 'f_17', 'f_419', 'f_434', 'f_327'], ['f_686', 'f_465', 'f_384', 'f_397', 'f_508'], ['f_692', 'f_151', 'f_248', 'f_35', 'f_494'], ['f_567', 'f_486', 'f_283', 'f_612', 'f_286'], ['f_615', 'f_262', 'f_418', 'f_471', 'f_261'], ['f_33', 'f_749', 'f_453', 'f_734', 'f_710'], ['f_637', 'f_631', 'f_524', 'f_777', 'f_553'], ['f_776', 'f_779', 'f_676', 'f_709', 'f_34'], ['f_241', 'f_713', 'f_708', 'f_594', 'f_789'], ['f_699', 'f_160', 'f_421', 'f_640', 'f_836'], ['f_642', 'f_650', 'f_538', 'f_610', 'f_500'], ['f_199', 'f_368', 'f_256', 'f_293', 'f_801'], ['f_702', 'f_350', 'f_423', 'f_726', 'f_799'], ['f_581', 'f_115', 'f_378', 'f_353', 'f_487'], ['f_690', 'f_399', 'f_570', 'f_701', 'f_636'], ['f_797', 'f_400', 'f_259', 'f_334', 'f_831'], ['f_432', 'f_822', 'f_407', 'f_179', 'f_693'], ['f_685', 'f_144', 'f_687', 'f_448', 'f_47'], ['f_244', 'f_250', 'f_634', 'f_475', 'f_668'], ['f_294', 'f_349', 'f_820', 'f_428', 'f_719'], ['f_671', 'f_559', 'f_678', 'f_30'], ['f_818', 'f_414', 'f_595', 'f_301', 'f_207'], ['f_502', 'f_546'], ['f_666', 'f_833', 'f_431', 'f_412', 'f_447'], ['f_755', 'f_805', 'f_821', 'f_458', 'f_437'], ['f_193', 'f_652', 'f_187', 'f_552', 'f_328'], ['f_662', 'f_116', 'f_608', 'f_488', 'f_812'], ['f_145', 'f_792', 'f_545', 'f_605', 'f_470'], ['f_537', 'f_717', 'f_164', 'f_497', 'f_509'], ['f_462', 'f_780', 'f_166', 'f_670', 'f_785'], ['f_628', 'f_750', 'f_584', 'f_377', 'f_461'], ['f_336', 'f_555', 'f_677', 'f_539', 'f_520'], ['f_819', 'f_756', 'f_675', 'f_722'], ['f_633', 'f_526', 'f_578', 'f_664', 'f_342'], ['f_13', 'f_194', 'f_603', 'f_826', 'f_606'], ['f_798', 'f_839', 'f_364', 'f_770'], ['f_550', 'f_417', 'f_564', 'f_260', 'f_482'], ['f_700', 'f_527', 'f_585', 'f_357', 'f_411'], ['f_705', 'f_22', 'f_590', 'f_46', 'f_367'], ['f_607', 'f_554', 'f_445', 'f_387', 'f_409'], ['f_363', 'f_258', 'f_459', 'f_521', 'f_736'], ['f_577', 'f_629', 'f_586', 'f_533', 'f_456'], ['f_243', 'f_473', 'f_657', 'f_621', 'f_703'], ['f_188', 'f_616', 'f_495', 'f_43', 'f_229'], ['f_714', 'f_298', 'f_660', 'f_467', 'f_436'], ['f_758', 'f_505', 'f_251', 'f_396', 'f_427'], ['f_800', 'f_737', 'f_813'], ['f_716', 'f_242', 'f_759', 'f_202'], ['f_694', 'f_803'], ['f_632', 'f_644', 'f_523', 'f_425', 'f_830'], ['f_519', 'f_206', 'f_372', 'f_542', 'f_767'], ['f_665', 'f_583', 'f_403', 'f_358'], ['f_673', 'f_824', 'f_376', 'f_761', 'f_728'], ['f_735', 'f_152', 'f_297'], ['f_620', 'f_25'], ['f_596', 'f_740', 'f_544', 'f_630', 'f_757'], ['f_385', 'f_622', 'f_314', 'f_834', 'f_721'], ['f_600', 'f_764', 'f_472', 'f_491'], ['f_362', 'f_575', 'f_651', 'f_330'], ['f_435', 'f_518', 'f_373', 'f_742', 'f_674'], ['f_661', 'f_386', 'f_624', 'f_506', 'f_485'], ['f_347', 'f_389'], ['f_379', 'f_653', 'f_484'], ['f_563', 'f_827', 'f_27', 'f_195', 'f_504'], ['f_547', 'f_784', 'f_572']]
XofN groups with 2 features: 4
XofN groups with 3 features: 4
XofN groups with 4 features: 10
XofN groups with 5 features: 90
pruning: True, include_original_features: with_org, averageAUROC: 0.5210596, HammingLoss: 0.21692, SubsetAccuracy: 0.10687,
pruning: False, include_original_features: with_org, averageAUROC: 0.5758082, HammingLoss: 0.28372, SubsetAccuracy: 0.061069,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.21947, SubsetAccuracy: 0.10687,
pruning: False, include_original_features: no_org, averageAUROC: 0.5444658, HammingLoss: 0.29771, SubsetAccuracy: 0.068702,

Fold 2/10 (fingerprint_all 1/1)

generate_XofN_list -> Generating groupings based on eval_criterion:['averageAUROC', 'HammingLoss', 'SubsetAccuracy'].

🔄 Processing features: 100%|██████████| 540/540 [1:57:52<00:00, 13.10s/feat]

XofN_groups: [['f_374', 'f_489', 'f_340', 'f_390', 'f_580'], ['f_20', 'f_511', 'f_592', 'f_14', 'f_375'], ['f_308', 'f_631', 'f_449', 'f_376', 'f_401'], ['f_366', 'f_860', 'f_43', 'f_0', 'f_333'], ['f_346', 'f_242', 'f_10', 'f_151', 'f_413'], ['f_406', 'f_763', 'f_660', 'f_11', 'f_131'], ['f_571', 'f_839', 'f_670', 'f_214', 'f_480'], ['f_2', 'f_129', 'f_570', 'f_613', 'f_540'], ['f_23', 'f_16', 'f_420', 'f_284', 'f_15'], ['f_287', 'f_399', 'f_683', 'f_300', 'f_408'], ['f_338', 'f_395', 'f_442', 'f_216', 'f_625'], ['f_186', 'f_812', 'f_143', 'f_684', 'f_508'], ['f_656', 'f_132', 'f_645', 'f_588', 'f_461'], ['f_392', 'f_215', 'f_146', 'f_412', 'f_451'], ['f_617', 'f_466', 'f_556', 'f_749', 'f_202'], ['f_335', 'f_361', 'f_672', 'f_241', 'f_699'], ['f_391', 'f_25', 'f_355', 'f_611', 'f_344'], ['f_452', 'f_467', 'f_560', 'f_285', 'f_365'], ['f_299', 'f_227', 'f_255', 'f_437', 'f_33'], ['f_12', 'f_622', 'f_696', 'f_341', 'f_474'], ['f_192', 'f_861', 'f_178', 'f_339', 'f_780'], ['f_643', 'f_517', 'f_549', 'f_351', 'f_230'], ['f_380', 'f_658', 'f_9', 'f_784'], ['f_697', 'f_483', 'f_569', 'f_654', 'f_703'], ['f_393', 'f_26', 'f_464', 'f_633', 'f_616'], ['f_185', 'f_496', 'f_577', 'f_826', 'f_665'], ['f_19', 'f_283', 'f_502', 'f_638', 'f_536'], ['f_614', 'f_840', 'f_717', 'f_441', 'f_350'], ['f_566', 'f_473', 'f_495', 'f_555', 'f_778'], ['f_639', 'f_244', 'f_356', 'f_582', 'f_791'], ['f_528', 'f_213', 'f_677', 'f_345', 'f_145'], ['f_440', 'f_586', 'f_416', 'f_505', 'f_370'], ['f_37', 'f_249', 'f_689', 'f_554', 'f_708'], ['f_659', 'f_531', 'f_674', 'f_607', 'f_719'], ['f_3', 'f_343', 'f_679', 'f_663', 'f_711'], ['f_405', 'f_515', 'f_384', 'f_603', 'f_160'], ['f_181', 'f_159', 'f_418', 'f_229', 'f_394'], ['f_682', 'f_533', 'f_628', 'f_539', 'f_1'], ['f_535', 'f_822', 'f_819', 'f_260', 'f_248'], ['f_180', 'f_398', 'f_543', 'f_629', 'f_166'], ['f_712', 'f_652', 'f_334', 'f_688', 'f_421'], ['f_516', 'f_706', 'f_680', 'f_537', 'f_207'], ['f_439', 'f_465', 'f_585', 'f_595', 'f_668'], ['f_681', 'f_144', 'f_115', 'f_591', 'f_419'], ['f_257', 'f_752', 'f_667', 'f_434', 'f_640'], ['f_646', 'f_301', 'f_538', 'f_507', 'f_575'], ['f_553', 'f_587', 'f_446', 'f_671', 'f_545'], ['f_692', 'f_305', 'f_387', 'f_358', 'f_597'], ['f_337', 'f_34', 'f_443', 'f_349', 'f_432'], ['f_24', 'f_499', 'f_657', 'f_484', 'f_447'], ['f_294', 'f_501', 'f_678', 'f_813', 'f_342'], ['f_579', 'f_388', 'f_776', 'f_770', 'f_347'], ['f_615', 'f_673', 'f_445', 'f_729', 'f_830'], ['f_704', 'f_820', 'f_709', 'f_728', 'f_327'], ['f_567', 'f_400', 'f_608', 'f_589', 'f_485'], ['f_702', 'f_458', 'f_546', 'f_453', 'f_612'], ['f_637', 'f_455', 'f_377', 'f_600', 'f_490'], ['f_818', 'f_755', 'f_524', 'f_710', 'f_179'], ['f_693', 'f_262', 'f_599', 'f_815', 'f_509'], ['f_593', 'f_650', 'f_750', 'f_195', 'f_497'], ['f_199', 'f_243', 'f_756', 'f_618', 'f_644'], ['f_691', 'f_475', 'f_576', 'f_634', 'f_403'], ['f_698', 'f_624', 'f_662', 'f_705', 'f_482'], ['f_686', 'f_734', 'f_256', 'f_261', 'f_845'], ['f_777', 'f_568', 'f_371', 'f_520', 'f_552'], ['f_685', 'f_805', 'f_363', 'f_578', 'f_486'], ['f_642', 'f_383', 'f_472', 'f_450', 'f_547'], ['f_462', 'f_157', 'f_206', 'f_430', 'f_833'], ['f_38', 'f_758', 'f_396', 'f_647', 'f_470'], ['f_797', 'f_518', 'f_716', 'f_722', 'f_194'], ['f_18', 'f_792'], ['f_193', 'f_522', 'f_584', 'f_487', 'f_604'], ['f_581', 'f_500', 'f_506', 'f_738', 'f_259'], ['f_573', 'f_359', 'f_431', 'f_435', 'f_602'], ['f_690', 'f_527', 'f_523', 'f_623', 'f_664'], ['f_353', 'f_721', 'f_530', 'f_565', 'f_389'], ['f_293', 'f_477', 'f_621', 'f_438', 'f_152'], ['f_286', 'f_767', 'f_357', 'f_386', 'f_757'], ['f_21', 'f_742', 'f_564', 'f_153', 'f_364'], ['f_641', 'f_526', 'f_503', 'f_116', 'f_619'], ['f_695', 'f_423', 'f_414', 'f_544'], ['f_666', 'f_397', 'f_491', 'f_362', 'f_493'], ['f_368', 'f_314', 'f_675', 'f_529', 'f_736'], ['f_336', 'f_373', 'f_759'], ['f_150', 'f_558', 'f_788', 'f_367', 'f_799'], ['f_779', 'f_385', 'f_297'], ['f_594', 'f_834', 'f_707', 'f_737', 'f_187'], ['f_713', 'f_258', 'f_800', 'f_521', 'f_559'], ['f_821', 'f_188', 'f_379', 'f_457', 'f_35'], ['f_701', 'f_636', 'f_824', 'f_519', 'f_764'], ['f_550', 'f_513', 'f_488', 'f_866', 'f_782'], ['f_798', 'f_735'], ['f_251', 'f_17', 'f_471', 'f_532', 'f_653'], ['f_714', 'f_429', 'f_448', 'f_831', 'f_635'], ['f_352', 'f_726', 'f_789', 'f_548', 'f_598'], ['f_332', 'f_372', 'f_118', 'f_771'], ['f_687', 'f_551', 'f_30', 'f_661', 'f_563'], ['f_700', 'f_292', 'f_422', 'f_46'], ['f_459', 'f_454', 'f_626', 'f_801', 'f_47'], ['f_605', 'f_827', 'f_725', 'f_164', 'f_328'], ['f_590', 'f_785', 'f_425', 'f_655', 'f_409'], ['f_542', 'f_609', 'f_601', 'f_494', 'f_200'], ['f_13', 'f_378', 'f_22', 'f_31', 'f_436'], ['f_498', 'f_715', 'f_476', 'f_382', 'f_510'], ['f_632', 'f_596', 'f_836', 'f_428'], ['f_620', 'f_504'], ['f_381', 'f_514', 'f_572', 'f_676', 'f_768'], ['f_574', 'f_773', 'f_583', 'f_250', 'f_27'], ['f_694', 'f_803', 'f_417'], ['f_456', 'f_167', 'f_460']]
XofN groups with 2 features: 3
XofN groups with 3 features: 4
XofN groups with 4 features: 5
XofN groups with 5 features: 98
pruning: True, include_original_features: with_org, averageAUROC: 0.5042429, HammingLoss: 0.19656, SubsetAccuracy: 0.12977,
pruning: False, include_original_features: with_org, averageAUROC: 0.5432544, HammingLoss: 0.28372, SubsetAccuracy: 0.045802,
pruning: True, include_original_features: no_org, averageAUROC: 0.5042429, HammingLoss: 0.19656, SubsetAccuracy: 0.12977,
pruning: False, include_original_features: no_org, averageAUROC: 0.56219, HammingLoss: 0.27354, SubsetAccuracy: 0.053435,

Fold 3/10 (fingerprint_all 1/1)

generate_XofN_list -> Generating groupings based on eval_criterion:['averageAUROC', 'HammingLoss', 'SubsetAccuracy'].

🔄 Processing features: 100%|██████████| 540/540 [1:58:05<00:00, 13.12s/feat]

XofN_groups: [['f_374', 'f_515', 'f_464', 'f_683', 'f_332'], ['f_20', 'f_328', 'f_573', 'f_11', 'f_564'], ['f_308', 'f_343', 'f_9', 'f_452', 'f_366'], ['f_346', 'f_361', 'f_344', 'f_719', 'f_509'], ['f_23', 'f_624', 'f_340', 'f_592', 'f_416'], ['f_335', 'f_395', 'f_15', 'f_437', 'f_582'], ['f_391', 'f_300', 'f_442', 'f_441', 'f_740'], ['f_287', 'f_394', 'f_0', 'f_644', 'f_569'], ['f_2', 'f_467', 'f_449', 'f_375', 'f_202'], ['f_656', 'f_454', 'f_518', 'f_611', 'f_285'], ['f_571', 'f_31', 'f_43', 'f_13', 'f_10'], ['f_299', 'f_213', 'f_633', 'f_510', 'f_664'], ['f_392', 'f_820', 'f_431', 'f_716', 'f_709'], ['f_24', 'f_685', 'f_549', 'f_370', 'f_438'], ['f_672', 'f_840', 'f_333', 'f_195', 'f_143'], ['f_566', 'f_398', 'f_351', 'f_696', 'f_679'], ['f_338', 'f_609', 'f_283'], ['f_406', 'f_129', 'f_640', 'f_667', 'f_556'], ['f_643', 'f_588', 'f_16', 'f_607', 'f_19'], ['f_697', 'f_514', 'f_553', 'f_704', 'f_533'], ['f_393', 'f_517', 'f_418', 'f_613', 'f_812'], ['f_440', 'f_489', 'f_618', 'f_14', 'f_706'], ['f_380', 'f_284', 'f_742', 'f_186', 'f_476'], ['f_3', 'f_784', 'f_145', 'f_695', 'f_390'], ['f_185', 'f_558', 'f_356', 'f_635', 'f_376'], ['f_516', 'f_229', 'f_682', 'f_255', 'f_355'], ['f_12', 'f_789', 'f_570', 'f_33', 'f_531'], ['f_192', 'f_834', 'f_540', 'f_657', 'f_511'], ['f_617', 'f_839', 'f_388', 'f_38', 'f_118'], ['f_639', 'f_758', 'f_538', 'f_470', 'f_131'], ['f_339', 'f_132', 'f_443', 'f_216', 'f_497'], ['f_528', 'f_631', 'f_446', 'f_735', 'f_359'], ['f_614', 'f_455', 'f_826', 'f_357', 'f_358'], ['f_146', 'f_752', 'f_608', 'f_499', 'f_349'], ['f_405', 'f_522', 'f_595', 'f_160', 'f_768'], ['f_712', 'f_805', 'f_819', 'f_513', 'f_477'], ['f_659', 'f_788', 'f_603', 'f_365', 'f_292'], ['f_451', 'f_831', 'f_383', 'f_526', 'f_703'], ['f_341', 'f_419', 'f_599', 'f_434', 'f_726'], ['f_181', 'f_230', 'f_552', 'f_408', 'f_345'], ['f_180', 'f_159', 'f_555', 'f_585', 'f_676'], ['f_37', 'f_144', 'f_551', 'f_430', 'f_420'], ['f_579', 'f_778', 'f_506', 'f_665', 'f_539'], ['f_257', 'f_401', 'f_384'], ['f_638', 'f_475', 'f_578', 'f_691', 'f_529'], ['f_535', 'f_725', 'f_520', 'f_493', 'f_490'], ['f_248', 'f_527', 'f_542', 'f_708', 'f_749'], ['f_637', 'f_47', 'f_178'], ['f_699', 'f_399', 'f_777', 'f_545', 'f_21'], ['f_684', 'f_473', 'f_502', 'f_568', 'f_836'], ['f_439', 'f_736', 'f_377', 'f_813', 'f_773'], ['f_567', 'f_400', 'f_314', 'f_677', 'f_668'], ['f_681', 'f_763', 'f_815'], ['f_646', 'f_799', 'f_771', 'f_600', 'f_188'], ['f_645', 'f_610', 'f_584', 'f_227'], ['f_615', 'f_821', 'f_523', 'f_728', 'f_559'], ['f_698', 'f_866', 'f_241', 'f_705', 'f_801'], ['f_686', 'f_601', 'f_628', 'f_215', 'f_575'], ['f_199', 'f_652', 'f_580', 'f_634', 'f_153'], ['f_663', 'f_546', 'f_371', 'f_386', 'f_486'], ['f_692', 'f_474', 'f_453', 'f_711', 'f_593'], ['f_690', 'f_243', 'f_576', 'f_707', 'f_258'], ['f_337', 'f_397', 'f_1', 'f_738', 'f_845'], ['f_693', 'f_782', 'f_688', 'f_689', 'f_798'], ['f_671', 'f_423', 'f_647', 'f_678', 'f_336'], ['f_776', 'f_722', 'f_710', 'f_655', 'f_508'], ['f_619', 'f_616', 'f_654', 'f_378', 'f_496'], ['f_818', 'f_260', 'f_797', 'f_34', 'f_18'], ['f_353', 'f_625', 'f_422', 'f_623', 'f_694'], ['f_193', 'f_483', 'f_495', 'f_756', 'f_256'], ['f_26', 'f_597', 'f_286', 'f_214', 'f_251'], ['f_150', 'f_459', 'f_259', 'f_261', 'f_759'], ['f_462', 'f_157', 'f_675', 'f_824', 'f_687'], ['f_293', 'f_822', 'f_504', 'f_194', 'f_622'], ['f_581', 'f_364', 'f_387', 'f_530', 'f_411'], ['f_432', 'f_591', 'f_179', 'f_262', 'f_25'], ['f_294', 'f_362', 'f_327', 'f_598', 'f_785'], ['f_642', 'f_305', 'f_560', 'f_650', 'f_450'], ['f_713', 'f_187', 'f_301', 'f_770', 'f_803'], ['f_702', 'f_494', 'f_673', 'f_755', 'f_363'], ['f_680', 'f_46'], ['f_602', 'f_621', 'f_389', 'f_653', 'f_487'], ['f_662', 'f_488', 'f_524', 'f_830', 'f_298'], ['f_537', 'f_717', 'f_409', 'f_670', 'f_164'], ['f_244', 'f_630', 'f_715', 'f_660', 'f_456'], ['f_536', 'f_791', 'f_151', 'f_27', 'f_482'], ['f_641', 'f_554'], ['f_334', 'f_152', 'f_714', 'f_583', 'f_385'], ['f_342', 'f_501'], ['f_586', 'f_503', 'f_445', 'f_596', 'f_396'], ['f_368', 'f_701', 'f_750'], ['f_779', 'f_577', 'f_350', 'f_461', 'f_407'], ['f_734', 'f_472', 'f_347', 'f_460'], ['f_594', 'f_547', 'f_574', 'f_636', 'f_379'], ['f_249', 'f_780', 'f_17', 'f_382', 'f_429'], ['f_548', 'f_587', 'f_737', 'f_572', 'f_30'], ['f_550', 'f_860', 'f_543', 'f_605'], ['f_507', 'f_466', 'f_800', 'f_250', 'f_532'], ['f_458', 'f_471', 'f_242', 'f_35'], ['f_666', 'f_485'], ['f_115', 'f_425', 'f_414', 'f_166', 'f_448'], ['f_658', 'f_700', 'f_403', 'f_207', 'f_436'], ['f_590', 'f_116', 'f_200'], ['f_412', 'f_563', 'f_421', 'f_413', 'f_729'], ['f_612', 'f_457', 'f_381', 'f_480', 'f_500'], ['f_606', 'f_757'], ['f_206', 'f_827', 'f_330', 'f_367', 'f_428'], ['f_519', 'f_417'], ['f_447', 'f_861'], ['f_541', 'f_767', 'f_297'], ['f_661', 'f_465', 'f_167'], ['f_674', 'f_427', 'f_521', 'f_373'], ['f_22', 'f_761'], ['f_372', 'f_721'], ['f_484', 'f_792']]
XofN groups with 2 features: 10
XofN groups with 3 features: 8
XofN groups with 4 features: 5
XofN groups with 5 features: 92
pruning: True, include_original_features: with_org, averageAUROC: 0.5279719, HammingLoss: 0.19275, SubsetAccuracy: 0.1374,
pruning: False, include_original_features: with_org, averageAUROC: 0.5743234, HammingLoss: 0.24873, SubsetAccuracy: 0.053435,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.19466, SubsetAccuracy: 0.12977,
pruning: False, include_original_features: no_org, averageAUROC: 0.5952291, HammingLoss: 0.24682, SubsetAccuracy: 0.068702,

Fold 4/10 (fingerprint_all 1/1)

generate_XofN_list -> Generating groupings based on eval_criterion:['averageAUROC', 'HammingLoss', 'SubsetAccuracy'].

🔄 Processing features: 100%|██████████| 540/540 [2:00:29<00:00, 13.39s/feat]

XofN_groups: [['f_374', 'f_644', 'f_332', 'f_459', 'f_345'], ['f_20', 'f_812', 'f_365', 'f_592', 'f_284'], ['f_308', 'f_826', 'f_153'], ['f_346', 'f_554', 'f_10', 'f_446', 'f_831'], ['f_366', 'f_229', 'f_9', 'f_466', 'f_726'], ['f_2', 'f_455', 'f_420', 'f_712', 'f_483'], ['f_656', 'f_132', 'f_391', 'f_0', 'f_215'], ['f_406', 'f_815', 'f_667', 'f_26', 'f_407'], ['f_287', 'f_861', 'f_1', 'f_818', 'f_15'], ['f_639', 'f_159', 'f_359', 'f_129', 'f_613'], ['f_335', 'f_784', 'f_585', 'f_285', 'f_513'], ['f_643', 'f_635', 'f_451', 'f_351', 'f_646'], ['f_697', 'f_467', 'f_143', 'f_696', 'f_654'], ['f_571', 'f_559', 'f_566', 'f_339', 'f_328'], ['f_392', 'f_515', 'f_698', 'f_443', 'f_523'], ['f_338', 'f_558', 'f_390', 'f_305', 'f_624'], ['f_516', 'f_343', 'f_262', 'f_27', 'f_405'], ['f_186', 'f_834', 'f_11', 'f_535', 'f_820'], ['f_23', 'f_242', 'f_178', 'f_777', 'f_145'], ['f_12', 'f_131', 'f_393', 'f_395', 'f_146'], ['f_380', 'f_401', 'f_545', 'f_14', 'f_116'], ['f_452', 'f_38', 'f_551', 'f_621', 'f_650'], ['f_672', 'f_334', 'f_681', 'f_436', 'f_845'], ['f_528', 'f_839'], ['f_659', 'f_631', 'f_439', 'f_22', 'f_501'], ['f_617', 'f_749', 'f_340', 'f_637', 'f_509'], ['f_440', 'f_752', 'f_785', 'f_771', 'f_866'], ['f_299', 'f_494', 'f_438', 'f_195', 'f_588'], ['f_192', 'f_115', 'f_601', 'f_553', 'f_248'], ['f_3', 'f_822', 'f_568', 'f_416', 'f_641'], ['f_19', 'f_409', 'f_540', 'f_597', 'f_378'], ['f_614', 'f_429', 'f_678', 'f_529', 'f_693'], ['f_185', 'f_518', 'f_611', 'f_645', 'f_622'], ['f_257', 'f_35', 'f_547', 'f_569', 'f_344'], ['f_24', 'f_593', 'f_216', 'f_758', 'f_206'], ['f_181', 'f_227', 'f_683', 'f_413'], ['f_638', 'f_301', 'f_628', 'f_448', 'f_194'], ['f_341', 'f_725', 'f_679', 'f_31', 'f_573'], ['f_180', 'f_230', 'f_821', 'f_612', 'f_461'], ['f_682', 'f_706', 'f_16', 'f_625', 'f_377'], ['f_37', 'f_347', 'f_602', 'f_788', 'f_598'], ['f_704', 'f_489', 'f_750', 'f_470', 'f_428'], ['f_615', 'f_249', 'f_286', 'f_46', 'f_773'], ['f_686', 'f_717', 'f_675', 'f_350', 'f_813'], ['f_685', 'f_422', 'f_673', 'f_437', 'f_460'], ['f_337', 'f_487', 'f_579', 'f_372', 'f_705'], ['f_567', 'f_260', 'f_824', 'f_711', 'f_488'], ['f_464', 'f_670', 'f_618', 'f_255', 'f_118'], ['f_692', 'f_300', 'f_536', 'f_355', 'f_688'], ['f_776', 'f_394', 'f_179', 'f_836', 'f_352'], ['f_684', 'f_423', 'f_356', 'f_689', 'f_388'], ['f_699', 'f_398', 'f_480', 'f_833', 'f_241'], ['f_690', 'f_496', 'f_572', 'f_361', 'f_202'], ['f_663', 'f_486', 'f_629', 'f_18', 'f_418'], ['f_432', 'f_580', 'f_582', 'f_495', 'f_549'], ['f_671', 'f_144', 'f_708'], ['f_199', 'f_454', 'f_431', 'f_364', 'f_152'], ['f_33', 'f_780', 'f_485', 'f_560', 'f_333'], ['f_213', 'f_244', 'f_336', 'f_258', 'f_768'], ['f_691', 'f_616', 'f_657', 'f_729', 'f_789'], ['f_581', 'f_397', 'f_674', 'f_596', 'f_695'], ['f_537', 'f_157', 'f_709', 'f_297', 'f_526'], ['f_462', 'f_447', 'f_605', 'f_522', 'f_445'], ['f_294', 'f_591'], ['f_713', 'f_860', 'f_759', 'f_710', 'f_47'], ['f_702', 'f_543', 'f_376', 'f_548', 'f_587'], ['f_293', 'f_791', 'f_449', 'f_610', 'f_583'], ['f_642', 'f_658', 'f_453', 'f_497', 'f_427'], ['f_349', 'f_342', 'f_435', 'f_636', 'f_757'], ['f_680', 'f_510', 'f_441', 'f_640'], ['f_259', 'f_477', 'f_609'], ['f_755', 'f_517', 'f_600', 'f_357', 'f_792'], ['f_193', 'f_716', 'f_386', 'f_457', 'f_511'], ['f_662', 'f_400', 'f_21', 'f_736', 'f_715'], ['f_188', 'f_417', 'f_442', 'f_475', 'f_799'], ['f_502', 'f_546'], ['f_368', 'f_25', 'f_430', 'f_770', 'f_484'], ['f_666', 'f_473', 'f_521', 'f_664', 'f_472'], ['f_375', 'f_653', 'f_735', 'f_700', 'f_719'], ['f_797', 'f_160', 'f_298', 'f_408', 'f_419'], ['f_493', 'f_533'], ['f_150', 'f_742', 'f_665', 'f_539', 'f_500'], ['f_701', 'f_214', 'f_676'], ['f_623', 'f_207', 'f_474', 'f_763', 'f_538'], ['f_779', 'f_734', 'f_633', 'f_370', 'f_371'], ['f_550', 'f_687', 'f_503', 'f_367', 'f_840'], ['f_450', 'f_819', 'f_519'], ['f_243', 'f_362', 'f_396', 'f_668', 'f_403'], ['f_363', 'f_421', 'f_778', 'f_577', 'f_514'], ['f_251', 'f_647', 'f_506', 'f_384', 'f_256'], ['f_458', 'f_187', 'f_721'], ['f_798', 'f_738', 'f_414', 'f_740', 'f_471'], ['f_707', 'f_399', 'f_703', 'f_151'], ['f_555', 'f_767', 'f_532', 'f_576', 'f_465'], ['f_655', 'f_728', 'f_373', 'f_570', 'f_387'], ['f_590', 'f_722', 'f_584', 'f_574'], ['f_714', 'f_30', 'f_634', 'f_434'], ['f_13', 'f_330', 'f_595', 'f_801', 'f_608'], ['f_200', 'f_761', 'f_756', 'f_389'], ['f_694', 'f_661'], ['f_563', 'f_805', 'f_43', 'f_504', 'f_17'], ['f_544', 'f_491'], ['f_283', 'f_482', 'f_603', 'f_499', 'f_652'], ['f_166', 'f_167']]
XofN groups with 2 features: 7
XofN groups with 3 features: 6
XofN groups with 4 features: 6
XofN groups with 5 features: 85
pruning: True, include_original_features: with_org, averageAUROC: 0.5164652, HammingLoss: 0.18193, SubsetAccuracy: 0.091603,
pruning: False, include_original_features: with_org, averageAUROC: 0.5644893, HammingLoss: 0.28372, SubsetAccuracy: 0.030534,
pruning: True, include_original_features: no_org, averageAUROC: 0.5153782, HammingLoss: 0.18257, SubsetAccuracy: 0.091603,
pruning: False, include_original_features: no_org, averageAUROC: 0.5392226, HammingLoss: 0.29071, SubsetAccuracy: 0.030534,

Fold 5/10 (fingerprint_all 1/1)

generate_XofN_list -> Generating groupings based on eval_criterion:['averageAUROC', 'HammingLoss', 'SubsetAccuracy'].

🔄 Processing features: 100%|██████████| 540/540 [2:02:40<00:00, 13.63s/feat]

XofN_groups: [['f_374', 'f_515', 'f_570', 'f_345', 'f_397'], ['f_20', 'f_361', 'f_328', 'f_413', 'f_10'], ['f_308', 'f_38', 'f_0', 'f_118', 'f_820'], ['f_23', 'f_284', 'f_367', 'f_14', 'f_255'], ['f_15', 'f_129', 'f_332', 'f_706', 'f_427'], ['f_346', 'f_839', 'f_9', 'f_554', 'f_729'], ['f_287', 'f_485', 'f_365', 'f_355', 'f_560'], ['f_366', 'f_343', 'f_344', 'f_815', 'f_752'], ['f_697', 'f_131', 'f_393', 'f_569'], ['f_406', 'f_831', 'f_640', 'f_333', 'f_726'], ['f_2', 'f_132', 'f_370', 'f_451', 'f_1'], ['f_299', 'f_215', 'f_390', 'f_195', 'f_283'], ['f_656', 'f_588', 'f_692', 'f_489', 'f_457'], ['f_335', 'f_833', 'f_420', 'f_12', 'f_616'], ['f_338', 'f_213', 'f_391', 'f_473', 'f_629'], ['f_571', 'f_780', 'f_696', 'f_650', 'f_416'], ['f_614', 'f_860', 'f_11', 'f_675', 'f_178'], ['f_566', 'f_216', 'f_439', 'f_465', 'f_417'], ['f_617', 'f_799', 'f_430', 'f_143', 'f_688'], ['f_672', 'f_144', 'f_334', 'f_582', 'f_349'], ['f_19', 'f_518', 'f_540', 'f_683', 'f_419'], ['f_405', 'f_475', 'f_634', 'f_447', 'f_387'], ['f_440', 'f_658', 'f_613', 'f_624', 'f_580'], ['f_452', 'f_301', 'f_351', 'f_602', 'f_805'], ['f_639', 'f_840', 'f_709', 'f_480', 'f_509'], ['f_380', 'f_394', 'f_285', 'f_441', 'f_592'], ['f_392', 'f_395', 'f_340', 'f_659', 'f_510'], ['f_643', 'f_454', 'f_593', 'f_523', 'f_713'], ['f_3', 'f_551', 'f_446', 'f_663', 'f_501'], ['f_185', 'f_300', 'f_356', 'f_470', 'f_812'], ['f_516', 'f_558', 'f_538', 'f_243', 'f_464'], ['f_339', 'f_722', 'f_443', 'f_409', 'f_719'], ['f_186', 'f_517', 'f_549', 'f_384', 'f_734'], ['f_146', 'f_363', 'f_379', 'f_611', 'f_552'], ['f_192', 'f_522', 'f_16', 'f_644', 'f_407'], ['f_257', 'f_398', 'f_607', 'f_563', 'f_758'], ['f_528', 'f_676', 'f_145', 'f_575', 'f_778'], ['f_181', 'f_647', 'f_418', 'f_202', 'f_350'], ['f_180', 'f_347', 'f_453', 'f_514', 'f_595'], ['f_341', 'f_229', 'f_249', 'f_408', 'f_535'], ['f_37', 'f_242', 'f_689', 'f_25', 'f_670'], ['f_712', 'f_459', 'f_530', 'f_711', 'f_555'], ['f_667', 'f_497', 'f_442', 'f_449', 'f_115'], ['f_638', 'f_423', 'f_673', 'f_531', 'f_597'], ['f_682', 'f_749', 'f_437', 'f_628', 'f_715'], ['f_24', 'f_357', 'f_414', 'f_431', 'f_358'], ['f_681', 'f_160', 'f_710', 'f_327', 'f_568'], ['f_699', 'f_152', 'f_797', 'f_386', 'f_587'], ['f_637', 'f_214', 'f_556', 'f_241', 'f_742'], ['f_33', 'f_625', 'f_584', 'f_704', 'f_18'], ['f_645', 'f_610', 'f_256', 'f_371', 'f_428'], ['f_615', 'f_694', 'f_520', 'f_559', 'f_352'], ['f_646', 'f_586', 'f_553', 'f_621', 'f_286'], ['f_686', 'f_378', 'f_375', 'f_608', 'f_305'], ['f_684', 'f_429', 'f_564', 'f_845', 'f_474'], ['f_567', 'f_159', 'f_668', 'f_768', 'f_792'], ['f_691', 'f_483', 'f_545', 'f_502', 'f_388'], ['f_248', 'f_622', 'f_35', 'f_708', 'f_511'], ['f_579', 'f_466', 'f_664', 'f_377', 'f_738'], ['f_698', 'f_438', 'f_677', 'f_450', 'f_461'], ['f_337', 'f_373', 'f_536', 'f_432', 'f_693'], ['f_199', 'f_507', 'f_633', 'f_524', 'f_789'], ['f_294', 'f_448', 'f_330', 'f_861', 'f_782'], ['f_818', 'f_34', 'f_777', 'f_707', 'f_770'], ['f_776', 'f_601', 'f_572', 'f_496', 'f_785'], ['f_671', 'f_368', 'f_153', 'f_150', 'f_705'], ['f_353', 'f_661', 'f_187', 'f_376', 'f_500'], ['f_690', 'f_292', 'f_227', 'f_578', 'f_460'], ['f_702', 'f_359', 'f_546', 'f_206', 'f_821'], ['f_537', 'f_13', 'f_456', 'f_599', 'f_757'], ['f_685', 'f_803', 'f_383', 'f_603'], ['f_680', 'f_609', 'f_679', 'f_539', 'f_472'], ['f_642', 'f_116', 'f_445', 'f_532', 'f_618'], ['f_21', 'f_230', 'f_662', 'f_403', 'f_506'], ['f_581', 'f_826', 'f_482', 'f_399', 'f_527'], ['f_462', 'f_157', 'f_678', 'f_740', 'f_714'], ['f_293', 'f_813', 'f_577', 'f_533', 'f_194'], ['f_193', 'f_784', 'f_396', 'f_244', 'f_695'], ['f_26', 'f_259', 'f_477', 'f_600', 'f_188'], ['f_342', 'f_400', 'f_487', 'f_494', 'f_827'], ['f_493', 'f_822', 'f_425', 'f_495'], ['f_623', 'f_834', 'f_262', 'f_657'], ['f_755', 'f_513', 'f_260', 'f_576', 'f_791'], ['f_251', 'f_412', 'f_585', 'f_830', 'f_703'], ['f_641', 'f_31', 'f_491', 'f_490', 'f_30'], ['f_701', 'f_250', 'f_660', 'f_771', 'f_655'], ['f_798', 'f_499', 'f_759', 'f_596', 'f_717'], ['f_779', 'f_258', 'f_665', 'f_716', 'f_336'], ['f_687', 'f_764', 'f_200', 'f_866', 'f_43'], ['f_654', 'f_467', 'f_435', 'f_652', 'f_504'], ['f_700', 'f_543', 'f_612', 'f_521', 'f_471'], ['f_819', 'f_207', 'f_298', 'f_728', 'f_17'], ['f_605', 'f_261', 'f_737', 'f_411', 'f_788'], ['f_590', 'f_47', 'f_767', 'f_27'], ['f_591', 'f_547', 'f_434', 'f_750', 'f_22'], ['f_800', 'f_422', 'f_519', 'f_458', 'f_372'], ['f_735', 'f_364', 'f_488', 'f_486'], ['f_756', 'f_736', 'f_484', 'f_46'], ['f_179', 'f_773'], ['f_385', 'f_635', 'f_725', 'f_836', 'f_674'], ['f_824', 'f_544', 'f_653', 'f_526', 'f_529'], ['f_631', 'f_763'], ['f_721', 'f_421', 'f_166', 'f_630', 'f_436'], ['f_151', 'f_164']]
XofN groups with 2 features: 3
XofN groups with 4 features: 7
XofN groups with 5 features: 94
pruning: True, include_original_features: with_org, averageAUROC: 0.5109767, HammingLoss: 0.21247, SubsetAccuracy: 0.091603,
pruning: False, include_original_features: with_org, averageAUROC: 0.5475677, HammingLoss: 0.29517, SubsetAccuracy: 0.038168,
pruning: True, include_original_features: no_org, averageAUROC: 0.5109767, HammingLoss: 0.21247, SubsetAccuracy: 0.091603,
pruning: False, include_original_features: no_org, averageAUROC: 0.5831609, HammingLoss: 0.27036, SubsetAccuracy: 0.022901,

Fold 6/10 (fingerprint_all 1/1)

generate_XofN_list -> Generating groupings based on eval_criterion:['averageAUROC', 'HammingLoss', 'SubsetAccuracy'].

🔄 Processing features: 100%|██████████| 540/540 [2:03:04<00:00, 13.68s/feat]

XofN_groups: [['f_374', 'f_489', 'f_420', 'f_588', 'f_540'], ['f_20', 'f_494', 'f_571', 'f_621', 'f_9'], ['f_23', 'f_394', 'f_592', 'f_713', 'f_243'], ['f_308', 'f_812', 'f_380', 'f_10', 'f_283'], ['f_366', 'f_568', 'f_333', 'f_518', 'f_771'], ['f_346', 'f_522', 'f_284', 'f_229', 'f_614'], ['f_406', 'f_587', 'f_0', 'f_344', 'f_132'], ['f_287', 'f_300', 'f_685', 'f_656', 'f_803'], ['f_186', 'f_515', 'f_338', 'f_345', 'f_805'], ['f_2', 'f_25', 'f_569', 'f_299', 'f_517'], ['f_192', 'f_815', 'f_696', 'f_682', 'f_398'], ['f_3', 'f_131', 'f_625', 'f_633', 'f_436'], ['f_697', 'f_401', 'f_422', 'f_549', 'f_564'], ['f_617', 'f_483', 'f_582', 'f_129', 'f_202'], ['f_19', 'f_285', 'f_328', 'f_393', 'f_683'], ['f_672', 'f_337', 'f_441', 'f_151', 'f_709'], ['f_566', 'f_408', 'f_340', 'f_643'], ['f_392', 'f_395', 'f_611', 'f_418', 'f_146'], ['f_15', 'f_213', 'f_145', 'f_1', 'f_351'], ['f_452', 'f_409', 'f_365', 'f_477', 'f_440'], ['f_335', 'f_716', 'f_555', 'f_143', 'f_679'], ['f_181', 'f_706', 'f_446', 'f_712', 'f_613'], ['f_12', 'f_215', 'f_646', 'f_353', 'f_301'], ['f_391', 'f_467', 'f_665', 'f_390', 'f_230'], ['f_339', 'f_359', 'f_443', 'f_496', 'f_530'], ['f_659', 'f_216', 'f_642', 'f_430', 'f_343'], ['f_37', 'f_471', 'f_259', 'f_356', 'f_187'], ['f_528', 'f_227', 'f_576', 'f_457', 'f_487'], ['f_180', 'f_486', 'f_657', 'f_756', 'f_442'], ['f_516', 'f_455', 'f_355', 'f_416', 'f_660'], ['f_185', 'f_361', 'f_839', 'f_785', 'f_11'], ['f_257', 'f_729', 'f_536', 'f_43', 'f_728'], ['f_405', 'f_160', 'f_607', 'f_14', 'f_510'], ['f_24', 'f_16', 'f_558', 'f_616', 'f_194'], ['f_639', 'f_244', 'f_597', 'f_178', 'f_438'], ['f_451', 'f_658', 'f_581', 'f_570', 'f_602'], ['f_341', 'f_820', 'f_464', 'f_255', 'f_465'], ['f_33', 'f_514', 'f_593', 'f_740', 'f_635'], ['f_535', 'f_475', 'f_437', 'f_453', 'f_674'], ['f_667', 'f_719', 'f_371', 'f_752', 'f_590'], ['f_638', 'f_644', 'f_375', 'f_480', 'f_653'], ['f_439', 'f_788', 'f_600', 'f_383', 'f_377'], ['f_681', 'f_779', 'f_688', 'f_352', 'f_460'], ['f_199', 'f_652', 'f_545', 'f_692', 'f_826'], ['f_579', 'f_830', 'f_520', 'f_293'], ['f_294', 'f_249', 'f_710', 'f_698', 'f_797'], ['f_637', 'f_725', 'f_490', 'f_640', 'f_834'], ['f_248', 'f_159', 'f_699', 'f_708', 'f_206'], ['f_663', 'f_152', 'f_449', 'f_538', 'f_150'], ['f_684', 'f_533', 'f_628', 'f_493', 'f_750'], ['f_690', 'f_419', 'f_286', 'f_543', 'f_715'], ['f_645', 'f_454', 'f_664', 'f_153', 'f_256'], ['f_704', 'f_473', 'f_376', 'f_671', 'f_373'], ['f_553', 'f_767', 'f_370', 'f_618', 'f_603'], ['f_686', 'f_711', 'f_662', 'f_556', 'f_722'], ['f_615', 'f_673', 'f_546', 'f_619', 'f_693'], ['f_776', 'f_458', 'f_434', 'f_386', 'f_529'], ['f_334', 'f_21', 'f_539', 'f_193', 'f_578'], ['f_691', 'f_298', 'f_831', 'f_511', 'f_262'], ['f_432', 'f_349', 'f_358', 'f_563', 'f_678'], ['f_567', 'f_399', 'f_734', 'f_387', 'f_599'], ['f_18', 'f_526', 'f_470', 'f_654', 'f_677'], ['f_573', 'f_768', 'f_384', 'f_641', 'f_524'], ['f_537', 'f_157', 'f_824', 'f_26', 'f_759'], ['f_818', 'f_583', 'f_179', 'f_580', 'f_200'], ['f_241', 'f_738', 'f_552', 'f_585', 'f_742'], ['f_702', 'f_531', 'f_623', 'f_547', 'f_821'], ['f_462', 'f_551', 'f_35', 'f_428', 'f_845'], ['f_777', 'f_115', 'f_836', 'f_789'], ['f_342', 'f_586', 'f_397', 'f_559'], ['f_368', 'f_31', 'f_780', 'f_450', 'f_482'], ['f_755', 'f_459', 'f_595', 'f_513', 'f_773'], ['f_695', 'f_305', 'f_608', 'f_495', 'f_414'], ['f_594', 'f_770', 'f_634', 'f_485', 'f_17'], ['f_188', 'f_527', 'f_431', 'f_258', 'f_721'], ['f_38', 'f_412', 'f_396', 'f_503', 'f_575'], ['f_666', 'f_833', 'f_668', 'f_499', 'f_167'], ['f_560', 'f_609', 'f_523', 'f_799', 'f_757'], ['f_336', 'f_357', 'f_577', 'f_532', 'f_502'], ['f_701', 'f_407', 'f_488', 'f_778'], ['f_819', 'f_506', 'f_584', 'f_574'], ['f_363', 'f_364', 'f_612', 'f_400', 'f_792'], ['f_705', 'f_505', 'f_367', 'f_13', 'f_620'], ['f_800', 'f_500', 'f_801', 'f_736'], ['f_591', 'f_749', 'f_737', 'f_421', 'f_508'], ['f_636', 'f_144', 'f_27', 'f_260', 'f_764'], ['f_550', 'f_417', 'f_548', 'f_670', 'f_650'], ['f_251', 'f_840', 'f_22', 'f_214'], ['f_758', 'f_423', 'f_474', 'f_388', 'f_195'], ['f_655', 'f_676', 'f_694', 'f_501', 'f_735'], ['f_798', 'f_763', 'f_707', 'f_629'], ['f_332', 'f_118', 'f_30', 'f_861', 'f_509'], ['f_34', 'f_703', 'f_860', 'f_466'], ['f_261', 'f_605', 'f_601', 'f_250', 'f_507'], ['f_714', 'f_242'], ['f_700', 'f_624', 'f_47', 'f_791', 'f_403'], ['f_385', 'f_429', 'f_411', 'f_447', 'f_472'], ['f_445', 'f_822', 'f_596', 'f_631', 'f_330'], ['f_687', 'f_827', 'f_661', 'f_46', 'f_717'], ['f_519', 'f_116', 'f_491', 'f_378', 'f_726'], ['f_598', 'f_362'], ['f_425', 'f_347', 'f_389', 'f_461', 'f_497'], ['f_435', 'f_813', 'f_521'], ['f_647', 'f_484', 'f_372', 'f_448', 'f_784'], ['f_379', 'f_427'], ['f_610', 'f_207', 'f_297', 'f_630'], ['f_572', 'f_504'], ['f_782', 'f_622', 'f_164', 'f_675', 'f_866']]
XofN groups with 2 features: 4
XofN groups with 3 features: 1
XofN groups with 4 features: 11
XofN groups with 5 features: 92
pruning: True, include_original_features: with_org, averageAUROC: 0.5, HammingLoss: 0.19656, SubsetAccuracy: 0.12977,
pruning: False, include_original_features: with_org, averageAUROC: 0.5613952, HammingLoss: 0.26145, SubsetAccuracy: 0.099237,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.19656, SubsetAccuracy: 0.12977,
pruning: False, include_original_features: no_org, averageAUROC: 0.5535381, HammingLoss: 0.28562, SubsetAccuracy: 0.038168,

Fold 7/10 (fingerprint_all 1/1)

generate_XofN_list -> Generating groupings based on eval_criterion:['averageAUROC', 'HammingLoss', 'SubsetAccuracy'].

🔄 Processing features: 100%|██████████| 540/540 [2:07:03<00:00, 14.12s/feat]

XofN_groups: [['f_374', 'f_401', 'f_618', 'f_600', 'f_486'], ['f_20', 'f_216', 'f_592', 'f_14', 'f_227'], ['f_23', 'f_344', 'f_15', 'f_432', 'f_11'], ['f_346', 'f_361', 'f_9', 'f_413', 'f_460'], ['f_308', 'f_132', 'f_599', 'f_25', 'f_629'], ['f_406', 'f_230', 'f_490', 'f_510', 'f_446'], ['f_366', 'f_840', 'f_10', 'f_178', 'f_679'], ['f_287', 'f_499', 'f_416', 'f_388', 'f_588'], ['f_2', 'f_436', 'f_286', 'f_284'], ['f_656', 'f_398', 'f_299', 'f_697', 'f_791'], ['f_451', 'f_830', 'f_607', 'f_683', 'f_393'], ['f_335', 'f_839', 'f_249', 'f_13', 'f_465'], ['f_571', 'f_706', 'f_634', 'f_355', 'f_43'], ['f_672', 'f_38', 'f_441', 'f_694', 'f_516'], ['f_19', 'f_664', 'f_357', 'f_414', 'f_513'], ['f_391', 'f_511', 'f_431', 'f_370', 'f_442'], ['f_338', 'f_423', 'f_392', 'f_283', 'f_676'], ['f_617', 'f_129', 'f_556', 'f_644', 'f_466'], ['f_643', 'f_455', 'f_709', 'f_371', 'f_749'], ['f_566', 'f_522', 'f_735', 'f_255', 'f_526'], ['f_639', 'f_860', 'f_822', 'f_356', 'f_660'], ['f_339', 'f_343', 'f_1', 'f_409', 'f_773'], ['f_3', 'f_827', 'f_434', 'f_797', 'f_397'], ['f_405', 'f_473', 'f_677', 'f_482', 'f_584'], ['f_528', 'f_395', 'f_375', 'f_332', 'f_834'], ['f_185', 'f_131', 'f_285', 'f_613', 'f_646'], ['f_614', 'f_488', 'f_179', 'f_429', 'f_384'], ['f_186', 'f_861', 'f_626', 'f_430', 'f_143'], ['f_452', 'f_725', 'f_351', 'f_524', 'f_487'], ['f_380', 'f_788', 'f_390', 'f_560', 'f_608'], ['f_440', 'f_215', 'f_688', 'f_533', 'f_570'], ['f_24', 'f_577', 'f_475', 'f_180', 'f_540'], ['f_12', 'f_767', 'f_502', 'f_449', 'f_582'], ['f_181', 'f_647', 'f_545', 'f_654', 'f_365'], ['f_712', 'f_729', 'f_710', 'f_408', 'f_394'], ['f_341', 'f_715', 'f_628', 'f_564', 'f_583'], ['f_345', 'f_726', 'f_668', 'f_579', 'f_453'], ['f_192', 'f_543', 'f_256', 'f_708', 'f_387'], ['f_638', 'f_568', 'f_578', 'f_603', 'f_538'], ['f_659', 'f_616', 'f_585', 'f_418', 'f_736'], ['f_146', 'f_428', 'f_698', 'f_818', 'f_813'], ['f_696', 'f_467', 'f_728', 'f_396', 'f_569'], ['f_420', 'f_866', 'f_711', 'f_386', 'f_333'], ['f_257', 'f_213', 'f_438', 'f_595', 'f_657'], ['f_439', 'f_457', 'f_552', 'f_609', 'f_494'], ['f_535', 'f_497', 'f_681', 'f_399', 'f_701'], ['f_682', 'f_292', 'f_778'], ['f_443', 'f_529', 'f_470', 'f_520', 'f_632'], ['f_340', 'f_454', 'f_153', 'f_580', 'f_363'], ['f_667', 'f_250', 'f_678', 'f_836'], ['f_686', 'f_118', 'f_241', 'f_640', 'f_716'], ['f_37', 'f_334', 'f_819', 'f_671', 'f_826'], ['f_33', 'f_625', 'f_555', 'f_761', 'f_612'], ['f_663', 'f_546', 'f_498', 'f_350', 'f_214'], ['f_692', 'f_242', 'f_248', 'f_591', 'f_506'], ['f_699', 'f_485', 'f_611', 'f_305', 'f_358'], ['f_464', 'f_47', 'f_655', 'f_833', 'f_523'], ['f_567', 'f_400', 'f_437', 'f_495', 'f_31'], ['f_645', 'f_812', 'f_593', 'f_536', 'f_480'], ['f_691', 'f_717', 'f_602', 'f_641', 'f_359'], ['f_553', 'f_622', 'f_145', 'f_549', 'f_364'], ['f_637', 'f_587', 'f_633', 'f_376', 'f_35'], ['f_615', 'f_527', 'f_16', 'f_472', 'f_597'], ['f_776', 'f_260', 'f_689', 'f_521', 'f_18'], ['f_581', 'f_489', 'f_353', 'f_259', 'f_229'], ['f_702', 'f_771', 'f_821', 'f_483', 'f_327'], ['f_685', 'f_601', 'f_623', 'f_474', 'f_411'], ['f_690', 'f_144'], ['f_462', 'f_200', 'f_815', 'f_719', 'f_820'], ['f_199', 'f_758', 'f_755', 'f_403', 'f_792'], ['f_704', 'f_300', 'f_572', 'f_539', 'f_636'], ['f_294', 'f_501'], ['f_368', 'f_800', 'f_377', 'f_187', 'f_505'], ['f_777', 'f_419', 'f_27', 'f_752', 'f_845'], ['f_573', 'f_770', 'f_530', 'f_756', 'f_789'], ['f_713', 'f_596', 'f_445', 'f_674', 'f_447'], ['f_26', 'f_450', 'f_750'], ['f_642', 'f_658', 'f_456', 'f_673', 'f_695'], ['f_337', 'f_379', 'f_558', 'f_373', 'f_150'], ['f_680', 'f_515', 'f_336', 'f_532', 'f_542'], ['f_537', 'f_159', 'f_193', 'f_297', 'f_551'], ['f_693', 'f_785', 'f_352', 'f_675', 'f_417'], ['f_619', 'f_768', 'f_383', 'f_504', 'f_621'], ['f_293', 'f_737', 'f_576', 'f_378', 'f_493'], ['f_244', 'f_799', 'f_508', 'f_46', 'f_831'], ['f_349', 'f_721', 'f_491', 'f_559', 'f_435'], ['f_342', 'f_362'], ['f_662', 'f_738', 'f_261', 'f_459', 'f_258'], ['f_21', 'f_764', 'f_705', 'f_554', 'f_151'], ['f_666', 'f_547', 'f_665', 'f_519', 'f_631'], ['f_779', 'f_115', 'f_22', 'f_759'], ['f_594', 'f_422', 'f_389', 'f_500', 'f_548'], ['f_243', 'f_824', 'f_574'], ['f_188', 'f_116', 'f_152', 'f_624', 'f_586'], ['f_550', 'f_605'], ['f_798', 'f_780', 'f_801', 'f_484', 'f_514'], ['f_707', 'f_458', 'f_412', 'f_496', 'f_714'], ['f_301', 'f_507', 'f_30', 'f_784'], ['f_734', 'f_157', 'f_206', 'f_425', 'f_742'], ['f_34', 'f_661', 'f_604', 'f_421', 'f_517'], ['f_687', 'f_262', 'f_407', 'f_448', 'f_722'], ['f_590', 'f_518', 'f_477'], ['f_703', 'f_763', 'f_385', 'f_782', 'f_164'], ['f_251', 'f_471', 'f_166'], ['f_620', 'f_298', 'f_167'], ['f_651', 'f_606', 'f_635'], ['f_563', 'f_652', 'f_427'], ['f_565', 'f_461', 'f_372', 'f_330', 'f_650'], ['f_367', 'f_207', 'f_575', 'f_314'], ['f_17', 'f_347', 'f_202', 'f_670'], ['f_531', 'f_195'], ['f_805', 'f_160'], ['f_757', 'f_740']]
XofN groups with 2 features: 7
XofN groups with 3 features: 8
XofN groups with 4 features: 6
XofN groups with 5 features: 92
pruning: True, include_original_features: with_org, averageAUROC: 0.5283742, HammingLoss: 0.20038, SubsetAccuracy: 0.1145,
pruning: False, include_original_features: with_org, averageAUROC: 0.5621321, HammingLoss: 0.29198, SubsetAccuracy: 0.091603,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.20293, SubsetAccuracy: 0.10687,
pruning: False, include_original_features: no_org, averageAUROC: 0.5676937, HammingLoss: 0.28944, SubsetAccuracy: 0.061069,

Fold 8/10 (fingerprint_all 1/1)

generate_XofN_list -> Generating groupings based on eval_criterion:['averageAUROC', 'HammingLoss', 'SubsetAccuracy'].

🔄 Processing features: 100%|██████████| 540/540 [2:05:20<00:00, 13.93s/feat]

XofN_groups: [['f_374', 'f_467', 'f_19', 'f_420', 'f_375'], ['f_20', 'f_300', 'f_390', 'f_0'], ['f_346', 'f_419', 'f_522', 'f_11', 'f_517'], ['f_308', 'f_361', 'f_284', 'f_366', 'f_719'], ['f_2', 'f_131', 'f_229', 'f_299', 'f_15'], ['f_571', 'f_515', 'f_333', 'f_473', 'f_510'], ['f_406', 'f_752', 'f_178', 'f_441', 'f_186'], ['f_23', 'f_343', 'f_195'], ['f_672', 'f_551', 'f_582', 'f_689', 'f_533'], ['f_566', 'f_454', 'f_442', 'f_631', 'f_656'], ['f_639', 'f_408', 'f_528', 'f_749', 'f_535'], ['f_338', 'f_216', 'f_146', 'f_368', 'f_213'], ['f_185', 'f_394', 'f_143', 'f_696', 'f_734'], ['f_339', 'f_644', 'f_613', 'f_558', 'f_116'], ['f_287', 'f_588', 'f_345', 'f_336', 'f_629'], ['f_391', 'f_514', 'f_445', 'f_115', 'f_593'], ['f_452', 'f_505', 'f_443', 'f_681', 'f_527'], ['f_3', 'f_494', 'f_553', 'f_653', 'f_645'], ['f_12', 'f_398', 'f_697', 'f_789', 'f_635'], ['f_516', 'f_839', 'f_840', 'f_569', 'f_717'], ['f_643', 'f_401', 'f_451', 'f_145', 'f_715'], ['f_335', 'f_489', 'f_684', 'f_646', 'f_227'], ['f_392', 'f_422', 'f_16', 'f_466', 'f_14'], ['f_617', 'f_215', 'f_540', 'f_332', 'f_395'], ['f_659', 'f_722', 'f_244', 'f_38', 'f_785'], ['f_24', 'f_438', 'f_344', 'f_423', 'f_496'], ['f_393', 'f_10', 'f_576', 'f_682', 'f_301'], ['f_380', 'f_866', 'f_283', 'f_705', 'f_737'], ['f_440', 'f_202', 'f_622', 'f_1', 'f_726'], ['f_712', 'f_486', 'f_487', 'f_150', 'f_861'], ['f_192', 'f_132', 'f_446', 'f_820', 'f_596'], ['f_614', 'f_427', 'f_430', 'f_160'], ['f_405', 'f_860', 'f_679', 'f_680', 'f_710'], ['f_340', 'f_417', 'f_729', 'f_555', 'f_362'], ['f_341', 'f_812', 'f_688', 'f_624', 'f_166'], ['f_181', 'f_230', 'f_518', 'f_567', 'f_285'], ['f_37', 'f_249', 'f_709', 'f_488', 'f_474'], ['f_638', 'f_359', 'f_365', 'f_455', 'f_449'], ['f_439', 'f_367', 'f_33', 'f_397', 'f_767'], ['f_611', 'f_625', 'f_602', 'f_580', 'f_370'], ['f_579', 'f_778', 'f_293', 'f_378', 'f_383'], ['f_699', 'f_159', 'f_641', 'f_46'], ['f_615', 'f_673', 'f_428', 'f_351', 'f_529'], ['f_637', 'f_350', 'f_683', 'f_356', 'f_18'], ['f_686', 'f_305', 'f_691', 'f_129', 'f_292'], ['f_667', 'f_497', 'f_453', 'f_471', 'f_768'], ['f_180', 'f_157', 'f_431', 'f_702', 'f_388'], ['f_698', 'f_647', 'f_450', 'f_819', 'f_298'], ['f_685', 'f_144', 'f_687', 'f_742', 'f_47'], ['f_21', 'f_475', 'f_152', 'f_35', 'f_477'], ['f_241', 'f_713', 'f_797', 'f_708', 'f_153'], ['f_663', 'f_386', 'f_384', 'f_418', 'f_530'], ['f_26', 'f_248', 'f_413', 'f_845', 'f_511'], ['f_199', 'f_652', 'f_539', 'f_30', 'f_258'], ['f_692', 'f_658', 'f_664', 'f_586', 'f_750'], ['f_334', 'f_620'], ['f_581', 'f_187', 'f_538', 'f_654', 'f_695'], ['f_704', 'f_508', 'f_493', 'f_118', 'f_671'], ['f_776', 'f_779', 'f_676', 'f_788', 'f_31'], ['f_690', 'f_243', 'f_357', 'f_358', 'f_206'], ['f_777', 'f_587', 'f_434', 'f_480', 'f_725'], ['f_537', 'f_707', 'f_599', 'f_831', 'f_670'], ['f_432', 'f_250', 'f_564', 'f_416', 'f_755'], ['f_592', 'f_792', 'f_484', 'f_560', 'f_429'], ['f_337', 'f_379', 'f_447', 'f_701', 'f_799'], ['f_536', 'f_483', 'f_353', 'f_526', 'f_568'], ['f_693', 'f_822', 'f_782', 'f_650', 'f_827'], ['f_642', 'f_409', 'f_612', 'f_521', 'f_256'], ['f_193', 'f_407', 'f_728', 'f_736', 'f_286'], ['f_462', 'f_458', 'f_22', 'f_662', 'f_179'], ['f_711', 'f_251', 'f_780', 'f_836', 'f_27'], ['f_294', 'f_501'], ['f_818', 'f_260', 'f_499', 'f_630', 'f_25'], ['f_594', 'f_833', 'f_255', 'f_352', 'f_167'], ['f_623', 'f_559', 'f_507', 'f_597', 'f_815'], ['f_342', 'f_242', 'f_605', 'f_17'], ['f_604', 'f_262', 'f_355', 'f_13', 'f_548'], ['f_259', 'f_436', 'f_803', 'f_694', 'f_261'], ['f_821', 'f_738', 'f_519', 'f_448', 'f_396'], ['f_666', 'f_616', 'f_570', 'f_601', 'f_655'], ['f_798', 'f_194', 'f_735'], ['f_349', 'f_759', 'f_460', 'f_371'], ['f_34', 'f_425', 'f_491', 'f_791', 'f_575'], ['f_412', 'f_456', 'f_363', 'f_373', 'f_706'], ['f_188', 'f_457'], ['f_550', 'f_716', 'f_703', 'f_465', 'f_328'], ['f_577', 'f_756', 'f_758', 'f_207', 'f_824'], ['f_700', 'f_485', 'f_609'], ['f_636', 'f_461', 'f_523', 'f_403', 'f_482'], ['f_591', 'f_503'], ['f_459', 'f_513', 'f_500', 'f_547', 'f_411'], ['f_800', 'f_610'], ['f_364', 'f_770', 'f_830'], ['f_714', 'f_771', 'f_598', 'f_314', 'f_757'], ['f_590', 'f_151', 'f_618', 'f_606', 'f_542'], ['f_200', 'f_583', 'f_677', 'f_826', 'f_675'], ['f_385', 'f_532', 'f_531'], ['f_661', 'f_764', 'f_763', 'f_214'], ['f_435', 'f_813', 'f_387', 'f_506', 'f_400'], ['f_414', 'f_399', 'f_504', 'f_347', 'f_595'], ['f_563', 'f_721', 'f_572'], ['f_372', 'f_740', 'f_472', 'f_621'], ['f_520', 'f_773'], ['f_634', 'f_608', 'f_490', 'f_805'], ['f_668', 'f_603', 'f_554', 'f_389', 'f_801'], ['f_834', 'f_330']]
XofN groups with 2 features: 7
XofN groups with 3 features: 6
XofN groups with 4 features: 8
XofN groups with 5 features: 85
pruning: True, include_original_features: with_org, averageAUROC: 0.4964468, HammingLoss: 0.21056, SubsetAccuracy: 0.061069,
pruning: False, include_original_features: with_org, averageAUROC: 0.5812424, HammingLoss: 0.26718, SubsetAccuracy: 0.076336,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.21247, SubsetAccuracy: 0.053435,
pruning: False, include_original_features: no_org, averageAUROC: 0.5669121, HammingLoss: 0.28435, SubsetAccuracy: 0.083969,

Fold 9/10 (fingerprint_all 1/1)

generate_XofN_list -> Generating groupings based on eval_criterion:['averageAUROC', 'HammingLoss', 'SubsetAccuracy'].

🔄 Processing features: 100%|██████████| 540/540 [2:08:49<00:00, 14.31s/feat]

XofN_groups: [['f_374', 'f_401', 'f_356', 'f_664', 'f_643'], ['f_20', 'f_588', 'f_299', 'f_619', 'f_213'], ['f_23', 'f_284', 'f_15', 'f_697', 'f_438'], ['f_287', 'f_661', 'f_679', 'f_406', 'f_567'], ['f_308', 'f_587', 'f_178', 'f_510', 'f_544'], ['f_346', 'f_394', 'f_710', 'f_333', 'f_298'], ['f_2', 'f_494', 'f_443', 'f_455', 'f_526'], ['f_338', 'f_515', 'f_709', 'f_749', 'f_728'], ['f_672', 'f_131', 'f_430', 'f_475', 'f_200'], ['f_393', 'f_582', 'f_285', 'f_1', 'f_497'], ['f_516', 'f_467', 'f_391', 'f_340', 'f_26'], ['f_366', 'f_129', 'f_351', 'f_14', 'f_646'], ['f_571', 'f_359', 'f_255', 'f_439', 'f_398'], ['f_656', 'f_132', 'f_615', 'f_18', 'f_658'], ['f_392', 'f_300', 'f_384', 'f_592', 'f_824'], ['f_380', 'f_767', 'f_9', 'f_698', 'f_532'], ['f_614', 'f_35', 'f_708', 'f_640', 'f_151'], ['f_566', 'f_644', 'f_613', 'f_683', 'f_483'], ['f_440', 'f_423', 'f_420', 'f_335', 'f_543'], ['f_617', 'f_454', 'f_688', 'f_371', 'f_449'], ['f_24', 'f_244', 'f_376', 'f_451', 'f_10'], ['f_19', 'f_616', 'f_464', 'f_377', 'f_740'], ['f_339', 'f_522', 'f_535', 'f_419', 'f_13'], ['f_185', 'f_558', 'f_437', 'f_332', 'f_773'], ['f_696', 'f_395', 'f_691', 'f_511', 'f_726'], ['f_186', 'f_292', 'f_441', 'f_179', 'f_388'], ['f_659', 'f_216', 'f_573', 'f_645', 'f_153'], ['f_452', 'f_706', 'f_345', 'f_116', 'f_629'], ['f_528', 'f_861', 'f_143', 'f_780', 'f_31'], ['f_192', 'f_118', 'f_599', 'f_609', 'f_736'], ['f_12', 'f_215', 'f_256', 'f_507', 'f_486'], ['f_341', 'f_473', 'f_365', 'f_791', 'f_545'], ['f_405', 'f_518', 'f_442', 'f_678', 'f_416'], ['f_712', 'f_305', 'f_611', 'f_638', 'f_477'], ['f_3', 'f_782', 'f_11', 'f_631', 'f_429'], ['f_181', 'f_422', 'f_654', 'f_799', 'f_390'], ['f_146', 'f_716', 'f_193', 'f_434', 'f_704'], ['f_639', 'f_167', 'f_446', 'f_572', 'f_367'], ['f_540', 'f_343', 'f_602', 'f_737', 'f_399'], ['f_257', 'f_227', 'f_671', 'f_523', 'f_47'], ['f_667', 'f_752', 'f_564', 'f_680', 'f_37'], ['f_681', 'f_517', 'f_725'], ['f_569', 'f_457', 'f_839', 'f_524'], ['f_682', 'f_46', 'f_677', 'f_693', 'f_513'], ['f_684', 'f_514', 'f_370', 'f_150', 'f_115'], ['f_686', 'f_713', 'f_660', 'f_692', 'f_797'], ['f_248', 'f_400'], ['f_663', 'f_758', 'f_655', 'f_584', 'f_352'], ['f_33', 'f_188', 'f_520', 'f_396', 'f_556'], ['f_637', 'f_788', 'f_618', 'f_502', 'f_836'], ['f_337', 'f_386', 'f_490', 'f_711', 'f_527'], ['f_579', 'f_330', 'f_634', 'f_668', 'f_568'], ['f_180', 'f_819', 'f_553', 'f_214'], ['f_241', 'f_301', 'f_466', 'f_350'], ['f_685', 'f_500', 'f_570', 'f_560', 'f_286'], ['f_581', 'f_621', 'f_470', 'f_375', 'f_229'], ['f_690', 'f_860', 'f_608', 'f_578', 'f_595'], ['f_689', 'f_496', 'f_355', 'f_574', 'f_529'], ['f_293', 'f_676', 'f_665', 'f_230', 'f_144'], ['f_699', 'f_547', 'f_603', 'f_798', 'f_826'], ['f_334', 'f_576', 'f_831', 'f_601', 'f_674'], ['f_16', 'f_840', 'f_0', 'f_283', 'f_635'], ['f_294', 'f_249', 'f_818', 'f_508', 'f_650'], ['f_642', 'f_187', 'f_552', 'f_703', 'f_166'], ['f_145', 'f_756', 'f_555', 'f_759', 'f_778'], ['f_462', 'f_160', 'f_206', 'f_407', 'f_27'], ['f_199', 'f_368', 'f_344', 'f_428', 'f_717'], ['f_593', 'f_25', 'f_707', 'f_542', 'f_541'], ['f_537', 'f_159', 'f_662', 'f_17', 'f_202'], ['f_776', 'f_625', 'f_701', 'f_34', 'f_485'], ['f_21', 'f_361', 'f_742', 'f_777', 'f_408'], ['f_597', 'f_489', 'f_641', 'f_580', 'f_735'], ['f_353', 'f_653', 'f_813', 'f_539', 'f_821'], ['f_432', 'f_418', 'f_789'], ['f_594', 'f_647', 'f_521', 'f_336', 'f_242'], ['f_536', 'f_551', 'f_606', 'f_750', 'f_194'], ['f_623', 'f_533', 'f_549', 'f_445', 'f_575'], ['f_38', 'f_605', 'f_381', 'f_715', 'f_559'], ['f_349', 'f_30', 'f_820', 'f_195', 'f_771'], ['f_702', 'f_459', 'f_633', 'f_714', 'f_757'], ['f_755', 'f_694', 'f_548', 'f_460', 'f_830'], ['f_342', 'f_488', 'f_506', 'f_43'], ['f_666', 'f_474', 'f_600', 'f_586', 'f_258'], ['f_493', 'f_822', 'f_491', 'f_546', 'f_363'], ['f_779', 'f_328', 'f_22', 'f_413', 'f_687'], ['f_550', 'f_431', 'f_801', 'f_465', 'f_675'], ['f_695', 'f_738', 'f_554', 'f_768'], ['f_604', 'f_262', 'f_472', 'f_453', 'f_207'], ['f_577', 'f_458', 'f_243', 'f_447', 'f_482'], ['f_498', 'f_845', 'f_565', 'f_297', 'f_761'], ['f_591', 'f_833', 'f_471', 'f_607', 'f_803'], ['f_705', 'f_505', 'f_719', 'f_347', 'f_382'], ['f_636', 'f_461', 'f_827'], ['f_487', 'f_509', 'f_495', 'f_652', 'f_480'], ['f_251', 'f_152', 'f_157', 'f_763', 'f_417'], ['f_800', 'f_421', 'f_364', 'f_834', 'f_770'], ['f_590', 'f_721', 'f_651', 'f_657', 'f_612'], ['f_734', 'f_357', 'f_414', 'f_538', 'f_358'], ['f_700', 'f_373', 'f_563', 'f_378', 'f_624'], ['f_412', 'f_784', 'f_403', 'f_389', 'f_673'], ['f_450', 'f_626', 'f_383', 'f_764', 'f_327'], ['f_519', 'f_670', 'f_585', 'f_387', 'f_622'], ['f_397', 'f_589', 'f_484', 'f_476'], ['f_362', 'f_598'], ['f_596', 'f_812'], ['f_261', 'f_531'], ['f_632', 'f_260'], ['f_435', 'f_610', 'f_530', 'f_448'], ['f_385', 'f_427', 'f_379', 'f_504', 'f_425'], ['f_620', 'f_499', 'f_866'], ['f_792', 'f_409'], ['f_729', 'f_164']]
XofN groups with 2 features: 7
XofN groups with 3 features: 4
XofN groups with 4 features: 7
XofN groups with 5 features: 94
pruning: True, include_original_features: with_org, averageAUROC: 0.5075387, HammingLoss: 0.19148, SubsetAccuracy: 0.1145,
pruning: False, include_original_features: with_org, averageAUROC: 0.5843607, HammingLoss: 0.26018, SubsetAccuracy: 0.083969,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.19338, SubsetAccuracy: 0.099237,
pruning: False, include_original_features: no_org, averageAUROC: 0.5286125, HammingLoss: 0.29453, SubsetAccuracy: 0.053435,

Fold 10/10 (fingerprint_all 1/1)

generate_XofN_list -> Generating groupings based on eval_criterion:['averageAUROC', 'HammingLoss', 'SubsetAccuracy'].

🔄 Processing features: 100%|██████████| 540/540 [2:12:38<00:00, 14.74s/feat]

XofN_groups: [['f_374', 'f_749', 'f_713', 'f_255', 'f_244'], ['f_20', 'f_515', 'f_355', 'f_351', 'f_230'], ['f_308', 'f_706', 'f_441', 'f_406', 'f_667'], ['f_287', 'f_778', 'f_356', 'f_15', 'f_653'], ['f_346', 'f_860', 'f_9', 'f_43', 'f_332'], ['f_23', 'f_715', 'f_430', 'f_421', 'f_292'], ['f_393', 'f_131', 'f_575', 'f_708', 'f_11'], ['f_366', 'f_242', 'f_10', 'f_420', 'f_443'], ['f_2', 'f_812', 'f_384', 'f_628', 'f_370'], ['f_186', 'f_616', 'f_143', 'f_845', 'f_283'], ['f_338', 'f_861', 'f_697', 'f_800', 'f_241'], ['f_299', 'f_588', 'f_642', 'f_416', 'f_129'], ['f_672', 'f_839', 'f_1', 'f_833', 'f_553'], ['f_566', 'f_216', 'f_146', 'f_368', 'f_493'], ['f_614', 'f_840', 'f_285', 'f_452', 'f_390'], ['f_391', 'f_489', 'f_625', 'f_668', 'f_635'], ['f_571', 'f_359', 'f_696', 'f_506', 'f_347'], ['f_617', 'f_436', 'f_178', 'f_581', 'f_361'], ['f_19', 'f_728', 'f_464', 'f_394', 'f_629'], ['f_335', 'f_742', 'f_704', 'f_30', 'f_522'], ['f_12', 'f_343', 'f_249', 'f_450', 'f_712'], ['f_339', 'f_631', 'f_570', 'f_564', 'f_397'], ['f_639', 'f_144', 'f_333', 'f_334', 'f_188'], ['f_516', 'f_300', 'f_613', 'f_14', 'f_470'], ['f_440', 'f_764', 'f_365', 'f_656', 'f_116'], ['f_643', 'f_409', 'f_540', 'f_528', 'f_454'], ['f_192', 'f_543', 'f_709', 'f_145', 'f_314'], ['f_3', 'f_438', 'f_634', 'f_757', 'f_608'], ['f_24', 'f_357', 'f_756', 'f_600', 'f_425'], ['f_659', 'f_115', 'f_377', 'f_398', 'f_740'], ['f_392', 'f_467', 'f_376', 'f_243', 'f_755'], ['f_185', 'f_229', 'f_552', 'f_428', 'f_590'], ['f_451', 'f_644', 'f_821', 'f_483', 'f_520'], ['f_405', 'f_533', 'f_623', 'f_549', 'f_531'], ['f_380', 'f_510', 'f_683', 'f_660', 'f_595'], ['f_341', 'f_725', 'f_449', 'f_546', 'f_719'], ['f_439', 'f_132', 'f_618', 'f_414', 'f_511'], ['f_181', 'f_157', 'f_437', 'f_407', 'f_256'], ['f_33', 'f_583', 'f_664', 'f_379', 'f_413'], ['f_257', 'f_826', 'f_597', 'f_150', 'f_442'], ['f_569', 'f_457', 'f_259', 'f_603', 'f_260'], ['f_180', 'f_159', 'f_258', 'f_545', 'f_459'], ['f_638', 'f_486', 'f_578', 'f_447', 'f_411'], ['f_37', 'f_711', 'f_776', 'f_710', 'f_487'], ['f_611', 'f_658', 'f_580', 'f_677', 'f_768'], ['f_682', 'f_227', 'f_584', 'f_25', 'f_16'], ['f_535', 'f_820', 'f_665'], ['f_345', 'f_455', 'f_573', 'f_688', 'f_502'], ['f_646', 'f_305', 'f_445', 'f_371', 'f_633'], ['f_579', 'f_422', 'f_495', 'f_456'], ['f_681', 'f_160', 'f_607', 'f_559', 'f_31'], ['f_340', 'f_215'], ['f_684', 'f_496', 'f_431', 'f_153', 'f_558'], ['f_698', 'f_831', 'f_619', 'f_678', 'f_788'], ['f_645', 'f_213', 'f_293', 'f_735', 'f_673'], ['f_593', 'f_803', 'f_830', 'f_585', 'f_524'], ['f_663', 'f_400', 'f_446', 'f_458', 'f_758'], ['f_685', 'f_500', 'f_657', 'f_690', 'f_701'], ['f_637', 'f_214', 'f_592', 'f_680', 'f_641'], ['f_294', 'f_501', 'f_179', 'f_815', 'f_342'], ['f_686', 'f_601', 'f_695', 'f_364', 'f_624'], ['f_692', 'f_791', 'f_453', 'f_537', 'f_518'], ['f_615', 'f_399', 'f_530', 'f_532', 'f_494'], ['f_567', 'f_465', 'f_418', 'f_694'], ['f_248', 'f_527', 'f_193', 'f_599', 'f_378'], ['f_691', 'f_427', 'f_650', 'f_622', 'f_375'], ['f_199', 'f_652', 'f_434', 'f_46', 'f_118'], ['f_671', 'f_38', 'f_759', 'f_640', 'f_767'], ['f_699', 'f_763', 'f_432', 'f_577', 'f_798'], ['f_536', 'f_819', 'f_770', 'f_0'], ['f_462', 'f_35', 'f_752', 'f_328', 'f_18'], ['f_21', 'f_47', 'f_799', 'f_729', 'f_490'], ['f_797', 'f_461', 'f_679', 'f_734', 'f_485'], ['f_337', 'f_602', 'f_676'], ['f_702', 'f_587', 'f_396', 'f_655', 'f_782'], ['f_693', 'f_822', 'f_151', 'f_286', 'f_556'], ['f_777', 'f_609', 'f_582', 'f_714', 'f_722'], ['f_689', 'f_423', 'f_507', 'f_834', 'f_750'], ['f_26', 'f_386', 'f_471', 'f_477', 'f_771'], ['f_301', 'f_353', 'f_555', 'f_548', 'f_703'], ['f_666', 'f_363'], ['f_349', 'f_621', 'f_554', 'f_594', 'f_538'], ['f_560', 'f_700', 'f_574', 'f_385', 'f_737'], ['f_818', 'f_488', 'f_358', 'f_498', 'f_736'], ['f_654', 'f_401', 'f_382', 'f_194', 'f_417'], ['f_586', 'f_187', 'f_383', 'f_824', 'f_250'], ['f_662', 'f_152', 'f_539', 'f_513', 'f_408'], ['f_261', 'f_517', 'f_519', 'f_480', 'f_484'], ['f_550', 'f_362', 'f_813'], ['f_707', 'f_336', 'f_352', 'f_497', 'f_387'], ['f_779', 'f_13', 'f_523', 'f_473', 'f_792'], ['f_604', 'f_514', 'f_565'], ['f_591', 'f_598', 'f_738', 'f_789', 'f_472'], ['f_412', 'f_195', 'f_726', 'f_466'], ['f_251', 'f_801', 'f_866'], ['f_705', 'f_499', 'f_504', 'f_448', 'f_721'], ['f_687', 'f_612', 'f_606', 'f_482', 'f_717'], ['f_34', 'f_632', 'f_297', 'f_576', 'f_476'], ['f_636', 'f_605', 'f_805', 'f_435', 'f_350'], ['f_716', 'f_521'], ['f_620', 'f_508', 'f_388', 'f_626', 'f_403'], ['f_541', 'f_647', 'f_373', 'f_547', 'f_785'], ['f_381', 'f_474', 'f_674'], ['f_395', 'f_491'], ['f_651', 'f_526', 'f_589'], ['f_542', 'f_202', 'f_206', 'f_784', 'f_298'], ['f_563', 'f_164', 'f_675', 'f_419'], ['f_780', 'f_207', 'f_367'], ['f_17', 'f_551', 'f_460', 'f_200', 'f_610'], ['f_596', 'f_568'], ['f_661', 'f_27'], ['f_22', 'f_827', 'f_327'], ['f_262', 'f_475'], ['f_529', 'f_330'], ['f_836', 'f_509'], ['f_773', 'f_670']]
XofN groups with 2 features: 10
XofN groups with 3 features: 9
XofN groups with 4 features: 5
XofN groups with 5 features: 92
pruning: True, include_original_features: with_org, averageAUROC: 0.5263954, HammingLoss: 0.19402, SubsetAccuracy: 0.12214,
pruning: False, include_original_features: with_org, averageAUROC: 0.5792129, HammingLoss: 0.27863, SubsetAccuracy: 0.045802,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.1972, SubsetAccuracy: 0.1145,
pruning: False, include_original_features: no_org, averageAUROC: 0.6094549, HammingLoss: 0.26081, SubsetAccuracy: 0.068702,
   pruning include_original_features          dataset  averageAUROC  \
0    False                    no_org  fingerprint_all      0.565048
1    False                  with_org  fingerprint_all      0.567379
2     True                    no_org  fingerprint_all      0.503060
3     True                  with_org  fingerprint_all      0.513947

   HammingLoss  SubsetAccuracy  nodes  leaves  groups  avg_group_features  \
0     0.279389        0.054962  980.6   490.8   109.6            4.677277
1     0.275448        0.062595  972.0   486.5   109.6            4.677277
2     0.200827        0.105343    2.2     1.6   109.6            4.677277
3     0.199363        0.109923    3.6     2.3   109.6            4.677277

   gen_XofN_time  training_time
0    7405.778034       0.806474
1    7405.778034       1.433403
2    7405.778034       0.806474
3    7405.778034       1.433403

In [4]:
# paths[6] - fingerprint_diverse
final_grouped_res = pd.DataFrame()
for df in cv_results:
    final_grouped_res = pd.concat([final_grouped_res, df])
final_grouped_res

,pruning,include_original_features,dataset,averageAUROC,HammingLoss,SubsetAccuracy,nodes,leaves,groups,avg_group_features,gen_XofN_time,training_time
0,False,no_org,fingerprint_all,0.565048,0.279389,0.054962,980.6,490.8,109.6,4.677277,7405.778034,0.806474
1,False,with_org,fingerprint_all,0.567379,0.275448,0.062595,972.0,486.5,109.6,4.677277,7405.778034,1.433403
2,True,no_org,fingerprint_all,0.503060,0.200827,0.105343,2.2,1.6,109.6,4.677277,7405.778034,0.806474
3,True,with_org,fingerprint_all,0.513947,0.199363,0.109923,3.6,2.3,109.6,4.677277,7405.778034,1.433403

In [22]:
# paths[7] - fingerprint_diverse
final_grouped_res = pd.DataFrame()
for df in cv_results:
    final_grouped_res = pd.concat([final_grouped_res, df])
final_grouped_res

,pruning,include_original_features,dataset,averageAUROC,HammingLoss,SubsetAccuracy,nodes,leaves,groups,avg_group_features,gen_XofN_time,training_time
0,False,no_org,fingerprint_diverse,0.577506,0.273612,0.239396,786.4,393.7,105.5,4.696913,6158.804027,0.787095
1,False,with_org,fingerprint_diverse,0.579968,0.261364,0.254546,787.4,394.2,105.5,4.696913,6158.804027,1.414068
2,True,no_org,fingerprint_diverse,0.511022,0.180682,0.431818,5.0,3.0,105.5,4.696913,6158.804027,0.787095
3,True,with_org,fingerprint_diverse,0.524099,0.178913,0.435607,6.6,3.8,105.5,4.696913,6158.804027,1.414068

In [5]:
# paths[8] - fingerprint_frequent
final_grouped_res = pd.DataFrame()
for df in cv_results:
    final_grouped_res = pd.concat([final_grouped_res, df])
final_grouped_res

,pruning,include_original_features,dataset,averageAUROC,HammingLoss,SubsetAccuracy,nodes,leaves,groups,avg_group_features,gen_XofN_time,training_time
0,False,no_org,fingerprint_frequent,0.570636,0.285095,0.350319,602.0,301.5,84.0,4.863861,6396.208116,0.852198
1,False,with_org,fingerprint_frequent,0.568670,0.277887,0.360173,596.4,298.7,84.0,4.863861,6396.208116,1.270581
2,True,no_org,fingerprint_frequent,0.559994,0.232903,0.503828,51.8,26.4,84.0,4.863861,6396.208116,0.852198
3,True,with_org,fingerprint_frequent,0.558241,0.230876,0.501540,51.4,26.2,84.0,4.863861,6396.208116,1.270581

In [5]:
# All results
save_path = "XofN_wrapper/"
final_grouped_res = pd.DataFrame()
for df in cv_results:
    final_grouped_res = pd.concat([final_grouped_res, df])
final_grouped_res.sort_values(by='dataset', ascending=False, inplace=True)
final_grouped_res = final_grouped_res.reset_index(drop=True)

if os.path.exists(save_path + "all_results.csv"):
    existing = pd.read_csv(save_path + "all_results.csv", index_col=0)
    combined = pd.concat([existing, final_grouped_res], ignore_index=True)
    combined.drop_duplicates(inplace=True)
else:
    combined = final_grouped_res
combined.to_csv(save_path + "all_results.csv")
combined

,pruning,include_original_features,dataset,averageAUROC,HammingLoss,SubsetAccuracy,nodes,leaves,groups,avg_group_features,gen_XofN_time,training_time
0,False,no_org,fingerprint_frequent,0.570636,0.285095,0.350319,602.0,301.5,84.0,4.863861,6396.208116,0.852198
1,False,with_org,fingerprint_frequent,0.568670,0.277887,0.360173,596.4,298.7,84.0,4.863861,6396.208116,1.270581
2,True,no_org,fingerprint_frequent,0.559994,0.232903,0.503828,51.8,26.4,84.0,4.863861,6396.208116,0.852198
3,True,with_org,fingerprint_frequent,0.558241,0.230876,0.501540,51.4,26.2,84.0,4.863861,6396.208116,1.270581
4,False,no_org,fingerprint_diverse,0.577506,0.273612,0.239396,786.4,393.7,105.5,4.696913,6158.804027,0.787095
5,False,with_org,fingerprint_diverse,0.579968,0.261364,0.254546,787.4,394.2,105.5,4.696913,6158.804027,1.414068
6,True,no_org,fingerprint_diverse,0.511022,0.180682,0.431818,5.0,3.0,105.5,4.696913,6158.804027,0.787095
7,True,with_org,fingerprint_diverse,0.524099,0.178913,0.435607,6.6,3.8,105.5,4.696913,6158.804027,1.414068
8,False,no_org,fingerprint_all,0.565048,0.279389,0.054962,980.6,490.8,109.6,4.677277,7405.778034,0.806474
9,False,with_org,fingerprint_all,0.567379,0.275448,0.062595,972.0,486.5,109.6,4.677277,7405.778034,1.433403
10,True,no_org,fingerprint_all,0.503060,0.200827,0.105343,2.2,1.6,109.6,4.677277,7405.778034,0.806474
11,True,with_org,fingerprint_all,0.513947,0.199363,0.109923,3.6,2.3,109.6,4.677277,7405.778034,1.433403

In [6]:
# Table ready (with pruning, rounded, compact)
save_path = "XofN_wrapper/"
res = pd.read_csv(save_path + "all_results.csv", index_col=0)
table_results = get_table_results(res, get_dataset_paths())
table_results.to_csv(save_path + "table_results.csv")
table_results

,include_original_features,dataset,averageAUROC,HammingLoss,SubsetAccuracy,Nodes; Leaves,#XofN; #Feat/XofN,# Ung. Feats,XofN time (s); PCT tr. time (s)
2,no_org,fingerprint_frequent,0.560,0.233,0.504,51.8; 26.4,84.0; 4.9,131.435655,6396.2; 0.9
3,with_org,fingerprint_frequent,0.558,0.231,0.502,51.4; 26.2,84.0; 4.9,131.435655,6396.2; 1.3
6,no_org,fingerprint_diverse,0.511,0.181,0.432,5.0; 3.0,105.5; 4.7,44.475715,6158.8; 0.8
7,with_org,fingerprint_diverse,0.524,0.179,0.436,6.6; 3.8,105.5; 4.7,44.475715,6158.8; 1.4
10,no_org,fingerprint_all,0.503,0.201,0.105,2.2; 1.6,109.6; 4.7,27.370465,7405.8; 0.8
11,with_org,fingerprint_all,0.514,0.199,0.110,3.6; 2.3,109.6; 4.7,27.370465,7405.8; 1.4

In [9]:
# Frequent with time
final_grouped_res = pd.DataFrame()
for df in cv_results:
    final_grouped_res = pd.concat([final_grouped_res, df])
final_grouped_res

,pruning,include_original_features,averageAUROC,HammingLoss,SubsetAccuracy,nodes,leaves,groups,avg_group_features,gen_XofN_time,training_time,dataset
0,False,no_org,0.568567,0.274587,0.389788,599.6,300.3,18.6,2.417036,5984.643825,1.109454,fingerprint_frequent
1,False,with_org,0.571161,0.280927,0.377649,598.8,299.9,18.6,2.417036,5984.643825,1.198192,fingerprint_frequent
2,True,no_org,0.518590,0.226579,0.520557,19.8,10.4,18.6,2.417036,5984.643825,1.109454,fingerprint_frequent
3,True,with_org,0.530389,0.229251,0.515213,27.6,14.3,18.6,2.417036,5984.643825,1.198192,fingerprint_frequent

In [4]:
# Diverse with time
final_grouped_res = pd.DataFrame()
for df in cv_results:
    final_grouped_res = pd.concat([final_grouped_res, df])
final_grouped_res

,pruning,include_original_features,averageAUROC,HammingLoss,SubsetAccuracy,nodes,leaves,groups,avg_group_features,gen_XofN_time,training_time,dataset
0,False,no_org,0.584899,0.270961,0.230303,791.6,396.3,67.9,2.527317,5860.982623,1.114352,fingerprint_diverse
1,False,with_org,0.583008,0.271718,0.237121,803.0,402.0,67.9,2.527317,5860.982623,1.280688,fingerprint_diverse
2,True,no_org,0.515306,0.179167,0.438638,5.2,3.1,67.9,2.527317,5860.982623,1.114352,fingerprint_diverse
3,True,with_org,0.518883,0.178788,0.437880,5.0,3.0,67.9,2.527317,5860.982623,1.280688,fingerprint_diverse

In [4]:
# All with time
final_grouped_res = pd.DataFrame()
for df in cv_results:
    final_grouped_res = pd.concat([final_grouped_res, df])
final_grouped_res

,pruning,include_original_features,averageAUROC,HammingLoss,SubsetAccuracy,nodes,leaves,groups,avg_group_features,gen_XofN_time,training_time,dataset
0,False,no_org,0.586784,0.266476,0.069466,970.2,485.6,75.4,2.35369,6578.325103,1.162779,fingerprint_all
1,False,with_org,0.592362,0.264057,0.070229,971.6,486.3,75.4,2.35369,6578.325103,1.355200,fingerprint_all
2,True,no_org,0.515989,0.198537,0.111450,3.2,2.1,75.4,2.35369,6578.325103,1.162779,fingerprint_all
3,True,with_org,0.515989,0.198537,0.111450,3.2,2.1,75.4,2.35369,6578.325103,1.355200,fingerprint_all