In [1]:
%load_ext autoreload
%autoreload 2

from sklearn.model_selection import KFold
from SIDER_dataset.libraries.XofN_library import *
from SIDER_dataset.libraries.PCT_library import run_PCT
from SIDER_dataset.libraries.feature_evaluation_methods import feature_variance_reduction_scores
from SIDER_dataset.libraries.utils import get_clus_path

In [2]:
# Set ADR to predict and scoring
clus_path = get_clus_path()
paths = get_dataset_paths()
print(len(paths), "datasets")

9 datasets

In [3]:
k = 10
random_state = 42
performances = []
ranking_criteria = "MDI"  # or "VAR"
include_original_features_options = [True, False]
training_algorithm = "Jaccard_min"
eval_criteria = ["averageAUROC", "HammingLoss", "SubsetAccuracy"]
max_size = 5
cv_results = []

for idx, path in enumerate(paths, start=1):
    run_config = f"\n--- Running with label:'{path["label_set"]}' training_algorithm:'{training_algorithm}' eval_criterion:'{eval_criteria}' max_size:'{max_size}' ---"
    print(run_config)
    run_config_name = "_".join(
        [
            path["dataset_name"],
            training_algorithm,
            "_".join(eval_criteria),
            str(max_size),
        ]
    )
    logging_path = f"XofN_jaccard_min/logs/{run_config_name}_logs.txt"
    print(f"Logs can be found in {logging_path}.")
    logger = get_logger(logging_path)
    logger.info(run_config_name)

    # Load dataset
    current_df = pd.read_csv(path["dataset_path"])
    features = get_features(current_df, path["label_set"])
    # current_df = current_df[features[:10] + path["label_set"]]
    kf = KFold(n_splits=k, shuffle=True, random_state=random_state)
    for fold, (train_idx, test_idx) in enumerate(kf.split(current_df), start=1):
        print(f"\nFold {fold}/{k} ({path["dataset_name"]} {idx}/{len(paths)})")
        train_dataset = current_df.iloc[train_idx]
        test_dataset = current_df.iloc[test_idx]

        if ranking_criteria == "VAR":
            feature_rankings = feature_variance_reduction_scores(train_dataset[features],
                                                                 train_dataset[path["label_set"]])
        elif ranking_criteria == "MDI":
            feature_rankings = calculate_mdi_multi_rf(train_dataset, path["label_set"])
        else:
            raise NotImplementedError

        XofN_groupings, avg_features, gen_XofN_time = generate_XofN_list_multi_jaccard(
            train_dataset,
            feature_rankings,
            max_size,
            logger,
            minimise=True
        )
        if len(XofN_groupings) == 0:
            print("no XofN groupings were created")
        else:
            for include_original_features in include_original_features_options:
                current_train_dataset = group_features(
                    train_dataset,
                    path["label_set"],
                    XofN_groupings,
                    include_original_features,
                    verbose=True
                )

                current_test_dataset = group_features(
                    test_dataset,
                    path["label_set"],
                    XofN_groupings,
                    include_original_features,
                    verbose=True
                )

                current_train_dataset.to_csv(f"XofN_jaccard_min/tmp/train_dataset.csv", index=False)
                current_test_dataset.to_csv(f"XofN_jaccard_min/tmp/test_dataset.csv", index=False)

                training_start = time.perf_counter()
                original_res, pruned_res, training_time = run_PCT(clus_path,
                                                                  "XofN_jaccard_min/tmp/train_dataset.csv",
                                                                  path["label_set"],
                                                                  eval_criteria,
                                                                  test_dataset_path=f"XofN_jaccard_min/tmp/test_dataset.csv")
                pruned_performance = get_fold_results(pruned_res, eval_criteria, True, fold, include_original_features,
                                                      XofN_groupings,
                                                      gen_XofN_time,
                                                      training_time, path["dataset_name"])
                performances.append(pruned_performance)
                performance = get_fold_results(original_res, eval_criteria, False, fold, include_original_features,
                                               XofN_groupings,
                                               gen_XofN_time,
                                               training_time, path["dataset_name"])
                performances.append(performance)

    if len(performances) == 0:
        print("no XofN groupings were created in any fold")
    else:
        final_perf_df = pd.DataFrame(performances)
        averages = final_perf_df.groupby(["pruning", 'include_original_features', 'dataset'])[
            ['averageAUROC', 'HammingLoss', 'SubsetAccuracy', 'nodes', 'leaves', 'groups',
             'avg_group_features', 'gen_XofN_time', 'training_time']].mean().reset_index()
        print(averages)
        cv_results.append(averages)
        performances = []
# paths[0] - features[:10] desktop 0.29m
# laptop ??m
# desktop 12h

--- Running with label:'['se_C0027497', 'se_C0018681', 'se_C0011603', 'se_C0015230', 'se_C0042963', 'se_C0012833', 'se_C0027769', 'se_C0020580', 'se_C0014457', 'se_C0017181', 'se_C0151763', 'se_C0038358']' training_algorithm:'Jaccard_min' eval_criterion:'['averageAUROC', 'HammingLoss', 'SubsetAccuracy']' max_size:'5' ---
Logs can be found in XofN_jaccard_min/logs/CPI+fingerprint_all_Jaccard_min_averageAUROC_HammingLoss_SubsetAccuracy_5_logs.txt.

Fold 1/10 (CPI+fingerprint_all 1/9)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [10:13<00:00,  3.50feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'f_413', 'f_262', 'f_151', 'f_635'], ['f_374', 'cpi_9606.ENSP00000268695', 'cpi_9606.ENSP00000414334', 'f_768', 'cpi_9606.ENSP00000359424'], ['f_308', 'cpi_9606.ENSP00000355192', 'f_616', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000374323'], ['f_20', 'cpi_9606.ENSP00000333212', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000295454', 'f_194'], ['f_3', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000337335', 'cpi_9606.ENSP00000286479'], ['f_299', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000323867', 'cpi_9606.ENSP00000367851', 'cpi_9606.ENSP00000360493'], ['f_452', 'f_25', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000259396', 'f_831'], ['f_672', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000321584', 'f_292', 'f_845'], ['f_23', 'cpi_9606.ENSP00000241052', 'f_118', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000356094'], ['f_393', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000380318', 'cpi_9606.ENSP00000354476'], ['f_380', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000270474', 'f_789', 'cpi_9606.ENSP00000342235'], ['f_366', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000220616', 'cpi_9606.ENSP00000395653', 'f_428'], ['f_346', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000279178', 'cpi_9606.ENSP00000319170', 'f_629'], ['f_440', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000353292', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000277010'], ['f_451', 'cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000245539', 'f_31', 'f_830'], ['f_185', 'cpi_9606.ENSP00000261205', 'cpi_9606.ENSP00000356832', 'cpi_9606.ENSP00000282561', 'cpi_9606.ENSP00000430684'], ['f_643', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000377947', 'f_27', 'cpi_9606.ENSP00000443459'], ['f_406', 'cpi_9606.ENSP00000352035', 'f_726', 'cpi_9606.ENSP00000257290', 'cpi_9606.ENSP00000408860'], ['f_192', 'cpi_9606.ENSP00000345096', 'cpi_9606.ENSP00000283254', 'f_47', 'cpi_9606.ENSP00000359353'], ['f_186', 'cpi_9606.ENSP00000279387', 'cpi_9606.ENSP00000389338', 'cpi_9606.ENSP00000411593', 'f_131'], ['f_614', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000332369', 'f_511', 'f_725'], ['f_659', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000362549', 'f_773', 'cpi_9606.ENSP00000355629'], ['f_566', 'cpi_9606.ENSP00000303540', 'f_529', 'cpi_9606.ENSP00000332296', 'cpi_9606.ENSP00000324856'], ['f_335', 'f_815', 'cpi_9606.ENSP00000264162', 'cpi_9606.ENSP00000367848', 'f_767'], ['f_617', 'cpi_9606.ENSP00000394033', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000394936'], ['f_15', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000470087', 'f_719'], ['f_391', 'cpi_9606.ENSP00000357204', 'f_866', 'cpi_9606.ENSP00000361206', 'f_788'], ['f_33', 'f_706', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000301645', 'f_510'], ['f_571', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000301891', 'f_736'], ['f_146', 'cpi_9606.ENSP00000222256', 'f_526', 'cpi_9606.ENSP00000290349', 'cpi_9606.ENSP00000304822'], ['f_405', 'cpi_9606.ENSP00000319531', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000221972', 'cpi_9606.ENSP00000316786'], ['f_37', 'f_782', 'f_164', 'cpi_9606.ENSP00000343782', 'f_554'], ['f_143', 'cpi_9606.ENSP00000225927', 'cpi_9606.ENSP00000355657', 'f_836', 'f_328'], ['f_12', 'cpi_9606.ENSP00000314214', 'cpi_9606.ENSP00000445340', 'cpi_9606.ENSP00000263126', 'cpi_9606.ENSP00000312455'], ['cpi_9606.ENSP00000311032', 'f_543', 'f_207', 'f_675', 'f_518'], ['f_287', 'f_408', 'cpi_9606.ENSP00000350616', 'f_166', 'cpi_9606.ENSP00000226574'], ['f_338', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000331746', 'cpi_9606.ENSP00000323568', 'f_460'], ['f_392', 'cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000447149', 'f_202', 'cpi_9606.ENSP00000300061'], ['f_535', 'cpi_9606.ENSP00000262888', 'cpi_9606.ENSP00000233146', 'f_297', 'cpi_9606.ENSP00000428924'], ['f_420', 'cpi_9606.ENSP00000312326', 'f_330', 'cpi_9606.ENSP00000252809', 'f_497'], ['f_639', 'f_715', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000256383', 'cpi_9606.ENSP00000274547'], ['f_339', 'cpi_9606.ENSP00000367102', 'f_670', 'cpi_9606.ENSP00000376432', 'f_771'], ['f_697', 'f_35', 'cpi_9606.ENSP00000274353', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000344352'], ['f_19', 'cpi_9606.ENSP00000472933', 'cpi_9606.ENSP00000463999', 'f_327', 'f_834'], ['f_390', 'cpi_9606.ENSP00000471397', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000312664', 'f_583'], ['f_285', 'cpi_9606.ENSP00000287878', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000264867', 'cpi_9606.ENSP00000451040'], ['f_613', 'cpi_9606.ENSP00000314649', 'cpi_9606.ENSP00000264637', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000319788'], ['f_181', 'cpi_9606.ENSP00000370129', 'cpi_9606.ENSP00000266376', 'cpi_9606.ENSP00000466799', 'f_167'], ['f_712', 'cpi_9606.ENSP00000218548', 'cpi_9606.ENSP00000283635', 'f_729', 'f_46'], ['f_569', 'f_214', 'cpi_9606.ENSP00000216465', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000305422'], ['f_656', 'cpi_9606.ENSP00000277508', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000303248', 'f_436'], ['f_579', 'cpi_9606.ENSP00000354193', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000360773', 'f_764'], ['f_638', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000399168', 'cpi_9606.ENSP00000329357', 'f_820'], ['f_696', 'cpi_9606.ENSP00000397582', 'f_474', 'cpi_9606.ENSP00000222330', 'f_298'], ['f_2', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000219794', 'cpi_9606.ENSP00000357283', 'f_509'], ['f_646', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000298472', 'f_749'], ['f_341', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000273398', 'cpi_9606.ENSP00000286301', 'cpi_9606.ENSP00000343040'], ['f_257', 'cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000299847', 'f_361'], ['f_683', 'cpi_9606.ENSP00000405573', 'cpi_9606.ENSP00000447173', 'f_505', 'cpi_9606.ENSP00000296871'], ['f_180', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000471569'], ['f_516', 'cpi_9606.ENSP00000359100', 'cpi_9606.ENSP00000430432', 'cpi_9606.ENSP00000378517', 'f_350'], ['f_682', 'f_839', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000246553', 'f_132'], ['f_443', 'cpi_9606.ENSP00000383365', 'cpi_9606.ENSP00000381097', 'cpi_9606.ENSP00000000442', 'f_587'], ['f_16', 'f_622', 'cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000258749', 'cpi_9606.ENSP00000387946'], ['f_681', 'f_215', 'f_568', 'f_417', 'cpi_9606.ENSP00000291295'], ['f_340', 'cpi_9606.ENSP00000373477', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000216962', 'f_827'], ['f_611', 'cpi_9606.ENSP00000237014', 'f_631', 'cpi_9606.ENSP00000358548', 'cpi_9606.ENSP00000307599'], ['f_645', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000366662', 'f_229'], ['f_21', 'cpi_9606.ENSP00000306490', 'f_116', 'f_752', 'cpi_9606.ENSP00000252519'], ['cpi_9606.ENSP00000342007', 'f_494', 'f_551', 'cpi_9606.ENSP00000321326', 'f_43'], ['f_684', 'cpi_9606.ENSP00000254976', 'cpi_9606.ENSP00000317379', 'cpi_9606.ENSP00000386306', 'f_473'], ['cpi_9606.ENSP00000265724', 'f_401', 'f_427', 'f_785', 'f_22'], ['f_540', 'cpi_9606.ENSP00000222481', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000411658', 'cpi_9606.ENSP00000326119'], ['f_293', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000358730', 'cpi_9606.ENSP00000394932'], ['f_698', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000357981', 'f_388', 'cpi_9606.ENSP00000216037'], ['cpi_9606.ENSP00000353820', 'f_26', 'f_812', 'cpi_9606.ENSP00000286648', 'f_799'], ['f_691', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000216540', 'f_792'], ['f_628', 'cpi_9606.ENSP00000216714', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000276449', 'f_448'], ['f_686', 'cpi_9606.ENSP00000231751', 'f_650', 'f_833', 'f_466'], ['f_365', 'cpi_9606.ENSP00000226578', 'cpi_9606.ENSP00000361359', 'cpi_9606.ENSP00000275525', 'cpi_9606.ENSP00000361666'], ['f_594', 'cpi_9606.ENSP00000362353', 'cpi_9606.ENSP00000358107', 'f_407', 'cpi_9606.ENSP00000260191'], ['f_439', 'cpi_9606.ENSP00000254488', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000275216', 'cpi_9606.ENSP00000356436'], ['f_528', 'cpi_9606.ENSP00000305221', 'cpi_9606.ENSP00000302967', 'f_757', 'cpi_9606.ENSP00000302846'], ['f_553', 'cpi_9606.ENSP00000332549', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000389414', 'f_159'], ['f_345', 'cpi_9606.ENSP00000297258', 'cpi_9606.ENSP00000344674', 'cpi_9606.ENSP00000343477', 'cpi_9606.ENSP00000353362'], ['f_704', 'cpi_9606.ENSP00000353224', 'cpi_9606.ENSP00000339260', 'f_728', 'cpi_9606.ENSP00000457706'], ['f_573', 'cpi_9606.ENSP00000371236', 'cpi_9606.ENSP00000297316', 'f_791', 'f_676'], ['f_615', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000231228', 'cpi_9606.ENSP00000332116', 'f_419'], ['f_637', 'cpi_9606.ENSP00000332256', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000340691', 'f_778'], ['f_671', 'cpi_9606.ENSP00000356729', 'cpi_9606.ENSP00000262441', 'cpi_9606.ENSP00000427514', 'f_609'], ['f_536', 'cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000338548', 'cpi_9606.ENSP00000344192'], ['f_567', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000328173', 'f_750', 'f_508'], ['f_368', 'f_230', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000217426'], ['f_602', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000259089', 'f_394'], ['f_294', 'cpi_9606.ENSP00000263321', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000331358', 'cpi_9606.ENSP00000295491'], ['f_641', 'cpi_9606.ENSP00000357669', 'cpi_9606.ENSP00000252723', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000417229'], ['f_666', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000164139', 'cpi_9606.ENSP00000251535', 'cpi_9606.ENSP00000356958'], ['f_692', 'cpi_9606.ENSP00000354532', 'f_533', 'f_496', 'cpi_9606.ENSP00000354394'], ['f_699', 'f_488', 'cpi_9606.ENSP00000364709', 'f_486', 'f_483'], ['f_353', 'cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000359998', 'f_826', 'cpi_9606.ENSP00000287936'], ['f_667', 'cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000301178', 'f_343', 'f_644'], ['f_375', 'f_242', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000254079', 'cpi_9606.ENSP00000308165'], ['f_693', 'cpi_9606.ENSP00000353720', 'f_517', 'cpi_9606.ENSP00000262948', 'f_513'], ['f_248', 'cpi_9606.ENSP00000279593', 'cpi_9606.ENSP00000311095', 'f_455', 'f_477'], ['f_593', 'cpi_9606.ENSP00000270142', 'f_840', 'f_759', 'cpi_9606.ENSP00000348069'], ['f_351', 'cpi_9606.ENSP00000233944', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000385806', 'f_409'], ['f_642', 'f_314', 'f_429', 'f_813', 'cpi_9606.ENSP00000261755'], ['f_145', 'cpi_9606.ENSP00000277541', 'cpi_9606.ENSP00000261196', 'cpi_9606.ENSP00000307235', 'f_763'], ['f_286', 'cpi_9606.ENSP00000337746', 'cpi_9606.ENSP00000296677', 'cpi_9606.ENSP00000225474', 'f_722'], ['f_597', 'f_456', 'cpi_9606.ENSP00000360967', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000370473'], ['cpi_9606.ENSP00000356438', 'f_213', 'f_336', 'cpi_9606.ENSP00000320025', 'f_621'], ['f_586', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000256958', 'cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000347942'], ['f_689', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000434516', 'f_647', 'cpi_9606.ENSP00000261937'], ['f_349', 'cpi_9606.ENSP00000385834', 'f_522', 'f_801', 'cpi_9606.ENSP00000330393'], ['f_680', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000264818', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000231454'], ['cpi_9606.ENSP00000360372', 'f_200', 'cpi_9606.ENSP00000293288', 'cpi_9606.ENSP00000307014', 'cpi_9606.ENSP00000234371'], ['f_581', 'f_411', 'cpi_9606.ENSP00000367309', 'f_422', 'cpi_9606.ENSP00000369530'], ['f_604', 'cpi_9606.ENSP00000313490', 'f_861', 'cpi_9606.ENSP00000359663', 'f_160'], ['f_777', 'cpi_9606.ENSP00000256119', 'f_461', 'cpi_9606.ENSP00000382659', 'cpi_9606.ENSP00000365016'], ['f_663', 'cpi_9606.ENSP00000252945', 'cpi_9606.ENSP00000419692', 'cpi_9606.ENSP00000261799', 'f_216'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000322617', 'f_17', 'cpi_9606.ENSP00000299267'], ['f_702', 'cpi_9606.ENSP00000276431', 'cpi_9606.ENSP00000354610', 'f_514', 'f_780'], ['cpi_9606.ENSP00000295897', 'f_115', 'f_454', 'f_195', 'f_770'], ['f_432', 'cpi_9606.ENSP00000363868', 'cpi_9606.ENSP00000339527', 'f_363', 'cpi_9606.ENSP00000264318'], ['f_199', 'cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000441691', 'f_558', 'f_738'], ['f_776', 'cpi_9606.ENSP00000303211', 'f_129', 'cpi_9606.ENSP00000309124', 'f_465'], ['f_342', 'cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000396320', 'f_475', 'cpi_9606.ENSP00000376943'], ['f_797', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000309572'], ['f_633', 'cpi_9606.ENSP00000264426', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000294728', 'cpi_9606.ENSP00000267101'], ['f_259', 'cpi_9606.ENSP00000318585', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000242057', 'f_625'], ['f_241', 'cpi_9606.ENSP00000374467', 'cpi_9606.ENSP00000353878', 'f_588', 'cpi_9606.ENSP00000261693'], ['f_377', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000303325', 'cpi_9606.ENSP00000200676', 'f_471'], ['f_24', 'cpi_9606.ENSP00000263341', 'cpi_9606.ENSP00000260649', 'cpi_9606.ENSP00000348897', 'f_653'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000311165', 'f_742', 'f_347', 'f_822'], ['f_685', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000308774'], ['f_619', 'cpi_9606.ENSP00000364212', 'cpi_9606.ENSP00000331912', 'cpi_9606.ENSP00000263980', 'f_30'], ['f_560', 'cpi_9606.ENSP00000353679', 'f_860', 'f_740', 'f_559'], ['f_690', 'cpi_9606.ENSP00000260970', 'cpi_9606.ENSP00000312673', 'f_467', 'cpi_9606.ENSP00000312029'], ['f_818', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000386284', 'f_305', 'cpi_9606.ENSP00000356954'], ['f_464', 'cpi_9606.ENSP00000234310', 'cpi_9606.ENSP00000255465', 'f_367', 'cpi_9606.ENSP00000291294'], ['f_493', 'cpi_9606.ENSP00000285979', 'cpi_9606.ENSP00000340943', 'cpi_9606.ENSP00000320935', 'cpi_9606.ENSP00000428340'], ['f_193', 'cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000296545', 'cpi_9606.ENSP00000448059', 'f_378'], ['f_10', 'cpi_9606.ENSP00000238379', 'cpi_9606.ENSP00000232219', 'f_398', 'f_480'], ['f_821', 'cpi_9606.ENSP00000308541', 'f_489', 'cpi_9606.ENSP00000365380', 'f_425'], ['cpi_9606.ENSP00000337450', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000362649', 'f_421', 'f_575'], ['f_144', 'cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000262367', 'f_34'], ['f_819', 'cpi_9606.ENSP00000261405', 'cpi_9606.ENSP00000297350', 'f_152', 'f_38'], ['f_709', 'cpi_9606.ENSP00000330032', 'cpi_9606.ENSP00000358595', 'f_423', 'cpi_9606.ENSP00000241261'], ['f_592', 'cpi_9606.ENSP00000248935', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000264657', 'cpi_9606.ENSP00000370381'], ['f_430', 'cpi_9606.ENSP00000346827', 'cpi_9606.ENSP00000240652', 'f_721', 'cpi_9606.ENSP00000304895'], ['f_755', 'cpi_9606.ENSP00000256078', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000260356', 'f_260'], ['f_150', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000382250', 'cpi_9606.ENSP00000380247', 'f_457'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000299178', 'cpi_9606.ENSP00000301634', 'f_630', 'f_658'], ['f_548', 'cpi_9606.ENSP00000298283', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000278616', 'f_359'], ['cpi_9606.ENSP00000354612', 'f_605', 'f_547', 'cpi_9606.ENSP00000372023', 'cpi_9606.ENSP00000358903'], ['f_502', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000253004', 'f_803', 'cpi_9606.ENSP00000362508'], ['f_18', 'cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000304408', 'f_717', 'f_805'], ['f_462', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000282753', 'f_397'], ['f_798', 'cpi_9606.ENSP00000352835', 'f_500', 'cpi_9606.ENSP00000226413', 'cpi_9606.ENSP00000318822'], ['f_701', 'cpi_9606.ENSP00000319591', 'cpi_9606.ENSP00000219919', 'f_499', 'cpi_9606.ENSP00000416293'], ['f_334', 'cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000239938', 'f_243', 'cpi_9606.ENSP00000274793'], ['f_337', 'cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000176763', 'cpi_9606.ENSP00000260010'], ['f_549', 'cpi_9606.ENSP00000236671', 'cpi_9606.ENSP00000379339', 'cpi_9606.ENSP00000297313', 'f_227'], ['cpi_9606.ENSP00000264381', 'f_713', 'f_784', 'cpi_9606.ENSP00000267843', 'cpi_9606.ENSP00000267119'], ['f_507', 'cpi_9606.ENSP00000234961', 'cpi_9606.ENSP00000302111', 'cpi_9606.ENSP00000343204', 'cpi_9606.ENSP00000366307'], ['cpi_9606.ENSP00000258743', 'f_652', 'cpi_9606.ENSP00000326219', 'cpi_9606.ENSP00000270570', 'f_687'], ['f_352', 'cpi_9606.ENSP00000348395', 'cpi_9606.ENSP00000310405', 'cpi_9606.ENSP00000252486', 'f_157'], ['f_487', 'cpi_9606.ENSP00000308032', 'cpi_9606.ENSP00000295256', 'cpi_9606.ENSP00000265723', 'f_756'], ['f_537', 'cpi_9606.ENSP00000282091', 'f_414', 'cpi_9606.ENSP00000248553', 'cpi_9606.ENSP00000353791'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000296122', 'f_300', 'cpi_9606.ENSP00000362036'], ['f_623', 'cpi_9606.ENSP00000354280', 'cpi_9606.ENSP00000414303', 'f_250', 'f_610'], ['f_442', 'cpi_9606.ENSP00000249750', 'cpi_9606.ENSP00000356213', 'f_705', 'cpi_9606.ENSP00000225964'], ['f_599', 'cpi_9606.ENSP00000292147', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000402152', 'f_364'], ['f_437', 'cpi_9606.ENSP00000397026', 'cpi_9606.ENSP00000233242', 'f_249', 'cpi_9606.ENSP00000254810'], ['f_418', 'cpi_9606.ENSP00000211122', 'cpi_9606.ENSP00000386171', 'cpi_9606.ENSP00000324248', 'cpi_9606.ENSP00000364310'], ['f_1', 'cpi_9606.ENSP00000376914', 'cpi_9606.ENSP00000277120', 'cpi_9606.ENSP00000384273', 'f_395'], ['f_244', 'cpi_9606.ENSP00000309845', 'cpi_9606.ENSP00000321821', 'cpi_9606.ENSP00000255380', 'f_301'], ['f_574', 'cpi_9606.ENSP00000327255', 'cpi_9606.ENSP00000305302', 'cpi_9606.ENSP00000267163', 'f_515'], ['f_13', 'cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000302961', 'f_458', 'cpi_9606.ENSP00000341045'], ['f_708', 'cpi_9606.ENSP00000447378', 'cpi_9606.ENSP00000347979', 'f_612', 'cpi_9606.ENSP00000255030'], ['f_654', 'cpi_9606.ENSP00000299855', 'cpi_9606.ENSP00000352702', 'f_700', 'cpi_9606.ENSP00000419782'], ['f_550', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000276571', 'cpi_9606.ENSP00000234071', 'f_399'], ['cpi_9606.ENSP00000270349', 'f_601', 'cpi_9606.ENSP00000378699', 'cpi_9606.ENSP00000241600', 'f_694'], ['cpi_9606.ENSP00000367959', 'cpi_9606.ENSP00000301633', 'f_459', 'cpi_9606.ENSP00000351885', 'cpi_9606.ENSP00000454071'], ['f_655', 'cpi_9606.ENSP00000369442', 'cpi_9606.ENSP00000231188', 'f_532', 'cpi_9606.ENSP00000329623'], ['f_11', 'cpi_9606.ENSP00000417901', 'cpi_9606.ENSP00000351273', 'f_187', 'cpi_9606.ENSP00000303452'], ['f_688', 'cpi_9606.ENSP00000286621', 'cpi_9606.ENSP00000355920', 'f_206', 'cpi_9606.ENSP00000301146'], ['f_370', 'cpi_9606.ENSP00000221138', 'cpi_9606.ENSP00000338018', 'cpi_9606.ENSP00000303174', 'f_661'], ['cpi_9606.ENSP00000297494', 'f_716', 'cpi_9606.ENSP00000346298', 'cpi_9606.ENSP00000318646', 'f_383'], ['f_332', 'cpi_9606.ENSP00000226299', 'cpi_9606.ENSP00000361668', 'cpi_9606.ENSP00000354558', 'f_707'], ['f_255', 'cpi_9606.ENSP00000349576', 'cpi_9606.ENSP00000309493', 'f_563', 'cpi_9606.ENSP00000222002'], ['f_546', 'cpi_9606.ENSP00000263269', 'cpi_9606.ENSP00000368683', 'cpi_9606.ENSP00000265403', 'f_734'], ['f_333', 'cpi_9606.ENSP00000358727', 'cpi_9606.ENSP00000412237', 'f_544', 'cpi_9606.ENSP00000410294'], ['f_450', 'cpi_9606.ENSP00000252321', 'cpi_9606.ENSP00000341828', 'f_711', 'cpi_9606.ENSP00000365663'], ['f_607', 'cpi_9606.ENSP00000296046', 'cpi_9606.ENSP00000428824', 'cpi_9606.ENSP00000358784', 'cpi_9606.ENSP00000310928'], ['f_14', 'cpi_9606.ENSP00000244051', 'cpi_9606.ENSP00000231449', 'f_761', 'cpi_9606.ENSP00000388648'], ['f_251', 'cpi_9606.ENSP00000231509', 'cpi_9606.ENSP00

🔄 Processing features: 100%|██████████| 2147/2147 [10:14<00:00,  3.49feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'f_413', 'f_262', 'f_428', 'cpi_9606.ENSP00000357669'], ['f_308', 'cpi_9606.ENSP00000288139', 'f_616', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000352035'], ['f_374', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000297268', 'cpi_9606.ENSP00000295452'], ['f_20', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000295454'], ['f_406', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000376914', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000369375'], ['f_393', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000323867', 'f_151', 'cpi_9606.ENSP00000367851'], ['f_346', 'cpi_9606.ENSP00000279178', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000395653', 'f_629'], ['f_299', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000357336', 'cpi_9606.ENSP00000331912'], ['f_451', 'cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000254976', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000277010'], ['f_366', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000301891'], ['f_380', 'cpi_9606.ENSP00000356094', 'cpi_9606.ENSP00000263088', 'f_726', 'cpi_9606.ENSP00000342235'], ['f_614', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000332369', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000274547'], ['f_452', 'f_25', 'cpi_9606.ENSP00000378517', 'cpi_9606.ENSP00000259486', 'f_635'], ['f_672', 'cpi_9606.ENSP00000409007', 'f_292', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000261416'], ['f_3', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000337335', 'f_529'], ['f_643', 'cpi_9606.ENSP00000366927', 'cpi_9606.ENSP00000263126', 'f_866', 'cpi_9606.ENSP00000233146'], ['f_405', 'cpi_9606.ENSP00000368305', 'f_789', 'cpi_9606.ENSP00000221972', 'cpi_9606.ENSP00000264318'], ['f_440', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000367608', 'f_791', 'cpi_9606.ENSP00000345708'], ['f_391', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000364782', 'f_845', 'cpi_9606.ENSP00000304822'], ['f_23', 'cpi_9606.ENSP00000385026', 'f_195', 'cpi_9606.ENSP00000443194', 'f_118'], ['f_392', 'cpi_9606.ENSP00000261205', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000369654', 'cpi_9606.ENSP00000411593'], ['f_617', 'cpi_9606.ENSP00000394033', 'cpi_9606.ENSP00000241453', 'f_836', 'cpi_9606.ENSP00000367848'], ['f_186', 'cpi_9606.ENSP00000279387', 'f_31', 'cpi_9606.ENSP00000226574', 'f_436'], ['f_338', 'f_554', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000292896', 'cpi_9606.ENSP00000447149'], ['f_12', 'cpi_9606.ENSP00000264162', 'cpi_9606.ENSP00000355657', 'cpi_9606.ENSP00000414334', 'f_831'], ['f_339', 'f_297', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000262367', 'cpi_9606.ENSP00000251535'], ['f_566', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000355629', 'cpi_9606.ENSP00000428864', 'f_526'], ['f_696', 'cpi_9606.ENSP00000397582', 'f_511', 'cpi_9606.ENSP00000360773', 'f_47'], ['f_287', 'cpi_9606.ENSP00000241052', 'f_194', 'f_773', 'f_799'], ['f_335', 'f_815', 'cpi_9606.ENSP00000358107', 'cpi_9606.ENSP00000359635', 'cpi_9606.ENSP00000370381'], ['f_15', 'cpi_9606.ENSP00000346103', 'cpi_9606.ENSP00000330484', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000430684'], ['f_697', 'cpi_9606.ENSP00000229319', 'cpi_9606.ENSP00000309818', 'f_35', 'f_830'], ['f_33', 'cpi_9606.ENSP00000346768', 'f_706', 'f_350', 'f_510'], ['f_571', 'f_752', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000352011', 'f_736'], ['f_528', 'cpi_9606.ENSP00000216465', 'cpi_9606.ENSP00000354476', 'cpi_9606.ENSP00000299267', 'cpi_9606.ENSP00000352900'], ['f_341', 'cpi_9606.ENSP00000359353', 'cpi_9606.ENSP00000273398', 'f_768', 'cpi_9606.ENSP00000216037'], ['f_146', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000290349', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000350767'], ['f_659', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000397026', 'cpi_9606.ENSP00000261937', 'cpi_9606.ENSP00000360493'], ['f_143', 'cpi_9606.ENSP00000313490', 'f_27', 'f_330', 'cpi_9606.ENSP00000200676'], ['f_181', 'cpi_9606.ENSP00000370129', 'cpi_9606.ENSP00000314214', 'f_166', 'cpi_9606.ENSP00000266376'], ['f_37', 'cpi_9606.ENSP00000263321', 'cpi_9606.ENSP00000222390', 'f_229', 'f_328'], ['f_192', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000364212', 'cpi_9606.ENSP00000386029', 'f_46'], ['f_611', 'f_861', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000216185', 'f_788'], ['f_420', 'cpi_9606.ENSP00000337746', 'cpi_9606.ENSP00000225964', 'f_327', 'f_767'], ['f_569', 'cpi_9606.ENSP00000304811', 'f_214', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000295491'], ['f_712', 'cpi_9606.ENSP00000218548', 'f_725', 'f_834', 'cpi_9606.ENSP00000412673'], ['f_535', 'cpi_9606.ENSP00000262888', 'cpi_9606.ENSP00000349576', 'f_670', 'cpi_9606.ENSP00000258042'], ['f_185', 'cpi_9606.ENSP00000386284', 'cpi_9606.ENSP00000359793', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000297350'], ['f_2', 'cpi_9606.ENSP00000219794', 'cpi_9606.ENSP00000471569', 'cpi_9606.ENSP00000448059', 'cpi_9606.ENSP00000252029'], ['f_180', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000252809', 'cpi_9606.ENSP00000373477', 'f_408'], ['f_19', 'cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000398632', 'cpi_9606.ENSP00000394936'], ['f_285', 'cpi_9606.ENSP00000233944', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000264867', 'cpi_9606.ENSP00000301178'], ['f_656', 'cpi_9606.ENSP00000362924', 'cpi_9606.ENSP00000264637', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000319788'], ['f_443', 'cpi_9606.ENSP00000223366', 'cpi_9606.ENSP00000327850', 'f_509', 'f_785'], ['cpi_9606.ENSP00000311032', 'f_518', 'cpi_9606.ENSP00000348897', 'f_551', 'cpi_9606.ENSP00000327431'], ['f_516', 'cpi_9606.ENSP00000359100', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000348827', 'f_202'], ['f_540', 'cpi_9606.ENSP00000471397', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000318822', 'f_675'], ['f_257', 'cpi_9606.ENSP00000332549', 'cpi_9606.ENSP00000362513', 'cpi_9606.ENSP00000292513', 'f_361'], ['cpi_9606.ENSP00000353820', 'f_26', 'f_131', 'f_749', 'cpi_9606.ENSP00000286648'], ['f_638', 'cpi_9606.ENSP00000225275', 'f_242', 'f_728', 'cpi_9606.ENSP00000417229'], ['f_345', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000430031', 'cpi_9606.ENSP00000470087', 'cpi_9606.ENSP00000312664'], ['f_439', 'cpi_9606.ENSP00000254488', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000387683'], ['f_692', 'cpi_9606.ENSP00000313699', 'cpi_9606.ENSP00000310447', 'f_474', 'f_43'], ['f_646', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000261196', 'cpi_9606.ENSP00000332296'], ['f_615', 'f_839', 'cpi_9606.ENSP00000303540', 'f_729', 'cpi_9606.ENSP00000278616'], ['f_698', 'cpi_9606.ENSP00000364709', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000297316', 'f_497'], ['f_21', 'cpi_9606.ENSP00000306490', 'f_116', 'cpi_9606.ENSP00000343838', 'f_467'], ['f_145', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000254227', 'f_631'], ['f_639', 'f_533', 'f_417', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000299178'], ['cpi_9606.ENSP00000265724', 'f_401', 'f_427', 'f_764', 'f_471'], ['f_340', 'cpi_9606.ENSP00000306606', 'cpi_9606.ENSP00000293230', 'cpi_9606.ENSP00000451040', 'f_460'], ['f_390', 'cpi_9606.ENSP00000011292', 'cpi_9606.ENSP00000240652', 'cpi_9606.ENSP00000343477', 'f_587'], ['f_553', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000340943', 'cpi_9606.ENSP00000311469', 'cpi_9606.ENSP00000282561'], ['f_645', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000320401', 'cpi_9606.ENSP00000275216', 'cpi_9606.ENSP00000304408'], ['f_579', 'cpi_9606.ENSP00000354193', 'cpi_9606.ENSP00000176763', 'cpi_9606.ENSP00000344352', 'cpi_9606.ENSP00000387946'], ['cpi_9606.ENSP00000342007', 'f_343', 'cpi_9606.ENSP00000350616', 'f_347', 'f_167'], ['f_684', 'cpi_9606.ENSP00000234389', 'cpi_9606.ENSP00000387888', 'f_473', 'cpi_9606.ENSP00000231188'], ['f_642', 'cpi_9606.ENSP00000270142', 'f_494', 'f_466', 'f_757'], ['f_682', 'cpi_9606.ENSP00000325120', 'f_715', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000241256'], ['f_16', 'cpi_9606.ENSP00000237014', 'f_622', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000258749'], ['f_567', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000356954', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000291295'], ['f_293', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000301633', 'cpi_9606.ENSP00000435591', 'f_298'], ['f_680', 'cpi_9606.ENSP00000306100', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000259396', 'f_771'], ['f_593', 'f_719', 'cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000365663', 'cpi_9606.ENSP00000356958'], ['f_693', 'f_650', 'f_609', 'cpi_9606.ENSP00000353720', 'f_496'], ['f_24', 'f_38', 'f_216', 'cpi_9606.ENSP00000338018', 'cpi_9606.ENSP00000218099'], ['f_637', 'cpi_9606.ENSP00000305480', 'cpi_9606.ENSP00000286301', 'cpi_9606.ENSP00000343040', 'cpi_9606.ENSP00000359285'], ['f_368', 'cpi_9606.ENSP00000264708', 'f_398', 'f_812', 'cpi_9606.ENSP00000295400'], ['f_681', 'f_215', 'f_508', 'cpi_9606.ENSP00000260970', 'cpi_9606.ENSP00000378890'], ['f_353', 'cpi_9606.ENSP00000352835', 'cpi_9606.ENSP00000225474', 'cpi_9606.ENSP00000222330', 'f_826'], ['f_689', 'cpi_9606.ENSP00000229277', 'f_388', 'cpi_9606.ENSP00000309493', 'cpi_9606.ENSP00000312455'], ['f_704', 'cpi_9606.ENSP00000314649', 'cpi_9606.ENSP00000322421', 'f_792', 'f_475'], ['f_464', 'cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000265403', 'cpi_9606.ENSP00000218721', 'f_448'], ['f_691', 'cpi_9606.ENSP00000276431', 'cpi_9606.ENSP00000260010', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000358903'], ['f_628', 'cpi_9606.ENSP00000216714', 'cpi_9606.ENSP00000251566', 'cpi_9606.ENSP00000389338', 'f_455'], ['f_365', 'cpi_9606.ENSP00000287878', 'cpi_9606.ENSP00000255465', 'cpi_9606.ENSP00000326119', 'cpi_9606.ENSP00000267843'], ['f_686', 'f_456', 'cpi_9606.ENSP00000231751', 'f_813', 'f_568'], ['cpi_9606.ENSP00000360372', 'f_200', 'f_644', 'cpi_9606.ENSP00000264896', 'f_407'], ['f_248', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000356729', 'cpi_9606.ENSP00000308165', 'f_488'], ['f_671', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000362353', 'cpi_9606.ENSP00000270776', 'f_583'], ['cpi_9606.ENSP00000336528', 'f_34', 'cpi_9606.ENSP00000219833', 'f_477', 'cpi_9606.ENSP00000370373'], ['f_613', 'cpi_9606.ENSP00000405573', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000316786', 'cpi_9606.ENSP00000358548'], ['f_667', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000298352', 'f_778'], ['f_241', 'f_132', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000260649', 'f_505'], ['f_594', 'cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000370473', 'f_164'], ['cpi_9606.ENSP00000367959', 'f_129', 'f_22', 'cpi_9606.ENSP00000256958', 'cpi_9606.ENSP00000381097'], ['f_213', 'cpi_9606.ENSP00000356438', 'f_336', 'cpi_9606.ENSP00000355533', 'f_559'], ['f_663', 'cpi_9606.ENSP00000363868', 'f_750', 'cpi_9606.ENSP00000257290', 'cpi_9606.ENSP00000352608'], ['f_710', 'cpi_9606.ENSP00000354532', 'cpi_9606.ENSP00000263980', 'f_722', 'cpi_9606.ENSP00000361359'], ['f_560', 'f_840', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000314508', 'cpi_9606.ENSP00000353878'], ['f_537', 'cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000367102', 'f_207', 'cpi_9606.ENSP00000320935'], ['f_695', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000321988', 'f_522'], ['f_683', 'cpi_9606.ENSP00000276651', 'cpi_9606.ENSP00000347979', 'cpi_9606.ENSP00000262999', 'f_827'], ['f_337', 'cpi_9606.ENSP00000303211', 'f_770', 'cpi_9606.ENSP00000347942', 'cpi_9606.ENSP00000338082'], ['cpi_9606.ENSP00000337450', 'f_30', 'f_763', 'cpi_9606.ENSP00000354569', 'cpi_9606.ENSP00000351209'], ['f_349', 'cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000369038', 'cpi_9606.ENSP00000275525'], ['f_777', 'cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000359539', 'cpi_9606.ENSP00000293288', 'f_676'], ['f_580', 'cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000344192'], ['f_375', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000354107', 'cpi_9606.ENSP00000369703', 'f_558'], ['f_199', 'cpi_9606.ENSP00000385834', 'f_394', 'cpi_9606.ENSP00000307599', 'cpi_9606.ENSP00000246553'], ['f_641', 'cpi_9606.ENSP00000283635', 'cpi_9606.ENSP00000251453', 'cpi_9606.ENSP00000323568', 'cpi_9606.ENSP00000333212'], ['f_797', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000348069', 'f_833'], ['f_430', 'cpi_9606.ENSP00000274353', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000231454', 'cpi_9606.ENSP00000261799'], ['f_549', 'cpi_9606.ENSP00000234310', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000309124', 'f_230'], ['f_666', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000294954', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000357283'], ['f_688', 'cpi_9606.ENSP00000332139', 'cpi_9606.ENSP00000428340', 'cpi_9606.ENSP00000368104', 'cpi_9606.ENSP00000376943'], ['f_633', 'cpi_9606.ENSP00000296046', 'cpi_9606.ENSP00000291294', 'cpi_9606.ENSP00000366307', 'f_115'], ['f_493', 'cpi_9606.ENSP00000295453', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000457706', 'f_486'], ['f_708', 'cpi_9606.ENSP00000358727', 'cpi_9606.ENSP00000427514', 'f_409', 'f_425'], ['f_602', 'cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000429374', 'f_363'], ['f_332', 'cpi_9606.ENSP00000380318', 'cpi_9606.ENSP00000276449', 'f_820', 'f_782'], ['f_536', 'cpi_9606.ENSP00000287936', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000365380', 'f_742'], ['f_294', 'cpi_9606.ENSP00000302564', 'f_159', 'cpi_9606.ENSP00000319814', 'f_429'], ['f_755', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000261693', 'cpi_9606.ENSP00000225927', 'cpi_9606.ENSP00000459962'], ['f_699', 'cpi_9606.ENSP00000261755', 'f_422', 'cpi_9606.ENSP00000304895', 'f_513'], ['f_818', 'cpi_9606.ENSP00000333994', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000362401', 'f_454'], ['f_462', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000360967', 'cpi_9606.ENSP00000362344', 'cpi_9606.ENSP00000374323'], ['cpi_9606.ENSP00000283916', 'f_461', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000155840', 'f_740'], ['f_776', 'f_489', 'cpi_9606.ENSP00000261405', 'cpi_9606.ENSP00000372023', 'f_738'], ['f_333', 'cpi_9606.ENSP00000354850', 'cpi_9606.ENSP00000410076', 'cpi_9606.ENSP00000264498', 'f_653'], ['f_592', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000445340', 'cpi_9606.ENSP00000354394', 'f_822'], ['f_432', 'cpi_9606.ENSP00000352516', 'f_419', 'cpi_9606.ENSP00000232219', 'f_759'], ['f_798', 'cpi_9606.ENSP00000262623', 'f_717', 'cpi_9606.ENSP00000241261', 'f_480'], ['f_702', 'cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000351885', 'f_483'], ['cpi_9606.ENSP00000264381', 'f_713', 'f_588', 'cpi_9606.ENSP00000369816', 'f_465'], ['f_449', 'cpi_9606.ENSP00000353679', 'cpi_9606.ENSP00000331746', 'f_367', 'cpi_9606.ENSP00000252723'], ['f_586', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000302961', 'cpi_9606.ENSP00000303452', 'f_801'], ['f_18', 'cpi_9606.ENSP00000472933', 'cpi_9606.ENSP00000463999', 'cpi_9606.ENSP00000339527', 'f_517'], ['cpi_9606.ENSP00000295897', 'f_187', 'cpi_9606.ENSP00000242057', 'cpi_9606.ENSP00000371929', 'f_411'], ['f_502', 'cpi_9606.ENSP00000279593', 'cpi_9606.ENSP00000305221', 'cpi_9606.ENSP00000388825', 'f_803'], ['f_690', 'cpi_9606.ENSP00000368727', 'f_721', 'cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000358784'], ['f_604', 'cpi_9606.ENSP00000305742', 'cpi_9606.ENSP00000296871', 'cpi_9606.ENSP00000234071', 'f_160'], ['f_11', 'cpi_9606.ENSP00000226578', 'cpi_9606.ENSP00000301974', 'cpi_9606.ENSP00000329357', 'f_543'], ['f_619', 'cpi_9606.ENSP00000244217', 'cpi_9606.ENSP00000358595', 'f_359', 'cpi_9606.ENSP00000260356'], ['cpi_9606.ENSP00000258743', 'f_652', 'cpi_9606.ENSP00000338627', 'cpi_9606.ENSP00000351957', 'f_314'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000406157', 'f_421', 'f_625'], ['f_193', 'cpi_9606.ENSP00000284981', 'f_500', 'cpi_9606.ENSP00000335511', 'f_647'], ['f_150', 'cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000318585', 'cpi_9606.ENSP00000248553', 'f_805'], ['f_685', 'cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000221515'], ['f_597', 'cpi_9606.ENSP00000276414', 'cpi_9606.ENSP00000441691', 'cpi_9606.ENSP00000379802', 'f_621'], ['f_351', 'cpi_9606.ENSP00000297258', 'cpi_9606.ENSP00000277541', 'cpi_9606.ENSP00000434045', 'f_423'], ['f_665', 'cpi_9606.ENSP00000263269', 'cpi_9606.ENSP00000303325', 'cpi_9606.ENSP00000341045', 'f_605'], ['f_342', 'cpi_9606.ENSP00000411532', 'cpi_9606.ENSP00000296122', 'f_227', 'cpi_9606.ENSP00000356162'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000227758', 'f_17', 'cpi_9606.ENSP00000256010', 'cpi_9606.ENSP00000242375'], ['f_445', 'cpi_9606.ENSP00000290866', 'cpi_9606.ENSP00000262948', 'cpi_9606.ENSP00000353292', 'f_514'], ['f_573', 'cpi_9606.ENSP00000293190', 'cpi_9606.ENSP00000310405', 'cpi_9606.ENSP00000362508', 'f_397'], ['f_709', 'cpi_9606.ENSP00000286621', 'cpi_9606.ENSP00000311095', 'f_395', 'cpi_9606.ENSP00000380252'], ['f_334', 'cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000376776', 'f_737', 'cpi_9606.ENSP00000263339'], ['f_574', 'cpi_9606.ENSP00000219700', 'cpi_9606.ENSP00000312029', 'cpi_9606.ENSP00000389414', 'cpi_9606.ENSP00000300061'], ['cpi_9606.ENSP00000231509', 'f_305', 'cpi_9606.ENSP00000343204', 'f_13', 'cpi_9606.ENSP00000309968'], ['f_546', 'cpi_9606.ENSP00000240139', 'cpi_9606.ENSP00000294728', 'f_610', 'cpi_9606.ENSP00000361666'], ['f_498', 'cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000346598', 'f_780', 'cpi_9606.ENSP00000333534'], ['f_599', 'cpi_9606.ENSP00000364035', 'cpi_9606.ENSP00000365016', 'f_784', 'f_301'], ['f_657', 'cpi_9606.ENSP00000236671', 'cpi_9606.ENSP00000311028', 'cpi_9606.ENSP00000297313', 'f_705'], ['f_623', 'cpi_9606.ENSP00000298171', 'cpi_9606.ENSP00000219919', 'cpi_9606.ENSP00000262461', 'f_157'], ['f_442', 'cpi_9606.ENSP00000338160', 'cpi_9606.ENSP00000450399', 'f_575', 'f_860'], ['f_259', 'cpi_9606.ENSP00000353427', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000303522', 'f_700'], ['f_507', 'cpi_9606.ENSP00000220809', 'cpi_9606.ENSP00000300738', 'f_515', 'cpi_9606.ENSP00000385806'], ['f_581', 'cpi_9606.ENSP00000354511', 'f_383', 'cpi_9606.ENSP00000320866', 'cpi_9606.ENSP00000394932'], ['f_249', 'f_300', 'cpi_9606.ENSP00000337103', 'cpi_9606.ENSP00000382659', 'cpi_9606.ENSP00000365686'], ['f_370', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000364802', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000308549'], ['f_542', 'cpi_9606.ENSP00000260102', 'cpi_9606.ENSP00000304915', 'cpi_9606.ENSP00000216862', 'f_532'], ['f_244', 'cpi_9606.ENSP00000221930', 'cpi_9606.ENSP00000357981', 'cpi_9606.ENSP00000319170', 'cpi_9606.ENSP00000319984'], ['f_550', 'cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000393847', 'f_260', 'cpi_9606.ENSP00000339001'], ['f_821', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000254810', 'cpi_9606.ENSP00000267101'], ['f_377', 'cpi_9606.ENSP00000330393', 'cpi_9606.ENSP00000262407', 'f_144', 'cpi_9606.ENSP00000321106'], ['f_286', 'cpi_9606.ENSP00000383365', 'cpi_9606.ENSP00000296677', 'cpi_9606.ENSP00000391826', 'f_364'], ['cpi_9606.ENSP00000270349', 'f_687', 'cpi_9606.ENSP00000377192', 'cpi_9606.ENSP00000274793', 'f_378'], ['f_412', 'cpi_9606.ENSP00000382342', 'cpi_9606.ENSP00000337773', 'cpi_9606.ENSP00000226413', 'cpi_9606.ENSP00000454071'], ['f_437', 'cpi_9606.ENSP00000264426', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000310928', 'cpi_9606.ENSP00000350348'], ['f_418', 'cpi_9606.ENSP00000268695', 'cpi_9606.ENSP00000416293', 'f_630', 'cpi_9606.ENSP00000252486'], ['f_548', 'cpi_9606.ENSP00000327255', 'cpi_9606.ENSP00000359532', 'cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000325822'], ['f_607', 'cpi_9606.ENSP00000345096', 'cpi_9606.ENSP00000239849', 'f_563', 'cpi_9606.ENSP00000287641'], ['cpi_9606.ENSP00000398698', 'cpi_9606.

🔄 Processing features: 100%|██████████| 2147/2147 [10:15<00:00,  3.49feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'f_26', 'f_131', 'f_413', 'f_118'], ['f_308', 'cpi_9606.ENSP00000334198', 'f_629', 'cpi_9606.ENSP00000374323', 'cpi_9606.ENSP00000385026'], ['f_374', 'cpi_9606.ENSP00000354193', 'cpi_9606.ENSP00000355657', 'f_768', 'cpi_9606.ENSP00000470087'], ['f_20', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000347942', 'cpi_9606.ENSP00000277010'], ['f_393', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000323867', 'f_151', 'cpi_9606.ENSP00000367851'], ['f_346', 'cpi_9606.ENSP00000279178', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000395653', 'cpi_9606.ENSP00000394936'], ['f_366', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000402152', 'f_428', 'cpi_9606.ENSP00000369375'], ['f_3', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000367102', 'cpi_9606.ENSP00000312304', 'f_526'], ['f_380', 'cpi_9606.ENSP00000337773', 'f_726', 'cpi_9606.ENSP00000342235', 'cpi_9606.ENSP00000351957'], ['f_406', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000309649', 'f_616', 'cpi_9606.ENSP00000233146'], ['f_617', 'cpi_9606.ENSP00000390600', 'f_789', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000359334'], ['f_614', 'cpi_9606.ENSP00000274353', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000356094'], ['f_643', 'cpi_9606.ENSP00000345096', 'f_866', 'f_845', 'cpi_9606.ENSP00000354476'], ['f_299', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000282841', 'cpi_9606.ENSP00000355629'], ['f_452', 'f_25', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000360773', 'cpi_9606.ENSP00000259396'], ['f_392', 'cpi_9606.ENSP00000321584', 'cpi_9606.ENSP00000447149', 'f_31', 'f_510'], ['f_287', 'cpi_9606.ENSP00000241052', 'f_292', 'f_194', 'cpi_9606.ENSP00000349320'], ['f_405', 'cpi_9606.ENSP00000305742', 'cpi_9606.ENSP00000359353', 'f_831', 'cpi_9606.ENSP00000359424'], ['f_672', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000341885'], ['f_23', 'f_195', 'cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000353362', 'f_297'], ['f_391', 'cpi_9606.ENSP00000397026', 'cpi_9606.ENSP00000430684', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000352900'], ['f_440', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000263088', 'f_757', 'cpi_9606.ENSP00000378517'], ['f_697', 'cpi_9606.ENSP00000264162', 'cpi_9606.ENSP00000414334', 'f_511', 'f_725'], ['f_37', 'f_229', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000263321', 'f_475'], ['f_146', 'cpi_9606.ENSP00000254976', 'cpi_9606.ENSP00000226444', 'f_529', 'cpi_9606.ENSP00000304822'], ['cpi_9606.ENSP00000311032', 'f_43', 'cpi_9606.ENSP00000352011', 'f_164', 'f_587'], ['f_638', 'cpi_9606.ENSP00000312286', 'f_670', 'cpi_9606.ENSP00000451040', 'f_836'], ['f_143', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000319170', 'cpi_9606.ENSP00000389338', 'f_27'], ['f_571', 'cpi_9606.ENSP00000360967', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000288139', 'f_815'], ['f_2', 'cpi_9606.ENSP00000222481', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000356832', 'f_788'], ['f_335', 'f_752', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000295454', 'cpi_9606.ENSP00000305422'], ['f_712', 'f_830', 'cpi_9606.ENSP00000218548', 'f_35', 'f_834'], ['f_186', 'cpi_9606.ENSP00000262407', 'f_635', 'cpi_9606.ENSP00000445340', 'cpi_9606.ENSP00000435591'], ['f_12', 'cpi_9606.ENSP00000261205', 'cpi_9606.ENSP00000262367', 'f_509', 'f_773'], ['f_613', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000312455'], ['f_185', 'cpi_9606.ENSP00000386284', 'cpi_9606.ENSP00000362403', 'cpi_9606.ENSP00000260010', 'f_47'], ['f_33', 'cpi_9606.ENSP00000346768', 'f_706', 'f_350', 'f_417'], ['f_192', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000334105', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000286479'], ['f_420', 'cpi_9606.ENSP00000285900', 'f_328', 'cpi_9606.ENSP00000267101', 'cpi_9606.ENSP00000216862'], ['f_639', 'f_715', 'cpi_9606.ENSP00000386306', 'f_427', 'cpi_9606.ENSP00000410732'], ['f_15', 'cpi_9606.ENSP00000354610', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000267017', 'cpi_9606.ENSP00000216037'], ['f_535', 'cpi_9606.ENSP00000376914', 'f_327', 'f_497', 'cpi_9606.ENSP00000427514'], ['f_181', 'cpi_9606.ENSP00000273550', 'cpi_9606.ENSP00000264637', 'cpi_9606.ENSP00000301891', 'cpi_9606.ENSP00000471569'], ['f_338', 'cpi_9606.ENSP00000331746', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000257290'], ['f_696', 'cpi_9606.ENSP00000368305', 'f_767', 'cpi_9606.ENSP00000221972', 'f_46'], ['f_566', 'cpi_9606.ENSP00000358107', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000332296', 'cpi_9606.ENSP00000245457'], ['f_451', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000389414'], ['f_528', 'cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000274547', 'cpi_9606.ENSP00000252809'], ['f_339', 'cpi_9606.ENSP00000376432', 'f_554', 'f_799', 'f_771'], ['f_257', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000362513', 'cpi_9606.ENSP00000222330'], ['f_540', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000220616', 'cpi_9606.ENSP00000307599', 'cpi_9606.ENSP00000296370'], ['f_19', 'cpi_9606.ENSP00000472933', 'f_330', 'cpi_9606.ENSP00000333212', 'cpi_9606.ENSP00000286301'], ['f_390', 'cpi_9606.ENSP00000233944', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000366307', 'f_436'], ['f_285', 'cpi_9606.ENSP00000287878', 'cpi_9606.ENSP00000387946', 'cpi_9606.ENSP00000263980', 'f_583'], ['f_340', 'cpi_9606.ENSP00000349576', 'cpi_9606.ENSP00000246553', 'cpi_9606.ENSP00000365016', 'cpi_9606.ENSP00000319788'], ['f_656', 'cpi_9606.ENSP00000234389', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000309572', 'f_460'], ['f_341', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000273398', 'f_778', 'cpi_9606.ENSP00000354394'], ['cpi_9606.ENSP00000342007', 'f_347', 'cpi_9606.ENSP00000299178', 'f_675', 'f_736'], ['f_345', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000272227', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000258749'], ['f_659', 'cpi_9606.ENSP00000305302', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000302846', 'cpi_9606.ENSP00000361359'], ['f_569', 'cpi_9606.ENSP00000237014', 'f_214', 'cpi_9606.ENSP00000343477', 'f_622'], ['f_692', 'cpi_9606.ENSP00000314649', 'f_473', 'cpi_9606.ENSP00000262948', 'cpi_9606.ENSP00000353292'], ['f_365', 'cpi_9606.ENSP00000226578', 'cpi_9606.ENSP00000312029', 'cpi_9606.ENSP00000316786', 'f_505'], ['f_611', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000362401', 'f_298'], ['f_698', 'cpi_9606.ENSP00000364709', 'cpi_9606.ENSP00000367848', 'cpi_9606.ENSP00000297316', 'f_474'], ['f_646', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000261196', 'cpi_9606.ENSP00000262888'], ['f_432', 'cpi_9606.ENSP00000363868', 'cpi_9606.ENSP00000291295', 'f_729', 'f_166'], ['f_689', 'cpi_9606.ENSP00000332256', 'f_388', 'cpi_9606.ENSP00000344352', 'cpi_9606.ENSP00000260191'], ['f_248', 'f_262', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000282753', 'cpi_9606.ENSP00000365686'], ['f_684', 'cpi_9606.ENSP00000354850', 'cpi_9606.ENSP00000358548', 'f_466', 'f_820'], ['f_443', 'cpi_9606.ENSP00000354554', 'cpi_9606.ENSP00000339527', 'f_785', 'f_202'], ['f_553', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000340943', 'f_207', 'cpi_9606.ENSP00000428864'], ['f_645', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000262160', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000266376'], ['f_699', 'f_488', 'cpi_9606.ENSP00000261755', 'f_792', 'f_791'], ['f_516', 'cpi_9606.ENSP00000397582', 'f_749', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000225474'], ['f_293', 'cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000283635', 'f_826', 'f_827'], ['cpi_9606.ENSP00000353820', 'f_408', 'f_522', 'f_812', 'f_551'], ['f_180', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000356436'], ['f_683', 'cpi_9606.ENSP00000248935', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000231228', 'cpi_9606.ENSP00000300061'], ['cpi_9606.ENSP00000270349', 'f_132', 'f_361', 'f_687', 'cpi_9606.ENSP00000301645'], ['f_579', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000164139', 'cpi_9606.ENSP00000365380', 'f_496'], ['f_615', 'f_839', 'cpi_9606.ENSP00000225275', 'f_419', 'cpi_9606.ENSP00000417229'], ['f_681', 'f_215', 'cpi_9606.ENSP00000342070', 'f_568', 'cpi_9606.ENSP00000221421'], ['f_682', 'cpi_9606.ENSP00000417281', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000356954', 'f_483'], ['f_16', 'cpi_9606.ENSP00000360608', 'f_242', 'cpi_9606.ENSP00000343040', 'cpi_9606.ENSP00000251535'], ['f_375', 'f_840', 'f_631', 'cpi_9606.ENSP00000337103', 'cpi_9606.ENSP00000320025'], ['cpi_9606.ENSP00000360372', 'f_200', 'f_763', 'f_508', 'cpi_9606.ENSP00000261799'], ['f_24', 'f_216', 'cpi_9606.ENSP00000306245', 'cpi_9606.ENSP00000358223', 'f_159'], ['f_642', 'f_407', 'f_429', 'f_750', 'cpi_9606.ENSP00000333994'], ['f_464', 'cpi_9606.ENSP00000234310', 'cpi_9606.ENSP00000255465', 'cpi_9606.ENSP00000360493', 'f_764'], ['f_567', 'cpi_9606.ENSP00000348069', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000320866', 'f_477'], ['f_333', 'cpi_9606.ENSP00000358727', 'cpi_9606.ENSP00000457706', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000308165'], ['f_704', 'cpi_9606.ENSP00000367123', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000311095', 'f_676'], ['f_439', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000270625', 'cpi_9606.ENSP00000398632', 'f_861'], ['f_641', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000246337', 'cpi_9606.ENSP00000337335', 'cpi_9606.ENSP00000344192'], ['f_667', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000292896', 'cpi_9606.ENSP00000408860', 'f_343'], ['f_663', 'f_813', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000242057', 'cpi_9606.ENSP00000274545'], ['f_241', 'cpi_9606.ENSP00000374467', 'f_129', 'f_401', 'cpi_9606.ENSP00000357283'], ['f_581', 'cpi_9606.ENSP00000285979', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000308774', 'f_728'], ['f_536', 'f_833', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000369654', 'cpi_9606.ENSP00000320935'], ['f_691', 'cpi_9606.ENSP00000296871', 'cpi_9606.ENSP00000268053', 'cpi_9606.ENSP00000262187', 'f_486'], ['f_686', 'cpi_9606.ENSP00000347754', 'f_650', 'cpi_9606.ENSP00000355930', 'cpi_9606.ENSP00000381097'], ['f_637', 'cpi_9606.ENSP00000219240', 'cpi_9606.ENSP00000260227', 'cpi_9606.ENSP00000261937', 'cpi_9606.ENSP00000312664'], ['f_199', 'cpi_9606.ENSP00000385834', 'f_394', 'f_409', 'cpi_9606.ENSP00000330393'], ['cpi_9606.ENSP00000367959', 'f_588', 'f_314', 'cpi_9606.ENSP00000366662', 'f_782'], ['cpi_9606.ENSP00000356438', 'f_213', 'f_336', 'f_448', 'cpi_9606.ENSP00000345708'], ['f_502', 'cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000275525', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000309124'], ['f_666', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000330484', 'cpi_9606.ENSP00000252723', 'f_609'], ['f_602', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000362036', 'f_116'], ['f_777', 'f_494', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000305692', 'f_770'], ['f_145', 'cpi_9606.ENSP00000354511', 'cpi_9606.ENSP00000376943', 'f_719', 'f_722'], ['f_680', 'cpi_9606.ENSP00000366927', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000410294', 'cpi_9606.ENSP00000326119'], ['f_351', 'cpi_9606.ENSP00000380318', 'cpi_9606.ENSP00000251566', 'f_167', 'f_740'], ['f_619', 'cpi_9606.ENSP00000399168', 'cpi_9606.ENSP00000331912', 'cpi_9606.ENSP00000346598', 'f_647'], ['f_593', 'cpi_9606.ENSP00000270142', 'f_455', 'cpi_9606.ENSP00000294728', 'f_822'], ['f_573', 'cpi_9606.ENSP00000364035', 'cpi_9606.ENSP00000301178', 'cpi_9606.ENSP00000231454', 'f_30'], ['f_337', 'cpi_9606.ENSP00000303211', 'f_644', 'f_513', 'cpi_9606.ENSP00000342560'], ['f_690', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000260970', 'f_461', 'cpi_9606.ENSP00000282561'], ['cpi_9606.ENSP00000265724', 'f_423', 'cpi_9606.ENSP00000359532', 'cpi_9606.ENSP00000295491', 'f_115'], ['f_368', 'cpi_9606.ENSP00000362525', 'f_518', 'cpi_9606.ENSP00000298171', 'cpi_9606.ENSP00000371929'], ['f_671', 'cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000252486', 'f_160'], ['f_150', 'cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000318585', 'cpi_9606.ENSP00000248553', 'f_543'], ['f_597', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000265171', 'f_411', 'f_230'], ['f_537', 'cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000321988', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000261693'], ['f_709', 'cpi_9606.ENSP00000364782', 'cpi_9606.ENSP00000329357', 'cpi_9606.ENSP00000361666', 'f_471'], ['f_353', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000256958', 'cpi_9606.ENSP00000351209', 'cpi_9606.ENSP00000350348'], ['f_294', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000368880', 'cpi_9606.ENSP00000276449'], ['cpi_9606.ENSP00000264381', 'f_458', 'f_625', 'f_227', 'cpi_9606.ENSP00000263126'], ['f_259', 'cpi_9606.ENSP00000216714', 'cpi_9606.ENSP00000370473', 'cpi_9606.ENSP00000308845', 'f_533'], ['f_797', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000259089', 'f_34'], ['f_430', 'cpi_9606.ENSP00000039007', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000293288', 'f_558'], ['f_818', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000332369', 'cpi_9606.ENSP00000463999', 'f_742'], ['f_693', 'f_517', 'cpi_9606.ENSP00000317842', 'cpi_9606.ENSP00000274026', 'cpi_9606.ENSP00000319984'], ['f_586', 'cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000419782', 'cpi_9606.ENSP00000428340'], ['f_560', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000278175', 'f_398'], ['f_594', 'cpi_9606.ENSP00000357669', 'cpi_9606.ENSP00000274793', 'cpi_9606.ENSP00000262352', 'f_422'], ['f_776', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000266682', 'f_489'], ['f_710', 'cpi_9606.ENSP00000216962', 'cpi_9606.ENSP00000298283', 'cpi_9606.ENSP00000267163', 'f_454'], ['cpi_9606.ENSP00000295897', 'f_187', 'f_514', 'cpi_9606.ENSP00000410076', 'cpi_9606.ENSP00000291700'], ['f_18', 'cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000297268', 'cpi_9606.ENSP00000355317', 'f_738'], ['f_21', 'cpi_9606.ENSP00000276198', 'cpi_9606.ENSP00000303174', 'cpi_9606.ENSP00000267119', 'f_759'], ['f_550', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000275300', 'cpi_9606.ENSP00000355533', 'f_157'], ['f_695', 'cpi_9606.ENSP00000301633', 'cpi_9606.ENSP00000356825', 'f_467', 'f_860'], ['f_628', 'cpi_9606.ENSP00000279387', 'cpi_9606.ENSP00000260356', 'f_653', 'cpi_9606.ENSP00000300900'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000380247', 'f_17', 'cpi_9606.ENSP00000348645', 'cpi_9606.ENSP00000299267'], ['f_702', 'cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000234071', 'f_780', 'cpi_9606.ENSP00000290349'], ['f_342', 'cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000331358', 'cpi_9606.ENSP00000222002', 'f_152'], ['f_349', 'cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000296522', 'cpi_9606.ENSP00000317379', 'cpi_9606.ENSP00000200676'], ['f_507', 'cpi_9606.ENSP00000355627', 'cpi_9606.ENSP00000254066', 'f_801', 'f_425'], ['f_442', 'cpi_9606.ENSP00000254488', 'cpi_9606.ENSP00000311028', 'cpi_9606.ENSP00000304915', 'cpi_9606.ENSP00000448059'], ['f_685', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000262623', 'f_251', 'f_456'], ['f_11', 'cpi_9606.ENSP00000471397', 'cpi_9606.ENSP00000264657', 'f_559', 'cpi_9606.ENSP00000369530'], ['f_462', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000309818', 'cpi_9606.ENSP00000256383', 'f_363'], ['cpi_9606.ENSP00000272190', 'f_612', 'f_575', 'cpi_9606.ENSP00000253727', 'cpi_9606.ENSP00000270776'], ['f_758', 'cpi_9606.ENSP00000352835', 'f_480', 'f_144', 'cpi_9606.ENSP00000318822'], ['f_655', 'cpi_9606.ENSP00000219700', 'cpi_9606.ENSP00000359635', 'f_359', 'cpi_9606.ENSP00000382659'], ['f_332', 'cpi_9606.ENSP00000337746', 'cpi_9606.ENSP00000310405', 'f_721', 'cpi_9606.ENSP00000233242'], ['cpi_9606.ENSP00000337450', 'f_22', 'cpi_9606.ENSP00000301634', 'cpi_9606.ENSP00000292513', 'f_421'], ['f_493', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000332549', 'cpi_9606.ENSP00000255380', 'f_367'], ['f_623', 'cpi_9606.ENSP00000276414', 'cpi_9606.ENSP00000311469', 'cpi_9606.ENSP00000278616', 'cpi_9606.ENSP00000326219'], ['f_688', 'cpi_9606.ENSP00000354532', 'cpi_9606.ENSP00000385806', 'f_805', 'cpi_9606.ENSP00000359663'], ['f_1', 'cpi_9606.ENSP00000226299', 'cpi_9606.ENSP00000296677', 'f_784', 'cpi_9606.ENSP00000304895'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000295589', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000352584', 'f_694'], ['f_412', 'cpi_9606.ENSP00000003084', 'cpi_9606.ENSP00000354558', 'f_717', 'cpi_9606.ENSP00000359793'], ['f_701', 'cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000355778', 'f_716', 'cpi_9606.ENSP00000358784'], ['f_449', 'cpi_9606.ENSP00000263269', 'cpi_9606.ENSP00000343925', 'f_803', 'cpi_9606.ENSP00000296122'], ['f_819', 'cpi_9606.ENSP00000220764', 'cpi_9606.ENSP00000267843', 'f_414', 'cpi_9606.ENSP00000308549'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000272847', 'cpi_9606.ENSP00000362649', 'f_737', 'cpi_9606.ENSP00000297350'], ['f_498', 'cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000241600', 'f_397', 'cpi_9606.ENSP00000364310'], ['f_574', 'cpi_9606.ENSP00000364212', 'cpi_9606.ENSP00000370381', 'cpi_9606.ENSP00000255030', 'f_395'], ['f_633', 'cpi_9606.ENSP00000264426', 'cpi_9606.ENSP00000231449', 'f_605', 'cpi_9606.ENSP00000302111'], ['f_654', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000295731', 'cpi_9606.ENSP00000409378', 'f_705'], ['f_548', 'cpi_9606.ENSP00000371236', 'cpi_9606.ENSP00000239938', 'f_500', 'cpi_9606.ENSP00000325822'], ['f_708', 'cpi_9606.ENSP00000330032', 'cpi_9606.ENSP00000355920', 'cpi_9606.ENSP00000391826', 'f_652'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000216540', 'f_734', 'cpi_9606.ENSP00000328808', 'f_301'], ['cpi_9606.ENSP00000354612', 'f_610', 'cpi_9606.ENSP00000358730', 'cpi_9606.ENSP00000263923', 'cpi_9606.ENSP00000364802'], ['f_549', 'cpi_9606.ENSP00000314214', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000287936', 'cpi_9606.ENSP00000307014'], ['f_352', 'cpi_9606.ENSP00000383365', 'cpi_9606.ENSP00000419692', 'f_465', 'f_206'], ['cpi_9606.ENSP00000324648', 'f_707', 'cpi_9606.ENSP00000459962', 'cpi_9606.ENSP00000353427', 'f_305'], ['f_592', 'cpi_9606.ENSP00000011292', 'cpi_9606.ENSP00000303248', 'cpi_9606.ENSP00000226574', 'f_38'], ['f_286', 'cpi_9606.ENSP00000430031', 'cpi_9606.ENSP00000416293', 'f_364', 'f_260'], ['f_798', 'cpi_9606.ENSP00000364731', 'f_485', 'cpi_9606.ENSP00000428924', 'f_532'], ['f_334', 'cpi_9606.ENSP00000396308', 'f_515', 'cpi_9606.ENSP00000295834', 'cpi_9606.ENSP00000307259'], ['cpi_9606.ENSP00000258743', 'cpi_9606.ENSP00000264818', 'f_630', 'cpi_9606.ENSP00000365663', 'f_658'], ['f_437', 'cpi_9606.ENSP00000279593', 'f_249', 'cpi_9606.ENSP00000388825', 'cpi_9606.ENSP00000309103'], ['f_13', 'cpi_9606.ENSP00000301141', 'cpi_9606.ENSP00000353915', 'cpi_9606.ENSP00000323568', 'f_378'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000234961', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000353791', 'f_399'], ['f_188', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000353224', 'cpi_9606.ENSP00000360973', 'cpi_9606.ENSP00000330199'], ['f_445', 'cpi_9606.ENSP00000335620', 'cpi_9606.ENSP00000291294', 'cpi_9606.ENSP00000454071', 'f_711'], ['f_370', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000346103', 'cpi_9606.ENSP00000241261', 'f_621'], ['f_555', 'cpi_9606.ENSP00000378699', 'cpi_9606.ENSP00000346298', 'cpi_9606.ENSP00000411658', 'cpi_9606.ENSP00000302967'], ['f_450', 'cpi_9606.ENSP00000252321', 'cpi_9606.ENSP00000387699', 'cpi_9606.ENSP00000349577', 'f_700'], ['f_356', 'cpi_9606.ENSP00000378306', 'cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000303452', 'f_563'], ['f_662', 'cpi_9606.ENSP00000368727', 'cpi_9606.ENSP00000366506', 'f_457', 'cpi_9606.ENSP00000225964'], ['f_580', 'cpi_9606.ENSP00000295453', 'cpi_9606.ENSP00000301974', 'cpi_9606.ENSP000002120

🔄 Processing features: 100%|██████████| 2147/2147 [10:15<00:00,  3.49feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'f_413', 'cpi_9606.ENSP00000431512', 'f_436', 'cpi_9606.ENSP00000356094'], ['f_20', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000359353', 'cpi_9606.ENSP00000354193'], ['f_308', 'cpi_9606.ENSP00000355192', 'f_616', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000333212'], ['f_374', 'cpi_9606.ENSP00000251595', 'cpi_9606.ENSP00000222256', 'f_771', 'f_831'], ['f_346', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000279178', 'cpi_9606.ENSP00000395653', 'cpi_9606.ENSP00000324856'], ['f_299', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000234590', 'f_151', 'cpi_9606.ENSP00000274793'], ['f_393', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000380318', 'cpi_9606.ENSP00000355629'], ['f_406', 'cpi_9606.ENSP00000394033', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000386306', 'f_629'], ['f_440', 'f_25', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000378517'], ['f_392', 'cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000254066', 'f_31', 'f_510'], ['f_366', 'cpi_9606.ENSP00000402608', 'cpi_9606.ENSP00000367848', 'f_428', 'cpi_9606.ENSP00000394936'], ['f_380', 'cpi_9606.ENSP00000263088', 'cpi_9606.ENSP00000221421', 'f_789', 'cpi_9606.ENSP00000351957'], ['f_452', 'cpi_9606.ENSP00000351209', 'f_726', 'cpi_9606.ENSP00000275300', 'f_635'], ['f_3', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000307599', 'cpi_9606.ENSP00000262352', 'f_834'], ['f_614', 'cpi_9606.ENSP00000386284', 'cpi_9606.ENSP00000295452', 'f_429', 'cpi_9606.ENSP00000344352'], ['f_451', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000264162', 'cpi_9606.ENSP00000277010', 'f_845'], ['f_37', 'cpi_9606.ENSP00000409007', 'f_229', 'f_27', 'cpi_9606.ENSP00000293745'], ['f_15', 'cpi_9606.ENSP00000397582', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000430684'], ['f_12', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000354850', 'cpi_9606.ENSP00000414334', 'cpi_9606.ENSP00000304822'], ['f_672', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000362353', 'cpi_9606.ENSP00000265294'], ['f_571', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000352702', 'f_554', 'cpi_9606.ENSP00000301891'], ['f_405', 'cpi_9606.ENSP00000305742', 'f_792', 'f_676', 'f_768'], ['f_338', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000321584', 'cpi_9606.ENSP00000257290', 'cpi_9606.ENSP00000294728'], ['f_420', 'cpi_9606.ENSP00000312326', 'f_328', 'f_836', 'cpi_9606.ENSP00000353292'], ['f_617', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000366662'], ['f_23', 'cpi_9606.ENSP00000350616', 'f_408', 'f_292', 'f_164'], ['f_528', 'cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000362508', 'f_460', 'cpi_9606.ENSP00000261196'], ['f_143', 'cpi_9606.ENSP00000254976', 'cpi_9606.ENSP00000359424', 'f_529', 'cpi_9606.ENSP00000349577'], ['f_643', 'cpi_9606.ENSP00000345096', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000354476'], ['f_391', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000313490', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000282561'], ['f_339', 'cpi_9606.ENSP00000256383', 'f_297', 'cpi_9606.ENSP00000295454', 'cpi_9606.ENSP00000353362'], ['f_146', 'cpi_9606.ENSP00000249750', 'f_526', 'cpi_9606.ENSP00000450399', 'f_587'], ['f_569', 'cpi_9606.ENSP00000279387', 'f_214', 'cpi_9606.ENSP00000305221', 'cpi_9606.ENSP00000300900'], ['f_19', 'cpi_9606.ENSP00000472933', 'cpi_9606.ENSP00000286301', 'cpi_9606.ENSP00000300061', 'f_773'], ['f_639', 'f_778', 'cpi_9606.ENSP00000292896', 'f_670', 'f_511'], ['f_287', 'cpi_9606.ENSP00000241052', 'f_118', 'f_194', 'f_47'], ['f_185', 'cpi_9606.ENSP00000368305', 'cpi_9606.ENSP00000221972', 'cpi_9606.ENSP00000258749', 'cpi_9606.ENSP00000389338'], ['f_535', 'cpi_9606.ENSP00000262888', 'cpi_9606.ENSP00000353791', 'f_509', 'cpi_9606.ENSP00000365016'], ['cpi_9606.ENSP00000353820', 'f_26', 'f_131', 'cpi_9606.ENSP00000360773', 'f_812'], ['f_335', 'f_815', 'cpi_9606.ENSP00000274353', 'cpi_9606.ENSP00000471569', 'f_813'], ['f_566', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000332296'], ['f_285', 'cpi_9606.ENSP00000287878', 'f_866', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000296370'], ['f_659', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000329357', 'cpi_9606.ENSP00000261937'], ['cpi_9606.ENSP00000342007', 'f_347', 'f_43', 'f_466', 'f_166'], ['f_186', 'cpi_9606.ENSP00000283635', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000355657', 'f_448'], ['f_192', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000218548', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000286479'], ['f_656', 'cpi_9606.ENSP00000364035', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000309124', 'cpi_9606.ENSP00000263321'], ['f_2', 'cpi_9606.ENSP00000330032', 'cpi_9606.ENSP00000364802', 'f_788', 'cpi_9606.ENSP00000319788'], ['cpi_9606.ENSP00000311032', 'f_207', 'f_675', 'f_522', 'f_830'], ['f_257', 'cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000216540', 'f_202'], ['f_579', 'cpi_9606.ENSP00000234389', 'cpi_9606.ENSP00000328173', 'f_330', 'f_725'], ['f_181', 'cpi_9606.ENSP00000273550', 'cpi_9606.ENSP00000263126', 'cpi_9606.ENSP00000242057', 'cpi_9606.ENSP00000445340'], ['f_33', 'f_706', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000355536', 'f_350'], ['f_443', 'cpi_9606.ENSP00000223366', 'cpi_9606.ENSP00000273398', 'f_327', 'f_497'], ['f_341', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000220003', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000263464'], ['f_697', 'cpi_9606.ENSP00000357669', 'cpi_9606.ENSP00000323568', 'cpi_9606.ENSP00000342235', 'cpi_9606.ENSP00000417229'], ['cpi_9606.ENSP00000356438', 'f_213', 'f_343', 'f_653', 'f_262'], ['f_390', 'cpi_9606.ENSP00000330484', 'cpi_9606.ENSP00000264637', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000314099'], ['f_696', 'cpi_9606.ENSP00000319531', 'cpi_9606.ENSP00000374323', 'f_767', 'f_46'], ['f_712', 'cpi_9606.ENSP00000262623', 'f_35', 'f_729', 'f_736'], ['f_439', 'cpi_9606.ENSP00000330199', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000367851', 'cpi_9606.ENSP00000245539'], ['cpi_9606.ENSP00000265724', 'f_455', 'f_427', 'f_722', 'f_799'], ['f_646', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000251453', 'cpi_9606.ENSP00000225927'], ['f_340', 'cpi_9606.ENSP00000306606', 'cpi_9606.ENSP00000362403', 'cpi_9606.ENSP00000360493', 'cpi_9606.ENSP00000312455'], ['f_553', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000340943', 'cpi_9606.ENSP00000454071', 'cpi_9606.ENSP00000343477'], ['f_671', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000272847', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000457706'], ['f_638', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000348827', 'f_820'], ['f_692', 'cpi_9606.ENSP00000225964', 'cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000259271', 'cpi_9606.ENSP00000389414'], ['f_681', 'f_215', 'cpi_9606.ENSP00000385026', 'f_417', 'f_568'], ['f_645', 'cpi_9606.ENSP00000254488', 'cpi_9606.ENSP00000296412', 'f_861', 'cpi_9606.ENSP00000266376'], ['f_684', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000305692', 'f_474', 'cpi_9606.ENSP00000232219'], ['f_540', 'cpi_9606.ENSP00000367123', 'cpi_9606.ENSP00000387946', 'cpi_9606.ENSP00000448059', 'cpi_9606.ENSP00000312664'], ['f_698', 'cpi_9606.ENSP00000364709', 'f_388', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000376776'], ['f_145', 'cpi_9606.ENSP00000335620', 'f_631', 'cpi_9606.ENSP00000256958', 'f_715'], ['f_180', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000252809', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000299178'], ['f_16', 'f_242', 'cpi_9606.ENSP00000360608', 'f_719', 'cpi_9606.ENSP00000251535'], ['f_683', 'cpi_9606.ENSP00000314649', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000419782', 'cpi_9606.ENSP00000366307'], ['f_691', 'f_839', 'cpi_9606.ENSP00000358107', 'cpi_9606.ENSP00000216037', 'cpi_9606.ENSP00000335511'], ['f_602', 'cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000295834'], ['f_611', 'cpi_9606.ENSP00000318585', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000428340'], ['f_613', 'cpi_9606.ENSP00000354610', 'cpi_9606.ENSP00000346103', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000316786'], ['f_637', 'cpi_9606.ENSP00000332256', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000463999', 'f_757'], ['f_293', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000301633', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000261205'], ['f_615', 'cpi_9606.ENSP00000369927', 'f_419', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000359100'], ['f_667', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000244217', 'f_361', 'cpi_9606.ENSP00000347942'], ['f_567', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000319814', 'f_749', 'cpi_9606.ENSP00000252486'], ['f_21', 'cpi_9606.ENSP00000306490', 'f_116', 'f_752', 'cpi_9606.ENSP00000267119'], ['f_516', 'cpi_9606.ENSP00000362329', 'cpi_9606.ENSP00000427514', 'f_298', 'cpi_9606.ENSP00000337335'], ['f_704', 'cpi_9606.ENSP00000441691', 'cpi_9606.ENSP00000254810', 'f_473', 'cpi_9606.ENSP00000451040'], ['f_294', 'cpi_9606.ENSP00000270142', 'f_230', 'cpi_9606.ENSP00000367102', 'cpi_9606.ENSP00000233242'], ['f_682', 'cpi_9606.ENSP00000363868', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000341828', 'f_840'], ['f_375', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000378323', 'f_782', 'f_827'], ['f_680', 'cpi_9606.ENSP00000305480', 'cpi_9606.ENSP00000225474', 'cpi_9606.ENSP00000264867', 'f_791'], ['f_432', 'cpi_9606.ENSP00000353720', 'f_533', 'f_486', 'f_167'], ['f_345', 'cpi_9606.ENSP00000277508', 'cpi_9606.ENSP00000346148', 'cpi_9606.ENSP00000337128', 'f_583'], ['f_693', 'f_650', 'cpi_9606.ENSP00000289753', 'f_496', 'cpi_9606.ENSP00000369530'], ['f_573', 'cpi_9606.ENSP00000293190', 'cpi_9606.ENSP00000252723', 'cpi_9606.ENSP00000470087', 'f_728'], ['f_560', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000311028', 'cpi_9606.ENSP00000358223', 'f_394'], ['f_689', 'cpi_9606.ENSP00000354532', 'cpi_9606.ENSP00000354394', 'cpi_9606.ENSP00000343040', 'cpi_9606.ENSP00000325822'], ['f_597', 'cpi_9606.ENSP00000266682', 'cpi_9606.ENSP00000312673', 'f_407', 'cpi_9606.ENSP00000311095'], ['f_353', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000368880', 'f_551', 'f_763'], ['cpi_9606.ENSP00000367959', 'f_129', 'f_22', 'cpi_9606.ENSP00000261799', 'cpi_9606.ENSP00000301634'], ['f_663', 'f_750', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000357204', 'f_508'], ['cpi_9606.ENSP00000337450', 'f_543', 'cpi_9606.ENSP00000291294', 'f_764', 'cpi_9606.ENSP00000306100'], ['cpi_9606.ENSP00000264381', 'f_216', 'f_713', 'cpi_9606.ENSP00000376943', 'cpi_9606.ENSP00000261693'], ['f_449', 'cpi_9606.ENSP00000397026', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000330393', 'f_505'], ['f_464', 'cpi_9606.ENSP00000264426', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000276449', 'f_785'], ['cpi_9606.ENSP00000360372', 'f_34', 'f_477', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000309818'], ['f_593', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000419692', 'f_401', 'cpi_9606.ENSP00000398632'], ['f_666', 'cpi_9606.ENSP00000332549', 'cpi_9606.ENSP00000312029', 'f_647', 'f_398'], ['f_332', 'cpi_9606.ENSP00000383365', 'cpi_9606.ENSP00000344674', 'cpi_9606.ENSP00000275525', 'cpi_9606.ENSP00000361359'], ['f_365', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000373477', 'cpi_9606.ENSP00000301178', 'f_622'], ['f_536', 'cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000358548', 'cpi_9606.ENSP00000344192'], ['f_797', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000332369', 'f_770'], ['f_818', 'cpi_9606.ENSP00000279593', 'f_423', 'cpi_9606.ENSP00000326119', 'f_195'], ['f_594', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000321999', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000357283'], ['f_642', 'cpi_9606.ENSP00000301141', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000259089', 'f_483'], ['f_199', 'cpi_9606.ENSP00000385834', 'f_489', 'f_518', 'cpi_9606.ENSP00000354107'], ['f_628', 'cpi_9606.ENSP00000216714', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000451030', 'f_409'], ['f_580', 'cpi_9606.ENSP00000363965', 'cpi_9606.ENSP00000382659', 'f_363', 'cpi_9606.ENSP00000274547'], ['f_699', 'f_488', 'cpi_9606.ENSP00000261267', 'f_422', 'f_471'], ['cpi_9606.ENSP00000295897', 'f_115', 'f_558', 'cpi_9606.ENSP00000248553', 'cpi_9606.ENSP00000402152'], ['f_351', 'cpi_9606.ENSP00000226578', 'cpi_9606.ENSP00000407375', 'cpi_9606.ENSP00000356954', 'f_513'], ['f_502', 'cpi_9606.ENSP00000234310', 'cpi_9606.ENSP00000362513', 'cpi_9606.ENSP00000348069', 'f_367'], ['f_798', 'f_517', 'cpi_9606.ENSP00000356729', 'cpi_9606.ENSP00000259486', 'f_717'], ['f_592', 'cpi_9606.ENSP00000222481', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000293288', 'f_833'], ['f_241', 'f_132', 'cpi_9606.ENSP00000319170', 'cpi_9606.ENSP00000308165', 'cpi_9606.ENSP00000362036'], ['f_248', 'cpi_9606.ENSP00000262407', 'cpi_9606.ENSP00000222330', 'f_454', 'f_609'], ['f_623', 'f_411', 'cpi_9606.ENSP00000346298', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000003100'], ['f_581', 'cpi_9606.ENSP00000285979', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000346017', 'f_467'], ['f_641', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000353472', 'cpi_9606.ENSP00000267101'], ['f_619', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000370912', 'cpi_9606.ENSP00000363296', 'f_494'], ['f_368', 'cpi_9606.ENSP00000272298', 'cpi_9606.ENSP00000260356', 'f_826', 'cpi_9606.ENSP00000340691'], ['f_690', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000264318', 'f_461'], ['f_777', 'cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000253004', 'cpi_9606.ENSP00000412673'], ['f_686', 'cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000296122', 'cpi_9606.ENSP00000381097', 'f_301'], ['f_11', 'cpi_9606.ENSP00000362924', 'cpi_9606.ENSP00000374265', 'f_740', 'f_644'], ['f_259', 'cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000370473', 'f_588', 'cpi_9606.ENSP00000370381'], ['f_695', 'cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000388825', 'f_822', 'f_30'], ['f_193', 'cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000296545', 'cpi_9606.ENSP00000155840', 'f_475'], ['f_10', 'cpi_9606.ENSP00000302441', 'cpi_9606.ENSP00000226574', 'f_159', 'f_759'], ['f_493', 'cpi_9606.ENSP00000387230', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000299267', 'f_860'], ['f_702', 'cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000263980', 'f_780', 'cpi_9606.ENSP00000386029'], ['f_462', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000241256', 'cpi_9606.ENSP00000270474', 'f_514'], ['f_591', 'cpi_9606.ENSP00000219070', 'f_160', 'cpi_9606.ENSP00000384957', 'cpi_9606.ENSP00000255465'], ['f_776', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000350348', 'cpi_9606.ENSP00000220616', 'f_364'], ['f_662', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000354569', 'cpi_9606.ENSP00000260010', 'f_421'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000218388', 'f_200', 'cpi_9606.ENSP00000331912', 'cpi_9606.ENSP00000365380'], ['f_1', 'cpi_9606.ENSP00000376914', 'cpi_9606.ENSP00000353427', 'cpi_9606.ENSP00000361666', 'f_738'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000292513', 'cpi_9606.ENSP00000296674', 'cpi_9606.ENSP00000270776', 'f_17'], ['f_688', 'cpi_9606.ENSP00000286621', 'cpi_9606.ENSP00000239938', 'f_559', 'f_742'], ['f_498', 'cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000349576', 'f_359', 'cpi_9606.ENSP00000231454'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000348645', 'cpi_9606.ENSP00000365775', 'f_687'], ['f_633', 'cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000327850', 'cpi_9606.ENSP00000358784', 'f_314'], ['f_333', 'cpi_9606.ENSP00000358727', 'cpi_9606.ENSP00000307014', 'cpi_9606.ENSP00000296871', 'f_721'], ['f_734', 'f_395', 'cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000308774'], ['f_607', 'cpi_9606.ENSP00000308897', 'cpi_9606.ENSP00000309103', 'f_144', 'f_425'], ['f_549', 'cpi_9606.ENSP00000236671', 'cpi_9606.ENSP00000429374', 'cpi_9606.ENSP00000320025', 'f_227'], ['f_548', 'cpi_9606.ENSP00000219700', 'cpi_9606.ENSP00000359635', 'cpi_9606.ENSP00000339527', 'f_480'], ['f_537', 'cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000353224', 'f_414', 'cpi_9606.ENSP00000233146'], ['f_701', 'cpi_9606.ENSP00000260970', 'cpi_9606.ENSP00000355920', 'cpi_9606.ENSP00000365663', 'f_624'], ['f_244', 'cpi_9606.ENSP00000396308', 'f_336', 'cpi_9606.ENSP00000304895', 'cpi_9606.ENSP00000386229'], ['f_349', 'cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000296522', 'cpi_9606.ENSP00000364805', 'cpi_9606.ENSP00000265403'], ['f_437', 'cpi_9606.ENSP00000263269', 'cpi_9606.ENSP00000222390', 'f_803', 'f_456'], ['f_546', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000310447', 'cpi_9606.ENSP00000466799', 'f_625'], ['f_24', 'cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000268053', 'cpi_9606.ENSP00000353878'], ['f_636', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000320866', 'f_801'], ['f_450', 'cpi_9606.ENSP00000234111', 'cpi_9606.ENSP00000227758', 'f_705', 'cpi_9606.ENSP00000256010'], ['f_150', 'cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000314508', 'f_250', 'cpi_9606.ENSP00000430432'], ['f_755', 'cpi_9606.ENSP00000342070', 'f_305', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000259396'], ['f_604', 'cpi_9606.ENSP00000331514', 'cpi_9606.ENSP00000348897', 'f_694', 'cpi_9606.ENSP00000252804'], ['f_708', 'cpi_9606.ENSP00000039007', 'cpi_9606.ENSP00000310405', 'cpi_9606.ENSP00000351273', 'f_805'], ['cpi_9606.ENSP00000272190', 'f_575', 'cpi_9606.ENSP00000253727', 'f_612', 'cpi_9606.ENSP00000355325'], ['f_654', 'cpi_9606.ENSP00000340684', 'cpi_9606.ENSP00000379330', 'f_610', 'cpi_9606.ENSP00000287936'], ['f_442', 'cpi_9606.ENSP00000001008', 'cpi_9606.ENSP00000356213', 'cpi_9606.ENSP00000416293', 'f_38'], ['cpi_9606.ENSP00000270349', 'f_605', 'cpi_9606.ENSP00000262160', 'f_465', 'cpi_9606.ENSP00000338082'], ['f_356', 'cpi_9606.ENSP00000338160', 'cpi_9606.ENSP00000303248', 'cpi_9606.ENSP00000297350', 'f_784'], ['f_550', 'cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000309757', 'f_157', 'cpi_9606.ENSP00000387683'], ['f_342', 'cpi_9606.ENSP00000307786', 'f_527', 'cpi_9606.ENSP00000267843', 'cpi_9606.ENSP00000359793'], ['f_18', 'cpi_9606.ENSP00000253303', 'cpi_9606.ENSP00000428924', 'cpi_9606.ENSP00000414303', 'f_652'], ['f_352', 'cpi_9606.ENSP00000348395', 'cpi_9606.ENSP00000296677', 'cpi_9606.ENSP00000278616', 'f_515'], ['f_430', 'cpi_9606.ENSP00000276651', 'cpi_9606.ENSP00000231188', 'cpi_9606.ENSP00000265723', 'cpi_9606.ENSP00000358903'], ['f_377', 'cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000311165', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000200676'], ['f_665', 'cpi_9606.ENSP00000219794', 'cpi_9606.ENSP00000355317', 'f_563', 'cpi_9606.ENSP00000267163'], ['f_14', 'cpi_9606.ENSP00000233944', 'cpi_9606.ENSP00000385806', 'f_206', 'cpi_9606.ENSP00000239849'], ['f_655', 'cpi_9606.ENSP00000309477', 'cpi_9606.ENSP00000251566', 'cpi_9606.ENSP00000303452', 'cpi_9606.ENSP00000244741'], ['f_685', 'cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000428824', 'f_500', 'cpi_9606.ENSP00000320935'], ['cpi_9606.ENSP00000354612', 'f_572', 'cpi_9606.ENSP00000347979', 'cpi_9606.ENSP00000229264', 'f_711'], ['f_507', 'cpi_9606.ENSP00000220809', 'f_824', 'cpi_9606.ENSP00000388648', 'cpi_9606.ENSP00000309968'], ['cpi_9606.ENSP00000258743', 'cpi_9606.ENSP00000326219', 'cpi_9606.ENSP00000352035', 'f_300', 'f_630'], ['f_586', 'cpi_9606.ENSP00000358022', 'cpi_9606.ENSP00000231228', 'cpi_9606.ENSP00000248041', 'f_707'], ['f_651', 'cpi_9606.ENSP00000333994', 'f_397', 'cpi_9606.ENSP00000420168', 'f_532'], ['f_574', 'cpi_9606.ENSP00000371236', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000276571', 'f_458'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000288022', 'f_459', 'cpi_9606.ENSP00000293330', 'f_337'], ['f_412', 'cpi

🔄 Processing features: 100%|██████████| 2147/2147 [10:16<00:00,  3.48feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'f_408', 'f_166', 'f_151', 'f_845'], ['f_20', 'cpi_9606.ENSP00000333212', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000295454', 'cpi_9606.ENSP00000299847'], ['f_374', 'cpi_9606.ENSP00000386284', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000286648', 'f_726'], ['f_308', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000353791', 'f_616', 'f_785'], ['f_299', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000367851', 'cpi_9606.ENSP00000430620', 'f_31'], ['f_346', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000395653', 'cpi_9606.ENSP00000279178', 'f_629'], ['f_614', 'cpi_9606.ENSP00000216465', 'f_789', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000316786'], ['f_617', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000335592'], ['f_405', 'cpi_9606.ENSP00000305742', 'cpi_9606.ENSP00000367848', 'f_413', 'f_768'], ['f_380', 'cpi_9606.ENSP00000263088', 'f_722', 'cpi_9606.ENSP00000277010', 'f_757'], ['f_452', 'f_25', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000365663', 'cpi_9606.ENSP00000360773'], ['f_406', 'cpi_9606.ENSP00000352035', 'cpi_9606.ENSP00000374323', 'f_831', 'f_820'], ['f_440', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000378517', 'cpi_9606.ENSP00000342235'], ['f_3', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000431512', 'f_676', 'cpi_9606.ENSP00000337335'], ['f_392', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000354476', 'cpi_9606.ENSP00000255409'], ['f_451', 'cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000245539', 'f_428', 'f_328'], ['f_186', 'cpi_9606.ENSP00000321584', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000414334', 'f_511'], ['f_391', 'cpi_9606.ENSP00000357204', 'cpi_9606.ENSP00000430684', 'f_866', 'cpi_9606.ENSP00000361206'], ['f_185', 'cpi_9606.ENSP00000264162', 'cpi_9606.ENSP00000278175', 'f_292', 'cpi_9606.ENSP00000309572'], ['f_393', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000380318', 'cpi_9606.ENSP00000355629'], ['f_23', 'cpi_9606.ENSP00000308541', 'f_195', 'f_635', 'f_118'], ['f_366', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000376178'], ['f_15', 'cpi_9606.ENSP00000397582', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000304822', 'f_214'], ['f_335', 'f_815', 'cpi_9606.ENSP00000274353', 'cpi_9606.ENSP00000331912', 'f_409'], ['f_672', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000216540'], ['f_566', 'cpi_9606.ENSP00000268251', 'f_836', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000332296'], ['f_571', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000301891', 'cpi_9606.ENSP00000353362', 'f_799'], ['f_12', 'cpi_9606.ENSP00000354850', 'f_529', 'cpi_9606.ENSP00000428824', 'cpi_9606.ENSP00000312455'], ['f_192', 'cpi_9606.ENSP00000303540', 'f_47', 'cpi_9606.ENSP00000364212', 'f_131'], ['f_287', 'cpi_9606.ENSP00000241052', 'f_194', 'cpi_9606.ENSP00000356094', 'f_773'], ['f_697', 'cpi_9606.ENSP00000357669', 'cpi_9606.ENSP00000323568', 'f_725', 'f_834'], ['f_338', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000262999'], ['f_19', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000326219', 'cpi_9606.ENSP00000419782', 'f_510'], ['f_420', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000359635', 'f_327', 'f_497'], ['f_390', 'cpi_9606.ENSP00000222481', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000356832', 'f_27'], ['f_643', 'cpi_9606.ENSP00000345096', 'cpi_9606.ENSP00000352900', 'f_202', 'f_26'], ['f_339', 'f_554', 'cpi_9606.ENSP00000371985', 'f_526', 'f_736'], ['f_143', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000274793', 'cpi_9606.ENSP00000256383', 'f_587'], ['f_37', 'cpi_9606.ENSP00000263321', 'f_229', 'f_35', 'cpi_9606.ENSP00000321326'], ['f_146', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000394936', 'cpi_9606.ENSP00000356150', 'f_297'], ['f_569', 'cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000341885', 'f_350'], ['f_579', 'cpi_9606.ENSP00000354193', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000262948', 'f_830'], ['f_285', 'cpi_9606.ENSP00000323867', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000264867', 'cpi_9606.ENSP00000326119'], ['cpi_9606.ENSP00000342007', 'f_347', 'cpi_9606.ENSP00000283635', 'f_763', 'cpi_9606.ENSP00000262441'], ['f_528', 'cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000263126', 'cpi_9606.ENSP00000309124', 'f_460'], ['f_2', 'cpi_9606.ENSP00000219794', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000296122', 'f_788'], ['cpi_9606.ENSP00000311032', 'f_509', 'f_164', 'f_454', 'f_116'], ['f_181', 'cpi_9606.ENSP00000273550', 'cpi_9606.ENSP00000264637', 'cpi_9606.ENSP00000471569', 'cpi_9606.ENSP00000367102'], ['f_340', 'cpi_9606.ENSP00000346827', 'cpi_9606.ENSP00000331746', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000319788'], ['f_656', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000361359'], ['f_639', 'f_715', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000319591', 'f_813'], ['cpi_9606.ENSP00000264381', 'f_593', 'f_719', 'cpi_9606.ENSP00000360493', 'cpi_9606.ENSP00000389338'], ['f_696', 'cpi_9606.ENSP00000354532', 'f_474', 'f_46', 'f_436'], ['f_712', 'f_767', 'cpi_9606.ENSP00000261755', 'f_771', 'cpi_9606.ENSP00000359353'], ['f_33', 'f_706', 'cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000336630', 'f_298'], ['f_684', 'cpi_9606.ENSP00000254976', 'cpi_9606.ENSP00000388648', 'f_330', 'cpi_9606.ENSP00000221972'], ['f_535', 'cpi_9606.ENSP00000376914', 'f_670', 'cpi_9606.ENSP00000457706', 'f_752'], ['f_611', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000251535', 'cpi_9606.ENSP00000000442'], ['f_659', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000387946', 'cpi_9606.ENSP00000369038', 'cpi_9606.ENSP00000343040'], ['cpi_9606.ENSP00000353820', 'f_22', 'f_778', 'f_812', 'cpi_9606.ENSP00000358548'], ['f_613', 'cpi_9606.ENSP00000313490', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000296871'], ['f_667', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000358107', 'f_388', 'f_792'], ['f_341', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000273398', 'cpi_9606.ENSP00000357283', 'cpi_9606.ENSP00000417229'], ['f_698', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000233146'], ['f_645', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000356436'], ['f_686', 'f_215', 'f_419', 'cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000408860'], ['f_646', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000359100', 'f_749'], ['f_638', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000297350', 'cpi_9606.ENSP00000226574'], ['f_443', 'cpi_9606.ENSP00000383365', 'f_675', 'cpi_9606.ENSP00000427514', 'f_764'], ['f_553', 'cpi_9606.ENSP00000279387', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000343477', 'f_167'], ['f_704', 'cpi_9606.ENSP00000364709', 'cpi_9606.ENSP00000295491', 'f_729', 'f_43'], ['f_615', 'f_839', 'cpi_9606.ENSP00000225275', 'f_429', 'f_738'], ['f_16', 'cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000261693', 'f_361', 'cpi_9606.ENSP00000451040'], ['f_681', 'cpi_9606.ENSP00000304811', 'f_417', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000344674'], ['f_257', 'cpi_9606.ENSP00000332549', 'cpi_9606.ENSP00000365380', 'cpi_9606.ENSP00000258749', 'f_343'], ['f_439', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000354610', 'f_861', 'cpi_9606.ENSP00000293288'], ['f_516', 'cpi_9606.ENSP00000309477', 'cpi_9606.ENSP00000410076', 'cpi_9606.ENSP00000428340', 'f_583'], ['f_683', 'cpi_9606.ENSP00000314649', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000300061', 'cpi_9606.ENSP00000252809'], ['f_689', 'cpi_9606.ENSP00000319531', 'cpi_9606.ENSP00000297316', 'f_791', 'cpi_9606.ENSP00000358595'], ['f_21', 'cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000252519', 'f_467', 'cpi_9606.ENSP00000356958'], ['f_691', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000216037', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000325120'], ['f_180', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000291294', 'cpi_9606.ENSP00000266376'], ['f_637', 'cpi_9606.ENSP00000306606', 'cpi_9606.ENSP00000328173', 'f_728', 'f_466'], ['f_345', 'cpi_9606.ENSP00000471397', 'cpi_9606.ENSP00000370473', 'cpi_9606.ENSP00000312664', 'f_505'], ['f_241', 'f_132', 'cpi_9606.ENSP00000333994', 'cpi_9606.ENSP00000222330', 'cpi_9606.ENSP00000381097'], ['f_502', 'cpi_9606.ENSP00000279593', 'f_782', 'cpi_9606.ENSP00000311095', 'f_551'], ['f_540', 'cpi_9606.ENSP00000226578', 'cpi_9606.ENSP00000419692', 'f_827', 'cpi_9606.ENSP00000376943'], ['f_692', 'cpi_9606.ENSP00000216962', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000412673', 'f_473'], ['cpi_9606.ENSP00000356438', 'f_213', 'f_407', 'f_568', 'f_448'], ['cpi_9606.ENSP00000222982', 'f_34', 'f_826', 'cpi_9606.ENSP00000292513', 'cpi_9606.ENSP00000301634'], ['cpi_9606.ENSP00000265724', 'f_401', 'f_427', 'cpi_9606.ENSP00000362036', 'f_750'], ['f_145', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000350928', 'f_622', 'cpi_9606.ENSP00000242057'], ['f_682', 'cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000274547'], ['f_567', 'cpi_9606.ENSP00000332369', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000276449', 'cpi_9606.ENSP00000400175'], ['f_702', 'cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000234071', 'f_483', 'cpi_9606.ENSP00000275525'], ['f_581', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000369654', 'cpi_9606.ENSP00000286301', 'cpi_9606.ENSP00000339527'], ['f_602', 'cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000467676', 'cpi_9606.ENSP00000353292'], ['f_294', 'cpi_9606.ENSP00000359285', 'f_262', 'cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000329357'], ['f_365', 'cpi_9606.ENSP00000233944', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000294728', 'cpi_9606.ENSP00000301178'], ['f_666', 'cpi_9606.ENSP00000355536', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000260010', 'cpi_9606.ENSP00000348069'], ['f_293', 'cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000359793', 'cpi_9606.ENSP00000283254'], ['f_464', 'cpi_9606.ENSP00000234310', 'cpi_9606.ENSP00000255465', 'f_207', 'cpi_9606.ENSP00000267101'], ['f_353', 'cpi_9606.ENSP00000216714', 'cpi_9606.ENSP00000428864', 'f_486', 'f_543'], ['f_641', 'cpi_9606.ENSP00000244217', 'cpi_9606.ENSP00000299267', 'cpi_9606.ENSP00000225474', 'cpi_9606.ENSP00000257290'], ['f_24', 'f_216', 'cpi_9606.ENSP00000223095', 'f_740', 'cpi_9606.ENSP00000369530'], ['f_573', 'cpi_9606.ENSP00000364035', 'cpi_9606.ENSP00000344352', 'cpi_9606.ENSP00000261937', 'cpi_9606.ENSP00000231188'], ['f_642', 'cpi_9606.ENSP00000318585', 'cpi_9606.ENSP00000347942', 'f_471', 'cpi_9606.ENSP00000369816'], ['f_671', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000362353', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000282561'], ['f_248', 'f_518', 'cpi_9606.ENSP00000307599', 'cpi_9606.ENSP00000262407', 'cpi_9606.ENSP00000262367'], ['f_709', 'cpi_9606.ENSP00000306100', 'cpi_9606.ENSP00000355657', 'f_475', 'f_394'], ['f_680', 'cpi_9606.ENSP00000261733', 'cpi_9606.ENSP00000365016', 'cpi_9606.ENSP00000261799', 'f_129'], ['f_594', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000321999', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000366307'], ['f_536', 'f_833', 'cpi_9606.ENSP00000305221', 'cpi_9606.ENSP00000382250', 'cpi_9606.ENSP00000270631'], ['f_699', 'f_488', 'cpi_9606.ENSP00000263269', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000222390'], ['f_690', 'f_609', 'cpi_9606.ENSP00000260970', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000248553'], ['cpi_9606.ENSP00000303211', 'f_537', 'f_558', 'f_477', 'cpi_9606.ENSP00000263980'], ['f_193', 'cpi_9606.ENSP00000328968', 'f_494', 'cpi_9606.ENSP00000363965', 'cpi_9606.ENSP00000394932'], ['f_628', 'cpi_9606.ENSP00000261205', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000278616', 'f_455'], ['f_655', 'cpi_9606.ENSP00000447378', 'cpi_9606.ENSP00000260356', 'f_508', 'f_522'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000371929', 'f_200', 'cpi_9606.ENSP00000296545'], ['f_549', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000349576', 'cpi_9606.ENSP00000388825', 'cpi_9606.ENSP00000354558'], ['f_375', 'f_242', 'f_631', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000375809'], ['f_432', 'cpi_9606.ENSP00000350616', 'f_533', 'f_496', 'cpi_9606.ENSP00000308845'], ['f_604', 'cpi_9606.ENSP00000280357', 'cpi_9606.ENSP00000312673', 'cpi_9606.ENSP00000231454', 'f_398'], ['f_619', 'cpi_9606.ENSP00000399168', 'cpi_9606.ENSP00000346598', 'cpi_9606.ENSP00000259396', 'cpi_9606.ENSP00000354394'], ['f_18', 'cpi_9606.ENSP00000472933', 'cpi_9606.ENSP00000470087', 'cpi_9606.ENSP00000295834', 'cpi_9606.ENSP00000252723'], ['f_560', 'f_840', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000260649', 'cpi_9606.ENSP00000353878'], ['f_597', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000276414', 'cpi_9606.ENSP00000300900', 'f_822'], ['f_332', 'cpi_9606.ENSP00000226299', 'cpi_9606.ENSP00000310405', 'cpi_9606.ENSP00000344192', 'f_461'], ['cpi_9606.ENSP00000360372', 'cpi_9606.ENSP00000306138', 'f_644', 'f_159', 'cpi_9606.ENSP00000227758'], ['f_663', 'cpi_9606.ENSP00000363868', 'cpi_9606.ENSP00000262888', 'f_414', 'cpi_9606.ENSP00000259089'], ['f_368', 'cpi_9606.ENSP00000385834', 'f_801', 'cpi_9606.ENSP00000330393', 'cpi_9606.ENSP00000372023'], ['f_623', 'f_456', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000368752', 'cpi_9606.ENSP00000019103'], ['cpi_9606.ENSP00000295897', 'f_115', 'f_514', 'f_399', 'cpi_9606.ENSP00000303424'], ['f_199', 'cpi_9606.ENSP00000354612', 'f_489', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000340691'], ['f_586', 'cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000256958', 'f_647', 'f_824'], ['f_548', 'cpi_9606.ENSP00000327801', 'cpi_9606.ENSP00000231228', 'f_770', 'f_513'], ['f_418', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000382659', 'cpi_9606.ENSP00000200676', 'f_336'], ['f_507', 'cpi_9606.ENSP00000220809', 'f_230', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000308549'], ['f_821', 'f_30', 'cpi_9606.ENSP00000335620', 'cpi_9606.ENSP00000308165', 'cpi_9606.ENSP00000350348'], ['f_286', 'cpi_9606.ENSP00000343885', 'cpi_9606.ENSP00000312029', 'f_759', 'f_653'], ['f_493', 'cpi_9606.ENSP00000254488', 'cpi_9606.ENSP00000298171', 'cpi_9606.ENSP00000466799', 'f_411'], ['f_818', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000350767', 'f_621'], ['f_437', 'cpi_9606.ENSP00000397026', 'f_860', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000356954'], ['f_662', 'cpi_9606.ENSP00000299178', 'cpi_9606.ENSP00000394033', 'cpi_9606.ENSP00000252486', 'f_423'], ['f_351', 'cpi_9606.ENSP00000308897', 'cpi_9606.ENSP00000346148', 'cpi_9606.ENSP00000267163', 'f_160'], ['f_797', 'cpi_9606.ENSP00000261405', 'f_301', 'cpi_9606.ENSP00000267843', 'f_422'], ['f_592', 'cpi_9606.ENSP00000248935', 'cpi_9606.ENSP00000307014', 'cpi_9606.ENSP00000361666', 'f_314'], ['cpi_9606.ENSP00000367959', 'f_588', 'f_425', 'cpi_9606.ENSP00000349252', 'cpi_9606.ENSP00000261196'], ['f_779', 'f_367', 'cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000221515', 'cpi_9606.ENSP00000237527'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000311165', 'f_742', 'f_780', 'cpi_9606.ENSP00000445340'], ['f_342', 'cpi_9606.ENSP00000353731', 'cpi_9606.ENSP00000282753', 'cpi_9606.ENSP00000232219', 'f_527'], ['f_708', 'cpi_9606.ENSP00000364782', 'cpi_9606.ENSP00000239938', 'f_559', 'f_625'], ['f_693', 'f_517', 'cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000246337', 'f_500'], ['f_633', 'cpi_9606.ENSP00000360141', 'cpi_9606.ENSP00000320935', 'f_803', 'cpi_9606.ENSP00000353427'], ['f_349', 'cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000296522', 'cpi_9606.ENSP00000317379', 'f_575'], ['f_580', 'cpi_9606.ENSP00000270142', 'f_144', 'f_721', 'cpi_9606.ENSP00000233242'], ['f_11', 'cpi_9606.ENSP00000368305', 'cpi_9606.ENSP00000264657', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000376776'], ['f_758', 'cpi_9606.ENSP00000352835', 'cpi_9606.ENSP00000343925', 'f_480', 'f_650'], ['f_685', 'cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000346017', 'f_363'], ['f_462', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000292095', 'f_359', 'cpi_9606.ENSP00000320866'], ['f_259', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000356694', 'cpi_9606.ENSP00000366506'], ['f_244', 'cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000304895', 'cpi_9606.ENSP00000389414', 'cpi_9606.ENSP00000378492'], ['f_412', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000353915', 'cpi_9606.ENSP00000430432', 'f_661'], ['f_755', 'cpi_9606.ENSP00000368438', 'cpi_9606.ENSP00000272847', 'f_305', 'cpi_9606.ENSP00000301146'], ['f_430', 'cpi_9606.ENSP00000264613', 'cpi_9606.ENSP00000379086', 'cpi_9606.ENSP00000318822', 'f_805'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000380247', 'f_17', 'cpi_9606.ENSP00000225371', 'cpi_9606.ENSP00000355533'], ['f_377', 'cpi_9606.ENSP00000319814', 'cpi_9606.ENSP00000357981', 'cpi_9606.ENSP00000324248', 'f_610'], ['f_333', 'cpi_9606.ENSP00000358727', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000231449', 'f_421'], ['f_688', 'cpi_9606.ENSP00000258662', 'cpi_9606.ENSP00000375066', 'cpi_9606.ENSP00000329623', 'f_157'], ['f_14', 'cpi_9606.ENSP00000287878', 'cpi_9606.ENSP00000385806', 'f_206', 'cpi_9606.ENSP00000245457'], ['f_777', 'cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000356671', 'f_364', 'cpi_9606.ENSP00000363296'], ['f_150', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000225927', 'cpi_9606.ENSP00000311028', 'f_250'], ['f_776', 'cpi_9606.ENSP00000337103', 'cpi_9606.ENSP00000320025', 'f_465', 'cpi_9606.ENSP00000380252'], ['f_654', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000295731', 'cpi_9606.ENSP00000319984', 'f_705'], ['f_337', 'cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000356729', 'cpi_9606.ENSP00000369757', 'f_499'], ['f_550', 'cpi_9606.ENSP00000356022', 'f_400', 'cpi_9606.ENSP00000240652', 'f_395'], ['f_651', 'cpi_9606.ENSP00000434516', 'f_397', 'cpi_9606.ENSP00000368632', 'cpi_9606.ENSP00000410294'], ['f_798', 'cpi_9606.ENSP00000338082', 'cpi_9606.ENSP00000220616', 'f_485', 'cpi_9606.ENSP00000219919'], ['f_734', 'cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000347979', 'cpi_9606.ENSP00000308774', 'cpi_9606.ENSP00000307259'], ['f_701', 'cpi_9606.ENSP00000237014', 'f_624', 'cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000463999'], ['cpi_9606.ENSP00000272190', 'f_612', 'cpi_9606.ENSP00000268035', 'cpi_9606.ENSP00000364802', 'f_687'], ['cpi_9606.ENSP00000324648', 'f_707', 'cpi_9606.ENSP00000241256', 'cpi_9606.ENSP00000435777', 'f_458'], ['f_819', 'cpi_9606.ENSP00000220764', 'f_717', 'cpi_9606.ENSP00000308032', 'cpi_9606.ENSP00000338072'], ['f_695', 'cpi_9606.ENSP00000356825', 'cpi_9606.ENSP00000301633', 'f_300', 'cpi_9606.ENSP00000375893'], ['f_710', 'cpi_9606.ENSP00000293404', 'cpi_9606.ENSP00000344173', 'cpi_9606.ENSP00000384273', 'f_227'], ['f_498', 'cpi_9606.ENSP00000367123', 'cpi_9606.ENSP00000448059', 'f_38', 'f_260'], ['cpi_9606.ENSP00000258743', 'f_652', 'cpi_9606.ENSP00000272167', 'cpi_9606.ENSP00000351885', 'f_515'], ['f_370', 'cpi_9606.ENSP00000330484', 'cpi_9606.ENSP00000407375', 'cpi_9606.ENSP00000239849', 'f_605'], ['f_714', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000355778', 'f_737'], ['f_334', 'cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000343782', 'f_362', 'cpi_9606.ENSP00000349577'], ['f_13', 'cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000352516', 'cpi_9606.ENSP00000325822', 'f_459'], ['f_449', 'cpi_9606.ENSP00000236671', 'cpi_9606.ENSP00000443459', 'f_700', 'cpi_9606.ENSP00000302846'], ['f_591', 'cpi_9606.ENSP00000219070', 'cpi_9606.ENSP00000305692', 'cpi_9606.ENSP00000318646', 'f_694'], ['f_10', 'cpi_9606.ENSP00000302441', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000306129', 'f_784'], ['f_

🔄 Processing features: 100%|██████████| 2147/2147 [10:16<00:00,  3.48feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'f_408', 'f_167', 'f_845', 'cpi_9606.ENSP00000367123'], ['f_308', 'f_616', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000263377', 'cpi_9606.ENSP00000351957'], ['f_20', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000314214', 'f_792', 'f_629'], ['f_374', 'cpi_9606.ENSP00000357066', 'cpi_9606.ENSP00000414334', 'f_25', 'f_27'], ['f_299', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000358223', 'f_151', 'cpi_9606.ENSP00000354476'], ['f_406', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000357068', 'f_791'], ['f_366', 'cpi_9606.ENSP00000402608', 'cpi_9606.ENSP00000279178', 'f_428', 'cpi_9606.ENSP00000286479'], ['f_391', 'cpi_9606.ENSP00000357204', 'cpi_9606.ENSP00000430684', 'f_866', 'cpi_9606.ENSP00000362036'], ['f_3', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000431512', 'f_749', 'f_836'], ['f_346', 'cpi_9606.ENSP00000395653', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000220616', 'f_510'], ['f_452', 'cpi_9606.ENSP00000337773', 'cpi_9606.ENSP00000342235', 'f_726', 'cpi_9606.ENSP00000299847'], ['f_380', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000257290', 'cpi_9606.ENSP00000355533', 'f_789'], ['f_643', 'cpi_9606.ENSP00000345096', 'cpi_9606.ENSP00000377947', 'f_194', 'cpi_9606.ENSP00000355629'], ['f_405', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000268251', 'f_413', 'f_768'], ['f_185', 'cpi_9606.ENSP00000264162', 'f_31', 'cpi_9606.ENSP00000305416', 'cpi_9606.ENSP00000359424'], ['f_440', 'f_728', 'cpi_9606.ENSP00000354193', 'cpi_9606.ENSP00000378517', 'cpi_9606.ENSP00000372547'], ['f_339', 'f_509', 'cpi_9606.ENSP00000394033', 'cpi_9606.ENSP00000353362', 'f_526'], ['f_186', 'cpi_9606.ENSP00000274353', 'cpi_9606.ENSP00000355657', 'f_511', 'f_118'], ['f_393', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000380318', 'f_587'], ['f_192', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000314508', 'f_47', 'cpi_9606.ENSP00000265294'], ['f_15', 'cpi_9606.ENSP00000397582', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000304822', 'f_214'], ['f_672', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000216465', 'f_292', 'cpi_9606.ENSP00000295452'], ['f_12', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000219794', 'f_635', 'cpi_9606.ENSP00000221972'], ['f_338', 'cpi_9606.ENSP00000349320', 'f_460', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000319814'], ['cpi_9606.ENSP00000311032', 'f_675', 'f_207', 'cpi_9606.ENSP00000356094', 'f_831'], ['f_617', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000308774', 'cpi_9606.ENSP00000335592'], ['f_340', 'cpi_9606.ENSP00000321584', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000389338'], ['f_23', 'cpi_9606.ENSP00000412237', 'f_195', 'cpi_9606.ENSP00000376432', 'f_529'], ['f_571', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000301891', 'f_799', 'f_833'], ['f_451', 'cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000277010', 'cpi_9606.ENSP00000294728'], ['f_566', 'f_427', 'cpi_9606.ENSP00000229264', 'f_773', 'cpi_9606.ENSP00000348645'], ['f_392', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000259396'], ['f_443', 'cpi_9606.ENSP00000262888', 'cpi_9606.ENSP00000233146', 'cpi_9606.ENSP00000370912', 'f_725'], ['f_181', 'cpi_9606.ENSP00000273550', 'cpi_9606.ENSP00000263126', 'cpi_9606.ENSP00000445340', 'f_131'], ['f_146', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000290349', 'f_417', 'f_328'], ['f_19', 'cpi_9606.ENSP00000472933', 'cpi_9606.ENSP00000333212', 'cpi_9606.ENSP00000394936', 'cpi_9606.ENSP00000359353'], ['f_535', 'cpi_9606.ENSP00000383365', 'f_297', 'f_788', 'cpi_9606.ENSP00000282561'], ['f_614', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000466799', 'cpi_9606.ENSP00000367848', 'f_830'], ['f_697', 'cpi_9606.ENSP00000354850', 'f_35', 'f_767', 'cpi_9606.ENSP00000360773'], ['f_656', 'cpi_9606.ENSP00000261205', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000309124', 'cpi_9606.ENSP00000252809'], ['f_528', 'cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000332296', 'cpi_9606.ENSP00000358784', 'f_43'], ['cpi_9606.ENSP00000342007', 'f_347', 'cpi_9606.ENSP00000299178', 'f_670', 'f_736'], ['f_335', 'f_815', 'cpi_9606.ENSP00000352835', 'f_719', 'f_436'], ['f_712', 'cpi_9606.ENSP00000254976', 'f_771', 'cpi_9606.ENSP00000317379', 'cpi_9606.ENSP00000222330'], ['f_143', 'cpi_9606.ENSP00000313490', 'cpi_9606.ENSP00000216037', 'f_327', 'f_202'], ['f_33', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000435591', 'f_706', 'cpi_9606.ENSP00000301633'], ['f_390', 'cpi_9606.ENSP00000259486', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000312455', 'f_583'], ['f_639', 'f_715', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000295834'], ['f_37', 'cpi_9606.ENSP00000263321', 'f_229', 'f_554', 'cpi_9606.ENSP00000321326'], ['f_287', 'cpi_9606.ENSP00000303211', 'f_631', 'f_166', 'cpi_9606.ENSP00000353292'], ['f_569', 'cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000264637', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000376943'], ['f_659', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000262948', 'f_839'], ['cpi_9606.ENSP00000353820', 'f_26', 'cpi_9606.ENSP00000286648', 'f_330', 'f_132'], ['f_2', 'cpi_9606.ENSP00000364035', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000319788', 'f_497'], ['f_285', 'cpi_9606.ENSP00000244217', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000200676', 'f_827'], ['f_579', 'cpi_9606.ENSP00000234389', 'f_388', 'cpi_9606.ENSP00000339527', 'cpi_9606.ENSP00000367851'], ['f_420', 'cpi_9606.ENSP00000312326', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000344352', 'cpi_9606.ENSP00000000442'], ['f_257', 'cpi_9606.ENSP00000332549', 'cpi_9606.ENSP00000387946', 'cpi_9606.ENSP00000258749', 'cpi_9606.ENSP00000470087'], ['f_682', 'cpi_9606.ENSP00000355155', 'f_778', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000356958'], ['f_611', 'cpi_9606.ENSP00000237014', 'cpi_9606.ENSP00000343477', 'cpi_9606.ENSP00000307599', 'f_622'], ['f_341', 'cpi_9606.ENSP00000295454', 'cpi_9606.ENSP00000273398', 'f_834', 'cpi_9606.ENSP00000417229'], ['f_638', 'cpi_9606.ENSP00000225275', 'f_242', 'f_455', 'f_764'], ['f_180', 'cpi_9606.ENSP00000370129', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000266376', 'cpi_9606.ENSP00000344192'], ['f_21', 'cpi_9606.ENSP00000270349', 'f_116', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000251535'], ['f_704', 'cpi_9606.ENSP00000308720', 'f_474', 'cpi_9606.ENSP00000451040', 'f_729'], ['f_646', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000353791', 'cpi_9606.ENSP00000261196', 'cpi_9606.ENSP00000305422'], ['cpi_9606.ENSP00000265724', 'f_407', 'f_401', 'f_722', 'f_129'], ['f_540', 'cpi_9606.ENSP00000226578', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000326119', 'f_505'], ['f_16', 'cpi_9606.ENSP00000360608', 'f_861', 'cpi_9606.ENSP00000225474', 'cpi_9606.ENSP00000242057'], ['f_696', 'cpi_9606.ENSP00000314649', 'cpi_9606.ENSP00000428340', 'cpi_9606.ENSP00000358548', 'f_46'], ['cpi_9606.ENSP00000260682', 'f_22', 'f_466', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000227758'], ['f_692', 'cpi_9606.ENSP00000354280', 'f_508', 'cpi_9606.ENSP00000361359', 'f_752'], ['f_684', 'cpi_9606.ENSP00000349576', 'cpi_9606.ENSP00000365016', 'f_473', 'cpi_9606.ENSP00000398632'], ['f_553', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000262441', 'f_164', 'cpi_9606.ENSP00000003100'], ['f_248', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000327801', 'f_262', 'cpi_9606.ENSP00000308165'], ['f_516', 'cpi_9606.ENSP00000354610', 'cpi_9606.ENSP00000411593', 'f_350', 'cpi_9606.ENSP00000388825'], ['f_345', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000274793', 'cpi_9606.ENSP00000329357', 'cpi_9606.ENSP00000359635'], ['f_353', 'cpi_9606.ENSP00000346768', 'f_298', 'cpi_9606.ENSP00000283635', 'cpi_9606.ENSP00000358730'], ['f_645', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000272847', 'cpi_9606.ENSP00000356436'], ['f_686', 'f_215', 'cpi_9606.ENSP00000231751', 'f_419', 'cpi_9606.ENSP00000222002'], ['f_293', 'cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000253004', 'f_826', 'f_740'], ['f_637', 'cpi_9606.ENSP00000317159', 'cpi_9606.ENSP00000286301', 'cpi_9606.ENSP00000343040', 'cpi_9606.ENSP00000337335'], ['f_681', 'cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000348069', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000261799'], ['f_613', 'cpi_9606.ENSP00000368305', 'cpi_9606.ENSP00000254227', 'f_551', 'cpi_9606.ENSP00000361666'], ['f_667', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000301178'], ['f_567', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000334198', 'f_813', 'cpi_9606.ENSP00000264818'], ['f_439', 'cpi_9606.ENSP00000360967', 'cpi_9606.ENSP00000341885', 'cpi_9606.ENSP00000311095', 'f_361'], ['f_365', 'cpi_9606.ENSP00000323867', 'cpi_9606.ENSP00000264867', 'f_448', 'f_785'], ['f_615', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000335511', 'f_429', 'cpi_9606.ENSP00000359100'], ['cpi_9606.ENSP00000264381', 'f_24', 'cpi_9606.ENSP00000367102', 'cpi_9606.ENSP00000275525', 'f_160'], ['f_683', 'cpi_9606.ENSP00000405573', 'cpi_9606.ENSP00000262367', 'cpi_9606.ENSP00000296871', 'f_409'], ['f_145', 'cpi_9606.ENSP00000375881', 'f_782', 'f_343', 'f_820'], ['f_11', 'cpi_9606.ENSP00000039007', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000360493', 'cpi_9606.ENSP00000261937'], ['f_592', 'cpi_9606.ENSP00000222481', 'cpi_9606.ENSP00000356832', 'cpi_9606.ENSP00000293288', 'f_757'], ['f_698', 'cpi_9606.ENSP00000364709', 'cpi_9606.ENSP00000297316', 'f_770', 'f_518'], ['f_294', 'cpi_9606.ENSP00000219070', 'f_159', 'f_653', 'f_568'], ['f_663', 'cpi_9606.ENSP00000363868', 'f_750', 'f_488', 'cpi_9606.ENSP00000369530'], ['f_680', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000306100', 'cpi_9606.ENSP00000260010', 'cpi_9606.ENSP00000312664'], ['f_593', 'cpi_9606.ENSP00000270142', 'cpi_9606.ENSP00000262999', 'f_230', 'f_822'], ['f_560', 'f_840', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000353224', 'cpi_9606.ENSP00000226574'], ['f_462', 'cpi_9606.ENSP00000328968', 'f_494', 'cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000261693'], ['f_709', 'cpi_9606.ENSP00000305692', 'cpi_9606.ENSP00000255465', 'cpi_9606.ENSP00000365686', 'f_763'], ['f_691', 'cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000346534', 'f_483'], ['f_536', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000385806', 'cpi_9606.ENSP00000259089', 'f_812'], ['f_797', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000328973', 'f_475'], ['f_581', 'cpi_9606.ENSP00000256119', 'f_676', 'cpi_9606.ENSP00000265643', 'cpi_9606.ENSP00000357283'], ['f_641', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000434516', 'cpi_9606.ENSP00000381097', 'cpi_9606.ENSP00000231454'], ['f_619', 'cpi_9606.ENSP00000371236', 'cpi_9606.ENSP00000252723', 'cpi_9606.ENSP00000374323', 'f_394'], ['f_671', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000362353', 'cpi_9606.ENSP00000248553', 'f_609'], ['f_602', 'cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000241600', 'f_477'], ['cpi_9606.ENSP00000360372', 'f_200', 'f_644', 'cpi_9606.ENSP00000309818', 'cpi_9606.ENSP00000155840'], ['f_690', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000332369', 'f_486', 'cpi_9606.ENSP00000354394'], ['f_286', 'cpi_9606.ENSP00000343885', 'cpi_9606.ENSP00000457706', 'cpi_9606.ENSP00000312029', 'f_543'], ['f_573', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000323568', 'cpi_9606.ENSP00000309572'], ['f_689', 'cpi_9606.ENSP00000354532', 'f_650', 'f_496', 'f_533'], ['f_1', 'cpi_9606.ENSP00000376914', 'cpi_9606.ENSP00000427514', 'f_461', 'f_625'], ['f_710', 'cpi_9606.ENSP00000358727', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000316786', 'f_647'], ['f_432', 'cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000428864', 'f_34', 'cpi_9606.ENSP00000274545'], ['f_337', 'cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000358107', 'cpi_9606.ENSP00000347942', 'f_17'], ['f_594', 'cpi_9606.ENSP00000318912', 'cpi_9606.ENSP00000321999', 'cpi_9606.ENSP00000366307', 'f_336'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000225371', 'cpi_9606.ENSP00000274547', 'f_687'], ['f_699', 'cpi_9606.ENSP00000295598', 'f_359', 'cpi_9606.ENSP00000302111', 'f_471'], ['f_349', 'cpi_9606.ENSP00000385834', 'f_522', 'f_801', 'cpi_9606.ENSP00000330393'], ['f_776', 'cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000343204', 'cpi_9606.ENSP00000356954'], ['f_502', 'cpi_9606.ENSP00000279593', 'f_803', 'cpi_9606.ENSP00000276449', 'f_513'], ['f_241', 'cpi_9606.ENSP00000357669', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000267101', 'f_588'], ['f_193', 'cpi_9606.ENSP00000342070', 'f_489', 'f_398', 'cpi_9606.ENSP00000370473'], ['f_702', 'cpi_9606.ENSP00000268053', 'cpi_9606.ENSP00000260649', 'f_514', 'f_422'], ['f_688', 'cpi_9606.ENSP00000309477', 'cpi_9606.ENSP00000297350', 'cpi_9606.ENSP00000263980', 'f_454'], ['f_655', 'cpi_9606.ENSP00000279387', 'cpi_9606.ENSP00000471569', 'cpi_9606.ENSP00000264657', 'f_115'], ['f_199', 'cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000292896', 'f_558', 'f_738'], ['cpi_9606.ENSP00000356438', 'f_213', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000295491', 'f_621'], ['cpi_9606.ENSP00000367959', 'f_456', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000331912'], ['f_586', 'cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000351209', 'f_30'], ['f_693', 'f_517', 'cpi_9606.ENSP00000317842', 'cpi_9606.ENSP00000300061', 'f_532'], ['cpi_9606.ENSP00000272190', 'f_610', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000233242', 'cpi_9606.ENSP00000254810'], ['f_642', 'cpi_9606.ENSP00000360968', 'cpi_9606.ENSP00000326219', 'f_465', 'cpi_9606.ENSP00000348897'], ['f_342', 'cpi_9606.ENSP00000346839', 'f_527', 'f_227', 'cpi_9606.ENSP00000267119'], ['f_662', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000221515', 'f_694'], ['f_375', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000295731', 'f_367', 'f_216'], ['cpi_9606.ENSP00000258743', 'f_652', 'cpi_9606.ENSP00000234071', 'f_314', 'cpi_9606.ENSP00000361206'], ['f_368', 'cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000364212', 'f_515', 'f_630'], ['f_708', 'cpi_9606.ENSP00000364782', 'cpi_9606.ENSP00000359663', 'f_411', 'f_742'], ['f_818', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000374265', 'f_601', 'f_395'], ['f_597', 'cpi_9606.ENSP00000354511', 'f_425', 'cpi_9606.ENSP00000299267', 'f_721'], ['f_798', 'f_485', 'cpi_9606.ENSP00000364731', 'cpi_9606.ENSP00000428924', 'f_717'], ['f_574', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000311028', 'cpi_9606.ENSP00000309493', 'f_397'], ['f_507', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000350198', 'cpi_9606.ENSP00000216862'], ['f_418', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000382659', 'cpi_9606.ENSP00000260356', 'f_605'], ['f_777', 'cpi_9606.ENSP00000296522', 'cpi_9606.ENSP00000367608', 'f_759', 'f_612'], ['f_580', 'cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000295453', 'cpi_9606.ENSP00000365663', 'f_467'], ['f_334', 'cpi_9606.ENSP00000396704', 'f_300', 'cpi_9606.ENSP00000321988', 'f_500'], ['f_493', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000340943', 'cpi_9606.ENSP00000311469', 'f_559'], ['f_464', 'cpi_9606.ENSP00000263088', 'cpi_9606.ENSP00000365380', 'f_575', 'f_860'], ['f_821', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000282753', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000325822'], ['f_249', 'f_305', 'cpi_9606.ENSP00000284981', 'f_805', 'cpi_9606.ENSP00000353878'], ['f_711', 'f_421', 'cpi_9606.ENSP00000340684', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000278616'], ['f_654', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000278175', 'cpi_9606.ENSP00000225964'], ['f_666', 'cpi_9606.ENSP00000312673', 'cpi_9606.ENSP00000280357', 'f_423', 'cpi_9606.ENSP00000252486'], ['f_150', 'cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000318585', 'f_363', 'cpi_9606.ENSP00000256958'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000362649', 'f_480', 'f_780'], ['cpi_9606.ENSP00000295897', 'f_779', 'f_187', 'cpi_9606.ENSP00000410076', 'cpi_9606.ENSP00000307014'], ['f_333', 'cpi_9606.ENSP00000358042', 'cpi_9606.ENSP00000267163', 'f_38', 'f_260'], ['f_549', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000373477', 'f_144', 'cpi_9606.ENSP00000260191'], ['f_351', 'cpi_9606.ENSP00000233944', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000343925', 'f_157'], ['f_412', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000386884', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000389414'], ['f_352', 'cpi_9606.ENSP00000348395', 'cpi_9606.ENSP00000310405', 'cpi_9606.ENSP00000351273', 'f_364'], ['f_244', 'cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000304895', 'cpi_9606.ENSP00000270776', 'cpi_9606.ENSP00000375893'], ['f_537', 'f_457', 'cpi_9606.ENSP00000331746', 'cpi_9606.ENSP00000305221', 'cpi_9606.ENSP00000353427'], ['f_18', 'cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000304408', 'f_784', 'cpi_9606.ENSP00000368104'], ['f_628', 'cpi_9606.ENSP00000216714', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000296122', 'f_700'], ['f_188', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000300900', 'f_152'], ['f_734', 'cpi_9606.ENSP00000226730', 'f_301', 'cpi_9606.ENSP00000427562', 'cpi_9606.ENSP00000270474'], ['f_259', 'cpi_9606.ENSP00000374467', 'cpi_9606.ENSP00000239938', 'cpi_9606.ENSP00000351885', 'f_705'], ['f_449', 'cpi_9606.ENSP00000397026', 'cpi_9606.ENSP00000419692', 'cpi_9606.ENSP00000463999', 'f_761'], ['f_442', 'cpi_9606.ENSP00000359998', 'cpi_9606.ENSP00000362924', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000343782'], ['f_695', 'cpi_9606.ENSP00000338018', 'cpi_9606.ENSP00000220003', 'f_414', 'cpi_9606.ENSP00000306490'], ['f_636', 'cpi_9606.ENSP00000337103', 'cpi_9606.ENSP00000318822', 'cpi_9606.ENSP00000253727', 'f_756'], ['f_819', 'cpi_9606.ENSP00000319591', 'cpi_9606.ENSP00000448059', 'cpi_9606.ENSP00000351908', 'f_504'], ['cpi_9606.ENSP00000337450', 'cpi_9606.ENSP00000302846', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000176763', 'f_206'], ['f_685', 'cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000320935', 'f_250'], ['f_430', 'cpi_9606.ENSP00000359680', 'cpi_9606.ENSP00000384273', 'cpi_9606.ENSP00000366506', 'f_563'], ['f_434', 'cpi_9606.ENSP00000330032', 'cpi_9606.ENSP00000407375', 'f_378', 'cpi_9606.ENSP00000356694'], ['f_377', 'cpi_9606.ENSP00000332973', 'cpi_9606.ENSP00000297268', 'f_661', 'cpi_9606.ENSP00000291294'], ['f_758', 'cpi_9606.ENSP00000352516', 'f_658', 'cpi_9606.ENSP00000350005', 'cpi_9606.ENSP00000303174'], ['f_550', 'cpi_9606.ENSP00000355627', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000252029', 'f_399'], ['f_255', 'cpi_9606.ENSP00000330484', 'cpi_9606.ENSP00000364802', 'cpi_9606.ENSP00000296545', 'f_713'], ['f_450', 'cpi_9606.ENSP00000252321', 'cpi_9606.ENSP00000361151', 'f_544', 'cpi_9606.ENSP00000231449'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000311165', 'f_737', 'cpi_9606.ENSP00000344674', 'f_153'], ['f_437', 'cpi_9606.ENSP00000264426', 'cpi_9606.ENSP00000354558', 'cpi_9606.ENSP00000359793', 'cpi_9606.ENSP00000265403'], ['f_332', 'cpi_9606.ENSP00000226299', 'cpi_9606.ENSP00000296677', 'cpi_9606.ENSP00000267843', 'f_716'], ['f_623', 'cpi_9606.ENSP00000266682', 'cpi_9606.ENSP00000262160', 'cpi_9606.ENSP00000287641', 'cpi_9606.ENSP00000241261'], ['f_633', 'cpi_9606.ENSP00000301634', 'cpi_9606.ENSP00000346103', 'cpi_9606.ENSP00000239849', 'f_701'], ['f_607', 'cpi_9606.ENSP00000234310', 'cpi_9606.ENSP00000347979', 'cpi_9606.ENSP00000349003', 'cpi_9606.ENSP00000341045'], ['f_555', 'cpi_9606.ENSP00000295256', 'cpi_9606.ENSP00000320401', 'cpi_9606.ENSP00000262461', 'cpi_9606.ENSP00000336630'], ['f_14', 'cpi_9606.ENSP00000287878', 'cpi_9606.ENSP00000262735', 'cpi_9606.ENSP00000231228', 'cpi_9606.ENSP00000270570'], ['f_755', 'cpi_9606.ENSP00000363965', 'cpi_9606.ENSP00000307235', 'cpi_

🔄 Processing features: 100%|██████████| 2147/2147 [10:16<00:00,  3.48feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'f_413', 'f_262', 'f_151', 'f_845'], ['f_308', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000288602', 'f_616', 'cpi_9606.ENSP00000299847'], ['f_20', 'cpi_9606.ENSP00000339260', 'f_729', 'cpi_9606.ENSP00000343204', 'cpi_9606.ENSP00000352011'], ['f_374', 'cpi_9606.ENSP00000222481', 'cpi_9606.ENSP00000253004', 'f_768', 'cpi_9606.ENSP00000359424'], ['f_452', 'f_25', 'cpi_9606.ENSP00000337773', 'f_789', 'cpi_9606.ENSP00000351957'], ['f_346', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000357068', 'f_629', 'cpi_9606.ENSP00000286479'], ['f_406', 'cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000344352', 'cpi_9606.ENSP00000394936'], ['f_380', 'cpi_9606.ENSP00000381097', 'f_726', 'cpi_9606.ENSP00000263377', 'cpi_9606.ENSP00000356094'], ['f_440', 'cpi_9606.ENSP00000358107', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000378517', 'cpi_9606.ENSP00000342235'], ['f_12', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000380318', 'cpi_9606.ENSP00000365233', 'f_635'], ['f_614', 'cpi_9606.ENSP00000332369', 'cpi_9606.ENSP00000251535', 'f_511', 'f_510'], ['f_3', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000283254', 'f_792', 'cpi_9606.ENSP00000292427'], ['f_23', 'cpi_9606.ENSP00000279387', 'cpi_9606.ENSP00000385026', 'f_194', 'f_292'], ['f_451', 'cpi_9606.ENSP00000312286', 'f_31', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000429374'], ['f_571', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000279178', 'f_836'], ['f_391', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000430684', 'cpi_9606.ENSP00000369038'], ['f_392', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000321584', 'cpi_9606.ENSP00000259271', 'cpi_9606.ENSP00000354476'], ['f_37', 'cpi_9606.ENSP00000263321', 'f_229', 'f_675', 'cpi_9606.ENSP00000307014'], ['f_405', 'cpi_9606.ENSP00000305742', 'cpi_9606.ENSP00000395653', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000382659'], ['f_366', 'cpi_9606.ENSP00000306397', 'f_428', 'f_831', 'cpi_9606.ENSP00000312455'], ['f_146', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000317379', 'f_47'], ['f_185', 'cpi_9606.ENSP00000386284', 'cpi_9606.ENSP00000246553', 'cpi_9606.ENSP00000409007', 'f_27'], ['f_192', 'cpi_9606.ENSP00000345096', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000359353', 'cpi_9606.ENSP00000309493'], ['f_143', 'cpi_9606.ENSP00000332549', 'cpi_9606.ENSP00000349577', 'f_529', 'f_767'], ['f_339', 'cpi_9606.ENSP00000291295', 'f_670', 'cpi_9606.ENSP00000301891', 'cpi_9606.ENSP00000337103'], ['f_390', 'cpi_9606.ENSP00000296412', 'f_866', 'cpi_9606.ENSP00000319531', 'cpi_9606.ENSP00000221972'], ['f_420', 'cpi_9606.ENSP00000397582', 'f_328', 'cpi_9606.ENSP00000360493', 'f_526'], ['f_528', 'cpi_9606.ENSP00000357204', 'cpi_9606.ENSP00000262888', 'cpi_9606.ENSP00000308774', 'cpi_9606.ENSP00000365016'], ['f_338', 'cpi_9606.ENSP00000292896', 'cpi_9606.ENSP00000360773', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000265294'], ['f_186', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000283635', 'cpi_9606.ENSP00000293404', 'f_118'], ['f_617', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000438284', 'cpi_9606.ENSP00000367848'], ['f_299', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000306100', 'cpi_9606.ENSP00000355629', 'cpi_9606.ENSP00000320171'], ['f_672', 'cpi_9606.ENSP00000270142', 'f_830', 'f_35', 'f_43'], ['f_393', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000327255', 'cpi_9606.ENSP00000451040', 'cpi_9606.ENSP00000445340'], ['f_659', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000332296', 'cpi_9606.ENSP00000361359'], ['f_15', 'cpi_9606.ENSP00000320401', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000343392', 'f_214'], ['f_643', 'cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000359539', 'cpi_9606.ENSP00000470087'], ['f_287', 'cpi_9606.ENSP00000241052', 'f_622', 'f_773', 'f_799'], ['f_19', 'cpi_9606.ENSP00000368305', 'cpi_9606.ENSP00000428924', 'cpi_9606.ENSP00000304822', 'cpi_9606.ENSP00000417229'], ['f_566', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000257290', 'cpi_9606.ENSP00000307599'], ['f_639', 'f_427', 'cpi_9606.ENSP00000237014', 'f_166', 'cpi_9606.ENSP00000216540'], ['f_181', 'cpi_9606.ENSP00000273550', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000471569', 'f_132'], ['f_569', 'cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000220616', 'f_725'], ['cpi_9606.ENSP00000311032', 'cpi_9606.ENSP00000003100', 'f_164', 'f_297', 'f_587'], ['f_33', 'cpi_9606.ENSP00000353720', 'f_706', 'f_298', 'cpi_9606.ENSP00000435591'], ['f_638', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000301974', 'f_757'], ['f_535', 'cpi_9606.ENSP00000286091', 'cpi_9606.ENSP00000354610', 'f_327', 'cpi_9606.ENSP00000339527'], ['f_2', 'cpi_9606.ENSP00000354532', 'cpi_9606.ENSP00000323568', 'f_788', 'f_834'], ['f_656', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000264637', 'cpi_9606.ENSP00000223366'], ['f_341', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000364805', 'cpi_9606.ENSP00000216392'], ['cpi_9606.ENSP00000353820', 'f_131', 'f_26', 'f_551', 'f_749'], ['f_257', 'cpi_9606.ENSP00000216962', 'cpi_9606.ENSP00000311028', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000222330'], ['f_335', 'f_752', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000414334'], ['f_712', 'cpi_9606.ENSP00000357669', 'f_771', 'cpi_9606.ENSP00000326219', 'cpi_9606.ENSP00000296122'], ['f_696', 'cpi_9606.ENSP00000274353', 'cpi_9606.ENSP00000355657', 'cpi_9606.ENSP00000255409', 'f_474'], ['f_579', 'cpi_9606.ENSP00000229319', 'f_330', 'cpi_9606.ENSP00000232219', 'f_497'], ['f_16', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000354107', 'cpi_9606.ENSP00000419692', 'cpi_9606.ENSP00000222390'], ['f_443', 'cpi_9606.ENSP00000349078', 'cpi_9606.ENSP00000275300', 'f_554', 'f_785'], ['f_615', 'f_839', 'cpi_9606.ENSP00000225275', 'f_419', 'cpi_9606.ENSP00000357283'], ['cpi_9606.ENSP00000360372', 'f_22', 'f_644', 'cpi_9606.ENSP00000353362', 'f_509'], ['f_680', 'cpi_9606.ENSP00000295454', 'cpi_9606.ENSP00000273398', 'cpi_9606.ENSP00000216037', 'cpi_9606.ENSP00000351908'], ['f_516', 'cpi_9606.ENSP00000244217', 'cpi_9606.ENSP00000310447', 'cpi_9606.ENSP00000387946', 'f_46'], ['f_345', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000430031', 'cpi_9606.ENSP00000252809', 'f_583'], ['f_285', 'cpi_9606.ENSP00000287878', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000366307', 'cpi_9606.ENSP00000305422'], ['f_686', 'f_215', 'f_343', 'cpi_9606.ENSP00000231751', 'f_650'], ['f_682', 'f_715', 'cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000330199', 'cpi_9606.ENSP00000260010'], ['f_645', 'cpi_9606.ENSP00000254488', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000355317', 'cpi_9606.ENSP00000282561'], ['f_611', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000333212', 'cpi_9606.ENSP00000368880', 'f_460'], ['f_637', 'cpi_9606.ENSP00000332256', 'cpi_9606.ENSP00000350785', 'cpi_9606.ENSP00000340691', 'f_820'], ['f_293', 'cpi_9606.ENSP00000301633', 'cpi_9606.ENSP00000390600', 'f_350', 'cpi_9606.ENSP00000348897'], ['f_667', 'cpi_9606.ENSP00000352835', 'f_676', 'f_361', 'f_408'], ['f_340', 'cpi_9606.ENSP00000314649', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000362403', 'cpi_9606.ENSP00000262187'], ['f_689', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000164139', 'cpi_9606.ENSP00000309572'], ['f_248', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000331358', 'cpi_9606.ENSP00000364212', 'f_518'], ['f_540', 'cpi_9606.ENSP00000297258', 'cpi_9606.ENSP00000367123', 'cpi_9606.ENSP00000319788', 'cpi_9606.ENSP00000326119'], ['f_684', 'cpi_9606.ENSP00000254976', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000259089', 'cpi_9606.ENSP00000354394'], ['f_698', 'cpi_9606.ENSP00000364709', 'cpi_9606.ENSP00000355778', 'f_388', 'f_508'], ['f_439', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000367851', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000343477'], ['f_594', 'cpi_9606.ENSP00000252723', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000264318'], ['f_671', 'f_407', 'cpi_9606.ENSP00000360967', 'cpi_9606.ENSP00000362353', 'cpi_9606.ENSP00000375809'], ['f_697', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000314508', 'cpi_9606.ENSP00000347942', 'cpi_9606.ENSP00000330393'], ['f_613', 'cpi_9606.ENSP00000362924', 'cpi_9606.ENSP00000306606', 'cpi_9606.ENSP00000312664', 'f_505'], ['f_704', 'cpi_9606.ENSP00000225964', 'cpi_9606.ENSP00000253799', 'f_466', 'f_728'], ['f_683', 'cpi_9606.ENSP00000323867', 'cpi_9606.ENSP00000386171', 'cpi_9606.ENSP00000296871', 'f_436'], ['cpi_9606.ENSP00000342007', 'f_347', 'cpi_9606.ENSP00000299178', 'f_736', 'cpi_9606.ENSP00000254227'], ['f_692', 'cpi_9606.ENSP00000261205', 'cpi_9606.ENSP00000254810', 'f_473', 'cpi_9606.ENSP00000353292'], ['f_573', 'cpi_9606.ENSP00000259486', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000262948', 'cpi_9606.ENSP00000343040'], ['f_241', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000252029', 'f_455', 'cpi_9606.ENSP00000389338'], ['f_597', 'cpi_9606.ENSP00000298171', 'cpi_9606.ENSP00000319814', 'cpi_9606.ENSP00000272227', 'cpi_9606.ENSP00000376943'], ['f_693', 'cpi_9606.ENSP00000342070', 'f_815', 'f_778', 'cpi_9606.ENSP00000267119'], ['f_641', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000341885', 'cpi_9606.ENSP00000353472', 'cpi_9606.ENSP00000388648'], ['f_602', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000467676', 'cpi_9606.ENSP00000286301'], ['f_666', 'cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000316786', 'cpi_9606.ENSP00000410294'], ['f_553', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000340943', 'cpi_9606.ENSP00000327850', 'f_30'], ['cpi_9606.ENSP00000356438', 'f_213', 'f_429', 'f_653', 'f_159'], ['f_549', 'cpi_9606.ENSP00000364782', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000394932', 'f_827'], ['f_180', 'cpi_9606.ENSP00000370129', 'cpi_9606.ENSP00000309477', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000344192'], ['f_681', 'f_417', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000348069', 'cpi_9606.ENSP00000363832'], ['f_333', 'cpi_9606.ENSP00000354850', 'cpi_9606.ENSP00000270631', 'cpi_9606.ENSP00000225474', 'f_202'], ['cpi_9606.ENSP00000367959', 'f_129', 'cpi_9606.ENSP00000256958', 'f_812', 'cpi_9606.ENSP00000267101'], ['f_699', 'f_488', 'cpi_9606.ENSP00000318912', 'cpi_9606.ENSP00000260649', 'f_813'], ['cpi_9606.ENSP00000265724', 'f_401', 'f_207', 'cpi_9606.ENSP00000309818', 'f_722'], ['f_365', 'cpi_9606.ENSP00000226578', 'cpi_9606.ENSP00000329357', 'f_764', 'cpi_9606.ENSP00000361666'], ['f_353', 'cpi_9606.ENSP00000381607', 'cpi_9606.ENSP00000294954', 'f_763', 'cpi_9606.ENSP00000261937'], ['f_375', 'f_242', 'f_631', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000274793'], ['f_690', 'f_609', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000394033', 'cpi_9606.ENSP00000463999'], ['f_593', 'f_719', 'cpi_9606.ENSP00000262407', 'f_840', 'cpi_9606.ENSP00000365686'], ['f_498', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000399168', 'cpi_9606.ENSP00000365380', 'cpi_9606.ENSP00000309124'], ['f_702', 'cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000261196', 'f_483'], ['f_642', 'cpi_9606.ENSP00000256119', 'f_568', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000277010'], ['f_818', 'f_533', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000358548', 'cpi_9606.ENSP00000225927'], ['f_430', 'cpi_9606.ENSP00000364035', 'cpi_9606.ENSP00000388825', 'cpi_9606.ENSP00000278616', 'f_425'], ['f_432', 'f_411', 'cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000317842', 'f_486'], ['f_691', 'cpi_9606.ENSP00000276431', 'cpi_9606.ENSP00000358595', 'f_513', 'f_448'], ['f_567', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000246337', 'cpi_9606.ENSP00000391676', 'cpi_9606.ENSP00000367102'], ['f_663', 'cpi_9606.ENSP00000363868', 'f_750', 'cpi_9606.ENSP00000369530', 'f_167'], ['f_646', 'cpi_9606.ENSP00000305302', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000282753'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000219833', 'f_34', 'f_477', 'cpi_9606.ENSP00000362649'], ['f_21', 'cpi_9606.ENSP00000306490', 'f_116', 'cpi_9606.ENSP00000252519', 'f_467'], ['f_150', 'cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000318585', 'cpi_9606.ENSP00000309103', 'cpi_9606.ENSP00000245539'], ['f_688', 'cpi_9606.ENSP00000349576', 'cpi_9606.ENSP00000398632', 'cpi_9606.ENSP00000231228', 'cpi_9606.ENSP00000275525'], ['f_342', 'f_782', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000219919'], ['f_628', 'cpi_9606.ENSP00000362513', 'cpi_9606.ENSP00000295491', 'cpi_9606.ENSP00000248076', 'cpi_9606.ENSP00000300061'], ['f_604', 'cpi_9606.ENSP00000312673', 'cpi_9606.ENSP00000321999', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000320935'], ['f_294', 'cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000218099', 'f_160', 'f_394'], ['f_536', 'f_770', 'cpi_9606.ENSP00000331746', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000457706'], ['f_464', 'cpi_9606.ENSP00000234310', 'cpi_9606.ENSP00000352584', 'cpi_9606.ENSP00000303248', 'cpi_9606.ENSP00000356954'], ['f_337', 'cpi_9606.ENSP00000303211', 'f_833', 'cpi_9606.ENSP00000266376', 'cpi_9606.ENSP00000381333'], ['f_351', 'cpi_9606.ENSP00000233944', 'cpi_9606.ENSP00000356671', 'cpi_9606.ENSP00000294728', 'f_409'], ['f_145', 'cpi_9606.ENSP00000335620', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000267017', 'f_471'], ['f_193', 'cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000296545', 'cpi_9606.ENSP00000448059', 'f_500'], ['f_259', 'cpi_9606.ENSP00000353427', 'cpi_9606.ENSP00000265403', 'cpi_9606.ENSP00000303522', 'f_115'], ['f_370', 'cpi_9606.ENSP00000447378', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000312029', 'cpi_9606.ENSP00000337335'], ['f_619', 'cpi_9606.ENSP00000366927', 'cpi_9606.ENSP00000328173', 'cpi_9606.ENSP00000293288', 'f_314'], ['f_537', 'f_423', 'cpi_9606.ENSP00000353915', 'cpi_9606.ENSP00000427562', 'cpi_9606.ENSP00000353224'], ['cpi_9606.ENSP00000354612', 'f_216', 'f_694', 'cpi_9606.ENSP00000301178', 'f_456'], ['f_199', 'cpi_9606.ENSP00000385834', 'f_489', 'f_398', 'cpi_9606.ENSP00000353791'], ['f_418', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000295256', 'cpi_9606.ENSP00000258749', 'f_625'], ['f_709', 'cpi_9606.ENSP00000405573', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000304895', 'f_791'], ['f_18', 'cpi_9606.ENSP00000472933', 'cpi_9606.ENSP00000311095', 'cpi_9606.ENSP00000307235', 'f_195'], ['f_592', 'cpi_9606.ENSP00000238018', 'cpi_9606.ENSP00000263980', 'f_861', 'cpi_9606.ENSP00000328973'], ['cpi_9606.ENSP00000222982', 'f_200', 'f_543', 'cpi_9606.ENSP00000292513', 'cpi_9606.ENSP00000344674'], ['f_286', 'cpi_9606.ENSP00000244051', 'cpi_9606.ENSP00000231454', 'cpi_9606.ENSP00000261799', 'cpi_9606.ENSP00000343925'], ['f_507', 'f_826', 'cpi_9606.ENSP00000338018', 'cpi_9606.ENSP00000320866', 'f_740'], ['cpi_9606.ENSP00000337450', 'f_461', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000295731', 'cpi_9606.ENSP00000364310'], ['f_244', 'cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000321988', 'cpi_9606.ENSP00000261693', 'cpi_9606.ENSP00000374323'], ['f_695', 'cpi_9606.ENSP00000354511', 'f_822', 'f_475', 'f_522'], ['f_662', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000300093', 'f_421', 'cpi_9606.ENSP00000416293'], ['f_607', 'cpi_9606.ENSP00000216714', 'cpi_9606.ENSP00000236671', 'cpi_9606.ENSP00000302967', 'f_860'], ['f_462', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000256383', 'cpi_9606.ENSP00000241256', 'f_496'], ['f_368', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000272298', 'f_647', 'f_515'], ['f_502', 'cpi_9606.ENSP00000279593', 'cpi_9606.ENSP00000295834', 'f_803', 'cpi_9606.ENSP00000359793'], ['f_776', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000349467', 'cpi_9606.ENSP00000362344', 'f_784'], ['f_24', 'cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000219700', 'f_805'], ['f_249', 'f_300', 'cpi_9606.ENSP00000284981', 'f_742', 'cpi_9606.ENSP00000308165'], ['f_581', 'cpi_9606.ENSP00000285979', 'cpi_9606.ENSP00000262367', 'f_422', 'cpi_9606.ENSP00000304915'], ['f_623', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000441691', 'cpi_9606.ENSP00000227758', 'f_230'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000322617', 'f_17', 'cpi_9606.ENSP00000291294', 'cpi_9606.ENSP00000299267'], ['f_580', 'cpi_9606.ENSP00000295453', 'cpi_9606.ENSP00000226574', 'cpi_9606.ENSP00000282018', 'f_363'], ['f_685', 'cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000346017', 'f_759'], ['f_493', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000427514', 'f_336'], ['f_819', 'cpi_9606.ENSP00000308032', 'cpi_9606.ENSP00000354569', 'f_717', 'cpi_9606.ENSP00000288135'], ['f_798', 'cpi_9606.ENSP00000364731', 'f_485', 'cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000338548'], ['f_701', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000320025', 'f_359', 'cpi_9606.ENSP00000380247'], ['f_349', 'cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000296522', 'f_494', 'cpi_9606.ENSP00000411593'], ['f_654', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000306138', 'f_605'], ['f_777', 'cpi_9606.ENSP00000374467', 'cpi_9606.ENSP00000393312', 'cpi_9606.ENSP00000293745', 'f_397'], ['f_586', 'cpi_9606.ENSP00000220809', 'cpi_9606.ENSP00000359211', 'f_544', 'f_517'], ['f_797', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000252486', 'f_480'], ['f_11', 'cpi_9606.ENSP00000039007', 'cpi_9606.ENSP00000262160', 'cpi_9606.ENSP00000264657', 'f_558'], ['f_821', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000338082', 'cpi_9606.ENSP00000242057', 'cpi_9606.ENSP00000366506'], ['f_450', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000314949', 'cpi_9606.ENSP00000459962', 'f_588'], ['f_779', 'cpi_9606.ENSP00000337459', 'cpi_9606.ENSP00000384957', 'cpi_9606.ENSP00000331912', 'f_367'], ['f_708', 'cpi_9606.ENSP00000305480', 'cpi_9606.ENSP00000310305', 'f_454', 'cpi_9606.ENSP00000302111'], ['f_352', 'cpi_9606.ENSP00000383365', 'cpi_9606.ENSP00000379086', 'cpi_9606.ENSP00000307240', 'f_738'], ['f_548', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000359100', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000274547'], ['f_555', 'cpi_9606.ENSP00000360247', 'cpi_9606.ENSP00000430432', 'cpi_9606.ENSP00000278175', 'f_610'], ['cpi_9606.ENSP00000272190', 'f_187', 'cpi_9606.ENSP00000236850', 'f_157', 'cpi_9606.ENSP00000266682'], ['f_655', 'cpi_9606.ENSP00000371236', 'cpi_9606.ENSP00000359663', 'f_559', 'cpi_9606.ENSP00000336630'], ['f_591', 'cpi_9606.ENSP00000219070', 'cpi_9606.ENSP00000398655', 'cpi_9606.ENSP00000216341', 'f_227'], ['f_541', 'cpi_9606.ENSP00000357066', 'cpi_9606.ENSP00000303424', 'cpi_9606.ENSP00000267163', 'f_801'], ['f_437', 'cpi_9606.ENSP00000297792', 'cpi_9606.ENSP00000303325', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000354558'], ['f_356', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000229447', 'cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000303452'], ['f_707', 'cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000318646', 'f_305'], ['f_453', 'cpi_9606.ENSP00000338627', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000370473', 'f_705'], ['f_153', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000259396', 'cpi_9606.ENSP00000428824', 'cpi_9606.ENSP00000364802'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000311165', 'f_737', 'cpi_9606.ENSP00000301634', 'cpi_9606.ENSP00000260191'], ['f_560', 'cpi_9606.ENSP00000299855', 'cpi_9606.ENSP00000419782', 'f_761', 'cpi_9606.ENSP00000346298'], ['f_711', 'f_364', 'cpi_9606.ENSP00000267377', 'cpi_9606.ENSP00000318822', 'cpi_9606.ENSP00000309649'], ['f_381', 'cpi_9606.ENSP00000434516', 'cpi_9606.ENSP00000262027', 'f_780', 'cpi_9606.ENSP00000260356'], ['f_755', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000311469', 'f_395', 'cpi_9606.ENSP00000237527'], ['f_377', 'cpi_9606.ENSP00000378323', 'cpi_9606.ENSP000

🔄 Processing features: 100%|██████████| 2147/2147 [10:17<00:00,  3.48feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'f_413', 'f_46', 'f_151', 'f_262'], ['f_374', 'cpi_9606.ENSP00000264705', 'f_831', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000409007'], ['f_308', 'cpi_9606.ENSP00000358784', 'cpi_9606.ENSP00000394936', 'cpi_9606.ENSP00000369375', 'f_529'], ['f_20', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000333212', 'cpi_9606.ENSP00000381097'], ['f_393', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000367851', 'cpi_9606.ENSP00000355629'], ['f_3', 'cpi_9606.ENSP00000023897', 'f_815', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000337335'], ['f_392', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000255409', 'f_510'], ['f_672', 'cpi_9606.ENSP00000279387', 'f_292', 'f_767', 'f_47'], ['f_391', 'cpi_9606.ENSP00000357204', 'f_866', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000430684'], ['f_346', 'cpi_9606.ENSP00000279178', 'cpi_9606.ENSP00000376432', 'f_629', 'cpi_9606.ENSP00000395653'], ['f_406', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000342235', 'f_820'], ['f_23', 'cpi_9606.ENSP00000319984', 'f_408', 'f_229', 'cpi_9606.ENSP00000364310'], ['f_299', 'cpi_9606.ENSP00000264162', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000277010', 'f_31'], ['f_452', 'f_25', 'cpi_9606.ENSP00000263088', 'f_789', 'cpi_9606.ENSP00000360773'], ['f_617', 'cpi_9606.ENSP00000394033', 'f_726', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000265294'], ['f_380', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000355533', 'cpi_9606.ENSP00000257290', 'f_768'], ['f_287', 'cpi_9606.ENSP00000241052', 'f_194', 'cpi_9606.ENSP00000349320', 'f_118'], ['f_614', 'cpi_9606.ENSP00000358107', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000344352'], ['f_185', 'cpi_9606.ENSP00000354850', 'f_845', 'cpi_9606.ENSP00000414334', 'cpi_9606.ENSP00000221972'], ['f_192', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000321584', 'cpi_9606.ENSP00000359353', 'f_131'], ['f_643', 'cpi_9606.ENSP00000345096', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000354476', 'f_622'], ['f_566', 'cpi_9606.ENSP00000312286', 'f_836', 'cpi_9606.ENSP00000329357', 'f_417'], ['f_571', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000301891', 'cpi_9606.ENSP00000287766', 'f_736'], ['f_405', 'cpi_9606.ENSP00000368305', 'cpi_9606.ENSP00000367848', 'f_635', 'cpi_9606.ENSP00000356094'], ['f_15', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000304822', 'cpi_9606.ENSP00000220616'], ['f_440', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000378517', 'f_791'], ['f_451', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000254066'], ['f_335', 'f_752', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000295454', 'f_511'], ['f_186', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000359096'], ['f_366', 'cpi_9606.ENSP00000402152', 'f_428', 'cpi_9606.ENSP00000321988', 'cpi_9606.ENSP00000376178'], ['f_143', 'cpi_9606.ENSP00000313490', 'f_328', 'f_773', 'f_719'], ['f_528', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000332296', 'cpi_9606.ENSP00000299267'], ['f_2', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000219794', 'cpi_9606.ENSP00000319788', 'f_526'], ['f_19', 'cpi_9606.ENSP00000312326', 'cpi_9606.ENSP00000286301', 'f_327', 'cpi_9606.ENSP00000252809'], ['f_638', 'f_839', 'cpi_9606.ENSP00000292896', 'cpi_9606.ENSP00000343204', 'f_830'], ['f_37', 'cpi_9606.ENSP00000263321', 'f_43', 'f_202', 'cpi_9606.ENSP00000282753'], ['f_656', 'cpi_9606.ENSP00000261205', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000309124', 'f_27'], ['f_146', 'cpi_9606.ENSP00000254976', 'cpi_9606.ENSP00000236671', 'f_297', 'cpi_9606.ENSP00000340691'], ['f_12', 'cpi_9606.ENSP00000314214', 'cpi_9606.ENSP00000445340', 'cpi_9606.ENSP00000297350', 'f_670'], ['f_339', 'f_509', 'cpi_9606.ENSP00000353362', 'f_834', 'cpi_9606.ENSP00000256383'], ['f_338', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000331746', 'cpi_9606.ENSP00000233242', 'f_460'], ['cpi_9606.ENSP00000353820', 'f_26', 'f_350', 'f_675', 'cpi_9606.ENSP00000286648'], ['f_696', 'cpi_9606.ENSP00000397582', 'cpi_9606.ENSP00000374323', 'f_298', 'cpi_9606.ENSP00000354394'], ['cpi_9606.ENSP00000311032', 'f_394', 'f_207', 'f_554', 'f_788'], ['f_33', 'f_706', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000283635'], ['f_535', 'cpi_9606.ENSP00000262888', 'cpi_9606.ENSP00000354107', 'f_330', 'cpi_9606.ENSP00000296122'], ['f_712', 'cpi_9606.ENSP00000261755', 'f_35', 'f_725', 'f_771'], ['f_639', 'f_427', 'cpi_9606.ENSP00000285979', 'cpi_9606.ENSP00000291700', 'f_166'], ['f_181', 'cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000451040', 'f_167'], ['f_257', 'cpi_9606.ENSP00000332549', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000258749', 'cpi_9606.ENSP00000222330'], ['f_611', 'cpi_9606.ENSP00000355155', 'f_214', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000264637'], ['f_697', 'cpi_9606.ENSP00000358727', 'f_749', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000216037'], ['f_341', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000273398', 'f_616', 'cpi_9606.ENSP00000312455'], ['f_340', 'cpi_9606.ENSP00000373477', 'cpi_9606.ENSP00000387946', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000389338'], ['cpi_9606.ENSP00000265724', 'f_455', 'f_757', 'f_785', 'f_436'], ['f_285', 'cpi_9606.ENSP00000229447', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000316786', 'cpi_9606.ENSP00000307599'], ['f_615', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000335511', 'f_587', 'cpi_9606.ENSP00000351957'], ['cpi_9606.ENSP00000342007', 'f_336', 'cpi_9606.ENSP00000299178', 'f_799', 'cpi_9606.ENSP00000348827'], ['f_692', 'cpi_9606.ENSP00000286621', 'f_474', 'f_728', 'cpi_9606.ENSP00000457706'], ['f_420', 'cpi_9606.ENSP00000226578', 'f_497', 'cpi_9606.ENSP00000360493', 'cpi_9606.ENSP00000470087'], ['f_579', 'cpi_9606.ENSP00000234389', 'cpi_9606.ENSP00000231188', 'cpi_9606.ENSP00000216862', 'f_496'], ['f_613', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000361359'], ['f_516', 'cpi_9606.ENSP00000244217', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000343477', 'cpi_9606.ENSP00000385026'], ['f_443', 'cpi_9606.ENSP00000223366', 'cpi_9606.ENSP00000327850', 'cpi_9606.ENSP00000339527', 'f_722'], ['f_553', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000362353', 'cpi_9606.ENSP00000003100', 'f_764'], ['f_540', 'cpi_9606.ENSP00000380318', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000387888', 'cpi_9606.ENSP00000326119'], ['f_684', 'cpi_9606.ENSP00000354532', 'cpi_9606.ENSP00000262352', 'f_466', 'cpi_9606.ENSP00000417229'], ['f_180', 'cpi_9606.ENSP00000352835', 'cpi_9606.ENSP00000343925', 'f_132', 'f_505'], ['f_659', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000388648', 'cpi_9606.ENSP00000356958'], ['f_646', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000320025'], ['f_345', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000466799', 'cpi_9606.ENSP00000263339', 'f_583'], ['f_569', 'cpi_9606.ENSP00000237014', 'cpi_9606.ENSP00000267101', 'f_631', 'cpi_9606.ENSP00000283254'], ['f_637', 'cpi_9606.ENSP00000332256', 'cpi_9606.ENSP00000356832', 'f_729', 'cpi_9606.ENSP00000343040'], ['f_704', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000305692', 'f_508', 'cpi_9606.ENSP00000353292'], ['f_293', 'cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000344192', 'cpi_9606.ENSP00000253004', 'f_812'], ['f_680', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000306100', 'cpi_9606.ENSP00000365016', 'cpi_9606.ENSP00000358548'], ['f_353', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000386884', 'f_827'], ['cpi_9606.ENSP00000367959', 'f_129', 'f_22', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000256958'], ['f_432', 'cpi_9606.ENSP00000350616', 'f_533', 'f_486', 'cpi_9606.ENSP00000262367'], ['f_645', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000341885', 'cpi_9606.ENSP00000282561', 'cpi_9606.ENSP00000355192'], ['f_390', 'cpi_9606.ENSP00000308897', 'cpi_9606.ENSP00000311095', 'f_782', 'f_551'], ['f_567', 'cpi_9606.ENSP00000254488', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000251535', 'f_715'], ['f_671', 'cpi_9606.ENSP00000216465', 'f_407', 'cpi_9606.ENSP00000231228', 'f_792'], ['f_686', 'f_215', 'f_419', 'cpi_9606.ENSP00000342070', 'f_361'], ['f_698', 'cpi_9606.ENSP00000364709', 'f_388', 'cpi_9606.ENSP00000297316', 'f_518'], ['f_689', 'cpi_9606.ENSP00000309477', 'cpi_9606.ENSP00000331912', 'cpi_9606.ENSP00000300061', 'cpi_9606.ENSP00000301178'], ['f_16', 'cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000274793', 'f_242'], ['f_24', 'f_216', 'cpi_9606.ENSP00000338018', 'f_740', 'cpi_9606.ENSP00000218099'], ['f_439', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000275216', 'cpi_9606.ENSP00000398632', 'cpi_9606.ENSP00000427514'], ['f_691', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000296871', 'f_483'], ['f_682', 'f_401', 'f_778', 'cpi_9606.ENSP00000397026', 'cpi_9606.ENSP00000231454'], ['f_365', 'cpi_9606.ENSP00000405573', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000295491', 'f_409'], ['f_560', 'f_840', 'cpi_9606.ENSP00000262407', 'cpi_9606.ENSP00000312664', 'cpi_9606.ENSP00000323568'], ['f_21', 'cpi_9606.ENSP00000306490', 'f_116', 'cpi_9606.ENSP00000252519', 'f_467'], ['f_667', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000327431', 'f_343', 'cpi_9606.ENSP00000347942'], ['cpi_9606.ENSP00000295897', 'f_115', 'f_454', 'f_159', 'f_644'], ['f_681', 'f_558', 'f_676', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000371929'], ['f_663', 'f_750', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000320866', 'f_488'], ['f_602', 'cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000266376'], ['f_619', 'cpi_9606.ENSP00000364212', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000252723', 'cpi_9606.ENSP00000264867'], ['f_537', 'cpi_9606.ENSP00000328968', 'f_164', 'cpi_9606.ENSP00000305221', 'cpi_9606.ENSP00000320935'], ['f_248', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000309818', 'f_473', 'cpi_9606.ENSP00000252486'], ['f_502', 'cpi_9606.ENSP00000264382', 'f_861', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000275525'], ['f_375', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000262187', 'cpi_9606.ENSP00000365663', 'f_653'], ['f_641', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000225927', 'cpi_9606.ENSP00000311028', 'cpi_9606.ENSP00000225474'], ['f_685', 'cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000263980', 'f_448', 'f_471'], ['f_573', 'cpi_9606.ENSP00000364035', 'cpi_9606.ENSP00000260010', 'f_813', 'f_195'], ['f_199', 'cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000330393', 'f_398', 'f_475'], ['f_150', 'cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000367102', 'cpi_9606.ENSP00000314508', 'cpi_9606.ENSP00000261799'], ['f_464', 'cpi_9606.ENSP00000264426', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000389414', 'f_347'], ['f_536', 'f_770', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000366307', 'cpi_9606.ENSP00000226574'], ['f_368', 'f_522', 'cpi_9606.ENSP00000349467', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000260356'], ['f_294', 'cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000368880', 'f_650'], ['cpi_9606.ENSP00000360372', 'f_200', 'f_494', 'cpi_9606.ENSP00000261693', 'cpi_9606.ENSP00000308774'], ['f_642', 'cpi_9606.ENSP00000396308', 'f_568', 'cpi_9606.ENSP00000276449', 'f_822'], ['f_580', 'cpi_9606.ENSP00000270142', 'f_429', 'cpi_9606.ENSP00000294728', 'f_230'], ['f_333', 'cpi_9606.ENSP00000430031', 'cpi_9606.ENSP00000365380', 'f_833', 'f_477'], ['cpi_9606.ENSP00000264381', 'f_458', 'cpi_9606.ENSP00000376943', 'cpi_9606.ENSP00000259396', 'f_157'], ['cpi_9606.ENSP00000356438', 'f_213', 'f_260', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000259089'], ['f_193', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000275300', 'cpi_9606.ENSP00000261937'], ['f_462', 'f_647', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000353915'], ['f_708', 'cpi_9606.ENSP00000364782', 'cpi_9606.ENSP00000222390', 'f_609', 'f_763'], ['cpi_9606.ENSP00000222982', 'f_543', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000369530', 'f_160'], ['f_776', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000332369', 'cpi_9606.ENSP00000463999', 'f_652'], ['f_666', 'cpi_9606.ENSP00000305742', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000356954', 'f_30'], ['f_593', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000419692', 'cpi_9606.ENSP00000322617', 'f_759'], ['f_241', 'cpi_9606.ENSP00000273550', 'cpi_9606.ENSP00000346298', 'cpi_9606.ENSP00000308165', 'f_588'], ['f_690', 'cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000264818', 'cpi_9606.ENSP00000471569', 'f_465'], ['f_437', 'cpi_9606.ENSP00000279593', 'cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000242057', 'f_860'], ['f_597', 'cpi_9606.ENSP00000276414', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000355657', 'f_517'], ['f_693', 'cpi_9606.ENSP00000354612', 'cpi_9606.ENSP00000409378', 'f_422', 'f_314'], ['f_145', 'cpi_9606.ENSP00000001008', 'cpi_9606.ENSP00000411658', 'f_575', 'cpi_9606.ENSP00000360967'], ['f_594', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000262441', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000260191'], ['f_592', 'cpi_9606.ENSP00000248935', 'cpi_9606.ENSP00000307014', 'cpi_9606.ENSP00000293288', 'f_461'], ['f_493', 'cpi_9606.ENSP00000319814', 'cpi_9606.ENSP00000359635', 'cpi_9606.ENSP00000357283', 'f_17'], ['f_337', 'cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000274547', 'cpi_9606.ENSP00000278616'], ['f_699', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000362924', 'f_499', 'cpi_9606.ENSP00000200676'], ['f_430', 'cpi_9606.ENSP00000314649', 'cpi_9606.ENSP00000240652', 'cpi_9606.ENSP00000267163', 'f_826'], ['f_581', 'cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000302811', 'cpi_9606.ENSP00000304895', 'f_500'], ['f_662', 'cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000288602', 'f_738', 'cpi_9606.ENSP00000226413'], ['f_701', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000282397', 'cpi_9606.ENSP00000348069', 'f_514'], ['cpi_9606.ENSP00000336528', 'f_34', 'cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000467676', 'cpi_9606.ENSP00000361666'], ['f_507', 'cpi_9606.ENSP00000220809', 'cpi_9606.ENSP00000353878', 'f_515', 'cpi_9606.ENSP00000242375'], ['f_342', 'cpi_9606.ENSP00000301633', 'cpi_9606.ENSP00000331358', 'cpi_9606.ENSP00000255465', 'f_152'], ['cpi_9606.ENSP00000270349', 'f_687', 'f_601', 'cpi_9606.ENSP00000262160', 'cpi_9606.ENSP00000322421'], ['f_821', 'f_425', 'cpi_9606.ENSP00000353427', 'cpi_9606.ENSP00000370473', 'f_513'], ['f_683', 'cpi_9606.ENSP00000306606', 'cpi_9606.ENSP00000328173', 'f_625', 'f_411'], ['f_777', 'cpi_9606.ENSP00000218548', 'cpi_9606.ENSP00000302111', 'f_364', 'f_717'], ['f_586', 'cpi_9606.ENSP00000269571', 'cpi_9606.ENSP00000382250', 'f_801', 'cpi_9606.ENSP00000303522'], ['f_628', 'cpi_9606.ENSP00000216714', 'cpi_9606.ENSP00000300900', 'f_144', 'cpi_9606.ENSP00000378492'], ['f_11', 'cpi_9606.ENSP00000471397', 'cpi_9606.ENSP00000264657', 'f_423', 'f_456'], ['f_818', 'cpi_9606.ENSP00000261405', 'cpi_9606.ENSP00000348897', 'f_489', 'cpi_9606.ENSP00000372023'], ['f_574', 'cpi_9606.ENSP00000274353', 'cpi_9606.ENSP00000263126', 'cpi_9606.ENSP00000262948', 'f_559'], ['cpi_9606.ENSP00000324648', 'f_459', 'cpi_9606.ENSP00000321106', 'cpi_9606.ENSP00000241600', 'f_206'], ['f_655', 'cpi_9606.ENSP00000399168', 'cpi_9606.ENSP00000346598', 'cpi_9606.ENSP00000267843', 'f_363'], ['f_1', 'cpi_9606.ENSP00000363018', 'cpi_9606.ENSP00000358223', 'f_721', 'cpi_9606.ENSP00000359663'], ['f_13', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000385806', 'cpi_9606.ENSP00000301634', 'f_421'], ['f_498', 'cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000233146', 'f_359', 'f_780'], ['f_798', 'cpi_9606.ENSP00000356729', 'cpi_9606.ENSP00000309968', 'f_480', 'f_527'], ['f_711', 'f_301', 'cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000317379', 'f_399'], ['f_755', 'cpi_9606.ENSP00000368727', 'cpi_9606.ENSP00000410076', 'f_395', 'cpi_9606.ENSP00000312029'], ['f_412', 'cpi_9606.ENSP00000354511', 'f_707', 'cpi_9606.ENSP00000318822', 'cpi_9606.ENSP00000261196'], ['f_604', 'cpi_9606.ENSP00000312673', 'cpi_9606.ENSP00000280357', 'f_694', 'f_305'], ['f_633', 'cpi_9606.ENSP00000234310', 'cpi_9606.ENSP00000347979', 'cpi_9606.ENSP00000324248', 'cpi_9606.ENSP00000325120'], ['f_549', 'cpi_9606.ENSP00000268695', 'cpi_9606.ENSP00000231449', 'cpi_9606.ENSP00000394932', 'f_227'], ['f_188', 'cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000221515', 'cpi_9606.ENSP00000294954', 'f_716'], ['f_623', 'cpi_9606.ENSP00000330199', 'cpi_9606.ENSP00000265643', 'cpi_9606.ENSP00000232219', 'cpi_9606.ENSP00000362036'], ['f_442', 'cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000370381', 'f_803', 'cpi_9606.ENSP00000291294'], ['f_349', 'cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000296522', 'cpi_9606.ENSP00000248553', 'f_605'], ['f_334', 'cpi_9606.ENSP00000352516', 'f_532', 'cpi_9606.ENSP00000295834', 'f_397'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000218388', 'f_805', 'cpi_9606.ENSP00000326219', 'cpi_9606.ENSP00000448059'], ['f_259', 'cpi_9606.ENSP00000318585', 'cpi_9606.ENSP00000387699', 'f_367', 'cpi_9606.ENSP00000364802'], ['f_688', 'cpi_9606.ENSP00000349576', 'cpi_9606.ENSP00000309493', 'f_742', 'cpi_9606.ENSP00000338548'], ['f_709', 'cpi_9606.ENSP00000216962', 'cpi_9606.ENSP00000298283', 'cpi_9606.ENSP00000351273', 'f_378'], ['f_702', 'cpi_9606.ENSP00000276431', 'cpi_9606.ENSP00000359100', 'cpi_9606.ENSP00000380247', 'f_457'], ['f_797', 'cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000318912', 'cpi_9606.ENSP00000264896', 'f_621'], ['f_352', 'cpi_9606.ENSP00000383365', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000366506', 'cpi_9606.ENSP00000263923'], ['f_555', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000344460', 'f_610', 'cpi_9606.ENSP00000255380'], ['f_332', 'cpi_9606.ENSP00000226299', 'cpi_9606.ENSP00000310405', 'f_784', 'f_713'], ['f_548', 'cpi_9606.ENSP00000219700', 'cpi_9606.ENSP00000382659', 'cpi_9606.ENSP00000400175', 'f_187'], ['f_418', 'cpi_9606.ENSP00000320401', 'cpi_9606.ENSP00000295256', 'cpi_9606.ENSP00000267119', 'cpi_9606.ENSP00000428340'], ['cpi_9606.ENSP00000258743', 'cpi_9606.ENSP00000354610', 'cpi_9606.ENSP00000176763', 'f_734', 'f_383'], ['f_654', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000278175', 'f_705'], ['f_591', 'cpi_9606.ENSP00000219070', 'f_400', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000252029'], ['f_351', 'cpi_9606.ENSP00000362441', 'cpi_9606.ENSP00000351908', 'cpi_9606.ENSP00000255030', 'f_661'], ['f_710', 'cpi_9606.ENSP00000216392', 'cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000380252', 'cpi_9606.ENSP00000265403'], ['f_714', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000297268', 'cpi_9606.ENSP00000369757', 'f_414'], ['f_550', 'cpi_9606.ENSP00000307786', 'f_612', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000303325'], ['f_758', 'cpi_9606.ENSP00000236850', 'cpi_9606.ENSP00000351885', 'f_658', 'cpi_9606.ENSP00000239938'], ['f_607', 'cpi_9606.ENSP00000369442', 'cpi_9606.ENSP00000363296', 'f_563', 'cpi_9606.ENSP00000362508'], ['f_679', 'cpi_9606.ENSP00000330032', 'cpi_9606.ENSP00000355920', 'f_630', 'f_300'], ['f_542', 'cpi_9606.ENSP00000314949', 'cpi_9606.ENSP00000270776', 'cpi_9606.ENSP00000292513', 'f_38'], ['f_251', 'cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000418960', 'cpi_9606.ENSP00000346148', 'f_153'], ['f_244', 'cpi_9606.ENSP00000260302', 'cpi_9606.ENSP00000354558', 'cpi_9606.ENSP00000359793', 'cpi_9606.ENSP00000387683'], ['f_819', 'cpi_9606.ENSP00000262623', 'cpi_9606.ENSP00000277120', 'cpi_9606.ENSP00000384273', 'f_531'], ['f_695', 'cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000256010', 'cpi_9606.ENSP00000333534', 'cpi_9606.ENSP00000348461'], ['f_546', 'cpi_9606.ENSP00000353

🔄 Processing features: 100%|██████████| 2147/2147 [10:17<00:00,  3.48feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'f_413', 'f_202', 'f_262', 'f_845'], ['f_374', 'cpi_9606.ENSP00000226578', 'f_768', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000293288'], ['f_308', 'cpi_9606.ENSP00000355192', 'f_616', 'cpi_9606.ENSP00000338627', 'f_831'], ['f_20', 'cpi_9606.ENSP00000352702', 'f_792', 'cpi_9606.ENSP00000262888', 'f_629'], ['f_346', 'cpi_9606.ENSP00000279178', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000395653', 'cpi_9606.ENSP00000394936'], ['f_366', 'cpi_9606.ENSP00000402608', 'cpi_9606.ENSP00000286479', 'f_428', 'f_726'], ['f_299', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000306606', 'f_151', 'cpi_9606.ENSP00000360493'], ['f_617', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000264318'], ['f_3', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000291700', 'f_529'], ['f_393', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000355629', 'cpi_9606.ENSP00000370373'], ['f_614', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000356094', 'cpi_9606.ENSP00000371985', 'f_789'], ['f_287', 'cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000349320', 'f_118', 'f_194'], ['f_452', 'f_25', 'cpi_9606.ENSP00000360773', 'cpi_9606.ENSP00000263088', 'cpi_9606.ENSP00000346598'], ['f_440', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000378517', 'cpi_9606.ENSP00000342235'], ['f_672', 'cpi_9606.ENSP00000409007', 'f_292', 'cpi_9606.ENSP00000264162', 'cpi_9606.ENSP00000352011'], ['f_380', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000365663', 'cpi_9606.ENSP00000257290'], ['f_392', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000354476'], ['f_566', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000332296', 'f_773', 'cpi_9606.ENSP00000376178'], ['f_405', 'cpi_9606.ENSP00000305742', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000364802', 'f_635'], ['f_339', 'f_670', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000394033', 'f_834'], ['f_391', 'cpi_9606.ENSP00000313490', 'f_725', 'f_866', 'cpi_9606.ENSP00000304822'], ['f_186', 'cpi_9606.ENSP00000261205', 'f_31', 'f_511', 'cpi_9606.ENSP00000216037'], ['f_23', 'f_408', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000363512', 'f_164'], ['f_571', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000256383', 'f_836', 'cpi_9606.ENSP00000301891'], ['f_659', 'cpi_9606.ENSP00000312286', 'f_526', 'cpi_9606.ENSP00000329357', 'f_427'], ['f_406', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000337773', 'cpi_9606.ENSP00000374323'], ['f_643', 'cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000277010', 'cpi_9606.ENSP00000316786'], ['f_2', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000282841', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000312455'], ['f_451', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000348786', 'cpi_9606.ENSP00000377947', 'f_328'], ['f_146', 'cpi_9606.ENSP00000397582', 'cpi_9606.ENSP00000430684', 'cpi_9606.ENSP00000222330', 'f_587'], ['f_192', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000321584', 'f_47', 'cpi_9606.ENSP00000359353'], ['f_12', 'cpi_9606.ENSP00000354850', 'cpi_9606.ENSP00000414334', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000343477'], ['f_420', 'cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000304408', 'f_330', 'f_830'], ['f_335', 'f_815', 'cpi_9606.ENSP00000274353', 'cpi_9606.ENSP00000254976', 'f_510'], ['f_528', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000362508', 'cpi_9606.ENSP00000367848', 'cpi_9606.ENSP00000320935'], ['f_15', 'cpi_9606.ENSP00000357204', 'cpi_9606.ENSP00000229264', 'f_214', 'cpi_9606.ENSP00000451040'], ['f_639', 'f_417', 'f_676', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000355920'], ['f_341', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000273398', 'cpi_9606.ENSP00000286301', 'cpi_9606.ENSP00000353878'], ['f_143', 'cpi_9606.ENSP00000225927', 'cpi_9606.ENSP00000262948', 'cpi_9606.ENSP00000470087', 'f_27'], ['f_338', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000368305', 'cpi_9606.ENSP00000261799', 'f_788'], ['f_285', 'cpi_9606.ENSP00000233944', 'cpi_9606.ENSP00000447149', 'f_436', 'cpi_9606.ENSP00000300061'], ['f_390', 'cpi_9606.ENSP00000234389', 'cpi_9606.ENSP00000264637', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000262367'], ['f_656', 'cpi_9606.ENSP00000382250', 'cpi_9606.ENSP00000220616', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000258749'], ['f_181', 'cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000368253', 'f_166', 'cpi_9606.ENSP00000252809'], ['f_185', 'cpi_9606.ENSP00000405573', 'cpi_9606.ENSP00000389338', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000263339'], ['cpi_9606.ENSP00000311032', 'f_43', 'f_167', 'cpi_9606.ENSP00000344674', 'f_131'], ['f_33', 'f_706', 'cpi_9606.ENSP00000353720', 'f_350', 'cpi_9606.ENSP00000435591'], ['f_696', 'cpi_9606.ENSP00000305692', 'cpi_9606.ENSP00000355657', 'f_474', 'f_298'], ['f_19', 'cpi_9606.ENSP00000333496', 'cpi_9606.ENSP00000374265', 'cpi_9606.ENSP00000381097', 'cpi_9606.ENSP00000457706'], ['f_535', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000297268', 'f_297', 'cpi_9606.ENSP00000428924'], ['f_37', 'f_230', 'cpi_9606.ENSP00000263321', 'f_509', 'cpi_9606.ENSP00000282753'], ['f_613', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000309124', 'cpi_9606.ENSP00000369375'], ['f_569', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000360967', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000266376'], ['f_257', 'cpi_9606.ENSP00000279387', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000337335', 'cpi_9606.ENSP00000359285'], ['f_638', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000297350', 'cpi_9606.ENSP00000308774'], ['f_516', 'cpi_9606.ENSP00000364035', 'cpi_9606.ENSP00000260227', 'f_46', 'f_771'], ['cpi_9606.ENSP00000353820', 'f_22', 'f_812', 'cpi_9606.ENSP00000286648', 'f_736'], ['f_697', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000246553', 'f_767', 'f_35'], ['f_712', 'f_533', 'cpi_9606.ENSP00000295454', 'cpi_9606.ENSP00000296122', 'cpi_9606.ENSP00000326219'], ['f_540', 'cpi_9606.ENSP00000359680', 'cpi_9606.ENSP00000221972', 'cpi_9606.ENSP00000319788', 'cpi_9606.ENSP00000276449'], ['f_686', 'f_215', 'f_419', 'cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000356436'], ['f_180', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000355778'], ['f_684', 'cpi_9606.ENSP00000314214', 'cpi_9606.ENSP00000354107', 'f_327', 'f_473'], ['f_21', 'cpi_9606.ENSP00000316244', 'cpi_9606.ENSP00000252519', 'f_728', 'cpi_9606.ENSP00000387946'], ['f_345', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000383365', 'cpi_9606.ENSP00000343040', 'f_583'], ['f_646', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000345096', 'cpi_9606.ENSP00000000442', 'f_749'], ['f_340', 'cpi_9606.ENSP00000319814', 'cpi_9606.ENSP00000349252', 'cpi_9606.ENSP00000296370', 'f_460'], ['f_698', 'cpi_9606.ENSP00000364709', 'f_388', 'cpi_9606.ENSP00000297316', 'f_729'], ['f_443', 'cpi_9606.ENSP00000223366', 'cpi_9606.ENSP00000327850', 'f_675', 'f_497'], ['cpi_9606.ENSP00000342007', 'f_26', 'cpi_9606.ENSP00000299178', 'f_554', 'cpi_9606.ENSP00000227758'], ['f_611', 'cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000333212', 'cpi_9606.ENSP00000261693', 'cpi_9606.ENSP00000326119'], ['f_439', 'cpi_9606.ENSP00000254488', 'cpi_9606.ENSP00000341885', 'cpi_9606.ENSP00000311095', 'f_622'], ['f_615', 'f_839', 'cpi_9606.ENSP00000332549', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000226574'], ['f_681', 'cpi_9606.ENSP00000418532', 'f_715', 'cpi_9606.ENSP00000417229', 'cpi_9606.ENSP00000253004'], ['f_579', 'cpi_9606.ENSP00000354193', 'cpi_9606.ENSP00000254810', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000347942'], ['cpi_9606.ENSP00000265724', 'f_455', 'f_785', 'f_207', 'f_361'], ['f_683', 'cpi_9606.ENSP00000314649', 'cpi_9606.ENSP00000240652', 'cpi_9606.ENSP00000427514', 'cpi_9606.ENSP00000312664'], ['f_16', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000353791', 'cpi_9606.ENSP00000305422', 'f_242'], ['f_248', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000292513', 'f_401', 'f_496'], ['f_553', 'cpi_9606.ENSP00000362353', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000367851', 'cpi_9606.ENSP00000285381'], ['cpi_9606.ENSP00000356438', 'f_213', 'f_343', 'f_429', 'f_799'], ['cpi_9606.ENSP00000264381', 'f_693', 'f_517', 'f_820', 'f_722'], ['f_293', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000301633', 'cpi_9606.ENSP00000344192', 'cpi_9606.ENSP00000358730'], ['f_682', 'f_778', 'cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000296871'], ['f_671', 'cpi_9606.ENSP00000356825', 'cpi_9606.ENSP00000371554', 'f_764', 'cpi_9606.ENSP00000275525'], ['f_704', 'cpi_9606.ENSP00000441691', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000344352', 'f_466'], ['f_692', 'cpi_9606.ENSP00000447378', 'cpi_9606.ENSP00000471569', 'cpi_9606.ENSP00000353292', 'f_475'], ['cpi_9606.ENSP00000360372', 'f_132', 'f_195', 'f_826', 'cpi_9606.ENSP00000267119'], ['f_145', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000256958', 'cpi_9606.ENSP00000391826', 'f_631'], ['f_695', 'f_861', 'cpi_9606.ENSP00000023897', 'f_719', 'cpi_9606.ENSP00000301178'], ['f_536', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000358107', 'cpi_9606.ENSP00000302846', 'f_116'], ['f_667', 'cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000242375', 'f_791', 'cpi_9606.ENSP00000231228'], ['f_689', 'cpi_9606.ENSP00000371236', 'f_650', 'f_508', 'cpi_9606.ENSP00000261937'], ['f_680', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000306100', 'cpi_9606.ENSP00000356150', 'f_757'], ['f_662', 'f_394', 'cpi_9606.ENSP00000237014', 'cpi_9606.ENSP00000348069', 'cpi_9606.ENSP00000242057'], ['f_464', 'cpi_9606.ENSP00000362513', 'cpi_9606.ENSP00000196551', 'cpi_9606.ENSP00000309493', 'cpi_9606.ENSP00000353427'], ['f_337', 'cpi_9606.ENSP00000303211', 'f_609', 'f_260', 'cpi_9606.ENSP00000366307'], ['f_241', 'cpi_9606.ENSP00000273550', 'cpi_9606.ENSP00000331912', 'cpi_9606.ENSP00000308165', 'cpi_9606.ENSP00000307599'], ['f_567', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000264818', 'f_518'], ['f_365', 'cpi_9606.ENSP00000471397', 'cpi_9606.ENSP00000294728', 'cpi_9606.ENSP00000376943', 'f_448'], ['f_573', 'cpi_9606.ENSP00000311028', 'cpi_9606.ENSP00000366927', 'cpi_9606.ENSP00000264867', 'cpi_9606.ENSP00000252723'], ['f_641', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000337354', 'cpi_9606.ENSP00000309572', 'f_407'], ['f_699', 'f_488', 'cpi_9606.ENSP00000397026', 'f_486', 'f_483'], ['f_691', 'cpi_9606.ENSP00000231454', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000317379'], ['f_353', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000283635', 'cpi_9606.ENSP00000343782', 'f_827'], ['f_581', 'f_568', 'cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000355317', 'f_494'], ['f_619', 'cpi_9606.ENSP00000364212', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000263980', 'cpi_9606.ENSP00000361359'], ['f_592', 'cpi_9606.ENSP00000276651', 'cpi_9606.ENSP00000428340', 'cpi_9606.ENSP00000358548', 'cpi_9606.ENSP00000262999'], ['f_645', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000275216', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000398632'], ['f_150', 'cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000287936', 'cpi_9606.ENSP00000359998', 'cpi_9606.ENSP00000365686'], ['f_594', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000318912', 'cpi_9606.ENSP00000225474', 'f_159'], ['f_602', 'cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000467676', 'f_477'], ['cpi_9606.ENSP00000222982', 'f_543', 'cpi_9606.ENSP00000356671', 'f_160', 'cpi_9606.ENSP00000376432'], ['f_690', 'cpi_9606.ENSP00000318820', 'f_750', 'cpi_9606.ENSP00000270570', 'f_398'], ['f_351', 'cpi_9606.ENSP00000287878', 'cpi_9606.ENSP00000370473', 'f_505', 'f_782'], ['f_604', 'cpi_9606.ENSP00000352516', 'cpi_9606.ENSP00000251535', 'f_647', 'f_860'], ['cpi_9606.ENSP00000260682', 'f_763', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000259089', 'f_200'], ['f_637', 'cpi_9606.ENSP00000332256', 'cpi_9606.ENSP00000356832', 'cpi_9606.ENSP00000359663', 'f_644'], ['f_199', 'cpi_9606.ENSP00000385834', 'f_489', 'cpi_9606.ENSP00000330393', 'f_522'], ['f_777', 'cpi_9606.ENSP00000225275', 'cpi_9606.ENSP00000295491', 'f_422', 'f_471'], ['cpi_9606.ENSP00000295897', 'f_115', 'f_514', 'cpi_9606.ENSP00000248553', 'cpi_9606.ENSP00000371929'], ['f_666', 'cpi_9606.ENSP00000357669', 'cpi_9606.ENSP00000445340', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000282561'], ['f_580', 'cpi_9606.ENSP00000270142', 'f_752', 'f_840', 'f_229'], ['f_368', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000393312', 'cpi_9606.ENSP00000454071', 'f_740'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000311165', 'f_742', 'f_129', 'f_687'], ['f_642', 'cpi_9606.ENSP00000285979', 'cpi_9606.ENSP00000216962', 'cpi_9606.ENSP00000323568', 'f_359'], ['f_548', 'cpi_9606.ENSP00000259486', 'cpi_9606.ENSP00000280357', 'cpi_9606.ENSP00000354394', 'f_813'], ['f_502', 'cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000340691', 'f_551', 'cpi_9606.ENSP00000367102'], ['f_342', 'f_227', 'cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000356954', 'cpi_9606.ENSP00000428864'], ['f_663', 'cpi_9606.ENSP00000363868', 'f_216', 'cpi_9606.ENSP00000362649', 'cpi_9606.ENSP00000361666'], ['cpi_9606.ENSP00000272190', 'f_364', 'f_157', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000301634'], ['f_11', 'cpi_9606.ENSP00000417901', 'cpi_9606.ENSP00000239938', 'f_409', 'f_513'], ['f_493', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000340943', 'cpi_9606.ENSP00000299267', 'f_34'], ['f_24', 'cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000303540', 'f_17'], ['f_18', 'cpi_9606.ENSP00000472933', 'cpi_9606.ENSP00000232219', 'f_770', 'f_759'], ['f_375', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000295256', 'cpi_9606.ENSP00000293745', 'f_559'], ['cpi_9606.ENSP00000367959', 'f_588', 'f_30', 'cpi_9606.ENSP00000267101', 'cpi_9606.ENSP00000003100'], ['f_437', 'cpi_9606.ENSP00000279593', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000312029', 'f_347'], ['f_574', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000365380', 'cpi_9606.ENSP00000389414', 'f_411'], ['cpi_9606.ENSP00000337450', 'f_461', 'cpi_9606.ENSP00000245457', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000260191'], ['f_193', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000332369', 'f_467', 'cpi_9606.ENSP00000295834'], ['f_685', 'cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000216540', 'f_822', 'f_653'], ['f_797', 'cpi_9606.ENSP00000284981', 'f_301', 'f_738', 'cpi_9606.ENSP00000259396'], ['f_449', 'cpi_9606.ENSP00000359100', 'cpi_9606.ENSP00000267017', 'cpi_9606.ENSP00000347979', 'f_314'], ['f_821', 'f_456', 'cpi_9606.ENSP00000364731', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000307014'], ['f_294', 'cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000331358', 'cpi_9606.ENSP00000222002', 'f_558'], ['f_655', 'cpi_9606.ENSP00000319531', 'cpi_9606.ENSP00000358595', 'f_833', 'cpi_9606.ENSP00000348897'], ['f_549', 'cpi_9606.ENSP00000264426', 'cpi_9606.ENSP00000252486', 'f_803', 'cpi_9606.ENSP00000291294'], ['f_430', 'cpi_9606.ENSP00000358727', 'cpi_9606.ENSP00000365016', 'f_454', 'f_425'], ['cpi_9606.ENSP00000270349', 'cpi_9606.ENSP00000011653', 'f_625', 'cpi_9606.ENSP00000241600', 'f_399'], ['f_593', 'cpi_9606.ENSP00000370129', 'cpi_9606.ENSP00000357283', 'cpi_9606.ENSP00000360973', 'cpi_9606.ENSP00000311469'], ['f_432', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000351209', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000255380'], ['f_776', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000338082', 'f_305', 'cpi_9606.ENSP00000225577'], ['f_537', 'f_423', 'cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000321988', 'cpi_9606.ENSP00000200676'], ['f_597', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000294954', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000274547'], ['f_657', 'cpi_9606.ENSP00000306397', 'f_367', 'cpi_9606.ENSP00000267163', 'f_780'], ['f_334', 'cpi_9606.ENSP00000396308', 'f_515', 'cpi_9606.ENSP00000274793', 'cpi_9606.ENSP00000263126'], ['cpi_9606.ENSP00000258743', 'f_395', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000318646', 'f_801'], ['f_585', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000236671', 'cpi_9606.ENSP00000429374', 'f_336'], ['f_628', 'cpi_9606.ENSP00000216714', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000368880', 'f_480'], ['f_818', 'cpi_9606.ENSP00000262623', 'cpi_9606.ENSP00000302111', 'f_621', 'cpi_9606.ENSP00000233242'], ['f_333', 'cpi_9606.ENSP00000293404', 'cpi_9606.ENSP00000384273', 'cpi_9606.ENSP00000308549', 'f_363'], ['f_550', 'cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000262160', 'f_527', 'f_144'], ['f_462', 'cpi_9606.ENSP00000243167', 'f_414', 'cpi_9606.ENSP00000278616', 'cpi_9606.ENSP00000226413'], ['f_702', 'cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000332116', 'f_717', 'cpi_9606.ENSP00000241261'], ['f_458', 'cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000321106', 'f_206', 'cpi_9606.ENSP00000362036'], ['f_188', 'cpi_9606.ENSP00000363822', 'cpi_9606.ENSP00000367309', 'cpi_9606.ENSP00000309968', 'f_152'], ['f_498', 'cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000255465', 'f_397', 'cpi_9606.ENSP00000410294'], ['f_332', 'cpi_9606.ENSP00000346103', 'cpi_9606.ENSP00000263464', 'cpi_9606.ENSP00000379086', 'f_721'], ['f_507', 'cpi_9606.ENSP00000220809', 'f_575', 'cpi_9606.ENSP00000359211', 'f_300'], ['f_798', 'cpi_9606.ENSP00000352835', 'f_421', 'cpi_9606.ENSP00000339527', 'cpi_9606.ENSP00000380247'], ['f_623', 'cpi_9606.ENSP00000216465', 'cpi_9606.ENSP00000304895', 'cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000402152'], ['f_633', 'cpi_9606.ENSP00000330484', 'cpi_9606.ENSP00000407375', 'cpi_9606.ENSP00000451030', 'f_610'], ['f_586', 'cpi_9606.ENSP00000358022', 'cpi_9606.ENSP00000261835', 'f_805', 'cpi_9606.ENSP00000267377'], ['f_819', 'cpi_9606.ENSP00000296522', 'cpi_9606.ENSP00000314508', 'f_389', 'cpi_9606.ENSP00000277120'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000219833', 'f_459', 'cpi_9606.ENSP00000320866', 'f_694'], ['f_487', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000314949', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000358223'], ['f_709', 'cpi_9606.ENSP00000354610', 'cpi_9606.ENSP00000430432', 'cpi_9606.ENSP00000267843', 'f_38'], ['f_755', 'cpi_9606.ENSP00000262017', 'cpi_9606.ENSP00000380252', 'f_601', 'cpi_9606.ENSP00000359793'], ['f_701', 'cpi_9606.ENSP00000260970', 'cpi_9606.ENSP00000312673', 'f_624', 'cpi_9606.ENSP00000306490'], ['cpi_9606.ENSP00000270202', 'cpi_9606.ENSP00000230671', 'f_652', 'cpi_9606.ENSP00000270625', 'f_500'], ['f_352', 'cpi_9606.ENSP00000226299', 'cpi_9606.ENSP00000328818', 'cpi_9606.ENSP00000351273', 'f_465'], ['f_286', 'cpi_9606.ENSP00000312326', 'cpi_9606.ENSP00000289753', 'cpi_9606.ENSP00000318822', 'f_784'], ['f_412', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000353915', 'cpi_9606.ENSP00000363827', 'f_630'], ['f_244', 'cpi_9606.ENSP00000260302', 'cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000261196', 'cpi_9606.ENSP00000307235'], ['f_708', 'cpi_9606.ENSP00000330032', 'cpi_9606.ENSP00000355930', 'f_457', 'cpi_9606.ENSP00000394932'], ['f_450', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000466399', 'f_705', 'cpi_9606.ENSP00000448059'], ['f_259', 'cpi_9606.ENSP00000320401', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000379339', 'cpi_9606.ENSP00000342560'], ['f_591', 'cpi_9606.ENSP00000219070', 'cpi_9606.ENSP00000361151', 'f_400', 'cpi_9606.ENSP00000435777'], ['f_453', 'cpi_9606.ENSP00000346298', 'cpi_9606.ENSP00000260010', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000303424'], ['f_377', 'cpi_9606.ENSP00000434516', 'cpi_9606.ENSP00000221515', 'cpi_9606.ENSP00000324248', 'f_661'], ['f_707', 'cpi_9606.ENSP00000301141', 'cpi_9606.ENSP00000303522', 'cpi_9606.ENSP00000433821', 'f_713'], ['f_370', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000378890', 'cpi_9606.ENSP00000310305', 'f_605'], ['f_541', 'cpi_9606.ENSP00000260102', 'cpi_9606.ENSP00000304915', 'cpi_9606.ENSP00000463999', 'f_737'], ['f_356', 'cpi_9606.ENSP00000

🔄 Processing features: 100%|██████████| 2147/2147 [10:18<00:00,  3.47feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'f_408', 'f_207', 'f_31', 'f_845'], ['f_308', 'cpi_9606.ENSP00000355192', 'f_616', 'cpi_9606.ENSP00000263377', 'cpi_9606.ENSP00000351957'], ['f_374', 'cpi_9606.ENSP00000039007', 'f_831', 'cpi_9606.ENSP00000395653', 'cpi_9606.ENSP00000409007'], ['f_20', 'cpi_9606.ENSP00000339260', 'f_792', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000262367'], ['f_346', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000279178', 'f_629', 'cpi_9606.ENSP00000324856'], ['f_451', 'cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000277010', 'f_151', 'cpi_9606.ENSP00000245539'], ['f_452', 'f_25', 'cpi_9606.ENSP00000263088', 'f_789', 'cpi_9606.ENSP00000342235'], ['f_406', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000374323', 'f_726'], ['f_614', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000371985', 'f_413', 'cpi_9606.ENSP00000356094'], ['f_287', 'cpi_9606.ENSP00000241052', 'f_194', 'cpi_9606.ENSP00000349320', 'f_292'], ['f_23', 'cpi_9606.ENSP00000350616', 'f_195', 'cpi_9606.ENSP00000359424', 'f_635'], ['f_143', 'cpi_9606.ENSP00000397582', 'cpi_9606.ENSP00000222330', 'cpi_9606.ENSP00000430684', 'f_328'], ['f_3', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000337335', 'f_834'], ['f_366', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000256383', 'cpi_9606.ENSP00000394936', 'f_428'], ['f_392', 'cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000263126', 'cpi_9606.ENSP00000354476'], ['f_299', 'cpi_9606.ENSP00000237014', 'cpi_9606.ENSP00000292427', 'f_866', 'cpi_9606.ENSP00000355629'], ['f_380', 'cpi_9606.ENSP00000355533', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000360773', 'cpi_9606.ENSP00000295452'], ['f_643', 'cpi_9606.ENSP00000345096', 'cpi_9606.ENSP00000377947', 'f_27', 'cpi_9606.ENSP00000451040'], ['f_405', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000309493', 'f_510'], ['f_15', 'cpi_9606.ENSP00000264162', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000428824', 'cpi_9606.ENSP00000304822'], ['f_566', 'cpi_9606.ENSP00000397026', 'f_773', 'cpi_9606.ENSP00000360493', 'f_427'], ['f_339', 'f_778', 'f_429', 'cpi_9606.ENSP00000348897', 'f_526'], ['cpi_9606.ENSP00000311032', 'f_116', 'f_164', 'f_675', 'f_587'], ['f_37', 'cpi_9606.ENSP00000263321', 'f_229', 'cpi_9606.ENSP00000299178', 'cpi_9606.ENSP00000414334'], ['f_146', 'cpi_9606.ENSP00000313490', 'f_529', 'cpi_9606.ENSP00000391826', 'f_350'], ['f_391', 'cpi_9606.ENSP00000359100', 'cpi_9606.ENSP00000370381', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000296370'], ['f_440', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000378517', 'f_791'], ['f_186', 'cpi_9606.ENSP00000279387', 'cpi_9606.ENSP00000359285', 'f_118', 'cpi_9606.ENSP00000354394'], ['f_659', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000332296', 'cpi_9606.ENSP00000389338'], ['f_571', 'cpi_9606.ENSP00000301891', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000352011', 'f_799'], ['f_672', 'cpi_9606.ENSP00000262352', 'f_43', 'cpi_9606.ENSP00000216465', 'f_836'], ['f_393', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000380318', 'cpi_9606.ENSP00000408860', 'f_214'], ['f_420', 'cpi_9606.ENSP00000312326', 'f_327', 'f_830', 'f_497'], ['f_696', 'cpi_9606.ENSP00000274353', 'f_511', 'cpi_9606.ENSP00000355657', 'f_47'], ['f_185', 'cpi_9606.ENSP00000261205', 'cpi_9606.ENSP00000356150', 'cpi_9606.ENSP00000353292', 'cpi_9606.ENSP00000216037'], ['f_33', 'f_706', 'cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000253004'], ['f_12', 'cpi_9606.ENSP00000261755', 'f_768', 'cpi_9606.ENSP00000231228', 'cpi_9606.ENSP00000312455'], ['f_192', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000321584', 'cpi_9606.ENSP00000367848', 'f_131'], ['f_528', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000362508', 'cpi_9606.ENSP00000359353', 'cpi_9606.ENSP00000291700'], ['cpi_9606.ENSP00000353820', 'f_26', 'f_749', 'cpi_9606.ENSP00000286648', 'f_554'], ['f_335', 'f_815', 'cpi_9606.ENSP00000358107', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000371929'], ['f_697', 'cpi_9606.ENSP00000357669', 'cpi_9606.ENSP00000323568', 'f_725', 'f_771'], ['f_535', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000262888', 'f_297', 'cpi_9606.ENSP00000365016'], ['cpi_9606.ENSP00000342007', 'f_347', 'f_460', 'f_167', 'f_509'], ['f_338', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000257290', 'cpi_9606.ENSP00000245457'], ['f_345', 'cpi_9606.ENSP00000323867', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000334198', 'f_436'], ['f_19', 'cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000391676', 'cpi_9606.ENSP00000367851', 'cpi_9606.ENSP00000417229'], ['f_638', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000385806', 'f_820', 'cpi_9606.ENSP00000295454'], ['f_646', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000323549'], ['f_712', 'f_767', 'f_35', 'cpi_9606.ENSP00000218548', 'cpi_9606.ENSP00000283635'], ['f_2', 'cpi_9606.ENSP00000222481', 'cpi_9606.ENSP00000270631', 'cpi_9606.ENSP00000319788', 'f_788'], ['f_390', 'cpi_9606.ENSP00000287878', 'cpi_9606.ENSP00000264637', 'cpi_9606.ENSP00000300061', 'cpi_9606.ENSP00000369375'], ['f_340', 'cpi_9606.ENSP00000368305', 'cpi_9606.ENSP00000000442', 'f_670', 'cpi_9606.ENSP00000225474'], ['f_617', 'cpi_9606.ENSP00000394033', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000178638', 'f_728'], ['f_341', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000273398', 'f_715', 'cpi_9606.ENSP00000221972'], ['f_656', 'cpi_9606.ENSP00000216714', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000356436', 'f_202'], ['f_285', 'cpi_9606.ENSP00000244051', 'cpi_9606.ENSP00000387946', 'cpi_9606.ENSP00000312664', 'f_583'], ['f_682', 'f_839', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000252486', 'cpi_9606.ENSP00000301974'], ['f_639', 'f_417', 'cpi_9606.ENSP00000292896', 'f_736', 'f_508'], ['f_569', 'cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000262999', 'f_46', 'cpi_9606.ENSP00000309124'], ['f_611', 'cpi_9606.ENSP00000273550', 'cpi_9606.ENSP00000305422', 'f_861', 'cpi_9606.ENSP00000254488'], ['f_365', 'cpi_9606.ENSP00000471397', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000266376', 'f_722'], ['f_540', 'cpi_9606.ENSP00000226578', 'cpi_9606.ENSP00000329357', 'cpi_9606.ENSP00000470087', 'f_785'], ['f_684', 'cpi_9606.ENSP00000353791', 'cpi_9606.ENSP00000350348', 'f_330', 'f_474'], ['f_181', 'cpi_9606.ENSP00000370129', 'cpi_9606.ENSP00000314214', 'f_166', 'f_298'], ['cpi_9606.ENSP00000265724', 'f_455', 'f_505', 'f_407', 'f_757'], ['f_645', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000266682', 'cpi_9606.ENSP00000366662', 'f_631'], ['f_615', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000256958', 'f_419'], ['f_443', 'cpi_9606.ENSP00000383365', 'cpi_9606.ENSP00000381097', 'cpi_9606.ENSP00000275525', 'cpi_9606.ENSP00000282561'], ['f_686', 'cpi_9606.ENSP00000258400', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000311095'], ['f_439', 'cpi_9606.ENSP00000354511', 'f_622', 'cpi_9606.ENSP00000231454', 'f_262'], ['f_553', 'cpi_9606.ENSP00000263269', 'cpi_9606.ENSP00000343477', 'cpi_9606.ENSP00000343040', 'cpi_9606.ENSP00000389414'], ['f_689', 'cpi_9606.ENSP00000319531', 'f_388', 'cpi_9606.ENSP00000285381', 'f_729'], ['f_180', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000295491', 'cpi_9606.ENSP00000252809', 'cpi_9606.ENSP00000359793'], ['f_698', 'cpi_9606.ENSP00000364709', 'cpi_9606.ENSP00000297316', 'f_466', 'f_448'], ['f_683', 'cpi_9606.ENSP00000306606', 'cpi_9606.ENSP00000328173', 'f_764', 'cpi_9606.ENSP00000326119'], ['f_21', 'cpi_9606.ENSP00000276198', 'f_752', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000358548'], ['f_613', 'cpi_9606.ENSP00000362924', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000457706'], ['f_579', 'cpi_9606.ENSP00000354107', 'cpi_9606.ENSP00000164139', 'cpi_9606.ENSP00000308845', 'f_496'], ['f_671', 'cpi_9606.ENSP00000356729', 'cpi_9606.ENSP00000262441', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000427514'], ['f_257', 'cpi_9606.ENSP00000332549', 'cpi_9606.ENSP00000258749', 'f_361', 'cpi_9606.ENSP00000376943'], ['f_602', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000270625', 'f_343'], ['f_516', 'cpi_9606.ENSP00000354610', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000388825', 'cpi_9606.ENSP00000252723'], ['f_294', 'cpi_9606.ENSP00000363868', 'f_159', 'cpi_9606.ENSP00000255409', 'f_401'], ['f_666', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000344352', 'cpi_9606.ENSP00000286301'], ['f_681', 'f_215', 'cpi_9606.ENSP00000291295', 'f_676', 'cpi_9606.ENSP00000305221'], ['cpi_9606.ENSP00000360372', 'f_132', 'f_22', 'f_812', 'cpi_9606.ENSP00000267119'], ['f_432', 'cpi_9606.ENSP00000317842', 'f_422', 'cpi_9606.ENSP00000376432', 'f_813'], ['f_248', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000282753', 'cpi_9606.ENSP00000296122', 'f_518'], ['f_641', 'cpi_9606.ENSP00000297792', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000242057', 'f_477'], ['f_680', 'cpi_9606.ENSP00000258662', 'cpi_9606.ENSP00000370473', 'f_750', 'cpi_9606.ENSP00000296871'], ['f_704', 'cpi_9606.ENSP00000360967', 'cpi_9606.ENSP00000302811', 'f_473', 'cpi_9606.ENSP00000232219'], ['f_241', 'cpi_9606.ENSP00000333994', 'f_129', 'f_719', 'cpi_9606.ENSP00000361359'], ['f_692', 'cpi_9606.ENSP00000305302', 'cpi_9606.ENSP00000216962', 'cpi_9606.ENSP00000361206', 'f_475'], ['f_667', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000333212', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000301178'], ['f_464', 'cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000312029', 'cpi_9606.ENSP00000251535', 'f_827'], ['f_699', 'f_488', 'cpi_9606.ENSP00000306397', 'f_486', 'f_483'], ['f_663', 'cpi_9606.ENSP00000348069', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000370254', 'f_409'], ['f_536', 'cpi_9606.ENSP00000352835', 'cpi_9606.ENSP00000339527', 'cpi_9606.ENSP00000261693', 'f_763'], ['f_145', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000348786', 'cpi_9606.ENSP00000357283', 'f_242'], ['f_594', 'cpi_9606.ENSP00000254976', 'cpi_9606.ENSP00000343204', 'cpi_9606.ENSP00000356958', 'f_494'], ['f_342', 'f_650', 'cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000428864'], ['f_16', 'cpi_9606.ENSP00000367309', 'cpi_9606.ENSP00000254066', 'f_782', 'cpi_9606.ENSP00000335511'], ['f_637', 'cpi_9606.ENSP00000332256', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000340691', 'f_609'], ['f_293', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000298171', 'f_551', 'cpi_9606.ENSP00000428340'], ['cpi_9606.ENSP00000264381', 'f_459', 'f_770', 'f_568', 'f_801'], ['f_333', 'cpi_9606.ENSP00000354850', 'cpi_9606.ENSP00000346017', 'cpi_9606.ENSP00000356954', 'cpi_9606.ENSP00000261937'], ['f_592', 'cpi_9606.ENSP00000011292', 'cpi_9606.ENSP00000303248', 'cpi_9606.ENSP00000261799', 'f_653'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000260191', 'f_17', 'cpi_9606.ENSP00000299267'], ['f_573', 'cpi_9606.ENSP00000399168', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000316786', 'cpi_9606.ENSP00000283254'], ['f_593', 'cpi_9606.ENSP00000270142', 'cpi_9606.ENSP00000294728', 'f_822', 'f_230'], ['f_560', 'f_840', 'cpi_9606.ENSP00000262407', 'cpi_9606.ENSP00000445340', 'f_394'], ['f_597', 'cpi_9606.ENSP00000276414', 'cpi_9606.ENSP00000314508', 'cpi_9606.ENSP00000226574', 'cpi_9606.ENSP00000307599'], ['cpi_9606.ENSP00000222982', 'f_543', 'cpi_9606.ENSP00000296522', 'f_160', 'cpi_9606.ENSP00000317379'], ['f_24', 'f_216', 'cpi_9606.ENSP00000338018', 'f_740', 'cpi_9606.ENSP00000218099'], ['f_619', 'cpi_9606.ENSP00000330032', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000359663', 'f_833'], ['f_628', 'cpi_9606.ENSP00000264426', 'cpi_9606.ENSP00000276449', 'cpi_9606.ENSP00000267101', 'f_558'], ['f_693', 'cpi_9606.ENSP00000342070', 'f_517', 'f_533', 'cpi_9606.ENSP00000308032'], ['f_567', 'cpi_9606.ENSP00000332369', 'cpi_9606.ENSP00000365663', 'cpi_9606.ENSP00000261835', 'f_644'], ['f_690', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000219919', 'f_398'], ['f_708', 'cpi_9606.ENSP00000305692', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000367102'], ['cpi_9606.ENSP00000295897', 'f_115', 'f_514', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000259089'], ['f_580', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000331746', 'cpi_9606.ENSP00000352584', 'f_721'], ['f_691', 'cpi_9606.ENSP00000268053', 'cpi_9606.ENSP00000220616', 'cpi_9606.ENSP00000304915', 'f_467'], ['f_776', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000365380', 'f_647'], ['f_818', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000398632', 'cpi_9606.ENSP00000347942', 'f_34'], ['f_368', 'f_522', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000311028', 'cpi_9606.ENSP00000386229'], ['f_353', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000285900', 'f_826', 'cpi_9606.ENSP00000274547'], ['f_685', 'cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000263980', 'cpi_9606.ENSP00000447173', 'f_465'], ['f_199', 'cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000330393', 'f_421', 'cpi_9606.ENSP00000336630'], ['f_581', 'cpi_9606.ENSP00000313661', 'cpi_9606.ENSP00000357204', 'cpi_9606.ENSP00000361666', 'f_759'], ['f_702', 'cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000234071', 'f_780', 'f_489'], ['f_537', 'cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000321988', 'f_359', 'cpi_9606.ENSP00000331358'], ['f_623', 'f_314', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000293288'], ['cpi_9606.ENSP00000270349', 'f_687', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000308165', 'cpi_9606.ENSP00000463999'], ['f_662', 'cpi_9606.ENSP00000229319', 'cpi_9606.ENSP00000274793', 'f_588', 'f_500'], ['f_18', 'cpi_9606.ENSP00000472933', 'cpi_9606.ENSP00000308774', 'f_471', 'f_625'], ['f_797', 'cpi_9606.ENSP00000284981', 'f_461', 'f_513', 'cpi_9606.ENSP00000259396'], ['cpi_9606.ENSP00000356438', 'f_213', 'f_260', 'cpi_9606.ENSP00000320025', 'f_336'], ['f_244', 'cpi_9606.ENSP00000396308', 'f_860', 'f_738', 'cpi_9606.ENSP00000200676'], ['cpi_9606.ENSP00000367959', 'f_30', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000331912'], ['f_549', 'cpi_9606.ENSP00000234310', 'cpi_9606.ENSP00000255465', 'f_367', 'cpi_9606.ENSP00000291294'], ['f_144', 'cpi_9606.ENSP00000354859', 'cpi_9606.ENSP00000366084', 'cpi_9606.ENSP00000362036', 'cpi_9606.ENSP00000344192'], ['f_193', 'cpi_9606.ENSP00000265023', 'cpi_9606.ENSP00000275300', 'cpi_9606.ENSP00000365775', 'f_454'], ['f_701', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000226413', 'f_480'], ['f_591', 'cpi_9606.ENSP00000219070', 'f_157', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000260010'], ['f_351', 'cpi_9606.ENSP00000343690', 'cpi_9606.ENSP00000239938', 'f_559', 'f_742'], ['f_612', 'f_590', 'cpi_9606.ENSP00000318585', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000412673'], ['f_334', 'cpi_9606.ENSP00000358963', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000264896', 'f_694'], ['cpi_9606.ENSP00000258743', 'f_652', 'cpi_9606.ENSP00000264818', 'cpi_9606.ENSP00000471569', 'f_200'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000265572', 'f_411', 'cpi_9606.ENSP00000263464', 'f_805'], ['f_633', 'cpi_9606.ENSP00000234389', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000354558', 'f_227'], ['f_462', 'cpi_9606.ENSP00000418532', 'f_423', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000302967'], ['f_349', 'cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000367123', 'cpi_9606.ENSP00000448059', 'f_575'], ['f_356', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000364802', 'cpi_9606.ENSP00000382659', 'cpi_9606.ENSP00000267843'], ['f_11', 'cpi_9606.ENSP00000346827', 'cpi_9606.ENSP00000356832', 'cpi_9606.ENSP00000351273', 'f_425'], ['f_777', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000223366', 'f_397', 'cpi_9606.ENSP00000278616'], ['f_375', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000382250', 'cpi_9606.ENSP00000320935', 'cpi_9606.ENSP00000261196'], ['f_377', 'cpi_9606.ENSP00000279593', 'f_803', 'cpi_9606.ENSP00000222381', 'f_717'], ['cpi_9606.ENSP00000324648', 'f_458', 'cpi_9606.ENSP00000321106', 'cpi_9606.ENSP00000241600', 'f_206'], ['f_655', 'cpi_9606.ENSP00000219700', 'cpi_9606.ENSP00000359635', 'cpi_9606.ENSP00000343925', 'f_305'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000348645', 'f_152', 'cpi_9606.ENSP00000352608'], ['f_337', 'cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000282397', 'cpi_9606.ENSP00000307014', 'cpi_9606.ENSP00000264867'], ['f_493', 'cpi_9606.ENSP00000434516', 'cpi_9606.ENSP00000221515', 'cpi_9606.ENSP00000409378', 'f_456'], ['f_574', 'cpi_9606.ENSP00000330484', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000264657', 'f_301'], ['f_150', 'cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000287936', 'cpi_9606.ENSP00000370912', 'cpi_9606.ENSP00000297350'], ['f_604', 'cpi_9606.ENSP00000344460', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000233242', 'f_300'], ['f_418', 'cpi_9606.ENSP00000305742', 'cpi_9606.ENSP00000366307', 'f_711', 'cpi_9606.ENSP00000248553'], ['f_430', 'cpi_9606.ENSP00000430031', 'cpi_9606.ENSP00000419692', 'f_363', 'cpi_9606.ENSP00000308549'], ['f_259', 'cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000270776', 'f_610'], ['f_546', 'cpi_9606.ENSP00000295256', 'cpi_9606.ENSP00000295834', 'cpi_9606.ENSP00000262461', 'f_605'], ['f_642', 'cpi_9606.ENSP00000289753', 'cpi_9606.ENSP00000332679', 'cpi_9606.ENSP00000344674', 'f_515'], ['f_758', 'cpi_9606.ENSP00000220764', 'cpi_9606.ENSP00000265403', 'f_563', 'cpi_9606.ENSP00000366506'], ['f_819', 'cpi_9606.ENSP00000262623', 'cpi_9606.ENSP00000302111', 'f_364', 'f_532'], ['f_657', 'cpi_9606.ENSP00000293190', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000459962'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000320295', 'f_38', 'f_737'], ['f_449', 'cpi_9606.ENSP00000447378', 'cpi_9606.ENSP00000347979', 'f_705', 'cpi_9606.ENSP00000285979'], ['f_502', 'cpi_9606.ENSP00000356671', 'cpi_9606.ENSP00000373477', 'cpi_9606.ENSP00000410076', 'f_630'], ['f_442', 'cpi_9606.ENSP00000261733', 'cpi_9606.ENSP00000304895', 'f_700', 'cpi_9606.ENSP00000303522'], ['f_542', 'cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000346598', 'cpi_9606.ENSP00000260356', 'f_395'], ['f_470', 'cpi_9606.ENSP00000349576', 'cpi_9606.ENSP00000339299', 'cpi_9606.ENSP00000325120', 'f_784'], ['f_14', 'cpi_9606.ENSP00000261386', 'cpi_9606.ENSP00000414303', 'cpi_9606.ENSP00000307240', 'f_713'], ['f_1', 'cpi_9606.ENSP00000376914', 'cpi_9606.ENSP00000277120', 'cpi_9606.ENSP00000384273', 'f_707'], ['cpi_9606.ENSP00000337450', 'cpi_9606.ENSP00000292513', 'cpi_9606.ENSP00000301634', 'f_527', 'cpi_9606.ENSP00000351209'], ['f_286', 'cpi_9606.ENSP00000363533', 'cpi_9606.ENSP00000236671', 'cpi_9606.ENSP00000327652', 'cpi_9606.ENSP00000255030'], ['f_798', 'cpi_9606.ENSP00000327801', 'f_485', 'cpi_9606.ENSP00000254810', 'f_383'], ['f_352', 'cpi_9606.ENSP00000348395', 'cpi_9606.ENSP00000296677', 'cpi_9606.ENSP00000301146', 'f_621'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000311165', 'f_716', 'cpi_9606.ENSP00000353878', 'cpi_9606.ENSP00000307445'], ['f_188', 'cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000272847', 'cpi_9606.ENSP00000330199', 'f_779'], ['f_450', 'cpi_9606.ENSP00000252321', 'cpi_9606.ENSP00000253727', 'cpi_9606.ENSP00000356694', 'f_761'], ['f_695', 'cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000359532', 'f_457'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000353427', 'cpi_9606.ENSP00000225964', 'f_250', 'cpi_9606.ENSP00000302846'], ['f_548', 'cpi_9606.ENSP00000259486', 'cpi_9606.ENSP00000280357', 'f_414', 'cpi_9606.ENSP00000296545'], ['f_332', 'cpi_9606.ENSP00000226299', 'cpi_9606.ENSP00000310405', 'cpi_9606.ENSP00000318822', 'f_187'], ['f_539', 'cpi_9606.ENSP00000364731', 'cpi_9606.ENSP00000428924', 'f_249', 'cpi_9606.ENSP00000241261'], ['f_

🔄 Processing features: 100%|██████████| 2147/2147 [10:21<00:00,  3.45feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'cpi_9606.ENSP00000431512', 'f_413', 'cpi_9606.ENSP00000312304', 'f_118'], ['f_346', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000301891', 'f_629', 'cpi_9606.ENSP00000395653'], ['f_308', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000351957', 'f_616', 'cpi_9606.ENSP00000394936'], ['f_566', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000279178', 'cpi_9606.ENSP00000355629'], ['f_617', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000241453', 'f_726', 'cpi_9606.ENSP00000324856'], ['f_335', 'cpi_9606.ENSP00000321584', 'f_834', 'cpi_9606.ENSP00000428340', 'f_31'], ['f_366', 'cpi_9606.ENSP00000310219', 'f_789', 'cpi_9606.ENSP00000359353', 'f_428'], ['cpi_9606.ENSP00000367959', 'f_588', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000301633', 'f_292'], ['cpi_9606.ENSP00000353820', 'f_131', 'f_26', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000360773'], ['f_391', 'cpi_9606.ENSP00000313490', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000352900'], ['cpi_9606.ENSP00000356438', 'f_216', 'f_401', 'cpi_9606.ENSP00000352011', 'f_427'], ['cpi_9606.ENSP00000354612', 'f_129', 'f_455', 'cpi_9606.ENSP00000277010', 'cpi_9606.ENSP00000286648'], ['f_186', 'cpi_9606.ENSP00000345096', 'f_511', 'f_845', 'cpi_9606.ENSP00000216037'], ['f_146', 'cpi_9606.ENSP00000277541', 'f_773', 'cpi_9606.ENSP00000274793', 'cpi_9606.ENSP00000304822'], ['f_643', 'cpi_9606.ENSP00000264426', 'cpi_9606.ENSP00000332296', 'cpi_9606.ENSP00000292427', 'f_151'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000234310', 'cpi_9606.ENSP00000372547', 'f_347', 'f_587'], ['f_2', 'cpi_9606.ENSP00000349576', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000218099'], ['f_571', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000256383', 'f_526'], ['f_637', 'cpi_9606.ENSP00000376914', 'cpi_9606.ENSP00000367848', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000357283'], ['f_380', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000355533', 'f_831', 'cpi_9606.ENSP00000257290'], ['f_614', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000251535', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000221972'], ['f_192', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000295454', 'f_47', 'cpi_9606.ENSP00000364212'], ['f_374', 'cpi_9606.ENSP00000264705', 'f_768', 'cpi_9606.ENSP00000295452', 'f_27'], ['f_12', 'cpi_9606.ENSP00000354532', 'f_635', 'cpi_9606.ENSP00000333212', 'f_788'], ['f_440', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000378517', 'f_25', 'cpi_9606.ENSP00000342235'], ['f_185', 'cpi_9606.ENSP00000364782', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000430684'], ['f_345', 'cpi_9606.ENSP00000233944', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000276449'], ['f_338', 'cpi_9606.ENSP00000331746', 'f_529', 'cpi_9606.ENSP00000274547', 'cpi_9606.ENSP00000309124'], ['f_393', 'cpi_9606.ENSP00000234590', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000354476', 'cpi_9606.ENSP00000408860'], ['f_692', 'cpi_9606.ENSP00000354193', 'f_725', 'cpi_9606.ENSP00000248041', 'f_330'], ['f_656', 'cpi_9606.ENSP00000305742', 'f_866', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000319788'], ['f_180', 'cpi_9606.ENSP00000273550', 'cpi_9606.ENSP00000263126', 'cpi_9606.ENSP00000356094', 'cpi_9606.ENSP00000264637'], ['cpi_9606.ENSP00000337450', 'f_715', 'f_763', 'f_262', 'cpi_9606.ENSP00000263321'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000261937', 'f_22', 'f_215'], ['f_615', 'cpi_9606.ENSP00000230671', 'f_839', 'cpi_9606.ENSP00000226574', 'cpi_9606.ENSP00000369530'], ['f_3', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000337335', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000321988'], ['cpi_9606.ENSP00000360372', 'f_132', 'f_812', 'cpi_9606.ENSP00000227758', 'f_551'], ['f_341', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000273398', 'f_836', 'f_830'], ['f_697', 'cpi_9606.ENSP00000357669', 'cpi_9606.ENSP00000414334', 'cpi_9606.ENSP00000445340', 'f_749'], ['f_645', 'cpi_9606.ENSP00000353791', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000366662', 'f_767'], ['f_611', 'cpi_9606.ENSP00000279387', 'cpi_9606.ENSP00000320401', 'f_214', 'cpi_9606.ENSP00000222256'], ['cpi_9606.ENSP00000311032', 'f_510', 'f_207', 'f_43', 'f_736'], ['f_299', 'cpi_9606.ENSP00000306397', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000358595', 'f_622'], ['f_553', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000321999', 'cpi_9606.ENSP00000282561', 'f_297'], ['f_704', 'cpi_9606.ENSP00000297792', 'cpi_9606.ENSP00000302811', 'cpi_9606.ENSP00000389414', 'f_327'], ['f_406', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000374323', 'f_820'], ['cpi_9606.ENSP00000328968', 'f_462', 'cpi_9606.ENSP00000385026', 'f_778', 'f_488'], ['f_143', 'cpi_9606.ENSP00000001008', 'cpi_9606.ENSP00000346148', 'f_328', 'cpi_9606.ENSP00000390600'], ['f_712', 'cpi_9606.ENSP00000218548', 'f_771', 'f_35', 'cpi_9606.ENSP00000345659'], ['f_405', 'cpi_9606.ENSP00000443459', 'cpi_9606.ENSP00000316786', 'f_792', 'cpi_9606.ENSP00000312029'], ['f_439', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000253799', 'f_861'], ['f_683', 'cpi_9606.ENSP00000323867', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000312455', 'cpi_9606.ENSP00000367851'], ['f_257', 'cpi_9606.ENSP00000332549', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000258749', 'cpi_9606.ENSP00000222330'], ['cpi_9606.ENSP00000258743', 'f_454', 'f_496', 'f_583', 'f_166'], ['f_20', 'cpi_9606.ENSP00000308032', 'cpi_9606.ENSP00000362649', 'f_729', 'f_194'], ['f_452', 'cpi_9606.ENSP00000358525', 'cpi_9606.ENSP00000347942', 'cpi_9606.ENSP00000343477', 'cpi_9606.ENSP00000242057'], ['f_535', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000350785', 'f_509', 'cpi_9606.ENSP00000365016'], ['cpi_9606.ENSP00000418532', 'f_602', 'cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000381097', 'cpi_9606.ENSP00000341390'], ['cpi_9606.ENSP00000324648', 'f_227', 'f_706', 'f_408', 'f_497'], ['f_528', 'cpi_9606.ENSP00000362508', 'cpi_9606.ENSP00000319814', 'cpi_9606.ENSP00000428864', 'f_460'], ['f_646', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000305302', 'cpi_9606.ENSP00000261196', 'cpi_9606.ENSP00000305422'], ['f_15', 'cpi_9606.ENSP00000330484', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000470087', 'f_417'], ['f_597', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000354107', 'cpi_9606.ENSP00000294954', 'f_361'], ['f_392', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000295834', 'f_202'], ['f_569', 'cpi_9606.ENSP00000397026', 'cpi_9606.ENSP00000419692', 'cpi_9606.ENSP00000376943', 'f_799'], ['f_684', 'cpi_9606.ENSP00000234389', 'cpi_9606.ENSP00000231188', 'f_554', 'f_474'], ['f_339', 'cpi_9606.ENSP00000394033', 'cpi_9606.ENSP00000367102', 'f_670', 'f_429'], ['f_671', 'cpi_9606.ENSP00000254488', 'cpi_9606.ENSP00000272847', 'f_675', 'f_229'], ['f_181', 'cpi_9606.ENSP00000370129', 'cpi_9606.ENSP00000314214', 'cpi_9606.ENSP00000387946', 'f_167'], ['f_19', 'cpi_9606.ENSP00000472933', 'cpi_9606.ENSP00000463999', 'cpi_9606.ENSP00000311095', 'cpi_9606.ENSP00000417229'], ['f_540', 'cpi_9606.ENSP00000287878', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000326119'], ['f_672', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000411658', 'cpi_9606.ENSP00000291295', 'f_815'], ['f_340', 'cpi_9606.ENSP00000302886', 'cpi_9606.ENSP00000362403', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000353292'], ['f_680', 'cpi_9606.ENSP00000471569', 'cpi_9606.ENSP00000306100', 'cpi_9606.ENSP00000419782', 'cpi_9606.ENSP00000286301'], ['f_451', 'cpi_9606.ENSP00000360967', 'cpi_9606.ENSP00000348786', 'cpi_9606.ENSP00000451040', 'f_436'], ['f_659', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000248572'], ['f_580', 'cpi_9606.ENSP00000375881', 'f_343', 'f_631', 'f_757'], ['f_432', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000353720', 'f_533', 'f_486'], ['f_691', 'cpi_9606.ENSP00000302564', 'f_483', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000256958'], ['f_698', 'cpi_9606.ENSP00000364709', 'f_388', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000216862'], ['cpi_9606.ENSP00000270349', 'cpi_9606.ENSP00000301645', 'f_465', 'f_195', 'cpi_9606.ENSP00000266376'], ['f_685', 'f_242', 'cpi_9606.ENSP00000307599', 'cpi_9606.ENSP00000241261', 'cpi_9606.ENSP00000262160'], ['f_145', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000290349', 'f_827', 'f_350'], ['f_365', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000356832', 'cpi_9606.ENSP00000344192'], ['f_682', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000303452', 'cpi_9606.ENSP00000225474', 'f_791'], ['cpi_9606.ENSP00000222982', 'f_543', 'cpi_9606.ENSP00000245457', 'cpi_9606.ENSP00000225927', 'f_164'], ['f_443', 'cpi_9606.ENSP00000312326', 'cpi_9606.ENSP00000232219', 'f_785', 'cpi_9606.ENSP00000389338'], ['cpi_9606.ENSP00000272190', 'f_115', 'f_728', 'f_159', 'cpi_9606.ENSP00000275525'], ['f_493', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000327850', 'f_407', 'cpi_9606.ENSP00000358548'], ['f_420', 'cpi_9606.ENSP00000304408', 'cpi_9606.ENSP00000318646', 'cpi_9606.ENSP00000300061', 'f_722'], ['f_758', 'cpi_9606.ENSP00000308541', 'f_298', 'cpi_9606.ENSP00000262999', 'f_230'], ['f_502', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000362513', 'cpi_9606.ENSP00000278175', 'cpi_9606.ENSP00000343040'], ['f_241', 'cpi_9606.ENSP00000360608', 'f_764', 'f_508', 'cpi_9606.ENSP00000252486'], ['f_16', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000296122', 'cpi_9606.ENSP00000262367'], ['f_390', 'cpi_9606.ENSP00000352584', 'cpi_9606.ENSP00000218758', 'f_505', 'f_448'], ['f_619', 'cpi_9606.ENSP00000244217', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000296871', 'f_466'], ['f_593', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000303522', 'cpi_9606.ENSP00000294728', 'cpi_9606.ENSP00000295491'], ['f_594', 'cpi_9606.ENSP00000358107', 'cpi_9606.ENSP00000333821', 'cpi_9606.ENSP00000234071', 'f_46'], ['f_293', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000283635', 'cpi_9606.ENSP00000358730', 'cpi_9606.ENSP00000355778'], ['f_689', 'cpi_9606.ENSP00000359719', 'cpi_9606.ENSP00000329357', 'f_647', 'f_750'], ['f_821', 'f_411', 'cpi_9606.ENSP00000335620', 'cpi_9606.ENSP00000366307', 'f_471'], ['f_642', 'f_422', 'cpi_9606.ENSP00000285979', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000261416'], ['f_666', 'cpi_9606.ENSP00000312673', 'cpi_9606.ENSP00000280357', 'cpi_9606.ENSP00000360493', 'cpi_9606.ENSP00000231454'], ['f_464', 'cpi_9606.ENSP00000263212', 'f_719', 'f_840', 'cpi_9606.ENSP00000376776'], ['f_592', 'cpi_9606.ENSP00000238018', 'cpi_9606.ENSP00000454071', 'cpi_9606.ENSP00000361666', 'f_676'], ['f_337', 'cpi_9606.ENSP00000359285', 'f_609', 'cpi_9606.ENSP00000261405', 'f_409'], ['cpi_9606.ENSP00000265724', 'f_423', 'cpi_9606.ENSP00000299178', 'cpi_9606.ENSP00000245539', 'f_116'], ['f_638', 'cpi_9606.ENSP00000225275', 'f_860', 'f_813', 'f_568'], ['f_641', 'cpi_9606.ENSP00000418447', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000252723', 'f_473'], ['f_536', 'cpi_9606.ENSP00000343838', 'f_833', 'cpi_9606.ENSP00000276571', 'cpi_9606.ENSP00000323568'], ['f_702', 'cpi_9606.ENSP00000276431', 'cpi_9606.ENSP00000260010', 'f_514', 'cpi_9606.ENSP00000348069'], ['f_516', 'cpi_9606.ENSP00000362329', 'cpi_9606.ENSP00000427514', 'f_782', 'f_475'], ['f_681', 'cpi_9606.ENSP00000337103', 'cpi_9606.ENSP00000261799', 'cpi_9606.ENSP00000370254', 'f_650'], ['f_546', 'cpi_9606.ENSP00000279593', 'cpi_9606.ENSP00000356958', 'f_367', 'cpi_9606.ENSP00000359793'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000312664', 'cpi_9606.ENSP00000311165', 'f_394', 'f_513'], ['f_300', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000326219'], ['f_579', 'cpi_9606.ENSP00000314499', 'cpi_9606.ENSP00000354394', 'f_518', 'f_770'], ['f_199', 'cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000275300', 'cpi_9606.ENSP00000365380', 'f_398'], ['f_244', 'cpi_9606.ENSP00000239223', 'cpi_9606.ENSP00000262461', 'f_752', 'f_336'], ['f_581', 'cpi_9606.ENSP00000319591', 'cpi_9606.ENSP00000307235', 'cpi_9606.ENSP00000386029', 'f_477'], ['f_248', 'cpi_9606.ENSP00000262623', 'cpi_9606.ENSP00000308165', 'cpi_9606.ENSP00000217426', 'f_522'], ['f_23', 'cpi_9606.ENSP00000363965', 'cpi_9606.ENSP00000354569', 'f_687', 'f_559'], ['f_573', 'cpi_9606.ENSP00000293190', 'cpi_9606.ENSP00000222390', 'f_419', 'f_494'], ['f_797', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000355920', 'f_558', 'cpi_9606.ENSP00000361359'], ['f_654', 'cpi_9606.ENSP00000378323', 'cpi_9606.ENSP00000387683', 'f_826', 'cpi_9606.ENSP00000298472'], ['f_33', 'cpi_9606.ENSP00000317842', 'cpi_9606.ENSP00000466799', 'cpi_9606.ENSP00000348897', 'f_653'], ['f_696', 'cpi_9606.ENSP00000286621', 'cpi_9606.ENSP00000457706', 'cpi_9606.ENSP00000356954', 'f_30'], ['f_507', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000353915', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000369375'], ['f_498', 'cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000325822'], ['f_734', 'cpi_9606.ENSP00000226730', 'f_395', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000259089'], ['f_699', 'cpi_9606.ENSP00000354280', 'f_644', 'cpi_9606.ENSP00000261693', 'f_34'], ['f_368', 'cpi_9606.ENSP00000358784', 'cpi_9606.ENSP00000263923', 'cpi_9606.ENSP00000301634', 'f_801'], ['f_628', 'cpi_9606.ENSP00000216714', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000301178', 'cpi_9606.ENSP00000448059'], ['f_153', 'cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000318585', 'cpi_9606.ENSP00000248553', 'f_738'], ['f_623', 'f_314', 'cpi_9606.ENSP00000266682', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000262888'], ['f_548', 'cpi_9606.ENSP00000327255', 'cpi_9606.ENSP00000330393', 'f_359', 'cpi_9606.ENSP00000222002'], ['f_515', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000267101', 'cpi_9606.ENSP00000293745'], ['f_353', 'cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000363596', 'cpi_9606.ENSP00000287936', 'f_707'], ['f_574', 'cpi_9606.ENSP00000399168', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000331912', 'cpi_9606.ENSP00000233242'], ['f_287', 'cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000260191', 'f_694', 'cpi_9606.ENSP00000410732'], ['f_37', 'cpi_9606.ENSP00000400175', 'cpi_9606.ENSP00000234371', 'cpi_9606.ENSP00000270776', 'f_740'], ['f_586', 'cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000353878', 'cpi_9606.ENSP00000370473', 'f_517'], ['f_667', 'cpi_9606.ENSP00000342070', 'f_822', 'f_425', 'f_742'], ['f_560', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000311028', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000293288'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000234961', 'f_456', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000255465'], ['f_599', 'cpi_9606.ENSP00000300093', 'cpi_9606.ENSP00000263980', 'f_461', 'cpi_9606.ENSP00000231228'], ['f_542', 'cpi_9606.ENSP00000314949', 'cpi_9606.ENSP00000299267', 'cpi_9606.ENSP00000304915', 'f_480'], ['f_349', 'cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000296522', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000200676'], ['f_604', 'cpi_9606.ENSP00000248923', 'cpi_9606.ENSP00000343204', 'cpi_9606.ENSP00000239938', 'f_17'], ['f_437', 'cpi_9606.ENSP00000332973', 'cpi_9606.ENSP00000297268', 'f_144', 'f_717'], ['f_539', 'cpi_9606.ENSP00000295256', 'cpi_9606.ENSP00000341045', 'f_625', 'cpi_9606.ENSP00000364802'], ['f_755', 'cpi_9606.ENSP00000344352', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000293330', 'f_652'], ['f_294', 'cpi_9606.ENSP00000285238', 'cpi_9606.ENSP00000362036', 'f_527', 'cpi_9606.ENSP00000320935'], ['f_286', 'cpi_9606.ENSP00000337746', 'cpi_9606.ENSP00000310405', 'f_759', 'f_160'], ['f_663', 'cpi_9606.ENSP00000363868', 'f_467', 'cpi_9606.ENSP00000341828', 'cpi_9606.ENSP00000355930'], ['f_259', 'cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000370381', 'cpi_9606.ENSP00000350005', 'cpi_9606.ENSP00000325120'], ['f_375', 'cpi_9606.ENSP00000299855', 'cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000382659', 'f_605'], ['f_708', 'cpi_9606.ENSP00000397582', 'cpi_9606.ENSP00000339527', 'f_489', 'cpi_9606.ENSP00000307014'], ['f_442', 'cpi_9606.ENSP00000359998', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000217305', 'cpi_9606.ENSP00000252809'], ['f_607', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000371138', 'f_610', 'cpi_9606.ENSP00000356430'], ['f_585', 'cpi_9606.ENSP00000236671', 'cpi_9606.ENSP00000310447', 'cpi_9606.ENSP00000365663', 'f_803'], ['cpi_9606.ENSP00000295897', 'f_363', 'f_378', 'cpi_9606.ENSP00000311469', 'cpi_9606.ENSP00000307445'], ['f_453', 'cpi_9606.ENSP00000338627', 'cpi_9606.ENSP00000196551', 'cpi_9606.ENSP00000398632', 'f_705'], ['f_188', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000307240', 'f_152'], ['f_449', 'cpi_9606.ENSP00000263269', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000259396', 'f_780'], ['f_418', 'cpi_9606.ENSP00000240139', 'cpi_9606.ENSP00000251566', 'f_575', 'cpi_9606.ENSP00000416293'], ['f_818', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000292896', 'f_305', 'cpi_9606.ENSP00000277120'], ['f_342', 'cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000260356', 'cpi_9606.ENSP00000340691', 'f_399'], ['cpi_9606.ENSP00000414303', 'f_414', 'cpi_9606.ENSP00000351209', 'cpi_9606.ENSP00000359532', 'f_157'], ['f_555', 'cpi_9606.ENSP00000314508', 'cpi_9606.ENSP00000301420', 'cpi_9606.ENSP00000267163', 'f_38'], ['cpi_9606.ENSP00000269305', 'f_658', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000176763', 'f_200'], ['f_285', 'cpi_9606.ENSP00000277508', 'cpi_9606.ENSP00000240652', 'f_721', 'cpi_9606.ENSP00000365775'], ['f_333', 'cpi_9606.ENSP00000358042', 'cpi_9606.ENSP00000264657', 'f_301', 'cpi_9606.ENSP00000308549'], ['f_549', 'cpi_9606.ENSP00000362924', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000343782'], ['f_21', 'cpi_9606.ENSP00000276198', 'cpi_9606.ENSP00000317272', 'f_457', 'cpi_9606.ENSP00000369816'], ['f_431', 'cpi_9606.ENSP00000349078', 'f_249', 'cpi_9606.ENSP00000309103', 'cpi_9606.ENSP00000367309'], ['f_613', 'cpi_9606.ENSP00000314649', 'cpi_9606.ENSP00000298386', 'cpi_9606.ENSP00000384273', 'cpi_9606.ENSP00000335511'], ['f_412', 'cpi_9606.ENSP00000382342', 'cpi_9606.ENSP00000309757', 'cpi_9606.ENSP00000301146', 'cpi_9606.ENSP00000220616'], ['f_800', 'cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000349577', 'f_206', 'f_421'], ['f_213', 'cpi_9606.ENSP00000287820', 'f_805', 'cpi_9606.ENSP00000320866', 'cpi_9606.ENSP00000344674'], ['f_657', 'cpi_9606.ENSP00000378306', 'cpi_9606.ENSP00000305221', 'f_700', 'cpi_9606.ENSP00000318822'], ['f_639', 'cpi_9606.ENSP00000333496', 'cpi_9606.ENSP00000332369', 'f_500', 'cpi_9606.ENSP00000265403'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000371985', 'f_612', 'cpi_9606.ENSP00000356198', 'f_550'], ['f_655', 'cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000302111', 'cpi_9606.ENSP00000231449', 'f_24'], ['f_567', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000199280', 'cpi_9606.ENSP00000226413', 'f_532'], ['f_377', 'cpi_9606.ENSP00000324173', 'cpi_9606.ENSP00000267119', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000324270'], ['f_523', 'cpi_9606.ENSP00000330199', 'cpi_9606.ENSP00000433821', 'cpi_9606.ENSP00000321106', 'cpi_9606.ENSP00000267843'], ['f_541', 'cpi_9606.ENSP00000434516', 'cpi_9606.ENSP00000297350', 'f_397', 'cpi_9606.ENSP00000370912'], ['f_243', 'cpi_9606.ENSP00000417281', 'cpi_9606.ENSP00000386171', 'cpi_9606.ENSP00000319984', 'f_364'], ['f_356', 'cpi_9606.ENSP00000286719', 'cpi_9606.ENSP00000387888', 'cpi_9606.ENSP00000255030', 'f_563'], ['f_777', 'cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000305692', 'cpi_9606.ENSP00000278616', 'f_716'], ['f_445', 'cpi_9606.ENSP00000354511', 'f_661', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000219919'], ['f_693', 'cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000427562', 'cpi_9606.ENSP00000310928', 'f_458'], ['f_686', 'cpi_9606.ENSP00000347754'

🔄 Processing features: 100%|██████████| 2147/2147 [10:20<00:00,  3.46feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'f_408', 'f_428', 'cpi_9606.ENSP00000414334', 'f_166'], ['f_366', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000395653', 'cpi_9606.ENSP00000220616', 'f_768'], ['cpi_9606.ENSP00000353820', 'f_131', 'f_26', 'cpi_9606.ENSP00000360773', 'f_715'], ['f_308', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000374323', 'cpi_9606.ENSP00000338627', 'f_791'], ['cpi_9606.ENSP00000342007', 'f_30', 'f_510', 'cpi_9606.ENSP00000359424', 'f_529'], ['cpi_9606.ENSP00000367959', 'f_132', 'cpi_9606.ENSP00000003100', 'f_494', 'f_292'], ['f_374', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000338082', 'f_31', 'cpi_9606.ENSP00000291700'], ['f_346', 'cpi_9606.ENSP00000279178', 'cpi_9606.ENSP00000256383', 'f_629', 'f_726'], ['f_405', 'cpi_9606.ENSP00000305742', 'cpi_9606.ENSP00000295452', 'f_789', 'f_413'], ['f_391', 'cpi_9606.ENSP00000313490', 'cpi_9606.ENSP00000430684', 'f_845', 'f_866'], ['f_20', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000367848', 'cpi_9606.ENSP00000314214'], ['f_146', 'cpi_9606.ENSP00000001008', 'f_836', 'cpi_9606.ENSP00000304822', 'f_350'], ['f_12', 'cpi_9606.ENSP00000354532', 'f_635', 'cpi_9606.ENSP00000262352', 'f_834'], ['f_335', 'cpi_9606.ENSP00000321584', 'f_511', 'f_752', 'cpi_9606.ENSP00000265294'], ['f_186', 'cpi_9606.ENSP00000345096', 'f_118', 'cpi_9606.ENSP00000409007', 'f_202'], ['f_643', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000332296', 'cpi_9606.ENSP00000355629', 'f_151'], ['f_185', 'cpi_9606.ENSP00000364782', 'cpi_9606.ENSP00000359793', 'cpi_9606.ENSP00000221972', 'cpi_9606.ENSP00000457706'], ['f_638', 'cpi_9606.ENSP00000225275', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000359353'], ['f_566', 'cpi_9606.ENSP00000229264', 'f_417', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000454071'], ['f_406', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000259089', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000335592'], ['f_299', 'cpi_9606.ENSP00000233944', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000354476', 'cpi_9606.ENSP00000451040'], ['f_528', 'cpi_9606.ENSP00000362508', 'f_460', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000351908'], ['f_645', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000353362'], ['f_712', 'f_830', 'cpi_9606.ENSP00000262623', 'f_47', 'f_771'], ['f_659', 'cpi_9606.ENSP00000254488', 'f_427', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000360493'], ['cpi_9606.ENSP00000311032', 'f_164', 'f_298', 'f_43', 'f_831'], ['f_571', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000301891', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000369375'], ['f_440', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000356436', 'f_25', 'cpi_9606.ENSP00000378517'], ['f_380', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000355533', 'cpi_9606.ENSP00000356094', 'cpi_9606.ENSP00000365663'], ['f_614', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000344674', 'f_749'], ['f_617', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000342235'], ['cpi_9606.ENSP00000356438', 'f_213', 'f_706', 'f_407', 'f_773'], ['f_535', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000262888', 'f_327', 'cpi_9606.ENSP00000367851'], ['f_181', 'cpi_9606.ENSP00000273550', 'cpi_9606.ENSP00000263126', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000299178'], ['f_393', 'cpi_9606.ENSP00000306397', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000277010', 'f_27'], ['f_339', 'cpi_9606.ENSP00000023897', 'f_526', 'cpi_9606.ENSP00000273398', 'f_736'], ['f_672', 'cpi_9606.ENSP00000279387', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000282561', 'f_767'], ['f_451', 'cpi_9606.ENSP00000330199', 'cpi_9606.ENSP00000348786', 'cpi_9606.ENSP00000264637', 'f_330'], ['f_696', 'cpi_9606.ENSP00000164139', 'cpi_9606.ENSP00000349576', 'f_46', 'cpi_9606.ENSP00000470087'], ['f_452', 'cpi_9606.ENSP00000354193', 'f_616', 'cpi_9606.ENSP00000259396', 'f_785'], ['f_3', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000367309', 'f_401'], ['f_192', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000296122', 'cpi_9606.ENSP00000292513'], ['f_338', 'cpi_9606.ENSP00000331746', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000261799', 'cpi_9606.ENSP00000306100'], ['cpi_9606.ENSP00000260682', 'f_22', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000322617', 'f_466'], ['f_143', 'cpi_9606.ENSP00000362924', 'cpi_9606.ENSP00000274793', 'f_328', 'cpi_9606.ENSP00000320025'], ['f_257', 'cpi_9606.ENSP00000234310', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000435591'], ['f_2', 'cpi_9606.ENSP00000357336', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000319788', 'cpi_9606.ENSP00000296370'], ['cpi_9606.ENSP00000360372', 'f_200', 'f_812', 'cpi_9606.ENSP00000293745', 'f_508'], ['f_646', 'cpi_9606.ENSP00000360967', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000298472'], ['f_656', 'cpi_9606.ENSP00000376914', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000427514', 'cpi_9606.ENSP00000398632'], ['f_615', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000231228', 'f_587', 'cpi_9606.ENSP00000309968'], ['f_345', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000200676', 'cpi_9606.ENSP00000376178'], ['cpi_9606.ENSP00000222982', 'f_314', 'f_778', 'cpi_9606.ENSP00000369530', 'f_763'], ['cpi_9606.ENSP00000354612', 'f_129', 'f_522', 'f_242', 'f_194'], ['f_439', 'cpi_9606.ENSP00000346298', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000467676', 'f_297'], ['f_392', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000254066', 'f_509'], ['cpi_9606.ENSP00000324648', 'f_227', 'f_543', 'cpi_9606.ENSP00000286648', 'f_583'], ['f_683', 'cpi_9606.ENSP00000287878', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000312455', 'cpi_9606.ENSP00000346534'], ['f_698', 'cpi_9606.ENSP00000364709', 'cpi_9606.ENSP00000216037', 'f_388', 'f_813'], ['f_420', 'cpi_9606.ENSP00000312326', 'f_675', 'cpi_9606.ENSP00000252809', 'f_497'], ['f_642', 'cpi_9606.ENSP00000333212', 'f_750', 'cpi_9606.ENSP00000292896', 'f_568'], ['f_180', 'cpi_9606.ENSP00000370129', 'cpi_9606.ENSP00000258749', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000266376'], ['f_375', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000333496', 'f_839', 'cpi_9606.ENSP00000326119'], ['f_145', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000261196', 'cpi_9606.ENSP00000263339', 'f_554'], ['f_569', 'cpi_9606.ENSP00000308032', 'cpi_9606.ENSP00000216962', 'f_214', 'cpi_9606.ENSP00000241600'], ['f_341', 'cpi_9606.ENSP00000331912', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000253004', 'cpi_9606.ENSP00000257290'], ['f_15', 'cpi_9606.ENSP00000320401', 'cpi_9606.ENSP00000343392', 'f_670', 'f_436'], ['f_443', 'cpi_9606.ENSP00000349252', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000459962'], ['f_23', 'cpi_9606.ENSP00000295453', 'f_631', 'cpi_9606.ENSP00000353292', 'cpi_9606.ENSP00000394936'], ['cpi_9606.ENSP00000270349', 'f_21', 'f_116', 'cpi_9606.ENSP00000367102', 'f_477'], ['f_540', 'cpi_9606.ENSP00000323867', 'cpi_9606.ENSP00000387946', 'cpi_9606.ENSP00000307599', 'cpi_9606.ENSP00000312664'], ['f_697', 'cpi_9606.ENSP00000357669', 'cpi_9606.ENSP00000248076', 'f_725', 'cpi_9606.ENSP00000417229'], ['f_580', 'cpi_9606.ENSP00000375881', 'f_622', 'f_429', 'f_820'], ['f_692', 'cpi_9606.ENSP00000354107', 'cpi_9606.ENSP00000216392', 'cpi_9606.ENSP00000245539', 'f_474'], ['f_680', 'cpi_9606.ENSP00000366927', 'cpi_9606.ENSP00000344352', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000286301'], ['f_16', 'cpi_9606.ENSP00000360608', 'f_861', 'f_719', 'cpi_9606.ENSP00000251535'], ['f_293', 'cpi_9606.ENSP00000301633', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000358730', 'cpi_9606.ENSP00000344192'], ['f_432', 'cpi_9606.ENSP00000363868', 'f_609', 'f_35', 'f_757'], ['cpi_9606.ENSP00000258743', 'f_454', 'cpi_9606.ENSP00000261937', 'f_207', 'cpi_9606.ENSP00000234071'], ['f_464', 'cpi_9606.ENSP00000264426', 'cpi_9606.ENSP00000311095', 'cpi_9606.ENSP00000343040', 'f_827'], ['f_353', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000283635', 'cpi_9606.ENSP00000301178', 'cpi_9606.ENSP00000314949'], ['f_593', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000356694', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000222256'], ['f_637', 'cpi_9606.ENSP00000435412', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000312029', 'f_729'], ['cpi_9606.ENSP00000265724', 'f_455', 'f_505', 'f_262', 'f_788'], ['f_639', 'cpi_9606.ENSP00000337335', 'cpi_9606.ENSP00000394033', 'cpi_9606.ENSP00000178638', 'f_792'], ['f_671', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000321999', 'f_229', 'f_764'], ['f_611', 'cpi_9606.ENSP00000301146', 'cpi_9606.ENSP00000260649', 'cpi_9606.ENSP00000428340', 'f_361'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000413074', 'f_742', 'f_513', 'f_486'], ['f_704', 'cpi_9606.ENSP00000305302', 'cpi_9606.ENSP00000435777', 'cpi_9606.ENSP00000389414', 'f_728'], ['f_682', 'cpi_9606.ENSP00000320709', 'cpi_9606.ENSP00000296871', 'cpi_9606.ENSP00000370373', 'f_799'], ['f_241', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000222330', 'cpi_9606.ENSP00000389338', 'f_815'], ['f_515', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000289753', 'f_115', 'cpi_9606.ENSP00000359663'], ['f_502', 'cpi_9606.ENSP00000279593', 'f_782', 'cpi_9606.ENSP00000267017', 'f_551'], ['f_365', 'cpi_9606.ENSP00000366620', 'cpi_9606.ENSP00000365380', 'cpi_9606.ENSP00000376943', 'f_448'], ['f_445', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000386171', 'cpi_9606.ENSP00000225474', 'f_471'], ['f_684', 'cpi_9606.ENSP00000353791', 'cpi_9606.ENSP00000317379', 'cpi_9606.ENSP00000381097', 'f_473'], ['f_340', 'cpi_9606.ENSP00000286091', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000366307', 'f_343'], ['f_516', 'cpi_9606.ENSP00000359100', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000343477', 'cpi_9606.ENSP00000382659'], ['f_248', 'cpi_9606.ENSP00000267119', 'cpi_9606.ENSP00000225927', 'cpi_9606.ENSP00000293330', 'f_167'], ['f_691', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000297350', 'cpi_9606.ENSP00000353878', 'cpi_9606.ENSP00000371929'], ['f_689', 'cpi_9606.ENSP00000362329', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000309818', 'f_676'], ['f_685', 'f_363', 'cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000275300', 'cpi_9606.ENSP00000363812'], ['f_667', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000351209', 'f_518'], ['f_613', 'cpi_9606.ENSP00000352584', 'cpi_9606.ENSP00000218758', 'cpi_9606.ENSP00000356954', 'f_409'], ['f_592', 'cpi_9606.ENSP00000369100', 'cpi_9606.ENSP00000329357', 'f_722', 'cpi_9606.ENSP00000361666'], ['f_702', 'cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000357283', 'f_483', 'f_195'], ['f_623', 'f_425', 'cpi_9606.ENSP00000305221', 'cpi_9606.ENSP00000354569', 'cpi_9606.ENSP00000382250'], ['f_150', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000348069', 'cpi_9606.ENSP00000353427', 'cpi_9606.ENSP00000308774'], ['f_597', 'cpi_9606.ENSP00000226413', 'cpi_9606.ENSP00000199280', 'cpi_9606.ENSP00000300061', 'f_411'], ['f_699', 'f_488', 'cpi_9606.ENSP00000358107', 'cpi_9606.ENSP00000262948', 'cpi_9606.ENSP00000385806'], ['f_586', 'cpi_9606.ENSP00000353720', 'f_826', 'cpi_9606.ENSP00000252723', 'f_394'], ['f_33', 'cpi_9606.ENSP00000358022', 'cpi_9606.ENSP00000252486', 'f_801', 'cpi_9606.ENSP00000217305'], ['cpi_9606.ENSP00000272190', 'f_489', 'f_575', 'cpi_9606.ENSP00000347942', 'cpi_9606.ENSP00000410732'], ['f_604', 'cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000242057', 'f_159'], ['f_594', 'cpi_9606.ENSP00000332549', 'cpi_9606.ENSP00000370473', 'f_647', 'f_398'], ['f_553', 'cpi_9606.ENSP00000354280', 'cpi_9606.ENSP00000308165', 'f_496', 'f_230'], ['f_244', 'f_840', 'cpi_9606.ENSP00000318585', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000295491'], ['f_370', 'cpi_9606.ENSP00000240139', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000267843', 'f_419'], ['f_666', 'cpi_9606.ENSP00000280357', 'cpi_9606.ENSP00000312673', 'cpi_9606.ENSP00000231454', 'f_588'], ['f_628', 'cpi_9606.ENSP00000216714', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000262999', 'f_558'], ['f_287', 'cpi_9606.ENSP00000241052', 'f_216', 'f_694', 'cpi_9606.ENSP00000345708'], ['f_581', 'cpi_9606.ENSP00000354511', 'f_422', 'f_533', 'f_456'], ['f_655', 'cpi_9606.ENSP00000399168', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000346598', 'cpi_9606.ENSP00000275525'], ['f_573', 'cpi_9606.ENSP00000297792', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000276449', 'f_833'], ['f_437', 'cpi_9606.ENSP00000397026', 'cpi_9606.ENSP00000309493', 'cpi_9606.ENSP00000226574', 'f_860'], ['f_294', 'cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000256958', 'cpi_9606.ENSP00000331358', 'f_160'], ['f_654', 'cpi_9606.ENSP00000239849', 'cpi_9606.ENSP00000356671', 'cpi_9606.ENSP00000262367', 'f_625'], ['f_546', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000307900', 'f_803', 'f_650'], ['f_549', 'cpi_9606.ENSP00000378306', 'cpi_9606.ENSP00000260356', 'f_653', 'f_475'], ['f_821', 'cpi_9606.ENSP00000218548', 'f_347', 'cpi_9606.ENSP00000261693', 'cpi_9606.ENSP00000316786'], ['f_536', 'cpi_9606.ENSP00000176183', 'cpi_9606.ENSP00000333926', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000358548'], ['f_390', 'cpi_9606.ENSP00000216410', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000361359', 'f_461'], ['f_641', 'cpi_9606.ENSP00000354871', 'cpi_9606.ENSP00000295454', 'cpi_9606.ENSP00000239938', 'f_559'], ['f_579', 'cpi_9606.ENSP00000374265', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000309124', 'f_517'], ['f_539', 'cpi_9606.ENSP00000341045', 'cpi_9606.ENSP00000295256', 'cpi_9606.ENSP00000263980', 'cpi_9606.ENSP00000385026'], ['f_818', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000332369', 'cpi_9606.ENSP00000354394'], ['f_507', 'cpi_9606.ENSP00000302961', 'cpi_9606.ENSP00000368880', 'f_738', 'cpi_9606.ENSP00000308549'], ['cpi_9606.ENSP00000219833', 'f_673', 'cpi_9606.ENSP00000340820', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000348827'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000234961', 'cpi_9606.ENSP00000362649', 'f_215', 'f_687'], ['f_19', 'cpi_9606.ENSP00000472933', 'cpi_9606.ENSP00000463999', 'cpi_9606.ENSP00000339527', 'f_770'], ['f_368', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000332816', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000428864'], ['f_695', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000352035', 'f_144', 'cpi_9606.ENSP00000287907'], ['f_412', 'cpi_9606.ENSP00000299855', 'cpi_9606.ENSP00000445340', 'cpi_9606.ENSP00000267101', 'f_644'], ['f_619', 'cpi_9606.ENSP00000286621', 'cpi_9606.ENSP00000248553', 'f_336', 'cpi_9606.ENSP00000386029'], ['f_710', 'cpi_9606.ENSP00000292147', 'cpi_9606.ENSP00000323568', 'cpi_9606.ENSP00000294728', 'f_480'], ['f_493', 'cpi_9606.ENSP00000276414', 'cpi_9606.ENSP00000263088', 'f_34', 'cpi_9606.ENSP00000293288'], ['f_243', 'cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000374467', 'f_822', 'cpi_9606.ENSP00000310928'], ['f_663', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000232219', 'f_467'], ['f_633', 'cpi_9606.ENSP00000362513', 'cpi_9606.ENSP00000361446', 'f_367', 'cpi_9606.ENSP00000349003'], ['f_657', 'cpi_9606.ENSP00000263269', 'cpi_9606.ENSP00000303325', 'f_740', 'f_423'], ['cpi_9606.ENSP00000418532', 'f_349', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000311028', 'cpi_9606.ENSP00000451030'], ['f_37', 'cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000349577', 'cpi_9606.ENSP00000255465', 'f_157'], ['f_430', 'cpi_9606.ENSP00000306817', 'cpi_9606.ENSP00000264657', 'f_514', 'cpi_9606.ENSP00000448059'], ['cpi_9606.ENSP00000270202', 'cpi_9606.ENSP00000471569', 'f_17', 'cpi_9606.ENSP00000328968', 'f_605'], ['f_286', 'cpi_9606.ENSP00000349595', 'cpi_9606.ENSP00000304915', 'cpi_9606.ENSP00000255030', 'f_721'], ['f_686', 'cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000296412', 'f_465', 'cpi_9606.ENSP00000372023'], ['f_377', 'cpi_9606.ENSP00000378323', 'f_610', 'cpi_9606.ENSP00000274547', 'cpi_9606.ENSP00000303452'], ['f_538', 'cpi_9606.ENSP00000211122', 'cpi_9606.ENSP00000260010', 'cpi_9606.ENSP00000287936', 'cpi_9606.ENSP00000303522'], ['f_602', 'cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000297268', 'f_784'], ['f_259', 'cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000370381', 'cpi_9606.ENSP00000354558', 'cpi_9606.ENSP00000307240'], ['cpi_9606.ENSP00000226730', 'f_713', 'cpi_9606.ENSP00000319814', 'f_759', 'cpi_9606.ENSP00000254976'], ['f_153', 'cpi_9606.ENSP00000296522', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000252029', 'f_805'], ['f_758', 'cpi_9606.ENSP00000361850', 'cpi_9606.ENSP00000379110', 'f_658', 'cpi_9606.ENSP00000295834'], ['f_636', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000263857', 'f_337', 'cpi_9606.ENSP00000304408'], ['f_560', 'cpi_9606.ENSP00000266682', 'cpi_9606.ENSP00000327850', 'cpi_9606.ENSP00000324248', 'f_705'], ['f_797', 'cpi_9606.ENSP00000261405', 'cpi_9606.ENSP00000225964', 'f_301', 'f_359'], ['cpi_9606.ENSP00000276198', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000276431', 'f_395', 'f_734'], ['f_193', 'cpi_9606.ENSP00000317842', 'cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000358784', 'f_378'], ['f_300', 'f_249', 'cpi_9606.ENSP00000304767', 'cpi_9606.ENSP00000362036', 'f_652'], ['f_418', 'cpi_9606.ENSP00000359998', 'cpi_9606.ENSP00000356213', 'cpi_9606.ENSP00000388648', 'f_700'], ['f_574', 'cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000302111', 'cpi_9606.ENSP00000359635', 'f_421'], ['f_199', 'cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000351885', 'f_457'], ['f_449', 'cpi_9606.ENSP00000217133', 'cpi_9606.ENSP00000303686', 'cpi_9606.ENSP00000325822', 'f_661'], ['f_548', 'cpi_9606.ENSP00000263212', 'cpi_9606.ENSP00000264867', 'f_397', 'f_305'], ['f_434', 'cpi_9606.ENSP00000276590', 'cpi_9606.ENSP00000388825', 'cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000299267'], ['f_755', 'cpi_9606.ENSP00000302846', 'cpi_9606.ENSP00000320935', 'cpi_9606.ENSP00000219919', 'f_621'], ['cpi_9606.ENSP00000295897', 'f_187', 'cpi_9606.ENSP00000263321', 'f_152', 'cpi_9606.ENSP00000362401'], ['cpi_9606.ENSP00000414303', 'f_459', 'cpi_9606.ENSP00000290349', 'cpi_9606.ENSP00000430432', 'f_13'], ['f_688', 'cpi_9606.ENSP00000282841', 'cpi_9606.ENSP00000371554', 'f_260', 'cpi_9606.ENSP00000318822'], ['f_476', 'cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000231449', 'f_24'], ['f_709', 'cpi_9606.ENSP00000314649', 'cpi_9606.ENSP00000356832', 'cpi_9606.ENSP00000263923', 'f_612'], ['f_519', 'cpi_9606.ENSP00000335620', 'cpi_9606.ENSP00000358511', 'cpi_9606.ENSP00000264896', 'f_711'], ['f_690', 'cpi_9606.ENSP00000260970', 'cpi_9606.ENSP00000364802', 'f_717', 'f_399'], ['f_450', 'cpi_9606.ENSP00000252321', 'cpi_9606.ENSP00000361151', 'cpi_9606.ENSP00000267377', 'f_819'], ['f_585', 'cpi_9606.ENSP00000418447', 'cpi_9606.ENSP00000325120', 'f_761', 'cpi_9606.ENSP00000365775'], ['f_800', 'cpi_9606.ENSP00000223095', 'cpi_9606.ENSP00000216540', 'f_38', 'cpi_9606.ENSP00000352608'], ['f_342', 'cpi_9606.ENSP00000411532', 'cpi_9606.ENSP00000365016', 'f_527', 'cpi_9606.ENSP00000350348'], ['cpi_9606.ENSP00000304845', 'cpi_9606.ENSP00000358963', 'cpi_9606.ENSP00000307014', 'cpi_9606.ENSP00000326219', 'f_780'], ['f_681', 'cpi_9606.ENSP00000360968', 'cpi_9606.ENSP00000262187', 'f_414', 'cpi_9606.ENSP00000255380'], ['f_356', 'cpi_9606.ENSP00000392262', 'cpi_9606.ENSP00000393333', 'cpi_9606.ENSP00000347979', 'cpi_9606.ENSP00000233242'], ['f_542', 'cpi_9606.ENSP00000248923', 'cpi_9606.ENSP00000216341', 'f_364', 'cpi_9606.ENSP00000329623'], ['f_385', 'cpi_9606.ENSP00000308541', 'cpi_9606.ENSP00000387699', 'f_624', 'cpi_9606.ENSP00000371985'], ['cpi_9606.ENSP00000355759', 'cpi_9606.ENSP00000234371', 'cpi_9606.ENSP00000376432', 'f_500', 'cpi_9606.ENSP00000260227'], ['f_665', 'cpi_9606.ENSP00000293190', 'cpi_9606.ENSP00000310305', 'f_563', 'cpi_9606.ENSP00000252945'], ['f_707', 'cpi_9606.ENSP00000346839', 'f_383', 

🔄 Processing features: 100%|██████████| 2147/2147 [10:20<00:00,  3.46feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'f_131', 'f_262', 'cpi_9606.ENSP00000428340', 'f_31'], ['cpi_9606.ENSP00000342007', 'f_347', 'f_773', 'cpi_9606.ENSP00000355629', 'f_587'], ['f_308', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000263377', 'f_616', 'cpi_9606.ENSP00000351957'], ['f_20', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000241453'], ['cpi_9606.ENSP00000353820', 'f_26', 'f_522', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000360773'], ['f_374', 'cpi_9606.ENSP00000362924', 'cpi_9606.ENSP00000285381', 'f_831', 'cpi_9606.ENSP00000286479'], ['f_391', 'cpi_9606.ENSP00000397026', 'cpi_9606.ENSP00000430684', 'f_428', 'cpi_9606.ENSP00000178638'], ['f_335', 'cpi_9606.ENSP00000358107', 'cpi_9606.ENSP00000357068', 'f_47', 'f_834'], ['cpi_9606.ENSP00000356438', 'f_213', 'f_510', 'cpi_9606.ENSP00000349320', 'f_706'], ['f_614', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000350928', 'f_413', 'f_789'], ['f_366', 'cpi_9606.ENSP00000306397', 'cpi_9606.ENSP00000279178', 'f_726', 'f_629'], ['f_392', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000357255', 'f_151', 'cpi_9606.ENSP00000277010'], ['f_338', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000342235'], ['f_405', 'cpi_9606.ENSP00000305742', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000395653', 'f_635'], ['f_146', 'cpi_9606.ENSP00000225927', 'cpi_9606.ENSP00000290349', 'f_529', 'cpi_9606.ENSP00000394936'], ['f_192', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000321584', 'cpi_9606.ENSP00000359353', 'f_845'], ['f_452', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000337773', 'f_25', 'cpi_9606.ENSP00000359100'], ['f_186', 'cpi_9606.ENSP00000279387', 'cpi_9606.ENSP00000359424', 'f_118', 'f_27'], ['f_346', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000302886', 'f_768', 'cpi_9606.ENSP00000409007'], ['f_566', 'cpi_9606.ENSP00000354476', 'cpi_9606.ENSP00000264426', 'f_836', 'cpi_9606.ENSP00000352900'], ['f_643', 'cpi_9606.ENSP00000354532', 'cpi_9606.ENSP00000377947', 'f_622', 'f_194'], ['f_185', 'cpi_9606.ENSP00000345096', 'cpi_9606.ENSP00000398632', 'f_292', 'cpi_9606.ENSP00000417229'], ['f_380', 'cpi_9606.ENSP00000381097', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000259396', 'cpi_9606.ENSP00000356094'], ['f_406', 'cpi_9606.ENSP00000358784', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000369375', 'f_526'], ['f_646', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000262160', 'f_866'], ['f_16', 'cpi_9606.ENSP00000343838', 'f_839', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000298472'], ['f_602', 'cpi_9606.ENSP00000304811', 'f_770', 'cpi_9606.ENSP00000331746', 'f_214'], ['f_341', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000273398', 'cpi_9606.ENSP00000216037', 'cpi_9606.ENSP00000312455'], ['f_579', 'cpi_9606.ENSP00000354193', 'f_328', 'cpi_9606.ENSP00000385026', 'f_830'], ['f_143', 'cpi_9606.ENSP00000313490', 'cpi_9606.ENSP00000304822', 'f_767', 'f_719'], ['f_712', 'f_533', 'cpi_9606.ENSP00000234310', 'cpi_9606.ENSP00000414334', 'cpi_9606.ENSP00000295454'], ['f_571', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000301891', 'cpi_9606.ENSP00000347942'], ['f_3', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000301634', 'f_511'], ['f_615', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000231228', 'f_771', 'cpi_9606.ENSP00000365663'], ['f_528', 'cpi_9606.ENSP00000362508', 'cpi_9606.ENSP00000308774', 'cpi_9606.ENSP00000262888', 'cpi_9606.ENSP00000367848'], ['f_617', 'cpi_9606.ENSP00000357615', 'cpi_9606.ENSP00000266376', 'cpi_9606.ENSP00000265294', 'f_820'], ['f_12', 'cpi_9606.ENSP00000268695', 'cpi_9606.ENSP00000351908', 'f_675', 'f_725'], ['f_697', 'cpi_9606.ENSP00000357669', 'cpi_9606.ENSP00000445340', 'f_788', 'f_749'], ['f_641', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000392262', 'cpi_9606.ENSP00000387946', 'f_202'], ['f_393', 'cpi_9606.ENSP00000287878', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000260191', 'f_497'], ['f_656', 'cpi_9606.ENSP00000286091', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000379086', 'cpi_9606.ENSP00000251535'], ['cpi_9606.ENSP00000354612', 'f_129', 'f_401', 'cpi_9606.ENSP00000283635', 'f_195'], ['f_365', 'cpi_9606.ENSP00000233944', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000326119'], ['f_659', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000332296', 'cpi_9606.ENSP00000389338'], ['f_299', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000374353', 'cpi_9606.ENSP00000470087', 'f_436'], ['f_443', 'cpi_9606.ENSP00000285900', 'cpi_9606.ENSP00000366662', 'f_297', 'cpi_9606.ENSP00000394932'], ['f_2', 'cpi_9606.ENSP00000297792', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000319788', 'cpi_9606.ENSP00000221972'], ['f_181', 'cpi_9606.ENSP00000370129', 'f_166', 'cpi_9606.ENSP00000314214', 'f_46'], ['f_339', 'cpi_9606.ENSP00000394033', 'f_799', 'f_330', 'cpi_9606.ENSP00000367102'], ['cpi_9606.ENSP00000367959', 'f_588', 'cpi_9606.ENSP00000301633', 'f_408', 'cpi_9606.ENSP00000372547'], ['f_683', 'cpi_9606.ENSP00000314649', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000368253', 'f_583'], ['f_698', 'cpi_9606.ENSP00000364709', 'f_388', 'cpi_9606.ENSP00000302111', 'f_729'], ['f_15', 'cpi_9606.ENSP00000320401', 'cpi_9606.ENSP00000361446', 'cpi_9606.ENSP00000378517', 'f_460'], ['f_440', 'cpi_9606.ENSP00000351209', 'cpi_9606.ENSP00000275300', 'f_791', 'f_813'], ['f_666', 'cpi_9606.ENSP00000332549', 'f_35', 'cpi_9606.ENSP00000349577', 'cpi_9606.ENSP00000337335'], ['cpi_9606.ENSP00000311032', 'cpi_9606.ENSP00000003100', 'f_207', 'f_43', 'f_394'], ['f_535', 'cpi_9606.ENSP00000225964', 'cpi_9606.ENSP00000253799', 'f_327', 'cpi_9606.ENSP00000388648'], ['f_451', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000264637', 'cpi_9606.ENSP00000292427'], ['f_569', 'cpi_9606.ENSP00000273550', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000451040', 'cpi_9606.ENSP00000352702'], ['f_432', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000328973', 'f_473', 'cpi_9606.ENSP00000360493'], ['f_340', 'cpi_9606.ENSP00000349576', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000362403', 'f_670'], ['f_345', 'cpi_9606.ENSP00000323867', 'cpi_9606.ENSP00000386171', 'cpi_9606.ENSP00000312664', 'f_505'], ['f_555', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000301645', 'f_782', 'cpi_9606.ENSP00000388825'], ['f_604', 'cpi_9606.ENSP00000279593', 'f_164', 'cpi_9606.ENSP00000258749', 'cpi_9606.ENSP00000356958'], ['f_645', 'cpi_9606.ENSP00000305302', 'cpi_9606.ENSP00000261196', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000367851'], ['f_692', 'cpi_9606.ENSP00000286621', 'cpi_9606.ENSP00000222256', 'f_474', 'f_509'], ['f_597', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000323549', 'f_167', 'cpi_9606.ENSP00000467676'], ['cpi_9606.ENSP00000328968', 'f_658', 'f_230', 'f_609', 'cpi_9606.ENSP00000457706'], ['f_594', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000216962', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000296871'], ['f_540', 'cpi_9606.ENSP00000352584', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000303248', 'cpi_9606.ENSP00000361359'], ['f_19', 'cpi_9606.ENSP00000472933', 'cpi_9606.ENSP00000333212', 'cpi_9606.ENSP00000286301', 'cpi_9606.ENSP00000222330'], ['f_439', 'cpi_9606.ENSP00000354107', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000295491', 'f_229'], ['f_639', 'f_778', 'cpi_9606.ENSP00000386306', 'f_508', 'cpi_9606.ENSP00000299178'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000261937', 'f_22', 'f_215'], ['f_680', 'cpi_9606.ENSP00000238018', 'cpi_9606.ENSP00000257290', 'cpi_9606.ENSP00000300061', 'cpi_9606.ENSP00000304915'], ['f_248', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000292513', 'f_455', 'f_676'], ['f_637', 'cpi_9606.ENSP00000376914', 'f_792', 'cpi_9606.ENSP00000297316', 'f_757'], ['f_257', 'cpi_9606.ENSP00000362513', 'cpi_9606.ENSP00000311028', 'cpi_9606.ENSP00000309493', 'cpi_9606.ENSP00000353292'], ['cpi_9606.ENSP00000265724', 'f_466', 'f_427', 'f_736', 'f_554'], ['cpi_9606.ENSP00000270349', 'f_132', 'f_398', 'f_812', 'f_407'], ['cpi_9606.ENSP00000360372', 'cpi_9606.ENSP00000296370', 'f_644', 'f_159', 'f_298'], ['f_180', 'cpi_9606.ENSP00000318822', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000321999', 'cpi_9606.ENSP00000242057'], ['cpi_9606.ENSP00000222982', 'f_543', 'f_715', 'cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000356150'], ['f_593', 'cpi_9606.ENSP00000353720', 'f_631', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000358548'], ['f_655', 'cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000362036', 'cpi_9606.ENSP00000357283', 'f_728'], ['f_684', 'cpi_9606.ENSP00000373674', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000282561', 'f_496'], ['f_691', 'cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000311095', 'f_483', 'f_417'], ['f_699', 'f_488', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000299267', 'f_350'], ['f_685', 'cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000331358', 'cpi_9606.ENSP00000222002'], ['f_390', 'cpi_9606.ENSP00000013034', 'cpi_9606.ENSP00000309649', 'f_764', 'cpi_9606.ENSP00000376943'], ['cpi_9606.ENSP00000337450', 'f_461', 'cpi_9606.ENSP00000302846', 'f_551', 'cpi_9606.ENSP00000362649'], ['f_145', 'cpi_9606.ENSP00000354511', 'f_827', 'cpi_9606.ENSP00000344192', 'cpi_9606.ENSP00000343040'], ['f_696', 'cpi_9606.ENSP00000314949', 'cpi_9606.ENSP00000270776', 'cpi_9606.ENSP00000301178', 'f_750'], ['f_553', 'cpi_9606.ENSP00000353791', 'cpi_9606.ENSP00000272847', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000343477'], ['f_682', 'cpi_9606.ENSP00000287936', 'cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000274545', 'f_361'], ['f_672', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000312673', 'cpi_9606.ENSP00000320935', 'cpi_9606.ENSP00000252723'], ['f_638', 'cpi_9606.ENSP00000225275', 'f_860', 'f_518', 'f_471'], ['f_333', 'cpi_9606.ENSP00000368349', 'cpi_9606.ENSP00000389414', 'cpi_9606.ENSP00000275525', 'f_722'], ['f_420', 'cpi_9606.ENSP00000312326', 'cpi_9606.ENSP00000252809', 'cpi_9606.ENSP00000261799', 'cpi_9606.ENSP00000261693'], ['f_241', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000344352', 'f_815'], ['f_695', 'cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000353427', 'cpi_9606.ENSP00000459962', 'f_785'], ['f_611', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000216911', 'cpi_9606.ENSP00000307599', 'f_568'], ['f_356', 'cpi_9606.ENSP00000371138', 'cpi_9606.ENSP00000341828', 'cpi_9606.ENSP00000262999', 'f_409'], ['f_244', 'cpi_9606.ENSP00000318585', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000361206', 'f_343'], ['f_293', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000358730', 'cpi_9606.ENSP00000259089', 'f_563'], ['f_464', 'cpi_9606.ENSP00000001008', 'cpi_9606.ENSP00000411658', 'cpi_9606.ENSP00000330393', 'f_448'], ['f_37', 'cpi_9606.ENSP00000400175', 'cpi_9606.ENSP00000354569', 'f_227', 'cpi_9606.ENSP00000255465'], ['f_663', 'cpi_9606.ENSP00000363868', 'f_216', 'cpi_9606.ENSP00000267101', 'f_477'], ['f_671', 'cpi_9606.ENSP00000266682', 'cpi_9606.ENSP00000348786', 'f_160', 'f_752'], ['f_21', 'cpi_9606.ENSP00000276198', 'f_494', 'cpi_9606.ENSP00000341045', 'cpi_9606.ENSP00000374323'], ['f_592', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000324105', 'cpi_9606.ENSP00000361666', 'f_653'], ['f_300', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000307014', 'cpi_9606.ENSP00000326219'], ['f_580', 'cpi_9606.ENSP00000375881', 'f_429', 'cpi_9606.ENSP00000390600', 'f_840'], ['f_353', 'cpi_9606.ENSP00000225474', 'cpi_9606.ENSP00000295256', 'cpi_9606.ENSP00000256958', 'cpi_9606.ENSP00000264318'], ['f_375', 'cpi_9606.ENSP00000385834', 'f_861', 'f_740', 'cpi_9606.ENSP00000348069'], ['f_704', 'cpi_9606.ENSP00000234389', 'cpi_9606.ENSP00000302811', 'f_475', 'cpi_9606.ENSP00000252486'], ['f_586', 'cpi_9606.ENSP00000358022', 'cpi_9606.ENSP00000358595', 'f_801', 'f_558'], ['f_667', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000222390'], ['f_581', 'cpi_9606.ENSP00000303174', 'cpi_9606.ENSP00000364805', 'cpi_9606.ENSP00000358963', 'f_513'], ['f_536', 'cpi_9606.ENSP00000293288', 'f_833', 'cpi_9606.ENSP00000427562', 'cpi_9606.ENSP00000262367'], ['f_337', 'cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000297350', 'cpi_9606.ENSP00000345659', 'f_650'], ['f_613', 'cpi_9606.ENSP00000368572', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000308165', 'f_763'], ['f_287', 'cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000312029', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000408860'], ['f_507', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000366307', 'cpi_9606.ENSP00000248553', 'cpi_9606.ENSP00000294954'], ['f_516', 'cpi_9606.ENSP00000362329', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000307235', 'f_486'], ['f_549', 'cpi_9606.ENSP00000216714', 'cpi_9606.ENSP00000356436', 'f_116', 'f_759'], ['f_412', 'f_826', 'cpi_9606.ENSP00000220809', 'cpi_9606.ENSP00000353878', 'cpi_9606.ENSP00000376776'], ['f_642', 'cpi_9606.ENSP00000285979', 'cpi_9606.ENSP00000256383', 'f_422', 'cpi_9606.ENSP00000303452'], ['f_623', 'f_411', 'cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000219919', 'cpi_9606.ENSP00000348827'], ['cpi_9606.ENSP00000418532', 'f_612', 'cpi_9606.ENSP00000340820', 'cpi_9606.ENSP00000323568', 'f_694'], ['cpi_9606.ENSP00000258743', 'f_454', 'cpi_9606.ENSP00000272167', 'f_738', 'f_34'], ['f_573', 'cpi_9606.ENSP00000244217', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000354394', 'f_647'], ['f_493', 'f_314', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000295400', 'cpi_9606.ENSP00000278175'], ['f_619', 'cpi_9606.ENSP00000364212', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000309124', 'f_419'], ['f_437', 'cpi_9606.ENSP00000337103', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000316786', 'f_610'], ['f_368', 'cpi_9606.ENSP00000305221', 'cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000220616', 'f_467'], ['f_33', 'cpi_9606.ENSP00000277541', 'cpi_9606.ENSP00000232219', 'f_115', 'f_625'], ['f_546', 'cpi_9606.ENSP00000293190', 'cpi_9606.ENSP00000343925', 'f_30', 'cpi_9606.ENSP00000309757'], ['f_689', 'cpi_9606.ENSP00000296411', 'cpi_9606.ENSP00000276449', 'cpi_9606.ENSP00000231454', 'f_359'], ['f_758', 'f_425', 'cpi_9606.ENSP00000335620', 'cpi_9606.ENSP00000264867', 'f_480'], ['f_243', 'f_242', 'cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000410076', 'cpi_9606.ENSP00000348645'], ['f_23', 'cpi_9606.ENSP00000363965', 'cpi_9606.ENSP00000335544', 'f_687', 'f_559'], ['f_199', 'cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000233242', 'f_421', 'f_515'], ['f_377', 'cpi_9606.ENSP00000332973', 'cpi_9606.ENSP00000297268', 'cpi_9606.ENSP00000356694', 'f_822'], ['f_153', 'cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000363804', 'f_465'], ['f_657', 'cpi_9606.ENSP00000227378', 'cpi_9606.ENSP00000356954', 'f_514', 'f_144'], ['f_150', 'cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000387683', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000255409'], ['f_686', 'f_489', 'cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000263321', 'cpi_9606.ENSP00000412673'], ['f_821', 'f_456', 'cpi_9606.ENSP00000327801', 'cpi_9606.ENSP00000226574', 'cpi_9606.ENSP00000260010'], ['f_188', 'cpi_9606.ENSP00000317842', 'cpi_9606.ENSP00000263126', 'cpi_9606.ENSP00000294728', 'f_157'], ['f_797', 'cpi_9606.ENSP00000261405', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000309572', 'f_414'], ['f_294', 'cpi_9606.ENSP00000417281', 'cpi_9606.ENSP00000466799', 'f_527', 'f_336'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000234961', 'cpi_9606.ENSP00000355778', 'f_363', 'cpi_9606.ENSP00000351885'], ['f_382', 'cpi_9606.ENSP00000370373', 'cpi_9606.ENSP00000274793', 'f_397', 'cpi_9606.ENSP00000325120'], ['f_679', 'cpi_9606.ENSP00000276590', 'cpi_9606.ENSP00000236671', 'f_423', 'f_721'], ['f_709', 'cpi_9606.ENSP00000364782', 'cpi_9606.ENSP00000329357', 'f_742', 'f_517'], ['f_193', 'cpi_9606.ENSP00000296522', 'cpi_9606.ENSP00000296122', 'cpi_9606.ENSP00000274547', 'f_500'], ['f_418', 'cpi_9606.ENSP00000347979', 'cpi_9606.ENSP00000340925', 'cpi_9606.ENSP00000370473', 'f_780'], ['f_673', 'cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000427514', 'cpi_9606.ENSP00000375809', 'f_200'], ['cpi_9606.ENSP00000272190', 'f_364', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000364802'], ['f_607', 'cpi_9606.ENSP00000418447', 'cpi_9606.ENSP00000260356', 'f_367', 'cpi_9606.ENSP00000331912'], ['cpi_9606.ENSP00000355759', 'cpi_9606.ENSP00000356825', 'cpi_9606.ENSP00000365016', 'f_17', 'cpi_9606.ENSP00000471569'], ['f_633', 'cpi_9606.ENSP00000176195', 'cpi_9606.ENSP00000332256', 'f_803', 'f_717'], ['f_560', 'cpi_9606.ENSP00000338627', 'cpi_9606.ENSP00000379330', 'f_705', 'cpi_9606.ENSP00000355317'], ['f_755', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000300738', 'cpi_9606.ENSP00000428924', 'f_395'], ['f_654', 'cpi_9606.ENSP00000330199', 'cpi_9606.ENSP00000218388', 'f_605', 'cpi_9606.ENSP00000265403'], ['f_599', 'cpi_9606.ENSP00000300093', 'cpi_9606.ENSP00000263980', 'f_805', 'cpi_9606.ENSP00000200676'], ['f_548', 'cpi_9606.ENSP00000399168', 'cpi_9606.ENSP00000231790', 'cpi_9606.ENSP00000296545', 'f_305'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000311165', 'f_652', 'cpi_9606.ENSP00000344674', 'f_661'], ['f_567', 'cpi_9606.ENSP00000368727', 'cpi_9606.ENSP00000211287', 'f_457', 'f_152'], ['f_442', 'cpi_9606.ENSP00000211122', 'cpi_9606.ENSP00000356671', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000338072'], ['f_708', 'cpi_9606.ENSP00000348775', 'cpi_9606.ENSP00000339527', 'cpi_9606.ENSP00000416293', 'f_301'], ['f_545', 'cpi_9606.ENSP00000345344', 'cpi_9606.ENSP00000309103', 'f_630', 'cpi_9606.ENSP00000310928'], ['f_690', 'cpi_9606.ENSP00000260970', 'cpi_9606.ENSP00000317379', 'cpi_9606.ENSP00000263464', 'f_399'], ['f_636', 'cpi_9606.ENSP00000254488', 'cpi_9606.ENSP00000463999', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000321106'], ['f_710', 'cpi_9606.ENSP00000164139', 'cpi_9606.ENSP00000346827', 'cpi_9606.ENSP00000329623', 'cpi_9606.ENSP00000370381'], ['f_498', 'cpi_9606.ENSP00000248923', 'cpi_9606.ENSP00000216341', 'f_24', 'cpi_9606.ENSP00000267843'], ['f_576', 'cpi_9606.ENSP00000374467', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000379213', 'f_38'], ['cpi_9606.ENSP00000295897', 'f_187', 'cpi_9606.ENSP00000302967', 'cpi_9606.ENSP00000338548', 'f_590'], ['f_574', 'cpi_9606.ENSP00000327255', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000320709', 'f_458'], ['f_502', 'cpi_9606.ENSP00000263212', 'f_575', 'f_711', 'cpi_9606.ENSP00000386229'], ['f_539', 'cpi_9606.ENSP00000241261', 'cpi_9606.ENSP00000337354', 'f_700', 'cpi_9606.ENSP00000308549'], ['f_702', 'cpi_9606.ENSP00000276431', 'cpi_9606.ENSP00000398655', 'f_531', 'cpi_9606.ENSP00000267377'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000315011', 'f_250', 'cpi_9606.ENSP00000341885', 'f_716'], ['f_352', 'cpi_9606.ENSP00000383365', 'cpi_9606.ENSP00000365380', 'cpi_9606.ENSP00000216797', 'f_260'], ['cpi_9606.ENSP00000270202', 'cpi_9606.ENSP00000346298', 'f_13', 'cpi_9606.ENSP00000303424', 'cpi_9606.ENSP00000300900'], ['f_776', 'cpi_9606.ENSP00000218548', 'cpi_9606.ENSP00000277120', 'f_532', 'f_707'], ['cpi_9606.ENSP00000262186', 'f_349', 'cpi_9606.ENSP00000225371', 'cpi_9606.ENSP00000352608', 'f_737'], ['f_450', 'cpi_9606.ENSP00000303211', 'f_249', 'cpi_9606.ENSP00000369654', 'cpi_9606.ENSP00000321988'], ['cpi_9606.ENSP00000464149', 'f_435', 'cpi_9606.ENSP00000228872', 'f_761', 'cpi_9606.ENSP00000350785'], ['f_628', 'cpi_9606.ENSP00000354871', 'cpi_9606.ENSP00000239938', 'f_334', 'cpi_9606.ENSP00000448059'], ['f_818', 'cpi_9606.ENSP00000262623', 'f_621', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000368752'], ['f_693', 'cpi_9606.ENSP00000340684', 'cpi_9606.ENSP00000369757', 'f_383', 'cpi_9606.ENSP00000234071'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000349252', 'f_591', 'cpi_9606.ENSP00000359532'], ['cpi_9606.ENSP00000354859', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000292095', 'f_734', 'cpi_9606.ENSP00000369816'], 

🔄 Processing features: 100%|██████████| 2147/2147 [10:20<00:00,  3.46feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'f_413', 'f_262', 'f_497', 'f_831'], ['f_366', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000324856', 'f_428', 'f_768'], ['f_374', 'cpi_9606.ENSP00000300738', 'cpi_9606.ENSP00000359424', 'f_771', 'f_789'], ['f_20', 'cpi_9606.ENSP00000352702', 'f_792', 'cpi_9606.ENSP00000369530', 'f_629'], ['cpi_9606.ENSP00000353820', 'f_131', 'cpi_9606.ENSP00000257290', 'f_292', 'cpi_9606.ENSP00000352011'], ['f_308', 'cpi_9606.ENSP00000355192', 'f_616', 'cpi_9606.ENSP00000394936', 'cpi_9606.ENSP00000402152'], ['f_535', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000305692', 'f_31', 'f_328'], ['f_346', 'cpi_9606.ENSP00000279178', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000395653', 'cpi_9606.ENSP00000220616'], ['f_391', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000313490', 'f_845', 'cpi_9606.ENSP00000304822'], ['f_338', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000321584', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000359353'], ['f_643', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000297268', 'f_151'], ['f_335', 'f_813', 'cpi_9606.ENSP00000358107', 'f_47', 'cpi_9606.ENSP00000265294'], ['f_146', 'f_773', 'cpi_9606.ENSP00000277541', 'cpi_9606.ENSP00000274793', 'f_27'], ['f_12', 'cpi_9606.ENSP00000332549', 'f_635', 'f_726', 'cpi_9606.ENSP00000333212'], ['f_440', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000378517', 'f_25'], ['f_186', 'cpi_9606.ENSP00000279387', 'f_436', 'f_118', 'cpi_9606.ENSP00000430684'], ['f_380', 'cpi_9606.ENSP00000337773', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000342235', 'cpi_9606.ENSP00000299847'], ['f_617', 'cpi_9606.ENSP00000394033', 'cpi_9606.ENSP00000374323', 'cpi_9606.ENSP00000367848', 'f_529'], ['cpi_9606.ENSP00000356438', 'f_213', 'f_408', 'f_510', 'f_706'], ['f_406', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000261799'], ['f_569', 'cpi_9606.ENSP00000305221', 'cpi_9606.ENSP00000355629', 'cpi_9606.ENSP00000341390', 'f_214'], ['f_611', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000451040', 'cpi_9606.ENSP00000332296', 'f_725'], ['f_451', 'cpi_9606.ENSP00000354107', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000254066', 'f_43'], ['f_571', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000301891', 'cpi_9606.ENSP00000353362', 'f_736'], ['f_405', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000220003', 'cpi_9606.ENSP00000295454', 'cpi_9606.ENSP00000316786'], ['f_528', 'cpi_9606.ENSP00000362508', 'cpi_9606.ENSP00000291700', 'f_820', 'cpi_9606.ENSP00000295452'], ['f_659', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000370254', 'f_526', 'f_866'], ['f_439', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000348786', 'cpi_9606.ENSP00000264637', 'f_622'], ['f_566', 'cpi_9606.ENSP00000357669', 'cpi_9606.ENSP00000354476', 'f_836', 'cpi_9606.ENSP00000377947'], ['f_588', 'cpi_9606.ENSP00000328968', 'f_230', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000223095'], ['f_185', 'cpi_9606.ENSP00000349576', 'cpi_9606.ENSP00000309493', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000252809'], ['f_341', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000273398', 'f_834', 'f_757'], ['f_192', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000345096', 'f_298', 'cpi_9606.ENSP00000344192'], ['cpi_9606.ENSP00000311032', 'f_518', 'f_587', 'cpi_9606.ENSP00000356094', 'f_207'], ['f_579', 'cpi_9606.ENSP00000354193', 'cpi_9606.ENSP00000471569', 'f_788', 'cpi_9606.ENSP00000360773'], ['f_672', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000327255', 'cpi_9606.ENSP00000319788', 'f_167'], ['f_180', 'cpi_9606.ENSP00000273550', 'cpi_9606.ENSP00000263126', 'f_46', 'cpi_9606.ENSP00000221972'], ['f_16', 'cpi_9606.ENSP00000360608', 'f_242', 'f_830', 'f_719'], ['cpi_9606.ENSP00000270349', 'f_515', 'f_194', 'cpi_9606.ENSP00000367102', 'f_767'], ['f_697', 'cpi_9606.ENSP00000314508', 'cpi_9606.ENSP00000414334', 'f_511', 'cpi_9606.ENSP00000248076'], ['f_553', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000263431', 'f_297', 'f_166'], ['f_656', 'cpi_9606.ENSP00000323867', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000366307', 'cpi_9606.ENSP00000312664'], ['f_145', 'cpi_9606.ENSP00000335620', 'cpi_9606.ENSP00000352900', 'f_631', 'f_350'], ['f_580', 'cpi_9606.ENSP00000295453', 'cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000457706', 'f_361'], ['f_143', 'cpi_9606.ENSP00000225927', 'cpi_9606.ENSP00000222330', 'cpi_9606.ENSP00000256383', 'cpi_9606.ENSP00000274545'], ['f_299', 'cpi_9606.ENSP00000306397', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000277010', 'f_202'], ['f_293', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000283635', 'cpi_9606.ENSP00000314949', 'cpi_9606.ENSP00000312455'], ['f_393', 'cpi_9606.ENSP00000287878', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000335511', 'f_583'], ['f_645', 'cpi_9606.ENSP00000254488', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000245539', 'f_229'], ['f_638', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000360493', 'f_749'], ['f_594', 'cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000222256', 'f_35', 'cpi_9606.ENSP00000387946'], ['f_339', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000272167', 'f_799', 'f_429'], ['f_2', 'cpi_9606.ENSP00000262290', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000470087', 'f_330'], ['f_493', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000299267', 'cpi_9606.ENSP00000361206'], ['f_602', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000353915', 'cpi_9606.ENSP00000266376', 'cpi_9606.ENSP00000323568'], ['f_637', 'cpi_9606.ENSP00000261755', 'f_729', 'cpi_9606.ENSP00000344352', 'f_466'], ['f_597', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000221421', 'f_407', 'cpi_9606.ENSP00000467676'], ['f_432', 'cpi_9606.ENSP00000363868', 'cpi_9606.ENSP00000369375', 'f_159', 'f_609'], ['f_614', 'cpi_9606.ENSP00000305742', 'cpi_9606.ENSP00000337335', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000286301'], ['cpi_9606.ENSP00000342007', 'f_347', 'cpi_9606.ENSP00000216037', 'cpi_9606.ENSP00000384957', 'f_554'], ['f_181', 'cpi_9606.ENSP00000370129', 'cpi_9606.ENSP00000314214', 'f_785', 'cpi_9606.ENSP00000262999'], ['f_452', 'cpi_9606.ENSP00000351209', 'cpi_9606.ENSP00000419782', 'f_722', 'cpi_9606.ENSP00000398632'], ['cpi_9606.ENSP00000265724', 'f_401', 'f_427', 'f_505', 'f_448'], ['f_646', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000261196', 'cpi_9606.ENSP00000294728'], ['f_682', 'f_778', 'cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000296871', 'cpi_9606.ENSP00000365686'], ['cpi_9606.ENSP00000283916', 'f_388', 'cpi_9606.ENSP00000311165', 'f_509', 'f_394'], ['f_696', 'cpi_9606.ENSP00000364782', 'f_474', 'cpi_9606.ENSP00000389338', 'cpi_9606.ENSP00000261937'], ['cpi_9606.ENSP00000263817', 'f_115', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000286648', 'f_568'], ['f_420', 'cpi_9606.ENSP00000312326', 'f_327', 'cpi_9606.ENSP00000343477', 'f_764'], ['f_536', 'cpi_9606.ENSP00000321106', 'f_770', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000368104'], ['f_3', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000225371', 'cpi_9606.ENSP00000347942', 'f_676'], ['f_392', 'cpi_9606.ENSP00000368349', 'cpi_9606.ENSP00000292427', 'f_460', 'cpi_9606.ENSP00000361359'], ['cpi_9606.ENSP00000360372', 'f_132', 'f_26', 'f_812', 'cpi_9606.ENSP00000307014'], ['f_683', 'cpi_9606.ENSP00000314649', 'cpi_9606.ENSP00000240652', 'cpi_9606.ENSP00000354394', 'f_827'], ['f_667', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000381097', 'f_343', 'f_715'], ['f_257', 'cpi_9606.ENSP00000234310', 'f_861', 'cpi_9606.ENSP00000233146', 'cpi_9606.ENSP00000225474'], ['f_353', 'cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000253004', 'f_826', 'f_675'], ['f_671', 'cpi_9606.ENSP00000266682', 'cpi_9606.ENSP00000327850', 'f_670', 'f_164'], ['f_540', 'cpi_9606.ENSP00000352584', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000303248', 'cpi_9606.ENSP00000417229'], ['f_712', 'cpi_9606.ENSP00000218548', 'f_750', 'cpi_9606.ENSP00000427514', 'f_508'], ['f_680', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000306100', 'cpi_9606.ENSP00000365016', 'cpi_9606.ENSP00000326119'], ['cpi_9606.ENSP00000337450', 'f_543', 'f_160', 'cpi_9606.ENSP00000311028', 'cpi_9606.ENSP00000292513'], ['f_443', 'cpi_9606.ENSP00000223366', 'cpi_9606.ENSP00000334105', 'f_815', 'cpi_9606.ENSP00000329357'], ['cpi_9606.ENSP00000260682', 'f_22', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000259089', 'f_129'], ['f_345', 'cpi_9606.ENSP00000233944', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000361666'], ['f_37', 'cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000256958', 'f_475', 'f_417'], ['f_639', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000355920', 'cpi_9606.ENSP00000262367', 'f_215'], ['f_684', 'cpi_9606.ENSP00000295400', 'cpi_9606.ENSP00000259271', 'f_473', 'cpi_9606.ENSP00000258749'], ['cpi_9606.ENSP00000367959', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000267101', 'f_644', 'f_195'], ['f_613', 'cpi_9606.ENSP00000362924', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000285381', 'f_551'], ['f_592', 'cpi_9606.ENSP00000238018', 'cpi_9606.ENSP00000309124', 'cpi_9606.ENSP00000367851', 'f_409'], ['f_685', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000298472'], ['cpi_9606.ENSP00000258743', 'f_454', 'cpi_9606.ENSP00000264818', 'cpi_9606.ENSP00000322617', 'f_653'], ['f_33', 'cpi_9606.ENSP00000301633', 'cpi_9606.ENSP00000234961', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000275525'], ['f_698', 'cpi_9606.ENSP00000364709', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000343040', 'f_419'], ['cpi_9606.ENSP00000270202', 'f_455', 'cpi_9606.ENSP00000370381', 'f_17', 'f_216'], ['cpi_9606.ENSP00000222982', 'f_763', 'cpi_9606.ENSP00000244217', 'f_34', 'cpi_9606.ENSP00000376776'], ['f_593', 'cpi_9606.ENSP00000303540', 'f_840', 'cpi_9606.ENSP00000309103', 'cpi_9606.ENSP00000262888'], ['f_586', 'cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000248553', 'f_801', 'cpi_9606.ENSP00000370473'], ['f_573', 'cpi_9606.ENSP00000297792', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000301178', 'f_650'], ['f_464', 'cpi_9606.ENSP00000236671', 'cpi_9606.ENSP00000443459', 'cpi_9606.ENSP00000376943', 'f_752'], ['f_507', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000307599', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000358730'], ['f_642', 'cpi_9606.ENSP00000285979', 'cpi_9606.ENSP00000364805', 'f_486', 'cpi_9606.ENSP00000303452'], ['f_227', 'cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000376178', 'f_694', 'cpi_9606.ENSP00000445340'], ['f_615', 'cpi_9606.ENSP00000225275', 'f_839', 'f_833', 'cpi_9606.ENSP00000358548'], ['f_19', 'cpi_9606.ENSP00000472933', 'cpi_9606.ENSP00000232219', 'f_496', 'f_471'], ['f_516', 'cpi_9606.ENSP00000330484', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000353292', 'f_782'], ['f_628', 'cpi_9606.ENSP00000216714', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000251535', 'f_558'], ['f_560', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000341885', 'cpi_9606.ENSP00000300061'], ['f_623', 'f_456', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000304915'], ['f_340', 'cpi_9606.ENSP00000234590', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000416293', 'f_740'], ['f_15', 'cpi_9606.ENSP00000320401', 'cpi_9606.ENSP00000343392', 'f_116', 'f_728'], ['f_199', 'cpi_9606.ENSP00000354612', 'f_522', 'cpi_9606.ENSP00000348069', 'cpi_9606.ENSP00000348897'], ['f_377', 'cpi_9606.ENSP00000279593', 'cpi_9606.ENSP00000312029', 'cpi_9606.ENSP00000389414', 'f_461'], ['f_548', 'cpi_9606.ENSP00000296522', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000308165'], ['f_619', 'cpi_9606.ENSP00000399168', 'cpi_9606.ENSP00000331912', 'cpi_9606.ENSP00000346598', 'cpi_9606.ENSP00000252723'], ['f_244', 'cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000311095', 'f_738', 'cpi_9606.ENSP00000348827'], ['f_691', 'cpi_9606.ENSP00000276431', 'cpi_9606.ENSP00000260010', 'f_513', 'cpi_9606.ENSP00000274547'], ['cpi_9606.ENSP00000261707', 'f_300', 'cpi_9606.ENSP00000262160', 'cpi_9606.ENSP00000295491', 'f_200'], ['f_390', 'cpi_9606.ENSP00000274606', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000357283', 'f_791'], ['f_365', 'cpi_9606.ENSP00000362441', 'cpi_9606.ENSP00000335560', 'cpi_9606.ENSP00000293288', 'f_717'], ['f_689', 'cpi_9606.ENSP00000354532', 'f_647', 'f_477', 'cpi_9606.ENSP00000231454'], ['f_692', 'cpi_9606.ENSP00000286621', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000226574', 'f_742'], ['cpi_9606.ENSP00000330237', 'f_517', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000349577', 'f_652'], ['f_150', 'cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000366084', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000386029'], ['f_658', 'cpi_9606.ENSP00000418532', 'f_398', 'cpi_9606.ENSP00000231228', 'cpi_9606.ENSP00000353427'], ['f_368', 'cpi_9606.ENSP00000349467', 'cpi_9606.ENSP00000260356', 'f_467', 'cpi_9606.ENSP00000346148'], ['f_695', 'cpi_9606.ENSP00000308032', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000365663', 'cpi_9606.ENSP00000366506'], ['f_153', 'cpi_9606.ENSP00000261405', 'cpi_9606.ENSP00000282561', 'cpi_9606.ENSP00000410076', 'f_336'], ['f_449', 'cpi_9606.ENSP00000397026', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000242057', 'f_367'], ['f_681', 'cpi_9606.ENSP00000360968', 'cpi_9606.ENSP00000344674', 'f_465', 'cpi_9606.ENSP00000216962'], ['f_666', 'cpi_9606.ENSP00000312673', 'cpi_9606.ENSP00000280357', 'cpi_9606.ENSP00000356954', 'f_483'], ['f_581', 'cpi_9606.ENSP00000256119', 'f_494', 'cpi_9606.ENSP00000355317', 'cpi_9606.ENSP00000259396'], ['f_641', 'cpi_9606.ENSP00000240139', 'cpi_9606.ENSP00000267843', 'f_422', 'f_30'], ['f_498', 'cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000356958', 'f_533'], ['f_241', 'cpi_9606.ENSP00000374467', 'cpi_9606.ENSP00000353878', 'cpi_9606.ENSP00000261693', 'f_423'], ['f_758', 'f_425', 'cpi_9606.ENSP00000001008', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000428824'], ['f_818', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000288602', 'f_395', 'cpi_9606.ENSP00000339527'], ['f_21', 'cpi_9606.ENSP00000327652', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000263377', 'f_721'], ['f_567', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000332369', 'cpi_9606.ENSP00000317379', 'f_759'], ['f_702', 'cpi_9606.ENSP00000252321', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000310928', 'f_822'], ['f_704', 'cpi_9606.ENSP00000441691', 'cpi_9606.ENSP00000355778', 'cpi_9606.ENSP00000276449', 'f_480'], ['f_248', 'cpi_9606.ENSP00000337103', 'cpi_9606.ENSP00000218721', 'cpi_9606.ENSP00000318822', 'f_488'], ['f_437', 'cpi_9606.ENSP00000265403', 'cpi_9606.ENSP00000351908', 'cpi_9606.ENSP00000428340', 'f_314'], ['f_821', 'f_411', 'cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000200676', 'cpi_9606.ENSP00000308845'], ['f_699', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000216392', 'f_359', 'cpi_9606.ENSP00000255465'], ['f_709', 'cpi_9606.ENSP00000306817', 'cpi_9606.ENSP00000239938', 'f_559', 'f_363'], ['f_375', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000333496', 'cpi_9606.ENSP00000255409', 'f_605'], ['cpi_9606.ENSP00000219833', 'f_673', 'cpi_9606.ENSP00000340820', 'cpi_9606.ENSP00000341045', 'cpi_9606.ENSP00000320935'], ['f_352', 'cpi_9606.ENSP00000383365', 'cpi_9606.ENSP00000365380', 'f_780', 'f_625'], ['f_333', 'cpi_9606.ENSP00000358042', 'cpi_9606.ENSP00000264657', 'f_514', 'cpi_9606.ENSP00000225964'], ['f_193', 'cpi_9606.ENSP00000304767', 'cpi_9606.ENSP00000364802', 'f_301', 'cpi_9606.ENSP00000359096'], ['f_655', 'cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000362036', 'f_397', 'cpi_9606.ENSP00000340691'], ['f_287', 'cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000351885', 'f_489'], ['cpi_9606.ENSP00000272190', 'f_610', 'cpi_9606.ENSP00000233242', 'cpi_9606.ENSP00000254810', 'f_399'], ['f_555', 'cpi_9606.ENSP00000263269', 'f_860', 'f_803', 'cpi_9606.ENSP00000296122'], ['f_442', 'cpi_9606.ENSP00000378306', 'cpi_9606.ENSP00000297350', 'f_575', 'f_711'], ['f_243', 'cpi_9606.ENSP00000239223', 'cpi_9606.ENSP00000262461', 'f_38', 'cpi_9606.ENSP00000255380'], ['f_797', 'cpi_9606.ENSP00000262623', 'cpi_9606.ENSP00000302111', 'f_621', 'cpi_9606.ENSP00000252486'], ['f_546', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000356213', 'cpi_9606.ENSP00000364310', 'f_337'], ['f_542', 'cpi_9606.ENSP00000219240', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000336630', 'f_421'], ['f_502', 'cpi_9606.ENSP00000307900', 'f_563', 'cpi_9606.ENSP00000267119', 'cpi_9606.ENSP00000293330'], ['f_286', 'cpi_9606.ENSP00000343885', 'cpi_9606.ENSP00000216797', 'f_805', 'cpi_9606.ENSP00000322924'], ['f_537', 'f_624', 'cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000385806', 'cpi_9606.ENSP00000294954'], ['cpi_9606.ENSP00000262186', 'f_349', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000365775', 'f_144'], ['f_523', 'cpi_9606.ENSP00000305302', 'cpi_9606.ENSP00000379330', 'cpi_9606.ENSP00000285930', 'f_705'], ['f_686', 'cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000262187', 'f_378', 'cpi_9606.ENSP00000325822'], ['f_574', 'cpi_9606.ENSP00000386284', 'cpi_9606.ENSP00000339299', 'cpi_9606.ENSP00000351273', 'f_305'], ['f_604', 'cpi_9606.ENSP00000331514', 'cpi_9606.ENSP00000300900', 'f_157', 'cpi_9606.ENSP00000325120'], ['f_294', 'cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000387683', 'cpi_9606.ENSP00000430432', 'cpi_9606.ENSP00000388648'], ['f_800', 'cpi_9606.ENSP00000220809', 'cpi_9606.ENSP00000332116', 'f_206', 'f_364'], ['cpi_9606.ENSP00000414303', 'f_187', 'cpi_9606.ENSP00000355533', 'f_687', 'cpi_9606.ENSP00000330393'], ['f_495', 'cpi_9606.ENSP00000264426', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000291294', 'f_661'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000292896', 'f_500', 'cpi_9606.ENSP00000263321', 'f_734'], ['f_538', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000368880', 'cpi_9606.ENSP00000217305', 'f_24'], ['f_418', 'cpi_9606.ENSP00000359998', 'cpi_9606.ENSP00000386171', 'cpi_9606.ENSP00000264498', 'f_630'], ['f_663', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000236850', 'f_414', 'cpi_9606.ENSP00000338072'], ['f_370', 'cpi_9606.ENSP00000263212', 'f_784', 'cpi_9606.ENSP00000358784', 'cpi_9606.ENSP00000400175'], ['f_430', 'cpi_9606.ENSP00000322991', 'cpi_9606.ENSP00000354558', 'f_260', 'cpi_9606.ENSP00000293745'], ['f_755', 'cpi_9606.ENSP00000378323', 'f_601', 'cpi_9606.ENSP00000301141', 'cpi_9606.ENSP00000331358'], ['f_412', 'cpi_9606.ENSP00000417281', 'cpi_9606.ENSP00000267377', 'cpi_9606.ENSP00000466799', 'f_707'], ['f_577', 'cpi_9606.ENSP00000331746', 'cpi_9606.ENSP00000362513', 'cpi_9606.ENSP00000292095', 'f_462'], ['f_654', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000295731', 'cpi_9606.ENSP00000319984', 'f_249'], ['f_453', 'cpi_9606.ENSP00000330199', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000356150', 'f_761'], ['f_259', 'cpi_9606.ENSP00000318585', 'cpi_9606.ENSP00000387699', 'cpi_9606.ENSP00000380252', 'cpi_9606.ENSP00000306490'], ['cpi_9606.ENSP00000295897', 'f_386', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000263980', 'cpi_9606.ENSP00000387888'], ['cpi_9606.ENSP00000355759', 'cpi_9606.ENSP00000226413', 'cpi_9606.ENSP00000402608', 'f_383', 'f_703'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000394932', 'f_716', 'cpi_9606.ENSP00000176195', 'f_188'], ['f_708', 'cpi_9606.ENSP00000292147', 'cpi_9606.ENSP00000262735', 'f_612', 'cpi_9606.ENSP00000307235'], ['f_798', 'cpi_9606.ENSP00000318912', 'f_485', 'cpi_9606.ENSP00000264867', 'cpi_9606.ENSP00000355657'], ['f_776', 'cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000264896', 'cpi_9606.ENSP00000362649', 'f_457'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000252804', 'f_152', 'cpi_9606.ENSP00000352608'], ['f_545', 'cpi_9606.ENSP00000345344', 'cpi_9606.ENSP00000295834', 'cpi_9606.ENSP00000303522', 'f_700'], ['f_633', 'cpi_9606.ENSP00000268695', 'cpi_9606.ENSP00000231449', 'cpi_9606.ENSP00000308774', 'f_544'], ['cpi_9606.ENSP00000304845', 'cpi_9606.ENSP00000176183', 'cpi_9606.ENSP00000326219', 'f_458', 'cpi_9606.ENSP00000218388']

🔄 Processing features: 100%|██████████| 2147/2147 [10:21<00:00,  3.46feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'cpi_9606.ENSP00000357669', 'f_413', 'f_408', 'f_831'], ['cpi_9606.ENSP00000356438', 'f_131', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000349320', 'f_115'], ['cpi_9606.ENSP00000328968', 'f_588', 'f_230', 'cpi_9606.ENSP00000350616', 'f_17'], ['f_366', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000412673'], ['f_643', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000283646', 'cpi_9606.ENSP00000354476'], ['cpi_9606.ENSP00000353820', 'f_26', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000360773', 'cpi_9606.ENSP00000335592'], ['f_143', 'cpi_9606.ENSP00000430684', 'cpi_9606.ENSP00000225927', 'f_726', 'cpi_9606.ENSP00000363018'], ['f_391', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000256383', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000411593'], ['f_346', 'cpi_9606.ENSP00000279178', 'f_629', 'cpi_9606.ENSP00000395653', 'cpi_9606.ENSP00000376432'], ['f_405', 'cpi_9606.ENSP00000306397', 'cpi_9606.ENSP00000295452', 'f_789', 'cpi_9606.ENSP00000350767'], ['cpi_9606.ENSP00000354612', 'f_132', 'cpi_9606.ENSP00000262186', 'f_522', 'f_292'], ['f_20', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000295454', 'cpi_9606.ENSP00000219240'], ['f_617', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000359334'], ['f_335', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000394033', 'f_47', 'cpi_9606.ENSP00000337773'], ['f_646', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000345096', 'f_836', 'cpi_9606.ENSP00000291700'], ['f_374', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000258662', 'cpi_9606.ENSP00000445340', 'cpi_9606.ENSP00000370381'], ['f_614', 'cpi_9606.ENSP00000305742', 'cpi_9606.ENSP00000333212', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000270570'], ['f_186', 'cpi_9606.ENSP00000279387', 'f_31', 'cpi_9606.ENSP00000365775', 'f_845'], ['f_3', 'cpi_9606.ENSP00000307599', 'cpi_9606.ENSP00000321584', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000347942'], ['f_645', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000377947'], ['f_380', 'cpi_9606.ENSP00000381097', 'cpi_9606.ENSP00000353292', 'cpi_9606.ENSP00000259396', 'cpi_9606.ENSP00000285381'], ['f_308', 'cpi_9606.ENSP00000355192', 'f_616', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000300061'], ['cpi_9606.ENSP00000367959', 'f_129', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000427562', 'f_25'], ['f_440', 'cpi_9606.ENSP00000358107', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000378517', 'cpi_9606.ENSP00000333496'], ['f_528', 'cpi_9606.ENSP00000220003', 'cpi_9606.ENSP00000263126', 'f_866', 'cpi_9606.ENSP00000319788'], ['f_638', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000297350', 'cpi_9606.ENSP00000371985'], ['cpi_9606.ENSP00000260682', 'f_749', 'f_22', 'f_635', 'cpi_9606.ENSP00000293745'], ['f_146', 'cpi_9606.ENSP00000277541', 'f_529', 'cpi_9606.ENSP00000297792', 'cpi_9606.ENSP00000394936'], ['f_338', 'cpi_9606.ENSP00000245457', 'cpi_9606.ENSP00000257290', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000274545'], ['f_180', 'cpi_9606.ENSP00000273550', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000356094', 'cpi_9606.ENSP00000301891'], ['f_185', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000355657', 'cpi_9606.ENSP00000364802', 'cpi_9606.ENSP00000323568'], ['f_15', 'cpi_9606.ENSP00000320401', 'cpi_9606.ENSP00000286091', 'cpi_9606.ENSP00000339027', 'f_428'], ['f_451', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000264162'], ['f_656', 'cpi_9606.ENSP00000323867', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000309493', 'f_151'], ['f_406', 'cpi_9606.ENSP00000352035', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000374323', 'cpi_9606.ENSP00000385026'], ['f_393', 'cpi_9606.ENSP00000338160', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000362441', 'cpi_9606.ENSP00000355629'], ['f_566', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000354193', 'f_526', 'f_328'], ['f_682', 'cpi_9606.ENSP00000363868', 'cpi_9606.ENSP00000334198', 'f_839', 'cpi_9606.ENSP00000360967'], ['f_697', 'cpi_9606.ENSP00000414334', 'f_511', 'cpi_9606.ENSP00000314649', 'cpi_9606.ENSP00000248076'], ['f_666', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000350928', 'cpi_9606.ENSP00000359635', 'cpi_9606.ENSP00000252723'], ['f_392', 'cpi_9606.ENSP00000364212', 'cpi_9606.ENSP00000367851', 'cpi_9606.ENSP00000316786', 'f_510'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000464149', 'f_417', 'f_706', 'f_773'], ['f_452', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000233146', 'cpi_9606.ENSP00000365663', 'f_330'], ['f_571', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000252809', 'f_799'], ['f_145', 'cpi_9606.ENSP00000341045', 'cpi_9606.ENSP00000290349', 'cpi_9606.ENSP00000262461', 'cpi_9606.ENSP00000220616'], ['f_339', 'f_715', 'f_676', 'cpi_9606.ENSP00000332369', 'f_736'], ['f_12', 'cpi_9606.ENSP00000349576', 'cpi_9606.ENSP00000262545', 'cpi_9606.ENSP00000283254', 'f_768'], ['f_181', 'cpi_9606.ENSP00000370129', 'cpi_9606.ENSP00000306100', 'f_166', 'cpi_9606.ENSP00000353791'], ['f_299', 'cpi_9606.ENSP00000233944', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000200676', 'cpi_9606.ENSP00000331912'], ['cpi_9606.ENSP00000311032', 'f_587', 'f_167', 'cpi_9606.ENSP00000367848', 'cpi_9606.ENSP00000344674'], ['f_615', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000231228', 'cpi_9606.ENSP00000254488', 'cpi_9606.ENSP00000286479'], ['f_535', 'cpi_9606.ENSP00000376914', 'cpi_9606.ENSP00000354107', 'f_327', 'cpi_9606.ENSP00000409007'], ['f_2', 'cpi_9606.ENSP00000286621', 'cpi_9606.ENSP00000471569', 'cpi_9606.ENSP00000448059', 'cpi_9606.ENSP00000226574'], ['f_345', 'cpi_9606.ENSP00000287878', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000296370'], ['f_432', 'cpi_9606.ENSP00000353720', 'f_473', 'cpi_9606.ENSP00000330199', 'f_729'], ['cpi_9606.ENSP00000337450', 'f_34', 'cpi_9606.ENSP00000302846', 'f_763', 'f_505'], ['f_684', 'cpi_9606.ENSP00000295400', 'cpi_9606.ENSP00000238018', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000253122'], ['f_659', 'cpi_9606.ENSP00000314949', 'cpi_9606.ENSP00000305302', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000276431'], ['f_439', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000352516', 'cpi_9606.ENSP00000298472', 'f_118'], ['f_569', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000217133', 'cpi_9606.ENSP00000402152', 'f_350'], ['f_712', 'cpi_9606.ENSP00000218548', 'f_830', 'f_834', 'f_35'], ['f_613', 'cpi_9606.ENSP00000362924', 'cpi_9606.ENSP00000264637', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000312455'], ['f_213', 'cpi_9606.ENSP00000293288', 'f_336', 'f_778', 'f_361'], ['f_540', 'cpi_9606.ENSP00000430031', 'cpi_9606.ENSP00000221972', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000309124'], ['cpi_9606.ENSP00000270349', 'f_401', 'cpi_9606.ENSP00000301633', 'f_422', 'f_687'], ['f_257', 'cpi_9606.ENSP00000234310', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000470087', 'cpi_9606.ENSP00000389338'], ['f_340', 'cpi_9606.ENSP00000357336', 'cpi_9606.ENSP00000373477', 'cpi_9606.ENSP00000427514', 'cpi_9606.ENSP00000346298'], ['f_16', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000366307', 'cpi_9606.ENSP00000222256', 'f_214'], ['f_553', 'cpi_9606.ENSP00000266682', 'cpi_9606.ENSP00000418447', 'cpi_9606.ENSP00000299267', 'f_752'], ['f_685', 'cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000305221', 'f_343', 'cpi_9606.ENSP00000307240'], ['f_672', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000459962', 'f_767', 'cpi_9606.ENSP00000348897'], ['f_192', 'cpi_9606.ENSP00000262623', 'cpi_9606.ENSP00000274547', 'cpi_9606.ENSP00000330393', 'cpi_9606.ENSP00000390600'], ['f_365', 'cpi_9606.ENSP00000226578', 'cpi_9606.ENSP00000387946', 'cpi_9606.ENSP00000318822', 'f_764'], ['f_623', 'f_30', 'cpi_9606.ENSP00000275525', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000291295'], ['cpi_9606.ENSP00000360372', 'f_644', 'f_508', 'f_200', 'cpi_9606.ENSP00000261693'], ['f_464', 'cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000258749', 'f_27'], ['f_597', 'cpi_9606.ENSP00000312673', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000338627', 'f_164'], ['f_248', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000292513', 'cpi_9606.ENSP00000356729', 'f_455'], ['f_580', 'cpi_9606.ENSP00000295453', 'f_622', 'cpi_9606.ENSP00000358784', 'cpi_9606.ENSP00000369375'], ['f_696', 'cpi_9606.ENSP00000216962', 'cpi_9606.ENSP00000295491', 'f_474', 'f_750'], ['f_698', 'cpi_9606.ENSP00000354280', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000359353', 'f_436'], ['f_536', 'cpi_9606.ENSP00000346768', 'f_833', 'cpi_9606.ENSP00000277010', 'cpi_9606.ENSP00000349078'], ['f_655', 'cpi_9606.ENSP00000283635', 'cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000361206'], ['f_593', 'cpi_9606.ENSP00000262160', 'cpi_9606.ENSP00000322421', 'f_202', 'f_820'], ['f_594', 'cpi_9606.ENSP00000362329', 'f_788', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000337335'], ['f_21', 'cpi_9606.ENSP00000276198', 'f_728', 'cpi_9606.ENSP00000362508', 'cpi_9606.ENSP00000267119'], ['f_502', 'cpi_9606.ENSP00000279593', 'cpi_9606.ENSP00000362513', 'f_782', 'f_551'], ['f_611', 'cpi_9606.ENSP00000262735', 'cpi_9606.ENSP00000397026', 'cpi_9606.ENSP00000311469', 'f_46'], ['f_341', 'cpi_9606.ENSP00000290541', 'cpi_9606.ENSP00000406157', 'f_725', 'cpi_9606.ENSP00000286301'], ['f_555', 'cpi_9606.ENSP00000374467', 'cpi_9606.ENSP00000255465', 'cpi_9606.ENSP00000348234', 'f_631'], ['f_680', 'cpi_9606.ENSP00000261733', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000430432', 'cpi_9606.ENSP00000216037'], ['f_689', 'cpi_9606.ENSP00000244217', 'f_388', 'cpi_9606.ENSP00000374265', 'cpi_9606.ENSP00000343040'], ['f_548', 'cpi_9606.ENSP00000240139', 'cpi_9606.ENSP00000304822', 'cpi_9606.ENSP00000296871', 'cpi_9606.ENSP00000254227'], ['f_19', 'cpi_9606.ENSP00000349595', 'cpi_9606.ENSP00000368632', 'cpi_9606.ENSP00000351209', 'cpi_9606.ENSP00000267843'], ['f_33', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000261196', 'cpi_9606.ENSP00000300151'], ['cpi_9606.ENSP00000265724', 'f_427', 'f_583', 'f_262', 'cpi_9606.ENSP00000433290'], ['f_293', 'cpi_9606.ENSP00000375881', 'f_812', 'f_460', 'cpi_9606.ENSP00000312664'], ['f_150', 'cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000318585', 'f_827', 'cpi_9606.ENSP00000274793'], ['f_602', 'cpi_9606.ENSP00000340684', 'f_770', 'cpi_9606.ENSP00000457706', 'cpi_9606.ENSP00000419692'], ['f_692', 'cpi_9606.ENSP00000302886', 'f_297', 'cpi_9606.ENSP00000378890', 'cpi_9606.ENSP00000310305'], ['f_287', 'cpi_9606.ENSP00000290866', 'f_194', 'cpi_9606.ENSP00000364310', 'f_207'], ['f_549', 'cpi_9606.ENSP00000327850', 'cpi_9606.ENSP00000352584', 'cpi_9606.ENSP00000346598', 'cpi_9606.ENSP00000347979'], ['f_667', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000301178', 'cpi_9606.ENSP00000386284', 'f_407'], ['f_581', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000301141', 'f_757', 'f_466'], ['f_671', 'cpi_9606.ENSP00000308720', 'f_43', 'cpi_9606.ENSP00000343477', 'f_815'], ['f_241', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000222330', 'cpi_9606.ENSP00000355778'], ['f_579', 'cpi_9606.ENSP00000304408', 'cpi_9606.ENSP00000253799', 'f_509', 'cpi_9606.ENSP00000254810'], ['f_515', 'cpi_9606.ENSP00000264381', 'f_513', 'cpi_9606.ENSP00000339527', 'f_719'], ['f_636', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000337103', 'cpi_9606.ENSP00000266376', 'cpi_9606.ENSP00000451040'], ['f_337', 'f_215', 'cpi_9606.ENSP00000261405', 'cpi_9606.ENSP00000262367', 'cpi_9606.ENSP00000342235'], ['f_821', 'f_314', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000348069', 'cpi_9606.ENSP00000254066'], ['f_663', 'f_216', 'f_791', 'cpi_9606.ENSP00000361359', 'cpi_9606.ENSP00000308774'], ['f_37', 'f_229', 'cpi_9606.ENSP00000256958', 'cpi_9606.ENSP00000355533', 'cpi_9606.ENSP00000329357'], ['cpi_9606.ENSP00000222982', 'f_543', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000272847', 'f_675'], ['f_619', 'cpi_9606.ENSP00000301634', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000297268', 'f_792'], ['f_244', 'cpi_9606.ENSP00000239223', 'cpi_9606.ENSP00000361666', 'f_298', 'f_518'], ['f_300', 'f_249', 'f_533', 'cpi_9606.ENSP00000284981', 'f_448'], ['f_695', 'cpi_9606.ENSP00000216797', 'f_496', 'cpi_9606.ENSP00000335620', 'cpi_9606.ENSP00000275216'], ['f_573', 'cpi_9606.ENSP00000359719', 'cpi_9606.ENSP00000221515', 'cpi_9606.ENSP00000225474', 'cpi_9606.ENSP00000417229'], ['f_683', 'cpi_9606.ENSP00000369100', 'cpi_9606.ENSP00000388825', 'cpi_9606.ENSP00000360493', 'f_722'], ['f_654', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000371138', 'cpi_9606.ENSP00000219833', 'f_554'], ['f_637', 'cpi_9606.ENSP00000332256', 'cpi_9606.ENSP00000343745', 'f_771', 'f_670'], ['f_642', 'cpi_9606.ENSP00000256119', 'f_497', 'f_568', 'cpi_9606.ENSP00000428340'], ['f_755', 'f_454', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000344352', 'cpi_9606.ENSP00000261465'], ['f_633', 'cpi_9606.ENSP00000216714', 'cpi_9606.ENSP00000251566', 'cpi_9606.ENSP00000310405', 'f_785'], ['f_607', 'cpi_9606.ENSP00000349577', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000264867', 'cpi_9606.ENSP00000307014'], ['f_777', 'f_494', 'cpi_9606.ENSP00000296522', 'cpi_9606.ENSP00000318912', 'cpi_9606.ENSP00000428924'], ['f_368', 'cpi_9606.ENSP00000418532', 'f_398', 'cpi_9606.ENSP00000365012', 'cpi_9606.ENSP00000410076'], ['f_443', 'cpi_9606.ENSP00000312326', 'cpi_9606.ENSP00000252321', 'cpi_9606.ENSP00000261937', 'cpi_9606.ENSP00000294728'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000347754', 'f_429', 'f_559', 'cpi_9606.ENSP00000332296'], ['f_153', 'cpi_9606.ENSP00000287820', 'cpi_9606.ENSP00000267101', 'cpi_9606.ENSP00000234071', 'f_116'], ['f_516', 'cpi_9606.ENSP00000309477', 'cpi_9606.ENSP00000308938', 'cpi_9606.ENSP00000376943', 'f_609'], ['f_735', 'f_517', 'cpi_9606.ENSP00000364709', 'cpi_9606.ENSP00000260356', 'cpi_9606.ENSP00000326119'], ['f_818', 'cpi_9606.ENSP00000378323', 'f_475', 'f_409', 'f_759'], ['f_560', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000332549', 'f_826', 'f_471'], ['f_639', 'cpi_9606.ENSP00000285979', 'cpi_9606.ENSP00000292896', 'cpi_9606.ENSP00000259089', 'f_558'], ['f_193', 'cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000348645', 'cpi_9606.ENSP00000263377', 'f_461'], ['f_691', 'cpi_9606.ENSP00000358525', 'f_483', 'cpi_9606.ENSP00000354394', 'f_486'], ['f_390', 'cpi_9606.ENSP00000216410', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000176763'], ['f_592', 'cpi_9606.ENSP00000434516', 'cpi_9606.ENSP00000365380', 'cpi_9606.ENSP00000320935', 'f_653'], ['f_800', 'cpi_9606.ENSP00000346839', 'f_813', 'f_480', 'cpi_9606.ENSP00000349252'], ['f_576', 'cpi_9606.ENSP00000354511', 'cpi_9606.ENSP00000241261', 'f_347', 'f_861'], ['f_493', 'cpi_9606.ENSP00000303522', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000259271', 'cpi_9606.ENSP00000298283'], ['f_704', 'cpi_9606.ENSP00000164139', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000248553', 'cpi_9606.ENSP00000312029'], ['cpi_9606.ENSP00000283916', 'f_394', 'cpi_9606.ENSP00000420487', 'f_801', 'cpi_9606.ENSP00000358548'], ['f_628', 'cpi_9606.ENSP00000327801', 'cpi_9606.ENSP00000216341', 'f_840', 'cpi_9606.ENSP00000367102'], ['f_356', 'cpi_9606.ENSP00000001008', 'cpi_9606.ENSP00000429374', 'cpi_9606.ENSP00000222390', 'f_647'], ['f_420', 'cpi_9606.ENSP00000383365', 'cpi_9606.ENSP00000282561', 'f_477', 'f_195'], ['f_709', 'cpi_9606.ENSP00000364782', 'cpi_9606.ENSP00000239938', 'cpi_9606.ENSP00000261799', 'f_411'], ['f_449', 'cpi_9606.ENSP00000264426', 'cpi_9606.ENSP00000252486', 'f_740', 'f_242'], ['f_641', 'cpi_9606.ENSP00000322991', 'cpi_9606.ENSP00000420168', 'cpi_9606.ENSP00000308165', 'f_419'], ['f_604', 'cpi_9606.ENSP00000370373', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000280357', 'cpi_9606.ENSP00000305422'], ['f_377', 'cpi_9606.ENSP00000332973', 'cpi_9606.ENSP00000296511', 'f_227', 'f_780'], ['f_546', 'cpi_9606.ENSP00000356671', 'cpi_9606.ENSP00000387683', 'cpi_9606.ENSP00000372023', 'f_425'], ['f_376', 'cpi_9606.ENSP00000300289', 'f_803', 'cpi_9606.ENSP00000356954', 'cpi_9606.ENSP00000411658'], ['f_681', 'cpi_9606.ENSP00000260970', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000310447', 'f_514'], ['f_658', 'cpi_9606.ENSP00000355759', 'cpi_9606.ENSP00000334105', 'cpi_9606.ENSP00000362036', 'f_738'], ['cpi_9606.ENSP00000324648', 'f_707', 'cpi_9606.ENSP00000241256', 'f_305', 'cpi_9606.ENSP00000311028'], ['f_450', 'cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000370473', 'f_575', 'cpi_9606.ENSP00000274606'], ['f_333', 'cpi_9606.ENSP00000231790', 'cpi_9606.ENSP00000430075', 'cpi_9606.ENSP00000356958', 'f_742'], ['f_797', 'cpi_9606.ENSP00000308541', 'f_650', 'cpi_9606.ENSP00000254976', 'cpi_9606.ENSP00000443194'], ['f_699', 'f_488', 'cpi_9606.ENSP00000219919', 'cpi_9606.ENSP00000443459', 'cpi_9606.ENSP00000416293'], ['f_567', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000319814', 'cpi_9606.ENSP00000277508', 'cpi_9606.ENSP00000353878'], ['f_199', 'cpi_9606.ENSP00000385834', 'f_489', 'cpi_9606.ENSP00000326219', 'f_822'], ['f_586', 'cpi_9606.ENSP00000363965', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000451030', 'f_467'], ['f_375', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000248437', 'cpi_9606.ENSP00000367309', 'f_860'], ['f_23', 'cpi_9606.ENSP00000264498', 'cpi_9606.ENSP00000359998', 'cpi_9606.ENSP00000357981', 'f_160'], ['f_442', 'cpi_9606.ENSP00000295256', 'cpi_9606.ENSP00000295834', 'cpi_9606.ENSP00000326159', 'f_625'], ['f_353', 'cpi_9606.ENSP00000386884', 'cpi_9606.ENSP00000357283', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000322617'], ['cpi_9606.ENSP00000258743', 'f_652', 'cpi_9606.ENSP00000263088', 'f_421', 'f_456'], ['f_702', 'cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000364035', 'cpi_9606.ENSP00000263980', 'f_717'], ['f_259', 'cpi_9606.ENSP00000441691', 'cpi_9606.ENSP00000222002', 'f_367', 'cpi_9606.ENSP00000372750'], ['f_657', 'cpi_9606.ENSP00000307900', 'cpi_9606.ENSP00000211122', 'f_605', 'cpi_9606.ENSP00000359793'], ['f_447', 'cpi_9606.ENSP00000317842', 'cpi_9606.ENSP00000308897', 'f_705', 'cpi_9606.ENSP00000380252'], ['f_673', 'cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000340820', 'cpi_9606.ENSP00000389414', 'cpi_9606.ENSP00000340691'], ['f_538', 'cpi_9606.ENSP00000300093', 'cpi_9606.ENSP00000368880', 'cpi_9606.ENSP00000255380', 'f_610'], ['f_758', 'cpi_9606.ENSP00000361850', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000338082', 'f_500'], ['f_495', 'cpi_9606.ENSP00000327255', 'f_700', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000251535'], ['f_261', 'cpi_9606.ENSP00000278616', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000321326', 'f_144'], ['f_713', 'cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000263321', 'cpi_9606.ENSP00000369654', 'f_465'], ['f_612', 'f_590', 'cpi_9606.ENSP00000242057', 'cpi_9606.ENSP00000377192', 'cpi_9606.ENSP00000380247'], ['f_589', 'cpi_9606.ENSP00000331514', 'cpi_9606.ENSP00000325822', 'f_159', 'cpi_9606.ENSP00000231454'], ['f_574', 'cpi_9606.ENSP00000262187', 'cpi_9606.ENSP00000218099', 'f_359', 'cpi_9606.ENSP00000325120'], ['f_565', 'cpi_9606.ENSP00000333821', 'cpi_9606.ENSP00000353427', 'cpi_9606.ENSP00000225964', 'cpi_9606.ENSP00000333534'], ['f_412', 'cpi_9606.ENSP00000353915', 'cpi_9606.ENSP00000302111', 'cpi_9606.ENSP00000344192', 'cpi_9606.ENSP00000385806'], ['cpi_9606.ENSP00000272190', 'f_364', 'cpi_9606.ENSP00000368752', 'cpi_9606.ENSP00000319170', 'f_157'], ['f_24', 'cpi_9606.ENSP00000223095', 'cpi_9606.ENSP00000372326', 'f_38', 'cpi_9606.ENSP00000371929'], ['f_686', 'cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000371067', 'cpi_9606.ENSP00000306490', 'f_457'], ['f_498', 'cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000231449', 'f_363', 'cpi_9606.ENSP00000467676'], ['f_487', 'cpi_9606.ENSP00000299855', 'cpi_9606.ENSP00000308845', 'f_423', 'f_206'], ['f_507', 'cpi_9606.ENSP00000417281', 'cpi_9606.ENSP00000267377', 'cpi_9606.ENSP00000265403', 'cpi_96

🔄 Processing features: 100%|██████████| 2147/2147 [10:21<00:00,  3.46feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'f_408', 'f_164', 'f_866', 'cpi_9606.ENSP00000344674'], ['cpi_9606.ENSP00000353820', 'f_131', 'f_510', 'cpi_9606.ENSP00000286648', 'f_749'], ['cpi_9606.ENSP00000342007', 'f_413', 'f_347', 'f_587', 'f_773'], ['f_374', 'cpi_9606.ENSP00000264705', 'f_768', 'cpi_9606.ENSP00000359424', 'f_202'], ['f_308', 'cpi_9606.ENSP00000355192', 'f_616', 'cpi_9606.ENSP00000263377', 'cpi_9606.ENSP00000342235'], ['f_346', 'cpi_9606.ENSP00000279178', 'cpi_9606.ENSP00000357068', 'f_629', 'cpi_9606.ENSP00000395653'], ['f_405', 'cpi_9606.ENSP00000305742', 'f_789', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000333212'], ['f_335', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000295454', 'f_834'], ['cpi_9606.ENSP00000270349', 'f_132', 'f_455', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000360773'], ['f_146', 'cpi_9606.ENSP00000313490', 'cpi_9606.ENSP00000430684', 'f_526', 'cpi_9606.ENSP00000304822'], ['f_20', 'cpi_9606.ENSP00000254488', 'f_729', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000221972'], ['f_643', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000359635', 'f_151'], ['f_16', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000287766', 'f_861', 'cpi_9606.ENSP00000296122'], ['f_614', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000411593', 'f_726', 'cpi_9606.ENSP00000343204'], ['f_180', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000263126', 'cpi_9606.ENSP00000356094', 'f_47'], ['f_566', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000355629', 'f_836'], ['cpi_9606.ENSP00000360372', 'cpi_9606.ENSP00000409007', 'f_200', 'f_812', 'cpi_9606.ENSP00000353362'], ['f_659', 'cpi_9606.ENSP00000360967', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000332296', 'cpi_9606.ENSP00000389338'], ['f_192', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000345096', 'cpi_9606.ENSP00000359353', 'f_845'], ['f_380', 'cpi_9606.ENSP00000257290', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000333496', 'f_31'], ['f_528', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000354476', 'cpi_9606.ENSP00000365016', 'cpi_9606.ENSP00000385026'], ['f_406', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000351209', 'f_831'], ['f_392', 'cpi_9606.ENSP00000375881', 'cpi_9606.ENSP00000277010', 'f_428', 'cpi_9606.ENSP00000367848'], ['f_452', 'cpi_9606.ENSP00000381097', 'f_25', 'cpi_9606.ENSP00000417229', 'cpi_9606.ENSP00000397026'], ['cpi_9606.ENSP00000356438', 'f_213', 'f_706', 'cpi_9606.ENSP00000352011', 'f_194'], ['f_12', 'cpi_9606.ENSP00000314649', 'cpi_9606.ENSP00000414334', 'f_635', 'f_27'], ['f_299', 'cpi_9606.ENSP00000321584', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000367851', 'cpi_9606.ENSP00000360493'], ['f_420', 'cpi_9606.ENSP00000354193', 'f_328', 'f_529', 'f_767'], ['f_391', 'cpi_9606.ENSP00000256383', 'cpi_9606.ENSP00000370381', 'cpi_9606.ENSP00000274793', 'cpi_9606.ENSP00000447149'], ['cpi_9606.ENSP00000311032', 'f_166', 'f_43', 'f_785', 'f_454'], ['cpi_9606.ENSP00000367959', 'f_129', 'cpi_9606.ENSP00000003100', 'f_292', 'f_497'], ['cpi_9606.ENSP00000328968', 'f_507', 'cpi_9606.ENSP00000305221', 'f_518', 'cpi_9606.ENSP00000457706'], ['f_439', 'cpi_9606.ENSP00000354107', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000245539'], ['f_186', 'cpi_9606.ENSP00000234310', 'f_511', 'cpi_9606.ENSP00000435591', 'f_118'], ['f_617', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000345502'], ['f_571', 'cpi_9606.ENSP00000353791', 'cpi_9606.ENSP00000301891', 'cpi_9606.ENSP00000369375', 'f_736'], ['f_2', 'cpi_9606.ENSP00000244217', 'cpi_9606.ENSP00000386029', 'f_788', 'cpi_9606.ENSP00000258749'], ['f_338', 'cpi_9606.ENSP00000331746', 'cpi_9606.ENSP00000359334', 'f_715', 'cpi_9606.ENSP00000374323'], ['f_366', 'cpi_9606.ENSP00000349595', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000216037', 'f_725'], ['f_341', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000273398', 'f_778', 'f_771'], ['f_645', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000357255', 'f_229'], ['f_637', 'cpi_9606.ENSP00000376914', 'cpi_9606.ENSP00000312455', 'f_830', 'cpi_9606.ENSP00000283635'], ['f_393', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000380318', 'f_214'], ['f_638', 'cpi_9606.ENSP00000225275', 'cpi_9606.ENSP00000352900', 'f_791', 'cpi_9606.ENSP00000337335'], ['f_3', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000307599', 'cpi_9606.ENSP00000410294', 'cpi_9606.ENSP00000305422'], ['f_181', 'cpi_9606.ENSP00000273550', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000471569', 'cpi_9606.ENSP00000445340'], ['f_185', 'cpi_9606.ENSP00000349576', 'cpi_9606.ENSP00000309493', 'cpi_9606.ENSP00000260010', 'cpi_9606.ENSP00000372547'], ['cpi_9606.ENSP00000354612', 'f_216', 'f_401', 'f_17', 'cpi_9606.ENSP00000267101'], ['cpi_9606.ENSP00000260682', 'f_215', 'f_22', 'f_466', 'cpi_9606.ENSP00000262352'], ['f_535', 'cpi_9606.ENSP00000430075', 'cpi_9606.ENSP00000326219', 'f_327', 'f_722'], ['f_257', 'cpi_9606.ENSP00000279387', 'cpi_9606.ENSP00000387946', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000451040'], ['cpi_9606.ENSP00000337450', 'f_543', 'f_26', 'cpi_9606.ENSP00000292513', 'cpi_9606.ENSP00000301634'], ['f_646', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000367608', 'f_330'], ['f_339', 'cpi_9606.ENSP00000376432', 'f_799', 'f_554', 'cpi_9606.ENSP00000308774'], ['f_569', 'cpi_9606.ENSP00000264426', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000361666', 'f_350'], ['f_451', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000348786', 'cpi_9606.ENSP00000264637', 'f_436'], ['f_143', 'cpi_9606.ENSP00000001008', 'cpi_9606.ENSP00000330393', 'f_297', 'f_764'], ['f_682', 'cpi_9606.ENSP00000355155', 'f_839', 'cpi_9606.ENSP00000434045', 'cpi_9606.ENSP00000251535'], ['cpi_9606.ENSP00000265724', 'f_417', 'f_407', 'f_505', 'f_675'], ['f_548', 'cpi_9606.ENSP00000286621', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000343040', 'cpi_9606.ENSP00000297316'], ['f_615', 'cpi_9606.ENSP00000293288', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000428864', 'f_460'], ['f_293', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000314949', 'f_427', 'f_298'], ['f_611', 'cpi_9606.ENSP00000301633', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000365380', 'cpi_9606.ENSP00000309124'], ['f_697', 'cpi_9606.ENSP00000357669', 'cpi_9606.ENSP00000323568', 'cpi_9606.ENSP00000261937', 'cpi_9606.ENSP00000389414'], ['f_656', 'cpi_9606.ENSP00000234389', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000388825', 'cpi_9606.ENSP00000319788'], ['f_692', 'cpi_9606.ENSP00000308720', 'f_670', 'f_474', 'cpi_9606.ENSP00000282561'], ['f_553', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000263431', 'f_509', 'f_167'], ['f_597', 'cpi_9606.ENSP00000338627', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000427514', 'cpi_9606.ENSP00000262888'], ['f_15', 'cpi_9606.ENSP00000320401', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000282753', 'f_719'], ['f_699', 'f_488', 'cpi_9606.ENSP00000364709', 'f_792', 'f_46'], ['f_345', 'cpi_9606.ENSP00000296411', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000254227', 'f_583'], ['f_666', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000216962', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000252723'], ['cpi_9606.ENSP00000324648', 'f_707', 'f_195', 'f_483', 'cpi_9606.ENSP00000376943'], ['f_443', 'cpi_9606.ENSP00000379802', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000346534', 'f_815'], ['f_712', 'cpi_9606.ENSP00000262623', 'f_35', 'f_609', 'cpi_9606.ENSP00000308165'], ['f_248', 'cpi_9606.ENSP00000378323', 'f_262', 'cpi_9606.ENSP00000297350', 'f_752'], ['f_540', 'cpi_9606.ENSP00000352584', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000272847', 'f_827'], ['f_440', 'cpi_9606.ENSP00000378517', 'cpi_9606.ENSP00000337773', 'f_728', 'cpi_9606.ENSP00000347942'], ['f_704', 'cpi_9606.ENSP00000441691', 'cpi_9606.ENSP00000355778', 'f_473', 'cpi_9606.ENSP00000376776'], ['cpi_9606.ENSP00000258743', 'f_395', 'cpi_9606.ENSP00000261799', 'cpi_9606.ENSP00000259271', 'f_207'], ['f_613', 'cpi_9606.ENSP00000362924', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000226574'], ['f_579', 'cpi_9606.ENSP00000297268', 'cpi_9606.ENSP00000428924', 'cpi_9606.ENSP00000353292', 'cpi_9606.ENSP00000248553'], ['f_680', 'cpi_9606.ENSP00000238018', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000286301', 'f_486'], ['f_696', 'cpi_9606.ENSP00000354532', 'cpi_9606.ENSP00000354394', 'f_750', 'f_475'], ['f_365', 'cpi_9606.ENSP00000366620', 'cpi_9606.ENSP00000470087', 'cpi_9606.ENSP00000356954', 'cpi_9606.ENSP00000367102'], ['cpi_9606.ENSP00000360317', 'f_763', 'cpi_9606.ENSP00000335511', 'f_160', 'cpi_9606.ENSP00000299267'], ['f_390', 'cpi_9606.ENSP00000358042', 'cpi_9606.ENSP00000343477', 'cpi_9606.ENSP00000275525', 'f_551'], ['f_340', 'cpi_9606.ENSP00000286091', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000231454', 'f_361'], ['cpi_9606.ENSP00000418532', 'f_647', 'f_398', 'cpi_9606.ENSP00000255380', 'f_343'], ['f_287', 'cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000312664', 'f_622'], ['f_683', 'cpi_9606.ENSP00000013034', 'cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000394936', 'f_448'], ['f_818', 'cpi_9606.ENSP00000023897', 'f_533', 'cpi_9606.ENSP00000256078', 'f_409'], ['f_602', 'cpi_9606.ENSP00000304811', 'f_833', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000262178'], ['f_353', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000256958', 'cpi_9606.ENSP00000358730'], ['f_672', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000301420', 'cpi_9606.ENSP00000274547', 'cpi_9606.ENSP00000344192'], ['f_684', 'cpi_9606.ENSP00000368349', 'f_508', 'cpi_9606.ENSP00000242057', 'cpi_9606.ENSP00000361359'], ['f_241', 'cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000311095', 'f_738', 'f_782'], ['f_19', 'cpi_9606.ENSP00000472933', 'cpi_9606.ENSP00000463999', 'f_676', 'cpi_9606.ENSP00000339527'], ['f_145', 'cpi_9606.ENSP00000295453', 'f_631', 'cpi_9606.ENSP00000362649', 'cpi_9606.ENSP00000300061'], ['f_37', 'cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000267119', 'cpi_9606.ENSP00000357283', 'f_159'], ['f_592', 'cpi_9606.ENSP00000369100', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000225474', 'f_820'], ['f_821', 'cpi_9606.ENSP00000302564', 'f_456', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000320935'], ['cpi_9606.ENSP00000262186', 'f_349', 'cpi_9606.ENSP00000296522', 'cpi_9606.ENSP00000222256', 'f_522'], ['f_33', 'cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000261196', 'f_801', 'f_230'], ['f_593', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000419692', 'f_757', 'cpi_9606.ENSP00000266376'], ['cpi_9606.ENSP00000283916', 'f_388', 'cpi_9606.ENSP00000311165', 'f_394', 'cpi_9606.ENSP00000301178'], ['f_691', 'cpi_9606.ENSP00000318585', 'cpi_9606.ENSP00000296871', 'cpi_9606.ENSP00000447173', 'f_717'], ['f_337', 'cpi_9606.ENSP00000303211', 'f_644', 'f_770', 'cpi_9606.ENSP00000366307'], ['f_244', 'f_242', 'cpi_9606.ENSP00000332549', 'cpi_9606.ENSP00000222330', 'f_588'], ['f_623', 'f_30', 'cpi_9606.ENSP00000305302', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000262367'], ['f_536', 'cpi_9606.ENSP00000362508', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000351908', 'f_742'], ['f_580', 'cpi_9606.ENSP00000363965', 'cpi_9606.ENSP00000372750', 'f_419', 'cpi_9606.ENSP00000326119'], ['f_153', 'cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000287936', 'cpi_9606.ENSP00000370912'], ['f_464', 'cpi_9606.ENSP00000236671', 'cpi_9606.ENSP00000443459', 'f_840', 'f_740'], ['cpi_9606.ENSP00000355759', 'f_336', 'cpi_9606.ENSP00000292896', 'cpi_9606.ENSP00000259089', 'f_694'], ['f_663', 'cpi_9606.ENSP00000363868', 'f_813', 'f_514', 'f_477'], ['f_619', 'cpi_9606.ENSP00000399168', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000348069'], ['f_412', 'cpi_9606.ENSP00000231751', 'f_826', 'cpi_9606.ENSP00000349577', 'f_314'], ['f_681', 'cpi_9606.ENSP00000343838', 'f_429', 'cpi_9606.ENSP00000371929', 'f_513'], ['f_432', 'cpi_9606.ENSP00000464149', 'f_496', 'cpi_9606.ENSP00000262948', 'cpi_9606.ENSP00000276449'], ['f_594', 'cpi_9606.ENSP00000312673', 'cpi_9606.ENSP00000280357', 'f_568', 'cpi_9606.ENSP00000294728'], ['f_375', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000295731', 'f_653', 'f_471'], ['f_698', 'cpi_9606.ENSP00000354280', 'f_650', 'cpi_9606.ENSP00000412673', 'f_480'], ['f_641', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000418447', 'cpi_9606.ENSP00000316786', 'f_411'], ['f_642', 'cpi_9606.ENSP00000285979', 'cpi_9606.ENSP00000253004', 'f_422', 'cpi_9606.ENSP00000416293'], ['f_516', 'cpi_9606.ENSP00000256578', 'cpi_9606.ENSP00000309572', 'f_558', 'f_425'], ['f_639', 'cpi_9606.ENSP00000394033', 'cpi_9606.ENSP00000226413', 'f_500', 'f_494'], ['f_574', 'cpi_9606.ENSP00000327255', 'cpi_9606.ENSP00000312029', 'f_759', 'f_116'], ['f_671', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000379330', 'f_517', 'cpi_9606.ENSP00000264657'], ['f_368', 'cpi_9606.ENSP00000385834', 'f_803', 'cpi_9606.ENSP00000358548', 'cpi_9606.ENSP00000365775'], ['f_655', 'cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000361206', 'f_359', 'cpi_9606.ENSP00000388648'], ['f_586', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000356694', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000328973'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000291294', 'f_34', 'cpi_9606.ENSP00000176763', 'cpi_9606.ENSP00000364802'], ['f_685', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000218548', 'f_251', 'cpi_9606.ENSP00000261693'], ['f_243', 'cpi_9606.ENSP00000239223', 'cpi_9606.ENSP00000262461', 'f_822', 'f_115'], ['f_628', 'cpi_9606.ENSP00000216714', 'cpi_9606.ENSP00000370473', 'cpi_9606.ENSP00000308845', 'f_227'], ['f_686', 'cpi_9606.ENSP00000317842', 'cpi_9606.ENSP00000331912', 'f_378', 'cpi_9606.ENSP00000386171'], ['f_199', 'cpi_9606.ENSP00000342070', 'f_489', 'cpi_9606.ENSP00000252486', 'cpi_9606.ENSP00000308549'], ['f_702', 'cpi_9606.ENSP00000276431', 'cpi_9606.ENSP00000354610', 'f_301', 'f_780'], ['cpi_9606.ENSP00000272190', 'cpi_9606.ENSP00000329357', 'f_421', 'cpi_9606.ENSP00000428340', 'cpi_9606.ENSP00000252029'], ['f_607', 'cpi_9606.ENSP00000277541', 'cpi_9606.ENSP00000317379', 'f_367', 'cpi_9606.ENSP00000359793'], ['f_573', 'cpi_9606.ENSP00000322991', 'cpi_9606.ENSP00000239938', 'f_363', 'cpi_9606.ENSP00000263321'], ['f_150', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000332116', 'f_187', 'cpi_9606.ENSP00000259396'], ['f_662', 'cpi_9606.ENSP00000368727', 'cpi_9606.ENSP00000410076', 'f_467', 'f_687'], ['f_755', 'cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000356832', 'f_423', 'cpi_9606.ENSP00000398632'], ['cpi_9606.ENSP00000398698', 'f_24', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000220616', 'f_157'], ['f_449', 'cpi_9606.ENSP00000279593', 'f_860', 'cpi_9606.ENSP00000309649', 'f_575'], ['f_23', 'cpi_9606.ENSP00000264498', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000241600', 'f_559'], ['f_502', 'cpi_9606.ENSP00000356671', 'cpi_9606.ENSP00000359998', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000338072'], ['f_758', 'cpi_9606.ENSP00000344352', 'cpi_9606.ENSP00000363832', 'f_610', 'cpi_9606.ENSP00000324248'], ['f_633', 'cpi_9606.ENSP00000251810', 'cpi_9606.ENSP00000304895', 'f_144', 'f_461'], ['f_445', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000346298', 'cpi_9606.ENSP00000353224', 'f_805'], ['f_356', 'cpi_9606.ENSP00000263212', 'cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000325822', 'f_305'], ['f_519', 'cpi_9606.ENSP00000252321', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000332369', 'f_605'], ['f_549', 'cpi_9606.ENSP00000297792', 'cpi_9606.ENSP00000378492', 'cpi_9606.ENSP00000343925', 'f_625'], ['f_21', 'cpi_9606.ENSP00000276198', 'cpi_9606.ENSP00000314508', 'cpi_9606.ENSP00000309968', 'f_457'], ['f_689', 'cpi_9606.ENSP00000357981', 'cpi_9606.ENSP00000319814', 'f_397', 'cpi_9606.ENSP00000263923'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000295491', 'f_206', 'f_658'], ['cpi_9606.ENSP00000261707', 'f_458', 'cpi_9606.ENSP00000369757', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000459962'], ['f_777', 'cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000382659', 'f_364', 'cpi_9606.ENSP00000362344'], ['f_711', 'cpi_9606.ENSP00000307766', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000252809', 'cpi_9606.ENSP00000217426'], ['f_193', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000327801', 'f_601', 'cpi_9606.ENSP00000216797'], ['f_567', 'cpi_9606.ENSP00000199280', 'cpi_9606.ENSP00000260191', 'f_515', 'cpi_9606.ENSP00000276414'], ['f_695', 'cpi_9606.ENSP00000338018', 'cpi_9606.ENSP00000220003', 'f_465', 'cpi_9606.ENSP00000380247'], ['f_300', 'cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000347979', 'cpi_9606.ENSP00000419782', 'f_250'], ['f_493', 'cpi_9606.ENSP00000330199', 'cpi_9606.ENSP00000411658', 'cpi_9606.ENSP00000302111', 'cpi_9606.ENSP00000300900'], ['f_667', 'cpi_9606.ENSP00000358107', 'cpi_9606.ENSP00000385806', 'cpi_9606.ENSP00000237527', 'f_784'], ['f_636', 'cpi_9606.ENSP00000299855', 'cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000232219', 'cpi_9606.ENSP00000346598'], ['f_377', 'cpi_9606.ENSP00000332973', 'cpi_9606.ENSP00000322421', 'f_334', 'cpi_9606.ENSP00000367309'], ['f_560', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000467676', 'cpi_9606.ENSP00000264867', 'f_705'], ['f_286', 'cpi_9606.ENSP00000343885', 'cpi_9606.ENSP00000380252', 'f_621', 'cpi_9606.ENSP00000299178'], ['f_539', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000308938', 'cpi_9606.ENSP00000353878', 'f_761'], ['f_259', 'cpi_9606.ENSP00000290349', 'cpi_9606.ENSP00000307014', 'cpi_9606.ENSP00000454071', 'cpi_9606.ENSP00000306490'], ['f_657', 'cpi_9606.ENSP00000215659', 'cpi_9606.ENSP00000327850', 'cpi_9606.ENSP00000266682', 'cpi_9606.ENSP00000231228'], ['f_612', 'cpi_9606.ENSP00000301141', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000303522', 'f_414'], ['f_665', 'cpi_9606.ENSP00000362334', 'cpi_9606.ENSP00000365663', 'cpi_9606.ENSP00000414303', 'f_563'], ['f_342', 'cpi_9606.ENSP00000219070', 'f_527', 'cpi_9606.ENSP00000361151', 'cpi_9606.ENSP00000255465'], ['cpi_9606.ENSP00000330237', 'f_152', 'cpi_9606.ENSP00000295598', 'f_38', 'cpi_9606.ENSP00000293745'], ['f_797', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000387683', 'f_260'], ['f_437', 'cpi_9606.ENSP00000296046', 'cpi_9606.ENSP00000356213', 'f_700', 'cpi_9606.ENSP00000233242'], ['f_709', 'cpi_9606.ENSP00000373674', 'cpi_9606.ENSP00000430432', 'f_721', 'cpi_9606.ENSP00000255030'], ['f_713', 'cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000268053', 'cpi_9606.ENSP00000254810', 'f_459'], ['f_418', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000295256', 'cpi_9606.ENSP00000308032', 'f_819'], ['cpi_9606.ENSP00000258400', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000267843', 'cpi_9606.ENSP00000311028', 'f_716'], ['f_654', 'cpi_9606.ENSP00000324173', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000216341', 'f_756'], ['f_294', 'cpi_9606.ENSP00000346839', 'f_399', 'f_701', 'cpi_9606.ENSP00000355657'], ['f_371', 'cpi_9606.ENSP00000413074', 'cpi_9606.ENSP00000296545', 'cpi_9606.ENSP00000372023', 'f_652'], ['f_626', 'cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000233146', 'cpi_9606.ENSP00000254066', 'f_532'], ['f_651', 'cpi_9606.ENSP00000248923', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000260356'], ['f_546', 'cpi_9606.ENSP00000307900', 'f_661', 'cpi_9606.ENSP00000310305', 'cpi_9606.ENSP00000200676'], ['f_438', 'cpi_9606.ENSP00000239849', 'cpi_9606.ENSP00000331602', 'f_590', 'cpi_9606.ENSP00000359096'], ['f_581', 'cpi_9606.ENSP00000360968', 'cpi_9606.ENSP00000364805', 'f_383', 'cpi_9606.ENSP00000375893'], ['f_690', 'cpi_9606.ENSP00000302961', 'cpi_9606.ENSP00000178638', 'f_400', 'cpi_9606.ENSP00000256906'], ['f_708', 'cpi_9606.ENSP00000362329', 'cpi_9606.ENSP00000278616', 'cpi_9606.ENSP00000303452', 'f_531'], ['f_434', 'cpi_9606.ENSP00000309477', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000363296', 'cpi_9606.ENSP00000364310'], ['f_256', 'cpi_9606.ENSP00000341045',

🔄 Processing features: 100%|██████████| 2147/2147 [10:21<00:00,  3.45feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'f_413', 'f_262', 'cpi_9606.ENSP00000354569', 'f_768'], ['f_374', 'cpi_9606.ENSP00000443459', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000301634', 'f_789'], ['f_566', 'cpi_9606.ENSP00000279178', 'cpi_9606.ENSP00000358107', 'cpi_9606.ENSP00000355629', 'cpi_9606.ENSP00000260191'], ['f_308', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000288602', 'f_616', 'cpi_9606.ENSP00000356832'], ['f_20', 'cpi_9606.ENSP00000333212', 'cpi_9606.ENSP00000295454', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000286479'], ['f_406', 'cpi_9606.ENSP00000344352', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000385026'], ['f_380', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000337773', 'f_726', 'cpi_9606.ENSP00000342235'], ['cpi_9606.ENSP00000342007', 'f_336', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000430684', 'f_635'], ['f_452', 'f_25', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000365663'], ['f_185', 'cpi_9606.ENSP00000364782', 'cpi_9606.ENSP00000355778', 'f_845', 'f_292'], ['f_451', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000245539'], ['f_391', 'cpi_9606.ENSP00000313490', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000467676', 'f_866'], ['cpi_9606.ENSP00000328968', 'f_131', 'cpi_9606.ENSP00000301633', 'f_144', 'f_510'], ['cpi_9606.ENSP00000353820', 'f_129', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000360773', 'f_812'], ['f_338', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000321584', 'f_31', 'cpi_9606.ENSP00000451040'], ['f_186', 'cpi_9606.ENSP00000279387', 'cpi_9606.ENSP00000414334', 'cpi_9606.ENSP00000355657', 'cpi_9606.ENSP00000361206'], ['f_643', 'cpi_9606.ENSP00000345096', 'cpi_9606.ENSP00000332296', 'f_151', 'cpi_9606.ENSP00000367851'], ['f_405', 'cpi_9606.ENSP00000305742', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000395653', 'f_831'], ['f_335', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000394033', 'f_771', 'cpi_9606.ENSP00000367848'], ['cpi_9606.ENSP00000311032', 'f_229', 'f_587', 'cpi_9606.ENSP00000356094', 'f_670'], ['f_659', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000389338', 'cpi_9606.ENSP00000387946'], ['f_614', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000314649', 'f_629', 'f_834'], ['f_440', 'cpi_9606.ENSP00000267101', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000319591', 'cpi_9606.ENSP00000311165'], ['f_12', 'cpi_9606.ENSP00000354532', 'cpi_9606.ENSP00000357068', 'f_773', 'cpi_9606.ENSP00000354394'], ['f_339', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000301891', 'f_529', 'cpi_9606.ENSP00000264318'], ['cpi_9606.ENSP00000354612', 'cpi_9606.ENSP00000409007', 'f_213', 'f_30', 'f_194'], ['f_143', 'cpi_9606.ENSP00000327255', 'f_47', 'f_328', 'f_526'], ['f_346', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000431512', 'f_428', 'cpi_9606.ENSP00000216037'], ['f_180', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000258749'], ['f_392', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000262160', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000354476'], ['f_528', 'cpi_9606.ENSP00000370129', 'cpi_9606.ENSP00000379330', 'f_460', 'f_43'], ['f_602', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000277010', 'f_833', 'cpi_9606.ENSP00000341390'], ['f_366', 'cpi_9606.ENSP00000349595', 'cpi_9606.ENSP00000256383', 'cpi_9606.ENSP00000359353', 'cpi_9606.ENSP00000365016'], ['f_3', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000283254', 'f_511', 'cpi_9606.ENSP00000369375'], ['f_257', 'cpi_9606.ENSP00000234310', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000260010', 'cpi_9606.ENSP00000428824'], ['f_2', 'cpi_9606.ENSP00000349576', 'cpi_9606.ENSP00000320171', 'cpi_9606.ENSP00000298386', 'f_836'], ['f_146', 'cpi_9606.ENSP00000277541', 'cpi_9606.ENSP00000274793', 'cpi_9606.ENSP00000304822', 'f_46'], ['f_181', 'cpi_9606.ENSP00000273550', 'cpi_9606.ENSP00000263126', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000221972'], ['f_579', 'cpi_9606.ENSP00000349078', 'cpi_9606.ENSP00000263321', 'f_330', 'f_788'], ['f_16', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000296122', 'cpi_9606.ENSP00000352900'], ['f_617', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000374323', 'cpi_9606.ENSP00000359334', 'f_820'], ['cpi_9606.ENSP00000356438', 'f_216', 'f_401', 'f_653', 'f_427'], ['f_692', 'cpi_9606.ENSP00000234389', 'cpi_9606.ENSP00000420194', 'f_327', 'f_474'], ['cpi_9606.ENSP00000270349', 'f_132', 'cpi_9606.ENSP00000003100', 'f_195', 'f_118'], ['f_439', 'cpi_9606.ENSP00000354107', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000251453'], ['f_192', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000364212', 'cpi_9606.ENSP00000307259', 'f_298'], ['f_535', 'cpi_9606.ENSP00000297792', 'f_509', 'cpi_9606.ENSP00000232219', 'f_497'], ['f_646', 'cpi_9606.ENSP00000261196', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000252809', 'cpi_9606.ENSP00000254066'], ['cpi_9606.ENSP00000260682', 'f_200', 'f_749', 'cpi_9606.ENSP00000292513', 'f_27'], ['cpi_9606.ENSP00000367959', 'f_588', 'f_411', 'cpi_9606.ENSP00000261799', 'f_728'], ['f_611', 'cpi_9606.ENSP00000305221', 'cpi_9606.ENSP00000419692', 'f_214', 'cpi_9606.ENSP00000253004'], ['f_682', 'f_839', 'cpi_9606.ENSP00000363832', 'f_715', 'cpi_9606.ENSP00000216341'], ['f_638', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000297350', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000308774'], ['f_393', 'cpi_9606.ENSP00000323867', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000366307', 'cpi_9606.ENSP00000305422'], ['f_569', 'cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000252486', 'f_350'], ['f_683', 'cpi_9606.ENSP00000233944', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000309124', 'cpi_9606.ENSP00000312455'], ['f_698', 'cpi_9606.ENSP00000364709', 'cpi_9606.ENSP00000295491', 'f_388', 'f_792'], ['f_571', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000365686', 'f_752', 'f_799'], ['f_341', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000273398', 'cpi_9606.ENSP00000337335', 'cpi_9606.ENSP00000286301'], ['f_37', 'cpi_9606.ENSP00000400175', 'cpi_9606.ENSP00000418447', 'f_554', 'cpi_9606.ENSP00000270625'], ['f_145', 'cpi_9606.ENSP00000290349', 'f_202', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000394936'], ['f_637', 'cpi_9606.ENSP00000472933', 'cpi_9606.ENSP00000463999', 'cpi_9606.ENSP00000312029', 'cpi_9606.ENSP00000417229'], ['f_337', 'cpi_9606.ENSP00000385834', 'f_215', 'cpi_9606.ENSP00000307599', 'cpi_9606.ENSP00000257290'], ['f_515', 'cpi_9606.ENSP00000302564', 'f_767', 'f_706', 'f_26'], ['cpi_9606.ENSP00000337450', 'f_543', 'cpi_9606.ENSP00000227758', 'f_408', 'f_207'], ['f_597', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000353791', 'f_164', 'cpi_9606.ENSP00000292427'], ['f_672', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000263269', 'cpi_9606.ENSP00000272847', 'f_830'], ['cpi_9606.ENSP00000324648', 'f_227', 'f_694', 'cpi_9606.ENSP00000307014', 'cpi_9606.ENSP00000358548'], ['f_684', 'cpi_9606.ENSP00000234590', 'cpi_9606.ENSP00000471569', 'f_725', 'cpi_9606.ENSP00000428924'], ['f_19', 'cpi_9606.ENSP00000376914', 'cpi_9606.ENSP00000381097', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000275525'], ['f_645', 'cpi_9606.ENSP00000254488', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000275216', 'cpi_9606.ENSP00000266376'], ['f_691', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000283635', 'cpi_9606.ENSP00000216540'], ['f_712', 'cpi_9606.ENSP00000218548', 'f_35', 'f_750', 'cpi_9606.ENSP00000427514'], ['f_615', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000344192', 'cpi_9606.ENSP00000229264'], ['f_641', 'cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000262948', 'f_407'], ['f_696', 'cpi_9606.ENSP00000359719', 'cpi_9606.ENSP00000297316', 'f_436', 'cpi_9606.ENSP00000343040'], ['f_345', 'cpi_9606.ENSP00000287878', 'cpi_9606.ENSP00000264637', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000356954'], ['f_553', 'cpi_9606.ENSP00000360967', 'cpi_9606.ENSP00000352561', 'cpi_9606.ENSP00000348786', 'f_675'], ['f_656', 'cpi_9606.ENSP00000362924', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000311095', 'cpi_9606.ENSP00000410076'], ['cpi_9606.ENSP00000360317', 'f_230', 'f_763', 'cpi_9606.ENSP00000353427', 'cpi_9606.ENSP00000303522'], ['f_15', 'cpi_9606.ENSP00000330484', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000278175', 'cpi_9606.ENSP00000309103'], ['f_293', 'cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000216714', 'cpi_9606.ENSP00000346148', 'cpi_9606.ENSP00000433821'], ['f_667', 'f_791', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000301178', 'cpi_9606.ENSP00000302886'], ['cpi_9606.ENSP00000222982', 'f_778', 'f_22', 'cpi_9606.ENSP00000244217', 'cpi_9606.ENSP00000303424'], ['f_516', 'cpi_9606.ENSP00000225927', 'cpi_9606.ENSP00000296674', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000225474'], ['cpi_9606.ENSP00000283916', 'f_297', 'f_314', 'f_513', 'f_429'], ['f_697', 'cpi_9606.ENSP00000357669', 'cpi_9606.ENSP00000445340', 'cpi_9606.ENSP00000410294', 'cpi_9606.ENSP00000355920'], ['f_580', 'cpi_9606.ENSP00000295453', 'cpi_9606.ENSP00000372750', 'f_361', 'cpi_9606.ENSP00000226574'], ['cpi_9606.ENSP00000262186', 'f_349', 'cpi_9606.ENSP00000296522', 'f_729', 'cpi_9606.ENSP00000359100'], ['f_299', 'cpi_9606.ENSP00000338160', 'cpi_9606.ENSP00000295834', 'cpi_9606.ENSP00000360493', 'f_622'], ['f_23', 'cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000389414', 'f_167', 'cpi_9606.ENSP00000312664'], ['cpi_9606.ENSP00000265724', 'f_455', 'f_417', 'f_505', 'f_166'], ['f_680', 'cpi_9606.ENSP00000238018', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000379086'], ['f_365', 'cpi_9606.ENSP00000366620', 'cpi_9606.ENSP00000365380', 'f_583', 'cpi_9606.ENSP00000261693'], ['f_639', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000259089', 'f_757', 'cpi_9606.ENSP00000285381'], ['f_592', 'cpi_9606.ENSP00000369100', 'cpi_9606.ENSP00000329357', 'cpi_9606.ENSP00000240652', 'f_764'], ['f_420', 'cpi_9606.ENSP00000312326', 'cpi_9606.ENSP00000361359', 'f_785', 'cpi_9606.ENSP00000378517'], ['f_248', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000216962', 'cpi_9606.ENSP00000343204', 'f_518'], ['f_586', 'cpi_9606.ENSP00000252519', 'f_826', 'cpi_9606.ENSP00000353915', 'cpi_9606.ENSP00000222390'], ['f_300', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000359663', 'f_551'], ['f_581', 'cpi_9606.ENSP00000260970', 'f_425', 'f_466', 'cpi_9606.ENSP00000300900'], ['f_432', 'cpi_9606.ENSP00000363868', 'f_159', 'cpi_9606.ENSP00000393312', 'f_815'], ['f_658', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000350198', 'f_722'], ['f_628', 'cpi_9606.ENSP00000362513', 'cpi_9606.ENSP00000248076', 'cpi_9606.ENSP00000346598', 'cpi_9606.ENSP00000254227'], ['f_464', 'cpi_9606.ENSP00000268695', 'cpi_9606.ENSP00000303248', 'cpi_9606.ENSP00000343477', 'f_827'], ['f_502', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000356213', 'f_782', 'cpi_9606.ENSP00000351885'], ['f_340', 'cpi_9606.ENSP00000286091', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000231454', 'cpi_9606.ENSP00000326119'], ['f_689', 'cpi_9606.ENSP00000362329', 'cpi_9606.ENSP00000254810', 'cpi_9606.ENSP00000019103', 'f_676'], ['f_493', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000332369', 'cpi_9606.ENSP00000321999', 'cpi_9606.ENSP00000346067'], ['f_33', 'cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000300061', 'f_631', 'f_343'], ['f_241', 'cpi_9606.ENSP00000303208', 'cpi_9606.ENSP00000376776', 'f_719', 'f_568'], ['cpi_9606.ENSP00000258400', 'f_21', 'cpi_9606.ENSP00000343838', 'f_477', 'cpi_9606.ENSP00000356150'], ['f_593', 'cpi_9606.ENSP00000307900', 'cpi_9606.ENSP00000222330', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000262367'], ['f_642', 'f_813', 'cpi_9606.ENSP00000308032', 'cpi_9606.ENSP00000384957', 'f_486'], ['f_636', 'f_242', 'cpi_9606.ENSP00000305302', 'cpi_9606.ENSP00000251535', 'cpi_9606.ENSP00000308165'], ['f_507', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000295256', 'f_494', 'cpi_9606.ENSP00000343782'], ['f_375', 'f_840', 'cpi_9606.ENSP00000367309', 'cpi_9606.ENSP00000398632', 'f_736'], ['f_704', 'cpi_9606.ENSP00000441691', 'cpi_9606.ENSP00000429374', 'f_508', 'cpi_9606.ENSP00000309572'], ['f_695', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000366506', 'cpi_9606.ENSP00000301146', 'cpi_9606.ENSP00000262187'], ['f_613', 'cpi_9606.ENSP00000352584', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000470087', 'f_409'], ['f_540', 'cpi_9606.ENSP00000345344', 'cpi_9606.ENSP00000346017', 'cpi_9606.ENSP00000216862', 'f_448'], ['f_654', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000333496', 'cpi_9606.ENSP00000270631', 'f_394'], ['f_536', 'f_770', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000282561', 'cpi_9606.ENSP00000013034'], ['f_287', 'cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000353292', 'cpi_9606.ENSP00000348069', 'cpi_9606.ENSP00000466799'], ['f_437', 'cpi_9606.ENSP00000279593', 'cpi_9606.ENSP00000419782', 'cpi_9606.ENSP00000293288', 'f_861'], ['f_671', 'cpi_9606.ENSP00000300738', 'cpi_9606.ENSP00000331358', 'cpi_9606.ENSP00000304895', 'f_609'], ['f_153', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000342070', 'f_801', 'cpi_9606.ENSP00000237527'], ['f_548', 'cpi_9606.ENSP00000219700', 'cpi_9606.ENSP00000359635', 'cpi_9606.ENSP00000327246', 'cpi_9606.ENSP00000288135'], ['f_443', 'cpi_9606.ENSP00000223366', 'cpi_9606.ENSP00000327850', 'cpi_9606.ENSP00000262178', 'cpi_9606.ENSP00000376943'], ['f_368', 'f_398', 'cpi_9606.ENSP00000318822', 'cpi_9606.ENSP00000276414', 'cpi_9606.ENSP00000354610'], ['f_623', 'f_456', 'cpi_9606.ENSP00000262623', 'cpi_9606.ENSP00000316786', 'f_496'], ['cpi_9606.ENSP00000360372', 'f_644', 'cpi_9606.ENSP00000299178', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000278616'], ['f_594', 'cpi_9606.ENSP00000312673', 'cpi_9606.ENSP00000294954', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000261937'], ['f_585', 'cpi_9606.ENSP00000306397', 'f_347', 'cpi_9606.ENSP00000411658', 'cpi_9606.ENSP00000319788'], ['cpi_9606.ENSP00000263817', 'f_116', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000459962'], ['f_199', 'cpi_9606.ENSP00000231751', 'f_522', 'cpi_9606.ENSP00000242057', 'f_480'], ['f_259', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000321988', 'cpi_9606.ENSP00000296871'], ['f_495', 'cpi_9606.ENSP00000397026', 'cpi_9606.ENSP00000263339', 'f_740', 'f_419'], ['f_702', 'f_558', 'cpi_9606.ENSP00000276431', 'cpi_9606.ENSP00000358595', 'f_780'], ['f_244', 'cpi_9606.ENSP00000361850', 'cpi_9606.ENSP00000361666', 'cpi_9606.ENSP00000233242', 'f_738'], ['f_685', 'cpi_9606.ENSP00000329623', 'cpi_9606.ENSP00000355533', 'cpi_9606.ENSP00000314949', 'f_471'], ['f_755', 'f_533', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000355317', 'cpi_9606.ENSP00000292896'], ['f_150', 'cpi_9606.ENSP00000303174', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000220616', 'cpi_9606.ENSP00000363812'], ['f_555', 'cpi_9606.ENSP00000350928', 'cpi_9606.ENSP00000435777', 'cpi_9606.ENSP00000256958', 'f_115'], ['f_686', 'cpi_9606.ENSP00000347754', 'f_650', 'cpi_9606.ENSP00000317379', 'f_473'], ['f_381', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000378323', 'cpi_9606.ENSP00000252723', 'f_475'], ['f_758', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000304767', 'cpi_9606.ENSP00000308845', 'f_489'], ['f_797', 'cpi_9606.ENSP00000261405', 'cpi_9606.ENSP00000331912', 'cpi_9606.ENSP00000347942', 'f_647'], ['cpi_9606.ENSP00000276198', 'f_625', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000274547', 'cpi_9606.ENSP00000196551'], ['f_713', 'cpi_9606.ENSP00000226730', 'f_160', 'f_822', 'cpi_9606.ENSP00000319814'], ['f_633', 'cpi_9606.ENSP00000300289', 'cpi_9606.ENSP00000304501', 'cpi_9606.ENSP00000457706', 'cpi_9606.ENSP00000367102'], ['f_377', 'cpi_9606.ENSP00000387683', 'cpi_9606.ENSP00000330393', 'cpi_9606.ENSP00000362036', 'cpi_9606.ENSP00000331746'], ['f_573', 'cpi_9606.ENSP00000246337', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000264867', 'f_483'], ['f_666', 'cpi_9606.ENSP00000226413', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000388648', 'f_34'], ['f_821', 'cpi_9606.ENSP00000308720', 'cpi_9606.ENSP00000356958', 'f_367', 'f_422'], ['f_663', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000220003', 'f_488', 'cpi_9606.ENSP00000370381'], ['f_353', 'cpi_9606.ENSP00000381607', 'cpi_9606.ENSP00000276571', 'cpi_9606.ENSP00000299267', 'cpi_9606.ENSP00000267119'], ['f_390', 'cpi_9606.ENSP00000358042', 'cpi_9606.ENSP00000379514', 'f_454', 'cpi_9606.ENSP00000310928'], ['f_681', 'cpi_9606.ENSP00000360968', 'cpi_9606.ENSP00000326219', 'f_457', 'cpi_9606.ENSP00000362353'], ['cpi_9606.ENSP00000361125', 'f_157', 'cpi_9606.ENSP00000371985', 'f_759', 'cpi_9606.ENSP00000370912'], ['f_576', 'cpi_9606.ENSP00000354511', 'f_803', 'cpi_9606.ENSP00000200676', 'f_363'], ['f_699', 'cpi_9606.ENSP00000354280', 'f_359', 'f_717', 'cpi_9606.ENSP00000259396'], ['f_560', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000379339', 'cpi_9606.ENSP00000294728'], ['f_442', 'cpi_9606.ENSP00000359998', 'cpi_9606.ENSP00000386171', 'cpi_9606.ENSP00000291294', 'f_559'], ['f_430', 'cpi_9606.ENSP00000430031', 'cpi_9606.ENSP00000320180', 'cpi_9606.ENSP00000320935', 'f_742'], ['f_776', 'cpi_9606.ENSP00000349467', 'cpi_9606.ENSP00000448059', 'f_421', 'f_805'], ['f_577', 'cpi_9606.ENSP00000260302', 'cpi_9606.ENSP00000336630', 'cpi_9606.ENSP00000364310', 'f_605'], ['f_777', 'cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000382659', 'f_461', 'cpi_9606.ENSP00000357283'], ['cpi_9606.ENSP00000272190', 'cpi_9606.ENSP00000353878', 'f_17', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000320866'], ['f_294', 'cpi_9606.ENSP00000318585', 'cpi_9606.ENSP00000384708', 'cpi_9606.ENSP00000311028', 'cpi_9606.ENSP00000378699'], ['f_412', 'cpi_9606.ENSP00000355627', 'cpi_9606.ENSP00000369757', 'cpi_9606.ENSP00000351908', 'f_610'], ['f_418', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000254976', 'f_575', 'cpi_9606.ENSP00000416293'], ['f_674', 'f_860', 'cpi_9606.ENSP00000359211', 'cpi_9606.ENSP00000225964', 'f_514'], ['f_546', 'cpi_9606.ENSP00000356671', 'cpi_9606.ENSP00000251566', 'cpi_9606.ENSP00000467494', 'cpi_9606.ENSP00000302111'], ['f_818', 'cpi_9606.ENSP00000307235', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000428864', 'f_423'], ['f_657', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000379213', 'f_395'], ['f_243', 'cpi_9606.ENSP00000239223', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000381333', 'f_38'], ['f_619', 'cpi_9606.ENSP00000286621', 'cpi_9606.ENSP00000276449', 'cpi_9606.ENSP00000289753', 'cpi_9606.ENSP00000411593'], ['f_487', 'cpi_9606.ENSP00000337103', 'cpi_9606.ENSP00000260356', 'cpi_9606.ENSP00000318646', 'f_756'], ['f_574', 'cpi_9606.ENSP00000392262', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000262441', 'cpi_9606.ENSP00000368104'], ['f_599', 'cpi_9606.ENSP00000370376', 'cpi_9606.ENSP00000341885', 'cpi_9606.ENSP00000243911', 'f_721'], ['f_541', 'cpi_9606.ENSP00000257770', 'f_517', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000327652'], ['f_538', 'cpi_9606.ENSP00000332549', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000245457', 'f_705'], ['f_673', 'cpi_9606.ENSP00000308541', 'f_334', 'f_784', 'cpi_9606.ENSP00000248572'], ['f_567', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000199280', 'cpi_9606.ENSP00000302846', 'cpi_9606.ENSP00000255409'], ['f_607', 'cpi_9606.ENSP00000378306', 'cpi_9606.ENSP00000267843', 'cpi_9606.ENSP00000231228', 'f_687'], ['f_549', 'cpi_9606.ENSP00000264426', 'cpi_9606.ENSP00000318077', 'cpi_9606.ENSP00000228872', 'f_630'], ['f_462', 'cpi_9606.ENSP00000290866', 'cpi_9606.ENSP00000350005', 'f_414', 'cpi_9606.ENSP00000275300'], ['f_665', 'cpi_9606.ENSP00000293190', 'cpi_9606.ENSP00000339527', 'cpi_9606.ENSP00000451605', 'f_563'], ['f_256', 'cpi_9606.ENSP00000341045', 'cpi_9606.ENSP00000216024', 'cpi_9606.ENSP00000333821', 'f_661'], ['f_606', 'cpi_9606.ENSP00000260102', 'cpi_9606.ENSP00000216392', 'cpi_9606.ENSP0

🔄 Processing features: 100%|██████████| 2147/2147 [10:21<00:00,  3.46feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'f_408', 'f_31', 'cpi_9606.ENSP00000326219', 'f_587'], ['cpi_9606.ENSP00000342007', 'f_17', 'cpi_9606.ENSP00000430684', 'f_118', 'f_529'], ['cpi_9606.ENSP00000353820', 'f_131', 'f_26', 'cpi_9606.ENSP00000352011', 'f_791'], ['f_20', 'cpi_9606.ENSP00000333212', 'cpi_9606.ENSP00000295454', 'cpi_9606.ENSP00000286301', 'cpi_9606.ENSP00000357068'], ['f_380', 'cpi_9606.ENSP00000351209', 'cpi_9606.ENSP00000351957', 'f_789', 'f_635'], ['f_143', 'cpi_9606.ENSP00000313490', 'cpi_9606.ENSP00000359424', 'f_726', 'cpi_9606.ENSP00000349320'], ['cpi_9606.ENSP00000328968', 'f_129', 'f_596', 'cpi_9606.ENSP00000343838', 'f_350'], ['f_308', 'cpi_9606.ENSP00000355192', 'f_616', 'cpi_9606.ENSP00000263377', 'f_768'], ['f_335', 'f_511', 'cpi_9606.ENSP00000321584', 'f_47', 'cpi_9606.ENSP00000359353'], ['f_185', 'cpi_9606.ENSP00000354532', 'f_845', 'f_292', 'cpi_9606.ENSP00000221972'], ['f_366', 'cpi_9606.ENSP00000273398', 'f_629', 'cpi_9606.ENSP00000279178', 'f_428'], ['f_192', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000278175'], ['f_451', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000265403', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000445340'], ['f_374', 'cpi_9606.ENSP00000268695', 'f_831', 'cpi_9606.ENSP00000414334', 'cpi_9606.ENSP00000409007'], ['f_405', 'cpi_9606.ENSP00000350928', 'cpi_9606.ENSP00000395653', 'f_413', 'cpi_9606.ENSP00000356094'], ['cpi_9606.ENSP00000270349', 'f_612', 'cpi_9606.ENSP00000003100', 'f_510', 'cpi_9606.ENSP00000301891'], ['f_528', 'cpi_9606.ENSP00000362508', 'cpi_9606.ENSP00000341390', 'f_43', 'cpi_9606.ENSP00000355629'], ['f_571', 'cpi_9606.ENSP00000277010', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000288139'], ['f_617', 'cpi_9606.ENSP00000394033', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000394936'], ['f_391', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000259271', 'f_866', 'f_719'], ['cpi_9606.ENSP00000311032', 'f_166', 'cpi_9606.ENSP00000367848', 'f_151', 'f_551'], ['f_346', 'cpi_9606.ENSP00000320866', 'cpi_9606.ENSP00000344674', 'cpi_9606.ENSP00000263126', 'cpi_9606.ENSP00000319788'], ['f_146', 'cpi_9606.ENSP00000277541', 'f_526', 'cpi_9606.ENSP00000236671', 'f_328'], ['f_439', 'cpi_9606.ENSP00000354107', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000295491', 'f_622'], ['f_452', 'cpi_9606.ENSP00000381097', 'f_25', 'cpi_9606.ENSP00000397026', 'f_757'], ['f_643', 'cpi_9606.ENSP00000345096', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000367851', 'f_27'], ['f_656', 'cpi_9606.ENSP00000362924', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000411593'], ['f_299', 'cpi_9606.ENSP00000338160', 'cpi_9606.ENSP00000387946', 'cpi_9606.ENSP00000295834', 'cpi_9606.ENSP00000360493'], ['f_341', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000329357'], ['f_257', 'cpi_9606.ENSP00000279387', 'cpi_9606.ENSP00000447149', 'f_836', 'cpi_9606.ENSP00000359285'], ['f_339', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000256383', 'f_834'], ['f_186', 'cpi_9606.ENSP00000283635', 'cpi_9606.ENSP00000218548', 'cpi_9606.ENSP00000389338', 'f_202'], ['f_393', 'cpi_9606.ENSP00000287878', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000354476', 'cpi_9606.ENSP00000295452'], ['f_3', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000367102', 'cpi_9606.ENSP00000220003', 'f_773'], ['f_535', 'cpi_9606.ENSP00000359719', 'f_330', 'f_830', 'f_497'], ['cpi_9606.ENSP00000265724', 'f_455', 'f_417', 'f_764', 'cpi_9606.ENSP00000286479'], ['f_712', 'cpi_9606.ENSP00000378323', 'f_767', 'f_771', 'f_35'], ['f_2', 'cpi_9606.ENSP00000349576', 'cpi_9606.ENSP00000262888', 'cpi_9606.ENSP00000470087', 'f_788'], ['cpi_9606.ENSP00000356438', 'f_216', 'f_336', 'f_427', 'f_343'], ['cpi_9606.ENSP00000258743', 'f_454', 'cpi_9606.ENSP00000261937', 'f_207', 'cpi_9606.ENSP00000226444'], ['f_566', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000454071', 'cpi_9606.ENSP00000260010', 'f_327'], ['f_180', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000302886', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000242057'], ['f_614', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000332369', 'cpi_9606.ENSP00000364802', 'f_749'], ['cpi_9606.ENSP00000367959', 'f_588', 'cpi_9606.ENSP00000301633', 'cpi_9606.ENSP00000372547', 'f_583'], ['f_666', 'cpi_9606.ENSP00000357669', 'cpi_9606.ENSP00000252723', 'f_725', 'cpi_9606.ENSP00000262352'], ['f_338', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000257290', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000216185'], ['f_697', 'cpi_9606.ENSP00000216962', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000233146', 'cpi_9606.ENSP00000216037'], ['f_659', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000332296', 'cpi_9606.ENSP00000312455'], ['f_696', 'cpi_9606.ENSP00000238018', 'cpi_9606.ENSP00000360773', 'cpi_9606.ENSP00000428340', 'f_436'], ['f_638', 'f_242', 'cpi_9606.ENSP00000225275', 'f_401', 'f_675'], ['f_645', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000348786', 'cpi_9606.ENSP00000264637', 'cpi_9606.ENSP00000304822'], ['f_12', 'cpi_9606.ENSP00000364212', 'cpi_9606.ENSP00000297268', 'cpi_9606.ENSP00000343477', 'f_670'], ['f_672', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000301420', 'cpi_9606.ENSP00000299267', 'f_229'], ['f_646', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000342235'], ['f_683', 'cpi_9606.ENSP00000314649', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000240652', 'f_505'], ['f_540', 'cpi_9606.ENSP00000233944', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000361359'], ['f_420', 'cpi_9606.ENSP00000312326', 'f_297', 'cpi_9606.ENSP00000378517', 'cpi_9606.ENSP00000344352'], ['f_682', 'cpi_9606.ENSP00000355155', 'f_715', 'f_839', 'cpi_9606.ENSP00000274793'], ['f_406', 'cpi_9606.ENSP00000352035', 'cpi_9606.ENSP00000374323', 'f_820', 'cpi_9606.ENSP00000341828'], ['f_392', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000292427', 'f_194'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000302846', 'f_22', 'f_728', 'f_785'], ['f_241', 'f_132', 'cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000308165', 'f_509'], ['f_569', 'cpi_9606.ENSP00000305221', 'f_214', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000451040'], ['f_464', 'cpi_9606.ENSP00000234310', 'cpi_9606.ENSP00000309124', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000267843'], ['f_181', 'cpi_9606.ENSP00000370129', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000262367', 'f_167'], ['f_287', 'cpi_9606.ENSP00000241052', 'f_736', 'cpi_9606.ENSP00000337335', 'f_722'], ['f_493', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000327850', 'f_361'], ['f_684', 'cpi_9606.ENSP00000368349', 'f_554', 'f_474', 'cpi_9606.ENSP00000258749'], ['f_637', 'cpi_9606.ENSP00000376914', 'cpi_9606.ENSP00000297316', 'f_466', 'f_799'], ['cpi_9606.ENSP00000337450', 'f_778', 'f_763', 'f_262', 'cpi_9606.ENSP00000244217'], ['f_440', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000262948', 'cpi_9606.ENSP00000259396', 'cpi_9606.ENSP00000353292'], ['f_33', 'cpi_9606.ENSP00000346768', 'f_706', 'cpi_9606.ENSP00000358730', 'f_298'], ['f_639', 'cpi_9606.ENSP00000367309', 'cpi_9606.ENSP00000266376', 'f_460', 'f_508'], ['f_611', 'cpi_9606.ENSP00000303208', 'cpi_9606.ENSP00000427514', 'cpi_9606.ENSP00000408860', 'f_46'], ['f_553', 'cpi_9606.ENSP00000254488', 'cpi_9606.ENSP00000272847', 'cpi_9606.ENSP00000398632', 'cpi_9606.ENSP00000285381'], ['f_602', 'cpi_9606.ENSP00000304811', 'f_833', 'cpi_9606.ENSP00000331746', 'cpi_9606.ENSP00000323568'], ['f_345', 'cpi_9606.ENSP00000258662', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000358548', 'f_861'], ['f_145', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000290349', 'cpi_9606.ENSP00000261196', 'f_631'], ['f_19', 'cpi_9606.ENSP00000354193', 'cpi_9606.ENSP00000331912', 'cpi_9606.ENSP00000417229', 'f_676'], ['f_365', 'cpi_9606.ENSP00000364257', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000369375'], ['f_340', 'cpi_9606.ENSP00000319814', 'cpi_9606.ENSP00000349252', 'cpi_9606.ENSP00000231454', 'cpi_9606.ENSP00000326119'], ['f_16', 'cpi_9606.ENSP00000307599', 'cpi_9606.ENSP00000341045', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000362401'], ['f_613', 'cpi_9606.ENSP00000352584', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000365380', 'f_827'], ['cpi_9606.ENSP00000324648', 'f_459', 'cpi_9606.ENSP00000286648', 'f_164', 'f_812'], ['f_353', 'cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000225474', 'cpi_9606.ENSP00000294954', 'f_826'], ['f_604', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000441691', 'f_407', 'f_792'], ['f_213', 'cpi_9606.ENSP00000226730', 'f_473', 'cpi_9606.ENSP00000358784', 'cpi_9606.ENSP00000320935'], ['f_579', 'cpi_9606.ENSP00000373674', 'cpi_9606.ENSP00000291700', 'f_729', 'cpi_9606.ENSP00000282561'], ['f_633', 'cpi_9606.ENSP00000216714', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000457706', 'f_840'], ['f_390', 'cpi_9606.ENSP00000323867', 'cpi_9606.ENSP00000264867', 'f_448', 'cpi_9606.ENSP00000361666'], ['cpi_9606.ENSP00000338345', 'f_153', 'f_116', 'cpi_9606.ENSP00000318585', 'cpi_9606.ENSP00000248553'], ['f_699', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000358107', 'f_488', 'f_477'], ['cpi_9606.ENSP00000360372', 'f_644', 'f_200', 'cpi_9606.ENSP00000261693', 'cpi_9606.ENSP00000220616'], ['f_685', 'cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000385806', 'f_429', 'cpi_9606.ENSP00000263321'], ['f_15', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000252809', 'cpi_9606.ENSP00000346598'], ['f_692', 'cpi_9606.ENSP00000286621', 'cpi_9606.ENSP00000311095', 'f_533', 'f_815'], ['cpi_9606.ENSP00000261707', 'f_624', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000311028', 'f_230'], ['f_698', 'cpi_9606.ENSP00000364709', 'f_388', 'f_813', 'cpi_9606.ENSP00000275525'], ['f_580', 'cpi_9606.ENSP00000363965', 'cpi_9606.ENSP00000372750', 'f_568', 'cpi_9606.ENSP00000376943'], ['f_619', 'cpi_9606.ENSP00000296411', 'cpi_9606.ENSP00000296871', 'cpi_9606.ENSP00000221421', 'f_750'], ['f_628', 'cpi_9606.ENSP00000264426', 'cpi_9606.ENSP00000252486', 'f_782', 'f_860'], ['f_502', 'cpi_9606.ENSP00000279593', 'cpi_9606.ENSP00000416293', 'f_653', 'cpi_9606.ENSP00000344192'], ['f_573', 'cpi_9606.ENSP00000322991', 'cpi_9606.ENSP00000316786', 'cpi_9606.ENSP00000343040', 'cpi_9606.ENSP00000354394'], ['f_293', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000256958', 'cpi_9606.ENSP00000376178'], ['f_594', 'cpi_9606.ENSP00000305742', 'cpi_9606.ENSP00000366307', 'cpi_9606.ENSP00000389414', 'f_647'], ['f_597', 'cpi_9606.ENSP00000360967', 'cpi_9606.ENSP00000411658', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000262999'], ['f_368', 'f_394', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000353427', 'cpi_9606.ENSP00000231228'], ['f_615', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000335511', 'f_419', 'cpi_9606.ENSP00000410294'], ['f_691', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000412673', 'f_717'], ['f_516', 'cpi_9606.ENSP00000362329', 'cpi_9606.ENSP00000339527', 'f_609', 'f_409'], ['f_623', 'f_456', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000362036', 'cpi_9606.ENSP00000370473'], ['f_443', 'cpi_9606.ENSP00000337746', 'cpi_9606.ENSP00000301974', 'f_752', 'f_770'], ['f_704', 'cpi_9606.ENSP00000257770', 'f_475', 'f_518', 'cpi_9606.ENSP00000312664'], ['cpi_9606.ENSP00000295897', 'f_215', 'f_621', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000263980'], ['f_586', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000386884', 'cpi_9606.ENSP00000261799'], ['f_37', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000234071', 'f_159'], ['f_244', 'cpi_9606.ENSP00000239223', 'cpi_9606.ENSP00000262461', 'f_801', 'f_423'], ['f_592', 'cpi_9606.ENSP00000362441', 'cpi_9606.ENSP00000351908', 'cpi_9606.ENSP00000301178', 'f_740'], ['f_23', 'cpi_9606.ENSP00000350616', 'f_195', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000251535'], ['f_671', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000379330', 'cpi_9606.ENSP00000357283', 'f_650'], ['f_150', 'cpi_9606.ENSP00000308032', 'cpi_9606.ENSP00000309845', 'f_363', 'cpi_9606.ENSP00000410732'], ['f_654', 'cpi_9606.ENSP00000299855', 'cpi_9606.ENSP00000376776', 'f_347', 'cpi_9606.ENSP00000312029'], ['f_560', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000467676', 'cpi_9606.ENSP00000386171', 'cpi_9606.ENSP00000222330'], ['f_655', 'cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000356958', 'f_494'], ['cpi_9606.ENSP00000293288', 'f_349', 'f_522', 'cpi_9606.ENSP00000272298', 'cpi_9606.ENSP00000448059'], ['cpi_9606.ENSP00000219833', 'f_673', 'cpi_9606.ENSP00000340820', 'cpi_9606.ENSP00000276449', 'cpi_9606.ENSP00000241261'], ['f_337', 'cpi_9606.ENSP00000303211', 'f_378', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000365016'], ['f_536', 'cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000245457', 'cpi_9606.ENSP00000385026', 'f_24'], ['f_581', 'cpi_9606.ENSP00000285979', 'cpi_9606.ENSP00000319591', 'f_496', 'cpi_9606.ENSP00000307235'], ['f_657', 'cpi_9606.ENSP00000362513', 'cpi_9606.ENSP00000253004', 'f_367', 'f_558'], ['cpi_9606.ENSP00000270202', 'f_34', 'cpi_9606.ENSP00000386029', 'f_398', 'cpi_9606.ENSP00000245539'], ['f_537', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000299178', 'f_514', 'cpi_9606.ENSP00000301634'], ['f_432', 'cpi_9606.ENSP00000363868', 'f_160', 'cpi_9606.ENSP00000255409', 'f_486'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000227758', 'f_115', 'cpi_9606.ENSP00000274547'], ['f_333', 'cpi_9606.ENSP00000430031', 'cpi_9606.ENSP00000419692', 'f_543', 'f_517'], ['f_193', 'f_489', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000355930', 'cpi_9606.ENSP00000253727'], ['f_248', 'cpi_9606.ENSP00000262623', 'cpi_9606.ENSP00000277120', 'f_30', 'f_471'], ['f_821', 'f_425', 'cpi_9606.ENSP00000335620', 'cpi_9606.ENSP00000307259', 'cpi_9606.ENSP00000363812'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000234961', 'f_314', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000370381'], ['f_680', 'cpi_9606.ENSP00000471569', 'cpi_9606.ENSP00000350785', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000226574'], ['f_689', 'cpi_9606.ENSP00000297792', 'cpi_9606.ENSP00000347942', 'cpi_9606.ENSP00000348069', 'f_411'], ['f_300', 'cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000320401', 'cpi_9606.ENSP00000164139'], ['f_567', 'cpi_9606.ENSP00000374467', 'cpi_9606.ENSP00000356954', 'f_467', 'f_513'], ['f_498', 'cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000297350', 'f_759'], ['f_667', 'cpi_9606.ENSP00000427562', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000294728', 'f_822'], ['f_555', 'cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000225927', 'cpi_9606.ENSP00000354558', 'f_803'], ['f_450', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000273550', 'f_625', 'f_711'], ['f_641', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000355657', 'cpi_9606.ENSP00000300061', 'f_422'], ['f_375', 'cpi_9606.ENSP00000338627', 'cpi_9606.ENSP00000232219', 'cpi_9606.ENSP00000324248', 'f_559'], ['f_542', 'cpi_9606.ENSP00000248923', 'cpi_9606.ENSP00000216341', 'f_483', 'cpi_9606.ENSP00000233242'], ['f_294', 'cpi_9606.ENSP00000338018', 'cpi_9606.ENSP00000399168', 'f_157', 'cpi_9606.ENSP00000260356'], ['cpi_9606.ENSP00000354612', 'f_250', 'f_610', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000200676'], ['f_449', 'cpi_9606.ENSP00000332549', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000463999', 'f_630'], ['f_709', 'cpi_9606.ENSP00000364782', 'cpi_9606.ENSP00000239938', 'f_461', 'cpi_9606.ENSP00000365775'], ['f_546', 'cpi_9606.ENSP00000307900', 'cpi_9606.ENSP00000358903', 'f_605', 'cpi_9606.ENSP00000307014'], ['f_199', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000342070', 'f_395', 'f_738'], ['f_507', 'cpi_9606.ENSP00000417281', 'cpi_9606.ENSP00000217305', 'f_515', 'cpi_9606.ENSP00000466799'], ['f_755', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000275300', 'f_301', 'cpi_9606.ENSP00000374265'], ['cpi_9606.ENSP00000215832', 'f_694', 'f_305', 'cpi_9606.ENSP00000267119', 'cpi_9606.ENSP00000260191'], ['f_286', 'cpi_9606.ENSP00000363533', 'cpi_9606.ENSP00000296545', 'f_742', 'f_480'], ['f_663', 'cpi_9606.ENSP00000263923', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000365686', 'f_457'], ['f_818', 'cpi_9606.ENSP00000304767', 'cpi_9606.ENSP00000308845', 'f_652', 'cpi_9606.ENSP00000287936'], ['f_243', 'cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000347979', 'cpi_9606.ENSP00000317379', 'f_780'], ['f_539', 'cpi_9606.ENSP00000211122', 'cpi_9606.ENSP00000356671', 'f_144', 'cpi_9606.ENSP00000410076'], ['cpi_9606.ENSP00000258400', 'f_21', 'cpi_9606.ENSP00000252804', 'cpi_9606.ENSP00000267101', 'cpi_9606.ENSP00000221515'], ['f_758', 'cpi_9606.ENSP00000296122', 'cpi_9606.ENSP00000261465', 'f_421', 'cpi_9606.ENSP00000362649'], ['f_593', 'cpi_9606.ENSP00000262160', 'cpi_9606.ENSP00000365663', 'cpi_9606.ENSP00000264657', 'cpi_9606.ENSP00000260970'], ['f_688', 'cpi_9606.ENSP00000272317', 'f_359', 'cpi_9606.ENSP00000278616', 'f_805'], ['f_442', 'cpi_9606.ENSP00000001008', 'cpi_9606.ENSP00000356213', 'cpi_9606.ENSP00000330393', 'f_575'], ['f_549', 'cpi_9606.ENSP00000349577', 'cpi_9606.ENSP00000296511', 'f_227', 'cpi_9606.ENSP00000379213'], ['f_430', 'cpi_9606.ENSP00000443459', 'cpi_9606.ENSP00000363804', 'f_721', 'cpi_9606.ENSP00000366506'], ['f_453', 'cpi_9606.ENSP00000353791', 'cpi_9606.ENSP00000260227', 'f_705', 'cpi_9606.ENSP00000270776'], ['f_434', 'cpi_9606.ENSP00000276590', 'cpi_9606.ENSP00000262735', 'f_260', 'cpi_9606.ENSP00000218099'], ['f_574', 'cpi_9606.ENSP00000327255', 'f_397', 'cpi_9606.ENSP00000266682', 'f_465'], ['f_377', 'cpi_9606.ENSP00000332973', 'cpi_9606.ENSP00000322421', 'f_334', 'f_687'], ['f_686', 'cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000270474', 'cpi_9606.ENSP00000428924', 'f_364'], ['f_585', 'cpi_9606.ENSP00000296046', 'cpi_9606.ENSP00000384708', 'f_661', 'cpi_9606.ENSP00000318822'], ['f_702', 'cpi_9606.ENSP00000276431', 'cpi_9606.ENSP00000359100', 'cpi_9606.ENSP00000380247', 'f_458'], ['f_800', 'cpi_9606.ENSP00000261405', 'cpi_9606.ENSP00000372023', 'f_38', 'cpi_9606.ENSP00000285930'], ['cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000320709', 'cpi_9606.ENSP00000338072', 'f_500', 'cpi_9606.ENSP00000420168'], ['f_797', 'cpi_9606.ENSP00000295453', 'cpi_9606.ENSP00000292513', 'cpi_9606.ENSP00000302111', 'f_414'], ['f_662', 'cpi_9606.ENSP00000296522', 'cpi_9606.ENSP00000219919', 'cpi_9606.ENSP00000293745', 'f_658'], ['f_606', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000246337', 'f_737', 'cpi_9606.ENSP00000011653'], ['cpi_9606.ENSP00000398698', 'cpi_9606.ENSP00000300151', 'cpi_9606.ENSP00000216392', 'f_206', 'f_531'], ['f_545', 'cpi_9606.ENSP00000263269', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000382659', 'f_563'], ['f_418', 'cpi_9606.ENSP00000295256', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000309757', 'f_249'], ['cpi_9606.ENSP00000276198', 'cpi_9606.ENSP00000269571', 'cpi_9606.ENSP00000382250', 'f_499', 'cpi_9606.ENSP00000387683'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000292896', 'cpi_9606.ENSP00000307240', 'f_734', 'f_187'], ['f_651', 'cpi_9606.ENSP00000327801', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000231449', 'f_532'], ['f_600', 'cpi_9606.ENSP00000364801', 'f_701', 'cpi_9606.ENSP00000360991', 'cpi_9606.ENSP00000303452'], ['f_636', 'cpi_9606.ENSP00000337103', 'cpi_9606.ENSP00000459962', 'f_462', 'cpi_9606.ENSP00000402152'], ['f_642', 'cpi_9606.ENSP00000337773', 'cpi_9606.ENSP00000328173', 'cpi_9606.ENSP00000304895', 'f_383'], ['f_710', 'cpi_9606.ENSP00000305692', 'cpi_9606.ENSP00000255465', 'cpi_9606.ENSP00000384273', 'cpi_9606.ENSP00000336630'], ['f_777', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000354610', 'cpi_9606.ENSP00000380252', 'f_601'], ['f_259', 'cpi_9606.ENSP00000303522', 'cpi_9606.ENSP00000314508', 'cpi_9606.ENSP0000

🔄 Processing features: 100%|██████████| 2147/2147 [10:21<00:00,  3.46feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'f_413', 'f_26', 'cpi_9606.ENSP00000286648', 'f_831'], ['f_308', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000381097', 'f_791'], ['cpi_9606.ENSP00000353820', 'f_131', 'cpi_9606.ENSP00000352011', 'f_510', 'cpi_9606.ENSP00000360773'], ['f_366', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000374265', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000279178'], ['f_20', 'cpi_9606.ENSP00000254488', 'f_729', 'cpi_9606.ENSP00000369530', 'f_629'], ['f_405', 'cpi_9606.ENSP00000305742', 'f_726', 'cpi_9606.ENSP00000395653', 'cpi_9606.ENSP00000295452'], ['cpi_9606.ENSP00000360372', 'f_132', 'f_194', 'f_292', 'cpi_9606.ENSP00000353362'], ['cpi_9606.ENSP00000356438', 'f_213', 'f_706', 'f_408', 'f_496'], ['f_181', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000356094'], ['f_374', 'cpi_9606.ENSP00000388107', 'f_768', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000409007'], ['f_391', 'cpi_9606.ENSP00000313490', 'cpi_9606.ENSP00000430684', 'f_845', 'cpi_9606.ENSP00000304822'], ['cpi_9606.ENSP00000328968', 'f_129', 'f_455', 'f_494', 'cpi_9606.ENSP00000343838'], ['f_566', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000355629', 'f_836', 'cpi_9606.ENSP00000370254'], ['f_451', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000352900'], ['f_186', 'cpi_9606.ENSP00000345096', 'f_31', 'f_511', 'f_118'], ['f_341', 'cpi_9606.ENSP00000359334', 'f_789', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000334198'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000262352', 'f_635', 'f_749', 'f_22'], ['f_192', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000364212', 'f_47', 'cpi_9606.ENSP00000301891'], ['f_346', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000256383', 'f_428', 'cpi_9606.ENSP00000394936'], ['cpi_9606.ENSP00000342007', 'f_347', 'cpi_9606.ENSP00000216037', 'f_587', 'f_167'], ['f_338', 'cpi_9606.ENSP00000321584', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000359353', 'cpi_9606.ENSP00000000442'], ['cpi_9606.ENSP00000367959', 'f_588', 'cpi_9606.ENSP00000003100', 'f_411', 'f_195'], ['f_643', 'cpi_9606.ENSP00000354532', 'cpi_9606.ENSP00000332296', 'f_151', 'cpi_9606.ENSP00000277010'], ['f_12', 'cpi_9606.ENSP00000268695', 'cpi_9606.ENSP00000414334', 'f_529', 'f_725'], ['f_659', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000387946', 'f_616'], ['f_335', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000394033', 'f_466', 'cpi_9606.ENSP00000367848'], ['f_571', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000262367', 'f_736'], ['cpi_9606.ENSP00000311032', 'f_394', 'f_497', 'f_207', 'f_43'], ['f_339', 'cpi_9606.ENSP00000335592', 'f_773', 'cpi_9606.ENSP00000259089', 'f_799'], ['f_380', 'cpi_9606.ENSP00000355533', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000347942', 'cpi_9606.ENSP00000386306'], ['f_2', 'cpi_9606.ENSP00000238018', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000372547'], ['f_443', 'cpi_9606.ENSP00000312326', 'f_328', 'f_830', 'cpi_9606.ENSP00000298472'], ['f_406', 'cpi_9606.ENSP00000376914', 'cpi_9606.ENSP00000374323', 'f_728', 'f_526'], ['f_617', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000352035', 'f_820', 'cpi_9606.ENSP00000342235'], ['cpi_9606.ENSP00000222982', 'f_778', 'f_164', 'cpi_9606.ENSP00000216962', 'f_763'], ['f_614', 'cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000316786', 'f_771'], ['f_638', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000268251', 'f_757', 'f_866'], ['f_185', 'cpi_9606.ENSP00000364782', 'f_27', 'cpi_9606.ENSP00000312455', 'cpi_9606.ENSP00000263339'], ['f_645', 'cpi_9606.ENSP00000360967', 'cpi_9606.ENSP00000348461', 'cpi_9606.ENSP00000222256', 'f_229'], ['f_420', 'cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000304408', 'f_767', 'f_327'], ['cpi_9606.ENSP00000337450', 'f_715', 'f_262', 'f_583', 'cpi_9606.ENSP00000301634'], ['f_19', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000264818', 'cpi_9606.ENSP00000417229'], ['f_602', 'cpi_9606.ENSP00000304811', 'f_839', 'cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000467676'], ['f_597', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000343925', 'f_166', 'cpi_9606.ENSP00000278175'], ['f_452', 'cpi_9606.ENSP00000354193', 'f_25', 'cpi_9606.ENSP00000259396', 'cpi_9606.ENSP00000378517'], ['f_440', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000233146', 'f_792', 'f_297'], ['f_683', 'cpi_9606.ENSP00000233944', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000305422', 'f_436'], ['f_528', 'cpi_9606.ENSP00000362508', 'cpi_9606.ENSP00000308774', 'cpi_9606.ENSP00000262888', 'f_330'], ['f_143', 'cpi_9606.ENSP00000225927', 'cpi_9606.ENSP00000222330', 'f_675', 'cpi_9606.ENSP00000263126'], ['f_637', 'cpi_9606.ENSP00000332256', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000344352', 'f_788'], ['f_656', 'cpi_9606.ENSP00000234389', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000216185', 'f_785'], ['f_464', 'cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000264637', 'cpi_9606.ENSP00000258749', 'cpi_9606.ENSP00000343040'], ['f_180', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000291294', 'f_46'], ['f_540', 'cpi_9606.ENSP00000287878', 'cpi_9606.ENSP00000221972', 'cpi_9606.ENSP00000263980', 'f_460'], ['f_393', 'cpi_9606.ENSP00000323867', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000354476', 'f_202'], ['cpi_9606.ENSP00000265724', 'f_401', 'f_417', 'f_505', 'f_509'], ['f_704', 'cpi_9606.ENSP00000441691', 'cpi_9606.ENSP00000309649', 'f_554', 'f_473'], ['f_611', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000333212', 'f_214', 'cpi_9606.ENSP00000451040'], ['f_646', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000261196', 'cpi_9606.ENSP00000294728'], ['f_697', 'cpi_9606.ENSP00000357669', 'cpi_9606.ENSP00000445340', 'cpi_9606.ENSP00000257290', 'cpi_9606.ENSP00000389414'], ['f_146', 'cpi_9606.ENSP00000290349', 'cpi_9606.ENSP00000366307', 'cpi_9606.ENSP00000220616', 'f_670'], ['cpi_9606.ENSP00000270349', 'f_522', 'f_812', 'f_409', 'cpi_9606.ENSP00000225474'], ['f_712', 'cpi_9606.ENSP00000218548', 'f_834', 'f_35', 'cpi_9606.ENSP00000283635'], ['f_365', 'cpi_9606.ENSP00000295834', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000327431', 'cpi_9606.ENSP00000470087'], ['f_299', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000234590', 'f_622', 'cpi_9606.ENSP00000320935'], ['f_535', 'cpi_9606.ENSP00000297261', 'cpi_9606.ENSP00000358548', 'f_722', 'cpi_9606.ENSP00000408860'], ['f_682', 'cpi_9606.ENSP00000397026', 'cpi_9606.ENSP00000447173', 'f_343', 'cpi_9606.ENSP00000242057'], ['f_392', 'cpi_9606.ENSP00000314649', 'cpi_9606.ENSP00000356213', 'cpi_9606.ENSP00000262999', 'f_815'], ['cpi_9606.ENSP00000324648', 'f_454', 'cpi_9606.ENSP00000306138', 'f_206', 'f_298'], ['f_300', 'cpi_9606.ENSP00000330237', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000349577', 'cpi_9606.ENSP00000266376'], ['f_145', 'cpi_9606.ENSP00000256958', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000348234', 'f_631'], ['f_615', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000454071', 'f_477', 'f_833'], ['f_579', 'cpi_9606.ENSP00000349576', 'cpi_9606.ENSP00000428924', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000343477'], ['f_257', 'cpi_9606.ENSP00000314949', 'cpi_9606.ENSP00000362513', 'cpi_9606.ENSP00000398632', 'f_361'], ['f_639', 'cpi_9606.ENSP00000319591', 'f_427', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000337335'], ['f_390', 'cpi_9606.ENSP00000352584', 'cpi_9606.ENSP00000218758', 'cpi_9606.ENSP00000435591', 'f_448'], ['f_684', 'cpi_9606.ENSP00000295400', 'cpi_9606.ENSP00000317379', 'f_474', 'cpi_9606.ENSP00000353292'], ['f_536', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000353791', 'f_770', 'cpi_9606.ENSP00000360493'], ['f_641', 'cpi_9606.ENSP00000279387', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000252723', 'f_676'], ['f_623', 'cpi_9606.ENSP00000230671', 'f_456', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000231454'], ['f_23', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000216862', 'f_160'], ['f_699', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000261405', 'f_533', 'f_350'], ['f_672', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000263321', 'cpi_9606.ENSP00000282561', 'cpi_9606.ENSP00000362036'], ['f_689', 'cpi_9606.ENSP00000244217', 'cpi_9606.ENSP00000295454', 'cpi_9606.ENSP00000286301', 'f_647'], ['f_3', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000367102', 'cpi_9606.ENSP00000343204'], ['f_368', 'cpi_9606.ENSP00000346768', 'f_398', 'cpi_9606.ENSP00000231228', 'cpi_9606.ENSP00000301178'], ['f_516', 'cpi_9606.ENSP00000379802', 'cpi_9606.ENSP00000326219', 'cpi_9606.ENSP00000389338', 'f_764'], ['f_613', 'cpi_9606.ENSP00000362924', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000319788'], ['f_16', 'cpi_9606.ENSP00000305302', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000356150'], ['f_594', 'cpi_9606.ENSP00000332549', 'cpi_9606.ENSP00000251535', 'f_388', 'cpi_9606.ENSP00000254227'], ['f_287', 'cpi_9606.ENSP00000241052', 'f_752', 'f_694', 'cpi_9606.ENSP00000312029'], ['f_340', 'cpi_9606.ENSP00000286091', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000344192'], ['f_667', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000358107', 'f_407', 'f_518'], ['f_439', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000308845', 'f_827'], ['f_33', 'cpi_9606.ENSP00000301633', 'cpi_9606.ENSP00000358730', 'cpi_9606.ENSP00000297350', 'cpi_9606.ENSP00000307599'], ['f_586', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000267377', 'f_551'], ['f_569', 'cpi_9606.ENSP00000354107', 'cpi_9606.ENSP00000273550', 'f_861', 'cpi_9606.ENSP00000308165'], ['cpi_9606.ENSP00000258743', 'f_558', 'cpi_9606.ENSP00000261937', 'cpi_9606.ENSP00000234071', 'f_801'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000310447', 'f_742', 'f_513', 'f_486'], ['f_15', 'cpi_9606.ENSP00000320401', 'cpi_9606.ENSP00000380318', 'f_719', 'cpi_9606.ENSP00000376943'], ['f_692', 'cpi_9606.ENSP00000286621', 'f_475', 'cpi_9606.ENSP00000457706', 'cpi_9606.ENSP00000376776'], ['cpi_9606.ENSP00000354612', 'f_515', 'f_242', 'f_508', 'f_782'], ['f_666', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000294954', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000367851'], ['f_37', 'f_230', 'cpi_9606.ENSP00000267119', 'cpi_9606.ENSP00000234371', 'cpi_9606.ENSP00000267843'], ['f_493', 'cpi_9606.ENSP00000295453', 'cpi_9606.ENSP00000303522', 'f_429', 'cpi_9606.ENSP00000226574'], ['f_353', 'cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000253004', 'f_826', 'cpi_9606.ENSP00000361359'], ['f_671', 'cpi_9606.ENSP00000330199', 'cpi_9606.ENSP00000379330', 'cpi_9606.ENSP00000357283', 'f_609'], ['f_695', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000259271', 'cpi_9606.ENSP00000359635', 'f_822'], ['f_342', 'cpi_9606.ENSP00000396704', 'f_159', 'cpi_9606.ENSP00000463999', 'f_568'], ['f_337', 'f_215', 'cpi_9606.ENSP00000260970', 'cpi_9606.ENSP00000312673', 'f_543'], ['f_680', 'cpi_9606.ENSP00000471569', 'cpi_9606.ENSP00000306100', 'cpi_9606.ENSP00000365016', 'cpi_9606.ENSP00000326119'], ['f_193', 'f_644', 'cpi_9606.ENSP00000225275', 'f_471', 'cpi_9606.ENSP00000309572'], ['f_548', 'cpi_9606.ENSP00000399168', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000275525'], ['f_702', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000296871', 'cpi_9606.ENSP00000466799', 'f_514'], ['f_377', 'cpi_9606.ENSP00000279593', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000354394', 'f_740'], ['f_655', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000274793', 'cpi_9606.ENSP00000293288'], ['f_698', 'cpi_9606.ENSP00000364709', 'cpi_9606.ENSP00000297316', 'f_419', 'cpi_9606.ENSP00000348897'], ['f_199', 'cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000356954', 'f_216', 'cpi_9606.ENSP00000344674'], ['f_592', 'cpi_9606.ENSP00000248935', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000252809', 'cpi_9606.ENSP00000261799'], ['f_628', 'cpi_9606.ENSP00000216714', 'cpi_9606.ENSP00000427514', 'f_840', 'f_653'], ['f_580', 'cpi_9606.ENSP00000305221', 'cpi_9606.ENSP00000331746', 'cpi_9606.ENSP00000323568', 'f_721'], ['f_619', 'cpi_9606.ENSP00000297792', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000276449', 'f_750'], ['f_345', 'cpi_9606.ENSP00000337354', 'cpi_9606.ENSP00000200676', 'cpi_9606.ENSP00000295491', 'f_116'], ['f_663', 'cpi_9606.ENSP00000363868', 'f_813', 'f_488', 'cpi_9606.ENSP00000312664'], ['f_432', 'f_422', 'cpi_9606.ENSP00000374467', 'cpi_9606.ENSP00000329357', 'cpi_9606.ENSP00000267101'], ['f_553', 'cpi_9606.ENSP00000338627', 'cpi_9606.ENSP00000272847', 'cpi_9606.ENSP00000252486', 'f_336'], ['f_696', 'cpi_9606.ENSP00000359719', 'cpi_9606.ENSP00000339527', 'cpi_9606.ENSP00000361666', 'f_363'], ['f_502', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000300061', 'f_860'], ['f_293', 'cpi_9606.ENSP00000276431', 'cpi_9606.ENSP00000365380', 'cpi_9606.ENSP00000355930', 'f_738'], ['f_507', 'cpi_9606.ENSP00000239849', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000320866', 'cpi_9606.ENSP00000245539'], ['f_797', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000332369', 'f_483'], ['f_375', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000295256', 'f_115', 'cpi_9606.ENSP00000155840'], ['f_574', 'cpi_9606.ENSP00000327255', 'cpi_9606.ENSP00000330393', 'f_359', 'cpi_9606.ENSP00000358595'], ['f_418', 'cpi_9606.ENSP00000266682', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000311028', 'f_625'], ['f_818', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000292896', 'cpi_9606.ENSP00000311095', 'f_34'], ['f_549', 'cpi_9606.ENSP00000264426', 'cpi_9606.ENSP00000348069', 'f_803', 'f_759'], ['f_600', 'cpi_9606.ENSP00000350928', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000261693', 'f_227'], ['cpi_9606.ENSP00000338345', 'f_188', 'cpi_9606.ENSP00000219919', 'f_489', 'cpi_9606.ENSP00000428340'], ['f_821', 'f_30', 'cpi_9606.ENSP00000335620', 'cpi_9606.ENSP00000264867', 'f_480'], ['cpi_9606.ENSP00000272190', 'f_421', 'f_200', 'cpi_9606.ENSP00000233242', 'cpi_9606.ENSP00000274547'], ['f_685', 'cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000309124', 'f_605', 'cpi_9606.ENSP00000260356'], ['f_708', 'cpi_9606.ENSP00000373674', 'cpi_9606.ENSP00000309493', 'f_461', 'cpi_9606.ENSP00000302111'], ['cpi_9606.ENSP00000398698', 'cpi_9606.ENSP00000376432', 'f_652', 'f_314', 'f_467'], ['f_538', 'cpi_9606.ENSP00000346298', 'cpi_9606.ENSP00000327850', 'cpi_9606.ENSP00000285930', 'f_144'], ['f_691', 'cpi_9606.ENSP00000358525', 'f_532', 'cpi_9606.ENSP00000331912', 'cpi_9606.ENSP00000340691'], ['f_560', 'cpi_9606.ENSP00000340684', 'cpi_9606.ENSP00000333496', 'f_705', 'cpi_9606.ENSP00000372023'], ['f_633', 'cpi_9606.ENSP00000362334', 'cpi_9606.ENSP00000451030', 'f_425', 'cpi_9606.ENSP00000419692'], ['f_642', 'cpi_9606.ENSP00000285979', 'cpi_9606.ENSP00000351908', 'cpi_9606.ENSP00000365663', 'f_621'], ['f_241', 'cpi_9606.ENSP00000417281', 'cpi_9606.ENSP00000375893', 'f_423', 'cpi_9606.ENSP00000262160'], ['f_800', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000342070', 'f_367', 'cpi_9606.ENSP00000232219'], ['f_437', 'cpi_9606.ENSP00000265403', 'cpi_9606.ENSP00000270625', 'cpi_9606.ENSP00000303325', 'cpi_9606.ENSP00000287936'], ['f_244', 'cpi_9606.ENSP00000318585', 'cpi_9606.ENSP00000353878', 'f_780', 'cpi_9606.ENSP00000370473'], ['f_607', 'cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000347979', 'f_559'], ['cpi_9606.ENSP00000418532', 'f_681', 'cpi_9606.ENSP00000430432', 'cpi_9606.ENSP00000388648', 'f_658'], ['f_654', 'cpi_9606.ENSP00000341045', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000298386', 'f_805'], ['f_555', 'cpi_9606.ENSP00000001008', 'cpi_9606.ENSP00000411658', 'f_650', 'f_38'], ['f_445', 'cpi_9606.ENSP00000370129', 'cpi_9606.ENSP00000217426', 'f_761', 'cpi_9606.ENSP00000260010'], ['f_604', 'cpi_9606.ENSP00000375881', 'cpi_9606.ENSP00000299267', 'f_17', 'cpi_9606.ENSP00000292513'], ['f_567', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000199280', 'cpi_9606.ENSP00000416293', 'f_500'], ['cpi_9606.ENSP00000262186', 'f_349', 'cpi_9606.ENSP00000296522', 'cpi_9606.ENSP00000248553', 'cpi_9606.ENSP00000356671'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000260191', 'f_250', 'cpi_9606.ENSP00000254810', 'f_301'], ['f_589', 'cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000255465', 'f_157', 'cpi_9606.ENSP00000410294'], ['f_573', 'cpi_9606.ENSP00000386284', 'cpi_9606.ENSP00000339299', 'cpi_9606.ENSP00000351273', 'f_305'], ['cpi_9606.ENSP00000219833', 'f_395', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000382659', 'f_517'], ['f_285', 'cpi_9606.ENSP00000362441', 'cpi_9606.ENSP00000296677', 'f_575', 'f_717'], ['f_294', 'cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000331358', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000307014'], ['f_248', 'cpi_9606.ENSP00000262623', 'cpi_9606.ENSP00000277120', 'cpi_9606.ENSP00000318822', 'f_152'], ['f_453', 'cpi_9606.ENSP00000263088', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000370381'], ['f_688', 'cpi_9606.ENSP00000304802', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000239938', 'f_784'], ['f_755', 'cpi_9606.ENSP00000327801', 'cpi_9606.ENSP00000293745', 'f_260', 'f_364'], ['cpi_9606.ENSP00000226730', 'f_713', 'cpi_9606.ENSP00000358784', 'f_465', 'cpi_9606.ENSP00000348786'], ['f_541', 'cpi_9606.ENSP00000248923', 'cpi_9606.ENSP00000216341', 'f_397', 'cpi_9606.ENSP00000356694'], ['f_21', 'cpi_9606.ENSP00000386069', 'cpi_9606.ENSP00000348645', 'cpi_9606.ENSP00000221515', 'f_457'], ['f_412', 'cpi_9606.ENSP00000220809', 'f_824', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000386229'], ['f_657', 'cpi_9606.ENSP00000236671', 'cpi_9606.ENSP00000443459', 'f_700', 'cpi_9606.ENSP00000321106'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000225371', 'cpi_9606.ENSP00000365775', 'f_687'], ['f_539', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000273077', 'f_711', 'cpi_9606.ENSP00000262461'], ['f_798', 'cpi_9606.ENSP00000308720', 'f_485', 'cpi_9606.ENSP00000304895', 'cpi_9606.ENSP00000306490'], ['cpi_9606.ENSP00000261707', 'f_458', 'cpi_9606.ENSP00000340820', 'cpi_9606.ENSP00000251566', 'cpi_9606.ENSP00000346598'], ['f_662', 'cpi_9606.ENSP00000237014', 'cpi_9606.ENSP00000366506', 'f_414', 'cpi_9606.ENSP00000320709'], ['f_585', 'cpi_9606.ENSP00000263269', 'cpi_9606.ENSP00000358903', 'f_701', 'cpi_9606.ENSP00000296122'], ['f_593', 'cpi_9606.ENSP00000363965', 'cpi_9606.ENSP00000273430', 'f_819', 'cpi_9606.ENSP00000321988'], ['f_352', 'cpi_9606.ENSP00000383365', 'cpi_9606.ENSP00000231449', 'cpi_9606.ENSP00000355778', 'f_24'], ['f_709', 'cpi_9606.ENSP00000306817', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000364802', 'f_610'], ['f_376', 'cpi_9606.ENSP00000345344', 'cpi_9606.ENSP00000309103', 'f_249', 'cpi_9606.ENSP00000255380'], ['f_487', 'cpi_9606.ENSP00000337103', 'cpi_9606.ENSP00000459962', 'f_334', 'cpi_9606.ENSP00000410076'], ['cpi_9606.ENSP00000223095', 'f_187', 'cpi_9606.ENSP00000409612', 'f_590', 'f_612'], ['f_564', 'cpi_9606.ENSP00000240139', 'cpi_9606.ENSP00000264657', 'cpi_9606.ENSP00000333534', 'f_661'], ['f_178', 'cpi_9606.ENSP00000292147', 'cpi_9606.ENSP00000262735', 'cpi_9606.ENSP00000307235', 'f_630'], ['cpi_9606.ENSP00000295897', 'f_601', 'cpi_9606.ENSP00000276198', 'cpi_9606.ENSP00000268053', 'cpi_9606.ENSP00000164139'], ['cpi_9606.ENSP00000306245', 'f_383', 'cpi_9606.ENSP00000260649', 'f_13', 'cpi_9606.ENSP00000448059'], ['cpi_9606.ENSP00000270202', 'cpi_9606.ENSP00000298283', 'f_531', 'f_707', 'cpi_9606.ENSP00000216392'], ['f_591', 'cpi_9606.ENSP00000219070', 'f_399', 'cpi_9606.ENSP00000361151', 'cpi_9606.ENSP00000252029'], ['f_243', 'cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000387683', 'cpi_9606.ENSP00000353427', 'cpi_9606.ENSP00000301974'], ['f_491', 'cpi_9606.ENSP00000317842', 'cpi_9606.ENSP00000443194', 'f_462', 'cpi_9606.ENSP00000338072'], 

🔄 Processing features: 100%|██████████| 2147/2147 [10:20<00:00,  3.46feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'f_408', 'f_31', 'f_207', 'cpi_9606.ENSP00000344674'], ['cpi_9606.ENSP00000356438', 'f_131', 'f_401', 'cpi_9606.ENSP00000352011', 'f_115'], ['cpi_9606.ENSP00000342007', 'f_413', 'cpi_9606.ENSP00000430684', 'f_635', 'f_587'], ['f_346', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000279178', 'f_629', 'cpi_9606.ENSP00000395653'], ['f_308', 'cpi_9606.ENSP00000355192', 'f_616', 'cpi_9606.ENSP00000263377', 'cpi_9606.ENSP00000351957'], ['f_405', 'cpi_9606.ENSP00000305742', 'f_789', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000356094'], ['cpi_9606.ENSP00000353820', 'f_510', 'f_26', 'f_749', 'f_428'], ['f_374', 'cpi_9606.ENSP00000354193', 'cpi_9606.ENSP00000359424', 'f_831', 'cpi_9606.ENSP00000331912'], ['f_406', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000342235'], ['f_338', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000321584', 'cpi_9606.ENSP00000257290', 'cpi_9606.ENSP00000356958'], ['f_186', 'cpi_9606.ENSP00000345096', 'f_845', 'f_511', 'f_118'], ['f_566', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000354476', 'cpi_9606.ENSP00000376432', 'f_836'], ['f_643', 'cpi_9606.ENSP00000264426', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000408860', 'f_151'], ['f_2', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000357336', 'cpi_9606.ENSP00000265294', 'f_529'], ['f_380', 'cpi_9606.ENSP00000381097', 'f_726', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000409007'], ['f_143', 'cpi_9606.ENSP00000225927', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000254810', 'f_526'], ['f_366', 'cpi_9606.ENSP00000386212', 'cpi_9606.ENSP00000394936', 'cpi_9606.ENSP00000286479', 'f_768'], ['f_697', 'cpi_9606.ENSP00000279387', 'cpi_9606.ENSP00000374323', 'f_767', 'f_292'], ['f_20', 'cpi_9606.ENSP00000360967', 'cpi_9606.ENSP00000367848', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000262888'], ['f_614', 'cpi_9606.ENSP00000234310', 'cpi_9606.ENSP00000295454', 'cpi_9606.ENSP00000221972', 'cpi_9606.ENSP00000337335'], ['cpi_9606.ENSP00000354612', 'f_129', 'f_455', 'f_242', 'f_830'], ['f_571', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000251535', 'f_736'], ['cpi_9606.ENSP00000328968', 'f_230', 'f_588', 'cpi_9606.ENSP00000223095', 'cpi_9606.ENSP00000003100'], ['f_393', 'cpi_9606.ENSP00000323867', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000355629', 'cpi_9606.ENSP00000277010'], ['f_146', 'f_773', 'cpi_9606.ENSP00000314649', 'f_25', 'cpi_9606.ENSP00000282561'], ['f_637', 'cpi_9606.ENSP00000376914', 'cpi_9606.ENSP00000359353', 'f_757', 'f_27'], ['f_659', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000387946', 'cpi_9606.ENSP00000389338'], ['f_341', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000273398', 'cpi_9606.ENSP00000414334', 'f_715'], ['f_181', 'cpi_9606.ENSP00000252804', 'f_47', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000368253'], ['f_392', 'cpi_9606.ENSP00000234389', 'cpi_9606.ENSP00000332296', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000470087'], ['f_452', 'cpi_9606.ENSP00000351209', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000304822'], ['f_299', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000234590', 'cpi_9606.ENSP00000451040', 'f_202'], ['f_391', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000312455', 'cpi_9606.ENSP00000260649'], ['cpi_9606.ENSP00000270349', 'cpi_9606.ENSP00000293288', 'f_558', 'cpi_9606.ENSP00000283635', 'f_425'], ['f_540', 'cpi_9606.ENSP00000233944', 'f_866', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000378517'], ['f_12', 'cpi_9606.ENSP00000268695', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000365380', 'cpi_9606.ENSP00000319788'], ['f_192', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000314508', 'cpi_9606.ENSP00000309493', 'cpi_9606.ENSP00000296350'], ['cpi_9606.ENSP00000360372', 'f_132', 'f_812', 'f_22', 'cpi_9606.ENSP00000267119'], ['f_569', 'cpi_9606.ENSP00000333212', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000297792', 'f_350'], ['f_335', 'cpi_9606.ENSP00000291700', 'f_752', 'cpi_9606.ENSP00000394033', 'cpi_9606.ENSP00000360773'], ['f_185', 'cpi_9606.ENSP00000354532', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000216037', 'f_46'], ['f_440', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000233146', 'f_785', 'cpi_9606.ENSP00000369375'], ['f_3', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000347942', 'cpi_9606.ENSP00000367102', 'cpi_9606.ENSP00000320866'], ['f_615', 'cpi_9606.ENSP00000303540', 'f_427', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000256958'], ['f_368', 'f_522', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000362525', 'f_706'], ['f_602', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000301645', 'f_770', 'cpi_9606.ENSP00000360493'], ['cpi_9606.ENSP00000311032', 'cpi_9606.ENSP00000299847', 'f_167', 'f_43', 'f_454'], ['f_451', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000245539', 'f_328'], ['f_646', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000262160', 'cpi_9606.ENSP00000358548', 'f_330'], ['f_528', 'cpi_9606.ENSP00000362508', 'cpi_9606.ENSP00000341390', 'f_327', 'f_497'], ['f_683', 'cpi_9606.ENSP00000341828', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000252809'], ['f_257', 'cpi_9606.ENSP00000314949', 'cpi_9606.ENSP00000362513', 'cpi_9606.ENSP00000398632', 'f_361'], ['f_339', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000256383', 'f_834', 'f_799'], ['f_19', 'cpi_9606.ENSP00000472933', 'cpi_9606.ENSP00000463999', 'cpi_9606.ENSP00000417229', 'f_771'], ['f_638', 'cpi_9606.ENSP00000225275', 'cpi_9606.ENSP00000264637', 'f_791', 'f_116'], ['f_645', 'cpi_9606.ENSP00000354107', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000266376'], ['f_365', 'cpi_9606.ENSP00000287878', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000366307', 'cpi_9606.ENSP00000301891'], ['f_604', 'cpi_9606.ENSP00000357669', 'cpi_9606.ENSP00000358595', 'f_164', 'f_788'], ['f_439', 'cpi_9606.ENSP00000353791', 'cpi_9606.ENSP00000348786', 'cpi_9606.ENSP00000343477', 'f_622'], ['f_180', 'cpi_9606.ENSP00000362329', 'cpi_9606.ENSP00000263339', 'f_166', 'f_343'], ['f_617', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000259089', 'cpi_9606.ENSP00000264318', 'f_820'], ['f_345', 'cpi_9606.ENSP00000430031', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000343040', 'f_436'], ['f_672', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000411658', 'cpi_9606.ENSP00000291295', 'f_297'], ['f_579', 'cpi_9606.ENSP00000346901', 'cpi_9606.ENSP00000363296', 'cpi_9606.ENSP00000365016', 'f_670'], ['f_639', 'f_778', 'cpi_9606.ENSP00000352035', 'cpi_9606.ENSP00000222256', 'f_508'], ['f_145', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000261196', 'f_675'], ['f_712', 'cpi_9606.ENSP00000262623', 'f_725', 'f_35', 'f_729'], ['f_684', 'cpi_9606.ENSP00000368349', 'f_554', 'f_474', 'cpi_9606.ENSP00000216862'], ['cpi_9606.ENSP00000324648', 'f_227', 'f_359', 'f_298', 'cpi_9606.ENSP00000301420'], ['f_553', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000263431', 'f_509', 'cpi_9606.ENSP00000258749'], ['f_611', 'cpi_9606.ENSP00000355155', 'f_214', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000216185'], ['f_586', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000307599', 'f_518', 'cpi_9606.ENSP00000222390'], ['f_293', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000358730', 'f_417', 'cpi_9606.ENSP00000364805'], ['cpi_9606.ENSP00000367959', 'f_30', 'cpi_9606.ENSP00000267101', 'cpi_9606.ENSP00000242057', 'f_496'], ['cpi_9606.ENSP00000263817', 'f_229', 'f_466', 'f_407', 'cpi_9606.ENSP00000295256'], ['f_15', 'cpi_9606.ENSP00000320401', 'cpi_9606.ENSP00000343392', 'f_460', 'f_827'], ['f_592', 'cpi_9606.ENSP00000238018', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000309124', 'f_583'], ['f_682', 'cpi_9606.ENSP00000320709', 'cpi_9606.ENSP00000260010', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000359285'], ['f_443', 'cpi_9606.ENSP00000312326', 'cpi_9606.ENSP00000340691', 'f_722', 'cpi_9606.ENSP00000312029'], ['f_535', 'cpi_9606.ENSP00000297268', 'cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000344352', 'f_728'], ['f_656', 'cpi_9606.ENSP00000362924', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000226574', 'cpi_9606.ENSP00000276449'], ['f_340', 'cpi_9606.ENSP00000286091', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000353292', 'f_764'], ['cpi_9606.ENSP00000265724', 'f_609', 'f_262', 'f_763', 'cpi_9606.ENSP00000299178'], ['f_818', 'cpi_9606.ENSP00000263686', 'f_473', 'cpi_9606.ENSP00000222330', 'cpi_9606.ENSP00000274547'], ['f_680', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000306100', 'cpi_9606.ENSP00000286301', 'cpi_9606.ENSP00000278175'], ['f_580', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000364709', 'f_839', 'f_419'], ['f_698', 'cpi_9606.ENSP00000354280', 'f_388', 'f_792', 'f_194'], ['f_33', 'cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000253004', 'f_826', 'cpi_9606.ENSP00000225474'], ['f_667', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000301178', 'cpi_9606.ENSP00000259396', 'cpi_9606.ENSP00000366662'], ['f_704', 'cpi_9606.ENSP00000441691', 'cpi_9606.ENSP00000355778', 'f_676', 'cpi_9606.ENSP00000376776'], ['f_507', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000457706', 'cpi_9606.ENSP00000353915'], ['f_248', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000292513', 'cpi_9606.ENSP00000311095', 'f_394'], ['f_671', 'cpi_9606.ENSP00000305302', 'cpi_9606.ENSP00000379330', 'cpi_9606.ENSP00000357283', 'f_815'], ['f_666', 'cpi_9606.ENSP00000358107', 'cpi_9606.ENSP00000272847', 'cpi_9606.ENSP00000370473', 'f_398'], ['f_695', 'cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000454071', 'f_822', 'f_568'], ['f_37', 'cpi_9606.ENSP00000400175', 'cpi_9606.ENSP00000354569', 'f_475', 'cpi_9606.ENSP00000242375'], ['f_349', 'cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000296522', 'cpi_9606.ENSP00000317379', 'cpi_9606.ENSP00000299267'], ['f_300', 'f_249', 'cpi_9606.ENSP00000261405', 'f_505', 'cpi_9606.ENSP00000410076'], ['cpi_9606.ENSP00000283916', 'f_456', 'f_742', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000410732'], ['f_21', 'cpi_9606.ENSP00000316244', 'cpi_9606.ENSP00000363868', 'cpi_9606.ENSP00000261799', 'cpi_9606.ENSP00000369530'], ['f_641', 'cpi_9606.ENSP00000364782', 'cpi_9606.ENSP00000252723', 'cpi_9606.ENSP00000275525', 'f_429'], ['f_16', 'cpi_9606.ENSP00000360608', 'f_861', 'f_719', 'cpi_9606.ENSP00000252486'], ['f_685', 'cpi_9606.ENSP00000301141', 'cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000300061', 'f_411'], ['f_213', 'f_336', 'f_559', 'cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000354394'], ['f_642', 'cpi_9606.ENSP00000313661', 'cpi_9606.ENSP00000345659', 'f_314', 'cpi_9606.ENSP00000221515'], ['f_287', 'cpi_9606.ENSP00000350616', 'f_195', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000312664'], ['f_623', 'cpi_9606.ENSP00000266682', 'cpi_9606.ENSP00000287641', 'cpi_9606.ENSP00000227758', 'f_533'], ['f_692', 'cpi_9606.ENSP00000302886', 'cpi_9606.ENSP00000310305', 'f_486', 'f_750'], ['f_418', 'cpi_9606.ENSP00000332549', 'f_782', 'f_840', 'cpi_9606.ENSP00000361359'], ['f_613', 'cpi_9606.ENSP00000352584', 'cpi_9606.ENSP00000218758', 'cpi_9606.ENSP00000356954', 'f_448'], ['f_593', 'cpi_9606.ENSP00000279593', 'cpi_9606.ENSP00000358903', 'f_409', 'cpi_9606.ENSP00000326119'], ['f_681', 'f_215', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000261937', 'cpi_9606.ENSP00000259271'], ['f_696', 'cpi_9606.ENSP00000286621', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000221421', 'f_833'], ['f_594', 'cpi_9606.ENSP00000263321', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000344192'], ['f_633', 'cpi_9606.ENSP00000216714', 'cpi_9606.ENSP00000367851', 'cpi_9606.ENSP00000316786', 'cpi_9606.ENSP00000295834'], ['f_353', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000388648', 'f_631'], ['f_549', 'cpi_9606.ENSP00000349577', 'cpi_9606.ENSP00000355657', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000296871'], ['f_691', 'cpi_9606.ENSP00000276431', 'cpi_9606.ENSP00000354610', 'f_513', 'f_494'], ['f_502', 'cpi_9606.ENSP00000397026', 'cpi_9606.ENSP00000329357', 'f_551', 'cpi_9606.ENSP00000348069'], ['f_515', 'cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000311028', 'f_647'], ['cpi_9606.ENSP00000226730', 'f_713', 'f_813', 'cpi_9606.ENSP00000393847', 'f_480'], ['f_699', 'f_488', 'cpi_9606.ENSP00000313490', 'f_483', 'cpi_9606.ENSP00000305422'], ['f_548', 'cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000361206', 'f_650', 'cpi_9606.ENSP00000376943'], ['f_501', 'cpi_9606.ENSP00000307786', 'f_159', 'f_144', 'cpi_9606.ENSP00000308165'], ['f_333', 'cpi_9606.ENSP00000400376', 'cpi_9606.ENSP00000382659', 'cpi_9606.ENSP00000267843', 'cpi_9606.ENSP00000261693'], ['f_536', 'cpi_9606.ENSP00000291294', 'cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000200676', 'f_363'], ['cpi_9606.ENSP00000338345', 'f_150', 'cpi_9606.ENSP00000287936', 'cpi_9606.ENSP00000471569', 'cpi_9606.ENSP00000370912'], ['f_390', 'cpi_9606.ENSP00000369100', 'cpi_9606.ENSP00000427514', 'cpi_9606.ENSP00000361666', 'f_477'], ['f_597', 'cpi_9606.ENSP00000254488', 'cpi_9606.ENSP00000237527', 'cpi_9606.ENSP00000248553', 'f_160'], ['cpi_9606.ENSP00000337450', 'f_461', 'cpi_9606.ENSP00000302846', 'cpi_9606.ENSP00000362649', 'f_200'], ['cpi_9606.ENSP00000258743', 'f_652', 'cpi_9606.ENSP00000264818', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000322617'], ['f_420', 'cpi_9606.ENSP00000343745', 'cpi_9606.ENSP00000445340', 'cpi_9606.ENSP00000389414', 'f_543'], ['f_600', 'cpi_9606.ENSP00000331746', 'cpi_9606.ENSP00000265403', 'cpi_9606.ENSP00000353427', 'cpi_9606.ENSP00000320935'], ['f_655', 'cpi_9606.ENSP00000386284', 'cpi_9606.ENSP00000388825', 'cpi_9606.ENSP00000278616', 'f_644'], ['f_658', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000302111', 'cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000264867'], ['f_375', 'cpi_9606.ENSP00000338627', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000467676', 'cpi_9606.ENSP00000294728'], ['f_412', 'cpi_9606.ENSP00000417281', 'cpi_9606.ENSP00000379110', 'f_801', 'cpi_9606.ENSP00000219919'], ['f_581', 'cpi_9606.ENSP00000306129', 'cpi_9606.ENSP00000346298', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000164139'], ['f_241', 'cpi_9606.ENSP00000335620', 'cpi_9606.ENSP00000350005', 'f_717', 'f_514'], ['f_432', 'cpi_9606.ENSP00000331514', 'f_34', 'cpi_9606.ENSP00000311469', 'f_759'], ['f_23', 'f_687', 'cpi_9606.ENSP00000375881', 'f_216', 'cpi_9606.ENSP00000263126'], ['f_294', 'cpi_9606.ENSP00000319591', 'cpi_9606.ENSP00000260356', 'cpi_9606.ENSP00000356694', 'f_260'], ['f_798', 'f_485', 'cpi_9606.ENSP00000262407', 'cpi_9606.ENSP00000330393', 'f_467'], ['f_244', 'cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000231454', 'f_738', 'cpi_9606.ENSP00000448059'], ['f_797', 'cpi_9606.ENSP00000218548', 'cpi_9606.ENSP00000277120', 'f_17', 'f_305'], ['f_619', 'cpi_9606.ENSP00000399168', 'cpi_9606.ENSP00000295491', 'cpi_9606.ENSP00000255465', 'f_471'], ['f_370', 'cpi_9606.ENSP00000371138', 'cpi_9606.ENSP00000274793', 'f_653', 'f_860'], ['f_516', 'cpi_9606.ENSP00000264162', 'cpi_9606.ENSP00000286648', 'f_625', 'cpi_9606.ENSP00000410294'], ['f_689', 'cpi_9606.ENSP00000228740', 'f_422', 'f_740', 'cpi_9606.ENSP00000233242'], ['f_628', 'cpi_9606.ENSP00000305221', 'cpi_9606.ENSP00000318646', 'cpi_9606.ENSP00000246553', 'cpi_9606.ENSP00000347979'], ['f_573', 'cpi_9606.ENSP00000293190', 'cpi_9606.ENSP00000339527', 'f_517', 'cpi_9606.ENSP00000296122'], ['f_542', 'cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000241600', 'f_397', 'f_421'], ['f_356', 'cpi_9606.ENSP00000292147', 'cpi_9606.ENSP00000323568', 'f_610', 'cpi_9606.ENSP00000264657'], ['f_493', 'cpi_9606.ENSP00000308720', 'f_347', 'cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000297350'], ['f_688', 'cpi_9606.ENSP00000349576', 'cpi_9606.ENSP00000339299', 'f_423', 'f_721'], ['f_442', 'cpi_9606.ENSP00000211122', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000263980', 'f_605'], ['f_690', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000260970', 'cpi_9606.ENSP00000355920', 'f_780'], ['f_567', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000288602', 'cpi_9606.ENSP00000296545', 'f_532'], ['cpi_9606.ENSP00000219833', 'f_489', 'cpi_9606.ENSP00000332816', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000341045'], ['f_560', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000333496', 'f_705', 'cpi_9606.ENSP00000332369'], ['f_476', 'cpi_9606.ENSP00000312673', 'cpi_9606.ENSP00000280357', 'f_301', 'cpi_9606.ENSP00000343925'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000336630', 'cpi_9606.ENSP00000394932', 'f_694'], ['f_453', 'cpi_9606.ENSP00000359998', 'cpi_9606.ENSP00000386171', 'f_575', 'cpi_9606.ENSP00000276571'], ['cpi_9606.ENSP00000354859', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000346598', 'f_458'], ['f_663', 'cpi_9606.ENSP00000239849', 'cpi_9606.ENSP00000308774', 'cpi_9606.ENSP00000262367', 'f_465'], ['cpi_9606.ENSP00000295897', 'f_187', 'f_395', 'cpi_9606.ENSP00000428340', 'cpi_9606.ENSP00000419782'], ['f_686', 'cpi_9606.ENSP00000308032', 'cpi_9606.ENSP00000241256', 'cpi_9606.ENSP00000365686', 'f_414'], ['f_555', 'cpi_9606.ENSP00000378699', 'cpi_9606.ENSP00000308897', 'f_367', 'cpi_9606.ENSP00000255380'], ['f_709', 'cpi_9606.ENSP00000447378', 'cpi_9606.ENSP00000318822', 'cpi_9606.ENSP00000451030', 'f_805'], ['f_495', 'cpi_9606.ENSP00000345344', 'cpi_9606.ENSP00000309103', 'f_761', 'cpi_9606.ENSP00000255030'], ['f_574', 'cpi_9606.ENSP00000219700', 'cpi_9606.ENSP00000359635', 'cpi_9606.ENSP00000428924', 'f_457'], ['f_755', 'cpi_9606.ENSP00000342070', 'f_364', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000232219'], ['cpi_9606.ENSP00000258400', 'cpi_9606.ENSP00000304845', 'cpi_9606.ENSP00000356150', 'f_157', 'f_459'], ['f_576', 'cpi_9606.ENSP00000354511', 'f_661', 'cpi_9606.ENSP00000241261', 'cpi_9606.ENSP00000307240'], ['f_538', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000314214', 'f_803', 'f_24'], ['f_450', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000336701', 'f_563', 'cpi_9606.ENSP00000372750'], ['f_351', 'cpi_9606.ENSP00000362441', 'cpi_9606.ENSP00000459962', 'cpi_9606.ENSP00000267163', 'f_38'], ['f_737', 'cpi_9606.ENSP00000414303', 'cpi_9606.ENSP00000359211', 'cpi_9606.ENSP00000225964', 'f_206'], ['f_546', 'cpi_9606.ENSP00000359719', 'cpi_9606.ENSP00000239938', 'f_701', 'cpi_9606.ENSP00000293745'], ['f_188', 'cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000294954', 'cpi_9606.ENSP00000330199', 'f_716'], ['cpi_9606.ENSP00000272190', 'f_612', 'cpi_9606.ENSP00000253727', 'cpi_9606.ENSP00000443194', 'f_734'], ['f_153', 'cpi_9606.ENSP00000231509', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000351885', 'cpi_9606.ENSP00000307014'], ['f_800', 'cpi_9606.ENSP00000346839', 'cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000220616', 'f_152'], ['f_342', 'cpi_9606.ENSP00000285238', 'cpi_9606.ENSP00000362036', 'f_527', 'cpi_9606.ENSP00000359793'], ['f_654', 'cpi_9606.ENSP00000248437', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000335657', 'f_756'], ['cpi_9606.ENSP00000355759', 'cpi_9606.ENSP00000226413', 'cpi_9606.ENSP00000359100', 'f_500', 'cpi_9606.ENSP00000370381'], ['f_539', 'cpi_9606.ENSP00000300060', 'cpi_9606.ENSP00000303522', 'cpi_9606.ENSP00000372023', 'f_711'], ['f_702', 'cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000290349', 'f_383'], ['f_286', 'cpi_9606.ENSP00000383365', 'cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000231449', 'cpi_9606.ENSP00000327652'], ['cpi_9606.ENSP00000215832', 'f_399', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000359532', 'f_598'], ['f_821', 'cpi_9606.ENSP00000372326', 'cpi_9606.ENSP00000304895', 'cpi_9606.ENSP00000386229', 'f_531'], ['f_758', 'cpi_9606.ENSP00000361850', 'cpi_9606.ENSP00000307259', 'cpi_9606.ENSP00000275300', 'f_334'], ['f_199', 'cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000262187', 'cpi_9606.ENSP00000268053', 'cpi_9606.ENSP00000331358'], ['f_714', 'cpi_9606.ENSP00000358525', 'cpi_9606.ENSP00000380252', 'f_601', 'cpi_9606.ENSP00000368104'], ['f_591', 'cpi_9606.ENSP00000219070', 'f_400',

🔄 Processing features: 100%|██████████| 2147/2147 [10:24<00:00,  3.44feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'f_413', 'f_151', 'f_262', 'cpi_9606.ENSP00000359096'], ['f_308', 'cpi_9606.ENSP00000355192', 'f_616', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000374323'], ['f_374', 'cpi_9606.ENSP00000264705', 'f_768', 'cpi_9606.ENSP00000359424', 'f_771'], ['f_23', 'cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000356094', 'f_118', 'f_31'], ['f_20', 'cpi_9606.ENSP00000261205', 'f_729', 'f_194', 'cpi_9606.ENSP00000357068'], ['f_299', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000229447', 'cpi_9606.ENSP00000360493', 'cpi_9606.ENSP00000354476'], ['f_3', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000319170', 'f_328', 'cpi_9606.ENSP00000286479'], ['f_672', 'cpi_9606.ENSP00000216465', 'f_292', 'f_845', 'cpi_9606.ENSP00000262352'], ['f_393', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000380318', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000355629'], ['f_452', 'f_25', 'cpi_9606.ENSP00000221421', 'f_831', 'cpi_9606.ENSP00000223366'], ['f_380', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000270474', 'f_726', 'cpi_9606.ENSP00000342235'], ['f_287', 'cpi_9606.ENSP00000385026', 'f_408', 'cpi_9606.ENSP00000274353', 'f_164'], ['f_285', 'cpi_9606.ENSP00000280701', 'f_866', 'cpi_9606.ENSP00000263339', 'f_27'], ['f_451', 'cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000277010', 'f_428'], ['f_37', 'f_782', 'cpi_9606.ENSP00000362353', 'f_554', 'f_35'], ['f_406', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000288139', 'f_789', 'f_629'], ['f_390', 'cpi_9606.ENSP00000471397', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000430684', 'f_529'], ['f_366', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000357336', 'cpi_9606.ENSP00000279178', 'f_417'], ['f_440', 'cpi_9606.ENSP00000262888', 'cpi_9606.ENSP00000233146', 'cpi_9606.ENSP00000372547', 'f_830'], ['f_185', 'cpi_9606.ENSP00000264162', 'cpi_9606.ENSP00000414334', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000352011'], ['f_192', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000412673', 'f_47', 'cpi_9606.ENSP00000356832'], ['f_571', 'cpi_9606.ENSP00000395653', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000301891', 'f_736'], ['f_643', 'cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000263126', 'f_622'], ['f_10', 'cpi_9606.ENSP00000238379', 'cpi_9606.ENSP00000463999', 'cpi_9606.ENSP00000457706', 'cpi_9606.ENSP00000221972'], ['f_420', 'cpi_9606.ENSP00000291565', 'cpi_9606.ENSP00000367851', 'f_767', 'f_297'], ['f_614', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000332369', 'cpi_9606.ENSP00000337335', 'f_725'], ['f_143', 'cpi_9606.ENSP00000254976', 'cpi_9606.ENSP00000258749', 'cpi_9606.ENSP00000222330', 'f_836'], ['f_186', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000357981', 'f_635', 'f_26'], ['f_15', 'cpi_9606.ENSP00000357204', 'cpi_9606.ENSP00000229264', 'f_861', 'f_526'], ['f_146', 'cpi_9606.ENSP00000319531', 'cpi_9606.ENSP00000304822', 'f_773', 'f_587'], ['f_659', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000389338'], ['f_33', 'f_706', 'f_350', 'cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000435591'], ['f_639', 'f_427', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000319591', 'f_799'], ['f_392', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000251535', 'f_202'], ['f_613', 'cpi_9606.ENSP00000405573', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000312455', 'f_510'], ['f_617', 'cpi_9606.ENSP00000352035', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000295452'], ['f_339', 'f_675', 'cpi_9606.ENSP00000367102', 'cpi_9606.ENSP00000220616', 'f_834'], ['f_346', 'cpi_9606.ENSP00000252804', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000367848'], ['f_686', 'f_215', 'cpi_9606.ENSP00000263321', 'f_419', 'f_670'], ['f_516', 'cpi_9606.ENSP00000397582', 'cpi_9606.ENSP00000470087', 'cpi_9606.ENSP00000343477', 'f_298'], ['f_681', 'f_568', 'cpi_9606.ENSP00000291295', 'f_483', 'f_460'], ['f_697', 'cpi_9606.ENSP00000314214', 'f_511', 'cpi_9606.ENSP00000402152', 'f_749'], ['f_12', 'cpi_9606.ENSP00000330032', 'cpi_9606.ENSP00000333212', 'cpi_9606.ENSP00000319788', 'f_788'], ['f_638', 'cpi_9606.ENSP00000237014', 'cpi_9606.ENSP00000216862', 'f_820', 'cpi_9606.ENSP00000359353'], ['f_181', 'cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000264637', 'f_166', 'cpi_9606.ENSP00000265294'], ['f_569', 'cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000332296', 'cpi_9606.ENSP00000252809', 'f_46'], ['f_405', 'cpi_9606.ENSP00000277508', 'cpi_9606.ENSP00000220003', 'cpi_9606.ENSP00000216037', 'f_757'], ['f_566', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000295834', 'cpi_9606.ENSP00000261937'], ['f_696', 'cpi_9606.ENSP00000359100', 'cpi_9606.ENSP00000430432', 'cpi_9606.ENSP00000360773', 'f_474'], ['f_335', 'f_815', 'cpi_9606.ENSP00000353224', 'cpi_9606.ENSP00000331912', 'cpi_9606.ENSP00000344674'], ['f_19', 'cpi_9606.ENSP00000376914', 'cpi_9606.ENSP00000286301', 'f_330', 'cpi_9606.ENSP00000275525'], ['f_391', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000320866', 'f_719', 'cpi_9606.ENSP00000368253'], ['f_579', 'cpi_9606.ENSP00000383365', 'f_327', 'cpi_9606.ENSP00000282561', 'f_752'], ['f_21', 'cpi_9606.ENSP00000306490', 'f_116', 'f_509', 'f_715'], ['f_535', 'cpi_9606.ENSP00000269159', 'cpi_9606.ENSP00000471569', 'cpi_9606.ENSP00000353292', 'cpi_9606.ENSP00000358548'], ['f_338', 'cpi_9606.ENSP00000434516', 'cpi_9606.ENSP00000299267', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000257290'], ['f_656', 'cpi_9606.ENSP00000222481', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000312664'], ['cpi_9606.ENSP00000311032', 'f_43', 'f_207', 'f_543', 'cpi_9606.ENSP00000349320'], ['f_340', 'cpi_9606.ENSP00000373477', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000164139', 'f_764'], ['f_693', 'cpi_9606.ENSP00000270142', 'f_422', 'f_812', 'cpi_9606.ENSP00000378517'], ['f_712', 'cpi_9606.ENSP00000229319', 'f_533', 'cpi_9606.ENSP00000311095', 'f_583'], ['f_698', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000410294', 'cpi_9606.ENSP00000394936'], ['f_683', 'cpi_9606.ENSP00000306606', 'cpi_9606.ENSP00000328173', 'cpi_9606.ENSP00000451040', 'f_505'], ['f_343', 'f_199', 'cpi_9606.ENSP00000385834', 'f_508', 'f_394'], ['f_443', 'cpi_9606.ENSP00000337746', 'f_497', 'cpi_9606.ENSP00000301974', 'cpi_9606.ENSP00000361359'], ['f_16', 'cpi_9606.ENSP00000249750', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000385806', 'f_361'], ['f_257', 'cpi_9606.ENSP00000382250', 'cpi_9606.ENSP00000320401', 'cpi_9606.ENSP00000344352', 'f_839'], ['f_684', 'cpi_9606.ENSP00000346827', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000365016'], ['f_332', 'cpi_9606.ENSP00000226299', 'cpi_9606.ENSP00000296677', 'cpi_9606.ENSP00000387946', 'cpi_9606.ENSP00000417229'], ['f_351', 'cpi_9606.ENSP00000226578', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000316786', 'f_436'], ['f_777', 'cpi_9606.ENSP00000371236', 'f_486', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000343040'], ['f_294', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000343782', 'f_167', 'f_229'], ['f_365', 'cpi_9606.ENSP00000297258', 'cpi_9606.ENSP00000296522', 'cpi_9606.ENSP00000326119', 'f_827'], ['f_646', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000387536', 'f_214', 'f_763'], ['f_528', 'cpi_9606.ENSP00000274026', 'cpi_9606.ENSP00000276449', 'cpi_9606.ENSP00000253727', 'cpi_9606.ENSP00000231228'], ['f_2', 'cpi_9606.ENSP00000011292', 'cpi_9606.ENSP00000379086', 'cpi_9606.ENSP00000225474', 'f_401'], ['f_293', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000350348', 'cpi_9606.ENSP00000242375'], ['f_642', 'f_314', 'f_429', 'cpi_9606.ENSP00000356729', 'f_750'], ['f_691', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000216540', 'f_792'], ['f_567', 'cpi_9606.ENSP00000219794', 'f_778', 'cpi_9606.ENSP00000389414', 'f_131'], ['f_611', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000408860', 'f_466'], ['cpi_9606.ENSP00000264381', 'f_713', 'f_227', 'f_785', 'f_791'], ['f_540', 'cpi_9606.ENSP00000341828', 'cpi_9606.ENSP00000355657', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000266376'], ['f_462', 'cpi_9606.ENSP00000303211', 'f_488', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000347942'], ['f_819', 'f_609', 'cpi_9606.ENSP00000352835', 'f_650', 'f_496'], ['f_0', 'cpi_9606.ENSP00000244051', 'cpi_9606.ENSP00000305422', 'f_722', 'cpi_9606.ENSP00000376943'], ['f_353', 'cpi_9606.ENSP00000344460', 'cpi_9606.ENSP00000344192', 'cpi_9606.ENSP00000376178', 'f_230'], ['f_248', 'cpi_9606.ENSP00000342070', 'f_455', 'cpi_9606.ENSP00000308165', 'f_477'], ['f_345', 'cpi_9606.ENSP00000430031', 'cpi_9606.ENSP00000419692', 'cpi_9606.ENSP00000361666', 'f_448'], ['f_628', 'cpi_9606.ENSP00000354610', 'cpi_9606.ENSP00000388825', 'cpi_9606.ENSP00000255465', 'cpi_9606.ENSP00000226574'], ['f_341', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000273398', 'cpi_9606.ENSP00000357283', 'f_813'], ['f_594', 'cpi_9606.ENSP00000340943', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000274545', 'f_407'], ['f_24', 'cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000283635', 'f_159'], ['f_144', 'cpi_9606.ENSP00000396308', 'f_738', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000296350'], ['cpi_9606.ENSP00000231509', 'f_34', 'f_826', 'f_518', 'cpi_9606.ENSP00000295454'], ['f_553', 'cpi_9606.ENSP00000298171', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000274547'], ['f_342', 'cpi_9606.ENSP00000355536', 'cpi_9606.ENSP00000260010', 'f_475', 'cpi_9606.ENSP00000259396'], ['f_645', 'cpi_9606.ENSP00000386284', 'cpi_9606.ENSP00000359793', 'cpi_9606.ENSP00000340691', 'f_551'], ['f_38', 'f_364', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000353679', 'f_160'], ['f_682', 'cpi_9606.ENSP00000236850', 'cpi_9606.ENSP00000296871', 'cpi_9606.ENSP00000338627', 'f_728'], ['f_573', 'cpi_9606.ENSP00000298283', 'cpi_9606.ENSP00000375809', 'f_388', 'cpi_9606.ENSP00000231454'], ['f_9', 'cpi_9606.ENSP00000343885', 'cpi_9606.ENSP00000329357', 'f_409', 'f_195'], ['f_690', 'cpi_9606.ENSP00000387123', 'f_676', 'cpi_9606.ENSP00000354394', 'f_216'], ['f_193', 'cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000296545', 'cpi_9606.ENSP00000312304', 'f_494'], ['f_667', 'cpi_9606.ENSP00000288022', 'cpi_9606.ENSP00000301178', 'f_647', 'cpi_9606.ENSP00000348069'], ['f_615', 'f_631', 'cpi_9606.ENSP00000315644', 'cpi_9606.ENSP00000391826', 'f_770'], ['f_368', 'cpi_9606.ENSP00000414303', 'cpi_9606.ENSP00000261733', 'f_644', 'f_840'], ['f_699', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000292896', 'f_473', 'cpi_9606.ENSP00000339527'], ['f_180', 'cpi_9606.ENSP00000302728', 'f_132', 'cpi_9606.ENSP00000343925', 'f_687'], ['f_671', 'cpi_9606.ENSP00000262441', 'cpi_9606.ENSP00000296046', 'cpi_9606.ENSP00000283254', 'f_30'], ['cpi_9606.ENSP00000265724', 'f_22', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000359532', 'cpi_9606.ENSP00000381097'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000380247', 'f_17', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000225371'], ['f_14', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000324105', 'cpi_9606.ENSP00000261799', 'f_653'], ['f_537', 'f_423', 'cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000274793', 'cpi_9606.ENSP00000267101'], ['f_701', 'f_467', 'cpi_9606.ENSP00000318868', 'cpi_9606.ENSP00000307599', 'f_833'], ['f_704', 'cpi_9606.ENSP00000367123', 'cpi_9606.ENSP00000248041', 'f_461', 'cpi_9606.ENSP00000359285'], ['f_18', 'cpi_9606.ENSP00000472933', 'cpi_9606.ENSP00000232219', 'f_471', 'f_522'], ['f_1', 'cpi_9606.ENSP00000302441', 'cpi_9606.ENSP00000427514', 'f_513', 'f_398'], ['f_798', 'cpi_9606.ENSP00000262407', 'cpi_9606.ENSP00000445340', 'f_489', 'f_717'], ['f_550', 'cpi_9606.ENSP00000356022', 'f_527', 'cpi_9606.ENSP00000256958', 'f_514'], ['f_680', 'cpi_9606.ENSP00000332256', 'cpi_9606.ENSP00000300061', 'f_129', 'cpi_9606.ENSP00000359334'], ['f_286', 'cpi_9606.ENSP00000363533', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000312029', 'f_740'], ['f_255', 'cpi_9606.ENSP00000248935', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000252723', 'f_115'], ['f_797', 'cpi_9606.ENSP00000299178', 'cpi_9606.ENSP00000347046', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000293288'], ['f_692', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000216962', 'cpi_9606.ENSP00000339260', 'f_517'], ['f_641', 'cpi_9606.ENSP00000374219', 'cpi_9606.ENSP00000242057', 'cpi_9606.ENSP00000023897', 'f_347'], ['f_776', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000374265', 'f_742', 'f_411'], ['f_637', 'cpi_9606.ENSP00000305480', 'cpi_9606.ENSP00000370473', 'f_421', 'cpi_9606.ENSP00000320935'], ['f_702', 'cpi_9606.ENSP00000261465', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000278616', 'f_822'], ['f_13', 'cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000325822', 'f_465'], ['f_11', 'cpi_9606.ENSP00000417901', 'cpi_9606.ENSP00000294728', 'f_558', 'cpi_9606.ENSP00000302111'], ['f_581', 'f_456', 'cpi_9606.ENSP00000367309', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000369530'], ['f_619', 'cpi_9606.ENSP00000293190', 'cpi_9606.ENSP00000356954', 'f_425', 'cpi_9606.ENSP00000314099'], ['f_439', 'cpi_9606.ENSP00000364212', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000309124', 'f_367'], ['f_666', 'cpi_9606.ENSP00000381333', 'cpi_9606.ENSP00000314649', 'cpi_9606.ENSP00000335511', 'f_336'], ['f_375', 'f_242', 'cpi_9606.ENSP00000263269', 'f_625', 'cpi_9606.ENSP00000233242'], ['cpi_9606.ENSP00000295897', 'f_187', 'f_759', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000376432'], ['f_249', 'f_300', 'cpi_9606.ENSP00000264668', 'cpi_9606.ENSP00000366307', 'f_500'], ['f_432', 'cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000262367', 'f_363', 'cpi_9606.ENSP00000454071'], ['f_464', 'cpi_9606.ENSP00000308897', 'cpi_9606.ENSP00000296122', 'f_860', 'f_588'], ['f_593', 'cpi_9606.ENSP00000327431', 'cpi_9606.ENSP00000321988', 'cpi_9606.ENSP00000261693', 'f_454'], ['f_663', 'cpi_9606.ENSP00000252945', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000326219', 'f_801'], ['f_487', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000356671', 'f_803', 'cpi_9606.ENSP00000330393'], ['f_705', 'cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000262948', 'f_399'], ['f_337', 'cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000297350', 'cpi_9606.ENSP00000388648'], ['f_818', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000352608', 'cpi_9606.ENSP00000252486', 'f_305'], ['f_592', 'cpi_9606.ENSP00000222482', 'cpi_9606.ENSP00000428824', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000370381'], ['f_549', 'cpi_9606.ENSP00000216714', 'cpi_9606.ENSP00000248553', 'f_605', 'cpi_9606.ENSP00000309493'], ['f_709', 'cpi_9606.ENSP00000330484', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000264657', 'f_559'], ['f_755', 'cpi_9606.ENSP00000383558', 'cpi_9606.ENSP00000358784', 'cpi_9606.ENSP00000359663', 'f_301'], ['f_259', 'cpi_9606.ENSP00000279230', 'cpi_9606.ENSP00000353427', 'cpi_9606.ENSP00000200676', 'f_610'], ['f_377', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000303325', 'cpi_9606.ENSP00000349252', 'f_480'], ['f_349', 'cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000369038', 'f_737'], ['f_604', 'cpi_9606.ENSP00000332549', 'cpi_9606.ENSP00000358903', 'f_359', 'cpi_9606.ENSP00000318822'], ['f_536', 'cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000217961', 'f_630', 'cpi_9606.ENSP00000327652'], ['f_284', 'cpi_9606.ENSP00000348395', 'cpi_9606.ENSP00000361668', 'f_721', 'f_200'], ['f_430', 'cpi_9606.ENSP00000359680', 'cpi_9606.ENSP00000239938', 'f_805', 'cpi_9606.ENSP00000448059'], ['f_498', 'cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000295491', 'cpi_9606.ENSP00000260356', 'f_780'], ['f_334', 'cpi_9606.ENSP00000302811', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000270776', 'f_457'], ['f_560', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000318646', 'cpi_9606.ENSP00000264867', 'cpi_9606.ENSP00000219833'], ['f_352', 'cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000297268', 'cpi_9606.ENSP00000369927', 'f_157'], ['f_591', 'cpi_9606.ENSP00000219070', 'f_400', 'cpi_9606.ENSP00000261196', 'cpi_9606.ENSP00000362036'], ['f_333', 'cpi_9606.ENSP00000358727', 'cpi_9606.ENSP00000307014', 'cpi_9606.ENSP00000351273', 'f_652'], ['f_716', 'cpi_9606.ENSP00000327251', 'cpi_9606.ENSP00000155840', 'f_658', 'cpi_9606.ENSP00000291700'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000393333', 'cpi_9606.ENSP00000241600', 'f_694', 'cpi_9606.ENSP00000252029'], ['f_711', 'cpi_9606.ENSP00000334105', 'cpi_9606.ENSP00000372023', 'f_532', 'f_397'], ['f_437', 'cpi_9606.ENSP00000338548', 'cpi_9606.ENSP00000346598', 'cpi_9606.ENSP00000246553', 'f_575'], ['f_586', 'cpi_9606.ENSP00000003084', 'cpi_9606.ENSP00000267119', 'cpi_9606.ENSP00000354558', 'cpi_9606.ENSP00000260191'], ['f_633', 'cpi_9606.ENSP00000360141', 'cpi_9606.ENSP00000323568', 'f_563', 'cpi_9606.ENSP00000343838'], ['f_251', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000309818', 'cpi_9606.ENSP00000396320', 'f_515'], ['f_689', 'cpi_9606.ENSP00000262848', 'cpi_9606.ENSP00000407375', 'f_378', 'cpi_9606.ENSP00000241261'], ['f_564', 'cpi_9606.ENSP00000447378', 'cpi_9606.ENSP00000267843', 'cpi_9606.ENSP00000287936', 'f_784'], ['f_241', 'cpi_9606.ENSP00000364709', 'f_395', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000372750'], ['f_708', 'cpi_9606.ENSP00000305692', 'cpi_9606.ENSP00000347979', 'cpi_9606.ENSP00000355930', 'f_612'], ['f_688', 'cpi_9606.ENSP00000306100', 'cpi_9606.ENSP00000410076', 'cpi_9606.ENSP00000355920', 'f_260'], ['f_150', 'cpi_9606.ENSP00000368438', 'cpi_9606.ENSP00000285979', 'cpi_9606.ENSP00000308774', 'f_756'], ['f_662', 'cpi_9606.ENSP00000303452', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000353878', 'f_213'], ['f_597', 'cpi_9606.ENSP00000467494', 'cpi_9606.ENSP00000371432', 'f_250', 'cpi_9606.ENSP00000309103'], ['f_145', 'cpi_9606.ENSP00000378699', 'cpi_9606.ENSP00000313699', 'f_761', 'cpi_9606.ENSP00000352702'], ['f_707', 'cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000382659', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000400175'], ['f_418', 'cpi_9606.ENSP00000337354', 'cpi_9606.ENSP00000370254', 'f_700', 'cpi_9606.ENSP00000378492'], ['cpi_9606.ENSP00000297494', 'f_779', 'cpi_9606.ENSP00000333496', 'cpi_9606.ENSP00000466799', 'f_383'], ['f_664', 'cpi_9606.ENSP00000433821', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000221515', 'cpi_9606.ENSP00000356694'], ['f_502', 'cpi_9606.ENSP00000248572', 'cpi_9606.ENSP00000368880', 'cpi_9606.ENSP00000262461', 'f_661'], ['f_449', 'cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000305221', 'cpi_9606.ENSP00000362403', 'f_206'], ['f_548', 'cpi_9606.ENSP00000364805', 'cpi_9606.ENSP00000365380', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000263980'], ['f_590', 'cpi_9606.ENSP00000256078', 'cpi_9606.ENSP00000311469', 'f_624', 'cpi_9606.ENSP00000301645'], ['f_453', 'cpi_9606.ENSP00000380514', 'f_544', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000363822'], ['f_602', 'cpi_9606.ENSP00000309845', 'cpi_9606.ENSP00000301146', 'cpi_9606.ENSP00000289753', 'f_414'], ['f_493', 'cpi_9606.ENSP00000319814', 'cpi_9606.ENSP00000359635', 'cpi_9606.ENSP00000384273', 'cpi_9606.ENSP00000287907'], ['f_370', 'cpi_9606.ENSP00000429374', 'cpi_9606.ENSP00000225927', 'cpi_9606.ENSP00000321106', 'cpi_9606.ENSP00000287766'], ['f_545', 'cpi_9606.ENSP00000364731', 'cpi_9606.ENSP00000428924', 'f_824', 'cpi_9606.ENSP00000275300'], ['f_660', 'cpi_9606.ENSP00000349576', 'cpi_9606.ENSP00000339299', 'cpi_9606.ENSP00000394932', 'f_621'], ['f_618', 'cpi_9606.ENSP00000379339', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000239849', 'cpi_9606.ENSP00000354107'], ['f_710', 'cpi_9606.ENSP00000354850', 'cpi_9606.ENSP00000303248', 'cpi_9606.ENSP00000329623', 'f_458'], ['f_381', 'cpi_9606.ENSP00000309591', 'cpi_9606.ENSP00000216797', 'f_531', 'cpi_9606.ENSP00000336630'], ['f_599', 'cpi_9606.ENSP00000039007', 'cpi_9606.ENSP00000263923', 'cpi_9606.ENSP00000308549', 'cpi_9606.ENSP00000228872'], ['f_538', '

🔄 Processing features: 100%|██████████| 2147/2147 [10:23<00:00,  3.44feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'f_413', 'f_262', 'f_151', 'f_845'], ['f_308', 'cpi_9606.ENSP00000288139', 'f_616', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000352035'], ['f_374', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000297268', 'cpi_9606.ENSP00000331912'], ['f_20', 'cpi_9606.ENSP00000261205', 'cpi_9606.ENSP00000295454', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000322617'], ['f_23', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000443194', 'f_631', 'f_118'], ['f_406', 'cpi_9606.ENSP00000376914', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000369375'], ['f_380', 'cpi_9606.ENSP00000263088', 'cpi_9606.ENSP00000356094', 'f_726', 'cpi_9606.ENSP00000342235'], ['f_393', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000354476'], ['f_299', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000262545', 'cpi_9606.ENSP00000355629'], ['f_672', 'cpi_9606.ENSP00000261416', 'f_292', 'cpi_9606.ENSP00000367851', 'cpi_9606.ENSP00000371985'], ['f_287', 'cpi_9606.ENSP00000241052', 'f_31', 'f_194', 'f_799'], ['f_3', 'cpi_9606.ENSP00000264162', 'cpi_9606.ENSP00000023897', 'f_831', 'cpi_9606.ENSP00000337335'], ['f_452', 'f_25', 'cpi_9606.ENSP00000259486', 'f_789', 'f_635'], ['f_614', 'cpi_9606.ENSP00000368305', 'cpi_9606.ENSP00000274545', 'f_511', 'cpi_9606.ENSP00000279178'], ['f_346', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000395653', 'f_629', 'cpi_9606.ENSP00000301891'], ['f_451', 'cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000254976', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000277010'], ['f_15', 'cpi_9606.ENSP00000397582', 'cpi_9606.ENSP00000447149', 'f_428', 'cpi_9606.ENSP00000411593'], ['f_392', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000238379', 'cpi_9606.ENSP00000299267'], ['f_440', 'cpi_9606.ENSP00000262888', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000233146', 'cpi_9606.ENSP00000340691'], ['f_285', 'cpi_9606.ENSP00000297258', 'f_866', 'cpi_9606.ENSP00000219794', 'cpi_9606.ENSP00000263126'], ['f_37', 'cpi_9606.ENSP00000263321', 'f_554', 'cpi_9606.ENSP00000285930', 'f_35'], ['f_366', 'cpi_9606.ENSP00000402608', 'cpi_9606.ENSP00000365775', 'f_768', 'cpi_9606.ENSP00000412673'], ['f_617', 'cpi_9606.ENSP00000394033', 'f_529', 'cpi_9606.ENSP00000359353', 'cpi_9606.ENSP00000374323'], ['f_696', 'cpi_9606.ENSP00000274353', 'cpi_9606.ENSP00000414334', 'cpi_9606.ENSP00000355657', 'f_830'], ['f_405', 'cpi_9606.ENSP00000229277', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000264318', 'f_510'], ['f_643', 'cpi_9606.ENSP00000357204', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000349252', 'cpi_9606.ENSP00000360493'], ['f_33', 'f_706', 'f_350', 'cpi_9606.ENSP00000352835', 'cpi_9606.ENSP00000359285'], ['f_339', 'f_297', 'cpi_9606.ENSP00000332369', 'f_771', 'f_736'], ['f_528', 'cpi_9606.ENSP00000216465', 'cpi_9606.ENSP00000274547', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000319591'], ['f_186', 'cpi_9606.ENSP00000229319', 'cpi_9606.ENSP00000346103', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000409007'], ['f_571', 'f_815', 'cpi_9606.ENSP00000262367', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000394936'], ['f_420', 'cpi_9606.ENSP00000337746', 'cpi_9606.ENSP00000225964', 'f_328', 'f_767'], ['f_516', 'cpi_9606.ENSP00000471397', 'f_47', 'cpi_9606.ENSP00000296370', 'f_27'], ['f_391', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000429374', 'cpi_9606.ENSP00000430684', 'cpi_9606.ENSP00000370381'], ['f_192', 'cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000386029', 'f_46', 'cpi_9606.ENSP00000352011'], ['f_390', 'cpi_9606.ENSP00000011292', 'cpi_9606.ENSP00000264637', 'cpi_9606.ENSP00000304822', 'cpi_9606.ENSP00000319788'], ['f_697', 'cpi_9606.ENSP00000313699', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000360773', 'cpi_9606.ENSP00000296122'], ['f_569', 'f_861', 'cpi_9606.ENSP00000338548', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000274793'], ['f_566', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000261937', 'cpi_9606.ENSP00000318822'], ['f_143', 'cpi_9606.ENSP00000366927', 'cpi_9606.ENSP00000443459', 'f_836', 'f_330'], ['f_146', 'cpi_9606.ENSP00000359100', 'f_526', 'cpi_9606.ENSP00000263339', 'f_327'], ['cpi_9606.ENSP00000311032', 'f_670', 'f_551', 'cpi_9606.ENSP00000327431', 'f_518'], ['f_19', 'cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000367848', 'cpi_9606.ENSP00000398632', 'f_773'], ['f_712', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000293230', 'f_834'], ['f_24', 'cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000222381', 'f_752', 'f_509'], ['f_12', 'cpi_9606.ENSP00000320866', 'cpi_9606.ENSP00000352608', 'cpi_9606.ENSP00000445340', 'cpi_9606.ENSP00000226574'], ['f_639', 'f_533', 'cpi_9606.ENSP00000299178', 'f_427', 'cpi_9606.ENSP00000292896'], ['f_185', 'cpi_9606.ENSP00000386284', 'cpi_9606.ENSP00000359793', 'cpi_9606.ENSP00000344352', 'cpi_9606.ENSP00000221972'], ['f_611', 'cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000451040', 'cpi_9606.ENSP00000353362'], ['f_335', 'cpi_9606.ENSP00000333994', 'cpi_9606.ENSP00000471569', 'cpi_9606.ENSP00000291700', 'f_466'], ['f_659', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000332296', 'cpi_9606.ENSP00000200676', 'cpi_9606.ENSP00000372023'], ['f_181', 'cpi_9606.ENSP00000234111', 'cpi_9606.ENSP00000448059', 'cpi_9606.ENSP00000349320', 'f_166'], ['f_338', 'f_675', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000298352', 'cpi_9606.ENSP00000245206'], ['f_535', 'cpi_9606.ENSP00000332139', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000378517', 'f_497'], ['f_537', 'cpi_9606.ENSP00000303211', 'f_488', 'f_715', 'cpi_9606.ENSP00000372547'], ['f_443', 'cpi_9606.ENSP00000223366', 'cpi_9606.ENSP00000327850', 'cpi_9606.ENSP00000176763', 'f_788'], ['f_340', 'cpi_9606.ENSP00000306606', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000297350', 'f_460'], ['f_656', 'cpi_9606.ENSP00000405573', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000312455', 'f_436'], ['f_26', 'cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000380247', 'f_408', 'f_496'], ['f_257', 'cpi_9606.ENSP00000332549', 'cpi_9606.ENSP00000251566', 'cpi_9606.ENSP00000292513', 'f_361'], ['f_540', 'cpi_9606.ENSP00000308897', 'cpi_9606.ENSP00000232219', 'cpi_9606.ENSP00000312664', 'cpi_9606.ENSP00000266376'], ['cpi_9606.ENSP00000265724', 'f_43', 'f_401', 'f_207', 'f_131'], ['f_10', 'cpi_9606.ENSP00000226299', 'cpi_9606.ENSP00000296677', 'cpi_9606.ENSP00000343477', 'cpi_9606.ENSP00000301178'], ['cpi_9606.ENSP00000231509', 'f_34', 'f_826', 'f_717', 'cpi_9606.ENSP00000351957'], ['f_693', 'cpi_9606.ENSP00000270142', 'f_422', 'cpi_9606.ENSP00000275525', 'cpi_9606.ENSP00000367102'], ['f_368', 'cpi_9606.ENSP00000264708', 'f_522', 'f_812', 'cpi_9606.ENSP00000295400'], ['f_21', 'cpi_9606.ENSP00000306490', 'f_116', 'cpi_9606.ENSP00000338082', 'cpi_9606.ENSP00000222002'], ['f_686', 'f_456', 'f_215', 'f_429', 'cpi_9606.ENSP00000231751'], ['f_681', 'f_676', 'f_417', 'cpi_9606.ENSP00000255084', 'cpi_9606.ENSP00000410732'], ['f_341', 'cpi_9606.ENSP00000273398', 'cpi_9606.ENSP00000359635', 'cpi_9606.ENSP00000216037', 'cpi_9606.ENSP00000291295'], ['f_567', 'cpi_9606.ENSP00000316786', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000356954', 'cpi_9606.ENSP00000343204'], ['f_2', 'cpi_9606.ENSP00000362576', 'cpi_9606.ENSP00000251535', 'cpi_9606.ENSP00000225474', 'f_587'], ['f_345', 'cpi_9606.ENSP00000277508', 'cpi_9606.ENSP00000346148', 'cpi_9606.ENSP00000246553', 'cpi_9606.ENSP00000376943'], ['cpi_9606.ENSP00000264381', 'f_458', 'f_719', 'f_770', 'cpi_9606.ENSP00000417229'], ['f_777', 'cpi_9606.ENSP00000342070', 'f_778', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000333212'], ['f_698', 'cpi_9606.ENSP00000364709', 'f_388', 'cpi_9606.ENSP00000297316', 'f_725'], ['f_642', 'f_407', 'cpi_9606.ENSP00000369654', 'f_568', 'f_820'], ['f_638', 'cpi_9606.ENSP00000237014', 'cpi_9606.ENSP00000216862', 'f_757', 'cpi_9606.ENSP00000345708'], ['f_332', 'cpi_9606.ENSP00000380318', 'cpi_9606.ENSP00000387888', 'cpi_9606.ENSP00000389338', 'f_202'], ['f_16', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000387683', 'f_839', 'f_622'], ['f_180', 'cpi_9606.ENSP00000261267', 'cpi_9606.ENSP00000368253', 'f_455', 'f_298'], ['f_145', 'cpi_9606.ENSP00000377192', 'cpi_9606.ENSP00000373477', 'f_782', 'f_827'], ['f_615', 'cpi_9606.ENSP00000318820', 'f_729', 'cpi_9606.ENSP00000369038', 'cpi_9606.ENSP00000387946'], ['f_11', 'cpi_9606.ENSP00000226578', 'cpi_9606.ENSP00000309493', 'cpi_9606.ENSP00000457706', 'cpi_9606.ENSP00000000442'], ['f_613', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000323568', 'cpi_9606.ENSP00000370473', 'cpi_9606.ENSP00000410076'], ['f_684', 'cpi_9606.ENSP00000358727', 'f_474', 'cpi_9606.ENSP00000365016', 'f_785'], ['f_553', 'cpi_9606.ENSP00000298171', 'cpi_9606.ENSP00000270776', 'cpi_9606.ENSP00000299847', 'f_764'], ['f_691', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000216540', 'f_792', 'f_214'], ['f_439', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000265403', 'cpi_9606.ENSP00000352702'], ['f_692', 'cpi_9606.ENSP00000276651', 'cpi_9606.ENSP00000302811', 'f_473', 'cpi_9606.ENSP00000386306'], ['f_464', 'cpi_9606.ENSP00000364035', 'cpi_9606.ENSP00000260010', 'cpi_9606.ENSP00000267843', 'cpi_9606.ENSP00000343040'], ['f_798', 'cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000359539', 'f_494', 'cpi_9606.ENSP00000348069'], ['f_365', 'cpi_9606.ENSP00000366620', 'cpi_9606.ENSP00000365380', 'cpi_9606.ENSP00000326119', 'f_583'], ['f_18', 'cpi_9606.ENSP00000472933', 'cpi_9606.ENSP00000470087', 'cpi_9606.ENSP00000252809', 'cpi_9606.ENSP00000311095'], ['f_579', 'cpi_9606.ENSP00000330032', 'cpi_9606.ENSP00000248041', 'f_722', 'cpi_9606.ENSP00000257290'], ['f_689', 'cpi_9606.ENSP00000244217', 'f_650', 'cpi_9606.ENSP00000286301', 'f_791'], ['cpi_9606.ENSP00000295897', 'f_343', 'f_187', 'f_164', 'f_763'], ['f_593', 'cpi_9606.ENSP00000419692', 'cpi_9606.ENSP00000382791', 'cpi_9606.ENSP00000258749', 'f_229'], ['f_663', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000420927', 'f_813', 'cpi_9606.ENSP00000369530'], ['f_14', 'cpi_9606.ENSP00000354499', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000222330', 'f_505'], ['f_776', 'cpi_9606.ENSP00000390600', 'f_489', 'cpi_9606.ENSP00000364212', 'f_167'], ['f_353', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000257068', 'cpi_9606.ENSP00000256958', 'f_749'], ['f_637', 'cpi_9606.ENSP00000305480', 'f_728', 'cpi_9606.ENSP00000361359', 'f_508'], ['f_337', 'cpi_9606.ENSP00000358301', 'f_477', 'cpi_9606.ENSP00000296046', 'f_833'], ['f_294', 'cpi_9606.ENSP00000340943', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000320935', 'cpi_9606.ENSP00000329357'], ['f_462', 'f_423', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000356729', 'f_486'], ['f_667', 'cpi_9606.ENSP00000263269', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000347942', 'f_647'], ['f_430', 'cpi_9606.ENSP00000359680', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000241261', 'f_750'], ['f_690', 'f_609', 'cpi_9606.ENSP00000319814', 'cpi_9606.ENSP00000357981', 'f_527'], ['f_249', 'f_419', 'f_305', 'cpi_9606.ENSP00000353224', 'cpi_9606.ENSP00000282753'], ['f_671', 'cpi_9606.ENSP00000362353', 'cpi_9606.ENSP00000353679', 'cpi_9606.ENSP00000282561', 'f_195'], ['f_646', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000358784', 'cpi_9606.ENSP00000275216', 'cpi_9606.ENSP00000242057'], ['f_797', 'cpi_9606.ENSP00000284981', 'f_483', 'f_132', 'cpi_9606.ENSP00000259396'], ['f_628', 'cpi_9606.ENSP00000364782', 'cpi_9606.ENSP00000303686', 'cpi_9606.ENSP00000254227', 'f_448'], ['f_241', 'cpi_9606.ENSP00000367123', 'f_129', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000261799'], ['f_342', 'cpi_9606.ENSP00000355536', 'f_230', 'f_475', 'cpi_9606.ENSP00000344192'], ['f_645', 'cpi_9606.ENSP00000260649', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000459962', 'cpi_9606.ENSP00000389414'], ['f_549', 'cpi_9606.ENSP00000251453', 'cpi_9606.ENSP00000236671', 'cpi_9606.ENSP00000309124', 'f_653'], ['f_680', 'cpi_9606.ENSP00000306100', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000231454', 'f_644'], ['f_9', 'cpi_9606.ENSP00000383365', 'cpi_9606.ENSP00000295491', 'cpi_9606.ENSP00000434045', 'cpi_9606.ENSP00000252723'], ['f_293', 'cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000253004', 'f_740'], ['f_695', 'f_822', 'cpi_9606.ENSP00000354511', 'cpi_9606.ENSP00000262999', 'f_347'], ['f_248', 'cpi_9606.ENSP00000219700', 'cpi_9606.ENSP00000308165', 'f_759', 'f_394'], ['f_375', 'f_840', 'cpi_9606.ENSP00000262407', 'cpi_9606.ENSP00000287766', 'f_559'], ['f_710', 'cpi_9606.ENSP00000354610', 'cpi_9606.ENSP00000430432', 'cpi_9606.ENSP00000354394', 'cpi_9606.ENSP00000361666'], ['f_560', 'f_242', 'cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000314508', 'cpi_9606.ENSP00000296350'], ['f_633', 'cpi_9606.ENSP00000216714', 'cpi_9606.ENSP00000362513', 'cpi_9606.ENSP00000296871', 'f_409'], ['f_708', 'cpi_9606.ENSP00000354850', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000368104', 'f_461'], ['f_705', 'cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000285979', 'f_159', 'f_216'], ['f_334', 'f_22', 'cpi_9606.ENSP00000350616', 'f_471', 'cpi_9606.ENSP00000381097'], ['f_581', 'cpi_9606.ENSP00000321988', 'cpi_9606.ENSP00000322421', 'cpi_9606.ENSP00000416293', 'f_421'], ['f_818', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000220616', 'f_621', 'cpi_9606.ENSP00000276449'], ['f_199', 'cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000330393', 'f_398', 'f_480'], ['f_682', 'cpi_9606.ENSP00000236850', 'cpi_9606.ENSP00000255465', 'cpi_9606.ENSP00000280357', 'f_454'], ['f_349', 'cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000315644', 'cpi_9606.ENSP00000427514', 'f_860'], ['f_755', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000261465', 'f_742', 'cpi_9606.ENSP00000252486'], ['f_699', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000264399', 'f_517', 'cpi_9606.ENSP00000261693'], ['f_701', 'f_467', 'cpi_9606.ENSP00000260970', 'cpi_9606.ENSP00000364802', 'f_160'], ['f_641', 'cpi_9606.ENSP00000333667', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000239938', 'f_513'], ['f_351', 'cpi_9606.ENSP00000377527', 'cpi_9606.ENSP00000320401', 'cpi_9606.ENSP00000301974', 'f_625'], ['f_709', 'cpi_9606.ENSP00000447378', 'cpi_9606.ENSP00000263980', 'cpi_9606.ENSP00000294728', 'f_543'], ['f_573', 'cpi_9606.ENSP00000264613', 'cpi_9606.ENSP00000260356', 'f_30', 'cpi_9606.ENSP00000393333'], ['f_619', 'cpi_9606.ENSP00000293190', 'cpi_9606.ENSP00000312029', 'cpi_9606.ENSP00000221421', 'f_411'], ['f_193', 'cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000296545', 'cpi_9606.ENSP00000413074', 'f_588'], ['f_702', 'cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000290349', 'cpi_9606.ENSP00000260191', 'f_780'], ['f_0', 'cpi_9606.ENSP00000361465', 'cpi_9606.ENSP00000219919', 'f_558', 'f_738'], ['f_333', 'cpi_9606.ENSP00000293404', 'cpi_9606.ENSP00000248553', 'f_514', 'f_115'], ['f_594', 'cpi_9606.ENSP00000262441', 'cpi_9606.ENSP00000181383', 'cpi_9606.ENSP00000341189', 'cpi_9606.ENSP00000283635'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000358548', 'cpi_9606.ENSP00000353292', 'cpi_9606.ENSP00000362401', 'f_367'], ['f_13', 'cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000325822'], ['f_779', 'cpi_9606.ENSP00000366506', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000233242', 'f_687'], ['f_683', 'cpi_9606.ENSP00000222481', 'cpi_9606.ENSP00000356832', 'cpi_9606.ENSP00000293288', 'f_801'], ['f_688', 'cpi_9606.ENSP00000283646', 'cpi_9606.ENSP00000001008', 'f_314', 'f_721'], ['f_704', 'cpi_9606.ENSP00000314214', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000304895', 'f_784'], ['f_286', 'cpi_9606.ENSP00000363533', 'cpi_9606.ENSP00000346901', 'f_363', 'cpi_9606.ENSP00000256906'], ['f_381', 'cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000241600', 'f_425', 'f_213'], ['f_819', 'cpi_9606.ENSP00000303830', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000355523', 'f_359'], ['f_550', 'cpi_9606.ENSP00000352516', 'cpi_9606.ENSP00000355920', 'f_227', 'cpi_9606.ENSP00000303540'], ['f_412', 'cpi_9606.ENSP00000382342', 'cpi_9606.ENSP00000337773', 'f_515', 'cpi_9606.ENSP00000354569'], ['f_1', 'cpi_9606.ENSP00000363018', 'cpi_9606.ENSP00000304408', 'cpi_9606.ENSP00000334246', 'f_575'], ['f_449', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000211122', 'cpi_9606.ENSP00000366307', 'f_144'], ['f_657', 'cpi_9606.ENSP00000252029', 'cpi_9606.ENSP00000346598', 'cpi_9606.ENSP00000305221', 'cpi_9606.ENSP00000303325'], ['f_711', 'cpi_9606.ENSP00000387536', 'f_301', 'cpi_9606.ENSP00000264657', 'f_17'], ['f_592', 'cpi_9606.ENSP00000222482', 'cpi_9606.ENSP00000435412', 'cpi_9606.ENSP00000267163', 'f_38'], ['f_493', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000299766', 'cpi_9606.ENSP00000286091', 'f_336'], ['f_432', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000354193', 'f_500', 'cpi_9606.ENSP00000385806'], ['f_542', 'cpi_9606.ENSP00000260102', 'cpi_9606.ENSP00000304915', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000371929'], ['f_604', 'cpi_9606.ENSP00000372326', 'cpi_9606.ENSP00000155840', 'f_694', 'cpi_9606.ENSP00000379110'], ['f_437', 'cpi_9606.ENSP00000251595', 'cpi_9606.ENSP00000218721', 'f_803', 'cpi_9606.ENSP00000370254'], ['f_662', 'cpi_9606.ENSP00000309818', 'cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000288602', 'cpi_9606.ENSP00000335511'], ['f_502', 'cpi_9606.ENSP00000330484', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000300061', 'f_605'], ['f_580', 'cpi_9606.ENSP00000382659', 'cpi_9606.ENSP00000250971', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000275300'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000217426', 'f_652', 'cpi_9606.ENSP00000319170', 'f_200'], ['f_664', 'cpi_9606.ENSP00000314649', 'cpi_9606.ENSP00000278175', 'cpi_9606.ENSP00000428340', 'cpi_9606.ENSP00000341045'], ['f_536', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000369703', 'cpi_9606.ENSP00000264867', 'cpi_9606.ENSP00000339527'], ['f_261', 'cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000307014', 'cpi_9606.ENSP00000367309', 'cpi_9606.ENSP00000357336'], ['f_507', 'cpi_9606.ENSP00000220809', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000352584', 'f_761'], ['f_591', 'cpi_9606.ENSP00000356022', 'f_399', 'f_395', 'cpi_9606.ENSP00000261196'], ['f_470', 'cpi_9606.ENSP00000341885', 'cpi_9606.ENSP00000293636', 'cpi_9606.ENSP00000321821', 'cpi_9606.ENSP00000347754'], ['f_574', 'cpi_9606.ENSP00000295731', 'cpi_9606.ENSP00000362508', 'cpi_9606.ENSP00000427279', 'cpi_9606.ENSP00000347979'], ['f_259', 'cpi_9606.ENSP00000321106', 'cpi_9606.ENSP00000262017', 'cpi_9606.ENSP00000252945', 'cpi_9606.ENSP00000218388'], ['f_498', 'cpi_9606.ENSP00000434516', 'cpi_9606.ENSP00000253727', 'cpi_9606.ENSP00000378492', 'cpi_9606.ENSP00000346534'], ['f_352', 'cpi_9606.ENSP00000348395', 'cpi_9606.ENSP00000310405', 'cpi_9606.ENSP00000308032', 'f_805'], ['f_418', 'cpi_9606.ENSP00000279593', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000258042', 'cpi_9606.ENSP00000267101'], ['f_179', 'cpi_9606.ENSP00000305692', 'cpi_9606.ENSP00000370373', 'cpi_9606.ENSP00000262352', 'f_157'], ['f_586', 'cpi_9606.ENSP00000003084', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000333534', 'f_206'], ['f_597', 'cpi_9606.ENSP00000383558', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000391826', 'f_250'], ['f_377', 'cpi_9606.ENSP00000310219', 'cpi_9606.ENSP00000221515', 'f_610', 'cpi_9606.ENSP00000324248'], ['f_548', 'cpi_9606.ENSP00000309477', 'cpi_9606.ENSP00000239849', 'cpi_9606.ENSP00000307599', 'f_378'], ['f_459', 'cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000353878', 'cpi_9606.ENSP00000268053'], ['f_344', 'cpi_9606.ENSP00000362329', 'cpi_9606.ENSP00000377948', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000346768'], ['f_665', 'cpi_9606.ENSP00000364805', 'cpi_9606.ENSP00000260630', 'f_563', 'cpi_9606.ENSP00000303452'], ['f_618', 'cpi_9606.ENSP00000346067', 'cpi_9606.ENSP00000349577', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000231228'], ['f_487', 'cpi_9606.ENSP00000252321', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000451560', 'cpi_9606.

🔄 Processing features: 100%|██████████| 2147/2147 [10:24<00:00,  3.44feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'f_26', 'f_408', 'f_151', 'f_413'], ['f_308', 'cpi_9606.ENSP00000334198', 'f_629', 'cpi_9606.ENSP00000374323', 'cpi_9606.ENSP00000385026'], ['f_374', 'cpi_9606.ENSP00000039007', 'f_768', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000409007'], ['f_23', 'f_687', 'cpi_9606.ENSP00000261416', 'f_509', 'f_631'], ['f_20', 'cpi_9606.ENSP00000254976', 'cpi_9606.ENSP00000333212', 'cpi_9606.ENSP00000347942', 'cpi_9606.ENSP00000286479'], ['f_3', 'cpi_9606.ENSP00000264162', 'cpi_9606.ENSP00000367102', 'f_726', 'cpi_9606.ENSP00000342235'], ['f_393', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000229447', 'f_845', 'cpi_9606.ENSP00000354476'], ['f_37', 'cpi_9606.ENSP00000263321', 'f_43', 'f_35', 'cpi_9606.ENSP00000262367'], ['f_346', 'cpi_9606.ENSP00000395653', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000279178', 'cpi_9606.ENSP00000394936'], ['f_287', 'cpi_9606.ENSP00000241052', 'f_292', 'f_670', 'cpi_9606.ENSP00000356094'], ['f_380', 'cpi_9606.ENSP00000263088', 'f_789', 'f_616', 'cpi_9606.ENSP00000360773'], ['f_614', 'cpi_9606.ENSP00000274353', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000389338'], ['f_366', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000402152', 'f_428', 'cpi_9606.ENSP00000369375'], ['f_452', 'f_25', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000233146', 'f_757'], ['f_571', 'cpi_9606.ENSP00000319170', 'f_799', 'cpi_9606.ENSP00000301891', 'cpi_9606.ENSP00000241453'], ['f_392', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000255409', 'f_510'], ['f_672', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000341885', 'f_118', 'cpi_9606.ENSP00000221421'], ['f_285', 'cpi_9606.ENSP00000242375', 'f_866', 'cpi_9606.ENSP00000263857', 'cpi_9606.ENSP00000221972'], ['f_299', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000380318', 'cpi_9606.ENSP00000355629'], ['f_420', 'cpi_9606.ENSP00000337746', 'f_31', 'f_328', 'f_831'], ['f_33', 'f_350', 'f_706', 'cpi_9606.ENSP00000352835', 'f_417'], ['f_340', 'cpi_9606.ENSP00000368305', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000319788', 'cpi_9606.ENSP00000304822'], ['f_390', 'cpi_9606.ENSP00000222481', 'cpi_9606.ENSP00000264637', 'cpi_9606.ENSP00000356832', 'f_27'], ['f_406', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000257290', 'cpi_9606.ENSP00000263126'], ['f_696', 'cpi_9606.ENSP00000354610', 'f_511', 'cpi_9606.ENSP00000262461', 'f_47'], ['f_15', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000445340', 'cpi_9606.ENSP00000451040'], ['f_146', 'cpi_9606.ENSP00000261205', 'f_836', 'cpi_9606.ENSP00000430684', 'cpi_9606.ENSP00000365016'], ['f_643', 'cpi_9606.ENSP00000332256', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000231228', 'cpi_9606.ENSP00000414334'], ['f_192', 'cpi_9606.ENSP00000327431', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000265294', 'f_635'], ['f_617', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000428924', 'cpi_9606.ENSP00000359334'], ['f_440', 'cpi_9606.ENSP00000262888', 'cpi_9606.ENSP00000378517', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000349576'], ['f_697', 'cpi_9606.ENSP00000354850', 'f_830', 'f_749', 'cpi_9606.ENSP00000344352'], ['f_391', 'cpi_9606.ENSP00000364035', 'cpi_9606.ENSP00000312455', 'f_725', 'cpi_9606.ENSP00000377947'], ['f_405', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000316786', 'cpi_9606.ENSP00000295454', 'cpi_9606.ENSP00000367851'], ['f_639', 'cpi_9606.ENSP00000410732', 'f_820', 'f_460', 'cpi_9606.ENSP00000355930'], ['f_185', 'cpi_9606.ENSP00000314214', 'cpi_9606.ENSP00000323568', 'cpi_9606.ENSP00000216037', 'f_587'], ['f_12', 'cpi_9606.ENSP00000386284', 'cpi_9606.ENSP00000339299', 'f_529', 'f_554'], ['f_638', 'cpi_9606.ENSP00000312286', 'f_675', 'cpi_9606.ENSP00000277120', 'f_773'], ['f_451', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000282753', 'cpi_9606.ENSP00000265403', 'cpi_9606.ENSP00000277010'], ['f_712', 'cpi_9606.ENSP00000261755', 'f_834', 'f_767', 'cpi_9606.ENSP00000359353'], ['f_2', 'cpi_9606.ENSP00000219794', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000367848', 'f_526'], ['f_19', 'cpi_9606.ENSP00000472933', 'cpi_9606.ENSP00000470087', 'f_297', 'cpi_9606.ENSP00000216862'], ['f_186', 'cpi_9606.ENSP00000262407', 'cpi_9606.ENSP00000330393', 'f_388', 'cpi_9606.ENSP00000457706'], ['f_181', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000277508', 'cpi_9606.ENSP00000349320', 'f_166'], ['f_535', 'cpi_9606.ENSP00000471397', 'f_327', 'f_497', 'cpi_9606.ENSP00000296370'], ['f_528', 'cpi_9606.ENSP00000216465', 'cpi_9606.ENSP00000368253', 'f_330', 'f_729'], ['f_613', 'cpi_9606.ENSP00000248935', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000305422', 'f_583'], ['f_339', 'cpi_9606.ENSP00000332369', 'f_771', 'f_736', 'cpi_9606.ENSP00000353362'], ['f_143', 'cpi_9606.ENSP00000229319', 'cpi_9606.ENSP00000274793', 'f_764', 'f_719'], ['f_569', 'cpi_9606.ENSP00000237014', 'f_214', 'cpi_9606.ENSP00000343477', 'cpi_9606.ENSP00000258749'], ['f_443', 'cpi_9606.ENSP00000354554', 'cpi_9606.ENSP00000339527', 'f_788', 'f_785'], ['f_566', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000447173', 'f_778', 'cpi_9606.ENSP00000389414'], ['f_516', 'cpi_9606.ENSP00000330484', 'cpi_9606.ENSP00000364802', 'cpi_9606.ENSP00000312029', 'f_298'], ['f_341', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000273398', 'f_715', 'cpi_9606.ENSP00000354394'], ['f_338', 'cpi_9606.ENSP00000387123', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000252809', 'f_401'], ['f_351', 'cpi_9606.ENSP00000226578', 'cpi_9606.ENSP00000332296', 'f_436', 'cpi_9606.ENSP00000222330'], ['f_681', 'f_215', 'f_466', 'cpi_9606.ENSP00000342070', 'f_427'], ['f_257', 'cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000299847', 'f_361'], ['cpi_9606.ENSP00000264381', 'f_605', 'f_752', 'f_164', 'f_465'], ['cpi_9606.ENSP00000311032', 'f_131', 'f_167', 'cpi_9606.ENSP00000352011', 'f_116'], ['f_332', 'cpi_9606.ENSP00000383365', 'cpi_9606.ENSP00000381097', 'cpi_9606.ENSP00000417229', 'cpi_9606.ENSP00000387946'], ['f_335', 'f_815', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000253004', 'cpi_9606.ENSP00000471569'], ['f_345', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000394033', 'f_505'], ['f_698', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000410294', 'cpi_9606.ENSP00000459962'], ['f_692', 'cpi_9606.ENSP00000270625', 'cpi_9606.ENSP00000346901', 'cpi_9606.ENSP00000386229', 'f_473'], ['f_248', 'f_262', 'cpi_9606.ENSP00000367123', 'f_518', 'cpi_9606.ENSP00000242057'], ['f_24', 'cpi_9606.ENSP00000319984', 'f_407', 'cpi_9606.ENSP00000285930', 'f_551'], ['f_540', 'cpi_9606.ENSP00000359680', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000262999'], ['f_659', 'cpi_9606.ENSP00000302728', 'cpi_9606.ENSP00000329357', 'f_839', 'cpi_9606.ENSP00000261937'], ['f_684', 'cpi_9606.ENSP00000330032', 'f_474', 'cpi_9606.ENSP00000427514', 'f_496'], ['f_365', 'cpi_9606.ENSP00000297258', 'cpi_9606.ENSP00000328173', 'cpi_9606.ENSP00000360493', 'f_827'], ['f_553', 'cpi_9606.ENSP00000298171', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000003100', 'f_229'], ['f_579', 'cpi_9606.ENSP00000374265', 'cpi_9606.ENSP00000164139', 'cpi_9606.ENSP00000267101', 'cpi_9606.ENSP00000386306'], ['f_689', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000409612', 'cpi_9606.ENSP00000286301', 'f_791'], ['f_567', 'cpi_9606.ENSP00000319814', 'cpi_9606.ENSP00000274547', 'cpi_9606.ENSP00000348069', 'cpi_9606.ENSP00000369530'], ['f_693', 'cpi_9606.ENSP00000270142', 'f_422', 'f_194', 'f_533'], ['f_11', 'cpi_9606.ENSP00000280701', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000343040', 'f_202'], ['f_686', 'f_419', 'cpi_9606.ENSP00000333994', 'f_750', 'cpi_9606.ENSP00000356954'], ['f_645', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000301974', 'cpi_9606.ENSP00000358548', 'cpi_9606.ENSP00000411593'], ['f_667', 'cpi_9606.ENSP00000369654', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000259089', 'f_650'], ['f_375', 'f_840', 'cpi_9606.ENSP00000353679', 'cpi_9606.ENSP00000312664', 'cpi_9606.ENSP00000308165'], ['f_777', 'cpi_9606.ENSP00000256119', 'f_494', 'cpi_9606.ENSP00000382659', 'f_455'], ['f_656', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000386171', 'cpi_9606.ENSP00000355657', 'cpi_9606.ENSP00000296871'], ['f_294', 'f_782', 'cpi_9606.ENSP00000340943', 'cpi_9606.ENSP00000234071', 'f_475'], ['f_537', 'cpi_9606.ENSP00000303211', 'f_488', 'f_483', 'cpi_9606.ENSP00000283254'], ['f_333', 'cpi_9606.ENSP00000358727', 'cpi_9606.ENSP00000260010', 'cpi_9606.ENSP00000226574', 'f_722'], ['f_611', 'cpi_9606.ENSP00000338548', 'cpi_9606.ENSP00000361206', 'f_861', 'cpi_9606.ENSP00000288139'], ['f_293', 'cpi_9606.ENSP00000356022', 'f_826', 'f_792', 'f_195'], ['f_462', 'f_423', 'cpi_9606.ENSP00000299178', 'f_207', 'cpi_9606.ENSP00000321988'], ['f_16', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000367309', 'f_622', 'cpi_9606.ENSP00000229264'], ['f_1', 'cpi_9606.ENSP00000376914', 'cpi_9606.ENSP00000275525', 'cpi_9606.ENSP00000361359', 'f_676'], ['f_550', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000302811', 'cpi_9606.ENSP00000220616', 'f_489'], ['f_593', 'cpi_9606.ENSP00000360683', 'f_343', 'cpi_9606.ENSP00000282561', 'f_759'], ['f_701', 'f_46', 'f_429', 'cpi_9606.ENSP00000344460', 'f_728'], ['f_646', 'cpi_9606.ENSP00000397582', 'cpi_9606.ENSP00000294728', 'f_812', 'f_394'], ['f_18', 'cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000297268', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000261693'], ['cpi_9606.ENSP00000265724', 'f_454', 'f_448', 'cpi_9606.ENSP00000359532', 'f_30'], ['f_180', 'cpi_9606.ENSP00000381333', 'cpi_9606.ENSP00000314649', 'cpi_9606.ENSP00000266376', 'cpi_9606.ENSP00000252723'], ['f_439', 'cpi_9606.ENSP00000398632', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000353791', 'cpi_9606.ENSP00000261196'], ['f_21', 'cpi_9606.ENSP00000306490', 'f_644', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000376432'], ['f_642', 'f_568', 'cpi_9606.ENSP00000264668', 'f_813', 'cpi_9606.ENSP00000337335'], ['f_699', 'cpi_9606.ENSP00000364709', 'f_508', 'cpi_9606.ENSP00000293288', 'f_717'], ['f_10', 'cpi_9606.ENSP00000226299', 'cpi_9606.ENSP00000296677', 'cpi_9606.ENSP00000326119', 'f_409'], ['f_581', 'cpi_9606.ENSP00000292896', 'cpi_9606.ENSP00000367608', 'f_609', 'f_833'], ['f_199', 'cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000346534', 'f_398', 'cpi_9606.ENSP00000278175'], ['cpi_9606.ENSP00000295897', 'f_115', 'f_514', 'f_477', 'cpi_9606.ENSP00000353292'], ['f_286', 'cpi_9606.ENSP00000430031', 'cpi_9606.ENSP00000365380', 'f_763', 'f_486'], ['f_352', 'cpi_9606.ENSP00000348395', 'cpi_9606.ENSP00000310405', 'cpi_9606.ENSP00000252486', 'cpi_9606.ENSP00000261799'], ['f_619', 'cpi_9606.ENSP00000364212', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000264867', 'cpi_9606.ENSP00000225474'], ['f_818', 'cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000299267', 'cpi_9606.ENSP00000311095'], ['f_691', 'cpi_9606.ENSP00000261733', 'cpi_9606.ENSP00000231454', 'f_513', 'cpi_9606.ENSP00000301178'], ['f_573', 'cpi_9606.ENSP00000371236', 'cpi_9606.ENSP00000239938', 'cpi_9606.ENSP00000023897', 'f_471'], ['f_432', 'cpi_9606.ENSP00000353720', 'f_159', 'cpi_9606.ENSP00000262948', 'cpi_9606.ENSP00000309124'], ['f_671', 'cpi_9606.ENSP00000362353', 'cpi_9606.ENSP00000366927', 'cpi_9606.ENSP00000300061', 'cpi_9606.ENSP00000344192'], ['f_819', 'cpi_9606.ENSP00000236850', 'cpi_9606.ENSP00000223366', 'f_34', 'f_770'], ['f_464', 'cpi_9606.ENSP00000360141', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000283635', 'f_740'], ['f_284', 'cpi_9606.ENSP00000366488', 'cpi_9606.ENSP00000376943', 'f_461', 'f_625'], ['cpi_9606.ENSP00000231509', 'f_707', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000335592', 'f_522'], ['f_690', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000260970', 'f_216', 'f_363'], ['f_337', 'cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000331912', 'f_17'], ['f_342', 'cpi_9606.ENSP00000355536', 'cpi_9606.ENSP00000297350', 'f_230', 'f_647'], ['f_663', 'cpi_9606.ENSP00000419692', 'cpi_9606.ENSP00000371929', 'f_457', 'cpi_9606.ENSP00000310447'], ['f_637', 'cpi_9606.ENSP00000305480', 'cpi_9606.ENSP00000370473', 'f_132', 'f_738'], ['f_628', 'cpi_9606.ENSP00000373477', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000361666', 'f_653'], ['f_798', 'cpi_9606.ENSP00000364731', 'f_485', 'cpi_9606.ENSP00000435591', 'f_129'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000380247', 'f_22', 'cpi_9606.ENSP00000225371', 'cpi_9606.ENSP00000348897'], ['f_680', 'cpi_9606.ENSP00000306100', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000309572', 'f_314'], ['f_241', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000388825', 'cpi_9606.ENSP00000251535', 'f_558'], ['f_368', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000272298', 'cpi_9606.ENSP00000260356', 'f_543'], ['f_615', 'cpi_9606.ENSP00000315644', 'f_242', 'cpi_9606.ENSP00000342560', 'cpi_9606.ENSP00000307599'], ['f_683', 'cpi_9606.ENSP00000405573', 'cpi_9606.ENSP00000295491', 'cpi_9606.ENSP00000267163', 'f_411'], ['f_353', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000321326', 'f_801', 'cpi_9606.ENSP00000321821'], ['f_602', 'cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000196551', 'cpi_9606.ENSP00000320935'], ['f_249', 'f_397', 'cpi_9606.ENSP00000332549', 'f_742', 'f_305'], ['f_704', 'cpi_9606.ENSP00000222553', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000356436', 'f_517'], ['f_430', 'cpi_9606.ENSP00000293404', 'cpi_9606.ENSP00000276449', 'cpi_9606.ENSP00000359663', 'f_559'], ['f_349', 'cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000320866', 'cpi_9606.ENSP00000326219', 'f_144'], ['f_594', 'cpi_9606.ENSP00000309818', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000366662', 'f_588'], ['f_710', 'cpi_9606.ENSP00000305692', 'cpi_9606.ENSP00000255465', 'cpi_9606.ENSP00000267119', 'f_425'], ['f_776', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000350348', 'cpi_9606.ENSP00000463999', 'f_160'], ['f_38', 'f_227', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000350616', 'f_737'], ['f_14', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000324105', 'f_822', 'f_347'], ['f_682', 'cpi_9606.ENSP00000334105', 'cpi_9606.ENSP00000287936', 'cpi_9606.ENSP00000267843', 'f_532'], ['f_666', 'cpi_9606.ENSP00000333667', 'cpi_9606.ENSP00000365663', 'f_336', 'cpi_9606.ENSP00000264657'], ['f_797', 'cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000219700', 'cpi_9606.ENSP00000200676', 'f_480'], ['f_150', 'cpi_9606.ENSP00000003084', 'f_364', 'cpi_9606.ENSP00000259396', 'cpi_9606.ENSP00000307240'], ['f_549', 'cpi_9606.ENSP00000435777', 'cpi_9606.ENSP00000236671', 'cpi_9606.ENSP00000320025', 'f_860'], ['f_334', 'cpi_9606.ENSP00000396308', 'f_515', 'cpi_9606.ENSP00000296122', 'cpi_9606.ENSP00000293330'], ['f_641', 'cpi_9606.ENSP00000319531', 'cpi_9606.ENSP00000300900', 'f_359', 'cpi_9606.ENSP00000278616'], ['f_13', 'cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000317379', 'f_467'], ['f_502', 'cpi_9606.ENSP00000293190', 'cpi_9606.ENSP00000343925', 'f_456', 'cpi_9606.ENSP00000248553'], ['f_536', 'cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000362525'], ['f_688', 'cpi_9606.ENSP00000308024', 'cpi_9606.ENSP00000233242', 'f_721', 'cpi_9606.ENSP00000336630'], ['f_193', 'cpi_9606.ENSP00000284981', 'f_601', 'f_421', 'cpi_9606.ENSP00000303540'], ['f_560', 'cpi_9606.ENSP00000337103', 'cpi_9606.ENSP00000221515', 'f_700', 'cpi_9606.ENSP00000370254'], ['f_458', 'cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000378699', 'cpi_9606.ENSP00000362036', 'f_694'], ['f_705', 'cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000288022', 'f_300', 'cpi_9606.ENSP00000286648'], ['f_655', 'cpi_9606.ENSP00000259486', 'cpi_9606.ENSP00000280357', 'f_301', 'f_187'], ['f_708', 'cpi_9606.ENSP00000307697', 'cpi_9606.ENSP00000380252', 'f_395', 'cpi_9606.ENSP00000335544'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000295731', 'f_200', 'cpi_9606.ENSP00000448059', 'f_378'], ['f_709', 'cpi_9606.ENSP00000344193', 'f_784', 'cpi_9606.ENSP00000309493', 'cpi_9606.ENSP00000341045'], ['f_714', 'cpi_9606.ENSP00000296545', 'cpi_9606.ENSP00000296674', 'cpi_9606.ENSP00000428340', 'f_612'], ['f_507', 'cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000295834', 'f_780'], ['f_734', 'cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000328973', 'f_459'], ['f_591', 'f_399', 'cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000391826'], ['f_145', 'cpi_9606.ENSP00000249750', 'cpi_9606.ENSP00000331746', 'f_575', 'cpi_9606.ENSP00000335511'], ['f_633', 'cpi_9606.ENSP00000216714', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000308549'], ['f_779', 'cpi_9606.ENSP00000234111', 'f_367', 'cpi_9606.ENSP00000333496', 'cpi_9606.ENSP00000307235'], ['f_548', 'cpi_9606.ENSP00000318868', 'cpi_9606.ENSP00000366307', 'cpi_9606.ENSP00000302111', 'f_500'], ['f_255', 'cpi_9606.ENSP00000346067', 'cpi_9606.ENSP00000270776', 'cpi_9606.ENSP00000246553', 'f_157'], ['f_654', 'cpi_9606.ENSP00000256104', 'cpi_9606.ENSP00000346598', 'f_630', 'cpi_9606.ENSP00000324270'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000292513', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000256958', 'f_716'], ['f_695', 'cpi_9606.ENSP00000379213', 'cpi_9606.ENSP00000335620', 'f_414', 'f_213'], ['f_449', 'cpi_9606.ENSP00000263269', 'cpi_9606.ENSP00000358903', 'f_803', 'cpi_9606.ENSP00000291294'], ['f_437', 'cpi_9606.ENSP00000251453', 'cpi_9606.ENSP00000251566', 'cpi_9606.ENSP00000362403', 'cpi_9606.ENSP00000394932'], ['f_259', 'cpi_9606.ENSP00000387699', 'cpi_9606.ENSP00000318585', 'cpi_9606.ENSP00000318822', 'f_711'], ['f_599', 'cpi_9606.ENSP00000369038', 'cpi_9606.ENSP00000216540', 'f_805', 'cpi_9606.ENSP00000241261'], ['f_618', 'cpi_9606.ENSP00000382250', 'cpi_9606.ENSP00000232219', 'cpi_9606.ENSP00000331358', 'f_621'], ['f_442', 'cpi_9606.ENSP00000011292', 'cpi_9606.ENSP00000411658', 'f_610', 'cpi_9606.ENSP00000357283'], ['f_564', 'cpi_9606.ENSP00000379339', 'cpi_9606.ENSP00000271331', 'cpi_9606.ENSP00000219919', 'f_260'], ['f_821', 'cpi_9606.ENSP00000220764', 'f_658', 'cpi_9606.ENSP00000370381', 'cpi_9606.ENSP00000379140'], ['f_9', 'cpi_9606.ENSP00000343885', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000226413', 'f_652'], ['f_590', 'cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000264818', 'f_438', 'cpi_9606.ENSP00000260191'], ['f_662', 'cpi_9606.ENSP00000262441', 'cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000339260', 'f_435'], ['f_356', 'cpi_9606.ENSP00000359100', 'cpi_9606.ENSP00000430432', 'cpi_9606.ENSP00000372023', 'cpi_9606.ENSP00000264498'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000429374', 'cpi_9606.ENSP00000230671', 'f_152', 'cpi_9606.ENSP00000358223'], ['f_188', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000299766', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000355533'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000019103', 'cpi_9606.ENSP00000362649', 'f_800', 'cpi_9606.ENSP00000305302'], ['f_450', 'cpi_9606.ENSP00000408695', 'cpi_9606.ENSP00000410076', 'f_761', 'cpi_9606.ENSP00000308774'], ['f_574', 'cpi_9606.ENSP00000364805', 'cpi_9606.ENSP00000359635', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000354558'], ['f_498', 'cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000358784', 'cpi_9606.ENSP00000322924', 'cpi_9606.ENSP00000400175'], ['f_702', 'cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000263980', 'cpi_9606.ENSP00000351885', 'f_383'], ['f_679', 'cpi_9606.ENSP00000402608', 'cpi_9606.ENSP00000353427', 'cpi_9606.ENSP00000263923', 'cpi_9606.ENSP00000292303'], ['f_597', 'cpi_9606.ENSP00000265171', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000356694', 'cpi_9606.ENSP00000366506'], ['f_487', 'cpi_9606.ENSP00000377192', 'cpi_9606.ENSP00000353878', 'cpi_9606.ENSP00000287766', 'f_735'], ['f_623', 'cpi_9606.ENSP00000371554', 'cpi_9606.ENSP00000266682', 'cpi_9606.ENSP00000265643', 'f_250'], ['f_755', 'cpi_9606.ENSP00000243167', 'cpi_9606.ENSP00000237527', 'cpi_9606

🔄 Processing features: 100%|██████████| 2147/2147 [10:24<00:00,  3.44feat/s]

XofN_groups: [['f_308', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000351957'], ['f_20', 'cpi_9606.ENSP00000254976', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000286479'], ['f_299', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000306100', 'f_151', 'cpi_9606.ENSP00000200676'], ['cpi_9606.ENSP00000337915', 'f_413', 'f_436', 'cpi_9606.ENSP00000261416', 'f_866'], ['f_374', 'cpi_9606.ENSP00000402608', 'cpi_9606.ENSP00000225927', 'f_834', 'f_831'], ['f_285', 'cpi_9606.ENSP00000302441', 'cpi_9606.ENSP00000447149', 'f_845', 'cpi_9606.ENSP00000309124'], ['f_3', 'cpi_9606.ENSP00000274353', 'cpi_9606.ENSP00000367102', 'f_529', 'f_768'], ['f_393', 'cpi_9606.ENSP00000380318', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000355629'], ['f_346', 'cpi_9606.ENSP00000395653', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000357068', 'f_629'], ['f_672', 'cpi_9606.ENSP00000264162', 'cpi_9606.ENSP00000362353', 'f_292', 'cpi_9606.ENSP00000367851'], ['f_406', 'cpi_9606.ENSP00000352035', 'f_616', 'cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000300061'], ['f_37', 'cpi_9606.ENSP00000263321', 'f_43', 'f_27', 'cpi_9606.ENSP00000282753'], ['f_440', 'f_25', 'cpi_9606.ENSP00000263088', 'cpi_9606.ENSP00000342235', 'f_789'], ['f_287', 'cpi_9606.ENSP00000241052', 'f_118', 'f_194', 'f_31'], ['f_23', 'f_408', 'cpi_9606.ENSP00000443194', 'f_164', 'cpi_9606.ENSP00000309818'], ['f_392', 'cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000332296', 'cpi_9606.ENSP00000277010'], ['f_420', 'cpi_9606.ENSP00000312326', 'f_328', 'f_726', 'cpi_9606.ENSP00000312304'], ['f_380', 'cpi_9606.ENSP00000291565', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000360773', 'cpi_9606.ENSP00000367848'], ['f_452', 'cpi_9606.ENSP00000259486', 'cpi_9606.ENSP00000233146', 'cpi_9606.ENSP00000257290', 'f_635'], ['f_15', 'cpi_9606.ENSP00000397582', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000430684'], ['f_451', 'cpi_9606.ENSP00000368305', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000304822', 'cpi_9606.ENSP00000354476'], ['f_614', 'cpi_9606.ENSP00000319531', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000359353', 'f_429'], ['f_571', 'f_554', 'cpi_9606.ENSP00000319170', 'f_736', 'cpi_9606.ENSP00000279178'], ['f_366', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000220616', 'f_428'], ['f_19', 'cpi_9606.ENSP00000472933', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000333212'], ['f_390', 'cpi_9606.ENSP00000222481', 'cpi_9606.ENSP00000264637', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000356832'], ['f_639', 'f_417', 'f_670', 'f_767', 'cpi_9606.ENSP00000292896'], ['f_696', 'cpi_9606.ENSP00000354850', 'cpi_9606.ENSP00000414334', 'f_511', 'f_47'], ['f_10', 'cpi_9606.ENSP00000226840', 'cpi_9606.ENSP00000343477', 'cpi_9606.ENSP00000356094', 'cpi_9606.ENSP00000216862'], ['f_339', 'f_297', 'cpi_9606.ENSP00000332369', 'f_799', 'f_771'], ['f_185', 'cpi_9606.ENSP00000364035', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000372547'], ['f_143', 'cpi_9606.ENSP00000261733', 'f_836', 'cpi_9606.ENSP00000320866', 'cpi_9606.ENSP00000258749'], ['f_617', 'cpi_9606.ENSP00000376914', 'cpi_9606.ENSP00000374323', 'cpi_9606.ENSP00000283254', 'f_820'], ['f_332', 'cpi_9606.ENSP00000383365', 'cpi_9606.ENSP00000344674', 'cpi_9606.ENSP00000221972', 'f_526'], ['f_12', 'cpi_9606.ENSP00000330032', 'cpi_9606.ENSP00000364802', 'f_773', 'f_587'], ['f_146', 'cpi_9606.ENSP00000367123', 'cpi_9606.ENSP00000263126', 'f_510', 'f_706'], ['f_33', 'cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000222002', 'f_350', 'cpi_9606.ENSP00000390600'], ['f_338', 'cpi_9606.ENSP00000357204', 'cpi_9606.ENSP00000354193', 'cpi_9606.ENSP00000261799', 'f_401'], ['f_186', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000344460', 'cpi_9606.ENSP00000216037', 'f_26'], ['f_659', 'cpi_9606.ENSP00000356729', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000343040'], ['f_656', 'cpi_9606.ENSP00000306606', 'cpi_9606.ENSP00000309493', 'cpi_9606.ENSP00000378517', 'f_460'], ['cpi_9606.ENSP00000311032', 'f_509', 'f_207', 'cpi_9606.ENSP00000349320', 'f_131'], ['f_535', 'cpi_9606.ENSP00000262888', 'cpi_9606.ENSP00000354107', 'f_330', 'cpi_9606.ENSP00000365016'], ['f_643', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000283646', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000276449'], ['f_528', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000362508', 'cpi_9606.ENSP00000348069'], ['f_681', 'f_215', 'f_676', 'cpi_9606.ENSP00000291295', 'f_427'], ['f_613', 'cpi_9606.ENSP00000354610', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000346103', 'cpi_9606.ENSP00000312455'], ['f_693', 'f_815', 'cpi_9606.ENSP00000270142', 'f_675', 'f_788'], ['cpi_9606.ENSP00000264381', 'f_343', 'f_734', 'f_35', 'cpi_9606.ENSP00000319788'], ['f_340', 'cpi_9606.ENSP00000373477', 'cpi_9606.ENSP00000248572', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000353362'], ['f_443', 'cpi_9606.ENSP00000223366', 'cpi_9606.ENSP00000273398', 'f_327', 'cpi_9606.ENSP00000353292'], ['f_181', 'cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000368253', 'f_166', 'cpi_9606.ENSP00000301891'], ['f_192', 'cpi_9606.ENSP00000229319', 'cpi_9606.ENSP00000330393', 'f_46', 'f_508'], ['f_697', 'cpi_9606.ENSP00000386284', 'cpi_9606.ENSP00000334105', 'f_725', 'f_749'], ['f_391', 'cpi_9606.ENSP00000219794', 'cpi_9606.ENSP00000309103', 'f_764', 'cpi_9606.ENSP00000346534'], ['f_712', 'f_830', 'cpi_9606.ENSP00000260102', 'cpi_9606.ENSP00000283635', 'cpi_9606.ENSP00000389338'], ['f_569', 'f_214', 'cpi_9606.ENSP00000338548', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000274793'], ['f_579', 'cpi_9606.ENSP00000305480', 'f_496', 'cpi_9606.ENSP00000451030', 'cpi_9606.ENSP00000360493'], ['f_335', 'f_752', 'cpi_9606.ENSP00000377192', 'cpi_9606.ENSP00000323568', 'f_750'], ['f_294', 'cpi_9606.ENSP00000355536', 'f_202', 'f_262', 'cpi_9606.ENSP00000355657'], ['f_405', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000295454', 'f_466', 'cpi_9606.ENSP00000296522'], ['f_2', 'cpi_9606.ENSP00000011292', 'cpi_9606.ENSP00000296122', 'cpi_9606.ENSP00000251535', 'cpi_9606.ENSP00000307599'], ['f_341', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000220003', 'cpi_9606.ENSP00000263464', 'f_715'], ['f_646', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000352702', 'f_497'], ['f_1', 'cpi_9606.ENSP00000238379', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000457706', 'cpi_9606.ENSP00000417229'], ['f_257', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000251453', 'cpi_9606.ENSP00000388825', 'f_361'], ['f_566', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000387946'], ['f_21', 'cpi_9606.ENSP00000306490', 'f_116', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000293745'], ['cpi_9606.ENSP00000265724', 'f_722', 'f_455', 'f_22', 'f_757'], ['f_698', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000471569', 'cpi_9606.ENSP00000353472', 'cpi_9606.ENSP00000261937'], ['f_692', 'cpi_9606.ENSP00000261205', 'f_474', 'cpi_9606.ENSP00000309572', 'f_728'], ['f_553', 'cpi_9606.ENSP00000340943', 'cpi_9606.ENSP00000299267', 'cpi_9606.ENSP00000363827', 'f_229'], ['f_611', 'cpi_9606.ENSP00000216465', 'cpi_9606.ENSP00000451040', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000463999'], ['f_671', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000262441', 'cpi_9606.ENSP00000291700', 'f_407'], ['f_38', 'f_559', 'cpi_9606.ENSP00000316786', 'f_650', 'cpi_9606.ENSP00000353224'], ['f_351', 'cpi_9606.ENSP00000226578', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000311095', 'cpi_9606.ENSP00000470087'], ['f_691', 'f_839', 'f_792', 'cpi_9606.ENSP00000249750', 'cpi_9606.ENSP00000450399'], ['f_684', 'cpi_9606.ENSP00000358727', 'cpi_9606.ENSP00000232219', 'f_473', 'cpi_9606.ENSP00000248553'], ['f_375', 'f_242', 'f_631', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000366307'], ['f_439', 'cpi_9606.ENSP00000333994', 'f_840', 'cpi_9606.ENSP00000293288', 'f_719'], ['f_567', 'cpi_9606.ENSP00000371985', 'f_729', 'cpi_9606.ENSP00000252486', 'cpi_9606.ENSP00000389414'], ['f_638', 'cpi_9606.ENSP00000237014', 'f_861', 'f_791', 'f_394'], ['f_516', 'cpi_9606.ENSP00000330484', 'f_298', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000252723'], ['f_686', 'f_419', 'cpi_9606.ENSP00000359285', 'f_622', 'cpi_9606.ENSP00000365686'], ['f_16', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000419692', 'cpi_9606.ENSP00000355192'], ['f_11', 'cpi_9606.ENSP00000039007', 'cpi_9606.ENSP00000310405', 'cpi_9606.ENSP00000225474', 'cpi_9606.ENSP00000262352'], ['f_689', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000216962', 'cpi_9606.ENSP00000381097', 'cpi_9606.ENSP00000358595'], ['f_702', 'cpi_9606.ENSP00000260010', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000326219'], ['f_540', 'cpi_9606.ENSP00000308897', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000252809', 'cpi_9606.ENSP00000344192'], ['f_690', 'cpi_9606.ENSP00000318820', 'f_568', 'cpi_9606.ENSP00000327431', 'f_813'], ['f_776', 'cpi_9606.ENSP00000261267', 'cpi_9606.ENSP00000376776', 'f_132', 'f_518'], ['f_615', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000219700', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000286301'], ['f_777', 'f_494', 'cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000253004', 'cpi_9606.ENSP00000394936'], ['f_683', 'cpi_9606.ENSP00000359100', 'cpi_9606.ENSP00000374265', 'cpi_9606.ENSP00000428340', 'f_583'], ['f_645', 'cpi_9606.ENSP00000277508', 'cpi_9606.ENSP00000275216', 'cpi_9606.ENSP00000335511', 'f_778'], ['f_449', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000405573', 'f_827', 'cpi_9606.ENSP00000254227'], ['f_550', 'cpi_9606.ENSP00000356022', 'cpi_9606.ENSP00000256958', 'f_475', 'f_448'], ['f_14', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000324105', 'f_505', 'cpi_9606.ENSP00000326119'], ['f_560', 'cpi_9606.ENSP00000364709', 'cpi_9606.ENSP00000312664', 'cpi_9606.ENSP00000263339', 'f_785'], ['cpi_9606.ENSP00000303211', 'f_537', 'f_488', 'f_483', 'f_486'], ['f_798', 'f_34', 'cpi_9606.ENSP00000352835', 'f_477', 'cpi_9606.ENSP00000242057'], ['f_667', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000338082', 'f_388', 'cpi_9606.ENSP00000344352'], ['f_701', 'f_609', 'f_167', 'cpi_9606.ENSP00000387123', 'cpi_9606.ENSP00000419782'], ['f_704', 'cpi_9606.ENSP00000382250', 'cpi_9606.ENSP00000331912', 'cpi_9606.ENSP00000445340', 'cpi_9606.ENSP00000282561'], ['f_688', 'cpi_9606.ENSP00000276651', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000354394', 'f_770'], ['f_663', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000259089', 'f_216'], ['f_180', 'cpi_9606.ENSP00000363641', 'cpi_9606.ENSP00000294728', 'f_409', 'f_159'], ['f_619', 'cpi_9606.ENSP00000371236', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000361359', 'f_812'], ['f_642', 'cpi_9606.ENSP00000264668', 'f_422', 'cpi_9606.ENSP00000275300', 'cpi_9606.ENSP00000288139'], ['f_637', 'cpi_9606.ENSP00000332256', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000295834', 'cpi_9606.ENSP00000267101'], ['f_641', 'cpi_9606.ENSP00000406157', 'cpi_9606.ENSP00000262948', 'cpi_9606.ENSP00000337335', 'f_195'], ['cpi_9606.ENSP00000295897', 'f_115', 'f_514', 'cpi_9606.ENSP00000301178', 'cpi_9606.ENSP00000376432'], ['f_342', 'f_782', 'cpi_9606.ENSP00000220764', 'cpi_9606.ENSP00000305221', 'f_160'], ['f_628', 'cpi_9606.ENSP00000216714', 'cpi_9606.ENSP00000263980', 'cpi_9606.ENSP00000435591', 'f_551'], ['f_345', 'cpi_9606.ENSP00000260649', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000255465', 'cpi_9606.ENSP00000361666'], ['f_293', 'cpi_9606.ENSP00000243167', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000386229', 'f_826'], ['f_581', 'cpi_9606.ENSP00000217961', 'cpi_9606.ENSP00000367309', 'f_517', 'f_471'], ['f_18', 'cpi_9606.ENSP00000253303', 'cpi_9606.ENSP00000428924', 'f_763', 'f_717'], ['f_662', 'cpi_9606.ENSP00000299178', 'cpi_9606.ENSP00000370254', 'f_533', 'f_588'], ['cpi_9606.ENSP00000231509', 'f_305', 'cpi_9606.ENSP00000369654', 'f_833', 'cpi_9606.ENSP00000376943'], ['f_536', 'cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000314508', 'cpi_9606.ENSP00000358548', 'cpi_9606.ENSP00000296350'], ['f_462', 'f_423', 'cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000329357'], ['f_199', 'cpi_9606.ENSP00000385834', 'f_489', 'f_398', 'cpi_9606.ENSP00000353791'], ['f_573', 'cpi_9606.ENSP00000298283', 'cpi_9606.ENSP00000216392', 'cpi_9606.ENSP00000275525', 'cpi_9606.ENSP00000347942'], ['f_145', 'cpi_9606.ENSP00000314649', 'cpi_9606.ENSP00000261196', 'cpi_9606.ENSP00000296370', 'f_801'], ['f_334', 'cpi_9606.ENSP00000396308', 'f_625', 'f_461', 'cpi_9606.ENSP00000427514'], ['f_464', 'cpi_9606.ENSP00000362036', 'cpi_9606.ENSP00000338185', 'f_230', 'f_822'], ['f_333', 'cpi_9606.ENSP00000447378', 'cpi_9606.ENSP00000448059', 'cpi_9606.ENSP00000356954', 'f_543'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000328173', 'f_17', 'cpi_9606.ENSP00000264318', 'f_522'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000225371', 'cpi_9606.ENSP00000370381', 'f_687'], ['f_705', 'cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000288022', 'f_467', 'cpi_9606.ENSP00000312029'], ['f_430', 'cpi_9606.ENSP00000253792', 'cpi_9606.ENSP00000264867', 'f_647', 'f_740'], ['f_441', 'cpi_9606.ENSP00000471397', 'cpi_9606.ENSP00000370473', 'f_653', 'f_759'], ['f_24', 'cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000302111', 'cpi_9606.ENSP00000262461'], ['f_193', 'cpi_9606.ENSP00000284981', 'f_644', 'f_513', 'cpi_9606.ENSP00000259396'], ['f_797', 'cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000311165', 'cpi_9606.ENSP00000222330', 'f_301'], ['f_365', 'cpi_9606.ENSP00000248935', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000308165', 'f_558'], ['f_368', 'cpi_9606.ENSP00000272298', 'cpi_9606.ENSP00000260356', 'f_515', 'f_805'], ['f_353', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000350348', 'cpi_9606.ENSP00000234389', 'f_738'], ['f_591', 'cpi_9606.ENSP00000331358', 'cpi_9606.ENSP00000353731', 'f_157', 'f_129'], ['f_248', 'cpi_9606.ENSP00000262407', 'cpi_9606.ENSP00000297316', 'f_454', 'f_30'], ['f_680', 'cpi_9606.ENSP00000366927', 'cpi_9606.ENSP00000410294', 'cpi_9606.ENSP00000454071', 'f_336'], ['f_602', 'cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000296674', 'f_363'], ['f_666', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000314214', 'cpi_9606.ENSP00000233242', 'f_359'], ['f_818', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000394033', 'f_395', 'cpi_9606.ENSP00000407375'], ['f_593', 'cpi_9606.ENSP00000321988', 'cpi_9606.ENSP00000322421', 'cpi_9606.ENSP00000261693', 'cpi_9606.ENSP00000296871'], ['cpi_9606.ENSP00000342007', 'f_347', 'cpi_9606.ENSP00000315011', 'cpi_9606.ENSP00000364805', 'cpi_9606.ENSP00000348897'], ['f_779', 'f_367', 'cpi_9606.ENSP00000234111', 'cpi_9606.ENSP00000333496', 'cpi_9606.ENSP00000412673'], ['f_682', 'cpi_9606.ENSP00000352608', 'cpi_9606.ENSP00000319814', 'cpi_9606.ENSP00000231454', 'f_213'], ['f_259', 'cpi_9606.ENSP00000318585', 'cpi_9606.ENSP00000295491', 'cpi_9606.ENSP00000267163', 'f_227'], ['f_432', 'cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000262367', 'cpi_9606.ENSP00000266376', 'f_411'], ['f_498', 'cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000335592', 'f_780', 'f_314'], ['f_633', 'cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000310447', 'cpi_9606.ENSP00000365663', 'f_860'], ['f_356', 'cpi_9606.ENSP00000429374', 'cpi_9606.ENSP00000270776', 'cpi_9606.ENSP00000310305', 'f_425'], ['f_241', 'cpi_9606.ENSP00000368438', 'cpi_9606.ENSP00000355930', 'cpi_9606.ENSP00000386029', 'f_480'], ['f_9', 'cpi_9606.ENSP00000337746', 'cpi_9606.ENSP00000296677', 'f_721', 'f_200'], ['f_699', 'cpi_9606.ENSP00000309477', 'cpi_9606.ENSP00000274547', 'f_421', 'cpi_9606.ENSP00000292513'], ['f_284', 'cpi_9606.ENSP00000348395', 'cpi_9606.ENSP00000434045', 'f_742', 'cpi_9606.ENSP00000351273'], ['f_286', 'cpi_9606.ENSP00000363533', 'cpi_9606.ENSP00000236671', 'cpi_9606.ENSP00000355920', 'cpi_9606.ENSP00000303540'], ['f_549', 'cpi_9606.ENSP00000380156', 'cpi_9606.ENSP00000386171', 'f_803', 'cpi_9606.ENSP00000239849'], ['f_352', 'cpi_9606.ENSP00000430031', 'cpi_9606.ENSP00000365380', 'f_465', 'cpi_9606.ENSP00000311469'], ['f_349', 'cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000361151', 'cpi_9606.ENSP00000355325', 'f_575'], ['f_604', 'cpi_9606.ENSP00000019103', 'cpi_9606.ENSP00000371432', 'f_456', 'cpi_9606.ENSP00000274545'], ['f_594', 'cpi_9606.ENSP00000272847', 'cpi_9606.ENSP00000347549', 'cpi_9606.ENSP00000343925', 'f_364'], ['f_574', 'cpi_9606.ENSP00000363614', 'cpi_9606.ENSP00000231228', 'f_500', 'cpi_9606.ENSP00000301645'], ['f_502', 'cpi_9606.ENSP00000279593', 'f_144', 'cpi_9606.ENSP00000349577', 'cpi_9606.ENSP00000226574'], ['f_711', 'cpi_9606.ENSP00000302811', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000343204', 'cpi_9606.ENSP00000003100'], ['f_708', 'cpi_9606.ENSP00000346827', 'cpi_9606.ENSP00000240652', 'cpi_9606.ENSP00000320935', 'f_784'], ['f_597', 'cpi_9606.ENSP00000298171', 'cpi_9606.ENSP00000219919', 'cpi_9606.ENSP00000358903', 'f_621'], ['f_585', 'cpi_9606.ENSP00000375730', 'cpi_9606.ENSP00000358223', 'f_605', 'cpi_9606.ENSP00000362549'], ['f_416', 'cpi_9606.ENSP00000359680', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000297350', 'f_652'], ['f_458', 'cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000351209', 'cpi_9606.ENSP00000394932', 'f_694'], ['f_716', 'cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000212015', 'cpi_9606.ENSP00000323549', 'f_251'], ['f_710', 'cpi_9606.ENSP00000293404', 'cpi_9606.ENSP00000391826', 'f_612', 'cpi_9606.ENSP00000287936'], ['f_412', 'cpi_9606.ENSP00000342070', 'f_824', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000218099'], ['f_337', 'cpi_9606.ENSP00000252945', 'cpi_9606.ENSP00000381333', 'cpi_9606.ENSP00000363804', 'f_624'], ['f_437', 'cpi_9606.ENSP00000264357', 'cpi_9606.ENSP00000339527', 'f_249', 'cpi_9606.ENSP00000366662'], ['f_592', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000271331', 'cpi_9606.ENSP00000378890', 'cpi_9606.ENSP00000329623'], ['f_623', 'cpi_9606.ENSP00000467494', 'cpi_9606.ENSP00000301146', 'cpi_9606.ENSP00000362649', 'f_250'], ['f_13', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000301974', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000301141'], ['f_586', 'cpi_9606.ENSP00000003084', 'cpi_9606.ENSP00000321821', 'cpi_9606.ENSP00000346598', 'f_601'], ['f_655', 'cpi_9606.ENSP00000244217', 'cpi_9606.ENSP00000267843', 'cpi_9606.ENSP00000265723', 'f_300'], ['f_709', 'cpi_9606.ENSP00000264705', 'cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000308032', 'f_260'], ['f_548', 'cpi_9606.ENSP00000318868', 'cpi_9606.ENSP00000239938', 'f_397', 'cpi_9606.ENSP00000320025'], ['f_453', 'cpi_9606.ENSP00000332549', 'cpi_9606.ENSP00000262735', 'f_630', 'cpi_9606.ENSP00000308774'], ['f_819', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000337103', 'f_389', 'cpi_9606.ENSP00000305302'], ['cpi_9606.ENSP00000297494', 'f_187', 'cpi_9606.ENSP00000346298', 'cpi_9606.ENSP00000311028', 'cpi_9606.ENSP00000398632'], ['f_188', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000383558', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000318822'], ['f_459', 'cpi_9606.ENSP00000225831', 'cpi_9606.ENSP00000307240', 'f_206', 'cpi_9606.ENSP00000339260'], ['f_755', 'cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000317379', 'f_378', 'cpi_9606.ENSP00000358784'], ['f_418', 'cpi_9606.ENSP00000466399', 'cpi_9606.ENSP00000251566', 'cpi_9606.ENSP00000244741', 'cpi_9606.ENSP00000287766'], ['f_442', 'cpi_9606.ENSP00000433821', 'cpi_9606.ENSP00000352584', 'cpi_9606.ENSP00000267017', 'cpi_9606.ENSP00000362525'], ['f_695', 'cpi_9606.ENSP00000309845', 'cpi_9606.ENSP00000333534', 'f_414', 'f_610'], ['f_150', 'cpi_9606.ENSP00000349467', 'cpi_9606.ENSP00000347979', 'cpi_9606.ENSP00000466799', 'f_457'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000225964', 'f_737'], ['f_344', 'cpi_9606.ENSP000

🔄 Processing features: 100%|██████████| 2147/2147 [10:24<00:00,  3.44feat/s]

XofN_groups: [['f_20', 'cpi_9606.ENSP00000219794', 'cpi_9606.ENSP00000367848', 'cpi_9606.ENSP00000333212', 'cpi_9606.ENSP00000241453'], ['f_299', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000367851', 'cpi_9606.ENSP00000430620', 'f_151'], ['cpi_9606.ENSP00000337915', 'f_413', 'f_262', 'f_845', 'f_768'], ['f_374', 'cpi_9606.ENSP00000386284', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000286648', 'f_726'], ['f_308', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000353791', 'f_616', 'f_722'], ['f_23', 'cpi_9606.ENSP00000385026', 'f_408', 'cpi_9606.ENSP00000355536', 'f_202'], ['f_380', 'cpi_9606.ENSP00000263088', 'f_789', 'f_785', 'cpi_9606.ENSP00000360773'], ['f_3', 'cpi_9606.ENSP00000222256', 'f_676', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000337335'], ['f_452', 'f_25', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000233146', 'f_757'], ['f_614', 'cpi_9606.ENSP00000216465', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000316786'], ['f_617', 'cpi_9606.ENSP00000352035', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000374323', 'f_820'], ['f_393', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000286091', 'cpi_9606.ENSP00000354476'], ['f_285', 'cpi_9606.ENSP00000308897', 'f_866', 'cpi_9606.ENSP00000295834', 'cpi_9606.ENSP00000296370'], ['f_346', 'cpi_9606.ENSP00000395653', 'f_629', 'cpi_9606.ENSP00000279178', 'cpi_9606.ENSP00000376432'], ['f_406', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000300061'], ['f_287', 'cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000356094', 'f_118', 'f_194'], ['f_672', 'cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000262441', 'f_292', 'cpi_9606.ENSP00000274545'], ['f_451', 'cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000277010', 'f_31'], ['cpi_9606.ENSP00000264381', 'f_593', 'f_719', 'cpi_9606.ENSP00000430684', 'f_635'], ['f_15', 'cpi_9606.ENSP00000264162', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000240652', 'cpi_9606.ENSP00000304822'], ['f_37', 'cpi_9606.ENSP00000263321', 'f_35', 'f_509', 'f_350'], ['f_440', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000257290', 'f_725'], ['f_19', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000419782', 'f_510'], ['f_392', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000346827', 'cpi_9606.ENSP00000309124', 'f_214'], ['f_390', 'cpi_9606.ENSP00000222481', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000303248', 'f_27'], ['f_420', 'cpi_9606.ENSP00000262888', 'cpi_9606.ENSP00000253799', 'f_328', 'f_497'], ['f_405', 'cpi_9606.ENSP00000319531', 'cpi_9606.ENSP00000359353', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000221972'], ['f_366', 'cpi_9606.ENSP00000402608', 'f_831', 'f_428', 'cpi_9606.ENSP00000394936'], ['f_339', 'f_297', 'cpi_9606.ENSP00000357204', 'f_834', 'cpi_9606.ENSP00000262367'], ['f_639', 'f_417', 'f_830', 'cpi_9606.ENSP00000410732', 'f_131'], ['f_566', 'cpi_9606.ENSP00000242375', 'f_529', 'cpi_9606.ENSP00000332296', 'cpi_9606.ENSP00000260191'], ['f_696', 'cpi_9606.ENSP00000274353', 'cpi_9606.ENSP00000414334', 'f_511', 'cpi_9606.ENSP00000355657'], ['f_186', 'cpi_9606.ENSP00000397582', 'cpi_9606.ENSP00000226574', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000470087'], ['f_643', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000355629', 'cpi_9606.ENSP00000264318'], ['f_391', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000370381', 'cpi_9606.ENSP00000264637'], ['f_192', 'cpi_9606.ENSP00000354850', 'cpi_9606.ENSP00000389338', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000301891'], ['f_571', 'f_773', 'cpi_9606.ENSP00000234071', 'f_736', 'cpi_9606.ENSP00000356150'], ['f_185', 'cpi_9606.ENSP00000261205', 'cpi_9606.ENSP00000256383', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000343477'], ['f_12', 'cpi_9606.ENSP00000229319', 'f_836', 'cpi_9606.ENSP00000312455', 'cpi_9606.ENSP00000258749'], ['f_146', 'cpi_9606.ENSP00000443194', 'f_526', 'cpi_9606.ENSP00000220616', 'cpi_9606.ENSP00000349320'], ['f_686', 'f_419', 'f_215', 'cpi_9606.ENSP00000342070', 'f_554'], ['f_697', 'cpi_9606.ENSP00000254976', 'cpi_9606.ENSP00000354610', 'cpi_9606.ENSP00000445340', 'f_749'], ['f_338', 'cpi_9606.ENSP00000356729', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000264867', 'cpi_9606.ENSP00000261799'], ['f_712', 'cpi_9606.ENSP00000261755', 'f_767', 'f_771', 'f_47'], ['f_659', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000343040'], ['f_698', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000309572'], ['f_332', 'cpi_9606.ENSP00000383365', 'cpi_9606.ENSP00000365380', 'cpi_9606.ENSP00000457706', 'cpi_9606.ENSP00000417229'], ['f_656', 'cpi_9606.ENSP00000364035', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000298386', 'cpi_9606.ENSP00000319788'], ['f_2', 'cpi_9606.ENSP00000368305', 'cpi_9606.ENSP00000305422', 'f_788', 'cpi_9606.ENSP00000358548'], ['f_143', 'cpi_9606.ENSP00000367123', 'cpi_9606.ENSP00000410076', 'cpi_9606.ENSP00000216037', 'f_587'], ['f_340', 'cpi_9606.ENSP00000306606', 'cpi_9606.ENSP00000246553', 'cpi_9606.ENSP00000360493', 'f_460'], ['f_33', 'f_706', 'cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000275216'], ['f_528', 'cpi_9606.ENSP00000306100', 'cpi_9606.ENSP00000263126', 'cpi_9606.ENSP00000231228', 'cpi_9606.ENSP00000342235'], ['f_681', 'f_815', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000359285', 'f_427'], ['f_569', 'cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000451040'], ['cpi_9606.ENSP00000311032', 'f_327', 'f_164', 'cpi_9606.ENSP00000299847', 'f_454'], ['f_516', 'cpi_9606.ENSP00000309477', 'cpi_9606.ENSP00000372023', 'cpi_9606.ENSP00000352011', 'f_46'], ['f_335', 'cpi_9606.ENSP00000333994', 'f_750', 'f_466', 'f_298'], ['f_535', 'cpi_9606.ENSP00000471397', 'f_330', 'f_752', 'cpi_9606.ENSP00000378517'], ['f_611', 'cpi_9606.ENSP00000237014', 'cpi_9606.ENSP00000326119', 'f_43', 'cpi_9606.ENSP00000348069'], ['f_553', 'cpi_9606.ENSP00000362353', 'cpi_9606.ENSP00000332369', 'f_670', 'cpi_9606.ENSP00000366662'], ['f_443', 'cpi_9606.ENSP00000337746', 'f_675', 'cpi_9606.ENSP00000339527', 'cpi_9606.ENSP00000353362'], ['f_579', 'cpi_9606.ENSP00000346103', 'cpi_9606.ENSP00000301634', 'cpi_9606.ENSP00000267101', 'cpi_9606.ENSP00000262352'], ['f_645', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000356436'], ['f_21', 'cpi_9606.ENSP00000372750', 'f_116', 'cpi_9606.ENSP00000321988', 'f_467'], ['f_638', 'cpi_9606.ENSP00000353679', 'f_242', 'f_791', 'cpi_9606.ENSP00000344352'], ['f_10', 'cpi_9606.ENSP00000226299', 'cpi_9606.ENSP00000296677', 'cpi_9606.ENSP00000387946', 'f_583'], ['f_684', 'cpi_9606.ENSP00000358727', 'cpi_9606.ENSP00000262948', 'f_474', 'f_496'], ['cpi_9606.ENSP00000303211', 'f_537', 'f_488', 'f_715', 'cpi_9606.ENSP00000334198'], ['f_24', 'cpi_9606.ENSP00000319984', 'f_407', 'f_827', 'cpi_9606.ENSP00000285930'], ['f_181', 'cpi_9606.ENSP00000448059', 'cpi_9606.ENSP00000253004', 'cpi_9606.ENSP00000368253', 'f_166'], ['f_613', 'cpi_9606.ENSP00000314214', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000312664', 'cpi_9606.ENSP00000252809'], ['f_689', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000312673', 'cpi_9606.ENSP00000286301', 'f_728'], ['f_646', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000282753', 'cpi_9606.ENSP00000341885', 'cpi_9606.ENSP00000270776'], ['f_692', 'cpi_9606.ENSP00000226578', 'f_473', 'cpi_9606.ENSP00000354394', 'f_729'], ['f_341', 'cpi_9606.ENSP00000295454', 'cpi_9606.ENSP00000273398', 'cpi_9606.ENSP00000357283', 'f_778'], ['f_567', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000276449', 'cpi_9606.ENSP00000400175', 'f_813'], ['f_573', 'cpi_9606.ENSP00000261733', 'f_388', 'cpi_9606.ENSP00000296871', 'f_792'], ['f_343', 'cpi_9606.ENSP00000295897', 'f_187', 'f_394', 'cpi_9606.ENSP00000274547'], ['f_257', 'cpi_9606.ENSP00000332549', 'f_861', 'cpi_9606.ENSP00000222330', 'cpi_9606.ENSP00000251535'], ['f_667', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000254810'], ['f_16', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000376178', 'f_622'], ['f_11', 'cpi_9606.ENSP00000264613', 'cpi_9606.ENSP00000379086', 'cpi_9606.ENSP00000225474', 'f_436'], ['f_704', 'cpi_9606.ENSP00000248935', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000346017', 'f_508'], ['f_361', 'f_26', 'f_590', 'cpi_9606.ENSP00000338548', 'f_486'], ['f_439', 'cpi_9606.ENSP00000434516', 'cpi_9606.ENSP00000297350', 'f_229', 'f_448'], ['f_18', 'cpi_9606.ENSP00000472933', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000361359', 'f_764'], ['f_241', 'cpi_9606.ENSP00000369654', 'f_132', 'cpi_9606.ENSP00000308165', 'cpi_9606.ENSP00000340925'], ['cpi_9606.ENSP00000265724', 'f_207', 'f_401', 'cpi_9606.ENSP00000362036', 'cpi_9606.ENSP00000299178'], ['f_581', 'cpi_9606.ENSP00000352835', 'f_568', 'f_494', 'cpi_9606.ENSP00000312029'], ['f_690', 'f_609', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000327431', 'f_799'], ['f_671', 'cpi_9606.ENSP00000298171', 'cpi_9606.ENSP00000305302', 'cpi_9606.ENSP00000003100', 'f_505'], ['f_637', 'cpi_9606.ENSP00000332256', 'cpi_9606.ENSP00000356832', 'cpi_9606.ENSP00000301178', 'f_518'], ['f_351', 'cpi_9606.ENSP00000313699', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000463999', 'cpi_9606.ENSP00000353292'], ['f_642', 'f_429', 'cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000338082', 'cpi_9606.ENSP00000466799'], ['f_294', 'f_782', 'cpi_9606.ENSP00000353731', 'f_159', 'cpi_9606.ENSP00000382659'], ['f_709', 'cpi_9606.ENSP00000293404', 'cpi_9606.ENSP00000248553', 'cpi_9606.ENSP00000275525', 'f_409'], ['f_375', 'f_840', 'f_631', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000266376'], ['f_353', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000348827', 'f_826'], ['f_540', 'cpi_9606.ENSP00000011292', 'cpi_9606.ENSP00000270631', 'cpi_9606.ENSP00000294728', 'cpi_9606.ENSP00000261937'], ['f_14', 'cpi_9606.ENSP00000343690', 'cpi_9606.ENSP00000329357', 'f_839', 'cpi_9606.ENSP00000375066'], ['f_345', 'cpi_9606.ENSP00000277508', 'cpi_9606.ENSP00000346148', 'cpi_9606.ENSP00000459962', 'f_551'], ['f_702', 'cpi_9606.ENSP00000314151', 'f_483', 'cpi_9606.ENSP00000304915', 'f_759'], ['f_699', 'f_533', 'cpi_9606.ENSP00000263269', 'f_477', 'cpi_9606.ENSP00000311095'], ['f_180', 'cpi_9606.ENSP00000261267', 'cpi_9606.ENSP00000361666', 'f_22', 'f_216'], ['f_286', 'cpi_9606.ENSP00000343885', 'cpi_9606.ENSP00000353878', 'cpi_9606.ENSP00000222390', 'f_763'], ['f_293', 'cpi_9606.ENSP00000243167', 'cpi_9606.ENSP00000350348', 'cpi_9606.ENSP00000344192', 'f_812'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000380247', 'f_17', 'cpi_9606.ENSP00000295491', 'cpi_9606.ENSP00000410294'], ['f_701', 'f_650', 'cpi_9606.ENSP00000344460', 'cpi_9606.ENSP00000381097', 'cpi_9606.ENSP00000367102'], ['f_248', 'cpi_9606.ENSP00000308024', 'f_455', 'f_167', 'cpi_9606.ENSP00000389414'], ['f_779', 'f_347', 'cpi_9606.ENSP00000234111', 'cpi_9606.ENSP00000366506', 'cpi_9606.ENSP00000346534'], ['f_615', 'cpi_9606.ENSP00000220809', 'cpi_9606.ENSP00000286479', 'f_833', 'cpi_9606.ENSP00000216862'], ['f_462', 'f_423', 'cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000362344', 'cpi_9606.ENSP00000347942'], ['f_342', 'cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000260010', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000267843'], ['f_662', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000303452', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000297316'], ['f_365', 'cpi_9606.ENSP00000366620', 'cpi_9606.ENSP00000293288', 'f_195', 'f_558'], ['f_691', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000231454'], ['f_430', 'cpi_9606.ENSP00000359680', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000376943', 'cpi_9606.ENSP00000261693'], ['f_663', 'cpi_9606.ENSP00000419692', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000242057'], ['f_683', 'cpi_9606.ENSP00000314649', 'cpi_9606.ENSP00000365016', 'cpi_9606.ENSP00000428340', 'f_740'], ['f_602', 'f_770', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000359100', 'cpi_9606.ENSP00000346598'], ['cpi_9606.ENSP00000231509', 'f_34', 'cpi_9606.ENSP00000299267', 'f_398', 'cpi_9606.ENSP00000264657'], ['f_349', 'cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000364212', 'f_522', 'cpi_9606.ENSP00000471569'], ['f_193', 'cpi_9606.ENSP00000284981', 'f_461', 'cpi_9606.ENSP00000307599', 'cpi_9606.ENSP00000283635'], ['f_708', 'cpi_9606.ENSP00000447378', 'cpi_9606.ENSP00000347979', 'f_475', 'f_543'], ['f_560', 'cpi_9606.ENSP00000371432', 'cpi_9606.ENSP00000261196', 'f_230', 'cpi_9606.ENSP00000356954'], ['f_818', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000374265', 'cpi_9606.ENSP00000340691', 'f_644'], ['f_693', 'cpi_9606.ENSP00000270142', 'f_422', 'f_513', 'cpi_9606.ENSP00000263339'], ['f_591', 'cpi_9606.ENSP00000356022', 'f_399', 'cpi_9606.ENSP00000256958', 'f_471'], ['f_688', 'cpi_9606.ENSP00000283646', 'cpi_9606.ENSP00000398632', 'cpi_9606.ENSP00000427514', 'f_129'], ['f_819', 'cpi_9606.ENSP00000368438', 'f_397', 'cpi_9606.ENSP00000384708', 'f_465'], ['f_619', 'cpi_9606.ENSP00000364805', 'cpi_9606.ENSP00000331912', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000252723'], ['f_705', 'cpi_9606.ENSP00000255380', 'f_647', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000371067'], ['f_199', 'cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000298352', 'cpi_9606.ENSP00000282561', 'f_480'], ['f_604', 'cpi_9606.ENSP00000360141', 'cpi_9606.ENSP00000326219', 'f_160', 'f_588'], ['f_13', 'cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000216714', 'cpi_9606.ENSP00000300900', 'f_822'], ['f_418', 'cpi_9606.ENSP00000255465', 'cpi_9606.ENSP00000295256', 'cpi_9606.ENSP00000355930', 'f_115'], ['f_682', 'cpi_9606.ENSP00000236850', 'cpi_9606.ENSP00000274026', 'f_305', 'cpi_9606.ENSP00000294954'], ['f_680', 'cpi_9606.ENSP00000376914', 'cpi_9606.ENSP00000302111', 'f_738', 'f_514'], ['f_464', 'cpi_9606.ENSP00000387683', 'cpi_9606.ENSP00000382250', 'cpi_9606.ENSP00000428824', 'cpi_9606.ENSP00000320935'], ['f_432', 'cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000233242', 'f_517', 'f_500'], ['f_368', 'f_801', 'cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000330393', 'cpi_9606.ENSP00000336630'], ['f_797', 'cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000301974', 'cpi_9606.ENSP00000388648', 'f_395'], ['f_734', 'cpi_9606.ENSP00000363822', 'cpi_9606.ENSP00000268251', 'f_359', 'cpi_9606.ENSP00000345502'], ['f_628', 'cpi_9606.ENSP00000327801', 'cpi_9606.ENSP00000379213', 'cpi_9606.ENSP00000359663', 'f_367'], ['f_1', 'cpi_9606.ENSP00000380318', 'cpi_9606.ENSP00000387888', 'f_653', 'f_559'], ['f_502', 'cpi_9606.ENSP00000260649', 'cpi_9606.ENSP00000373477', 'f_803', 'f_860'], ['f_777', 'cpi_9606.ENSP00000387123', 'f_421', 'cpi_9606.ENSP00000278616', 'cpi_9606.ENSP00000283254'], ['f_38', 'cpi_9606.ENSP00000387662', 'cpi_9606.ENSP00000265403', 'f_605', 'cpi_9606.ENSP00000344674'], ['f_550', 'cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000260356', 'f_527', 'f_30'], ['f_549', 'cpi_9606.ENSP00000330484', 'cpi_9606.ENSP00000407375', 'f_227', 'f_625'], ['f_437', 'cpi_9606.ENSP00000293190', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000291294', 'f_411'], ['f_352', 'cpi_9606.ENSP00000348395', 'cpi_9606.ENSP00000310405', 'cpi_9606.ENSP00000252486', 'f_742'], ['f_594', 'cpi_9606.ENSP00000340943', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000359635', 'f_336'], ['f_776', 'cpi_9606.ENSP00000308541', 'f_489', 'cpi_9606.ENSP00000335592', 'f_717'], ['f_334', 'cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000296350', 'f_687', 'f_213'], ['f_337', 'cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000001008', 'cpi_9606.ENSP00000259089', 'f_458'], ['f_441', 'cpi_9606.ENSP00000300289', 'cpi_9606.ENSP00000239938', 'f_805', 'f_314'], ['f_700', 'cpi_9606.ENSP00000356825', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000329623', 'f_300'], ['f_655', 'cpi_9606.ENSP00000318868', 'cpi_9606.ENSP00000370473', 'cpi_9606.ENSP00000348897', 'f_456'], ['f_259', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000320401', 'cpi_9606.ENSP00000331746', 'f_363'], ['f_536', 'cpi_9606.ENSP00000276571', 'cpi_9606.ENSP00000352516', 'f_784', 'cpi_9606.ENSP00000366307'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000323568', 'f_157', 'cpi_9606.ENSP00000357981'], ['f_716', 'cpi_9606.ENSP00000297494', 'cpi_9606.ENSP00000311028', 'cpi_9606.ENSP00000254488', 'f_425'], ['f_755', 'cpi_9606.ENSP00000261465', 'cpi_9606.ENSP00000320866', 'f_652', 'cpi_9606.ENSP00000293745'], ['f_597', 'cpi_9606.ENSP00000265171', 'cpi_9606.ENSP00000253122', 'f_144', 'cpi_9606.ENSP00000351885'], ['f_333', 'cpi_9606.ENSP00000358042', 'cpi_9606.ENSP00000231188', 'cpi_9606.ENSP00000267163', 'f_200'], ['f_377', 'cpi_9606.ENSP00000319814', 'cpi_9606.ENSP00000297268', 'cpi_9606.ENSP00000277120', 'f_610'], ['f_284', 'cpi_9606.ENSP00000234590', 'cpi_9606.ENSP00000221515', 'f_721', 'cpi_9606.ENSP00000259396'], ['f_798', 'cpi_9606.ENSP00000262407', 'f_485', 'cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000314099'], ['f_548', 'cpi_9606.ENSP00000310219', 'cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000385806', 'cpi_9606.ENSP00000289753'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000328173', 'f_612', 'cpi_9606.ENSP00000200676', 'f_694'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000019103', 'cpi_9606.ENSP00000384957', 'f_737', 'cpi_9606.ENSP00000318822'], ['f_344', 'cpi_9606.ENSP00000265421', 'cpi_9606.ENSP00000274793', 'cpi_9606.ENSP00000353915', 'f_206'], ['f_249', 'f_515', 'cpi_9606.ENSP00000315644', 'cpi_9606.ENSP00000378492', 'f_658'], ['f_780', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000467494', 'f_575'], ['f_623', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000321999', 'cpi_9606.ENSP00000368752', 'cpi_9606.ENSP00000320025'], ['f_145', 'cpi_9606.ENSP00000319170', 'cpi_9606.ENSP00000356694', 'cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000345659'], ['f_633', 'cpi_9606.ENSP00000236671', 'cpi_9606.ENSP00000318646', 'cpi_9606.ENSP00000324248', 'cpi_9606.ENSP00000303540'], ['f_641', 'cpi_9606.ENSP00000249750', 'cpi_9606.ENSP00000263980', 'cpi_9606.ENSP00000467676', 'f_301'], ['f_370', 'cpi_9606.ENSP00000405573', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000349003', 'f_661'], ['f_188', 'cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000246337', 'f_152', 'f_756'], ['f_498', 'cpi_9606.ENSP00000244217', 'cpi_9606.ENSP00000362513', 'cpi_9606.ENSP00000322924', 'f_364'], ['f_412', 'cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000303424', 'cpi_9606.ENSP00000251566'], ['f_592', 'cpi_9606.ENSP00000347549', 'cpi_9606.ENSP00000304501', 'cpi_9606.ENSP00000358784', 'cpi_9606.ENSP00000310928'], ['f_710', 'cpi_9606.ENSP00000305692', 'cpi_9606.ENSP00000435777', 'cpi_9606.ENSP00000239849', 'f_378'], ['f_666', 'cpi_9606.ENSP00000280357', 'cpi_9606.ENSP00000259486', 'cpi_9606.ENSP00000307766', 'cpi_9606.ENSP00000351273'], ['f_178', 'cpi_9606.ENSP00000264705', 'cpi_9606.ENSP00000354558', 'cpi_9606.ENSP00000292513', 'f_260'], ['f_487', 'cpi_9606.ENSP00000331602', 'cpi_9606.ENSP00000262461', 'f_711', 'cpi_9606.ENSP00000332812'], ['f_244', 'cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000355778', 'cpi_9606.ENSP00000225964', 'f_503'], ['f_586', 'cpi_9606.ENSP00000003084', 'cpi_9606.ENSP00000369757', 'f_761', 'cpi_9606.ENSP00000290349'], ['f_0', 'cpi_9606.ENSP00000311873', 'cpi_9606.ENSP00000231449', 'cpi_9606.ENSP00000360973', 'f_630'], ['f_758', 'cpi_9606.ENSP00000220764', 'cpi_9606.ENSP00000411658', 'cpi_9606.ENSP00000402152', 'f_563'], ['f_599', 'cpi_9606.ENSP00000276651', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000308549', 'cpi_9606.ENSP00000304895'], ['f_507', 'cpi_9606.ENSP00000382342', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000251453', 'cpi_9606.ENSP00000217305'], ['f_580', 'cpi_9606.ENSP00000309845', 'cpi_9606.ENSP00000308032',

🔄 Processing features: 100%|██████████| 2147/2147 [10:24<00:00,  3.44feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'f_408', 'f_845', 'cpi_9606.ENSP00000367123', 'f_31'], ['f_308', 'f_616', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000263377', 'cpi_9606.ENSP00000351957'], ['f_20', 'cpi_9606.ENSP00000254976', 'cpi_9606.ENSP00000333212', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000286479'], ['f_374', 'cpi_9606.ENSP00000039007', 'cpi_9606.ENSP00000395653', 'f_25', 'f_27'], ['f_23', 'f_413', 'cpi_9606.ENSP00000216465', 'f_118', 'f_631'], ['f_3', 'cpi_9606.ENSP00000222256', 'f_466', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000337335'], ['f_299', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000363812', 'f_151', 'cpi_9606.ENSP00000380318'], ['f_406', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000355192', 'f_629', 'cpi_9606.ENSP00000351209'], ['f_672', 'cpi_9606.ENSP00000264162', 'cpi_9606.ENSP00000262441', 'f_292', 'cpi_9606.ENSP00000367851'], ['f_285', 'cpi_9606.ENSP00000244217', 'f_866', 'cpi_9606.ENSP00000358595', 'f_587'], ['f_380', 'cpi_9606.ENSP00000263088', 'cpi_9606.ENSP00000342235', 'f_789', 'cpi_9606.ENSP00000356094'], ['f_366', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000374265', 'cpi_9606.ENSP00000279178', 'f_768'], ['f_19', 'cpi_9606.ENSP00000376914', 'f_510', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000354476'], ['f_452', 'cpi_9606.ENSP00000259486', 'f_726', 'cpi_9606.ENSP00000257290', 'f_635'], ['f_440', 'cpi_9606.ENSP00000285381', 'f_728', 'cpi_9606.ENSP00000233146', 'cpi_9606.ENSP00000372547'], ['f_393', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000229447', 'f_194', 'cpi_9606.ENSP00000360493'], ['f_37', 'cpi_9606.ENSP00000263321', 'f_509', 'f_35', 'f_229'], ['f_346', 'cpi_9606.ENSP00000402608', 'cpi_9606.ENSP00000430684', 'f_831', 'f_428'], ['f_185', 'cpi_9606.ENSP00000354850', 'cpi_9606.ENSP00000414334', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000359424'], ['f_617', 'cpi_9606.ENSP00000394033', 'cpi_9606.ENSP00000374323', 'cpi_9606.ENSP00000367848', 'f_836'], ['f_287', 'cpi_9606.ENSP00000303211', 'f_195', 'f_166', 'f_47'], ['f_340', 'cpi_9606.ENSP00000368305', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000319788', 'cpi_9606.ENSP00000355629'], ['f_15', 'cpi_9606.ENSP00000357204', 'cpi_9606.ENSP00000229264', 'f_861', 'cpi_9606.ENSP00000216037'], ['f_571', 'cpi_9606.ENSP00000295598', 'f_815', 'cpi_9606.ENSP00000277010', 'f_749'], ['f_33', 'cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000390600', 'f_350', 'cpi_9606.ENSP00000435591'], ['f_392', 'cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000332296', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000331912'], ['f_391', 'cpi_9606.ENSP00000219794', 'f_725', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000312455'], ['f_192', 'cpi_9606.ENSP00000352835', 'cpi_9606.ENSP00000265294', 'f_511', 'f_46'], ['f_451', 'cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000245539', 'f_417', 'f_328'], ['f_12', 'cpi_9606.ENSP00000261205', 'f_529', 'cpi_9606.ENSP00000262367', 'f_788'], ['f_390', 'cpi_9606.ENSP00000364035', 'cpi_9606.ENSP00000264637', 'cpi_9606.ENSP00000304822', 'cpi_9606.ENSP00000352011'], ['f_186', 'cpi_9606.ENSP00000274353', 'cpi_9606.ENSP00000355657', 'f_131', 'f_202'], ['f_339', 'f_675', 'cpi_9606.ENSP00000319170', 'f_771', 'f_799'], ['f_405', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000221972', 'f_526'], ['f_420', 'cpi_9606.ENSP00000354193', 'f_830', 'f_297', 'f_773'], ['cpi_9606.ENSP00000264381', 'f_24', 'f_706', 'f_554', 'f_207'], ['f_535', 'cpi_9606.ENSP00000262888', 'cpi_9606.ENSP00000344674', 'cpi_9606.ENSP00000471569', 'cpi_9606.ENSP00000232219'], ['f_643', 'cpi_9606.ENSP00000405573', 'cpi_9606.ENSP00000447173', 'f_214', 'f_622'], ['f_639', 'f_757', 'cpi_9606.ENSP00000373477', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000359353'], ['f_614', 'cpi_9606.ENSP00000371236', 'cpi_9606.ENSP00000316786', 'f_791', 'cpi_9606.ENSP00000343040'], ['f_697', 'cpi_9606.ENSP00000397582', 'f_767', 'cpi_9606.ENSP00000360773', 'cpi_9606.ENSP00000417229'], ['f_181', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000448059', 'cpi_9606.ENSP00000367102', 'cpi_9606.ENSP00000296370'], ['f_712', 'cpi_9606.ENSP00000217426', 'f_834', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000222330'], ['f_143', 'cpi_9606.ENSP00000354610', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000470087'], ['f_443', 'cpi_9606.ENSP00000383365', 'cpi_9606.ENSP00000381097', 'cpi_9606.ENSP00000282561', 'cpi_9606.ENSP00000394936'], ['f_146', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000356150', 'f_427', 'cpi_9606.ENSP00000283254'], ['f_686', 'f_215', 'f_419', 'f_670', 'cpi_9606.ENSP00000342070'], ['cpi_9606.ENSP00000311032', 'f_43', 'f_167', 'f_551', 'cpi_9606.ENSP00000003100'], ['f_656', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000352584', 'cpi_9606.ENSP00000309493'], ['f_21', 'cpi_9606.ENSP00000319984', 'f_752', 'f_116', 'f_327'], ['f_569', 'cpi_9606.ENSP00000237014', 'f_460', 'cpi_9606.ENSP00000343477', 'cpi_9606.ENSP00000258749'], ['f_516', 'cpi_9606.ENSP00000341885', 'cpi_9606.ENSP00000225927', 'cpi_9606.ENSP00000350767', 'f_583'], ['f_528', 'cpi_9606.ENSP00000319814', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000274547', 'cpi_9606.ENSP00000358548'], ['f_566', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000297268', 'cpi_9606.ENSP00000353878', 'f_833'], ['f_2', 'cpi_9606.ENSP00000222481', 'cpi_9606.ENSP00000270631', 'cpi_9606.ENSP00000389338', 'cpi_9606.ENSP00000386306'], ['f_638', 'cpi_9606.ENSP00000314214', 'cpi_9606.ENSP00000297350', 'cpi_9606.ENSP00000387946', 'cpi_9606.ENSP00000301891'], ['f_1', 'cpi_9606.ENSP00000226299', 'cpi_9606.ENSP00000296677', 'f_764', 'cpi_9606.ENSP00000326119'], ['f_681', 'f_568', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000365686'], ['f_338', 'cpi_9606.ENSP00000387536', 'cpi_9606.ENSP00000254227', 'f_401', 'f_330'], ['f_11', 'cpi_9606.ENSP00000226578', 'cpi_9606.ENSP00000457706', 'cpi_9606.ENSP00000451040', 'f_436'], ['f_286', 'cpi_9606.ENSP00000343885', 'cpi_9606.ENSP00000226574', 'cpi_9606.ENSP00000286301', 'f_736'], ['f_696', 'cpi_9606.ENSP00000319531', 'f_474', 'f_298', 'cpi_9606.ENSP00000309572'], ['f_659', 'cpi_9606.ENSP00000364731', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000312664', 'cpi_9606.ENSP00000261937'], ['f_10', 'cpi_9606.ENSP00000271620', 'cpi_9606.ENSP00000309124', 'cpi_9606.ENSP00000354394', 'cpi_9606.ENSP00000353362'], ['cpi_9606.ENSP00000336528', 'f_26', 'cpi_9606.ENSP00000380247', 'f_497', 'cpi_9606.ENSP00000310447'], ['f_257', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000346103', 'cpi_9606.ENSP00000299847'], ['f_692', 'cpi_9606.ENSP00000288022', 'cpi_9606.ENSP00000302811', 'f_508', 'cpi_9606.ENSP00000305422'], ['f_462', 'f_488', 'cpi_9606.ENSP00000328968', 'f_715', 'cpi_9606.ENSP00000220616'], ['f_611', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000361666'], ['f_248', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000282753', 'cpi_9606.ENSP00000242057', 'f_477'], ['f_341', 'cpi_9606.ENSP00000295454', 'cpi_9606.ENSP00000273398', 'f_778', 'cpi_9606.ENSP00000225474'], ['f_613', 'cpi_9606.ENSP00000314649', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000356832', 'f_827'], ['f_693', 'cpi_9606.ENSP00000270142', 'f_422', 'f_407', 'cpi_9606.ENSP00000378517'], ['f_335', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000386029', 'f_719'], ['f_579', 'cpi_9606.ENSP00000408526', 'f_388', 'cpi_9606.ENSP00000346534', 'f_792'], ['f_667', 'cpi_9606.ENSP00000220764', 'cpi_9606.ENSP00000410732', 'f_676', 'f_448'], ['f_0', 'cpi_9606.ENSP00000339399', 'cpi_9606.ENSP00000300061', 'cpi_9606.ENSP00000216862', 'f_505'], ['f_698', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000219700', 'f_729', 'f_820'], ['f_682', 'f_839', 'f_132', 'cpi_9606.ENSP00000222553', 'cpi_9606.ENSP00000334198'], ['f_684', 'cpi_9606.ENSP00000358727', 'cpi_9606.ENSP00000365016', 'f_473', 'cpi_9606.ENSP00000376943'], ['cpi_9606.ENSP00000231509', 'f_34', 'f_826', 'f_770', 'f_518'], ['f_637', 'cpi_9606.ENSP00000317159', 'cpi_9606.ENSP00000361359', 'cpi_9606.ENSP00000275525', 'cpi_9606.ENSP00000296871'], ['f_776', 'cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000347942'], ['f_704', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000164139', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000339527'], ['f_332', 'cpi_9606.ENSP00000337746', 'cpi_9606.ENSP00000310405', 'cpi_9606.ENSP00000293288', 'f_763'], ['f_567', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000348069', 'f_262'], ['f_343', 'f_593', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000323568', 'cpi_9606.ENSP00000263126'], ['f_180', 'cpi_9606.ENSP00000353224', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000318822', 'f_455'], ['f_16', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000367309', 'f_361', 'cpi_9606.ENSP00000353427'], ['f_294', 'f_782', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000387123', 'f_159'], ['f_690', 'cpi_9606.ENSP00000318820', 'f_750', 'cpi_9606.ENSP00000332369', 'f_429'], ['f_663', 'cpi_9606.ENSP00000369816', 'f_813', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000428924'], ['f_353', 'cpi_9606.ENSP00000355536', 'cpi_9606.ENSP00000344192', 'cpi_9606.ENSP00000259396', 'f_722'], ['f_671', 'cpi_9606.ENSP00000362353', 'cpi_9606.ENSP00000356729', 'cpi_9606.ENSP00000365663', 'f_496'], ['f_553', 'cpi_9606.ENSP00000340943', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000427514', 'f_336'], ['f_293', 'cpi_9606.ENSP00000243167', 'f_812', 'cpi_9606.ENSP00000278616', 'cpi_9606.ENSP00000301178'], ['f_710', 'cpi_9606.ENSP00000305692', 'cpi_9606.ENSP00000255465', 'cpi_9606.ENSP00000344352', 'cpi_9606.ENSP00000263339'], ['f_560', 'f_840', 'cpi_9606.ENSP00000364709', 'cpi_9606.ENSP00000296350', 'f_803'], ['f_646', 'cpi_9606.ENSP00000321988', 'cpi_9606.ENSP00000301974', 'cpi_9606.ENSP00000346598', 'cpi_9606.ENSP00000260356'], ['f_540', 'cpi_9606.ENSP00000296046', 'cpi_9606.ENSP00000272847', 'cpi_9606.ENSP00000307599', 'cpi_9606.ENSP00000356954'], ['f_345', 'cpi_9606.ENSP00000295834', 'cpi_9606.ENSP00000406157', 'cpi_9606.ENSP00000252723', 'f_409'], ['f_537', 'f_423', 'cpi_9606.ENSP00000264668', 'cpi_9606.ENSP00000371929', 'f_486'], ['f_709', 'cpi_9606.ENSP00000309477', 'cpi_9606.ENSP00000402152', 'f_785', 'cpi_9606.ENSP00000308165'], ['f_342', 'cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000234071', 'f_164', 'cpi_9606.ENSP00000285930'], ['f_14', 'cpi_9606.ENSP00000244051', 'cpi_9606.ENSP00000294728', 'cpi_9606.ENSP00000261799', 'f_543'], ['f_38', 'cpi_9606.ENSP00000222381', 'f_559', 'cpi_9606.ENSP00000263980', 'cpi_9606.ENSP00000295491'], ['f_581', 'cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000308774', 'f_494'], ['f_642', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000280357', 'f_609', 'cpi_9606.ENSP00000266376'], ['f_249', 'cpi_9606.ENSP00000409378', 'f_300', 'cpi_9606.ENSP00000264896', 'cpi_9606.ENSP00000362649'], ['f_334', 'cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000376776', 'f_625', 'f_359'], ['f_365', 'cpi_9606.ENSP00000265174', 'cpi_9606.ENSP00000311095', 'f_740', 'f_558'], ['f_689', 'cpi_9606.ENSP00000318868', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000262352', 'f_394'], ['f_439', 'cpi_9606.ENSP00000382791', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000267101', 'cpi_9606.ENSP00000329357'], ['f_18', 'cpi_9606.ENSP00000472933', 'cpi_9606.ENSP00000274793', 'cpi_9606.ENSP00000252809', 'f_522'], ['f_645', 'cpi_9606.ENSP00000276571', 'cpi_9606.ENSP00000011292', 'f_471', 'f_742'], ['f_691', 'cpi_9606.ENSP00000268053', 'cpi_9606.ENSP00000231454', 'cpi_9606.ENSP00000227758', 'f_483'], ['f_798', 'f_485', 'cpi_9606.ENSP00000338548', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000428340'], ['cpi_9606.ENSP00000265724', 'f_694', 'f_129', 'cpi_9606.ENSP00000359793', 'cpi_9606.ENSP00000345659'], ['f_701', 'cpi_9606.ENSP00000344460', 'f_650', 'cpi_9606.ENSP00000376178', 'f_533'], ['f_711', 'f_22', 'f_513', 'cpi_9606.ENSP00000350616', 'f_644'], ['f_573', 'cpi_9606.ENSP00000364801', 'cpi_9606.ENSP00000320935', 'f_398', 'cpi_9606.ENSP00000359285'], ['f_777', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000357981', 'f_397', 'cpi_9606.ENSP00000353292'], ['f_368', 'cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000275216', 'cpi_9606.ENSP00000283635', 'f_363'], ['cpi_9606.ENSP00000342007', 'f_347', 'cpi_9606.ENSP00000299178', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000216540'], ['cpi_9606.ENSP00000241052', 'f_213', 'f_465', 'cpi_9606.ENSP00000312029', 'cpi_9606.ENSP00000320025'], ['f_619', 'cpi_9606.ENSP00000264613', 'f_30', 'cpi_9606.ENSP00000261693', 'f_216'], ['f_351', 'cpi_9606.ENSP00000421566', 'cpi_9606.ENSP00000261196', 'f_461', 'f_230'], ['f_662', 'cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000338072', 'f_457'], ['f_688', 'cpi_9606.ENSP00000248935', 'cpi_9606.ENSP00000267119', 'f_475', 'f_653'], ['f_615', 'cpi_9606.ENSP00000315644', 'f_860', 'f_454', 'f_738'], ['f_683', 'cpi_9606.ENSP00000306606', 'cpi_9606.ENSP00000328173', 'f_242', 'f_367'], ['f_337', 'cpi_9606.ENSP00000284981', 'f_305', 'f_759', 'f_17'], ['f_241', 'cpi_9606.ENSP00000332549', 'cpi_9606.ENSP00000251535', 'f_489', 'cpi_9606.ENSP00000382659'], ['f_199', 'cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000330393', 'f_480', 'cpi_9606.ENSP00000336630'], ['f_145', 'cpi_9606.ENSP00000229319', 'f_575', 'cpi_9606.ENSP00000252486', 'cpi_9606.ENSP00000416293'], ['f_193', 'cpi_9606.ENSP00000296545', 'cpi_9606.ENSP00000307014', 'cpi_9606.ENSP00000327431', 'f_421'], ['f_680', 'cpi_9606.ENSP00000306100', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000260010', 'f_717'], ['f_594', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000445340', 'cpi_9606.ENSP00000359635', 'f_588'], ['cpi_9606.ENSP00000295897', 'f_779', 'f_314', 'f_822', 'cpi_9606.ENSP00000248553'], ['f_702', 'cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000357283', 'f_780', 'cpi_9606.ENSP00000303540'], ['f_641', 'cpi_9606.ENSP00000362036', 'cpi_9606.ENSP00000353472', 'cpi_9606.ENSP00000347979', 'f_647'], ['f_352', 'cpi_9606.ENSP00000348395', 'cpi_9606.ENSP00000361668', 'cpi_9606.ENSP00000221421', 'f_721'], ['f_797', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000343204', 'f_395', 'cpi_9606.ENSP00000370381'], ['f_550', 'cpi_9606.ENSP00000356022', 'f_160', 'cpi_9606.ENSP00000256958', 'f_227'], ['f_349', 'cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000320866', 'cpi_9606.ENSP00000326219', 'f_737'], ['f_430', 'cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000231228', 'f_411', 'f_805'], ['f_259', 'cpi_9606.ENSP00000279230', 'cpi_9606.ENSP00000263464', 'f_115', 'cpi_9606.ENSP00000299267'], ['f_591', 'cpi_9606.ENSP00000274026', 'cpi_9606.ENSP00000309818', 'cpi_9606.ENSP00000275300', 'f_610'], ['f_344', 'cpi_9606.ENSP00000362329', 'cpi_9606.ENSP00000222390', 'f_514', 'f_801'], ['f_655', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000399168', 'cpi_9606.ENSP00000239849', 'f_301'], ['f_708', 'cpi_9606.ENSP00000260649', 'cpi_9606.ENSP00000378890', 'cpi_9606.ENSP00000267163', 'f_456'], ['f_818', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000301645', 'f_458'], ['f_592', 'cpi_9606.ENSP00000276651', 'cpi_9606.ENSP00000366307', 'cpi_9606.ENSP00000354558', 'f_425'], ['f_699', 'cpi_9606.ENSP00000420927', 'f_467', 'cpi_9606.ENSP00000306490', 'f_687'], ['f_705', 'cpi_9606.ENSP00000255380', 'f_517', 'cpi_9606.ENSP00000386284', 'f_527'], ['f_734', 'cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000259089', 'cpi_9606.ENSP00000310928'], ['f_375', 'cpi_9606.ENSP00000353679', 'cpi_9606.ENSP00000262948', 'f_144', 'cpi_9606.ENSP00000200676'], ['f_819', 'cpi_9606.ENSP00000279593', 'cpi_9606.ENSP00000389414', 'f_157', 'cpi_9606.ENSP00000365380'], ['f_441', 'cpi_9606.ENSP00000359680', 'cpi_9606.ENSP00000276449', 'cpi_9606.ENSP00000359663', 'f_652'], ['f_498', 'cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000370254', 'f_500'], ['f_654', 'cpi_9606.ENSP00000382250', 'cpi_9606.ENSP00000387683', 'f_605', 'cpi_9606.ENSP00000292513'], ['f_628', 'cpi_9606.ENSP00000216714', 'cpi_9606.ENSP00000370473', 'cpi_9606.ENSP00000428864', 'f_700'], ['f_333', 'cpi_9606.ENSP00000293404', 'cpi_9606.ENSP00000391826', 'f_784', 'f_200'], ['f_432', 'cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000253004', 'f_621', 'cpi_9606.ENSP00000341045'], ['f_536', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000327652', 'f_601'], ['f_150', 'cpi_9606.ENSP00000368438', 'cpi_9606.ENSP00000355930', 'f_630', 'f_459'], ['f_464', 'cpi_9606.ENSP00000429374', 'cpi_9606.ENSP00000236671', 'cpi_9606.ENSP00000355523', 'f_713'], ['f_602', 'cpi_9606.ENSP00000419692', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000317379', 'f_544'], ['cpi_9606.ENSP00000272190', 'f_364', 'f_206', 'cpi_9606.ENSP00000265403', 'cpi_9606.ENSP00000256383'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000315011', 'cpi_9606.ENSP00000410294', 'f_716', 'cpi_9606.ENSP00000300900'], ['f_434', 'cpi_9606.ENSP00000330032', 'cpi_9606.ENSP00000233242', 'f_563', 'cpi_9606.ENSP00000355920'], ['f_493', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000293190', 'f_250', 'cpi_9606.ENSP00000296122'], ['f_586', 'cpi_9606.ENSP00000268035', 'cpi_9606.ENSP00000396320', 'f_707', 'cpi_9606.ENSP00000303522'], ['f_574', 'cpi_9606.ENSP00000434516', 'cpi_9606.ENSP00000221515', 'cpi_9606.ENSP00000302846', 'f_378'], ['f_636', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000359100', 'cpi_9606.ENSP00000335511', 'f_824'], ['f_377', 'cpi_9606.ENSP00000261465', 'cpi_9606.ENSP00000260227', 'f_661', 'cpi_9606.ENSP00000314099'], ['f_370', 'cpi_9606.ENSP00000330484', 'cpi_9606.ENSP00000364802', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000308549'], ['cpi_9606.ENSP00000325120', 'f_188', 'cpi_9606.ENSP00000369647', 'cpi_9606.ENSP00000270776', 'f_152'], ['f_418', 'cpi_9606.ENSP00000295256', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000309757'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000218388', 'cpi_9606.ENSP00000307235', 'f_695', 'cpi_9606.ENSP00000362513'], ['f_549', 'cpi_9606.ENSP00000196551', 'cpi_9606.ENSP00000251566', 'cpi_9606.ENSP00000388825', 'cpi_9606.ENSP00000302111'], ['f_564', 'cpi_9606.ENSP00000251453', 'cpi_9606.ENSP00000246553', 'cpi_9606.ENSP00000219919', 'cpi_9606.ENSP00000267843'], ['f_755', 'cpi_9606.ENSP00000298171', 'cpi_9606.ENSP00000398632', 'cpi_9606.ENSP00000358784', 'cpi_9606.ENSP00000463999'], ['f_502', 'cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000327850', 'cpi_9606.ENSP00000262461', 'f_761'], ['f_666', 'cpi_9606.ENSP00000360141', 'cpi_9606.ENSP00000338627', 'cpi_9606.ENSP00000369530', 'f_260'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000311165', 'f_386', 'cpi_9606.ENSP00000291700', 'f_532'], ['f_714', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000298283', 'f_515', 'cpi_9606.ENSP00000293330'], ['f_453', 'cpi_9606.ENSP00000277508', 'cpi_9606.ENSP00000278175', 'f_756', 'cpi_9606.ENSP00000225964'], ['f_261', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000285979', 'cpi_9606.ENSP00000467676'], ['f_487', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000314949', 'cpi_9606.ENSP00000304915', 'f_251'], ['f_412', 'cpi_9606.ENSP00000220809', 'cpi_9606.ENSP00000356694', 'cpi_9606.ENSP00000311469', 'f_624'], ['f_255', 'cpi_9606.ENSP00000270625', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000329623'], ['f_520', 'cpi_9606.ENSP00000435777', 'cpi_9606.ENSP00000386171', 'cpi_9606.ENSP00000321106', 'cpi_9606.ENSP00000372023'], ['f_632', 'cpi_9606.ENSP00000352516', 'cpi_9606.ENSP00000360973', 'cpi_9606.ENSP00000261835', 'f_658'], ['cpi_9606.ENSP00000330237', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000369038', 'f_13', 'f_414'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000292896', 'cpi_9606.ENSP00000370912', 'f_612', 'f_590'], ['cpi_9606.ENSP00000363822', 'f_187', 'cpi_9606.ENSP00000369654', 'cpi_9606.ENSP00000331358', 'f_153'], ['f_580', 'cpi_9606.ENSP00000309845', 'cpi_9606.ENSP00000308032', 

🔄 Processing features: 100%|██████████| 2147/2147 [10:24<00:00,  3.44feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'f_413', 'f_151', 'f_262', 'f_845'], ['f_308', 'cpi_9606.ENSP00000380318', 'f_616', 'cpi_9606.ENSP00000394936', 'cpi_9606.ENSP00000417229'], ['f_20', 'cpi_9606.ENSP00000254976', 'cpi_9606.ENSP00000343204', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000286479'], ['f_23', 'cpi_9606.ENSP00000385026', 'f_408', 'cpi_9606.ENSP00000274353', 'cpi_9606.ENSP00000356094'], ['f_3', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000285930', 'f_789', 'cpi_9606.ENSP00000337335'], ['f_374', 'cpi_9606.ENSP00000222481', 'cpi_9606.ENSP00000253004', 'f_768', 'cpi_9606.ENSP00000359424'], ['f_452', 'f_25', 'cpi_9606.ENSP00000259486', 'f_726', 'cpi_9606.ENSP00000342235'], ['f_440', 'cpi_9606.ENSP00000354850', 'cpi_9606.ENSP00000378517', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000347942'], ['f_37', 'cpi_9606.ENSP00000263321', 'f_43', 'cpi_9606.ENSP00000357255', 'f_35'], ['f_390', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000351908', 'f_27'], ['f_346', 'cpi_9606.ENSP00000395653', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000337773', 'f_629'], ['f_451', 'cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000298472', 'f_31', 'cpi_9606.ENSP00000341885'], ['f_380', 'cpi_9606.ENSP00000264818', 'cpi_9606.ENSP00000277508', 'cpi_9606.ENSP00000262888', 'f_831'], ['f_406', 'cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000344352', 'f_836'], ['f_672', 'cpi_9606.ENSP00000270142', 'f_292', 'cpi_9606.ENSP00000295452', 'f_830'], ['f_571', 'cpi_9606.ENSP00000443194', 'f_799', 'f_529', 'cpi_9606.ENSP00000365686'], ['f_366', 'cpi_9606.ENSP00000319531', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000220616', 'f_428'], ['f_287', 'cpi_9606.ENSP00000241052', 'f_118', 'f_622', 'f_47'], ['f_392', 'cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000363812', 'f_510', 'cpi_9606.ENSP00000277010'], ['f_614', 'cpi_9606.ENSP00000332369', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000279178', 'cpi_9606.ENSP00000459962'], ['f_299', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000357336', 'cpi_9606.ENSP00000354476'], ['f_391', 'cpi_9606.ENSP00000357204', 'f_866', 'cpi_9606.ENSP00000429374', 'f_635'], ['f_143', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000349577', 'f_328'], ['f_285', 'cpi_9606.ENSP00000377527', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000430684'], ['f_393', 'cpi_9606.ENSP00000306100', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000355629', 'cpi_9606.ENSP00000245206'], ['f_12', 'cpi_9606.ENSP00000261205', 'cpi_9606.ENSP00000445340', 'cpi_9606.ENSP00000301634', 'f_526'], ['f_405', 'cpi_9606.ENSP00000386284', 'cpi_9606.ENSP00000359353', 'cpi_9606.ENSP00000221972', 'cpi_9606.ENSP00000352011'], ['f_639', 'cpi_9606.ENSP00000237014', 'f_417', 'f_767', 'f_166'], ['f_617', 'cpi_9606.ENSP00000405573', 'cpi_9606.ENSP00000374323', 'cpi_9606.ENSP00000367848', 'f_773'], ['f_339', 'f_675', 'cpi_9606.ENSP00000291295', 'f_834', 'cpi_9606.ENSP00000351957'], ['f_185', 'cpi_9606.ENSP00000364035', 'cpi_9606.ENSP00000246553', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000304822'], ['f_192', 'cpi_9606.ENSP00000229319', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000274793', 'f_511'], ['f_146', 'cpi_9606.ENSP00000319170', 'cpi_9606.ENSP00000236671', 'cpi_9606.ENSP00000222330', 'f_587'], ['f_420', 'cpi_9606.ENSP00000397582', 'cpi_9606.ENSP00000360493', 'f_297', 'cpi_9606.ENSP00000355317'], ['f_569', 'f_214', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000297258', 'cpi_9606.ENSP00000260649'], ['f_643', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000283646', 'f_202'], ['f_15', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000264637', 'cpi_9606.ENSP00000234389', 'cpi_9606.ENSP00000262187'], ['f_686', 'f_343', 'f_215', 'f_419', 'cpi_9606.ENSP00000353720'], ['f_19', 'cpi_9606.ENSP00000368305', 'cpi_9606.ENSP00000428924', 'cpi_9606.ENSP00000470087', 'cpi_9606.ENSP00000252809'], ['f_33', 'f_706', 'f_298', 'cpi_9606.ENSP00000352835', 'cpi_9606.ENSP00000435591'], ['f_659', 'cpi_9606.ENSP00000364731', 'cpi_9606.ENSP00000332296', 'cpi_9606.ENSP00000361359', 'cpi_9606.ENSP00000257290'], ['f_186', 'cpi_9606.ENSP00000344460', 'cpi_9606.ENSP00000282753', 'cpi_9606.ENSP00000283635', 'cpi_9606.ENSP00000226574'], ['cpi_9606.ENSP00000311032', 'f_670', 'f_207', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000259271'], ['f_535', 'cpi_9606.ENSP00000305480', 'f_327', 'cpi_9606.ENSP00000382659', 'cpi_9606.ENSP00000365016'], ['f_528', 'cpi_9606.ENSP00000216465', 'cpi_9606.ENSP00000308774', 'cpi_9606.ENSP00000309124', 'cpi_9606.ENSP00000301891'], ['f_656', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000386171', 'cpi_9606.ENSP00000355657', 'cpi_9606.ENSP00000296871'], ['f_2', 'cpi_9606.ENSP00000219794', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000312455', 'f_771'], ['f_693', 'f_752', 'cpi_9606.ENSP00000284981', 'f_330', 'f_788'], ['f_345', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000430031', 'cpi_9606.ENSP00000319788', 'cpi_9606.ENSP00000343040'], ['f_338', 'cpi_9606.ENSP00000292896', 'cpi_9606.ENSP00000360773', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000370912'], ['f_638', 'cpi_9606.ENSP00000225275', 'f_242', 'f_791', 'cpi_9606.ENSP00000357283'], ['f_516', 'cpi_9606.ENSP00000447378', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000387946', 'f_350'], ['f_443', 'cpi_9606.ENSP00000223366', 'cpi_9606.ENSP00000327850', 'f_554', 'f_497'], ['f_696', 'cpi_9606.ENSP00000293404', 'cpi_9606.ENSP00000216392', 'cpi_9606.ENSP00000296122', 'cpi_9606.ENSP00000457706'], ['f_712', 'f_725', 'cpi_9606.ENSP00000222553', 'f_474', 'cpi_9606.ENSP00000398632'], ['f_341', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000273398', 'cpi_9606.ENSP00000414334', 'cpi_9606.ENSP00000286301'], ['f_181', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000355192', 'f_132'], ['f_681', 'f_429', 'f_427', 'cpi_9606.ENSP00000410732', 'f_131'], ['f_340', 'cpi_9606.ENSP00000308024', 'cpi_9606.ENSP00000232219', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000225474'], ['f_540', 'cpi_9606.ENSP00000306606', 'cpi_9606.ENSP00000362924', 'cpi_9606.ENSP00000451040', 'cpi_9606.ENSP00000326119'], ['f_566', 'cpi_9606.ENSP00000377192', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000316786', 'cpi_9606.ENSP00000261937'], ['f_248', 'cpi_9606.ENSP00000333994', 'cpi_9606.ENSP00000307014', 'cpi_9606.ENSP00000389338', 'f_30'], ['f_698', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000350785', 'cpi_9606.ENSP00000307235'], ['f_257', 'cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000339527', 'f_436'], ['f_16', 'cpi_9606.ENSP00000419692', 'cpi_9606.ENSP00000352035', 'cpi_9606.ENSP00000317379', 'f_785'], ['f_611', 'cpi_9606.ENSP00000368880', 'cpi_9606.ENSP00000338548', 'cpi_9606.ENSP00000319814', 'f_460'], ['f_18', 'cpi_9606.ENSP00000472933', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000333212', 'f_509'], ['f_567', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000398655', 'f_736'], ['f_24', 'cpi_9606.ENSP00000319984', 'f_407', 'cpi_9606.ENSP00000222381', 'f_827'], ['f_579', 'cpi_9606.ENSP00000346103', 'cpi_9606.ENSP00000326219', 'cpi_9606.ENSP00000216341', 'f_729'], ['f_667', 'cpi_9606.ENSP00000390600', 'f_715', 'cpi_9606.ENSP00000371554', 'cpi_9606.ENSP00000295454'], ['f_332', 'cpi_9606.ENSP00000383365', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000329357', 'cpi_9606.ENSP00000259089'], ['f_645', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000293190', 'f_229', 'f_815'], ['f_690', 'cpi_9606.ENSP00000318820', 'f_813', 'f_778', 'cpi_9606.ENSP00000335592'], ['f_613', 'cpi_9606.ENSP00000417901', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000227758', 'f_583'], ['f_688', 'cpi_9606.ENSP00000039007', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000354394', 'f_448'], ['f_615', 'f_839', 'cpi_9606.ENSP00000315644', 'f_792', 'cpi_9606.ENSP00000296350'], ['f_637', 'cpi_9606.ENSP00000332256', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000216037'], ['f_430', 'cpi_9606.ENSP00000226578', 'cpi_9606.ENSP00000254810', 'cpi_9606.ENSP00000312029', 'f_194'], ['f_549', 'cpi_9606.ENSP00000295491', 'cpi_9606.ENSP00000251566', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000323568'], ['f_573', 'cpi_9606.ENSP00000371236', 'cpi_9606.ENSP00000388648', 'cpi_9606.ENSP00000231228', 'f_820'], ['cpi_9606.ENSP00000336528', 'f_26', 'f_115', 'cpi_9606.ENSP00000299178', 'f_518'], ['f_351', 'cpi_9606.ENSP00000376914', 'cpi_9606.ENSP00000263339', 'f_764', 'cpi_9606.ENSP00000376943'], ['f_553', 'cpi_9606.ENSP00000362353', 'cpi_9606.ENSP00000367851', 'cpi_9606.ENSP00000366927', 'f_425'], ['f_365', 'cpi_9606.ENSP00000264162', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000365380', 'cpi_9606.ENSP00000294728'], ['f_689', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000466399', 'cpi_9606.ENSP00000463999', 'f_466'], ['f_697', 'cpi_9606.ENSP00000314214', 'cpi_9606.ENSP00000402152', 'f_749', 'cpi_9606.ENSP00000260010'], ['f_335', 'cpi_9606.ENSP00000369654', 'f_750', 'cpi_9606.ENSP00000178638', 'f_719'], ['f_594', 'cpi_9606.ENSP00000340943', 'cpi_9606.ENSP00000318912', 'cpi_9606.ENSP00000164139', 'f_46'], ['f_699', 'f_488', 'cpi_9606.ENSP00000364709', 'cpi_9606.ENSP00000355778', 'f_486'], ['f_642', 'f_676', 'cpi_9606.ENSP00000264668', 'f_757', 'cpi_9606.ENSP00000369375'], ['f_671', 'cpi_9606.ENSP00000298171', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000375809', 'f_456'], ['f_537', 'cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000338072', 'f_164', 'f_558'], ['f_779', 'cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000358548', 'f_728', 'cpi_9606.ENSP00000346534'], ['f_663', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000387536', 'f_216', 'cpi_9606.ENSP00000261799'], ['f_11', 'cpi_9606.ENSP00000011292', 'cpi_9606.ENSP00000379086', 'cpi_9606.ENSP00000343477', 'cpi_9606.ENSP00000275525'], ['f_293', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000350348', 'cpi_9606.ENSP00000344192', 'cpi_9606.ENSP00000301645'], ['f_249', 'f_305', 'f_401', 'cpi_9606.ENSP00000356729', 'cpi_9606.ENSP00000309818'], ['f_10', 'cpi_9606.ENSP00000226299', 'cpi_9606.ENSP00000296677', 'f_505', 'cpi_9606.ENSP00000278616'], ['f_462', 'f_423', 'cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000321988', 'f_167'], ['f_662', 'cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000274547', 'cpi_9606.ENSP00000262367', 'f_508'], ['f_294', 'f_782', 'cpi_9606.ENSP00000262441', 'cpi_9606.ENSP00000353224', 'cpi_9606.ENSP00000292095'], ['f_342', 'cpi_9606.ENSP00000355536', 'cpi_9606.ENSP00000320935', 'cpi_9606.ENSP00000252029', 'f_475'], ['f_684', 'cpi_9606.ENSP00000445175', 'cpi_9606.ENSP00000261835', 'f_473', 'cpi_9606.ENSP00000394932'], ['f_692', 'cpi_9606.ENSP00000320866', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000471569', 'cpi_9606.ENSP00000252723'], ['f_333', 'cpi_9606.ENSP00000276651', 'cpi_9606.ENSP00000410815', 'cpi_9606.ENSP00000216962', 'cpi_9606.ENSP00000262999'], ['f_353', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000338082', 'f_826', 'f_361'], ['f_683', 'cpi_9606.ENSP00000314649', 'cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000366307', 'f_861'], ['f_704', 'cpi_9606.ENSP00000225964', 'cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000328973', 'f_722'], ['f_819', 'f_609', 'cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000260102', 'f_650'], ['f_691', 'cpi_9606.ENSP00000268053', 'cpi_9606.ENSP00000353878', 'cpi_9606.ENSP00000231454', 'f_483'], ['cpi_9606.ENSP00000264381', 'f_458', 'f_770', 'f_116', 'cpi_9606.ENSP00000261693'], ['f_818', 'f_533', 'cpi_9606.ENSP00000262407', 'cpi_9606.ENSP00000307599', 'f_496'], ['f_14', 'cpi_9606.ENSP00000244051', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000296545', 'f_551'], ['cpi_9606.ENSP00000265724', 'f_455', 'cpi_9606.ENSP00000359793', 'f_200', 'f_471'], ['f_682', 'cpi_9606.ENSP00000236850', 'cpi_9606.ENSP00000255465', 'cpi_9606.ENSP00000294954', 'f_129'], ['f_628', 'cpi_9606.ENSP00000293813', 'cpi_9606.ENSP00000261196', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000308165'], ['f_241', 'cpi_9606.ENSP00000327431', 'cpi_9606.ENSP00000356954', 'cpi_9606.ENSP00000258749', 'cpi_9606.ENSP00000297316'], ['f_193', 'cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000448059', 'f_388', 'f_480'], ['f_680', 'cpi_9606.ENSP00000379500', 'cpi_9606.ENSP00000295834', 'f_568', 'cpi_9606.ENSP00000293288'], ['f_641', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000246337', 'cpi_9606.ENSP00000222390', 'f_833'], ['f_199', 'cpi_9606.ENSP00000231751', 'f_394', 'cpi_9606.ENSP00000275300', 'f_409'], ['f_368', 'cpi_9606.ENSP00000381607', 'cpi_9606.ENSP00000356213', 'f_647', 'f_543'], ['f_702', 'cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000353362', 'f_398'], ['f_34', 'cpi_9606.ENSP00000231509', 'f_763', 'cpi_9606.ENSP00000301178', 'cpi_9606.ENSP00000318868'], ['f_21', 'cpi_9606.ENSP00000306490', 'f_467', 'cpi_9606.ENSP00000265403', 'cpi_9606.ENSP00000330393'], ['f_776', 'cpi_9606.ENSP00000220764', 'cpi_9606.ENSP00000331912', 'f_742', 'f_513'], ['f_1', 'cpi_9606.ENSP00000229447', 'cpi_9606.ENSP00000356150', 'cpi_9606.ENSP00000353292', 'cpi_9606.ENSP00000282561'], ['f_593', 'f_631', 'cpi_9606.ENSP00000295598', 'cpi_9606.ENSP00000325120', 'f_461'], ['f_798', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000364212', 'cpi_9606.ENSP00000266376', 'f_489'], ['f_180', 'cpi_9606.ENSP00000261267', 'cpi_9606.ENSP00000291294', 'f_22', 'f_454'], ['f_619', 'cpi_9606.ENSP00000399168', 'cpi_9606.ENSP00000346015', 'f_314', 'f_477'], ['f_375', 'f_840', 'cpi_9606.ENSP00000263269', 'cpi_9606.ENSP00000312664', 'f_812'], ['f_464', 'cpi_9606.ENSP00000318646', 'cpi_9606.ENSP00000352584', 'cpi_9606.ENSP00000309493', 'f_230'], ['f_777', 'f_494', 'cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000348069', 'cpi_9606.ENSP00000356671'], ['f_602', 'cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000372326', 'cpi_9606.ENSP00000283254', 'f_522'], ['f_507', 'cpi_9606.ENSP00000220809', 'cpi_9606.ENSP00000309477', 'f_803', 'f_517'], ['f_432', 'f_411', 'cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000317842', 'cpi_9606.ENSP00000410294'], ['f_337', 'cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000345659', 'f_644', 'cpi_9606.ENSP00000221515'], ['f_581', 'cpi_9606.ENSP00000354511', 'f_422', 'f_500', 'cpi_9606.ENSP00000427514'], ['f_797', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000262948', 'cpi_9606.ENSP00000259396'], ['f_498', 'cpi_9606.ENSP00000357066', 'cpi_9606.ENSP00000320171', 'cpi_9606.ENSP00000300061', 'f_195'], ['f_286', 'cpi_9606.ENSP00000272227', 'cpi_9606.ENSP00000340925', 'cpi_9606.ENSP00000304895', 'cpi_9606.ENSP00000361666'], ['f_0', 'cpi_9606.ENSP00000324105', 'cpi_9606.ENSP00000391676', 'cpi_9606.ENSP00000367102', 'f_653'], ['f_701', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000394033', 'f_359', 'cpi_9606.ENSP00000242057'], ['f_555', 'cpi_9606.ENSP00000378699', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000339260', 'f_336'], ['f_536', 'cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000298352', 'cpi_9606.ENSP00000216862', 'f_363'], ['f_666', 'cpi_9606.ENSP00000019103', 'cpi_9606.ENSP00000371432', 'cpi_9606.ENSP00000251535', 'cpi_9606.ENSP00000011653'], ['f_591', 'cpi_9606.ENSP00000356022', 'f_527', 'cpi_9606.ENSP00000256958', 'f_514'], ['f_284', 'cpi_9606.ENSP00000348395', 'cpi_9606.ENSP00000309103', 'cpi_9606.ENSP00000295619', 'f_740'], ['f_695', 'cpi_9606.ENSP00000356825', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000359334'], ['f_709', 'cpi_9606.ENSP00000373674', 'cpi_9606.ENSP00000295731', 'cpi_9606.ENSP00000267163', 'f_738'], ['f_259', 'cpi_9606.ENSP00000261733', 'cpi_9606.ENSP00000303325', 'f_605', 'cpi_9606.ENSP00000299267'], ['f_711', 'cpi_9606.ENSP00000396308', 'f_625', 'cpi_9606.ENSP00000277120', 'cpi_9606.ENSP00000311095'], ['f_38', 'cpi_9606.ENSP00000302150', 'f_227', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000219919'], ['f_450', 'cpi_9606.ENSP00000260356', 'cpi_9606.ENSP00000256383', 'cpi_9606.ENSP00000225927', 'f_588'], ['f_705', 'cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000302961', 'f_465'], ['f_550', 'cpi_9606.ENSP00000353731', 'f_159', 'cpi_9606.ENSP00000331358', 'cpi_9606.ENSP00000305221'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000304915', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000364805', 'cpi_9606.ENSP00000359100'], ['f_213', 'f_687', 'f_559', 'cpi_9606.ENSP00000296271', 'cpi_9606.ENSP00000358784'], ['f_707', 'f_860', 'cpi_9606.ENSP00000417281', 'cpi_9606.ENSP00000256078', 'f_717'], ['f_370', 'cpi_9606.ENSP00000251453', 'cpi_9606.ENSP00000353472', 'cpi_9606.ENSP00000347979', 'cpi_9606.ENSP00000310928'], ['f_710', 'cpi_9606.ENSP00000349576', 'cpi_9606.ENSP00000310305', 'f_347', 'f_721'], ['f_418', 'cpi_9606.ENSP00000249750', 'cpi_9606.ENSP00000278175', 'cpi_9606.ENSP00000260191', 'f_575'], ['f_145', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000389414', 'f_801'], ['f_453', 'cpi_9606.ENSP00000332549', 'cpi_9606.ENSP00000228872', 'f_630', 'f_144'], ['f_592', 'cpi_9606.ENSP00000317159', 'cpi_9606.ENSP00000264657', 'f_160', 'f_822'], ['f_604', 'cpi_9606.ENSP00000360141', 'f_694', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000233242'], ['f_349', 'cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000302846', 'cpi_9606.ENSP00000386029'], ['f_439', 'cpi_9606.ENSP00000311469', 'cpi_9606.ENSP00000298386', 'f_759', 'cpi_9606.ENSP00000287766'], ['f_150', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000433821', 'cpi_9606.ENSP00000454071', 'f_250'], ['f_334', 'cpi_9606.ENSP00000367309', 'cpi_9606.ENSP00000376178', 'f_17', 'f_805'], ['f_548', 'cpi_9606.ENSP00000359635', 'cpi_9606.ENSP00000219700', 'f_421', 'cpi_9606.ENSP00000355930'], ['f_708', 'cpi_9606.ENSP00000354610', 'cpi_9606.ENSP00000286091', 'cpi_9606.ENSP00000287936', 'f_395'], ['f_646', 'cpi_9606.ENSP00000276571', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000252486'], ['f_13', 'cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000263923'], ['f_700', 'cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000467494', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000282397'], ['f_283', 'cpi_9606.ENSP00000264932', 'cpi_9606.ENSP00000270631', 'cpi_9606.ENSP00000307240', 'f_784'], ['f_412', 'cpi_9606.ENSP00000380252', 'cpi_9606.ENSP00000375093', 'cpi_9606.ENSP00000387683', 'f_515'], ['f_655', 'cpi_9606.ENSP00000346067', 'cpi_9606.ENSP00000420487', 'cpi_9606.ENSP00000370473', 'f_397'], ['f_352', 'cpi_9606.ENSP00000367615', 'cpi_9606.ENSP00000267119', 'cpi_9606.ENSP00000414303', 'f_457'], ['f_563', 'cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000344674', 'f_414'], ['f_590', 'f_612', 'cpi_9606.ENSP00000272298', 'cpi_9606.ENSP00000276449', 'cpi_9606.ENSP00000303540'], ['f_541', 'cpi_9606.ENSP00000255084', 'cpi_9606.ENSP00000286648', 'f_780', 'cpi_9606.ENSP00000273430'], ['f_446', 'cpi_9606.ENSP00000359680', 'cpi_9606.ENSP00000262160', 'cpi_9606.ENSP00000302111', 'cpi_9606.ENSP00000336630'], ['f_502', 'cpi_9606.ENSP00000279593', 'cpi_9606.ENSP00000309757', 'f_610', 'cpi_9606.ENSP00000369530'], ['cpi_9606.ENSP00000360372', 'cpi_9606.ENSP00000321326', 'f_601', 'cpi_9606.ENSP00000200676', 'cpi_9606.ENSP00000311028'], ['f_437', 'cpi_9606.ENSP00000346598', 'cpi_9606.ENSP00000362513', 'cpi_9606.ENSP00000388825', 'cpi_9606.ENSP00000244741'], ['f_755', 'cpi_9606.ENSP00000383558', 'cpi_9606.ENSP00000345774', 'f_652', 'cpi_9606.ENSP00000263126'], ['f_356', 'cpi_9606.ENSP00000435777', 'cpi_9606.ENSP00000256442', 'cpi_9606.ENSP00000393333', 'f_301'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000263980', 'cpi_9606.ENSP00000381097', 'cpi_9606.ENSP00000365233', 'f_459'], ['f_381', 'cpi_9606.ENSP00000406157', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000393312', 'f_658'], ['f_597', 'cpi_9606.ENSP00000379213', 'cpi_9606.ENSP00000306561', 'cpi_9606.ENSP00000248553', 'f_157'], ['f_607', 'cpi_9606.ENSP00000216714', 'cpi_9606.ENSP00000234310', 'cpi_9606.ENSP000

🔄 Processing features: 100%|██████████| 2147/2147 [10:23<00:00,  3.44feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'f_46', 'f_413', 'f_151', 'f_262'], ['f_20', 'cpi_9606.ENSP00000254976', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000333212', 'cpi_9606.ENSP00000286301'], ['f_308', 'cpi_9606.ENSP00000288139', 'f_616', 'cpi_9606.ENSP00000394936', 'cpi_9606.ENSP00000376432'], ['f_672', 'cpi_9606.ENSP00000216465', 'f_292', 'f_845', 'f_767'], ['f_23', 'cpi_9606.ENSP00000319984', 'f_408', 'cpi_9606.ENSP00000357204', 'f_164'], ['f_287', 'cpi_9606.ENSP00000241052', 'f_194', 'f_118', 'cpi_9606.ENSP00000356094'], ['f_3', 'f_815', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000390600', 'f_789'], ['f_393', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000367851', 'cpi_9606.ENSP00000355629'], ['f_374', 'cpi_9606.ENSP00000264705', 'f_831', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000409007'], ['f_299', 'cpi_9606.ENSP00000264162', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000277010', 'f_31'], ['f_392', 'cpi_9606.ENSP00000368305', 'cpi_9606.ENSP00000264637', 'f_510', 'cpi_9606.ENSP00000354476'], ['f_346', 'cpi_9606.ENSP00000395653', 'cpi_9606.ENSP00000357068', 'f_629', 'cpi_9606.ENSP00000279178'], ['f_452', 'f_25', 'cpi_9606.ENSP00000263088', 'f_726', 'cpi_9606.ENSP00000342235'], ['f_380', 'cpi_9606.ENSP00000259486', 'cpi_9606.ENSP00000360773', 'f_768', 'f_785'], ['f_406', 'cpi_9606.ENSP00000352035', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000374323', 'f_820'], ['f_614', 'cpi_9606.ENSP00000344460', 'cpi_9606.ENSP00000295452', 'f_749', 'cpi_9606.ENSP00000316786'], ['f_37', 'f_670', 'cpi_9606.ENSP00000357255', 'f_202', 'cpi_9606.ENSP00000274353'], ['f_15', 'cpi_9606.ENSP00000358727', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000252809', 'f_214'], ['f_285', 'cpi_9606.ENSP00000229447', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000430684'], ['f_451', 'cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000361206', 'f_428', 'f_328'], ['f_440', 'cpi_9606.ENSP00000262888', 'cpi_9606.ENSP00000233146', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000178638'], ['f_571', 'cpi_9606.ENSP00000327431', 'f_736', 'f_529', 'cpi_9606.ENSP00000324856'], ['f_19', 'cpi_9606.ENSP00000312326', 'cpi_9606.ENSP00000304822', 'cpi_9606.ENSP00000367848', 'f_836'], ['f_617', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000265294'], ['f_643', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000380318', 'f_622'], ['f_192', 'cpi_9606.ENSP00000354850', 'f_47', 'cpi_9606.ENSP00000359353', 'f_131'], ['f_566', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000200676', 'f_715'], ['f_391', 'cpi_9606.ENSP00000364035', 'f_866', 'f_788', 'f_719'], ['f_638', 'f_839', 'cpi_9606.ENSP00000261755', 'f_511', 'f_526'], ['f_33', 'f_350', 'f_706', 'cpi_9606.ENSP00000352835', 'cpi_9606.ENSP00000435591'], ['f_143', 'cpi_9606.ENSP00000261205', 'cpi_9606.ENSP00000340691', 'f_773', 'f_327'], ['f_516', 'cpi_9606.ENSP00000397582', 'cpi_9606.ENSP00000343477', 'f_27', 'cpi_9606.ENSP00000451040'], ['f_686', 'f_215', 'f_419', 'f_509', 'f_298'], ['f_340', 'cpi_9606.ENSP00000373477', 'cpi_9606.ENSP00000332296', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000353362'], ['f_696', 'cpi_9606.ENSP00000319531', 'cpi_9606.ENSP00000414334', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000221972'], ['f_639', 'f_427', 'cpi_9606.ENSP00000292896', 'f_830', 'cpi_9606.ENSP00000365686'], ['f_339', 'f_675', 'cpi_9606.ENSP00000219794', 'f_834', 'f_799'], ['f_146', 'cpi_9606.ENSP00000249750', 'f_297', 'cpi_9606.ENSP00000349320', 'f_587'], ['f_24', 'cpi_9606.ENSP00000372750', 'f_407', 'cpi_9606.ENSP00000443194', 'f_554'], ['f_366', 'cpi_9606.ENSP00000273398', 'cpi_9606.ENSP00000263126', 'f_635', 'cpi_9606.ENSP00000216037'], ['f_185', 'cpi_9606.ENSP00000314214', 'cpi_9606.ENSP00000355657', 'cpi_9606.ENSP00000386306', 'f_436'], ['f_535', 'cpi_9606.ENSP00000306100', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000365016', 'f_497'], ['f_656', 'cpi_9606.ENSP00000341885', 'cpi_9606.ENSP00000386171', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000258749'], ['f_186', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000231228', 'f_26'], ['f_2', 'cpi_9606.ENSP00000330032', 'cpi_9606.ENSP00000319788', 'cpi_9606.ENSP00000358595', 'f_725'], ['f_12', 'cpi_9606.ENSP00000314649', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000298472'], ['cpi_9606.ENSP00000311032', 'f_43', 'f_207', 'f_394', 'f_722'], ['f_181', 'cpi_9606.ENSP00000338082', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000431512', 'f_132'], ['f_611', 'cpi_9606.ENSP00000237014', 'cpi_9606.ENSP00000309124', 'f_631', 'f_460'], ['f_405', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000356150', 'cpi_9606.ENSP00000309493', 'f_792'], ['f_338', 'cpi_9606.ENSP00000298352', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000254227', 'f_728'], ['f_390', 'cpi_9606.ENSP00000308897', 'cpi_9606.ENSP00000387946', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000312455'], ['f_528', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000274547'], ['f_420', 'cpi_9606.ENSP00000226578', 'f_330', 'f_752', 'cpi_9606.ENSP00000360493'], ['f_553', 'cpi_9606.ENSP00000362353', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000363827', 'f_229'], ['f_659', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000318822', 'cpi_9606.ENSP00000257290'], ['f_257', 'cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000263339', 'f_361', 'cpi_9606.ENSP00000354394'], ['f_443', 'cpi_9606.ENSP00000383365', 'cpi_9606.ENSP00000381097', 'cpi_9606.ENSP00000282561', 'cpi_9606.ENSP00000470087'], ['f_613', 'cpi_9606.ENSP00000405573', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000295491', 'cpi_9606.ENSP00000361359'], ['f_712', 'f_35', 'cpi_9606.ENSP00000353224', 'cpi_9606.ENSP00000295454', 'f_771'], ['f_693', 'cpi_9606.ENSP00000255380', 'f_647', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000410732'], ['f_335', 'cpi_9606.ENSP00000369654', 'cpi_9606.ENSP00000321988', 'f_750', 'f_466'], ['cpi_9606.ENSP00000264381', 'f_458', 'f_770', 'f_782', 'f_166'], ['f_689', 'cpi_9606.ENSP00000309477', 'cpi_9606.ENSP00000471569', 'f_388', 'cpi_9606.ENSP00000296370'], ['f_615', 'cpi_9606.ENSP00000318820', 'f_417', 'cpi_9606.ENSP00000252723', 'cpi_9606.ENSP00000369038'], ['f_681', 'f_429', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000291295', 'f_757'], ['cpi_9606.ENSP00000265724', 'f_455', 'f_505', 'f_486', 'f_167'], ['f_540', 'cpi_9606.ENSP00000471397', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000305422', 'f_583'], ['f_567', 'cpi_9606.ENSP00000319814', 'cpi_9606.ENSP00000301891', 'cpi_9606.ENSP00000264318', 'f_813'], ['f_569', 'cpi_9606.ENSP00000338548', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000311095', 'cpi_9606.ENSP00000389338'], ['f_341', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000343204', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000283254'], ['f_697', 'cpi_9606.ENSP00000387123', 'cpi_9606.ENSP00000410294', 'cpi_9606.ENSP00000417229', 'cpi_9606.ENSP00000225474'], ['f_462', 'cpi_9606.ENSP00000303211', 'f_488', 'f_778', 'cpi_9606.ENSP00000264867'], ['f_579', 'cpi_9606.ENSP00000430031', 'cpi_9606.ENSP00000365380', 'cpi_9606.ENSP00000457706', 'f_729'], ['f_353', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000244217', 'cpi_9606.ENSP00000344192', 'f_812'], ['f_701', 'f_568', 'cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000220616'], ['f_248', 'cpi_9606.ENSP00000262407', 'f_401', 'cpi_9606.ENSP00000222330', 'f_518'], ['f_537', 'f_423', 'cpi_9606.ENSP00000342070', 'f_496', 'f_764'], ['f_1', 'cpi_9606.ENSP00000363018', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000326119', 'cpi_9606.ENSP00000262999'], ['f_698', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000331912', 'cpi_9606.ENSP00000428924', 'cpi_9606.ENSP00000428340'], ['f_10', 'cpi_9606.ENSP00000302441', 'cpi_9606.ENSP00000329357', 'cpi_9606.ENSP00000261937', 'f_409'], ['f_21', 'cpi_9606.ENSP00000306490', 'f_116', 'cpi_9606.ENSP00000268053', 'f_467'], ['f_692', 'cpi_9606.ENSP00000382250', 'cpi_9606.ENSP00000386029', 'f_474', 'cpi_9606.ENSP00000263321'], ['f_345', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000466799', 'cpi_9606.ENSP00000339527', 'cpi_9606.ENSP00000296350'], ['cpi_9606.ENSP00000295897', 'f_343', 'f_187', 'f_763', 'cpi_9606.ENSP00000378517'], ['f_439', 'cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000358784', 'cpi_9606.ENSP00000294728', 'f_230'], ['f_671', 'cpi_9606.ENSP00000262441', 'cpi_9606.ENSP00000356729', 'cpi_9606.ENSP00000275525', 'cpi_9606.ENSP00000352011'], ['f_432', 'cpi_9606.ENSP00000350616', 'f_508', 'cpi_9606.ENSP00000262367', 'cpi_9606.ENSP00000369375'], ['f_704', 'cpi_9606.ENSP00000362036', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000389414', 'f_791'], ['f_645', 'cpi_9606.ENSP00000217961', 'cpi_9606.ENSP00000297350', 'cpi_9606.ENSP00000267101', 'f_448'], ['f_193', 'cpi_9606.ENSP00000284981', 'f_533', 'f_477', 'cpi_9606.ENSP00000283635'], ['cpi_9606.ENSP00000336528', 'f_34', 'cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000251535', 'cpi_9606.ENSP00000261799'], ['f_684', 'cpi_9606.ENSP00000223366', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000232219', 'f_676'], ['f_365', 'cpi_9606.ENSP00000380514', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000312664', 'f_827'], ['f_368', 'cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000265403', 'cpi_9606.ENSP00000346534'], ['f_776', 'cpi_9606.ENSP00000265643', 'cpi_9606.ENSP00000292095', 'f_473', 'cpi_9606.ENSP00000463999'], ['f_333', 'cpi_9606.ENSP00000417901', 'cpi_9606.ENSP00000427514', 'cpi_9606.ENSP00000337335', 'f_833'], ['f_294', 'cpi_9606.ENSP00000338018', 'cpi_9606.ENSP00000218099', 'f_159', 'cpi_9606.ENSP00000245539'], ['f_180', 'cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000225927', 'f_551', 'cpi_9606.ENSP00000308165'], ['f_332', 'cpi_9606.ENSP00000226299', 'cpi_9606.ENSP00000310405', 'cpi_9606.ENSP00000376943', 'f_461'], ['f_667', 'cpi_9606.ENSP00000333994', 'cpi_9606.ENSP00000347942', 'f_650', 'f_559'], ['f_11', 'cpi_9606.ENSP00000323867', 'cpi_9606.ENSP00000263980', 'cpi_9606.ENSP00000261693', 'f_195'], ['f_646', 'cpi_9606.ENSP00000282753', 'cpi_9606.ENSP00000306606', 'cpi_9606.ENSP00000300061', 'f_653'], ['f_642', 'cpi_9606.ENSP00000396308', 'f_471', 'cpi_9606.ENSP00000221421', 'f_30'], ['f_293', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000364212', 'cpi_9606.ENSP00000366307', 'f_740'], ['f_637', 'cpi_9606.ENSP00000332256', 'cpi_9606.ENSP00000344352', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000348069'], ['f_641', 'cpi_9606.ENSP00000386284', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000231454', 'cpi_9606.ENSP00000301178'], ['f_708', 'cpi_9606.ENSP00000354610', 'cpi_9606.ENSP00000297268', 'cpi_9606.ENSP00000353292', 'cpi_9606.ENSP00000343040'], ['f_687', 'f_213', 'cpi_9606.ENSP00000270142', 'cpi_9606.ENSP00000367102', 'f_742'], ['f_663', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000419692', 'cpi_9606.ENSP00000320866', 'f_483'], ['f_464', 'cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000312029', 'cpi_9606.ENSP00000242057', 'f_347'], ['f_13', 'cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000307599', 'cpi_9606.ENSP00000311028'], ['f_680', 'cpi_9606.ENSP00000366927', 'cpi_9606.ENSP00000262948', 'cpi_9606.ENSP00000335511', 'f_522'], ['f_798', 'cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000299267', 'cpi_9606.ENSP00000254810', 'f_717'], ['f_690', 'f_609', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000276449', 'f_399'], ['f_619', 'cpi_9606.ENSP00000371236', 'cpi_9606.ENSP00000296871', 'f_644', 'f_513'], ['f_284', 'cpi_9606.ENSP00000348395', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000459962', 'f_543'], ['f_573', 'cpi_9606.ENSP00000248935', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000262352', 'f_314'], ['f_430', 'cpi_9606.ENSP00000276651', 'cpi_9606.ENSP00000358548', 'cpi_9606.ENSP00000370473', 'f_558'], ['f_688', 'cpi_9606.ENSP00000291565', 'cpi_9606.ENSP00000246553', 'f_475', 'f_398'], ['f_709', 'cpi_9606.ENSP00000447378', 'cpi_9606.ENSP00000255465', 'cpi_9606.ENSP00000361666', 'f_411'], ['f_199', 'cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000330393', 'f_216', 'f_480'], ['f_777', 'cpi_9606.ENSP00000256119', 'f_494', 'cpi_9606.ENSP00000382659', 'f_129'], ['f_593', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000303522', 'cpi_9606.ENSP00000226574'], ['f_560', 'f_840', 'cpi_9606.ENSP00000353679', 'cpi_9606.ENSP00000293288', 'f_454'], ['f_334', 'f_514', 'cpi_9606.ENSP00000299178', 'cpi_9606.ENSP00000252804', 'cpi_9606.ENSP00000372023'], ['f_691', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000260010', 'cpi_9606.ENSP00000326219', 'cpi_9606.ENSP00000359334'], ['f_342', 'cpi_9606.ENSP00000340943', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000241261', 'f_227'], ['f_711', 'f_22', 'cpi_9606.ENSP00000352516', 'f_759', 'cpi_9606.ENSP00000355930'], ['f_16', 'cpi_9606.ENSP00000332549', 'cpi_9606.ENSP00000274793', 'f_242', 'f_625'], ['cpi_9606.ENSP00000231509', 'f_153', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000266376', 'cpi_9606.ENSP00000341828'], ['f_705', 'cpi_9606.ENSP00000354612', 'f_359', 'cpi_9606.ENSP00000332369', 'cpi_9606.ENSP00000322617'], ['f_550', 'cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000356832', 'f_157', 'f_803'], ['f_594', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000164139', 'cpi_9606.ENSP00000252486', 'f_588'], ['f_628', 'cpi_9606.ENSP00000379339', 'cpi_9606.ENSP00000236671', 'cpi_9606.ENSP00000320025', 'f_861'], ['f_9', 'cpi_9606.ENSP00000343885', 'cpi_9606.ENSP00000222390', 'f_826', 'f_517'], ['f_38', 'cpi_9606.ENSP00000234111', 'cpi_9606.ENSP00000236850', 'f_400', 'f_115'], ['f_375', 'cpi_9606.ENSP00000243167', 'f_860', 'cpi_9606.ENSP00000278616', 'f_738'], ['f_581', 'f_422', 'cpi_9606.ENSP00000264668', 'cpi_9606.ENSP00000385806', 'f_500'], ['f_144', 'f_301', 'cpi_9606.ENSP00000364709', 'f_160', 'cpi_9606.ENSP00000264657'], ['f_699', 'cpi_9606.ENSP00000263269', 'f_499', 'cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000300900'], ['f_437', 'cpi_9606.ENSP00000222553', 'cpi_9606.ENSP00000234071', 'f_249', 'cpi_9606.ENSP00000356954'], ['f_682', 'cpi_9606.ENSP00000261733', 'cpi_9606.ENSP00000304895', 'f_822', 'f_305'], ['f_351', 'cpi_9606.ENSP00000261386', 'cpi_9606.ENSP00000343925', 'f_425', 'f_780'], ['f_337', 'cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000176763', 'f_17'], ['f_604', 'cpi_9606.ENSP00000448059', 'cpi_9606.ENSP00000251453', 'cpi_9606.ENSP00000445340', 'cpi_9606.ENSP00000357283'], ['f_592', 'cpi_9606.ENSP00000222481', 'cpi_9606.ENSP00000303248', 'cpi_9606.ENSP00000267163', 'f_456'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000328173', 'f_367', 'f_716', 'cpi_9606.ENSP00000411593'], ['f_574', 'cpi_9606.ENSP00000219700', 'cpi_9606.ENSP00000359635', 'cpi_9606.ENSP00000233242', 'f_421'], ['f_819', 'cpi_9606.ENSP00000220764', 'cpi_9606.ENSP00000267843', 'f_363', 'cpi_9606.ENSP00000355920'], ['f_591', 'cpi_9606.ENSP00000356022', 'f_527', 'cpi_9606.ENSP00000256958', 'cpi_9606.ENSP00000259396'], ['f_349', 'cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000344674', 'f_336'], ['f_779', 'cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000003100', 'f_200', 'cpi_9606.ENSP00000355778'], ['f_662', 'cpi_9606.ENSP00000309818', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000359100', 'f_489'], ['f_502', 'cpi_9606.ENSP00000367123', 'cpi_9606.ENSP00000251566', 'cpi_9606.ENSP00000359663', 'f_801'], ['f_666', 'cpi_9606.ENSP00000357669', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000323568', 'f_152'], ['f_549', 'cpi_9606.ENSP00000296674', 'cpi_9606.ENSP00000352584', 'cpi_9606.ENSP00000267017', 'cpi_9606.ENSP00000261196'], ['f_241', 'cpi_9606.ENSP00000260102', 'cpi_9606.ENSP00000398632', 'f_395', 'cpi_9606.ENSP00000296122'], ['f_498', 'cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000346598', 'cpi_9606.ENSP00000260356', 'f_397'], ['f_755', 'cpi_9606.ENSP00000383558', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000248553', 'f_364'], ['f_602', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000331746', 'cpi_9606.ENSP00000353427', 'cpi_9606.ENSP00000320935'], ['f_818', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000307235', 'cpi_9606.ENSP00000419782', 'f_621'], ['f_821', 'cpi_9606.ENSP00000378699', 'cpi_9606.ENSP00000261465', 'f_658', 'cpi_9606.ENSP00000216341'], ['f_580', 'cpi_9606.ENSP00000298171', 'cpi_9606.ENSP00000341045', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000371929'], ['f_352', 'cpi_9606.ENSP00000363533', 'cpi_9606.ENSP00000296545', 'f_465', 'f_805'], ['f_633', 'cpi_9606.ENSP00000360141', 'f_605', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000369530'], ['f_18', 'cpi_9606.ENSP00000472933', 'cpi_9606.ENSP00000309103', 'f_260', 'cpi_9606.ENSP00000335657'], ['f_418', 'cpi_9606.ENSP00000382791', 'cpi_9606.ENSP00000380252', 'f_575', 'cpi_9606.ENSP00000309757'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000218388', 'cpi_9606.ENSP00000370381', 'f_694', 'f_612'], ['f_14', 'cpi_9606.ENSP00000253792', 'cpi_9606.ENSP00000454071', 'f_721', 'cpi_9606.ENSP00000325120'], ['f_536', 'cpi_9606.ENSP00000276571', 'cpi_9606.ENSP00000358107', 'f_784', 'cpi_9606.ENSP00000310928'], ['f_145', 'cpi_9606.ENSP00000335620', 'cpi_9606.ENSP00000278175', 'cpi_9606.ENSP00000391826', 'f_250'], ['f_655', 'cpi_9606.ENSP00000313490', 'cpi_9606.ENSP00000239938', 'f_378', 'cpi_9606.ENSP00000252519'], ['f_493', 'cpi_9606.ENSP00000303452', 'cpi_9606.ENSP00000318646', 'cpi_9606.ENSP00000320401', 'cpi_9606.ENSP00000302111'], ['f_623', 'cpi_9606.ENSP00000375093', 'cpi_9606.ENSP00000364805', 'cpi_9606.ENSP00000387683', 'f_661'], ['f_702', 'cpi_9606.ENSP00000368438', 'f_532', 'cpi_9606.ENSP00000353915', 'cpi_9606.ENSP00000321821'], ['f_507', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000368880', 'cpi_9606.ENSP00000262461', 'f_515'], ['f_442', 'cpi_9606.ENSP00000330484', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000414303', 'f_610'], ['f_683', 'cpi_9606.ENSP00000347549', 'cpi_9606.ENSP00000428824', 'cpi_9606.ENSP00000384273', 'f_563'], ['f_710', 'cpi_9606.ENSP00000305692', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000307014', 'f_652'], ['f_0', 'cpi_9606.ENSP00000376914', 'cpi_9606.ENSP00000277120', 'f_713', 'cpi_9606.ENSP00000354558'], ['f_714', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000430432', 'cpi_9606.ENSP00000245457', 'cpi_9606.ENSP00000225964'], ['f_259', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000270776', 'cpi_9606.ENSP00000303325', 'f_700'], ['f_188', 'cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000280357', 'f_300', 'cpi_9606.ENSP00000295834'], ['f_286', 'cpi_9606.ENSP00000343745', 'cpi_9606.ENSP00000287936', 'cpi_9606.ENSP00000367309', 'f_630'], ['f_261', 'cpi_9606.ENSP00000220809', 'cpi_9606.ENSP00000353878', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000380247'], ['f_251', 'cpi_9606.ENSP00000268035', 'cpi_9606.ENSP00000267119', 'cpi_9606.ENSP00000353791', 'cpi_9606.ENSP00000418532'], ['f_597', 'cpi_9606.ENSP00000431719', 'cpi_9606.ENSP00000314508', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000354107'], ['f_797', 'cpi_9606.ENSP00000350348', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000323549', 'f_547'], ['f_487', 'cpi_9606.ENSP00000274026', 'cpi_9606.ENSP00000331602', 'f_761', 'cpi_9606.ENSP00000285979'], ['f_450', 'cpi_9606.ENSP00000264498', 'cpi_9606.ENSP00000351908', 'cpi_9606.ENSP00000365663', 'f_206'], ['f_255', 'cpi_9606.ENSP00000435777', 'cpi_9606.ENSP00000219919', 'cpi_9606.ENSP00000388825', 'cpi_9606.ENSP00000351273'], ['f_542', 'cpi_9606.ENSP00000346063', 'cpi_9606.ENSP00000304915', 'f_457', 'cpi_9606.ENSP00000222381'], ['f_548', 'cpi_9606.ENSP00000345974', 'cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000255030', 'f_414'], ['cpi_9606.ENSP00000330237', 'cpi_9606.ENSP00000295598', 'f_695', 'f_459', 'cpi_9606.ENSP00000307240'], ['f_679', 'cpi_9606.ENSP00000262848', 'cpi_9606.ENSP00000407375', 'cpi_9606.ENSP00000231449', 'f_624'], ['f_654', 'cpi_9606.ENSP00000302728', 'f_824', 'cpi_9606.ENSP00000253727', 'cpi_9606.ENSP00000339260'], ['f_607', '

🔄 Processing features: 100%|██████████| 2147/2147 [10:24<00:00,  3.44feat/s]

XofN_groups: [['f_374', 'cpi_9606.ENSP00000402608', 'cpi_9606.ENSP00000286479', 'f_831', 'cpi_9606.ENSP00000365663'], ['cpi_9606.ENSP00000337915', 'f_413', 'f_845', 'f_151', 'f_262'], ['f_287', 'cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000356094', 'f_118', 'f_194'], ['f_308', 'cpi_9606.ENSP00000355192', 'f_616', 'cpi_9606.ENSP00000338627', 'f_768'], ['f_3', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000337335', 'f_789'], ['f_299', 'cpi_9606.ENSP00000306606', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000360493', 'cpi_9606.ENSP00000354476'], ['f_20', 'cpi_9606.ENSP00000261205', 'f_792', 'cpi_9606.ENSP00000262352', 'f_629'], ['f_393', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000355629', 'cpi_9606.ENSP00000370373'], ['f_23', 'cpi_9606.ENSP00000385026', 'f_408', 'cpi_9606.ENSP00000362353', 'f_292'], ['f_672', 'cpi_9606.ENSP00000264162', 'cpi_9606.ENSP00000367851', 'cpi_9606.ENSP00000361206', 'f_726'], ['f_285', 'cpi_9606.ENSP00000383365', 'f_866', 'cpi_9606.ENSP00000221972', 'cpi_9606.ENSP00000470087'], ['f_366', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000374265', 'cpi_9606.ENSP00000279178', 'f_428'], ['f_440', 'f_25', 'cpi_9606.ENSP00000382250', 'cpi_9606.ENSP00000342235', 'cpi_9606.ENSP00000378517'], ['f_614', 'cpi_9606.ENSP00000368305', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000316786', 'f_511'], ['f_452', 'cpi_9606.ENSP00000259486', 'cpi_9606.ENSP00000360773', 'cpi_9606.ENSP00000337773', 'f_635'], ['f_346', 'cpi_9606.ENSP00000395653', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000394936', 'cpi_9606.ENSP00000256383'], ['f_380', 'cpi_9606.ENSP00000263088', 'cpi_9606.ENSP00000381097', 'cpi_9606.ENSP00000353292', 'cpi_9606.ENSP00000277010'], ['f_571', 'cpi_9606.ENSP00000319170', 'cpi_9606.ENSP00000285381', 'f_429', 'f_791'], ['f_390', 'cpi_9606.ENSP00000359680', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000216037'], ['f_406', 'cpi_9606.ENSP00000352035', 'cpi_9606.ENSP00000242057', 'cpi_9606.ENSP00000374323', 'f_529'], ['f_617', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000264318'], ['cpi_9606.ENSP00000264381', 'f_693', 'f_815', 'f_670', 'f_31'], ['f_392', 'cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000332296', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000451040'], ['f_405', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000333496', 'cpi_9606.ENSP00000359353', 'f_510'], ['f_420', 'cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000304408', 'f_328', 'f_830'], ['f_15', 'cpi_9606.ENSP00000397582', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000304822', 'f_214'], ['f_37', 'cpi_9606.ENSP00000263321', 'f_43', 'cpi_9606.ENSP00000282753', 'f_35'], ['f_696', 'cpi_9606.ENSP00000274353', 'cpi_9606.ENSP00000414334', 'cpi_9606.ENSP00000355657', 'f_474'], ['f_659', 'cpi_9606.ENSP00000312286', 'f_773', 'cpi_9606.ENSP00000329357', 'f_427'], ['f_686', 'f_419', 'f_215', 'cpi_9606.ENSP00000342070', 'f_509'], ['f_339', 'f_330', 'cpi_9606.ENSP00000332369', 'f_771', 'f_799'], ['f_186', 'cpi_9606.ENSP00000371236', 'cpi_9606.ENSP00000389338', 'cpi_9606.ENSP00000409007', 'f_27'], ['f_566', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000200676', 'f_834'], ['f_33', 'f_706', 'f_350', 'cpi_9606.ENSP00000243167', 'cpi_9606.ENSP00000344192'], ['f_451', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000339260', 'f_836'], ['cpi_9606.ENSP00000311032', 'f_675', 'f_164', 'cpi_9606.ENSP00000344674', 'f_526'], ['f_192', 'cpi_9606.ENSP00000354850', 'cpi_9606.ENSP00000307240', 'f_47', 'cpi_9606.ENSP00000265294'], ['f_19', 'cpi_9606.ENSP00000376914', 'cpi_9606.ENSP00000312455', 'cpi_9606.ENSP00000286301', 'cpi_9606.ENSP00000367848'], ['f_391', 'cpi_9606.ENSP00000357204', 'f_725', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000398632'], ['f_639', 'f_568', 'f_417', 'cpi_9606.ENSP00000254976', 'f_736'], ['f_516', 'cpi_9606.ENSP00000364035', 'cpi_9606.ENSP00000260227', 'f_202', 'cpi_9606.ENSP00000430684'], ['f_146', 'cpi_9606.ENSP00000305692', 'cpi_9606.ENSP00000368104', 'f_587', 'f_297'], ['f_181', 'cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000368253', 'f_166', 'cpi_9606.ENSP00000301891'], ['f_143', 'cpi_9606.ENSP00000319531', 'cpi_9606.ENSP00000252486', 'cpi_9606.ENSP00000262367', 'f_767'], ['f_643', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000296511', 'f_622'], ['f_12', 'cpi_9606.ENSP00000314214', 'cpi_9606.ENSP00000254810', 'cpi_9606.ENSP00000303540', 'f_788'], ['f_185', 'cpi_9606.ENSP00000405573', 'cpi_9606.ENSP00000427514', 'cpi_9606.ENSP00000295491', 'cpi_9606.ENSP00000263339'], ['f_2', 'cpi_9606.ENSP00000417901', 'cpi_9606.ENSP00000319788', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000305422'], ['f_340', 'cpi_9606.ENSP00000358727', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000252809', 'f_436'], ['f_656', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000309124', 'cpi_9606.ENSP00000457706'], ['f_613', 'cpi_9606.ENSP00000471397', 'cpi_9606.ENSP00000264637', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000326119'], ['f_681', 'cpi_9606.ENSP00000291295', 'f_676', 'f_460', 'cpi_9606.ENSP00000359285'], ['f_21', 'cpi_9606.ENSP00000306490', 'f_752', 'f_116', 'f_554'], ['f_528', 'cpi_9606.ENSP00000216465', 'cpi_9606.ENSP00000365016', 'f_729', 'f_327'], ['f_341', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000241453'], ['f_361', 'f_667', 'cpi_9606.ENSP00000352835', 'f_647', 'f_778'], ['f_569', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000341885', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000353362'], ['f_335', 'cpi_9606.ENSP00000262888', 'cpi_9606.ENSP00000233146', 'cpi_9606.ENSP00000320935', 'f_466'], ['f_338', 'cpi_9606.ENSP00000327431', 'f_757', 'cpi_9606.ENSP00000295834', 'cpi_9606.ENSP00000339527'], ['f_697', 'cpi_9606.ENSP00000229319', 'f_749', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000417229'], ['f_248', 'cpi_9606.ENSP00000356729', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000431719', 'f_455'], ['f_351', 'cpi_9606.ENSP00000226578', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000222330', 'f_583'], ['f_535', 'cpi_9606.ENSP00000223366', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000312304', 'f_497'], ['f_712', 'f_533', 'cpi_9606.ENSP00000326219', 'cpi_9606.ENSP00000295454', 'cpi_9606.ENSP00000296122'], ['f_443', 'cpi_9606.ENSP00000337746', 'cpi_9606.ENSP00000343477', 'cpi_9606.ENSP00000301974', 'f_722'], ['f_567', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000276449', 'f_715', 'f_750'], ['f_553', 'cpi_9606.ENSP00000332549', 'cpi_9606.ENSP00000309649', 'f_229', 'f_167'], ['f_698', 'cpi_9606.ENSP00000344460', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000257290', 'f_728'], ['f_684', 'cpi_9606.ENSP00000330032', 'f_473', 'cpi_9606.ENSP00000311095', 'f_785'], ['f_257', 'cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000387946', 'cpi_9606.ENSP00000299847'], ['f_683', 'cpi_9606.ENSP00000276651', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000296871'], ['f_540', 'cpi_9606.ENSP00000297258', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000309493', 'cpi_9606.ENSP00000312664'], ['cpi_9606.ENSP00000231509', 'f_34', 'f_46', 'f_805', 'f_518'], ['f_690', 'cpi_9606.ENSP00000318820', 'f_131', 'f_813', 'cpi_9606.ENSP00000412673'], ['f_337', 'cpi_9606.ENSP00000303211', 'f_609', 'f_388', 'cpi_9606.ENSP00000266376'], ['f_671', 'cpi_9606.ENSP00000367123', 'cpi_9606.ENSP00000410732', 'f_407', 'cpi_9606.ENSP00000258749'], ['f_581', 'cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000355317', 'f_494', 'f_298'], ['f_18', 'cpi_9606.ENSP00000472933', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000333212', 'cpi_9606.ENSP00000297316'], ['f_689', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000331912', 'cpi_9606.ENSP00000355778', 'cpi_9606.ENSP00000376178'], ['f_11', 'cpi_9606.ENSP00000280701', 'cpi_9606.ENSP00000226574', 'cpi_9606.ENSP00000261937', 'f_448'], ['f_777', 'f_26', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000301634'], ['f_646', 'cpi_9606.ENSP00000237014', 'cpi_9606.ENSP00000346598', 'f_820', 'cpi_9606.ENSP00000216862'], ['f_638', 'cpi_9606.ENSP00000353679', 'f_860', 'cpi_9606.ENSP00000344352', 'f_508'], ['f_10', 'cpi_9606.ENSP00000302441', 'cpi_9606.ENSP00000354394', 'cpi_9606.ENSP00000343040', 'f_764'], ['f_345', 'cpi_9606.ENSP00000277508', 'cpi_9606.ENSP00000218758', 'f_505', 'cpi_9606.ENSP00000376943'], ['f_611', 'cpi_9606.ENSP00000338548', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000274793', 'cpi_9606.ENSP00000296370'], ['f_662', 'cpi_9606.ENSP00000299178', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000335592', 'f_763'], ['f_332', 'cpi_9606.ENSP00000346103', 'cpi_9606.ENSP00000263464', 'cpi_9606.ENSP00000379086', 'cpi_9606.ENSP00000261799'], ['f_573', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000262948', 'cpi_9606.ENSP00000386229'], ['cpi_9606.ENSP00000265724', 'f_207', 'f_401', 'f_483', 'cpi_9606.ENSP00000359793'], ['f_16', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000419692', 'cpi_9606.ENSP00000307599'], ['f_9', 'cpi_9606.ENSP00000226299', 'cpi_9606.ENSP00000328818', 'cpi_9606.ENSP00000293288', 'f_719'], ['f_180', 'cpi_9606.ENSP00000372326', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000227758'], ['f_294', 'f_782', 'cpi_9606.ENSP00000343782', 'f_159', 'cpi_9606.ENSP00000234071'], ['cpi_9606.ENSP00000295897', 'f_343', 'f_514', 'f_477', 'f_195'], ['f_365', 'cpi_9606.ENSP00000366620', 'cpi_9606.ENSP00000365380', 'cpi_9606.ENSP00000296350', 'f_827'], ['f_579', 'cpi_9606.ENSP00000306100', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000467676', 'cpi_9606.ENSP00000282561'], ['f_550', 'cpi_9606.ENSP00000270142', 'f_230', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000367102'], ['f_439', 'cpi_9606.ENSP00000377192', 'cpi_9606.ENSP00000358548', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000323568'], ['f_692', 'cpi_9606.ENSP00000447378', 'cpi_9606.ENSP00000471569', 'f_475', 'cpi_9606.ENSP00000361359'], ['f_462', 'f_423', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000373477', 'cpi_9606.ENSP00000369530'], ['f_24', 'cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000283635'], ['f_663', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000310219', 'f_216', 'cpi_9606.ENSP00000347942'], ['f_615', 'f_839', 'cpi_9606.ENSP00000315644', 'cpi_9606.ENSP00000352011', 'f_631'], ['f_695', 'f_861', 'cpi_9606.ENSP00000331602', 'cpi_9606.ENSP00000299267', 'cpi_9606.ENSP00000362036'], ['f_699', 'f_488', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000354610', 'cpi_9606.ENSP00000274547'], ['f_284', 'cpi_9606.ENSP00000348395', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000275525', 'f_409'], ['f_818', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000220616', 'cpi_9606.ENSP00000351957', 'f_454'], ['f_537', 'f_650', 'cpi_9606.ENSP00000262017', 'f_398', 'f_759'], ['f_776', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000267119', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000348069'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000380247', 'f_22', 'f_496', 'cpi_9606.ENSP00000252804'], ['f_798', 'cpi_9606.ENSP00000333994', 'f_517', 'cpi_9606.ENSP00000312029', 'f_471'], ['f_353', 'cpi_9606.ENSP00000234111', 'cpi_9606.ENSP00000256958', 'cpi_9606.ENSP00000451030', 'f_812'], ['f_705', 'cpi_9606.ENSP00000396308', 'f_422', 'cpi_9606.ENSP00000389414', 'cpi_9606.ENSP00000293745'], ['f_682', 'cpi_9606.ENSP00000249750', 'cpi_9606.ENSP00000307014', 'cpi_9606.ENSP00000264867', 'f_132'], ['f_193', 'cpi_9606.ENSP00000284981', 'f_644', 'f_513', 'cpi_9606.ENSP00000259396'], ['f_241', 'cpi_9606.ENSP00000298352', 'cpi_9606.ENSP00000308165', 'f_129', 'cpi_9606.ENSP00000317379'], ['f_704', 'cpi_9606.ENSP00000366927', 'cpi_9606.ENSP00000318646', 'cpi_9606.ENSP00000428340', 'cpi_9606.ENSP00000252723'], ['f_13', 'cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000321988', 'cpi_9606.ENSP00000363812', 'f_467'], ['f_536', 'cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000369654', 'f_833', 'f_840'], ['f_342', 'f_227', 'cpi_9606.ENSP00000364731', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000259089'], ['f_293', 'cpi_9606.ENSP00000355536', 'cpi_9606.ENSP00000263126', 'cpi_9606.ENSP00000260010', 'f_486'], ['f_283', 'cpi_9606.ENSP00000264705', 'cpi_9606.ENSP00000359663', 'f_394', 'f_551'], ['f_334', 'cpi_9606.ENSP00000376776', 'f_625', 'cpi_9606.ENSP00000260102', 'cpi_9606.ENSP00000301178'], ['f_691', 'cpi_9606.ENSP00000268053', 'cpi_9606.ENSP00000231454', 'cpi_9606.ENSP00000353878', 'cpi_9606.ENSP00000216962'], ['f_642', 'cpi_9606.ENSP00000367309', 'cpi_9606.ENSP00000229264', 'f_30', 'f_822'], ['f_637', 'cpi_9606.ENSP00000332256', 'cpi_9606.ENSP00000356832', 'f_770', 'f_738'], ['f_594', 'cpi_9606.ENSP00000340943', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000430432', 'cpi_9606.ENSP00000225474'], ['f_641', 'cpi_9606.ENSP00000318912', 'cpi_9606.ENSP00000309572', 'f_411', 'f_558'], ['f_701', 'cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000267101', 'f_314'], ['f_464', 'cpi_9606.ENSP00000429374', 'cpi_9606.ENSP00000236671', 'cpi_9606.ENSP00000297313', 'f_115'], ['f_286', 'cpi_9606.ENSP00000312326', 'cpi_9606.ENSP00000239938', 'cpi_9606.ENSP00000328973', 'f_543'], ['f_574', 'cpi_9606.ENSP00000359100', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000356954', 'f_456'], ['f_645', 'cpi_9606.ENSP00000330484', 'cpi_9606.ENSP00000300061', 'cpi_9606.ENSP00000294728', 'cpi_9606.ENSP00000251535'], ['f_619', 'cpi_9606.ENSP00000364212', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000263980', 'cpi_9606.ENSP00000261693'], ['f_680', 'cpi_9606.ENSP00000380318', 'cpi_9606.ENSP00000448059', 'f_522', 'cpi_9606.ENSP00000264657'], ['f_437', 'cpi_9606.ENSP00000263269', 'cpi_9606.ENSP00000407375', 'f_653', 'cpi_9606.ENSP00000361666'], ['f_458', 'cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000241261', 'f_200', 'f_461'], ['f_145', 'cpi_9606.ENSP00000434516', 'cpi_9606.ENSP00000297350', 'f_575', 'f_242'], ['f_549', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000267017', 'cpi_9606.ENSP00000378890', 'f_740'], ['f_548', 'cpi_9606.ENSP00000309477', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000356958', 'f_359'], ['f_779', 'f_347', 'cpi_9606.ENSP00000366506', 'cpi_9606.ENSP00000358784', 'cpi_9606.ENSP00000431512'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000301420', 'f_601', 'cpi_9606.ENSP00000310447', 'f_687'], ['f_1', 'cpi_9606.ENSP00000238379', 'cpi_9606.ENSP00000261196', 'cpi_9606.ENSP00000216797', 'f_742'], ['f_487', 'cpi_9606.ENSP00000260356', 'cpi_9606.ENSP00000225927', 'cpi_9606.ENSP00000311028', 'f_336'], ['f_368', 'cpi_9606.ENSP00000272298', 'cpi_9606.ENSP00000351209', 'f_826', 'cpi_9606.ENSP00000233242'], ['f_593', 'cpi_9606.ENSP00000356671', 'cpi_9606.ENSP00000255465', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000255380'], ['f_375', 'cpi_9606.ENSP00000353224', 'cpi_9606.ENSP00000323549', 'f_144', 'f_559'], ['f_592', 'cpi_9606.ENSP00000387536', 'cpi_9606.ENSP00000384273', 'f_801', 'f_160'], ['f_432', 'cpi_9606.ENSP00000288022', 'cpi_9606.ENSP00000306138', 'f_363', 'f_480'], ['f_199', 'cpi_9606.ENSP00000385834', 'f_489', 'cpi_9606.ENSP00000330393', 'f_515'], ['f_356', 'cpi_9606.ENSP00000196551', 'cpi_9606.ENSP00000314649', 'cpi_9606.ENSP00000370473', 'f_425'], ['f_628', 'cpi_9606.ENSP00000216714', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000366307', 'f_395'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000262441', 'cpi_9606.ENSP00000362649', 'f_630', 'f_421'], ['f_249', 'f_300', 'cpi_9606.ENSP00000264668', 'cpi_9606.ENSP00000319591', 'f_652'], ['f_819', 'cpi_9606.ENSP00000220764', 'f_717', 'cpi_9606.ENSP00000267843', 'cpi_9606.ENSP00000331358'], ['f_333', 'cpi_9606.ENSP00000293404', 'cpi_9606.ENSP00000248553', 'f_38', 'cpi_9606.ENSP00000391826'], ['f_797', 'cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000292095', 'f_301', 'cpi_9606.ENSP00000301633'], ['f_711', 'cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000348645', 'f_17', 'cpi_9606.ENSP00000368766'], ['f_430', 'cpi_9606.ENSP00000435777', 'cpi_9606.ENSP00000346827', 'cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000256010'], ['f_702', 'cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000366662', 'f_780', 'cpi_9606.ENSP00000335511'], ['f_188', 'cpi_9606.ENSP00000363822', 'cpi_9606.ENSP00000338082', 'f_588', 'cpi_9606.ENSP00000295589'], ['f_666', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000359635', 'cpi_9606.ENSP00000445340', 'f_157'], ['f_502', 'cpi_9606.ENSP00000368880', 'cpi_9606.ENSP00000270625', 'cpi_9606.ENSP00000270776', 'f_761'], ['f_821', 'cpi_9606.ENSP00000352516', 'f_658', 'cpi_9606.ENSP00000350005', 'cpi_9606.ENSP00000364802'], ['f_14', 'cpi_9606.ENSP00000244051', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000231228', 'f_721'], ['f_150', 'cpi_9606.ENSP00000368438', 'cpi_9606.ENSP00000355930', 'f_465', 'f_364'], ['f_657', 'cpi_9606.ENSP00000293190', 'cpi_9606.ENSP00000222390', 'f_803', 'cpi_9606.ENSP00000325822'], ['cpi_9606.ENSP00000330237', 'f_152', 'cpi_9606.ENSP00000364709', 'f_414', 'f_213'], ['f_708', 'cpi_9606.ENSP00000258662', 'cpi_9606.ENSP00000375093', 'cpi_9606.ENSP00000302111', 'f_500'], ['cpi_9606.ENSP00000297494', 'f_716', 'cpi_9606.ENSP00000379339', 'cpi_9606.ENSP00000353791', 'cpi_9606.ENSP00000003100'], ['f_604', 'cpi_9606.ENSP00000360141', 'cpi_9606.ENSP00000353427', 'cpi_9606.ENSP00000300900', 'f_694'], ['f_710', 'cpi_9606.ENSP00000039007', 'cpi_9606.ENSP00000253727', 'f_367', 'cpi_9606.ENSP00000463999'], ['f_655', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000246337', 'cpi_9606.ENSP00000255030', 'f_397'], ['f_602', 'cpi_9606.ENSP00000321106', 'cpi_9606.ENSP00000386284', 'f_621', 'f_700'], ['f_586', 'cpi_9606.ENSP00000220809', 'f_824', 'cpi_9606.ENSP00000352584', 'cpi_9606.ENSP00000353915'], ['f_493', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000260649', 'cpi_9606.ENSP00000347979', 'cpi_9606.ENSP00000409378'], ['f_498', 'cpi_9606.ENSP00000279593', 'cpi_9606.ENSP00000380252', 'cpi_9606.ENSP00000277120', 'f_305'], ['f_633', 'cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000459962', 'f_610'], ['f_377', 'cpi_9606.ENSP00000217961', 'cpi_9606.ENSP00000410076', 'f_605', 'cpi_9606.ENSP00000292513'], ['f_206', 'cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000309818', 'f_459', 'cpi_9606.ENSP00000433821'], ['f_709', 'cpi_9606.ENSP00000251453', 'cpi_9606.ENSP00000011292', 'cpi_9606.ENSP00000278616', 'f_260'], ['f_688', 'cpi_9606.ENSP00000229447', 'cpi_9606.ENSP00000354558', 'cpi_9606.ENSP00000370381', 'f_612'], ['f_352', 'cpi_9606.ENSP00000430031', 'cpi_9606.ENSP00000231449', 'f_457', 'cpi_9606.ENSP00000357283'], ['f_412', 'cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000253004', 'f_713', 'cpi_9606.ENSP00000320401'], ['f_560', 'cpi_9606.ENSP00000262407', 'cpi_9606.ENSP00000262735', 'f_756', 'cpi_9606.ENSP00000371929'], ['f_418', 'cpi_9606.ENSP00000382791', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000293272', 'f_661'], ['f_453', 'cpi_9606.ENSP00000261733', 'cpi_9606.ENSP00000263431', 'f_544', 'cpi_9606.ENSP00000310928'], ['f_261', 'cpi_9606.ENSP00000349467', 'cpi_9606.ENSP00000372023', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000287766'], ['f_599', 'cpi_9606.ENSP00000248935', 'cpi_9606.ENSP00000304895', 'f_784', 'cpi_9606.ENSP00000336630'], ['f_450', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000466399', 'f_563', 'cpi_9606.ENSP00000261707'], ['f_580', 'cpi_9606.ENSP00000261267', 'cpi_9606.ENSP00000291294', 'f_250', 'cpi_9606.ENSP00000301146'], ['f_591', 'cpi_9606.ENSP00000356022', 'f_527', 'cpi_9606.ENSP00000303424', 'cpi_9606.ENSP00000176763'], ['f_0', 'cpi_9606.ENSP00000302620', 'cpi_9606.ENSP00000264832', 'f_187', 'cpi_9606.ENSP00000414303'], ['f_381', 'cpi_9606.ENSP00000309591', 'cpi_9606.ENSP00000318822', 'f_531', 'cpi_9606.ENSP00000309757'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000356150', 'f_737', 'cpi_9606.ENSP00000219919'], ['f_470', 'cpi_9606.ENSP00000346067', '

🔄 Processing features: 100%|██████████| 2147/2147 [10:24<00:00,  3.44feat/s]

XofN_groups: [['f_308', 'cpi_9606.ENSP00000355192', 'f_616', 'cpi_9606.ENSP00000263377', 'cpi_9606.ENSP00000351957'], ['cpi_9606.ENSP00000337915', 'f_408', 'f_151', 'f_31', 'f_845'], ['f_374', 'cpi_9606.ENSP00000039007', 'f_831', 'cpi_9606.ENSP00000395653', 'cpi_9606.ENSP00000409007'], ['f_20', 'cpi_9606.ENSP00000254976', 'cpi_9606.ENSP00000333212', 'cpi_9606.ENSP00000277010', 'cpi_9606.ENSP00000286301'], ['f_23', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000274353', 'f_631', 'f_413'], ['f_287', 'cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000356094', 'f_194', 'f_118'], ['f_451', 'cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000354476', 'f_428'], ['f_3', 'cpi_9606.ENSP00000264162', 'f_789', 'cpi_9606.ENSP00000337335', 'cpi_9606.ENSP00000302811'], ['f_390', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000222481', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000270631'], ['f_346', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000279178', 'f_629'], ['f_299', 'cpi_9606.ENSP00000237014', 'cpi_9606.ENSP00000292427', 'f_866', 'cpi_9606.ENSP00000355629'], ['f_452', 'f_25', 'cpi_9606.ENSP00000263088', 'f_726', 'cpi_9606.ENSP00000342235'], ['f_406', 'cpi_9606.ENSP00000352035', 'cpi_9606.ENSP00000374323', 'f_773', 'f_820'], ['f_392', 'cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000363812', 'f_510', 'cpi_9606.ENSP00000300061'], ['f_285', 'cpi_9606.ENSP00000380318', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000304822', 'cpi_9606.ENSP00000200676'], ['f_37', 'cpi_9606.ENSP00000263321', 'f_43', 'cpi_9606.ENSP00000282753', 'f_35'], ['f_672', 'cpi_9606.ENSP00000216465', 'f_675', 'f_292', 'cpi_9606.ENSP00000262352'], ['f_15', 'cpi_9606.ENSP00000397582', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000430684', 'cpi_9606.ENSP00000316786'], ['f_614', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000319531', 'f_511', 'f_749'], ['f_380', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000365663', 'cpi_9606.ENSP00000360773', 'cpi_9606.ENSP00000295452'], ['f_643', 'cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000332296', 'cpi_9606.ENSP00000231228', 'f_27'], ['f_440', 'cpi_9606.ENSP00000262888', 'cpi_9606.ENSP00000233146', 'cpi_9606.ENSP00000372547', 'f_791'], ['f_659', 'cpi_9606.ENSP00000357204', 'cpi_9606.ENSP00000360493', 'f_526', 'cpi_9606.ENSP00000229264'], ['f_571', 'cpi_9606.ENSP00000319170', 'cpi_9606.ENSP00000301891', 'f_768', 'f_429'], ['f_566', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000257290', 'cpi_9606.ENSP00000343040'], ['f_19', 'cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000391676', 'cpi_9606.ENSP00000367848', 'cpi_9606.ENSP00000367851'], ['f_420', 'cpi_9606.ENSP00000337746', 'f_328', 'cpi_9606.ENSP00000459962', 'f_529'], ['cpi_9606.ENSP00000311032', 'f_116', 'f_554', 'f_164', 'f_587'], ['f_366', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000343204', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000376178'], ['f_340', 'cpi_9606.ENSP00000368305', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000319788', 'f_436'], ['f_405', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000309493', 'f_635'], ['f_339', 'f_676', 'f_670', 'f_778', 'cpi_9606.ENSP00000332369'], ['f_393', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000376914', 'f_214', 'cpi_9606.ENSP00000359353'], ['f_33', 'f_706', 'cpi_9606.ENSP00000352835', 'f_350', 'cpi_9606.ENSP00000435591'], ['f_617', 'cpi_9606.ENSP00000394033', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000394936'], ['f_696', 'cpi_9606.ENSP00000354610', 'cpi_9606.ENSP00000370381', 'f_47', 'cpi_9606.ENSP00000369375'], ['f_186', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000428824', 'f_202'], ['f_143', 'cpi_9606.ENSP00000229319', 'cpi_9606.ENSP00000274793', 'f_836', 'f_297'], ['f_146', 'cpi_9606.ENSP00000359100', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000222330', 'cpi_9606.ENSP00000366307'], ['cpi_9606.ENSP00000264381', 'f_22', 'f_815', 'f_719', 'f_465'], ['f_639', 'f_427', 'f_767', 'cpi_9606.ENSP00000292896', 'f_131'], ['f_12', 'cpi_9606.ENSP00000261205', 'cpi_9606.ENSP00000414334', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000263339'], ['f_192', 'cpi_9606.ENSP00000327431', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000296545', 'cpi_9606.ENSP00000389338'], ['f_391', 'cpi_9606.ENSP00000471397', 'f_725', 'cpi_9606.ENSP00000264637', 'cpi_9606.ENSP00000312455'], ['f_686', 'cpi_9606.ENSP00000270142', 'f_215', 'f_509', 'f_568'], ['f_712', 'f_830', 'cpi_9606.ENSP00000330032', 'f_771', 'f_46'], ['f_638', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000447173', 'f_757', 'cpi_9606.ENSP00000408860'], ['f_681', 'cpi_9606.ENSP00000291295', 'f_460', 'cpi_9606.ENSP00000359285', 'f_466'], ['f_697', 'cpi_9606.ENSP00000354850', 'cpi_9606.ENSP00000278175', 'f_788', 'cpi_9606.ENSP00000216037'], ['f_2', 'cpi_9606.ENSP00000386284', 'cpi_9606.ENSP00000301974', 'cpi_9606.ENSP00000344352', 'cpi_9606.ENSP00000221972'], ['f_345', 'cpi_9606.ENSP00000226578', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000451040', 'cpi_9606.ENSP00000457706'], ['f_611', 'cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000262999', 'f_298', 'cpi_9606.ENSP00000309124'], ['f_185', 'cpi_9606.ENSP00000314214', 'cpi_9606.ENSP00000445340', 'cpi_9606.ENSP00000365016', 'cpi_9606.ENSP00000263126'], ['f_528', 'cpi_9606.ENSP00000244051', 'cpi_9606.ENSP00000387946', 'f_327', 'f_792'], ['f_443', 'cpi_9606.ENSP00000383365', 'f_330', 'f_497', 'cpi_9606.ENSP00000365380'], ['f_646', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000318912', 'f_763', 'f_834'], ['f_535', 'cpi_9606.ENSP00000258662', 'cpi_9606.ENSP00000350348', 'f_785', 'cpi_9606.ENSP00000343477'], ['f_569', 'cpi_9606.ENSP00000338548', 'cpi_9606.ENSP00000419692', 'cpi_9606.ENSP00000251535', 'cpi_9606.ENSP00000353362'], ['f_21', 'f_752', 'cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000358548', 'f_715'], ['f_656', 'cpi_9606.ENSP00000295491', 'cpi_9606.ENSP00000297258', 'cpi_9606.ENSP00000388825', 'cpi_9606.ENSP00000299847'], ['f_338', 'cpi_9606.ENSP00000434516', 'cpi_9606.ENSP00000299267', 'cpi_9606.ENSP00000261799', 'f_839'], ['f_540', 'cpi_9606.ENSP00000220616', 'cpi_9606.ENSP00000386171', 'cpi_9606.ENSP00000448059', 'cpi_9606.ENSP00000326119'], ['f_613', 'cpi_9606.ENSP00000306606', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000323568', 'cpi_9606.ENSP00000312664'], ['f_365', 'cpi_9606.ENSP00000295834', 'cpi_9606.ENSP00000277508', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000470087'], ['f_553', 'cpi_9606.ENSP00000262441', 'cpi_9606.ENSP00000181383', 'f_229', 'f_26'], ['f_181', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000348827', 'f_166', 'cpi_9606.ENSP00000266376'], ['f_516', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000346103', 'cpi_9606.ENSP00000353292', 'cpi_9606.ENSP00000329357'], ['f_341', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000273398', 'cpi_9606.ENSP00000417229', 'cpi_9606.ENSP00000283635'], ['f_257', 'cpi_9606.ENSP00000358727', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000365686', 'f_448'], ['f_342', 'f_782', 'cpi_9606.ENSP00000299178', 'f_262', 'cpi_9606.ENSP00000217426'], ['f_335', 'cpi_9606.ENSP00000333994', 'f_813', 'cpi_9606.ENSP00000226574', 'f_477'], ['cpi_9606.ENSP00000265724', 'f_207', 'f_455', 'f_722', 'f_407'], ['f_698', 'cpi_9606.ENSP00000364709', 'f_388', 'f_729', 'f_474'], ['f_248', 'cpi_9606.ENSP00000356729', 'cpi_9606.ENSP00000267119', 'cpi_9606.ENSP00000334198', 'f_473'], ['f_645', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000361206', 'f_799'], ['f_776', 'cpi_9606.ENSP00000390600', 'f_533', 'cpi_9606.ENSP00000262407', 'f_518'], ['f_361', 'cpi_9606.ENSP00000295897', 'f_187', 'cpi_9606.ENSP00000378517', 'f_394'], ['f_615', 'cpi_9606.ENSP00000318820', 'f_417', 'cpi_9606.ENSP00000252723', 'cpi_9606.ENSP00000369038'], ['f_537', 'cpi_9606.ENSP00000303211', 'f_488', 'f_483', 'cpi_9606.ENSP00000386306'], ['f_464', 'cpi_9606.ENSP00000364035', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000252809'], ['f_11', 'cpi_9606.ENSP00000346827', 'cpi_9606.ENSP00000356832', 'cpi_9606.ENSP00000296370', 'f_583'], ['f_689', 'cpi_9606.ENSP00000371236', 'cpi_9606.ENSP00000297316', 'f_728', 'f_736'], ['f_684', 'cpi_9606.ENSP00000430031', 'cpi_9606.ENSP00000381097', 'cpi_9606.ENSP00000282561', 'f_622'], ['f_294', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000343782', 'f_167', 'cpi_9606.ENSP00000216185'], ['f_683', 'cpi_9606.ENSP00000222482', 'cpi_9606.ENSP00000303248', 'cpi_9606.ENSP00000354394', 'cpi_9606.ENSP00000346534'], ['f_693', 'cpi_9606.ENSP00000342070', 'f_422', 'cpi_9606.ENSP00000275525', 'f_750'], ['f_24', 'cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000222381', 'f_827', 'cpi_9606.ENSP00000352584'], ['f_579', 'cpi_9606.ENSP00000234389', 'cpi_9606.ENSP00000363296', 'cpi_9606.ENSP00000311095', 'f_764'], ['f_690', 'f_609', 'cpi_9606.ENSP00000302961', 'cpi_9606.ENSP00000282018', 'f_409'], ['f_180', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000318646', 'cpi_9606.ENSP00000324270', 'f_343'], ['f_144', 'f_717', 'cpi_9606.ENSP00000308541', 'f_588', 'f_508'], ['f_18', 'cpi_9606.ENSP00000472933', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000361359', 'cpi_9606.ENSP00000376943'], ['f_641', 'cpi_9606.ENSP00000259486', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000261937'], ['f_671', 'cpi_9606.ENSP00000298171', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000330393'], ['f_701', 'f_419', 'cpi_9606.ENSP00000344460', 'cpi_9606.ENSP00000369816', 'f_461'], ['f_439', 'cpi_9606.ENSP00000354511', 'cpi_9606.ENSP00000231454', 'f_505', 'f_812'], ['cpi_9606.ENSP00000336528', 'f_34', 'cpi_9606.ENSP00000219833', 'f_398', 'cpi_9606.ENSP00000262367'], ['f_241', 'cpi_9606.ENSP00000355155', 'f_132', 'cpi_9606.ENSP00000246553', 'f_401'], ['f_1', 'cpi_9606.ENSP00000226299', 'cpi_9606.ENSP00000296677', 'cpi_9606.ENSP00000347942', 'cpi_9606.ENSP00000367102'], ['f_699', 'cpi_9606.ENSP00000263269', 'f_494', 'f_833', 'cpi_9606.ENSP00000252486'], ['f_667', 'cpi_9606.ENSP00000338082', 'cpi_9606.ENSP00000259089', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000293288'], ['f_682', 'cpi_9606.ENSP00000236850', 'cpi_9606.ENSP00000280357', 'cpi_9606.ENSP00000307599', 'f_522'], ['f_840', 'f_375', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000376776'], ['f_199', 'cpi_9606.ENSP00000385834', 'f_489', 'cpi_9606.ENSP00000353791', 'f_30'], ['f_334', 'cpi_9606.ENSP00000396308', 'f_625', 'cpi_9606.ENSP00000258749', 'cpi_9606.ENSP00000427514'], ['f_573', 'cpi_9606.ENSP00000399168', 'cpi_9606.ENSP00000295454', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000225474'], ['f_333', 'cpi_9606.ENSP00000296754', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000301178', 'f_770'], ['f_567', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000276449', 'cpi_9606.ENSP00000291700', 'f_644'], ['f_193', 'cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000260010', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000389414'], ['f_692', 'cpi_9606.ENSP00000447378', 'cpi_9606.ENSP00000471569', 'f_475', 'f_551'], ['f_14', 'cpi_9606.ENSP00000343690', 'cpi_9606.ENSP00000305422', 'f_861', 'f_740'], ['f_16', 'cpi_9606.ENSP00000295598', 'cpi_9606.ENSP00000356958', 'f_216', 'cpi_9606.ENSP00000296871'], ['f_351', 'cpi_9606.ENSP00000306100', 'cpi_9606.ENSP00000346017', 'cpi_9606.ENSP00000297350', 'f_653'], ['f_619', 'cpi_9606.ENSP00000333667', 'cpi_9606.ENSP00000371929', 'f_650', 'cpi_9606.ENSP00000344192'], ['f_642', 'cpi_9606.ENSP00000309818', 'cpi_9606.ENSP00000321988', 'cpi_9606.ENSP00000331912', 'cpi_9606.ENSP00000346598'], ['f_797', 'cpi_9606.ENSP00000284981', 'f_513', 'f_486', 'f_543'], ['f_663', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000263857', 'cpi_9606.ENSP00000356954'], ['f_818', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000355657', 'cpi_9606.ENSP00000267101'], ['f_594', 'cpi_9606.ENSP00000272847', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000370473'], ['f_637', 'cpi_9606.ENSP00000332256', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000340691', 'f_471'], ['f_432', 'cpi_9606.ENSP00000353720', 'f_496', 'cpi_9606.ENSP00000253004', 'f_159'], ['cpi_9606.ENSP00000231509', 'f_423', 'cpi_9606.ENSP00000218099', 'f_115', 'cpi_9606.ENSP00000351885'], ['cpi_9606.ENSP00000353820', 'f_359', 'cpi_9606.ENSP00000328173', 'f_129', 'cpi_9606.ENSP00000364310'], ['f_704', 'cpi_9606.ENSP00000367123', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000216862', 'f_480'], ['f_680', 'cpi_9606.ENSP00000417901', 'cpi_9606.ENSP00000239938', 'f_467', 'f_559'], ['f_462', 'cpi_9606.ENSP00000350616', 'f_454', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000261693'], ['f_602', 'cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000270625', 'f_517'], ['f_777', 'cpi_9606.ENSP00000243167', 'f_647', 'cpi_9606.ENSP00000294728', 'f_500'], ['f_332', 'cpi_9606.ENSP00000348395', 'cpi_9606.ENSP00000310405', 'cpi_9606.ENSP00000242057', 'f_195'], ['f_13', 'cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000265403', 'f_305'], ['f_368', 'cpi_9606.ENSP00000355536', 'cpi_9606.ENSP00000274547', 'f_230', 'cpi_9606.ENSP00000410294'], ['f_249', 'f_716', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000313699', 'f_395'], ['f_591', 'cpi_9606.ENSP00000356022', 'f_399', 'cpi_9606.ENSP00000256958', 'f_558'], ['f_819', 'cpi_9606.ENSP00000220764', 'cpi_9606.ENSP00000335592', 'f_459', 'cpi_9606.ENSP00000357283'], ['f_593', 'cpi_9606.ENSP00000305692', 'cpi_9606.ENSP00000396320', 'f_242', 'cpi_9606.ENSP00000241261'], ['f_691', 'cpi_9606.ENSP00000268053', 'cpi_9606.ENSP00000353878', 'cpi_9606.ENSP00000428924', 'f_514'], ['f_662', 'cpi_9606.ENSP00000217961', 'cpi_9606.ENSP00000348069', 'f_738', 'cpi_9606.ENSP00000416293'], ['f_711', 'f_421', 'cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000463999'], ['f_581', 'cpi_9606.ENSP00000264668', 'cpi_9606.ENSP00000385806', 'cpi_9606.ENSP00000361666', 'f_515'], ['f_286', 'cpi_9606.ENSP00000363533', 'cpi_9606.ENSP00000312029', 'f_759', 'f_742'], ['f_708', 'cpi_9606.ENSP00000228476', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000308165', 'f_826'], ['f_536', 'cpi_9606.ENSP00000387230', 'f_860', 'cpi_9606.ENSP00000300900', 'f_784'], ['f_353', 'cpi_9606.ENSP00000369654', 'cpi_9606.ENSP00000277120', 'f_801', 'f_456'], ['f_145', 'cpi_9606.ENSP00000249750', 'cpi_9606.ENSP00000331746', 'f_605', 'cpi_9606.ENSP00000335511'], ['f_293', 'cpi_9606.ENSP00000386884', 'cpi_9606.ENSP00000276651', 'f_336', 'cpi_9606.ENSP00000260191'], ['cpi_9606.ENSP00000342007', 'f_347', 'cpi_9606.ENSP00000359793', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000255465'], ['f_352', 'cpi_9606.ENSP00000343885', 'cpi_9606.ENSP00000339527', 'f_822', 'cpi_9606.ENSP00000259396'], ['f_255', 'cpi_9606.ENSP00000382250', 'cpi_9606.ENSP00000310447', 'cpi_9606.ENSP00000320935', 'f_314'], ['f_705', 'cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000288022', 'f_300', 'cpi_9606.ENSP00000343925'], ['f_498', 'cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000260356', 'f_780', 'f_411'], ['f_702', 'cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000263980', 'cpi_9606.ENSP00000366662', 'f_213'], ['f_549', 'cpi_9606.ENSP00000308897', 'cpi_9606.ENSP00000296122', 'f_227', 'f_687'], ['f_550', 'cpi_9606.ENSP00000317842', 'f_160', 'cpi_9606.ENSP00000262461', 'cpi_9606.ENSP00000379140'], ['f_349', 'cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000260649', 'cpi_9606.ENSP00000239849', 'f_575'], ['f_666', 'cpi_9606.ENSP00000360141', 'cpi_9606.ENSP00000222390', 'f_17', 'cpi_9606.ENSP00000303540'], ['f_628', 'cpi_9606.ENSP00000216714', 'cpi_9606.ENSP00000233242', 'cpi_9606.ENSP00000320025', 'f_610'], ['f_430', 'cpi_9606.ENSP00000344193', 'cpi_9606.ENSP00000267163', 'f_425', 'cpi_9606.ENSP00000325822'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000351209', 'f_157'], ['f_337', 'cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000296046', 'f_624', 'cpi_9606.ENSP00000262948'], ['f_560', 'cpi_9606.ENSP00000364731', 'cpi_9606.ENSP00000278616', 'cpi_9606.ENSP00000335657', 'f_805'], ['f_206', 'cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000321106', 'f_458', 'cpi_9606.ENSP00000311028'], ['f_259', 'cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000307014', 'cpi_9606.ENSP00000320401', 'f_367'], ['f_437', 'cpi_9606.ENSP00000330484', 'cpi_9606.ENSP00000407375', 'f_803', 'f_363'], ['f_418', 'cpi_9606.ENSP00000293190', 'cpi_9606.ENSP00000358903', 'f_700', 'cpi_9606.ENSP00000366506'], ['f_10', 'cpi_9606.ENSP00000302441', 'cpi_9606.ENSP00000359663', 'f_721', 'f_200'], ['f_356', 'cpi_9606.ENSP00000433821', 'cpi_9606.ENSP00000270776', 'cpi_9606.ENSP00000310305', 'f_301'], ['f_755', 'cpi_9606.ENSP00000383558', 'cpi_9606.ENSP00000219919', 'f_652', 'cpi_9606.ENSP00000293745'], ['f_284', 'cpi_9606.ENSP00000324105', 'cpi_9606.ENSP00000221515', 'cpi_9606.ENSP00000318822', 'f_260'], ['f_798', 'cpi_9606.ENSP00000327801', 'f_485', 'cpi_9606.ENSP00000304895', 'f_364'], ['f_655', 'cpi_9606.ENSP00000219700', 'cpi_9606.ENSP00000359635', 'cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000367309'], ['f_377', 'cpi_9606.ENSP00000378699', 'cpi_9606.ENSP00000362036', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000267843'], ['f_38', 'cpi_9606.ENSP00000387662', 'cpi_9606.ENSP00000387683', 'f_737', 'cpi_9606.ENSP00000428340'], ['f_657', 'cpi_9606.ENSP00000373477', 'cpi_9606.ENSP00000356671', 'cpi_9606.ENSP00000410076', 'f_630'], ['f_688', 'cpi_9606.ENSP00000264705', 'cpi_9606.ENSP00000264657', 'cpi_9606.ENSP00000328973', 'f_612'], ['f_150', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000252029', 'cpi_9606.ENSP00000364802', 'cpi_9606.ENSP00000380247'], ['f_574', 'cpi_9606.ENSP00000318868', 'cpi_9606.ENSP00000264867', 'f_397', 'cpi_9606.ENSP00000325120'], ['f_710', 'cpi_9606.ENSP00000164139', 'cpi_9606.ENSP00000300151', 'cpi_9606.ENSP00000355920', 'cpi_9606.ENSP00000329623'], ['f_495', 'cpi_9606.ENSP00000332549', 'cpi_9606.ENSP00000305221', 'f_563', 'cpi_9606.ENSP00000292513'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000311165', 'f_621', 'cpi_9606.ENSP00000430432', 'f_694'], ['f_597', 'cpi_9606.ENSP00000265171', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000356694', 'cpi_9606.ENSP00000336630'], ['f_734', 'cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000394932', 'f_532'], ['f_487', 'cpi_9606.ENSP00000252321', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000256383', 'f_761'], ['f_633', 'cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000264498'], ['f_779', 'cpi_9606.ENSP00000234111', 'cpi_9606.ENSP00000454071', 'cpi_9606.ENSP00000362353', 'f_658'], ['f_442', 'cpi_9606.ENSP00000261733', 'cpi_9606.ENSP00000414303', 'cpi_9606.ENSP00000304915', 'cpi_9606.ENSP00000308774'], ['f_450', 'cpi_9606.ENSP00000274026', 'cpi_9606.ENSP00000331602', 'cpi_9606.ENSP00000285979', 'f_756'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000265572', 'cpi_9606.ENSP00000364805', 'f_527', 'cpi_9606.ENSP00000362513'], ['f_546', 'cpi_9606.ENSP00000341828', 'cpi_9606.ENSP00000263431', 'cpi_9606.ENSP00000230671', 'f_661'], ['f_592', 'cpi_9606.ENSP00000011292', 'cpi_9606.ENSP00000379086', 'f_713', 'cpi_9606.ENSP00000310928'], ['f_507', 'cpi_9606.ENSP00000220809', 'f_824', 'cpi_9606.ENSP00000356198', 'cpi_9606.ENSP00000347979'], ['f_188', 'cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000467494', 'cpi_9606.ENSP00000339260', 'f_152'], ['f_548', 'cpi_9606.ENSP00000313490', 'cpi_9606.ENSP00000391826', 'f_457', 'cpi_9606.ENSP00000327652'], ['f_821', 'cpi_9606.ENSP00000352516', 'cpi_9606.ENSP00000261196', 'cpi_9606.ENSP00000303325', 'f_531'], ['f_542', 'cpi_9606.ENSP00000260102', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000359532', 'cpi_9606.ENSP00000384273'], ['f_545', 'cpi_9606.ENSP00000380514', 'cpi_9606.ENSP00000354558', 'cpi_9606.ENSP00000254488', 'f_544'], ['f_502', 'cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000251566', 'cpi_9606.ENSP00000054668', 'cpi_9606.ENSP00000388648'], ['f_664', 'cpi_9

🔄 Processing features: 100%|██████████| 1607/1607 [06:52<00:00,  3.90feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'cpi_9606.ENSP00000301634', 'cpi_9606.ENSP00000359793', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000358595'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000356094', 'cpi_9606.ENSP00000355629'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000304822', 'cpi_9606.ENSP00000367848'], ['cpi_9606.ENSP00000311032', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000299847'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000359353', 'cpi_9606.ENSP00000332296'], ['cpi_9606.ENSP00000360372', 'cpi_9606.ENSP00000309818', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000261799', 'cpi_9606.ENSP00000267119'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000301891', 'cpi_9606.ENSP00000261937', 'cpi_9606.ENSP00000395653'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000360773', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000299178'], ['cpi_9606.ENSP00000231509', 'cpi_9606.ENSP00000277010', 'cpi_9606.ENSP00000367102', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000351957'], ['cpi_9606.ENSP00000265724', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000359532', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000295454'], ['cpi_9606.ENSP00000367959', 'cpi_9606.ENSP00000337335', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000267101', 'cpi_9606.ENSP00000264318'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000374323', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000312664'], ['cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000366506', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000348897'], ['cpi_9606.ENSP00000369960', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000292427'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000467676', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000389414'], ['cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000266376', 'cpi_9606.ENSP00000316786', 'cpi_9606.ENSP00000358548', 'cpi_9606.ENSP00000377947'], ['cpi_9606.ENSP00000264381', 'cpi_9606.ENSP00000319788', 'cpi_9606.ENSP00000417229', 'cpi_9606.ENSP00000342235', 'cpi_9606.ENSP00000261693'], ['cpi_9606.ENSP00000272190', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000354476', 'cpi_9606.ENSP00000275525', 'cpi_9606.ENSP00000274547'], ['cpi_9606.ENSP00000337450', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000364802', 'cpi_9606.ENSP00000378517'], ['cpi_9606.ENSP00000260433', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000257290', 'cpi_9606.ENSP00000430684', 'cpi_9606.ENSP00000298472'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000262441', 'cpi_9606.ENSP00000362649', 'cpi_9606.ENSP00000279178', 'cpi_9606.ENSP00000389338'], ['cpi_9606.ENSP00000258743', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000326219', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000241453'], ['cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000263321', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000361666', 'cpi_9606.ENSP00000292095'], ['cpi_9606.ENSP00000270349', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000326119', 'cpi_9606.ENSP00000262367'], ['cpi_9606.ENSP00000305372', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000283635'], ['cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000414334', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000334198'], ['cpi_9606.ENSP00000270202', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000303424', 'cpi_9606.ENSP00000333212'], ['cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000363822', 'cpi_9606.ENSP00000299267', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000251535'], ['cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000370381', 'cpi_9606.ENSP00000308165'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000451040'], ['cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000414303', 'cpi_9606.ENSP00000347942', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000344352'], ['cpi_9606.ENSP00000356438', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000394936', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000381097'], ['cpi_9606.ENSP00000337949', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000428340', 'cpi_9606.ENSP00000295491'], ['cpi_9606.ENSP00000297494', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000301178', 'cpi_9606.ENSP00000387946'], ['cpi_9606.ENSP00000280155', 'cpi_9606.ENSP00000354612', 'cpi_9606.ENSP00000216037', 'cpi_9606.ENSP00000343040', 'cpi_9606.ENSP00000447149'], ['cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000471569', 'cpi_9606.ENSP00000252809'], ['cpi_9606.ENSP00000316244', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000221972', 'cpi_9606.ENSP00000307599'], ['cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000225474', 'cpi_9606.ENSP00000353292', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000331912'], ['cpi_9606.ENSP00000258400', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000312455', 'cpi_9606.ENSP00000361206'], ['cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000233242', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000372023', 'cpi_9606.ENSP00000308774'], ['cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000260356', 'cpi_9606.ENSP00000262888', 'cpi_9606.ENSP00000410294'], ['cpi_9606.ENSP00000354859', 'cpi_9606.ENSP00000366084', 'cpi_9606.ENSP00000344192', 'cpi_9606.ENSP00000362036', 'cpi_9606.ENSP00000263126'], ['cpi_9606.ENSP00000295897', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000242057', 'cpi_9606.ENSP00000457706', 'cpi_9606.ENSP00000356832'], ['cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000252723', 'cpi_9606.ENSP00000419782', 'cpi_9606.ENSP00000303540'], ['cpi_9606.ENSP00000269305', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000258749', 'cpi_9606.ENSP00000367851', 'cpi_9606.ENSP00000307014'], ['cpi_9606.ENSP00000398698', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000349577', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000289753'], ['cpi_9606.ENSP00000358963', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000219700', 'cpi_9606.ENSP00000286301', 'cpi_9606.ENSP00000348069'], ['cpi_9606.ENSP00000330237', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000264637', 'cpi_9606.ENSP00000411593'], ['cpi_9606.ENSP00000215832', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000259396', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000309493'], ['cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000329623', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000368766', 'cpi_9606.ENSP00000345659'], ['cpi_9606.ENSP00000386069', 'cpi_9606.ENSP00000359478', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000359096'], ['cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000356954', 'cpi_9606.ENSP00000360493', 'cpi_9606.ENSP00000262461'], ['cpi_9606.ENSP00000306512', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000349252', 'cpi_9606.ENSP00000470087', 'cpi_9606.ENSP00000361359'], ['cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000357283', 'cpi_9606.ENSP00000351209', 'cpi_9606.ENSP00000409378'], ['cpi_9606.ENSP00000355759', 'cpi_9606.ENSP00000374467', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000327652', 'cpi_9606.ENSP00000311095'], ['cpi_9606.ENSP00000411532', 'cpi_9606.ENSP00000231454', 'cpi_9606.ENSP00000261196', 'cpi_9606.ENSP00000267843', 'cpi_9606.ENSP00000276198'], ['cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000398632', 'cpi_9606.ENSP00000300061', 'cpi_9606.ENSP00000256958', 'cpi_9606.ENSP00000387281'], ['cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000381333', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000310928', 'cpi_9606.ENSP00000402152'], ['cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000273550', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000222330', 'cpi_9606.ENSP00000368253'], ['cpi_9606.ENSP00000263025', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000216962', 'cpi_9606.ENSP00000309124'], ['cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000282561', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000445340'], ['cpi_9606.ENSP00000308541', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000376943', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000297350'], ['cpi_9606.ENSP00000306245', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000332369', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000358784'], ['cpi_9606.ENSP00000302150', 'cpi_9606.ENSP00000270474', 'cpi_9606.ENSP00000259089', 'cpi_9606.ENSP00000318822', 'cpi_9606.ENSP00000264867'], ['cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000317379', 'cpi_9606.ENSP00000263923'], ['cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000221515', 'cpi_9606.ENSP00000388648', 'cpi_9606.ENSP00000322617'], ['cpi_9606.ENSP00000252945', 'cpi_9606.ENSP00000340943', 'cpi_9606.ENSP00000323568', 'cpi_9606.ENSP00000343477', 'cpi_9606.ENSP00000356436'], ['cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000304845', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000274026', 'cpi_9606.ENSP00000296871'], ['cpi_9606.ENSP00000237612', 'cpi_9606.ENSP00000464149', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000200676'], ['cpi_9606.ENSP00000287820', 'cpi_9606.ENSP00000378699', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000341885', 'cpi_9606.ENSP00000307235'], ['cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000252321', 'cpi_9606.ENSP00000294728', 'cpi_9606.ENSP00000373169', 'cpi_9606.ENSP00000370254'], ['cpi_9606.ENSP00000412237', 'cpi_9606.ENSP00000216465', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000360967'], ['cpi_9606.ENSP00000219070', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000176183', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000270776'], ['cpi_9606.ENSP00000387662', 'cpi_9606.ENSP00000303174', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000276449'], ['cpi_9606.ENSP00000306662', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000293288', 'cpi_9606.ENSP00000295834', 'cpi_9606.ENSP00000291700'], ['cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000463999', 'cpi_9606.ENSP00000354394'], ['cpi_9606.ENSP00000220764', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000313661', 'cpi_9606.ENSP00000226574', 'cpi_9606.ENSP00000255465'], ['cpi_9606.ENSP00000361405', 'cpi_9606.ENSP00000355325', 'cpi_9606.ENSP00000365663', 'cpi_9606.ENSP00000260010', 'cpi_9606.ENSP00000282397'], ['cpi_9606.ENSP00000270142', 'cpi_9606.ENSP00000400175', 'cpi_9606.ENSP00000329357', 'cpi_9606.ENSP00000292513', 'cpi_9606.ENSP00000338548'], ['cpi_9606.ENSP00000225831', 'cpi_9606.ENSP00000248553', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000353915', 'cpi_9606.ENSP00000370473'], ['cpi_9606.ENSP00000344456', 'cpi_9606.ENSP00000320935', 'cpi_9606.ENSP00000448059', 'cpi_9606.ENSP00000333496', 'cpi_9606.ENSP00000356694'], ['cpi_9606.ENSP00000394624', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000309757'], ['cpi_9606.ENSP00000327251', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000306129', 'cpi_9606.ENSP00000302111'], ['cpi_9606.ENSP00000284981', 'cpi_9606.ENSP00000384273', 'cpi_9606.ENSP00000353791', 'cpi_9606.ENSP00000340820', 'cpi_9606.ENSP00000300900'], ['cpi_9606.ENSP00000358327', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000261465', 'cpi_9606.ENSP00000296674', 'cpi_9606.ENSP00000339527'], ['cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000262948', 'cpi_9606.ENSP00000385806', 'cpi_9606.ENSP00000307766', 'cpi_9606.ENSP00000266682'], ['cpi_9606.ENSP00000368438', 'cpi_9606.ENSP00000355930', 'cpi_9606.ENSP00000355657', 'cpi_9606.ENSP00000274793', 'cpi_9606.ENSP00000263980'], ['cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000321584', 'cpi_9606.ENSP00000256010', 'cpi_9606.ENSP00000341045', 'cpi_9606.ENSP00000254488'], ['cpi_9606.ENSP00000352835', 'cpi_9606.ENSP00000264657', 'cpi_9606.ENSP00000303452', 'cpi_9606.ENSP00000285979', 'cpi_9606.ENSP00000323549'], ['cpi_9606.ENSP00000340684', 'cpi_9606.ENSP00000231449', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000382659'], ['cpi_9606.ENSP00000263341', 'cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000342560', 'cpi_9606.ENSP00000427514'], ['cpi_9606.ENSP00000264832', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000288135', 'cpi_9606.ENSP00000386229', 'cpi_9606.ENSP00000305302'], ['cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000241261', 'cpi_9606.ENSP00000398655', 'cpi_9606.ENSP00000366307', 'cpi_9606.ENSP00000290349'], ['cpi_9606.ENSP00000234111', 'cpi_9606.ENSP00000259486', 'cpi_9606.ENSP00000358511', 'cpi_9606.ENSP00000347979', 'cpi_9606.ENSP00000358903'], ['cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000354558', 'cpi_9606.ENSP00000346598', 'cpi_9606.ENSP00000305221', 'cpi_9606.ENSP00000307445'], ['cpi_9606.ENSP00000337459', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000196551', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000312029'], ['cpi_9606.ENSP00000369050', 'cpi_9606.ENSP00000362810', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000410076', 'cpi_9606.ENSP00000386171'], ['cpi_9606.ENSP00000290866', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000362353', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000459962'], ['cpi_9606.ENSP00000369647', 'cpi_9606.ENSP00000252486', 'cpi_9606.ENSP00000353427', 'cpi_9606.ENSP00000176763', 'cpi_9606.ENSP00000379339'], ['cpi_9606.ENSP00000265572', 'cpi_9606.ENSP00000275300', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000419692', 'cpi_9606.ENSP00000352584'], ['cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000321988', 'cpi_9606.ENSP00000331358', 'cpi_9606.ENSP00000239849', 'cpi_9606.ENSP00000311028'], ['cpi_9606.ENSP00000216117', 'cpi_9606.ENSP00000359899', 'cpi_9606.ENSP00000318646', 'cpi_9606.ENSP00000251566', 'cpi_9606.ENSP00000330199'], ['cpi_9606.ENSP00000317842', 'cpi_9606.ENSP00000233146', 'cpi_9606.ENSP00000277120', 'cpi_9606.ENSP00000287936', 'cpi_9606.ENSP00000428924'], ['cpi_9606.ENSP00000331746', 'cpi_9606.ENSP00000264162', 'cpi_9606.ENSP00000264498', 'cpi_9606.ENSP00000320709', 'cpi_9606.ENSP00000353878'], ['cpi_9606.ENSP00000309845', 'cpi_9606.ENSP00000301146', 'cpi_9606.ENSP00000291294', 'cpi_9606.ENSP00000297268', 'cpi_9606.ENSP00000330393'], ['cpi_9606.ENSP00000260970', 'cpi_9606.ENSP00000355920', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000346298', 'cpi_9606.ENSP00000217426'], ['cpi_9606.ENSP00000356825', 'cpi_9606.ENSP00000231228', 'cpi_9606.ENSP00000407375', 'cpi_9606.ENSP00000252029', 'cpi_9606.ENSP00000343838'], ['cpi_9606.ENSP00000266970', 'cpi_9606.ENSP00000303522', 'cpi_9606.ENSP00000337773', 'cpi_9606.ENSP00000346148', 'cpi_9606.ENSP00000338627'], ['cpi_9606.ENSP00000322924', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000234389', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000222002'], ['cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000324270', 'cpi_9606.ENSP00000232219', 'cpi_9606.ENSP00000344674', 'cpi_9606.ENSP00000393312'], ['cpi_9606.ENSP00000272298', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000336630', 'cpi_9606.ENSP00000454071', 'cpi_9606.ENSP00000418960'], ['cpi_9606.ENSP00000378323', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000287907', 'cpi_9606.ENSP00000354107', 'cpi_9606.ENSP00000358424'], ['cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000295598', 'cpi_9606.ENSP00000360973', 'cpi_9606.ENSP00000254810', 'cpi_9606.ENSP00000219919'], ['cpi_9606.ENSP00000370571', 'cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000341189', 'cpi_9606.ENSP00000433821', 'cpi_9606.ENSP00000355317'], ['cpi_9606.ENSP00000338018', 'cpi_9606.ENSP00000354610', 'cpi_9606.ENSP00000335544', 'cpi_9606.ENSP00000268053', 'cpi_9606.ENSP00000304915'], ['cpi_9606.ENSP00000305742', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000225927', 'cpi_9606.ENSP00000365380', 'cpi_9606.ENSP00000310447'], ['cpi_9606.ENSP00000349467', 'cpi_9606.ENSP00000244741', 'cpi_9606.ENSP00000308549', 'cpi_9606.ENSP00000277508', 'cpi_9606.ENSP00000343204'], ['cpi_9606.ENSP00000315644', 'cpi_9606.ENSP00000312652', 'cpi_9606.ENSP00000302846', 'cpi_9606.ENSP00000320401', 'cpi_9606.ENSP00000364805'], ['cpi_9606.ENSP00000218548', 'cpi_9606.ENSP00000360266', 'cpi_9606.ENSP00000365016', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000358730'], ['cpi_9606.ENSP00000345096', 'cpi_9606.ENSP00000262735', 'cpi_9606.ENSP00000267377', 'cpi_9606.ENSP00000225964', 'cpi_9606.ENSP00000301633'], ['cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000375066', 'cpi_9606.ENSP00000304895', 'cpi_9606.ENSP00000368632', 'cpi_9606.ENSP00000356671'], ['cpi_9606.ENSP00000274353', 'cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000264896', 'cpi_9606.ENSP00000380252', 'cpi_9606.ENSP00000359635'], ['cpi_9606.ENSP00000353731', 'cpi_9606.ENSP00000226413', 'cpi_9606.ENSP00000296122', 'cpi_9606.ENSP00000301141', 'cpi_9606.ENSP00000270625'], ['cpi_9606.ENSP00000225275', 'cpi_9606.ENSP00000276571', 'cpi_9606.ENSP00000362513', 'cpi_9606.ENSP00000295256', 'cpi_9606.ENSP00000278616'], ['cpi_9606.ENSP00000367309', 'cpi_9606.ENSP00000332816', 'cpi_9606.ENSP00000239938', 'cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000394033'], ['cpi_9606.ENSP00000260302', 'cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000309103', 'cpi_9606.ENSP00000351885', 'cpi_9606.ENSP00000220616'], ['cpi_9606.ENSP00000262623', 'cpi_9606.ENSP00000225577', 'cpi_9606.ENSP00000362508', 'cpi_9606.ENSP00000350198', 'cpi_9606.ENSP00000263464'], ['cpi_9606.ENSP00000357669', 'cpi_9606.ENSP00000287641', 'cpi_9606.ENSP00000265723', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000308845'], ['cpi_9606.ENSP00000229135', 'cpi_9606.ENSP00000362401', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000356150'], ['cpi_9606.ENSP00000296545', 'cpi_9606.ENSP00000327431', 'cpi_9606.ENSP00000355778', 'cpi_9606.ENSP00000333534', 'cpi_9606.ENSP00000333821'], ['cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000393333', 'cpi_9606.ENSP00000308032', 'cpi_9606.ENSP00000429374', 'cpi_9606.ENSP00000285238'], ['cpi_9606.ENSP00000236850', 'cpi_9606.ENSP00000280357', 'cpi_9606.ENSP00000451030', 'cpi_9606.ENSP00000387683', 'cpi_9606.ENSP00000251453'], ['cpi_9606.ENSP00000257497', 'cpi_9606.ENSP00000314508', 'cpi_9606.ENSP00000296522', 'cpi_9606.ENSP00000368104', 'cpi_9606.ENSP00000276431'], ['cpi_9606.ENSP00000285379', 'cpi_9606.ENSP00000386884', 'cpi_9606.ENSP00000256383', 'cpi_9606.ENSP00000368752', 'cpi_9606.ENSP00000388825'], ['cpi_9606.ENSP00000354850', 'cpi_9606.ENSP00000379213', 'cpi_9606.ENSP00000260630', 'cpi_9606.ENSP00000370129', 'cpi_9606.ENSP00000319591'], ['cpi_9606.ENSP00000223095', 'cpi_9606.ENSP00000362924', 'cpi_9606.ENSP00000420168', 'cpi_9606.ENSP00000217305', 'cpi_9606.ENSP00000348645'], ['cpi_9606.ENSP00000234961', 'cpi_9606.ENSP00000319814', 'cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000253727', 'cpi_9606.ENSP00000357981'], ['cpi_9606.ENSP00000386284', 'cpi_9606.ENSP00000368683', 'cpi_9606.ENSP00000260227', 'cpi_9606.ENSP00000341828', 'cpi_9606.ENSP00000427562'], ['cpi_9606.ENSP00000368305', 'cpi_9606.ENSP00000242152', 'cpi_9606.ENSP00000269571', 'cpi_9606.ENSP00000435777', 'cpi_9606.ENSP00000354569'], ['cpi_9606.ENSP00000234310', 'cpi_9606.ENSP00000379140', 'cpi_9606.ENSP00000265403', 'cpi_9606.ENSP00000351908', 'cpi_9606.ENSP00000417281'], ['cpi_9606.ENSP00000239223', 'cpi_9606.ENSP00000297469', 'cpi_9606.ENSP00000311469', 'cpi_9606.ENSP0000043

🔄 Processing features: 100%|██████████| 1607/1607 [06:50<00:00,  3.92feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'cpi_9606.ENSP00000309818', 'cpi_9606.ENSP00000301634', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000332296'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000299178', 'cpi_9606.ENSP00000261937', 'cpi_9606.ENSP00000430684'], ['cpi_9606.ENSP00000360372', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000355629', 'cpi_9606.ENSP00000414334'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000360773', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000356094', 'cpi_9606.ENSP00000295452'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000367848', 'cpi_9606.ENSP00000319788'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000467676'], ['cpi_9606.ENSP00000265724', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000359353', 'cpi_9606.ENSP00000294954'], ['cpi_9606.ENSP00000311032', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000359793'], ['cpi_9606.ENSP00000367959', 'cpi_9606.ENSP00000337335', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000267101', 'cpi_9606.ENSP00000427514'], ['cpi_9606.ENSP00000369960', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000367102', 'cpi_9606.ENSP00000409007'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000395653'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000349252', 'cpi_9606.ENSP00000266376', 'cpi_9606.ENSP00000417229'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000295491', 'cpi_9606.ENSP00000295454'], ['cpi_9606.ENSP00000270349', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000301891', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000257290'], ['cpi_9606.ENSP00000231509', 'cpi_9606.ENSP00000382659', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000251535', 'cpi_9606.ENSP00000261799'], ['cpi_9606.ENSP00000272190', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000354476', 'cpi_9606.ENSP00000275525', 'cpi_9606.ENSP00000374323'], ['cpi_9606.ENSP00000264381', 'cpi_9606.ENSP00000389338', 'cpi_9606.ENSP00000279178', 'cpi_9606.ENSP00000342235', 'cpi_9606.ENSP00000259396'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000362353', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000216037'], ['cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000263321', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000320935', 'cpi_9606.ENSP00000274547'], ['cpi_9606.ENSP00000305372', 'cpi_9606.ENSP00000277010', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000233242', 'cpi_9606.ENSP00000283635'], ['cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000370381', 'cpi_9606.ENSP00000258749'], ['cpi_9606.ENSP00000260433', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000381097', 'cpi_9606.ENSP00000348069', 'cpi_9606.ENSP00000298472'], ['cpi_9606.ENSP00000258743', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000259089', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000352900'], ['cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000299267'], ['cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000410294', 'cpi_9606.ENSP00000262888'], ['cpi_9606.ENSP00000297494', 'cpi_9606.ENSP00000394936', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000335592'], ['cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000225474', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000353915'], ['cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000242057'], ['cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000363822', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000261196'], ['cpi_9606.ENSP00000337450', 'cpi_9606.ENSP00000262441', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000344674', 'cpi_9606.ENSP00000286301'], ['cpi_9606.ENSP00000270202', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000307599', 'cpi_9606.ENSP00000303424', 'cpi_9606.ENSP00000305422'], ['cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000282753', 'cpi_9606.ENSP00000312664', 'cpi_9606.ENSP00000344192', 'cpi_9606.ENSP00000471569'], ['cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000316786', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000301178'], ['cpi_9606.ENSP00000280155', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000361206'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000301974', 'cpi_9606.ENSP00000353427', 'cpi_9606.ENSP00000304822', 'cpi_9606.ENSP00000293288'], ['cpi_9606.ENSP00000258400', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000302111', 'cpi_9606.ENSP00000353292', 'cpi_9606.ENSP00000343040'], ['cpi_9606.ENSP00000398698', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000387946'], ['cpi_9606.ENSP00000337949', 'cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000326119', 'cpi_9606.ENSP00000221972', 'cpi_9606.ENSP00000331912'], ['cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000357981', 'cpi_9606.ENSP00000463999', 'cpi_9606.ENSP00000264867'], ['cpi_9606.ENSP00000316244', 'cpi_9606.ENSP00000359478', 'cpi_9606.ENSP00000362036', 'cpi_9606.ENSP00000367851', 'cpi_9606.ENSP00000360493'], ['cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000237612', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000361359', 'cpi_9606.ENSP00000359100'], ['cpi_9606.ENSP00000354859', 'cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000308165'], ['cpi_9606.ENSP00000366506', 'cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000200676'], ['cpi_9606.ENSP00000356438', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000470087', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000264637'], ['cpi_9606.ENSP00000215832', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000326219', 'cpi_9606.ENSP00000261693', 'cpi_9606.ENSP00000451040'], ['cpi_9606.ENSP00000368766', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000365380', 'cpi_9606.ENSP00000410076'], ['cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000294728', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000347942'], ['cpi_9606.ENSP00000295897', 'cpi_9606.ENSP00000378517', 'cpi_9606.ENSP00000332369', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000346534'], ['cpi_9606.ENSP00000263025', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000341828', 'cpi_9606.ENSP00000260010', 'cpi_9606.ENSP00000376178'], ['cpi_9606.ENSP00000269305', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000389414', 'cpi_9606.ENSP00000311028', 'cpi_9606.ENSP00000350198'], ['cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000226574', 'cpi_9606.ENSP00000263923'], ['cpi_9606.ENSP00000306512', 'cpi_9606.ENSP00000264162', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000252809', 'cpi_9606.ENSP00000306662'], ['cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000361666', 'cpi_9606.ENSP00000303830', 'cpi_9606.ENSP00000329357', 'cpi_9606.ENSP00000233146'], ['cpi_9606.ENSP00000358963', 'cpi_9606.ENSP00000315644', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000256383', 'cpi_9606.ENSP00000176763'], ['cpi_9606.ENSP00000237014', 'cpi_9606.ENSP00000354558', 'cpi_9606.ENSP00000296871', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000276198'], ['cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000234111', 'cpi_9606.ENSP00000256958', 'cpi_9606.ENSP00000346598', 'cpi_9606.ENSP00000312455'], ['cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000298171', 'cpi_9606.ENSP00000274793', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000368253'], ['cpi_9606.ENSP00000330237', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000290349'], ['cpi_9606.ENSP00000354612', 'cpi_9606.ENSP00000339527', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000288602'], ['cpi_9606.ENSP00000306245', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000376943', 'cpi_9606.ENSP00000270625', 'cpi_9606.ENSP00000323568'], ['cpi_9606.ENSP00000386069', 'cpi_9606.ENSP00000345096', 'cpi_9606.ENSP00000358548', 'cpi_9606.ENSP00000300061', 'cpi_9606.ENSP00000363812'], ['cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000318822', 'cpi_9606.ENSP00000262367', 'cpi_9606.ENSP00000454071'], ['cpi_9606.ENSP00000302150', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000356954', 'cpi_9606.ENSP00000394033', 'cpi_9606.ENSP00000333212'], ['cpi_9606.ENSP00000387281', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000354610', 'cpi_9606.ENSP00000309968', 'cpi_9606.ENSP00000231454'], ['cpi_9606.ENSP00000308541', 'cpi_9606.ENSP00000282561', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000381333', 'cpi_9606.ENSP00000222330'], ['cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000231228', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000263980', 'cpi_9606.ENSP00000352702'], ['cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000353878', 'cpi_9606.ENSP00000263126', 'cpi_9606.ENSP00000260649', 'cpi_9606.ENSP00000312029'], ['cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000341045', 'cpi_9606.ENSP00000356150', 'cpi_9606.ENSP00000176183'], ['cpi_9606.ENSP00000225831', 'cpi_9606.ENSP00000364802', 'cpi_9606.ENSP00000289753', 'cpi_9606.ENSP00000372023', 'cpi_9606.ENSP00000466799'], ['cpi_9606.ENSP00000270142', 'cpi_9606.ENSP00000373169', 'cpi_9606.ENSP00000297350', 'cpi_9606.ENSP00000457706', 'cpi_9606.ENSP00000366307'], ['cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000329623', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000429374'], ['cpi_9606.ENSP00000252945', 'cpi_9606.ENSP00000340943', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000358784', 'cpi_9606.ENSP00000252486'], ['cpi_9606.ENSP00000361405', 'cpi_9606.ENSP00000448059', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000357283'], ['cpi_9606.ENSP00000355759', 'cpi_9606.ENSP00000374467', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000309124', 'cpi_9606.ENSP00000355317'], ['cpi_9606.ENSP00000344456', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000295834', 'cpi_9606.ENSP00000360973', 'cpi_9606.ENSP00000221515'], ['cpi_9606.ENSP00000327652', 'cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000344352'], ['cpi_9606.ENSP00000464149', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000311095', 'cpi_9606.ENSP00000445340', 'cpi_9606.ENSP00000351885'], ['cpi_9606.ENSP00000219070', 'cpi_9606.ENSP00000340684', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000220616', 'cpi_9606.ENSP00000447149'], ['cpi_9606.ENSP00000220764', 'cpi_9606.ENSP00000260356', 'cpi_9606.ENSP00000313661', 'cpi_9606.ENSP00000369757', 'cpi_9606.ENSP00000262461'], ['cpi_9606.ENSP00000414303', 'cpi_9606.ENSP00000304915', 'cpi_9606.ENSP00000349576', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000358903'], ['cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000366084', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000308774'], ['cpi_9606.ENSP00000387662', 'cpi_9606.ENSP00000386284', 'cpi_9606.ENSP00000343477', 'cpi_9606.ENSP00000288135', 'cpi_9606.ENSP00000231751'], ['cpi_9606.ENSP00000327251', 'cpi_9606.ENSP00000267119', 'cpi_9606.ENSP00000267843', 'cpi_9606.ENSP00000428340', 'cpi_9606.ENSP00000349577'], ['cpi_9606.ENSP00000412237', 'cpi_9606.ENSP00000327431', 'cpi_9606.ENSP00000343204', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000306129'], ['cpi_9606.ENSP00000290866', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000302811', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000353791'], ['cpi_9606.ENSP00000264832', 'cpi_9606.ENSP00000295598', 'cpi_9606.ENSP00000307235', 'cpi_9606.ENSP00000354394', 'cpi_9606.ENSP00000287907'], ['cpi_9606.ENSP00000394624', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000328173', 'cpi_9606.ENSP00000296122'], ['cpi_9606.ENSP00000284981', 'cpi_9606.ENSP00000304895', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000393312'], ['cpi_9606.ENSP00000223095', 'cpi_9606.ENSP00000320866', 'cpi_9606.ENSP00000252723', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000307014'], ['cpi_9606.ENSP00000358327', 'cpi_9606.ENSP00000296522', 'cpi_9606.ENSP00000317379', 'cpi_9606.ENSP00000234961', 'cpi_9606.ENSP00000255465'], ['cpi_9606.ENSP00000368438', 'cpi_9606.ENSP00000275216', 'cpi_9606.ENSP00000276449', 'cpi_9606.ENSP00000355657', 'cpi_9606.ENSP00000248553'], ['cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000252029', 'cpi_9606.ENSP00000330393', 'cpi_9606.ENSP00000308549', 'cpi_9606.ENSP00000359663'], ['cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000246337', 'cpi_9606.ENSP00000359635', 'cpi_9606.ENSP00000346148', 'cpi_9606.ENSP00000365775'], ['cpi_9606.ENSP00000411532', 'cpi_9606.ENSP00000355930', 'cpi_9606.ENSP00000419692', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000260970'], ['cpi_9606.ENSP00000354511', 'cpi_9606.ENSP00000278616', 'cpi_9606.ENSP00000292513', 'cpi_9606.ENSP00000351209', 'cpi_9606.ENSP00000398632'], ['cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000225927', 'cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000307766', 'cpi_9606.ENSP00000434364'], ['cpi_9606.ENSP00000263341', 'cpi_9606.ENSP00000352608', 'cpi_9606.ENSP00000254810', 'cpi_9606.ENSP00000451605', 'cpi_9606.ENSP00000178638'], ['cpi_9606.ENSP00000331746', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000303174', 'cpi_9606.ENSP00000262948', 'cpi_9606.ENSP00000339260'], ['cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000322924', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000264657'], ['cpi_9606.ENSP00000304845', 'cpi_9606.ENSP00000350348', 'cpi_9606.ENSP00000364805', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000309757'], ['cpi_9606.ENSP00000265572', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000380252', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000428924'], ['cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000303522', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000348461', 'cpi_9606.ENSP00000268251'], ['cpi_9606.ENSP00000317842', 'cpi_9606.ENSP00000368752', 'cpi_9606.ENSP00000336630', 'cpi_9606.ENSP00000225964', 'cpi_9606.ENSP00000358595'], ['cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000359899', 'cpi_9606.ENSP00000251453', 'cpi_9606.ENSP00000347979', 'cpi_9606.ENSP00000270474'], ['cpi_9606.ENSP00000337459', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000435777', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000356694'], ['cpi_9606.ENSP00000369050', 'cpi_9606.ENSP00000362401', 'cpi_9606.ENSP00000379339', 'cpi_9606.ENSP00000352584', 'cpi_9606.ENSP00000232219'], ['cpi_9606.ENSP00000218548', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000358511', 'cpi_9606.ENSP00000362344'], ['cpi_9606.ENSP00000352835', 'cpi_9606.ENSP00000368683', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000419782', 'cpi_9606.ENSP00000351908'], ['cpi_9606.ENSP00000236850', 'cpi_9606.ENSP00000254488', 'cpi_9606.ENSP00000291294', 'cpi_9606.ENSP00000388648', 'cpi_9606.ENSP00000297268'], ['cpi_9606.ENSP00000305742', 'cpi_9606.ENSP00000287936', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000331358', 'cpi_9606.ENSP00000301146'], ['cpi_9606.ENSP00000262623', 'cpi_9606.ENSP00000360266', 'cpi_9606.ENSP00000365016', 'cpi_9606.ENSP00000261465', 'cpi_9606.ENSP00000358730'], ['cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000292896', 'cpi_9606.ENSP00000264818', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000342560'], ['cpi_9606.ENSP00000287820', 'cpi_9606.ENSP00000359910', 'cpi_9606.ENSP00000459962', 'cpi_9606.ENSP00000277120', 'cpi_9606.ENSP00000365663'], ['cpi_9606.ENSP00000369647', 'cpi_9606.ENSP00000241261', 'cpi_9606.ENSP00000262160', 'cpi_9606.ENSP00000385806', 'cpi_9606.ENSP00000266682'], ['cpi_9606.ENSP00000370571', 'cpi_9606.ENSP00000310928', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000435412', 'cpi_9606.ENSP00000267377'], ['cpi_9606.ENSP00000312652', 'cpi_9606.ENSP00000302846', 'cpi_9606.ENSP00000223366', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000309103'], ['cpi_9606.ENSP00000363868', 'cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000275300', 'cpi_9606.ENSP00000211287', 'cpi_9606.ENSP00000433821'], ['cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000231449', 'cpi_9606.ENSP00000330199', 'cpi_9606.ENSP00000196551', 'cpi_9606.ENSP00000384273'], ['cpi_9606.ENSP00000378323', 'cpi_9606.ENSP00000287641', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000305302', 'cpi_9606.ENSP00000400175'], ['cpi_9606.ENSP00000349467', 'cpi_9606.ENSP00000244741', 'cpi_9606.ENSP00000346298', 'cpi_9606.ENSP00000333821', 'cpi_9606.ENSP00000305221'], ['cpi_9606.ENSP00000260302', 'cpi_9606.ENSP00000367309', 'cpi_9606.ENSP00000378699', 'cpi_9606.ENSP00000296545', 'cpi_9606.ENSP00000356832'], ['cpi_9606.ENSP00000356022', 'cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000356671', 'cpi_9606.ENSP00000387683', 'cpi_9606.ENSP00000355778'], ['cpi_9606.ENSP00000275493', 'cpi_9606.ENSP00000349003', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000274026', 'cpi_9606.ENSP00000368104'], ['cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000262735', 'cpi_9606.ENSP00000311469', 'cpi_9606.ENSP00000304501', 'cpi_9606.ENSP00000268035'], ['cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000354107', 'cpi_9606.ENSP00000278175', 'cpi_9606.ENSP00000320401', 'cpi_9606.ENSP00000332816'], ['cpi_9606.ENSP00000357669', 'cpi_9606.ENSP00000297469', 'cpi_9606.ENSP00000360967', 'cpi_9606.ENSP00000228872', 'cpi_9606.ENSP00000318646'], ['cpi_9606.ENSP00000309845', 'cpi_9606.ENSP00000260630', 'cpi_9606.ENSP00000245457', 'cpi_9606.ENSP00000270776', 'cpi_9606.ENSP00000341885'], ['cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000244217', 'cpi_9606.ENSP00000427279', 'cpi_9606.ENSP00000338627', 'cpi_9606.ENSP00000264498'], ['cpi_9606.ENSP00000356825', 'cpi_9606.ENSP00000379213', 'cpi_9606.ENSP00000420168', 'cpi_9606.ENSP00000320709', 'cpi_9606.ENSP00000296674'], ['cpi_9606.ENSP00000216117', 'cpi_9606.ENSP00000362810', 'cpi_9606.ENSP00000346067', 'cpi_9606.ENSP00000355533', 'cpi_9606.ENSP00000362525'], ['cpi_9606.ENSP00000234310', 'cpi_9606.ENSP00000386884', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000252321', 'cpi_9606.ENSP00000280357'], ['cpi_9606.ENSP00000357204', 'cpi_9606.ENSP00000292303', 'cpi_9606.ENSP00000302967', 'cpi_9606.ENSP00000215659', 'cpi_9606.ENSP00000256119'], ['cpi_9606.ENSP00000229135', 'cpi_9606.ENSP00000384957', 'cpi_9606.ENSP00000285979', 'cpi_9606.ENSP00000272847', 'cpi_9606.ENSP00000265164'], ['cpi_9606.ENSP00000338548', 'cpi_9606.ENSP00000257497', 'cpi_9606.ENSP00000265723', 'cpi_9606.ENSP00000295400', 'cpi_9606.ENSP00000320171'], ['cpi_9606.ENSP00000262407', 'cpi_9606.ENSP00000273430', 'cpi_9606.ENSP00000263464', 'cpi_9606.ENSP00000362508', 'cpi_9606.ENSP00000321999'], ['cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000467494', 'cpi_9606.ENSP00000211122', 'cpi_9606.ENSP00000369654', 'cpi_9606.ENSP00000225577'], ['cpi_9606.ENSP00000318585', 'cpi_9606.ENSP00000307259', 'cpi_9606.ENSP00000407375', 'cpi_9606.ENSP00000341189', 'cpi_9606.ENSP00000367608'], ['cpi_9606.ENSP00000381607', 'cpi_9606.ENSP00000276571', 'cpi_9606.ENSP00000430432', 'cpi_9606.ENSP00000362513', 'cpi_9606.ENSP00000239849'], ['cpi_9606.ENSP00000321584', 'cpi_9606.ENSP00000217305', 'cpi_9606.ENSP00000386171', 'cpi_9606.ENSP00000264896', 'cpi_9606.ENSP00000355920'], ['cpi_9606.ENSP00000279387', 'cpi_9606.ENSP00000353483', 'cpi_9606.ENSP00000384708', 'cpi_9606.ENSP00000300151', 'cpi_9606.ENSP00000333534'], ['cpi_9606.ENSP00000266970', 'cpi_9606.ENSP00000324248', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP0000033

🔄 Processing features: 100%|██████████| 1607/1607 [06:50<00:00,  3.92feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'cpi_9606.ENSP00000326219', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000356094', 'cpi_9606.ENSP00000359424'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000355629', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000295452'], ['cpi_9606.ENSP00000360372', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000309818', 'cpi_9606.ENSP00000261937', 'cpi_9606.ENSP00000227758'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000261799', 'cpi_9606.ENSP00000430684', 'cpi_9606.ENSP00000367848'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000359353', 'cpi_9606.ENSP00000286479'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000257290', 'cpi_9606.ENSP00000332296', 'cpi_9606.ENSP00000265294'], ['cpi_9606.ENSP00000231509', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000347942'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000274547'], ['cpi_9606.ENSP00000265724', 'cpi_9606.ENSP00000374323', 'cpi_9606.ENSP00000304822', 'cpi_9606.ENSP00000337335', 'cpi_9606.ENSP00000299178'], ['cpi_9606.ENSP00000367959', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000267101', 'cpi_9606.ENSP00000200676', 'cpi_9606.ENSP00000352900'], ['cpi_9606.ENSP00000311032', 'cpi_9606.ENSP00000295454', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000395653'], ['cpi_9606.ENSP00000272190', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000275525', 'cpi_9606.ENSP00000354476', 'cpi_9606.ENSP00000241453'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000312664', 'cpi_9606.ENSP00000381097'], ['cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000282753', 'cpi_9606.ENSP00000344192', 'cpi_9606.ENSP00000326119', 'cpi_9606.ENSP00000342235'], ['cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000263321', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000414334', 'cpi_9606.ENSP00000367102'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000261196', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000412673'], ['cpi_9606.ENSP00000264381', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000216037', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000252809'], ['cpi_9606.ENSP00000270349', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000266376', 'cpi_9606.ENSP00000319788', 'cpi_9606.ENSP00000387946'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000298171', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000221972'], ['cpi_9606.ENSP00000260433', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000457706', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000308165'], ['cpi_9606.ENSP00000369960', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000260010'], ['cpi_9606.ENSP00000363822', 'cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000299267', 'cpi_9606.ENSP00000367851'], ['cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000370381', 'cpi_9606.ENSP00000360773'], ['cpi_9606.ENSP00000337450', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000362649', 'cpi_9606.ENSP00000286301', 'cpi_9606.ENSP00000389338'], ['cpi_9606.ENSP00000270202', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000394936', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000298472'], ['cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000277010', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000274545'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000296545', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000258749'], ['cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000261693', 'cpi_9606.ENSP00000225474'], ['cpi_9606.ENSP00000366506', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000283635'], ['cpi_9606.ENSP00000398698', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000301178', 'cpi_9606.ENSP00000264637', 'cpi_9606.ENSP00000357283'], ['cpi_9606.ENSP00000356438', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000242057'], ['cpi_9606.ENSP00000354612', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000346534'], ['cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000301891', 'cpi_9606.ENSP00000294728', 'cpi_9606.ENSP00000417229', 'cpi_9606.ENSP00000428340'], ['cpi_9606.ENSP00000258743', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000259089', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000279178'], ['cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000251535', 'cpi_9606.ENSP00000252723', 'cpi_9606.ENSP00000428924'], ['cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000302111', 'cpi_9606.ENSP00000353292', 'cpi_9606.ENSP00000343040'], ['cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000233242', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000356671', 'cpi_9606.ENSP00000307599'], ['cpi_9606.ENSP00000316244', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000344352', 'cpi_9606.ENSP00000368253'], ['cpi_9606.ENSP00000280155', 'cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000376943', 'cpi_9606.ENSP00000305422'], ['cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000414303', 'cpi_9606.ENSP00000356954', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000447149'], ['cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000273550', 'cpi_9606.ENSP00000231454', 'cpi_9606.ENSP00000343477', 'cpi_9606.ENSP00000471569'], ['cpi_9606.ENSP00000297494', 'cpi_9606.ENSP00000331912', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000445340'], ['cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000316786', 'cpi_9606.ENSP00000252486', 'cpi_9606.ENSP00000387281', 'cpi_9606.ENSP00000259396'], ['cpi_9606.ENSP00000295897', 'cpi_9606.ENSP00000378517', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000361359', 'cpi_9606.ENSP00000222256'], ['cpi_9606.ENSP00000305372', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000333212'], ['cpi_9606.ENSP00000354859', 'cpi_9606.ENSP00000359478', 'cpi_9606.ENSP00000362036', 'cpi_9606.ENSP00000263923', 'cpi_9606.ENSP00000255465'], ['cpi_9606.ENSP00000258400', 'cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000176763'], ['cpi_9606.ENSP00000215832', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000451040', 'cpi_9606.ENSP00000216962', 'cpi_9606.ENSP00000309124'], ['cpi_9606.ENSP00000269305', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000389414', 'cpi_9606.ENSP00000220616', 'cpi_9606.ENSP00000000442'], ['cpi_9606.ENSP00000337949', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000430432', 'cpi_9606.ENSP00000293288'], ['cpi_9606.ENSP00000237014', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000354558', 'cpi_9606.ENSP00000368766', 'cpi_9606.ENSP00000300061'], ['cpi_9606.ENSP00000358963', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000226574', 'cpi_9606.ENSP00000332369'], ['cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000282397', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000307014'], ['cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000330237', 'cpi_9606.ENSP00000295491', 'cpi_9606.ENSP00000307235', 'cpi_9606.ENSP00000263126'], ['cpi_9606.ENSP00000263025', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000267119', 'cpi_9606.ENSP00000274793', 'cpi_9606.ENSP00000290349'], ['cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000364805', 'cpi_9606.ENSP00000348069'], ['cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000330393', 'cpi_9606.ENSP00000262948', 'cpi_9606.ENSP00000345659'], ['cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000296122', 'cpi_9606.ENSP00000292513', 'cpi_9606.ENSP00000358548'], ['cpi_9606.ENSP00000411532', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000365016', 'cpi_9606.ENSP00000361666', 'cpi_9606.ENSP00000262888'], ['cpi_9606.ENSP00000386069', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000323568'], ['cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000398632', 'cpi_9606.ENSP00000256958', 'cpi_9606.ENSP00000176183', 'cpi_9606.ENSP00000358784'], ['cpi_9606.ENSP00000276198', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000260356', 'cpi_9606.ENSP00000427514', 'cpi_9606.ENSP00000459962'], ['cpi_9606.ENSP00000306512', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000302967', 'cpi_9606.ENSP00000297350', 'cpi_9606.ENSP00000365380'], ['cpi_9606.ENSP00000306245', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000312455', 'cpi_9606.ENSP00000467676', 'cpi_9606.ENSP00000352702'], ['cpi_9606.ENSP00000308541', 'cpi_9606.ENSP00000282561', 'cpi_9606.ENSP00000329357', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000470087'], ['cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000306662', 'cpi_9606.ENSP00000366307', 'cpi_9606.ENSP00000355657'], ['cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000329623', 'cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000355317', 'cpi_9606.ENSP00000311095'], ['cpi_9606.ENSP00000252945', 'cpi_9606.ENSP00000340943', 'cpi_9606.ENSP00000368880', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000410294'], ['cpi_9606.ENSP00000302150', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000318822', 'cpi_9606.ENSP00000359793', 'cpi_9606.ENSP00000353791'], ['cpi_9606.ENSP00000287820', 'cpi_9606.ENSP00000378699', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000311028', 'cpi_9606.ENSP00000267843'], ['cpi_9606.ENSP00000270142', 'cpi_9606.ENSP00000400175', 'cpi_9606.ENSP00000276449', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000376178'], ['cpi_9606.ENSP00000366084', 'cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000262367', 'cpi_9606.ENSP00000340820', 'cpi_9606.ENSP00000305221'], ['cpi_9606.ENSP00000355759', 'cpi_9606.ENSP00000394033', 'cpi_9606.ENSP00000301974', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000222330'], ['cpi_9606.ENSP00000373169', 'cpi_9606.ENSP00000357204', 'cpi_9606.ENSP00000360493', 'cpi_9606.ENSP00000353878', 'cpi_9606.ENSP00000385806'], ['cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000241261', 'cpi_9606.ENSP00000288135', 'cpi_9606.ENSP00000285979'], ['cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000289753'], ['cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000356832', 'cpi_9606.ENSP00000277120', 'cpi_9606.ENSP00000382659', 'cpi_9606.ENSP00000448059'], ['cpi_9606.ENSP00000464149', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000304845', 'cpi_9606.ENSP00000353198', 'cpi_9606.ENSP00000353427'], ['cpi_9606.ENSP00000412237', 'cpi_9606.ENSP00000327801', 'cpi_9606.ENSP00000354394', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000287907'], ['cpi_9606.ENSP00000313661', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000232219', 'cpi_9606.ENSP00000225964'], ['cpi_9606.ENSP00000219070', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000327652', 'cpi_9606.ENSP00000252029', 'cpi_9606.ENSP00000348827'], ['cpi_9606.ENSP00000290866', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000302811', 'cpi_9606.ENSP00000248553', 'cpi_9606.ENSP00000230671'], ['cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000212015', 'cpi_9606.ENSP00000308774', 'cpi_9606.ENSP00000303174', 'cpi_9606.ENSP00000260191'], ['cpi_9606.ENSP00000225831', 'cpi_9606.ENSP00000364802', 'cpi_9606.ENSP00000339527', 'cpi_9606.ENSP00000359635', 'cpi_9606.ENSP00000463999'], ['cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000263341', 'cpi_9606.ENSP00000356150', 'cpi_9606.ENSP00000254488', 'cpi_9606.ENSP00000254066'], ['cpi_9606.ENSP00000223095', 'cpi_9606.ENSP00000304915', 'cpi_9606.ENSP00000419782', 'cpi_9606.ENSP00000360967', 'cpi_9606.ENSP00000263980'], ['cpi_9606.ENSP00000284981', 'cpi_9606.ENSP00000304895', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000296871'], ['cpi_9606.ENSP00000358327', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000261465', 'cpi_9606.ENSP00000341885', 'cpi_9606.ENSP00000350767'], ['cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000321988', 'cpi_9606.ENSP00000331358', 'cpi_9606.ENSP00000239849', 'cpi_9606.ENSP00000429374'], ['cpi_9606.ENSP00000368438', 'cpi_9606.ENSP00000355930', 'cpi_9606.ENSP00000320935', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000310447'], ['cpi_9606.ENSP00000237612', 'cpi_9606.ENSP00000441691', 'cpi_9606.ENSP00000355778', 'cpi_9606.ENSP00000307766', 'cpi_9606.ENSP00000358595'], ['cpi_9606.ENSP00000361405', 'cpi_9606.ENSP00000311121', 'cpi_9606.ENSP00000365663', 'cpi_9606.ENSP00000301141', 'cpi_9606.ENSP00000312029'], ['cpi_9606.ENSP00000394624', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000347979', 'cpi_9606.ENSP00000310928', 'cpi_9606.ENSP00000308845'], ['cpi_9606.ENSP00000344456', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000295834', 'cpi_9606.ENSP00000367309', 'cpi_9606.ENSP00000278616'], ['cpi_9606.ENSP00000337459', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000270625', 'cpi_9606.ENSP00000219919', 'cpi_9606.ENSP00000370473'], ['cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000256010', 'cpi_9606.ENSP00000372023', 'cpi_9606.ENSP00000317379', 'cpi_9606.ENSP00000391826'], ['cpi_9606.ENSP00000306129', 'cpi_9606.ENSP00000356729', 'cpi_9606.ENSP00000333496', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000341045'], ['cpi_9606.ENSP00000327251', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000466799', 'cpi_9606.ENSP00000358730'], ['cpi_9606.ENSP00000340684', 'cpi_9606.ENSP00000231449', 'cpi_9606.ENSP00000388648', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000241600'], ['cpi_9606.ENSP00000387662', 'cpi_9606.ENSP00000301146', 'cpi_9606.ENSP00000263464', 'cpi_9606.ENSP00000343204', 'cpi_9606.ENSP00000338082'], ['cpi_9606.ENSP00000264832', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000341828', 'cpi_9606.ENSP00000311469', 'cpi_9606.ENSP00000294954'], ['cpi_9606.ENSP00000303522', 'cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000351209', 'cpi_9606.ENSP00000260970'], ['cpi_9606.ENSP00000345096', 'cpi_9606.ENSP00000264657', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000248041', 'cpi_9606.ENSP00000322924'], ['cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000236850', 'cpi_9606.ENSP00000262461', 'cpi_9606.ENSP00000291294', 'cpi_9606.ENSP00000320401'], ['cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000350348', 'cpi_9606.ENSP00000219700', 'cpi_9606.ENSP00000221515', 'cpi_9606.ENSP00000196551'], ['cpi_9606.ENSP00000354511', 'cpi_9606.ENSP00000380252', 'cpi_9606.ENSP00000264867', 'cpi_9606.ENSP00000338548', 'cpi_9606.ENSP00000178638'], ['cpi_9606.ENSP00000369050', 'cpi_9606.ENSP00000359899', 'cpi_9606.ENSP00000368752', 'cpi_9606.ENSP00000318646', 'cpi_9606.ENSP00000370254'], ['cpi_9606.ENSP00000265572', 'cpi_9606.ENSP00000265723', 'cpi_9606.ENSP00000337773', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000332816'], ['cpi_9606.ENSP00000369647', 'cpi_9606.ENSP00000270776', 'cpi_9606.ENSP00000369757', 'cpi_9606.ENSP00000354107', 'cpi_9606.ENSP00000263339'], ['cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000275300', 'cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000287936', 'cpi_9606.ENSP00000270474'], ['cpi_9606.ENSP00000305742', 'cpi_9606.ENSP00000454071', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000393312', 'cpi_9606.ENSP00000266682'], ['cpi_9606.ENSP00000234111', 'cpi_9606.ENSP00000312673', 'cpi_9606.ENSP00000360973', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000253122'], ['cpi_9606.ENSP00000295598', 'cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000309757', 'cpi_9606.ENSP00000254810', 'cpi_9606.ENSP00000378492'], ['cpi_9606.ENSP00000356825', 'cpi_9606.ENSP00000231228', 'cpi_9606.ENSP00000407375', 'cpi_9606.ENSP00000356694', 'cpi_9606.ENSP00000305302'], ['cpi_9606.ENSP00000216117', 'cpi_9606.ENSP00000248076', 'cpi_9606.ENSP00000435777', 'cpi_9606.ENSP00000362513', 'cpi_9606.ENSP00000346298'], ['cpi_9606.ENSP00000349467', 'cpi_9606.ENSP00000262735', 'cpi_9606.ENSP00000359100', 'cpi_9606.ENSP00000330199', 'cpi_9606.ENSP00000257068'], ['cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000233146', 'cpi_9606.ENSP00000419692', 'cpi_9606.ENSP00000251566', 'cpi_9606.ENSP00000308549'], ['cpi_9606.ENSP00000225275', 'cpi_9606.ENSP00000287641', 'cpi_9606.ENSP00000338627', 'cpi_9606.ENSP00000309103', 'cpi_9606.ENSP00000349252'], ['cpi_9606.ENSP00000257497', 'cpi_9606.ENSP00000314508', 'cpi_9606.ENSP00000384273', 'cpi_9606.ENSP00000344674', 'cpi_9606.ENSP00000362508'], ['cpi_9606.ENSP00000312652', 'cpi_9606.ENSP00000275216', 'cpi_9606.ENSP00000263377', 'cpi_9606.ENSP00000308032', 'cpi_9606.ENSP00000301633'], ['cpi_9606.ENSP00000307786', 'cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000368104', 'cpi_9606.ENSP00000351908', 'cpi_9606.ENSP00000333534'], ['cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000368683', 'cpi_9606.ENSP00000265403', 'cpi_9606.ENSP00000349577', 'cpi_9606.ENSP00000353915'], ['cpi_9606.ENSP00000274353', 'cpi_9606.ENSP00000264498', 'cpi_9606.ENSP00000342560', 'cpi_9606.ENSP00000268035', 'cpi_9606.ENSP00000387683'], ['cpi_9606.ENSP00000370571', 'cpi_9606.ENSP00000256078', 'cpi_9606.ENSP00000410076', 'cpi_9606.ENSP00000253727', 'cpi_9606.ENSP00000262160'], ['cpi_9606.ENSP00000352608', 'cpi_9606.ENSP00000239938', 'cpi_9606.ENSP00000319814', 'cpi_9606.ENSP00000234961', 'cpi_9606.ENSP00000363512'], ['cpi_9606.ENSP00000272298', 'cpi_9606.ENSP00000244741', 'cpi_9606.ENSP00000355523', 'cpi_9606.ENSP00000387888', 'cpi_9606.ENSP00000346598'], ['cpi_9606.ENSP00000309845', 'cpi_9606.ENSP00000321821', 'cpi_9606.ENSP00000245457', 'cpi_9606.ENSP00000297268', 'cpi_9606.ENSP00000398655'], ['cpi_9606.ENSP00000331514', 'cpi_9606.ENSP00000360991', 'cpi_9606.ENSP00000362401', 'cpi_9606.ENSP00000256383', 'cpi_9606.ENSP00000217426'], ['cpi_9606.ENSP00000320709', 'cpi_9606.ENSP00000381333', 'cpi_9606.ENSP00000359998', 'cpi_9606.ENSP00000304408', 'cpi_9606.ENSP00000427562'], ['cpi_9606.ENSP00000285379', 'cpi_9606.ENSP00000386884', 'cpi_9606.ENSP00000264896', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000301634'], ['cpi_9606.ENSP00000275493', 'cpi_9606.ENSP00000324248', 'cpi_9606.ENSP00000420168', 'cpi_9606.ENSP00000259271', 'cpi_9606.ENSP00000433821'], ['cpi_9606.ENSP00000315644', 'cpi_9606.ENSP00000358511', 'cpi_9606.ENSP00000260227', 'cpi_9606.ENSP00000368632', 'cpi_9606.ENSP00000346148'], ['cpi_9606.ENSP00000338018', 'cpi_9606.ENSP00000305692', 'cpi_9606.ENSP00000302846', 'cpi_9606.ENSP00000268053', 'cpi_9606.ENSP00000296674'], ['cpi_9606.ENSP00000378323', 'cpi_9606.ENSP00000360968', 'cpi_9606.ENSP00000303452', 'cpi_9606.ENSP00000352584', 'cpi_9606.ENSP00000251453'], ['cpi_9606.ENSP00000375066', 'cpi_9606.ENSP00000358107', 'cpi_9606.ENSP00000228872', 'cpi_9606.ENSP00000346067', 'cpi_9606.ENSP00000332679'], ['cpi_9606.ENSP00000356022', 'cpi_9606.ENSP00000307259', 'cpi_9606.ENSP00000311165', 'cpi_9606.ENSP00000341189', 'cpi_9606.ENSP00000379339'], ['cpi_9606.ENSP00000279387', 'cpi_9606.ENSP00000360266', 'cpi_9606.ENSP00000350198', 'cpi_9606.ENSP00000334246', 'cpi_9606.ENSP00000216341'], ['cpi_9606.ENSP00000317842', 'cpi_9606.ENSP00000297469', 'cpi_9606.ENSP00000297258', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000218388'], ['cpi_9606.ENSP00000234310', 'cpi_9606.ENSP00000242152', 'cpi_9606.ENSP00000269571', 'cpi_9606.ENSP00000274026', 'cpi_9606.ENSP00000370129'], ['cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000393333', 'cpi_9606.ENSP00000252321', 'cpi_9606.ENSP00000370912', 'cpi_9606.ENSP00000351885'], ['cpi_9606.ENSP00000321584', 'cpi_9606.ENSP00000273430', 'cpi_9606.ENSP00000386171', 'cpi_9606.ENSP0000026

🔄 Processing features: 100%|██████████| 1607/1607 [06:50<00:00,  3.92feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'cpi_9606.ENSP00000326219', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000356094', 'cpi_9606.ENSP00000298472'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000367848', 'cpi_9606.ENSP00000299178'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000355629', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000374323'], ['cpi_9606.ENSP00000360372', 'cpi_9606.ENSP00000303522', 'cpi_9606.ENSP00000261937', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000430684'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000261799', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000332296'], ['cpi_9606.ENSP00000311032', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000359353', 'cpi_9606.ENSP00000003100'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000382659', 'cpi_9606.ENSP00000414334'], ['cpi_9606.ENSP00000265724', 'cpi_9606.ENSP00000304822', 'cpi_9606.ENSP00000354569', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000381097'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000301891', 'cpi_9606.ENSP00000395653'], ['cpi_9606.ENSP00000367959', 'cpi_9606.ENSP00000301634', 'cpi_9606.ENSP00000242057', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000264318'], ['cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000309818', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000344192', 'cpi_9606.ENSP00000360773'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000417229', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000266376'], ['cpi_9606.ENSP00000272190', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000354476', 'cpi_9606.ENSP00000275525', 'cpi_9606.ENSP00000337335'], ['cpi_9606.ENSP00000369960', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000408860'], ['cpi_9606.ENSP00000231509', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000257290'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000351209', 'cpi_9606.ENSP00000389338'], ['cpi_9606.ENSP00000270349', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000319788', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000267101'], ['cpi_9606.ENSP00000337450', 'cpi_9606.ENSP00000262441', 'cpi_9606.ENSP00000362649', 'cpi_9606.ENSP00000342235', 'cpi_9606.ENSP00000216037'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000295454', 'cpi_9606.ENSP00000291700'], ['cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000263321', 'cpi_9606.ENSP00000316786', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000377947'], ['cpi_9606.ENSP00000264381', 'cpi_9606.ENSP00000279178', 'cpi_9606.ENSP00000457706', 'cpi_9606.ENSP00000259396', 'cpi_9606.ENSP00000340691'], ['cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000363822', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000335592'], ['cpi_9606.ENSP00000260433', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000347942', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000226574'], ['cpi_9606.ENSP00000270202', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000295491', 'cpi_9606.ENSP00000258749'], ['cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000358548'], ['cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000367102', 'cpi_9606.ENSP00000343040'], ['cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000277010', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000359334'], ['cpi_9606.ENSP00000305372', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000274547', 'cpi_9606.ENSP00000283635'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000299267', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000259089'], ['cpi_9606.ENSP00000258743', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000220616', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000412673'], ['cpi_9606.ENSP00000398698', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000394936', 'cpi_9606.ENSP00000307014'], ['cpi_9606.ENSP00000280155', 'cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000302111', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000334198'], ['cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000330237', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000451040', 'cpi_9606.ENSP00000348897'], ['cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000320935'], ['cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000252723', 'cpi_9606.ENSP00000241600'], ['cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000225474', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000353915'], ['cpi_9606.ENSP00000356438', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000387946', 'cpi_9606.ENSP00000222256'], ['cpi_9606.ENSP00000337949', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000398632', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000241453'], ['cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000233242', 'cpi_9606.ENSP00000301178', 'cpi_9606.ENSP00000267119'], ['cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000331912', 'cpi_9606.ENSP00000312455'], ['cpi_9606.ENSP00000258400', 'cpi_9606.ENSP00000353731', 'cpi_9606.ENSP00000344352', 'cpi_9606.ENSP00000221972', 'cpi_9606.ENSP00000389414'], ['cpi_9606.ENSP00000237014', 'cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000282561', 'cpi_9606.ENSP00000386029'], ['cpi_9606.ENSP00000316244', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000307599', 'cpi_9606.ENSP00000286301', 'cpi_9606.ENSP00000467676'], ['cpi_9606.ENSP00000215832', 'cpi_9606.ENSP00000471569', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000365663'], ['cpi_9606.ENSP00000366506', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000323568', 'cpi_9606.ENSP00000312664', 'cpi_9606.ENSP00000356436'], ['cpi_9606.ENSP00000354612', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000222330', 'cpi_9606.ENSP00000410076', 'cpi_9606.ENSP00000367851'], ['cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000359478', 'cpi_9606.ENSP00000362036', 'cpi_9606.ENSP00000361359', 'cpi_9606.ENSP00000470087'], ['cpi_9606.ENSP00000295897', 'cpi_9606.ENSP00000378517', 'cpi_9606.ENSP00000311469', 'cpi_9606.ENSP00000311028', 'cpi_9606.ENSP00000359793'], ['cpi_9606.ENSP00000269305', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000263126', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000276198'], ['cpi_9606.ENSP00000297494', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000252029', 'cpi_9606.ENSP00000333212', 'cpi_9606.ENSP00000264637'], ['cpi_9606.ENSP00000386069', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000370381', 'cpi_9606.ENSP00000348069'], ['cpi_9606.ENSP00000306245', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000261693', 'cpi_9606.ENSP00000353878', 'cpi_9606.ENSP00000320025'], ['cpi_9606.ENSP00000308541', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000361666', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000337773'], ['cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000264832', 'cpi_9606.ENSP00000262888', 'cpi_9606.ENSP00000343204', 'cpi_9606.ENSP00000200676'], ['cpi_9606.ENSP00000263025', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000309124', 'cpi_9606.ENSP00000359096'], ['cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000270474', 'cpi_9606.ENSP00000326119', 'cpi_9606.ENSP00000387281', 'cpi_9606.ENSP00000256958'], ['cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000356954', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000410294', 'cpi_9606.ENSP00000248553'], ['cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000241261', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000308774', 'cpi_9606.ENSP00000262367'], ['cpi_9606.ENSP00000368766', 'cpi_9606.ENSP00000329623', 'cpi_9606.ENSP00000314508', 'cpi_9606.ENSP00000353292', 'cpi_9606.ENSP00000376178'], ['cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000308165', 'cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000428340'], ['cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000381333', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000310928', 'cpi_9606.ENSP00000347979'], ['cpi_9606.ENSP00000306662', 'cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000445340', 'cpi_9606.ENSP00000360493'], ['cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000364805', 'cpi_9606.ENSP00000289753'], ['cpi_9606.ENSP00000354859', 'cpi_9606.ENSP00000357204', 'cpi_9606.ENSP00000343477', 'cpi_9606.ENSP00000251535', 'cpi_9606.ENSP00000356671'], ['cpi_9606.ENSP00000220764', 'cpi_9606.ENSP00000293288', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000327652'], ['cpi_9606.ENSP00000414303', 'cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000346598'], ['cpi_9606.ENSP00000355759', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000292896', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000427514'], ['cpi_9606.ENSP00000219070', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000216341', 'cpi_9606.ENSP00000254976', 'cpi_9606.ENSP00000300061'], ['cpi_9606.ENSP00000411532', 'cpi_9606.ENSP00000231454', 'cpi_9606.ENSP00000261196', 'cpi_9606.ENSP00000267843', 'cpi_9606.ENSP00000430432'], ['cpi_9606.ENSP00000306512', 'cpi_9606.ENSP00000318912', 'cpi_9606.ENSP00000369757', 'cpi_9606.ENSP00000364802', 'cpi_9606.ENSP00000447149'], ['cpi_9606.ENSP00000358963', 'cpi_9606.ENSP00000304845', 'cpi_9606.ENSP00000355778', 'cpi_9606.ENSP00000382250', 'cpi_9606.ENSP00000297350'], ['cpi_9606.ENSP00000287820', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000341885', 'cpi_9606.ENSP00000376943', 'cpi_9606.ENSP00000287766'], ['cpi_9606.ENSP00000368438', 'cpi_9606.ENSP00000355930', 'cpi_9606.ENSP00000329357', 'cpi_9606.ENSP00000274793', 'cpi_9606.ENSP00000176183'], ['cpi_9606.ENSP00000237612', 'cpi_9606.ENSP00000441691', 'cpi_9606.ENSP00000254810', 'cpi_9606.ENSP00000276449', 'cpi_9606.ENSP00000296871'], ['cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000353427', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000318646'], ['cpi_9606.ENSP00000225831', 'cpi_9606.ENSP00000349576', 'cpi_9606.ENSP00000339527', 'cpi_9606.ENSP00000373169', 'cpi_9606.ENSP00000252809'], ['cpi_9606.ENSP00000290866', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000380252', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000331358'], ['cpi_9606.ENSP00000252945', 'cpi_9606.ENSP00000298171', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000366307', 'cpi_9606.ENSP00000242375'], ['cpi_9606.ENSP00000302150', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000256383', 'cpi_9606.ENSP00000292513', 'cpi_9606.ENSP00000260010'], ['cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000212015', 'cpi_9606.ENSP00000176763', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000429374'], ['cpi_9606.ENSP00000464149', 'cpi_9606.ENSP00000378699', 'cpi_9606.ENSP00000349252', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000313661'], ['cpi_9606.ENSP00000412237', 'cpi_9606.ENSP00000327801', 'cpi_9606.ENSP00000294728', 'cpi_9606.ENSP00000463999', 'cpi_9606.ENSP00000338627'], ['cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000263341', 'cpi_9606.ENSP00000354394', 'cpi_9606.ENSP00000196551', 'cpi_9606.ENSP00000339260'], ['cpi_9606.ENSP00000344456', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000263923', 'cpi_9606.ENSP00000302811', 'cpi_9606.ENSP00000353791'], ['cpi_9606.ENSP00000361405', 'cpi_9606.ENSP00000355325', 'cpi_9606.ENSP00000277120', 'cpi_9606.ENSP00000263980', 'cpi_9606.ENSP00000359998'], ['cpi_9606.ENSP00000387662', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000340820', 'cpi_9606.ENSP00000344674', 'cpi_9606.ENSP00000364310'], ['cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000366084', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000216962', 'cpi_9606.ENSP00000332369'], ['cpi_9606.ENSP00000358327', 'cpi_9606.ENSP00000314949', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000370473', 'cpi_9606.ENSP00000448059'], ['cpi_9606.ENSP00000306129', 'cpi_9606.ENSP00000356729', 'cpi_9606.ENSP00000385806', 'cpi_9606.ENSP00000262948', 'cpi_9606.ENSP00000230671'], ['cpi_9606.ENSP00000327251', 'cpi_9606.ENSP00000358784', 'cpi_9606.ENSP00000354610', 'cpi_9606.ENSP00000253727', 'cpi_9606.ENSP00000307766'], ['cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000279387', 'cpi_9606.ENSP00000225964', 'cpi_9606.ENSP00000311095', 'cpi_9606.ENSP00000322924'], ['cpi_9606.ENSP00000350348', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000360967', 'cpi_9606.ENSP00000357283', 'cpi_9606.ENSP00000296674'], ['cpi_9606.ENSP00000234111', 'cpi_9606.ENSP00000312673', 'cpi_9606.ENSP00000358730', 'cpi_9606.ENSP00000252486', 'cpi_9606.ENSP00000307235'], ['cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000236850', 'cpi_9606.ENSP00000255465', 'cpi_9606.ENSP00000294954'], ['cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000303174', 'cpi_9606.ENSP00000435777', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000264657'], ['cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000231449', 'cpi_9606.ENSP00000233146', 'cpi_9606.ENSP00000282397', 'cpi_9606.ENSP00000295834'], ['cpi_9606.ENSP00000270142', 'cpi_9606.ENSP00000400175', 'cpi_9606.ENSP00000285979', 'cpi_9606.ENSP00000307445', 'cpi_9606.ENSP00000270625'], ['cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000327431', 'cpi_9606.ENSP00000370912', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000231751'], ['cpi_9606.ENSP00000340684', 'cpi_9606.ENSP00000319591', 'cpi_9606.ENSP00000356694', 'cpi_9606.ENSP00000278616', 'cpi_9606.ENSP00000256119'], ['cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000330393', 'cpi_9606.ENSP00000372023', 'cpi_9606.ENSP00000303452', 'cpi_9606.ENSP00000379339'], ['cpi_9606.ENSP00000223095', 'cpi_9606.ENSP00000273550', 'cpi_9606.ENSP00000354107', 'cpi_9606.ENSP00000307259', 'cpi_9606.ENSP00000396320'], ['cpi_9606.ENSP00000369050', 'cpi_9606.ENSP00000301974', 'cpi_9606.ENSP00000356150', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000260356'], ['cpi_9606.ENSP00000337459', 'cpi_9606.ENSP00000333496', 'cpi_9606.ENSP00000366927', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000333821'], ['cpi_9606.ENSP00000331746', 'cpi_9606.ENSP00000301146', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000263857', 'cpi_9606.ENSP00000216797'], ['cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000321988', 'cpi_9606.ENSP00000239849', 'cpi_9606.ENSP00000362401', 'cpi_9606.ENSP00000251453'], ['cpi_9606.ENSP00000257497', 'cpi_9606.ENSP00000338548', 'cpi_9606.ENSP00000454071', 'cpi_9606.ENSP00000318822', 'cpi_9606.ENSP00000433821'], ['cpi_9606.ENSP00000394624', 'cpi_9606.ENSP00000301633', 'cpi_9606.ENSP00000302967', 'cpi_9606.ENSP00000341045', 'cpi_9606.ENSP00000434364'], ['cpi_9606.ENSP00000369647', 'cpi_9606.ENSP00000219919', 'cpi_9606.ENSP00000275300', 'cpi_9606.ENSP00000264867', 'cpi_9606.ENSP00000365380'], ['cpi_9606.ENSP00000370571', 'cpi_9606.ENSP00000295256', 'cpi_9606.ENSP00000262461', 'cpi_9606.ENSP00000312029', 'cpi_9606.ENSP00000388648'], ['cpi_9606.ENSP00000274353', 'cpi_9606.ENSP00000264498', 'cpi_9606.ENSP00000354558', 'cpi_9606.ENSP00000297268', 'cpi_9606.ENSP00000254488'], ['cpi_9606.ENSP00000315644', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000287936', 'cpi_9606.ENSP00000360973', 'cpi_9606.ENSP00000355657'], ['cpi_9606.ENSP00000349467', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000276431', 'cpi_9606.ENSP00000393312', 'cpi_9606.ENSP00000323549'], ['cpi_9606.ENSP00000265572', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000295400', 'cpi_9606.ENSP00000309757', 'cpi_9606.ENSP00000266682'], ['cpi_9606.ENSP00000304915', 'cpi_9606.ENSP00000367309', 'cpi_9606.ENSP00000265164', 'cpi_9606.ENSP00000268053', 'cpi_9606.ENSP00000332816'], ['cpi_9606.ENSP00000312652', 'cpi_9606.ENSP00000357981', 'cpi_9606.ENSP00000252804', 'cpi_9606.ENSP00000336630', 'cpi_9606.ENSP00000263464'], ['cpi_9606.ENSP00000338018', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000346067', 'cpi_9606.ENSP00000270776', 'cpi_9606.ENSP00000358511'], ['cpi_9606.ENSP00000272298', 'cpi_9606.ENSP00000244741', 'cpi_9606.ENSP00000221515', 'cpi_9606.ENSP00000386229', 'cpi_9606.ENSP00000305221'], ['cpi_9606.ENSP00000216117', 'cpi_9606.ENSP00000282753', 'cpi_9606.ENSP00000310447', 'cpi_9606.ENSP00000386171', 'cpi_9606.ENSP00000288135'], ['cpi_9606.ENSP00000352835', 'cpi_9606.ENSP00000368683', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000419782', 'cpi_9606.ENSP00000459962'], ['cpi_9606.ENSP00000357669', 'cpi_9606.ENSP00000262735', 'cpi_9606.ENSP00000287907', 'cpi_9606.ENSP00000305302', 'cpi_9606.ENSP00000296412'], ['cpi_9606.ENSP00000218548', 'cpi_9606.ENSP00000384273', 'cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000317379', 'cpi_9606.ENSP00000253122'], ['cpi_9606.ENSP00000354511', 'cpi_9606.ENSP00000239938', 'cpi_9606.ENSP00000320866', 'cpi_9606.ENSP00000351885', 'cpi_9606.ENSP00000419692'], ['cpi_9606.ENSP00000309845', 'cpi_9606.ENSP00000308032', 'cpi_9606.ENSP00000291294', 'cpi_9606.ENSP00000349577', 'cpi_9606.ENSP00000352584'], ['cpi_9606.ENSP00000275493', 'cpi_9606.ENSP00000342560', 'cpi_9606.ENSP00000346298', 'cpi_9606.ENSP00000232219', 'cpi_9606.ENSP00000368632'], ['cpi_9606.ENSP00000345096', 'cpi_9606.ENSP00000297469', 'cpi_9606.ENSP00000368880', 'cpi_9606.ENSP00000348645', 'cpi_9606.ENSP00000330199'], ['cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000324270', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000218388', 'cpi_9606.ENSP00000420168'], ['cpi_9606.ENSP00000305742', 'cpi_9606.ENSP00000265723', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000333534', 'cpi_9606.ENSP00000359635'], ['cpi_9606.ENSP00000266970', 'cpi_9606.ENSP00000231228', 'cpi_9606.ENSP00000309968', 'cpi_9606.ENSP00000346827', 'cpi_9606.ENSP00000321106'], ['cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000301141', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000407375', 'cpi_9606.ENSP00000347046'], ['cpi_9606.ENSP00000265023', 'cpi_9606.ENSP00000288022', 'cpi_9606.ENSP00000365016', 'cpi_9606.ENSP00000300151', 'cpi_9606.ENSP00000309103'], ['cpi_9606.ENSP00000356825', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000359532', 'cpi_9606.ENSP00000368752', 'cpi_9606.ENSP00000346148'], ['cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000362353', 'cpi_9606.ENSP00000211122', 'cpi_9606.ENSP00000360266', 'cpi_9606.ENSP00000356832'], ['cpi_9606.ENSP00000368349', 'cpi_9606.ENSP00000362508', 'cpi_9606.ENSP00000257068', 'cpi_9606.ENSP00000371554', 'cpi_9606.ENSP00000225577'], ['cpi_9606.ENSP00000262623', 'cpi_9606.ENSP00000304895', 'cpi_9606.ENSP00000215659', 'cpi_9606.ENSP00000308549', 'cpi_9606.ENSP00000320401'], ['cpi_9606.ENSP00000229135', 'cpi_9606.ENSP00000384957', 'cpi_9606.ENSP00000302846', 'cpi_9606.ENSP00000360968', 'cpi_9606.ENSP00000427562'], ['cpi_9606.ENSP00000360683', 'cpi_9606.ENSP00000287641', 'cpi_9606.ENSP00000368104', 'cpi_9606.ENSP00000361151', 'cpi_9606.ENSP00000225371'], ['cpi_9606.ENSP00000296545', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000254079', 'cpi_9606.ENSP00000387683', 'cpi_9606.ENSP00000351908'], ['cpi_9606.ENSP00000364709', 'cpi_9606.ENSP00000242152', 'cpi_9606.ENSP00000417281', 'cpi_9606.ENSP00000265403', 'cpi_9606.ENSP00000358424'], ['cpi_9606.ENSP00000260970', 'cpi_9606.ENSP00000355920', 'cpi_9606.ENSP00000338082', 'cpi_9606.ENSP00000296122', 'cpi_9606.ENSP00000320709'], ['cpi_9606.ENSP00000234961', 'cpi_9606.ENSP00000319814', 'cpi_9606.ENSP00000268035', 'cpi_9606.ENSP00000219700', 'cpi_9606.ENSP00000374265'], ['cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000393333', 'cpi_9606.ENSP00000360991', 'cpi_9606.ENSP0000030

🔄 Processing features: 100%|██████████| 1607/1607 [06:51<00:00,  3.91feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'cpi_9606.ENSP00000356671', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000356094', 'cpi_9606.ENSP00000414334'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000355629', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000360773'], ['cpi_9606.ENSP00000360372', 'cpi_9606.ENSP00000309818', 'cpi_9606.ENSP00000261937', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000430684'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000367848', 'cpi_9606.ENSP00000299178'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000301891', 'cpi_9606.ENSP00000395653'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000221972'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000261799', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000353292'], ['cpi_9606.ENSP00000265724', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000359793', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000359353'], ['cpi_9606.ENSP00000369960', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000365686'], ['cpi_9606.ENSP00000272190', 'cpi_9606.ENSP00000225474', 'cpi_9606.ENSP00000354476', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000337335'], ['cpi_9606.ENSP00000311032', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000344674'], ['cpi_9606.ENSP00000367959', 'cpi_9606.ENSP00000301634', 'cpi_9606.ENSP00000417229', 'cpi_9606.ENSP00000252486', 'cpi_9606.ENSP00000346534'], ['cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000312664', 'cpi_9606.ENSP00000344192', 'cpi_9606.ENSP00000410732'], ['cpi_9606.ENSP00000231509', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000266376', 'cpi_9606.ENSP00000323568', 'cpi_9606.ENSP00000367102'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000374323', 'cpi_9606.ENSP00000398632'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000292896', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000279178'], ['cpi_9606.ENSP00000270349', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000319788', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000267101'], ['cpi_9606.ENSP00000264381', 'cpi_9606.ENSP00000275525', 'cpi_9606.ENSP00000342235', 'cpi_9606.ENSP00000347979', 'cpi_9606.ENSP00000352011'], ['cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000263321', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000257290', 'cpi_9606.ENSP00000358548'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000262441', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000389338', 'cpi_9606.ENSP00000351209'], ['cpi_9606.ENSP00000337450', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000362649', 'cpi_9606.ENSP00000216037', 'cpi_9606.ENSP00000297350'], ['cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000277010', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000335592'], ['cpi_9606.ENSP00000258743', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000326219', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000293745'], ['cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000361666', 'cpi_9606.ENSP00000332296', 'cpi_9606.ENSP00000295454'], ['cpi_9606.ENSP00000260433', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000347942', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000252519'], ['cpi_9606.ENSP00000356438', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000394936', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000381097'], ['cpi_9606.ENSP00000354612', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000348069', 'cpi_9606.ENSP00000300061', 'cpi_9606.ENSP00000274547'], ['cpi_9606.ENSP00000305372', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000364802'], ['cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000316786', 'cpi_9606.ENSP00000261693', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000301178'], ['cpi_9606.ENSP00000270202', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000445340', 'cpi_9606.ENSP00000307599', 'cpi_9606.ENSP00000377947'], ['cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000414303', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000309124', 'cpi_9606.ENSP00000252809'], ['cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000316244', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000370381', 'cpi_9606.ENSP00000454071'], ['cpi_9606.ENSP00000297494', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000387946'], ['cpi_9606.ENSP00000398698', 'cpi_9606.ENSP00000331912', 'cpi_9606.ENSP00000262888', 'cpi_9606.ENSP00000259089', 'cpi_9606.ENSP00000348827'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000304822', 'cpi_9606.ENSP00000299267', 'cpi_9606.ENSP00000283635'], ['cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000286301', 'cpi_9606.ENSP00000402152'], ['cpi_9606.ENSP00000258400', 'cpi_9606.ENSP00000363822', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000367851'], ['cpi_9606.ENSP00000237014', 'cpi_9606.ENSP00000354558', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000471569', 'cpi_9606.ENSP00000368766'], ['cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000260356', 'cpi_9606.ENSP00000263923', 'cpi_9606.ENSP00000362036'], ['cpi_9606.ENSP00000337949', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000263126', 'cpi_9606.ENSP00000356832'], ['cpi_9606.ENSP00000295897', 'cpi_9606.ENSP00000378517', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000222256'], ['cpi_9606.ENSP00000280155', 'cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000302111', 'cpi_9606.ENSP00000262461', 'cpi_9606.ENSP00000260010'], ['cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000226574', 'cpi_9606.ENSP00000330393'], ['cpi_9606.ENSP00000215832', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000307014', 'cpi_9606.ENSP00000274793', 'cpi_9606.ENSP00000259396'], ['cpi_9606.ENSP00000269305', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000389414', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000264637'], ['cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000322924', 'cpi_9606.ENSP00000251535', 'cpi_9606.ENSP00000320025'], ['cpi_9606.ENSP00000358963', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000343040'], ['cpi_9606.ENSP00000308541', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000332369'], ['cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000233242', 'cpi_9606.ENSP00000286091', 'cpi_9606.ENSP00000376943', 'cpi_9606.ENSP00000000442'], ['cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000329623', 'cpi_9606.ENSP00000262367', 'cpi_9606.ENSP00000258749', 'cpi_9606.ENSP00000360967'], ['cpi_9606.ENSP00000354859', 'cpi_9606.ENSP00000359478', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000360493'], ['cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000273550', 'cpi_9606.ENSP00000356954', 'cpi_9606.ENSP00000470087', 'cpi_9606.ENSP00000343477'], ['cpi_9606.ENSP00000411532', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000308774', 'cpi_9606.ENSP00000408860'], ['cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000304845', 'cpi_9606.ENSP00000267119', 'cpi_9606.ENSP00000410076', 'cpi_9606.ENSP00000222330'], ['cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000329357', 'cpi_9606.ENSP00000254227'], ['cpi_9606.ENSP00000263025', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000451040', 'cpi_9606.ENSP00000259271', 'cpi_9606.ENSP00000363812'], ['cpi_9606.ENSP00000252945', 'cpi_9606.ENSP00000298171', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000366307', 'cpi_9606.ENSP00000276449'], ['cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000332816', 'cpi_9606.ENSP00000325822'], ['cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000357204', 'cpi_9606.ENSP00000326119', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000361206'], ['cpi_9606.ENSP00000306245', 'cpi_9606.ENSP00000225927', 'cpi_9606.ENSP00000312455', 'cpi_9606.ENSP00000295491', 'cpi_9606.ENSP00000323549'], ['cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000241261', 'cpi_9606.ENSP00000428924', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000290349'], ['cpi_9606.ENSP00000330237', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000327431', 'cpi_9606.ENSP00000353427', 'cpi_9606.ENSP00000282561'], ['cpi_9606.ENSP00000386069', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000219700', 'cpi_9606.ENSP00000361359', 'cpi_9606.ENSP00000345708'], ['cpi_9606.ENSP00000306512', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000435412', 'cpi_9606.ENSP00000386171', 'cpi_9606.ENSP00000353791'], ['cpi_9606.ENSP00000387281', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000242057', 'cpi_9606.ENSP00000263980'], ['cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000428340', 'cpi_9606.ENSP00000309757', 'cpi_9606.ENSP00000233146', 'cpi_9606.ENSP00000261196'], ['cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000256383', 'cpi_9606.ENSP00000267843', 'cpi_9606.ENSP00000315011'], ['cpi_9606.ENSP00000355759', 'cpi_9606.ENSP00000282753', 'cpi_9606.ENSP00000268053', 'cpi_9606.ENSP00000220616', 'cpi_9606.ENSP00000308165'], ['cpi_9606.ENSP00000327652', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000354394', 'cpi_9606.ENSP00000430432', 'cpi_9606.ENSP00000295834'], ['cpi_9606.ENSP00000270142', 'cpi_9606.ENSP00000294728', 'cpi_9606.ENSP00000296522', 'cpi_9606.ENSP00000344352', 'cpi_9606.ENSP00000287766'], ['cpi_9606.ENSP00000220764', 'cpi_9606.ENSP00000293288', 'cpi_9606.ENSP00000276198', 'cpi_9606.ENSP00000255465', 'cpi_9606.ENSP00000285381'], ['cpi_9606.ENSP00000237612', 'cpi_9606.ENSP00000254976', 'cpi_9606.ENSP00000355317', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000311095'], ['cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000302967', 'cpi_9606.ENSP00000200676', 'cpi_9606.ENSP00000262948'], ['cpi_9606.ENSP00000302150', 'cpi_9606.ENSP00000274353', 'cpi_9606.ENSP00000355657', 'cpi_9606.ENSP00000264867', 'cpi_9606.ENSP00000252723'], ['cpi_9606.ENSP00000290866', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000353878', 'cpi_9606.ENSP00000366506'], ['cpi_9606.ENSP00000366084', 'cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000463999'], ['cpi_9606.ENSP00000358327', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000261465', 'cpi_9606.ENSP00000457706', 'cpi_9606.ENSP00000447149'], ['cpi_9606.ENSP00000412237', 'cpi_9606.ENSP00000327801', 'cpi_9606.ENSP00000365663', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000358784'], ['cpi_9606.ENSP00000306662', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000333212', 'cpi_9606.ENSP00000278616', 'cpi_9606.ENSP00000416293'], ['cpi_9606.ENSP00000287820', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000254079', 'cpi_9606.ENSP00000410294', 'cpi_9606.ENSP00000231454'], ['cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000341189', 'cpi_9606.ENSP00000289753', 'cpi_9606.ENSP00000364805'], ['cpi_9606.ENSP00000373169', 'cpi_9606.ENSP00000338548', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000427514', 'cpi_9606.ENSP00000256958'], ['cpi_9606.ENSP00000284981', 'cpi_9606.ENSP00000318822', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000427562'], ['cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000400175', 'cpi_9606.ENSP00000313661', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000305302'], ['cpi_9606.ENSP00000219070', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000346598', 'cpi_9606.ENSP00000355930'], ['cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000321988', 'cpi_9606.ENSP00000239849', 'cpi_9606.ENSP00000331358', 'cpi_9606.ENSP00000287936'], ['cpi_9606.ENSP00000368438', 'cpi_9606.ENSP00000306129', 'cpi_9606.ENSP00000343204', 'cpi_9606.ENSP00000296871', 'cpi_9606.ENSP00000254488'], ['cpi_9606.ENSP00000464149', 'cpi_9606.ENSP00000378699', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000370473', 'cpi_9606.ENSP00000317379'], ['cpi_9606.ENSP00000387662', 'cpi_9606.ENSP00000305221', 'cpi_9606.ENSP00000388648', 'cpi_9606.ENSP00000330199', 'cpi_9606.ENSP00000308845'], ['cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000303522', 'cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000320935'], ['cpi_9606.ENSP00000263341', 'cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000467676', 'cpi_9606.ENSP00000354107', 'cpi_9606.ENSP00000451030'], ['cpi_9606.ENSP00000327251', 'cpi_9606.ENSP00000346298', 'cpi_9606.ENSP00000311028', 'cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000386229'], ['cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000212015', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000176763'], ['cpi_9606.ENSP00000394624', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000266682', 'cpi_9606.ENSP00000263686'], ['cpi_9606.ENSP00000223095', 'cpi_9606.ENSP00000362924', 'cpi_9606.ENSP00000338627', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000355920'], ['cpi_9606.ENSP00000176183', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000355778', 'cpi_9606.ENSP00000385806', 'cpi_9606.ENSP00000351885'], ['cpi_9606.ENSP00000225831', 'cpi_9606.ENSP00000248553', 'cpi_9606.ENSP00000353915', 'cpi_9606.ENSP00000270776', 'cpi_9606.ENSP00000333496'], ['cpi_9606.ENSP00000216117', 'cpi_9606.ENSP00000362810', 'cpi_9606.ENSP00000270625', 'cpi_9606.ENSP00000362513', 'cpi_9606.ENSP00000372023'], ['cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000292513', 'cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000296122'], ['cpi_9606.ENSP00000315644', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000307766', 'cpi_9606.ENSP00000311469', 'cpi_9606.ENSP00000296545'], ['cpi_9606.ENSP00000331746', 'cpi_9606.ENSP00000356729', 'cpi_9606.ENSP00000320709', 'cpi_9606.ENSP00000356150', 'cpi_9606.ENSP00000285979'], ['cpi_9606.ENSP00000309845', 'cpi_9606.ENSP00000301146', 'cpi_9606.ENSP00000291294', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000352584'], ['cpi_9606.ENSP00000265572', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000312029', 'cpi_9606.ENSP00000380252', 'cpi_9606.ENSP00000359635'], ['cpi_9606.ENSP00000337459', 'cpi_9606.ENSP00000352035', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000339527', 'cpi_9606.ENSP00000310928'], ['cpi_9606.ENSP00000368305', 'cpi_9606.ENSP00000264657', 'cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000303174', 'cpi_9606.ENSP00000225964'], ['cpi_9606.ENSP00000312652', 'cpi_9606.ENSP00000394033', 'cpi_9606.ENSP00000304915', 'cpi_9606.ENSP00000448059', 'cpi_9606.ENSP00000357283'], ['cpi_9606.ENSP00000236850', 'cpi_9606.ENSP00000274026', 'cpi_9606.ENSP00000307235', 'cpi_9606.ENSP00000370129', 'cpi_9606.ENSP00000231228'], ['cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000366416', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000466799', 'cpi_9606.ENSP00000337773'], ['cpi_9606.ENSP00000352835', 'cpi_9606.ENSP00000368683', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000340820'], ['cpi_9606.ENSP00000361405', 'cpi_9606.ENSP00000369654', 'cpi_9606.ENSP00000308176', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000340684'], ['cpi_9606.ENSP00000369050', 'cpi_9606.ENSP00000359899', 'cpi_9606.ENSP00000252029', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000288135'], ['cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000295598', 'cpi_9606.ENSP00000273430', 'cpi_9606.ENSP00000252804', 'cpi_9606.ENSP00000368752'], ['cpi_9606.ENSP00000370571', 'cpi_9606.ENSP00000351908', 'cpi_9606.ENSP00000338082', 'cpi_9606.ENSP00000348645', 'cpi_9606.ENSP00000267163'], ['cpi_9606.ENSP00000218548', 'cpi_9606.ENSP00000384273', 'cpi_9606.ENSP00000277120', 'cpi_9606.ENSP00000216962', 'cpi_9606.ENSP00000367309'], ['cpi_9606.ENSP00000262623', 'cpi_9606.ENSP00000360266', 'cpi_9606.ENSP00000270474', 'cpi_9606.ENSP00000226413', 'cpi_9606.ENSP00000252321'], ['cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000301974', 'cpi_9606.ENSP00000219919', 'cpi_9606.ENSP00000379339'], ['cpi_9606.ENSP00000345096', 'cpi_9606.ENSP00000262735', 'cpi_9606.ENSP00000358730', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000216797'], ['cpi_9606.ENSP00000354511', 'cpi_9606.ENSP00000264832', 'cpi_9606.ENSP00000265723', 'cpi_9606.ENSP00000282397', 'cpi_9606.ENSP00000365380'], ['cpi_9606.ENSP00000234310', 'cpi_9606.ENSP00000234961', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000393312', 'cpi_9606.ENSP00000221515'], ['cpi_9606.ENSP00000350348', 'cpi_9606.ENSP00000358107', 'cpi_9606.ENSP00000275300', 'cpi_9606.ENSP00000264498', 'cpi_9606.ENSP00000253727'], ['cpi_9606.ENSP00000234111', 'cpi_9606.ENSP00000312673', 'cpi_9606.ENSP00000342560', 'cpi_9606.ENSP00000420168', 'cpi_9606.ENSP00000297268'], ['cpi_9606.ENSP00000266970', 'cpi_9606.ENSP00000256010', 'cpi_9606.ENSP00000225371', 'cpi_9606.ENSP00000322421', 'cpi_9606.ENSP00000231449'], ['cpi_9606.ENSP00000321584', 'cpi_9606.ENSP00000358511', 'cpi_9606.ENSP00000304895', 'cpi_9606.ENSP00000276431', 'cpi_9606.ENSP00000341045'], ['cpi_9606.ENSP00000375066', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000417281', 'cpi_9606.ENSP00000365016', 'cpi_9606.ENSP00000356825'], ['cpi_9606.ENSP00000378323', 'cpi_9606.ENSP00000239938', 'cpi_9606.ENSP00000333534', 'cpi_9606.ENSP00000303452', 'cpi_9606.ENSP00000223366'], ['cpi_9606.ENSP00000257497', 'cpi_9606.ENSP00000314508', 'cpi_9606.ENSP00000263464', 'cpi_9606.ENSP00000362508', 'cpi_9606.ENSP00000382659'], ['cpi_9606.ENSP00000285379', 'cpi_9606.ENSP00000386884', 'cpi_9606.ENSP00000253004', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000264896'], ['cpi_9606.ENSP00000265023', 'cpi_9606.ENSP00000228872', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000433821', 'cpi_9606.ENSP00000319170'], ['cpi_9606.ENSP00000364709', 'cpi_9606.ENSP00000338018', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000321106', 'cpi_9606.ENSP00000310447'], ['cpi_9606.ENSP00000363868', 'cpi_9606.ENSP00000384957', 'cpi_9606.ENSP00000336630', 'cpi_9606.ENSP00000268035', 'cpi_9606.ENSP00000308032'], ['cpi_9606.ENSP00000305742', 'cpi_9606.ENSP00000309103', 'cpi_9606.ENSP00000331736', 'cpi_9606.ENSP00000393333', 'cpi_9606.ENSP00000332116'], ['cpi_9606.ENSP00000331514', 'cpi_9606.ENSP00000244741', 'cpi_9606.ENSP00000234371', 'cpi_9606.ENSP00000346067', 'cpi_9606.ENSP00000248041'], ['cpi_9606.ENSP00000275493', 'cpi_9606.ENSP00000349577', 'cpi_9606.ENSP00000302846', 'cpi_9606.ENSP00000320401', 'cpi_9606.ENSP00000296511'], ['cpi_9606.ENSP00000355627', 'cpi_9606.ENSP00000301633', 'cpi_9606.ENSP00000441691', 'cpi_9606.ENSP00000369757', 'cpi_9606.ENSP00000459962'], ['cpi_9606.ENSP00000405573', 'cpi_9606.ENSP00000297469', 'cpi_9606.ENSP00000419692', 'cpi_9606.ENSP00000296674', 'cpi_9606.ENSP00000269571'], ['cpi_9606.ENSP00000358022', 'cpi_9606.ENSP00000287641', 'cpi_9606.ENSP00000262160', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000368104'], ['cpi_9606.ENSP00000225275', 'cpi_9606.ENSP00000379213', 'cpi_9606.ENSP00000211122', 'cpi_9606.ENSP00000164139', 'cpi_9606.ENSP00000358903'], ['cpi_9606.ENSP00000368349', 'cpi_9606.ENSP00000321821', 'cpi_9606.ENSP00000245457', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000225577'], ['cpi_9606.ENSP00000332549', 'cpi_9606.ENSP00000360968', 'cpi_9606.ENSP00000362401', 'cpi_9606.ENSP00000341885', 'cpi_9606.ENSP00000285238'], ['cpi_9606.ENSP00000369647', 'cpi_9606.ENSP00000335620', 'cpi_9606.ENSP00000348461', 'cpi_9606.ENSP00000356694', 'cpi_9606.ENSP00000251566'], ['cpi_9606.ENSP00000260302', 'cpi_9606.ENSP00000324173', 'cpi_9606.ENSP00000371554', 'cpi_9606.ENSP0000021

🔄 Processing features: 100%|██████████| 1607/1607 [06:50<00:00,  3.91feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'cpi_9606.ENSP00000326219', 'cpi_9606.ENSP00000320866', 'cpi_9606.ENSP00000356094', 'cpi_9606.ENSP00000374323'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000309818', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000360773'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000355629', 'cpi_9606.ENSP00000367848', 'cpi_9606.ENSP00000332296'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000414334'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000301891', 'cpi_9606.ENSP00000261937'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000292513'], ['cpi_9606.ENSP00000360372', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000307014', 'cpi_9606.ENSP00000261799', 'cpi_9606.ENSP00000357068'], ['cpi_9606.ENSP00000311032', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000359353', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000299847'], ['cpi_9606.ENSP00000265724', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000337335'], ['cpi_9606.ENSP00000231509', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000417229'], ['cpi_9606.ENSP00000367959', 'cpi_9606.ENSP00000301634', 'cpi_9606.ENSP00000242057', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000264318'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000312664', 'cpi_9606.ENSP00000381097'], ['cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000344192', 'cpi_9606.ENSP00000326119', 'cpi_9606.ENSP00000342235'], ['cpi_9606.ENSP00000272190', 'cpi_9606.ENSP00000354476', 'cpi_9606.ENSP00000301178', 'cpi_9606.ENSP00000275525', 'cpi_9606.ENSP00000457706'], ['cpi_9606.ENSP00000369960', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000267101'], ['cpi_9606.ENSP00000264381', 'cpi_9606.ENSP00000319788', 'cpi_9606.ENSP00000216037', 'cpi_9606.ENSP00000360493', 'cpi_9606.ENSP00000386306'], ['cpi_9606.ENSP00000337450', 'cpi_9606.ENSP00000262441', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000351209', 'cpi_9606.ENSP00000389338'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000395653', 'cpi_9606.ENSP00000277010'], ['cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000263321', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000367102', 'cpi_9606.ENSP00000348897'], ['cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000316786', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000261693', 'cpi_9606.ENSP00000299267'], ['cpi_9606.ENSP00000270349', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000266376', 'cpi_9606.ENSP00000312455', 'cpi_9606.ENSP00000279178'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000362353', 'cpi_9606.ENSP00000362649', 'cpi_9606.ENSP00000286301', 'cpi_9606.ENSP00000342850'], ['cpi_9606.ENSP00000260433', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000257290', 'cpi_9606.ENSP00000430684', 'cpi_9606.ENSP00000298472'], ['cpi_9606.ENSP00000258743', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000264818', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000352900'], ['cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000370381', 'cpi_9606.ENSP00000369375'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000377947'], ['cpi_9606.ENSP00000305372', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000283635', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000454071'], ['cpi_9606.ENSP00000270202', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000387946', 'cpi_9606.ENSP00000258749'], ['cpi_9606.ENSP00000356438', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000394936', 'cpi_9606.ENSP00000295454', 'cpi_9606.ENSP00000361206'], ['cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000322924', 'cpi_9606.ENSP00000251535', 'cpi_9606.ENSP00000241453'], ['cpi_9606.ENSP00000363822', 'cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000274547', 'cpi_9606.ENSP00000307599', 'cpi_9606.ENSP00000261196'], ['cpi_9606.ENSP00000297494', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000264637'], ['cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000389414', 'cpi_9606.ENSP00000222330'], ['cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000356954', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000435591'], ['cpi_9606.ENSP00000337949', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000428340', 'cpi_9606.ENSP00000376943', 'cpi_9606.ENSP00000221972'], ['cpi_9606.ENSP00000354612', 'cpi_9606.ENSP00000348069', 'cpi_9606.ENSP00000378517', 'cpi_9606.ENSP00000252723', 'cpi_9606.ENSP00000291295'], ['cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000233242', 'cpi_9606.ENSP00000331912', 'cpi_9606.ENSP00000302111', 'cpi_9606.ENSP00000259089'], ['cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000414303', 'cpi_9606.ENSP00000347942', 'cpi_9606.ENSP00000252809', 'cpi_9606.ENSP00000471569'], ['cpi_9606.ENSP00000280155', 'cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000325822'], ['cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000410294', 'cpi_9606.ENSP00000349577', 'cpi_9606.ENSP00000363812'], ['cpi_9606.ENSP00000366506', 'cpi_9606.ENSP00000225474', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000358548'], ['cpi_9606.ENSP00000354859', 'cpi_9606.ENSP00000359478', 'cpi_9606.ENSP00000362036', 'cpi_9606.ENSP00000361359', 'cpi_9606.ENSP00000320025'], ['cpi_9606.ENSP00000258400', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000293288', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000000442'], ['cpi_9606.ENSP00000269305', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000367851', 'cpi_9606.ENSP00000267119'], ['cpi_9606.ENSP00000398698', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000220616', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000333212'], ['cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000364805', 'cpi_9606.ENSP00000289753'], ['cpi_9606.ENSP00000295897', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000353292', 'cpi_9606.ENSP00000248553', 'cpi_9606.ENSP00000368766'], ['cpi_9606.ENSP00000237014', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000354558', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000276198'], ['cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000241261', 'cpi_9606.ENSP00000260010', 'cpi_9606.ENSP00000309124', 'cpi_9606.ENSP00000263126'], ['cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000262461', 'cpi_9606.ENSP00000320935'], ['cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000343040', 'cpi_9606.ENSP00000358595'], ['cpi_9606.ENSP00000263025', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000259396', 'cpi_9606.ENSP00000451040', 'cpi_9606.ENSP00000216962'], ['cpi_9606.ENSP00000215832', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000274793', 'cpi_9606.ENSP00000290349'], ['cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000361666', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000343477', 'cpi_9606.ENSP00000292896'], ['cpi_9606.ENSP00000316244', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000344352'], ['cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000329623', 'cpi_9606.ENSP00000295491', 'cpi_9606.ENSP00000386069', 'cpi_9606.ENSP00000294728'], ['cpi_9606.ENSP00000330237', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000327431', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000398632'], ['cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000226574', 'cpi_9606.ENSP00000470087'], ['cpi_9606.ENSP00000306245', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000332369', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000300061'], ['cpi_9606.ENSP00000411532', 'cpi_9606.ENSP00000355930', 'cpi_9606.ENSP00000308165', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000308774'], ['cpi_9606.ENSP00000308541', 'cpi_9606.ENSP00000282561', 'cpi_9606.ENSP00000256383', 'cpi_9606.ENSP00000304822', 'cpi_9606.ENSP00000255465'], ['cpi_9606.ENSP00000302150', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000252029', 'cpi_9606.ENSP00000231454', 'cpi_9606.ENSP00000310928'], ['cpi_9606.ENSP00000387281', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000221421'], ['cpi_9606.ENSP00000306512', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000297350', 'cpi_9606.ENSP00000262888'], ['cpi_9606.ENSP00000252945', 'cpi_9606.ENSP00000353915', 'cpi_9606.ENSP00000323568', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000219919'], ['cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000312029', 'cpi_9606.ENSP00000267843', 'cpi_9606.ENSP00000463999'], ['cpi_9606.ENSP00000237612', 'cpi_9606.ENSP00000254976', 'cpi_9606.ENSP00000445340', 'cpi_9606.ENSP00000311095', 'cpi_9606.ENSP00000307240'], ['cpi_9606.ENSP00000358963', 'cpi_9606.ENSP00000357204', 'cpi_9606.ENSP00000353878', 'cpi_9606.ENSP00000225964', 'cpi_9606.ENSP00000256958'], ['cpi_9606.ENSP00000225831', 'cpi_9606.ENSP00000364802', 'cpi_9606.ENSP00000339527', 'cpi_9606.ENSP00000359635', 'cpi_9606.ENSP00000301645'], ['cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000357283', 'cpi_9606.ENSP00000356694'], ['cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000270474'], ['cpi_9606.ENSP00000270142', 'cpi_9606.ENSP00000400175', 'cpi_9606.ENSP00000276449', 'cpi_9606.ENSP00000382659', 'cpi_9606.ENSP00000358784'], ['cpi_9606.ENSP00000366084', 'cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000262367', 'cpi_9606.ENSP00000356671', 'cpi_9606.ENSP00000260356'], ['cpi_9606.ENSP00000355759', 'cpi_9606.ENSP00000218548', 'cpi_9606.ENSP00000427514', 'cpi_9606.ENSP00000373169', 'cpi_9606.ENSP00000295834'], ['cpi_9606.ENSP00000412237', 'cpi_9606.ENSP00000327801', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000306662'], ['cpi_9606.ENSP00000220764', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000176183', 'cpi_9606.ENSP00000329357', 'cpi_9606.ENSP00000297268'], ['cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000366307', 'cpi_9606.ENSP00000372023', 'cpi_9606.ENSP00000307235', 'cpi_9606.ENSP00000327652'], ['cpi_9606.ENSP00000361405', 'cpi_9606.ENSP00000355325', 'cpi_9606.ENSP00000365663', 'cpi_9606.ENSP00000296871', 'cpi_9606.ENSP00000282397'], ['cpi_9606.ENSP00000344456', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000448059', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000164139'], ['cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000263341', 'cpi_9606.ENSP00000354394', 'cpi_9606.ENSP00000311028', 'cpi_9606.ENSP00000352702'], ['cpi_9606.ENSP00000287820', 'cpi_9606.ENSP00000345502', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000388648', 'cpi_9606.ENSP00000306129'], ['cpi_9606.ENSP00000219070', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000353791', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000341045'], ['cpi_9606.ENSP00000387662', 'cpi_9606.ENSP00000305221', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000318822', 'cpi_9606.ENSP00000332816'], ['cpi_9606.ENSP00000234111', 'cpi_9606.ENSP00000263980', 'cpi_9606.ENSP00000371554', 'cpi_9606.ENSP00000252486', 'cpi_9606.ENSP00000358730'], ['cpi_9606.ENSP00000274353', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000313661', 'cpi_9606.ENSP00000200676', 'cpi_9606.ENSP00000262948'], ['cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000367309', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000355533', 'cpi_9606.ENSP00000428924'], ['cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000368104', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000294954'], ['cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000321988', 'cpi_9606.ENSP00000331358', 'cpi_9606.ENSP00000239849', 'cpi_9606.ENSP00000263923'], ['cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000212015', 'cpi_9606.ENSP00000176763', 'cpi_9606.ENSP00000355778', 'cpi_9606.ENSP00000418532'], ['cpi_9606.ENSP00000290866', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000303452', 'cpi_9606.ENSP00000338548', 'cpi_9606.ENSP00000346598'], ['cpi_9606.ENSP00000284981', 'cpi_9606.ENSP00000384273', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000340820', 'cpi_9606.ENSP00000320401'], ['cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000211287', 'cpi_9606.ENSP00000459962', 'cpi_9606.ENSP00000311469'], ['cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000307766', 'cpi_9606.ENSP00000394033', 'cpi_9606.ENSP00000309757'], ['cpi_9606.ENSP00000331746', 'cpi_9606.ENSP00000356729', 'cpi_9606.ENSP00000319591', 'cpi_9606.ENSP00000303174', 'cpi_9606.ENSP00000380252'], ['cpi_9606.ENSP00000464149', 'cpi_9606.ENSP00000378699', 'cpi_9606.ENSP00000381333', 'cpi_9606.ENSP00000221515', 'cpi_9606.ENSP00000353427'], ['cpi_9606.ENSP00000303522', 'cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000285979', 'cpi_9606.ENSP00000231228', 'cpi_9606.ENSP00000292095'], ['cpi_9606.ENSP00000327251', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000216392', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000254066'], ['cpi_9606.ENSP00000223095', 'cpi_9606.ENSP00000362924', 'cpi_9606.ENSP00000420168', 'cpi_9606.ENSP00000287907', 'cpi_9606.ENSP00000275300'], ['cpi_9606.ENSP00000264832', 'cpi_9606.ENSP00000405573', 'cpi_9606.ENSP00000410076', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000355920'], ['cpi_9606.ENSP00000358327', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000356832', 'cpi_9606.ENSP00000337773', 'cpi_9606.ENSP00000365380'], ['cpi_9606.ENSP00000257497', 'cpi_9606.ENSP00000314508', 'cpi_9606.ENSP00000330393', 'cpi_9606.ENSP00000287936', 'cpi_9606.ENSP00000355657'], ['cpi_9606.ENSP00000352835', 'cpi_9606.ENSP00000264657', 'cpi_9606.ENSP00000360967', 'cpi_9606.ENSP00000355317', 'cpi_9606.ENSP00000376178'], ['cpi_9606.ENSP00000315644', 'cpi_9606.ENSP00000312652', 'cpi_9606.ENSP00000245457', 'cpi_9606.ENSP00000270776', 'cpi_9606.ENSP00000430432'], ['cpi_9606.ENSP00000340684', 'cpi_9606.ENSP00000278616', 'cpi_9606.ENSP00000309968', 'cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000296545'], ['cpi_9606.ENSP00000337459', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000270625', 'cpi_9606.ENSP00000304915', 'cpi_9606.ENSP00000304845'], ['cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000295598', 'cpi_9606.ENSP00000347979', 'cpi_9606.ENSP00000360973', 'cpi_9606.ENSP00000365016'], ['cpi_9606.ENSP00000305742', 'cpi_9606.ENSP00000264867', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000393312', 'cpi_9606.ENSP00000266682'], ['cpi_9606.ENSP00000338018', 'cpi_9606.ENSP00000399168', 'cpi_9606.ENSP00000419692', 'cpi_9606.ENSP00000234961', 'cpi_9606.ENSP00000434364'], ['cpi_9606.ENSP00000394624', 'cpi_9606.ENSP00000262160', 'cpi_9606.ENSP00000305302', 'cpi_9606.ENSP00000429374', 'cpi_9606.ENSP00000386171'], ['cpi_9606.ENSP00000368438', 'cpi_9606.ENSP00000336630', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000254488'], ['cpi_9606.ENSP00000216117', 'cpi_9606.ENSP00000282753', 'cpi_9606.ENSP00000232219', 'cpi_9606.ENSP00000368632', 'cpi_9606.ENSP00000385806'], ['cpi_9606.ENSP00000265572', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000295400', 'cpi_9606.ENSP00000330199', 'cpi_9606.ENSP00000296674'], ['cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000275216', 'cpi_9606.ENSP00000354107', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000419782'], ['cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000350348', 'cpi_9606.ENSP00000417281', 'cpi_9606.ENSP00000225927', 'cpi_9606.ENSP00000346298'], ['cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000358107', 'cpi_9606.ENSP00000304895', 'cpi_9606.ENSP00000338627', 'cpi_9606.ENSP00000467676'], ['cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000343204', 'cpi_9606.ENSP00000239938', 'cpi_9606.ENSP00000351885', 'cpi_9606.ENSP00000354569'], ['cpi_9606.ENSP00000321584', 'cpi_9606.ENSP00000370473', 'cpi_9606.ENSP00000451030', 'cpi_9606.ENSP00000265723', 'cpi_9606.ENSP00000260970'], ['cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000253004', 'cpi_9606.ENSP00000342560', 'cpi_9606.ENSP00000265403', 'cpi_9606.ENSP00000302967'], ['cpi_9606.ENSP00000229135', 'cpi_9606.ENSP00000384957', 'cpi_9606.ENSP00000369757', 'cpi_9606.ENSP00000301146', 'cpi_9606.ENSP00000321106'], ['cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000262735', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000299178', 'cpi_9606.ENSP00000310447'], ['cpi_9606.ENSP00000345096', 'cpi_9606.ENSP00000386229', 'cpi_9606.ENSP00000228872', 'cpi_9606.ENSP00000356825', 'cpi_9606.ENSP00000231449'], ['cpi_9606.ENSP00000349467', 'cpi_9606.ENSP00000387683', 'cpi_9606.ENSP00000291294', 'cpi_9606.ENSP00000352584', 'cpi_9606.ENSP00000344674'], ['cpi_9606.ENSP00000317842', 'cpi_9606.ENSP00000233146', 'cpi_9606.ENSP00000277120', 'cpi_9606.ENSP00000317379', 'cpi_9606.ENSP00000324270'], ['cpi_9606.ENSP00000309845', 'cpi_9606.ENSP00000308032', 'cpi_9606.ENSP00000302846', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000274026'], ['cpi_9606.ENSP00000363868', 'cpi_9606.ENSP00000287641', 'cpi_9606.ENSP00000418960', 'cpi_9606.ENSP00000288135', 'cpi_9606.ENSP00000366662'], ['cpi_9606.ENSP00000260302', 'cpi_9606.ENSP00000369050', 'cpi_9606.ENSP00000362401', 'cpi_9606.ENSP00000356150', 'cpi_9606.ENSP00000296122'], ['cpi_9606.ENSP00000262623', 'cpi_9606.ENSP00000360266', 'cpi_9606.ENSP00000320709', 'cpi_9606.ENSP00000303424', 'cpi_9606.ENSP00000211122'], ['cpi_9606.ENSP00000301141', 'cpi_9606.ENSP00000301974', 'cpi_9606.ENSP00000251453', 'cpi_9606.ENSP00000244741', 'cpi_9606.ENSP00000268251'], ['cpi_9606.ENSP00000225275', 'cpi_9606.ENSP00000379213', 'cpi_9606.ENSP00000322421', 'cpi_9606.ENSP00000398655', 'cpi_9606.ENSP00000368683'], ['cpi_9606.ENSP00000273550', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000358511', 'cpi_9606.ENSP00000264896', 'cpi_9606.ENSP00000341885'], ['cpi_9606.ENSP00000358022', 'cpi_9606.ENSP00000217305', 'cpi_9606.ENSP00000311165', 'cpi_9606.ENSP00000253727', 'cpi_9606.ENSP00000346148'], ['cpi_9606.ENSP00000354511', 'cpi_9606.ENSP00000353483', 'cpi_9606.ENSP00000359793', 'cpi_9606.ENSP00000288602', 'cpi_9606.ENSP00000333534'], ['cpi_9606.ENSP00000375066', 'cpi_9606.ENSP00000288022', 'cpi_9606.ENSP00000368880', 'cpi_9606.ENSP00000268053', 'cpi_9606.ENSP00000264498'], ['cpi_9606.ENSP00000262407', 'cpi_9606.ENSP00000273430', 'cpi_9606.ENSP00000263464', 'cpi_9606.ENSP00000362508', 'cpi_9606.ENSP00000292303'], ['cpi_9606.ENSP00000275493', 'cpi_9606.ENSP00000308549', 'cpi_9606.ENSP00000359998', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000466799'], ['cpi_9606.ENSP00000352608', 'cpi_9606.ENSP00000319814', 'cpi_9606.ENSP00000269571', 'cpi_9606.ENSP00000333821', 'cpi_9606.ENSP00000272298'], ['cpi_9606.ENSP00000279387', 'cpi_9606.ENSP00000360968', 'cpi_9606.ENSP00000278175', 'cpi_9606.ENSP00000357981', 'cpi_9606.ENSP00000225577'], ['cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000377192', 'cpi_9606.ENSP00000226413', 'cpi_9606.ENSP00000368752', 'cpi_9606.ENSP00000359100'], ['cpi_9606.ENSP00000266970', 'cpi_9606.ENSP00000335544', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000331736', 'cpi_9606.ENSP00000215659'], ['cpi_9606.ENSP00000252321', 'cpi_9606.ENSP00000393333', 'cpi_9606.ENSP00000356198', 'cpi_9606.ENSP00000362513', 'cpi_9606.ENSP00000435777'], ['cpi_9606.ENSP00000354850', 'cpi_9606.ENSP00000276571', 'cpi_9606.ENSP00000309103', 'cpi_9606.ENSP0000029

🔄 Processing features: 100%|██████████| 1607/1607 [06:50<00:00,  3.91feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'cpi_9606.ENSP00000357669', 'cpi_9606.ENSP00000356094', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000297350'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000261937', 'cpi_9606.ENSP00000430684'], ['cpi_9606.ENSP00000360372', 'cpi_9606.ENSP00000309818', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000355629', 'cpi_9606.ENSP00000267119'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000274547', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000342235'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000355657'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000301891'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000360773', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000451040'], ['cpi_9606.ENSP00000265724', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000362810', 'cpi_9606.ENSP00000411593'], ['cpi_9606.ENSP00000311032', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000370381', 'cpi_9606.ENSP00000003100'], ['cpi_9606.ENSP00000231509', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000410076'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000312664', 'cpi_9606.ENSP00000374323'], ['cpi_9606.ENSP00000367959', 'cpi_9606.ENSP00000337335', 'cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000321584', 'cpi_9606.ENSP00000417229'], ['cpi_9606.ENSP00000272190', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000220616', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000259396'], ['cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000305372', 'cpi_9606.ENSP00000259089', 'cpi_9606.ENSP00000355778', 'cpi_9606.ENSP00000295454'], ['cpi_9606.ENSP00000264381', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000319788', 'cpi_9606.ENSP00000267843', 'cpi_9606.ENSP00000216037'], ['cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000263321', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000414334', 'cpi_9606.ENSP00000354476'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000301634', 'cpi_9606.ENSP00000299178', 'cpi_9606.ENSP00000445340', 'cpi_9606.ENSP00000221972'], ['cpi_9606.ENSP00000369960', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000279178', 'cpi_9606.ENSP00000267101'], ['cpi_9606.ENSP00000258743', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000352608', 'cpi_9606.ENSP00000257290', 'cpi_9606.ENSP00000395653'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000261196'], ['cpi_9606.ENSP00000260433', 'cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000389338', 'cpi_9606.ENSP00000261799'], ['cpi_9606.ENSP00000363822', 'cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000299267', 'cpi_9606.ENSP00000410294'], ['cpi_9606.ENSP00000270349', 'cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000367102', 'cpi_9606.ENSP00000347942', 'cpi_9606.ENSP00000343477'], ['cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000344352'], ['cpi_9606.ENSP00000337450', 'cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000319170', 'cpi_9606.ENSP00000251535', 'cpi_9606.ENSP00000386029'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000263126', 'cpi_9606.ENSP00000308774', 'cpi_9606.ENSP00000252519'], ['cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000237014', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000200676', 'cpi_9606.ENSP00000367848'], ['cpi_9606.ENSP00000297494', 'cpi_9606.ENSP00000277010', 'cpi_9606.ENSP00000471569', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000332296'], ['cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000266376', 'cpi_9606.ENSP00000359353', 'cpi_9606.ENSP00000351957'], ['cpi_9606.ENSP00000270202', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000331912', 'cpi_9606.ENSP00000353915', 'cpi_9606.ENSP00000352900'], ['cpi_9606.ENSP00000356438', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000394936', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000381097'], ['cpi_9606.ENSP00000398698', 'cpi_9606.ENSP00000394033', 'cpi_9606.ENSP00000252029', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000178638'], ['cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000274793', 'cpi_9606.ENSP00000343040'], ['cpi_9606.ENSP00000337949', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000278616'], ['cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000302111', 'cpi_9606.ENSP00000256958'], ['cpi_9606.ENSP00000316244', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000283635', 'cpi_9606.ENSP00000307014', 'cpi_9606.ENSP00000323568'], ['cpi_9606.ENSP00000354859', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000320935', 'cpi_9606.ENSP00000427562'], ['cpi_9606.ENSP00000354612', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000348069', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000304822'], ['cpi_9606.ENSP00000215832', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000359910', 'cpi_9606.ENSP00000338548'], ['cpi_9606.ENSP00000280155', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000221515'], ['cpi_9606.ENSP00000358963', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000357204', 'cpi_9606.ENSP00000417281', 'cpi_9606.ENSP00000225964'], ['cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000258400', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000387946'], ['cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000398632', 'cpi_9606.ENSP00000252809', 'cpi_9606.ENSP00000402608'], ['cpi_9606.ENSP00000295897', 'cpi_9606.ENSP00000378517', 'cpi_9606.ENSP00000282397', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000361359'], ['cpi_9606.ENSP00000306245', 'cpi_9606.ENSP00000332369', 'cpi_9606.ENSP00000314508', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000365686'], ['cpi_9606.ENSP00000269305', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000389414', 'cpi_9606.ENSP00000176763', 'cpi_9606.ENSP00000307240'], ['cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000367851', 'cpi_9606.ENSP00000275525'], ['cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000365233', 'cpi_9606.ENSP00000352035'], ['cpi_9606.ENSP00000330237', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000292896', 'cpi_9606.ENSP00000264637', 'cpi_9606.ENSP00000470087'], ['cpi_9606.ENSP00000263025', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000355325', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000368632'], ['cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000414303', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000245206'], ['cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000316786', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000261693', 'cpi_9606.ENSP00000343204'], ['cpi_9606.ENSP00000344456', 'cpi_9606.ENSP00000252945', 'cpi_9606.ENSP00000295834', 'cpi_9606.ENSP00000263923', 'cpi_9606.ENSP00000245539'], ['cpi_9606.ENSP00000366506', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000326119'], ['cpi_9606.ENSP00000220764', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000222330', 'cpi_9606.ENSP00000336630', 'cpi_9606.ENSP00000358784'], ['cpi_9606.ENSP00000308541', 'cpi_9606.ENSP00000361666', 'cpi_9606.ENSP00000419692', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000339527'], ['cpi_9606.ENSP00000276198', 'cpi_9606.ENSP00000234111', 'cpi_9606.ENSP00000307599', 'cpi_9606.ENSP00000226574', 'cpi_9606.ENSP00000301178'], ['cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000301974', 'cpi_9606.ENSP00000318646', 'cpi_9606.ENSP00000318822'], ['cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000304845', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000467676', 'cpi_9606.ENSP00000308165'], ['cpi_9606.ENSP00000368766', 'cpi_9606.ENSP00000329623', 'cpi_9606.ENSP00000358107', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000254227'], ['cpi_9606.ENSP00000306512', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000353791', 'cpi_9606.ENSP00000428924', 'cpi_9606.ENSP00000312455'], ['cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000318585', 'cpi_9606.ENSP00000242057', 'cpi_9606.ENSP00000457706', 'cpi_9606.ENSP00000365380'], ['cpi_9606.ENSP00000237612', 'cpi_9606.ENSP00000254976', 'cpi_9606.ENSP00000360967', 'cpi_9606.ENSP00000355317', 'cpi_9606.ENSP00000296871'], ['cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000293288', 'cpi_9606.ENSP00000262461', 'cpi_9606.ENSP00000306662', 'cpi_9606.ENSP00000368104'], ['cpi_9606.ENSP00000411532', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000344192', 'cpi_9606.ENSP00000309124', 'cpi_9606.ENSP00000369530'], ['cpi_9606.ENSP00000270142', 'cpi_9606.ENSP00000260356', 'cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000295491', 'cpi_9606.ENSP00000333212'], ['cpi_9606.ENSP00000302150', 'cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000359793', 'cpi_9606.ENSP00000353292'], ['cpi_9606.ENSP00000352835', 'cpi_9606.ENSP00000264657', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000258749'], ['cpi_9606.ENSP00000287820', 'cpi_9606.ENSP00000448059', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000340820', 'cpi_9606.ENSP00000358548'], ['cpi_9606.ENSP00000225831', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000372023', 'cpi_9606.ENSP00000262888'], ['cpi_9606.ENSP00000386069', 'cpi_9606.ENSP00000359478', 'cpi_9606.ENSP00000286301', 'cpi_9606.ENSP00000336762', 'cpi_9606.ENSP00000310447'], ['cpi_9606.ENSP00000387281', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000330393', 'cpi_9606.ENSP00000241261', 'cpi_9606.ENSP00000362401'], ['cpi_9606.ENSP00000284981', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000376943', 'cpi_9606.ENSP00000464149', 'cpi_9606.ENSP00000260191'], ['cpi_9606.ENSP00000412237', 'cpi_9606.ENSP00000327801', 'cpi_9606.ENSP00000254810', 'cpi_9606.ENSP00000294728', 'cpi_9606.ENSP00000463999'], ['cpi_9606.ENSP00000355759', 'cpi_9606.ENSP00000268053', 'cpi_9606.ENSP00000282753', 'cpi_9606.ENSP00000266682', 'cpi_9606.ENSP00000337773'], ['cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000260970', 'cpi_9606.ENSP00000252321', 'cpi_9606.ENSP00000296122', 'cpi_9606.ENSP00000360493'], ['cpi_9606.ENSP00000361405', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000216341', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000388648'], ['cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000288135', 'cpi_9606.ENSP00000254488', 'cpi_9606.ENSP00000359539', 'cpi_9606.ENSP00000356954'], ['cpi_9606.ENSP00000350348', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000234389', 'cpi_9606.ENSP00000252486', 'cpi_9606.ENSP00000225474'], ['cpi_9606.ENSP00000387662', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000359635', 'cpi_9606.ENSP00000354107'], ['cpi_9606.ENSP00000290866', 'cpi_9606.ENSP00000375066', 'cpi_9606.ENSP00000354394', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000356729'], ['cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000305742', 'cpi_9606.ENSP00000285979', 'cpi_9606.ENSP00000400175', 'cpi_9606.ENSP00000347979'], ['cpi_9606.ENSP00000218548', 'cpi_9606.ENSP00000223095', 'cpi_9606.ENSP00000391676', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000253122'], ['cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000226413', 'cpi_9606.ENSP00000317379', 'cpi_9606.ENSP00000330199'], ['cpi_9606.ENSP00000313661', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000361850', 'cpi_9606.ENSP00000225426', 'cpi_9606.ENSP00000394932'], ['cpi_9606.ENSP00000327652', 'cpi_9606.ENSP00000234310', 'cpi_9606.ENSP00000260010', 'cpi_9606.ENSP00000233146', 'cpi_9606.ENSP00000233242'], ['cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000355920', 'cpi_9606.ENSP00000305302', 'cpi_9606.ENSP00000356436'], ['cpi_9606.ENSP00000176183', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000297268', 'cpi_9606.ENSP00000350767'], ['cpi_9606.ENSP00000263341', 'cpi_9606.ENSP00000340684', 'cpi_9606.ENSP00000369654', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000275300'], ['cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000295598', 'cpi_9606.ENSP00000418960', 'cpi_9606.ENSP00000346298', 'cpi_9606.ENSP00000270570'], ['cpi_9606.ENSP00000327251', 'cpi_9606.ENSP00000338627', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000216392', 'cpi_9606.ENSP00000262948'], ['cpi_9606.ENSP00000394624', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000443459', 'cpi_9606.ENSP00000420168'], ['cpi_9606.ENSP00000306129', 'cpi_9606.ENSP00000317842', 'cpi_9606.ENSP00000263377', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000256383'], ['cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000264832', 'cpi_9606.ENSP00000260102', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000307235'], ['cpi_9606.ENSP00000262623', 'cpi_9606.ENSP00000384273', 'cpi_9606.ENSP00000277120', 'cpi_9606.ENSP00000367309', 'cpi_9606.ENSP00000255465'], ['cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000231228', 'cpi_9606.ENSP00000301141', 'cpi_9606.ENSP00000311165', 'cpi_9606.ENSP00000348827'], ['cpi_9606.ENSP00000289753', 'cpi_9606.ENSP00000260302', 'cpi_9606.ENSP00000301146', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000311121'], ['cpi_9606.ENSP00000216117', 'cpi_9606.ENSP00000359899', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000305221', 'cpi_9606.ENSP00000300061'], ['cpi_9606.ENSP00000315644', 'cpi_9606.ENSP00000303522', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000288602'], ['cpi_9606.ENSP00000265572', 'cpi_9606.ENSP00000288022', 'cpi_9606.ENSP00000312029', 'cpi_9606.ENSP00000311028', 'cpi_9606.ENSP00000370129'], ['cpi_9606.ENSP00000369050', 'cpi_9606.ENSP00000319591', 'cpi_9606.ENSP00000291294', 'cpi_9606.ENSP00000420487', 'cpi_9606.ENSP00000296370'], ['cpi_9606.ENSP00000373169', 'cpi_9606.ENSP00000277508', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000354558', 'cpi_9606.ENSP00000300900'], ['cpi_9606.ENSP00000358327', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000248041'], ['cpi_9606.ENSP00000236850', 'cpi_9606.ENSP00000381333', 'cpi_9606.ENSP00000282561', 'cpi_9606.ENSP00000365012', 'cpi_9606.ENSP00000333926'], ['cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000285238', 'cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000357283', 'cpi_9606.ENSP00000429374'], ['cpi_9606.ENSP00000337459', 'cpi_9606.ENSP00000384957', 'cpi_9606.ENSP00000435777', 'cpi_9606.ENSP00000365016', 'cpi_9606.ENSP00000311469'], ['cpi_9606.ENSP00000369647', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000231454', 'cpi_9606.ENSP00000428340', 'cpi_9606.ENSP00000280357'], ['cpi_9606.ENSP00000257497', 'cpi_9606.ENSP00000341045', 'cpi_9606.ENSP00000352584', 'cpi_9606.ENSP00000265164', 'cpi_9606.ENSP00000335511'], ['cpi_9606.ENSP00000345096', 'cpi_9606.ENSP00000262735', 'cpi_9606.ENSP00000331358', 'cpi_9606.ENSP00000252723', 'cpi_9606.ENSP00000351209'], ['cpi_9606.ENSP00000356022', 'cpi_9606.ENSP00000220809', 'cpi_9606.ENSP00000290349', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000322617'], ['cpi_9606.ENSP00000338018', 'cpi_9606.ENSP00000321988', 'cpi_9606.ENSP00000248076', 'cpi_9606.ENSP00000270625', 'cpi_9606.ENSP00000320401'], ['cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000301633', 'cpi_9606.ENSP00000259271', 'cpi_9606.ENSP00000369757', 'cpi_9606.ENSP00000354569'], ['cpi_9606.ENSP00000225275', 'cpi_9606.ENSP00000294954', 'cpi_9606.ENSP00000304895', 'cpi_9606.ENSP00000377192', 'cpi_9606.ENSP00000370912'], ['cpi_9606.ENSP00000386284', 'cpi_9606.ENSP00000368683', 'cpi_9606.ENSP00000303174', 'cpi_9606.ENSP00000253727', 'cpi_9606.ENSP00000307766'], ['cpi_9606.ENSP00000219070', 'cpi_9606.ENSP00000398655', 'cpi_9606.ENSP00000283646', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000338160'], ['cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000355930', 'cpi_9606.ENSP00000309103', 'cpi_9606.ENSP00000216962', 'cpi_9606.ENSP00000341885'], ['cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000295453', 'cpi_9606.ENSP00000335544', 'cpi_9606.ENSP00000351885', 'cpi_9606.ENSP00000211122'], ['cpi_9606.ENSP00000331746', 'cpi_9606.ENSP00000363868', 'cpi_9606.ENSP00000356671', 'cpi_9606.ENSP00000321821', 'cpi_9606.ENSP00000435412'], ['cpi_9606.ENSP00000354511', 'cpi_9606.ENSP00000380252', 'cpi_9606.ENSP00000331736', 'cpi_9606.ENSP00000362344', 'cpi_9606.ENSP00000362513'], ['cpi_9606.ENSP00000368305', 'cpi_9606.ENSP00000264498', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000385806'], ['cpi_9606.ENSP00000272298', 'cpi_9606.ENSP00000366084', 'cpi_9606.ENSP00000427514', 'cpi_9606.ENSP00000263980', 'cpi_9606.ENSP00000270776'], ['cpi_9606.ENSP00000307786', 'cpi_9606.ENSP00000384708', 'cpi_9606.ENSP00000228872', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000314649'], ['cpi_9606.ENSP00000309845', 'cpi_9606.ENSP00000308032', 'cpi_9606.ENSP00000245457', 'cpi_9606.ENSP00000264896', 'cpi_9606.ENSP00000349577'], ['cpi_9606.ENSP00000279387', 'cpi_9606.ENSP00000329357', 'cpi_9606.ENSP00000276571', 'cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000333534'], ['cpi_9606.ENSP00000312652', 'cpi_9606.ENSP00000340943', 'cpi_9606.ENSP00000265403', 'cpi_9606.ENSP00000333496', 'cpi_9606.ENSP00000216714'], ['cpi_9606.ENSP00000285379', 'cpi_9606.ENSP00000382659', 'cpi_9606.ENSP00000356694', 'cpi_9606.ENSP00000261479', 'cpi_9606.ENSP00000164139'], ['cpi_9606.ENSP00000356825', 'cpi_9606.ENSP00000407375', 'cpi_9606.ENSP00000311095', 'cpi_9606.ENSP00000348461', 'cpi_9606.ENSP00000324270'], ['cpi_9606.ENSP00000378323', 'cpi_9606.ENSP00000321106', 'cpi_9606.ENSP00000269571', 'cpi_9606.ENSP00000387683', 'cpi_9606.ENSP00000326219'], ['cpi_9606.ENSP00000368349', 'cpi_9606.ENSP00000362508', 'cpi_9606.ENSP00000303452', 'cpi_9606.ENSP00000287936', 'cpi_9606.ENSP00000386212'], ['cpi_9606.ENSP00000370571', 'cpi_9606.ENSP00000327431', 'cpi_9606.ENSP00000219919', 'cpi_9606.ENSP00000353878', 'cpi_9606.ENSP00000292513'], ['cpi_9606.ENSP00000322924', 'cpi_9606.ENSP00000264162', 'cpi_9606.ENSP00000251849', 'cpi_9606.ENSP00000310928', 'cpi_9606.ENSP00000296674'], ['cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000298171', 'cpi_9606.ENSP00000276449', 'cpi_9606.ENSP00000262187', 'cpi_9606.ENSP00000370373'], ['cpi_9606.ENSP00000349467', 'cpi_9606.ENSP00000262441', 'cpi_9606.ENSP00000244741', 'cpi_9606.ENSP00000319814', 'cpi_9606.ENSP00000332816'], ['cpi_9606.ENSP00000358022', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000260630', 'cpi_9606.ENSP00000349252', 'cpi_9606.ENSP00000359532'], ['cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000261465', 'cpi_9606.ENSP00000360266', 'cpi_9606.ENSP00000287907', 'cpi_9606.ENSP00000251566'], ['cpi_9606.ENSP00000229135', 'cpi_9606.ENSP00000359680', 'cpi_9606.ENSP00000359998', 'cpi_9606.ENSP00000276414', 'cpi_9606.ENSP00000393312'], ['cpi_9606.ENSP00000320709', 'cpi_9606.ENSP00000272847', 'cpi_9606.ENSP00000345774', 'cpi_9606.ENSP00000378699', 'cpi_9606.ENSP00000379339'], ['cpi_9606.ENSP00000302811', 'cpi_9606.ENSP00000227507', 'cpi_9606.ENSP00000344674', 'cpi_9606.ENSP00000272227', 'cpi_9606.ENSP00000387888'], ['cpi_9606.ENSP00000304915', 'cpi_9606.ENSP00000274606', 'cpi_9606.ENSP00000320866', 'cpi_9606.ENSP00000309757', 'cpi_9606.ENSP00000251453'], ['cpi_9606.ENSP00000234961', 'cpi_9606.ENSP00000219700', 'cpi_9606.ENSP00000232219', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000363115'], ['cpi_9606.ENSP00000273550', 'cpi_9606.ENSP00000239849', 'cpi_9606.ENSP00000363089', 'cpi_9606.ENSP0000036

🔄 Processing features: 100%|██████████| 1607/1607 [06:50<00:00,  3.91feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'cpi_9606.ENSP00000263321', 'cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000356094', 'cpi_9606.ENSP00000359424'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000355629', 'cpi_9606.ENSP00000395653'], ['cpi_9606.ENSP00000360372', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000296370'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000231228', 'cpi_9606.ENSP00000261937', 'cpi_9606.ENSP00000295452'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000262888'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000360773', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000265294'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000337335', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000312304'], ['cpi_9606.ENSP00000311032', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000367848', 'cpi_9606.ENSP00000445340'], ['cpi_9606.ENSP00000231509', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000218099'], ['cpi_9606.ENSP00000265724', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000299178', 'cpi_9606.ENSP00000359353', 'cpi_9606.ENSP00000291295'], ['cpi_9606.ENSP00000367959', 'cpi_9606.ENSP00000301634', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000242057', 'cpi_9606.ENSP00000369375'], ['cpi_9606.ENSP00000272190', 'cpi_9606.ENSP00000277010', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000410732'], ['cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000309818', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000358548', 'cpi_9606.ENSP00000225927'], ['cpi_9606.ENSP00000369960', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000274547'], ['cpi_9606.ENSP00000264381', 'cpi_9606.ENSP00000266376', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000319788', 'cpi_9606.ENSP00000342235'], ['cpi_9606.ENSP00000270349', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000367102', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000267101'], ['cpi_9606.ENSP00000258743', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000261799', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000394936'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000374323', 'cpi_9606.ENSP00000312664', 'cpi_9606.ENSP00000398632'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000274353', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000389338', 'cpi_9606.ENSP00000352900'], ['cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000283635'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000261196'], ['cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000363822', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000414334'], ['cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000394033', 'cpi_9606.ENSP00000257290', 'cpi_9606.ENSP00000279178'], ['cpi_9606.ENSP00000270202', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000258749', 'cpi_9606.ENSP00000377947'], ['cpi_9606.ENSP00000337450', 'cpi_9606.ENSP00000262441', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000216037'], ['cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000354476', 'cpi_9606.ENSP00000216962', 'cpi_9606.ENSP00000301891'], ['cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000295454'], ['cpi_9606.ENSP00000260433', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000347942', 'cpi_9606.ENSP00000387281'], ['cpi_9606.ENSP00000356438', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000332296', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000381097'], ['cpi_9606.ENSP00000305372', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000299267', 'cpi_9606.ENSP00000430684', 'cpi_9606.ENSP00000217426'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000428340'], ['cpi_9606.ENSP00000398698', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000301178', 'cpi_9606.ENSP00000220616', 'cpi_9606.ENSP00000387946'], ['cpi_9606.ENSP00000354612', 'cpi_9606.ENSP00000348069', 'cpi_9606.ENSP00000304822', 'cpi_9606.ENSP00000282397', 'cpi_9606.ENSP00000344352'], ['cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000255409'], ['cpi_9606.ENSP00000297494', 'cpi_9606.ENSP00000252029', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000417229'], ['cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000237612', 'cpi_9606.ENSP00000367851', 'cpi_9606.ENSP00000356671', 'cpi_9606.ENSP00000251535'], ['cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000233242', 'cpi_9606.ENSP00000358107', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000261835'], ['cpi_9606.ENSP00000337949', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000328973'], ['cpi_9606.ENSP00000215832', 'cpi_9606.ENSP00000471569', 'cpi_9606.ENSP00000307599', 'cpi_9606.ENSP00000341828', 'cpi_9606.ENSP00000333212'], ['cpi_9606.ENSP00000258400', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000302111', 'cpi_9606.ENSP00000343040'], ['cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000225474', 'cpi_9606.ENSP00000320709', 'cpi_9606.ENSP00000353915', 'cpi_9606.ENSP00000270776'], ['cpi_9606.ENSP00000316244', 'cpi_9606.ENSP00000359478', 'cpi_9606.ENSP00000221972', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000386029'], ['cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000316786', 'cpi_9606.ENSP00000321988', 'cpi_9606.ENSP00000286301', 'cpi_9606.ENSP00000331912'], ['cpi_9606.ENSP00000354859', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000344192', 'cpi_9606.ENSP00000340820', 'cpi_9606.ENSP00000309968'], ['cpi_9606.ENSP00000330237', 'cpi_9606.ENSP00000218548', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000254227'], ['cpi_9606.ENSP00000358963', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000275525', 'cpi_9606.ENSP00000248553'], ['cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000356954', 'cpi_9606.ENSP00000326119', 'cpi_9606.ENSP00000409378'], ['cpi_9606.ENSP00000280155', 'cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000255465', 'cpi_9606.ENSP00000389414'], ['cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000259396', 'cpi_9606.ENSP00000293745'], ['cpi_9606.ENSP00000366506', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000434516', 'cpi_9606.ENSP00000270474'], ['cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000361666', 'cpi_9606.ENSP00000332816', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000365663'], ['cpi_9606.ENSP00000306512', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000318912', 'cpi_9606.ENSP00000311095', 'cpi_9606.ENSP00000312455'], ['cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000236850', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000366662'], ['cpi_9606.ENSP00000295897', 'cpi_9606.ENSP00000378517', 'cpi_9606.ENSP00000311469', 'cpi_9606.ENSP00000259089', 'cpi_9606.ENSP00000361359'], ['cpi_9606.ENSP00000263025', 'cpi_9606.ENSP00000349577', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000295834', 'cpi_9606.ENSP00000304915'], ['cpi_9606.ENSP00000386069', 'cpi_9606.ENSP00000237014', 'cpi_9606.ENSP00000264867', 'cpi_9606.ENSP00000463999', 'cpi_9606.ENSP00000309572'], ['cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000286091', 'cpi_9606.ENSP00000310928', 'cpi_9606.ENSP00000454071', 'cpi_9606.ENSP00000340691'], ['cpi_9606.ENSP00000306245', 'cpi_9606.ENSP00000376943', 'cpi_9606.ENSP00000303830', 'cpi_9606.ENSP00000370381', 'cpi_9606.ENSP00000264637'], ['cpi_9606.ENSP00000276198', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000466799', 'cpi_9606.ENSP00000285930'], ['cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000357283', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000295491'], ['cpi_9606.ENSP00000411532', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000368766', 'cpi_9606.ENSP00000309124', 'cpi_9606.ENSP00000263126'], ['cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000231454', 'cpi_9606.ENSP00000470087', 'cpi_9606.ENSP00000317379'], ['cpi_9606.ENSP00000368438', 'cpi_9606.ENSP00000293288', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000274793'], ['cpi_9606.ENSP00000225831', 'cpi_9606.ENSP00000364802', 'cpi_9606.ENSP00000372023', 'cpi_9606.ENSP00000355930', 'cpi_9606.ENSP00000335511'], ['cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000378699', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000256958'], ['cpi_9606.ENSP00000269305', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000355920', 'cpi_9606.ENSP00000366927', 'cpi_9606.ENSP00000308165'], ['cpi_9606.ENSP00000302150', 'cpi_9606.ENSP00000273550', 'cpi_9606.ENSP00000261693', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000451040'], ['cpi_9606.ENSP00000387662', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000356729', 'cpi_9606.ENSP00000216392'], ['cpi_9606.ENSP00000355759', 'cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000362036', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000320866'], ['cpi_9606.ENSP00000414303', 'cpi_9606.ENSP00000327431', 'cpi_9606.ENSP00000363804', 'cpi_9606.ENSP00000375809', 'cpi_9606.ENSP00000297350'], ['cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000260302', 'cpi_9606.ENSP00000307235', 'cpi_9606.ENSP00000355533', 'cpi_9606.ENSP00000366307'], ['cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000355536', 'cpi_9606.ENSP00000356694', 'cpi_9606.ENSP00000320935'], ['cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000313661', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000360493'], ['cpi_9606.ENSP00000220764', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000306662', 'cpi_9606.ENSP00000263980', 'cpi_9606.ENSP00000311165'], ['cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000301974', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000242375'], ['cpi_9606.ENSP00000366084', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000309757', 'cpi_9606.ENSP00000305221', 'cpi_9606.ENSP00000343204'], ['cpi_9606.ENSP00000252945', 'cpi_9606.ENSP00000303522', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000353292', 'cpi_9606.ENSP00000219919'], ['cpi_9606.ENSP00000412237', 'cpi_9606.ENSP00000292896', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000252486', 'cpi_9606.ENSP00000388648'], ['cpi_9606.ENSP00000308541', 'cpi_9606.ENSP00000370473', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000332369', 'cpi_9606.ENSP00000232219'], ['cpi_9606.ENSP00000344456', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000164139', 'cpi_9606.ENSP00000448059', 'cpi_9606.ENSP00000358903'], ['cpi_9606.ENSP00000270142', 'cpi_9606.ENSP00000294728', 'cpi_9606.ENSP00000359635', 'cpi_9606.ENSP00000307014', 'cpi_9606.ENSP00000222330'], ['cpi_9606.ENSP00000287820', 'cpi_9606.ENSP00000264818', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000457706', 'cpi_9606.ENSP00000176183'], ['cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000252723', 'cpi_9606.ENSP00000289753', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000338548'], ['cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000263341', 'cpi_9606.ENSP00000309103', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000373169'], ['cpi_9606.ENSP00000223095', 'cpi_9606.ENSP00000362924', 'cpi_9606.ENSP00000382659', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000176763'], ['cpi_9606.ENSP00000327652', 'cpi_9606.ENSP00000216117', 'cpi_9606.ENSP00000302967', 'cpi_9606.ENSP00000310447', 'cpi_9606.ENSP00000386171'], ['cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000367309', 'cpi_9606.ENSP00000410294', 'cpi_9606.ENSP00000353427', 'cpi_9606.ENSP00000296122'], ['cpi_9606.ENSP00000394624', 'cpi_9606.ENSP00000301633', 'cpi_9606.ENSP00000200676', 'cpi_9606.ENSP00000312029', 'cpi_9606.ENSP00000241600'], ['cpi_9606.ENSP00000464149', 'cpi_9606.ENSP00000252809', 'cpi_9606.ENSP00000217305', 'cpi_9606.ENSP00000253727', 'cpi_9606.ENSP00000351885'], ['cpi_9606.ENSP00000219070', 'cpi_9606.ENSP00000361151', 'cpi_9606.ENSP00000340523', 'cpi_9606.ENSP00000343477', 'cpi_9606.ENSP00000398655'], ['cpi_9606.ENSP00000350348', 'cpi_9606.ENSP00000317842', 'cpi_9606.ENSP00000268053', 'cpi_9606.ENSP00000262948', 'cpi_9606.ENSP00000339260'], ['cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000226574', 'cpi_9606.ENSP00000263923', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000262160'], ['cpi_9606.ENSP00000234111', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000296871', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000355317'], ['cpi_9606.ENSP00000290866', 'cpi_9606.ENSP00000228872', 'cpi_9606.ENSP00000302811', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000276449'], ['cpi_9606.ENSP00000337459', 'cpi_9606.ENSP00000352035', 'cpi_9606.ENSP00000305692', 'cpi_9606.ENSP00000354394', 'cpi_9606.ENSP00000267119'], ['cpi_9606.ENSP00000327251', 'cpi_9606.ENSP00000354610', 'cpi_9606.ENSP00000358784', 'cpi_9606.ENSP00000329357', 'cpi_9606.ENSP00000307766'], ['cpi_9606.ENSP00000264832', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000407375', 'cpi_9606.ENSP00000287907', 'cpi_9606.ENSP00000300061'], ['cpi_9606.ENSP00000284981', 'cpi_9606.ENSP00000267843', 'cpi_9606.ENSP00000287936', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000459962'], ['cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000282753', 'cpi_9606.ENSP00000347979', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000330393'], ['cpi_9606.ENSP00000265572', 'cpi_9606.ENSP00000217961', 'cpi_9606.ENSP00000318822', 'cpi_9606.ENSP00000399168', 'cpi_9606.ENSP00000282561'], ['cpi_9606.ENSP00000361405', 'cpi_9606.ENSP00000287713', 'cpi_9606.ENSP00000308774', 'cpi_9606.ENSP00000263464', 'cpi_9606.ENSP00000306129'], ['cpi_9606.ENSP00000340684', 'cpi_9606.ENSP00000264657', 'cpi_9606.ENSP00000347046', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000263339'], ['cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000295598', 'cpi_9606.ENSP00000254079', 'cpi_9606.ENSP00000362401', 'cpi_9606.ENSP00000303174'], ['cpi_9606.ENSP00000358327', 'cpi_9606.ENSP00000296522', 'cpi_9606.ENSP00000371554', 'cpi_9606.ENSP00000248041', 'cpi_9606.ENSP00000261205'], ['cpi_9606.ENSP00000369050', 'cpi_9606.ENSP00000234310', 'cpi_9606.ENSP00000315011', 'cpi_9606.ENSP00000352608', 'cpi_9606.ENSP00000268035'], ['cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000296545', 'cpi_9606.ENSP00000341045', 'cpi_9606.ENSP00000322924', 'cpi_9606.ENSP00000362649'], ['cpi_9606.ENSP00000262623', 'cpi_9606.ENSP00000360266', 'cpi_9606.ENSP00000358730', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000420168'], ['cpi_9606.ENSP00000312652', 'cpi_9606.ENSP00000441691', 'cpi_9606.ENSP00000292513', 'cpi_9606.ENSP00000357669', 'cpi_9606.ENSP00000354558'], ['cpi_9606.ENSP00000315644', 'cpi_9606.ENSP00000277120', 'cpi_9606.ENSP00000321106', 'cpi_9606.ENSP00000260010', 'cpi_9606.ENSP00000337773'], ['cpi_9606.ENSP00000338018', 'cpi_9606.ENSP00000260649', 'cpi_9606.ENSP00000332256', 'cpi_9606.ENSP00000275300', 'cpi_9606.ENSP00000360973'], ['cpi_9606.ENSP00000331746', 'cpi_9606.ENSP00000353679', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000419782', 'cpi_9606.ENSP00000254488'], ['cpi_9606.ENSP00000378323', 'cpi_9606.ENSP00000304845', 'cpi_9606.ENSP00000297268', 'cpi_9606.ENSP00000308549', 'cpi_9606.ENSP00000358424'], ['cpi_9606.ENSP00000234961', 'cpi_9606.ENSP00000408695', 'cpi_9606.ENSP00000410076', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000365012'], ['cpi_9606.ENSP00000368683', 'cpi_9606.ENSP00000386284', 'cpi_9606.ENSP00000355657', 'cpi_9606.ENSP00000236671', 'cpi_9606.ENSP00000342560'], ['cpi_9606.ENSP00000369647', 'cpi_9606.ENSP00000241261', 'cpi_9606.ENSP00000353224', 'cpi_9606.ENSP00000353791', 'cpi_9606.ENSP00000339527'], ['cpi_9606.ENSP00000225275', 'cpi_9606.ENSP00000329623', 'cpi_9606.ENSP00000359793', 'cpi_9606.ENSP00000322421', 'cpi_9606.ENSP00000327850'], ['cpi_9606.ENSP00000301141', 'cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000265723', 'cpi_9606.ENSP00000300738', 'cpi_9606.ENSP00000337825'], ['cpi_9606.ENSP00000380252', 'cpi_9606.ENSP00000262407', 'cpi_9606.ENSP00000226413', 'cpi_9606.ENSP00000332116', 'cpi_9606.ENSP00000260356'], ['cpi_9606.ENSP00000257497', 'cpi_9606.ENSP00000397026', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000218388', 'cpi_9606.ENSP00000326219'], ['cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000375066', 'cpi_9606.ENSP00000304895', 'cpi_9606.ENSP00000359998', 'cpi_9606.ENSP00000393312'], ['cpi_9606.ENSP00000370571', 'cpi_9606.ENSP00000323568', 'cpi_9606.ENSP00000353878', 'cpi_9606.ENSP00000377192', 'cpi_9606.ENSP00000360991'], ['cpi_9606.ENSP00000298171', 'cpi_9606.ENSP00000320401', 'cpi_9606.ENSP00000244741', 'cpi_9606.ENSP00000266682', 'cpi_9606.ENSP00000382250'], ['cpi_9606.ENSP00000356825', 'cpi_9606.ENSP00000278616', 'cpi_9606.ENSP00000276414', 'cpi_9606.ENSP00000304408', 'cpi_9606.ENSP00000345502'], ['cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000384273', 'cpi_9606.ENSP00000346901', 'cpi_9606.ENSP00000427514'], ['cpi_9606.ENSP00000357204', 'cpi_9606.ENSP00000287641', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000212015', 'cpi_9606.ENSP00000359100'], ['cpi_9606.ENSP00000353731', 'cpi_9606.ENSP00000331358', 'cpi_9606.ENSP00000297258', 'cpi_9606.ENSP00000385806', 'cpi_9606.ENSP00000381607'], ['cpi_9606.ENSP00000285379', 'cpi_9606.ENSP00000400175', 'cpi_9606.ENSP00000292303', 'cpi_9606.ENSP00000305302', 'cpi_9606.ENSP00000225577'], ['cpi_9606.ENSP00000217133', 'cpi_9606.ENSP00000262735', 'cpi_9606.ENSP00000384957', 'cpi_9606.ENSP00000285979', 'cpi_9606.ENSP00000219700'], ['cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000374467', 'cpi_9606.ENSP00000335544', 'cpi_9606.ENSP00000001008', 'cpi_9606.ENSP00000346148'], ['cpi_9606.ENSP00000229135', 'cpi_9606.ENSP00000328173', 'cpi_9606.ENSP00000332679', 'cpi_9606.ENSP00000263088', 'cpi_9606.ENSP00000216911'], ['cpi_9606.ENSP00000266970', 'cpi_9606.ENSP00000354569', 'cpi_9606.ENSP00000225964', 'cpi_9606.ENSP00000312673', 'cpi_9606.ENSP00000362513'], ['cpi_9606.ENSP00000356022', 'cpi_9606.ENSP00000428924', 'cpi_9606.ENSP00000358511', 'cpi_9606.ENSP00000349252', 'cpi_9606.ENSP00000348645'], ['cpi_9606.ENSP00000354511', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000365380', 'cpi_9606.ENSP00000314508', 'cpi_9606.ENSP00000386229'], ['cpi_9606.ENSP00000355627', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000362344', 'cpi_9606.ENSP00000306100', 'cpi_9606.ENSP00000362549'], ['cpi_9606.ENSP00000231449', 'cpi_9606.ENSP00000264162', 'cpi_9606.ENSP00000248572', 'cpi_9606.ENSP00000360968', 'cpi_9606.ENSP00000303686'], ['cpi_9606.ENSP00000294954', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000349467', 'cpi_9606.ENSP00000338082'], ['cpi_9606.ENSP00000248437', 'cpi_9606.ENSP00000359899', 'cpi_9606.ENSP00000301146', 'cpi_9606.ENSP00000256078', 'cpi_9606.ENSP00000352584'], ['cpi_9606.ENSP00000368349', 'cpi_9606.ENSP00000221930', 'cpi_9606.ENSP00000324248', 'cpi_9606.ENSP00000262461', 'cpi_9606.ENSP00000387683'], ['cpi_9606.ENSP00000327801', 'cpi_9606.ENSP00000339191', 'cpi_9606.ENSP00000267377', 'cpi_9606.ENSP00000305355', 'cpi_9606.ENSP00000338627'], ['cpi_9606.ENSP00000265023', 'cpi_9606.ENSP00000430031', 'cpi_9606.ENSP00000351908', 'cpi_9606.ENSP00000362508', 'cpi_9606.ENSP00000368880'], ['cpi_9606.ENSP00000275493', 'cpi_9606.ENSP00000350198', 'cpi_9606.ENSP00000272227', 'cpi_9606.ENSP0000026

🔄 Processing features: 100%|██████████| 1607/1607 [06:50<00:00,  3.91feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000326219', 'cpi_9606.ENSP00000356094', 'cpi_9606.ENSP00000218388'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000355629', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000360773'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000359353', 'cpi_9606.ENSP00000299178'], ['cpi_9606.ENSP00000360372', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000261799', 'cpi_9606.ENSP00000372547'], ['cpi_9606.ENSP00000311032', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000367848', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000299847'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000257290', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000370381'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000430684', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000298472'], ['cpi_9606.ENSP00000265724', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000381097', 'cpi_9606.ENSP00000275525'], ['cpi_9606.ENSP00000367959', 'cpi_9606.ENSP00000337335', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000261937', 'cpi_9606.ENSP00000302111'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000395653', 'cpi_9606.ENSP00000274547'], ['cpi_9606.ENSP00000272190', 'cpi_9606.ENSP00000301178', 'cpi_9606.ENSP00000354476', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000410732'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000374323', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000312664'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000295491', 'cpi_9606.ENSP00000295454', 'cpi_9606.ENSP00000261196'], ['cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000332296', 'cpi_9606.ENSP00000342235'], ['cpi_9606.ENSP00000231509', 'cpi_9606.ENSP00000266376', 'cpi_9606.ENSP00000332369', 'cpi_9606.ENSP00000417229', 'cpi_9606.ENSP00000319788'], ['cpi_9606.ENSP00000369960', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000358548'], ['cpi_9606.ENSP00000264381', 'cpi_9606.ENSP00000279178', 'cpi_9606.ENSP00000389338', 'cpi_9606.ENSP00000259396', 'cpi_9606.ENSP00000355192'], ['cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000263321', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000367102', 'cpi_9606.ENSP00000471569'], ['cpi_9606.ENSP00000258743', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000259089', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000277010'], ['cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000220764', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000301891', 'cpi_9606.ENSP00000412673'], ['cpi_9606.ENSP00000270349', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000267101', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000316786'], ['cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000343040'], ['cpi_9606.ENSP00000356438', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000394936', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000216037'], ['cpi_9606.ENSP00000337450', 'cpi_9606.ENSP00000301634', 'cpi_9606.ENSP00000359793', 'cpi_9606.ENSP00000251535', 'cpi_9606.ENSP00000347942'], ['cpi_9606.ENSP00000305372', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000283635', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000274545'], ['cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000414303', 'cpi_9606.ENSP00000286301', 'cpi_9606.ENSP00000252809', 'cpi_9606.ENSP00000359334'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000262441', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000351209', 'cpi_9606.ENSP00000354394'], ['cpi_9606.ENSP00000363822', 'cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000414334', 'cpi_9606.ENSP00000285381'], ['cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000299267', 'cpi_9606.ENSP00000267119'], ['cpi_9606.ENSP00000270202', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000387946', 'cpi_9606.ENSP00000258749'], ['cpi_9606.ENSP00000260433', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000307014', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000343477'], ['cpi_9606.ENSP00000337949', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000394932'], ['cpi_9606.ENSP00000366506', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000225474', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000317379'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000451040'], ['cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000348069', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000386029'], ['cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000367851', 'cpi_9606.ENSP00000354558', 'cpi_9606.ENSP00000242057'], ['cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000233242', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000331912', 'cpi_9606.ENSP00000226574'], ['cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000419782', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000378517'], ['cpi_9606.ENSP00000297494', 'cpi_9606.ENSP00000353791', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000260010', 'cpi_9606.ENSP00000326119'], ['cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000312455', 'cpi_9606.ENSP00000411593'], ['cpi_9606.ENSP00000237014', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000387281', 'cpi_9606.ENSP00000344192'], ['cpi_9606.ENSP00000280155', 'cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000255465', 'cpi_9606.ENSP00000376943', 'cpi_9606.ENSP00000362036'], ['cpi_9606.ENSP00000354612', 'cpi_9606.ENSP00000222330', 'cpi_9606.ENSP00000304822', 'cpi_9606.ENSP00000294728', 'cpi_9606.ENSP00000356436'], ['cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000361666', 'cpi_9606.ENSP00000356954', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000334198'], ['cpi_9606.ENSP00000316244', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000344352', 'cpi_9606.ENSP00000000442'], ['cpi_9606.ENSP00000269305', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000389414', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000264637'], ['cpi_9606.ENSP00000354859', 'cpi_9606.ENSP00000359478', 'cpi_9606.ENSP00000221972', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000216962'], ['cpi_9606.ENSP00000398698', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000220616', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000408860'], ['cpi_9606.ENSP00000308541', 'cpi_9606.ENSP00000361359', 'cpi_9606.ENSP00000263126', 'cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000470087'], ['cpi_9606.ENSP00000258400', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000260356', 'cpi_9606.ENSP00000262888', 'cpi_9606.ENSP00000410294'], ['cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000427514', 'cpi_9606.ENSP00000176763', 'cpi_9606.ENSP00000307599', 'cpi_9606.ENSP00000256958'], ['cpi_9606.ENSP00000306245', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000360493', 'cpi_9606.ENSP00000394033'], ['cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000296545', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000448059'], ['cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000398632', 'cpi_9606.ENSP00000300061', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000386069'], ['cpi_9606.ENSP00000330237', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000292896', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000276198'], ['cpi_9606.ENSP00000263025', 'cpi_9606.ENSP00000274793', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000349252'], ['cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000329623', 'cpi_9606.ENSP00000262367', 'cpi_9606.ENSP00000368766', 'cpi_9606.ENSP00000252486'], ['cpi_9606.ENSP00000215832', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000353292', 'cpi_9606.ENSP00000362344', 'cpi_9606.ENSP00000262999'], ['cpi_9606.ENSP00000252945', 'cpi_9606.ENSP00000298171', 'cpi_9606.ENSP00000357283', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000211122'], ['cpi_9606.ENSP00000295897', 'cpi_9606.ENSP00000457706', 'cpi_9606.ENSP00000276449', 'cpi_9606.ENSP00000297350', 'cpi_9606.ENSP00000308774'], ['cpi_9606.ENSP00000358963', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000252723', 'cpi_9606.ENSP00000261693'], ['cpi_9606.ENSP00000411532', 'cpi_9606.ENSP00000355930', 'cpi_9606.ENSP00000308165', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000270776'], ['cpi_9606.ENSP00000306512', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000368632', 'cpi_9606.ENSP00000306662', 'cpi_9606.ENSP00000305422'], ['cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000309124', 'cpi_9606.ENSP00000351885'], ['cpi_9606.ENSP00000237612', 'cpi_9606.ENSP00000357981', 'cpi_9606.ENSP00000330393', 'cpi_9606.ENSP00000333212', 'cpi_9606.ENSP00000336630'], ['cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000323568', 'cpi_9606.ENSP00000332816'], ['cpi_9606.ENSP00000366084', 'cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000312029', 'cpi_9606.ENSP00000428340'], ['cpi_9606.ENSP00000344456', 'cpi_9606.ENSP00000309757', 'cpi_9606.ENSP00000282561', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000445340'], ['cpi_9606.ENSP00000225831', 'cpi_9606.ENSP00000248553', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000353915', 'cpi_9606.ENSP00000359635'], ['cpi_9606.ENSP00000302150', 'cpi_9606.ENSP00000293288', 'cpi_9606.ENSP00000364212', 'cpi_9606.ENSP00000320935', 'cpi_9606.ENSP00000371985'], ['cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000304845', 'cpi_9606.ENSP00000467676', 'cpi_9606.ENSP00000200676', 'cpi_9606.ENSP00000386171'], ['cpi_9606.ENSP00000284981', 'cpi_9606.ENSP00000384273', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000463999', 'cpi_9606.ENSP00000370473'], ['cpi_9606.ENSP00000361405', 'cpi_9606.ENSP00000355325', 'cpi_9606.ENSP00000365663', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000339527'], ['cpi_9606.ENSP00000219070', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000327652'], ['cpi_9606.ENSP00000412237', 'cpi_9606.ENSP00000327801', 'cpi_9606.ENSP00000355778', 'cpi_9606.ENSP00000373169', 'cpi_9606.ENSP00000358784'], ['cpi_9606.ENSP00000287820', 'cpi_9606.ENSP00000220003', 'cpi_9606.ENSP00000353427', 'cpi_9606.ENSP00000234961', 'cpi_9606.ENSP00000354107'], ['cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000241261', 'cpi_9606.ENSP00000398655', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000360967'], ['cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000231449', 'cpi_9606.ENSP00000259271', 'cpi_9606.ENSP00000410076', 'cpi_9606.ENSP00000221421'], ['cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000329357', 'cpi_9606.ENSP00000291294', 'cpi_9606.ENSP00000263923'], ['cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000289753', 'cpi_9606.ENSP00000265403', 'cpi_9606.ENSP00000262461'], ['cpi_9606.ENSP00000387662', 'cpi_9606.ENSP00000305221', 'cpi_9606.ENSP00000388648', 'cpi_9606.ENSP00000346598', 'cpi_9606.ENSP00000339260'], ['cpi_9606.ENSP00000340684', 'cpi_9606.ENSP00000264657', 'cpi_9606.ENSP00000333496', 'cpi_9606.ENSP00000341045', 'cpi_9606.ENSP00000270474'], ['cpi_9606.ENSP00000355759', 'cpi_9606.ENSP00000374467', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000306129', 'cpi_9606.ENSP00000366307'], ['cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000321988', 'cpi_9606.ENSP00000296871', 'cpi_9606.ENSP00000267843', 'cpi_9606.ENSP00000176183'], ['cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000264498', 'cpi_9606.ENSP00000287936', 'cpi_9606.ENSP00000278616', 'cpi_9606.ENSP00000308549'], ['cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000311095', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000282397', 'cpi_9606.ENSP00000357255'], ['cpi_9606.ENSP00000350348', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000318822', 'cpi_9606.ENSP00000419692', 'cpi_9606.ENSP00000225964'], ['cpi_9606.ENSP00000368438', 'cpi_9606.ENSP00000296122', 'cpi_9606.ENSP00000263341', 'cpi_9606.ENSP00000254488', 'cpi_9606.ENSP00000340820'], ['cpi_9606.ENSP00000313661', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000311028', 'cpi_9606.ENSP00000264867'], ['cpi_9606.ENSP00000290866', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000331358', 'cpi_9606.ENSP00000295834', 'cpi_9606.ENSP00000337773'], ['cpi_9606.ENSP00000337459', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000429374', 'cpi_9606.ENSP00000231454', 'cpi_9606.ENSP00000307235'], ['cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000303522', 'cpi_9606.ENSP00000372023', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000325822'], ['cpi_9606.ENSP00000264832', 'cpi_9606.ENSP00000338548', 'cpi_9606.ENSP00000364802', 'cpi_9606.ENSP00000287907', 'cpi_9606.ENSP00000434364'], ['cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000301974', 'cpi_9606.ENSP00000275300', 'cpi_9606.ENSP00000256119'], ['cpi_9606.ENSP00000394624', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000305302', 'cpi_9606.ENSP00000262948', 'cpi_9606.ENSP00000369816'], ['cpi_9606.ENSP00000305742', 'cpi_9606.ENSP00000454071', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000307766', 'cpi_9606.ENSP00000428924'], ['cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000382659', 'cpi_9606.ENSP00000215659'], ['cpi_9606.ENSP00000327251', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000216392', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000347979'], ['cpi_9606.ENSP00000274353', 'cpi_9606.ENSP00000355657', 'cpi_9606.ENSP00000322924', 'cpi_9606.ENSP00000356694', 'cpi_9606.ENSP00000221515'], ['cpi_9606.ENSP00000216117', 'cpi_9606.ENSP00000282753', 'cpi_9606.ENSP00000310447', 'cpi_9606.ENSP00000263464', 'cpi_9606.ENSP00000358903'], ['cpi_9606.ENSP00000309845', 'cpi_9606.ENSP00000301146', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000310928', 'cpi_9606.ENSP00000178638'], ['cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000365380', 'cpi_9606.ENSP00000211287', 'cpi_9606.ENSP00000311469'], ['cpi_9606.ENSP00000265572', 'cpi_9606.ENSP00000262160', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000380252', 'cpi_9606.ENSP00000368104'], ['cpi_9606.ENSP00000358327', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000356832', 'cpi_9606.ENSP00000252029', 'cpi_9606.ENSP00000285979'], ['cpi_9606.ENSP00000369647', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000309103', 'cpi_9606.ENSP00000266682', 'cpi_9606.ENSP00000433821'], ['cpi_9606.ENSP00000236850', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000355317', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000353878'], ['cpi_9606.ENSP00000356825', 'cpi_9606.ENSP00000231228', 'cpi_9606.ENSP00000407375', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000263980'], ['cpi_9606.ENSP00000223095', 'cpi_9606.ENSP00000362924', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000349577', 'cpi_9606.ENSP00000265643'], ['cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000226413', 'cpi_9606.ENSP00000225371', 'cpi_9606.ENSP00000219919', 'cpi_9606.ENSP00000164139'], ['cpi_9606.ENSP00000218548', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000366662'], ['cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000303174', 'cpi_9606.ENSP00000318646', 'cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000358730'], ['cpi_9606.ENSP00000270142', 'cpi_9606.ENSP00000400175', 'cpi_9606.ENSP00000308032', 'cpi_9606.ENSP00000292513', 'cpi_9606.ENSP00000341885'], ['cpi_9606.ENSP00000315644', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000245457', 'cpi_9606.ENSP00000369050', 'cpi_9606.ENSP00000346298'], ['cpi_9606.ENSP00000345096', 'cpi_9606.ENSP00000385806', 'cpi_9606.ENSP00000355920', 'cpi_9606.ENSP00000330199', 'cpi_9606.ENSP00000304915'], ['cpi_9606.ENSP00000312652', 'cpi_9606.ENSP00000362353', 'cpi_9606.ENSP00000368752', 'cpi_9606.ENSP00000343204', 'cpi_9606.ENSP00000297268'], ['cpi_9606.ENSP00000464149', 'cpi_9606.ENSP00000378699', 'cpi_9606.ENSP00000381333', 'cpi_9606.ENSP00000362508', 'cpi_9606.ENSP00000430432'], ['cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000262735', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000451605', 'cpi_9606.ENSP00000301141'], ['cpi_9606.ENSP00000349467', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000275216', 'cpi_9606.ENSP00000338627', 'cpi_9606.ENSP00000268035'], ['cpi_9606.ENSP00000386284', 'cpi_9606.ENSP00000368683', 'cpi_9606.ENSP00000365016', 'cpi_9606.ENSP00000459962', 'cpi_9606.ENSP00000347046'], ['cpi_9606.ENSP00000331746', 'cpi_9606.ENSP00000356729', 'cpi_9606.ENSP00000319591', 'cpi_9606.ENSP00000288135', 'cpi_9606.ENSP00000320401'], ['cpi_9606.ENSP00000234310', 'cpi_9606.ENSP00000233146', 'cpi_9606.ENSP00000358511', 'cpi_9606.ENSP00000265723', 'cpi_9606.ENSP00000277120'], ['cpi_9606.ENSP00000229135', 'cpi_9606.ENSP00000384957', 'cpi_9606.ENSP00000369757', 'cpi_9606.ENSP00000367309', 'cpi_9606.ENSP00000342560'], ['cpi_9606.ENSP00000317842', 'cpi_9606.ENSP00000261465', 'cpi_9606.ENSP00000267377', 'cpi_9606.ENSP00000304895', 'cpi_9606.ENSP00000318912'], ['cpi_9606.ENSP00000257497', 'cpi_9606.ENSP00000314508', 'cpi_9606.ENSP00000239849', 'cpi_9606.ENSP00000256383', 'cpi_9606.ENSP00000260970'], ['cpi_9606.ENSP00000272298', 'cpi_9606.ENSP00000244741', 'cpi_9606.ENSP00000387683', 'cpi_9606.ENSP00000451030', 'cpi_9606.ENSP00000344674'], ['cpi_9606.ENSP00000295598', 'cpi_9606.ENSP00000360266', 'cpi_9606.ENSP00000294954', 'cpi_9606.ENSP00000320709', 'cpi_9606.ENSP00000420168'], ['cpi_9606.ENSP00000262623', 'cpi_9606.ENSP00000225577', 'cpi_9606.ENSP00000368880', 'cpi_9606.ENSP00000217305', 'cpi_9606.ENSP00000362525'], ['cpi_9606.ENSP00000368349', 'cpi_9606.ENSP00000333534', 'cpi_9606.ENSP00000302846', 'cpi_9606.ENSP00000352584', 'cpi_9606.ENSP00000370912'], ['cpi_9606.ENSP00000273550', 'cpi_9606.ENSP00000393333', 'cpi_9606.ENSP00000252321', 'cpi_9606.ENSP00000321821', 'cpi_9606.ENSP00000427562'], ['cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000272847', 'cpi_9606.ENSP00000359998', 'cpi_9606.ENSP00000356671', 'cpi_9606.ENSP00000341189'], ['cpi_9606.ENSP00000321584', 'cpi_9606.ENSP00000386884', 'cpi_9606.ENSP00000276431', 'cpi_9606.ENSP00000251566', 'cpi_9606.ENSP00000393312'], ['cpi_9606.ENSP00000354511', 'cpi_9606.ENSP00000232219', 'cpi_9606.ENSP00000290349', 'cpi_9606.ENSP00000315011', 'cpi_9606.ENSP00000216341'], ['cpi_9606.ENSP00000266970', 'cpi_9606.ENSP00000335544', 'cpi_9606.ENSP00000288602', 'cpi_9606.ENSP00000225927', 'cpi_9606.ENSP00000239938'], ['cpi_9606.ENSP00000225275', 'cpi_9606.ENSP00000379213', 'cpi_9606.ENSP00000362649', 'cpi_9606.ENSP00000362513', 'cpi_9606.ENSP00000274026'], ['cpi_9606.ENSP00000307786', 'cpi_9606.ENSP00000384708', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000264896', 'cpi_9606.ENSP00000345774'], ['cpi_9606.ENSP00000260302', 'cpi_9606.ENSP00000321106', 'cpi_9606.ENSP00000341828', 'cpi_9606.ENSP00000269571', 'cpi_9606.ENSP00000296674'], ['cpi_9606.ENSP00000378323', 'cpi_9606.ENSP00000360968', 'cpi_9606.ENSP00000303424', 'cpi_9606.ENSP00000263377', 'cpi_9606.ENSP00000320866'], ['cpi_9606.ENSP00000363868', 'cpi_9606.ENSP00000287641', 'cpi_9606.ENSP00000418960', 'cpi_9606.ENSP00000296522', 'cpi_9606.ENSP00000346148'], ['cpi_9606.ENSP00000275493', 'cpi_9606.ENSP00000360973', 'cpi_9606.ENSP00000387888', 'cpi_9606.ENSP00000270625', 'cpi_9606.ENSP00000351908'], ['cpi_9606.ENSP00000318585', 'cpi_9606.ENSP00000387699', 'cpi_9606.ENSP00000301633', 'cpi_9606.ENSP00000304408', 'cpi_9606.ENSP00000366416'], ['cpi_9606.ENSP00000375066', 'cpi_9606.ENSP00000288022', 'cpi_9606.ENSP00000253727', 'cpi_9606.ENSP0000026

🔄 Processing features: 100%|██████████| 1607/1607 [06:50<00:00,  3.92feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'cpi_9606.ENSP00000326219', 'cpi_9606.ENSP00000312455', 'cpi_9606.ENSP00000356094', 'cpi_9606.ENSP00000285381'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000374323'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000360773', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000355629'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000359353', 'cpi_9606.ENSP00000299178'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000394936'], ['cpi_9606.ENSP00000360372', 'cpi_9606.ENSP00000309818', 'cpi_9606.ENSP00000307014', 'cpi_9606.ENSP00000261937', 'cpi_9606.ENSP00000430684'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000301891', 'cpi_9606.ENSP00000257290'], ['cpi_9606.ENSP00000311032', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000299847'], ['cpi_9606.ENSP00000265724', 'cpi_9606.ENSP00000304822', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000367848', 'cpi_9606.ENSP00000381097'], ['cpi_9606.ENSP00000264381', 'cpi_9606.ENSP00000319788', 'cpi_9606.ENSP00000261799', 'cpi_9606.ENSP00000337335', 'cpi_9606.ENSP00000261693'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000312664', 'cpi_9606.ENSP00000266376'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000467676', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000395653'], ['cpi_9606.ENSP00000367959', 'cpi_9606.ENSP00000301634', 'cpi_9606.ENSP00000242057', 'cpi_9606.ENSP00000286301', 'cpi_9606.ENSP00000309124'], ['cpi_9606.ENSP00000272190', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000354476', 'cpi_9606.ENSP00000417229', 'cpi_9606.ENSP00000295454'], ['cpi_9606.ENSP00000369960', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000274547', 'cpi_9606.ENSP00000351957'], ['cpi_9606.ENSP00000270349', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000267101', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000279178'], ['cpi_9606.ENSP00000305372', 'cpi_9606.ENSP00000277010', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000233242', 'cpi_9606.ENSP00000283635'], ['cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000414334', 'cpi_9606.ENSP00000342235'], ['cpi_9606.ENSP00000337450', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000384957', 'cpi_9606.ENSP00000318822', 'cpi_9606.ENSP00000221972'], ['cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000263321', 'cpi_9606.ENSP00000316786', 'cpi_9606.ENSP00000367851', 'cpi_9606.ENSP00000323568'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000359793', 'cpi_9606.ENSP00000256383', 'cpi_9606.ENSP00000347942', 'cpi_9606.ENSP00000285930'], ['cpi_9606.ENSP00000258743', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000259089', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000216037'], ['cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000389338', 'cpi_9606.ENSP00000386306'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000299267', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000451040'], ['cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000343040', 'cpi_9606.ENSP00000367102', 'cpi_9606.ENSP00000359334'], ['cpi_9606.ENSP00000231509', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000358548', 'cpi_9606.ENSP00000225474'], ['cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000363822', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000261196'], ['cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000344192', 'cpi_9606.ENSP00000326119', 'cpi_9606.ENSP00000353292'], ['cpi_9606.ENSP00000356438', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000332296'], ['cpi_9606.ENSP00000297494', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000300900'], ['cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000252723', 'cpi_9606.ENSP00000463999', 'cpi_9606.ENSP00000362036'], ['cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000296871', 'cpi_9606.ENSP00000307599'], ['cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000301178'], ['cpi_9606.ENSP00000260433', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000308165', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000347979'], ['cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000297350', 'cpi_9606.ENSP00000241453'], ['cpi_9606.ENSP00000270202', 'cpi_9606.ENSP00000331912', 'cpi_9606.ENSP00000445340', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000258749'], ['cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000320025'], ['cpi_9606.ENSP00000398698', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000220616', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000471569'], ['cpi_9606.ENSP00000280155', 'cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000275525', 'cpi_9606.ENSP00000256958'], ['cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000414303', 'cpi_9606.ENSP00000356954', 'cpi_9606.ENSP00000252809', 'cpi_9606.ENSP00000387946'], ['cpi_9606.ENSP00000237014', 'cpi_9606.ENSP00000348069', 'cpi_9606.ENSP00000376943', 'cpi_9606.ENSP00000231454', 'cpi_9606.ENSP00000325822'], ['cpi_9606.ENSP00000366506', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000378517', 'cpi_9606.ENSP00000344352'], ['cpi_9606.ENSP00000354859', 'cpi_9606.ENSP00000359478', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000361359', 'cpi_9606.ENSP00000470087'], ['cpi_9606.ENSP00000337949', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000457706', 'cpi_9606.ENSP00000320935'], ['cpi_9606.ENSP00000316244', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000308774', 'cpi_9606.ENSP00000302111', 'cpi_9606.ENSP00000264867'], ['cpi_9606.ENSP00000295897', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000267119', 'cpi_9606.ENSP00000262888', 'cpi_9606.ENSP00000354394'], ['cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000378699', 'cpi_9606.ENSP00000361666', 'cpi_9606.ENSP00000295491', 'cpi_9606.ENSP00000221515'], ['cpi_9606.ENSP00000269305', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000389414', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000264637'], ['cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000358784', 'cpi_9606.ENSP00000357283', 'cpi_9606.ENSP00000411593'], ['cpi_9606.ENSP00000215832', 'cpi_9606.ENSP00000370381', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000274793', 'cpi_9606.ENSP00000289753'], ['cpi_9606.ENSP00000258400', 'cpi_9606.ENSP00000304845', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000226574', 'cpi_9606.ENSP00000216185'], ['cpi_9606.ENSP00000358963', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000305422'], ['cpi_9606.ENSP00000330237', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000292896', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000276198'], ['cpi_9606.ENSP00000354612', 'cpi_9606.ENSP00000339527', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000259396', 'cpi_9606.ENSP00000307240'], ['cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000364805', 'cpi_9606.ENSP00000254227'], ['cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000282561', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000300061'], ['cpi_9606.ENSP00000308541', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000332369'], ['cpi_9606.ENSP00000387281', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000200676'], ['cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000241261', 'cpi_9606.ENSP00000428924', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000251535'], ['cpi_9606.ENSP00000411532', 'cpi_9606.ENSP00000333212', 'cpi_9606.ENSP00000260010', 'cpi_9606.ENSP00000368766', 'cpi_9606.ENSP00000267843'], ['cpi_9606.ENSP00000306512', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000253004', 'cpi_9606.ENSP00000306662'], ['cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000329623', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000294728'], ['cpi_9606.ENSP00000263025', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000366307', 'cpi_9606.ENSP00000362344', 'cpi_9606.ENSP00000373169'], ['cpi_9606.ENSP00000386069', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000365775'], ['cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000262441', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000248553', 'cpi_9606.ENSP00000262461'], ['cpi_9606.ENSP00000306245', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000428340', 'cpi_9606.ENSP00000360493', 'cpi_9606.ENSP00000359096'], ['cpi_9606.ENSP00000344456', 'cpi_9606.ENSP00000176183', 'cpi_9606.ENSP00000295834', 'cpi_9606.ENSP00000225964', 'cpi_9606.ENSP00000307235'], ['cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000388648', 'cpi_9606.ENSP00000255465'], ['cpi_9606.ENSP00000220764', 'cpi_9606.ENSP00000293288', 'cpi_9606.ENSP00000263126', 'cpi_9606.ENSP00000327652', 'cpi_9606.ENSP00000343477'], ['cpi_9606.ENSP00000252945', 'cpi_9606.ENSP00000298171', 'cpi_9606.ENSP00000312029', 'cpi_9606.ENSP00000353427', 'cpi_9606.ENSP00000310447'], ['cpi_9606.ENSP00000302150', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000355657', 'cpi_9606.ENSP00000292513', 'cpi_9606.ENSP00000410294'], ['cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000400175', 'cpi_9606.ENSP00000311095', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000307766'], ['cpi_9606.ENSP00000237612', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000277120', 'cpi_9606.ENSP00000303522'], ['cpi_9606.ENSP00000355759', 'cpi_9606.ENSP00000282753', 'cpi_9606.ENSP00000268053', 'cpi_9606.ENSP00000317379', 'cpi_9606.ENSP00000427514'], ['cpi_9606.ENSP00000313661', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000368880', 'cpi_9606.ENSP00000262367', 'cpi_9606.ENSP00000266682'], ['cpi_9606.ENSP00000387662', 'cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000340820', 'cpi_9606.ENSP00000353791'], ['cpi_9606.ENSP00000361405', 'cpi_9606.ENSP00000355325', 'cpi_9606.ENSP00000222330', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000301645'], ['cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000366084', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000356671', 'cpi_9606.ENSP00000216862'], ['cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000231449', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000232219', 'cpi_9606.ENSP00000322617'], ['cpi_9606.ENSP00000464149', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000380252', 'cpi_9606.ENSP00000324248', 'cpi_9606.ENSP00000364802'], ['cpi_9606.ENSP00000219070', 'cpi_9606.ENSP00000398655', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000260356', 'cpi_9606.ENSP00000178638'], ['cpi_9606.ENSP00000225831', 'cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000176763', 'cpi_9606.ENSP00000306129', 'cpi_9606.ENSP00000329357'], ['cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000212015', 'cpi_9606.ENSP00000355778', 'cpi_9606.ENSP00000359635', 'cpi_9606.ENSP00000303174'], ['cpi_9606.ENSP00000358327', 'cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000233146', 'cpi_9606.ENSP00000287936'], ['cpi_9606.ENSP00000287820', 'cpi_9606.ENSP00000359910', 'cpi_9606.ENSP00000382659', 'cpi_9606.ENSP00000263923', 'cpi_9606.ENSP00000365663'], ['cpi_9606.ENSP00000290866', 'cpi_9606.ENSP00000278616', 'cpi_9606.ENSP00000276414', 'cpi_9606.ENSP00000311469', 'cpi_9606.ENSP00000216962'], ['cpi_9606.ENSP00000368438', 'cpi_9606.ENSP00000355930', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000216392'], ['cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000322924'], ['cpi_9606.ENSP00000394624', 'cpi_9606.ENSP00000301633', 'cpi_9606.ENSP00000310928', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000231228'], ['cpi_9606.ENSP00000412237', 'cpi_9606.ENSP00000327801', 'cpi_9606.ENSP00000353915', 'cpi_9606.ENSP00000338627', 'cpi_9606.ENSP00000252486'], ['cpi_9606.ENSP00000350348', 'cpi_9606.ENSP00000356729', 'cpi_9606.ENSP00000365016', 'cpi_9606.ENSP00000346598', 'cpi_9606.ENSP00000354107'], ['cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000351209', 'cpi_9606.ENSP00000321988'], ['cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000356694', 'cpi_9606.ENSP00000353878', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000296122'], ['cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000252321', 'cpi_9606.ENSP00000354558', 'cpi_9606.ENSP00000393333', 'cpi_9606.ENSP00000320401'], ['cpi_9606.ENSP00000263341', 'cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000262948', 'cpi_9606.ENSP00000254488', 'cpi_9606.ENSP00000221421'], ['cpi_9606.ENSP00000264832', 'cpi_9606.ENSP00000405573', 'cpi_9606.ENSP00000287907', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000360967'], ['cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000275300', 'cpi_9606.ENSP00000365380', 'cpi_9606.ENSP00000270776', 'cpi_9606.ENSP00000263980'], ['cpi_9606.ENSP00000234111', 'cpi_9606.ENSP00000312673', 'cpi_9606.ENSP00000358730', 'cpi_9606.ENSP00000398632', 'cpi_9606.ENSP00000330393'], ['cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000309757', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000303424', 'cpi_9606.ENSP00000253122'], ['cpi_9606.ENSP00000340684', 'cpi_9606.ENSP00000319591', 'cpi_9606.ENSP00000264657', 'cpi_9606.ENSP00000270474', 'cpi_9606.ENSP00000285979'], ['cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000336630', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000385806'], ['cpi_9606.ENSP00000352835', 'cpi_9606.ENSP00000368683', 'cpi_9606.ENSP00000369050', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000275216'], ['cpi_9606.ENSP00000236850', 'cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000264498', 'cpi_9606.ENSP00000330199', 'cpi_9606.ENSP00000448059'], ['cpi_9606.ENSP00000327251', 'cpi_9606.ENSP00000346298', 'cpi_9606.ENSP00000393312', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000311028'], ['cpi_9606.ENSP00000265572', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000282397', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000410076'], ['cpi_9606.ENSP00000223095', 'cpi_9606.ENSP00000362924', 'cpi_9606.ENSP00000341045', 'cpi_9606.ENSP00000307259', 'cpi_9606.ENSP00000305302'], ['cpi_9606.ENSP00000337459', 'cpi_9606.ENSP00000333496', 'cpi_9606.ENSP00000219919', 'cpi_9606.ENSP00000333821', 'cpi_9606.ENSP00000267163'], ['cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000252029', 'cpi_9606.ENSP00000288135', 'cpi_9606.ENSP00000331358', 'cpi_9606.ENSP00000241600'], ['cpi_9606.ENSP00000295598', 'cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000372023', 'cpi_9606.ENSP00000362401', 'cpi_9606.ENSP00000222002'], ['cpi_9606.ENSP00000216117', 'cpi_9606.ENSP00000301974', 'cpi_9606.ENSP00000341885', 'cpi_9606.ENSP00000305221', 'cpi_9606.ENSP00000338548'], ['cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000324270', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000349577', 'cpi_9606.ENSP00000304915'], ['cpi_9606.ENSP00000218548', 'cpi_9606.ENSP00000384273', 'cpi_9606.ENSP00000308549', 'cpi_9606.ENSP00000276449', 'cpi_9606.ENSP00000349252'], ['cpi_9606.ENSP00000315644', 'cpi_9606.ENSP00000312652', 'cpi_9606.ENSP00000245457', 'cpi_9606.ENSP00000301146', 'cpi_9606.ENSP00000332816'], ['cpi_9606.ENSP00000317842', 'cpi_9606.ENSP00000297469', 'cpi_9606.ENSP00000263464', 'cpi_9606.ENSP00000343204', 'cpi_9606.ENSP00000260970'], ['cpi_9606.ENSP00000262623', 'cpi_9606.ENSP00000239938', 'cpi_9606.ENSP00000351885', 'cpi_9606.ENSP00000451030', 'cpi_9606.ENSP00000262160'], ['cpi_9606.ENSP00000305742', 'cpi_9606.ENSP00000454071', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000459962', 'cpi_9606.ENSP00000419782'], ['cpi_9606.ENSP00000321584', 'cpi_9606.ENSP00000370473', 'cpi_9606.ENSP00000265723', 'cpi_9606.ENSP00000342560', 'cpi_9606.ENSP00000254810'], ['cpi_9606.ENSP00000369647', 'cpi_9606.ENSP00000269571', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000297268', 'cpi_9606.ENSP00000259271'], ['cpi_9606.ENSP00000375066', 'cpi_9606.ENSP00000357204', 'cpi_9606.ENSP00000360266', 'cpi_9606.ENSP00000320709', 'cpi_9606.ENSP00000435777'], ['cpi_9606.ENSP00000309845', 'cpi_9606.ENSP00000308032', 'cpi_9606.ENSP00000291294', 'cpi_9606.ENSP00000352584', 'cpi_9606.ENSP00000363827'], ['cpi_9606.ENSP00000367309', 'cpi_9606.ENSP00000369757', 'cpi_9606.ENSP00000368752', 'cpi_9606.ENSP00000307445', 'cpi_9606.ENSP00000164139'], ['cpi_9606.ENSP00000370571', 'cpi_9606.ENSP00000328173', 'cpi_9606.ENSP00000309103', 'cpi_9606.ENSP00000355533', 'cpi_9606.ENSP00000348645'], ['cpi_9606.ENSP00000234310', 'cpi_9606.ENSP00000262735', 'cpi_9606.ENSP00000234961', 'cpi_9606.ENSP00000288602', 'cpi_9606.ENSP00000387683'], ['cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000244741', 'cpi_9606.ENSP00000335657', 'cpi_9606.ENSP00000333534', 'cpi_9606.ENSP00000344674'], ['cpi_9606.ENSP00000338018', 'cpi_9606.ENSP00000303830', 'cpi_9606.ENSP00000362513', 'cpi_9606.ENSP00000303452', 'cpi_9606.ENSP00000433821'], ['cpi_9606.ENSP00000275493', 'cpi_9606.ENSP00000360973', 'cpi_9606.ENSP00000216341', 'cpi_9606.ENSP00000251566', 'cpi_9606.ENSP00000386171'], ['cpi_9606.ENSP00000284981', 'cpi_9606.ENSP00000304895', 'cpi_9606.ENSP00000356825', 'cpi_9606.ENSP00000270625', 'cpi_9606.ENSP00000248041'], ['cpi_9606.ENSP00000270142', 'cpi_9606.ENSP00000260630', 'cpi_9606.ENSP00000315011', 'cpi_9606.ENSP00000296674', 'cpi_9606.ENSP00000368104'], ['cpi_9606.ENSP00000394033', 'cpi_9606.ENSP00000296545', 'cpi_9606.ENSP00000254079', 'cpi_9606.ENSP00000226413', 'cpi_9606.ENSP00000362508'], ['cpi_9606.ENSP00000285379', 'cpi_9606.ENSP00000386884', 'cpi_9606.ENSP00000356832', 'cpi_9606.ENSP00000420168', 'cpi_9606.ENSP00000260649'], ['cpi_9606.ENSP00000225275', 'cpi_9606.ENSP00000379213', 'cpi_9606.ENSP00000211122', 'cpi_9606.ENSP00000363089', 'cpi_9606.ENSP00000225927'], ['cpi_9606.ENSP00000331746', 'cpi_9606.ENSP00000358107', 'cpi_9606.ENSP00000341189', 'cpi_9606.ENSP00000356150', 'cpi_9606.ENSP00000301141'], ['cpi_9606.ENSP00000378323', 'cpi_9606.ENSP00000360968', 'cpi_9606.ENSP00000302846', 'cpi_9606.ENSP00000308938', 'cpi_9606.ENSP00000211287'], ['cpi_9606.ENSP00000353731', 'cpi_9606.ENSP00000248076', 'cpi_9606.ENSP00000321821', 'cpi_9606.ENSP00000429374', 'cpi_9606.ENSP00000252804'], ['cpi_9606.ENSP00000349467', 'cpi_9606.ENSP00000239849', 'cpi_9606.ENSP00000341828', 'cpi_9606.ENSP00000294954', 'cpi_9606.ENSP00000359998'], ['cpi_9606.ENSP00000272298', 'cpi_9606.ENSP00000265403', 'cpi_9606.ENSP00000386229', 'cpi_9606.ENSP00000351908', 'cpi_9606.ENSP00000371554'], ['cpi_9606.ENSP00000279387', 'cpi_9606.ENSP00000360991', 'cpi_9606.ENSP00000276571', 'cpi_9606.ENSP00000368632', 'cpi_9606.ENSP00000225371'], ['cpi_9606.ENSP00000386284', 'cpi_9606.ENSP00000321106', 'cpi_9606.ENSP00000348461', 'cpi_9606.ENSP00000334246', 'cpi_9606.ENSP00000427562'], ['cpi_9606.ENSP00000265023', 'cpi_9606.ENSP00000314508', 'cpi_9606.ENSP00000253727', 'cpi_9606.ENSP00000274026', 'cpi_9606.ENSP00000355920'], ['cpi_9606.ENSP00000356022', 'cpi_9606.ENSP00000358511', 'cpi_9606.ENSP00000311165', 'cpi_9606.ENSP00000430432', 'cpi_9606.ENSP00000318646'], ['cpi_9606.ENSP00000229135', 'cpi_9606.ENSP00000267377', 'cpi_9606.ENSP00000263377', 'cpi_9606.ENSP0000035

🔄 Processing features: 100%|██████████| 1607/1607 [06:51<00:00,  3.91feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'cpi_9606.ENSP00000244217', 'cpi_9606.ENSP00000295491', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000356094'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000331746', 'cpi_9606.ENSP00000283635', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000355629'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000261799', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000245539'], ['cpi_9606.ENSP00000311032', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000344674'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000459962', 'cpi_9606.ENSP00000414334', 'cpi_9606.ENSP00000367848'], ['cpi_9606.ENSP00000360372', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000303522', 'cpi_9606.ENSP00000381097', 'cpi_9606.ENSP00000430684'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000257290', 'cpi_9606.ENSP00000467676', 'cpi_9606.ENSP00000376178'], ['cpi_9606.ENSP00000258743', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000261937', 'cpi_9606.ENSP00000359353'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000417229', 'cpi_9606.ENSP00000262367', 'cpi_9606.ENSP00000359334'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000302846', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000374323', 'cpi_9606.ENSP00000241600'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000304822', 'cpi_9606.ENSP00000361206'], ['cpi_9606.ENSP00000265724', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000299178', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000311028'], ['cpi_9606.ENSP00000367959', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000267101', 'cpi_9606.ENSP00000335592'], ['cpi_9606.ENSP00000270349', 'cpi_9606.ENSP00000337335', 'cpi_9606.ENSP00000273550', 'cpi_9606.ENSP00000360773', 'cpi_9606.ENSP00000261693'], ['cpi_9606.ENSP00000356438', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000394936', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000372547'], ['cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000358548', 'cpi_9606.ENSP00000346598', 'cpi_9606.ENSP00000300900'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000367102', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000341885'], ['cpi_9606.ENSP00000272190', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000348069', 'cpi_9606.ENSP00000342235', 'cpi_9606.ENSP00000410732'], ['cpi_9606.ENSP00000337450', 'cpi_9606.ENSP00000245457', 'cpi_9606.ENSP00000428340', 'cpi_9606.ENSP00000362036', 'cpi_9606.ENSP00000365775'], ['cpi_9606.ENSP00000354612', 'cpi_9606.ENSP00000277010', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000339527', 'cpi_9606.ENSP00000023897'], ['cpi_9606.ENSP00000258400', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000225474', 'cpi_9606.ENSP00000274545'], ['cpi_9606.ENSP00000369960', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000293288', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000429374'], ['cpi_9606.ENSP00000260433', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000354476', 'cpi_9606.ENSP00000457706', 'cpi_9606.ENSP00000264318'], ['cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000378323', 'cpi_9606.ENSP00000361666', 'cpi_9606.ENSP00000387946', 'cpi_9606.ENSP00000299267'], ['cpi_9606.ENSP00000337949', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000275525', 'cpi_9606.ENSP00000286301'], ['cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000263321', 'cpi_9606.ENSP00000266376', 'cpi_9606.ENSP00000274547'], ['cpi_9606.ENSP00000313661', 'cpi_9606.ENSP00000321584', 'cpi_9606.ENSP00000307599', 'cpi_9606.ENSP00000279178', 'cpi_9606.ENSP00000361359'], ['cpi_9606.ENSP00000215832', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000301891', 'cpi_9606.ENSP00000377947'], ['cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000295454'], ['cpi_9606.ENSP00000354859', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000308845'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000316786'], ['cpi_9606.ENSP00000269305', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000389414', 'cpi_9606.ENSP00000196551', 'cpi_9606.ENSP00000291295'], ['cpi_9606.ENSP00000358963', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000314949', 'cpi_9606.ENSP00000216037', 'cpi_9606.ENSP00000343040'], ['cpi_9606.ENSP00000297494', 'cpi_9606.ENSP00000251453', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000332296', 'cpi_9606.ENSP00000345659'], ['cpi_9606.ENSP00000276198', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000384273', 'cpi_9606.ENSP00000471569'], ['cpi_9606.ENSP00000270202', 'cpi_9606.ENSP00000331912', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000445340', 'cpi_9606.ENSP00000298472'], ['cpi_9606.ENSP00000305372', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000389338', 'cpi_9606.ENSP00000267119'], ['cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000363822', 'cpi_9606.ENSP00000349576', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000367851'], ['cpi_9606.ENSP00000366506', 'cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000344192'], ['cpi_9606.ENSP00000280155', 'cpi_9606.ENSP00000345096', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000312664', 'cpi_9606.ENSP00000348827'], ['cpi_9606.ENSP00000287820', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000356150', 'cpi_9606.ENSP00000347942', 'cpi_9606.ENSP00000332369'], ['cpi_9606.ENSP00000316244', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000344352', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000000442'], ['cpi_9606.ENSP00000306512', 'cpi_9606.ENSP00000394033', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000262888', 'cpi_9606.ENSP00000254227'], ['cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000226574', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000301178'], ['cpi_9606.ENSP00000330237', 'cpi_9606.ENSP00000234310', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000451040', 'cpi_9606.ENSP00000370381'], ['cpi_9606.ENSP00000263025', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000305422'], ['cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000289753', 'cpi_9606.ENSP00000333212', 'cpi_9606.ENSP00000357981', 'cpi_9606.ENSP00000329357'], ['cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000301633', 'cpi_9606.ENSP00000221972', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000351885'], ['cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000353427', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000319788'], ['cpi_9606.ENSP00000264381', 'cpi_9606.ENSP00000326119', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000311469', 'cpi_9606.ENSP00000379339'], ['cpi_9606.ENSP00000252945', 'cpi_9606.ENSP00000278616', 'cpi_9606.ENSP00000326219', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000258749'], ['cpi_9606.ENSP00000329623', 'cpi_9606.ENSP00000368766', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000300151', 'cpi_9606.ENSP00000395653'], ['cpi_9606.ENSP00000366084', 'cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000308165', 'cpi_9606.ENSP00000349252', 'cpi_9606.ENSP00000296674'], ['cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000241261', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000433821'], ['cpi_9606.ENSP00000306245', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000256383', 'cpi_9606.ENSP00000345708'], ['cpi_9606.ENSP00000414303', 'cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000231454', 'cpi_9606.ENSP00000307014', 'cpi_9606.ENSP00000353878'], ['cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000318646', 'cpi_9606.ENSP00000353292'], ['cpi_9606.ENSP00000386069', 'cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000360493', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000435777'], ['cpi_9606.ENSP00000398698', 'cpi_9606.ENSP00000308897', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000309572'], ['cpi_9606.ENSP00000412237', 'cpi_9606.ENSP00000254488', 'cpi_9606.ENSP00000251535', 'cpi_9606.ENSP00000216962', 'cpi_9606.ENSP00000264637'], ['cpi_9606.ENSP00000237612', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000307766', 'cpi_9606.ENSP00000270625', 'cpi_9606.ENSP00000254066'], ['cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000304845', 'cpi_9606.ENSP00000300061', 'cpi_9606.ENSP00000259089', 'cpi_9606.ENSP00000200676'], ['cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000356694', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000333821', 'cpi_9606.ENSP00000242057'], ['cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000376943', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000220616', 'cpi_9606.ENSP00000234071'], ['cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000274606', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000312455', 'cpi_9606.ENSP00000409378'], ['cpi_9606.ENSP00000464149', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000259396', 'cpi_9606.ENSP00000364802', 'cpi_9606.ENSP00000375893'], ['cpi_9606.ENSP00000305742', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000261196', 'cpi_9606.ENSP00000285930'], ['cpi_9606.ENSP00000218548', 'cpi_9606.ENSP00000355759', 'cpi_9606.ENSP00000282561', 'cpi_9606.ENSP00000410294', 'cpi_9606.ENSP00000470087'], ['cpi_9606.ENSP00000231509', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000274793', 'cpi_9606.ENSP00000301634', 'cpi_9606.ENSP00000387281'], ['cpi_9606.ENSP00000295897', 'cpi_9606.ENSP00000378517', 'cpi_9606.ENSP00000356832', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000254976'], ['cpi_9606.ENSP00000263341', 'cpi_9606.ENSP00000358107', 'cpi_9606.ENSP00000262948', 'cpi_9606.ENSP00000342560', 'cpi_9606.ENSP00000216862'], ['cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000369757', 'cpi_9606.ENSP00000358784', 'cpi_9606.ENSP00000322924'], ['cpi_9606.ENSP00000363868', 'cpi_9606.ENSP00000302111', 'cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000308774'], ['cpi_9606.ENSP00000302150', 'cpi_9606.ENSP00000356954', 'cpi_9606.ENSP00000264818', 'cpi_9606.ENSP00000410076', 'cpi_9606.ENSP00000309968'], ['cpi_9606.ENSP00000290866', 'cpi_9606.ENSP00000252809', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000353198', 'cpi_9606.ENSP00000339260'], ['cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000306662', 'cpi_9606.ENSP00000248553', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000309124'], ['cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000292303', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000343477', 'cpi_9606.ENSP00000359096'], ['cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000288602', 'cpi_9606.ENSP00000176183', 'cpi_9606.ENSP00000270474'], ['cpi_9606.ENSP00000262623', 'cpi_9606.ENSP00000354558', 'cpi_9606.ENSP00000296871', 'cpi_9606.ENSP00000263126', 'cpi_9606.ENSP00000466799'], ['cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000330393', 'cpi_9606.ENSP00000372023', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000369816'], ['cpi_9606.ENSP00000279387', 'cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000287907', 'cpi_9606.ENSP00000297350', 'cpi_9606.ENSP00000365380'], ['cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000369050', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000260010', 'cpi_9606.ENSP00000267843'], ['cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000294728', 'cpi_9606.ENSP00000365663', 'cpi_9606.ENSP00000448059', 'cpi_9606.ENSP00000388648'], ['cpi_9606.ENSP00000394624', 'cpi_9606.ENSP00000256958', 'cpi_9606.ENSP00000427514', 'cpi_9606.ENSP00000280357', 'cpi_9606.ENSP00000263980'], ['cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000463999', 'cpi_9606.ENSP00000380252', 'cpi_9606.ENSP00000260191'], ['cpi_9606.ENSP00000337459', 'cpi_9606.ENSP00000333496', 'cpi_9606.ENSP00000337773', 'cpi_9606.ENSP00000354394', 'cpi_9606.ENSP00000307235'], ['cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000239938', 'cpi_9606.ENSP00000349577', 'cpi_9606.ENSP00000262461', 'cpi_9606.ENSP00000348786'], ['cpi_9606.ENSP00000370571', 'cpi_9606.ENSP00000357283', 'cpi_9606.ENSP00000338082', 'cpi_9606.ENSP00000343204', 'cpi_9606.ENSP00000320935'], ['cpi_9606.ENSP00000361405', 'cpi_9606.ENSP00000351209', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000398632', 'cpi_9606.ENSP00000373169'], ['cpi_9606.ENSP00000358327', 'cpi_9606.ENSP00000296522', 'cpi_9606.ENSP00000354610', 'cpi_9606.ENSP00000233242', 'cpi_9606.ENSP00000233146'], ['cpi_9606.ENSP00000327251', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000253727', 'cpi_9606.ENSP00000300738', 'cpi_9606.ENSP00000327652'], ['cpi_9606.ENSP00000223095', 'cpi_9606.ENSP00000362924', 'cpi_9606.ENSP00000252723', 'cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000420168'], ['cpi_9606.ENSP00000216117', 'cpi_9606.ENSP00000248076', 'cpi_9606.ENSP00000346067', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000355533'], ['cpi_9606.ENSP00000340684', 'cpi_9606.ENSP00000231449', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000359910'], ['cpi_9606.ENSP00000219070', 'cpi_9606.ENSP00000361151', 'cpi_9606.ENSP00000255465', 'cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000355778'], ['cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000358730', 'cpi_9606.ENSP00000295834', 'cpi_9606.ENSP00000318822'], ['cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000400175', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000350348', 'cpi_9606.ENSP00000253004'], ['cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000306129', 'cpi_9606.ENSP00000309757', 'cpi_9606.ENSP00000332816', 'cpi_9606.ENSP00000298283'], ['cpi_9606.ENSP00000307786', 'cpi_9606.ENSP00000360973', 'cpi_9606.ENSP00000419692', 'cpi_9606.ENSP00000346148', 'cpi_9606.ENSP00000353791'], ['cpi_9606.ENSP00000357669', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000308549', 'cpi_9606.ENSP00000347979', 'cpi_9606.ENSP00000252486'], ['cpi_9606.ENSP00000308541', 'cpi_9606.ENSP00000387699', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000382250'], ['cpi_9606.ENSP00000266970', 'cpi_9606.ENSP00000358511', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000221515', 'cpi_9606.ENSP00000362649'], ['cpi_9606.ENSP00000317842', 'cpi_9606.ENSP00000277120', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000311095', 'cpi_9606.ENSP00000385806'], ['cpi_9606.ENSP00000374467', 'cpi_9606.ENSP00000264657', 'cpi_9606.ENSP00000310928', 'cpi_9606.ENSP00000353915', 'cpi_9606.ENSP00000285979'], ['cpi_9606.ENSP00000358022', 'cpi_9606.ENSP00000355317', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000292896', 'cpi_9606.ENSP00000393312'], ['cpi_9606.ENSP00000368349', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000291294', 'cpi_9606.ENSP00000305221', 'cpi_9606.ENSP00000222330'], ['cpi_9606.ENSP00000225831', 'cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000254810', 'cpi_9606.ENSP00000359635', 'cpi_9606.ENSP00000287936'], ['cpi_9606.ENSP00000364709', 'cpi_9606.ENSP00000264832', 'cpi_9606.ENSP00000294954', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000263923'], ['cpi_9606.ENSP00000265572', 'cpi_9606.ENSP00000212015', 'cpi_9606.ENSP00000260227', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000419782'], ['cpi_9606.ENSP00000264498', 'cpi_9606.ENSP00000320709', 'cpi_9606.ENSP00000359998', 'cpi_9606.ENSP00000298171', 'cpi_9606.ENSP00000364805'], ['cpi_9606.ENSP00000387662', 'cpi_9606.ENSP00000308032', 'cpi_9606.ENSP00000259271', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000366307'], ['cpi_9606.ENSP00000354511', 'cpi_9606.ENSP00000353483', 'cpi_9606.ENSP00000371554', 'cpi_9606.ENSP00000430432', 'cpi_9606.ENSP00000290349'], ['cpi_9606.ENSP00000411532', 'cpi_9606.ENSP00000231228', 'cpi_9606.ENSP00000301146', 'cpi_9606.ENSP00000312029', 'cpi_9606.ENSP00000345502'], ['cpi_9606.ENSP00000368683', 'cpi_9606.ENSP00000296122', 'cpi_9606.ENSP00000297268', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000347046'], ['cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000417281', 'cpi_9606.ENSP00000324248', 'cpi_9606.ENSP00000351908', 'cpi_9606.ENSP00000275300'], ['cpi_9606.ENSP00000318585', 'cpi_9606.ENSP00000287641', 'cpi_9606.ENSP00000309103', 'cpi_9606.ENSP00000225964', 'cpi_9606.ENSP00000319591'], ['cpi_9606.ENSP00000338018', 'cpi_9606.ENSP00000399168', 'cpi_9606.ENSP00000234961', 'cpi_9606.ENSP00000276449', 'cpi_9606.ENSP00000434364'], ['cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000246337', 'cpi_9606.ENSP00000327431', 'cpi_9606.ENSP00000288135', 'cpi_9606.ENSP00000260630'], ['cpi_9606.ENSP00000331514', 'cpi_9606.ENSP00000244741', 'cpi_9606.ENSP00000331358', 'cpi_9606.ENSP00000333534', 'cpi_9606.ENSP00000274026'], ['cpi_9606.ENSP00000301141', 'cpi_9606.ENSP00000321106', 'cpi_9606.ENSP00000361446', 'cpi_9606.ENSP00000270776', 'cpi_9606.ENSP00000218388'], ['cpi_9606.ENSP00000260970', 'cpi_9606.ENSP00000375066', 'cpi_9606.ENSP00000232219', 'cpi_9606.ENSP00000360967', 'cpi_9606.ENSP00000265164'], ['cpi_9606.ENSP00000355627', 'cpi_9606.ENSP00000355657', 'cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000386171', 'cpi_9606.ENSP00000362525'], ['cpi_9606.ENSP00000368727', 'cpi_9606.ENSP00000260356', 'cpi_9606.ENSP00000267377', 'cpi_9606.ENSP00000323568', 'cpi_9606.ENSP00000320401'], ['cpi_9606.ENSP00000260302', 'cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000336630', 'cpi_9606.ENSP00000265403', 'cpi_9606.ENSP00000295256'], ['cpi_9606.ENSP00000252321', 'cpi_9606.ENSP00000420194', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000263857'], ['cpi_9606.ENSP00000269571', 'cpi_9606.ENSP00000307259', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000349467'], ['cpi_9606.ENSP00000369647', 'cpi_9606.ENSP00000268035', 'cpi_9606.ENSP00000310447', 'cpi_9606.ENSP00000330199', 'cpi_9606.ENSP00000304915'], ['cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000381333', 'cpi_9606.ENSP00000354107', 'cpi_9606.ENSP00000303174', 'cpi_9606.ENSP00000303830'], ['cpi_9606.ENSP00000239223', 'cpi_9606.ENSP00000255008', 'cpi_9606.ENSP00000266682', 'cpi_9606.ENSP00000387683', 'cpi_9606.ENSP00000362344'], ['cpi_9606.ENSP00000248437', 'cpi_9606.ENSP00000262735', 'cpi_9606.ENSP00000341828', 'cpi_9606.ENSP00000451605', 'cpi_9606.ENSP00000305302'], ['cpi_9606.ENSP00000367309', 'cpi_9606.ENSP00000370473', 'cpi_9606.ENSP00000219700', 'cpi_9606.ENSP00000211287', 'cpi_9606.ENSP00000348461'], ['cpi_9606.ENSP00000229135', 'cpi_9606.ENSP00000384957', 'cpi_9606.ENSP00000355930', 'cpi_9606.ENSP00000346298', 'cpi_9606.ENSP00000340820'], ['cpi_9606.ENSP00000313490', 'cpi_9606.ENSP00000296140', 'cpi_9606.ENSP00000312652', 'cpi_9606.ENSP00000276431', 'cpi_9606.ENSP00000341045'], ['cpi_9606.ENSP00000264426', 'cpi_9606.ENSP00000242152', 'cpi_9606.ENSP00000228872', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000338627'], ['cpi_9606.ENSP00000371067', 'cpi_9606.ENSP00000363596', 'cpi_9606.ENSP00000363965', 'cpi_9606.ENSP00000302967', 'cpi_9606.ENSP00000215659'], ['cpi_9606.ENSP00000272298', 'cpi_9606.ENSP00000268053', 'cpi_9606.ENSP00000349003', 'cpi_9606.ENSP00000262187', 'cpi_9606.ENSP00000264867'], ['cpi_9606.ENSP00000356825', 'cpi_9606.ENSP00000384708', 'cpi_9606.ENSP00000378699', 'cpi_9606.ENSP00000368632', 'cpi_9606.ENSP00000252804'], ['cpi_9606.ENSP00000261405', 'cpi_9606.ENSP00000360968', 'cpi_9606.ENSP00000333685', 'cpi_9606.ENSP00000365016', 'cpi_9606.ENSP00000350198'], ['cpi_9606.ENSP00000397026', 'cpi_9606.ENSP00000393333', 'cpi_9606.ENSP00000360991', 'cpi_9606.ENSP00000225371', 'cpi_9606.ENSP00000282397'], ['cpi_9606.ENSP00000239849', 'cpi_9606.ENSP00000356671', 'cpi_9606.ENSP00000257497', 'cpi_9606.ENSP00000372326', 'cpi_9606.ENSP00000334246'], ['cpi_9606.ENSP00000285379', 'cpi_9606.ENSP00000386884', 'cpi_9606.ENSP00000225426', 'cpi_9606.ENSP0000035

🔄 Processing features: 100%|██████████| 1607/1607 [06:50<00:00,  3.91feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'cpi_9606.ENSP00000362924', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000356094', 'cpi_9606.ENSP00000285381'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000430684', 'cpi_9606.ENSP00000367848', 'cpi_9606.ENSP00000374323'], ['cpi_9606.ENSP00000360372', 'cpi_9606.ENSP00000293288', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000355629', 'cpi_9606.ENSP00000216341'], ['cpi_9606.ENSP00000367959', 'cpi_9606.ENSP00000337335', 'cpi_9606.ENSP00000283635', 'cpi_9606.ENSP00000267101', 'cpi_9606.ENSP00000261196'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000360773', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000370381'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000257290', 'cpi_9606.ENSP00000359353', 'cpi_9606.ENSP00000286648'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000414334', 'cpi_9606.ENSP00000262888', 'cpi_9606.ENSP00000339527'], ['cpi_9606.ENSP00000311032', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000299847'], ['cpi_9606.ENSP00000270349', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000261937', 'cpi_9606.ENSP00000301891', 'cpi_9606.ENSP00000355192'], ['cpi_9606.ENSP00000356438', 'cpi_9606.ENSP00000277010', 'cpi_9606.ENSP00000266376', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000372547'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000244217', 'cpi_9606.ENSP00000389338', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000254227'], ['cpi_9606.ENSP00000258743', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000261799', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000220616'], ['cpi_9606.ENSP00000337450', 'cpi_9606.ENSP00000302846', 'cpi_9606.ENSP00000362649', 'cpi_9606.ENSP00000342235', 'cpi_9606.ENSP00000216037'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000367102', 'cpi_9606.ENSP00000369375'], ['cpi_9606.ENSP00000265724', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000299178', 'cpi_9606.ENSP00000381097', 'cpi_9606.ENSP00000348897'], ['cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000312664', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000332296'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000326119', 'cpi_9606.ENSP00000288139'], ['cpi_9606.ENSP00000272190', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000354476', 'cpi_9606.ENSP00000417229', 'cpi_9606.ENSP00000299267'], ['cpi_9606.ENSP00000354612', 'cpi_9606.ENSP00000348069', 'cpi_9606.ENSP00000301178', 'cpi_9606.ENSP00000304822', 'cpi_9606.ENSP00000295454'], ['cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000454071', 'cpi_9606.ENSP00000274547'], ['cpi_9606.ENSP00000269305', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000389414', 'cpi_9606.ENSP00000298472'], ['cpi_9606.ENSP00000354859', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000225474', 'cpi_9606.ENSP00000351209', 'cpi_9606.ENSP00000320935'], ['cpi_9606.ENSP00000369960', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000259089', 'cpi_9606.ENSP00000353292'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000377947'], ['cpi_9606.ENSP00000337949', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000242057', 'cpi_9606.ENSP00000457706'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000467676', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000395653'], ['cpi_9606.ENSP00000270202', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000279178'], ['cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000223095', 'cpi_9606.ENSP00000263321', 'cpi_9606.ENSP00000361666', 'cpi_9606.ENSP00000412673'], ['cpi_9606.ENSP00000264381', 'cpi_9606.ENSP00000319788', 'cpi_9606.ENSP00000451040', 'cpi_9606.ENSP00000261693', 'cpi_9606.ENSP00000334198'], ['cpi_9606.ENSP00000258400', 'cpi_9606.ENSP00000329623', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000471569', 'cpi_9606.ENSP00000342850'], ['cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000286301', 'cpi_9606.ENSP00000317379', 'cpi_9606.ENSP00000307599'], ['cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000308165', 'cpi_9606.ENSP00000331912'], ['cpi_9606.ENSP00000358963', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000343040', 'cpi_9606.ENSP00000355778'], ['cpi_9606.ENSP00000276198', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000347942', 'cpi_9606.ENSP00000226574', 'cpi_9606.ENSP00000356694'], ['cpi_9606.ENSP00000316244', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000233146'], ['cpi_9606.ENSP00000366506', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000275525', 'cpi_9606.ENSP00000428340', 'cpi_9606.ENSP00000344192'], ['cpi_9606.ENSP00000398698', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000394936', 'cpi_9606.ENSP00000367851', 'cpi_9606.ENSP00000307014'], ['cpi_9606.ENSP00000297494', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000470087'], ['cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000273550', 'cpi_9606.ENSP00000356954', 'cpi_9606.ENSP00000360493', 'cpi_9606.ENSP00000402152'], ['cpi_9606.ENSP00000313661', 'cpi_9606.ENSP00000304845', 'cpi_9606.ENSP00000302111', 'cpi_9606.ENSP00000308774', 'cpi_9606.ENSP00000358784'], ['cpi_9606.ENSP00000263025', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000387946', 'cpi_9606.ENSP00000359096'], ['cpi_9606.ENSP00000305372', 'cpi_9606.ENSP00000303174', 'cpi_9606.ENSP00000388648', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000445340'], ['cpi_9606.ENSP00000215832', 'cpi_9606.ENSP00000274793', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000259396', 'cpi_9606.ENSP00000293745'], ['cpi_9606.ENSP00000366084', 'cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000295491'], ['cpi_9606.ENSP00000280155', 'cpi_9606.ENSP00000358107', 'cpi_9606.ENSP00000344352', 'cpi_9606.ENSP00000221972', 'cpi_9606.ENSP00000309124'], ['cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000270474', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000427562'], ['cpi_9606.ENSP00000306245', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000376943', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000297350'], ['cpi_9606.ENSP00000237612', 'cpi_9606.ENSP00000254488', 'cpi_9606.ENSP00000362036', 'cpi_9606.ENSP00000282561', 'cpi_9606.ENSP00000258749'], ['cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000256958', 'cpi_9606.ENSP00000385806', 'cpi_9606.ENSP00000343838'], ['cpi_9606.ENSP00000287820', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000311028', 'cpi_9606.ENSP00000343477', 'cpi_9606.ENSP00000387281'], ['cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000427514', 'cpi_9606.ENSP00000386069'], ['cpi_9606.ENSP00000331746', 'cpi_9606.ENSP00000305221', 'cpi_9606.ENSP00000353427', 'cpi_9606.ENSP00000200676', 'cpi_9606.ENSP00000323568'], ['cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000231454', 'cpi_9606.ENSP00000333212', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000411593'], ['cpi_9606.ENSP00000289753', 'cpi_9606.ENSP00000320709', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000372023', 'cpi_9606.ENSP00000260010'], ['cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000176763', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000361359'], ['cpi_9606.ENSP00000252945', 'cpi_9606.ENSP00000353915', 'cpi_9606.ENSP00000357283', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000216185'], ['cpi_9606.ENSP00000234310', 'cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000263126', 'cpi_9606.ENSP00000368766', 'cpi_9606.ENSP00000262999'], ['cpi_9606.ENSP00000231509', 'cpi_9606.ENSP00000251535', 'cpi_9606.ENSP00000332369', 'cpi_9606.ENSP00000216962', 'cpi_9606.ENSP00000354394'], ['cpi_9606.ENSP00000355759', 'cpi_9606.ENSP00000374467', 'cpi_9606.ENSP00000306129', 'cpi_9606.ENSP00000378517', 'cpi_9606.ENSP00000233242'], ['cpi_9606.ENSP00000412237', 'cpi_9606.ENSP00000340684', 'cpi_9606.ENSP00000365663', 'cpi_9606.ENSP00000358548', 'cpi_9606.ENSP00000000442'], ['cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000447149'], ['cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000296871', 'cpi_9606.ENSP00000448059', 'cpi_9606.ENSP00000262367'], ['cpi_9606.ENSP00000394624', 'cpi_9606.ENSP00000301633', 'cpi_9606.ENSP00000310928', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000360967'], ['cpi_9606.ENSP00000306512', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000302967', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000294728'], ['cpi_9606.ENSP00000305742', 'cpi_9606.ENSP00000366307', 'cpi_9606.ENSP00000248553', 'cpi_9606.ENSP00000222330', 'cpi_9606.ENSP00000255380'], ['cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000346148', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000307766'], ['cpi_9606.ENSP00000308541', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000463999', 'cpi_9606.ENSP00000280357'], ['cpi_9606.ENSP00000363868', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000312455', 'cpi_9606.ENSP00000327652', 'cpi_9606.ENSP00000264637'], ['cpi_9606.ENSP00000414303', 'cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000262160', 'cpi_9606.ENSP00000267843', 'cpi_9606.ENSP00000307235'], ['cpi_9606.ENSP00000363822', 'cpi_9606.ENSP00000303522', 'cpi_9606.ENSP00000349576', 'cpi_9606.ENSP00000410294', 'cpi_9606.ENSP00000398632'], ['cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000370473', 'cpi_9606.ENSP00000410076', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000264867'], ['cpi_9606.ENSP00000464149', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000294954', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000352702'], ['cpi_9606.ENSP00000345096', 'cpi_9606.ENSP00000264657', 'cpi_9606.ENSP00000300061', 'cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000391826'], ['cpi_9606.ENSP00000306662', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000252809', 'cpi_9606.ENSP00000330393'], ['cpi_9606.ENSP00000295897', 'cpi_9606.ENSP00000373169', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000343204', 'cpi_9606.ENSP00000263980'], ['cpi_9606.ENSP00000330237', 'cpi_9606.ENSP00000364709', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000322617'], ['cpi_9606.ENSP00000290866', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000347979', 'cpi_9606.ENSP00000316786'], ['cpi_9606.ENSP00000302150', 'cpi_9606.ENSP00000256383', 'cpi_9606.ENSP00000311095', 'cpi_9606.ENSP00000263377', 'cpi_9606.ENSP00000263923'], ['cpi_9606.ENSP00000260433', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000353791', 'cpi_9606.ENSP00000355317', 'cpi_9606.ENSP00000394932'], ['cpi_9606.ENSP00000219070', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000267119', 'cpi_9606.ENSP00000382659'], ['cpi_9606.ENSP00000358327', 'cpi_9606.ENSP00000296522', 'cpi_9606.ENSP00000310447', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000176183'], ['cpi_9606.ENSP00000265572', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000252723', 'cpi_9606.ENSP00000290349', 'cpi_9606.ENSP00000312029'], ['cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000369757', 'cpi_9606.ENSP00000270776', 'cpi_9606.ENSP00000331358'], ['cpi_9606.ENSP00000358022', 'cpi_9606.ENSP00000309757', 'cpi_9606.ENSP00000231228', 'cpi_9606.ENSP00000285979', 'cpi_9606.ENSP00000326219'], ['cpi_9606.ENSP00000327251', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000164139', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000260356'], ['cpi_9606.ENSP00000361405', 'cpi_9606.ENSP00000355325', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000451030'], ['cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000239223', 'cpi_9606.ENSP00000262461', 'cpi_9606.ENSP00000336630', 'cpi_9606.ENSP00000312652'], ['cpi_9606.ENSP00000279387', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000252486', 'cpi_9606.ENSP00000255465'], ['cpi_9606.ENSP00000332549', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000318822', 'cpi_9606.ENSP00000322924', 'cpi_9606.ENSP00000428924'], ['cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000241261', 'cpi_9606.ENSP00000356671', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000288135'], ['cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000354107', 'cpi_9606.ENSP00000329357', 'cpi_9606.ENSP00000362353', 'cpi_9606.ENSP00000234071'], ['cpi_9606.ENSP00000321584', 'cpi_9606.ENSP00000263341', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000342560'], ['cpi_9606.ENSP00000307786', 'cpi_9606.ENSP00000355930', 'cpi_9606.ENSP00000365380', 'cpi_9606.ENSP00000266682', 'cpi_9606.ENSP00000216392'], ['cpi_9606.ENSP00000274606', 'cpi_9606.ENSP00000304915', 'cpi_9606.ENSP00000276449', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000222256'], ['cpi_9606.ENSP00000411532', 'cpi_9606.ENSP00000365016', 'cpi_9606.ENSP00000358730', 'cpi_9606.ENSP00000356729', 'cpi_9606.ENSP00000287936'], ['cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000298171', 'cpi_9606.ENSP00000225964', 'cpi_9606.ENSP00000221515'], ['cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000314949', 'cpi_9606.ENSP00000287907', 'cpi_9606.ENSP00000304408', 'cpi_9606.ENSP00000227758'], ['cpi_9606.ENSP00000225831', 'cpi_9606.ENSP00000364802', 'cpi_9606.ENSP00000359635', 'cpi_9606.ENSP00000259271', 'cpi_9606.ENSP00000245457'], ['cpi_9606.ENSP00000337459', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000371554', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000345708'], ['cpi_9606.ENSP00000357669', 'cpi_9606.ENSP00000262735', 'cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000305302'], ['cpi_9606.ENSP00000371067', 'cpi_9606.ENSP00000234961', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000296122'], ['cpi_9606.ENSP00000225275', 'cpi_9606.ENSP00000239938', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000351885', 'cpi_9606.ENSP00000340820'], ['cpi_9606.ENSP00000260970', 'cpi_9606.ENSP00000312673', 'cpi_9606.ENSP00000358511', 'cpi_9606.ENSP00000278616', 'cpi_9606.ENSP00000330199'], ['cpi_9606.ENSP00000331514', 'cpi_9606.ENSP00000244741', 'cpi_9606.ENSP00000282018', 'cpi_9606.ENSP00000346598', 'cpi_9606.ENSP00000333534'], ['cpi_9606.ENSP00000231449', 'cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000262948', 'cpi_9606.ENSP00000346298', 'cpi_9606.ENSP00000321988'], ['cpi_9606.ENSP00000369050', 'cpi_9606.ENSP00000366416', 'cpi_9606.ENSP00000301634', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000295834'], ['cpi_9606.ENSP00000264498', 'cpi_9606.ENSP00000354193', 'cpi_9606.ENSP00000400175', 'cpi_9606.ENSP00000338627', 'cpi_9606.ENSP00000226413'], ['cpi_9606.ENSP00000370571', 'cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000252804', 'cpi_9606.ENSP00000386171'], ['cpi_9606.ENSP00000216117', 'cpi_9606.ENSP00000433290', 'cpi_9606.ENSP00000341885', 'cpi_9606.ENSP00000341045', 'cpi_9606.ENSP00000352584'], ['cpi_9606.ENSP00000266970', 'cpi_9606.ENSP00000335544', 'cpi_9606.ENSP00000355657', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000242375'], ['cpi_9606.ENSP00000354511', 'cpi_9606.ENSP00000380252', 'cpi_9606.ENSP00000239849', 'cpi_9606.ENSP00000332816', 'cpi_9606.ENSP00000232219'], ['cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000349252', 'cpi_9606.ENSP00000386229', 'cpi_9606.ENSP00000384273', 'cpi_9606.ENSP00000256119'], ['cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000304895', 'cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000282397'], ['cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000212015', 'cpi_9606.ENSP00000311469', 'cpi_9606.ENSP00000260649', 'cpi_9606.ENSP00000268251'], ['cpi_9606.ENSP00000262623', 'cpi_9606.ENSP00000360266', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000252029', 'cpi_9606.ENSP00000354569'], ['cpi_9606.ENSP00000301141', 'cpi_9606.ENSP00000321106', 'cpi_9606.ENSP00000251453', 'cpi_9606.ENSP00000225927', 'cpi_9606.ENSP00000354558'], ['cpi_9606.ENSP00000355627', 'cpi_9606.ENSP00000353878', 'cpi_9606.ENSP00000320401', 'cpi_9606.ENSP00000377192', 'cpi_9606.ENSP00000348645'], ['cpi_9606.ENSP00000368349', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000360973', 'cpi_9606.ENSP00000275300', 'cpi_9606.ENSP00000393312'], ['cpi_9606.ENSP00000324806', 'cpi_9606.ENSP00000315011', 'cpi_9606.ENSP00000301146', 'cpi_9606.ENSP00000296674', 'cpi_9606.ENSP00000265723'], ['cpi_9606.ENSP00000368683', 'cpi_9606.ENSP00000394033', 'cpi_9606.ENSP00000361151', 'cpi_9606.ENSP00000308032', 'cpi_9606.ENSP00000254810'], ['cpi_9606.ENSP00000279593', 'cpi_9606.ENSP00000393333', 'cpi_9606.ENSP00000309103', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000366662'], ['cpi_9606.ENSP00000338018', 'cpi_9606.ENSP00000399168', 'cpi_9606.ENSP00000419692', 'cpi_9606.ENSP00000267377', 'cpi_9606.ENSP00000371985'], ['cpi_9606.ENSP00000275493', 'cpi_9606.ENSP00000349577', 'cpi_9606.ENSP00000308549', 'cpi_9606.ENSP00000264896', 'cpi_9606.ENSP00000196551'], ['cpi_9606.ENSP00000299855', 'cpi_9606.ENSP00000367309', 'cpi_9606.ENSP00000264832', 'cpi_9606.ENSP00000378699', 'cpi_9606.ENSP00000344674'], ['cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000362344', 'cpi_9606.ENSP00000335657', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000277120'], ['cpi_9606.ENSP00000220809', 'cpi_9606.ENSP00000333685', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000459962', 'cpi_9606.ENSP00000341828'], ['cpi_9606.ENSP00000261405', 'cpi_9606.ENSP00000362508', 'cpi_9606.ENSP00000215659', 'cpi_9606.ENSP00000433821', 'cpi_9606.ENSP00000303452'], ['cpi_9606.ENSP00000285379', 'cpi_9606.ENSP00000386884', 'cpi_9606.ENSP00000364805', 'cpi_9606.ENSP00000297268', 'cpi_9606.ENSP00000466799'], ['cpi_9606.ENSP00000260302', 'cpi_9606.ENSP00000355920', 'cpi_9606.ENSP00000211287', 'cpi_9606.ENSP00000253727', 'cpi_9606.ENSP00000419782'], ['cpi_9606.ENSP00000218548', 'cpi_9606.ENSP00000225577', 'cpi_9606.ENSP00000217305', 'cpi_9606.ENSP00000263464', 'cpi_9606.ENSP00000387683'], ['cpi_9606.ENSP00000368727', 'cpi_9606.ENSP00000292303', 'cpi_9606.ENSP00000219919', 'cpi_9606.ENSP00000356150', 'cpi_9606.ENSP00000331736'], ['cpi_9606.ENSP00000356825', 'cpi_9606.ENSP00000228872', 'cpi_9606.ENSP00000307259', 'cpi_9606.ENSP00000379339', 'cpi_9606.ENSP00000346901'], ['cpi_9606.ENSP00000381607', 'cpi_9606.ENSP00000276571', 'cpi_9606.ENSP00000430432', 'cpi_9606.ENSP00000362513', 'cpi_9606.ENSP00000355533'], ['cpi_9606.ENSP00000375881', 'cpi_9606.ENSP00000324248', 'cpi_9606.ENSP00000252321', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000320866'], ['cpi_9606.ENSP00000337103', 'cpi_9606.ENSP00000276414', 'cpi_9606.ENSP00000276431', 'cpi_9606.ENSP00000270625', 'cpi_9606.ENSP00000248041'], ['cpi_9606.ENSP00000359478', 'cpi_9606.ENSP00000375066', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000265403', 'cpi_9606.ENSP00000435777'], ['cpi_9606.ENSP00000302665', 'cpi_9606.ENSP00000338082', 'cpi_9606.ENSP00000370912', 'cpi_9606.ENSP00000368752', 'cpi_9606.ENSP00000303424'], ['cpi_9606.ENSP00000387662', 'cpi_9606.ENSP00000387888', 'cpi_9606.ENSP00000382250', 'cpi_9606.ENSP00000351908', 'cpi_9606.ENSP00000236850'], ['cpi_9606.ENSP00000229135', 'cpi_9606.ENSP00000384957', 'cpi_9606.ENSP00000384708', 'cpi_9606.ENSP00000359998', 'cpi_9606.ENSP00000303830'], ['cpi_9606.ENSP00000370129', 'cpi_9606.ENSP00000379110', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000341189', 'cpi_9606.ENSP00000407375'], ['cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000260630', 'cpi_9606.ENSP00000429374', 'cpi_9606.ENSP0000025

🔄 Processing features: 100%|██████████| 1607/1607 [06:50<00:00,  3.91feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000326219', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000356094'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000355629', 'cpi_9606.ENSP00000359353', 'cpi_9606.ENSP00000304822'], ['cpi_9606.ENSP00000360372', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000261937', 'cpi_9606.ENSP00000430684'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000360773', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000332296'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000257290', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000291294'], ['cpi_9606.ENSP00000367959', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000267101', 'cpi_9606.ENSP00000427514', 'cpi_9606.ENSP00000428340'], ['cpi_9606.ENSP00000311032', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000367848'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000354394'], ['cpi_9606.ENSP00000258743', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000261799', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000220616'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000337335', 'cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000463999'], ['cpi_9606.ENSP00000337450', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000336630', 'cpi_9606.ENSP00000301891', 'cpi_9606.ENSP00000286479'], ['cpi_9606.ENSP00000270349', 'cpi_9606.ENSP00000293288', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000332816'], ['cpi_9606.ENSP00000265724', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000303522', 'cpi_9606.ENSP00000381097', 'cpi_9606.ENSP00000263321'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000351209', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000358548', 'cpi_9606.ENSP00000307599'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000244217', 'cpi_9606.ENSP00000279178', 'cpi_9606.ENSP00000216037', 'cpi_9606.ENSP00000297350'], ['cpi_9606.ENSP00000272190', 'cpi_9606.ENSP00000354476', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000295454', 'cpi_9606.ENSP00000000442'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000299267', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000377947'], ['cpi_9606.ENSP00000354612', 'cpi_9606.ENSP00000277010', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000414334', 'cpi_9606.ENSP00000339527'], ['cpi_9606.ENSP00000260433', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000283635', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000374323'], ['cpi_9606.ENSP00000369960', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000335592'], ['cpi_9606.ENSP00000356438', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000351957'], ['cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000279387', 'cpi_9606.ENSP00000367102', 'cpi_9606.ENSP00000275525', 'cpi_9606.ENSP00000457706'], ['cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000312664', 'cpi_9606.ENSP00000344192', 'cpi_9606.ENSP00000263126'], ['cpi_9606.ENSP00000269305', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000266376'], ['cpi_9606.ENSP00000258400', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000302111', 'cpi_9606.ENSP00000417229', 'cpi_9606.ENSP00000343040'], ['cpi_9606.ENSP00000337949', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000366307', 'cpi_9606.ENSP00000378517', 'cpi_9606.ENSP00000326119'], ['cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000389414', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000342235'], ['cpi_9606.ENSP00000354859', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000278616', 'cpi_9606.ENSP00000370381', 'cpi_9606.ENSP00000301178'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000394936'], ['cpi_9606.ENSP00000215832', 'cpi_9606.ENSP00000274547', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000387946', 'cpi_9606.ENSP00000445340'], ['cpi_9606.ENSP00000363822', 'cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000200676', 'cpi_9606.ENSP00000395653', 'cpi_9606.ENSP00000245539'], ['cpi_9606.ENSP00000270202', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000353292', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000352900'], ['cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000261196', 'cpi_9606.ENSP00000300061', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000348069'], ['cpi_9606.ENSP00000297494', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000319788'], ['cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000343477'], ['cpi_9606.ENSP00000358963', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000344352', 'cpi_9606.ENSP00000320935', 'cpi_9606.ENSP00000362036'], ['cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000273550', 'cpi_9606.ENSP00000356954', 'cpi_9606.ENSP00000471569', 'cpi_9606.ENSP00000470087'], ['cpi_9606.ENSP00000305372', 'cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000323568'], ['cpi_9606.ENSP00000263025', 'cpi_9606.ENSP00000331912', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000344674', 'cpi_9606.ENSP00000264637'], ['cpi_9606.ENSP00000398698', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000254227'], ['cpi_9606.ENSP00000316244', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000263980'], ['cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000333212', 'cpi_9606.ENSP00000231454', 'cpi_9606.ENSP00000451040', 'cpi_9606.ENSP00000389338'], ['cpi_9606.ENSP00000366506', 'cpi_9606.ENSP00000304845', 'cpi_9606.ENSP00000365663', 'cpi_9606.ENSP00000353791', 'cpi_9606.ENSP00000357283'], ['cpi_9606.ENSP00000276198', 'cpi_9606.ENSP00000394033', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000226574', 'cpi_9606.ENSP00000360493'], ['cpi_9606.ENSP00000290866', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000376943', 'cpi_9606.ENSP00000259396', 'cpi_9606.ENSP00000258749'], ['cpi_9606.ENSP00000306245', 'cpi_9606.ENSP00000242057', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000223366', 'cpi_9606.ENSP00000225474'], ['cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000286301', 'cpi_9606.ENSP00000295491'], ['cpi_9606.ENSP00000264381', 'cpi_9606.ENSP00000312455', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000252809', 'cpi_9606.ENSP00000320025'], ['cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000454071', 'cpi_9606.ENSP00000347942'], ['cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000294728', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000267119'], ['cpi_9606.ENSP00000313661', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000330393', 'cpi_9606.ENSP00000234071'], ['cpi_9606.ENSP00000386069', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000262888'], ['cpi_9606.ENSP00000321584', 'cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000368766', 'cpi_9606.ENSP00000309124', 'cpi_9606.ENSP00000367851'], ['cpi_9606.ENSP00000219070', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000296871', 'cpi_9606.ENSP00000241453'], ['cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000366084', 'cpi_9606.ENSP00000308165', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000369530'], ['cpi_9606.ENSP00000330237', 'cpi_9606.ENSP00000364709', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000280155', 'cpi_9606.ENSP00000411593'], ['cpi_9606.ENSP00000302150', 'cpi_9606.ENSP00000314949', 'cpi_9606.ENSP00000251535', 'cpi_9606.ENSP00000361359', 'cpi_9606.ENSP00000347979'], ['cpi_9606.ENSP00000378323', 'cpi_9606.ENSP00000361666', 'cpi_9606.ENSP00000221972', 'cpi_9606.ENSP00000358784', 'cpi_9606.ENSP00000409378'], ['cpi_9606.ENSP00000252945', 'cpi_9606.ENSP00000353915', 'cpi_9606.ENSP00000353427', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000264867'], ['cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000261693', 'cpi_9606.ENSP00000387281', 'cpi_9606.ENSP00000388648', 'cpi_9606.ENSP00000216185'], ['cpi_9606.ENSP00000308541', 'cpi_9606.ENSP00000329623', 'cpi_9606.ENSP00000276449', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000231228'], ['cpi_9606.ENSP00000218548', 'cpi_9606.ENSP00000384273', 'cpi_9606.ENSP00000287936', 'cpi_9606.ENSP00000176183', 'cpi_9606.ENSP00000307014'], ['cpi_9606.ENSP00000306512', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000355533', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000216862'], ['cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000320709', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000260010'], ['cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000385806', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000311095', 'cpi_9606.ENSP00000393312'], ['cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000322924', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000292095'], ['cpi_9606.ENSP00000234310', 'cpi_9606.ENSP00000264657', 'cpi_9606.ENSP00000282561', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000255465'], ['cpi_9606.ENSP00000345096', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000252723'], ['cpi_9606.ENSP00000262623', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000373169', 'cpi_9606.ENSP00000338548'], ['cpi_9606.ENSP00000355759', 'cpi_9606.ENSP00000248076', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000270474', 'cpi_9606.ENSP00000252486'], ['cpi_9606.ENSP00000295897', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000266682', 'cpi_9606.ENSP00000451030', 'cpi_9606.ENSP00000305422'], ['cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000316786', 'cpi_9606.ENSP00000312029', 'cpi_9606.ENSP00000262461'], ['cpi_9606.ENSP00000363868', 'cpi_9606.ENSP00000296522', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000289753'], ['cpi_9606.ENSP00000223095', 'cpi_9606.ENSP00000362924', 'cpi_9606.ENSP00000268053', 'cpi_9606.ENSP00000307235', 'cpi_9606.ENSP00000414303'], ['cpi_9606.ENSP00000231509', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000410076', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000328973'], ['cpi_9606.ENSP00000464149', 'cpi_9606.ENSP00000237612', 'cpi_9606.ENSP00000217305', 'cpi_9606.ENSP00000355657', 'cpi_9606.ENSP00000364802'], ['cpi_9606.ENSP00000306662', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000222330', 'cpi_9606.ENSP00000233242', 'cpi_9606.ENSP00000256119'], ['cpi_9606.ENSP00000361405', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000256958', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000263464'], ['cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000371067', 'cpi_9606.ENSP00000239849', 'cpi_9606.ENSP00000430432', 'cpi_9606.ENSP00000295834'], ['cpi_9606.ENSP00000287820', 'cpi_9606.ENSP00000259089', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000448059', 'cpi_9606.ENSP00000352702'], ['cpi_9606.ENSP00000263341', 'cpi_9606.ENSP00000364782', 'cpi_9606.ENSP00000254488', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000308774'], ['cpi_9606.ENSP00000331746', 'cpi_9606.ENSP00000303174', 'cpi_9606.ENSP00000354107', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000365016'], ['cpi_9606.ENSP00000340684', 'cpi_9606.ENSP00000231449', 'cpi_9606.ENSP00000333496', 'cpi_9606.ENSP00000233146', 'cpi_9606.ENSP00000274793'], ['cpi_9606.ENSP00000307786', 'cpi_9606.ENSP00000260356', 'cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000410294', 'cpi_9606.ENSP00000309649'], ['cpi_9606.ENSP00000327251', 'cpi_9606.ENSP00000252321', 'cpi_9606.ENSP00000225927', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000346298'], ['cpi_9606.ENSP00000306129', 'cpi_9606.ENSP00000358107', 'cpi_9606.ENSP00000310928', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000346598'], ['cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000386229', 'cpi_9606.ENSP00000265723', 'cpi_9606.ENSP00000360967'], ['cpi_9606.ENSP00000411532', 'cpi_9606.ENSP00000296122', 'cpi_9606.ENSP00000267843', 'cpi_9606.ENSP00000366416', 'cpi_9606.ENSP00000241600'], ['cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000295598', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000398632', 'cpi_9606.ENSP00000434364'], ['cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000400175', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000307766', 'cpi_9606.ENSP00000262948'], ['cpi_9606.ENSP00000358327', 'cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000356832', 'cpi_9606.ENSP00000248553', 'cpi_9606.ENSP00000386171'], ['cpi_9606.ENSP00000216117', 'cpi_9606.ENSP00000354569', 'cpi_9606.ENSP00000311028', 'cpi_9606.ENSP00000305221', 'cpi_9606.ENSP00000305302'], ['cpi_9606.ENSP00000337459', 'cpi_9606.ENSP00000330199', 'cpi_9606.ENSP00000301633', 'cpi_9606.ENSP00000216962', 'cpi_9606.ENSP00000365380'], ['cpi_9606.ENSP00000369050', 'cpi_9606.ENSP00000292513', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000372023', 'cpi_9606.ENSP00000338627'], ['cpi_9606.ENSP00000264498', 'cpi_9606.ENSP00000263923', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000369816'], ['cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000241261', 'cpi_9606.ENSP00000428924', 'cpi_9606.ENSP00000359635', 'cpi_9606.ENSP00000254066'], ['cpi_9606.ENSP00000394624', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000268035', 'cpi_9606.ENSP00000270776', 'cpi_9606.ENSP00000346067'], ['cpi_9606.ENSP00000327652', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000318822', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000282397'], ['cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000275300', 'cpi_9606.ENSP00000419692', 'cpi_9606.ENSP00000274026', 'cpi_9606.ENSP00000299178'], ['cpi_9606.ENSP00000305742', 'cpi_9606.ENSP00000244741', 'cpi_9606.ENSP00000285979', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000359793'], ['cpi_9606.ENSP00000412237', 'cpi_9606.ENSP00000327801', 'cpi_9606.ENSP00000355778', 'cpi_9606.ENSP00000287907', 'cpi_9606.ENSP00000362513'], ['cpi_9606.ENSP00000331514', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000309757', 'cpi_9606.ENSP00000382659', 'cpi_9606.ENSP00000419782'], ['cpi_9606.ENSP00000368683', 'cpi_9606.ENSP00000302886', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000176763', 'cpi_9606.ENSP00000262367'], ['cpi_9606.ENSP00000357669', 'cpi_9606.ENSP00000354558', 'cpi_9606.ENSP00000234371', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000341045'], ['cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000216714', 'cpi_9606.ENSP00000331736', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000343204'], ['cpi_9606.ENSP00000356825', 'cpi_9606.ENSP00000355930', 'cpi_9606.ENSP00000329357', 'cpi_9606.ENSP00000225964', 'cpi_9606.ENSP00000259271'], ['cpi_9606.ENSP00000225831', 'cpi_9606.ENSP00000349576', 'cpi_9606.ENSP00000355317', 'cpi_9606.ENSP00000321106', 'cpi_9606.ENSP00000352584'], ['cpi_9606.ENSP00000370571', 'cpi_9606.ENSP00000351908', 'cpi_9606.ENSP00000352035', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000296545'], ['cpi_9606.ENSP00000274606', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000264832', 'cpi_9606.ENSP00000301146', 'cpi_9606.ENSP00000331358'], ['cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000212015', 'cpi_9606.ENSP00000427562', 'cpi_9606.ENSP00000356694', 'cpi_9606.ENSP00000391826'], ['cpi_9606.ENSP00000292303', 'cpi_9606.ENSP00000370129', 'cpi_9606.ENSP00000219700', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000368752'], ['cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000276414', 'cpi_9606.ENSP00000232219', 'cpi_9606.ENSP00000338082', 'cpi_9606.ENSP00000380252'], ['cpi_9606.ENSP00000265572', 'cpi_9606.ENSP00000262160', 'cpi_9606.ENSP00000309968', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000252029'], ['cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000324270', 'cpi_9606.ENSP00000353878', 'cpi_9606.ENSP00000368104', 'cpi_9606.ENSP00000349577'], ['cpi_9606.ENSP00000368349', 'cpi_9606.ENSP00000308032', 'cpi_9606.ENSP00000315011', 'cpi_9606.ENSP00000317379', 'cpi_9606.ENSP00000338018'], ['cpi_9606.ENSP00000301141', 'cpi_9606.ENSP00000369647', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000263377', 'cpi_9606.ENSP00000256383'], ['cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000304895', 'cpi_9606.ENSP00000358511', 'cpi_9606.ENSP00000252804', 'cpi_9606.ENSP00000332369'], ['cpi_9606.ENSP00000368727', 'cpi_9606.ENSP00000358730', 'cpi_9606.ENSP00000264896', 'cpi_9606.ENSP00000357981', 'cpi_9606.ENSP00000285238'], ['cpi_9606.ENSP00000260970', 'cpi_9606.ENSP00000312673', 'cpi_9606.ENSP00000393333', 'cpi_9606.ENSP00000297268', 'cpi_9606.ENSP00000253004'], ['cpi_9606.ENSP00000266970', 'cpi_9606.ENSP00000360973', 'cpi_9606.ENSP00000348645', 'cpi_9606.ENSP00000221515', 'cpi_9606.ENSP00000362649'], ['cpi_9606.ENSP00000225275', 'cpi_9606.ENSP00000379213', 'cpi_9606.ENSP00000322421', 'cpi_9606.ENSP00000364805', 'cpi_9606.ENSP00000311469'], ['cpi_9606.ENSP00000318585', 'cpi_9606.ENSP00000387699', 'cpi_9606.ENSP00000459962', 'cpi_9606.ENSP00000320401', 'cpi_9606.ENSP00000320866'], ['cpi_9606.ENSP00000261405', 'cpi_9606.ENSP00000341189', 'cpi_9606.ENSP00000433821', 'cpi_9606.ENSP00000234961', 'cpi_9606.ENSP00000242375'], ['cpi_9606.ENSP00000317842', 'cpi_9606.ENSP00000297469', 'cpi_9606.ENSP00000219919', 'cpi_9606.ENSP00000251453', 'cpi_9606.ENSP00000350767'], ['cpi_9606.ENSP00000359478', 'cpi_9606.ENSP00000386884', 'cpi_9606.ENSP00000368632', 'cpi_9606.ENSP00000319591', 'cpi_9606.ENSP00000288135'], ['cpi_9606.ENSP00000367309', 'cpi_9606.ENSP00000369757', 'cpi_9606.ENSP00000304915', 'cpi_9606.ENSP00000292896', 'cpi_9606.ENSP00000225371'], ['cpi_9606.ENSP00000275493', 'cpi_9606.ENSP00000328173', 'cpi_9606.ENSP00000321988', 'cpi_9606.ENSP00000420168', 'cpi_9606.ENSP00000256906'], ['cpi_9606.ENSP00000279593', 'cpi_9606.ENSP00000262735', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000290349', 'cpi_9606.ENSP00000333534'], ['cpi_9606.ENSP00000332549', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000307445', 'cpi_9606.ENSP00000309103', 'cpi_9606.ENSP00000217426'], ['cpi_9606.ENSP00000269571', 'cpi_9606.ENSP00000362401', 'cpi_9606.ENSP00000349252', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000368880'], ['cpi_9606.ENSP00000375881', 'cpi_9606.ENSP00000308549', 'cpi_9606.ENSP00000340820', 'cpi_9606.ENSP00000359998', 'cpi_9606.ENSP00000351885'], ['cpi_9606.ENSP00000354532', 'cpi_9606.ENSP00000239938', 'cpi_9606.ENSP00000273430', 'cpi_9606.ENSP00000332679', 'cpi_9606.ENSP00000429374'], ['cpi_9606.ENSP00000355627', 'cpi_9606.ENSP00000301634', 'cpi_9606.ENSP00000360968', 'cpi_9606.ENSP00000356671', 'cpi_9606.ENSP00000253727'], ['cpi_9606.ENSP00000322788', 'cpi_9606.ENSP00000341828', 'cpi_9606.ENSP00000369654', 'cpi_9606.ENSP00000355920', 'cpi_9606.ENSP00000260227'], ['cpi_9606.ENSP00000387662', 'cpi_9606.ENSP00000362508', 'cpi_9606.ENSP00000382250', 'cpi_9606.ENSP00000333926', 'cpi_9606.ENSP00000277120'], ['cpi_9606.ENSP00000334145', 'cpi_9606.ENSP00000319814', 'cpi_9606.ENSP00000337773', 'cpi_9606.ENSP00000324173', 'cpi_9606.ENSP00000287641'], ['cpi_9606.ENSP00000363965', 'cpi_9606.ENSP00000241256', 'cpi_9606.ENSP00000321821', 'cpi_9606.ENSP00000296674', 'cpi_9606.ENSP00000216392'], ['cpi_9606.ENSP00000239223', 'cpi_9606.ENSP00000355523', 'cpi_9606.ENSP00000379339', 'cpi_9606.ENSP00000387683', 'cpi_9606.ENSP00000312652'], ['cpi_9606.ENSP00000302961', 'cpi_9606.ENSP00000335657', 'cpi_9606.ENSP00000305355', 'cpi_9606.ENSP00000353731', 'cpi_9606.ENSP00000248041'], ['cpi_9606.ENSP00000294954', 'cpi_9606.ENSP00000314649', 'cpi_9606.ENSP00000221930', 'cpi_9606.ENSP00000327431', 'cpi_9606.ENSP00000349467'], ['cpi_9606.ENSP00000302665', 'cpi_9606.ENSP00000211122', 'cpi_9606.ENSP00000342560', 'cpi_9606.ENSP0000035

🔄 Processing features: 100%|██████████| 1607/1607 [06:50<00:00,  3.92feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'cpi_9606.ENSP00000414334', 'cpi_9606.ENSP00000359793', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000285930'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000430684', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000356094'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000261937', 'cpi_9606.ENSP00000367848', 'cpi_9606.ENSP00000299178'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000360773', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000355629', 'cpi_9606.ENSP00000265294'], ['cpi_9606.ENSP00000360372', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000261799', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000372547'], ['cpi_9606.ENSP00000311032', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000359353', 'cpi_9606.ENSP00000445340', 'cpi_9606.ENSP00000003100'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000267119', 'cpi_9606.ENSP00000349577'], ['cpi_9606.ENSP00000367959', 'cpi_9606.ENSP00000337335', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000347942', 'cpi_9606.ENSP00000343477'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000395653', 'cpi_9606.ENSP00000374323', 'cpi_9606.ENSP00000312664'], ['cpi_9606.ENSP00000337450', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000355778', 'cpi_9606.ENSP00000216037', 'cpi_9606.ENSP00000385026'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000303424', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000332296'], ['cpi_9606.ENSP00000270349', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000367102', 'cpi_9606.ENSP00000340820'], ['cpi_9606.ENSP00000258400', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000257290'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000251535', 'cpi_9606.ENSP00000286479'], ['cpi_9606.ENSP00000265724', 'cpi_9606.ENSP00000304822', 'cpi_9606.ENSP00000354569', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000299847'], ['cpi_9606.ENSP00000258743', 'cpi_9606.ENSP00000261196', 'cpi_9606.ENSP00000262888', 'cpi_9606.ENSP00000295454', 'cpi_9606.ENSP00000394936'], ['cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000333212', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000353292'], ['cpi_9606.ENSP00000272190', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000354476', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000000442'], ['cpi_9606.ENSP00000356438', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000277010', 'cpi_9606.ENSP00000387946'], ['cpi_9606.ENSP00000369960', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000221972'], ['cpi_9606.ENSP00000337949', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000417229', 'cpi_9606.ENSP00000377947'], ['cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000363822', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000266376', 'cpi_9606.ENSP00000258749'], ['cpi_9606.ENSP00000215832', 'cpi_9606.ENSP00000274547', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000298472'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000353427', 'cpi_9606.ENSP00000299267', 'cpi_9606.ENSP00000292513', 'cpi_9606.ENSP00000447149'], ['cpi_9606.ENSP00000260433', 'cpi_9606.ENSP00000283635', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000381097', 'cpi_9606.ENSP00000359334'], ['cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000344192', 'cpi_9606.ENSP00000326119', 'cpi_9606.ENSP00000342235'], ['cpi_9606.ENSP00000276198', 'cpi_9606.ENSP00000293288', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000256958', 'cpi_9606.ENSP00000274545'], ['cpi_9606.ENSP00000354612', 'cpi_9606.ENSP00000348069', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000252723'], ['cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000231454', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000389338', 'cpi_9606.ENSP00000301891'], ['cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000320935', 'cpi_9606.ENSP00000289753', 'cpi_9606.ENSP00000386029'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000467676', 'cpi_9606.ENSP00000471569', 'cpi_9606.ENSP00000218099'], ['cpi_9606.ENSP00000354859', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000361359', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000275525'], ['cpi_9606.ENSP00000264381', 'cpi_9606.ENSP00000319788', 'cpi_9606.ENSP00000261693', 'cpi_9606.ENSP00000267101', 'cpi_9606.ENSP00000451040'], ['cpi_9606.ENSP00000316244', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000301178', 'cpi_9606.ENSP00000200676'], ['cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000263321', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000279178', 'cpi_9606.ENSP00000470087'], ['cpi_9606.ENSP00000263025', 'cpi_9606.ENSP00000331912', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000291295'], ['cpi_9606.ENSP00000297494', 'cpi_9606.ENSP00000353791', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000264637', 'cpi_9606.ENSP00000252809'], ['cpi_9606.ENSP00000358963', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000344352', 'cpi_9606.ENSP00000300061', 'cpi_9606.ENSP00000362649'], ['cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000366084', 'cpi_9606.ENSP00000286301', 'cpi_9606.ENSP00000262367', 'cpi_9606.ENSP00000259396'], ['cpi_9606.ENSP00000231509', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000343040', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000241453'], ['cpi_9606.ENSP00000398698', 'cpi_9606.ENSP00000176763', 'cpi_9606.ENSP00000295491', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000262999'], ['cpi_9606.ENSP00000305372', 'cpi_9606.ENSP00000303174', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000357283', 'cpi_9606.ENSP00000370381'], ['cpi_9606.ENSP00000269305', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000389414', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000254227'], ['cpi_9606.ENSP00000345096', 'cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000292427'], ['cpi_9606.ENSP00000368766', 'cpi_9606.ENSP00000329623', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000408860'], ['cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000273550', 'cpi_9606.ENSP00000356954', 'cpi_9606.ENSP00000307599', 'cpi_9606.ENSP00000263126'], ['cpi_9606.ENSP00000386069', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000454071', 'cpi_9606.ENSP00000225474'], ['cpi_9606.ENSP00000270202', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000242057', 'cpi_9606.ENSP00000216962'], ['cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000226574', 'cpi_9606.ENSP00000263923'], ['cpi_9606.ENSP00000308541', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000463999', 'cpi_9606.ENSP00000302111'], ['cpi_9606.ENSP00000280155', 'cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000347979', 'cpi_9606.ENSP00000362036', 'cpi_9606.ENSP00000367851'], ['cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000327652'], ['cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000304845', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000326219', 'cpi_9606.ENSP00000296871'], ['cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000330237', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000398632'], ['cpi_9606.ENSP00000234310', 'cpi_9606.ENSP00000361666', 'cpi_9606.ENSP00000255465', 'cpi_9606.ENSP00000358548', 'cpi_9606.ENSP00000378517'], ['cpi_9606.ENSP00000306512', 'cpi_9606.ENSP00000318912', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000308165'], ['cpi_9606.ENSP00000223095', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000262948', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000387281'], ['cpi_9606.ENSP00000414303', 'cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000376943', 'cpi_9606.ENSP00000307014'], ['cpi_9606.ENSP00000287820', 'cpi_9606.ENSP00000259089', 'cpi_9606.ENSP00000176183', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000312455'], ['cpi_9606.ENSP00000366506', 'cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000294728', 'cpi_9606.ENSP00000428340', 'cpi_9606.ENSP00000338548'], ['cpi_9606.ENSP00000313661', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000323568', 'cpi_9606.ENSP00000355533'], ['cpi_9606.ENSP00000237612', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000332369', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000343782'], ['cpi_9606.ENSP00000306245', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000353878', 'cpi_9606.ENSP00000360967', 'cpi_9606.ENSP00000360493'], ['cpi_9606.ENSP00000252945', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000353915', 'cpi_9606.ENSP00000259271', 'cpi_9606.ENSP00000300900'], ['cpi_9606.ENSP00000302150', 'cpi_9606.ENSP00000296122', 'cpi_9606.ENSP00000295256', 'cpi_9606.ENSP00000262461', 'cpi_9606.ENSP00000457706'], ['cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000306662', 'cpi_9606.ENSP00000295834', 'cpi_9606.ENSP00000221515', 'cpi_9606.ENSP00000304915'], ['cpi_9606.ENSP00000305742', 'cpi_9606.ENSP00000366307', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000222330', 'cpi_9606.ENSP00000231228'], ['cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000248553', 'cpi_9606.ENSP00000216392', 'cpi_9606.ENSP00000309124'], ['cpi_9606.ENSP00000363868', 'cpi_9606.ENSP00000339527', 'cpi_9606.ENSP00000393312', 'cpi_9606.ENSP00000316786', 'cpi_9606.ENSP00000225964'], ['cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000275300', 'cpi_9606.ENSP00000365663', 'cpi_9606.ENSP00000308774'], ['cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000270776', 'cpi_9606.ENSP00000428924'], ['cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000410294', 'cpi_9606.ENSP00000331358', 'cpi_9606.ENSP00000260356'], ['cpi_9606.ENSP00000290866', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000372023', 'cpi_9606.ENSP00000317379'], ['cpi_9606.ENSP00000378323', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000318822', 'cpi_9606.ENSP00000373169', 'cpi_9606.ENSP00000351209'], ['cpi_9606.ENSP00000355759', 'cpi_9606.ENSP00000374467', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000352608'], ['cpi_9606.ENSP00000412237', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000332816', 'cpi_9606.ENSP00000448059', 'cpi_9606.ENSP00000354394'], ['cpi_9606.ENSP00000321584', 'cpi_9606.ENSP00000264657', 'cpi_9606.ENSP00000282561', 'cpi_9606.ENSP00000263980', 'cpi_9606.ENSP00000434364'], ['cpi_9606.ENSP00000358327', 'cpi_9606.ENSP00000296522', 'cpi_9606.ENSP00000371554', 'cpi_9606.ENSP00000267843', 'cpi_9606.ENSP00000355317'], ['cpi_9606.ENSP00000263341', 'cpi_9606.ENSP00000399168', 'cpi_9606.ENSP00000233146', 'cpi_9606.ENSP00000329357', 'cpi_9606.ENSP00000307766'], ['cpi_9606.ENSP00000337459', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000311028', 'cpi_9606.ENSP00000307235', 'cpi_9606.ENSP00000311095'], ['cpi_9606.ENSP00000279387', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000427514', 'cpi_9606.ENSP00000287907', 'cpi_9606.ENSP00000346298'], ['cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000370473', 'cpi_9606.ENSP00000410076', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000322924'], ['cpi_9606.ENSP00000262623', 'cpi_9606.ENSP00000360266', 'cpi_9606.ENSP00000297350', 'cpi_9606.ENSP00000270474', 'cpi_9606.ENSP00000287766'], ['cpi_9606.ENSP00000464149', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000276449', 'cpi_9606.ENSP00000459962', 'cpi_9606.ENSP00000443194'], ['cpi_9606.ENSP00000340684', 'cpi_9606.ENSP00000231449', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000388648', 'cpi_9606.ENSP00000220616'], ['cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000309757', 'cpi_9606.ENSP00000382659', 'cpi_9606.ENSP00000358784'], ['cpi_9606.ENSP00000295897', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000343204', 'cpi_9606.ENSP00000349252', 'cpi_9606.ENSP00000308549'], ['cpi_9606.ENSP00000411532', 'cpi_9606.ENSP00000355930', 'cpi_9606.ENSP00000365380', 'cpi_9606.ENSP00000264867', 'cpi_9606.ENSP00000337773'], ['cpi_9606.ENSP00000307786', 'cpi_9606.ENSP00000312029', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000252029'], ['cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000330393', 'cpi_9606.ENSP00000336630', 'cpi_9606.ENSP00000282397', 'cpi_9606.ENSP00000369816'], ['cpi_9606.ENSP00000219070', 'cpi_9606.ENSP00000398655', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000260010', 'cpi_9606.ENSP00000178638'], ['cpi_9606.ENSP00000327251', 'cpi_9606.ENSP00000330199', 'cpi_9606.ENSP00000164139', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000306129'], ['cpi_9606.ENSP00000361405', 'cpi_9606.ENSP00000355325', 'cpi_9606.ENSP00000277120', 'cpi_9606.ENSP00000274793', 'cpi_9606.ENSP00000385806'], ['cpi_9606.ENSP00000218548', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000356671', 'cpi_9606.ENSP00000420168', 'cpi_9606.ENSP00000358730'], ['cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000233242', 'cpi_9606.ENSP00000291294', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000321988'], ['cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000276571', 'cpi_9606.ENSP00000252486', 'cpi_9606.ENSP00000365012', 'cpi_9606.ENSP00000419692'], ['cpi_9606.ENSP00000358022', 'cpi_9606.ENSP00000365016', 'cpi_9606.ENSP00000307259', 'cpi_9606.ENSP00000266682', 'cpi_9606.ENSP00000366662'], ['cpi_9606.ENSP00000320709', 'cpi_9606.ENSP00000264498', 'cpi_9606.ENSP00000359998', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000352702'], ['cpi_9606.ENSP00000301141', 'cpi_9606.ENSP00000303522', 'cpi_9606.ENSP00000356150', 'cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000386171'], ['cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000337103', 'cpi_9606.ENSP00000430432', 'cpi_9606.ENSP00000363089', 'cpi_9606.ENSP00000254488'], ['cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000260970', 'cpi_9606.ENSP00000278616', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000237527'], ['cpi_9606.ENSP00000331514', 'cpi_9606.ENSP00000244741', 'cpi_9606.ENSP00000335544', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000285979'], ['cpi_9606.ENSP00000397026', 'cpi_9606.ENSP00000354558', 'cpi_9606.ENSP00000303452', 'cpi_9606.ENSP00000320401', 'cpi_9606.ENSP00000344674'], ['cpi_9606.ENSP00000274606', 'cpi_9606.ENSP00000310928', 'cpi_9606.ENSP00000301146', 'cpi_9606.ENSP00000362353', 'cpi_9606.ENSP00000394932'], ['cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000298171', 'cpi_9606.ENSP00000241261', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000359635'], ['cpi_9606.ENSP00000216117', 'cpi_9606.ENSP00000433290', 'cpi_9606.ENSP00000270625', 'cpi_9606.ENSP00000305221', 'cpi_9606.ENSP00000305302'], ['cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000232219', 'cpi_9606.ENSP00000351885', 'cpi_9606.ENSP00000338627'], ['cpi_9606.ENSP00000368349', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000342560', 'cpi_9606.ENSP00000355657', 'cpi_9606.ENSP00000364802'], ['cpi_9606.ENSP00000394624', 'cpi_9606.ENSP00000301633', 'cpi_9606.ENSP00000223366', 'cpi_9606.ENSP00000362401', 'cpi_9606.ENSP00000341045'], ['cpi_9606.ENSP00000369050', 'cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000433821', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000225927'], ['cpi_9606.ENSP00000368683', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000265403', 'cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000296674'], ['cpi_9606.ENSP00000371067', 'cpi_9606.ENSP00000234961', 'cpi_9606.ENSP00000218388', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000287936'], ['cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000295400', 'cpi_9606.ENSP00000400175', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000354107'], ['cpi_9606.ENSP00000338018', 'cpi_9606.ENSP00000305692', 'cpi_9606.ENSP00000302846', 'cpi_9606.ENSP00000311469', 'cpi_9606.ENSP00000368104'], ['cpi_9606.ENSP00000265572', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000290349', 'cpi_9606.ENSP00000356832'], ['cpi_9606.ENSP00000370571', 'cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000253727', 'cpi_9606.ENSP00000356694'], ['cpi_9606.ENSP00000354511', 'cpi_9606.ENSP00000380252', 'cpi_9606.ENSP00000239849', 'cpi_9606.ENSP00000320866', 'cpi_9606.ENSP00000360973'], ['cpi_9606.ENSP00000317842', 'cpi_9606.ENSP00000297469', 'cpi_9606.ENSP00000219919', 'cpi_9606.ENSP00000346598', 'cpi_9606.ENSP00000304895'], ['cpi_9606.ENSP00000349467', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000333821', 'cpi_9606.ENSP00000352584', 'cpi_9606.ENSP00000363827'], ['cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000212015', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000346103', 'cpi_9606.ENSP00000362508'], ['cpi_9606.ENSP00000358511', 'cpi_9606.ENSP00000285238', 'cpi_9606.ENSP00000357981', 'cpi_9606.ENSP00000260227', 'cpi_9606.ENSP00000355920'], ['cpi_9606.ENSP00000387662', 'cpi_9606.ENSP00000387683', 'cpi_9606.ENSP00000382250', 'cpi_9606.ENSP00000309103', 'cpi_9606.ENSP00000367309'], ['cpi_9606.ENSP00000266970', 'cpi_9606.ENSP00000295589', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000394033', 'cpi_9606.ENSP00000332679'], ['cpi_9606.ENSP00000300738', 'cpi_9606.ENSP00000262735', 'cpi_9606.ENSP00000275216', 'cpi_9606.ENSP00000427562', 'cpi_9606.ENSP00000378699'], ['cpi_9606.ENSP00000360968', 'cpi_9606.ENSP00000314949', 'cpi_9606.ENSP00000359532', 'cpi_9606.ENSP00000384273', 'cpi_9606.ENSP00000274026'], ['cpi_9606.ENSP00000292303', 'cpi_9606.ENSP00000333926', 'cpi_9606.ENSP00000225577', 'cpi_9606.ENSP00000297268', 'cpi_9606.ENSP00000466799'], ['cpi_9606.ENSP00000318585', 'cpi_9606.ENSP00000239938', 'cpi_9606.ENSP00000419782', 'cpi_9606.ENSP00000304408', 'cpi_9606.ENSP00000307445'], ['cpi_9606.ENSP00000368727', 'cpi_9606.ENSP00000217305', 'cpi_9606.ENSP00000264896', 'cpi_9606.ENSP00000256383', 'cpi_9606.ENSP00000346901'], ['cpi_9606.ENSP00000225275', 'cpi_9606.ENSP00000379213', 'cpi_9606.ENSP00000211122', 'cpi_9606.ENSP00000369654', 'cpi_9606.ENSP00000288135'], ['cpi_9606.ENSP00000275493', 'cpi_9606.ENSP00000324248', 'cpi_9606.ENSP00000274353', 'cpi_9606.ENSP00000362513', 'cpi_9606.ENSP00000318646'], ['cpi_9606.ENSP00000225831', 'cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000365233', 'cpi_9606.ENSP00000302811', 'cpi_9606.ENSP00000251566'], ['cpi_9606.ENSP00000239223', 'cpi_9606.ENSP00000287641', 'cpi_9606.ENSP00000348645', 'cpi_9606.ENSP00000357669', 'cpi_9606.ENSP00000268053'], ['cpi_9606.ENSP00000386884', 'cpi_9606.ENSP00000288022', 'cpi_9606.ENSP00000368880', 'cpi_9606.ENSP00000196551', 'cpi_9606.ENSP00000356729'], ['cpi_9606.ENSP00000264426', 'cpi_9606.ENSP00000242152', 'cpi_9606.ENSP00000228872', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000321999'], ['cpi_9606.ENSP00000264832', 'cpi_9606.ENSP00000352035', 'cpi_9606.ENSP00000407375', 'cpi_9606.ENSP00000341828', 'cpi_9606.ENSP00000336764'], ['cpi_9606.ENSP00000355627', 'cpi_9606.ENSP00000369757', 'cpi_9606.ENSP00000368752', 'cpi_9606.ENSP00000353472', 'cpi_9606.ENSP00000341885'], ['cpi_9606.ENSP00000304767', 'cpi_9606.ENSP00000268035', 'cpi_9606.ENSP00000225371', 'cpi_9606.ENSP00000429374', 'cpi_9606.ENSP00000248041'], ['cpi_9606.ENSP00000313490', 'cpi_9606.ENSP00000312652', 'cpi_9606.ENSP00000267377', 'cpi_9606.ENSP00000276431', 'cpi_9606.ENSP00000387888'], ['cpi_9606.ENSP00000229135', 'cpi_9606.ENSP00000384957', 'cpi_9606.ENSP00000308032', 'cpi_9606.ENSP00000245457', 'cpi_9606.ENSP00000364805'], ['cpi_9606.ENSP00000324806', 'cpi_9606.ENSP00000366416', 'cpi_9606.ENSP00000333534', 'cpi_9606.ENSP00000379339', 'cpi_9606.ENSP00000265723'], ['cpi_9606.ENSP00000354532', 'cpi_9606.ENSP00000273430', 'cpi_9606.ENSP00000252321', 'cpi_9606.ENSP0000032

🔄 Processing features: 100%|██████████| 1607/1607 [06:51<00:00,  3.91feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'cpi_9606.ENSP00000354569', 'cpi_9606.ENSP00000253004', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000285381'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000261937', 'cpi_9606.ENSP00000430684', 'cpi_9606.ENSP00000322617'], ['cpi_9606.ENSP00000367959', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000267101', 'cpi_9606.ENSP00000355629', 'cpi_9606.ENSP00000427514'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000360773', 'cpi_9606.ENSP00000248076', 'cpi_9606.ENSP00000295452'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000315011', 'cpi_9606.ENSP00000367848', 'cpi_9606.ENSP00000216037', 'cpi_9606.ENSP00000372547'], ['cpi_9606.ENSP00000360372', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000257290', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000356094'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000414334', 'cpi_9606.ENSP00000459962', 'cpi_9606.ENSP00000254066'], ['cpi_9606.ENSP00000311032', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000359353', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000395653'], ['cpi_9606.ENSP00000265724', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000299178', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000381097'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000374323', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000312664'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000244217', 'cpi_9606.ENSP00000389338', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000385026'], ['cpi_9606.ENSP00000258400', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000347942'], ['cpi_9606.ENSP00000258743', 'cpi_9606.ENSP00000279387', 'cpi_9606.ENSP00000261799', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000337335'], ['cpi_9606.ENSP00000356438', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000394936', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000351957'], ['cpi_9606.ENSP00000337450', 'cpi_9606.ENSP00000245457', 'cpi_9606.ENSP00000362649', 'cpi_9606.ENSP00000342235', 'cpi_9606.ENSP00000342850'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000301891', 'cpi_9606.ENSP00000364802', 'cpi_9606.ENSP00000274547'], ['cpi_9606.ENSP00000354612', 'cpi_9606.ENSP00000277010', 'cpi_9606.ENSP00000292303', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000283254'], ['cpi_9606.ENSP00000270349', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000319788', 'cpi_9606.ENSP00000326119'], ['cpi_9606.ENSP00000272190', 'cpi_9606.ENSP00000354476', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000000442'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000366416', 'cpi_9606.ENSP00000299267', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000344352'], ['cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000367102', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000275525'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000467676', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000332296'], ['cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000259089', 'cpi_9606.ENSP00000377947'], ['cpi_9606.ENSP00000337949', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000352900'], ['cpi_9606.ENSP00000369960', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000302111', 'cpi_9606.ENSP00000343040', 'cpi_9606.ENSP00000308774'], ['cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000279178', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000283635', 'cpi_9606.ENSP00000348069'], ['cpi_9606.ENSP00000260433', 'cpi_9606.ENSP00000266376', 'cpi_9606.ENSP00000353427', 'cpi_9606.ENSP00000336630', 'cpi_9606.ENSP00000471569'], ['cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000293288', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000258749', 'cpi_9606.ENSP00000410732'], ['cpi_9606.ENSP00000354859', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000301178'], ['cpi_9606.ENSP00000269305', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000389414', 'cpi_9606.ENSP00000387946', 'cpi_9606.ENSP00000369375'], ['cpi_9606.ENSP00000297494', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000263321', 'cpi_9606.ENSP00000264637'], ['cpi_9606.ENSP00000215832', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000359532'], ['cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000304845', 'cpi_9606.ENSP00000296871', 'cpi_9606.ENSP00000355778', 'cpi_9606.ENSP00000331912'], ['cpi_9606.ENSP00000270202', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000359793', 'cpi_9606.ENSP00000261196'], ['cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000286301', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000295454'], ['cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000366084', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000417229'], ['cpi_9606.ENSP00000358963', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000320935', 'cpi_9606.ENSP00000353878'], ['cpi_9606.ENSP00000305372', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000357283', 'cpi_9606.ENSP00000262461', 'cpi_9606.ENSP00000333212'], ['cpi_9606.ENSP00000366506', 'cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000307599', 'cpi_9606.ENSP00000251535', 'cpi_9606.ENSP00000308165'], ['cpi_9606.ENSP00000316244', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000297350', 'cpi_9606.ENSP00000226574'], ['cpi_9606.ENSP00000219070', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000470087', 'cpi_9606.ENSP00000338072'], ['cpi_9606.ENSP00000305742', 'cpi_9606.ENSP00000361666', 'cpi_9606.ENSP00000231454', 'cpi_9606.ENSP00000428340', 'cpi_9606.ENSP00000262999'], ['cpi_9606.ENSP00000264381', 'cpi_9606.ENSP00000376943', 'cpi_9606.ENSP00000261693', 'cpi_9606.ENSP00000252809', 'cpi_9606.ENSP00000320025'], ['cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000363822', 'cpi_9606.ENSP00000370381', 'cpi_9606.ENSP00000410294', 'cpi_9606.ENSP00000428864'], ['cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000256958', 'cpi_9606.ENSP00000378517'], ['cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000237612', 'cpi_9606.ENSP00000357981', 'cpi_9606.ENSP00000367851', 'cpi_9606.ENSP00000274793'], ['cpi_9606.ENSP00000345096', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000294728', 'cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000312455'], ['cpi_9606.ENSP00000398698', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000220616', 'cpi_9606.ENSP00000242057', 'cpi_9606.ENSP00000447149'], ['cpi_9606.ENSP00000231509', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000410076', 'cpi_9606.ENSP00000307014', 'cpi_9606.ENSP00000451040'], ['cpi_9606.ENSP00000313661', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000323568', 'cpi_9606.ENSP00000267119', 'cpi_9606.ENSP00000304822'], ['cpi_9606.ENSP00000414303', 'cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000282561', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000296350'], ['cpi_9606.ENSP00000263025', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000307445', 'cpi_9606.ENSP00000361359', 'cpi_9606.ENSP00000301634'], ['cpi_9606.ENSP00000280155', 'cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000344192'], ['cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000225474', 'cpi_9606.ENSP00000382659', 'cpi_9606.ENSP00000221972'], ['cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000302665', 'cpi_9606.ENSP00000358548', 'cpi_9606.ENSP00000445340', 'cpi_9606.ENSP00000358223'], ['cpi_9606.ENSP00000276198', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000200676'], ['cpi_9606.ENSP00000330237', 'cpi_9606.ENSP00000374467', 'cpi_9606.ENSP00000327652', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000398632'], ['cpi_9606.ENSP00000287820', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000332369', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000343477'], ['cpi_9606.ENSP00000252945', 'cpi_9606.ENSP00000353915', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000263126', 'cpi_9606.ENSP00000259271'], ['cpi_9606.ENSP00000368766', 'cpi_9606.ENSP00000329623', 'cpi_9606.ENSP00000234389', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000363812'], ['cpi_9606.ENSP00000306512', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000259396', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000300061'], ['cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000248553', 'cpi_9606.ENSP00000262888', 'cpi_9606.ENSP00000309124'], ['cpi_9606.ENSP00000412237', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000263923', 'cpi_9606.ENSP00000364310'], ['cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000303830', 'cpi_9606.ENSP00000267843'], ['cpi_9606.ENSP00000295897', 'cpi_9606.ENSP00000353292', 'cpi_9606.ENSP00000457706', 'cpi_9606.ENSP00000295589', 'cpi_9606.ENSP00000463999'], ['cpi_9606.ENSP00000337459', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000216962', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000360493'], ['cpi_9606.ENSP00000308541', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000356954'], ['cpi_9606.ENSP00000378323', 'cpi_9606.ENSP00000252723', 'cpi_9606.ENSP00000387281', 'cpi_9606.ENSP00000358784', 'cpi_9606.ENSP00000222390'], ['cpi_9606.ENSP00000331746', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000233242', 'cpi_9606.ENSP00000362036', 'cpi_9606.ENSP00000276449'], ['cpi_9606.ENSP00000355759', 'cpi_9606.ENSP00000394033', 'cpi_9606.ENSP00000234371', 'cpi_9606.ENSP00000252486', 'cpi_9606.ENSP00000270474'], ['cpi_9606.ENSP00000321584', 'cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000306662', 'cpi_9606.ENSP00000366307', 'cpi_9606.ENSP00000358595'], ['cpi_9606.ENSP00000306245', 'cpi_9606.ENSP00000260649', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000347979', 'cpi_9606.ENSP00000316786'], ['cpi_9606.ENSP00000290866', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000290349', 'cpi_9606.ENSP00000222330'], ['cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000289753', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000260010'], ['cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000263980', 'cpi_9606.ENSP00000260630', 'cpi_9606.ENSP00000231228', 'cpi_9606.ENSP00000348827'], ['cpi_9606.ENSP00000263341', 'cpi_9606.ENSP00000296122', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000339527', 'cpi_9606.ENSP00000351209'], ['cpi_9606.ENSP00000302150', 'cpi_9606.ENSP00000256383', 'cpi_9606.ENSP00000311095', 'cpi_9606.ENSP00000263377', 'cpi_9606.ENSP00000292513'], ['cpi_9606.ENSP00000262623', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000386069', 'cpi_9606.ENSP00000285930'], ['cpi_9606.ENSP00000234310', 'cpi_9606.ENSP00000264657', 'cpi_9606.ENSP00000255465', 'cpi_9606.ENSP00000287907', 'cpi_9606.ENSP00000416293'], ['cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000312029', 'cpi_9606.ENSP00000419782', 'cpi_9606.ENSP00000337773'], ['cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000318822', 'cpi_9606.ENSP00000365380', 'cpi_9606.ENSP00000295834'], ['cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000241261', 'cpi_9606.ENSP00000428924', 'cpi_9606.ENSP00000225927', 'cpi_9606.ENSP00000262367'], ['cpi_9606.ENSP00000340684', 'cpi_9606.ENSP00000231449', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000388648', 'cpi_9606.ENSP00000305221'], ['cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000294954', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000310928', 'cpi_9606.ENSP00000372023'], ['cpi_9606.ENSP00000306129', 'cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000252029', 'cpi_9606.ENSP00000330393', 'cpi_9606.ENSP00000295491'], ['cpi_9606.ENSP00000176183', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000225964', 'cpi_9606.ENSP00000326219'], ['cpi_9606.ENSP00000464149', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000373169', 'cpi_9606.ENSP00000297268'], ['cpi_9606.ENSP00000358327', 'cpi_9606.ENSP00000296522', 'cpi_9606.ENSP00000317379', 'cpi_9606.ENSP00000221515', 'cpi_9606.ENSP00000360973'], ['cpi_9606.ENSP00000363868', 'cpi_9606.ENSP00000303522', 'cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000385806', 'cpi_9606.ENSP00000343782'], ['cpi_9606.ENSP00000394624', 'cpi_9606.ENSP00000301633', 'cpi_9606.ENSP00000351885', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000253727'], ['cpi_9606.ENSP00000307786', 'cpi_9606.ENSP00000226413', 'cpi_9606.ENSP00000260356', 'cpi_9606.ENSP00000393312', 'cpi_9606.ENSP00000339260'], ['cpi_9606.ENSP00000216117', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000302846', 'cpi_9606.ENSP00000362513', 'cpi_9606.ENSP00000252321'], ['cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000307766', 'cpi_9606.ENSP00000219700', 'cpi_9606.ENSP00000176763', 'cpi_9606.ENSP00000329357'], ['cpi_9606.ENSP00000264498', 'cpi_9606.ENSP00000320709', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000307235', 'cpi_9606.ENSP00000230671'], ['cpi_9606.ENSP00000218548', 'cpi_9606.ENSP00000360266', 'cpi_9606.ENSP00000254488', 'cpi_9606.ENSP00000365016', 'cpi_9606.ENSP00000217426'], ['cpi_9606.ENSP00000225831', 'cpi_9606.ENSP00000349576', 'cpi_9606.ENSP00000322924', 'cpi_9606.ENSP00000354394', 'cpi_9606.ENSP00000338548'], ['cpi_9606.ENSP00000327251', 'cpi_9606.ENSP00000353791', 'cpi_9606.ENSP00000216392', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000370473'], ['cpi_9606.ENSP00000223095', 'cpi_9606.ENSP00000362924', 'cpi_9606.ENSP00000448059', 'cpi_9606.ENSP00000239938', 'cpi_9606.ENSP00000360967'], ['cpi_9606.ENSP00000265572', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000282397', 'cpi_9606.ENSP00000232219', 'cpi_9606.ENSP00000376178'], ['cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000354107', 'cpi_9606.ENSP00000303424', 'cpi_9606.ENSP00000365663', 'cpi_9606.ENSP00000251566'], ['cpi_9606.ENSP00000357669', 'cpi_9606.ENSP00000262735', 'cpi_9606.ENSP00000343204', 'cpi_9606.ENSP00000358730', 'cpi_9606.ENSP00000233146'], ['cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000400175', 'cpi_9606.ENSP00000266682', 'cpi_9606.ENSP00000304915', 'cpi_9606.ENSP00000346598'], ['cpi_9606.ENSP00000361405', 'cpi_9606.ENSP00000355325', 'cpi_9606.ENSP00000433290', 'cpi_9606.ENSP00000287936', 'cpi_9606.ENSP00000277120'], ['cpi_9606.ENSP00000317842', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000211287', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000222002'], ['cpi_9606.ENSP00000411532', 'cpi_9606.ENSP00000355930', 'cpi_9606.ENSP00000264867', 'cpi_9606.ENSP00000355657', 'cpi_9606.ENSP00000260970'], ['cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000292896', 'cpi_9606.ENSP00000398655', 'cpi_9606.ENSP00000273430', 'cpi_9606.ENSP00000370254'], ['cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000212015', 'cpi_9606.ENSP00000359635', 'cpi_9606.ENSP00000370912', 'cpi_9606.ENSP00000303174'], ['cpi_9606.ENSP00000387662', 'cpi_9606.ENSP00000362508', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000278616', 'cpi_9606.ENSP00000270776'], ['cpi_9606.ENSP00000369050', 'cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000356150', 'cpi_9606.ENSP00000219919', 'cpi_9606.ENSP00000305302'], ['cpi_9606.ENSP00000358022', 'cpi_9606.ENSP00000309757', 'cpi_9606.ENSP00000285979', 'cpi_9606.ENSP00000362401', 'cpi_9606.ENSP00000379339'], ['cpi_9606.ENSP00000368683', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000341045', 'cpi_9606.ENSP00000349577', 'cpi_9606.ENSP00000262948'], ['cpi_9606.ENSP00000355627', 'cpi_9606.ENSP00000384273', 'cpi_9606.ENSP00000340820', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000466799'], ['cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000275300', 'cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000368752', 'cpi_9606.ENSP00000419692'], ['cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000354558', 'cpi_9606.ENSP00000282018', 'cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000321988'], ['cpi_9606.ENSP00000356825', 'cpi_9606.ENSP00000228872', 'cpi_9606.ENSP00000308549', 'cpi_9606.ENSP00000433821', 'cpi_9606.ENSP00000242375'], ['cpi_9606.ENSP00000266970', 'cpi_9606.ENSP00000331358', 'cpi_9606.ENSP00000288602', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000330199'], ['cpi_9606.ENSP00000368727', 'cpi_9606.ENSP00000358511', 'cpi_9606.ENSP00000264896', 'cpi_9606.ENSP00000311469', 'cpi_9606.ENSP00000268035'], ['cpi_9606.ENSP00000301141', 'cpi_9606.ENSP00000321106', 'cpi_9606.ENSP00000311028', 'cpi_9606.ENSP00000352584', 'cpi_9606.ENSP00000270570'], ['cpi_9606.ENSP00000359478', 'cpi_9606.ENSP00000375066', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000391676', 'cpi_9606.ENSP00000346298'], ['cpi_9606.ENSP00000275493', 'cpi_9606.ENSP00000335544', 'cpi_9606.ENSP00000341885', 'cpi_9606.ENSP00000239849', 'cpi_9606.ENSP00000164139'], ['cpi_9606.ENSP00000331514', 'cpi_9606.ENSP00000380252', 'cpi_9606.ENSP00000218721', 'cpi_9606.ENSP00000318646', 'cpi_9606.ENSP00000321821'], ['cpi_9606.ENSP00000370571', 'cpi_9606.ENSP00000351908', 'cpi_9606.ENSP00000352035', 'cpi_9606.ENSP00000291294', 'cpi_9606.ENSP00000368880'], ['cpi_9606.ENSP00000338018', 'cpi_9606.ENSP00000399168', 'cpi_9606.ENSP00000356832', 'cpi_9606.ENSP00000234961', 'cpi_9606.ENSP00000211122'], ['cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000298171', 'cpi_9606.ENSP00000338627', 'cpi_9606.ENSP00000244741', 'cpi_9606.ENSP00000355533'], ['cpi_9606.ENSP00000225275', 'cpi_9606.ENSP00000379213', 'cpi_9606.ENSP00000420168', 'cpi_9606.ENSP00000356671', 'cpi_9606.ENSP00000369654'], ['cpi_9606.ENSP00000382342', 'cpi_9606.ENSP00000355317', 'cpi_9606.ENSP00000454071', 'cpi_9606.ENSP00000296674', 'cpi_9606.ENSP00000350767'], ['cpi_9606.ENSP00000318585', 'cpi_9606.ENSP00000387699', 'cpi_9606.ENSP00000309103', 'cpi_9606.ENSP00000309493', 'cpi_9606.ENSP00000268053'], ['cpi_9606.ENSP00000229135', 'cpi_9606.ENSP00000276414', 'cpi_9606.ENSP00000274026', 'cpi_9606.ENSP00000252804', 'cpi_9606.ENSP00000332816'], ['cpi_9606.ENSP00000239223', 'cpi_9606.ENSP00000287641', 'cpi_9606.ENSP00000427562', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000349252'], ['cpi_9606.ENSP00000354511', 'cpi_9606.ENSP00000264832', 'cpi_9606.ENSP00000320866', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000378699'], ['cpi_9606.ENSP00000299855', 'cpi_9606.ENSP00000393333', 'cpi_9606.ENSP00000288135', 'cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000301146'], ['cpi_9606.ENSP00000265023', 'cpi_9606.ENSP00000262160', 'cpi_9606.ENSP00000331736', 'cpi_9606.ENSP00000251453', 'cpi_9606.ENSP00000280357'], ['cpi_9606.ENSP00000358107', 'cpi_9606.ENSP00000307259', 'cpi_9606.ENSP00000304895', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000356694'], ['cpi_9606.ENSP00000324806', 'cpi_9606.ENSP00000303452', 'cpi_9606.ENSP00000308032', 'cpi_9606.ENSP00000364805', 'cpi_9606.ENSP00000338082'], ['cpi_9606.ENSP00000261405', 'cpi_9606.ENSP00000360968', 'cpi_9606.ENSP00000435777', 'cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000386171'], ['cpi_9606.ENSP00000397026', 'cpi_9606.ENSP00000360247', 'cpi_9606.ENSP00000303686', 'cpi_9606.ENSP00000218388', 'cpi_9606.ENSP00000344674'], ['cpi_9606.ENSP00000315644', 'cpi_9606.ENSP00000312652', 'cpi_9606.ENSP00000275216', 'cpi_9606.ENSP00000265403', 'cpi_9606.ENSP00000430432'], ['cpi_9606.ENSP00000313490', 'cpi_9606.ENSP00000386884', 'cpi_9606.ENSP00000276431', 'cpi_9606.ENSP00000296545', 'cpi_9606.ENSP00000236850'], ['cpi_9606.ENSP00000349467', 'cpi_9606.ENSP00000341189', 'cpi_9606.ENSP00000381333', 'cpi_9606.ENSP00000359998', 'cpi_9606.ENSP00000354610'], ['cpi_9606.ENSP00000248437', 'cpi_9606.ENSP00000367309', 'cpi_9606.ENSP00000387683', 'cpi_9606.ENSP00000225371', 'cpi_9606.ENSP00000309818'], ['cpi_9606.ENSP00000353483', 'cpi_9606.ENSP00000319814', 'cpi_9606.ENSP00000324248', 'cpi_9606.ENSP0000027

🔄 Processing features: 100%|██████████| 1607/1607 [06:51<00:00,  3.91feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'cpi_9606.ENSP00000326219', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000356094', 'cpi_9606.ENSP00000365686'], ['cpi_9606.ENSP00000360372', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000261937', 'cpi_9606.ENSP00000430684', 'cpi_9606.ENSP00000352900'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000360773', 'cpi_9606.ENSP00000355629', 'cpi_9606.ENSP00000295452'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000367848', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000377947'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000347942', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000299178'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000359353', 'cpi_9606.ENSP00000286479'], ['cpi_9606.ENSP00000367959', 'cpi_9606.ENSP00000337335', 'cpi_9606.ENSP00000302111', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000257290'], ['cpi_9606.ENSP00000311032', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000353362'], ['cpi_9606.ENSP00000258743', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000261799', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000220616'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000367102', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000312304'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000311165', 'cpi_9606.ENSP00000374323', 'cpi_9606.ENSP00000312664', 'cpi_9606.ENSP00000372547'], ['cpi_9606.ENSP00000265724', 'cpi_9606.ENSP00000304822', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000332296'], ['cpi_9606.ENSP00000270349', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000301891', 'cpi_9606.ENSP00000241453'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000244217', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000279178', 'cpi_9606.ENSP00000389338'], ['cpi_9606.ENSP00000354612', 'cpi_9606.ENSP00000277010', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000378517'], ['cpi_9606.ENSP00000337450', 'cpi_9606.ENSP00000302846', 'cpi_9606.ENSP00000362649', 'cpi_9606.ENSP00000286301', 'cpi_9606.ENSP00000395653'], ['cpi_9606.ENSP00000356438', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000394936', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000381097'], ['cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000354476', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000447149'], ['cpi_9606.ENSP00000272190', 'cpi_9606.ENSP00000216037', 'cpi_9606.ENSP00000457706', 'cpi_9606.ENSP00000295454', 'cpi_9606.ENSP00000319788'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000299267', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000298472'], ['cpi_9606.ENSP00000269305', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000242057', 'cpi_9606.ENSP00000376178'], ['cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000342235', 'cpi_9606.ENSP00000410732'], ['cpi_9606.ENSP00000258400', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000267101', 'cpi_9606.ENSP00000283635', 'cpi_9606.ENSP00000417229'], ['cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000378323', 'cpi_9606.ENSP00000361666', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000274547'], ['cpi_9606.ENSP00000337949', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000301178', 'cpi_9606.ENSP00000357283'], ['cpi_9606.ENSP00000369960', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000414334', 'cpi_9606.ENSP00000259089'], ['cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000273550', 'cpi_9606.ENSP00000356954', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000264637'], ['cpi_9606.ENSP00000264381', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000326119', 'cpi_9606.ENSP00000266376', 'cpi_9606.ENSP00000258749'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000467676', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000408860'], ['cpi_9606.ENSP00000363822', 'cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000307599', 'cpi_9606.ENSP00000367851'], ['cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000366506', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000361359', 'cpi_9606.ENSP00000275525'], ['cpi_9606.ENSP00000260433', 'cpi_9606.ENSP00000353427', 'cpi_9606.ENSP00000348069', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000382659'], ['cpi_9606.ENSP00000398698', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000387946', 'cpi_9606.ENSP00000470087', 'cpi_9606.ENSP00000216962'], ['cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000333212', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000221972', 'cpi_9606.ENSP00000359334'], ['cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000304845', 'cpi_9606.ENSP00000344192', 'cpi_9606.ENSP00000428924', 'cpi_9606.ENSP00000331912'], ['cpi_9606.ENSP00000270202', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000471569', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000263321'], ['cpi_9606.ENSP00000354859', 'cpi_9606.ENSP00000290866', 'cpi_9606.ENSP00000344352', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000411593'], ['cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000261196', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000308165', 'cpi_9606.ENSP00000176183'], ['cpi_9606.ENSP00000276198', 'cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000346598', 'cpi_9606.ENSP00000363812'], ['cpi_9606.ENSP00000297494', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000225474', 'cpi_9606.ENSP00000332816'], ['cpi_9606.ENSP00000313661', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000320935', 'cpi_9606.ENSP00000353878'], ['cpi_9606.ENSP00000306512', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000259396', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000300061'], ['cpi_9606.ENSP00000231509', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000251535', 'cpi_9606.ENSP00000343040', 'cpi_9606.ENSP00000445340'], ['cpi_9606.ENSP00000345096', 'cpi_9606.ENSP00000293288', 'cpi_9606.ENSP00000231454', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000451040'], ['cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000256958', 'cpi_9606.ENSP00000255465', 'cpi_9606.ENSP00000295491'], ['cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000294728', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000260010'], ['cpi_9606.ENSP00000252945', 'cpi_9606.ENSP00000353915', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000310928', 'cpi_9606.ENSP00000274793'], ['cpi_9606.ENSP00000358963', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000370381', 'cpi_9606.ENSP00000226574'], ['cpi_9606.ENSP00000305372', 'cpi_9606.ENSP00000303174', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000376943', 'cpi_9606.ENSP00000352584'], ['cpi_9606.ENSP00000215832', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000389414', 'cpi_9606.ENSP00000222330'], ['cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000267119', 'cpi_9606.ENSP00000312455', 'cpi_9606.ENSP00000262888'], ['cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000294954', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000263126', 'cpi_9606.ENSP00000366307'], ['cpi_9606.ENSP00000237612', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000362036', 'cpi_9606.ENSP00000282561', 'cpi_9606.ENSP00000296122'], ['cpi_9606.ENSP00000316244', 'cpi_9606.ENSP00000223095', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000252723'], ['cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000366084', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000332369'], ['cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000261693', 'cpi_9606.ENSP00000296871', 'cpi_9606.ENSP00000448059'], ['cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000464149', 'cpi_9606.ENSP00000252809', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000398632'], ['cpi_9606.ENSP00000280155', 'cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000311095'], ['cpi_9606.ENSP00000387281', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000360493', 'cpi_9606.ENSP00000356436'], ['cpi_9606.ENSP00000263025', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000353292', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000372750'], ['cpi_9606.ENSP00000234310', 'cpi_9606.ENSP00000329623', 'cpi_9606.ENSP00000386069', 'cpi_9606.ENSP00000297350', 'cpi_9606.ENSP00000309124'], ['cpi_9606.ENSP00000414303', 'cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000358548', 'cpi_9606.ENSP00000331358'], ['cpi_9606.ENSP00000295897', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000248553', 'cpi_9606.ENSP00000391676', 'cpi_9606.ENSP00000343477'], ['cpi_9606.ENSP00000330237', 'cpi_9606.ENSP00000374467', 'cpi_9606.ENSP00000327652', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000351885'], ['cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000428340', 'cpi_9606.ENSP00000306129', 'cpi_9606.ENSP00000233242', 'cpi_9606.ENSP00000416293'], ['cpi_9606.ENSP00000287820', 'cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000398655', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000365663'], ['cpi_9606.ENSP00000263341', 'cpi_9606.ENSP00000399168', 'cpi_9606.ENSP00000372023', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000368766'], ['cpi_9606.ENSP00000289753', 'cpi_9606.ENSP00000320709', 'cpi_9606.ENSP00000211122', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000262461'], ['cpi_9606.ENSP00000355759', 'cpi_9606.ENSP00000305221', 'cpi_9606.ENSP00000248076', 'cpi_9606.ENSP00000311028', 'cpi_9606.ENSP00000260356'], ['cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000358107', 'cpi_9606.ENSP00000278616', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000345708'], ['cpi_9606.ENSP00000305742', 'cpi_9606.ENSP00000454071', 'cpi_9606.ENSP00000318822', 'cpi_9606.ENSP00000306662', 'cpi_9606.ENSP00000307014'], ['cpi_9606.ENSP00000331746', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000354394', 'cpi_9606.ENSP00000330393'], ['cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000262948', 'cpi_9606.ENSP00000362401'], ['cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000263980', 'cpi_9606.ENSP00000252486', 'cpi_9606.ENSP00000373169', 'cpi_9606.ENSP00000365775'], ['cpi_9606.ENSP00000306245', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000262367', 'cpi_9606.ENSP00000308774', 'cpi_9606.ENSP00000239849'], ['cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000312029', 'cpi_9606.ENSP00000466799', 'cpi_9606.ENSP00000200676'], ['cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000303522', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000351209', 'cpi_9606.ENSP00000357255'], ['cpi_9606.ENSP00000308541', 'cpi_9606.ENSP00000316786', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000463999', 'cpi_9606.ENSP00000211287'], ['cpi_9606.ENSP00000219070', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000353791', 'cpi_9606.ENSP00000164139', 'cpi_9606.ENSP00000365380'], ['cpi_9606.ENSP00000412237', 'cpi_9606.ENSP00000254488', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000263923', 'cpi_9606.ENSP00000364310'], ['cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000400175', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000307235', 'cpi_9606.ENSP00000307766'], ['cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000368683', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000355657', 'cpi_9606.ENSP00000349577'], ['cpi_9606.ENSP00000327251', 'cpi_9606.ENSP00000358784', 'cpi_9606.ENSP00000410294', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000304915'], ['cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000275300', 'cpi_9606.ENSP00000303452', 'cpi_9606.ENSP00000287936', 'cpi_9606.ENSP00000256383'], ['cpi_9606.ENSP00000321584', 'cpi_9606.ENSP00000264657', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000360967', 'cpi_9606.ENSP00000287907'], ['cpi_9606.ENSP00000302150', 'cpi_9606.ENSP00000246337', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000329357', 'cpi_9606.ENSP00000292513'], ['cpi_9606.ENSP00000363868', 'cpi_9606.ENSP00000322924', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000339527', 'cpi_9606.ENSP00000370473'], ['cpi_9606.ENSP00000262623', 'cpi_9606.ENSP00000384273', 'cpi_9606.ENSP00000277120', 'cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000270776'], ['cpi_9606.ENSP00000358327', 'cpi_9606.ENSP00000296522', 'cpi_9606.ENSP00000317379', 'cpi_9606.ENSP00000267843', 'cpi_9606.ENSP00000427514'], ['cpi_9606.ENSP00000218548', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000337773', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000218388'], ['cpi_9606.ENSP00000361405', 'cpi_9606.ENSP00000355325', 'cpi_9606.ENSP00000282397', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000338072'], ['cpi_9606.ENSP00000337459', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000393312', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000362525'], ['cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000241261', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000290349', 'cpi_9606.ENSP00000256119'], ['cpi_9606.ENSP00000266970', 'cpi_9606.ENSP00000231228', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000320401', 'cpi_9606.ENSP00000344674'], ['cpi_9606.ENSP00000369050', 'cpi_9606.ENSP00000307445', 'cpi_9606.ENSP00000263464', 'cpi_9606.ENSP00000310447', 'cpi_9606.ENSP00000410076'], ['cpi_9606.ENSP00000387662', 'cpi_9606.ENSP00000362508', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000378699', 'cpi_9606.ENSP00000433821'], ['cpi_9606.ENSP00000265572', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000221515', 'cpi_9606.ENSP00000388648', 'cpi_9606.ENSP00000308845'], ['cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000355317', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000295834', 'cpi_9606.ENSP00000268251'], ['cpi_9606.ENSP00000340684', 'cpi_9606.ENSP00000231449', 'cpi_9606.ENSP00000333496', 'cpi_9606.ENSP00000387683', 'cpi_9606.ENSP00000351908'], ['cpi_9606.ENSP00000358022', 'cpi_9606.ENSP00000309757', 'cpi_9606.ENSP00000285979', 'cpi_9606.ENSP00000303424', 'cpi_9606.ENSP00000297268'], ['cpi_9606.ENSP00000368349', 'cpi_9606.ENSP00000276449', 'cpi_9606.ENSP00000275216', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000360266'], ['cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000354107', 'cpi_9606.ENSP00000336630', 'cpi_9606.ENSP00000364802', 'cpi_9606.ENSP00000222390'], ['cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000288135', 'cpi_9606.ENSP00000252029', 'cpi_9606.ENSP00000335657', 'cpi_9606.ENSP00000266682'], ['cpi_9606.ENSP00000331514', 'cpi_9606.ENSP00000244741', 'cpi_9606.ENSP00000359793', 'cpi_9606.ENSP00000333534', 'cpi_9606.ENSP00000270625'], ['cpi_9606.ENSP00000216117', 'cpi_9606.ENSP00000282018', 'cpi_9606.ENSP00000318646', 'cpi_9606.ENSP00000362513', 'cpi_9606.ENSP00000347979'], ['cpi_9606.ENSP00000411532', 'cpi_9606.ENSP00000355930', 'cpi_9606.ENSP00000264867', 'cpi_9606.ENSP00000219919', 'cpi_9606.ENSP00000429374'], ['cpi_9606.ENSP00000307786', 'cpi_9606.ENSP00000291294', 'cpi_9606.ENSP00000176763', 'cpi_9606.ENSP00000365016', 'cpi_9606.ENSP00000217426'], ['cpi_9606.ENSP00000225831', 'cpi_9606.ENSP00000349576', 'cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000338548', 'cpi_9606.ENSP00000323568'], ['cpi_9606.ENSP00000264498', 'cpi_9606.ENSP00000354193', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000309103'], ['cpi_9606.ENSP00000324806', 'cpi_9606.ENSP00000366416', 'cpi_9606.ENSP00000301146', 'cpi_9606.ENSP00000341885', 'cpi_9606.ENSP00000305302'], ['cpi_9606.ENSP00000356825', 'cpi_9606.ENSP00000301633', 'cpi_9606.ENSP00000308549', 'cpi_9606.ENSP00000368104', 'cpi_9606.ENSP00000296545'], ['cpi_9606.ENSP00000357669', 'cpi_9606.ENSP00000354558', 'cpi_9606.ENSP00000346298', 'cpi_9606.ENSP00000354569', 'cpi_9606.ENSP00000341045'], ['cpi_9606.ENSP00000301141', 'cpi_9606.ENSP00000314949', 'cpi_9606.ENSP00000321106', 'cpi_9606.ENSP00000225964', 'cpi_9606.ENSP00000232219'], ['cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000212015', 'cpi_9606.ENSP00000355778', 'cpi_9606.ENSP00000359635', 'cpi_9606.ENSP00000251566'], ['cpi_9606.ENSP00000225275', 'cpi_9606.ENSP00000379213', 'cpi_9606.ENSP00000311469', 'cpi_9606.ENSP00000385806', 'cpi_9606.ENSP00000330199'], ['cpi_9606.ENSP00000354511', 'cpi_9606.ENSP00000380252', 'cpi_9606.ENSP00000216392', 'cpi_9606.ENSP00000233146', 'cpi_9606.ENSP00000309493'], ['cpi_9606.ENSP00000275493', 'cpi_9606.ENSP00000358730', 'cpi_9606.ENSP00000387888', 'cpi_9606.ENSP00000251453', 'cpi_9606.ENSP00000338627'], ['cpi_9606.ENSP00000355627', 'cpi_9606.ENSP00000369757', 'cpi_9606.ENSP00000368752', 'cpi_9606.ENSP00000253727', 'cpi_9606.ENSP00000367309'], ['cpi_9606.ENSP00000332549', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000459962', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000342560'], ['cpi_9606.ENSP00000308032', 'cpi_9606.ENSP00000245457', 'cpi_9606.ENSP00000368880', 'cpi_9606.ENSP00000364805', 'cpi_9606.ENSP00000350767'], ['cpi_9606.ENSP00000394624', 'cpi_9606.ENSP00000262160', 'cpi_9606.ENSP00000356150', 'cpi_9606.ENSP00000386171', 'cpi_9606.ENSP00000363827'], ['cpi_9606.ENSP00000317842', 'cpi_9606.ENSP00000274026', 'cpi_9606.ENSP00000379140', 'cpi_9606.ENSP00000265403', 'cpi_9606.ENSP00000270474'], ['cpi_9606.ENSP00000369647', 'cpi_9606.ENSP00000335620', 'cpi_9606.ENSP00000356671', 'cpi_9606.ENSP00000321821', 'cpi_9606.ENSP00000419692'], ['cpi_9606.ENSP00000285379', 'cpi_9606.ENSP00000386884', 'cpi_9606.ENSP00000264896', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000349252'], ['cpi_9606.ENSP00000234961', 'cpi_9606.ENSP00000348645', 'cpi_9606.ENSP00000418960', 'cpi_9606.ENSP00000312652', 'cpi_9606.ENSP00000357981'], ['cpi_9606.ENSP00000292303', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000363804', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000340820'], ['cpi_9606.ENSP00000370571', 'cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000343204', 'cpi_9606.ENSP00000264832'], ['cpi_9606.ENSP00000299855', 'cpi_9606.ENSP00000393333', 'cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000252321', 'cpi_9606.ENSP00000260970'], ['cpi_9606.ENSP00000397026', 'cpi_9606.ENSP00000239938', 'cpi_9606.ENSP00000356694', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000309968'], ['cpi_9606.ENSP00000364709', 'cpi_9606.ENSP00000338018', 'cpi_9606.ENSP00000335544', 'cpi_9606.ENSP00000435777', 'cpi_9606.ENSP00000242375'], ['cpi_9606.ENSP00000279593', 'cpi_9606.ENSP00000262735', 'cpi_9606.ENSP00000374265', 'cpi_9606.ENSP00000267377', 'cpi_9606.ENSP00000359100'], ['cpi_9606.ENSP00000349467', 'cpi_9606.ENSP00000341189', 'cpi_9606.ENSP00000381333', 'cpi_9606.ENSP00000420168', 'cpi_9606.ENSP00000225927'], ['cpi_9606.ENSP00000302665', 'cpi_9606.ENSP00000427562', 'cpi_9606.ENSP00000307259', 'cpi_9606.ENSP00000359998', 'cpi_9606.ENSP00000265723'], ['cpi_9606.ENSP00000367207', 'cpi_9606.ENSP00000338082', 'cpi_9606.ENSP00000295589', 'cpi_9606.ENSP00000225371', 'cpi_9606.ENSP00000368632'], ['cpi_9606.ENSP00000371067', 'cpi_9606.ENSP00000358511', 'cpi_9606.ENSP00000370373', 'cpi_9606.ENSP00000268053', 'cpi_9606.ENSP00000215659'], ['cpi_9606.ENSP00000295453', 'cpi_9606.ENSP00000433290', 'cpi_9606.ENSP00000333685', 'cpi_9606.ENSP00000304895', 'cpi_9606.ENSP00000252804'], ['cpi_9606.ENSP00000359478', 'cpi_9606.ENSP00000375066', 'cpi_9606.ENSP00000219700', 'cpi_9606.ENSP00000379339', 'cpi_9606.ENSP00000346901'], ['cpi_9606.ENSP00000229135', 'cpi_9606.ENSP00000328173', 'cpi_9606.ENSP00000321988', 'cpi_9606.ENSP00000332679', 'cpi_9606.ENSP00000276431'], ['cpi_9606.ENSP00000302961', 'cpi_9606.ENSP00000324270', 'cpi_9606.ENSP00000305355', 'cpi_9606.ENSP00000355533', 'cpi_9606.ENSP00000259271'], ['cpi_9606.ENSP00000216714', 'cpi_9606.ENSP00000287641', 'cpi_9606.ENSP00000236850', 'cpi_9606.ENSP00000356729', 'cpi_9606.ENSP00000196551'], ['cpi_9606.ENSP00000272298', 'cpi_9606.ENSP00000331736', 'cpi_9606.ENSP00000362353', 'cpi_9606.ENSP0000024

🔄 Processing features: 100%|██████████| 1607/1607 [06:51<00:00,  3.91feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'cpi_9606.ENSP00000357669', 'cpi_9606.ENSP00000414334', 'cpi_9606.ENSP00000356094', 'cpi_9606.ENSP00000402152'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000464149', 'cpi_9606.ENSP00000263126', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000385026'], ['cpi_9606.ENSP00000360372', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000261937', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000372547'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000261799', 'cpi_9606.ENSP00000430684', 'cpi_9606.ENSP00000295454'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000360773', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000355629'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000370381', 'cpi_9606.ENSP00000274547'], ['cpi_9606.ENSP00000367959', 'cpi_9606.ENSP00000337335', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000286301'], ['cpi_9606.ENSP00000311032', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000376432'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000292513', 'cpi_9606.ENSP00000395653', 'cpi_9606.ENSP00000342235'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000367102', 'cpi_9606.ENSP00000257290', 'cpi_9606.ENSP00000370373'], ['cpi_9606.ENSP00000265724', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000299178', 'cpi_9606.ENSP00000263321'], ['cpi_9606.ENSP00000337450', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000302846', 'cpi_9606.ENSP00000374323', 'cpi_9606.ENSP00000297268'], ['cpi_9606.ENSP00000272190', 'cpi_9606.ENSP00000354476', 'cpi_9606.ENSP00000417229', 'cpi_9606.ENSP00000457706', 'cpi_9606.ENSP00000410732'], ['cpi_9606.ENSP00000258743', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000357615', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000277010'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000367848', 'cpi_9606.ENSP00000332296', 'cpi_9606.ENSP00000283635'], ['cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000344192', 'cpi_9606.ENSP00000359353', 'cpi_9606.ENSP00000298472'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000312664', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000351209'], ['cpi_9606.ENSP00000270349', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000267101', 'cpi_9606.ENSP00000301891', 'cpi_9606.ENSP00000288139'], ['cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000361666', 'cpi_9606.ENSP00000295452'], ['cpi_9606.ENSP00000356438', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000266376', 'cpi_9606.ENSP00000394936', 'cpi_9606.ENSP00000288602'], ['cpi_9606.ENSP00000369960', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000302111', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000299267'], ['cpi_9606.ENSP00000260433', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000347942', 'cpi_9606.ENSP00000386306'], ['cpi_9606.ENSP00000258400', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000221972'], ['cpi_9606.ENSP00000264381', 'cpi_9606.ENSP00000279178', 'cpi_9606.ENSP00000259396', 'cpi_9606.ENSP00000216037', 'cpi_9606.ENSP00000343477'], ['cpi_9606.ENSP00000354612', 'cpi_9606.ENSP00000348069', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000267843', 'cpi_9606.ENSP00000363812'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000467676', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000270776'], ['cpi_9606.ENSP00000398698', 'cpi_9606.ENSP00000471569', 'cpi_9606.ENSP00000357336', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000285381'], ['cpi_9606.ENSP00000363822', 'cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000242057', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000334198'], ['cpi_9606.ENSP00000215832', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000387946', 'cpi_9606.ENSP00000353791'], ['cpi_9606.ENSP00000270202', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000331912', 'cpi_9606.ENSP00000319788', 'cpi_9606.ENSP00000262888'], ['cpi_9606.ENSP00000269305', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000389414', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000245539'], ['cpi_9606.ENSP00000297494', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000340691'], ['cpi_9606.ENSP00000354859', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000344352', 'cpi_9606.ENSP00000241453'], ['cpi_9606.ENSP00000366506', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000320935', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000381097'], ['cpi_9606.ENSP00000263025', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000216962', 'cpi_9606.ENSP00000261693'], ['cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000349252', 'cpi_9606.ENSP00000301178', 'cpi_9606.ENSP00000389338'], ['cpi_9606.ENSP00000378323', 'cpi_9606.ENSP00000294728', 'cpi_9606.ENSP00000304822', 'cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000296350'], ['cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000394033', 'cpi_9606.ENSP00000448059', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000231454'], ['cpi_9606.ENSP00000276198', 'cpi_9606.ENSP00000293288', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000256958', 'cpi_9606.ENSP00000295491'], ['cpi_9606.ENSP00000305372', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000241261', 'cpi_9606.ENSP00000390600'], ['cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000333534', 'cpi_9606.ENSP00000289753', 'cpi_9606.ENSP00000347979'], ['cpi_9606.ENSP00000337949', 'cpi_9606.ENSP00000358107', 'cpi_9606.ENSP00000262461', 'cpi_9606.ENSP00000372023', 'cpi_9606.ENSP00000367851'], ['cpi_9606.ENSP00000316244', 'cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000357283', 'cpi_9606.ENSP00000233146', 'cpi_9606.ENSP00000261196'], ['cpi_9606.ENSP00000313661', 'cpi_9606.ENSP00000304845', 'cpi_9606.ENSP00000266682', 'cpi_9606.ENSP00000200676', 'cpi_9606.ENSP00000252029'], ['cpi_9606.ENSP00000358963', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000427562', 'cpi_9606.ENSP00000343040', 'cpi_9606.ENSP00000304408'], ['cpi_9606.ENSP00000237612', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000362036', 'cpi_9606.ENSP00000361359', 'cpi_9606.ENSP00000303522'], ['cpi_9606.ENSP00000414303', 'cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000451040', 'cpi_9606.ENSP00000376943'], ['cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000226574', 'cpi_9606.ENSP00000297350'], ['cpi_9606.ENSP00000280155', 'cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000309124'], ['cpi_9606.ENSP00000223095', 'cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000251535', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000285930'], ['cpi_9606.ENSP00000219070', 'cpi_9606.ENSP00000340684', 'cpi_9606.ENSP00000264637', 'cpi_9606.ENSP00000305302', 'cpi_9606.ENSP00000292427'], ['cpi_9606.ENSP00000306512', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000362649', 'cpi_9606.ENSP00000326119', 'cpi_9606.ENSP00000368253'], ['cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000252945', 'cpi_9606.ENSP00000260356', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000274793'], ['cpi_9606.ENSP00000287820', 'cpi_9606.ENSP00000332369', 'cpi_9606.ENSP00000378699', 'cpi_9606.ENSP00000353292', 'cpi_9606.ENSP00000258749'], ['cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000305221', 'cpi_9606.ENSP00000296871', 'cpi_9606.ENSP00000275525', 'cpi_9606.ENSP00000307240'], ['cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000368766', 'cpi_9606.ENSP00000303174', 'cpi_9606.ENSP00000445340', 'cpi_9606.ENSP00000293745'], ['cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000470087', 'cpi_9606.ENSP00000221421'], ['cpi_9606.ENSP00000231509', 'cpi_9606.ENSP00000176763', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000351885', 'cpi_9606.ENSP00000355657'], ['cpi_9606.ENSP00000290866', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000312455', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000311469'], ['cpi_9606.ENSP00000386069', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000454071', 'cpi_9606.ENSP00000290349'], ['cpi_9606.ENSP00000355759', 'cpi_9606.ENSP00000374467', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000359635'], ['cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000231449', 'cpi_9606.ENSP00000428340', 'cpi_9606.ENSP00000463999', 'cpi_9606.ENSP00000337773'], ['cpi_9606.ENSP00000302150', 'cpi_9606.ENSP00000356954', 'cpi_9606.ENSP00000300738', 'cpi_9606.ENSP00000259089', 'cpi_9606.ENSP00000225474'], ['cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000300061'], ['cpi_9606.ENSP00000330237', 'cpi_9606.ENSP00000364709', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000307599'], ['cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000308165', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000402608'], ['cpi_9606.ENSP00000387281', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000219919', 'cpi_9606.ENSP00000360493'], ['cpi_9606.ENSP00000331746', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000320401', 'cpi_9606.ENSP00000388648', 'cpi_9606.ENSP00000262367'], ['cpi_9606.ENSP00000295897', 'cpi_9606.ENSP00000378517', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000365775'], ['cpi_9606.ENSP00000306245', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000360967', 'cpi_9606.ENSP00000318822'], ['cpi_9606.ENSP00000234310', 'cpi_9606.ENSP00000329623', 'cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000333212'], ['cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000218548', 'cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000358548', 'cpi_9606.ENSP00000306662'], ['cpi_9606.ENSP00000305742', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000287936', 'cpi_9606.ENSP00000252723', 'cpi_9606.ENSP00000225964'], ['cpi_9606.ENSP00000279387', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000354394', 'cpi_9606.ENSP00000287907', 'cpi_9606.ENSP00000358784'], ['cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000252321', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000310447', 'cpi_9606.ENSP00000346298'], ['cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000267119', 'cpi_9606.ENSP00000295589'], ['cpi_9606.ENSP00000306129', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000254488', 'cpi_9606.ENSP00000398632', 'cpi_9606.ENSP00000307014'], ['cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000263923', 'cpi_9606.ENSP00000356694', 'cpi_9606.ENSP00000364802', 'cpi_9606.ENSP00000252809'], ['cpi_9606.ENSP00000394624', 'cpi_9606.ENSP00000301633', 'cpi_9606.ENSP00000310928', 'cpi_9606.ENSP00000330199', 'cpi_9606.ENSP00000242375'], ['cpi_9606.ENSP00000327251', 'cpi_9606.ENSP00000338627', 'cpi_9606.ENSP00000338548', 'cpi_9606.ENSP00000295400', 'cpi_9606.ENSP00000353915'], ['cpi_9606.ENSP00000363868', 'cpi_9606.ENSP00000352608', 'cpi_9606.ENSP00000339527', 'cpi_9606.ENSP00000327652', 'cpi_9606.ENSP00000316786'], ['cpi_9606.ENSP00000387662', 'cpi_9606.ENSP00000362508', 'cpi_9606.ENSP00000231790', 'cpi_9606.ENSP00000308774', 'cpi_9606.ENSP00000263980'], ['cpi_9606.ENSP00000262623', 'cpi_9606.ENSP00000239938', 'cpi_9606.ENSP00000282397', 'cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000260010'], ['cpi_9606.ENSP00000308541', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000264657'], ['cpi_9606.ENSP00000263341', 'cpi_9606.ENSP00000296122', 'cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000178638'], ['cpi_9606.ENSP00000354511', 'cpi_9606.ENSP00000278616', 'cpi_9606.ENSP00000282561', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000222330'], ['cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000366084', 'cpi_9606.ENSP00000312029', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000410294'], ['cpi_9606.ENSP00000412237', 'cpi_9606.ENSP00000327801', 'cpi_9606.ENSP00000220616', 'cpi_9606.ENSP00000410076', 'cpi_9606.ENSP00000362513'], ['cpi_9606.ENSP00000358022', 'cpi_9606.ENSP00000285979', 'cpi_9606.ENSP00000231228', 'cpi_9606.ENSP00000309757', 'cpi_9606.ENSP00000291700'], ['cpi_9606.ENSP00000370571', 'cpi_9606.ENSP00000441691', 'cpi_9606.ENSP00000221515', 'cpi_9606.ENSP00000248553', 'cpi_9606.ENSP00000340820'], ['cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000307766', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000323568', 'cpi_9606.ENSP00000341390'], ['cpi_9606.ENSP00000337459', 'cpi_9606.ENSP00000352035', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000354107'], ['cpi_9606.ENSP00000320709', 'cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000264498', 'cpi_9606.ENSP00000353878'], ['cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000294954', 'cpi_9606.ENSP00000420168', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000371929'], ['cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000314649', 'cpi_9606.ENSP00000255465', 'cpi_9606.ENSP00000384273', 'cpi_9606.ENSP00000332816'], ['cpi_9606.ENSP00000358327', 'cpi_9606.ENSP00000295598', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000307235', 'cpi_9606.ENSP00000248041'], ['cpi_9606.ENSP00000370129', 'cpi_9606.ENSP00000322924', 'cpi_9606.ENSP00000329357', 'cpi_9606.ENSP00000314508', 'cpi_9606.ENSP00000274026'], ['cpi_9606.ENSP00000265572', 'cpi_9606.ENSP00000262160', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000380252', 'cpi_9606.ENSP00000368104'], ['cpi_9606.ENSP00000266970', 'cpi_9606.ENSP00000331358', 'cpi_9606.ENSP00000371554', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000369816'], ['cpi_9606.ENSP00000411532', 'cpi_9606.ENSP00000233242', 'cpi_9606.ENSP00000291294', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000343204'], ['cpi_9606.ENSP00000361405', 'cpi_9606.ENSP00000355325', 'cpi_9606.ENSP00000352584', 'cpi_9606.ENSP00000176183', 'cpi_9606.ENSP00000341045'], ['cpi_9606.ENSP00000338018', 'cpi_9606.ENSP00000399168', 'cpi_9606.ENSP00000346598', 'cpi_9606.ENSP00000276449', 'cpi_9606.ENSP00000373169'], ['cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000369050', 'cpi_9606.ENSP00000356150', 'cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000366307'], ['cpi_9606.ENSP00000239223', 'cpi_9606.ENSP00000365663', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000336630', 'cpi_9606.ENSP00000263377'], ['cpi_9606.ENSP00000274606', 'cpi_9606.ENSP00000301141', 'cpi_9606.ENSP00000321106', 'cpi_9606.ENSP00000252486', 'cpi_9606.ENSP00000393312'], ['cpi_9606.ENSP00000216117', 'cpi_9606.ENSP00000248076', 'cpi_9606.ENSP00000311028', 'cpi_9606.ENSP00000251566', 'cpi_9606.ENSP00000353427'], ['cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000288135', 'cpi_9606.ENSP00000311165', 'cpi_9606.ENSP00000234961', 'cpi_9606.ENSP00000260191'], ['cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000400175', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000304915', 'cpi_9606.ENSP00000428924'], ['cpi_9606.ENSP00000368349', 'cpi_9606.ENSP00000308032', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000427514', 'cpi_9606.ENSP00000385806'], ['cpi_9606.ENSP00000368683', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000292896', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000355920'], ['cpi_9606.ENSP00000371067', 'cpi_9606.ENSP00000358511', 'cpi_9606.ENSP00000308938', 'cpi_9606.ENSP00000295834', 'cpi_9606.ENSP00000368752'], ['cpi_9606.ENSP00000317842', 'cpi_9606.ENSP00000297469', 'cpi_9606.ENSP00000262948', 'cpi_9606.ENSP00000368632', 'cpi_9606.ENSP00000331736'], ['cpi_9606.ENSP00000244217', 'cpi_9606.ENSP00000360968', 'cpi_9606.ENSP00000244741', 'cpi_9606.ENSP00000359793', 'cpi_9606.ENSP00000260970'], ['cpi_9606.ENSP00000260302', 'cpi_9606.ENSP00000367309', 'cpi_9606.ENSP00000215659', 'cpi_9606.ENSP00000239849', 'cpi_9606.ENSP00000359998'], ['cpi_9606.ENSP00000355627', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000362344', 'cpi_9606.ENSP00000211122', 'cpi_9606.ENSP00000318820'], ['cpi_9606.ENSP00000279593', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000382659', 'cpi_9606.ENSP00000211287', 'cpi_9606.ENSP00000295453'], ['cpi_9606.ENSP00000225831', 'cpi_9606.ENSP00000349576', 'cpi_9606.ENSP00000358730', 'cpi_9606.ENSP00000365233', 'cpi_9606.ENSP00000387683'], ['cpi_9606.ENSP00000261405', 'cpi_9606.ENSP00000354558', 'cpi_9606.ENSP00000265403', 'cpi_9606.ENSP00000223366', 'cpi_9606.ENSP00000307445'], ['cpi_9606.ENSP00000225275', 'cpi_9606.ENSP00000379213', 'cpi_9606.ENSP00000349577', 'cpi_9606.ENSP00000369654', 'cpi_9606.ENSP00000360991'], ['cpi_9606.ENSP00000314949', 'cpi_9606.ENSP00000301146', 'cpi_9606.ENSP00000303452', 'cpi_9606.ENSP00000317379', 'cpi_9606.ENSP00000264867'], ['cpi_9606.ENSP00000359478', 'cpi_9606.ENSP00000287641', 'cpi_9606.ENSP00000302886', 'cpi_9606.ENSP00000330393', 'cpi_9606.ENSP00000459962'], ['cpi_9606.ENSP00000397026', 'cpi_9606.ENSP00000419692', 'cpi_9606.ENSP00000321821', 'cpi_9606.ENSP00000362401', 'cpi_9606.ENSP00000435412'], ['cpi_9606.ENSP00000331514', 'cpi_9606.ENSP00000311095', 'cpi_9606.ENSP00000355778', 'cpi_9606.ENSP00000355533', 'cpi_9606.ENSP00000268053'], ['cpi_9606.ENSP00000332549', 'cpi_9606.ENSP00000334246', 'cpi_9606.ENSP00000354569', 'cpi_9606.ENSP00000275300', 'cpi_9606.ENSP00000280357'], ['cpi_9606.ENSP00000363965', 'cpi_9606.ENSP00000234371', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000360266', 'cpi_9606.ENSP00000298283'], ['cpi_9606.ENSP00000269571', 'cpi_9606.ENSP00000433290', 'cpi_9606.ENSP00000386284', 'cpi_9606.ENSP00000264896', 'cpi_9606.ENSP00000360247'], ['cpi_9606.ENSP00000369647', 'cpi_9606.ENSP00000335620', 'cpi_9606.ENSP00000356671', 'cpi_9606.ENSP00000387888', 'cpi_9606.ENSP00000256383'], ['cpi_9606.ENSP00000264832', 'cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000300151', 'cpi_9606.ENSP00000355930', 'cpi_9606.ENSP00000356825'], ['cpi_9606.ENSP00000275493', 'cpi_9606.ENSP00000245206', 'cpi_9606.ENSP00000254976', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000355317'], ['cpi_9606.ENSP00000272298', 'cpi_9606.ENSP00000341189', 'cpi_9606.ENSP00000381333', 'cpi_9606.ENSP00000356729', 'cpi_9606.ENSP00000428864'], ['cpi_9606.ENSP00000265023', 'cpi_9606.ENSP00000232219', 'cpi_9606.ENSP00000384957', 'cpi_9606.ENSP00000369757', 'cpi_9606.ENSP00000270474'], ['cpi_9606.ENSP00000292303', 'cpi_9606.ENSP00000250378', 'cpi_9606.ENSP00000365016', 'cpi_9606.ENSP00000276431', 'cpi_9606.ENSP00000332679'], ['cpi_9606.ENSP00000334145', 'cpi_9606.ENSP00000321988', 'cpi_9606.ENSP00000282018', 'cpi_9606.ENSP00000260630', 'cpi_9606.ENSP00000301634'], ['cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000407375', 'cpi_9606.ENSP00000322421', 'cpi_9606.ENSP00000309103', 'cpi_9606.ENSP00000277120'], ['cpi_9606.ENSP00000229135', 'cpi_9606.ENSP00000338082', 'cpi_9606.ENSP00000346901', 'cpi_9606.ENSP00000324270', 'cpi_9606.ENSP00000252804'], ['cpi_9606.ENSP00000264426', 'cpi_9606.ENSP00000242152', 'cpi_9606.ENSP00000228872', 'cpi_9606.ENSP00000261465', 'cpi_9606.ENSP00000318912'], ['cpi_9606.ENSP00000354532', 'cpi_9606.ENSP00000304895', 'cpi_9606.ENSP00000326159', 'cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000386171'], ['cpi_9606.ENSP00000382342', 'cpi_9606.ENSP00000277508', 'cpi_9606.ENSP00000303424', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000357981'], ['cpi_9606.ENSP00000349467', 'cpi_9606.ENSP00000245457', 'cpi_9606.ENSP00000263464', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000327431'], ['cpi_9606.ENSP00000324806', 'cpi_9606.ENSP00000366416', 'cpi_9606.ENSP00000466799', 'cpi_9606.ENSP00000333496', 'cpi_9606.ENSP00000345774'], ['cpi_9606.ENSP00000299855', 'cpi_9606.ENSP00000365380', 'cpi_9606.ENSP00000348645', 'cpi_9606.ENSP0000036

🔄 Processing features: 100%|██████████| 1607/1607 [06:52<00:00,  3.90feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000395653', 'cpi_9606.ENSP00000225927'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000234310', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000355629', 'cpi_9606.ENSP00000342850'], ['cpi_9606.ENSP00000360372', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000261937'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000430684', 'cpi_9606.ENSP00000257290', 'cpi_9606.ENSP00000361151'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000360773', 'cpi_9606.ENSP00000279387', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000265294'], ['cpi_9606.ENSP00000311032', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000359353', 'cpi_9606.ENSP00000356094'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000345096', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000355317', 'cpi_9606.ENSP00000299847'], ['cpi_9606.ENSP00000367959', 'cpi_9606.ENSP00000337335', 'cpi_9606.ENSP00000273550', 'cpi_9606.ENSP00000286301', 'cpi_9606.ENSP00000261196'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000367102', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000216962'], ['cpi_9606.ENSP00000337450', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000263321', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000374323'], ['cpi_9606.ENSP00000265724', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000299178', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000367848'], ['cpi_9606.ENSP00000258743', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000261799', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000394936'], ['cpi_9606.ENSP00000272190', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000354476', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000241453'], ['cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000305372', 'cpi_9606.ENSP00000283635', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000359424'], ['cpi_9606.ENSP00000270349', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000267101', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000301891'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000244217', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000317379', 'cpi_9606.ENSP00000352900'], ['cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000356671'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000216392', 'cpi_9606.ENSP00000332816', 'cpi_9606.ENSP00000262888'], ['cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000389414', 'cpi_9606.ENSP00000367608'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000467676', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000277010'], ['cpi_9606.ENSP00000258400', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000302111', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000417229'], ['cpi_9606.ENSP00000269305', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000266376', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000226444'], ['cpi_9606.ENSP00000398698', 'cpi_9606.ENSP00000394033', 'cpi_9606.ENSP00000220616', 'cpi_9606.ENSP00000342235', 'cpi_9606.ENSP00000377947'], ['cpi_9606.ENSP00000369960', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000293288', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000356436'], ['cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000329623', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000256958', 'cpi_9606.ENSP00000258749'], ['cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000363822', 'cpi_9606.ENSP00000397026', 'cpi_9606.ENSP00000414334', 'cpi_9606.ENSP00000242057'], ['cpi_9606.ENSP00000356438', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000332296', 'cpi_9606.ENSP00000381097', 'cpi_9606.ENSP00000322617'], ['cpi_9606.ENSP00000260433', 'cpi_9606.ENSP00000354193', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000261693', 'cpi_9606.ENSP00000319788'], ['cpi_9606.ENSP00000215832', 'cpi_9606.ENSP00000274547', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000309649'], ['cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000366506', 'cpi_9606.ENSP00000219700', 'cpi_9606.ENSP00000471569'], ['cpi_9606.ENSP00000354612', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000301178', 'cpi_9606.ENSP00000349577'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000312673', 'cpi_9606.ENSP00000355920', 'cpi_9606.ENSP00000399168', 'cpi_9606.ENSP00000348897'], ['cpi_9606.ENSP00000358963', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000344352', 'cpi_9606.ENSP00000292427'], ['cpi_9606.ENSP00000270202', 'cpi_9606.ENSP00000262623', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000295834', 'cpi_9606.ENSP00000307014'], ['cpi_9606.ENSP00000297494', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000259089', 'cpi_9606.ENSP00000359096'], ['cpi_9606.ENSP00000264381', 'cpi_9606.ENSP00000279178', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000347942'], ['cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000216037', 'cpi_9606.ENSP00000387281', 'cpi_9606.ENSP00000454071'], ['cpi_9606.ENSP00000252945', 'cpi_9606.ENSP00000378323', 'cpi_9606.ENSP00000262160', 'cpi_9606.ENSP00000263126', 'cpi_9606.ENSP00000353915'], ['cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000223095', 'cpi_9606.ENSP00000251535', 'cpi_9606.ENSP00000295454', 'cpi_9606.ENSP00000304915'], ['cpi_9606.ENSP00000321584', 'cpi_9606.ENSP00000414303', 'cpi_9606.ENSP00000428340', 'cpi_9606.ENSP00000311095', 'cpi_9606.ENSP00000320866'], ['cpi_9606.ENSP00000386069', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000344192', 'cpi_9606.ENSP00000410294'], ['cpi_9606.ENSP00000305742', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000225474', 'cpi_9606.ENSP00000398632', 'cpi_9606.ENSP00000316244'], ['cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000358107', 'cpi_9606.ENSP00000278616', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000333212'], ['cpi_9606.ENSP00000280155', 'cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000357669', 'cpi_9606.ENSP00000252809', 'cpi_9606.ENSP00000463999'], ['cpi_9606.ENSP00000263025', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000274793'], ['cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000353292', 'cpi_9606.ENSP00000220003'], ['cpi_9606.ENSP00000276198', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000384273', 'cpi_9606.ENSP00000367851', 'cpi_9606.ENSP00000419782'], ['cpi_9606.ENSP00000231509', 'cpi_9606.ENSP00000355533', 'cpi_9606.ENSP00000382659', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000357283'], ['cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000260649'], ['cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000232219', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000358595'], ['cpi_9606.ENSP00000366084', 'cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000308165', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000412673'], ['cpi_9606.ENSP00000337949', 'cpi_9606.ENSP00000374467', 'cpi_9606.ENSP00000301633', 'cpi_9606.ENSP00000275525', 'cpi_9606.ENSP00000221972'], ['cpi_9606.ENSP00000306245', 'cpi_9606.ENSP00000303830', 'cpi_9606.ENSP00000361666', 'cpi_9606.ENSP00000312664', 'cpi_9606.ENSP00000270776'], ['cpi_9606.ENSP00000330237', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000328173', 'cpi_9606.ENSP00000387946', 'cpi_9606.ENSP00000451040'], ['cpi_9606.ENSP00000368766', 'cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000307599', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000164139'], ['cpi_9606.ENSP00000313661', 'cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000360493', 'cpi_9606.ENSP00000353224'], ['cpi_9606.ENSP00000302150', 'cpi_9606.ENSP00000356954', 'cpi_9606.ENSP00000398655', 'cpi_9606.ENSP00000348786', 'cpi_9606.ENSP00000385026'], ['cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000434516', 'cpi_9606.ENSP00000267119', 'cpi_9606.ENSP00000308774'], ['cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000337103', 'cpi_9606.ENSP00000376943', 'cpi_9606.ENSP00000309757', 'cpi_9606.ENSP00000331912'], ['cpi_9606.ENSP00000306512', 'cpi_9606.ENSP00000370381', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000346148', 'cpi_9606.ENSP00000264637'], ['cpi_9606.ENSP00000218548', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000361359', 'cpi_9606.ENSP00000378517', 'cpi_9606.ENSP00000372750'], ['cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000331746', 'cpi_9606.ENSP00000320709', 'cpi_9606.ENSP00000388648', 'cpi_9606.ENSP00000297991'], ['cpi_9606.ENSP00000306662', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000340820', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000321988'], ['cpi_9606.ENSP00000308541', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000248572', 'cpi_9606.ENSP00000311165', 'cpi_9606.ENSP00000327652'], ['cpi_9606.ENSP00000289753', 'cpi_9606.ENSP00000304845', 'cpi_9606.ENSP00000319814', 'cpi_9606.ENSP00000304822', 'cpi_9606.ENSP00000375809'], ['cpi_9606.ENSP00000464149', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000312455', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000345502'], ['cpi_9606.ENSP00000295897', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000248553', 'cpi_9606.ENSP00000343204', 'cpi_9606.ENSP00000448059'], ['cpi_9606.ENSP00000290866', 'cpi_9606.ENSP00000228872', 'cpi_9606.ENSP00000302811', 'cpi_9606.ENSP00000259396', 'cpi_9606.ENSP00000296412'], ['cpi_9606.ENSP00000355759', 'cpi_9606.ENSP00000318585', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000282561', 'cpi_9606.ENSP00000306129'], ['cpi_9606.ENSP00000354859', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000351209', 'cpi_9606.ENSP00000389338', 'cpi_9606.ENSP00000274545'], ['cpi_9606.ENSP00000219070', 'cpi_9606.ENSP00000340684', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000435591'], ['cpi_9606.ENSP00000263341', 'cpi_9606.ENSP00000296122', 'cpi_9606.ENSP00000252029', 'cpi_9606.ENSP00000264818', 'cpi_9606.ENSP00000333496'], ['cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000231454', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000470087', 'cpi_9606.ENSP00000299267'], ['cpi_9606.ENSP00000411532', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000393333', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000359100'], ['cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000248076', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000310447'], ['cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000270474', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000378699'], ['cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000252486', 'cpi_9606.ENSP00000365663', 'cpi_9606.ENSP00000363812'], ['cpi_9606.ENSP00000237612', 'cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000231228', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000343040'], ['cpi_9606.ENSP00000307766', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000222330', 'cpi_9606.ENSP00000263980', 'cpi_9606.ENSP00000311028'], ['cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000359478', 'cpi_9606.ENSP00000369757', 'cpi_9606.ENSP00000225964', 'cpi_9606.ENSP00000300061'], ['cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000466799', 'cpi_9606.ENSP00000358784', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000457706'], ['cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000310928', 'cpi_9606.ENSP00000286091', 'cpi_9606.ENSP00000358548', 'cpi_9606.ENSP00000393312'], ['cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000294954', 'cpi_9606.ENSP00000233242', 'cpi_9606.ENSP00000355778', 'cpi_9606.ENSP00000338548'], ['cpi_9606.ENSP00000412237', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000294728', 'cpi_9606.ENSP00000362344'], ['cpi_9606.ENSP00000394624', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000200676', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000362924'], ['cpi_9606.ENSP00000358327', 'cpi_9606.ENSP00000296522', 'cpi_9606.ENSP00000371554', 'cpi_9606.ENSP00000248041', 'cpi_9606.ENSP00000337825'], ['cpi_9606.ENSP00000337459', 'cpi_9606.ENSP00000384957', 'cpi_9606.ENSP00000219919', 'cpi_9606.ENSP00000327850', 'cpi_9606.ENSP00000326119'], ['cpi_9606.ENSP00000266970', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000303522'], ['cpi_9606.ENSP00000361405', 'cpi_9606.ENSP00000314508', 'cpi_9606.ENSP00000409612', 'cpi_9606.ENSP00000355930', 'cpi_9606.ENSP00000370912'], ['cpi_9606.ENSP00000358022', 'cpi_9606.ENSP00000365016', 'cpi_9606.ENSP00000358730', 'cpi_9606.ENSP00000377192', 'cpi_9606.ENSP00000295731'], ['cpi_9606.ENSP00000176183', 'cpi_9606.ENSP00000303174', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000356694', 'cpi_9606.ENSP00000297268'], ['cpi_9606.ENSP00000225831', 'cpi_9606.ENSP00000301634', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000276449', 'cpi_9606.ENSP00000447149'], ['cpi_9606.ENSP00000369050', 'cpi_9606.ENSP00000261405', 'cpi_9606.ENSP00000354610', 'cpi_9606.ENSP00000354394', 'cpi_9606.ENSP00000242375'], ['cpi_9606.ENSP00000327251', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000275300', 'cpi_9606.ENSP00000176763'], ['cpi_9606.ENSP00000307786', 'cpi_9606.ENSP00000353472', 'cpi_9606.ENSP00000291294', 'cpi_9606.ENSP00000341045', 'cpi_9606.ENSP00000309124'], ['cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000348069', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000265403', 'cpi_9606.ENSP00000336630'], ['cpi_9606.ENSP00000322924', 'cpi_9606.ENSP00000317842', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000262948', 'cpi_9606.ENSP00000358424'], ['cpi_9606.ENSP00000373169', 'cpi_9606.ENSP00000276431', 'cpi_9606.ENSP00000263923', 'cpi_9606.ENSP00000295491', 'cpi_9606.ENSP00000260010'], ['cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000226574', 'cpi_9606.ENSP00000365012', 'cpi_9606.ENSP00000347046', 'cpi_9606.ENSP00000366307'], ['cpi_9606.ENSP00000216117', 'cpi_9606.ENSP00000282018', 'cpi_9606.ENSP00000362036', 'cpi_9606.ENSP00000343477', 'cpi_9606.ENSP00000337354'], ['cpi_9606.ENSP00000331514', 'cpi_9606.ENSP00000244741', 'cpi_9606.ENSP00000349467', 'cpi_9606.ENSP00000306606', 'cpi_9606.ENSP00000359793'], ['cpi_9606.ENSP00000371067', 'cpi_9606.ENSP00000264498', 'cpi_9606.ENSP00000236850', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000402152'], ['cpi_9606.ENSP00000387662', 'cpi_9606.ENSP00000305221', 'cpi_9606.ENSP00000332116', 'cpi_9606.ENSP00000318822', 'cpi_9606.ENSP00000428924'], ['cpi_9606.ENSP00000338018', 'cpi_9606.ENSP00000305692', 'cpi_9606.ENSP00000297258', 'cpi_9606.ENSP00000316786', 'cpi_9606.ENSP00000287907'], ['cpi_9606.ENSP00000368683', 'cpi_9606.ENSP00000364782', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000307235', 'cpi_9606.ENSP00000254079'], ['cpi_9606.ENSP00000354511', 'cpi_9606.ENSP00000296871', 'cpi_9606.ENSP00000355657', 'cpi_9606.ENSP00000386171', 'cpi_9606.ENSP00000262187'], ['cpi_9606.ENSP00000260970', 'cpi_9606.ENSP00000287936', 'cpi_9606.ENSP00000308549', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000262461'], ['cpi_9606.ENSP00000252321', 'cpi_9606.ENSP00000245457', 'cpi_9606.ENSP00000320935', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000309103'], ['cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000367309', 'cpi_9606.ENSP00000252723', 'cpi_9606.ENSP00000352608', 'cpi_9606.ENSP00000353427'], ['cpi_9606.ENSP00000287820', 'cpi_9606.ENSP00000332369', 'cpi_9606.ENSP00000364805', 'cpi_9606.ENSP00000267843', 'cpi_9606.ENSP00000255409'], ['cpi_9606.ENSP00000367207', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000335544', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000256383'], ['cpi_9606.ENSP00000370571', 'cpi_9606.ENSP00000239223', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000333821'], ['cpi_9606.ENSP00000264832', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000352584', 'cpi_9606.ENSP00000267377'], ['cpi_9606.ENSP00000363868', 'cpi_9606.ENSP00000302846', 'cpi_9606.ENSP00000339527', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000341885'], ['cpi_9606.ENSP00000314949', 'cpi_9606.ENSP00000301141', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000451605', 'cpi_9606.ENSP00000357066'], ['cpi_9606.ENSP00000274606', 'cpi_9606.ENSP00000264657', 'cpi_9606.ENSP00000285979', 'cpi_9606.ENSP00000303452', 'cpi_9606.ENSP00000305355'], ['cpi_9606.ENSP00000368349', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000362353', 'cpi_9606.ENSP00000385806', 'cpi_9606.ENSP00000263088'], ['cpi_9606.ENSP00000292303', 'cpi_9606.ENSP00000368727', 'cpi_9606.ENSP00000304408', 'cpi_9606.ENSP00000329357', 'cpi_9606.ENSP00000354107'], ['cpi_9606.ENSP00000234961', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000264867', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000253004'], ['cpi_9606.ENSP00000225275', 'cpi_9606.ENSP00000237527', 'cpi_9606.ENSP00000304895', 'cpi_9606.ENSP00000272227', 'cpi_9606.ENSP00000311469'], ['cpi_9606.ENSP00000356825', 'cpi_9606.ENSP00000370473', 'cpi_9606.ENSP00000241261', 'cpi_9606.ENSP00000360973', 'cpi_9606.ENSP00000259486'], ['cpi_9606.ENSP00000260302', 'cpi_9606.ENSP00000331358', 'cpi_9606.ENSP00000288135', 'cpi_9606.ENSP00000225371', 'cpi_9606.ENSP00000273077'], ['cpi_9606.ENSP00000364709', 'cpi_9606.ENSP00000302665', 'cpi_9606.ENSP00000380252', 'cpi_9606.ENSP00000342560', 'cpi_9606.ENSP00000362513'], ['cpi_9606.ENSP00000313490', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000276571', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000333534'], ['cpi_9606.ENSP00000229135', 'cpi_9606.ENSP00000259271', 'cpi_9606.ENSP00000381333', 'cpi_9606.ENSP00000356150', 'cpi_9606.ENSP00000356729'], ['cpi_9606.ENSP00000355627', 'cpi_9606.ENSP00000253727', 'cpi_9606.ENSP00000330484', 'cpi_9606.ENSP00000364802', 'cpi_9606.ENSP00000354558'], ['cpi_9606.ENSP00000295598', 'cpi_9606.ENSP00000239938', 'cpi_9606.ENSP00000348645', 'cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000321821'], ['cpi_9606.ENSP00000307259', 'cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000236671', 'cpi_9606.ENSP00000359635', 'cpi_9606.ENSP00000302967'], ['cpi_9606.ENSP00000382342', 'cpi_9606.ENSP00000260227', 'cpi_9606.ENSP00000334105', 'cpi_9606.ENSP00000285900', 'cpi_9606.ENSP00000400175'], ['cpi_9606.ENSP00000358525', 'cpi_9606.ENSP00000262735', 'cpi_9606.ENSP00000272167', 'cpi_9606.ENSP00000225577', 'cpi_9606.ENSP00000402608'], ['cpi_9606.ENSP00000265572', 'cpi_9606.ENSP00000265723', 'cpi_9606.ENSP00000362649', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000371138'], ['cpi_9606.ENSP00000254488', 'cpi_9606.ENSP00000360266', 'cpi_9606.ENSP00000303424', 'cpi_9606.ENSP00000368104', 'cpi_9606.ENSP00000433821'], ['cpi_9606.ENSP00000334145', 'cpi_9606.ENSP00000321106', 'cpi_9606.ENSP00000013034', 'cpi_9606.ENSP00000326219', 'cpi_9606.ENSP00000332679'], ['cpi_9606.ENSP00000324806', 'cpi_9606.ENSP00000445340', 'cpi_9606.ENSP00000339001', 'cpi_9606.ENSP00000459962', 'cpi_9606.ENSP00000341189'], ['cpi_9606.ENSP00000231449', 'cpi_9606.ENSP00000264426', 'cpi_9606.ENSP00000216911', 'cpi_9606.ENSP00000337773', 'cpi_9606.ENSP00000226413'], ['cpi_9606.ENSP00000275493', 'cpi_9606.ENSP00000261205', 'cpi_9606.ENSP00000262367', 'cpi_9606.ENSP00000320401', 'cpi_9606.ENSP00000218388'], ['cpi_9606.ENSP00000269571', 'cpi_9606.ENSP00000369647', 'cpi_9606.ENSP00000370373', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000318646'], ['cpi_9606.ENSP00000308032', 'cpi_9606.ENSP00000256078', 'cpi_9606.ENSP00000292513', 'cpi_9606.ENSP00000435777', 'cpi_9606.ENSP00000306561'], ['cpi_9606.ENSP00000216714', 'cpi_9606.ENSP00000339191', 'cpi_9606.ENSP00000358511', 'cpi_9606.ENSP00000365233', 'cpi_9606.ENSP00000217961'], ['cpi_9606.ENSP00000353483', 'cpi_9606.ENSP00000217386', 'cpi_9606.ENSP00000340523', 'cpi_9606.ENSP00000252804', 'cpi_9606.ENSP00000282397'], ['cpi_9606.ENSP00000299855', 'cpi_9606.ENSP00000315011', 'cpi_9606.ENSP00000341828', 'cpi_9606.ENSP0000034

🔄 Processing features: 100%|██████████| 1607/1607 [06:50<00:00,  3.91feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'cpi_9606.ENSP00000356094', 'cpi_9606.ENSP00000367123', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000352900'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000355629', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000259089'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000261937', 'cpi_9606.ENSP00000430684', 'cpi_9606.ENSP00000218388'], ['cpi_9606.ENSP00000360372', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000257290', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000372547'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000360773', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000451040'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000357283', 'cpi_9606.ENSP00000359353'], ['cpi_9606.ENSP00000367959', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000267101', 'cpi_9606.ENSP00000329357', 'cpi_9606.ENSP00000328973'], ['cpi_9606.ENSP00000311032', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000367848', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000216862'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000245457', 'cpi_9606.ENSP00000389338', 'cpi_9606.ENSP00000374323', 'cpi_9606.ENSP00000225964'], ['cpi_9606.ENSP00000258743', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000261799', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000395653'], ['cpi_9606.ENSP00000265724', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000433290', 'cpi_9606.ENSP00000337335', 'cpi_9606.ENSP00000385026'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000343477', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000283254'], ['cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000320709', 'cpi_9606.ENSP00000295452'], ['cpi_9606.ENSP00000356438', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000394936', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000351957'], ['cpi_9606.ENSP00000337450', 'cpi_9606.ENSP00000244217', 'cpi_9606.ENSP00000342235', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000216037'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000367102', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000467676'], ['cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000312664', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000344192'], ['cpi_9606.ENSP00000272190', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000275525', 'cpi_9606.ENSP00000312455', 'cpi_9606.ENSP00000295454'], ['cpi_9606.ENSP00000258400', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000293288', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000358548'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000299267', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000394932'], ['cpi_9606.ENSP00000354612', 'cpi_9606.ENSP00000277010', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000348069', 'cpi_9606.ENSP00000339527'], ['cpi_9606.ENSP00000269305', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000242057', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000298472'], ['cpi_9606.ENSP00000270349', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000301891', 'cpi_9606.ENSP00000266376', 'cpi_9606.ENSP00000332296'], ['cpi_9606.ENSP00000215832', 'cpi_9606.ENSP00000354476', 'cpi_9606.ENSP00000274547', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000386306'], ['cpi_9606.ENSP00000354859', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000361359', 'cpi_9606.ENSP00000417229'], ['cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000319788', 'cpi_9606.ENSP00000221972', 'cpi_9606.ENSP00000221421'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000261196'], ['cpi_9606.ENSP00000260433', 'cpi_9606.ENSP00000414334', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000353427', 'cpi_9606.ENSP00000359334'], ['cpi_9606.ENSP00000270202', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000307599', 'cpi_9606.ENSP00000387946', 'cpi_9606.ENSP00000258749'], ['cpi_9606.ENSP00000316244', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000344352', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000000442'], ['cpi_9606.ENSP00000305372', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000283635', 'cpi_9606.ENSP00000274545'], ['cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000263321', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000279178', 'cpi_9606.ENSP00000381097'], ['cpi_9606.ENSP00000358963', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000351209', 'cpi_9606.ENSP00000343040'], ['cpi_9606.ENSP00000363822', 'cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000251535', 'cpi_9606.ENSP00000308774'], ['cpi_9606.ENSP00000263025', 'cpi_9606.ENSP00000471569', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000330393', 'cpi_9606.ENSP00000349577'], ['cpi_9606.ENSP00000276198', 'cpi_9606.ENSP00000345096', 'cpi_9606.ENSP00000347942', 'cpi_9606.ENSP00000320935', 'cpi_9606.ENSP00000334198'], ['cpi_9606.ENSP00000287820', 'cpi_9606.ENSP00000220003', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000222330', 'cpi_9606.ENSP00000457706'], ['cpi_9606.ENSP00000398698', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000267119'], ['cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000223095', 'cpi_9606.ENSP00000361666', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000317379'], ['cpi_9606.ENSP00000313661', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000326119', 'cpi_9606.ENSP00000411593'], ['cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000368766', 'cpi_9606.ENSP00000256958', 'cpi_9606.ENSP00000445340', 'cpi_9606.ENSP00000367851'], ['cpi_9606.ENSP00000297494', 'cpi_9606.ENSP00000353791', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000264637', 'cpi_9606.ENSP00000340691'], ['cpi_9606.ENSP00000369960', 'cpi_9606.ENSP00000329623', 'cpi_9606.ENSP00000358107', 'cpi_9606.ENSP00000353292', 'cpi_9606.ENSP00000331912'], ['cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000259396'], ['cpi_9606.ENSP00000306245', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000376943', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000360967'], ['cpi_9606.ENSP00000337949', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000428340', 'cpi_9606.ENSP00000221515', 'cpi_9606.ENSP00000435591'], ['cpi_9606.ENSP00000306512', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000362649', 'cpi_9606.ENSP00000263126', 'cpi_9606.ENSP00000286301'], ['cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000273550', 'cpi_9606.ENSP00000356954', 'cpi_9606.ENSP00000470087', 'cpi_9606.ENSP00000370381'], ['cpi_9606.ENSP00000237612', 'cpi_9606.ENSP00000254488', 'cpi_9606.ENSP00000382659', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000274793'], ['cpi_9606.ENSP00000414303', 'cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000410294'], ['cpi_9606.ENSP00000305742', 'cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000360493', 'cpi_9606.ENSP00000306662'], ['cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000321584', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000301178', 'cpi_9606.ENSP00000308165'], ['cpi_9606.ENSP00000264381', 'cpi_9606.ENSP00000261693', 'cpi_9606.ENSP00000378517', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000282397'], ['cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000176763', 'cpi_9606.ENSP00000323568', 'cpi_9606.ENSP00000252486'], ['cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000314949', 'cpi_9606.ENSP00000304822', 'cpi_9606.ENSP00000254227'], ['cpi_9606.ENSP00000387281', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000232219', 'cpi_9606.ENSP00000302967', 'cpi_9606.ENSP00000297350'], ['cpi_9606.ENSP00000280155', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000226574', 'cpi_9606.ENSP00000309493'], ['cpi_9606.ENSP00000386069', 'cpi_9606.ENSP00000302111', 'cpi_9606.ENSP00000370129', 'cpi_9606.ENSP00000233242', 'cpi_9606.ENSP00000295491'], ['cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000364805', 'cpi_9606.ENSP00000263923', 'cpi_9606.ENSP00000363812'], ['cpi_9606.ENSP00000308541', 'cpi_9606.ENSP00000252723', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000320025'], ['cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000400175', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000303522', 'cpi_9606.ENSP00000337773'], ['cpi_9606.ENSP00000279387', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000296871', 'cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000354394'], ['cpi_9606.ENSP00000330237', 'cpi_9606.ENSP00000374467', 'cpi_9606.ENSP00000365380', 'cpi_9606.ENSP00000309124', 'cpi_9606.ENSP00000220616'], ['cpi_9606.ENSP00000252945', 'cpi_9606.ENSP00000231454', 'cpi_9606.ENSP00000259271', 'cpi_9606.ENSP00000372023', 'cpi_9606.ENSP00000285381'], ['cpi_9606.ENSP00000378323', 'cpi_9606.ENSP00000294728', 'cpi_9606.ENSP00000267843', 'cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000376776'], ['cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000366084', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000262888', 'cpi_9606.ENSP00000332369'], ['cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000312029', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000307014', 'cpi_9606.ENSP00000358595'], ['cpi_9606.ENSP00000355759', 'cpi_9606.ENSP00000333212', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000365016', 'cpi_9606.ENSP00000343782'], ['cpi_9606.ENSP00000231509', 'cpi_9606.ENSP00000459962', 'cpi_9606.ENSP00000389414', 'cpi_9606.ENSP00000200676', 'cpi_9606.ENSP00000326219'], ['cpi_9606.ENSP00000295897', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000343204', 'cpi_9606.ENSP00000280357'], ['cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000368683', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000225474', 'cpi_9606.ENSP00000398632'], ['cpi_9606.ENSP00000340684', 'cpi_9606.ENSP00000231449', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000388648', 'cpi_9606.ENSP00000305221'], ['cpi_9606.ENSP00000263341', 'cpi_9606.ENSP00000296122', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000299178'], ['cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000282018', 'cpi_9606.ENSP00000354558', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000300061'], ['cpi_9606.ENSP00000331746', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000282561', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000463999'], ['cpi_9606.ENSP00000289753', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000385806', 'cpi_9606.ENSP00000355778', 'cpi_9606.ENSP00000307235'], ['cpi_9606.ENSP00000219070', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000260010'], ['cpi_9606.ENSP00000358327', 'cpi_9606.ENSP00000362924', 'cpi_9606.ENSP00000276449', 'cpi_9606.ENSP00000253727', 'cpi_9606.ENSP00000176183'], ['cpi_9606.ENSP00000290866', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000380252', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000301974'], ['cpi_9606.ENSP00000306129', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000260970'], ['cpi_9606.ENSP00000234310', 'cpi_9606.ENSP00000262735', 'cpi_9606.ENSP00000233146', 'cpi_9606.ENSP00000327652', 'cpi_9606.ENSP00000285930'], ['cpi_9606.ENSP00000262623', 'cpi_9606.ENSP00000360266', 'cpi_9606.ENSP00000316786', 'cpi_9606.ENSP00000354107', 'cpi_9606.ENSP00000309572'], ['cpi_9606.ENSP00000464149', 'cpi_9606.ENSP00000264657', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000216962', 'cpi_9606.ENSP00000344674'], ['cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000256010', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000275300'], ['cpi_9606.ENSP00000322924', 'cpi_9606.ENSP00000304845', 'cpi_9606.ENSP00000356671', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000419692'], ['cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000373169'], ['cpi_9606.ENSP00000302150', 'cpi_9606.ENSP00000256383', 'cpi_9606.ENSP00000311095', 'cpi_9606.ENSP00000263377', 'cpi_9606.ENSP00000292513'], ['cpi_9606.ENSP00000307786', 'cpi_9606.ENSP00000366506', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000270776', 'cpi_9606.ENSP00000428924'], ['cpi_9606.ENSP00000387662', 'cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000418960', 'cpi_9606.ENSP00000369757', 'cpi_9606.ENSP00000366307'], ['cpi_9606.ENSP00000266970', 'cpi_9606.ENSP00000354569', 'cpi_9606.ENSP00000266682', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000351908'], ['cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000309757', 'cpi_9606.ENSP00000288135', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000226413'], ['cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000427514', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000410076'], ['cpi_9606.ENSP00000411532', 'cpi_9606.ENSP00000355930', 'cpi_9606.ENSP00000255465', 'cpi_9606.ENSP00000262367', 'cpi_9606.ENSP00000398655'], ['cpi_9606.ENSP00000307766', 'cpi_9606.ENSP00000301633', 'cpi_9606.ENSP00000330199', 'cpi_9606.ENSP00000310928', 'cpi_9606.ENSP00000303174'], ['cpi_9606.ENSP00000327251', 'cpi_9606.ENSP00000358784', 'cpi_9606.ENSP00000254810', 'cpi_9606.ENSP00000341828', 'cpi_9606.ENSP00000270570'], ['cpi_9606.ENSP00000354511', 'cpi_9606.ENSP00000278616', 'cpi_9606.ENSP00000305302', 'cpi_9606.ENSP00000359793', 'cpi_9606.ENSP00000367608'], ['cpi_9606.ENSP00000276431', 'cpi_9606.ENSP00000355920', 'cpi_9606.ENSP00000304895', 'cpi_9606.ENSP00000357981', 'cpi_9606.ENSP00000287907'], ['cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000394033', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000260356', 'cpi_9606.ENSP00000362401'], ['cpi_9606.ENSP00000412237', 'cpi_9606.ENSP00000292896', 'cpi_9606.ENSP00000321988', 'cpi_9606.ENSP00000346298', 'cpi_9606.ENSP00000384273'], ['cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000324270', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000252029'], ['cpi_9606.ENSP00000394624', 'cpi_9606.ENSP00000262160', 'cpi_9606.ENSP00000241261', 'cpi_9606.ENSP00000338627', 'cpi_9606.ENSP00000447173'], ['cpi_9606.ENSP00000264498', 'cpi_9606.ENSP00000354193', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000355317'], ['cpi_9606.ENSP00000218548', 'cpi_9606.ENSP00000277120', 'cpi_9606.ENSP00000312652', 'cpi_9606.ENSP00000318822', 'cpi_9606.ENSP00000367309'], ['cpi_9606.ENSP00000225275', 'cpi_9606.ENSP00000353915', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000262461', 'cpi_9606.ENSP00000262948'], ['cpi_9606.ENSP00000370571', 'cpi_9606.ENSP00000386171', 'cpi_9606.ENSP00000353878', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000231228'], ['cpi_9606.ENSP00000357669', 'cpi_9606.ENSP00000369050', 'cpi_9606.ENSP00000303452', 'cpi_9606.ENSP00000346598', 'cpi_9606.ENSP00000265723'], ['cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000296545', 'cpi_9606.ENSP00000448059', 'cpi_9606.ENSP00000340820', 'cpi_9606.ENSP00000264867'], ['cpi_9606.ENSP00000361405', 'cpi_9606.ENSP00000268053', 'cpi_9606.ENSP00000216392', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000359998'], ['cpi_9606.ENSP00000363868', 'cpi_9606.ENSP00000287641', 'cpi_9606.ENSP00000352584', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000252809'], ['cpi_9606.ENSP00000358022', 'cpi_9606.ENSP00000307445', 'cpi_9606.ENSP00000285979', 'cpi_9606.ENSP00000248572', 'cpi_9606.ENSP00000365663'], ['cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000311469', 'cpi_9606.ENSP00000379213', 'cpi_9606.ENSP00000427562', 'cpi_9606.ENSP00000270474'], ['cpi_9606.ENSP00000368349', 'cpi_9606.ENSP00000393333', 'cpi_9606.ENSP00000309103', 'cpi_9606.ENSP00000420168', 'cpi_9606.ENSP00000222002'], ['cpi_9606.ENSP00000337459', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000248553', 'cpi_9606.ENSP00000393312', 'cpi_9606.ENSP00000341045'], ['cpi_9606.ENSP00000371067', 'cpi_9606.ENSP00000248076', 'cpi_9606.ENSP00000301146', 'cpi_9606.ENSP00000368632', 'cpi_9606.ENSP00000295834'], ['cpi_9606.ENSP00000265572', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000347979', 'cpi_9606.ENSP00000362036', 'cpi_9606.ENSP00000353472'], ['cpi_9606.ENSP00000338018', 'cpi_9606.ENSP00000399168', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000321106', 'cpi_9606.ENSP00000368104'], ['cpi_9606.ENSP00000331514', 'cpi_9606.ENSP00000244741', 'cpi_9606.ENSP00000331358', 'cpi_9606.ENSP00000333534', 'cpi_9606.ENSP00000379339'], ['cpi_9606.ENSP00000216117', 'cpi_9606.ENSP00000241256', 'cpi_9606.ENSP00000356150', 'cpi_9606.ENSP00000362513', 'cpi_9606.ENSP00000332816'], ['cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000262187', 'cpi_9606.ENSP00000386229', 'cpi_9606.ENSP00000211122', 'cpi_9606.ENSP00000356825'], ['cpi_9606.ENSP00000397026', 'cpi_9606.ENSP00000264832', 'cpi_9606.ENSP00000342307', 'cpi_9606.ENSP00000430432', 'cpi_9606.ENSP00000320401'], ['cpi_9606.ENSP00000261405', 'cpi_9606.ENSP00000234111', 'cpi_9606.ENSP00000297268', 'cpi_9606.ENSP00000358730', 'cpi_9606.ENSP00000370912'], ['cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000307259', 'cpi_9606.ENSP00000287936', 'cpi_9606.ENSP00000251566', 'cpi_9606.ENSP00000311028'], ['cpi_9606.ENSP00000252321', 'cpi_9606.ENSP00000234371', 'cpi_9606.ENSP00000356198', 'cpi_9606.ENSP00000355657', 'cpi_9606.ENSP00000324173'], ['cpi_9606.ENSP00000299855', 'cpi_9606.ENSP00000273430', 'cpi_9606.ENSP00000362508', 'cpi_9606.ENSP00000433821', 'cpi_9606.ENSP00000234071'], ['cpi_9606.ENSP00000274606', 'cpi_9606.ENSP00000276414', 'cpi_9606.ENSP00000236671', 'cpi_9606.ENSP00000407375', 'cpi_9606.ENSP00000355533'], ['cpi_9606.ENSP00000368727', 'cpi_9606.ENSP00000386884', 'cpi_9606.ENSP00000387683', 'cpi_9606.ENSP00000351885', 'cpi_9606.ENSP00000303325'], ['cpi_9606.ENSP00000355627', 'cpi_9606.ENSP00000301634', 'cpi_9606.ENSP00000360991', 'cpi_9606.ENSP00000263980', 'cpi_9606.ENSP00000391676'], ['cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000345774', 'cpi_9606.ENSP00000454071', 'cpi_9606.ENSP00000356694', 'cpi_9606.ENSP00000270625'], ['cpi_9606.ENSP00000225831', 'cpi_9606.ENSP00000364802', 'cpi_9606.ENSP00000359635', 'cpi_9606.ENSP00000336630', 'cpi_9606.ENSP00000368752'], ['cpi_9606.ENSP00000354532', 'cpi_9606.ENSP00000315011', 'cpi_9606.ENSP00000308032', 'cpi_9606.ENSP00000216341', 'cpi_9606.ENSP00000268035'], ['cpi_9606.ENSP00000367207', 'cpi_9606.ENSP00000338082', 'cpi_9606.ENSP00000335544', 'cpi_9606.ENSP00000366927', 'cpi_9606.ENSP00000348461'], ['cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000300151', 'cpi_9606.ENSP00000370473', 'cpi_9606.ENSP00000291294', 'cpi_9606.ENSP00000301141'], ['cpi_9606.ENSP00000275493', 'cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000265403', 'cpi_9606.ENSP00000429374', 'cpi_9606.ENSP00000225927'], ['cpi_9606.ENSP00000294954', 'cpi_9606.ENSP00000353679', 'cpi_9606.ENSP00000269571', 'cpi_9606.ENSP00000318646', 'cpi_9606.ENSP00000304915'], ['cpi_9606.ENSP00000239223', 'cpi_9606.ENSP00000234961', 'cpi_9606.ENSP00000252804', 'cpi_9606.ENSP00000239938', 'cpi_9606.ENSP00000319170'], ['cpi_9606.ENSP00000239849', 'cpi_9606.ENSP00000317842', 'cpi_9606.ENSP00000379140', 'cpi_9606.ENSP00000264818', 'cpi_9606.ENSP00000263464'], ['cpi_9606.ENSP00000260302', 'cpi_9606.ENSP00000358511', 'cpi_9606.ENSP00000228872', 'cpi_9606.ENSP00000318912', 'cpi_9606.ENSP00000296522'], ['cpi_9606.ENSP00000364709', 'cpi_9606.ENSP00000335657', 'cpi_9606.ENSP00000265164', 'cpi_9606.ENSP00000334246', 'cpi_9606.ENSP00000217426'], ['cpi_9606.ENSP00000349467', 'cpi_9606.ENSP00000341189', 'cpi_9606.ENSP00000303424', 'cpi_9606.ENSP00000314649', 'cpi_9606.ENSP00000378699'], ['cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000362344', 'cpi_9606.ENSP00000368880', 'cpi_9606.ENSP00000295589', 'cpi_9606.ENSP00000242375'], ['cpi_9606.ENSP00000359478', 'cpi_9606.ENSP00000375066', 'cpi_9606.ENSP00000356729', 'cpi_9606.ENSP0000029

🔄 Processing features: 100%|██████████| 1607/1607 [06:50<00:00,  3.91feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'cpi_9606.ENSP00000344674', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000216962', 'cpi_9606.ENSP00000356094'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000355629', 'cpi_9606.ENSP00000360773'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000430684', 'cpi_9606.ENSP00000261937', 'cpi_9606.ENSP00000265294'], ['cpi_9606.ENSP00000360372', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000347942', 'cpi_9606.ENSP00000312664', 'cpi_9606.ENSP00000355778'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000414334', 'cpi_9606.ENSP00000257290', 'cpi_9606.ENSP00000367848'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000221972', 'cpi_9606.ENSP00000345659'], ['cpi_9606.ENSP00000311032', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000359353', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000299847'], ['cpi_9606.ENSP00000367959', 'cpi_9606.ENSP00000337335', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000286301', 'cpi_9606.ENSP00000364310'], ['cpi_9606.ENSP00000265724', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000299178', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000263321'], ['cpi_9606.ENSP00000337450', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000374323', 'cpi_9606.ENSP00000323568', 'cpi_9606.ENSP00000312304'], ['cpi_9606.ENSP00000270349', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000267101', 'cpi_9606.ENSP00000301891'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000244217', 'cpi_9606.ENSP00000216037', 'cpi_9606.ENSP00000367102', 'cpi_9606.ENSP00000385026'], ['cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000344192', 'cpi_9606.ENSP00000342235', 'cpi_9606.ENSP00000285381'], ['cpi_9606.ENSP00000272190', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000354476', 'cpi_9606.ENSP00000417229'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000376943', 'cpi_9606.ENSP00000266376'], ['cpi_9606.ENSP00000258400', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000293288', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000000442'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000299267', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000377947'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000333212', 'cpi_9606.ENSP00000274547', 'cpi_9606.ENSP00000261799'], ['cpi_9606.ENSP00000369960', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000295454'], ['cpi_9606.ENSP00000215832', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000387946', 'cpi_9606.ENSP00000395653'], ['cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000378323', 'cpi_9606.ENSP00000279178', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000410732'], ['cpi_9606.ENSP00000356438', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000394936', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000381097'], ['cpi_9606.ENSP00000264381', 'cpi_9606.ENSP00000319788', 'cpi_9606.ENSP00000326119', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000352900'], ['cpi_9606.ENSP00000258743', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000259089', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000277010'], ['cpi_9606.ENSP00000363822', 'cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000308774'], ['cpi_9606.ENSP00000260433', 'cpi_9606.ENSP00000283635', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000389338'], ['cpi_9606.ENSP00000316244', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000344352', 'cpi_9606.ENSP00000332296'], ['cpi_9606.ENSP00000297494', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000261196', 'cpi_9606.ENSP00000342850'], ['cpi_9606.ENSP00000337949', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000275525', 'cpi_9606.ENSP00000241453'], ['cpi_9606.ENSP00000354859', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000358548'], ['cpi_9606.ENSP00000366506', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000226574', 'cpi_9606.ENSP00000320935', 'cpi_9606.ENSP00000301178'], ['cpi_9606.ENSP00000398698', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000220616', 'cpi_9606.ENSP00000254227'], ['cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000258749', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000471569'], ['cpi_9606.ENSP00000231509', 'cpi_9606.ENSP00000251535', 'cpi_9606.ENSP00000382659', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000348069'], ['cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000356954'], ['cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000273550', 'cpi_9606.ENSP00000231454', 'cpi_9606.ENSP00000343477', 'cpi_9606.ENSP00000331912'], ['cpi_9606.ENSP00000306245', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000312455', 'cpi_9606.ENSP00000263126'], ['cpi_9606.ENSP00000313661', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000302111', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000343040'], ['cpi_9606.ENSP00000263025', 'cpi_9606.ENSP00000370381', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000470087'], ['cpi_9606.ENSP00000358963', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000254810', 'cpi_9606.ENSP00000200676'], ['cpi_9606.ENSP00000354612', 'cpi_9606.ENSP00000339527', 'cpi_9606.ENSP00000304822', 'cpi_9606.ENSP00000307599', 'cpi_9606.ENSP00000356436'], ['cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000368766', 'cpi_9606.ENSP00000260010'], ['cpi_9606.ENSP00000280155', 'cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000295491', 'cpi_9606.ENSP00000389414'], ['cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000267119', 'cpi_9606.ENSP00000451040', 'cpi_9606.ENSP00000292896'], ['cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000306662', 'cpi_9606.ENSP00000256958', 'cpi_9606.ENSP00000445340', 'cpi_9606.ENSP00000292427'], ['cpi_9606.ENSP00000366084', 'cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000308165', 'cpi_9606.ENSP00000262888', 'cpi_9606.ENSP00000457706'], ['cpi_9606.ENSP00000287820', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000386069', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000233146'], ['cpi_9606.ENSP00000270202', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000264637'], ['cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000463999', 'cpi_9606.ENSP00000225964'], ['cpi_9606.ENSP00000305742', 'cpi_9606.ENSP00000361666', 'cpi_9606.ENSP00000454071', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000222330'], ['cpi_9606.ENSP00000305372', 'cpi_9606.ENSP00000303174', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000300061', 'cpi_9606.ENSP00000359096'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000326219'], ['cpi_9606.ENSP00000276198', 'cpi_9606.ENSP00000400175', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000329357'], ['cpi_9606.ENSP00000306512', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000264818', 'cpi_9606.ENSP00000261693', 'cpi_9606.ENSP00000307014'], ['cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000294954', 'cpi_9606.ENSP00000225474', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000358784'], ['cpi_9606.ENSP00000252945', 'cpi_9606.ENSP00000353915', 'cpi_9606.ENSP00000357283', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000274793'], ['cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000322924', 'cpi_9606.ENSP00000262461', 'cpi_9606.ENSP00000367851'], ['cpi_9606.ENSP00000269305', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000311095', 'cpi_9606.ENSP00000362036', 'cpi_9606.ENSP00000378517'], ['cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000304845', 'cpi_9606.ENSP00000301634', 'cpi_9606.ENSP00000353292', 'cpi_9606.ENSP00000297268'], ['cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000361359', 'cpi_9606.ENSP00000359100', 'cpi_9606.ENSP00000428340'], ['cpi_9606.ENSP00000218548', 'cpi_9606.ENSP00000330237', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000398632', 'cpi_9606.ENSP00000327652'], ['cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000366307', 'cpi_9606.ENSP00000387281', 'cpi_9606.ENSP00000270776', 'cpi_9606.ENSP00000252809'], ['cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000259396', 'cpi_9606.ENSP00000307240'], ['cpi_9606.ENSP00000263341', 'cpi_9606.ENSP00000355533', 'cpi_9606.ENSP00000242057', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000340691'], ['cpi_9606.ENSP00000302150', 'cpi_9606.ENSP00000467676', 'cpi_9606.ENSP00000219919', 'cpi_9606.ENSP00000292513', 'cpi_9606.ENSP00000252723'], ['cpi_9606.ENSP00000295897', 'cpi_9606.ENSP00000296871', 'cpi_9606.ENSP00000356832', 'cpi_9606.ENSP00000448059', 'cpi_9606.ENSP00000263339'], ['cpi_9606.ENSP00000358327', 'cpi_9606.ENSP00000296522', 'cpi_9606.ENSP00000317379', 'cpi_9606.ENSP00000267843', 'cpi_9606.ENSP00000335511'], ['cpi_9606.ENSP00000279387', 'cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000297350', 'cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000216862'], ['cpi_9606.ENSP00000219070', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000353791', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000248553'], ['cpi_9606.ENSP00000237612', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000231228', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000282561'], ['cpi_9606.ENSP00000355759', 'cpi_9606.ENSP00000374467', 'cpi_9606.ENSP00000373169', 'cpi_9606.ENSP00000360493', 'cpi_9606.ENSP00000349252'], ['cpi_9606.ENSP00000357669', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000372023', 'cpi_9606.ENSP00000309124'], ['cpi_9606.ENSP00000414303', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000363804', 'cpi_9606.ENSP00000316786', 'cpi_9606.ENSP00000410294'], ['cpi_9606.ENSP00000327251', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000289753'], ['cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000312029', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000288602'], ['cpi_9606.ENSP00000223095', 'cpi_9606.ENSP00000362924', 'cpi_9606.ENSP00000318822', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000176183'], ['cpi_9606.ENSP00000464149', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000324248', 'cpi_9606.ENSP00000347979', 'cpi_9606.ENSP00000309649'], ['cpi_9606.ENSP00000306129', 'cpi_9606.ENSP00000254488', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000253004'], ['cpi_9606.ENSP00000262623', 'cpi_9606.ENSP00000277120', 'cpi_9606.ENSP00000384273', 'cpi_9606.ENSP00000332369', 'cpi_9606.ENSP00000287936'], ['cpi_9606.ENSP00000331746', 'cpi_9606.ENSP00000305221', 'cpi_9606.ENSP00000353427', 'cpi_9606.ENSP00000263923', 'cpi_9606.ENSP00000262367'], ['cpi_9606.ENSP00000290866', 'cpi_9606.ENSP00000262948', 'cpi_9606.ENSP00000276449', 'cpi_9606.ENSP00000386171', 'cpi_9606.ENSP00000352702'], ['cpi_9606.ENSP00000412237', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000340820', 'cpi_9606.ENSP00000354394'], ['cpi_9606.ENSP00000337459', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000311028', 'cpi_9606.ENSP00000304915', 'cpi_9606.ENSP00000233242'], ['cpi_9606.ENSP00000225275', 'cpi_9606.ENSP00000329623', 'cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000428924'], ['cpi_9606.ENSP00000307786', 'cpi_9606.ENSP00000294728', 'cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000176763', 'cpi_9606.ENSP00000291294'], ['cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000295598', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000309757', 'cpi_9606.ENSP00000307766'], ['cpi_9606.ENSP00000360608', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000295834', 'cpi_9606.ENSP00000287907', 'cpi_9606.ENSP00000241261'], ['cpi_9606.ENSP00000364782', 'cpi_9606.ENSP00000380252', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000358730', 'cpi_9606.ENSP00000330393'], ['cpi_9606.ENSP00000308541', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000343204', 'cpi_9606.ENSP00000255465', 'cpi_9606.ENSP00000256906'], ['cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000368683', 'cpi_9606.ENSP00000296122', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000349577'], ['cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000355317', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000264657', 'cpi_9606.ENSP00000270474'], ['cpi_9606.ENSP00000411532', 'cpi_9606.ENSP00000355930', 'cpi_9606.ENSP00000264867', 'cpi_9606.ENSP00000365380', 'cpi_9606.ENSP00000310447'], ['cpi_9606.ENSP00000361405', 'cpi_9606.ENSP00000355325', 'cpi_9606.ENSP00000365663', 'cpi_9606.ENSP00000282397', 'cpi_9606.ENSP00000355920'], ['cpi_9606.ENSP00000266970', 'cpi_9606.ENSP00000331358', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000355657', 'cpi_9606.ENSP00000331736'], ['cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000295400', 'cpi_9606.ENSP00000319814', 'cpi_9606.ENSP00000351885', 'cpi_9606.ENSP00000263980'], ['cpi_9606.ENSP00000370571', 'cpi_9606.ENSP00000310928', 'cpi_9606.ENSP00000410076', 'cpi_9606.ENSP00000308176', 'cpi_9606.ENSP00000307235'], ['cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000301633', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000358511', 'cpi_9606.ENSP00000241600'], ['cpi_9606.ENSP00000345096', 'cpi_9606.ENSP00000385806', 'cpi_9606.ENSP00000336630', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000252486'], ['cpi_9606.ENSP00000387662', 'cpi_9606.ENSP00000320401', 'cpi_9606.ENSP00000388648', 'cpi_9606.ENSP00000346598', 'cpi_9606.ENSP00000216185'], ['cpi_9606.ENSP00000321584', 'cpi_9606.ENSP00000370473', 'cpi_9606.ENSP00000265723', 'cpi_9606.ENSP00000342560', 'cpi_9606.ENSP00000354107'], ['cpi_9606.ENSP00000216117', 'cpi_9606.ENSP00000282018', 'cpi_9606.ENSP00000379339', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000305302'], ['cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000231449', 'cpi_9606.ENSP00000259271', 'cpi_9606.ENSP00000311469', 'cpi_9606.ENSP00000237527'], ['cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000245457', 'cpi_9606.ENSP00000360967', 'cpi_9606.ENSP00000353878', 'cpi_9606.ENSP00000365016'], ['cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000212015', 'cpi_9606.ENSP00000359635', 'cpi_9606.ENSP00000216341', 'cpi_9606.ENSP00000341045'], ['cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000256010', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000266682'], ['cpi_9606.ENSP00000338018', 'cpi_9606.ENSP00000399168', 'cpi_9606.ENSP00000419692', 'cpi_9606.ENSP00000234961', 'cpi_9606.ENSP00000394033'], ['cpi_9606.ENSP00000371067', 'cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000303522', 'cpi_9606.ENSP00000260356', 'cpi_9606.ENSP00000435777'], ['cpi_9606.ENSP00000369050', 'cpi_9606.ENSP00000433290', 'cpi_9606.ENSP00000252029', 'cpi_9606.ENSP00000351209', 'cpi_9606.ENSP00000278616'], ['cpi_9606.ENSP00000225831', 'cpi_9606.ENSP00000364802', 'cpi_9606.ENSP00000333821', 'cpi_9606.ENSP00000346298', 'cpi_9606.ENSP00000332816'], ['cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000265403', 'cpi_9606.ENSP00000362353', 'cpi_9606.ENSP00000330199'], ['cpi_9606.ENSP00000394624', 'cpi_9606.ENSP00000262160', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000356150', 'cpi_9606.ENSP00000253727'], ['cpi_9606.ENSP00000265572', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000427514', 'cpi_9606.ENSP00000280357', 'cpi_9606.ENSP00000268053'], ['cpi_9606.ENSP00000274606', 'cpi_9606.ENSP00000360266', 'cpi_9606.ENSP00000359793', 'cpi_9606.ENSP00000275300', 'cpi_9606.ENSP00000285979'], ['cpi_9606.ENSP00000354511', 'cpi_9606.ENSP00000264832', 'cpi_9606.ENSP00000232219', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000216392'], ['cpi_9606.ENSP00000368727', 'cpi_9606.ENSP00000354558', 'cpi_9606.ENSP00000307445', 'cpi_9606.ENSP00000338548', 'cpi_9606.ENSP00000338627'], ['cpi_9606.ENSP00000363868', 'cpi_9606.ENSP00000351908', 'cpi_9606.ENSP00000287641', 'cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000324856'], ['cpi_9606.ENSP00000301141', 'cpi_9606.ENSP00000314949', 'cpi_9606.ENSP00000321106', 'cpi_9606.ENSP00000352584', 'cpi_9606.ENSP00000270625'], ['cpi_9606.ENSP00000358022', 'cpi_9606.ENSP00000321988', 'cpi_9606.ENSP00000362401', 'cpi_9606.ENSP00000333534', 'cpi_9606.ENSP00000196551'], ['cpi_9606.ENSP00000279593', 'cpi_9606.ENSP00000262735', 'cpi_9606.ENSP00000459962', 'cpi_9606.ENSP00000419782', 'cpi_9606.ENSP00000318912'], ['cpi_9606.ENSP00000239223', 'cpi_9606.ENSP00000242152', 'cpi_9606.ENSP00000427562', 'cpi_9606.ENSP00000357981', 'cpi_9606.ENSP00000362549'], ['cpi_9606.ENSP00000260970', 'cpi_9606.ENSP00000312673', 'cpi_9606.ENSP00000308549', 'cpi_9606.ENSP00000221515', 'cpi_9606.ENSP00000263464'], ['cpi_9606.ENSP00000317842', 'cpi_9606.ENSP00000297469', 'cpi_9606.ENSP00000311165', 'cpi_9606.ENSP00000239938', 'cpi_9606.ENSP00000268251'], ['cpi_9606.ENSP00000264498', 'cpi_9606.ENSP00000320709', 'cpi_9606.ENSP00000420168', 'cpi_9606.ENSP00000321999', 'cpi_9606.ENSP00000288135'], ['cpi_9606.ENSP00000276431', 'cpi_9606.ENSP00000393312', 'cpi_9606.ENSP00000367309', 'cpi_9606.ENSP00000239849', 'cpi_9606.ENSP00000296674'], ['cpi_9606.ENSP00000292303', 'cpi_9606.ENSP00000288022', 'cpi_9606.ENSP00000368880', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000429374'], ['cpi_9606.ENSP00000252321', 'cpi_9606.ENSP00000393333', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000398655', 'cpi_9606.ENSP00000337773'], ['cpi_9606.ENSP00000302665', 'cpi_9606.ENSP00000340684', 'cpi_9606.ENSP00000341885', 'cpi_9606.ENSP00000368752', 'cpi_9606.ENSP00000360973'], ['cpi_9606.ENSP00000331514', 'cpi_9606.ENSP00000244741', 'cpi_9606.ENSP00000354569', 'cpi_9606.ENSP00000248041', 'cpi_9606.ENSP00000433821'], ['cpi_9606.ENSP00000370129', 'cpi_9606.ENSP00000379110', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000341189', 'cpi_9606.ENSP00000430432'], ['cpi_9606.ENSP00000397026', 'cpi_9606.ENSP00000296545', 'cpi_9606.ENSP00000256383', 'cpi_9606.ENSP00000362513', 'cpi_9606.ENSP00000267377'], ['cpi_9606.ENSP00000260302', 'cpi_9606.ENSP00000302846', 'cpi_9606.ENSP00000301146', 'cpi_9606.ENSP00000362649', 'cpi_9606.ENSP00000378699'], ['cpi_9606.ENSP00000265023', 'cpi_9606.ENSP00000314508', 'cpi_9606.ENSP00000309968', 'cpi_9606.ENSP00000228872', 'cpi_9606.ENSP00000356825'], ['cpi_9606.ENSP00000382342', 'cpi_9606.ENSP00000276571', 'cpi_9606.ENSP00000368632', 'cpi_9606.ENSP00000356671', 'cpi_9606.ENSP00000334246'], ['cpi_9606.ENSP00000272298', 'cpi_9606.ENSP00000368104', 'cpi_9606.ENSP00000349003', 'cpi_9606.ENSP00000359998', 'cpi_9606.ENSP00000274026'], ['cpi_9606.ENSP00000367207', 'cpi_9606.ENSP00000338082', 'cpi_9606.ENSP00000335544', 'cpi_9606.ENSP00000370912', 'cpi_9606.ENSP00000264896'], ['cpi_9606.ENSP00000318585', 'cpi_9606.ENSP00000387699', 'cpi_9606.ENSP00000309103', 'cpi_9606.ENSP00000304408', 'cpi_9606.ENSP00000226413'], ['cpi_9606.ENSP00000355627', 'cpi_9606.ENSP00000369757', 'cpi_9606.ENSP00000225927', 'cpi_9606.ENSP00000418960', 'cpi_9606.ENSP00000318646'], ['cpi_9606.ENSP00000269571', 'cpi_9606.ENSP00000282753', 'cpi_9606.ENSP00000274353', 'cpi_9606.ENSP00000362508', 'cpi_9606.ENSP00000164139'], ['cpi_9606.ENSP00000324806', 'cpi_9606.ENSP00000366416', 'cpi_9606.ENSP00000387683', 'cpi_9606.ENSP00000251453', 'cpi_9606.ENSP00000356694'], ['cpi_9606.ENSP00000359478', 'cpi_9606.ENSP00000363596', 'cpi_9606.ENSP00000219700', 'cpi_9606.ENSP00000211287', 'cpi_9606.ENSP00000220809'], ['cpi_9606.ENSP00000299855', 'cpi_9606.ENSP00000315011', 'cpi_9606.ENSP00000341828', 'cpi_9606.ENSP0000022

🔄 Processing features: 100%|██████████| 1607/1607 [06:51<00:00,  3.90feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'cpi_9606.ENSP00000326219', 'cpi_9606.ENSP00000356094', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000298472'], ['cpi_9606.ENSP00000231509', 'cpi_9606.ENSP00000274547', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000301891', 'cpi_9606.ENSP00000355629'], ['cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000261937'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000367848'], ['cpi_9606.ENSP00000237014', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000277010', 'cpi_9606.ENSP00000337335', 'cpi_9606.ENSP00000358548'], ['cpi_9606.ENSP00000311032', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000299847'], ['cpi_9606.ENSP00000264381', 'cpi_9606.ENSP00000319788', 'cpi_9606.ENSP00000417229', 'cpi_9606.ENSP00000342235', 'cpi_9606.ENSP00000261693'], ['cpi_9606.ENSP00000265724', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000299178', 'cpi_9606.ENSP00000359353', 'cpi_9606.ENSP00000245539'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000299267', 'cpi_9606.ENSP00000332296'], ['cpi_9606.ENSP00000369960', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000295452'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000309818', 'cpi_9606.ENSP00000430684', 'cpi_9606.ENSP00000374323', 'cpi_9606.ENSP00000348897'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000266376', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000264318'], ['cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000252809', 'cpi_9606.ENSP00000261799', 'cpi_9606.ENSP00000316244'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000377947'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000312664', 'cpi_9606.ENSP00000331912', 'cpi_9606.ENSP00000381097'], ['cpi_9606.ENSP00000360372', 'cpi_9606.ENSP00000359793', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000360773'], ['cpi_9606.ENSP00000272190', 'cpi_9606.ENSP00000389338', 'cpi_9606.ENSP00000301178', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000447149'], ['cpi_9606.ENSP00000363822', 'cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000283254'], ['cpi_9606.ENSP00000260433', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000283635', 'cpi_9606.ENSP00000257290', 'cpi_9606.ENSP00000359334'], ['cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000370381', 'cpi_9606.ENSP00000395653'], ['cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000354476', 'cpi_9606.ENSP00000414334'], ['cpi_9606.ENSP00000367959', 'cpi_9606.ENSP00000301634', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000242057', 'cpi_9606.ENSP00000342850'], ['cpi_9606.ENSP00000220764', 'cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000279178', 'cpi_9606.ENSP00000295454'], ['cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000263321', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000367102', 'cpi_9606.ENSP00000335592'], ['cpi_9606.ENSP00000316786', 'cpi_9606.ENSP00000357204', 'cpi_9606.ENSP00000398632', 'cpi_9606.ENSP00000387281', 'cpi_9606.ENSP00000216037'], ['cpi_9606.ENSP00000305372', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000347942'], ['cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000367851', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000302111', 'cpi_9606.ENSP00000471569'], ['cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000225474', 'cpi_9606.ENSP00000362036', 'cpi_9606.ENSP00000280155', 'cpi_9606.ENSP00000307599'], ['cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000357283', 'cpi_9606.ENSP00000295491'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000262441', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000364802', 'cpi_9606.ENSP00000286301'], ['cpi_9606.ENSP00000366506', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000354394', 'cpi_9606.ENSP00000293745'], ['cpi_9606.ENSP00000270202', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000394936', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000241600'], ['cpi_9606.ENSP00000270349', 'cpi_9606.ENSP00000303830', 'cpi_9606.ENSP00000251535', 'cpi_9606.ENSP00000387946', 'cpi_9606.ENSP00000346534'], ['cpi_9606.ENSP00000295897', 'cpi_9606.ENSP00000378517', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000259396'], ['cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000263341', 'cpi_9606.ENSP00000376943', 'cpi_9606.ENSP00000264637', 'cpi_9606.ENSP00000353362'], ['cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000366307', 'cpi_9606.ENSP00000275525', 'cpi_9606.ENSP00000336630', 'cpi_9606.ENSP00000343477'], ['cpi_9606.ENSP00000411532', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000344192', 'cpi_9606.ENSP00000410294', 'cpi_9606.ENSP00000343040'], ['cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000320866', 'cpi_9606.ENSP00000361666', 'cpi_9606.ENSP00000359285'], ['cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000260010', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000312455'], ['cpi_9606.ENSP00000284981', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000326119', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000333212'], ['cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000356954', 'cpi_9606.ENSP00000259089', 'cpi_9606.ENSP00000428340'], ['cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000386284', 'cpi_9606.ENSP00000221972', 'cpi_9606.ENSP00000344352', 'cpi_9606.ENSP00000470087'], ['cpi_9606.ENSP00000350348', 'cpi_9606.ENSP00000356729', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000348069', 'cpi_9606.ENSP00000155840'], ['cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000359635'], ['cpi_9606.ENSP00000398698', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000220616', 'cpi_9606.ENSP00000221421'], ['cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000236850', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000304822', 'cpi_9606.ENSP00000389414'], ['cpi_9606.ENSP00000297494', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000393312', 'cpi_9606.ENSP00000296370'], ['cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000327652', 'cpi_9606.ENSP00000307014'], ['cpi_9606.ENSP00000354859', 'cpi_9606.ENSP00000264162', 'cpi_9606.ENSP00000361359', 'cpi_9606.ENSP00000267101', 'cpi_9606.ENSP00000261196'], ['cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000330237', 'cpi_9606.ENSP00000327431', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000258749'], ['cpi_9606.ENSP00000337450', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000362649', 'cpi_9606.ENSP00000297350', 'cpi_9606.ENSP00000216862'], ['cpi_9606.ENSP00000337949', 'cpi_9606.ENSP00000354850', 'cpi_9606.ENSP00000278616', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000263126'], ['cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000233242', 'cpi_9606.ENSP00000386069', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000222330'], ['cpi_9606.ENSP00000274353', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000372023', 'cpi_9606.ENSP00000276198', 'cpi_9606.ENSP00000308165'], ['cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000353679', 'cpi_9606.ENSP00000252723', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000267119'], ['cpi_9606.ENSP00000356438', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000451040', 'cpi_9606.ENSP00000457706'], ['cpi_9606.ENSP00000352835', 'cpi_9606.ENSP00000264657', 'cpi_9606.ENSP00000353292', 'cpi_9606.ENSP00000312029', 'cpi_9606.ENSP00000252945'], ['cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000260356', 'cpi_9606.ENSP00000309124', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000308845'], ['cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000263980', 'cpi_9606.ENSP00000256958', 'cpi_9606.ENSP00000176183', 'cpi_9606.ENSP00000427514'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000291294', 'cpi_9606.ENSP00000252519'], ['cpi_9606.ENSP00000381333', 'cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000200676'], ['cpi_9606.ENSP00000368766', 'cpi_9606.ENSP00000353731', 'cpi_9606.ENSP00000232219', 'cpi_9606.ENSP00000360493', 'cpi_9606.ENSP00000176763'], ['cpi_9606.ENSP00000308541', 'cpi_9606.ENSP00000282561', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000256383', 'cpi_9606.ENSP00000445340'], ['cpi_9606.ENSP00000373169', 'cpi_9606.ENSP00000338548', 'cpi_9606.ENSP00000252486', 'cpi_9606.ENSP00000344674', 'cpi_9606.ENSP00000356436'], ['cpi_9606.ENSP00000258743', 'cpi_9606.ENSP00000264818', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000231454'], ['cpi_9606.ENSP00000306512', 'cpi_9606.ENSP00000318912', 'cpi_9606.ENSP00000300061', 'cpi_9606.ENSP00000369757', 'cpi_9606.ENSP00000306662'], ['cpi_9606.ENSP00000225831', 'cpi_9606.ENSP00000248553', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000262888', 'cpi_9606.ENSP00000355920'], ['cpi_9606.ENSP00000306245', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000332369', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000463999'], ['cpi_9606.ENSP00000358963', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000346598', 'cpi_9606.ENSP00000221515'], ['cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000313661', 'cpi_9606.ENSP00000294728', 'cpi_9606.ENSP00000266682'], ['cpi_9606.ENSP00000387662', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000254488', 'cpi_9606.ENSP00000293288', 'cpi_9606.ENSP00000348827'], ['cpi_9606.ENSP00000261205', 'cpi_9606.ENSP00000412237', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000262948', 'cpi_9606.ENSP00000267843'], ['cpi_9606.ENSP00000354612', 'cpi_9606.ENSP00000339527', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000340820', 'cpi_9606.ENSP00000258400'], ['cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000264832', 'cpi_9606.ENSP00000314508', 'cpi_9606.ENSP00000365663', 'cpi_9606.ENSP00000307235'], ['cpi_9606.ENSP00000368305', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000289753', 'cpi_9606.ENSP00000311095', 'cpi_9606.ENSP00000358784'], ['cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000353878', 'cpi_9606.ENSP00000248041', 'cpi_9606.ENSP00000229264'], ['cpi_9606.ENSP00000270142', 'cpi_9606.ENSP00000400175', 'cpi_9606.ENSP00000276449', 'cpi_9606.ENSP00000382659', 'cpi_9606.ENSP00000351209'], ['cpi_9606.ENSP00000215832', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000216962', 'cpi_9606.ENSP00000255465', 'cpi_9606.ENSP00000296871'], ['cpi_9606.ENSP00000216465', 'cpi_9606.ENSP00000414303', 'cpi_9606.ENSP00000329357', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000308774'], ['cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000388648', 'cpi_9606.ENSP00000225964', 'cpi_9606.ENSP00000306129'], ['cpi_9606.ENSP00000302150', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000355657', 'cpi_9606.ENSP00000292513', 'cpi_9606.ENSP00000359663'], ['cpi_9606.ENSP00000269305', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000428924', 'cpi_9606.ENSP00000369816'], ['cpi_9606.ENSP00000309845', 'cpi_9606.ENSP00000301146', 'cpi_9606.ENSP00000353915', 'cpi_9606.ENSP00000310928', 'cpi_9606.ENSP00000314099'], ['cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000226574', 'cpi_9606.ENSP00000234961', 'cpi_9606.ENSP00000360967'], ['cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000341045', 'cpi_9606.ENSP00000295834', 'cpi_9606.ENSP00000263923'], ['cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000274793', 'cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000385806', 'cpi_9606.ENSP00000303174'], ['cpi_9606.ENSP00000257497', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000225927', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000467676'], ['cpi_9606.ENSP00000263025', 'cpi_9606.ENSP00000349577', 'cpi_9606.ENSP00000288602', 'cpi_9606.ENSP00000354569', 'cpi_9606.ENSP00000285979'], ['cpi_9606.ENSP00000394624', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000330393', 'cpi_9606.ENSP00000347979', 'cpi_9606.ENSP00000311028'], ['cpi_9606.ENSP00000296545', 'cpi_9606.ENSP00000254976', 'cpi_9606.ENSP00000265723', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000252029'], ['cpi_9606.ENSP00000265572', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000318822', 'cpi_9606.ENSP00000262367', 'cpi_9606.ENSP00000253727'], ['cpi_9606.ENSP00000330032', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000358327', 'cpi_9606.ENSP00000360973', 'cpi_9606.ENSP00000353427'], ['cpi_9606.ENSP00000361405', 'cpi_9606.ENSP00000355325', 'cpi_9606.ENSP00000277120', 'cpi_9606.ENSP00000459962', 'cpi_9606.ENSP00000352584'], ['cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000282753', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000321988', 'cpi_9606.ENSP00000262461'], ['cpi_9606.ENSP00000234111', 'cpi_9606.ENSP00000264867', 'cpi_9606.ENSP00000275300', 'cpi_9606.ENSP00000350198', 'cpi_9606.ENSP00000311469'], ['cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000370473', 'cpi_9606.ENSP00000320935', 'cpi_9606.ENSP00000448059', 'cpi_9606.ENSP00000296674'], ['cpi_9606.ENSP00000237612', 'cpi_9606.ENSP00000292896', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000307766', 'cpi_9606.ENSP00000365016'], ['cpi_9606.ENSP00000408695', 'cpi_9606.ENSP00000410076', 'cpi_9606.ENSP00000282397', 'cpi_9606.ENSP00000322924', 'cpi_9606.ENSP00000261835'], ['cpi_9606.ENSP00000315644', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000287907', 'cpi_9606.ENSP00000287936', 'cpi_9606.ENSP00000343204'], ['cpi_9606.ENSP00000378699', 'cpi_9606.ENSP00000464149', 'cpi_9606.ENSP00000362353', 'cpi_9606.ENSP00000353791', 'cpi_9606.ENSP00000346768'], ['cpi_9606.ENSP00000304915', 'cpi_9606.ENSP00000268053', 'cpi_9606.ENSP00000265164', 'cpi_9606.ENSP00000367309', 'cpi_9606.ENSP00000332816'], ['cpi_9606.ENSP00000312652', 'cpi_9606.ENSP00000340943', 'cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000329623', 'cpi_9606.ENSP00000270776'], ['cpi_9606.ENSP00000327801', 'cpi_9606.ENSP00000231228', 'cpi_9606.ENSP00000304845', 'cpi_9606.ENSP00000355778', 'cpi_9606.ENSP00000356694'], ['cpi_9606.ENSP00000375066', 'cpi_9606.ENSP00000359478', 'cpi_9606.ENSP00000357981', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000363832'], ['cpi_9606.ENSP00000405573', 'cpi_9606.ENSP00000354558', 'cpi_9606.ENSP00000239938', 'cpi_9606.ENSP00000270625', 'cpi_9606.ENSP00000307445'], ['cpi_9606.ENSP00000356022', 'cpi_9606.ENSP00000296122', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000303522', 'cpi_9606.ENSP00000396320'], ['cpi_9606.ENSP00000298171', 'cpi_9606.ENSP00000320709', 'cpi_9606.ENSP00000420168', 'cpi_9606.ENSP00000264498', 'cpi_9606.ENSP00000317379'], ['cpi_9606.ENSP00000295598', 'cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000309757', 'cpi_9606.ENSP00000354107', 'cpi_9606.ENSP00000342560'], ['cpi_9606.ENSP00000355759', 'cpi_9606.ENSP00000362810', 'cpi_9606.ENSP00000394033', 'cpi_9606.ENSP00000305221', 'cpi_9606.ENSP00000270474'], ['cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000362344', 'cpi_9606.ENSP00000323568', 'cpi_9606.ENSP00000358511', 'cpi_9606.ENSP00000368104'], ['cpi_9606.ENSP00000369647', 'cpi_9606.ENSP00000241261', 'cpi_9606.ENSP00000353224', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000178638'], ['cpi_9606.ENSP00000222553', 'cpi_9606.ENSP00000451030', 'cpi_9606.ENSP00000228872', 'cpi_9606.ENSP00000305302', 'cpi_9606.ENSP00000418532'], ['cpi_9606.ENSP00000262407', 'cpi_9606.ENSP00000380252', 'cpi_9606.ENSP00000239849', 'cpi_9606.ENSP00000226413', 'cpi_9606.ENSP00000253122'], ['cpi_9606.ENSP00000356825', 'cpi_9606.ENSP00000355930', 'cpi_9606.ENSP00000295400', 'cpi_9606.ENSP00000365380', 'cpi_9606.ENSP00000219700'], ['cpi_9606.ENSP00000342952', 'cpi_9606.ENSP00000384273', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000433821', 'cpi_9606.ENSP00000265403'], ['cpi_9606.ENSP00000219070', 'cpi_9606.ENSP00000398655', 'cpi_9606.ENSP00000338082', 'cpi_9606.ENSP00000324248', 'cpi_9606.ENSP00000330199'], ['cpi_9606.ENSP00000397582', 'cpi_9606.ENSP00000368683', 'cpi_9606.ENSP00000419692', 'cpi_9606.ENSP00000308032', 'cpi_9606.ENSP00000196551'], ['cpi_9606.ENSP00000272298', 'cpi_9606.ENSP00000244741', 'cpi_9606.ENSP00000261465', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000355317'], ['cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000379213', 'cpi_9606.ENSP00000311165', 'cpi_9606.ENSP00000346298', 'cpi_9606.ENSP00000216797'], ['cpi_9606.ENSP00000275216', 'cpi_9606.ENSP00000277508', 'cpi_9606.ENSP00000297268', 'cpi_9606.ENSP00000309103', 'cpi_9606.ENSP00000338627'], ['cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000306606', 'cpi_9606.ENSP00000328173', 'cpi_9606.ENSP00000338018', 'cpi_9606.ENSP00000356671'], ['cpi_9606.ENSP00000373477', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000358730', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000368880'], ['cpi_9606.ENSP00000272847', 'cpi_9606.ENSP00000306100', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000252321', 'cpi_9606.ENSP00000260970'], ['cpi_9606.ENSP00000229447', 'cpi_9606.ENSP00000231449', 'cpi_9606.ENSP00000233146', 'cpi_9606.ENSP00000386229', 'cpi_9606.ENSP00000341885'], ['cpi_9606.ENSP00000359899', 'cpi_9606.ENSP00000369050', 'cpi_9606.ENSP00000263464', 'cpi_9606.ENSP00000310447', 'cpi_9606.ENSP00000268251'], ['cpi_9606.ENSP00000352608', 'cpi_9606.ENSP00000371554', 'cpi_9606.ENSP00000262735', 'cpi_9606.ENSP00000427562', 'cpi_9606.ENSP00000308549'], ['cpi_9606.ENSP00000333994', 'cpi_9606.ENSP00000393333', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000301633', 'cpi_9606.ENSP00000351885'], ['cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000331358', 'cpi_9606.ENSP00000301141', 'cpi_9606.ENSP00000379339', 'cpi_9606.ENSP00000454071'], ['cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000466799', 'cpi_9606.ENSP00000303452', 'cpi_9606.ENSP00000318646', 'cpi_9606.ENSP00000368752'], ['cpi_9606.ENSP00000364035', 'cpi_9606.ENSP00000304895', 'cpi_9606.ENSP00000267377', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000371985'], ['cpi_9606.ENSP00000383365', 'cpi_9606.ENSP00000265023', 'cpi_9606.ENSP00000288135', 'cpi_9606.ENSP00000387683', 'cpi_9606.ENSP00000386171'], ['cpi_9606.ENSP00000229319', 'cpi_9606.ENSP00000321106', 'cpi_9606.ENSP00000333534', 'cpi_9606.ENSP00000351908', 'cpi_9606.ENSP00000223095'], ['cpi_9606.ENSP00000327251', 'cpi_9606.ENSP00000352035', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000254810', 'cpi_9606.ENSP00000293897'], ['cpi_9606.ENSP00000349467', 'cpi_9606.ENSP00000341189', 'cpi_9606.ENSP00000333821', 'cpi_9606.ENSP00000211122', 'cpi_9606.ENSP00000164139'], ['cpi_9606.ENSP00000257068', 'cpi_9606.ENSP00000234389', 'cpi_9606.ENSP00000362508', 'cpi_9606.ENSP00000331602', 'cpi_9606.ENSP00000268035'], ['cpi_9606.ENSP00000355536', 'cpi_9606.ENSP00000260630', 'cpi_9606.ENSP00000264896', 'cpi_9606.ENSP00000359532', 'cpi_9606.ENSP00000435777'], ['cpi_9606.ENSP00000344460', 'cpi_9606.ENSP00000287641', 'cpi_9606.ENSP00000221930', 'cpi_9606.ENSP00000349252', 'cpi_9606.ENSP00000320401'], ['cpi_9606.ENSP00000348775', 'cpi_9606.ENSP00000360266', 'cpi_9606.ENSP00000234371', 'cpi_9606.ENSP00000429374', 'cpi_9606.ENSP00000362513'], ['cpi_9606.ENSP00000260302', 'cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000219919', 'cpi_9606.ENSP00000356150', 'cpi_9606.ENSP00000332679'], ['cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000256010', 'cpi_9606.ENSP00000295453', 'cpi_9606.ENSP00000337773', 'cpi_9606.ENSP00000251453'], ['cpi_9606.ENSP00000261267', 'cpi_9606.ENSP00000276571', 'cpi_9606.ENSP00000321821', 'cpi_9606.ENSP0000029

🔄 Processing features: 100%|██████████| 1607/1607 [06:51<00:00,  3.91feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000359793', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000395653'], ['cpi_9606.ENSP00000231509', 'cpi_9606.ENSP00000277010', 'cpi_9606.ENSP00000225474', 'cpi_9606.ENSP00000266376', 'cpi_9606.ENSP00000356094'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000359353', 'cpi_9606.ENSP00000428864'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000261937'], ['cpi_9606.ENSP00000264381', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000261799', 'cpi_9606.ENSP00000337335', 'cpi_9606.ENSP00000367848'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000220616', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000377947'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000355629', 'cpi_9606.ENSP00000260010', 'cpi_9606.ENSP00000265294'], ['cpi_9606.ENSP00000265724', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000381097', 'cpi_9606.ENSP00000387946'], ['cpi_9606.ENSP00000360372', 'cpi_9606.ENSP00000309818', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000332296', 'cpi_9606.ENSP00000357068'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000295491', 'cpi_9606.ENSP00000295454', 'cpi_9606.ENSP00000261196'], ['cpi_9606.ENSP00000260433', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000283635', 'cpi_9606.ENSP00000347942', 'cpi_9606.ENSP00000430684'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000309124'], ['cpi_9606.ENSP00000237014', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000358548'], ['cpi_9606.ENSP00000311032', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000344674'], ['cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000342235', 'cpi_9606.ENSP00000417229', 'cpi_9606.ENSP00000352900'], ['cpi_9606.ENSP00000369960', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000221972'], ['cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000367851', 'cpi_9606.ENSP00000301891', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000389338'], ['cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000414303', 'cpi_9606.ENSP00000319788', 'cpi_9606.ENSP00000282561', 'cpi_9606.ENSP00000261693'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000374323', 'cpi_9606.ENSP00000312664'], ['cpi_9606.ENSP00000272190', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000275525', 'cpi_9606.ENSP00000354476', 'cpi_9606.ENSP00000457706'], ['cpi_9606.ENSP00000263321', 'cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000367102', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000231454'], ['cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000357204', 'cpi_9606.ENSP00000326119', 'cpi_9606.ENSP00000353362'], ['cpi_9606.ENSP00000220764', 'cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000279178', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000299267'], ['cpi_9606.ENSP00000305372', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000274547', 'cpi_9606.ENSP00000357283', 'cpi_9606.ENSP00000333212'], ['cpi_9606.ENSP00000270202', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000394936', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000298472'], ['cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000363822', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000359334'], ['cpi_9606.ENSP00000316786', 'cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000398632', 'cpi_9606.ENSP00000360773', 'cpi_9606.ENSP00000264637'], ['cpi_9606.ENSP00000270142', 'cpi_9606.ENSP00000361666', 'cpi_9606.ENSP00000294728', 'cpi_9606.ENSP00000257290', 'cpi_9606.ENSP00000412673'], ['cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000233242', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000286301'], ['cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000302111', 'cpi_9606.ENSP00000308165', 'cpi_9606.ENSP00000451040', 'cpi_9606.ENSP00000335592'], ['cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000354394', 'cpi_9606.ENSP00000301178'], ['cpi_9606.ENSP00000367959', 'cpi_9606.ENSP00000301634', 'cpi_9606.ENSP00000242057', 'cpi_9606.ENSP00000343477', 'cpi_9606.ENSP00000331912'], ['cpi_9606.ENSP00000398698', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000293745'], ['cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000386284', 'cpi_9606.ENSP00000344192', 'cpi_9606.ENSP00000252809', 'cpi_9606.ENSP00000312455'], ['cpi_9606.ENSP00000366506', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000222330'], ['cpi_9606.ENSP00000295897', 'cpi_9606.ENSP00000378517', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000216037'], ['cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000362810', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000252723', 'cpi_9606.ENSP00000255465'], ['cpi_9606.ENSP00000344456', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000304822', 'cpi_9606.ENSP00000348069', 'cpi_9606.ENSP00000471569'], ['cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000352835', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000296871', 'cpi_9606.ENSP00000386029'], ['cpi_9606.ENSP00000297494', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000353791', 'cpi_9606.ENSP00000267101', 'cpi_9606.ENSP00000216392'], ['cpi_9606.ENSP00000368438', 'cpi_9606.ENSP00000355930', 'cpi_9606.ENSP00000259396', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000311095'], ['cpi_9606.ENSP00000411532', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000346534'], ['cpi_9606.ENSP00000337949', 'cpi_9606.ENSP00000264162', 'cpi_9606.ENSP00000376943', 'cpi_9606.ENSP00000414334', 'cpi_9606.ENSP00000357255'], ['cpi_9606.ENSP00000284981', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000330393', 'cpi_9606.ENSP00000320025'], ['cpi_9606.ENSP00000270349', 'cpi_9606.ENSP00000262888', 'cpi_9606.ENSP00000262948', 'cpi_9606.ENSP00000200676', 'cpi_9606.ENSP00000222390'], ['cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000263341', 'cpi_9606.ENSP00000307599', 'cpi_9606.ENSP00000259089', 'cpi_9606.ENSP00000292427'], ['cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000389414', 'cpi_9606.ENSP00000366307'], ['cpi_9606.ENSP00000308541', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000470087'], ['cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000354850', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000410294', 'cpi_9606.ENSP00000356954'], ['cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000252486', 'cpi_9606.ENSP00000280155', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000334198'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000362353', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000351209', 'cpi_9606.ENSP00000274793'], ['cpi_9606.ENSP00000316244', 'cpi_9606.ENSP00000359478', 'cpi_9606.ENSP00000362036', 'cpi_9606.ENSP00000361359', 'cpi_9606.ENSP00000176763'], ['cpi_9606.ENSP00000337450', 'cpi_9606.ENSP00000340943', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000428340', 'cpi_9606.ENSP00000427514'], ['cpi_9606.ENSP00000258743', 'cpi_9606.ENSP00000264818', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000263126', 'cpi_9606.ENSP00000258749'], ['cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000225831', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000288135', 'cpi_9606.ENSP00000296370'], ['cpi_9606.ENSP00000330237', 'cpi_9606.ENSP00000405573', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000368766', 'cpi_9606.ENSP00000221421'], ['cpi_9606.ENSP00000356438', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000270776', 'cpi_9606.ENSP00000339527'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000296545', 'cpi_9606.ENSP00000448059', 'cpi_9606.ENSP00000329357'], ['cpi_9606.ENSP00000306245', 'cpi_9606.ENSP00000310928', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000332369', 'cpi_9606.ENSP00000340691'], ['cpi_9606.ENSP00000274353', 'cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000260356', 'cpi_9606.ENSP00000360493', 'cpi_9606.ENSP00000216962'], ['cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000378699', 'cpi_9606.ENSP00000312029', 'cpi_9606.ENSP00000346598', 'cpi_9606.ENSP00000267843'], ['cpi_9606.ENSP00000354612', 'cpi_9606.ENSP00000263923', 'cpi_9606.ENSP00000343040', 'cpi_9606.ENSP00000353292', 'cpi_9606.ENSP00000311028'], ['cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000226574', 'cpi_9606.ENSP00000427562', 'cpi_9606.ENSP00000251535', 'cpi_9606.ENSP00000370473'], ['cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000384273', 'cpi_9606.ENSP00000358784', 'cpi_9606.ENSP00000386069', 'cpi_9606.ENSP00000252519'], ['cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000258400', 'cpi_9606.ENSP00000410076', 'cpi_9606.ENSP00000320935', 'cpi_9606.ENSP00000359663'], ['cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000231228', 'cpi_9606.ENSP00000347979', 'cpi_9606.ENSP00000365016', 'cpi_9606.ENSP00000387281'], ['cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000338548', 'cpi_9606.ENSP00000407375', 'cpi_9606.ENSP00000264867', 'cpi_9606.ENSP00000176183'], ['cpi_9606.ENSP00000236850', 'cpi_9606.ENSP00000274026', 'cpi_9606.ENSP00000293288', 'cpi_9606.ENSP00000276198', 'cpi_9606.ENSP00000307014'], ['cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000354859', 'cpi_9606.ENSP00000267119'], ['cpi_9606.ENSP00000358963', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000323568', 'cpi_9606.ENSP00000344352', 'cpi_9606.ENSP00000254066'], ['cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000252029', 'cpi_9606.ENSP00000327652', 'cpi_9606.ENSP00000221515', 'cpi_9606.ENSP00000364802'], ['cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000254976', 'cpi_9606.ENSP00000300061', 'cpi_9606.ENSP00000307235', 'cpi_9606.ENSP00000463999'], ['cpi_9606.ENSP00000261205', 'cpi_9606.ENSP00000412237', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000372023', 'cpi_9606.ENSP00000295834'], ['cpi_9606.ENSP00000306512', 'cpi_9606.ENSP00000318912', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000365380'], ['cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000356729', 'cpi_9606.ENSP00000319591', 'cpi_9606.ENSP00000256958', 'cpi_9606.ENSP00000329623'], ['cpi_9606.ENSP00000373169', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000241261', 'cpi_9606.ENSP00000340820'], ['cpi_9606.ENSP00000327431', 'cpi_9606.ENSP00000237612', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000336630', 'cpi_9606.ENSP00000287766'], ['cpi_9606.ENSP00000215832', 'cpi_9606.ENSP00000370381', 'cpi_9606.ENSP00000341828', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000289753'], ['cpi_9606.ENSP00000306662', 'cpi_9606.ENSP00000353731', 'cpi_9606.ENSP00000232219', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000308774'], ['cpi_9606.ENSP00000302150', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000353878', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000276449'], ['cpi_9606.ENSP00000397582', 'cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000299178', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000352702'], ['cpi_9606.ENSP00000257497', 'cpi_9606.ENSP00000314508', 'cpi_9606.ENSP00000287936', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000278616'], ['cpi_9606.ENSP00000360683', 'cpi_9606.ENSP00000313661', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000297350'], ['cpi_9606.ENSP00000356022', 'cpi_9606.ENSP00000356671', 'cpi_9606.ENSP00000307766', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000360967'], ['cpi_9606.ENSP00000234111', 'cpi_9606.ENSP00000259486', 'cpi_9606.ENSP00000358511', 'cpi_9606.ENSP00000303174', 'cpi_9606.ENSP00000428924'], ['cpi_9606.ENSP00000264832', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000285979', 'cpi_9606.ENSP00000353915'], ['cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000262441', 'cpi_9606.ENSP00000236671', 'cpi_9606.ENSP00000318822', 'cpi_9606.ENSP00000365663'], ['cpi_9606.ENSP00000361405', 'cpi_9606.ENSP00000359910', 'cpi_9606.ENSP00000277120', 'cpi_9606.ENSP00000263980', 'cpi_9606.ENSP00000304811'], ['cpi_9606.ENSP00000304915', 'cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000369757', 'cpi_9606.ENSP00000367309', 'cpi_9606.ENSP00000454071'], ['cpi_9606.ENSP00000269305', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000292513', 'cpi_9606.ENSP00000248041'], ['cpi_9606.ENSP00000309845', 'cpi_9606.ENSP00000301146', 'cpi_9606.ENSP00000291294', 'cpi_9606.ENSP00000297268', 'cpi_9606.ENSP00000353427'], ['cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000312652', 'cpi_9606.ENSP00000262461', 'cpi_9606.ENSP00000388648', 'cpi_9606.ENSP00000341045'], ['cpi_9606.ENSP00000301974', 'cpi_9606.ENSP00000355759', 'cpi_9606.ENSP00000268053', 'cpi_9606.ENSP00000467676', 'cpi_9606.ENSP00000445340'], ['cpi_9606.ENSP00000263025', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000164139', 'cpi_9606.ENSP00000233146', 'cpi_9606.ENSP00000306129'], ['cpi_9606.ENSP00000303522', 'cpi_9606.ENSP00000321988', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000355657', 'cpi_9606.ENSP00000248553'], ['cpi_9606.ENSP00000252945', 'cpi_9606.ENSP00000298171', 'cpi_9606.ENSP00000352584', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000264657'], ['cpi_9606.ENSP00000394624', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000305302', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000359635'], ['cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000419782', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000354558'], ['cpi_9606.ENSP00000359899', 'cpi_9606.ENSP00000369050', 'cpi_9606.ENSP00000263464', 'cpi_9606.ENSP00000296122', 'cpi_9606.ENSP00000368104'], ['cpi_9606.ENSP00000302811', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000304845', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000302564'], ['cpi_9606.ENSP00000349467', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000360973', 'cpi_9606.ENSP00000354107', 'cpi_9606.ENSP00000393312'], ['cpi_9606.ENSP00000295598', 'cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000358327', 'cpi_9606.ENSP00000317379', 'cpi_9606.ENSP00000350767'], ['cpi_9606.ENSP00000387662', 'cpi_9606.ENSP00000311469', 'cpi_9606.ENSP00000386171', 'cpi_9606.ENSP00000254488', 'cpi_9606.ENSP00000270625'], ['cpi_9606.ENSP00000229447', 'cpi_9606.ENSP00000231449', 'cpi_9606.ENSP00000346067', 'cpi_9606.ENSP00000305221', 'cpi_9606.ENSP00000322924'], ['cpi_9606.ENSP00000216465', 'cpi_9606.ENSP00000304895', 'cpi_9606.ENSP00000287907', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000429374'], ['cpi_9606.ENSP00000272298', 'cpi_9606.ENSP00000309757', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000386229', 'cpi_9606.ENSP00000266682'], ['cpi_9606.ENSP00000282753', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000269571', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000231751'], ['cpi_9606.ENSP00000368305', 'cpi_9606.ENSP00000368683', 'cpi_9606.ENSP00000301141', 'cpi_9606.ENSP00000296674', 'cpi_9606.ENSP00000370254'], ['cpi_9606.ENSP00000353679', 'cpi_9606.ENSP00000275216', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000356694', 'cpi_9606.ENSP00000225964'], ['cpi_9606.ENSP00000331602', 'cpi_9606.ENSP00000239849', 'cpi_9606.ENSP00000211287', 'cpi_9606.ENSP00000382659', 'cpi_9606.ENSP00000396320'], ['cpi_9606.ENSP00000265572', 'cpi_9606.ENSP00000219700', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000356832'], ['cpi_9606.ENSP00000327801', 'cpi_9606.ENSP00000239938', 'cpi_9606.ENSP00000355317', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000264498'], ['cpi_9606.ENSP00000330032', 'cpi_9606.ENSP00000355920', 'cpi_9606.ENSP00000333534', 'cpi_9606.ENSP00000419692', 'cpi_9606.ENSP00000464149'], ['cpi_9606.ENSP00000375066', 'cpi_9606.ENSP00000288022', 'cpi_9606.ENSP00000368880', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000323549'], ['cpi_9606.ENSP00000369647', 'cpi_9606.ENSP00000282397', 'cpi_9606.ENSP00000275300', 'cpi_9606.ENSP00000256383', 'cpi_9606.ENSP00000225927'], ['cpi_9606.ENSP00000292896', 'cpi_9606.ENSP00000380252', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000226413', 'cpi_9606.ENSP00000351885'], ['cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000377192', 'cpi_9606.ENSP00000331358', 'cpi_9606.ENSP00000330199', 'cpi_9606.ENSP00000228872'], ['cpi_9606.ENSP00000287820', 'cpi_9606.ENSP00000320866', 'cpi_9606.ENSP00000326219', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000294954'], ['cpi_9606.ENSP00000380318', 'cpi_9606.ENSP00000265403', 'cpi_9606.ENSP00000358730', 'cpi_9606.ENSP00000244741', 'cpi_9606.ENSP00000346298'], ['cpi_9606.ENSP00000408695', 'cpi_9606.ENSP00000280357', 'cpi_9606.ENSP00000342560', 'cpi_9606.ENSP00000338627', 'cpi_9606.ENSP00000371554'], ['cpi_9606.ENSP00000219070', 'cpi_9606.ENSP00000398655', 'cpi_9606.ENSP00000338082', 'cpi_9606.ENSP00000308032', 'cpi_9606.ENSP00000333821'], ['cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000335657', 'cpi_9606.ENSP00000309103', 'cpi_9606.ENSP00000223366', 'cpi_9606.ENSP00000363827'], ['cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000379213', 'cpi_9606.ENSP00000349577', 'cpi_9606.ENSP00000264896', 'cpi_9606.ENSP00000362508'], ['cpi_9606.ENSP00000356825', 'cpi_9606.ENSP00000301633', 'cpi_9606.ENSP00000308549', 'cpi_9606.ENSP00000385806', 'cpi_9606.ENSP00000368632'], ['cpi_9606.ENSP00000315644', 'cpi_9606.ENSP00000242152', 'cpi_9606.ENSP00000253727', 'cpi_9606.ENSP00000262160', 'cpi_9606.ENSP00000320401'], ['cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000341189', 'cpi_9606.ENSP00000270474', 'cpi_9606.ENSP00000262735'], ['cpi_9606.ENSP00000373477', 'cpi_9606.ENSP00000303830', 'cpi_9606.ENSP00000217305', 'cpi_9606.ENSP00000265723', 'cpi_9606.ENSP00000215659'], ['cpi_9606.ENSP00000327251', 'cpi_9606.ENSP00000252321', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000349252', 'cpi_9606.ENSP00000348461'], ['cpi_9606.ENSP00000383365', 'cpi_9606.ENSP00000223095', 'cpi_9606.ENSP00000324248', 'cpi_9606.ENSP00000355778', 'cpi_9606.ENSP00000260970'], ['cpi_9606.ENSP00000264613', 'cpi_9606.ENSP00000400175', 'cpi_9606.ENSP00000321106', 'cpi_9606.ENSP00000332679', 'cpi_9606.ENSP00000225577'], ['cpi_9606.ENSP00000222553', 'cpi_9606.ENSP00000451030', 'cpi_9606.ENSP00000367207', 'cpi_9606.ENSP00000387683', 'cpi_9606.ENSP00000251453'], ['cpi_9606.ENSP00000340684', 'cpi_9606.ENSP00000260227', 'cpi_9606.ENSP00000353483', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000348645'], ['cpi_9606.ENSP00000337459', 'cpi_9606.ENSP00000394033', 'cpi_9606.ENSP00000362401', 'cpi_9606.ENSP00000219919', 'cpi_9606.ENSP00000218388'], ['cpi_9606.ENSP00000268035', 'cpi_9606.ENSP00000374265', 'cpi_9606.ENSP00000299766', 'cpi_9606.ENSP00000262367', 'cpi_9606.ENSP00000331736'], ['cpi_9606.ENSP00000217386', 'cpi_9606.ENSP00000306606', 'cpi_9606.ENSP00000324173', 'cpi_9606.ENSP00000360968', 'cpi_9606.ENSP00000332816'], ['cpi_9606.ENSP00000262407', 'cpi_9606.ENSP00000273430', 'cpi_9606.ENSP00000360991', 'cpi_9606.ENSP00000216341', 'cpi_9606.ENSP00000296522'], ['cpi_9606.ENSP00000359680', 'cpi_9606.ENSP00000360266', 'cpi_9606.ENSP00000303424', 'cpi_9606.ENSP00000334246', 'cpi_9606.ENSP00000252804'], ['cpi_9606.ENSP00000355536', 'cpi_9606.ENSP00000260630', 'cpi_9606.ENSP00000370129', 'cpi_9606.ENSP00000260649', 'cpi_9606.ENSP00000234961'], ['cpi_9606.ENSP00000306100', 'cpi_9606.ENSP00000381333', 'cpi_9606.ENSP00000321821', 'cpi_9606.ENSP00000318646', 'cpi_9606.ENSP00000320709'], ['cpi_9606.ENSP00000344460', 'cpi_9606.ENSP00000287641', 'cpi_9606.ENSP00000295400', 'cpi_9606.ENSP00000265164', 'cpi_9606.ENSP00000290866'], ['cpi_9606.ENSP00000434516', 'cpi_9606.ENSP00000386884', 'cpi_9606.ENSP00000288602', 'cpi_9606.ENSP0000035

🔄 Processing features: 100%|██████████| 1607/1607 [06:52<00:00,  3.90feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'cpi_9606.ENSP00000301634', 'cpi_9606.ENSP00000359793', 'cpi_9606.ENSP00000258749', 'cpi_9606.ENSP00000332296'], ['cpi_9606.ENSP00000231509', 'cpi_9606.ENSP00000327431', 'cpi_9606.ENSP00000356094', 'cpi_9606.ENSP00000395653', 'cpi_9606.ENSP00000323568'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000350348', 'cpi_9606.ENSP00000263464', 'cpi_9606.ENSP00000367848'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000261937'], ['cpi_9606.ENSP00000360372', 'cpi_9606.ENSP00000309818', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000261799'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000257290'], ['cpi_9606.ENSP00000237014', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000277010', 'cpi_9606.ENSP00000319788', 'cpi_9606.ENSP00000337335'], ['cpi_9606.ENSP00000264381', 'cpi_9606.ENSP00000355629', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000389338', 'cpi_9606.ENSP00000342235'], ['cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000266376', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000417229'], ['cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000263321', 'cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000274547', 'cpi_9606.ENSP00000358548'], ['cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000265294'], ['cpi_9606.ENSP00000265724', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000359353', 'cpi_9606.ENSP00000245539'], ['cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000360773', 'cpi_9606.ENSP00000354476'], ['cpi_9606.ENSP00000311032', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000445340'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000304822', 'cpi_9606.ENSP00000299267', 'cpi_9606.ENSP00000254227'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000283635', 'cpi_9606.ENSP00000279178'], ['cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000299178', 'cpi_9606.ENSP00000295491', 'cpi_9606.ENSP00000326119', 'cpi_9606.ENSP00000344192'], ['cpi_9606.ENSP00000272190', 'cpi_9606.ENSP00000301178', 'cpi_9606.ENSP00000275525', 'cpi_9606.ENSP00000295454', 'cpi_9606.ENSP00000333212'], ['cpi_9606.ENSP00000260433', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000362036', 'cpi_9606.ENSP00000430684', 'cpi_9606.ENSP00000347942'], ['cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000225474', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000309124'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000374323', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000260010'], ['cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000369960', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000221972'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000311469', 'cpi_9606.ENSP00000312664', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000334198'], ['cpi_9606.ENSP00000220764', 'cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000301891'], ['cpi_9606.ENSP00000305372', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000343040'], ['cpi_9606.ENSP00000295897', 'cpi_9606.ENSP00000378517', 'cpi_9606.ENSP00000307599', 'cpi_9606.ENSP00000242057', 'cpi_9606.ENSP00000335592'], ['cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000316786', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000387281'], ['cpi_9606.ENSP00000344456', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000320935'], ['cpi_9606.ENSP00000270349', 'cpi_9606.ENSP00000304915', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000414334', 'cpi_9606.ENSP00000412673'], ['cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000367851', 'cpi_9606.ENSP00000216037', 'cpi_9606.ENSP00000353292', 'cpi_9606.ENSP00000367102'], ['cpi_9606.ENSP00000363822', 'cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000381097', 'cpi_9606.ENSP00000261196'], ['cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000361666'], ['cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000260356', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000368766'], ['cpi_9606.ENSP00000270202', 'cpi_9606.ENSP00000331912', 'cpi_9606.ENSP00000394936', 'cpi_9606.ENSP00000353915', 'cpi_9606.ENSP00000366307'], ['cpi_9606.ENSP00000284981', 'cpi_9606.ENSP00000343477', 'cpi_9606.ENSP00000259396', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000470087'], ['cpi_9606.ENSP00000367959', 'cpi_9606.ENSP00000354610', 'cpi_9606.ENSP00000330393', 'cpi_9606.ENSP00000457706', 'cpi_9606.ENSP00000471569'], ['cpi_9606.ENSP00000366506', 'cpi_9606.ENSP00000233242', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000263980'], ['cpi_9606.ENSP00000368438', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000451040', 'cpi_9606.ENSP00000231454', 'cpi_9606.ENSP00000386029'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000340943', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000356954'], ['cpi_9606.ENSP00000270142', 'cpi_9606.ENSP00000294728', 'cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000267101', 'cpi_9606.ENSP00000352011'], ['cpi_9606.ENSP00000280155', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000255465', 'cpi_9606.ENSP00000296871', 'cpi_9606.ENSP00000386171'], ['cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000234111', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000312455', 'cpi_9606.ENSP00000256958'], ['cpi_9606.ENSP00000316244', 'cpi_9606.ENSP00000357204', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000376943'], ['cpi_9606.ENSP00000274353', 'cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000282561', 'cpi_9606.ENSP00000261693'], ['cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000264637', 'cpi_9606.ENSP00000226574'], ['cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000308165', 'cpi_9606.ENSP00000307014', 'cpi_9606.ENSP00000428340'], ['cpi_9606.ENSP00000308541', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000358963', 'cpi_9606.ENSP00000251535', 'cpi_9606.ENSP00000320025'], ['cpi_9606.ENSP00000411532', 'cpi_9606.ENSP00000355930', 'cpi_9606.ENSP00000286301', 'cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000370381'], ['cpi_9606.ENSP00000258743', 'cpi_9606.ENSP00000326219', 'cpi_9606.ENSP00000463999', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000263126'], ['cpi_9606.ENSP00000354859', 'cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000357283', 'cpi_9606.ENSP00000376432'], ['cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000313661', 'cpi_9606.ENSP00000389414'], ['cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000327652', 'cpi_9606.ENSP00000259089'], ['cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000233146'], ['cpi_9606.ENSP00000398698', 'cpi_9606.ENSP00000238379', 'cpi_9606.ENSP00000387946', 'cpi_9606.ENSP00000344352', 'cpi_9606.ENSP00000300061'], ['cpi_9606.ENSP00000386284', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000354394', 'cpi_9606.ENSP00000386229', 'cpi_9606.ENSP00000000442'], ['cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000264162', 'cpi_9606.ENSP00000385806', 'cpi_9606.ENSP00000293288', 'cpi_9606.ENSP00000410294'], ['cpi_9606.ENSP00000225831', 'cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000252809'], ['cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000356729', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000348069'], ['cpi_9606.ENSP00000356438', 'cpi_9606.ENSP00000328173', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000200676', 'cpi_9606.ENSP00000386069'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000384957', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000291294', 'cpi_9606.ENSP00000364802'], ['cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000358784'], ['cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000302811', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000302111', 'cpi_9606.ENSP00000352702'], ['cpi_9606.ENSP00000337450', 'cpi_9606.ENSP00000362810', 'cpi_9606.ENSP00000270625', 'cpi_9606.ENSP00000318822', 'cpi_9606.ENSP00000270776'], ['cpi_9606.ENSP00000252945', 'cpi_9606.ENSP00000298171', 'cpi_9606.ENSP00000312029', 'cpi_9606.ENSP00000388648', 'cpi_9606.ENSP00000371929'], ['cpi_9606.ENSP00000297494', 'cpi_9606.ENSP00000353791', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000346598', 'cpi_9606.ENSP00000361359'], ['cpi_9606.ENSP00000373169', 'cpi_9606.ENSP00000338548', 'cpi_9606.ENSP00000252486', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000331358'], ['cpi_9606.ENSP00000257497', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000347979', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000230671'], ['cpi_9606.ENSP00000306245', 'cpi_9606.ENSP00000225927', 'cpi_9606.ENSP00000332369', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000262461'], ['cpi_9606.ENSP00000237612', 'cpi_9606.ENSP00000369654', 'cpi_9606.ENSP00000220616', 'cpi_9606.ENSP00000360493', 'cpi_9606.ENSP00000276198'], ['cpi_9606.ENSP00000354612', 'cpi_9606.ENSP00000339527', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000365663', 'cpi_9606.ENSP00000393312'], ['cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000241261', 'cpi_9606.ENSP00000258400', 'cpi_9606.ENSP00000396320'], ['cpi_9606.ENSP00000330237', 'cpi_9606.ENSP00000397582', 'cpi_9606.ENSP00000222330', 'cpi_9606.ENSP00000306662', 'cpi_9606.ENSP00000267119'], ['cpi_9606.ENSP00000263025', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000216962', 'cpi_9606.ENSP00000289753', 'cpi_9606.ENSP00000297350'], ['cpi_9606.ENSP00000337949', 'cpi_9606.ENSP00000354850', 'cpi_9606.ENSP00000278616', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000394033'], ['cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000378699', 'cpi_9606.ENSP00000261465', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000262888'], ['cpi_9606.ENSP00000355759', 'cpi_9606.ENSP00000268053', 'cpi_9606.ENSP00000301974', 'cpi_9606.ENSP00000311028', 'cpi_9606.ENSP00000301645'], ['cpi_9606.ENSP00000306512', 'cpi_9606.ENSP00000318912', 'cpi_9606.ENSP00000306129', 'cpi_9606.ENSP00000360967', 'cpi_9606.ENSP00000340820'], ['cpi_9606.ENSP00000302150', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000365380', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000216797'], ['cpi_9606.ENSP00000269305', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000351209', 'cpi_9606.ENSP00000292513'], ['cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000303522', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000231228', 'cpi_9606.ENSP00000287766'], ['cpi_9606.ENSP00000387662', 'cpi_9606.ENSP00000341045', 'cpi_9606.ENSP00000398632', 'cpi_9606.ENSP00000467676', 'cpi_9606.ENSP00000254488'], ['cpi_9606.ENSP00000215832', 'cpi_9606.ENSP00000344674', 'cpi_9606.ENSP00000352035', 'cpi_9606.ENSP00000311095', 'cpi_9606.ENSP00000176183'], ['cpi_9606.ENSP00000264832', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000451030', 'cpi_9606.ENSP00000407375', 'cpi_9606.ENSP00000356825'], ['cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000370473', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000287907', 'cpi_9606.ENSP00000308774'], ['cpi_9606.ENSP00000356022', 'cpi_9606.ENSP00000307766', 'cpi_9606.ENSP00000428924', 'cpi_9606.ENSP00000287936', 'cpi_9606.ENSP00000270570'], ['cpi_9606.ENSP00000315644', 'cpi_9606.ENSP00000263341', 'cpi_9606.ENSP00000263923', 'cpi_9606.ENSP00000322924', 'cpi_9606.ENSP00000305302'], ['cpi_9606.ENSP00000309845', 'cpi_9606.ENSP00000448059', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000307235', 'cpi_9606.ENSP00000376178'], ['cpi_9606.ENSP00000296545', 'cpi_9606.ENSP00000254976', 'cpi_9606.ENSP00000265723', 'cpi_9606.ENSP00000354107', 'cpi_9606.ENSP00000356832'], ['cpi_9606.ENSP00000353731', 'cpi_9606.ENSP00000359899', 'cpi_9606.ENSP00000232219', 'cpi_9606.ENSP00000414303', 'cpi_9606.ENSP00000282397'], ['cpi_9606.ENSP00000368305', 'cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000234961', 'cpi_9606.ENSP00000266682'], ['cpi_9606.ENSP00000360683', 'cpi_9606.ENSP00000252723', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000264657'], ['cpi_9606.ENSP00000352835', 'cpi_9606.ENSP00000368683', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000296122', 'cpi_9606.ENSP00000263339'], ['cpi_9606.ENSP00000312652', 'cpi_9606.ENSP00000272847', 'cpi_9606.ENSP00000219919', 'cpi_9606.ENSP00000353878', 'cpi_9606.ENSP00000346298'], ['cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000288022', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000288135', 'cpi_9606.ENSP00000353427'], ['cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000212015', 'cpi_9606.ENSP00000330199', 'cpi_9606.ENSP00000332816', 'cpi_9606.ENSP00000303174'], ['cpi_9606.ENSP00000367309', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000380252', 'cpi_9606.ENSP00000351885', 'cpi_9606.ENSP00000295834'], ['cpi_9606.ENSP00000361405', 'cpi_9606.ENSP00000292896', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000338627', 'cpi_9606.ENSP00000329357'], ['cpi_9606.ENSP00000229319', 'cpi_9606.ENSP00000262735', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000336630', 'cpi_9606.ENSP00000285979'], ['cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000321988', 'cpi_9606.ENSP00000239849', 'cpi_9606.ENSP00000430432', 'cpi_9606.ENSP00000363089'], ['cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000381333', 'cpi_9606.ENSP00000263377', 'cpi_9606.ENSP00000358327'], ['cpi_9606.ENSP00000295598', 'cpi_9606.ENSP00000384273', 'cpi_9606.ENSP00000277120', 'cpi_9606.ENSP00000273430', 'cpi_9606.ENSP00000274026'], ['cpi_9606.ENSP00000217386', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000248553', 'cpi_9606.ENSP00000355657', 'cpi_9606.ENSP00000229264'], ['cpi_9606.ENSP00000011292', 'cpi_9606.ENSP00000362353', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000319591'], ['cpi_9606.ENSP00000408695', 'cpi_9606.ENSP00000410076', 'cpi_9606.ENSP00000259271', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000360973'], ['cpi_9606.ENSP00000375066', 'cpi_9606.ENSP00000359478', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000264896', 'cpi_9606.ENSP00000329623'], ['cpi_9606.ENSP00000412237', 'cpi_9606.ENSP00000216465', 'cpi_9606.ENSP00000296674', 'cpi_9606.ENSP00000267843', 'cpi_9606.ENSP00000274793'], ['cpi_9606.ENSP00000236850', 'cpi_9606.ENSP00000223366', 'cpi_9606.ENSP00000382659', 'cpi_9606.ENSP00000355317', 'cpi_9606.ENSP00000304811'], ['cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000372023', 'cpi_9606.ENSP00000359532', 'cpi_9606.ENSP00000226730'], ['cpi_9606.ENSP00000369647', 'cpi_9606.ENSP00000368752', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000356671', 'cpi_9606.ENSP00000346768'], ['cpi_9606.ENSP00000333994', 'cpi_9606.ENSP00000354558', 'cpi_9606.ENSP00000366416', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000364805'], ['cpi_9606.ENSP00000268035', 'cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000333194', 'cpi_9606.ENSP00000346067', 'cpi_9606.ENSP00000305221'], ['cpi_9606.ENSP00000369050', 'cpi_9606.ENSP00000303452', 'cpi_9606.ENSP00000252029', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000264867'], ['cpi_9606.ENSP00000265023', 'cpi_9606.ENSP00000314508', 'cpi_9606.ENSP00000239938', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000310928'], ['cpi_9606.ENSP00000464149', 'cpi_9606.ENSP00000228872', 'cpi_9606.ENSP00000217305', 'cpi_9606.ENSP00000343204', 'cpi_9606.ENSP00000427514'], ['cpi_9606.ENSP00000330032', 'cpi_9606.ENSP00000276449', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000262948', 'cpi_9606.ENSP00000290866'], ['cpi_9606.ENSP00000219070', 'cpi_9606.ENSP00000340684', 'cpi_9606.ENSP00000333496', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000270474'], ['cpi_9606.ENSP00000327251', 'cpi_9606.ENSP00000427562', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000359635'], ['cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000231449', 'cpi_9606.ENSP00000454071', 'cpi_9606.ENSP00000262367', 'cpi_9606.ENSP00000176763'], ['cpi_9606.ENSP00000262407', 'cpi_9606.ENSP00000321106', 'cpi_9606.ENSP00000338018', 'cpi_9606.ENSP00000419692', 'cpi_9606.ENSP00000320401'], ['cpi_9606.ENSP00000222553', 'cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000309103', 'cpi_9606.ENSP00000393333', 'cpi_9606.ENSP00000304845'], ['cpi_9606.ENSP00000342952', 'cpi_9606.ENSP00000304895', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000352584'], ['cpi_9606.ENSP00000349467', 'cpi_9606.ENSP00000387683', 'cpi_9606.ENSP00000302846', 'cpi_9606.ENSP00000309757', 'cpi_9606.ENSP00000276431'], ['cpi_9606.ENSP00000306100', 'cpi_9606.ENSP00000379213', 'cpi_9606.ENSP00000252321', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000320709'], ['cpi_9606.ENSP00000353679', 'cpi_9606.ENSP00000321999', 'cpi_9606.ENSP00000365016', 'cpi_9606.ENSP00000301146', 'cpi_9606.ENSP00000459962'], ['cpi_9606.ENSP00000319170', 'cpi_9606.ENSP00000360266', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000358730', 'cpi_9606.ENSP00000362513'], ['cpi_9606.ENSP00000264613', 'cpi_9606.ENSP00000264498', 'cpi_9606.ENSP00000400175', 'cpi_9606.ENSP00000355920', 'cpi_9606.ENSP00000354569'], ['cpi_9606.ENSP00000265572', 'cpi_9606.ENSP00000219700', 'cpi_9606.ENSP00000341189', 'cpi_9606.ENSP00000351908', 'cpi_9606.ENSP00000275300'], ['cpi_9606.ENSP00000337459', 'cpi_9606.ENSP00000362344', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000342560', 'cpi_9606.ENSP00000370129'], ['cpi_9606.ENSP00000324270', 'cpi_9606.ENSP00000234389', 'cpi_9606.ENSP00000324173', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000352561'], ['cpi_9606.ENSP00000380318', 'cpi_9606.ENSP00000265403', 'cpi_9606.ENSP00000244741', 'cpi_9606.ENSP00000308549', 'cpi_9606.ENSP00000221515'], ['cpi_9606.ENSP00000352608', 'cpi_9606.ENSP00000371554', 'cpi_9606.ENSP00000315011', 'cpi_9606.ENSP00000362508', 'cpi_9606.ENSP00000256383'], ['cpi_9606.ENSP00000216117', 'cpi_9606.ENSP00000256010', 'cpi_9606.ENSP00000379339', 'cpi_9606.ENSP00000387888', 'cpi_9606.ENSP00000358223'], ['cpi_9606.ENSP00000364035', 'cpi_9606.ENSP00000221930', 'cpi_9606.ENSP00000287641', 'cpi_9606.ENSP00000285379', 'cpi_9606.ENSP00000294954'], ['cpi_9606.ENSP00000420194', 'cpi_9606.ENSP00000306606', 'cpi_9606.ENSP00000331736', 'cpi_9606.ENSP00000252804', 'cpi_9606.ENSP00000260970'], ['cpi_9606.ENSP00000287820', 'cpi_9606.ENSP00000262623', 'cpi_9606.ENSP00000267377', 'cpi_9606.ENSP00000355778', 'cpi_9606.ENSP00000363832'], ['cpi_9606.ENSP00000261267', 'cpi_9606.ENSP00000297469', 'cpi_9606.ENSP00000348645', 'cpi_9606.ENSP00000290349', 'cpi_9606.ENSP00000253727'], ['cpi_9606.ENSP00000434516', 'cpi_9606.ENSP00000223095', 'cpi_9606.ENSP00000320180', 'cpi_9606.ENSP00000333534', 'cpi_9606.ENSP00000368632'], ['cpi_9606.ENSP00000373477', 'cpi_9606.ENSP00000303830', 'cpi_9606.ENSP00000358511', 'cpi_9606.ENSP00000225371', 'cpi_9606.ENSP00000225964'], ['cpi_9606.ENSP00000263088', 'cpi_9606.ENSP00000293272', 'cpi_9606.ENSP00000356694', 'cpi_9606.ENSP00000254810', 'cpi_9606.ENSP00000251566'], ['cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000306138', 'cpi_9606.ENSP00000295453', 'cpi_9606.ENSP00000337773', 'cpi_9606.ENSP00000368880'], ['cpi_9606.ENSP00000005178', 'cpi_9606.ENSP00000242152', 'cpi_9606.ENSP00000368104', 'cpi_9606.ENSP0000030

🔄 Processing features: 100%|██████████| 1607/1607 [06:51<00:00,  3.90feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'cpi_9606.ENSP00000326219', 'cpi_9606.ENSP00000359793', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000359424'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000356094', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000367848'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000382659', 'cpi_9606.ENSP00000414334', 'cpi_9606.ENSP00000178638'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000355629', 'cpi_9606.ENSP00000259089'], ['cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000301891', 'cpi_9606.ENSP00000395653', 'cpi_9606.ENSP00000220616'], ['cpi_9606.ENSP00000360372', 'cpi_9606.ENSP00000309818', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000347942', 'cpi_9606.ENSP00000312664'], ['cpi_9606.ENSP00000237014', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000277010', 'cpi_9606.ENSP00000337335', 'cpi_9606.ENSP00000358548'], ['cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000263321', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000261937'], ['cpi_9606.ENSP00000311032', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000359353', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000357068'], ['cpi_9606.ENSP00000264381', 'cpi_9606.ENSP00000389338', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000342235', 'cpi_9606.ENSP00000279178'], ['cpi_9606.ENSP00000231509', 'cpi_9606.ENSP00000266376', 'cpi_9606.ENSP00000332369', 'cpi_9606.ENSP00000251535', 'cpi_9606.ENSP00000323568'], ['cpi_9606.ENSP00000369960', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000295491'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000261799', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000332296'], ['cpi_9606.ENSP00000265724', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000301974', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000360773'], ['cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000370381', 'cpi_9606.ENSP00000257290'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000319170', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000394936', 'cpi_9606.ENSP00000430684'], ['cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000354476', 'cpi_9606.ENSP00000359334'], ['cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000282753', 'cpi_9606.ENSP00000445340', 'cpi_9606.ENSP00000344192', 'cpi_9606.ENSP00000326119'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000374323', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000255409'], ['cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000320935', 'cpi_9606.ENSP00000417229'], ['cpi_9606.ENSP00000363822', 'cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000274547', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000346534'], ['cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000225474', 'cpi_9606.ENSP00000319788', 'cpi_9606.ENSP00000288139'], ['cpi_9606.ENSP00000367959', 'cpi_9606.ENSP00000301634', 'cpi_9606.ENSP00000242057', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000264318'], ['cpi_9606.ENSP00000344456', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000299267', 'cpi_9606.ENSP00000348069'], ['cpi_9606.ENSP00000260433', 'cpi_9606.ENSP00000382250', 'cpi_9606.ENSP00000471569', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000274793'], ['cpi_9606.ENSP00000316786', 'cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000260010', 'cpi_9606.ENSP00000295454'], ['cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000233242', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000367102'], ['cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000252809', 'cpi_9606.ENSP00000386306'], ['cpi_9606.ENSP00000272190', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000275525', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000343477'], ['cpi_9606.ENSP00000284981', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000470087', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000344352'], ['cpi_9606.ENSP00000220764', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000368766', 'cpi_9606.ENSP00000307599'], ['cpi_9606.ENSP00000411532', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000308165', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000283254'], ['cpi_9606.ENSP00000398698', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000216037'], ['cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000359478', 'cpi_9606.ENSP00000221972', 'cpi_9606.ENSP00000362649', 'cpi_9606.ENSP00000386029'], ['cpi_9606.ENSP00000270142', 'cpi_9606.ENSP00000361666', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000331912', 'cpi_9606.ENSP00000352011'], ['cpi_9606.ENSP00000270202', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000258749', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000353292'], ['cpi_9606.ENSP00000295897', 'cpi_9606.ENSP00000378517', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000259396'], ['cpi_9606.ENSP00000305372', 'cpi_9606.ENSP00000356729', 'cpi_9606.ENSP00000301178', 'cpi_9606.ENSP00000264637', 'cpi_9606.ENSP00000361206'], ['cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000274353', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000339527', 'cpi_9606.ENSP00000276198'], ['cpi_9606.ENSP00000308541', 'cpi_9606.ENSP00000365380', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000451040', 'cpi_9606.ENSP00000376943'], ['cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000309124'], ['cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000387946', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000308774'], ['cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000386284', 'cpi_9606.ENSP00000278616', 'cpi_9606.ENSP00000286301', 'cpi_9606.ENSP00000263126'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000262441', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000351209', 'cpi_9606.ENSP00000354394'], ['cpi_9606.ENSP00000350348', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000356954', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000267101'], ['cpi_9606.ENSP00000352835', 'cpi_9606.ENSP00000264657', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000261196'], ['cpi_9606.ENSP00000270349', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000312455', 'cpi_9606.ENSP00000381097', 'cpi_9606.ENSP00000303540'], ['cpi_9606.ENSP00000337949', 'cpi_9606.ENSP00000264162', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000304822', 'cpi_9606.ENSP00000360493'], ['cpi_9606.ENSP00000297494', 'cpi_9606.ENSP00000353791', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000216962', 'cpi_9606.ENSP00000222330'], ['cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000355759', 'cpi_9606.ENSP00000362036', 'cpi_9606.ENSP00000343040', 'cpi_9606.ENSP00000333212'], ['cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000398632', 'cpi_9606.ENSP00000330393', 'cpi_9606.ENSP00000280155', 'cpi_9606.ENSP00000343204'], ['cpi_9606.ENSP00000258743', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000297350'], ['cpi_9606.ENSP00000234111', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000289753', 'cpi_9606.ENSP00000347979', 'cpi_9606.ENSP00000283635'], ['cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000366506', 'cpi_9606.ENSP00000361359', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000352702'], ['cpi_9606.ENSP00000368438', 'cpi_9606.ENSP00000355930', 'cpi_9606.ENSP00000261693', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000296871'], ['cpi_9606.ENSP00000316244', 'cpi_9606.ENSP00000338548', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000368880', 'cpi_9606.ENSP00000262461'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000254810', 'cpi_9606.ENSP00000351885', 'cpi_9606.ENSP00000231454'], ['cpi_9606.ENSP00000354859', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000329357', 'cpi_9606.ENSP00000428340', 'cpi_9606.ENSP00000256958'], ['cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000296545', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000356436'], ['cpi_9606.ENSP00000387281', 'cpi_9606.ENSP00000268053', 'cpi_9606.ENSP00000302111', 'cpi_9606.ENSP00000428924', 'cpi_9606.ENSP00000200676'], ['cpi_9606.ENSP00000236850', 'cpi_9606.ENSP00000233146', 'cpi_9606.ENSP00000389414', 'cpi_9606.ENSP00000312029', 'cpi_9606.ENSP00000358963'], ['cpi_9606.ENSP00000337450', 'cpi_9606.ENSP00000340943', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000367851'], ['cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000354850', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000410294', 'cpi_9606.ENSP00000252945'], ['cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000357283'], ['cpi_9606.ENSP00000309845', 'cpi_9606.ENSP00000367309', 'cpi_9606.ENSP00000282561', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000349577'], ['cpi_9606.ENSP00000330237', 'cpi_9606.ENSP00000397582', 'cpi_9606.ENSP00000306662', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000311095'], ['cpi_9606.ENSP00000354612', 'cpi_9606.ENSP00000287907', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000353878', 'cpi_9606.ENSP00000402152'], ['cpi_9606.ENSP00000386069', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000228872', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000362401'], ['cpi_9606.ENSP00000306245', 'cpi_9606.ENSP00000305692', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000457706', 'cpi_9606.ENSP00000463999'], ['cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000381333', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000176763', 'cpi_9606.ENSP00000364802'], ['cpi_9606.ENSP00000215832', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000267119', 'cpi_9606.ENSP00000448059', 'cpi_9606.ENSP00000294728'], ['cpi_9606.ENSP00000356438', 'cpi_9606.ENSP00000262888', 'cpi_9606.ENSP00000307014', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000309572'], ['cpi_9606.ENSP00000258400', 'cpi_9606.ENSP00000315644', 'cpi_9606.ENSP00000253727', 'cpi_9606.ENSP00000300061', 'cpi_9606.ENSP00000307235'], ['cpi_9606.ENSP00000361405', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000216341', 'cpi_9606.ENSP00000360967'], ['cpi_9606.ENSP00000306512', 'cpi_9606.ENSP00000318912', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000365016', 'cpi_9606.ENSP00000459962'], ['cpi_9606.ENSP00000225831', 'cpi_9606.ENSP00000344674', 'cpi_9606.ENSP00000310447', 'cpi_9606.ENSP00000293288', 'cpi_9606.ENSP00000299178'], ['cpi_9606.ENSP00000257497', 'cpi_9606.ENSP00000357204', 'cpi_9606.ENSP00000263923', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000266682'], ['cpi_9606.ENSP00000302811', 'cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000255465', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000388648'], ['cpi_9606.ENSP00000263025', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000270776', 'cpi_9606.ENSP00000354569'], ['cpi_9606.ENSP00000387662', 'cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000282397', 'cpi_9606.ENSP00000253122'], ['cpi_9606.ENSP00000302150', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000355657', 'cpi_9606.ENSP00000292513', 'cpi_9606.ENSP00000226574'], ['cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000248553', 'cpi_9606.ENSP00000340820', 'cpi_9606.ENSP00000305302', 'cpi_9606.ENSP00000351908'], ['cpi_9606.ENSP00000237612', 'cpi_9606.ENSP00000327431', 'cpi_9606.ENSP00000355317', 'cpi_9606.ENSP00000355778', 'cpi_9606.ENSP00000218099'], ['cpi_9606.ENSP00000298171', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000318822', 'cpi_9606.ENSP00000386171', 'cpi_9606.ENSP00000252486'], ['cpi_9606.ENSP00000264832', 'cpi_9606.ENSP00000405573', 'cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000288135', 'cpi_9606.ENSP00000252723'], ['cpi_9606.ENSP00000269305', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000353915', 'cpi_9606.ENSP00000254488'], ['cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000372023', 'cpi_9606.ENSP00000430432', 'cpi_9606.ENSP00000327652'], ['cpi_9606.ENSP00000312652', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000354107', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000359635'], ['cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000362353', 'cpi_9606.ENSP00000387888', 'cpi_9606.ENSP00000353427', 'cpi_9606.ENSP00000330199'], ['cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000288022', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000368632'], ['cpi_9606.ENSP00000222553', 'cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000256010', 'cpi_9606.ENSP00000346298', 'cpi_9606.ENSP00000345659'], ['cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000260356', 'cpi_9606.ENSP00000346598', 'cpi_9606.ENSP00000354558', 'cpi_9606.ENSP00000234371'], ['cpi_9606.ENSP00000378699', 'cpi_9606.ENSP00000464149', 'cpi_9606.ENSP00000267843', 'cpi_9606.ENSP00000262367', 'cpi_9606.ENSP00000331358'], ['cpi_9606.ENSP00000304915', 'cpi_9606.ENSP00000414303', 'cpi_9606.ENSP00000349576', 'cpi_9606.ENSP00000221515', 'cpi_9606.ENSP00000295834'], ['cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000263341', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000373169', 'cpi_9606.ENSP00000262948'], ['cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000252029', 'cpi_9606.ENSP00000306129', 'cpi_9606.ENSP00000264867', 'cpi_9606.ENSP00000308845'], ['cpi_9606.ENSP00000290866', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000380252', 'cpi_9606.ENSP00000309493', 'cpi_9606.ENSP00000427562'], ['cpi_9606.ENSP00000360683', 'cpi_9606.ENSP00000176183', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000287936', 'cpi_9606.ENSP00000231228'], ['cpi_9606.ENSP00000287820', 'cpi_9606.ENSP00000359910', 'cpi_9606.ENSP00000365663', 'cpi_9606.ENSP00000307766', 'cpi_9606.ENSP00000398655'], ['cpi_9606.ENSP00000353679', 'cpi_9606.ENSP00000275216', 'cpi_9606.ENSP00000384273', 'cpi_9606.ENSP00000338627', 'cpi_9606.ENSP00000276449'], ['cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000377192', 'cpi_9606.ENSP00000368683', 'cpi_9606.ENSP00000303174', 'cpi_9606.ENSP00000270474'], ['cpi_9606.ENSP00000321988', 'cpi_9606.ENSP00000362810', 'cpi_9606.ENSP00000358784', 'cpi_9606.ENSP00000427514', 'cpi_9606.ENSP00000400175'], ['cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000341828', 'cpi_9606.ENSP00000241261', 'cpi_9606.ENSP00000366307'], ['cpi_9606.ENSP00000303522', 'cpi_9606.ENSP00000353731', 'cpi_9606.ENSP00000232219', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000280357'], ['cpi_9606.ENSP00000358327', 'cpi_9606.ENSP00000354610', 'cpi_9606.ENSP00000226413', 'cpi_9606.ENSP00000300151', 'cpi_9606.ENSP00000370473'], ['cpi_9606.ENSP00000229319', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000321106', 'cpi_9606.ENSP00000338018', 'cpi_9606.ENSP00000419692'], ['cpi_9606.ENSP00000394624', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000310928', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000263980'], ['cpi_9606.ENSP00000254976', 'cpi_9606.ENSP00000275300', 'cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000319814', 'cpi_9606.ENSP00000290349'], ['cpi_9606.ENSP00000219070', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000311028', 'cpi_9606.ENSP00000341045', 'cpi_9606.ENSP00000313661'], ['cpi_9606.ENSP00000229447', 'cpi_9606.ENSP00000231449', 'cpi_9606.ENSP00000298283', 'cpi_9606.ENSP00000335544', 'cpi_9606.ENSP00000329623'], ['cpi_9606.ENSP00000368305', 'cpi_9606.ENSP00000262735', 'cpi_9606.ENSP00000322924', 'cpi_9606.ENSP00000225964', 'cpi_9606.ENSP00000393312'], ['cpi_9606.ENSP00000356022', 'cpi_9606.ENSP00000296122', 'cpi_9606.ENSP00000359532', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000346768'], ['cpi_9606.ENSP00000327251', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000292896', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000309103'], ['cpi_9606.ENSP00000408695', 'cpi_9606.ENSP00000211287', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000358730', 'cpi_9606.ENSP00000467676'], ['cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000309757', 'cpi_9606.ENSP00000302846', 'cpi_9606.ENSP00000285979', 'cpi_9606.ENSP00000364805'], ['cpi_9606.ENSP00000375066', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000304895', 'cpi_9606.ENSP00000357981', 'cpi_9606.ENSP00000311469'], ['cpi_9606.ENSP00000340684', 'cpi_9606.ENSP00000260227', 'cpi_9606.ENSP00000410076', 'cpi_9606.ENSP00000356694', 'cpi_9606.ENSP00000366084'], ['cpi_9606.ENSP00000359899', 'cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000360968', 'cpi_9606.ENSP00000370912', 'cpi_9606.ENSP00000356825'], ['cpi_9606.ENSP00000264613', 'cpi_9606.ENSP00000393333', 'cpi_9606.ENSP00000269571', 'cpi_9606.ENSP00000259271', 'cpi_9606.ENSP00000369050'], ['cpi_9606.ENSP00000327801', 'cpi_9606.ENSP00000412237', 'cpi_9606.ENSP00000256383', 'cpi_9606.ENSP00000303686', 'cpi_9606.ENSP00000305221'], ['cpi_9606.ENSP00000265572', 'cpi_9606.ENSP00000348645', 'cpi_9606.ENSP00000418960', 'cpi_9606.ENSP00000328173', 'cpi_9606.ENSP00000368104'], ['cpi_9606.ENSP00000370571', 'cpi_9606.ENSP00000256078', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000346901', 'cpi_9606.ENSP00000341885'], ['cpi_9606.ENSP00000257068', 'cpi_9606.ENSP00000306606', 'cpi_9606.ENSP00000385806', 'cpi_9606.ENSP00000358022', 'cpi_9606.ENSP00000418532'], ['cpi_9606.ENSP00000434516', 'cpi_9606.ENSP00000223095', 'cpi_9606.ENSP00000260970', 'cpi_9606.ENSP00000303452', 'cpi_9606.ENSP00000265164'], ['cpi_9606.ENSP00000261465', 'cpi_9606.ENSP00000320866', 'cpi_9606.ENSP00000239938', 'cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000270625'], ['cpi_9606.ENSP00000337459', 'cpi_9606.ENSP00000384957', 'cpi_9606.ENSP00000288602', 'cpi_9606.ENSP00000236671', 'cpi_9606.ENSP00000307445'], ['cpi_9606.ENSP00000369647', 'cpi_9606.ENSP00000366927', 'cpi_9606.ENSP00000268035', 'cpi_9606.ENSP00000356832', 'cpi_9606.ENSP00000343838'], ['cpi_9606.ENSP00000380318', 'cpi_9606.ENSP00000301146', 'cpi_9606.ENSP00000241256', 'cpi_9606.ENSP00000244741', 'cpi_9606.ENSP00000359539'], ['cpi_9606.ENSP00000352608', 'cpi_9606.ENSP00000355920', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000252321', 'cpi_9606.ENSP00000265023'], ['cpi_9606.ENSP00000226578', 'cpi_9606.ENSP00000276414', 'cpi_9606.ENSP00000301633', 'cpi_9606.ENSP00000304845', 'cpi_9606.ENSP00000239849'], ['cpi_9606.ENSP00000261267', 'cpi_9606.ENSP00000276571', 'cpi_9606.ENSP00000321821', 'cpi_9606.ENSP00000296522', 'cpi_9606.ENSP00000356671'], ['cpi_9606.ENSP00000358525', 'cpi_9606.ENSP00000315011', 'cpi_9606.ENSP00000360991', 'cpi_9606.ENSP00000251453', 'cpi_9606.ENSP00000352584'], ['cpi_9606.ENSP00000295598', 'cpi_9606.ENSP00000360266', 'cpi_9606.ENSP00000218721', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000211122'], ['cpi_9606.ENSP00000307697', 'cpi_9606.ENSP00000324270', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000435777', 'cpi_9606.ENSP00000216117'], ['cpi_9606.ENSP00000333994', 'cpi_9606.ENSP00000335657', 'cpi_9606.ENSP00000359998', 'cpi_9606.ENSP00000367207', 'cpi_9606.ENSP00000314949'], ['cpi_9606.ENSP00000260302', 'cpi_9606.ENSP00000291294', 'cpi_9606.ENSP00000308032', 'cpi_9606.ENSP00000246337', 'cpi_9606.ENSP00000371985'], ['cpi_9606.ENSP00000369654', 'cpi_9606.ENSP00000225577', 'cpi_9606.ENSP00000282018', 'cpi_9606.ENSP00000225371', 'cpi_9606.ENSP00000314649'], ['cpi_9606.ENSP00000342952', 'cpi_9606.ENSP00000341189', 'cpi_9606.ENSP00000356150', 'cpi_9606.ENSP00000454071', 'cpi_9606.ENSP00000362525'], ['cpi_9606.ENSP00000354511', 'cpi_9606.ENSP00000265723', 'cpi_9606.ENSP00000258042', 'cpi_9606.ENSP00000420168', 'cpi_9606.ENSP00000332816'], ['cpi_9606.ENSP00000217386', 'cpi_9606.ENSP00000372326', 'cpi_9606.ENSP00000164139', 'cpi_9606.ENSP00000407375', 'cpi_9606.ENSP00000394033'], ['cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000248076', 'cpi_9606.ENSP00000362508', 'cpi_9606.ENSP0000043

🔄 Processing features: 100%|██████████| 1607/1607 [06:51<00:00,  3.90feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'cpi_9606.ENSP00000253004', 'cpi_9606.ENSP00000395653', 'cpi_9606.ENSP00000356094', 'cpi_9606.ENSP00000312455'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000261799', 'cpi_9606.ENSP00000430684'], ['cpi_9606.ENSP00000360372', 'cpi_9606.ENSP00000309818', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000355629', 'cpi_9606.ENSP00000312664'], ['cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000372547'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000382659', 'cpi_9606.ENSP00000337335'], ['cpi_9606.ENSP00000231509', 'cpi_9606.ENSP00000266376', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000417229'], ['cpi_9606.ENSP00000237014', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000277010', 'cpi_9606.ENSP00000358548'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000367848', 'cpi_9606.ENSP00000374323', 'cpi_9606.ENSP00000359424'], ['cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000316786', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000360773'], ['cpi_9606.ENSP00000264381', 'cpi_9606.ENSP00000319788', 'cpi_9606.ENSP00000342235', 'cpi_9606.ENSP00000326119', 'cpi_9606.ENSP00000332296'], ['cpi_9606.ENSP00000265724', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000304822', 'cpi_9606.ENSP00000299178', 'cpi_9606.ENSP00000265294'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000264318'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000359353', 'cpi_9606.ENSP00000257290', 'cpi_9606.ENSP00000370381'], ['cpi_9606.ENSP00000263321', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000295491'], ['cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000414334', 'cpi_9606.ENSP00000354476'], ['cpi_9606.ENSP00000272190', 'cpi_9606.ENSP00000275525', 'cpi_9606.ENSP00000301178', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000343477'], ['cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000357204', 'cpi_9606.ENSP00000367102', 'cpi_9606.ENSP00000261937', 'cpi_9606.ENSP00000457706'], ['cpi_9606.ENSP00000369960', 'cpi_9606.ENSP00000301634', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000252486', 'cpi_9606.ENSP00000301891'], ['cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000349320'], ['cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000282753', 'cpi_9606.ENSP00000376943', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000359334'], ['cpi_9606.ENSP00000311032', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000344674', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000295454'], ['cpi_9606.ENSP00000260433', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000347942', 'cpi_9606.ENSP00000274547'], ['cpi_9606.ENSP00000363822', 'cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000381097'], ['cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000327431', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000355317'], ['cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000225474', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000353915', 'cpi_9606.ENSP00000242057'], ['cpi_9606.ENSP00000270349', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000262367', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000346534'], ['cpi_9606.ENSP00000305372', 'cpi_9606.ENSP00000233242', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000283635'], ['cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000220764', 'cpi_9606.ENSP00000279178', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000412673'], ['cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000254976', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000302111'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000311165', 'cpi_9606.ENSP00000216037', 'cpi_9606.ENSP00000307599', 'cpi_9606.ENSP00000352900'], ['cpi_9606.ENSP00000352835', 'cpi_9606.ENSP00000330237', 'cpi_9606.ENSP00000394936', 'cpi_9606.ENSP00000451040', 'cpi_9606.ENSP00000471569'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000389338', 'cpi_9606.ENSP00000351209'], ['cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000427514', 'cpi_9606.ENSP00000267101', 'cpi_9606.ENSP00000220616'], ['cpi_9606.ENSP00000337450', 'cpi_9606.ENSP00000340943', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000428340', 'cpi_9606.ENSP00000221972'], ['cpi_9606.ENSP00000284981', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000344352'], ['cpi_9606.ENSP00000368438', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000294728', 'cpi_9606.ENSP00000299267', 'cpi_9606.ENSP00000259089'], ['cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000248553', 'cpi_9606.ENSP00000164139'], ['cpi_9606.ENSP00000270142', 'cpi_9606.ENSP00000361666', 'cpi_9606.ENSP00000348069', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000286301'], ['cpi_9606.ENSP00000270202', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000262888', 'cpi_9606.ENSP00000387946', 'cpi_9606.ENSP00000258749'], ['cpi_9606.ENSP00000297494', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000470087'], ['cpi_9606.ENSP00000350348', 'cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000389414'], ['cpi_9606.ENSP00000344456', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000320935', 'cpi_9606.ENSP00000328968'], ['cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000263341', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000331912'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000263126', 'cpi_9606.ENSP00000298171'], ['cpi_9606.ENSP00000308541', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000222330', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000270570'], ['cpi_9606.ENSP00000367959', 'cpi_9606.ENSP00000354610', 'cpi_9606.ENSP00000329357', 'cpi_9606.ENSP00000309124', 'cpi_9606.ENSP00000320025'], ['cpi_9606.ENSP00000398698', 'cpi_9606.ENSP00000352608', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000227758'], ['cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000260356', 'cpi_9606.ENSP00000362036', 'cpi_9606.ENSP00000263923'], ['cpi_9606.ENSP00000366506', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000378517', 'cpi_9606.ENSP00000261693'], ['cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000398632', 'cpi_9606.ENSP00000268053', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000308774'], ['cpi_9606.ENSP00000411532', 'cpi_9606.ENSP00000344192', 'cpi_9606.ENSP00000355930', 'cpi_9606.ENSP00000259396', 'cpi_9606.ENSP00000365663'], ['cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000356954', 'cpi_9606.ENSP00000354558', 'cpi_9606.ENSP00000296871'], ['cpi_9606.ENSP00000337949', 'cpi_9606.ENSP00000264162', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000267119', 'cpi_9606.ENSP00000255030'], ['cpi_9606.ENSP00000316244', 'cpi_9606.ENSP00000359478', 'cpi_9606.ENSP00000367851', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000307014'], ['cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000308165', 'cpi_9606.ENSP00000346598'], ['cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000200676'], ['cpi_9606.ENSP00000258743', 'cpi_9606.ENSP00000295731', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000343040'], ['cpi_9606.ENSP00000257497', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000251535', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000333212'], ['cpi_9606.ENSP00000295897', 'cpi_9606.ENSP00000226574', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000376432'], ['cpi_9606.ENSP00000354612', 'cpi_9606.ENSP00000339527', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000288602'], ['cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000236850', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000262461', 'cpi_9606.ENSP00000354859'], ['cpi_9606.ENSP00000356438', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000420168', 'cpi_9606.ENSP00000264637', 'cpi_9606.ENSP00000353292'], ['cpi_9606.ENSP00000280155', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000263339'], ['cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000378699', 'cpi_9606.ENSP00000349252', 'cpi_9606.ENSP00000360493', 'cpi_9606.ENSP00000323568'], ['cpi_9606.ENSP00000387662', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000353878', 'cpi_9606.ENSP00000256958'], ['cpi_9606.ENSP00000237612', 'cpi_9606.ENSP00000441691', 'cpi_9606.ENSP00000274793', 'cpi_9606.ENSP00000276198', 'cpi_9606.ENSP00000467676'], ['cpi_9606.ENSP00000225831', 'cpi_9606.ENSP00000364802', 'cpi_9606.ENSP00000410294', 'cpi_9606.ENSP00000387281', 'cpi_9606.ENSP00000347979'], ['cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000361359', 'cpi_9606.ENSP00000307766', 'cpi_9606.ENSP00000252809'], ['cpi_9606.ENSP00000368766', 'cpi_9606.ENSP00000386284', 'cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000260010', 'cpi_9606.ENSP00000363827'], ['cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000356729', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000296674'], ['cpi_9606.ENSP00000234111', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000295834', 'cpi_9606.ENSP00000308549', 'cpi_9606.ENSP00000380252'], ['cpi_9606.ENSP00000274353', 'cpi_9606.ENSP00000264832', 'cpi_9606.ENSP00000295400', 'cpi_9606.ENSP00000289753', 'cpi_9606.ENSP00000261835'], ['cpi_9606.ENSP00000306245', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000356150', 'cpi_9606.ENSP00000293288', 'cpi_9606.ENSP00000230671'], ['cpi_9606.ENSP00000405573', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000373169', 'cpi_9606.ENSP00000270625', 'cpi_9606.ENSP00000297350'], ['cpi_9606.ENSP00000358963', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000318822', 'cpi_9606.ENSP00000282561', 'cpi_9606.ENSP00000309649'], ['cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000311095', 'cpi_9606.ENSP00000386069', 'cpi_9606.ENSP00000263980', 'cpi_9606.ENSP00000178638'], ['cpi_9606.ENSP00000261205', 'cpi_9606.ENSP00000412237', 'cpi_9606.ENSP00000256383', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000252723'], ['cpi_9606.ENSP00000306512', 'cpi_9606.ENSP00000318912', 'cpi_9606.ENSP00000369757', 'cpi_9606.ENSP00000300061', 'cpi_9606.ENSP00000258400'], ['cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000338548', 'cpi_9606.ENSP00000330393', 'cpi_9606.ENSP00000384273', 'cpi_9606.ENSP00000261196'], ['cpi_9606.ENSP00000269305', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000448059', 'cpi_9606.ENSP00000231454', 'cpi_9606.ENSP00000216962'], ['cpi_9606.ENSP00000263025', 'cpi_9606.ENSP00000349577', 'cpi_9606.ENSP00000366307', 'cpi_9606.ENSP00000372023', 'cpi_9606.ENSP00000306662'], ['cpi_9606.ENSP00000312652', 'cpi_9606.ENSP00000262441', 'cpi_9606.ENSP00000270776', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000241261'], ['cpi_9606.ENSP00000315644', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000327652', 'cpi_9606.ENSP00000337773', 'cpi_9606.ENSP00000445340'], ['cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000414303', 'cpi_9606.ENSP00000355657', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000331358'], ['cpi_9606.ENSP00000215832', 'cpi_9606.ENSP00000254488', 'cpi_9606.ENSP00000435777', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000353427'], ['cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000231449', 'cpi_9606.ENSP00000233146', 'cpi_9606.ENSP00000357283', 'cpi_9606.ENSP00000313661'], ['cpi_9606.ENSP00000361405', 'cpi_9606.ENSP00000211122', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000176183', 'cpi_9606.ENSP00000396320'], ['cpi_9606.ENSP00000252945', 'cpi_9606.ENSP00000362353', 'cpi_9606.ENSP00000263464', 'cpi_9606.ENSP00000221515', 'cpi_9606.ENSP00000463999'], ['cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000276449', 'cpi_9606.ENSP00000368880', 'cpi_9606.ENSP00000433821', 'cpi_9606.ENSP00000311469'], ['cpi_9606.ENSP00000303522', 'cpi_9606.ENSP00000353731', 'cpi_9606.ENSP00000232219', 'cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000388648'], ['cpi_9606.ENSP00000304915', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000332369', 'cpi_9606.ENSP00000454071', 'cpi_9606.ENSP00000355759'], ['cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000329623', 'cpi_9606.ENSP00000277120', 'cpi_9606.ENSP00000429374', 'cpi_9606.ENSP00000309757'], ['cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000332116', 'cpi_9606.ENSP00000358327', 'cpi_9606.ENSP00000267843', 'cpi_9606.ENSP00000301645'], ['cpi_9606.ENSP00000301974', 'cpi_9606.ENSP00000369050', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000255465', 'cpi_9606.ENSP00000311028'], ['cpi_9606.ENSP00000394624', 'cpi_9606.ENSP00000262160', 'cpi_9606.ENSP00000360967', 'cpi_9606.ENSP00000318646', 'cpi_9606.ENSP00000369927'], ['cpi_9606.ENSP00000375066', 'cpi_9606.ENSP00000277508', 'cpi_9606.ENSP00000343204', 'cpi_9606.ENSP00000287936', 'cpi_9606.ENSP00000225964'], ['cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000410076', 'cpi_9606.ENSP00000428924', 'cpi_9606.ENSP00000303174', 'cpi_9606.ENSP00000270474'], ['cpi_9606.ENSP00000327801', 'cpi_9606.ENSP00000264657', 'cpi_9606.ENSP00000365016', 'cpi_9606.ENSP00000358730', 'cpi_9606.ENSP00000217426'], ['cpi_9606.ENSP00000349467', 'cpi_9606.ENSP00000354394', 'cpi_9606.ENSP00000360973', 'cpi_9606.ENSP00000353791', 'cpi_9606.ENSP00000346148'], ['cpi_9606.ENSP00000216465', 'cpi_9606.ENSP00000304895', 'cpi_9606.ENSP00000322924', 'cpi_9606.ENSP00000358784', 'cpi_9606.ENSP00000355778'], ['cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000381333', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000278616', 'cpi_9606.ENSP00000309968'], ['cpi_9606.ENSP00000296545', 'cpi_9606.ENSP00000259486', 'cpi_9606.ENSP00000211287', 'cpi_9606.ENSP00000304845', 'cpi_9606.ENSP00000287907'], ['cpi_9606.ENSP00000360683', 'cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000275300', 'cpi_9606.ENSP00000307259', 'cpi_9606.ENSP00000354107'], ['cpi_9606.ENSP00000354850', 'cpi_9606.ENSP00000275216', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000356694', 'cpi_9606.ENSP00000262948'], ['cpi_9606.ENSP00000369647', 'cpi_9606.ENSP00000219919', 'cpi_9606.ENSP00000341885', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000370473'], ['cpi_9606.ENSP00000368305', 'cpi_9606.ENSP00000239938', 'cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000196551', 'cpi_9606.ENSP00000307235'], ['cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000252029', 'cpi_9606.ENSP00000387699', 'cpi_9606.ENSP00000407375', 'cpi_9606.ENSP00000464149'], ['cpi_9606.ENSP00000309845', 'cpi_9606.ENSP00000301146', 'cpi_9606.ENSP00000291294', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000368632'], ['cpi_9606.ENSP00000302150', 'cpi_9606.ENSP00000309477', 'cpi_9606.ENSP00000264867', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000379339'], ['cpi_9606.ENSP00000262407', 'cpi_9606.ENSP00000262735', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000306129', 'cpi_9606.ENSP00000301633'], ['cpi_9606.ENSP00000287820', 'cpi_9606.ENSP00000345502', 'cpi_9606.ENSP00000305302', 'cpi_9606.ENSP00000342560', 'cpi_9606.ENSP00000418960'], ['cpi_9606.ENSP00000265572', 'cpi_9606.ENSP00000348645', 'cpi_9606.ENSP00000282397', 'cpi_9606.ENSP00000385806', 'cpi_9606.ENSP00000254810'], ['cpi_9606.ENSP00000229447', 'cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000400175', 'cpi_9606.ENSP00000419692', 'cpi_9606.ENSP00000364805'], ['cpi_9606.ENSP00000340684', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000266682', 'cpi_9606.ENSP00000251453', 'cpi_9606.ENSP00000310928'], ['cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000256010', 'cpi_9606.ENSP00000295453', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000309103'], ['cpi_9606.ENSP00000353679', 'cpi_9606.ENSP00000321999', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000216392'], ['cpi_9606.ENSP00000261267', 'cpi_9606.ENSP00000276571', 'cpi_9606.ENSP00000312029', 'cpi_9606.ENSP00000285979', 'cpi_9606.ENSP00000290349'], ['cpi_9606.ENSP00000408695', 'cpi_9606.ENSP00000357981', 'cpi_9606.ENSP00000217305', 'cpi_9606.ENSP00000370912', 'cpi_9606.ENSP00000320709'], ['cpi_9606.ENSP00000362810', 'cpi_9606.ENSP00000321988', 'cpi_9606.ENSP00000358022', 'cpi_9606.ENSP00000333534', 'cpi_9606.ENSP00000333496'], ['cpi_9606.ENSP00000319531', 'cpi_9606.ENSP00000386884', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000296122', 'cpi_9606.ENSP00000212015'], ['cpi_9606.ENSP00000397582', 'cpi_9606.ENSP00000368683', 'cpi_9606.ENSP00000308032', 'cpi_9606.ENSP00000253727', 'cpi_9606.ENSP00000231228'], ['cpi_9606.ENSP00000364035', 'cpi_9606.ENSP00000260227', 'cpi_9606.ENSP00000393333', 'cpi_9606.ENSP00000338018', 'cpi_9606.ENSP00000253122'], ['cpi_9606.ENSP00000295598', 'cpi_9606.ENSP00000360266', 'cpi_9606.ENSP00000359793', 'cpi_9606.ENSP00000301141', 'cpi_9606.ENSP00000218388'], ['cpi_9606.ENSP00000219070', 'cpi_9606.ENSP00000361151', 'cpi_9606.ENSP00000394033', 'cpi_9606.ENSP00000321106', 'cpi_9606.ENSP00000341045'], ['cpi_9606.ENSP00000306100', 'cpi_9606.ENSP00000467494', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000252321', 'cpi_9606.ENSP00000288135'], ['cpi_9606.ENSP00000342952', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000228872', 'cpi_9606.ENSP00000302967', 'cpi_9606.ENSP00000305221'], ['cpi_9606.ENSP00000330032', 'cpi_9606.ENSP00000355920', 'cpi_9606.ENSP00000360968', 'cpi_9606.ENSP00000430432', 'cpi_9606.ENSP00000351885'], ['cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000370571', 'cpi_9606.ENSP00000340820', 'cpi_9606.ENSP00000365380', 'cpi_9606.ENSP00000225371'], ['cpi_9606.ENSP00000264613', 'cpi_9606.ENSP00000264498', 'cpi_9606.ENSP00000379110', 'cpi_9606.ENSP00000317379', 'cpi_9606.ENSP00000330199'], ['cpi_9606.ENSP00000290866', 'cpi_9606.ENSP00000263431', 'cpi_9606.ENSP00000239849', 'cpi_9606.ENSP00000246337', 'cpi_9606.ENSP00000302811'], ['cpi_9606.ENSP00000431719', 'cpi_9606.ENSP00000288022', 'cpi_9606.ENSP00000236671', 'cpi_9606.ENSP00000356832', 'cpi_9606.ENSP00000176763'], ['cpi_9606.ENSP00000327251', 'cpi_9606.ENSP00000346298', 'cpi_9606.ENSP00000371554', 'cpi_9606.ENSP00000355533', 'cpi_9606.ENSP00000244741'], ['cpi_9606.ENSP00000356825', 'cpi_9606.ENSP00000336630', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000297268', 'cpi_9606.ENSP00000398655'], ['cpi_9606.ENSP00000355536', 'cpi_9606.ENSP00000368104', 'cpi_9606.ENSP00000292513', 'cpi_9606.ENSP00000360247', 'cpi_9606.ENSP00000355155'], ['cpi_9606.ENSP00000229319', 'cpi_9606.ENSP00000335657', 'cpi_9606.ENSP00000269571', 'cpi_9606.ENSP00000252804', 'cpi_9606.ENSP00000338627'], ['cpi_9606.ENSP00000359899', 'cpi_9606.ENSP00000306606', 'cpi_9606.ENSP00000268035', 'cpi_9606.ENSP00000300151', 'cpi_9606.ENSP00000362525'], ['cpi_9606.ENSP00000320866', 'cpi_9606.ENSP00000261465', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000324248', 'cpi_9606.ENSP00000353483'], ['cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000227507', 'cpi_9606.ENSP00000294954', 'cpi_9606.ENSP00000359998', 'cpi_9606.ENSP00000356671'], ['cpi_9606.ENSP00000272298', 'cpi_9606.ENSP00000341189', 'cpi_9606.ENSP00000303424', 'cpi_9606.ENSP00000358107', 'cpi_9606.ENSP00000312673'], ['cpi_9606.ENSP00000362401', 'cpi_9606.ENSP00000234389', 'cpi_9606.ENSP00000362508', 'cpi_9606.ENSP00000332816', 'cpi_9606.ENSP00000216185'], ['cpi_9606.ENSP00000337459', 'cpi_9606.ENSP00000352035', 'cpi_9606.ENSP00000341828', 'cpi_9606.ENSP0000033

🔄 Processing features: 100%|██████████| 1607/1607 [06:52<00:00,  3.90feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'cpi_9606.ENSP00000356094', 'cpi_9606.ENSP00000326219', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000359424'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000367102', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000261937'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000332296'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000359353', 'cpi_9606.ENSP00000286479'], ['cpi_9606.ENSP00000264381', 'cpi_9606.ENSP00000319788', 'cpi_9606.ENSP00000355629', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000417229'], ['cpi_9606.ENSP00000231509', 'cpi_9606.ENSP00000266376', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000395653', 'cpi_9606.ENSP00000343040'], ['cpi_9606.ENSP00000360372', 'cpi_9606.ENSP00000359793', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000312664', 'cpi_9606.ENSP00000261799'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000374323', 'cpi_9606.ENSP00000260010'], ['cpi_9606.ENSP00000265724', 'cpi_9606.ENSP00000304822', 'cpi_9606.ENSP00000299178', 'cpi_9606.ENSP00000367848', 'cpi_9606.ENSP00000381097'], ['cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000263321', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000354476', 'cpi_9606.ENSP00000274547'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000358548', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000353292', 'cpi_9606.ENSP00000348897'], ['cpi_9606.ENSP00000369960', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000221972'], ['cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000360773', 'cpi_9606.ENSP00000261196'], ['cpi_9606.ENSP00000260433', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000283635', 'cpi_9606.ENSP00000430684', 'cpi_9606.ENSP00000257290'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000337335', 'cpi_9606.ENSP00000279178'], ['cpi_9606.ENSP00000311032', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000295454', 'cpi_9606.ENSP00000312304'], ['cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000277010', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000301891', 'cpi_9606.ENSP00000347942'], ['cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000353362'], ['cpi_9606.ENSP00000305372', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000216037', 'cpi_9606.ENSP00000454071'], ['cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000241453'], ['cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000367851', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000275525', 'cpi_9606.ENSP00000342235'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000311165', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000326119', 'cpi_9606.ENSP00000352900'], ['cpi_9606.ENSP00000272190', 'cpi_9606.ENSP00000301178', 'cpi_9606.ENSP00000329357', 'cpi_9606.ENSP00000348069', 'cpi_9606.ENSP00000410732'], ['cpi_9606.ENSP00000270202', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000387946'], ['cpi_9606.ENSP00000270349', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000225474', 'cpi_9606.ENSP00000259089'], ['cpi_9606.ENSP00000220764', 'cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000451040'], ['cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000361666', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000346534'], ['cpi_9606.ENSP00000363822', 'cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000299267', 'cpi_9606.ENSP00000307599', 'cpi_9606.ENSP00000414334'], ['cpi_9606.ENSP00000367959', 'cpi_9606.ENSP00000301634', 'cpi_9606.ENSP00000242057', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000331912'], ['cpi_9606.ENSP00000411532', 'cpi_9606.ENSP00000233242', 'cpi_9606.ENSP00000327652', 'cpi_9606.ENSP00000471569', 'cpi_9606.ENSP00000378517'], ['cpi_9606.ENSP00000398698', 'cpi_9606.ENSP00000386029', 'cpi_9606.ENSP00000394936', 'cpi_9606.ENSP00000382250', 'cpi_9606.ENSP00000463999'], ['cpi_9606.ENSP00000316786', 'cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000398632', 'cpi_9606.ENSP00000264637', 'cpi_9606.ENSP00000310447'], ['cpi_9606.ENSP00000274353', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000372023', 'cpi_9606.ENSP00000276198', 'cpi_9606.ENSP00000261693'], ['cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000282753', 'cpi_9606.ENSP00000344192', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000347979'], ['cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000222330', 'cpi_9606.ENSP00000389338'], ['cpi_9606.ENSP00000366506', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000286301'], ['cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000368880', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000410294'], ['cpi_9606.ENSP00000270142', 'cpi_9606.ENSP00000294728', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000267101'], ['cpi_9606.ENSP00000280155', 'cpi_9606.ENSP00000357204', 'cpi_9606.ENSP00000302111', 'cpi_9606.ENSP00000360493', 'cpi_9606.ENSP00000288139'], ['cpi_9606.ENSP00000297494', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000333212'], ['cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000356954', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000355778', 'cpi_9606.ENSP00000251535'], ['cpi_9606.ENSP00000316244', 'cpi_9606.ENSP00000359478', 'cpi_9606.ENSP00000362036', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000258749'], ['cpi_9606.ENSP00000344456', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000320935', 'cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000289753'], ['cpi_9606.ENSP00000337949', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000368632', 'cpi_9606.ENSP00000376943'], ['cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000359635', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000470087'], ['cpi_9606.ENSP00000284981', 'cpi_9606.ENSP00000343477', 'cpi_9606.ENSP00000259396', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000308774'], ['cpi_9606.ENSP00000295897', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000457706', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000262888'], ['cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000330237', 'cpi_9606.ENSP00000327431', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000368766'], ['cpi_9606.ENSP00000350348', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000268053', 'cpi_9606.ENSP00000308165', 'cpi_9606.ENSP00000380252'], ['cpi_9606.ENSP00000308541', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000389414', 'cpi_9606.ENSP00000344352'], ['cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000296871', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000255465'], ['cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000361359', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000263126'], ['cpi_9606.ENSP00000368438', 'cpi_9606.ENSP00000355930', 'cpi_9606.ENSP00000231454', 'cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000340820'], ['cpi_9606.ENSP00000356438', 'cpi_9606.ENSP00000176763', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000357283', 'cpi_9606.ENSP00000306662'], ['cpi_9606.ENSP00000236850', 'cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000303174'], ['cpi_9606.ENSP00000354859', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000330393', 'cpi_9606.ENSP00000267843', 'cpi_9606.ENSP00000428340'], ['cpi_9606.ENSP00000254976', 'cpi_9606.ENSP00000296545', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000252723', 'cpi_9606.ENSP00000252519'], ['cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000354394', 'cpi_9606.ENSP00000287907', 'cpi_9606.ENSP00000353791'], ['cpi_9606.ENSP00000258743', 'cpi_9606.ENSP00000264818', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000200676', 'cpi_9606.ENSP00000267119'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000353427', 'cpi_9606.ENSP00000303452', 'cpi_9606.ENSP00000293288', 'cpi_9606.ENSP00000295834'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000340943', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000348827'], ['cpi_9606.ENSP00000358963', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000312455'], ['cpi_9606.ENSP00000234111', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000252321', 'cpi_9606.ENSP00000387281', 'cpi_9606.ENSP00000256958'], ['cpi_9606.ENSP00000386069', 'cpi_9606.ENSP00000338548', 'cpi_9606.ENSP00000252486', 'cpi_9606.ENSP00000344674', 'cpi_9606.ENSP00000252809'], ['cpi_9606.ENSP00000354612', 'cpi_9606.ENSP00000339527', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000393312', 'cpi_9606.ENSP00000222256'], ['cpi_9606.ENSP00000337450', 'cpi_9606.ENSP00000362353', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000318822', 'cpi_9606.ENSP00000282561'], ['cpi_9606.ENSP00000263025', 'cpi_9606.ENSP00000370381', 'cpi_9606.ENSP00000307014', 'cpi_9606.ENSP00000274793', 'cpi_9606.ENSP00000304915'], ['cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000263980', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000313661', 'cpi_9606.ENSP00000295491'], ['cpi_9606.ENSP00000257497', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000358784', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000309124'], ['cpi_9606.ENSP00000306512', 'cpi_9606.ENSP00000220616', 'cpi_9606.ENSP00000270776', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000346598'], ['cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000370473', 'cpi_9606.ENSP00000311469', 'cpi_9606.ENSP00000258400', 'cpi_9606.ENSP00000445340'], ['cpi_9606.ENSP00000368305', 'cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000176183', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000369530'], ['cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000263341', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000373169', 'cpi_9606.ENSP00000254066'], ['cpi_9606.ENSP00000215832', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000216962', 'cpi_9606.ENSP00000300061', 'cpi_9606.ENSP00000297350'], ['cpi_9606.ENSP00000387662', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000305221'], ['cpi_9606.ENSP00000352835', 'cpi_9606.ENSP00000264657', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000355317'], ['cpi_9606.ENSP00000306245', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000353878', 'cpi_9606.ENSP00000360967', 'cpi_9606.ENSP00000312029'], ['cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000341045', 'cpi_9606.ENSP00000226574', 'cpi_9606.ENSP00000262461'], ['cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000262441', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000310928', 'cpi_9606.ENSP00000285979'], ['cpi_9606.ENSP00000355759', 'cpi_9606.ENSP00000301974', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000349252', 'cpi_9606.ENSP00000340691'], ['cpi_9606.ENSP00000264832', 'cpi_9606.ENSP00000405573', 'cpi_9606.ENSP00000410076', 'cpi_9606.ENSP00000307235', 'cpi_9606.ENSP00000263339'], ['cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000343204', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000304811'], ['cpi_9606.ENSP00000237612', 'cpi_9606.ENSP00000441691', 'cpi_9606.ENSP00000254810', 'cpi_9606.ENSP00000307766', 'cpi_9606.ENSP00000276449'], ['cpi_9606.ENSP00000315644', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000322924', 'cpi_9606.ENSP00000287936', 'cpi_9606.ENSP00000355657'], ['cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000260356', 'cpi_9606.ENSP00000263923', 'cpi_9606.ENSP00000356694'], ['cpi_9606.ENSP00000312652', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000364802', 'cpi_9606.ENSP00000252029', 'cpi_9606.ENSP00000366307'], ['cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000362344', 'cpi_9606.ENSP00000323568', 'cpi_9606.ENSP00000306129', 'cpi_9606.ENSP00000311095'], ['cpi_9606.ENSP00000303522', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000233146', 'cpi_9606.ENSP00000277120', 'cpi_9606.ENSP00000270570'], ['cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000275300', 'cpi_9606.ENSP00000332369', 'cpi_9606.ENSP00000365663', 'cpi_9606.ENSP00000353915'], ['cpi_9606.ENSP00000360683', 'cpi_9606.ENSP00000414303', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000360973', 'cpi_9606.ENSP00000225964'], ['cpi_9606.ENSP00000261205', 'cpi_9606.ENSP00000412237', 'cpi_9606.ENSP00000256383', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000385806'], ['cpi_9606.ENSP00000229447', 'cpi_9606.ENSP00000384273', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000336630', 'cpi_9606.ENSP00000346768'], ['cpi_9606.ENSP00000302150', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000365380', 'cpi_9606.ENSP00000264867', 'cpi_9606.ENSP00000388648'], ['cpi_9606.ENSP00000265572', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000341189', 'cpi_9606.ENSP00000356150', 'cpi_9606.ENSP00000338627'], ['cpi_9606.ENSP00000269305', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000292513', 'cpi_9606.ENSP00000351209'], ['cpi_9606.ENSP00000225831', 'cpi_9606.ENSP00000349576', 'cpi_9606.ENSP00000358730', 'cpi_9606.ENSP00000365016', 'cpi_9606.ENSP00000266682'], ['cpi_9606.ENSP00000361405', 'cpi_9606.ENSP00000355325', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000337773', 'cpi_9606.ENSP00000231449'], ['cpi_9606.ENSP00000252945', 'cpi_9606.ENSP00000298171', 'cpi_9606.ENSP00000263464', 'cpi_9606.ENSP00000221515', 'cpi_9606.ENSP00000317379'], ['cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000264498', 'cpi_9606.ENSP00000164139', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000241261'], ['cpi_9606.ENSP00000302811', 'cpi_9606.ENSP00000417281', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000386171', 'cpi_9606.ENSP00000354107'], ['cpi_9606.ENSP00000295598', 'cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000358327', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000359532'], ['cpi_9606.ENSP00000375066', 'cpi_9606.ENSP00000264162', 'cpi_9606.ENSP00000329623', 'cpi_9606.ENSP00000467676', 'cpi_9606.ENSP00000309757'], ['cpi_9606.ENSP00000394624', 'cpi_9606.ENSP00000232219', 'cpi_9606.ENSP00000302967', 'cpi_9606.ENSP00000351885', 'cpi_9606.ENSP00000305302'], ['cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000362401', 'cpi_9606.ENSP00000304845', 'cpi_9606.ENSP00000248553', 'cpi_9606.ENSP00000332816'], ['cpi_9606.ENSP00000367309', 'cpi_9606.ENSP00000400175', 'cpi_9606.ENSP00000362649', 'cpi_9606.ENSP00000262948', 'cpi_9606.ENSP00000301146'], ['cpi_9606.ENSP00000337459', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000311028', 'cpi_9606.ENSP00000225927', 'cpi_9606.ENSP00000370254'], ['cpi_9606.ENSP00000397582', 'cpi_9606.ENSP00000239938', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000349003', 'cpi_9606.ENSP00000427562'], ['cpi_9606.ENSP00000262407', 'cpi_9606.ENSP00000262735', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000231228', 'cpi_9606.ENSP00000270474'], ['cpi_9606.ENSP00000237014', 'cpi_9606.ENSP00000354558', 'cpi_9606.ENSP00000309493', 'cpi_9606.ENSP00000320401', 'cpi_9606.ENSP00000251453'], ['cpi_9606.ENSP00000353731', 'cpi_9606.ENSP00000382659', 'cpi_9606.ENSP00000296122', 'cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000226413'], ['cpi_9606.ENSP00000222553', 'cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000309103', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000430432'], ['cpi_9606.ENSP00000321988', 'cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000331358', 'cpi_9606.ENSP00000239849', 'cpi_9606.ENSP00000270625'], ['cpi_9606.ENSP00000327801', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000302846', 'cpi_9606.ENSP00000308032', 'cpi_9606.ENSP00000314099'], ['cpi_9606.ENSP00000364035', 'cpi_9606.ENSP00000278616', 'cpi_9606.ENSP00000276414', 'cpi_9606.ENSP00000297268', 'cpi_9606.ENSP00000254488'], ['cpi_9606.ENSP00000381333', 'cpi_9606.ENSP00000353679', 'cpi_9606.ENSP00000427514', 'cpi_9606.ENSP00000346298', 'cpi_9606.ENSP00000419782'], ['cpi_9606.ENSP00000320866', 'cpi_9606.ENSP00000261465', 'cpi_9606.ENSP00000253727', 'cpi_9606.ENSP00000355920', 'cpi_9606.ENSP00000323549'], ['cpi_9606.ENSP00000330032', 'cpi_9606.ENSP00000369050', 'cpi_9606.ENSP00000321106', 'cpi_9606.ENSP00000464149', 'cpi_9606.ENSP00000327850'], ['cpi_9606.ENSP00000268035', 'cpi_9606.ENSP00000448059', 'cpi_9606.ENSP00000259271', 'cpi_9606.ENSP00000419692', 'cpi_9606.ENSP00000362525'], ['cpi_9606.ENSP00000383365', 'cpi_9606.ENSP00000265023', 'cpi_9606.ENSP00000288135', 'cpi_9606.ENSP00000330199', 'cpi_9606.ENSP00000262367'], ['cpi_9606.ENSP00000260302', 'cpi_9606.ENSP00000291294', 'cpi_9606.ENSP00000333534', 'cpi_9606.ENSP00000351908', 'cpi_9606.ENSP00000363827'], ['cpi_9606.ENSP00000356022', 'cpi_9606.ENSP00000428924', 'cpi_9606.ENSP00000358511', 'cpi_9606.ENSP00000252804', 'cpi_9606.ENSP00000290349'], ['cpi_9606.ENSP00000340684', 'cpi_9606.ENSP00000319591', 'cpi_9606.ENSP00000244741', 'cpi_9606.ENSP00000387683', 'cpi_9606.ENSP00000342560'], ['cpi_9606.ENSP00000275216', 'cpi_9606.ENSP00000222481', 'cpi_9606.ENSP00000320709', 'cpi_9606.ENSP00000301633', 'cpi_9606.ENSP00000350767'], ['cpi_9606.ENSP00000287820', 'cpi_9606.ENSP00000359910', 'cpi_9606.ENSP00000459962', 'cpi_9606.ENSP00000282397', 'cpi_9606.ENSP00000333496'], ['cpi_9606.ENSP00000259486', 'cpi_9606.ENSP00000260970', 'cpi_9606.ENSP00000217305', 'cpi_9606.ENSP00000228872', 'cpi_9606.ENSP00000219919'], ['cpi_9606.ENSP00000327251', 'cpi_9606.ENSP00000352035', 'cpi_9606.ENSP00000341828', 'cpi_9606.ENSP00000369757', 'cpi_9606.ENSP00000354569'], ['cpi_9606.ENSP00000434516', 'cpi_9606.ENSP00000223095', 'cpi_9606.ENSP00000245457', 'cpi_9606.ENSP00000355533', 'cpi_9606.ENSP00000362549'], ['cpi_9606.ENSP00000356825', 'cpi_9606.ENSP00000371554', 'cpi_9606.ENSP00000305651', 'cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000362508'], ['cpi_9606.ENSP00000264613', 'cpi_9606.ENSP00000379213', 'cpi_9606.ENSP00000301141', 'cpi_9606.ENSP00000368683', 'cpi_9606.ENSP00000364805'], ['cpi_9606.ENSP00000219070', 'cpi_9606.ENSP00000398655', 'cpi_9606.ENSP00000338082', 'cpi_9606.ENSP00000294954', 'cpi_9606.ENSP00000248041'], ['cpi_9606.ENSP00000290866', 'cpi_9606.ENSP00000265643', 'cpi_9606.ENSP00000262160', 'cpi_9606.ENSP00000358022', 'cpi_9606.ENSP00000296674'], ['cpi_9606.ENSP00000246657', 'cpi_9606.ENSP00000277508', 'cpi_9606.ENSP00000346148', 'cpi_9606.ENSP00000349467', 'cpi_9606.ENSP00000366084'], ['cpi_9606.ENSP00000386284', 'cpi_9606.ENSP00000324270', 'cpi_9606.ENSP00000218388', 'cpi_9606.ENSP00000321821', 'cpi_9606.ENSP00000356671'], ['cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000466799', 'cpi_9606.ENSP00000335544', 'cpi_9606.ENSP00000341885', 'cpi_9606.ENSP00000269571'], ['cpi_9606.ENSP00000408695', 'cpi_9606.ENSP00000211287', 'cpi_9606.ENSP00000295589', 'cpi_9606.ENSP00000318646', 'cpi_9606.ENSP00000368104'], ['cpi_9606.ENSP00000331602', 'cpi_9606.ENSP00000274026', 'cpi_9606.ENSP00000379140', 'cpi_9606.ENSP00000265403', 'cpi_9606.ENSP00000433821'], ['cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000256010', 'cpi_9606.ENSP00000295453', 'cpi_9606.ENSP00000429374', 'cpi_9606.ENSP00000368752'], ['cpi_9606.ENSP00000257068', 'cpi_9606.ENSP00000288022', 'cpi_9606.ENSP00000304895', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000292896'], ['cpi_9606.ENSP00000342952', 'cpi_9606.ENSP00000331736', 'cpi_9606.ENSP00000196551', 'cpi_9606.ENSP00000236671', 'cpi_9606.ENSP00000315011'], ['cpi_9606.ENSP00000380318', 'cpi_9606.ENSP00000387888', 'cpi_9606.ENSP00000308549', 'cpi_9606.ENSP00000216117', 'cpi_9606.ENSP00000379339'], ['cpi_9606.ENSP00000369647', 'cpi_9606.ENSP00000335620', 'cpi_9606.ENSP00000348461', 'cpi_9606.ENSP0000021

🔄 Processing features: 100%|██████████| 1607/1607 [06:52<00:00,  3.90feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'cpi_9606.ENSP00000309818', 'cpi_9606.ENSP00000364805', 'cpi_9606.ENSP00000395653', 'cpi_9606.ENSP00000312455'], ['cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000356094', 'cpi_9606.ENSP00000301891', 'cpi_9606.ENSP00000312304'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000359353'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000299178', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000342235'], ['cpi_9606.ENSP00000231509', 'cpi_9606.ENSP00000266376', 'cpi_9606.ENSP00000355629', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000274545'], ['cpi_9606.ENSP00000360372', 'cpi_9606.ENSP00000303522', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000389338', 'cpi_9606.ENSP00000261937'], ['cpi_9606.ENSP00000265724', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000337335', 'cpi_9606.ENSP00000359793', 'cpi_9606.ENSP00000367848'], ['cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000263321', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000414334'], ['cpi_9606.ENSP00000237014', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000277010', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000358548'], ['cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000360773', 'cpi_9606.ENSP00000265294'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000374323', 'cpi_9606.ENSP00000348897'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000264318'], ['cpi_9606.ENSP00000311032', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000445340', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000295454'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000301974', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000261799', 'cpi_9606.ENSP00000332296'], ['cpi_9606.ENSP00000260433', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000362036', 'cpi_9606.ENSP00000354476', 'cpi_9606.ENSP00000216037'], ['cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000417229'], ['cpi_9606.ENSP00000264381', 'cpi_9606.ENSP00000319788', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000326119', 'cpi_9606.ENSP00000386306'], ['cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000225474', 'cpi_9606.ENSP00000295491', 'cpi_9606.ENSP00000257290', 'cpi_9606.ENSP00000367102'], ['cpi_9606.ENSP00000272190', 'cpi_9606.ENSP00000275525', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000354394', 'cpi_9606.ENSP00000274547'], ['cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000369960', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000233242', 'cpi_9606.ENSP00000378517'], ['cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000360493', 'cpi_9606.ENSP00000410732'], ['cpi_9606.ENSP00000305372', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000471569', 'cpi_9606.ENSP00000353362'], ['cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000408860'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000311165', 'cpi_9606.ENSP00000312664', 'cpi_9606.ENSP00000381097', 'cpi_9606.ENSP00000262999'], ['cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000363822', 'cpi_9606.ENSP00000299267', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000410294'], ['cpi_9606.ENSP00000411532', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000221972', 'cpi_9606.ENSP00000279178', 'cpi_9606.ENSP00000412673'], ['cpi_9606.ENSP00000368438', 'cpi_9606.ENSP00000389414', 'cpi_9606.ENSP00000361359', 'cpi_9606.ENSP00000354859', 'cpi_9606.ENSP00000000442'], ['cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000306662', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000343477', 'cpi_9606.ENSP00000347942'], ['cpi_9606.ENSP00000270142', 'cpi_9606.ENSP00000361666', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000348069', 'cpi_9606.ENSP00000359285'], ['cpi_9606.ENSP00000367959', 'cpi_9606.ENSP00000301634', 'cpi_9606.ENSP00000252486', 'cpi_9606.ENSP00000301178', 'cpi_9606.ENSP00000331912'], ['cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000260356', 'cpi_9606.ENSP00000283635', 'cpi_9606.ENSP00000335592'], ['cpi_9606.ENSP00000220764', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000451040', 'cpi_9606.ENSP00000376943', 'cpi_9606.ENSP00000307599'], ['cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000367851', 'cpi_9606.ENSP00000300061', 'cpi_9606.ENSP00000354558', 'cpi_9606.ENSP00000251535'], ['cpi_9606.ENSP00000274353', 'cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000308165', 'cpi_9606.ENSP00000263126'], ['cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000316786', 'cpi_9606.ENSP00000398632', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000264637'], ['cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000234111', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000343040', 'cpi_9606.ENSP00000241453'], ['cpi_9606.ENSP00000337450', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000286301'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000262441', 'cpi_9606.ENSP00000362649', 'cpi_9606.ENSP00000297350', 'cpi_9606.ENSP00000409007'], ['cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000457706', 'cpi_9606.ENSP00000346534'], ['cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000263341', 'cpi_9606.ENSP00000387946', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000386029'], ['cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000430684'], ['cpi_9606.ENSP00000398698', 'cpi_9606.ENSP00000262888', 'cpi_9606.ENSP00000394936', 'cpi_9606.ENSP00000233146', 'cpi_9606.ENSP00000267119'], ['cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000344192', 'cpi_9606.ENSP00000387281', 'cpi_9606.ENSP00000411593'], ['cpi_9606.ENSP00000284981', 'cpi_9606.ENSP00000261693', 'cpi_9606.ENSP00000267101', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000333212'], ['cpi_9606.ENSP00000295897', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000226574', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000259089'], ['cpi_9606.ENSP00000344456', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000304822', 'cpi_9606.ENSP00000200676', 'cpi_9606.ENSP00000276198'], ['cpi_9606.ENSP00000280155', 'cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000302111', 'cpi_9606.ENSP00000370381', 'cpi_9606.ENSP00000260010'], ['cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000386284', 'cpi_9606.ENSP00000278616', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000242057'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000359899', 'cpi_9606.ENSP00000353427', 'cpi_9606.ENSP00000252723', 'cpi_9606.ENSP00000310447'], ['cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000236850', 'cpi_9606.ENSP00000307235', 'cpi_9606.ENSP00000267843', 'cpi_9606.ENSP00000361206'], ['cpi_9606.ENSP00000350348', 'cpi_9606.ENSP00000359478', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000225964', 'cpi_9606.ENSP00000330393'], ['cpi_9606.ENSP00000366506', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000337773', 'cpi_9606.ENSP00000320935', 'cpi_9606.ENSP00000293288'], ['cpi_9606.ENSP00000270349', 'cpi_9606.ENSP00000321988', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000176763', 'cpi_9606.ENSP00000353292'], ['cpi_9606.ENSP00000270202', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000258749', 'cpi_9606.ENSP00000262367', 'cpi_9606.ENSP00000216962'], ['cpi_9606.ENSP00000297494', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000353791', 'cpi_9606.ENSP00000252809', 'cpi_9606.ENSP00000435591'], ['cpi_9606.ENSP00000356438', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000307014', 'cpi_9606.ENSP00000470087', 'cpi_9606.ENSP00000259396'], ['cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000294728', 'cpi_9606.ENSP00000313661', 'cpi_9606.ENSP00000344352'], ['cpi_9606.ENSP00000316244', 'cpi_9606.ENSP00000357204', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000263923', 'cpi_9606.ENSP00000276449'], ['cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000354850', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000309124', 'cpi_9606.ENSP00000222330'], ['cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000296122', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000306129'], ['cpi_9606.ENSP00000352835', 'cpi_9606.ENSP00000264657', 'cpi_9606.ENSP00000356954', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000323549'], ['cpi_9606.ENSP00000337949', 'cpi_9606.ENSP00000264162', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000307240'], ['cpi_9606.ENSP00000354612', 'cpi_9606.ENSP00000339527', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000463999'], ['cpi_9606.ENSP00000386069', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000323568', 'cpi_9606.ENSP00000400175', 'cpi_9606.ENSP00000329357'], ['cpi_9606.ENSP00000258743', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000254227'], ['cpi_9606.ENSP00000308541', 'cpi_9606.ENSP00000356694', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000261196', 'cpi_9606.ENSP00000312029'], ['cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000241261', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000332816'], ['cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000264832', 'cpi_9606.ENSP00000358784', 'cpi_9606.ENSP00000307766', 'cpi_9606.ENSP00000348827'], ['cpi_9606.ENSP00000358963', 'cpi_9606.ENSP00000338548', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000264867', 'cpi_9606.ENSP00000318822'], ['cpi_9606.ENSP00000225831', 'cpi_9606.ENSP00000364802', 'cpi_9606.ENSP00000332369', 'cpi_9606.ENSP00000357283', 'cpi_9606.ENSP00000289753'], ['cpi_9606.ENSP00000306245', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000353878', 'cpi_9606.ENSP00000266682', 'cpi_9606.ENSP00000231454'], ['cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000275216', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000428340', 'cpi_9606.ENSP00000285979'], ['cpi_9606.ENSP00000373169', 'cpi_9606.ENSP00000356729', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000218388', 'cpi_9606.ENSP00000365775'], ['cpi_9606.ENSP00000257497', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000384273', 'cpi_9606.ENSP00000368766'], ['cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000258400', 'cpi_9606.ENSP00000262948'], ['cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000378699', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000351885', 'cpi_9606.ENSP00000274793'], ['cpi_9606.ENSP00000237612', 'cpi_9606.ENSP00000282753', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000355657', 'cpi_9606.ENSP00000385806'], ['cpi_9606.ENSP00000387662', 'cpi_9606.ENSP00000311469', 'cpi_9606.ENSP00000366307', 'cpi_9606.ENSP00000231228', 'cpi_9606.ENSP00000287766'], ['cpi_9606.ENSP00000306512', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000305302', 'cpi_9606.ENSP00000282561', 'cpi_9606.ENSP00000372023'], ['cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000311095', 'cpi_9606.ENSP00000263980', 'cpi_9606.ENSP00000308774'], ['cpi_9606.ENSP00000302811', 'cpi_9606.ENSP00000268053', 'cpi_9606.ENSP00000220616', 'cpi_9606.ENSP00000355759', 'cpi_9606.ENSP00000371929'], ['cpi_9606.ENSP00000302150', 'cpi_9606.ENSP00000309477', 'cpi_9606.ENSP00000347979', 'cpi_9606.ENSP00000310928', 'cpi_9606.ENSP00000256958'], ['cpi_9606.ENSP00000215832', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000341828', 'cpi_9606.ENSP00000295834', 'cpi_9606.ENSP00000226413'], ['cpi_9606.ENSP00000368305', 'cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000176183', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000296871'], ['cpi_9606.ENSP00000405573', 'cpi_9606.ENSP00000330237', 'cpi_9606.ENSP00000327652', 'cpi_9606.ENSP00000427514', 'cpi_9606.ENSP00000252945'], ['cpi_9606.ENSP00000263025', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000255465', 'cpi_9606.ENSP00000216392', 'cpi_9606.ENSP00000353915'], ['cpi_9606.ENSP00000309845', 'cpi_9606.ENSP00000448059', 'cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000428924', 'cpi_9606.ENSP00000345708'], ['cpi_9606.ENSP00000369647', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000368104', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000352702'], ['cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000322924'], ['cpi_9606.ENSP00000327431', 'cpi_9606.ENSP00000412237', 'cpi_9606.ENSP00000343204', 'cpi_9606.ENSP00000414303', 'cpi_9606.ENSP00000386171'], ['cpi_9606.ENSP00000216465', 'cpi_9606.ENSP00000304895', 'cpi_9606.ENSP00000248553', 'cpi_9606.ENSP00000331358', 'cpi_9606.ENSP00000396320'], ['cpi_9606.ENSP00000304915', 'cpi_9606.ENSP00000367309', 'cpi_9606.ENSP00000369757', 'cpi_9606.ENSP00000262461', 'cpi_9606.ENSP00000380252'], ['cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000225577', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000410076'], ['cpi_9606.ENSP00000327801', 'cpi_9606.ENSP00000239938', 'cpi_9606.ENSP00000365016', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000267377'], ['cpi_9606.ENSP00000263088', 'cpi_9606.ENSP00000262735', 'cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000346598', 'cpi_9606.ENSP00000305221'], ['cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000355930', 'cpi_9606.ENSP00000282397', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000287936'], ['cpi_9606.ENSP00000298171', 'cpi_9606.ENSP00000304845', 'cpi_9606.ENSP00000418960', 'cpi_9606.ENSP00000365663', 'cpi_9606.ENSP00000275300'], ['cpi_9606.ENSP00000269305', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000292513', 'cpi_9606.ENSP00000252029'], ['cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000370473', 'cpi_9606.ENSP00000356150', 'cpi_9606.ENSP00000454071', 'cpi_9606.ENSP00000260970'], ['cpi_9606.ENSP00000315644', 'cpi_9606.ENSP00000312652', 'cpi_9606.ENSP00000379213', 'cpi_9606.ENSP00000270776', 'cpi_9606.ENSP00000319591'], ['cpi_9606.ENSP00000261205', 'cpi_9606.ENSP00000231449', 'cpi_9606.ENSP00000356832', 'cpi_9606.ENSP00000388648', 'cpi_9606.ENSP00000346298'], ['cpi_9606.ENSP00000397582', 'cpi_9606.ENSP00000358327', 'cpi_9606.ENSP00000335657', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000311028'], ['cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000265403', 'cpi_9606.ENSP00000244741', 'cpi_9606.ENSP00000467676'], ['cpi_9606.ENSP00000296545', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000419782', 'cpi_9606.ENSP00000351209', 'cpi_9606.ENSP00000382659'], ['cpi_9606.ENSP00000353679', 'cpi_9606.ENSP00000272847', 'cpi_9606.ENSP00000269571', 'cpi_9606.ENSP00000254488', 'cpi_9606.ENSP00000320709'], ['cpi_9606.ENSP00000356022', 'cpi_9606.ENSP00000358511', 'cpi_9606.ENSP00000355778', 'cpi_9606.ENSP00000303174', 'cpi_9606.ENSP00000356671'], ['cpi_9606.ENSP00000375066', 'cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000221515', 'cpi_9606.ENSP00000329623'], ['cpi_9606.ENSP00000360683', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000287907', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000253122'], ['cpi_9606.ENSP00000362810', 'cpi_9606.ENSP00000353731', 'cpi_9606.ENSP00000232219', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000270625'], ['cpi_9606.ENSP00000327251', 'cpi_9606.ENSP00000164139', 'cpi_9606.ENSP00000330199', 'cpi_9606.ENSP00000318646', 'cpi_9606.ENSP00000343838'], ['cpi_9606.ENSP00000408695', 'cpi_9606.ENSP00000280357', 'cpi_9606.ENSP00000217305', 'cpi_9606.ENSP00000464149', 'cpi_9606.ENSP00000320401'], ['cpi_9606.ENSP00000222553', 'cpi_9606.ENSP00000368683', 'cpi_9606.ENSP00000301146', 'cpi_9606.ENSP00000333496', 'cpi_9606.ENSP00000309757'], ['cpi_9606.ENSP00000229447', 'cpi_9606.ENSP00000360266', 'cpi_9606.ENSP00000294954', 'cpi_9606.ENSP00000270474', 'cpi_9606.ENSP00000360967'], ['cpi_9606.ENSP00000361405', 'cpi_9606.ENSP00000355325', 'cpi_9606.ENSP00000277120', 'cpi_9606.ENSP00000218099', 'cpi_9606.ENSP00000362525'], ['cpi_9606.ENSP00000394624', 'cpi_9606.ENSP00000228872', 'cpi_9606.ENSP00000302967', 'cpi_9606.ENSP00000338627', 'cpi_9606.ENSP00000346148'], ['cpi_9606.ENSP00000373477', 'cpi_9606.ENSP00000303830', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000358730', 'cpi_9606.ENSP00000357255'], ['cpi_9606.ENSP00000287820', 'cpi_9606.ENSP00000459962', 'cpi_9606.ENSP00000359910', 'cpi_9606.ENSP00000430432', 'cpi_9606.ENSP00000393312'], ['cpi_9606.ENSP00000265572', 'cpi_9606.ENSP00000252804', 'cpi_9606.ENSP00000268035', 'cpi_9606.ENSP00000362513', 'cpi_9606.ENSP00000196551'], ['cpi_9606.ENSP00000219070', 'cpi_9606.ENSP00000398655', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000341045', 'cpi_9606.ENSP00000354107'], ['cpi_9606.ENSP00000259486', 'cpi_9606.ENSP00000215659', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000321106', 'cpi_9606.ENSP00000317379'], ['cpi_9606.ENSP00000324270', 'cpi_9606.ENSP00000274026', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000256383', 'cpi_9606.ENSP00000297268'], ['cpi_9606.ENSP00000319170', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000386884', 'cpi_9606.ENSP00000338018', 'cpi_9606.ENSP00000387888'], ['cpi_9606.ENSP00000434516', 'cpi_9606.ENSP00000365380', 'cpi_9606.ENSP00000234961', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000341189'], ['cpi_9606.ENSP00000355536', 'cpi_9606.ENSP00000321999', 'cpi_9606.ENSP00000308032', 'cpi_9606.ENSP00000348461', 'cpi_9606.ENSP00000427562'], ['cpi_9606.ENSP00000375093', 'cpi_9606.ENSP00000344460', 'cpi_9606.ENSP00000419692', 'cpi_9606.ENSP00000362508', 'cpi_9606.ENSP00000368880'], ['cpi_9606.ENSP00000358525', 'cpi_9606.ENSP00000315011', 'cpi_9606.ENSP00000309103', 'cpi_9606.ENSP00000326219', 'cpi_9606.ENSP00000369050'], ['cpi_9606.ENSP00000226578', 'cpi_9606.ENSP00000393333', 'cpi_9606.ENSP00000254810', 'cpi_9606.ENSP00000333534', 'cpi_9606.ENSP00000239849'], ['cpi_9606.ENSP00000229135', 'cpi_9606.ENSP00000384957', 'cpi_9606.ENSP00000359635', 'cpi_9606.ENSP00000355317', 'cpi_9606.ENSP00000211122'], ['cpi_9606.ENSP00000261267', 'cpi_9606.ENSP00000276571', 'cpi_9606.ENSP00000248041', 'cpi_9606.ENSP00000344674', 'cpi_9606.ENSP00000340820'], ['cpi_9606.ENSP00000348775', 'cpi_9606.ENSP00000276414', 'cpi_9606.ENSP00000223095', 'cpi_9606.ENSP00000435777', 'cpi_9606.ENSP00000332679'], ['cpi_9606.ENSP00000342952', 'cpi_9606.ENSP00000288135', 'cpi_9606.ENSP00000387683', 'cpi_9606.ENSP00000296522', 'cpi_9606.ENSP00000290866'], ['cpi_9606.ENSP00000260302', 'cpi_9606.ENSP00000242152', 'cpi_9606.ENSP00000236671', 'cpi_9606.ENSP00000296674', 'cpi_9606.ENSP00000251566'], ['cpi_9606.ENSP00000362401', 'cpi_9606.ENSP00000353483', 'cpi_9606.ENSP00000348645', 'cpi_9606.ENSP00000355533', 'cpi_9606.ENSP00000252321'], ['cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000336630', 'cpi_9606.ENSP00000368752', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000359096'], ['cpi_9606.ENSP00000217386', 'cpi_9606.ENSP00000314508', 'cpi_9606.ENSP00000253727', 'cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000360247'], ['cpi_9606.ENSP00000317842', 'cpi_9606.ENSP00000297469', 'cpi_9606.ENSP00000219919', 'cpi_9606.ENSP00000341885', 'cpi_9606.ENSP00000331736'], ['cpi_9606.ENSP00000307697', 'cpi_9606.ENSP00000407375', 'cpi_9606.ENSP00000305651', 'cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000295453'], ['cpi_9606.ENSP00000338082', 'cpi_9606.ENSP00000367207', 'cpi_9606.ENSP00000335544', 'cpi_9606.ENSP00000288602', 'cpi_9606.ENSP00000363832'], ['cpi_9606.ENSP00000337459', 'cpi_9606.ENSP00000352035', 'cpi_9606.ENSP00000466799', 'cpi_9606.ENSP00000359532', 'cpi_9606.ENSP00000301633'], ['cpi_9606.ENSP00000340684', 'cpi_9606.ENSP00000260227', 'cpi_9606.ENSP00000261465', 'cpi_9606.ENSP00000349577', 'cpi_9606.ENSP00000308549'], ['cpi_9606.ENSP00000246657', 'cpi_9606.ENSP00000277508', 'cpi_9606.ENSP00000342307', 'cpi_9606.ENSP0000021

🔄 Processing features: 100%|██████████| 1607/1607 [06:51<00:00,  3.90feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000356094', 'cpi_9606.ENSP00000428340'], ['cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000263088'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000237014', 'cpi_9606.ENSP00000350348', 'cpi_9606.ENSP00000395653', 'cpi_9606.ENSP00000275300'], ['cpi_9606.ENSP00000231509', 'cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000262407', 'cpi_9606.ENSP00000262888'], ['cpi_9606.ENSP00000360372', 'cpi_9606.ENSP00000263321', 'cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000265171', 'cpi_9606.ENSP00000355629'], ['cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000277010', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000266376', 'cpi_9606.ENSP00000351957'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000360773'], ['cpi_9606.ENSP00000265724', 'cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000304822', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000263126'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000309818', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000285381', 'cpi_9606.ENSP00000369375'], ['cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000378699', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000320866'], ['cpi_9606.ENSP00000264381', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000275525', 'cpi_9606.ENSP00000388648'], ['cpi_9606.ENSP00000369960', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000358548'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000384957', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000261937'], ['cpi_9606.ENSP00000311032', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000367848', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000216465'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000374323', 'cpi_9606.ENSP00000312664', 'cpi_9606.ENSP00000359353'], ['cpi_9606.ENSP00000272190', 'cpi_9606.ENSP00000225474', 'cpi_9606.ENSP00000372547', 'cpi_9606.ENSP00000417229', 'cpi_9606.ENSP00000295834'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000311165', 'cpi_9606.ENSP00000261196'], ['cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000305372', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000216962', 'cpi_9606.ENSP00000279178'], ['cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000327431', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000398632'], ['cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000301634', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000354476'], ['cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000316786', 'cpi_9606.ENSP00000367851', 'cpi_9606.ENSP00000301891'], ['cpi_9606.ENSP00000411532', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000261799'], ['cpi_9606.ENSP00000367959', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000340820', 'cpi_9606.ENSP00000374353'], ['cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000236850', 'cpi_9606.ENSP00000367102'], ['cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000317379', 'cpi_9606.ENSP00000463999'], ['cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000252519', 'cpi_9606.ENSP00000301178', 'cpi_9606.ENSP00000283635', 'cpi_9606.ENSP00000352900'], ['cpi_9606.ENSP00000344456', 'cpi_9606.ENSP00000389414', 'cpi_9606.ENSP00000256958', 'cpi_9606.ENSP00000258749', 'cpi_9606.ENSP00000023897'], ['cpi_9606.ENSP00000270202', 'cpi_9606.ENSP00000319170', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000356671'], ['cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000357204', 'cpi_9606.ENSP00000302111', 'cpi_9606.ENSP00000337335', 'cpi_9606.ENSP00000257290'], ['cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000220764', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000251535'], ['cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000363822', 'cpi_9606.ENSP00000274547', 'cpi_9606.ENSP00000354610', 'cpi_9606.ENSP00000334198'], ['cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000262441', 'cpi_9606.ENSP00000233242', 'cpi_9606.ENSP00000319788', 'cpi_9606.ENSP00000386306'], ['cpi_9606.ENSP00000280155', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000314508', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000343204'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000362353', 'cpi_9606.ENSP00000306100', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000332296'], ['cpi_9606.ENSP00000270349', 'cpi_9606.ENSP00000303830', 'cpi_9606.ENSP00000361666', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000375809'], ['cpi_9606.ENSP00000258743', 'cpi_9606.ENSP00000326219', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000342235', 'cpi_9606.ENSP00000293745'], ['cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000237612', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000242057'], ['cpi_9606.ENSP00000295897', 'cpi_9606.ENSP00000378517', 'cpi_9606.ENSP00000347942', 'cpi_9606.ENSP00000248572', 'cpi_9606.ENSP00000283254'], ['cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000304915', 'cpi_9606.ENSP00000369816', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000359285'], ['cpi_9606.ENSP00000234111', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000389338', 'cpi_9606.ENSP00000299267', 'cpi_9606.ENSP00000245457'], ['cpi_9606.ENSP00000260433', 'cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000225927', 'cpi_9606.ENSP00000430684'], ['cpi_9606.ENSP00000398698', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000394936', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000221421'], ['cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000386284', 'cpi_9606.ENSP00000321988', 'cpi_9606.ENSP00000260010', 'cpi_9606.ENSP00000312455'], ['cpi_9606.ENSP00000337450', 'cpi_9606.ENSP00000381333', 'cpi_9606.ENSP00000295731', 'cpi_9606.ENSP00000225964', 'cpi_9606.ENSP00000216037'], ['cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000366307', 'cpi_9606.ENSP00000252809', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000295454'], ['cpi_9606.ENSP00000337949', 'cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000331912', 'cpi_9606.ENSP00000278616'], ['cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000353224', 'cpi_9606.ENSP00000419782', 'cpi_9606.ENSP00000376943'], ['cpi_9606.ENSP00000352835', 'cpi_9606.ENSP00000368766', 'cpi_9606.ENSP00000221972', 'cpi_9606.ENSP00000326119', 'cpi_9606.ENSP00000333212'], ['cpi_9606.ENSP00000316244', 'cpi_9606.ENSP00000359478', 'cpi_9606.ENSP00000360493', 'cpi_9606.ENSP00000260649', 'cpi_9606.ENSP00000297316'], ['cpi_9606.ENSP00000354859', 'cpi_9606.ENSP00000405573', 'cpi_9606.ENSP00000344192', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000267101'], ['cpi_9606.ENSP00000297494', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000367608', 'cpi_9606.ENSP00000353791', 'cpi_9606.ENSP00000387946'], ['cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000387281', 'cpi_9606.ENSP00000434516', 'cpi_9606.ENSP00000410294', 'cpi_9606.ENSP00000264318'], ['cpi_9606.ENSP00000308541', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000332816', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000340691'], ['cpi_9606.ENSP00000356438', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000307599', 'cpi_9606.ENSP00000381097'], ['cpi_9606.ENSP00000330237', 'cpi_9606.ENSP00000397582', 'cpi_9606.ENSP00000349577', 'cpi_9606.ENSP00000307014', 'cpi_9606.ENSP00000311095'], ['cpi_9606.ENSP00000368438', 'cpi_9606.ENSP00000355930', 'cpi_9606.ENSP00000216392', 'cpi_9606.ENSP00000261693', 'cpi_9606.ENSP00000386029'], ['cpi_9606.ENSP00000358963', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000310928'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000231228', 'cpi_9606.ENSP00000273398', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000414334'], ['cpi_9606.ENSP00000258400', 'cpi_9606.ENSP00000307697', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000232219', 'cpi_9606.ENSP00000358595'], ['cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000252029', 'cpi_9606.ENSP00000294728', 'cpi_9606.ENSP00000295491'], ['cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000268035', 'cpi_9606.ENSP00000358424', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000296122'], ['cpi_9606.ENSP00000387662', 'cpi_9606.ENSP00000217961', 'cpi_9606.ENSP00000270776', 'cpi_9606.ENSP00000259089', 'cpi_9606.ENSP00000344352'], ['cpi_9606.ENSP00000257497', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000259396', 'cpi_9606.ENSP00000264818'], ['cpi_9606.ENSP00000215832', 'cpi_9606.ENSP00000471569', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000164139', 'cpi_9606.ENSP00000451040'], ['cpi_9606.ENSP00000386069', 'cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000259486', 'cpi_9606.ENSP00000355657', 'cpi_9606.ENSP00000308774'], ['cpi_9606.ENSP00000366506', 'cpi_9606.ENSP00000264162', 'cpi_9606.ENSP00000252486', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000241453'], ['cpi_9606.ENSP00000309845', 'cpi_9606.ENSP00000252945', 'cpi_9606.ENSP00000286301', 'cpi_9606.ENSP00000353915', 'cpi_9606.ENSP00000338548'], ['cpi_9606.ENSP00000306662', 'cpi_9606.ENSP00000338082', 'cpi_9606.ENSP00000309103', 'cpi_9606.ENSP00000317842', 'cpi_9606.ENSP00000267119'], ['cpi_9606.ENSP00000225831', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000259271', 'cpi_9606.ENSP00000276449', 'cpi_9606.ENSP00000448059'], ['cpi_9606.ENSP00000373169', 'cpi_9606.ENSP00000354850', 'cpi_9606.ENSP00000354394', 'cpi_9606.ENSP00000343040', 'cpi_9606.ENSP00000346534'], ['cpi_9606.ENSP00000306245', 'cpi_9606.ENSP00000359100', 'cpi_9606.ENSP00000398655', 'cpi_9606.ENSP00000370381', 'cpi_9606.ENSP00000457706'], ['cpi_9606.ENSP00000306512', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000220616', 'cpi_9606.ENSP00000346148', 'cpi_9606.ENSP00000264637'], ['cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000244741', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000309124'], ['cpi_9606.ENSP00000302811', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000000442'], ['cpi_9606.ENSP00000282753', 'cpi_9606.ENSP00000355759', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000282561', 'cpi_9606.ENSP00000353292'], ['cpi_9606.ENSP00000263025', 'cpi_9606.ENSP00000274793', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000270474', 'cpi_9606.ENSP00000310447'], ['cpi_9606.ENSP00000301974', 'cpi_9606.ENSP00000414303', 'cpi_9606.ENSP00000229319', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000357283'], ['cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000308165', 'cpi_9606.ENSP00000327652', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000307235'], ['cpi_9606.ENSP00000276198', 'cpi_9606.ENSP00000260302', 'cpi_9606.ENSP00000262948', 'cpi_9606.ENSP00000320935', 'cpi_9606.ENSP00000396320'], ['cpi_9606.ENSP00000369647', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000228872', 'cpi_9606.ENSP00000345502', 'cpi_9606.ENSP00000371929'], ['cpi_9606.ENSP00000264832', 'cpi_9606.ENSP00000352035', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000294954', 'cpi_9606.ENSP00000219700'], ['cpi_9606.ENSP00000269305', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000355920', 'cpi_9606.ENSP00000231454'], ['cpi_9606.ENSP00000360683', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000293288', 'cpi_9606.ENSP00000353472', 'cpi_9606.ENSP00000289753'], ['cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000339191', 'cpi_9606.ENSP00000355317', 'cpi_9606.ENSP00000393312', 'cpi_9606.ENSP00000454071'], ['cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000229447', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000304811'], ['cpi_9606.ENSP00000375066', 'cpi_9606.ENSP00000353679', 'cpi_9606.ENSP00000356954', 'cpi_9606.ENSP00000370473', 'cpi_9606.ENSP00000335511'], ['cpi_9606.ENSP00000361405', 'cpi_9606.ENSP00000262193', 'cpi_9606.ENSP00000470087', 'cpi_9606.ENSP00000305355', 'cpi_9606.ENSP00000300061'], ['cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000340943', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000361359', 'cpi_9606.ENSP00000358784'], ['cpi_9606.ENSP00000313661', 'cpi_9606.ENSP00000408695', 'cpi_9606.ENSP00000391676', 'cpi_9606.ENSP00000348069', 'cpi_9606.ENSP00000263980'], ['cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000318822', 'cpi_9606.ENSP00000349467', 'cpi_9606.ENSP00000263923'], ['cpi_9606.ENSP00000315644', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000176183', 'cpi_9606.ENSP00000287936', 'cpi_9606.ENSP00000176763'], ['cpi_9606.ENSP00000327801', 'cpi_9606.ENSP00000412237', 'cpi_9606.ENSP00000371554', 'cpi_9606.ENSP00000297991', 'cpi_9606.ENSP00000386171'], ['cpi_9606.ENSP00000302150', 'cpi_9606.ENSP00000234310', 'cpi_9606.ENSP00000362344', 'cpi_9606.ENSP00000264867', 'cpi_9606.ENSP00000277120'], ['cpi_9606.ENSP00000367309', 'cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000466799', 'cpi_9606.ENSP00000296871', 'cpi_9606.ENSP00000365663'], ['cpi_9606.ENSP00000254976', 'cpi_9606.ENSP00000296545', 'cpi_9606.ENSP00000265723', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000363832'], ['cpi_9606.ENSP00000299178', 'cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000348775', 'cpi_9606.ENSP00000327850', 'cpi_9606.ENSP00000218099'], ['cpi_9606.ENSP00000394624', 'cpi_9606.ENSP00000262160', 'cpi_9606.ENSP00000252804', 'cpi_9606.ENSP00000290349', 'cpi_9606.ENSP00000362649'], ['cpi_9606.ENSP00000222553', 'cpi_9606.ENSP00000264657', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000333496', 'cpi_9606.ENSP00000382659'], ['cpi_9606.ENSP00000327251', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000267843', 'cpi_9606.ENSP00000409612', 'cpi_9606.ENSP00000363812'], ['cpi_9606.ENSP00000270142', 'cpi_9606.ENSP00000400175', 'cpi_9606.ENSP00000428924', 'cpi_9606.ENSP00000357669', 'cpi_9606.ENSP00000385806'], ['cpi_9606.ENSP00000464149', 'cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000248553', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000323568'], ['cpi_9606.ENSP00000356729', 'cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000260227', 'cpi_9606.ENSP00000253004', 'cpi_9606.ENSP00000309757'], ['cpi_9606.ENSP00000354612', 'cpi_9606.ENSP00000359899', 'cpi_9606.ENSP00000252723', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000256383'], ['cpi_9606.ENSP00000217386', 'cpi_9606.ENSP00000352608', 'cpi_9606.ENSP00000226574', 'cpi_9606.ENSP00000330393', 'cpi_9606.ENSP00000361206'], ['cpi_9606.ENSP00000330032', 'cpi_9606.ENSP00000221930', 'cpi_9606.ENSP00000364805', 'cpi_9606.ENSP00000217305', 'cpi_9606.ENSP00000343477'], ['cpi_9606.ENSP00000356825', 'cpi_9606.ENSP00000329357', 'cpi_9606.ENSP00000360973', 'cpi_9606.ENSP00000297268', 'cpi_9606.ENSP00000222330'], ['cpi_9606.ENSP00000265572', 'cpi_9606.ENSP00000348645', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000348786'], ['cpi_9606.ENSP00000356022', 'cpi_9606.ENSP00000297258', 'cpi_9606.ENSP00000307766', 'cpi_9606.ENSP00000355778', 'cpi_9606.ENSP00000346768'], ['cpi_9606.ENSP00000380318', 'cpi_9606.ENSP00000260356', 'cpi_9606.ENSP00000225577', 'cpi_9606.ENSP00000287907', 'cpi_9606.ENSP00000418532'], ['cpi_9606.ENSP00000290866', 'cpi_9606.ENSP00000257068', 'cpi_9606.ENSP00000304845', 'cpi_9606.ENSP00000364802', 'cpi_9606.ENSP00000346901'], ['cpi_9606.ENSP00000362810', 'cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000200676', 'cpi_9606.ENSP00000347046'], ['cpi_9606.ENSP00000312652', 'cpi_9606.ENSP00000441691', 'cpi_9606.ENSP00000459962', 'cpi_9606.ENSP00000254079', 'cpi_9606.ENSP00000377192'], ['cpi_9606.ENSP00000229135', 'cpi_9606.ENSP00000359793', 'cpi_9606.ENSP00000225371', 'cpi_9606.ENSP00000359635', 'cpi_9606.ENSP00000216911'], ['cpi_9606.ENSP00000364035', 'cpi_9606.ENSP00000304895', 'cpi_9606.ENSP00000322924', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000312673'], ['cpi_9606.ENSP00000295598', 'cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000301633', 'cpi_9606.ENSP00000306129', 'cpi_9606.ENSP00000399168'], ['cpi_9606.ENSP00000370571', 'cpi_9606.ENSP00000305692', 'cpi_9606.ENSP00000347979', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000272167'], ['cpi_9606.ENSP00000263341', 'cpi_9606.ENSP00000359910', 'cpi_9606.ENSP00000370912', 'cpi_9606.ENSP00000386229', 'cpi_9606.ENSP00000365016'], ['cpi_9606.ENSP00000332369', 'cpi_9606.ENSP00000319591', 'cpi_9606.ENSP00000291294', 'cpi_9606.ENSP00000219919', 'cpi_9606.ENSP00000359663'], ['cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000331358', 'cpi_9606.ENSP00000356694', 'cpi_9606.ENSP00000297350', 'cpi_9606.ENSP00000353427'], ['cpi_9606.ENSP00000272298', 'cpi_9606.ENSP00000255465', 'cpi_9606.ENSP00000336630', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000384273'], ['cpi_9606.ENSP00000340684', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000320709', 'cpi_9606.ENSP00000380252', 'cpi_9606.ENSP00000264498'], ['cpi_9606.ENSP00000368305', 'cpi_9606.ENSP00000360266', 'cpi_9606.ENSP00000292513', 'cpi_9606.ENSP00000305221', 'cpi_9606.ENSP00000218388'], ['cpi_9606.ENSP00000287820', 'cpi_9606.ENSP00000295256', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000358730', 'cpi_9606.ENSP00000365012'], ['cpi_9606.ENSP00000324270', 'cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000332116', 'cpi_9606.ENSP00000362513', 'cpi_9606.ENSP00000220003'], ['cpi_9606.ENSP00000358525', 'cpi_9606.ENSP00000339527', 'cpi_9606.ENSP00000262461', 'cpi_9606.ENSP00000231449', 'cpi_9606.ENSP00000230671'], ['cpi_9606.ENSP00000373477', 'cpi_9606.ENSP00000358511', 'cpi_9606.ENSP00000427514', 'cpi_9606.ENSP00000362334', 'cpi_9606.ENSP00000337354'], ['cpi_9606.ENSP00000447378', 'cpi_9606.ENSP00000301146', 'cpi_9606.ENSP00000331746', 'cpi_9606.ENSP00000256442', 'cpi_9606.ENSP00000270570'], ['cpi_9606.ENSP00000322788', 'cpi_9606.ENSP00000341828', 'cpi_9606.ENSP00000263431', 'cpi_9606.ENSP00000360967', 'cpi_9606.ENSP00000311028'], ['cpi_9606.ENSP00000234961', 'cpi_9606.ENSP00000368880', 'cpi_9606.ENSP00000268053', 'cpi_9606.ENSP00000273550', 'cpi_9606.ENSP00000337825'], ['cpi_9606.ENSP00000372326', 'cpi_9606.ENSP00000451030', 'cpi_9606.ENSP00000341045', 'cpi_9606.ENSP00000241261', 'cpi_9606.ENSP00000288135'], ['cpi_9606.ENSP00000274026', 'cpi_9606.ENSP00000226413', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000269159', 'cpi_9606.ENSP00000355533'], ['cpi_9606.ENSP00000358327', 'cpi_9606.ENSP00000366416', 'cpi_9606.ENSP00000330484', 'cpi_9606.ENSP00000270625', 'cpi_9606.ENSP00000332679'], ['cpi_9606.ENSP00000275216', 'cpi_9606.ENSP00000288022', 'cpi_9606.ENSP00000236671', 'cpi_9606.ENSP00000369050', 'cpi_9606.ENSP00000383365'], ['cpi_9606.ENSP00000357981', 'cpi_9606.ENSP00000262735', 'cpi_9606.ENSP00000342560', 'cpi_9606.ENSP00000420487', 'cpi_9606.ENSP00000368727'], ['cpi_9606.ENSP00000264613', 'cpi_9606.ENSP00000368683', 'cpi_9606.ENSP00000301141', 'cpi_9606.ENSP00000321999', 'cpi_9606.ENSP00000348827'], ['cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000246657', 'cpi_9606.ENSP00000239849', 'cpi_9606.ENSP00000302967', 'cpi_9606.ENSP00000368104'], ['cpi_9606.ENSP00000337459', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000362401', 'cpi_9606.ENSP00000320401'], ['cpi_9606.ENSP00000275493', 'cpi_9606.ENSP00000292303', 'cpi_9606.ENSP00000272227', 'cpi_9606.ENSP00000362924', 'cpi_9606.ENSP00000361151'], ['cpi_9606.ENSP00000354511', 'cpi_9606.ENSP00000372023', 'cpi_9606.ENSP00000312029', 'cpi_9606.ENSP00000370373', 'cpi_9606.ENSP00000348461'], ['cpi_9606.ENSP00000265023', 'cpi_9606.ENSP00000331736', 'cpi_9606.ENSP00000435777', 'cpi_9606.ENSP00000354107', 'cpi_9606.ENSP00000303174'], ['cpi_9606.ENSP00000329623', 'cpi_9606.ENSP00000234389', 'cpi_9606.ENSP00000334105', 'cpi_9606.ENSP0000031

🔄 Processing features: 100%|██████████| 1607/1607 [06:51<00:00,  3.91feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'cpi_9606.ENSP00000326219', 'cpi_9606.ENSP00000356094', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000285381'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000274547', 'cpi_9606.ENSP00000301891', 'cpi_9606.ENSP00000395653'], ['cpi_9606.ENSP00000231509', 'cpi_9606.ENSP00000266376', 'cpi_9606.ENSP00000355629', 'cpi_9606.ENSP00000264318', 'cpi_9606.ENSP00000351957'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000367848', 'cpi_9606.ENSP00000286479'], ['cpi_9606.ENSP00000265724', 'cpi_9606.ENSP00000360773', 'cpi_9606.ENSP00000265294', 'cpi_9606.ENSP00000299178', 'cpi_9606.ENSP00000332296'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000295452', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000261799'], ['cpi_9606.ENSP00000360372', 'cpi_9606.ENSP00000309818', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000377947', 'cpi_9606.ENSP00000372547'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000359353', 'cpi_9606.ENSP00000374323', 'cpi_9606.ENSP00000260010'], ['cpi_9606.ENSP00000264381', 'cpi_9606.ENSP00000367102', 'cpi_9606.ENSP00000389338', 'cpi_9606.ENSP00000342235', 'cpi_9606.ENSP00000254227'], ['cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000277010', 'cpi_9606.ENSP00000356958', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000312664'], ['cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000330237', 'cpi_9606.ENSP00000283635', 'cpi_9606.ENSP00000261937', 'cpi_9606.ENSP00000245539'], ['cpi_9606.ENSP00000369960', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000225474', 'cpi_9606.ENSP00000299267'], ['cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000263321', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000410732'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000361206'], ['cpi_9606.ENSP00000272190', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000354476', 'cpi_9606.ENSP00000457706'], ['cpi_9606.ENSP00000311032', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000394936'], ['cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000299847', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000414334', 'cpi_9606.ENSP00000386029'], ['cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000337335', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000359334'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000300900', 'cpi_9606.ENSP00000216037', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000343477'], ['cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000257290'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000358548', 'cpi_9606.ENSP00000352011', 'cpi_9606.ENSP00000295454', 'cpi_9606.ENSP00000286301'], ['cpi_9606.ENSP00000316786', 'cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000261693', 'cpi_9606.ENSP00000285930'], ['cpi_9606.ENSP00000305372', 'cpi_9606.ENSP00000233242', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000301178', 'cpi_9606.ENSP00000279178'], ['cpi_9606.ENSP00000260433', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000430684', 'cpi_9606.ENSP00000347942', 'cpi_9606.ENSP00000386306'], ['cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000301974', 'cpi_9606.ENSP00000346598', 'cpi_9606.ENSP00000344192', 'cpi_9606.ENSP00000326119'], ['cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000357204', 'cpi_9606.ENSP00000319788', 'cpi_9606.ENSP00000417229', 'cpi_9606.ENSP00000369816'], ['cpi_9606.ENSP00000237014', 'cpi_9606.ENSP00000216862', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000354558', 'cpi_9606.ENSP00000412673'], ['cpi_9606.ENSP00000367959', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000267101', 'cpi_9606.ENSP00000200676', 'cpi_9606.ENSP00000352900'], ['cpi_9606.ENSP00000220764', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000451040', 'cpi_9606.ENSP00000376943', 'cpi_9606.ENSP00000307599'], ['cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000398632', 'cpi_9606.ENSP00000332369', 'cpi_9606.ENSP00000308165', 'cpi_9606.ENSP00000341390'], ['cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000367851', 'cpi_9606.ENSP00000275525', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000343782'], ['cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000331912', 'cpi_9606.ENSP00000307014'], ['cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000328968', 'cpi_9606.ENSP00000361666', 'cpi_9606.ENSP00000306606', 'cpi_9606.ENSP00000339527'], ['cpi_9606.ENSP00000350348', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000354394', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000343040'], ['cpi_9606.ENSP00000295897', 'cpi_9606.ENSP00000378517', 'cpi_9606.ENSP00000241453', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000259396'], ['cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000363822', 'cpi_9606.ENSP00000471569', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000242057'], ['cpi_9606.ENSP00000344456', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000320935', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000262888'], ['cpi_9606.ENSP00000270142', 'cpi_9606.ENSP00000294728', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000259089'], ['cpi_9606.ENSP00000270349', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000312455', 'cpi_9606.ENSP00000381097', 'cpi_9606.ENSP00000320025'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000262441', 'cpi_9606.ENSP00000369530', 'cpi_9606.ENSP00000351209', 'cpi_9606.ENSP00000304822'], ['cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000344352', 'cpi_9606.ENSP00000389414'], ['cpi_9606.ENSP00000270202', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000387946', 'cpi_9606.ENSP00000258749', 'cpi_9606.ENSP00000295491'], ['cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000309124', 'cpi_9606.ENSP00000251535'], ['cpi_9606.ENSP00000297494', 'cpi_9606.ENSP00000308774', 'cpi_9606.ENSP00000370381', 'cpi_9606.ENSP00000264637', 'cpi_9606.ENSP00000229264'], ['cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000414303', 'cpi_9606.ENSP00000402152', 'cpi_9606.ENSP00000356954', 'cpi_9606.ENSP00000435591'], ['cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000263341', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000307240', 'cpi_9606.ENSP00000428340'], ['cpi_9606.ENSP00000368438', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000221972', 'cpi_9606.ENSP00000263126', 'cpi_9606.ENSP00000463999'], ['cpi_9606.ENSP00000411532', 'cpi_9606.ENSP00000231228', 'cpi_9606.ENSP00000333212', 'cpi_9606.ENSP00000000442', 'cpi_9606.ENSP00000470087'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000322617', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000291294', 'cpi_9606.ENSP00000252519'], ['cpi_9606.ENSP00000284981', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000296871', 'cpi_9606.ENSP00000291700'], ['cpi_9606.ENSP00000398698', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000349577', 'cpi_9606.ENSP00000293745', 'cpi_9606.ENSP00000296370'], ['cpi_9606.ENSP00000316244', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000262461', 'cpi_9606.ENSP00000256958'], ['cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000355759', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000301645'], ['cpi_9606.ENSP00000337450', 'cpi_9606.ENSP00000340943', 'cpi_9606.ENSP00000176763', 'cpi_9606.ENSP00000364802', 'cpi_9606.ENSP00000282561'], ['cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000221421', 'cpi_9606.ENSP00000231454', 'cpi_9606.ENSP00000348069', 'cpi_9606.ENSP00000267119'], ['cpi_9606.ENSP00000366506', 'cpi_9606.ENSP00000264162', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000410294', 'cpi_9606.ENSP00000356436'], ['cpi_9606.ENSP00000337949', 'cpi_9606.ENSP00000354850', 'cpi_9606.ENSP00000278616', 'cpi_9606.ENSP00000368253', 'cpi_9606.ENSP00000262367'], ['cpi_9606.ENSP00000280155', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000318822', 'cpi_9606.ENSP00000427514', 'cpi_9606.ENSP00000359635'], ['cpi_9606.ENSP00000258743', 'cpi_9606.ENSP00000264818', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000297350', 'cpi_9606.ENSP00000353292'], ['cpi_9606.ENSP00000387662', 'cpi_9606.ENSP00000311469', 'cpi_9606.ENSP00000361359', 'cpi_9606.ENSP00000252809', 'cpi_9606.ENSP00000287766'], ['cpi_9606.ENSP00000234111', 'cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000289753', 'cpi_9606.ENSP00000359663'], ['cpi_9606.ENSP00000354612', 'cpi_9606.ENSP00000222330', 'cpi_9606.ENSP00000287907', 'cpi_9606.ENSP00000360493', 'cpi_9606.ENSP00000261196'], ['cpi_9606.ENSP00000387281', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000330393', 'cpi_9606.ENSP00000226574', 'cpi_9606.ENSP00000263923'], ['cpi_9606.ENSP00000236850', 'cpi_9606.ENSP00000274026', 'cpi_9606.ENSP00000293288', 'cpi_9606.ENSP00000276198', 'cpi_9606.ENSP00000358595'], ['cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000300061', 'cpi_9606.ENSP00000321988', 'cpi_9606.ENSP00000365380', 'cpi_9606.ENSP00000386069'], ['cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000448059', 'cpi_9606.ENSP00000382659'], ['cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000309649', 'cpi_9606.ENSP00000310928', 'cpi_9606.ENSP00000358784'], ['cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000338548', 'cpi_9606.ENSP00000252723', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000274793'], ['cpi_9606.ENSP00000354859', 'cpi_9606.ENSP00000359478', 'cpi_9606.ENSP00000362036', 'cpi_9606.ENSP00000297268', 'cpi_9606.ENSP00000428924'], ['cpi_9606.ENSP00000356022', 'cpi_9606.ENSP00000373169', 'cpi_9606.ENSP00000296122', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000445340'], ['cpi_9606.ENSP00000356438', 'cpi_9606.ENSP00000410076', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000312029', 'cpi_9606.ENSP00000345659'], ['cpi_9606.ENSP00000225831', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000357283', 'cpi_9606.ENSP00000313661'], ['cpi_9606.ENSP00000306662', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000366307', 'cpi_9606.ENSP00000268251'], ['cpi_9606.ENSP00000405573', 'cpi_9606.ENSP00000264832', 'cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000311028'], ['cpi_9606.ENSP00000308541', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000368766', 'cpi_9606.ENSP00000343204', 'cpi_9606.ENSP00000255465'], ['cpi_9606.ENSP00000352835', 'cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000258400', 'cpi_9606.ENSP00000311095', 'cpi_9606.ENSP00000267843'], ['cpi_9606.ENSP00000358963', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000295834', 'cpi_9606.ENSP00000225964'], ['cpi_9606.ENSP00000306245', 'cpi_9606.ENSP00000358223', 'cpi_9606.ENSP00000353878', 'cpi_9606.ENSP00000360967', 'cpi_9606.ENSP00000276449'], ['cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000248553', 'cpi_9606.ENSP00000323568', 'cpi_9606.ENSP00000340820', 'cpi_9606.ENSP00000341045'], ['cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000263980', 'cpi_9606.ENSP00000351885', 'cpi_9606.ENSP00000176183', 'cpi_9606.ENSP00000314099'], ['cpi_9606.ENSP00000215832', 'cpi_9606.ENSP00000344674', 'cpi_9606.ENSP00000216962', 'cpi_9606.ENSP00000260356', 'cpi_9606.ENSP00000327652'], ['cpi_9606.ENSP00000306512', 'cpi_9606.ENSP00000220616', 'cpi_9606.ENSP00000270776', 'cpi_9606.ENSP00000385806', 'cpi_9606.ENSP00000306129'], ['cpi_9606.ENSP00000296545', 'cpi_9606.ENSP00000254976', 'cpi_9606.ENSP00000265723', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000252029'], ['cpi_9606.ENSP00000263025', 'cpi_9606.ENSP00000467676', 'cpi_9606.ENSP00000263377', 'cpi_9606.ENSP00000370473', 'cpi_9606.ENSP00000307766'], ['cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000379140', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000252486'], ['cpi_9606.ENSP00000378699', 'cpi_9606.ENSP00000464149', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000321999', 'cpi_9606.ENSP00000353427'], ['cpi_9606.ENSP00000309845', 'cpi_9606.ENSP00000301146', 'cpi_9606.ENSP00000353915', 'cpi_9606.ENSP00000365663', 'cpi_9606.ENSP00000355657'], ['cpi_9606.ENSP00000269305', 'cpi_9606.ENSP00000292896', 'cpi_9606.ENSP00000261835', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000245457'], ['cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000329623', 'cpi_9606.ENSP00000363827', 'cpi_9606.ENSP00000356832', 'cpi_9606.ENSP00000337773'], ['cpi_9606.ENSP00000360683', 'cpi_9606.ENSP00000226730', 'cpi_9606.ENSP00000372023', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000362401'], ['cpi_9606.ENSP00000369647', 'cpi_9606.ENSP00000302111', 'cpi_9606.ENSP00000305221', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000296674'], ['cpi_9606.ENSP00000362353', 'cpi_9606.ENSP00000252945', 'cpi_9606.ENSP00000263464', 'cpi_9606.ENSP00000216185', 'cpi_9606.ENSP00000356694'], ['cpi_9606.ENSP00000312652', 'cpi_9606.ENSP00000275216', 'cpi_9606.ENSP00000219919', 'cpi_9606.ENSP00000254488', 'cpi_9606.ENSP00000356150'], ['cpi_9606.ENSP00000302150', 'cpi_9606.ENSP00000364212', 'cpi_9606.ENSP00000347979', 'cpi_9606.ENSP00000292513', 'cpi_9606.ENSP00000329357'], ['cpi_9606.ENSP00000261205', 'cpi_9606.ENSP00000412237', 'cpi_9606.ENSP00000251453', 'cpi_9606.ENSP00000353791', 'cpi_9606.ENSP00000264657'], ['cpi_9606.ENSP00000303522', 'cpi_9606.ENSP00000353731', 'cpi_9606.ENSP00000232219', 'cpi_9606.ENSP00000282397', 'cpi_9606.ENSP00000256119'], ['cpi_9606.ENSP00000302811', 'cpi_9606.ENSP00000356729', 'cpi_9606.ENSP00000365016', 'cpi_9606.ENSP00000287936', 'cpi_9606.ENSP00000254810'], ['cpi_9606.ENSP00000237612', 'cpi_9606.ENSP00000352608', 'cpi_9606.ENSP00000355778', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000264867'], ['cpi_9606.ENSP00000375066', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000219700', 'cpi_9606.ENSP00000221515', 'cpi_9606.ENSP00000196551'], ['cpi_9606.ENSP00000282753', 'cpi_9606.ENSP00000216117', 'cpi_9606.ENSP00000310447', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000252321'], ['cpi_9606.ENSP00000274353', 'cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000262948', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000155840'], ['cpi_9606.ENSP00000304915', 'cpi_9606.ENSP00000367309', 'cpi_9606.ENSP00000433821', 'cpi_9606.ENSP00000304845', 'cpi_9606.ENSP00000263686'], ['cpi_9606.ENSP00000330032', 'cpi_9606.ENSP00000384273', 'cpi_9606.ENSP00000285979', 'cpi_9606.ENSP00000359793', 'cpi_9606.ENSP00000270474'], ['cpi_9606.ENSP00000340684', 'cpi_9606.ENSP00000319591', 'cpi_9606.ENSP00000241261', 'cpi_9606.ENSP00000393312', 'cpi_9606.ENSP00000239849'], ['cpi_9606.ENSP00000361405', 'cpi_9606.ENSP00000355325', 'cpi_9606.ENSP00000384957', 'cpi_9606.ENSP00000277120', 'cpi_9606.ENSP00000275300'], ['cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000377192', 'cpi_9606.ENSP00000368683', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000367608'], ['cpi_9606.ENSP00000315644', 'cpi_9606.ENSP00000322924', 'cpi_9606.ENSP00000368880', 'cpi_9606.ENSP00000268053', 'cpi_9606.ENSP00000307235'], ['cpi_9606.ENSP00000268035', 'cpi_9606.ENSP00000374265', 'cpi_9606.ENSP00000336630', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000363512'], ['cpi_9606.ENSP00000396704', 'cpi_9606.ENSP00000355930', 'cpi_9606.ENSP00000304408', 'cpi_9606.ENSP00000270625', 'cpi_9606.ENSP00000331358'], ['cpi_9606.ENSP00000287820', 'cpi_9606.ENSP00000220003', 'cpi_9606.ENSP00000354107', 'cpi_9606.ENSP00000358730', 'cpi_9606.ENSP00000303174'], ['cpi_9606.ENSP00000408695', 'cpi_9606.ENSP00000280357', 'cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000225577'], ['cpi_9606.ENSP00000290866', 'cpi_9606.ENSP00000287641', 'cpi_9606.ENSP00000388648', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000435777'], ['cpi_9606.ENSP00000327801', 'cpi_9606.ENSP00000239938', 'cpi_9606.ENSP00000355317', 'cpi_9606.ENSP00000266682', 'cpi_9606.ENSP00000419782'], ['cpi_9606.ENSP00000381333', 'cpi_9606.ENSP00000306100', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000216797', 'cpi_9606.ENSP00000332816'], ['cpi_9606.ENSP00000356825', 'cpi_9606.ENSP00000228872', 'cpi_9606.ENSP00000360973', 'cpi_9606.ENSP00000305302', 'cpi_9606.ENSP00000318646'], ['cpi_9606.ENSP00000217386', 'cpi_9606.ENSP00000314508', 'cpi_9606.ENSP00000380252', 'cpi_9606.ENSP00000341885', 'cpi_9606.ENSP00000386171'], ['cpi_9606.ENSP00000349467', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000303424', 'cpi_9606.ENSP00000330199', 'cpi_9606.ENSP00000309757'], ['cpi_9606.ENSP00000229447', 'cpi_9606.ENSP00000231449', 'cpi_9606.ENSP00000358327', 'cpi_9606.ENSP00000379339', 'cpi_9606.ENSP00000352584'], ['cpi_9606.ENSP00000262407', 'cpi_9606.ENSP00000262735', 'cpi_9606.ENSP00000338627', 'cpi_9606.ENSP00000342560', 'cpi_9606.ENSP00000301633'], ['cpi_9606.ENSP00000373477', 'cpi_9606.ENSP00000303830', 'cpi_9606.ENSP00000264498', 'cpi_9606.ENSP00000308549', 'cpi_9606.ENSP00000346298'], ['cpi_9606.ENSP00000260302', 'cpi_9606.ENSP00000369050', 'cpi_9606.ENSP00000359532', 'cpi_9606.ENSP00000317379', 'cpi_9606.ENSP00000233146'], ['cpi_9606.ENSP00000394624', 'cpi_9606.ENSP00000262160', 'cpi_9606.ENSP00000276431', 'cpi_9606.ENSP00000429374', 'cpi_9606.ENSP00000260970'], ['cpi_9606.ENSP00000295598', 'cpi_9606.ENSP00000360266', 'cpi_9606.ENSP00000294954', 'cpi_9606.ENSP00000320709', 'cpi_9606.ENSP00000420168'], ['cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000303452', 'cpi_9606.ENSP00000256383'], ['cpi_9606.ENSP00000359899', 'cpi_9606.ENSP00000394033', 'cpi_9606.ENSP00000301141', 'cpi_9606.ENSP00000218388', 'cpi_9606.ENSP00000288135'], ['cpi_9606.ENSP00000265572', 'cpi_9606.ENSP00000252804', 'cpi_9606.ENSP00000418960', 'cpi_9606.ENSP00000454071', 'cpi_9606.ENSP00000369757'], ['cpi_9606.ENSP00000447378', 'cpi_9606.ENSP00000338018', 'cpi_9606.ENSP00000320401', 'cpi_9606.ENSP00000349003', 'cpi_9606.ENSP00000419692'], ['cpi_9606.ENSP00000298171', 'cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000417281', 'cpi_9606.ENSP00000223095', 'cpi_9606.ENSP00000459962'], ['cpi_9606.ENSP00000362810', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000244741', 'cpi_9606.ENSP00000308032', 'cpi_9606.ENSP00000359096'], ['cpi_9606.ENSP00000331602', 'cpi_9606.ENSP00000234961', 'cpi_9606.ENSP00000304895', 'cpi_9606.ENSP00000357981', 'cpi_9606.ENSP00000296522'], ['cpi_9606.ENSP00000219070', 'cpi_9606.ENSP00000398655', 'cpi_9606.ENSP00000338082', 'cpi_9606.ENSP00000355920', 'cpi_9606.ENSP00000253727'], ['cpi_9606.ENSP00000327251', 'cpi_9606.ENSP00000356671', 'cpi_9606.ENSP00000349576', 'cpi_9606.ENSP00000307445', 'cpi_9606.ENSP00000362508'], ['cpi_9606.ENSP00000397582', 'cpi_9606.ENSP00000393333', 'cpi_9606.ENSP00000309103', 'cpi_9606.ENSP00000349252', 'cpi_9606.ENSP00000222381'], ['cpi_9606.ENSP00000307697', 'cpi_9606.ENSP00000321106', 'cpi_9606.ENSP00000400175', 'cpi_9606.ENSP00000333534', 'cpi_9606.ENSP00000362649'], ['cpi_9606.ENSP00000337459', 'cpi_9606.ENSP00000427562', 'cpi_9606.ENSP00000466799', 'cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000303686'], ['cpi_9606.ENSP00000222553', 'cpi_9606.ENSP00000451030', 'cpi_9606.ENSP00000265403', 'cpi_9606.ENSP00000348645', 'cpi_9606.ENSP00000290349'], ['cpi_9606.ENSP00000320866', 'cpi_9606.ENSP00000261465', 'cpi_9606.ENSP00000407375', 'cpi_9606.ENSP00000368104', 'cpi_9606.ENSP00000307259'], ['cpi_9606.ENSP00000324270', 'cpi_9606.ENSP00000234389', 'cpi_9606.ENSP00000387683', 'cpi_9606.ENSP00000351908', 'cpi_9606.ENSP00000225371'], ['cpi_9606.ENSP00000348775', 'cpi_9606.ENSP00000335657', 'cpi_9606.ENSP00000269571', 'cpi_9606.ENSP00000431512', 'cpi_9606.ENSP00000257068'], ['cpi_9606.ENSP00000272847', 'cpi_9606.ENSP00000222481', 'cpi_9606.ENSP00000341189', 'cpi_9606.ENSP00000272298', 'cpi_9606.ENSP00000212015'], ['cpi_9606.ENSP00000380318', 'cpi_9606.ENSP00000334246', 'cpi_9606.ENSP00000302846', 'cpi_9606.ENSP0000033

🔄 Processing features: 100%|██████████| 1607/1607 [06:52<00:00,  3.90feat/s]

XofN_groups: [['cpi_9606.ENSP00000337915', 'cpi_9606.ENSP00000319170', 'cpi_9606.ENSP00000285930', 'cpi_9606.ENSP00000359424', 'cpi_9606.ENSP00000356094'], ['cpi_9606.ENSP00000231509', 'cpi_9606.ENSP00000266376', 'cpi_9606.ENSP00000355629', 'cpi_9606.ENSP00000395653', 'cpi_9606.ENSP00000264318'], ['cpi_9606.ENSP00000336528', 'cpi_9606.ENSP00000380247', 'cpi_9606.ENSP00000301891', 'cpi_9606.ENSP00000351957', 'cpi_9606.ENSP00000372547'], ['cpi_9606.ENSP00000260682', 'cpi_9606.ENSP00000347754', 'cpi_9606.ENSP00000262441', 'cpi_9606.ENSP00000263126', 'cpi_9606.ENSP00000430684'], ['cpi_9606.ENSP00000237014', 'cpi_9606.ENSP00000390600', 'cpi_9606.ENSP00000277010', 'cpi_9606.ENSP00000274547', 'cpi_9606.ENSP00000216862'], ['cpi_9606.ENSP00000264381', 'cpi_9606.ENSP00000319788', 'cpi_9606.ENSP00000342235', 'cpi_9606.ENSP00000326119', 'cpi_9606.ENSP00000414334'], ['cpi_9606.ENSP00000342007', 'cpi_9606.ENSP00000321326', 'cpi_9606.ENSP00000299267', 'cpi_9606.ENSP00000429374', 'cpi_9606.ENSP00000261799'], ['cpi_9606.ENSP00000360372', 'cpi_9606.ENSP00000309818', 'cpi_9606.ENSP00000155840', 'cpi_9606.ENSP00000363812', 'cpi_9606.ENSP00000360773'], ['cpi_9606.ENSP00000353820', 'cpi_9606.ENSP00000410732', 'cpi_9606.ENSP00000357068', 'cpi_9606.ENSP00000286648', 'cpi_9606.ENSP00000261937'], ['cpi_9606.ENSP00000263321', 'cpi_9606.ENSP00000385026', 'cpi_9606.ENSP00000325120', 'cpi_9606.ENSP00000345708', 'cpi_9606.ENSP00000332369'], ['cpi_9606.ENSP00000263817', 'cpi_9606.ENSP00000350348', 'cpi_9606.ENSP00000286479', 'cpi_9606.ENSP00000309572', 'cpi_9606.ENSP00000295491'], ['cpi_9606.ENSP00000311032', 'cpi_9606.ENSP00000295454', 'cpi_9606.ENSP00000349320', 'cpi_9606.ENSP00000003100', 'cpi_9606.ENSP00000299847'], ['cpi_9606.ENSP00000206249', 'cpi_9606.ENSP00000359285', 'cpi_9606.ENSP00000216540', 'cpi_9606.ENSP00000331912', 'cpi_9606.ENSP00000354476'], ['cpi_9606.ENSP00000303211', 'cpi_9606.ENSP00000342850', 'cpi_9606.ENSP00000225474', 'cpi_9606.ENSP00000288139', 'cpi_9606.ENSP00000417229'], ['cpi_9606.ENSP00000265724', 'cpi_9606.ENSP00000357981', 'cpi_9606.ENSP00000337335', 'cpi_9606.ENSP00000412673', 'cpi_9606.ENSP00000352011'], ['cpi_9606.ENSP00000369960', 'cpi_9606.ENSP00000443194', 'cpi_9606.ENSP00000365686', 'cpi_9606.ENSP00000292427', 'cpi_9606.ENSP00000377947'], ['cpi_9606.ENSP00000319984', 'cpi_9606.ENSP00000343925', 'cpi_9606.ENSP00000301634', 'cpi_9606.ENSP00000376432', 'cpi_9606.ENSP00000200676'], ['cpi_9606.ENSP00000283916', 'cpi_9606.ENSP00000354610', 'cpi_9606.ENSP00000374323', 'cpi_9606.ENSP00000312664', 'cpi_9606.ENSP00000295452'], ['cpi_9606.ENSP00000261755', 'cpi_9606.ENSP00000366506', 'cpi_9606.ENSP00000262999', 'cpi_9606.ENSP00000023897', 'cpi_9606.ENSP00000297350'], ['cpi_9606.ENSP00000272190', 'cpi_9606.ENSP00000411593', 'cpi_9606.ENSP00000369375', 'cpi_9606.ENSP00000389338', 'cpi_9606.ENSP00000301146'], ['cpi_9606.ENSP00000305372', 'cpi_9606.ENSP00000264382', 'cpi_9606.ENSP00000245539', 'cpi_9606.ENSP00000332296', 'cpi_9606.ENSP00000265294'], ['cpi_9606.ENSP00000241052', 'cpi_9606.ENSP00000355192', 'cpi_9606.ENSP00000274545', 'cpi_9606.ENSP00000352900', 'cpi_9606.ENSP00000348069'], ['cpi_9606.ENSP00000260433', 'cpi_9606.ENSP00000352608', 'cpi_9606.ENSP00000410076', 'cpi_9606.ENSP00000359353', 'cpi_9606.ENSP00000351209'], ['cpi_9606.ENSP00000270142', 'cpi_9606.ENSP00000260356', 'cpi_9606.ENSP00000367102', 'cpi_9606.ENSP00000367848', 'cpi_9606.ENSP00000257290'], ['cpi_9606.ENSP00000306490', 'cpi_9606.ENSP00000363822', 'cpi_9606.ENSP00000348897', 'cpi_9606.ENSP00000283254', 'cpi_9606.ENSP00000252519'], ['cpi_9606.ENSP00000261416', 'cpi_9606.ENSP00000337949', 'cpi_9606.ENSP00000303540', 'cpi_9606.ENSP00000372023', 'cpi_9606.ENSP00000275525'], ['cpi_9606.ENSP00000358301', 'cpi_9606.ENSP00000255409', 'cpi_9606.ENSP00000233242', 'cpi_9606.ENSP00000361206', 'cpi_9606.ENSP00000471569'], ['cpi_9606.ENSP00000344456', 'cpi_9606.ENSP00000408860', 'cpi_9606.ENSP00000359334', 'cpi_9606.ENSP00000353362', 'cpi_9606.ENSP00000320935'], ['cpi_9606.ENSP00000312286', 'cpi_9606.ENSP00000262186', 'cpi_9606.ENSP00000349252', 'cpi_9606.ENSP00000279178', 'cpi_9606.ENSP00000386029'], ['cpi_9606.ENSP00000324648', 'cpi_9606.ENSP00000282753', 'cpi_9606.ENSP00000241600', 'cpi_9606.ENSP00000358548', 'cpi_9606.ENSP00000344192'], ['cpi_9606.ENSP00000270349', 'cpi_9606.ENSP00000291295', 'cpi_9606.ENSP00000260010', 'cpi_9606.ENSP00000251535', 'cpi_9606.ENSP00000267101'], ['cpi_9606.ENSP00000270202', 'cpi_9606.ENSP00000386306', 'cpi_9606.ENSP00000335592', 'cpi_9606.ENSP00000298472', 'cpi_9606.ENSP00000387946'], ['cpi_9606.ENSP00000316786', 'cpi_9606.ENSP00000261205', 'cpi_9606.ENSP00000364310', 'cpi_9606.ENSP00000308165', 'cpi_9606.ENSP00000402152'], ['cpi_9606.ENSP00000367959', 'cpi_9606.ENSP00000252029', 'cpi_9606.ENSP00000242057', 'cpi_9606.ENSP00000427514', 'cpi_9606.ENSP00000000442'], ['cpi_9606.ENSP00000361125', 'cpi_9606.ENSP00000371985', 'cpi_9606.ENSP00000420168', 'cpi_9606.ENSP00000264637', 'cpi_9606.ENSP00000351885'], ['cpi_9606.ENSP00000264708', 'cpi_9606.ENSP00000286301', 'cpi_9606.ENSP00000359663', 'cpi_9606.ENSP00000394936', 'cpi_9606.ENSP00000370381'], ['cpi_9606.ENSP00000284981', 'cpi_9606.ENSP00000343477', 'cpi_9606.ENSP00000259396', 'cpi_9606.ENSP00000307599', 'cpi_9606.ENSP00000241453'], ['cpi_9606.ENSP00000280155', 'cpi_9606.ENSP00000222381', 'cpi_9606.ENSP00000302111', 'cpi_9606.ENSP00000262461', 'cpi_9606.ENSP00000347942'], ['cpi_9606.ENSP00000255380', 'cpi_9606.ENSP00000318820', 'cpi_9606.ENSP00000447149', 'cpi_9606.ENSP00000304822', 'cpi_9606.ENSP00000283635'], ['cpi_9606.ENSP00000416293', 'cpi_9606.ENSP00000226444', 'cpi_9606.ENSP00000376178', 'cpi_9606.ENSP00000409007', 'cpi_9606.ENSP00000216037'], ['cpi_9606.ENSP00000409378', 'cpi_9606.ENSP00000234111', 'cpi_9606.ENSP00000308845', 'cpi_9606.ENSP00000347979', 'cpi_9606.ENSP00000410294'], ['cpi_9606.ENSP00000222256', 'cpi_9606.ENSP00000225831', 'cpi_9606.ENSP00000346534', 'cpi_9606.ENSP00000176763', 'cpi_9606.ENSP00000252809'], ['cpi_9606.ENSP00000368438', 'cpi_9606.ENSP00000343782', 'cpi_9606.ENSP00000369050', 'cpi_9606.ENSP00000328973', 'cpi_9606.ENSP00000381097'], ['cpi_9606.ENSP00000356438', 'cpi_9606.ENSP00000320025', 'cpi_9606.ENSP00000287766', 'cpi_9606.ENSP00000258749', 'cpi_9606.ENSP00000267119'], ['cpi_9606.ENSP00000222982', 'cpi_9606.ENSP00000299178', 'cpi_9606.ENSP00000234389', 'cpi_9606.ENSP00000378517', 'cpi_9606.ENSP00000252723'], ['cpi_9606.ENSP00000274353', 'cpi_9606.ENSP00000367851', 'cpi_9606.ENSP00000361666', 'cpi_9606.ENSP00000340691', 'cpi_9606.ENSP00000316244'], ['cpi_9606.ENSP00000372750', 'cpi_9606.ENSP00000242375', 'cpi_9606.ENSP00000296350', 'cpi_9606.ENSP00000221972', 'cpi_9606.ENSP00000394033'], ['cpi_9606.ENSP00000398698', 'cpi_9606.ENSP00000326219', 'cpi_9606.ENSP00000270570', 'cpi_9606.ENSP00000310447', 'cpi_9606.ENSP00000368253'], ['cpi_9606.ENSP00000297494', 'cpi_9606.ENSP00000353791', 'cpi_9606.ENSP00000312304', 'cpi_9606.ENSP00000301178', 'cpi_9606.ENSP00000362036'], ['cpi_9606.ENSP00000360317', 'cpi_9606.ENSP00000262888', 'cpi_9606.ENSP00000365775', 'cpi_9606.ENSP00000451040', 'cpi_9606.ENSP00000307014'], ['cpi_9606.ENSP00000387281', 'cpi_9606.ENSP00000315644', 'cpi_9606.ENSP00000447173', 'cpi_9606.ENSP00000359635', 'cpi_9606.ENSP00000470087'], ['cpi_9606.ENSP00000258743', 'cpi_9606.ENSP00000405573', 'cpi_9606.ENSP00000297316', 'cpi_9606.ENSP00000343040', 'cpi_9606.ENSP00000252945'], ['cpi_9606.ENSP00000295897', 'cpi_9606.ENSP00000457706', 'cpi_9606.ENSP00000353292', 'cpi_9606.ENSP00000259089', 'cpi_9606.ENSP00000448059'], ['cpi_9606.ENSP00000324856', 'cpi_9606.ENSP00000330237', 'cpi_9606.ENSP00000327431', 'cpi_9606.ENSP00000337773', 'cpi_9606.ENSP00000356958'], ['cpi_9606.ENSP00000396308', 'cpi_9606.ENSP00000376776', 'cpi_9606.ENSP00000231449', 'cpi_9606.ENSP00000254227', 'cpi_9606.ENSP00000311469'], ['cpi_9606.ENSP00000337450', 'cpi_9606.ENSP00000362810', 'cpi_9606.ENSP00000435777', 'cpi_9606.ENSP00000318822', 'cpi_9606.ENSP00000255465'], ['cpi_9606.ENSP00000236850', 'cpi_9606.ENSP00000274026', 'cpi_9606.ENSP00000282561', 'cpi_9606.ENSP00000338072', 'cpi_9606.ENSP00000254488'], ['cpi_9606.ENSP00000258400', 'cpi_9606.ENSP00000386284', 'cpi_9606.ENSP00000344352', 'cpi_9606.ENSP00000261693', 'cpi_9606.ENSP00000263923'], ['cpi_9606.ENSP00000398632', 'cpi_9606.ENSP00000357204', 'cpi_9606.ENSP00000267843', 'cpi_9606.ENSP00000386069', 'cpi_9606.ENSP00000300900'], ['cpi_9606.ENSP00000255030', 'cpi_9606.ENSP00000219833', 'cpi_9606.ENSP00000314508', 'cpi_9606.ENSP00000376943', 'cpi_9606.ENSP00000303174'], ['cpi_9606.ENSP00000354612', 'cpi_9606.ENSP00000339527', 'cpi_9606.ENSP00000262352', 'cpi_9606.ENSP00000356436', 'cpi_9606.ENSP00000362344'], ['cpi_9606.ENSP00000261707', 'cpi_9606.ENSP00000378699', 'cpi_9606.ENSP00000261465', 'cpi_9606.ENSP00000360493', 'cpi_9606.ENSP00000285381'], ['cpi_9606.ENSP00000306245', 'cpi_9606.ENSP00000270776', 'cpi_9606.ENSP00000334198', 'cpi_9606.ENSP00000305422', 'cpi_9606.ENSP00000220616'], ['cpi_9606.ENSP00000308541', 'cpi_9606.ENSP00000321821', 'cpi_9606.ENSP00000335511', 'cpi_9606.ENSP00000290349', 'cpi_9606.ENSP00000307240'], ['cpi_9606.ENSP00000368305', 'cpi_9606.ENSP00000351273', 'cpi_9606.ENSP00000276198', 'cpi_9606.ENSP00000225964', 'cpi_9606.ENSP00000305221'], ['cpi_9606.ENSP00000314151', 'cpi_9606.ENSP00000234071', 'cpi_9606.ENSP00000358327', 'cpi_9606.ENSP00000234961', 'cpi_9606.ENSP00000233146'], ['cpi_9606.ENSP00000353720', 'cpi_9606.ENSP00000338548', 'cpi_9606.ENSP00000294728', 'cpi_9606.ENSP00000352702', 'cpi_9606.ENSP00000262367'], ['cpi_9606.ENSP00000263025', 'cpi_9606.ENSP00000229264', 'cpi_9606.ENSP00000344674', 'cpi_9606.ENSP00000389414', 'cpi_9606.ENSP00000361359'], ['cpi_9606.ENSP00000387662', 'cpi_9606.ENSP00000254066', 'cpi_9606.ENSP00000339260', 'cpi_9606.ENSP00000463999', 'cpi_9606.ENSP00000338082'], ['cpi_9606.ENSP00000368766', 'cpi_9606.ENSP00000353731', 'cpi_9606.ENSP00000304845', 'cpi_9606.ENSP00000308774', 'cpi_9606.ENSP00000328968'], ['cpi_9606.ENSP00000257497', 'cpi_9606.ENSP00000011653', 'cpi_9606.ENSP00000358784', 'cpi_9606.ENSP00000394932', 'cpi_9606.ENSP00000293745'], ['cpi_9606.ENSP00000359478', 'cpi_9606.ENSP00000354859', 'cpi_9606.ENSP00000355533', 'cpi_9606.ENSP00000435591', 'cpi_9606.ENSP00000467676'], ['cpi_9606.ENSP00000312652', 'cpi_9606.ENSP00000340943', 'cpi_9606.ENSP00000369654', 'cpi_9606.ENSP00000293288', 'cpi_9606.ENSP00000260970'], ['cpi_9606.ENSP00000302150', 'cpi_9606.ENSP00000217426', 'cpi_9606.ENSP00000356954', 'cpi_9606.ENSP00000360967', 'cpi_9606.ENSP00000261196'], ['cpi_9606.ENSP00000361405', 'cpi_9606.ENSP00000355325', 'cpi_9606.ENSP00000268251', 'cpi_9606.ENSP00000231454', 'cpi_9606.ENSP00000339001'], ['cpi_9606.ENSP00000303522', 'cpi_9606.ENSP00000341390', 'cpi_9606.ENSP00000226574', 'cpi_9606.ENSP00000304811', 'cpi_9606.ENSP00000282397'], ['cpi_9606.ENSP00000366005', 'cpi_9606.ENSP00000370254', 'cpi_9606.ENSP00000396320', 'cpi_9606.ENSP00000307766', 'cpi_9606.ENSP00000252486'], ['cpi_9606.ENSP00000306662', 'cpi_9606.ENSP00000355155', 'cpi_9606.ENSP00000333212', 'cpi_9606.ENSP00000296370', 'cpi_9606.ENSP00000256958'], ['cpi_9606.ENSP00000237612', 'cpi_9606.ENSP00000441691', 'cpi_9606.ENSP00000355778', 'cpi_9606.ENSP00000358963', 'cpi_9606.ENSP00000276449'], ['cpi_9606.ENSP00000306512', 'cpi_9606.ENSP00000364035', 'cpi_9606.ENSP00000289753', 'cpi_9606.ENSP00000297268', 'cpi_9606.ENSP00000312455'], ['cpi_9606.ENSP00000296545', 'cpi_9606.ENSP00000259486', 'cpi_9606.ENSP00000354394', 'cpi_9606.ENSP00000176183', 'cpi_9606.ENSP00000280357'], ['cpi_9606.ENSP00000373169', 'cpi_9606.ENSP00000356729', 'cpi_9606.ENSP00000348827', 'cpi_9606.ENSP00000262948', 'cpi_9606.ENSP00000292896'], ['cpi_9606.ENSP00000360683', 'cpi_9606.ENSP00000313661', 'cpi_9606.ENSP00000418532', 'cpi_9606.ENSP00000300061', 'cpi_9606.ENSP00000241261'], ['cpi_9606.ENSP00000263686', 'cpi_9606.ENSP00000222002', 'cpi_9606.ENSP00000222330', 'cpi_9606.ENSP00000211287', 'cpi_9606.ENSP00000256383'], ['cpi_9606.ENSP00000215832', 'cpi_9606.ENSP00000402608', 'cpi_9606.ENSP00000253122', 'cpi_9606.ENSP00000254976', 'cpi_9606.ENSP00000357283'], ['cpi_9606.ENSP00000287820', 'cpi_9606.ENSP00000359910', 'cpi_9606.ENSP00000291700', 'cpi_9606.ENSP00000358730', 'cpi_9606.ENSP00000435412'], ['cpi_9606.ENSP00000229447', 'cpi_9606.ENSP00000264657', 'cpi_9606.ENSP00000346598', 'cpi_9606.ENSP00000285979', 'cpi_9606.ENSP00000353915'], ['cpi_9606.ENSP00000356825', 'cpi_9606.ENSP00000362353', 'cpi_9606.ENSP00000329623', 'cpi_9606.ENSP00000274793', 'cpi_9606.ENSP00000311028'], ['cpi_9606.ENSP00000414303', 'cpi_9606.ENSP00000354850', 'cpi_9606.ENSP00000355657', 'cpi_9606.ENSP00000296871', 'cpi_9606.ENSP00000221421'], ['cpi_9606.ENSP00000363512', 'cpi_9606.ENSP00000359096', 'cpi_9606.ENSP00000330393', 'cpi_9606.ENSP00000327652', 'cpi_9606.ENSP00000387683'], ['cpi_9606.ENSP00000353679', 'cpi_9606.ENSP00000381333', 'cpi_9606.ENSP00000329357', 'cpi_9606.ENSP00000354107', 'cpi_9606.ENSP00000419782'], ['cpi_9606.ENSP00000282091', 'cpi_9606.ENSP00000246337', 'cpi_9606.ENSP00000428340', 'cpi_9606.ENSP00000346148', 'cpi_9606.ENSP00000365380'], ['cpi_9606.ENSP00000302811', 'cpi_9606.ENSP00000222390', 'cpi_9606.ENSP00000288022', 'cpi_9606.ENSP00000325822', 'cpi_9606.ENSP00000288602'], ['cpi_9606.ENSP00000369647', 'cpi_9606.ENSP00000345659', 'cpi_9606.ENSP00000368104', 'cpi_9606.ENSP00000266682', 'cpi_9606.ENSP00000215659'], ['cpi_9606.ENSP00000428864', 'cpi_9606.ENSP00000350616', 'cpi_9606.ENSP00000267163', 'cpi_9606.ENSP00000309124', 'cpi_9606.ENSP00000391676'], ['cpi_9606.ENSP00000265572', 'cpi_9606.ENSP00000306606', 'cpi_9606.ENSP00000221515', 'cpi_9606.ENSP00000263980', 'cpi_9606.ENSP00000369530'], ['cpi_9606.ENSP00000412237', 'cpi_9606.ENSP00000327801', 'cpi_9606.ENSP00000338627', 'cpi_9606.ENSP00000393312', 'cpi_9606.ENSP00000362513'], ['cpi_9606.ENSP00000263088', 'cpi_9606.ENSP00000262735', 'cpi_9606.ENSP00000230671', 'cpi_9606.ENSP00000231228', 'cpi_9606.ENSP00000353878'], ['cpi_9606.ENSP00000253799', 'cpi_9606.ENSP00000369927', 'cpi_9606.ENSP00000260649', 'cpi_9606.ENSP00000322924', 'cpi_9606.ENSP00000295453'], ['cpi_9606.ENSP00000301974', 'cpi_9606.ENSP00000355759', 'cpi_9606.ENSP00000268053', 'cpi_9606.ENSP00000302886', 'cpi_9606.ENSP00000305302'], ['cpi_9606.ENSP00000269305', 'cpi_9606.ENSP00000434364', 'cpi_9606.ENSP00000270625', 'cpi_9606.ENSP00000301645', 'cpi_9606.ENSP00000360973'], ['cpi_9606.ENSP00000359899', 'cpi_9606.ENSP00000321988', 'cpi_9606.ENSP00000384273', 'cpi_9606.ENSP00000323549', 'cpi_9606.ENSP00000318646'], ['cpi_9606.ENSP00000356022', 'cpi_9606.ENSP00000358511', 'cpi_9606.ENSP00000427562', 'cpi_9606.ENSP00000219919', 'cpi_9606.ENSP00000400175'], ['cpi_9606.ENSP00000219070', 'cpi_9606.ENSP00000341828', 'cpi_9606.ENSP00000341885', 'cpi_9606.ENSP00000256906', 'cpi_9606.ENSP00000341045'], ['cpi_9606.ENSP00000309845', 'cpi_9606.ENSP00000260630', 'cpi_9606.ENSP00000291294', 'cpi_9606.ENSP00000260191', 'cpi_9606.ENSP00000288135'], ['cpi_9606.ENSP00000295598', 'cpi_9606.ENSP00000264832', 'cpi_9606.ENSP00000352584', 'cpi_9606.ENSP00000306129', 'cpi_9606.ENSP00000346298'], ['cpi_9606.ENSP00000394624', 'cpi_9606.ENSP00000296412', 'cpi_9606.ENSP00000330199', 'cpi_9606.ENSP00000370473', 'cpi_9606.ENSP00000216797'], ['cpi_9606.ENSP00000229319', 'cpi_9606.ENSP00000367309', 'cpi_9606.ENSP00000354558', 'cpi_9606.ENSP00000265403', 'cpi_9606.ENSP00000296522'], ['cpi_9606.ENSP00000222553', 'cpi_9606.ENSP00000338345', 'cpi_9606.ENSP00000311095', 'cpi_9606.ENSP00000371929', 'cpi_9606.ENSP00000388648'], ['cpi_9606.ENSP00000272298', 'cpi_9606.ENSP00000346768', 'cpi_9606.ENSP00000336630', 'cpi_9606.ENSP00000296511', 'cpi_9606.ENSP00000349577'], ['cpi_9606.ENSP00000337459', 'cpi_9606.ENSP00000352035', 'cpi_9606.ENSP00000366662', 'cpi_9606.ENSP00000312029', 'cpi_9606.ENSP00000342560'], ['cpi_9606.ENSP00000327251', 'cpi_9606.ENSP00000223366', 'cpi_9606.ENSP00000321636', 'cpi_9606.ENSP00000320401', 'cpi_9606.ENSP00000267377'], ['cpi_9606.ENSP00000352835', 'cpi_9606.ENSP00000350767', 'cpi_9606.ENSP00000302846', 'cpi_9606.ENSP00000302564', 'cpi_9606.ENSP00000360247'], ['cpi_9606.ENSP00000447378', 'cpi_9606.ENSP00000239849', 'cpi_9606.ENSP00000287907', 'cpi_9606.ENSP00000343838', 'cpi_9606.ENSP00000418960'], ['cpi_9606.ENSP00000320866', 'cpi_9606.ENSP00000292095', 'cpi_9606.ENSP00000276571', 'cpi_9606.ENSP00000362549', 'cpi_9606.ENSP00000361423'], ['cpi_9606.ENSP00000385834', 'cpi_9606.ENSP00000256010', 'cpi_9606.ENSP00000227758', 'cpi_9606.ENSP00000251566', 'cpi_9606.ENSP00000348234'], ['cpi_9606.ENSP00000317842', 'cpi_9606.ENSP00000297469', 'cpi_9606.ENSP00000317272', 'cpi_9606.ENSP00000178638', 'cpi_9606.ENSP00000287936'], ['cpi_9606.ENSP00000231751', 'cpi_9606.ENSP00000275300', 'cpi_9606.ENSP00000307235', 'cpi_9606.ENSP00000419692', 'cpi_9606.ENSP00000322617'], ['cpi_9606.ENSP00000342070', 'cpi_9606.ENSP00000257068', 'cpi_9606.ENSP00000308032', 'cpi_9606.ENSP00000295834', 'cpi_9606.ENSP00000368632'], ['cpi_9606.ENSP00000256119', 'cpi_9606.ENSP00000303830', 'cpi_9606.ENSP00000333534', 'cpi_9606.ENSP00000278175', 'cpi_9606.ENSP00000353427'], ['cpi_9606.ENSP00000324270', 'cpi_9606.ENSP00000291565', 'cpi_9606.ENSP00000278616', 'cpi_9606.ENSP00000362508', 'cpi_9606.ENSP00000445340'], ['cpi_9606.ENSP00000298171', 'cpi_9606.ENSP00000363832', 'cpi_9606.ENSP00000358903', 'cpi_9606.ENSP00000332816', 'cpi_9606.ENSP00000359998'], ['cpi_9606.ENSP00000349467', 'cpi_9606.ENSP00000358595', 'cpi_9606.ENSP00000366307', 'cpi_9606.ENSP00000245457', 'cpi_9606.ENSP00000248553'], ['cpi_9606.ENSP00000217386', 'cpi_9606.ENSP00000311165', 'cpi_9606.ENSP00000295400', 'cpi_9606.ENSP00000300151', 'cpi_9606.ENSP00000301141'], ['cpi_9606.ENSP00000434516', 'cpi_9606.ENSP00000263339', 'cpi_9606.ENSP00000428924', 'cpi_9606.ENSP00000340684', 'cpi_9606.ENSP00000276431'], ['cpi_9606.ENSP00000261267', 'cpi_9606.ENSP00000264498', 'cpi_9606.ENSP00000308549', 'cpi_9606.ENSP00000362525', 'cpi_9606.ENSP00000296674'], ['cpi_9606.ENSP00000330032', 'cpi_9606.ENSP00000387888', 'cpi_9606.ENSP00000263341', 'cpi_9606.ENSP00000293897', 'cpi_9606.ENSP00000367608'], ['cpi_9606.ENSP00000348775', 'cpi_9606.ENSP00000380252', 'cpi_9606.ENSP00000379140', 'cpi_9606.ENSP00000433821', 'cpi_9606.ENSP00000323568'], ['cpi_9606.ENSP00000355536', 'cpi_9606.ENSP00000365016', 'cpi_9606.ENSP00000382659', 'cpi_9606.ENSP00000356694', 'cpi_9606.ENSP00000199280'], ['cpi_9606.ENSP00000265023', 'cpi_9606.ENSP00000302961', 'cpi_9606.ENSP00000309757', 'cpi_9606.ENSP00000370373', 'cpi_9606.ENSP00000466799'], ['cpi_9606.ENSP00000268035', 'cpi_9606.ENSP00000275216', 'cpi_9606.ENSP00000314099', 'cpi_9606.ENSP00000332679', 'cpi_9606.ENSP00000365663'], ['cpi_9606.ENSP00000319531', 'cpi_9606.ENSP00000239938', 'cpi_9606.ENSP00000248041', 'cpi_9606.ENSP00000349003', 'cpi_9606.ENSP00000270474'], ['cpi_9606.ENSP00000342952', 'cpi_9606.ENSP00000341189', 'cpi_9606.ENSP00000351908', 'cpi_9606.ENSP00000225426', 'cpi_9606.ENSP00000369816'], ['cpi_9606.ENSP00000279230', 'cpi_9606.ENSP00000277508', 'cpi_9606.ENSP00000216117', 'cpi_9606.ENSP00000251453', 'cpi_9606.ENSP00000360991'], ['cpi_9606.ENSP00000370571', 'cpi_9606.ENSP00000293230', 'cpi_9606.ENSP00000317379', 'cpi_9606.ENSP00000391826', 'cpi_9606.ENSP00000303424'], ['cpi_9606.ENSP00000226578', 'cpi_9606.ENSP00000368683', 'cpi_9606.ENSP00000369757', 'cpi_9606.ENSP00000211122', 'cpi_9606.ENSP00000350198'], ['cpi_9606.ENSP00000359680', 'cpi_9606.ENSP00000334246', 'cpi_9606.ENSP00000333821', 'cpi_9606.ENSP00000364802', 'cpi_9606.ENSP00000244741'], ['cpi_9606.ENSP00000275493', 'cpi_9606.ENSP00000324248', 'cpi_9606.ENSP00000379339', 'cpi_9606.ENSP00000219240', 'cpi_9606.ENSP00000331736'], ['cpi_9606.ENSP00000372326', 'cpi_9606.ENSP00000357255', 'cpi_9606.ENSP00000363089', 'cpi_9606.ENSP00000322421', 'cpi_9606.ENSP00000237527'], ['cpi_9606.ENSP00000290866', 'cpi_9606.ENSP00000265643', 'cpi_9606.ENSP00000232219', 'cpi_9606.ENSP00000338160', 'cpi_9606.ENSP00000356832'], ['cpi_9606.ENSP00000397582', 'cpi_9606.ENSP00000223095', 'cpi_9606.ENSP00000287641', 'cpi_9606.ENSP0000037

🔄 Processing features: 100%|██████████| 540/540 [01:27<00:00,  6.14feat/s]

XofN_groups: [['f_374', 'f_726', 'f_194', 'f_771', 'f_509'], ['f_20', 'f_792', 'f_629', 'f_635', 'f_328'], ['f_23', 'f_413', 'f_195', 'f_428', 'f_675'], ['f_308', 'f_616', 'f_722', 'f_768', 'f_25'], ['f_346', 'f_831', 'f_749', 'f_460', 'f_31'], ['f_366', 'f_789', 'f_799', 'f_417', 'f_510'], ['f_287', 'f_408', 'f_631', 'f_292', 'f_773'], ['f_2', 'f_529', 'f_27', 'f_587', 'f_725'], ['f_393', 'f_866', 'f_622', 'f_214', 'f_785'], ['f_19', 'f_327', 'f_836', 'f_151', 'f_436'], ['f_299', 'f_845', 'f_202', 'f_839', 'f_497'], ['f_571', 'f_526', 'f_736', 'f_833', 'f_427'], ['f_406', 'f_815', 'f_788', 'f_409', 'f_330'], ['f_697', 'f_511', 'f_767', 'f_812', 'f_26'], ['f_24', 'f_216', 'f_46', 'f_43', 'f_653'], ['f_452', 'f_729', 'f_757', 'f_297', 'f_47'], ['f_391', 'f_719', 'f_827', 'f_118', 'f_670'], ['f_335', 'f_750', 'f_466', 'f_298', 'f_554'], ['f_338', 'f_820', 'f_401', 'f_834', 'f_350'], ['f_15', 'f_861', 'f_782', 'f_764', 'f_262'], ['f_339', 'f_419', 'f_813', 'f_131', 'f_166'], ['f_639', 'f_778', 'f_508', 'f_167', 'f_728'], ['f_672', 'f_830', 'f_752', 'f_207', 'f_407'], ['f_380', 'f_650', 'f_477', 'f_583', 'f_448'], ['f_186', 'f_388', 'f_474', 'f_505', 'f_394'], ['f_528', 'f_840', 'f_229', 'f_676', 'f_770'], ['f_656', 'f_706', 'f_361', 'f_715', 'f_35'], ['f_392', 'f_398', 'f_343', 'f_471', 'f_496'], ['f_643', 'f_242', 'f_461', 'f_429', 'f_791'], ['f_185', 'f_455', 'f_132', 'f_551', 'f_164'], ['f_566', 'f_860', 'f_568', 'f_740', 'f_759'], ['f_659', 'f_116', 'f_483', 'f_625', 'f_486'], ['f_405', 'f_609', 'f_159', 'f_763', 'f_129'], ['f_614', 'f_522', 'f_533', 'f_588', 'f_425'], ['f_440', 'f_518', 'f_738', 'f_647', 'f_721'], ['f_12', 'f_558', 'f_314', 'f_422', 'f_513'], ['f_192', 'f_473', 'f_215', 'f_30', 'f_822'], ['f_451', 'f_230', 'f_543', 'f_780', 'f_411'], ['f_143', 'f_801', 'f_454', 'f_456', 'f_784'], ['f_3', 'f_423', 'f_494', 'f_717', 'f_742'], ['f_181', 'f_514', 'f_200', 'f_559', 'f_644'], ['f_617', 'f_465', 'f_38', 'f_826', 'f_475'], ['f_696', 'f_489', 'f_363', 'f_803', 'f_160'], ['f_340', 'f_144', 'f_575', 'f_480', 'f_517'], ['f_180', 'f_347', 'f_694', 'f_213', 'f_336'], ['f_420', 'f_467', 'f_115', 'f_22', 'f_805'], ['f_37', 'f_227', 'f_488', 'f_364', 'f_713'], ['f_257', 'f_605', 'f_301', 'f_687', 'f_716'], ['f_341', 'f_421', 'f_515', 'f_206', 'f_737'], ['f_712', 'f_34', 'f_652', 'f_397', 'f_367'], ['f_146', 'f_187', 'f_705', 'f_395', 'f_157'], ['f_535', 'f_621', 'f_610', 'f_500', 'f_779'], ['f_667', 'f_378', 'f_661', 'f_457', 'f_707'], ['f_439', 'f_249', 'f_305', 'f_359', 'f_544'], ['f_345', 'f_563', 'f_414', 'f_711', 'f_17'], ['f_646', 'f_337', 'f_601', 'f_532', 'f_734'], ['f_443', 'f_260', 'f_630', 'f_458', 'f_612'], ['f_638', 'f_334', 'f_300', 'f_531', 'f_400'], ['f_365', 'f_459', 'f_537', 'f_152', 'f_761'], ['f_540', 'f_700', 'f_624', 'f_658', 'f_399'], ['f_569', 'f_824', 'f_383', 'f_776', 'f_527'], ['f_611', 'f_701', 'f_385', 'f_673', 'f_591'], ['f_516', 'f_188', 'f_756', 'f_485', 'f_349'], ['f_682', 'f_342', 'f_586', 'f_800', 'f_432'], ['f_579', 'f_438', 'f_590', 'f_503', 'f_250'], ['f_691', 'f_550', 'f_412', 'f_685', 'f_462'], ['f_698', 'f_499', 'f_598', 'f_251', 'f_507'], ['f_464', 'f_681', 'f_368', 'f_501', 'f_735'], ['f_11', 'f_686', 'f_362', 'f_386', 'f_663'], ['f_613', 'f_693', 'f_243', 'f_294', 'f_755'], ['f_692', 'f_572', 'f_632', 'f_577', 'f_690'], ['f_567', 'f_435', 'f_623', 'f_193', 'f_615'], ['f_33', 'f_798', 'f_547', 'f_758', 'f_620'], ['f_645', 'f_819', 'f_504', 'f_703', 'f_353'], ['f_637', 'f_389', 'f_199', 'f_293', 'f_493'], ['f_241', 'f_642', 'f_372', 'f_662', 'f_597'], ['f_683', 'f_153', 'f_818', 'f_581', 'f_674'], ['f_684', 'f_484', 'f_565', 'f_13', 'f_821'], ['f_16', 'f_699', 'f_445', 'f_21', 'f_626'], ['f_553', 'f_714', 'f_596', 'f_695', 'f_797'], ['f_248', 'f_379', 'f_536', 'f_589', 'f_150'], ['f_593', 'f_476', 'f_671', 'f_261', 'f_602'], ['f_702', 'f_576', 'f_704', 'f_636', 'f_604'], ['f_592', 'f_777', 'f_519', 'f_244', 'f_580'], ['f_14', 'f_258', 'f_594', 'f_487', 'f_542'], ['f_689', 'f_560', 'f_530', 'f_666', 'f_377'], ['f_390', 'f_491', 'f_382', 'f_450', 'f_600'], ['f_619', 'f_373', 'f_375', 'f_688', 'f_259'], ['f_573', 'f_447', 'f_654', 'f_633', 'f_651'], ['f_18', 'f_521', 'f_606', 'f_555', 'f_145'], ['f_680', 'f_357', 'f_502', 'f_381', 'f_628'], ['f_285', 'f_431', 'f_541', 'f_546', 'f_641'], ['f_333', 'f_523', 'f_498', 'f_539', 'f_655'], ['f_709', 'f_506', 'f_574', 'f_665', 'f_286'], ['f_332', 'f_472', 'f_548', 'f_437', 'f_710'], ['f_351', 'f_482', 'f_179', 'f_538', 'f_352'], ['f_418', 'f_708', 'f_657', 'f_9', 'f_403'], ['f_430', 'f_396', 'f_549', 'f_283', 'f_387'], ['f_449', 'f_679', 'f_358', 'f_356', 'f_453'], ['f_607', 'f_256', 'f_0', 'f_585', 'f_599'], ['f_1', 'f_442', 'f_545', 'f_371', 'f_495'], ['f_178', 'f_376', 'f_618', 'f_344', 'f_434'], ['f_582', 'f_370', 'f_284', 'f_578', 'f_10'], ['f_564', 'f_416', 'f_603', 'f_446', 'f_255'], ['f_664', 'f_441', 'f_384', 'f_490', 'f_355'], ['f_520', 'f_556', 'f_524', 'f_584', 'f_640'], ['f_570', 'f_678', 'f_677', 'f_660', 'f_552'], ['f_595', 'f_470', 'f_668', 'f_608', 'f_634']]
XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5210596, HammingLoss: 0.21692, SubsetAccuracy: 0.10687,
pruning: False, include_original_features: with_org, averageAUROC: 0.5916742, HammingLoss: 0.27863, SubsetAccuracy: 0.038168,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.21947, SubsetAccuracy: 0.10687,
pruning: False, include_original_features: no_org, averageAUROC: 0.5516067, HammingLoss: 0.29771, SubsetAccuracy: 0.045802,

Fold 2/10 (fingerprint_all 7/9)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:27<00:00,  6.17feat/s]

XofN_groups: [['f_374', 'f_831', 'f_27', 'f_194', 'f_771'], ['f_20', 'f_792', 'f_629', 'f_328', 'f_214'], ['f_308', 'f_616', 'f_785', 'f_789', 'f_25'], ['f_366', 'f_726', 'f_428', 'f_778', 'f_466'], ['f_346', 'f_768', 'f_715', 'f_327', 'f_31'], ['f_406', 'f_529', 'f_791', 'f_788', 'f_118'], ['f_571', 'f_836', 'f_799', 'f_429', 'f_509'], ['f_2', 'f_526', 'f_725', 'f_413', 'f_510'], ['f_23', 'f_195', 'f_292', 'f_166', 'f_47'], ['f_287', 'f_408', 'f_635', 'f_207', 'f_622'], ['f_338', 'f_820', 'f_866', 'f_773', 'f_455'], ['f_186', 'f_845', 'f_511', 'f_202', 'f_436'], ['f_656', 'f_151', 'f_26', 'f_448', 'f_719'], ['f_15', 'f_861', 'f_782', 'f_670', 'f_764'], ['f_392', 'f_840', 'f_229', 'f_554', 'f_815'], ['f_617', 'f_757', 'f_834', 'f_401', 'f_497'], ['f_335', 'f_752', 'f_830', 'f_749', 'f_262'], ['f_391', 'f_505', 'f_460', 'f_587', 'f_330'], ['f_452', 'f_297', 'f_767', 'f_722', 'f_650'], ['f_299', 'f_839', 'f_675', 'f_583', 'f_736'], ['f_12', 'f_43', 'f_350', 'f_609', 'f_417'], ['f_451', 'f_631', 'f_427', 'f_706', 'f_46'], ['f_192', 'f_131', 'f_298', 'f_407', 'f_729'], ['f_672', 'f_167', 'f_676', 'f_728', 'f_129'], ['f_643', 'f_827', 'f_230', 'f_388', 'f_471'], ['f_380', 'f_813', 'f_419', 'f_35', 'f_738'], ['f_697', 'f_474', 'f_750', 'f_394', 'f_812'], ['f_393', 'f_242', 'f_486', 'f_513', 'f_409'], ['f_185', 'f_132', 'f_343', 'f_568', 'f_164'], ['f_143', 'f_763', 'f_551', 'f_518', 'f_533'], ['f_19', 'f_477', 'f_770', 'f_361', 'f_508'], ['f_614', 'f_488', 'f_483', 'f_588', 'f_456'], ['f_566', 'f_116', 'f_833', 'f_644', 'f_740'], ['f_639', 'f_215', 'f_473', 'f_522', 'f_187'], ['f_528', 'f_822', 'f_742', 'f_30', 'f_496'], ['f_339', 'f_489', 'f_398', 'f_759', 'f_115'], ['f_146', 'f_801', 'f_721', 'f_314', 'f_558'], ['f_440', 'f_647', 'f_784', 'f_559', 'f_216'], ['f_37', 'f_475', 'f_159', 'f_653', 'f_860'], ['f_659', 'f_465', 'f_144', 'f_625', 'f_411'], ['f_3', 'f_423', 'f_422', 'f_480', 'f_717'], ['f_405', 'f_454', 'f_780', 'f_425', 'f_527'], ['f_181', 'f_514', 'f_200', 'f_494', 'f_421'], ['f_682', 'f_395', 'f_249', 'f_467', 'f_336'], ['f_535', 'f_543', 'f_517', 'f_803', 'f_500'], ['f_180', 'f_347', 'f_694', 'f_213', 'f_461'], ['f_712', 'f_34', 'f_826', 'f_38', 'f_363'], ['f_420', 'f_805', 'f_359', 'f_22', 'f_227'], ['f_516', 'f_367', 'f_160', 'f_364', 'f_305'], ['f_341', 'f_260', 'f_301', 'f_206', 'f_532'], ['f_696', 'f_612', 'f_575', 'f_457', 'f_157'], ['f_699', 'f_485', 'f_458', 'f_515', 'f_658'], ['f_569', 'f_711', 'f_414', 'f_610', 'f_737'], ['f_638', 'f_334', 'f_300', 'f_531', 'f_687'], ['f_365', 'f_605', 'f_17', 'f_652', 'f_24'], ['f_439', 'f_337', 'f_621', 'f_713', 'f_459'], ['f_340', 'f_630', 'f_397', 'f_400', 'f_383'], ['f_681', 'f_624', 'f_586', 'f_800', 'f_503'], ['f_257', 'f_563', 'f_707', 'f_349', 'f_378'], ['f_667', 'f_601', 'f_661', 'f_399', 'f_591'], ['f_33', 'f_824', 'f_716', 'f_776', 'f_499'], ['f_646', 'f_700', 'f_362', 'f_779', 'f_547'], ['f_611', 'f_705', 'f_250', 'f_152', 'f_734'], ['f_540', 'f_761', 'f_537', 'f_673', 'f_598'], ['f_553', 'f_544', 'f_153', 'f_501', 'f_188'], ['f_248', 'f_243', 'f_368', 'f_701', 'f_342'], ['f_345', 'f_462', 'f_251', 'f_685', 'f_438'], ['f_692', 'f_572', 'f_756', 'f_550', 'f_412'], ['f_16', 'f_819', 'f_507', 'f_294', 'f_703'], ['f_11', 'f_385', 'f_663', 'f_432', 'f_504'], ['f_684', 'f_389', 'f_735', 'f_615', 'f_353'], ['f_443', 'f_386', 'f_590', 'f_632', 'f_293'], ['f_579', 'f_596', 'f_755', 'f_620', 'f_577'], ['f_704', 'f_484', 'f_690', 'f_758', 'f_686'], ['f_464', 'f_693', 'f_193', 'f_379', 'f_662'], ['f_14', 'f_13', 'f_623', 'f_798', 'f_674'], ['f_567', 'f_435', 'f_597', 'f_818', 'f_519'], ['f_390', 'f_642', 'f_244', 'f_797', 'f_372'], ['f_702', 'f_671', 'f_491', 'f_21', 'f_476'], ['f_637', 'f_636', 'f_199', 'f_493', 'f_150'], ['f_593', 'f_565', 'f_581', 'f_241', 'f_536'], ['f_645', 'f_589', 'f_487', 'f_821', 'f_777'], ['f_691', 'f_373', 'f_626', 'f_602', 'f_377'], ['f_698', 'f_560', 'f_261', 'f_580', 'f_714'], ['f_613', 'f_695', 'f_604', 'f_445', 'f_450'], ['f_680', 'f_447', 'f_666', 'f_654', 'f_576'], ['f_683', 'f_258', 'f_594', 'f_375', 'f_542'], ['f_592', 'f_521', 'f_382', 'f_259', 'f_689'], ['f_285', 'f_530', 'f_651', 'f_145', 'f_502'], ['f_18', 'f_357', 'f_606', 'f_600', 'f_539'], ['f_573', 'f_472', 'f_633', 'f_381', 'f_431'], ['f_286', 'f_482', 'f_541', 'f_665', 'f_555'], ['f_333', 'f_506', 'f_498', 'f_546', 'f_641'], ['f_1', 'f_523', 'f_655', 'f_628', 'f_403'], ['f_549', 'f_574', 'f_396', 'f_352', 'f_538'], ['f_619', 'f_453', 'f_283', 'f_657', 'f_548'], ['f_709', 'f_387', 'f_437', 'f_9', 'f_256'], ['f_708', 'f_358', 'f_585', 'f_0', 'f_418'], ['f_430', 'f_442', 'f_545', 'f_344', 'f_495'], ['f_10', 'f_376', 'f_356', 'f_449', 'f_688'], ['f_607', 'f_284', 'f_710', 'f_351', 'f_599'], ['f_332', 'f_371', 'f_179', 'f_255', 'f_582'], ['f_178', 'f_618', 'f_446', 'f_679', 'f_355'], ['f_564', 'f_416', 'f_370', 'f_441', 'f_578'], ['f_570', 'f_434', 'f_384', 'f_640', 'f_524'], ['f_664', 'f_556', 'f_595', 'f_490', 'f_603'], ['f_520', 'f_678', 'f_584', 'f_660', 'f_608'], ['f_668', 'f_677', 'f_552', 'f_470', 'f_634']]
XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5042429, HammingLoss: 0.19656, SubsetAccuracy: 0.12977,
pruning: False, include_original_features: with_org, averageAUROC: 0.5751556, HammingLoss: 0.26272, SubsetAccuracy: 0.099237,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.1972, SubsetAccuracy: 0.12214,
pruning: False, include_original_features: no_org, averageAUROC: 0.5773026, HammingLoss: 0.29326, SubsetAccuracy: 0.053435,

Fold 3/10 (fingerprint_all 7/9)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:27<00:00,  6.16feat/s]

XofN_groups: [['f_374', 'f_831', 'f_31', 'f_510', 'f_719'], ['f_20', 'f_792', 'f_629', 'f_497', 'f_194'], ['f_308', 'f_616', 'f_789', 'f_785', 'f_27'], ['f_346', 'f_428', 'f_726', 'f_429', 'f_799'], ['f_366', 'f_768', 'f_466', 'f_460', 'f_635'], ['f_23', 'f_408', 'f_292', 'f_164', 'f_529'], ['f_335', 'f_815', 'f_511', 'f_750', 'f_25'], ['f_391', 'f_866', 'f_788', 'f_782', 'f_836'], ['f_287', 'f_631', 'f_413', 'f_262', 'f_118'], ['f_2', 'f_725', 'f_773', 'f_47', 'f_587'], ['f_656', 'f_151', 'f_845', 'f_526', 'f_26'], ['f_571', 'f_736', 'f_752', 'f_297', 'f_455'], ['f_299', 'f_861', 'f_202', 'f_757', 'f_583'], ['f_392', 'f_840', 'f_675', 'f_398', 'f_505'], ['f_24', 'f_216', 'f_622', 'f_43', 'f_207'], ['f_672', 'f_830', 'f_330', 'f_167', 'f_229'], ['f_566', 'f_427', 'f_328', 'f_834', 'f_767'], ['f_338', 'f_820', 'f_401', 'f_813', 'f_676'], ['f_406', 'f_791', 'f_771', 'f_778', 'f_409'], ['f_643', 'f_214', 'f_436', 'f_706', 'f_554'], ['f_19', 'f_327', 'f_722', 'f_417', 'f_448'], ['f_697', 'f_35', 'f_749', 'f_715', 'f_764'], ['f_393', 'f_839', 'f_670', 'f_486', 'f_471'], ['f_440', 'f_728', 'f_729', 'f_388', 'f_46'], ['f_452', 'f_509', 'f_496', 'f_650', 'f_827'], ['f_380', 'f_419', 'f_298', 'f_483', 'f_166'], ['f_3', 'f_477', 'f_131', 'f_350', 'f_551'], ['f_185', 'f_407', 'f_474', 'f_568', 'f_653'], ['f_186', 'f_473', 'f_812', 'f_394', 'f_343'], ['f_516', 'f_30', 'f_195', 'f_763', 'f_132'], ['f_12', 'f_609', 'f_559', 'f_740', 'f_644'], ['f_192', 'f_508', 'f_215', 'f_411', 'f_543'], ['f_617', 'f_533', 'f_759', 'f_522', 'f_647'], ['f_639', 'f_454', 'f_738', 'f_488', 'f_361'], ['f_143', 'f_588', 'f_518', 'f_833', 'f_801'], ['f_339', 'f_489', 'f_717', 'f_494', 'f_314'], ['f_528', 'f_770', 'f_230', 'f_822', 'f_513'], ['f_614', 'f_558', 'f_425', 'f_422', 'f_116'], ['f_146', 'f_347', 'f_742', 'f_780', 'f_456'], ['f_696', 'f_475', 'f_826', 'f_38', 'f_625'], ['f_15', 'f_242', 'f_461', 'f_803', 'f_159'], ['f_405', 'f_423', 'f_200', 'f_467', 'f_115'], ['f_712', 'f_34', 'f_721', 'f_514', 'f_359'], ['f_659', 'f_860', 'f_465', 'f_575', 'f_517'], ['f_451', 'f_144', 'f_630', 'f_480', 'f_397'], ['f_341', 'f_129', 'f_363', 'f_378', 'f_687'], ['f_181', 'f_395', 'f_160', 'f_336', 'f_213'], ['f_180', 'f_22', 'f_301', 'f_784', 'f_249'], ['f_667', 'f_621', 'f_367', 'f_457', 'f_707'], ['f_37', 'f_227', 'f_694', 'f_364', 'f_805'], ['f_579', 'f_305', 'f_544', 'f_612', 'f_713'], ['f_420', 'f_421', 'f_652', 'f_515', 'f_206'], ['f_365', 'f_610', 'f_414', 'f_187', 'f_711'], ['f_257', 'f_605', 'f_716', 'f_17', 'f_500'], ['f_638', 'f_334', 'f_300', 'f_532', 'f_260'], ['f_535', 'f_601', 'f_661', 'f_658', 'f_400'], ['f_540', 'f_563', 'f_737', 'f_503', 'f_157'], ['f_443', 'f_761', 'f_458', 'f_152', 'f_598'], ['f_248', 'f_499', 'f_459', 'f_824', 'f_734'], ['f_637', 'f_531', 'f_527', 'f_362', 'f_705'], ['f_345', 'f_337', 'f_624', 'f_399', 'f_501'], ['f_340', 'f_700', 'f_383', 'f_385', 'f_485'], ['f_682', 'f_342', 'f_779', 'f_586', 'f_673'], ['f_569', 'f_701', 'f_800', 'f_591', 'f_349'], ['f_699', 'f_547', 'f_550', 'f_412', 'f_188'], ['f_684', 'f_438', 'f_590', 'f_250', 'f_294'], ['f_439', 'f_776', 'f_251', 'f_153', 'f_615'], ['f_567', 'f_435', 'f_756', 'f_507', 'f_685'], ['f_681', 'f_372', 'f_623', 'f_368', 'f_735'], ['f_464', 'f_462', 'f_193', 'f_572', 'f_632'], ['f_646', 'f_819', 'f_504', 'f_703', 'f_353'], ['f_611', 'f_537', 'f_620', 'f_577', 'f_755'], ['f_33', 'f_798', 'f_389', 'f_663', 'f_758'], ['f_645', 'f_432', 'f_386', 'f_690', 'f_293'], ['f_691', 'f_818', 'f_484', 'f_597', 'f_686'], ['f_698', 'f_379', 'f_199', 'f_493', 'f_21'], ['f_553', 'f_13', 'f_565', 'f_596', 'f_821'], ['f_683', 'f_693', 'f_243', 'f_662', 'f_602'], ['f_704', 'f_674', 'f_626', 'f_797', 'f_536'], ['f_390', 'f_581', 'f_244', 'f_714', 'f_519'], ['f_16', 'f_589', 'f_671', 'f_445', 'f_642'], ['f_592', 'f_261', 'f_777', 'f_580', 'f_636'], ['f_692', 'f_487', 'f_476', 'f_150', 'f_702'], ['f_613', 'f_695', 'f_604', 'f_447', 'f_241'], ['f_573', 'f_491', 'f_377', 'f_375', 'f_594'], ['f_14', 'f_258', 'f_666', 'f_593', 'f_450'], ['f_285', 'f_373', 'f_542', 'f_560', 'f_576'], ['f_619', 'f_521', 'f_600', 'f_654', 'f_382'], ['f_689', 'f_357', 'f_633', 'f_651', 'f_145'], ['f_18', 'f_530', 'f_606', 'f_546', 'f_259'], ['f_680', 'f_431', 'f_381', 'f_502', 'f_628'], ['f_688', 'f_506', 'f_541', 'f_555', 'f_286'], ['f_641', 'f_472', 'f_9', 'f_665', 'f_498'], ['f_709', 'f_482', 'f_574', 'f_437', 'f_539'], ['f_11', 'f_523', 'f_655', 'f_453', 'f_549'], ['f_333', 'f_403', 'f_548', 'f_585', 'f_352'], ['f_1', 'f_396', 'f_607', 'f_538', 'f_710'], ['f_430', 'f_387', 'f_657', 'f_283', 'f_418'], ['f_564', 'f_358', 'f_0', 'f_495', 'f_256'], ['f_332', 'f_442', 'f_356', 'f_545', 'f_179'], ['f_351', 'f_376', 'f_708', 'f_449', 'f_599'], ['f_679', 'f_255', 'f_284', 'f_371', 'f_344'], ['f_434', 'f_10', 'f_618', 'f_355', 'f_582'], ['f_664', 'f_178', 'f_370', 'f_416', 'f_578'], ['f_446', 'f_603', 'f_441', 'f_677', 'f_384'], ['f_520', 'f_556', 'f_584', 'f_524', 'f_640'], ['f_660', 'f_570', 'f_490', 'f_552', 'f_595'], ['f_678', 'f_608', 'f_470', 'f_668', 'f_634']]
XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5279719, HammingLoss: 0.19275, SubsetAccuracy: 0.1374,
pruning: False, include_original_features: with_org, averageAUROC: 0.5656856, HammingLoss: 0.26399, SubsetAccuracy: 0.061069,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.19466, SubsetAccuracy: 0.12977,
pruning: False, include_original_features: no_org, averageAUROC: 0.5409912, HammingLoss: 0.28053, SubsetAccuracy: 0.045802,

Fold 4/10 (fingerprint_all 7/9)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:27<00:00,  6.15feat/s]

XofN_groups: [['f_374', 'f_768', 'f_194', 'f_31', 'f_771'], ['f_20', 'f_792', 'f_629', 'f_428', 'f_510'], ['f_308', 'f_616', 'f_789', 'f_25', 'f_409'], ['f_346', 'f_726', 'f_460', 'f_635', 'f_429'], ['f_366', 'f_831', 'f_466', 'f_427', 'f_413'], ['f_2', 'f_529', 'f_725', 'f_27', 'f_47'], ['f_656', 'f_151', 'f_845', 'f_836', 'f_706'], ['f_406', 'f_773', 'f_791', 'f_788', 'f_26'], ['f_287', 'f_22', 'f_292', 'f_526', 'f_799'], ['f_639', 'f_417', 'f_830', 'f_131', 'f_166'], ['f_335', 'f_815', 'f_436', 'f_511', 'f_46'], ['f_643', 'f_861', 'f_202', 'f_554', 'f_583'], ['f_697', 'f_767', 'f_35', 'f_749', 'f_448'], ['f_571', 'f_736', 'f_752', 'f_327', 'f_214'], ['f_15', 'f_866', 'f_719', 'f_118', 'f_587'], ['f_392', 'f_840', 'f_509', 'f_398', 'f_505'], ['f_391', 'f_764', 'f_782', 'f_839', 'f_408'], ['f_338', 'f_820', 'f_455', 'f_834', 'f_497'], ['f_516', 'f_350', 'f_407', 'f_670', 'f_827'], ['f_186', 'f_262', 'f_132', 'f_622', 'f_298'], ['f_23', 'f_631', 'f_167', 'f_609', 'f_330'], ['f_12', 'f_675', 'f_722', 'f_401', 'f_411'], ['f_380', 'f_650', 'f_757', 'f_785', 'f_229'], ['f_452', 'f_297', 'f_729', 'f_388', 'f_343'], ['f_672', 'f_43', 'f_164', 'f_496', 'f_474'], ['f_566', 'f_328', 'f_477', 'f_860', 'f_647'], ['f_528', 'f_486', 'f_778', 'f_763', 'f_471'], ['f_339', 'f_568', 'f_750', 'f_129', 'f_715'], ['f_659', 'f_394', 'f_676', 'f_242', 'f_728'], ['f_617', 'f_813', 'f_454', 'f_30', 'f_195'], ['f_440', 'f_518', 'f_551', 'f_770', 'f_513'], ['f_299', 'f_230', 'f_461', 'f_419', 'f_361'], ['f_192', 'f_508', 'f_215', 'f_314', 'f_207'], ['f_712', 'f_533', 'f_812', 'f_522', 'f_759'], ['f_143', 'f_738', 'f_425', 'f_721', 'f_558'], ['f_393', 'f_826', 'f_780', 'f_456', 'f_625'], ['f_405', 'f_588', 'f_159', 'f_717', 'f_473'], ['f_3', 'f_423', 'f_801', 'f_833', 'f_494'], ['f_19', 'f_644', 'f_116', 'f_740', 'f_559'], ['f_614', 'f_488', 'f_483', 'f_336', 'f_216'], ['f_451', 'f_653', 'f_115', 'f_822', 'f_475'], ['f_146', 'f_543', 'f_347', 'f_363', 'f_38'], ['f_185', 'f_489', 'f_687', 'f_397', 'f_742'], ['f_257', 'f_144', 'f_367', 'f_514', 'f_422'], ['f_420', 'f_805', 'f_517', 'f_480', 'f_200'], ['f_24', 'f_160', 'f_803', 'f_213', 'f_305'], ['f_696', 'f_421', 'f_652', 'f_467', 'f_206'], ['f_181', 'f_694', 'f_227', 'f_364', 'f_713'], ['f_638', 'f_711', 'f_515', 'f_500', 'f_575'], ['f_341', 'f_359', 'f_465', 'f_784', 'f_301'], ['f_340', 'f_610', 'f_414', 'f_157', 'f_334'], ['f_535', 'f_621', 'f_395', 'f_734', 'f_532'], ['f_540', 'f_605', 'f_457', 'f_17', 'f_716'], ['f_365', 'f_661', 'f_260', 'f_34', 'f_624'], ['f_569', 'f_705', 'f_458', 'f_612', 'f_630'], ['f_443', 'f_601', 'f_563', 'f_658', 'f_400'], ['f_667', 'f_378', 'f_591', 'f_707', 'f_586'], ['f_180', 'f_590', 'f_459', 'f_300', 'f_537'], ['f_682', 'f_249', 'f_383', 'f_362', 'f_527'], ['f_37', 'f_399', 'f_700', 'f_187', 'f_737'], ['f_345', 'f_337', 'f_761', 'f_152', 'f_503'], ['f_698', 'f_438', 'f_349', 'f_800', 'f_598'], ['f_613', 'f_544', 'f_485', 'f_462', 'f_531'], ['f_611', 'f_824', 'f_776', 'f_501', 'f_673'], ['f_681', 'f_435', 'f_250', 'f_623', 'f_294'], ['f_439', 'f_701', 'f_550', 'f_386', 'f_507'], ['f_704', 'f_188', 'f_547', 'f_779', 'f_342'], ['f_615', 'f_818', 'f_499', 'f_756', 'f_412'], ['f_390', 'f_686', 'f_251', 'f_243', 'f_368'], ['f_685', 'f_662', 'f_353', 'f_797', 'f_703'], ['f_645', 'f_819', 'f_572', 'f_577', 'f_663'], ['f_11', 'f_385', 'f_690', 'f_504', 'f_432'], ['f_579', 'f_389', 'f_735', 'f_293', 'f_758'], ['f_567', 'f_372', 'f_597', 'f_755', 'f_33'], ['f_464', 'f_693', 'f_153', 'f_632', 'f_193'], ['f_692', 'f_484', 'f_620', 'f_13', 'f_821'], ['f_684', 'f_379', 'f_798', 'f_21', 'f_445'], ['f_699', 'f_450', 'f_695', 'f_199', 'f_493'], ['f_646', 'f_248', 'f_596', 'f_589', 'f_581'], ['f_637', 'f_674', 'f_642', 'f_244', 'f_714'], ['f_671', 'f_491', 'f_565', 'f_150', 'f_536'], ['f_241', 'f_602', 'f_626', 'f_519', 'f_691'], ['f_16', 'f_476', 'f_553', 'f_261', 'f_702'], ['f_619', 'f_636', 'f_580', 'f_777', 'f_377'], ['f_592', 'f_258', 'f_604', 'f_487', 'f_593'], ['f_145', 'f_666', 'f_600', 'f_560', 'f_542'], ['f_14', 'f_373', 'f_594', 'f_576', 'f_382'], ['f_683', 'f_447', 'f_651', 'f_654', 'f_689'], ['f_641', 'f_375', 'f_530', 'f_688', 'f_521'], ['f_285', 'f_259', 'f_606', 'f_539', 'f_680'], ['f_573', 'f_357', 'f_633', 'f_381', 'f_9'], ['f_18', 'f_431', 'f_541', 'f_546', 'f_655'], ['f_502', 'f_498', 'f_523', 'f_286', 'f_574'], ['f_333', 'f_472', 'f_548', 'f_665', 'f_555'], ['f_332', 'f_482', 'f_628', 'f_709', 'f_538'], ['f_607', 'f_506', 'f_352', 'f_418', 'f_710'], ['f_442', 'f_179', 'f_657', 'f_283', 'f_403'], ['f_1', 'f_396', 'f_549', 'f_356', 'f_387'], ['f_449', 'f_708', 'f_358', 'f_0', 'f_453'], ['f_430', 'f_256', 'f_585', 'f_344', 'f_437'], ['f_351', 'f_495', 'f_599', 'f_545', 'f_679'], ['f_10', 'f_376', 'f_371', 'f_284', 'f_618'], ['f_178', 'f_370', 'f_582', 'f_603', 'f_416'], ['f_434', 'f_255', 'f_578', 'f_441', 'f_446'], ['f_664', 'f_556', 'f_355', 'f_640', 'f_384'], ['f_564', 'f_490', 'f_584', 'f_524', 'f_608'], ['f_570', 'f_678', 'f_677', 'f_660', 'f_552'], ['f_520', 'f_595', 'f_668', 'f_470', 'f_634']]
XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5164652, HammingLoss: 0.18193, SubsetAccuracy: 0.091603,
pruning: False, include_original_features: with_org, averageAUROC: 0.5746296, HammingLoss: 0.257, SubsetAccuracy: 0.099237,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.18448, SubsetAccuracy: 0.091603,
pruning: False, include_original_features: no_org, averageAUROC: 0.5393954, HammingLoss: 0.28562, SubsetAccuracy: 0.038168,

Fold 5/10 (fingerprint_all 7/9)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:27<00:00,  6.15feat/s]

XofN_groups: [['f_374', 'f_768', 'f_834', 'f_27', 'f_194'], ['f_20', 'f_792', 'f_616', 'f_726', 'f_328'], ['f_308', 'f_529', 'f_629', 'f_789', 'f_778'], ['f_23', 'f_408', 'f_292', 'f_428', 'f_773'], ['f_15', 'f_866', 'f_214', 'f_31', 'f_836'], ['f_346', 'f_831', 'f_749', 'f_460', 'f_635'], ['f_287', 'f_413', 'f_631', 'f_118', 'f_47'], ['f_366', 'f_736', 'f_510', 'f_427', 'f_466'], ['f_697', 'f_511', 'f_725', 'f_815', 'f_845'], ['f_406', 'f_526', 'f_791', 'f_715', 'f_25'], ['f_2', 'f_788', 'f_587', 'f_771', 'f_26'], ['f_393', 'f_151', 'f_622', 'f_583', 'f_509'], ['f_299', 'f_861', 'f_202', 'f_764', 'f_820'], ['f_656', 'f_706', 'f_436', 'f_417', 'f_719'], ['f_335', 'f_752', 'f_830', 'f_350', 'f_522'], ['f_338', 'f_401', 'f_757', 'f_497', 'f_729'], ['f_451', 'f_43', 'f_767', 'f_839', 'f_505'], ['f_571', 'f_799', 'f_327', 'f_785', 'f_508'], ['f_614', 'f_166', 'f_429', 'f_728', 'f_46'], ['f_566', 'f_477', 'f_297', 'f_361', 'f_298'], ['f_617', 'f_750', 'f_455', 'f_330', 'f_738'], ['f_672', 'f_675', 'f_229', 'f_35', 'f_676'], ['f_19', 'f_554', 'f_722', 'f_262', 'f_394'], ['f_405', 'f_568', 'f_670', 'f_167', 'f_813'], ['f_440', 'f_650', 'f_496', 'f_551', 'f_770'], ['f_452', 'f_518', 'f_388', 'f_827', 'f_782'], ['f_639', 'f_533', 'f_409', 'f_759', 'f_398'], ['f_380', 'f_419', 'f_483', 'f_207', 'f_343'], ['f_392', 'f_840', 'f_486', 'f_471', 'f_653'], ['f_643', 'f_242', 'f_494', 'f_513', 'f_740'], ['f_3', 'f_423', 'f_801', 'f_833', 'f_448'], ['f_185', 'f_131', 'f_407', 'f_763', 'f_195'], ['f_516', 'f_812', 'f_474', 'f_164', 'f_558'], ['f_339', 'f_644', 'f_609', 'f_475', 'f_215'], ['f_186', 'f_473', 'f_30', 'f_588', 'f_230'], ['f_391', 'f_347', 'f_822', 'f_116', 'f_488'], ['f_143', 'f_543', 'f_717', 'f_625', 'f_314'], ['f_146', 'f_38', 'f_363', 'f_216', 'f_559'], ['f_12', 'f_461', 'f_115', 'f_647', 'f_159'], ['f_659', 'f_860', 'f_467', 'f_742', 'f_411'], ['f_340', 'f_425', 'f_780', 'f_454', 'f_422'], ['f_192', 'f_132', 'f_456', 'f_721', 'f_465'], ['f_420', 'f_805', 'f_517', 'f_200', 'f_480'], ['f_257', 'f_144', 'f_129', 'f_784', 'f_22'], ['f_528', 'f_514', 'f_711', 'f_359', 'f_575'], ['f_696', 'f_489', 'f_826', 'f_397', 'f_687'], ['f_181', 'f_395', 'f_160', 'f_336', 'f_605'], ['f_180', 'f_367', 'f_694', 'f_213', 'f_612'], ['f_341', 'f_421', 'f_515', 'f_206', 'f_737'], ['f_37', 'f_227', 'f_260', 'f_364', 'f_713'], ['f_365', 'f_803', 'f_157', 'f_24', 'f_301'], ['f_712', 'f_34', 'f_652', 'f_300', 'f_610'], ['f_439', 'f_249', 'f_621', 'f_500', 'f_716'], ['f_667', 'f_378', 'f_661', 'f_414', 'f_707'], ['f_638', 'f_334', 'f_305', 'f_598', 'f_399'], ['f_569', 'f_705', 'f_457', 'f_187', 'f_152'], ['f_682', 'f_532', 'f_776', 'f_601', 'f_563'], ['f_443', 'f_630', 'f_458', 'f_485', 'f_734'], ['f_535', 'f_250', 'f_459', 'f_17', 'f_337'], ['f_681', 'f_383', 'f_527', 'f_503', 'f_761'], ['f_699', 'f_499', 'f_531', 'f_779', 'f_501'], ['f_637', 'f_658', 'f_624', 'f_544', 'f_400'], ['f_11', 'f_824', 'f_547', 'f_591', 'f_800'], ['f_33', 'f_756', 'f_438', 'f_537', 'f_362'], ['f_645', 'f_700', 'f_550', 'f_386', 'f_673'], ['f_540', 'f_462', 'f_251', 'f_153', 'f_342'], ['f_615', 'f_590', 'f_294', 'f_385', 'f_586'], ['f_646', 'f_819', 'f_572', 'f_188', 'f_412'], ['f_686', 'f_507', 'f_758', 'f_663', 'f_389'], ['f_613', 'f_693', 'f_349', 'f_755', 'f_243'], ['f_684', 'f_504', 'f_735', 'f_368', 'f_577'], ['f_567', 'f_435', 'f_432', 'f_293', 'f_193'], ['f_611', 'f_701', 'f_623', 'f_372', 'f_703'], ['f_345', 'f_261', 'f_690', 'f_353', 'f_620'], ['f_691', 'f_818', 'f_484', 'f_632', 'f_685'], ['f_704', 'f_379', 'f_798', 'f_21', 'f_821'], ['f_248', 'f_596', 'f_597', 'f_13', 'f_662'], ['f_579', 'f_519', 'f_199', 'f_626', 'f_445'], ['f_698', 'f_674', 'f_797', 'f_695', 'f_565'], ['f_689', 'f_636', 'f_580', 'f_589', 'f_150'], ['f_464', 'f_714', 'f_642', 'f_487', 'f_671'], ['f_16', 'f_476', 'f_581', 'f_241', 'f_493'], ['f_553', 'f_702', 'f_576', 'f_777', 'f_560'], ['f_692', 'f_450', 'f_604', 'f_244', 'f_602'], ['f_390', 'f_258', 'f_536', 'f_594', 'f_654'], ['f_593', 'f_666', 'f_491', 'f_688', 'f_375'], ['f_14', 'f_373', 'f_542', 'f_377', 'f_145'], ['f_683', 'f_447', 'f_382', 'f_357', 'f_680'], ['f_592', 'f_521', 'f_651', 'f_259', 'f_286'], ['f_573', 'f_530', 'f_9', 'f_546', 'f_606'], ['f_18', 'f_431', 'f_541', 'f_600', 'f_403'], ['f_333', 'f_482', 'f_381', 'f_502', 'f_641'], ['f_619', 'f_506', 'f_633', 'f_352', 'f_498'], ['f_285', 'f_523', 'f_655', 'f_539', 'f_710'], ['f_1', 'f_472', 'f_574', 'f_665', 'f_555'], ['f_708', 'f_396', 'f_548', 'f_437', 'f_628'], ['f_332', 'f_387', 'f_607', 'f_453', 'f_709'], ['f_549', 'f_344', 'f_358', 'f_356', 'f_538'], ['f_449', 'f_679', 'f_256', 'f_430', 'f_442'], ['f_10', 'f_418', 'f_585', 'f_179', 'f_545'], ['f_351', 'f_657', 'f_599', 'f_495', 'f_283'], ['f_178', 'f_376', 'f_371', 'f_0', 'f_618'], ['f_434', 'f_284', 'f_578', 'f_255', 'f_582'], ['f_564', 'f_416', 'f_370', 'f_441', 'f_603'], ['f_664', 'f_446', 'f_355', 'f_640', 'f_384'], ['f_520', 'f_556', 'f_584', 'f_524', 'f_490'], ['f_570', 'f_678', 'f_677', 'f_660', 'f_552'], ['f_470', 'f_608', 'f_668', 'f_595', 'f_634']]
XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5065552, HammingLoss: 0.20929, SubsetAccuracy: 0.091603,
pruning: False, include_original_features: with_org, averageAUROC: 0.564367, HammingLoss: 0.2869, SubsetAccuracy: 0.053435,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.20992, SubsetAccuracy: 0.091603,
pruning: False, include_original_features: no_org, averageAUROC: 0.6023343, HammingLoss: 0.27099, SubsetAccuracy: 0.076336,

Fold 6/10 (fingerprint_all 7/9)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:27<00:00,  6.16feat/s]

XofN_groups: [['f_374', 'f_771', 'f_768', 'f_31', 'f_194'], ['f_20', 'f_729', 'f_629', 'f_328', 'f_428'], ['f_23', 'f_195', 'f_413', 'f_635', 'f_118'], ['f_308', 'f_616', 'f_789', 'f_785', 'f_25'], ['f_366', 'f_831', 'f_834', 'f_460', 'f_510'], ['f_346', 'f_726', 'f_429', 'f_799', 'f_722'], ['f_406', 'f_529', 'f_791', 'f_725', 'f_27'], ['f_287', 'f_631', 'f_292', 'f_35', 'f_836'], ['f_186', 'f_845', 'f_511', 'f_436', 'f_202'], ['f_571', 'f_773', 'f_736', 'f_327', 'f_749'], ['f_2', 'f_788', 'f_526', 'f_587', 'f_47'], ['f_192', 'f_131', 'f_46', 'f_455', 'f_407'], ['f_338', 'f_820', 'f_866', 'f_401', 'f_792'], ['f_3', 'f_508', 'f_477', 'f_330', 'f_298'], ['f_656', 'f_151', 'f_583', 'f_297', 'f_719'], ['f_697', 'f_830', 'f_815', 'f_448', 'f_670'], ['f_617', 'f_757', 'f_752', 'f_676', 'f_214'], ['f_19', 'f_509', 'f_466', 'f_764', 'f_427'], ['f_672', 'f_767', 'f_43', 'f_167', 'f_622'], ['f_566', 'f_417', 'f_675', 'f_833', 'f_568'], ['f_392', 'f_840', 'f_554', 'f_229', 'f_505'], ['f_380', 'f_650', 'f_750', 'f_715', 'f_706'], ['f_15', 'f_861', 'f_782', 'f_408', 'f_26'], ['f_452', 'f_518', 'f_388', 'f_827', 'f_350'], ['f_335', 'f_813', 'f_474', 'f_778', 'f_486'], ['f_440', 'f_728', 'f_497', 'f_551', 'f_262'], ['f_181', 'f_166', 'f_132', 'f_361', 'f_763'], ['f_299', 'f_839', 'f_419', 'f_653', 'f_461'], ['f_12', 'f_409', 'f_609', 'f_473', 'f_207'], ['f_391', 'f_394', 'f_242', 'f_475', 'f_812'], ['f_339', 'f_489', 'f_738', 'f_398', 'f_343'], ['f_614', 'f_488', 'f_588', 'f_533', 'f_522'], ['f_659', 'f_770', 'f_116', 'f_483', 'f_740'], ['f_143', 'f_801', 'f_558', 'f_164', 'f_721'], ['f_146', 'f_347', 'f_759', 'f_742', 'f_115'], ['f_393', 'f_860', 'f_496', 'f_471', 'f_625'], ['f_643', 'f_230', 'f_644', 'f_513', 'f_30'], ['f_37', 'f_159', 'f_129', 'f_575', 'f_494'], ['f_528', 'f_467', 'f_144', 'f_514', 'f_411'], ['f_180', 'f_454', 'f_22', 'f_216', 'f_422'], ['f_516', 'f_425', 'f_826', 'f_480', 'f_717'], ['f_185', 'f_423', 'f_456', 'f_543', 'f_780'], ['f_712', 'f_34', 'f_805', 'f_314', 'f_215'], ['f_420', 'f_822', 'f_359', 'f_630', 'f_559'], ['f_257', 'f_227', 'f_647', 'f_38', 'f_160'], ['f_405', 'f_336', 'f_465', 'f_694', 'f_213'], ['f_24', 'f_687', 'f_397', 'f_761', 'f_421'], ['f_639', 'f_500', 'f_517', 'f_200', 'f_652'], ['f_451', 'f_367', 'f_621', 'f_249', 'f_395'], ['f_341', 'f_363', 'f_260', 'f_803', 'f_301'], ['f_11', 'f_784', 'f_713', 'f_305', 'f_364'], ['f_540', 'f_610', 'f_400', 'f_187', 'f_711'], ['f_33', 'f_824', 'f_515', 'f_612', 'f_707'], ['f_340', 'f_605', 'f_457', 'f_157', 'f_734'], ['f_535', 'f_414', 'f_206', 'f_300', 'f_658'], ['f_667', 'f_378', 'f_563', 'f_532', 'f_399'], ['f_696', 'f_601', 'f_661', 'f_383', 'f_17'], ['f_638', 'f_334', 'f_531', 'f_716', 'f_544'], ['f_682', 'f_458', 'f_776', 'f_598', 'f_527'], ['f_439', 'f_700', 'f_459', 'f_152', 'f_503'], ['f_681', 'f_624', 'f_737', 'f_349', 'f_501'], ['f_611', 'f_705', 'f_779', 'f_362', 'f_590'], ['f_569', 'f_337', 'f_250', 'f_673', 'f_620'], ['f_365', 'f_537', 'f_485', 'f_251', 'f_591'], ['f_199', 'f_438', 'f_586', 'f_342', 'f_701'], ['f_16', 'f_819', 'f_550', 'f_507', 'f_800'], ['f_613', 'f_462', 'f_499', 'f_735', 'f_412'], ['f_579', 'f_504', 'f_756', 'f_188', 'f_294'], ['f_698', 'f_547', 'f_385', 'f_663', 'f_368'], ['f_637', 'f_572', 'f_755', 'f_615', 'f_353'], ['f_345', 'f_686', 'f_386', 'f_632', 'f_293'], ['f_248', 'f_153', 'f_703', 'f_372', 'f_623'], ['f_699', 'f_450', 'f_685', 'f_758', 'f_690'], ['f_683', 'f_693', 'f_243', 'f_193', 'f_662'], ['f_646', 'f_432', 'f_389', 'f_714', 'f_577'], ['f_684', 'f_484', 'f_798', 'f_821', 'f_21'], ['f_443', 'f_261', 'f_567', 'f_435', 'f_797'], ['f_593', 'f_818', 'f_565', 'f_695', 'f_445'], ['f_645', 'f_626', 'f_150', 'f_674', 'f_642'], ['f_704', 'f_379', 'f_589', 'f_13', 'f_244'], ['f_553', 'f_596', 'f_476', 'f_581', 'f_536'], ['f_689', 'f_636', 'f_580', 'f_241', 'f_702'], ['f_692', 'f_487', 'f_604', 'f_602', 'f_258'], ['f_671', 'f_519', 'f_542', 'f_691', 'f_576'], ['f_18', 'f_491', 'f_777', 'f_493', 'f_375'], ['f_14', 'f_373', 'f_597', 'f_382', 'f_560'], ['f_390', 'f_447', 'f_594', 'f_377', 'f_654'], ['f_573', 'f_521', 'f_600', 'f_666', 'f_145'], ['f_641', 'f_357', 'f_633', 'f_286', 'f_259'], ['f_592', 'f_530', 'f_651', 'f_431', 'f_680'], ['f_464', 'f_606', 'f_539', 'f_352', 'f_403'], ['f_619', 'f_472', 'f_9', 'f_665', 'f_381'], ['f_333', 'f_506', 'f_541', 'f_502', 'f_555'], ['f_709', 'f_482', 'f_498', 'f_546', 'f_655'], ['f_549', 'f_574', 'f_396', 'f_283', 'f_523'], ['f_688', 'f_387', 'f_548', 'f_628', 'f_453'], ['f_285', 'f_358', 'f_710', 'f_585', 'f_538'], ['f_442', 'f_679', 'f_657', 'f_356', 'f_256'], ['f_351', 'f_418', 'f_708', 'f_495', 'f_179'], ['f_430', 'f_437', 'f_0', 'f_545', 'f_607'], ['f_1', 'f_376', 'f_371', 'f_449', 'f_599'], ['f_332', 'f_618', 'f_344', 'f_370', 'f_434'], ['f_564', 'f_284', 'f_578', 'f_10', 'f_446'], ['f_664', 'f_582', 'f_255', 'f_178', 'f_603'], ['f_570', 'f_416', 'f_677', 'f_441', 'f_640'], ['f_520', 'f_556', 'f_355', 'f_524', 'f_384'], ['f_678', 'f_552', 'f_490', 'f_584', 'f_608'], ['f_660', 'f_595', 'f_470', 'f_668', 'f_634']]
XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5128616, HammingLoss: 0.19529, SubsetAccuracy: 0.1374,
pruning: False, include_original_features: with_org, averageAUROC: 0.5554486, HammingLoss: 0.27417, SubsetAccuracy: 0.061069,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.19656, SubsetAccuracy: 0.12977,
pruning: False, include_original_features: no_org, averageAUROC: 0.5453141, HammingLoss: 0.28053, SubsetAccuracy: 0.045802,

Fold 7/10 (fingerprint_all 7/9)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:27<00:00,  6.16feat/s]

XofN_groups: [['f_374', 'f_831', 'f_31', 'f_194', 'f_834'], ['f_20', 'f_629', 'f_792', 'f_214', 'f_497'], ['f_23', 'f_408', 'f_292', 'f_428', 'f_118'], ['f_346', 'f_789', 'f_413', 'f_749', 'f_460'], ['f_308', 'f_616', 'f_726', 'f_25', 'f_722'], ['f_406', 'f_768', 'f_27', 'f_791', 'f_785'], ['f_366', 'f_820', 'f_510', 'f_836', 'f_676'], ['f_287', 'f_631', 'f_35', 'f_635', 'f_47'], ['f_2', 'f_529', 'f_328', 'f_725', 'f_587'], ['f_656', 'f_866', 'f_526', 'f_706', 'f_26'], ['f_451', 'f_151', 'f_845', 'f_436', 'f_773'], ['f_335', 'f_815', 'f_511', 'f_350', 'f_736'], ['f_571', 'f_799', 'f_752', 'f_330', 'f_427'], ['f_299', 'f_840', 'f_229', 'f_583', 'f_675'], ['f_672', 'f_830', 'f_167', 'f_43', 'f_46'], ['f_19', 'f_327', 'f_202', 'f_771', 'f_767'], ['f_391', 'f_788', 'f_719', 'f_505', 'f_417'], ['f_393', 'f_861', 'f_670', 'f_764', 'f_715'], ['f_338', 'f_455', 'f_757', 'f_729', 'f_298'], ['f_617', 'f_813', 'f_778', 'f_297', 'f_401'], ['f_516', 'f_509', 'f_407', 'f_262', 'f_827'], ['f_643', 'f_622', 'f_839', 'f_554', 'f_388'], ['f_566', 'f_477', 'f_242', 'f_833', 'f_650'], ['f_639', 'f_166', 'f_533', 'f_409', 'f_728'], ['f_339', 'f_429', 'f_750', 'f_131', 'f_782'], ['f_697', 'f_812', 'f_474', 'f_518', 'f_207'], ['f_15', 'f_448', 'f_230', 'f_466', 'f_759'], ['f_3', 'f_496', 'f_423', 'f_471', 'f_770'], ['f_392', 'f_398', 'f_195', 'f_361', 'f_116'], ['f_405', 'f_568', 'f_164', 'f_215', 'f_343'], ['f_528', 'f_486', 'f_860', 'f_653', 'f_558'], ['f_185', 'f_132', 'f_763', 'f_609', 'f_159'], ['f_614', 'f_508', 'f_394', 'f_588', 'f_551'], ['f_186', 'f_473', 'f_30', 'f_494', 'f_625'], ['f_452', 'f_644', 'f_456', 'f_513', 'f_805'], ['f_380', 'f_419', 'f_483', 'f_738', 'f_721'], ['f_440', 'f_467', 'f_559', 'f_742', 'f_216'], ['f_24', 'f_740', 'f_129', 'f_694', 'f_461'], ['f_143', 'f_543', 'f_717', 'f_347', 'f_647'], ['f_12', 'f_522', 'f_475', 'f_822', 'f_411'], ['f_181', 'f_454', 'f_801', 'f_314', 'f_488'], ['f_712', 'f_489', 'f_425', 'f_826', 'f_780'], ['f_341', 'f_422', 'f_514', 'f_200', 'f_480'], ['f_345', 'f_144', 'f_160', 'f_575', 'f_364'], ['f_192', 'f_421', 'f_517', 'f_687', 'f_115'], ['f_11', 'f_336', 'f_784', 'f_34', 'f_624'], ['f_638', 'f_711', 'f_38', 'f_500', 'f_515'], ['f_659', 'f_465', 'f_713', 'f_213', 'f_227'], ['f_146', 'f_363', 'f_803', 'f_305', 'f_157'], ['f_696', 'f_378', 'f_367', 'f_395', 'f_716'], ['f_420', 'f_621', 'f_22', 'f_301', 'f_249'], ['f_257', 'f_605', 'f_17', 'f_414', 'f_397'], ['f_540', 'f_610', 'f_652', 'f_359', 'f_334'], ['f_439', 'f_700', 'f_457', 'f_300', 'f_187'], ['f_535', 'f_260', 'f_630', 'f_532', 'f_612'], ['f_682', 'f_383', 'f_776', 'f_400', 'f_598'], ['f_443', 'f_601', 'f_206', 'f_658', 'f_737'], ['f_340', 'f_337', 'f_761', 'f_458', 'f_152'], ['f_667', 'f_459', 'f_707', 'f_563', 'f_294'], ['f_646', 'f_705', 'f_531', 'f_485', 'f_734'], ['f_686', 'f_438', 'f_586', 'f_779', 'f_503'], ['f_180', 'f_661', 'f_349', 'f_800', 'f_342'], ['f_37', 'f_527', 'f_701', 'f_673', 'f_412'], ['f_579', 'f_250', 'f_499', 'f_501', 'f_663'], ['f_33', 'f_824', 'f_547', 'f_462', 'f_362'], ['f_692', 'f_544', 'f_507', 'f_399', 'f_591'], ['f_613', 'f_537', 'f_153', 'f_251', 'f_550'], ['f_681', 'f_435', 'f_756', 'f_615', 'f_368'], ['f_698', 'f_572', 'f_188', 'f_353', 'f_755'], ['f_365', 'f_819', 'f_386', 'f_293', 'f_685'], ['f_699', 'f_450', 'f_623', 'f_21', 'f_385'], ['f_611', 'f_798', 'f_577', 'f_620', 'f_690'], ['f_248', 'f_243', 'f_632', 'f_536', 'f_590'], ['f_464', 'f_693', 'f_193', 'f_504', 'f_703'], ['f_567', 'f_372', 'f_432', 'f_758', 'f_602'], ['f_645', 'f_735', 'f_389', 'f_797', 'f_581'], ['f_691', 'f_818', 'f_484', 'f_597', 'f_13'], ['f_553', 'f_714', 'f_596', 'f_199', 'f_642'], ['f_684', 'f_379', 'f_662', 'f_821', 'f_150'], ['f_569', 'f_777', 'f_493', 'f_445', 'f_244'], ['f_637', 'f_674', 'f_695', 'f_565', 'f_580'], ['f_592', 'f_261', 'f_626', 'f_671', 'f_519'], ['f_390', 'f_241', 'f_589', 'f_636', 'f_702'], ['f_16', 'f_476', 'f_704', 'f_491', 'f_377'], ['f_145', 'f_604', 'f_593', 'f_689', 'f_576'], ['f_14', 'f_258', 'f_542', 'f_487', 'f_666'], ['f_683', 'f_373', 'f_594', 'f_560', 'f_382'], ['f_375', 'f_651', 'f_530', 'f_688', 'f_447'], ['f_285', 'f_521', 'f_606', 'f_654', 'f_600'], ['f_573', 'f_357', 'f_502', 'f_381', 'f_9'], ['f_680', 'f_431', 'f_541', 'f_546', 'f_259'], ['f_18', 'f_539', 'f_498', 'f_628', 'f_555'], ['f_333', 'f_506', 'f_574', 'f_665', 'f_453'], ['f_619', 'f_472', 'f_633', 'f_286', 'f_523'], ['f_641', 'f_482', 'f_283', 'f_437', 'f_548'], ['f_607', 'f_403', 'f_655', 'f_352', 'f_538'], ['f_430', 'f_396', 'f_549', 'f_0', 'f_387'], ['f_708', 'f_358', 'f_657', 'f_344', 'f_418'], ['f_351', 'f_256', 'f_179', 'f_585', 'f_442'], ['f_709', 'f_495', 'f_284', 'f_545', 'f_356'], ['f_710', 'f_376', 'f_10', 'f_449', 'f_599'], ['f_332', 'f_371', 'f_1', 'f_618', 'f_679'], ['f_178', 'f_370', 'f_582', 'f_578', 'f_416'], ['f_564', 'f_441', 'f_255', 'f_434', 'f_603'], ['f_446', 'f_584', 'f_355', 'f_640', 'f_384'], ['f_520', 'f_490', 'f_664', 'f_524', 'f_595'], ['f_570', 'f_678', 'f_677', 'f_556', 'f_552'], ['f_660', 'f_608', 'f_470', 'f_668', 'f_634']]
XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5283742, HammingLoss: 0.20038, SubsetAccuracy: 0.1145,
pruning: False, include_original_features: with_org, averageAUROC: 0.5765869, HammingLoss: 0.27799, SubsetAccuracy: 0.068702,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.20293, SubsetAccuracy: 0.10687,
pruning: False, include_original_features: no_org, averageAUROC: 0.5634492, HammingLoss: 0.28372, SubsetAccuracy: 0.045802,

Fold 8/10 (fingerprint_all 7/9)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:27<00:00,  6.15feat/s]

XofN_groups: [['f_374', 'f_831', 'f_834', 'f_202', 'f_31'], ['f_20', 'f_729', 'f_629', 'f_428', 'f_194'], ['f_346', 'f_749', 'f_768', 'f_460', 'f_27'], ['f_308', 'f_616', 'f_789', 'f_722', 'f_25'], ['f_2', 'f_635', 'f_726', 'f_413', 'f_771'], ['f_571', 'f_773', 'f_799', 'f_429', 'f_670'], ['f_406', 'f_836', 'f_791', 'f_788', 'f_118'], ['f_15', 'f_866', 'f_845', 'f_214', 'f_529'], ['f_366', 'f_427', 'f_466', 'f_736', 'f_509'], ['f_23', 'f_195', 'f_292', 'f_47', 'f_166'], ['f_672', 'f_830', 'f_43', 'f_526', 'f_35'], ['f_566', 'f_417', 'f_328', 'f_477', 'f_622'], ['f_656', 'f_151', 'f_510', 'f_436', 'f_583'], ['f_639', 'f_715', 'f_511', 'f_297', 'f_750'], ['f_338', 'f_820', 'f_401', 'f_497', 'f_792'], ['f_185', 'f_587', 'f_26', 'f_131', 'f_675'], ['f_339', 'f_330', 'f_778', 'f_813', 'f_489'], ['f_19', 'f_327', 'f_785', 'f_767', 'f_262'], ['f_287', 'f_408', 'f_164', 'f_740', 'f_609'], ['f_391', 'f_725', 'f_719', 'f_505', 'f_839'], ['f_299', 'f_861', 'f_229', 'f_764', 'f_554'], ['f_452', 'f_757', 'f_455', 'f_676', 'f_46'], ['f_3', 'f_409', 'f_759', 'f_508', 'f_782'], ['f_186', 'f_388', 'f_474', 'f_298', 'f_728'], ['f_12', 'f_350', 'f_815', 'f_448', 'f_473'], ['f_516', 'f_407', 'f_812', 'f_827', 'f_475'], ['f_643', 'f_840', 'f_486', 'f_471', 'f_763'], ['f_335', 'f_752', 'f_533', 'f_650', 'f_522'], ['f_392', 'f_631', 'f_706', 'f_496', 'f_30'], ['f_617', 'f_644', 'f_833', 'f_551', 'f_116'], ['f_659', 'f_568', 'f_770', 'f_483', 'f_115'], ['f_24', 'f_215', 'f_653', 'f_167', 'f_559'], ['f_393', 'f_242', 'f_419', 'f_461', 'f_625'], ['f_380', 'f_647', 'f_343', 'f_738', 'f_721'], ['f_440', 'f_518', 'f_543', 'f_230', 'f_207'], ['f_697', 'f_494', 'f_132', 'f_361', 'f_742'], ['f_712', 'f_394', 'f_34', 'f_801', 'f_784'], ['f_192', 'f_129', 'f_411', 'f_422', 'f_513'], ['f_143', 'f_588', 'f_717', 'f_314', 'f_826'], ['f_528', 'f_558', 'f_860', 'f_517', 'f_630'], ['f_614', 'f_488', 'f_398', 'f_822', 'f_456'], ['f_451', 'f_803', 'f_780', 'f_454', 'f_425'], ['f_257', 'f_144', 'f_347', 'f_216', 'f_159'], ['f_146', 'f_38', 'f_363', 'f_805', 'f_213'], ['f_696', 'f_480', 'f_467', 'f_200', 'f_652'], ['f_535', 'f_359', 'f_336', 'f_465', 'f_227'], ['f_405', 'f_423', 'f_687', 'f_364', 'f_305'], ['f_340', 'f_575', 'f_160', 'f_514', 'f_711'], ['f_341', 'f_421', 'f_515', 'f_206', 'f_737'], ['f_181', 'f_395', 'f_400', 'f_605', 'f_713'], ['f_37', 'f_527', 'f_367', 'f_800', 'f_378'], ['f_638', 'f_334', 'f_500', 'f_300', 'f_707'], ['f_540', 'f_610', 'f_457', 'f_694', 'f_397'], ['f_439', 'f_249', 'f_621', 'f_301', 'f_22'], ['f_611', 'f_705', 'f_414', 'f_157', 'f_187'], ['f_33', 'f_824', 'f_612', 'f_337', 'f_716'], ['f_420', 'f_260', 'f_761', 'f_532', 'f_734'], ['f_443', 'f_601', 'f_661', 'f_658', 'f_399'], ['f_365', 'f_563', 'f_624', 'f_250', 'f_17'], ['f_569', 'f_700', 'f_458', 'f_779', 'f_591'], ['f_579', 'f_459', 'f_544', 'f_485', 'f_503'], ['f_613', 'f_537', 'f_152', 'f_598', 'f_735'], ['f_699', 'f_499', 'f_531', 'f_501', 'f_703'], ['f_684', 'f_438', 'f_586', 'f_756', 'f_362'], ['f_615', 'f_590', 'f_383', 'f_758', 'f_432'], ['f_637', 'f_547', 'f_251', 'f_462', 'f_349'], ['f_686', 'f_294', 'f_412', 'f_673', 'f_386'], ['f_345', 'f_776', 'f_188', 'f_368', 'f_550'], ['f_682', 'f_342', 'f_507', 'f_701', 'f_243'], ['f_667', 'f_373', 'f_662', 'f_623', 'f_293'], ['f_180', 'f_21', 'f_620', 'f_353', 'f_818'], ['f_553', 'f_385', 'f_663', 'f_572', 'f_755'], ['f_645', 'f_819', 'f_504', 'f_577', 'f_690'], ['f_14', 'f_693', 'f_153', 'f_632', 'f_372'], ['f_698', 'f_389', 'f_685', 'f_681', 'f_821'], ['f_646', 'f_797', 'f_484', 'f_565', 'f_581'], ['f_464', 'f_798', 'f_695', 'f_379', 'f_199'], ['f_567', 'f_435', 'f_597', 'f_193', 'f_536'], ['f_683', 'f_13', 'f_589', 'f_674', 'f_671'], ['f_241', 'f_642', 'f_375', 'f_626', 'f_602'], ['f_390', 'f_261', 'f_248', 'f_493', 'f_150'], ['f_16', 'f_476', 'f_445', 'f_704', 'f_244'], ['f_692', 'f_487', 'f_714', 'f_377', 'f_580'], ['f_691', 'f_519', 'f_777', 'f_600', 'f_594'], ['f_593', 'f_604', 'f_576', 'f_702', 'f_9'], ['f_573', 'f_636', 'f_258', 'f_283', 'f_666'], ['f_592', 'f_596', 'f_542', 'f_530', 'f_689'], ['f_680', 'f_491', 'f_633', 'f_382', 'f_560'], ['f_333', 'f_447', 'f_651', 'f_654', 'f_259'], ['f_145', 'f_606', 'f_450', 'f_688', 'f_502'], ['f_285', 'f_521', 'f_541', 'f_431', 'f_641'], ['f_619', 'f_357', 'f_628', 'f_18', 'f_381'], ['f_11', 'f_523', 'f_498', 'f_546', 'f_655'], ['f_332', 'f_539', 'f_574', 'f_657', 'f_555'], ['f_607', 'f_472', 'f_548', 'f_286', 'f_453'], ['f_709', 'f_482', 'f_665', 'f_352', 'f_418'], ['f_1', 'f_506', 'f_549', 'f_356', 'f_538'], ['f_351', 'f_403', 'f_710', 'f_585', 'f_442'], ['f_430', 'f_396', 'f_437', 'f_344', 'f_387'], ['f_708', 'f_358', 'f_545', 'f_0', 'f_256'], ['f_449', 'f_679', 'f_495', 'f_599', 'f_284'], ['f_178', 'f_376', 'f_371', 'f_10', 'f_179'], ['f_434', 'f_255', 'f_582', 'f_618', 'f_416'], ['f_370', 'f_441', 'f_578', 'f_446', 'f_384'], ['f_564', 'f_556', 'f_355', 'f_640', 'f_603'], ['f_664', 'f_490', 'f_552', 'f_524', 'f_595'], ['f_570', 'f_678', 'f_584', 'f_660', 'f_608'], ['f_520', 'f_677', 'f_634', 'f_668', 'f_470']]
XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.4964468, HammingLoss: 0.21056, SubsetAccuracy: 0.061069,
pruning: False, include_original_features: with_org, averageAUROC: 0.5704855, HammingLoss: 0.28117, SubsetAccuracy: 0.053435,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.21247, SubsetAccuracy: 0.053435,
pruning: False, include_original_features: no_org, averageAUROC: 0.5698964, HammingLoss: 0.29071, SubsetAccuracy: 0.038168,

Fold 9/10 (fingerprint_all 7/9)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:27<00:00,  6.15feat/s]

XofN_groups: [['f_374', 'f_836', 'f_27', 'f_202', 'f_510'], ['f_20', 'f_792', 'f_629', 'f_194', 'f_635'], ['f_23', 'f_687', 'f_631', 'f_31', 'f_118'], ['f_287', 'f_195', 'f_413', 'f_428', 'f_529'], ['f_308', 'f_616', 'f_831', 'f_785', 'f_328'], ['f_346', 'f_789', 'f_330', 'f_427', 'f_799'], ['f_2', 'f_768', 'f_47', 'f_587', 'f_25'], ['f_338', 'f_726', 'f_460', 'f_845', 'f_455'], ['f_672', 'f_292', 'f_830', 'f_167', 'f_43'], ['f_393', 'f_866', 'f_214', 'f_622', 'f_773'], ['f_516', 'f_350', 'f_771', 'f_436', 'f_26'], ['f_366', 'f_417', 'f_327', 'f_526', 'f_736'], ['f_571', 'f_675', 'f_815', 'f_511', 'f_788'], ['f_406', 'f_791', 'f_725', 'f_722', 'f_151'], ['f_656', 'f_706', 'f_448', 'f_719', 'f_297'], ['f_392', 'f_861', 'f_670', 'f_229', 'f_752'], ['f_380', 'f_767', 'f_554', 'f_650', 'f_497'], ['f_299', 'f_840', 'f_583', 'f_509', 'f_408'], ['f_614', 'f_729', 'f_757', 'f_166', 'f_46'], ['f_566', 'f_839', 'f_715', 'f_834', 'f_262'], ['f_440', 'f_728', 'f_388', 'f_466', 'f_298'], ['f_697', 'f_35', 'f_749', 'f_518', 'f_764'], ['f_617', 'f_820', 'f_401', 'f_676', 'f_833'], ['f_24', 'f_216', 'f_803', 'f_159', 'f_609'], ['f_19', 'f_505', 'f_496', 'f_782', 'f_770'], ['f_15', 'f_827', 'f_230', 'f_763', 'f_407'], ['f_339', 'f_429', 'f_750', 'f_131', 'f_778'], ['f_643', 'f_461', 'f_740', 'f_242', 'f_568'], ['f_185', 'f_474', 'f_409', 'f_30', 'f_812'], ['f_696', 'f_508', 'f_813', 'f_411', 'f_477'], ['f_335', 'f_644', 'f_471', 'f_647', 'f_343'], ['f_391', 'f_551', 'f_394', 'f_473', 'f_164'], ['f_186', 'f_475', 'f_314', 'f_215', 'f_207'], ['f_659', 'f_419', 'f_361', 'f_653', 'f_116'], ['f_452', 'f_363', 'f_336', 'f_621', 'f_759'], ['f_451', 'f_115', 'f_822', 'f_347', 'f_742'], ['f_528', 'f_486', 'f_558', 'f_860', 'f_425'], ['f_192', 'f_132', 'f_456', 'f_494', 'f_513'], ['f_12', 'f_454', 'f_738', 'f_721', 'f_522'], ['f_341', 'f_533', 'f_398', 'f_801', 'f_160'], ['f_405', 'f_488', 'f_588', 'f_483', 'f_517'], ['f_712', 'f_489', 'f_543', 'f_22', 'f_717'], ['f_3', 'f_423', 'f_422', 'f_250', 'f_480'], ['f_143', 'f_625', 'f_780', 'f_559', 'f_826'], ['f_181', 'f_129', 'f_694', 'f_144', 'f_467'], ['f_146', 'f_575', 'f_514', 'f_711', 'f_38'], ['f_639', 'f_395', 'f_187', 'f_200', 'f_515'], ['f_340', 'f_367', 'f_213', 'f_713', 'f_465'], ['f_540', 'f_610', 'f_652', 'f_421', 'f_249'], ['f_420', 'f_784', 'f_359', 'f_305', 'f_227'], ['f_257', 'f_605', 'f_301', 'f_716', 'f_17'], ['f_613', 'f_661', 'f_364', 'f_34', 'f_805'], ['f_439', 'f_337', 'f_260', 'f_761', 'f_532'], ['f_365', 'f_157', 'f_630', 'f_300', 'f_500'], ['f_667', 'f_612', 'f_414', 'f_563', 'f_707'], ['f_37', 'f_527', 'f_700', 'f_397', 'f_658'], ['f_681', 'f_457', 'f_152', 'f_598', 'f_737'], ['f_11', 'f_206', 'f_458', 'f_624', 'f_462'], ['f_638', 'f_334', 'f_531', 'f_378', 'f_734'], ['f_611', 'f_705', 'f_459', 'f_779', 'f_544'], ['f_569', 'f_824', 'f_383', 'f_776', 'f_400'], ['f_443', 'f_601', 'f_590', 'f_503', 'f_399'], ['f_682', 'f_342', 'f_586', 'f_673', 'f_701'], ['f_535', 'f_362', 'f_800', 'f_153', 'f_188'], ['f_567', 'f_435', 'f_756', 'f_412', 'f_294'], ['f_345', 'f_537', 'f_485', 'f_251', 'f_501'], ['f_684', 'f_438', 'f_735', 'f_591', 'f_349'], ['f_698', 'f_547', 'f_507', 'f_703', 'f_550'], ['f_686', 'f_379', 'f_797', 'f_615', 'f_353'], ['f_248', 'f_499', 'f_632', 'f_368', 'f_663'], ['f_645', 'f_819', 'f_572', 'f_577', 'f_755'], ['f_33', 'f_798', 'f_685', 'f_389', 'f_620'], ['f_637', 'f_385', 'f_674', 'f_432', 'f_21'], ['f_646', 'f_818', 'f_504', 'f_565', 'f_293'], ['f_579', 'f_386', 'f_690', 'f_372', 'f_193'], ['f_14', 'f_693', 'f_243', 'f_199', 'f_662'], ['f_692', 'f_484', 'f_626', 'f_13', 'f_758'], ['f_683', 'f_261', 'f_699', 'f_580', 'f_636'], ['f_180', 'f_581', 'f_150', 'f_589', 'f_536'], ['f_241', 'f_642', 'f_560', 'f_476', 'f_602'], ['f_390', 'f_714', 'f_623', 'f_596', 'f_821'], ['f_689', 'f_519', 'f_597', 'f_702', 'f_445'], ['f_464', 'f_777', 'f_695', 'f_487', 'f_594'], ['f_592', 'f_244', 'f_671', 'f_491', 'f_604'], ['f_553', 'f_258', 'f_542', 'f_375', 'f_691'], ['f_285', 'f_493', 'f_373', 'f_382', 'f_593'], ['f_16', 'f_666', 'f_704', 'f_447', 'f_377'], ['f_145', 'f_651', 'f_600', 'f_450', 'f_680'], ['f_573', 'f_521', 'f_633', 'f_654', 'f_606'], ['f_333', 'f_357', 'f_541', 'f_576', 'f_502'], ['f_688', 'f_530', 'f_381', 'f_546', 'f_259'], ['f_18', 'f_431', 'f_498', 'f_628', 'f_539'], ['f_619', 'f_472', 'f_9', 'f_665', 'f_555'], ['f_641', 'f_506', 'f_283', 'f_437', 'f_574'], ['f_351', 'f_523', 'f_655', 'f_453', 'f_710'], ['f_430', 'f_482', 'f_548', 'f_585', 'f_286'], ['f_1', 'f_403', 'f_549', 'f_709', 'f_538'], ['f_708', 'f_396', 'f_449', 'f_352', 'f_387'], ['f_599', 'f_358', 'f_657', 'f_0', 'f_356'], ['f_332', 'f_256', 'f_607', 'f_442', 'f_179'], ['f_178', 'f_418', 'f_545', 'f_679', 'f_495'], ['f_564', 'f_376', 'f_284', 'f_434', 'f_344'], ['f_664', 'f_10', 'f_371', 'f_582', 'f_255'], ['f_370', 'f_441', 'f_618', 'f_416', 'f_603'], ['f_446', 'f_578', 'f_355', 'f_640', 'f_524'], ['f_570', 'f_660', 'f_384', 'f_556', 'f_677'], ['f_520', 'f_490', 'f_584', 'f_678', 'f_595'], ['f_668', 'f_470', 'f_608', 'f_552', 'f_634']]
XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5075387, HammingLoss: 0.19148, SubsetAccuracy: 0.1145,
pruning: False, include_original_features: with_org, averageAUROC: 0.5538615, HammingLoss: 0.27672, SubsetAccuracy: 0.061069,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.19338, SubsetAccuracy: 0.099237,
pruning: False, include_original_features: no_org, averageAUROC: 0.5751454, HammingLoss: 0.28562, SubsetAccuracy: 0.030534,

Fold 10/10 (fingerprint_all 7/9)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:27<00:00,  6.16feat/s]

XofN_groups: [['f_374', 'f_831', 'f_31', 'f_834', 'f_202'], ['f_20', 'f_729', 'f_629', 'f_635', 'f_194'], ['f_308', 'f_791', 'f_529', 'f_25', 'f_788'], ['f_287', 'f_413', 'f_195', 'f_428', 'f_118'], ['f_346', 'f_789', 'f_510', 'f_330', 'f_460'], ['f_23', 'f_631', 'f_292', 'f_164', 'f_836'], ['f_393', 'f_866', 'f_214', 'f_27', 'f_622'], ['f_366', 'f_726', 'f_509', 'f_427', 'f_466'], ['f_406', 'f_616', 'f_768', 'f_785', 'f_328'], ['f_2', 'f_725', 'f_526', 'f_47', 'f_587'], ['f_186', 'f_845', 'f_511', 'f_436', 'f_773'], ['f_338', 'f_820', 'f_771', 'f_401', 'f_497'], ['f_299', 'f_151', 'f_815', 'f_43', 'f_719'], ['f_672', 'f_830', 'f_752', 'f_297', 'f_229'], ['f_566', 'f_417', 'f_327', 'f_676', 'f_799'], ['f_614', 'f_749', 'f_767', 'f_166', 'f_131'], ['f_391', 'f_782', 'f_505', 'f_408', 'f_839'], ['f_571', 'f_736', 'f_728', 'f_429', 'f_215'], ['f_697', 'f_35', 'f_609', 'f_448', 'f_670'], ['f_15', 'f_861', 'f_764', 'f_675', 'f_715'], ['f_617', 'f_778', 'f_750', 'f_554', 'f_455'], ['f_452', 'f_518', 'f_757', 'f_722', 'f_388'], ['f_19', 'f_583', 'f_350', 'f_477', 'f_770'], ['f_335', 'f_813', 'f_486', 'f_26', 'f_625'], ['f_12', 'f_46', 'f_474', 'f_343', 'f_394'], ['f_339', 'f_568', 'f_833', 'f_483', 'f_298'], ['f_639', 'f_533', 'f_409', 'f_522', 'f_650'], ['f_516', 'f_407', 'f_812', 'f_827', 'f_508'], ['f_440', 'f_792', 'f_706', 'f_425', 'f_496'], ['f_643', 'f_840', 'f_262', 'f_471', 'f_398'], ['f_528', 'f_230', 'f_822', 'f_30', 'f_763'], ['f_192', 'f_473', 'f_216', 'f_361', 'f_419'], ['f_656', 'f_551', 'f_167', 'f_116', 'f_461'], ['f_3', 'f_759', 'f_475', 'f_624', 'f_314'], ['f_24', 'f_740', 'f_559', 'f_213', 'f_647'], ['f_659', 'f_242', 'f_644', 'f_653', 'f_513'], ['f_143', 'f_738', 'f_558', 'f_411', 'f_721'], ['f_392', 'f_860', 'f_467', 'f_456', 'f_454'], ['f_185', 'f_132', 'f_207', 'f_494', 'f_742'], ['f_451', 'f_115', 'f_347', 'f_543', 'f_717'], ['f_405', 'f_588', 'f_488', 'f_336', 'f_780'], ['f_146', 'f_801', 'f_514', 'f_784', 'f_144'], ['f_380', 'f_422', 'f_805', 'f_363', 'f_480'], ['f_341', 'f_517', 'f_500', 'f_826', 'f_200'], ['f_420', 'f_38', 'f_159', 'f_129', 'f_465'], ['f_712', 'f_489', 'f_22', 'f_515', 'f_707'], ['f_439', 'f_367', 'f_423', 'f_711', 'f_364'], ['f_181', 'f_395', 'f_160', 'f_575', 'f_457'], ['f_33', 'f_803', 'f_397', 'f_716', 'f_249'], ['f_257', 'f_227', 'f_687', 'f_359', 'f_652'], ['f_540', 'f_610', 'f_414', 'f_694', 'f_334'], ['f_569', 'f_705', 'f_532', 'f_157', 'f_301'], ['f_180', 'f_34', 'f_713', 'f_630', 'f_612'], ['f_696', 'f_421', 'f_621', 'f_206', 'f_737'], ['f_667', 'f_378', 'f_563', 'f_531', 'f_400'], ['f_638', 'f_300', 'f_605', 'f_383', 'f_187'], ['f_37', 'f_399', 'f_701', 'f_658', 'f_673'], ['f_611', 'f_337', 'f_305', 'f_544', 'f_260'], ['f_443', 'f_601', 'f_661', 'f_586', 'f_800'], ['f_390', 'f_761', 'f_152', 'f_458', 'f_537'], ['f_11', 'f_17', 'f_459', 'f_824', 'f_734'], ['f_365', 'f_700', 'f_527', 'f_503', 'f_776'], ['f_682', 'f_342', 'f_349', 'f_779', 'f_188'], ['f_613', 'f_462', 'f_485', 'f_598', 'f_735'], ['f_535', 'f_250', 'f_153', 'f_501', 'f_756'], ['f_345', 'f_819', 'f_499', 'f_362', 'f_412'], ['f_646', 'f_432', 'f_251', 'f_547', 'f_591'], ['f_579', 'f_438', 'f_590', 'f_550', 'f_507'], ['f_681', 'f_435', 'f_294', 'f_755', 'f_615'], ['f_340', 'f_686', 'f_385', 'f_663', 'f_368'], ['f_684', 'f_572', 'f_620', 'f_353', 'f_703'], ['f_698', 'f_389', 'f_293', 'f_690', 'f_758'], ['f_645', 'f_797', 'f_504', 'f_632', 'f_577'], ['f_593', 'f_818', 'f_623', 'f_662', 'f_372'], ['f_683', 'f_693', 'f_243', 'f_193', 'f_567'], ['f_685', 'f_798', 'f_484', 'f_642', 'f_821'], ['f_637', 'f_379', 'f_199', 'f_493', 'f_21'], ['f_692', 'f_674', 'f_565', 'f_13', 'f_386'], ['f_248', 'f_150', 'f_597', 'f_445', 'f_714'], ['f_691', 'f_519', 'f_671', 'f_581', 'f_244'], ['f_241', 'f_536', 'f_626', 'f_596', 'f_702'], ['f_464', 'f_777', 'f_695', 'f_636', 'f_476'], ['f_16', 'f_699', 'f_580', 'f_589', 'f_491'], ['f_553', 'f_261', 'f_604', 'f_602', 'f_450'], ['f_704', 'f_487', 'f_666', 'f_576', 'f_377'], ['f_18', 'f_258', 'f_594', 'f_560', 'f_542'], ['f_14', 'f_373', 'f_382', 'f_654', 'f_689'], ['f_145', 'f_651', 'f_447', 'f_9', 'f_600'], ['f_628', 'f_606', 'f_375', 'f_357', 'f_680'], ['f_573', 'f_521', 'f_633', 'f_259', 'f_381'], ['f_592', 'f_530', 'f_541', 'f_431', 'f_286'], ['f_333', 'f_506', 'f_498', 'f_502', 'f_555'], ['f_619', 'f_472', 'f_283', 'f_665', 'f_655'], ['f_549', 'f_641', 'f_539', 'f_352', 'f_523'], ['f_285', 'f_482', 'f_574', 'f_546', 'f_688'], ['f_1', 'f_403', 'f_548', 'f_437', 'f_538'], ['f_709', 'f_396', 'f_449', 'f_0', 'f_387'], ['f_332', 'f_358', 'f_607', 'f_453', 'f_710'], ['f_351', 'f_256', 'f_179', 'f_585', 'f_442'], ['f_708', 'f_418', 'f_657', 'f_344', 'f_356'], ['f_599', 'f_495', 'f_284', 'f_545', 'f_430'], ['f_679', 'f_376', 'f_10', 'f_371', 'f_618'], ['f_178', 'f_370', 'f_582', 'f_603', 'f_416'], ['f_564', 'f_441', 'f_578', 'f_446', 'f_255'], ['f_664', 'f_434', 'f_355', 'f_490', 'f_384'], ['f_520', 'f_556', 'f_524', 'f_677', 'f_640'], ['f_660', 'f_570', 'f_584', 'f_678', 'f_552'], ['f_595', 'f_470', 'f_668', 'f_608', 'f_634']]
XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5263954, HammingLoss: 0.19402, SubsetAccuracy: 0.12214,
pruning: False, include_original_features: with_org, averageAUROC: 0.5721553, HammingLoss: 0.25382, SubsetAccuracy: 0.053435,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.1972, SubsetAccuracy: 0.1145,
pruning: False, include_original_features: no_org, averageAUROC: 0.5583862, HammingLoss: 0.26972, SubsetAccuracy: 0.022901,
   pruning include_original_features          dataset  averageAUROC  \
0    False                    no_org  fingerprint_all      0.562382
1    False                  with_org  fingerprint_all      0.570005
2     True                    no_org  fingerprint_all      0.500000
3     True                  with_org  fingerprint_all      0.514791

   HammingLoss  SubsetAccuracy  nodes  leaves  groups  avg_group_features  \
0     0.283841        0.044275  972.4   486.7   108.0                 5.0
1     0.271311        0.064886  974.2   487.6   108.0                 5.0
2     0.200827        0.104580    1.2     1.1   108.0                 5.0
3     0.198918        0.110685    3.2     2.1   108.0                 5.0

   gen_XofN_time  training_time
0      87.712154       0.745348
1      87.712154       1.635671
2      87.712154       0.745348
3      87.712154       1.635671

--- Running with label:'['se_C0027769', 'se_C0020580', 'se_C0014457', 'se_C0017181', 'se_C0151763', 'se_C0038358']' training_algorithm:'Jaccard_min' eval_criterion:'['averageAUROC', 'HammingLoss', 'SubsetAccuracy']' max_size:'5' ---
Logs can be found in XofN_jaccard_min/logs/fingerprint_diverse_Jaccard_min_averageAUROC_HammingLoss_SubsetAccuracy_5_logs.txt.

Fold 1/10 (fingerprint_diverse 8/9)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:27<00:00,  6.15feat/s]

XofN_groups: [['f_374', 'f_771', 'f_768', 'f_31', 'f_194'], ['f_20', 'f_729', 'f_629', 'f_428', 'f_214'], ['f_2', 'f_789', 'f_413', 'f_635', 'f_834'], ['f_335', 'f_511', 'f_752', 'f_726', 'f_719'], ['f_308', 'f_616', 'f_831', 'f_722', 'f_25'], ['f_566', 'f_529', 'f_417', 'f_328', 'f_845'], ['f_528', 'f_151', 'f_836', 'f_43', 'f_27'], ['f_287', 'f_195', 'f_292', 'f_526', 'f_166'], ['f_643', 'f_866', 'f_622', 'f_773', 'f_26'], ['f_346', 'f_460', 'f_725', 'f_749', 'f_510'], ['f_192', 'f_47', 'f_118', 'f_131', 'f_497'], ['f_185', 'f_436', 'f_587', 'f_583', 'f_670'], ['f_12', 'f_509', 'f_788', 'f_764', 'f_401'], ['f_366', 'f_427', 'f_466', 'f_799', 'f_675'], ['f_406', 'f_791', 'f_736', 'f_785', 'f_202'], ['f_656', 'f_706', 'f_782', 'f_297', 'f_407'], ['f_672', 'f_830', 'f_815', 'f_330', 'f_167'], ['f_338', 'f_820', 'f_455', 'f_770', 'f_505'], ['f_391', 'f_408', 'f_827', 'f_394', 'f_350'], ['f_186', 'f_388', 'f_474', 'f_554', 'f_46'], ['f_180', 'f_207', 'f_132', 'f_298', 'f_361'], ['f_392', 'f_861', 'f_327', 'f_486', 'f_229'], ['f_659', 'f_839', 'f_715', 'f_833', 'f_631'], ['f_146', 'f_767', 'f_763', 'f_551', 'f_518'], ['f_23', 'f_740', 'f_164', 'f_129', 'f_609'], ['f_697', 'f_35', 'f_448', 'f_477', 'f_792'], ['f_516', 'f_262', 'f_812', 'f_778', 'f_471'], ['f_682', 'f_757', 'f_242', 'f_419', 'f_215'], ['f_571', 'f_429', 'f_728', 'f_216', 'f_475'], ['f_617', 'f_813', 'f_676', 'f_454', 'f_30'], ['f_393', 'f_840', 'f_568', 'f_513', 'f_653'], ['f_540', 'f_409', 'f_116', 'f_759', 'f_522'], ['f_299', 'f_230', 'f_461', 'f_801', 'f_411'], ['f_181', 'f_343', 'f_508', 'f_398', 'f_200'], ['f_451', 'f_822', 'f_115', 'f_347', 'f_543'], ['f_638', 'f_860', 'f_750', 'f_473', 'f_650'], ['f_439', 'f_826', 'f_314', 'f_717', 'f_644'], ['f_699', 'f_488', 'f_483', 'f_456', 'f_496'], ['f_257', 'f_144', 'f_647', 'f_559', 'f_625'], ['f_405', 'f_588', 'f_159', 'f_533', 'f_780'], ['f_452', 'f_467', 'f_425', 'f_805', 'f_423'], ['f_380', 'f_422', 'f_742', 'f_514', 'f_738'], ['f_713', 'f_34', 'f_784', 'f_213', 'f_336'], ['f_341', 'f_494', 'f_421', 'f_38', 'f_558'], ['f_696', 'f_489', 'f_160', 'f_363', 'f_803'], ['f_712', 'f_301', 'f_721', 'f_22', 'f_532'], ['f_776', 'f_305', 'f_364', 'f_527', 'f_397'], ['f_611', 'f_711', 'f_575', 'f_465', 'f_517'], ['f_645', 'f_337', 'f_621', 'f_480', 'f_687'], ['f_15', 'f_605', 'f_157', 'f_457', 'f_367'], ['f_37', 'f_227', 'f_694', 'f_652', 'f_359'], ['f_339', 'f_395', 'f_716', 'f_187', 'f_515'], ['f_667', 'f_612', 'f_414', 'f_707', 'f_610'], ['f_334', 'f_17', 'f_737', 'f_500', 'f_300'], ['f_646', 'f_24', 'f_761', 'f_260', 'f_458'], ['f_3', 'f_624', 'f_658', 'f_630', 'f_503'], ['f_440', 'f_378', 'f_249', 'f_459', 'f_152'], ['f_340', 'f_206', 'f_601', 'f_705', 'f_531'], ['f_569', 'f_824', 'f_383', 'f_432', 'f_400'], ['f_143', 'f_544', 'f_598', 'f_399', 'f_661'], ['f_614', 'f_685', 'f_250', 'f_586', 'f_563'], ['f_365', 'f_700', 'f_485', 'f_734', 'f_591'], ['f_592', 'f_462', 'f_499', 'f_251', 'f_501'], ['f_683', 'f_537', 'f_547', 'f_779', 'f_188'], ['f_535', 'f_362', 'f_386', 'f_701', 'f_349'], ['f_615', 'f_755', 'f_435', 'f_693', 'f_673'], ['f_16', 'f_819', 'f_342', 'f_800', 'f_507'], ['f_19', 'f_385', 'f_550', 'f_686', 'f_438'], ['f_593', 'f_756', 'f_294', 'f_368', 'f_681'], ['f_345', 'f_590', 'f_243', 'f_412', 'f_662'], ['f_248', 'f_153', 'f_620', 'f_293', 'f_703'], ['f_145', 'f_735', 'f_639', 'f_623', 'f_353'], ['f_698', 'f_572', 'f_663', 'f_577', 'f_33'], ['f_692', 'f_504', 'f_632', 'f_193', 'f_690'], ['f_244', 'f_642', 'f_818', 'f_375', 'f_589'], ['f_553', 'f_13', 'f_389', 'f_565', 'f_758'], ['f_704', 'f_484', 'f_798', 'f_21', 'f_821'], ['f_580', 'f_626', 'f_372', 'f_797', 'f_567'], ['f_502', 'f_777', 'f_602', 'f_493', 'f_199'], ['f_443', 'f_261', 'f_476', 'f_445', 'f_581'], ['f_641', 'f_379', 'f_695', 'f_241', 'f_536'], ['f_420', 'f_596', 'f_714', 'f_597', 'f_150'], ['f_613', 'f_258', 'f_671', 'f_702', 'f_674'], ['f_637', 'f_519', 'f_576', 'f_691', 'f_604'], ['f_579', 'f_491', 'f_594', 'f_450', 'f_377'], ['f_464', 'f_542', 'f_636', 'f_684', 'f_447'], ['f_259', 'f_689', 'f_560', 'f_666', 'f_373'], ['f_573', 'f_521', 'f_600', 'f_654', 'f_382'], ['f_680', 'f_487', 'f_530', 'f_651', 'f_546'], ['f_370', 'f_357', 'f_606', 'f_555', 'f_286'], ['f_655', 'f_431', 'f_9', 'f_628', 'f_381'], ['f_619', 'f_506', 'f_633', 'f_18', 'f_541'], ['f_549', 'f_498', 'f_539', 'f_352', 'f_403'], ['f_437', 'f_574', 'f_472', 'f_688', 'f_523'], ['f_453', 'f_548', 'f_344', 'f_665', 'f_482'], ['f_449', 'f_709', 'f_396', 'f_283', 'f_538'], ['f_607', 'f_387', 'f_0', 'f_657', 'f_710'], ['f_333', 'f_358', 'f_585', 'f_179', 'f_418'], ['f_11', 'f_256', 'f_545', 'f_356', 'f_442'], ['f_390', 'f_495', 'f_708', 'f_376', 'f_599'], ['f_430', 'f_14', 'f_371', 'f_284', 'f_285'], ['f_564', 'f_351', 'f_679', 'f_1', 'f_618'], ['f_434', 'f_10', 'f_603', 'f_255', 'f_332'], ['f_178', 'f_578', 'f_446', 'f_582', 'f_355'], ['f_664', 'f_416', 'f_384', 'f_441', 'f_584'], ['f_470', 'f_490', 'f_524', 'f_677', 'f_640'], ['f_520', 'f_556', 'f_595', 'f_678', 'f_570'], ['f_660', 'f_552', 'f_608', 'f_668', 'f_634']]
XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.4998924, HammingLoss: 0.20707, SubsetAccuracy: 0.43182,
pruning: False, include_original_features: with_org, averageAUROC: 0.5565838, HammingLoss: 0.2702, SubsetAccuracy: 0.25758,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.21212, SubsetAccuracy: 0.40909,
pruning: False, include_original_features: no_org, averageAUROC: 0.5528202, HammingLoss: 0.29293, SubsetAccuracy: 0.22727,

Fold 2/10 (fingerprint_diverse 8/9)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:27<00:00,  6.16feat/s]

XofN_groups: [['f_374', 'f_768', 'f_31', 'f_194', 'f_771'], ['f_20', 'f_729', 'f_629', 'f_328', 'f_428'], ['f_338', 'f_460', 'f_726', 'f_845', 'f_401'], ['f_308', 'f_616', 'f_25', 'f_789', 'f_785'], ['f_346', 'f_831', 'f_778', 'f_749', 'f_510'], ['f_643', 'f_866', 'f_622', 'f_27', 'f_214'], ['f_335', 'f_511', 'f_752', 'f_47', 'f_436'], ['f_287', 'f_195', 'f_635', 'f_118', 'f_413'], ['f_2', 'f_788', 'f_529', 'f_26', 'f_587'], ['f_697', 'f_725', 'f_35', 'f_292', 'f_834'], ['f_406', 'f_836', 'f_791', 'f_799', 'f_466'], ['f_366', 'f_715', 'f_297', 'f_773', 'f_151'], ['f_143', 'f_526', 'f_327', 'f_767', 'f_46'], ['f_23', 'f_631', 'f_167', 'f_736', 'f_330'], ['f_566', 'f_427', 'f_670', 'f_676', 'f_361'], ['f_299', 'f_861', 'f_202', 'f_757', 'f_583'], ['f_617', 'f_820', 'f_792', 'f_675', 'f_455'], ['f_15', 'f_417', 'f_719', 'f_827', 'f_497'], ['f_185', 'f_262', 'f_298', 'f_131', 'f_554'], ['f_393', 'f_840', 'f_764', 'f_229', 'f_509'], ['f_528', 'f_43', 'f_815', 'f_839', 'f_388'], ['f_192', 'f_350', 'f_508', 'f_407', 'f_448'], ['f_186', 'f_473', 'f_722', 'f_650', 'f_394'], ['f_392', 'f_408', 'f_505', 'f_398', 'f_343'], ['f_391', 'f_782', 'f_551', 'f_518', 'f_830'], ['f_571', 'f_429', 'f_728', 'f_215', 'f_207'], ['f_19', 'f_496', 'f_706', 'f_166', 'f_770'], ['f_638', 'f_242', 'f_474', 'f_477', 'f_740'], ['f_12', 'f_609', 'f_409', 'f_471', 'f_486'], ['f_181', 'f_132', 'f_164', 'f_763', 'f_363'], ['f_656', 'f_647', 'f_347', 'f_822', 'f_116'], ['f_213', 'f_336', 'f_559', 'f_621', 'f_687'], ['f_405', 'f_568', 'f_813', 'f_159', 'f_129'], ['f_339', 'f_419', 'f_750', 'f_513', 'f_522'], ['f_672', 'f_30', 'f_488', 'f_759', 'f_812'], ['f_146', 'f_738', 'f_860', 'f_721', 'f_314'], ['f_257', 'f_230', 'f_411', 'f_588', 'f_475'], ['f_3', 'f_423', 'f_801', 'f_833', 'f_494'], ['f_380', 'f_644', 'f_456', 'f_742', 'f_717'], ['f_334', 'f_625', 'f_422', 'f_22', 'f_480'], ['f_440', 'f_483', 'f_784', 'f_425', 'f_200'], ['f_439', 'f_115', 'f_653', 'f_461', 'f_465'], ['f_365', 'f_558', 'f_780', 'f_575', 'f_160'], ['f_345', 'f_454', 'f_144', 'f_803', 'f_467'], ['f_340', 'f_543', 'f_367', 'f_216', 'f_24'], ['f_614', 'f_533', 'f_517', 'f_694', 'f_826'], ['f_682', 'f_489', 'f_249', 'f_515', 'f_514'], ['f_341', 'f_359', 'f_38', 'f_305', 'f_805'], ['f_452', 'f_630', 'f_300', 'f_500', 'f_737'], ['f_516', 'f_610', 'f_187', 'f_301', 'f_716'], ['f_713', 'f_250', 'f_421', 'f_527', 'f_364'], ['f_611', 'f_711', 'f_457', 'f_395', 'f_734'], ['f_180', 'f_157', 'f_414', 'f_605', 'f_397'], ['f_659', 'f_458', 'f_206', 'f_260', 'f_227'], ['f_535', 'f_652', 'f_34', 'f_612', 'f_503'], ['f_712', 'f_378', 'f_658', 'f_563', 'f_707'], ['f_699', 'f_485', 'f_532', 'f_661', 'f_779'], ['f_540', 'f_705', 'f_400', 'f_598', 'f_459'], ['f_37', 'f_399', 'f_701', 'f_624', 'f_531'], ['f_646', 'f_337', 'f_601', 'f_544', 'f_383'], ['f_776', 'f_615', 'f_17', 'f_362', 'f_761'], ['f_639', 'f_412', 'f_758', 'f_294', 'f_824'], ['f_451', 'f_700', 'f_501', 'f_152', 'f_800'], ['f_581', 'f_438', 'f_591', 'f_735', 'f_586'], ['f_16', 'f_819', 'f_342', 'f_349', 'f_188'], ['f_667', 'f_243', 'f_550', 'f_251', 'f_673'], ['f_553', 'f_385', 'f_663', 'f_368', 'f_547'], ['f_248', 'f_153', 'f_620', 'f_685', 'f_507'], ['f_569', 'f_756', 'f_462', 'f_577', 'f_293'], ['f_150', 'f_703', 'f_372', 'f_537', 'f_755'], ['f_645', 'f_432', 'f_499', 'f_590', 'f_632'], ['f_692', 'f_572', 'f_193', 'f_353', 'f_681'], ['f_696', 'f_504', 'f_686', 'f_33', 'f_690'], ['f_244', 'f_693', 'f_536', 'f_662', 'f_435'], ['f_420', 'f_386', 'f_714', 'f_623', 'f_389'], ['f_592', 'f_13', 'f_626', 'f_484', 'f_818'], ['f_671', 'f_596', 'f_199', 'f_567', 'f_695'], ['f_241', 'f_642', 'f_379', 'f_589', 'f_602'], ['f_579', 'f_519', 'f_798', 'f_445', 'f_21'], ['f_641', 'f_674', 'f_797', 'f_580', 'f_261'], ['f_691', 'f_373', 'f_597', 'f_777', 'f_821'], ['f_145', 'f_565', 'f_493', 'f_702', 'f_491'], ['f_593', 'f_476', 'f_704', 'f_447', 'f_576'], ['f_684', 'f_487', 'f_604', 'f_258', 'f_377'], ['f_464', 'f_542', 'f_636', 'f_698', 'f_357'], ['f_637', 'f_450', 'f_600', 'f_666', 'f_521'], ['f_613', 'f_594', 'f_560', 'f_530', 'f_382'], ['f_683', 'f_654', 'f_651', 'f_259', 'f_443'], ['f_680', 'f_375', 'f_431', 'f_606', 'f_633'], ['f_333', 'f_472', 'f_541', 'f_502', 'f_689'], ['f_607', 'f_381', 'f_506', 'f_18', 'f_555'], ['f_390', 'f_498', 'f_539', 'f_665', 'f_655'], ['f_619', 'f_482', 'f_9', 'f_546', 'f_574'], ['f_573', 'f_403', 'f_283', 'f_628', 'f_548'], ['f_11', 'f_523', 'f_437', 'f_356', 'f_396'], ['f_549', 'f_352', 'f_387', 'f_688', 'f_453'], ['f_599', 'f_358', 'f_286', 'f_657', 'f_418'], ['f_709', 'f_538', 'f_585', 'f_0', 'f_256'], ['f_564', 'f_442', 'f_1', 'f_495', 'f_710'], ['f_449', 'f_708', 'f_14', 'f_545', 'f_179'], ['f_376', 'f_679', 'f_285', 'f_430', 'f_371'], ['f_178', 'f_618', 'f_351', 'f_434', 'f_284'], ['f_664', 'f_344', 'f_370', 'f_10', 'f_578'], ['f_446', 'f_603', 'f_332', 'f_255', 'f_582'], ['f_520', 'f_416', 'f_640', 'f_355', 'f_441'], ['f_595', 'f_490', 'f_384', 'f_524', 'f_677'], ['f_570', 'f_678', 'f_584', 'f_556', 'f_552'], ['f_608', 'f_660', 'f_470', 'f_668', 'f_634']]
XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5159545, HammingLoss: 0.17803, SubsetAccuracy: 0.43939,
pruning: False, include_original_features: with_org, averageAUROC: 0.5547464, HammingLoss: 0.26389, SubsetAccuracy: 0.23485,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.18182, SubsetAccuracy: 0.42424,
pruning: False, include_original_features: no_org, averageAUROC: 0.5889551, HammingLoss: 0.28409, SubsetAccuracy: 0.21212,

Fold 3/10 (fingerprint_diverse 8/9)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:27<00:00,  6.15feat/s]

XofN_groups: [['f_20', 'f_729', 'f_629', 'f_194', 'f_510'], ['f_374', 'f_726', 'f_771', 'f_202', 'f_25'], ['f_308', 'f_616', 'f_768', 'f_785', 'f_27'], ['f_23', 'f_428', 'f_631', 'f_413', 'f_118'], ['f_335', 'f_813', 'f_31', 'f_752', 'f_511'], ['f_287', 'f_195', 'f_292', 'f_166', 'f_47'], ['f_346', 'f_831', 'f_460', 'f_635', 'f_429'], ['f_643', 'f_866', 'f_26', 'f_845', 'f_436'], ['f_338', 'f_773', 'f_151', 'f_778', 'f_328'], ['f_566', 'f_836', 'f_839', 'f_477', 'f_330'], ['f_406', 'f_789', 'f_791', 'f_722', 'f_799'], ['f_185', 'f_529', 'f_587', 'f_131', 'f_407'], ['f_143', 'f_526', 'f_297', 'f_830', 'f_350'], ['f_528', 'f_43', 'f_792', 'f_497', 'f_736'], ['f_186', 'f_388', 'f_474', 'f_214', 'f_583'], ['f_391', 'f_725', 'f_719', 'f_505', 'f_448'], ['f_12', 'f_834', 'f_788', 'f_670', 'f_455'], ['f_2', 'f_466', 'f_509', 'f_298', 'f_622'], ['f_366', 'f_427', 'f_568', 'f_675', 'f_767'], ['f_672', 'f_327', 'f_815', 'f_164', 'f_417'], ['f_697', 'f_35', 'f_749', 'f_715', 'f_554'], ['f_339', 'f_676', 'f_750', 'f_454', 'f_46'], ['f_299', 'f_861', 'f_229', 'f_764', 'f_408'], ['f_392', 'f_840', 'f_398', 'f_471', 'f_262'], ['f_393', 'f_242', 'f_757', 'f_461', 'f_782'], ['f_341', 'f_820', 'f_609', 'f_167', 'f_706'], ['f_192', 'f_508', 'f_409', 'f_728', 'f_522'], ['f_181', 'f_132', 'f_401', 'f_207', 'f_343'], ['f_659', 'f_361', 'f_419', 'f_653', 'f_116'], ['f_617', 'f_644', 'f_833', 'f_513', 'f_551'], ['f_19', 'f_496', 'f_827', 'f_770', 'f_115'], ['f_656', 'f_647', 'f_763', 'f_347', 'f_822'], ['f_646', 'f_812', 'f_394', 'f_759', 'f_860'], ['f_712', 'f_533', 'f_518', 'f_543', 'f_650'], ['f_380', 'f_483', 'f_486', 'f_742', 'f_425'], ['f_180', 'f_22', 'f_216', 'f_144', 'f_423'], ['f_696', 'f_473', 'f_30', 'f_826', 'f_422'], ['f_248', 'f_488', 'f_314', 'f_558', 'f_717'], ['f_451', 'f_230', 'f_411', 'f_625', 'f_780'], ['f_405', 'f_588', 'f_159', 'f_336', 'f_465'], ['f_667', 'f_456', 'f_467', 'f_215', 'f_805'], ['f_614', 'f_475', 'f_738', 'f_160', 'f_514'], ['f_571', 'f_395', 'f_721', 'f_801', 'f_494'], ['f_540', 'f_740', 'f_363', 'f_129', 'f_157'], ['f_340', 'f_575', 'f_517', 'f_480', 'f_711'], ['f_639', 'f_500', 'f_515', 'f_200', 'f_652'], ['f_516', 'f_367', 'f_489', 'f_187', 'f_397'], ['f_146', 'f_38', 'f_559', 'f_24', 'f_213'], ['f_535', 'f_784', 'f_305', 'f_359', 'f_687'], ['f_3', 'f_301', 'f_601', 'f_503', 'f_803'], ['f_257', 'f_227', 'f_694', 'f_364', 'f_458'], ['f_15', 'f_605', 'f_421', 'f_713', 'f_630'], ['f_241', 'f_34', 'f_362', 'f_761', 'f_716'], ['f_615', 'f_249', 'f_457', 'f_17', 'f_707'], ['f_440', 'f_621', 'f_610', 'f_414', 'f_779'], ['f_439', 'f_337', 'f_544', 'f_532', 'f_260'], ['f_365', 'f_206', 'f_459', 'f_300', 'f_334'], ['f_638', 'f_531', 'f_776', 'f_378', 'f_661'], ['f_569', 'f_705', 'f_383', 'f_612', 'f_824'], ['f_452', 'f_250', 'f_563', 'f_624', 'f_527'], ['f_645', 'f_700', 'f_658', 'f_400', 'f_501'], ['f_579', 'f_438', 'f_590', 'f_598', 'f_737'], ['f_611', 'f_701', 'f_385', 'f_673', 'f_591'], ['f_692', 'f_251', 'f_152', 'f_294', 'f_663'], ['f_818', 'f_399', 'f_550', 'f_188', 'f_586'], ['f_597', 'f_485', 'f_537', 'f_735', 'f_342'], ['f_704', 'f_572', 'f_756', 'f_412', 'f_37'], ['f_432', 'f_499', 'f_734', 'f_507', 'f_800'], ['f_682', 'f_462', 'f_349', 'f_755', 'f_547'], ['f_671', 'f_389', 'f_703', 'f_368', 'f_690'], ['f_536', 'f_819', 'f_504', 'f_577', 'f_662'], ['f_145', 'f_798', 'f_623', 'f_21', 'f_353'], ['f_33', 'f_699', 'f_685', 'f_386', 'f_632'], ['f_683', 'f_686', 'f_620', 'f_243', 'f_293'], ['f_613', 'f_693', 'f_153', 'f_199', 'f_493'], ['f_345', 'f_681', 'f_758', 'f_484', 'f_193'], ['f_602', 'f_797', 'f_596', 'f_567', 'f_821'], ['f_684', 'f_379', 'f_589', 'f_13', 'f_445'], ['f_553', 'f_714', 'f_372', 'f_150', 'f_702'], ['f_573', 'f_435', 'f_642', 'f_244', 'f_691'], ['f_443', 'f_261', 'f_565', 'f_674', 'f_581'], ['f_593', 'f_777', 'f_695', 'f_576', 'f_476'], ['f_580', 'f_626', 'f_636', 'f_698', 'f_377'], ['f_680', 'f_519', 'f_600', 'f_604', 'f_258'], ['f_464', 'f_542', 'f_487', 'f_420', 'f_491'], ['f_594', 'f_373', 'f_9', 'f_16', 'f_382'], ['f_11', 'f_447', 'f_666', 'f_450', 'f_651'], ['f_637', 'f_560', 'f_530', 'f_606', 'f_546'], ['f_259', 'f_689', 'f_654', 'f_541', 'f_521'], ['f_390', 'f_357', 'f_381', 'f_375', 'f_641'], ['f_592', 'f_498', 'f_431', 'f_502', 'f_655'], ['f_333', 'f_506', 'f_574', 'f_665', 'f_555'], ['f_628', 'f_619', 'f_539', 'f_18', 'f_523'], ['f_607', 'f_472', 'f_548', 'f_286', 'f_538'], ['f_709', 'f_482', 'f_633', 'f_352', 'f_453'], ['f_449', 'f_688', 'f_403', 'f_283', 'f_387'], ['f_437', 'f_710', 'f_396', 'f_0', 'f_442'], ['f_376', 'f_708', 'f_358', 'f_344', 'f_418'], ['f_549', 'f_1', 'f_256', 'f_356', 'f_657'], ['f_664', 'f_585', 'f_284', 'f_495', 'f_430'], ['f_371', 'f_545', 'f_10', 'f_14', 'f_599'], ['f_564', 'f_285', 'f_679', 'f_332', 'f_618'], ['f_178', 'f_351', 'f_603', 'f_179', 'f_446'], ['f_370', 'f_582', 'f_416', 'f_578', 'f_434'], ['f_520', 'f_441', 'f_255', 'f_640', 'f_677'], ['f_556', 'f_355', 'f_584', 'f_524', 'f_384'], ['f_660', 'f_570', 'f_490', 'f_552', 'f_595'], ['f_470', 'f_678', 'f_608', 'f_668', 'f_634']]
XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5248989, HammingLoss: 0.20833, SubsetAccuracy: 0.37879,
pruning: False, include_original_features: with_org, averageAUROC: 0.5824672, HammingLoss: 0.29167, SubsetAccuracy: 0.18182,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.21465, SubsetAccuracy: 0.35606,
pruning: False, include_original_features: no_org, averageAUROC: 0.5640459, HammingLoss: 0.27778, SubsetAccuracy: 0.18182,

Fold 4/10 (fingerprint_diverse 8/9)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:27<00:00,  6.15feat/s]

XofN_groups: [['f_374', 'f_768', 'f_194', 'f_31', 'f_834'], ['f_335', 'f_511', 'f_752', 'f_789', 'f_719'], ['f_20', 'f_729', 'f_629', 'f_328', 'f_587'], ['f_338', 'f_726', 'f_460', 'f_845', 'f_401'], ['f_391', 'f_866', 'f_788', 'f_635', 'f_782'], ['f_308', 'f_616', 'f_831', 'f_791', 'f_25'], ['f_186', 'f_118', 'f_27', 'f_436', 'f_836'], ['f_643', 'f_151', 'f_622', 'f_26', 'f_675'], ['f_299', 'f_861', 'f_202', 'f_583', 'f_413'], ['f_12', 'f_529', 'f_510', 'f_670', 'f_725'], ['f_566', 'f_526', 'f_214', 'f_833', 'f_778'], ['f_2', 'f_773', 'f_455', 'f_497', 'f_297'], ['f_19', 'f_428', 'f_327', 'f_771', 'f_830'], ['f_697', 'f_749', 'f_35', 'f_767', 'f_292'], ['f_659', 'f_427', 'f_770', 'f_722', 'f_394'], ['f_143', 'f_47', 'f_330', 'f_715', 'f_706'], ['f_146', 'f_554', 'f_350', 'f_417', 'f_764'], ['f_185', 'f_448', 'f_46', 'f_262', 'f_509'], ['f_346', 'f_799', 'f_429', 'f_728', 'f_298'], ['f_617', 'f_820', 'f_792', 'f_409', 'f_407'], ['f_366', 'f_466', 'f_736', 'f_215', 'f_166'], ['f_339', 'f_568', 'f_750', 'f_131', 'f_167'], ['f_656', 'f_840', 'f_505', 'f_408', 'f_518'], ['f_180', 'f_132', 'f_164', 'f_361', 'f_785'], ['f_406', 'f_815', 'f_43', 'f_483', 'f_388'], ['f_23', 'f_195', 'f_129', 'f_398', 'f_757'], ['f_287', 'f_631', 'f_687', 'f_609', 'f_559'], ['f_181', 'f_216', 'f_343', 'f_207', 'f_508'], ['f_528', 'f_229', 'f_477', 'f_827', 'f_650'], ['f_712', 'f_533', 'f_763', 'f_551', 'f_486'], ['f_392', 'f_522', 'f_839', 'f_676', 'f_513'], ['f_393', 'f_242', 'f_471', 'f_496', 'f_625'], ['f_192', 'f_474', 'f_422', 'f_30', 'f_558'], ['f_571', 'f_644', 'f_742', 'f_411', 'f_116'], ['f_682', 'f_813', 'f_454', 'f_860', 'f_738'], ['f_380', 'f_419', 'f_494', 'f_740', 'f_588'], ['f_15', 'f_230', 'f_653', 'f_461', 'f_822'], ['f_257', 'f_812', 'f_144', 'f_647', 'f_759'], ['f_452', 'f_721', 'f_425', 'f_801', 'f_423'], ['f_672', 'f_159', 'f_38', 'f_473', 'f_213'], ['f_696', 'f_475', 'f_314', 'f_826', 'f_717'], ['f_341', 'f_467', 'f_456', 'f_488', 'f_514'], ['f_3', 'f_364', 'f_780', 'f_489', 'f_543'], ['f_540', 'f_347', 'f_115', 'f_160', 'f_465'], ['f_440', 'f_621', 'f_336', 'f_363', 'f_227'], ['f_439', 'f_249', 'f_517', 'f_805', 'f_480'], ['f_645', 'f_803', 'f_359', 'f_305', 'f_784'], ['f_685', 'f_605', 'f_414', 'f_301', 'f_200'], ['f_405', 'f_34', 'f_515', 'f_575', 'f_707'], ['f_345', 'f_367', 'f_652', 'f_421', 'f_711'], ['f_713', 'f_250', 'f_395', 'f_527', 'f_591'], ['f_365', 'f_610', 'f_716', 'f_187', 'f_157'], ['f_244', 'f_24', 'f_22', 'f_342', 'f_658'], ['f_516', 'f_661', 'f_378', 'f_500', 'f_694'], ['f_593', 'f_705', 'f_457', 'f_612', 'f_734'], ['f_614', 'f_399', 'f_532', 'f_397', 'f_761'], ['f_646', 'f_337', 'f_601', 'f_458', 'f_544'], ['f_638', 'f_334', 'f_300', 'f_531', 'f_400'], ['f_684', 'f_260', 'f_630', 'f_383', 'f_206'], ['f_340', 'f_563', 'f_17', 'f_737', 'f_459'], ['f_699', 'f_485', 'f_503', 'f_349', 'f_800'], ['f_611', 'f_700', 'f_779', 'f_598', 'f_624'], ['f_667', 'f_438', 'f_537', 'f_586', 'f_501'], ['f_248', 'f_152', 'f_362', 'f_824', 'f_368'], ['f_451', 'f_701', 'f_386', 'f_550', 'f_673'], ['f_16', 'f_819', 'f_507', 'f_294', 'f_188'], ['f_776', 'f_615', 'f_353', 'f_758', 'f_663'], ['f_535', 'f_251', 'f_153', 'f_37', 'f_756'], ['f_639', 'f_412', 'f_821', 'f_499', 'f_632'], ['f_613', 'f_462', 'f_547', 'f_735', 'f_385'], ['f_592', 'f_686', 'f_504', 'f_620', 'f_797'], ['f_569', 'f_798', 'f_577', 'f_690', 'f_293'], ['f_755', 'f_484', 'f_432', 'f_703', 'f_33'], ['f_553', 'f_13', 'f_572', 'f_565', 'f_590'], ['f_602', 'f_662', 'f_243', 'f_818', 'f_623'], ['f_683', 'f_693', 'f_389', 'f_193', 'f_589'], ['f_692', 'f_379', 'f_681', 'f_199', 'f_435'], ['f_536', 'f_626', 'f_596', 'f_671', 'f_21'], ['f_241', 'f_642', 'f_372', 'f_476', 'f_375'], ['f_597', 'f_519', 'f_777', 'f_581', 'f_445'], ['f_704', 'f_674', 'f_567', 'f_261', 'f_580'], ['f_637', 'f_636', 'f_695', 'f_714', 'f_576'], ['f_698', 'f_560', 'f_493', 'f_150', 'f_702'], ['f_691', 'f_373', 'f_666', 'f_579', 'f_450'], ['f_420', 'f_258', 'f_604', 'f_487', 'f_377'], ['f_443', 'f_491', 'f_594', 'f_654', 'f_542'], ['f_145', 'f_382', 'f_600', 'f_447', 'f_689'], ['f_464', 'f_651', 'f_521', 'f_680', 'f_259'], ['f_607', 'f_606', 'f_357', 'f_18', 'f_530'], ['f_502', 'f_381', 'f_431', 'f_286', 'f_641'], ['f_573', 'f_472', 'f_633', 'f_541', 'f_9'], ['f_628', 'f_498', 'f_539', 'f_352', 'f_523'], ['f_390', 'f_555', 'f_574', 'f_546', 'f_688'], ['f_619', 'f_506', 'f_283', 'f_665', 'f_655'], ['f_11', 'f_482', 'f_548', 'f_437', 'f_453'], ['f_333', 'f_403', 'f_549', 'f_0', 'f_538'], ['f_709', 'f_396', 'f_449', 'f_344', 'f_387'], ['f_599', 'f_358', 'f_657', 'f_1', 'f_418'], ['f_710', 'f_442', 'f_585', 'f_284', 'f_256'], ['f_285', 'f_495', 'f_708', 'f_545', 'f_179'], ['f_14', 'f_376', 'f_430', 'f_679', 'f_356'], ['f_370', 'f_10', 'f_351', 'f_678', 'f_618'], ['f_564', 'f_332', 'f_371', 'f_178', 'f_582'], ['f_664', 'f_416', 'f_255', 'f_434', 'f_578'], ['f_446', 'f_603', 'f_441', 'f_355', 'f_677'], ['f_520', 'f_556', 'f_384', 'f_524', 'f_584'], ['f_570', 'f_640', 'f_552', 'f_490', 'f_660'], ['f_595', 'f_470', 'f_668', 'f_608', 'f_634']]
XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5025671, HammingLoss: 0.15657, SubsetAccuracy: 0.4697,
pruning: False, include_original_features: with_org, averageAUROC: 0.5610068, HammingLoss: 0.25505, SubsetAccuracy: 0.25,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.15657, SubsetAccuracy: 0.47727,
pruning: False, include_original_features: no_org, averageAUROC: 0.5624604, HammingLoss: 0.26389, SubsetAccuracy: 0.25,

Fold 5/10 (fingerprint_diverse 8/9)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:27<00:00,  6.16feat/s]

XofN_groups: [['f_374', 'f_831', 'f_31', 'f_771', 'f_510'], ['f_335', 'f_47', 'f_834', 'f_726', 'f_497'], ['f_20', 'f_629', 'f_792', 'f_194', 'f_328'], ['f_338', 'f_401', 'f_820', 'f_866', 'f_529'], ['f_287', 'f_195', 'f_413', 'f_428', 'f_773'], ['f_2', 'f_768', 'f_27', 'f_635', 'f_587'], ['f_346', 'f_616', 'f_789', 'f_799', 'f_330'], ['f_308', 'f_836', 'f_791', 'f_788', 'f_25'], ['f_656', 'f_151', 'f_845', 'f_526', 'f_118'], ['f_391', 'f_725', 'f_719', 'f_460', 'f_505'], ['f_643', 'f_861', 'f_202', 'f_815', 'f_736'], ['f_186', 'f_511', 'f_292', 'f_436', 'f_749'], ['f_143', 'f_767', 'f_764', 'f_297', 'f_350'], ['f_528', 'f_729', 'f_43', 'f_26', 'f_622'], ['f_617', 'f_757', 'f_455', 'f_722', 'f_214'], ['f_23', 'f_408', 'f_167', 'f_740', 'f_752'], ['f_392', 'f_840', 'f_327', 'f_631', 'f_477'], ['f_566', 'f_427', 'f_554', 'f_676', 'f_361'], ['f_185', 'f_583', 'f_474', 'f_262', 'f_670'], ['f_659', 'f_417', 'f_429', 'f_509', 'f_343'], ['f_146', 'f_706', 'f_675', 'f_830', 'f_46'], ['f_181', 'f_166', 'f_132', 'f_298', 'f_466'], ['f_366', 'f_568', 'f_813', 'f_522', 'f_131'], ['f_697', 'f_35', 'f_533', 'f_812', 'f_785'], ['f_192', 'f_508', 'f_461', 'f_407', 'f_728'], ['f_12', 'f_409', 'f_609', 'f_782', 'f_207'], ['f_672', 'f_159', 'f_473', 'f_38', 'f_778'], ['f_713', 'f_129', 'f_715', 'f_750', 'f_314'], ['f_571', 'f_419', 'f_215', 'f_229', 'f_475'], ['f_439', 'f_448', 'f_230', 'f_833', 'f_759'], ['f_380', 'f_650', 'f_827', 'f_496', 'f_770'], ['f_393', 'f_839', 'f_486', 'f_471', 'f_763'], ['f_682', 'f_242', 'f_483', 'f_738', 'f_489'], ['f_341', 'f_518', 'f_388', 'f_513', 'f_801'], ['f_180', 'f_347', 'f_454', 'f_164', 'f_822'], ['f_299', 'f_860', 'f_653', 'f_644', 'f_717'], ['f_406', 'f_558', 'f_422', 'f_30', 'f_551'], ['f_712', 'f_494', 'f_742', 'f_480', 'f_411'], ['f_339', 'f_588', 'f_465', 'f_456', 'f_467'], ['f_452', 'f_517', 'f_543', 'f_780', 'f_425'], ['f_345', 'f_394', 'f_116', 'f_514', 'f_488'], ['f_667', 'f_647', 'f_621', 'f_216', 'f_559'], ['f_3', 'f_423', 'f_398', 'f_115', 'f_721'], ['f_639', 'f_500', 'f_687', 'f_359', 'f_363'], ['f_614', 'f_336', 'f_34', 'f_364', 'f_625'], ['f_540', 'f_367', 'f_144', 'f_160', 'f_395'], ['f_405', 'f_200', 'f_421', 'f_515', 'f_826'], ['f_257', 'f_227', 'f_575', 'f_305', 'f_260'], ['f_365', 'f_803', 'f_157', 'f_24', 'f_301'], ['f_19', 'f_805', 'f_213', 'f_22', 'f_300'], ['f_15', 'f_605', 'f_17', 'f_457', 'f_784'], ['f_645', 'f_610', 'f_414', 'f_397', 'f_711'], ['f_638', 'f_334', 'f_532', 'f_716', 'f_661'], ['f_451', 'f_700', 'f_601', 'f_658', 'f_249'], ['f_241', 'f_598', 'f_694', 'f_630', 'f_612'], ['f_685', 'f_383', 'f_544', 'f_337', 'f_378'], ['f_440', 'f_652', 'f_458', 'f_755', 'f_485'], ['f_516', 'f_563', 'f_187', 'f_152', 'f_459'], ['f_646', 'f_705', 'f_531', 'f_737', 'f_206'], ['f_37', 'f_527', 'f_701', 'f_624', 'f_586'], ['f_696', 'f_438', 'f_707', 'f_412', 'f_761'], ['f_535', 'f_250', 'f_400', 'f_503', 'f_663'], ['f_691', 'f_362', 'f_776', 'f_399', 'f_188'], ['f_248', 'f_153', 'f_501', 'f_824', 'f_673'], ['f_579', 'f_251', 'f_499', 'f_734', 'f_591'], ['f_340', 'f_537', 'f_547', 'f_735', 'f_507'], ['f_420', 'f_800', 'f_550', 'f_349', 'f_690'], ['f_611', 'f_819', 'f_779', 'f_342', 'f_368'], ['f_602', 'f_756', 'f_294', 'f_386', 'f_681'], ['f_569', 'f_462', 'f_620', 'f_577', 'f_590'], ['f_199', 'f_379', 'f_432', 'f_615', 'f_353'], ['f_593', 'f_818', 'f_632', 'f_293', 'f_703'], ['f_698', 'f_572', 'f_686', 'f_33', 'f_758'], ['f_244', 'f_693', 'f_536', 'f_662', 'f_435'], ['f_145', 'f_798', 'f_623', 'f_21', 'f_372'], ['f_692', 'f_504', 'f_385', 'f_567', 'f_193'], ['f_573', 'f_243', 'f_797', 'f_389', 'f_581'], ['f_16', 'f_699', 'f_597', 'f_445', 'f_821'], ['f_592', 'f_13', 'f_626', 'f_484', 'f_671'], ['f_704', 'f_674', 'f_565', 'f_150', 'f_642'], ['f_684', 'f_596', 'f_589', 'f_580', 'f_261'], ['f_443', 'f_519', 'f_714', 'f_493', 'f_702'], ['f_683', 'f_777', 'f_487', 'f_695', 'f_476'], ['f_637', 'f_636', 'f_576', 'f_553', 'f_604'], ['f_259', 'f_689', 'f_560', 'f_666', 'f_377'], ['f_613', 'f_258', 'f_594', 'f_450', 'f_542'], ['f_464', 'f_382', 'f_491', 'f_654', 'f_680'], ['f_619', 'f_373', 'f_375', 'f_600', 'f_651'], ['f_390', 'f_530', 'f_606', 'f_447', 'f_688'], ['f_502', 'f_381', 'f_521', 'f_286', 'f_357'], ['f_641', 'f_431', 'f_633', 'f_18', 'f_541'], ['f_628', 'f_498', 'f_539', 'f_352', 'f_523'], ['f_14', 'f_506', 'f_574', 'f_555', 'f_710'], ['f_607', 'f_472', 'f_655', 'f_9', 'f_538'], ['f_11', 'f_482', 'f_548', 'f_665', 'f_453'], ['f_549', 'f_403', 'f_709', 'f_283', 'f_546'], ['f_449', 'f_708', 'f_396', 'f_0', 'f_387'], ['f_333', 'f_358', 'f_437', 'f_344', 'f_256'], ['f_418', 'f_179', 'f_657', 'f_284', 'f_442'], ['f_376', 'f_679', 'f_356', 'f_585', 'f_1'], ['f_351', 'f_495', 'f_430', 'f_545', 'f_599'], ['f_370', 'f_10', 'f_285', 'f_618', 'f_582'], ['f_564', 'f_332', 'f_371', 'f_178', 'f_446'], ['f_434', 'f_255', 'f_578', 'f_416', 'f_603'], ['f_664', 'f_441', 'f_552', 'f_490', 'f_355'], ['f_520', 'f_556', 'f_384', 'f_524', 'f_584'], ['f_470', 'f_640', 'f_570', 'f_678', 'f_677'], ['f_608', 'f_660', 'f_668', 'f_595', 'f_634']]
XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5211034, HammingLoss: 0.17045, SubsetAccuracy: 0.47727,
pruning: False, include_original_features: with_org, averageAUROC: 0.5744289, HammingLoss: 0.27904, SubsetAccuracy: 0.16667,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.17803, SubsetAccuracy: 0.45455,
pruning: False, include_original_features: no_org, averageAUROC: 0.5227316, HammingLoss: 0.28914, SubsetAccuracy: 0.18939,

Fold 6/10 (fingerprint_diverse 8/9)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:28<00:00,  6.13feat/s]

XofN_groups: [['f_374', 'f_768', 'f_834', 'f_25', 'f_194'], ['f_20', 'f_792', 'f_629', 'f_510', 'f_676'], ['f_335', 'f_31', 'f_771', 'f_47', 'f_831'], ['f_338', 'f_789', 'f_460', 'f_328', 'f_845'], ['f_308', 'f_616', 'f_785', 'f_726', 'f_214'], ['f_391', 'f_788', 'f_866', 'f_635', 'f_782'], ['f_23', 'f_195', 'f_428', 'f_292', 'f_526'], ['f_656', 'f_151', 'f_27', 'f_836', 'f_118'], ['f_346', 'f_725', 'f_429', 'f_729', 'f_722'], ['f_143', 'f_529', 'f_767', 'f_327', 'f_587'], ['f_528', 'f_861', 'f_773', 'f_466', 'f_554'], ['f_366', 'f_799', 'f_568', 'f_427', 'f_670'], ['f_672', 'f_413', 'f_830', 'f_43', 'f_815'], ['f_186', 'f_511', 'f_436', 'f_202', 'f_583'], ['f_2', 'f_497', 'f_330', 'f_505', 'f_455'], ['f_697', 'f_35', 'f_749', 'f_752', 'f_736'], ['f_146', 'f_706', 'f_297', 'f_715', 'f_350'], ['f_659', 'f_839', 'f_675', 'f_419', 'f_622'], ['f_287', 'f_408', 'f_167', 'f_764', 'f_229'], ['f_406', 'f_791', 'f_778', 'f_26', 'f_409'], ['f_392', 'f_840', 'f_509', 'f_631', 'f_486'], ['f_15', 'f_417', 'f_719', 'f_827', 'f_407'], ['f_643', 'f_461', 'f_820', 'f_551', 'f_166'], ['f_393', 'f_242', 'f_757', 'f_401', 'f_740'], ['f_566', 'f_477', 'f_361', 'f_653', 'f_46'], ['f_571', 'f_728', 'f_215', 'f_508', 'f_298'], ['f_339', 'f_813', 'f_474', 'f_394', 'f_388'], ['f_192', 'f_131', 'f_262', 'f_609', 'f_763'], ['f_185', 'f_448', 'f_473', 'f_518', 'f_207'], ['f_380', 'f_650', 'f_750', 'f_496', 'f_343'], ['f_617', 'f_483', 'f_833', 'f_759', 'f_116'], ['f_341', 'f_533', 'f_522', 'f_812', 'f_822'], ['f_12', 'f_647', 'f_398', 'f_471', 'f_738'], ['f_452', 'f_644', 'f_425', 'f_230', 'f_513'], ['f_451', 'f_860', 'f_717', 'f_625', 'f_164'], ['f_299', 'f_780', 'f_826', 'f_30', 'f_480'], ['f_365', 'f_558', 'f_801', 'f_770', 'f_115'], ['f_712', 'f_475', 'f_494', 'f_411', 'f_588'], ['f_19', 'f_467', 'f_159', 'f_216', 'f_803'], ['f_699', 'f_488', 'f_132', 'f_314', 'f_422'], ['f_180', 'f_347', 'f_454', 'f_144', 'f_160'], ['f_181', 'f_129', 'f_694', 'f_336', 'f_517'], ['f_638', 'f_38', 'f_227', 'f_364', 'f_465'], ['f_685', 'f_363', 'f_605', 'f_456', 'f_213'], ['f_682', 'f_423', 'f_249', 'f_421', 'f_515'], ['f_540', 'f_514', 'f_200', 'f_721', 'f_559'], ['f_405', 'f_17', 'f_543', 'f_500', 'f_24'], ['f_645', 'f_575', 'f_414', 'f_711', 'f_397'], ['f_334', 'f_22', 'f_532', 'f_805', 'f_359'], ['f_614', 'f_34', 'f_742', 'f_713', 'f_503'], ['f_776', 'f_489', 'f_598', 'f_157', 'f_630'], ['f_667', 'f_621', 'f_301', 'f_687', 'f_784'], ['f_439', 'f_367', 'f_457', 'f_337', 'f_716'], ['f_639', 'f_187', 'f_395', 'f_527', 'f_300'], ['f_440', 'f_652', 'f_612', 'f_305', 'f_590'], ['f_569', 'f_705', 'f_458', 'f_206', 'f_737'], ['f_671', 'f_400', 'f_761', 'f_362', 'f_459'], ['f_637', 'f_260', 'f_501', 'f_610', 'f_658'], ['f_646', 'f_700', 'f_601', 'f_591', 'f_734'], ['f_145', 'f_701', 'f_342', 'f_250', 'f_624'], ['f_597', 'f_251', 'f_152', 'f_661', 'f_294'], ['f_611', 'f_824', 'f_531', 'f_707', 'f_462'], ['f_257', 'f_563', 'f_779', 'f_349', 'f_378'], ['f_692', 'f_438', 'f_544', 'f_383', 'f_399'], ['f_579', 'f_485', 'f_756', 'f_188', 'f_550'], ['f_602', 'f_819', 'f_386', 'f_37', 'f_800'], ['f_345', 'f_537', 'f_499', 'f_735', 'f_586'], ['f_244', 'f_693', 'f_412', 'f_673', 'f_663'], ['f_516', 'f_686', 'f_547', 'f_703', 'f_507'], ['f_33', 'f_798', 'f_572', 'f_615', 'f_758'], ['f_691', 'f_353', 'f_818', 'f_504', 'f_620'], ['f_698', 'f_389', 'f_368', 'f_755', 'f_577'], ['f_593', 'f_797', 'f_632', 'f_293', 'f_690'], ['f_702', 'f_432', 'f_372', 'f_193', 'f_243'], ['f_199', 'f_487', 'f_623', 'f_681', 'f_385'], ['f_535', 'f_153', 'f_626', 'f_435', 'f_248'], ['f_696', 'f_484', 'f_21', 'f_589', 'f_821'], ['f_684', 'f_379', 'f_662', 'f_13', 'f_377'], ['f_704', 'f_674', 'f_565', 'f_150', 'f_581'], ['f_613', 'f_642', 'f_261', 'f_567', 'f_493'], ['f_340', 'f_714', 'f_596', 'f_3', 'f_553'], ['f_502', 'f_777', 'f_536', 'f_519', 'f_476'], ['f_464', 'f_695', 'f_604', 'f_636', 'f_241'], ['f_683', 'f_258', 'f_580', 'f_594', 'f_445'], ['f_16', 'f_666', 'f_491', 'f_443', 'f_542'], ['f_641', 'f_560', 'f_576', 'f_420', 'f_373'], ['f_592', 'f_447', 'f_382', 'f_654', 'f_689'], ['f_628', 'f_651', 'f_450', 'f_680', 'f_357'], ['f_390', 'f_530', 'f_606', 'f_375', 'f_521'], ['f_259', 'f_352', 'f_541', 'f_539', 'f_600'], ['f_573', 'f_431', 'f_9', 'f_546', 'f_381'], ['f_619', 'f_506', 'f_633', 'f_18', 'f_498'], ['f_607', 'f_472', 'f_655', 'f_286', 'f_555'], ['f_453', 'f_574', 'f_344', 'f_523', 'f_665'], ['f_708', 'f_482', 'f_548', 'f_437', 'f_418'], ['f_442', 'f_688', 'f_657', 'f_283', 'f_403'], ['f_710', 'f_396', 'f_549', 'f_0', 'f_538'], ['f_709', 'f_387', 'f_585', 'f_284', 'f_256'], ['f_430', 'f_358', 'f_14', 'f_495', 'f_179'], ['f_333', 'f_545', 'f_285', 'f_449', 'f_599'], ['f_11', 'f_376', 'f_356', 'f_351', 'f_434'], ['f_1', 'f_371', 'f_679', 'f_255', 'f_10'], ['f_564', 'f_332', 'f_370', 'f_582', 'f_618'], ['f_664', 'f_178', 'f_446', 'f_355', 'f_578'], ['f_640', 'f_384', 'f_416', 'f_603', 'f_441'], ['f_595', 'f_490', 'f_584', 'f_524', 'f_556'], ['f_570', 'f_660', 'f_677', 'f_678', 'f_552'], ['f_668', 'f_520', 'f_608', 'f_470', 'f_634']]
XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.512575, HammingLoss: 0.15657, SubsetAccuracy: 0.45455,
pruning: False, include_original_features: with_org, averageAUROC: 0.5264449, HammingLoss: 0.27399, SubsetAccuracy: 0.18182,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.15657, SubsetAccuracy: 0.45455,
pruning: False, include_original_features: no_org, averageAUROC: 0.5271856, HammingLoss: 0.27399, SubsetAccuracy: 0.18182,

Fold 7/10 (fingerprint_diverse 8/9)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:27<00:00,  6.16feat/s]

XofN_groups: [['f_374', 'f_836', 'f_31', 'f_25', 'f_194'], ['f_20', 'f_792', 'f_629', 'f_497', 'f_214'], ['f_2', 'f_831', 'f_635', 'f_413', 'f_27'], ['f_643', 'f_866', 'f_622', 'f_789', 'f_815'], ['f_338', 'f_726', 'f_328', 'f_460', 'f_845'], ['f_346', 'f_768', 'f_428', 'f_429', 'f_511'], ['f_617', 'f_616', 'f_830', 'f_722', 'f_401'], ['f_23', 'f_195', 'f_526', 'f_292', 'f_448'], ['f_335', 'f_752', 'f_350', 'f_510', 'f_436'], ['f_391', 'f_725', 'f_719', 'f_529', 'f_151'], ['f_656', 'f_773', 'f_706', 'f_417', 'f_118'], ['f_12', 'f_788', 'f_834', 'f_587', 'f_670'], ['f_287', 'f_408', 'f_207', 'f_47', 'f_771'], ['f_185', 'f_262', 'f_46', 'f_131', 'f_509'], ['f_143', 'f_767', 'f_298', 'f_330', 'f_202'], ['f_659', 'f_427', 'f_778', 'f_297', 'f_26'], ['f_299', 'f_840', 'f_229', 'f_583', 'f_675'], ['f_672', 'f_43', 'f_35', 'f_505', 'f_715'], ['f_406', 'f_791', 'f_785', 'f_820', 'f_409'], ['f_566', 'f_839', 'f_477', 'f_327', 'f_764'], ['f_181', 'f_455', 'f_166', 'f_132', 'f_799'], ['f_393', 'f_861', 'f_757', 'f_676', 'f_728'], ['f_308', 'f_750', 'f_554', 'f_466', 'f_407'], ['f_192', 'f_508', 'f_215', 'f_388', 'f_736'], ['f_528', 'f_729', 'f_242', 'f_471', 'f_461'], ['f_366', 'f_568', 'f_813', 'f_216', 'f_782'], ['f_15', 'f_631', 'f_860', 'f_167', 'f_749'], ['f_646', 'f_763', 'f_551', 'f_230', 'f_496'], ['f_186', 'f_474', 'f_812', 'f_394', 'f_827'], ['f_19', 'f_419', 'f_343', 'f_738', 'f_522'], ['f_571', 'f_483', 'f_833', 'f_116', 'f_759'], ['f_180', 'f_164', 'f_454', 'f_361', 'f_347'], ['f_638', 'f_144', 'f_518', 'f_533', 'f_625'], ['f_685', 'f_363', 'f_129', 'f_653', 'f_609'], ['f_452', 'f_650', 'f_721', 'f_801', 'f_423'], ['f_440', 'f_644', 'f_770', 'f_513', 'f_115'], ['f_639', 'f_558', 'f_473', 'f_717', 'f_159'], ['f_697', 'f_494', 'f_475', 'f_30', 'f_588'], ['f_146', 'f_543', 'f_780', 'f_456', 'f_514'], ['f_345', 'f_740', 'f_822', 'f_647', 'f_559'], ['f_339', 'f_465', 'f_486', 'f_314', 'f_742'], ['f_682', 'f_395', 'f_398', 'f_249', 'f_213'], ['f_614', 'f_488', 'f_425', 'f_467', 'f_826'], ['f_712', 'f_34', 'f_805', 'f_411', 'f_422'], ['f_392', 'f_517', 'f_803', 'f_500', 'f_711'], ['f_380', 'f_336', 'f_621', 'f_301', 'f_200'], ['f_341', 'f_421', 'f_38', 'f_737', 'f_22'], ['f_439', 'f_367', 'f_414', 'f_334', 'f_359'], ['f_3', 'f_364', 'f_480', 'f_378', 'f_575'], ['f_699', 'f_485', 'f_305', 'f_784', 'f_658'], ['f_645', 'f_337', 'f_457', 'f_397', 'f_761'], ['f_405', 'f_160', 'f_489', 'f_713', 'f_187'], ['f_667', 'f_612', 'f_458', 'f_24', 'f_630'], ['f_615', 'f_227', 'f_687', 'f_459', 'f_515'], ['f_451', 'f_700', 'f_260', 'f_532', 'f_716'], ['f_248', 'f_152', 'f_610', 'f_503', 'f_652'], ['f_365', 'f_157', 'f_605', 'f_624', 'f_598'], ['f_611', 'f_705', 'f_300', 'f_531', 'f_206'], ['f_540', 'f_661', 'f_694', 'f_250', 'f_362'], ['f_569', 'f_824', 'f_383', 'f_776', 'f_400'], ['f_696', 'f_601', 'f_563', 'f_586', 'f_707'], ['f_145', 'f_544', 'f_537', 'f_501', 'f_734'], ['f_579', 'f_438', 'f_17', 'f_800', 'f_591'], ['f_597', 'f_389', 'f_701', 'f_342', 'f_349'], ['f_535', 'f_251', 'f_527', 'f_550', 'f_663'], ['f_257', 'f_462', 'f_673', 'f_399', 'f_735'], ['f_516', 'f_188', 'f_779', 'f_499', 'f_756'], ['f_199', 'f_294', 'f_368', 'f_243', 'f_690'], ['f_613', 'f_686', 'f_412', 'f_385', 'f_37'], ['f_340', 'f_819', 'f_547', 'f_507', 'f_758'], ['f_16', 'f_798', 'f_353', 'f_623', 'f_703'], ['f_691', 'f_293', 'f_818', 'f_572', 'f_632'], ['f_684', 'f_504', 'f_755', 'f_620', 'f_33'], ['f_443', 'f_386', 'f_590', 'f_662', 'f_435'], ['f_683', 'f_681', 'f_484', 'f_193', 'f_432'], ['f_573', 'f_372', 'f_693', 'f_153', 'f_821'], ['f_593', 'f_797', 'f_476', 'f_21', 'f_445'], ['f_692', 'f_379', 'f_589', 'f_13', 'f_577'], ['f_420', 'f_261', 'f_567', 'f_674', 'f_695'], ['f_244', 'f_581', 'f_375', 'f_626', 'f_671'], ['f_602', 'f_565', 'f_596', 'f_642', 'f_241'], ['f_553', 'f_714', 'f_519', 'f_150', 'f_702'], ['f_464', 'f_777', 'f_636', 'f_580', 'f_666'], ['f_619', 'f_491', 'f_493', 'f_536', 'f_377'], ['f_592', 'f_258', 'f_604', 'f_487', 'f_704'], ['f_680', 'f_373', 'f_594', 'f_560', 'f_576'], ['f_259', 'f_698', 'f_654', 'f_542', 'f_600'], ['f_390', 'f_447', 'f_382', 'f_450', 'f_689'], ['f_637', 'f_521', 'f_651', 'f_502', 'f_530'], ['f_641', 'f_357', 'f_633', 'f_18', 'f_381'], ['f_546', 'f_606', 'f_431', 'f_286', 'f_555'], ['f_628', 'f_541', 'f_539', 'f_352', 'f_523'], ['f_688', 'f_482', 'f_498', 'f_665', 'f_655'], ['f_607', 'f_472', 'f_574', 'f_9', 'f_453'], ['f_333', 'f_506', 'f_548', 'f_437', 'f_418'], ['f_708', 'f_403', 'f_549', 'f_283', 'f_538'], ['f_442', 'f_179', 'f_585', 'f_344', 'f_396'], ['f_11', 'f_387', 'f_657', 'f_356', 'f_256'], ['f_599', 'f_358', 'f_14', 'f_495', 'f_709'], ['f_1', 'f_545', 'f_430', 'f_449', 'f_710'], ['f_370', 'f_376', 'f_0', 'f_679', 'f_285'], ['f_564', 'f_351', 'f_284', 'f_371', 'f_582'], ['f_434', 'f_10', 'f_618', 'f_255', 'f_332'], ['f_664', 'f_178', 'f_446', 'f_355', 'f_603'], ['f_595', 'f_416', 'f_578', 'f_441', 'f_678'], ['f_640', 'f_384', 'f_524', 'f_677', 'f_556'], ['f_570', 'f_660', 'f_584', 'f_490', 'f_552'], ['f_668', 'f_520', 'f_608', 'f_470', 'f_634']]
XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5132904, HammingLoss: 0.17677, SubsetAccuracy: 0.45455,
pruning: False, include_original_features: with_org, averageAUROC: 0.6222929, HammingLoss: 0.25126, SubsetAccuracy: 0.27273,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.17929, SubsetAccuracy: 0.43939,
pruning: False, include_original_features: no_org, averageAUROC: 0.5947144, HammingLoss: 0.25379, SubsetAccuracy: 0.32576,

Fold 8/10 (fingerprint_diverse 8/9)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:27<00:00,  6.15feat/s]

XofN_groups: [['f_374', 'f_831', 'f_31', 'f_529', 'f_771'], ['f_23', 'f_195', 'f_292', 'f_635', 'f_428'], ['f_20', 'f_792', 'f_629', 'f_194', 'f_328'], ['f_2', 'f_768', 'f_836', 'f_27', 'f_413'], ['f_287', 'f_631', 'f_47', 'f_773', 'f_118'], ['f_308', 'f_616', 'f_789', 'f_409', 'f_25'], ['f_335', 'f_511', 'f_815', 'f_726', 'f_736'], ['f_339', 'f_834', 'f_526', 'f_330', 'f_799'], ['f_12', 'f_725', 'f_510', 'f_670', 'f_497'], ['f_338', 'f_820', 'f_866', 'f_401', 'f_436'], ['f_186', 'f_845', 'f_131', 'f_26', 'f_214'], ['f_185', 'f_151', 'f_587', 'f_262', 'f_583'], ['f_391', 'f_788', 'f_719', 'f_505', 'f_460'], ['f_346', 'f_749', 'f_417', 'f_830', 'f_722'], ['f_406', 'f_791', 'f_778', 'f_202', 'f_764'], ['f_392', 'f_861', 'f_675', 'f_229', 'f_752'], ['f_697', 'f_35', 'f_767', 'f_812', 'f_477'], ['f_643', 'f_622', 'f_427', 'f_827', 'f_509'], ['f_192', 'f_46', 'f_132', 'f_455', 'f_554'], ['f_656', 'f_706', 'f_297', 'f_448', 'f_350'], ['f_566', 'f_839', 'f_715', 'f_327', 'f_653'], ['f_143', 'f_298', 'f_43', 'f_729', 'f_407'], ['f_528', 'f_840', 'f_466', 'f_757', 'f_770'], ['f_617', 'f_813', 'f_676', 'f_454', 'f_166'], ['f_257', 'f_361', 'f_408', 'f_785', 'f_116'], ['f_405', 'f_429', 'f_167', 'f_750', 'f_129'], ['f_181', 'f_164', 'f_215', 'f_343', 'f_508'], ['f_659', 'f_568', 'f_833', 'f_483', 'f_242'], ['f_638', 'f_728', 'f_860', 'f_419', 'f_513'], ['f_180', 'f_207', 'f_423', 'f_782', 'f_486'], ['f_393', 'f_230', 'f_461', 'f_551', 'f_625'], ['f_571', 'f_644', 'f_471', 'f_742', 'f_30'], ['f_15', 'f_763', 'f_347', 'f_609', 'f_650'], ['f_696', 'f_474', 'f_388', 'f_518', 'f_588'], ['f_380', 'f_496', 'f_558', 'f_425', 'f_738'], ['f_366', 'f_394', 'f_759', 'f_647', 'f_533'], ['f_341', 'f_522', 'f_473', 'f_822', 'f_411'], ['f_146', 'f_543', 'f_717', 'f_314', 'f_144'], ['f_540', 'f_740', 'f_159', 'f_115', 'f_467'], ['f_667', 'f_494', 'f_456', 'f_805', 'f_780'], ['f_299', 'f_826', 'f_517', 'f_216', 'f_480'], ['f_451', 'f_803', 'f_475', 'f_38', 'f_160'], ['f_682', 'f_801', 'f_398', 'f_489', 'f_249'], ['f_672', 'f_34', 'f_336', 'f_621', 'f_213'], ['f_713', 'f_227', 'f_488', 'f_364', 'f_305'], ['f_19', 'f_422', 'f_559', 'f_514', 'f_200'], ['f_685', 'f_363', 'f_605', 'f_421', 'f_515'], ['f_452', 'f_721', 'f_465', 'f_367', 'f_359'], ['f_614', 'f_395', 'f_687', 'f_187', 'f_716'], ['f_645', 'f_575', 'f_414', 'f_711', 'f_397'], ['f_698', 'f_378', 'f_500', 'f_22', 'f_300'], ['f_593', 'f_705', 'f_457', 'f_301', 'f_206'], ['f_516', 'f_610', 'f_652', 'f_17', 'f_24'], ['f_244', 'f_591', 'f_694', 'f_658', 'f_784'], ['f_241', 'f_503', 'f_157', 'f_761', 'f_458'], ['f_340', 'f_334', 'f_260', 'f_532', 'f_563'], ['f_646', 'f_337', 'f_601', 'f_459', 'f_734'], ['f_440', 'f_630', 'f_612', 'f_598', 'f_527'], ['f_37', 'f_399', 'f_701', 'f_624', 'f_737'], ['f_615', 'f_590', 'f_383', 'f_707', 'f_438'], ['f_776', 'f_400', 'f_501', 'f_531', 'f_544'], ['f_602', 'f_700', 'f_362', 'f_779', 'f_152'], ['f_3', 'f_673', 'f_250', 'f_342', 'f_349'], ['f_639', 'f_412', 'f_758', 'f_294', 'f_824'], ['f_243', 'f_693', 'f_251', 'f_550', 'f_661'], ['f_199', 'f_499', 'f_432', 'f_586', 'f_663'], ['f_699', 'f_485', 'f_507', 'f_800', 'f_188'], ['f_365', 'f_537', 'f_547', 'f_735', 'f_368'], ['f_439', 'f_681', 'f_385', 'f_632', 'f_572'], ['f_33', 'f_462', 'f_389', 'f_756', 'f_577'], ['f_611', 'f_819', 'f_386', 'f_686', 'f_353'], ['f_345', 'f_153', 'f_798', 'f_623', 'f_703'], ['f_712', 'f_504', 'f_620', 'f_293', 'f_690'], ['f_535', 'f_261', 'f_662', 'f_755', 'f_435'], ['f_597', 'f_596', 'f_818', 'f_21', 'f_821'], ['f_145', 'f_248', 'f_567', 'f_372', 'f_493'], ['f_692', 'f_484', 'f_193', 'f_565', 'f_445'], ['f_579', 'f_519', 'f_589', 'f_13', 'f_797'], ['f_536', 'f_626', 'f_258', 'f_581', 'f_671'], ['f_420', 'f_379', 'f_714', 'f_642', 'f_377'], ['f_704', 'f_674', 'f_476', 'f_150', 'f_702'], ['f_684', 'f_491', 'f_604', 'f_580', 'f_691'], ['f_637', 'f_373', 'f_695', 'f_777', 'f_375'], ['f_613', 'f_666', 'f_636', 'f_553', 'f_576'], ['f_569', 'f_594', 'f_530', 'f_443', 'f_487'], ['f_683', 'f_447', 'f_542', 'f_450', 'f_689'], ['f_619', 'f_521', 'f_16', 'f_600', 'f_382'], ['f_259', 'f_352', 'f_560', 'f_651', 'f_665'], ['f_680', 'f_654', 'f_357', 'f_606', 'f_633'], ['f_502', 'f_381', 'f_431', 'f_18', 'f_641'], ['f_573', 'f_506', 'f_9', 'f_555', 'f_541'], ['f_592', 'f_498', 'f_472', 'f_546', 'f_655'], ['f_628', 'f_574', 'f_539', 'f_286', 'f_523'], ['f_418', 'f_548', 'f_1', 'f_482', 'f_549'], ['f_464', 'f_403', 'f_688', 'f_283', 'f_538'], ['f_333', 'f_396', 'f_437', 'f_344', 'f_387'], ['f_607', 'f_358', 'f_0', 'f_657', 'f_709'], ['f_390', 'f_256', 'f_710', 'f_585', 'f_453'], ['f_11', 'f_442', 'f_356', 'f_495', 'f_179'], ['f_376', 'f_708', 'f_14', 'f_545', 'f_599'], ['f_449', 'f_679', 'f_430', 'f_285', 'f_371'], ['f_178', 'f_618', 'f_351', 'f_434', 'f_284'], ['f_370', 'f_10', 'f_640', 'f_332', 'f_603'], ['f_664', 'f_582', 'f_255', 'f_446', 'f_578'], ['f_564', 'f_416', 'f_677', 'f_441', 'f_384'], ['f_668', 'f_490', 'f_355', 'f_524', 'f_584'], ['f_595', 'f_556', 'f_552', 'f_678', 'f_570'], ['f_470', 'f_660', 'f_608', 'f_520', 'f_634']]
XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5173483, HammingLoss: 0.19823, SubsetAccuracy: 0.39394,
pruning: False, include_original_features: with_org, averageAUROC: 0.5604702, HammingLoss: 0.26768, SubsetAccuracy: 0.23485,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.20328, SubsetAccuracy: 0.37879,
pruning: False, include_original_features: no_org, averageAUROC: 0.5661888, HammingLoss: 0.28662, SubsetAccuracy: 0.2197,

Fold 9/10 (fingerprint_diverse 8/9)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:27<00:00,  6.16feat/s]

XofN_groups: [['f_374', 'f_831', 'f_834', 'f_27', 'f_202'], ['f_20', 'f_792', 'f_629', 'f_194', 'f_635'], ['f_2', 'f_768', 'f_413', 'f_771', 'f_510'], ['f_346', 'f_726', 'f_428', 'f_297', 'f_616'], ['f_23', 'f_687', 'f_631', 'f_31', 'f_836'], ['f_338', 'f_789', 'f_466', 'f_866', 'f_728'], ['f_308', 'f_791', 'f_773', 'f_118', 'f_778'], ['f_287', 'f_195', 'f_292', 'f_526', 'f_47'], ['f_391', 'f_845', 'f_788', 'f_719', 'f_151'], ['f_366', 'f_330', 'f_460', 'f_799', 'f_529'], ['f_406', 'f_752', 'f_736', 'f_25', 'f_328'], ['f_697', 'f_511', 'f_725', 'f_749', 'f_815'], ['f_12', 'f_675', 'f_587', 'f_436', 'f_26'], ['f_643', 'f_861', 'f_229', 'f_670', 'f_505'], ['f_528', 'f_43', 'f_729', 'f_622', 'f_427'], ['f_335', 'f_757', 'f_409', 'f_486', 'f_782'], ['f_143', 'f_767', 'f_327', 'f_350', 'f_764'], ['f_656', 'f_706', 'f_554', 'f_417', 'f_448'], ['f_566', 'f_214', 'f_715', 'f_509', 'f_361'], ['f_186', 'f_131', 'f_388', 'f_583', 'f_343'], ['f_392', 'f_840', 'f_398', 'f_408', 'f_497'], ['f_185', 'f_46', 'f_262', 'f_132', 'f_609'], ['f_299', 'f_839', 'f_820', 'f_676', 'f_401'], ['f_181', 'f_166', 'f_455', 'f_298', 'f_129'], ['f_540', 'f_827', 'f_167', 'f_394', 'f_812'], ['f_712', 'f_830', 'f_35', 'f_518', 'f_763'], ['f_682', 'f_242', 'f_483', 'f_568', 'f_738'], ['f_180', 'f_207', 'f_454', 'f_785', 'f_407'], ['f_393', 'f_722', 'f_230', 'f_471', 'f_770'], ['f_19', 'f_429', 'f_813', 'f_164', 'f_740'], ['f_617', 'f_750', 'f_558', 'f_477', 'f_508'], ['f_440', 'f_650', 'f_496', 'f_551', 'f_833'], ['f_146', 'f_801', 'f_419', 'f_522', 'f_116'], ['f_638', 'f_860', 'f_644', 'f_513', 'f_653'], ['f_15', 'f_144', 'f_625', 'f_461', 'f_159'], ['f_345', 'f_474', 'f_822', 'f_803', 'f_215'], ['f_571', 'f_467', 'f_115', 'f_514', 'f_533'], ['f_244', 'f_38', 'f_216', 'f_363', 'f_559'], ['f_667', 'f_647', 'f_759', 'f_347', 'f_742'], ['f_672', 'f_160', 'f_473', 'f_717', 'f_30'], ['f_192', 'f_489', 'f_314', 'f_494', 'f_780'], ['f_659', 'f_423', 'f_721', 'f_249', 'f_411'], ['f_614', 'f_488', 'f_588', 'f_456', 'f_422'], ['f_452', 'f_517', 'f_543', 'f_630', 'f_475'], ['f_341', 'f_425', 'f_421', 'f_826', 'f_200'], ['f_339', 'f_395', 'f_187', 'f_716', 'f_336'], ['f_241', 'f_301', 'f_22', 'f_805', 'f_213'], ['f_685', 'f_24', 'f_480', 'f_761', 'f_612'], ['f_451', 'f_575', 'f_359', 'f_711', 'f_465'], ['f_380', 'f_621', 'f_227', 'f_713', 'f_414'], ['f_405', 'f_17', 'f_364', 'f_305', 'f_784'], ['f_37', 'f_157', 'f_544', 'f_500', 'f_515'], ['f_569', 'f_334', 'f_457', 'f_367', 'f_694'], ['f_340', 'f_610', 'f_652', 'f_34', 'f_397'], ['f_439', 'f_337', 'f_260', 'f_532', 'f_824'], ['f_257', 'f_605', 'f_624', 'f_206', 'f_658'], ['f_646', 'f_705', 'f_601', 'f_383', 'f_734'], ['f_516', 'f_661', 'f_378', 'f_707', 'f_349'], ['f_145', 'f_700', 'f_503', 'f_737', 'f_300'], ['f_535', 'f_458', 'f_152', 'f_250', 'f_563'], ['f_593', 'f_819', 'f_459', 'f_615', 'f_800'], ['f_696', 'f_438', 'f_586', 'f_756', 'f_400'], ['f_3', 'f_673', 'f_598', 'f_412', 'f_779'], ['f_699', 'f_485', 'f_531', 'f_501', 'f_385'], ['f_597', 'f_251', 'f_527', 'f_681', 'f_362'], ['f_592', 'f_537', 'f_399', 'f_188', 'f_342'], ['f_690', 'f_435', 'f_507', 'f_591', 'f_703'], ['f_365', 'f_462', 'f_499', 'f_735', 'f_550'], ['f_639', 'f_372', 'f_294', 'f_755', 'f_368'], ['f_645', 'f_776', 'f_386', 'f_620', 'f_353'], ['f_443', 'f_547', 'f_701', 'f_758', 'f_293'], ['f_420', 'f_572', 'f_590', 'f_632', 'f_577'], ['f_432', 'f_389', 'f_663', 'f_33', 'f_821'], ['f_536', 'f_662', 'f_797', 'f_504', 'f_623'], ['f_602', 'f_798', 'f_596', 'f_686', 'f_600'], ['f_579', 'f_519', 'f_193', 'f_589', 'f_243'], ['f_698', 'f_674', 'f_21', 'f_493', 'f_199'], ['f_692', 'f_484', 'f_565', 'f_13', 'f_818'], ['f_573', 'f_153', 'f_693', 'f_445', 'f_248'], ['f_580', 'f_567', 'f_261', 'f_671', 'f_491'], ['f_611', 'f_777', 'f_530', 'f_642', 'f_626'], ['f_684', 'f_379', 'f_714', 'f_377', 'f_581'], ['f_683', 'f_150', 'f_476', 'f_636', 'f_695'], ['f_553', 'f_702', 'f_373', 'f_604', 'f_375'], ['f_16', 'f_666', 'f_704', 'f_447', 'f_691'], ['f_613', 'f_258', 'f_594', 'f_487', 'f_542'], ['f_637', 'f_450', 'f_576', 'f_382', 'f_521'], ['f_641', 'f_560', 'f_555', 'f_688', 'f_259'], ['f_390', 'f_651', 'f_654', 'f_357', 'f_689'], ['f_680', 'f_431', 'f_381', 'f_502', 'f_628'], ['f_464', 'f_606', 'f_539', 'f_286', 'f_523'], ['f_619', 'f_472', 'f_633', 'f_18', 'f_541'], ['f_607', 'f_498', 'f_506', 'f_352', 'f_546'], ['f_333', 'f_482', 'f_574', 'f_665', 'f_453'], ['f_285', 'f_403', 'f_655', 'f_437', 'f_710'], ['f_549', 'f_548', 'f_396', 'f_9', 'f_538'], ['f_709', 'f_387', 'f_657', 'f_283', 'f_418'], ['f_449', 'f_708', 'f_358', 'f_0', 'f_256'], ['f_1', 'f_442', 'f_585', 'f_356', 'f_179'], ['f_376', 'f_679', 'f_14', 'f_495', 'f_430'], ['f_11', 'f_545', 'f_599', 'f_351', 'f_618'], ['f_564', 'f_284', 'f_371', 'f_10', 'f_370'], ['f_178', 'f_603', 'f_344', 'f_595', 'f_332'], ['f_664', 'f_582', 'f_255', 'f_446', 'f_578'], ['f_434', 'f_355', 'f_416', 'f_677', 'f_640'], ['f_520', 'f_441', 'f_678', 'f_384', 'f_490'], ['f_524', 'f_584', 'f_556', 'f_608', 'f_570'], ['f_470', 'f_660', 'f_668', 'f_552', 'f_634']]
XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5284038, HammingLoss: 0.15909, SubsetAccuracy: 0.42424,
pruning: False, include_original_features: with_org, averageAUROC: 0.5302506, HammingLoss: 0.25631, SubsetAccuracy: 0.25758,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.15152, SubsetAccuracy: 0.43939,
pruning: False, include_original_features: no_org, averageAUROC: 0.5674231, HammingLoss: 0.26894, SubsetAccuracy: 0.24242,

Fold 10/10 (fingerprint_diverse 8/9)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:27<00:00,  6.14feat/s]

XofN_groups: [['f_374', 'f_831', 'f_194', 'f_834', 'f_31'], ['f_335', 'f_466', 'f_47', 'f_511', 'f_789'], ['f_20', 'f_792', 'f_629', 'f_328', 'f_635'], ['f_346', 'f_726', 'f_428', 'f_749', 'f_799'], ['f_2', 'f_768', 'f_413', 'f_510', 'f_27'], ['f_338', 'f_820', 'f_529', 'f_845', 'f_455'], ['f_12', 'f_836', 'f_118', 'f_587', 'f_675'], ['f_617', 'f_616', 'f_813', 'f_25', 'f_330'], ['f_308', 'f_526', 'f_791', 'f_725', 'f_214'], ['f_566', 'f_773', 'f_417', 'f_297', 'f_788'], ['f_391', 'f_866', 'f_719', 'f_408', 'f_505'], ['f_287', 'f_195', 'f_292', 'f_166', 'f_736'], ['f_185', 'f_151', 'f_26', 'f_771', 'f_350'], ['f_186', 'f_131', 'f_202', 'f_388', 'f_670'], ['f_406', 'f_750', 'f_327', 'f_778', 'f_401'], ['f_23', 'f_631', 'f_167', 'f_448', 'f_509'], ['f_656', 'f_460', 'f_706', 'f_436', 'f_554'], ['f_392', 'f_861', 'f_398', 'f_583', 'f_471'], ['f_366', 'f_429', 'f_427', 'f_622', 'f_728'], ['f_393', 'f_840', 'f_229', 'f_764', 'f_767'], ['f_143', 'f_830', 'f_46', 'f_43', 'f_738'], ['f_241', 'f_132', 'f_715', 'f_298', 'f_717'], ['f_639', 'f_757', 'f_729', 'f_454', 'f_497'], ['f_571', 'f_815', 'f_833', 'f_483', 'f_116'], ['f_697', 'f_35', 'f_812', 'f_752', 'f_650'], ['f_380', 'f_722', 'f_262', 'f_518', 'f_770'], ['f_452', 'f_785', 'f_394', 'f_782', 'f_343'], ['f_528', 'f_486', 'f_839', 'f_742', 'f_513'], ['f_3', 'f_477', 'f_423', 'f_827', 'f_508'], ['f_643', 'f_242', 'f_522', 'f_676', 'f_759'], ['f_672', 'f_207', 'f_609', 'f_496', 'f_474'], ['f_339', 'f_568', 'f_215', 'f_475', 'f_407'], ['f_659', 'f_419', 'f_361', 'f_740', 'f_588'], ['f_682', 'f_860', 'f_129', 'f_763', 'f_647'], ['f_614', 'f_533', 'f_164', 'f_644', 'f_551'], ['f_181', 'f_409', 'f_159', 'f_514', 'f_144'], ['f_540', 'f_653', 'f_822', 'f_115', 'f_488'], ['f_405', 'f_558', 'f_801', 'f_34', 'f_456'], ['f_638', 'f_467', 'f_230', 'f_473', 'f_216'], ['f_192', 'f_489', 'f_30', 'f_494', 'f_780'], ['f_439', 'f_826', 'f_314', 'f_625', 'f_422'], ['f_146', 'f_543', 'f_347', 'f_363', 'f_213'], ['f_334', 'f_300', 'f_22', 'f_480', 'f_805'], ['f_341', 'f_517', 'f_500', 'f_200', 'f_411'], ['f_19', 'f_461', 'f_803', 'f_160', 'f_721'], ['f_180', 'f_559', 'f_687', 'f_301', 'f_336'], ['f_516', 'f_425', 'f_784', 'f_421', 'f_713'], ['f_667', 'f_621', 'f_395', 'f_38', 'f_605'], ['f_611', 'f_711', 'f_575', 'f_465', 'f_364'], ['f_257', 'f_227', 'f_367', 'f_716', 'f_694'], ['f_244', 'f_24', 'f_591', 'f_157', 'f_761'], ['f_699', 'f_485', 'f_305', 'f_658', 'f_515'], ['f_440', 'f_652', 'f_359', 'f_249', 'f_532'], ['f_15', 'f_705', 'f_187', 'f_152', 'f_457'], ['f_535', 'f_414', 'f_206', 'f_397', 'f_544'], ['f_299', 'f_337', 'f_630', 'f_260', 'f_503'], ['f_345', 'f_610', 'f_737', 'f_17', 'f_531'], ['f_712', 'f_378', 'f_586', 'f_563', 'f_707'], ['f_451', 'f_700', 'f_601', 'f_400', 'f_598'], ['f_340', 'f_661', 'f_250', 'f_612', 'f_527'], ['f_443', 'f_458', 'f_824', 'f_499', 'f_734'], ['f_696', 'f_438', 'f_459', 'f_590', 'f_462'], ['f_646', 'f_432', 'f_383', 'f_399', 'f_701'], ['f_579', 'f_362', 'f_386', 'f_756', 'f_624'], ['f_420', 'f_251', 'f_153', 'f_501', 'f_779'], ['f_685', 'f_662', 'f_412', 'f_342', 'f_673'], ['f_248', 'f_349', 'f_615', 'f_800', 'f_294'], ['f_365', 'f_537', 'f_547', 'f_735', 'f_507'], ['f_569', 'f_819', 'f_188', 'f_550', 'f_368'], ['f_259', 'f_663', 'f_37', 'f_776', 'f_695'], ['f_683', 'f_686', 'f_504', 'f_620', 'f_818'], ['f_597', 'f_389', 'f_681', 'f_385', 'f_755'], ['f_16', 'f_798', 'f_353', 'f_623', 'f_703'], ['f_645', 'f_690', 'f_577', 'f_632', 'f_572'], ['f_145', 'f_693', 'f_199', 'f_758', 'f_293'], ['f_593', 'f_797', 'f_33', 'f_567', 'f_243'], ['f_602', 'f_565', 'f_445', 'f_193', 'f_671'], ['f_613', 'f_13', 'f_493', 'f_589', 'f_372'], ['f_150', 'f_626', 'f_536', 'f_435', 'f_553'], ['f_692', 'f_484', 'f_476', 'f_21', 'f_821'], ['f_684', 'f_379', 'f_714', 'f_377', 'f_581'], ['f_698', 'f_674', 'f_642', 'f_576', 'f_702'], ['f_691', 'f_519', 'f_777', 'f_580', 'f_600'], ['f_464', 'f_261', 'f_666', 'f_596', 'f_704'], ['f_637', 'f_636', 'f_604', 'f_258', 'f_546'], ['f_689', 'f_560', 'f_530', 'f_594', 'f_491'], ['f_680', 'f_373', 'f_542', 'f_375', 'f_633'], ['f_390', 'f_447', 'f_382', 'f_487', 'f_665'], ['f_641', 'f_654', 'f_555', 'f_688', 'f_521'], ['f_619', 'f_450', 'f_628', 'f_357', 'f_651'], ['f_502', 'f_606', 'f_431', 'f_286', 'f_403'], ['f_549', 'f_541', 'f_539', 'f_352', 'f_472'], ['f_592', 'f_381', 'f_506', 'f_18', 'f_523'], ['f_333', 'f_482', 'f_498', 'f_437', 'f_655'], ['f_607', 'f_396', 'f_574', 'f_9', 'f_538'], ['f_11', 'f_387', 'f_548', 'f_585', 'f_573'], ['f_709', 'f_358', 'f_657', 'f_283', 'f_453'], ['f_442', 'f_710', 'f_495', 'f_344', 'f_256'], ['f_418', 'f_708', 'f_545', 'f_284', 'f_356'], ['f_430', 'f_376', 'f_14', 'f_449', 'f_679'], ['f_370', 'f_1', 'f_285', 'f_179', 'f_599'], ['f_434', 'f_351', 'f_618', 'f_0', 'f_371'], ['f_664', 'f_10', 'f_384', 'f_332', 'f_578'], ['f_564', 'f_582', 'f_255', 'f_178', 'f_446'], ['f_570', 'f_416', 'f_603', 'f_441', 'f_660'], ['f_640', 'f_355', 'f_677', 'f_524', 'f_552'], ['f_668', 'f_490', 'f_584', 'f_556', 'f_595'], ['f_520', 'f_678', 'f_608', 'f_634', 'f_470']]
XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5337387, HammingLoss: 0.17677, SubsetAccuracy: 0.44697,
pruning: False, include_original_features: with_org, averageAUROC: 0.6065934, HammingLoss: 0.27399, SubsetAccuracy: 0.25758,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.18182, SubsetAccuracy: 0.42424,
pruning: False, include_original_features: no_org, averageAUROC: 0.5780543, HammingLoss: 0.27778, SubsetAccuracy: 0.24242,
   pruning include_original_features              dataset  averageAUROC  \
0    False                    no_org  fingerprint_diverse      0.562458
1    False                  with_org  fingerprint_diverse      0.567529
2     True                    no_org  fingerprint_diverse      0.500000
3     True                  with_org  fingerprint_diverse      0.516977

   HammingLoss  SubsetAccuracy  nodes  leaves  groups  avg_group_features  \
0     0.276895        0.227272  805.4   403.2   108.0                 5.0
1     0.268308        0.229548  777.8   389.4   108.0                 5.0
2     0.181567        0.425757    1.0     1.0   108.0                 5.0
3     0.178788        0.437122    3.6     2.3   108.0                 5.0

   gen_XofN_time  training_time
0      87.787998       0.743740
1      87.787998       1.584081
2      87.787998       0.743740
3      87.787998       1.584081

--- Running with label:'['se_C0027497', 'se_C0018681', 'se_C0011603', 'se_C0015230', 'se_C0042963', 'se_C0012833']' training_algorithm:'Jaccard_min' eval_criterion:'['averageAUROC', 'HammingLoss', 'SubsetAccuracy']' max_size:'5' ---
Logs can be found in XofN_jaccard_min/logs/fingerprint_frequent_Jaccard_min_averageAUROC_HammingLoss_SubsetAccuracy_5_logs.txt.

Fold 1/10 (fingerprint_frequent 9/9)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:27<00:00,  6.14feat/s]

XofN_groups: [['f_374', 'f_831', 'f_194', 'f_771', 'f_31'], ['f_20', 'f_729', 'f_629', 'f_214', 'f_510'], ['f_23', 'f_413', 'f_631', 'f_47', 'f_118'], ['f_346', 'f_789', 'f_799', 'f_428', 'f_616'], ['f_308', 'f_773', 'f_791', 'f_788', 'f_25'], ['f_366', 'f_726', 'f_736', 'f_460', 'f_466'], ['f_15', 'f_866', 'f_836', 'f_719', 'f_436'], ['f_451', 'f_845', 'f_151', 'f_526', 'f_328'], ['f_287', 'f_408', 'f_622', 'f_292', 'f_164'], ['f_672', 'f_830', 'f_229', 'f_327', 'f_27'], ['f_19', 'f_529', 'f_330', 'f_202', 'f_587'], ['f_406', 'f_768', 'f_728', 'f_722', 'f_635'], ['f_697', 'f_511', 'f_725', 'f_749', 'f_497'], ['f_639', 'f_778', 'f_131', 'f_166', 'f_297'], ['f_3', 'f_477', 'f_423', 'f_767', 'f_675'], ['f_37', 'f_782', 'f_43', 'f_35', 'f_394'], ['f_2', 'f_834', 'f_26', 'f_509', 'f_409'], ['f_299', 'f_861', 'f_583', 'f_757', 'f_262'], ['f_393', 'f_840', 'f_764', 'f_554', 'f_471'], ['f_392', 'f_839', 'f_670', 'f_398', 'f_505'], ['f_380', 'f_785', 'f_820', 'f_455', 'f_486'], ['f_452', 'f_792', 'f_650', 'f_706', 'f_448'], ['f_420', 'f_752', 'f_427', 'f_350', 'f_770'], ['f_11', 'f_417', 'f_298', 'f_676', 'f_167'], ['f_712', 'f_533', 'f_815', 'f_812', 'f_407'], ['f_614', 'f_419', 'f_474', 'f_46', 'f_207'], ['f_656', 'f_827', 'f_715', 'f_401', 'f_116'], ['f_571', 'f_833', 'f_429', 'f_483', 'f_132'], ['f_24', 'f_215', 'f_195', 'f_361', 'f_687'], ['f_440', 'f_496', 'f_551', 'f_456', 'f_230'], ['f_566', 'f_242', 'f_568', 'f_740', 'f_750'], ['f_696', 'f_508', 'f_813', 'f_388', 'f_522'], ['f_617', 'f_759', 'f_473', 'f_518', 'f_763'], ['f_391', 'f_653', 'f_343', 'f_461', 'f_363'], ['f_339', 'f_644', 'f_513', 'f_216', 'f_314'], ['f_686', 'f_489', 'f_780', 'f_425', 'f_467'], ['f_186', 'f_475', 'f_30', 'f_588', 'f_494'], ['f_185', 'f_609', 'f_129', 'f_159', 'f_543'], ['f_338', 'f_558', 'f_801', 'f_411', 'f_721'], ['f_12', 'f_454', 'f_115', 'f_347', 'f_647'], ['f_659', 'f_860', 'f_738', 'f_514', 'f_784'], ['f_192', 'f_480', 'f_422', 'f_625', 'f_488'], ['f_569', 'f_711', 'f_575', 'f_465', 'f_517'], ['f_38', 'f_559', 'f_260', 'f_336', 'f_213'], ['f_340', 'f_144', 'f_160', 'f_717', 'f_630'], ['f_516', 'f_367', 'f_742', 'f_822', 'f_359'], ['f_681', 'f_457', 'f_17', 'f_364', 'f_395'], ['f_390', 'f_610', 'f_826', 'f_421', 'f_200'], ['f_14', 'f_803', 'f_157', 'f_414', 'f_301'], ['f_405', 'f_34', 'f_515', 'f_805', 'f_249'], ['f_33', 'f_707', 'f_713', 'f_761', 'f_612'], ['f_528', 'f_397', 'f_334', 'f_532', 'f_22'], ['f_332', 'f_652', 'f_227', 'f_694', 'f_300'], ['f_643', 'f_605', 'f_187', 'f_500', 'f_624'], ['f_335', 'f_305', 'f_716', 'f_544', 'f_658'], ['f_143', 'f_250', 'f_661', 'f_458', 'f_152'], ['f_567', 'f_399', 'f_503', 'f_737', 'f_531'], ['f_443', 'f_621', 'f_206', 'f_383', 'f_756'], ['f_663', 'f_435', 'f_459', 'f_251', 'f_673'], ['f_341', 'f_378', 'f_586', 'f_563', 'f_779'], ['f_535', 'f_601', 'f_734', 'f_412', 'f_824'], ['f_146', 'f_188', 'f_590', 'f_342', 'f_800'], ['f_285', 'f_705', 'f_400', 'f_598', 'f_735'], ['f_611', 'f_337', 'f_620', 'f_527', 'f_501'], ['f_21', 'f_438', 'f_591', 'f_776', 'f_507'], ['f_181', 'f_349', 'f_462', 'f_362', 'f_485'], ['f_667', 'f_550', 'f_243', 'f_700', 'f_368'], ['f_439', 'f_701', 'f_294', 'f_386', 'f_432'], ['f_579', 'f_499', 'f_632', 'f_385', 'f_537'], ['f_613', 'f_819', 'f_547', 'f_615', 'f_755'], ['f_684', 'f_572', 'f_703', 'f_353', 'f_818'], ['f_638', 'f_797', 'f_293', 'f_389', 'f_623'], ['f_345', 'f_693', 'f_153', 'f_577', 'f_798'], ['f_257', 'f_690', 'f_695', 'f_504', 'f_199'], ['f_10', 'f_261', 'f_662', 'f_685', 'f_248'], ['f_464', 'f_193', 'f_642', 'f_484', 'f_565'], ['f_18', 'f_13', 'f_379', 'f_626', 'f_758'], ['f_682', 'f_671', 'f_372', 'f_714', 'f_150'], ['f_540', 'f_581', 'f_244', 'f_699', 'f_674'], ['f_704', 'f_487', 'f_476', 'f_821', 'f_602'], ['f_553', 'f_596', 'f_589', 'f_536', 'f_702'], ['f_698', 'f_636', 'f_580', 'f_576', 'f_691'], ['f_365', 'f_777', 'f_493', 'f_258', 'f_519'], ['f_592', 'f_241', 'f_445', 'f_597', 'f_604'], ['f_180', 'f_542', 'f_646', 'f_450', 'f_692'], ['f_333', 'f_491', 'f_594', 'f_593', 'f_645'], ['f_683', 'f_373', 'f_666', 'f_16', 'f_382'], ['f_689', 'f_560', 'f_530', 'f_651', 'f_377'], ['f_637', 'f_447', 'f_600', 'f_606', 'f_654'], ['f_573', 'f_521', 'f_375', 'f_688', 'f_259'], ['f_286', 'f_357', 'f_541', 'f_546', 'f_145'], ['f_708', 'f_431', 'f_381', 'f_502', 'f_680'], ['f_709', 'f_472', 'f_498', 'f_665', 'f_555'], ['f_619', 'f_506', 'f_633', 'f_352', 'f_539'], ['f_1', 'f_523', 'f_655', 'f_628', 'f_403'], ['f_351', 'f_482', 'f_574', 'f_437', 'f_641'], ['f_549', 'f_548', 'f_396', 'f_9', 'f_538'], ['f_284', 'f_387', 'f_607', 'f_453', 'f_710'], ['f_430', 'f_358', 'f_585', 'f_283', 'f_418'], ['f_0', 'f_256', 'f_657', 'f_356', 'f_442'], ['f_449', 'f_679', 'f_495', 'f_599', 'f_344'], ['f_178', 'f_545', 'f_371', 'f_376', 'f_582'], ['f_255', 'f_179', 'f_446', 'f_618', 'f_416'], ['f_564', 'f_441', 'f_370', 'f_434', 'f_355'], ['f_520', 'f_556', 'f_384', 'f_524', 'f_578'], ['f_664', 'f_490', 'f_552', 'f_640', 'f_570'], ['f_678', 'f_603', 'f_595', 'f_660', 'f_470'], ['f_677', 'f_608', 'f_668', 'f_584', 'f_634']]
XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5183434, HammingLoss: 0.18939, SubsetAccuracy: 0.50758,
pruning: False, include_original_features: with_org, averageAUROC: 0.5427652, HammingLoss: 0.27904, SubsetAccuracy: 0.30303,
pruning: True, include_original_features: no_org, averageAUROC: 0.594594, HammingLoss: 0.20707, SubsetAccuracy: 0.49242,
pruning: False, include_original_features: no_org, averageAUROC: 0.5594765, HammingLoss: 0.2803, SubsetAccuracy: 0.36364,

Fold 2/10 (fingerprint_frequent 9/9)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:27<00:00,  6.15feat/s]

XofN_groups: [['f_374', 'f_831', 'f_194', 'f_27', 'f_834'], ['f_20', 'f_729', 'f_629', 'f_428', 'f_214'], ['f_23', 'f_413', 'f_631', 'f_436', 'f_118'], ['f_308', 'f_616', 'f_529', 'f_25', 'f_409'], ['f_516', 'f_31', 'f_47', 'f_836', 'f_771'], ['f_366', 'f_726', 'f_417', 'f_635', 'f_749'], ['f_19', 'f_773', 'f_510', 'f_151', 'f_845'], ['f_672', 'f_292', 'f_526', 'f_830', 'f_43'], ['f_406', 'f_789', 'f_791', 'f_799', 'f_785'], ['f_346', 'f_768', 'f_427', 'f_728', 'f_429'], ['f_287', 'f_408', 'f_448', 'f_164', 'f_460'], ['f_15', 'f_866', 'f_622', 'f_587', 'f_827'], ['f_639', 'f_533', 'f_486', 'f_166', 'f_327'], ['f_380', 'f_757', 'f_722', 'f_388', 'f_518'], ['f_440', 'f_792', 'f_788', 'f_330', 'f_650'], ['f_24', 'f_216', 'f_262', 'f_670', 'f_202'], ['f_3', 'f_815', 'f_511', 'f_328', 'f_715'], ['f_656', 'f_706', 'f_26', 'f_719', 'f_297'], ['f_452', 'f_820', 'f_497', 'f_764', 'f_401'], ['f_614', 'f_767', 'f_477', 'f_35', 'f_350'], ['f_451', 'f_675', 'f_861', 'f_229', 'f_752'], ['f_571', 'f_736', 'f_509', 'f_568', 'f_215'], ['f_11', 'f_583', 'f_554', 'f_763', 'f_725'], ['f_393', 'f_840', 'f_505', 'f_471', 'f_455'], ['f_566', 'f_839', 'f_676', 'f_394', 'f_833'], ['f_2', 'f_466', 'f_298', 'f_407', 'f_207'], ['f_697', 'f_131', 'f_812', 'f_494', 'f_551'], ['f_299', 'f_242', 'f_496', 'f_513', 'f_195'], ['f_338', 'f_750', 'f_778', 'f_653', 'f_361'], ['f_37', 'f_782', 'f_157', 'f_473', 'f_588'], ['f_391', 'f_483', 'f_46', 'f_167', 'f_740'], ['f_335', 'f_813', 'f_508', 'f_522', 'f_423'], ['f_339', 'f_489', 'f_398', 'f_116', 'f_343'], ['f_14', 'f_474', 'f_543', 'f_347', 'f_159'], ['f_712', 'f_475', 'f_609', 'f_826', 'f_644'], ['f_617', 'f_454', 'f_738', 'f_721', 'f_30'], ['f_643', 'f_461', 'f_230', 'f_419', 'f_625'], ['f_143', 'f_759', 'f_742', 'f_411', 'f_200'], ['f_185', 'f_132', 'f_770', 'f_115', 'f_687'], ['f_420', 'f_456', 'f_822', 'f_488', 'f_467'], ['f_681', 'f_465', 'f_129', 'f_647', 'f_801'], ['f_12', 'f_558', 'f_425', 'f_422', 'f_717'], ['f_181', 'f_514', 'f_559', 'f_860', 'f_17'], ['f_405', 'f_780', 'f_517', 'f_480', 'f_694'], ['f_392', 'f_314', 'f_144', 'f_784', 'f_395'], ['f_340', 'f_38', 'f_160', 'f_363', 'f_605'], ['f_390', 'f_367', 'f_652', 'f_421', 'f_711'], ['f_186', 'f_378', 'f_336', 'f_34', 'f_213'], ['f_696', 'f_805', 'f_359', 'f_301', 'f_22'], ['f_146', 'f_575', 'f_364', 'f_334', 'f_305'], ['f_462', 'f_414', 'f_397', 'f_206', 'f_515'], ['f_33', 'f_803', 'f_300', 'f_707', 'f_612'], ['f_659', 'f_457', 'f_713', 'f_761', 'f_716'], ['f_332', 'f_610', 'f_260', 'f_532', 'f_227'], ['f_192', 'f_500', 'f_624', 'f_630', 'f_400'], ['f_684', 'f_621', 'f_658', 'f_661', 'f_779'], ['f_443', 'f_601', 'f_563', 'f_586', 'f_503'], ['f_341', 'f_187', 'f_152', 'f_458', 'f_734'], ['f_637', 'f_459', 'f_527', 'f_544', 'f_362'], ['f_257', 'f_537', 'f_673', 'f_349', 'f_824'], ['f_613', 'f_705', 'f_399', 'f_531', 'f_737'], ['f_528', 'f_337', 'f_438', 'f_598', 'f_800'], ['f_569', 'f_700', 'f_383', 'f_249', 'f_685'], ['f_611', 'f_701', 'f_591', 'f_385', 'f_412'], ['f_579', 'f_250', 'f_485', 'f_501', 'f_663'], ['f_535', 'f_251', 'f_153', 'f_342', 'f_756'], ['f_686', 'f_294', 'f_386', 'f_507', 'f_776'], ['f_439', 'f_432', 'f_188', 'f_547', 'f_550'], ['f_667', 'f_243', 'f_615', 'f_693', 'f_368'], ['f_645', 'f_819', 'f_499', 'f_703', 'f_353'], ['f_638', 'f_818', 'f_484', 'f_632', 'f_293'], ['f_698', 'f_572', 'f_755', 'f_577', 'f_620'], ['f_567', 'f_435', 'f_623', 'f_590', 'f_758'], ['f_540', 'f_735', 'f_150', 'f_372', 'f_493'], ['f_692', 'f_504', 'f_798', 'f_445', 'f_690'], ['f_248', 'f_389', 'f_597', 'f_21', 'f_662'], ['f_365', 'f_261', 'f_797', 'f_581', 'f_674'], ['f_18', 'f_193', 'f_379', 'f_642', 'f_589'], ['f_464', 'f_714', 'f_596', 'f_199', 'f_671'], ['f_553', 'f_13', 'f_565', 'f_519', 'f_821'], ['f_285', 'f_244', 'f_699', 'f_580', 'f_636'], ['f_345', 'f_258', 'f_777', 'f_602', 'f_626'], ['f_16', 'f_476', 'f_695', 'f_241', 'f_373'], ['f_180', 'f_536', 'f_604', 'f_487', 'f_704'], ['f_592', 'f_491', 'f_666', 'f_702', 'f_646'], ['f_593', 'f_594', 'f_576', 'f_682', 'f_9'], ['f_689', 'f_447', 'f_377', 'f_691', 'f_560'], ['f_430', 'f_450', 'f_542', 'f_530', 'f_145'], ['f_573', 'f_521', 'f_375', 'f_600', 'f_382'], ['f_333', 'f_654', 'f_651', 'f_357', 'f_633'], ['f_351', 'f_259', 'f_606', 'f_539', 'f_680'], ['f_619', 'f_472', 'f_283', 'f_665', 'f_381'], ['f_10', 'f_431', 'f_541', 'f_546', 'f_641'], ['f_688', 'f_482', 'f_498', 'f_502', 'f_555'], ['f_286', 'f_506', 'f_574', 'f_628', 'f_418'], ['f_709', 'f_403', 'f_548', 'f_437', 'f_352'], ['f_683', 'f_396', 'f_655', 'f_657', 'f_0'], ['f_1', 'f_523', 'f_607', 'f_453', 'f_710'], ['f_708', 'f_387', 'f_549', 'f_344', 'f_538'], ['f_284', 'f_358', 'f_356', 'f_585', 'f_256'], ['f_178', 'f_442', 'f_545', 'f_599', 'f_495'], ['f_449', 'f_679', 'f_371', 'f_376', 'f_582'], ['f_434', 'f_255', 'f_179', 'f_370', 'f_416'], ['f_564', 'f_441', 'f_618', 'f_446', 'f_355'], ['f_664', 'f_556', 'f_384', 'f_524', 'f_603'], ['f_608', 'f_490', 'f_578', 'f_640', 'f_570'], ['f_660', 'f_552', 'f_584', 'f_678', 'f_595'], ['f_520', 'f_677', 'f_668', 'f_634', 'f_470']]
XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.4752998, HammingLoss: 0.20707, SubsetAccuracy: 0.53788,
pruning: False, include_original_features: with_org, averageAUROC: 0.4928321, HammingLoss: 0.28157, SubsetAccuracy: 0.36364,
pruning: True, include_original_features: no_org, averageAUROC: 0.4717108, HammingLoss: 0.21086, SubsetAccuracy: 0.5303,
pruning: False, include_original_features: no_org, averageAUROC: 0.5656697, HammingLoss: 0.26641, SubsetAccuracy: 0.38636,

Fold 3/10 (fingerprint_frequent 9/9)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:27<00:00,  6.14feat/s]

XofN_groups: [['f_374', 'f_831', 'f_27', 'f_771', 'f_194'], ['f_20', 'f_792', 'f_629', 'f_635', 'f_428'], ['f_23', 'f_413', 'f_631', 'f_118', 'f_47'], ['f_346', 'f_768', 'f_429', 'f_460', 'f_31'], ['f_3', 'f_726', 'f_834', 'f_409', 'f_328'], ['f_308', 'f_616', 'f_789', 'f_722', 'f_327'], ['f_366', 'f_466', 'f_417', 'f_799', 'f_675'], ['f_639', 'f_427', 'f_676', 'f_736', 'f_511'], ['f_299', 'f_866', 'f_202', 'f_436', 'f_214'], ['f_672', 'f_292', 'f_43', 'f_845', 'f_767'], ['f_19', 'f_510', 'f_297', 'f_836', 'f_830'], ['f_37', 'f_782', 'f_35', 'f_509', 'f_448'], ['f_571', 'f_529', 'f_568', 'f_670', 'f_788'], ['f_287', 'f_408', 'f_207', 'f_526', 'f_229'], ['f_24', 'f_216', 'f_407', 'f_151', 'f_554'], ['f_15', 'f_861', 'f_773', 'f_719', 'f_330'], ['f_393', 'f_840', 'f_757', 'f_583', 'f_497'], ['f_406', 'f_791', 'f_778', 'f_25', 'f_26'], ['f_614', 'f_749', 'f_166', 'f_725', 'f_508'], ['f_452', 'f_785', 'f_650', 'f_518', 'f_401'], ['f_380', 'f_729', 'f_820', 'f_587', 'f_262'], ['f_440', 'f_728', 'f_715', 'f_388', 'f_505'], ['f_516', 'f_350', 'f_764', 'f_474', 'f_167'], ['f_339', 'f_813', 'f_419', 'f_131', 'f_622'], ['f_566', 'f_839', 'f_477', 'f_833', 'f_455'], ['f_420', 'f_815', 'f_770', 'f_706', 'f_471'], ['f_451', 'f_752', 'f_242', 'f_812', 'f_513'], ['f_405', 'f_46', 'f_394', 'f_132', 'f_164'], ['f_392', 'f_398', 'f_195', 'f_361', 'f_298'], ['f_12', 'f_827', 'f_461', 'f_116', 'f_423'], ['f_391', 'f_551', 'f_763', 'f_473', 'f_230'], ['f_697', 'f_533', 'f_543', 'f_343', 'f_647'], ['f_11', 'f_750', 'f_522', 'f_475', 'f_456'], ['f_186', 'f_489', 'f_30', 'f_494', 'f_740'], ['f_659', 'f_860', 'f_644', 'f_653', 'f_514'], ['f_338', 'f_558', 'f_486', 'f_314', 'f_717'], ['f_33', 'f_826', 'f_425', 'f_780', 'f_625'], ['f_696', 'f_609', 'f_496', 'f_347', 'f_454'], ['f_535', 'f_411', 'f_759', 'f_742', 'f_483'], ['f_656', 'f_559', 'f_144', 'f_467', 'f_336'], ['f_192', 'f_215', 'f_480', 'f_38', 'f_363'], ['f_617', 'f_465', 'f_738', 'f_129', 'f_721'], ['f_686', 'f_378', 'f_213', 'f_227', 'f_822'], ['f_443', 'f_517', 'f_805', 'f_115', 'f_22'], ['f_2', 'f_801', 'f_395', 'f_159', 'f_422'], ['f_181', 'f_160', 'f_301', 'f_605', 'f_588'], ['f_681', 'f_457', 'f_488', 'f_364', 'f_397'], ['f_143', 'f_575', 'f_305', 'f_157', 'f_187'], ['f_185', 'f_421', 'f_200', 'f_784', 'f_624'], ['f_340', 'f_803', 'f_359', 'f_34', 'f_711'], ['f_146', 'f_367', 'f_250', 'f_716', 'f_694'], ['f_698', 'f_621', 'f_658', 'f_687', 'f_737'], ['f_643', 'f_337', 'f_630', 'f_515', 'f_500'], ['f_332', 'f_206', 'f_300', 'f_414', 'f_707'], ['f_712', 'f_652', 'f_17', 'f_532', 'f_610'], ['f_569', 'f_334', 'f_458', 'f_761', 'f_713'], ['f_14', 'f_563', 'f_260', 'f_249', 'f_531'], ['f_335', 'f_601', 'f_734', 'f_612', 'f_459'], ['f_663', 'f_435', 'f_383', 'f_776', 'f_703'], ['f_341', 'f_527', 'f_503', 'f_661', 'f_800'], ['f_567', 'f_399', 'f_598', 'f_673', 'f_586'], ['f_528', 'f_705', 'f_438', 'f_251', 'f_152'], ['f_390', 'f_544', 'f_400', 'f_537', 'f_501'], ['f_18', 'f_824', 'f_485', 'f_591', 'f_779'], ['f_613', 'f_700', 'f_499', 'f_550', 'f_385'], ['f_611', 'f_701', 'f_362', 'f_386', 'f_432'], ['f_684', 'f_547', 'f_735', 'f_342', 'f_412'], ['f_540', 'f_462', 'f_153', 'f_188', 'f_756'], ['f_579', 'f_572', 'f_294', 'f_590', 'f_507'], ['f_615', 'f_755', 'f_349', 'f_577', 'f_693'], ['f_439', 'f_819', 'f_504', 'f_193', 'f_368'], ['f_10', 'f_261', 'f_690', 'f_353', 'f_620'], ['f_637', 'f_243', 'f_199', 'f_293', 'f_632'], ['f_285', 'f_13', 'f_623', 'f_389', 'f_798'], ['f_667', 'f_373', 'f_662', 'f_685', 'f_797'], ['f_257', 'f_642', 'f_818', 'f_484', 'f_695'], ['f_704', 'f_379', 'f_589', 'f_21', 'f_758'], ['f_638', 'f_241', 'f_372', 'f_597', 'f_714'], ['f_345', 'f_150', 'f_248', 'f_493', 'f_702'], ['f_1', 'f_244', 'f_581', 'f_674', 'f_699'], ['f_180', 'f_777', 'f_602', 'f_821', 'f_596'], ['f_692', 'f_487', 'f_565', 'f_445', 'f_536'], ['f_689', 'f_636', 'f_580', 'f_626', 'f_576'], ['f_646', 'f_476', 'f_519', 'f_671', 'f_691'], ['f_365', 'f_258', 'f_553', 'f_604', 'f_682'], ['f_619', 'f_491', 'f_645', 'f_377', 'f_450'], ['f_333', 'f_447', 'f_666', 'f_593', 'f_560'], ['f_464', 'f_542', 'f_654', 'f_594', 'f_521'], ['f_592', 'f_357', 'f_382', 'f_375', 'f_680'], ['f_286', 'f_530', 'f_651', 'f_16', 'f_546'], ['f_688', 'f_506', 'f_606', 'f_145', 'f_600'], ['f_628', 'f_541', 'f_431', 'f_352', 'f_259'], ['f_641', 'f_472', 'f_633', 'f_381', 'f_9'], ['f_549', 'f_498', 'f_539', 'f_283', 'f_403'], ['f_351', 'f_523', 'f_655', 'f_502', 'f_573'], ['f_430', 'f_482', 'f_574', 'f_555', 'f_0'], ['f_683', 'f_396', 'f_548', 'f_665', 'f_284'], ['f_708', 'f_387', 'f_437', 'f_344', 'f_453'], ['f_710', 'f_358', 'f_585', 'f_599', 'f_418'], ['f_709', 'f_538', 'f_657', 'f_179', 'f_256'], ['f_679', 'f_442', 'f_495', 'f_356', 'f_607'], ['f_582', 'f_545', 'f_371', 'f_449', 'f_178'], ['f_564', 'f_376', 'f_446', 'f_441', 'f_618'], ['f_434', 'f_255', 'f_603', 'f_416', 'f_370'], ['f_520', 'f_490', 'f_355', 'f_640', 'f_384'], ['f_664', 'f_556', 'f_595', 'f_524', 'f_578'], ['f_570', 'f_678', 'f_584', 'f_660', 'f_608'], ['f_668', 'f_677', 'f_552', 'f_470', 'f_634']]
XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5678056, HammingLoss: 0.20833, SubsetAccuracy: 0.56061,
pruning: False, include_original_features: with_org, averageAUROC: 0.5858653, HammingLoss: 0.26389, SubsetAccuracy: 0.37121,
pruning: True, include_original_features: no_org, averageAUROC: 0.5212114, HammingLoss: 0.22096, SubsetAccuracy: 0.54545,
pruning: False, include_original_features: no_org, averageAUROC: 0.5529351, HammingLoss: 0.27652, SubsetAccuracy: 0.40909,

Fold 4/10 (fingerprint_frequent 9/9)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:28<00:00,  6.14feat/s]

XofN_groups: [['f_374', 'f_789', 'f_834', 'f_25', 'f_202'], ['f_20', 'f_792', 'f_629', 'f_328', 'f_194'], ['f_672', 'f_292', 'f_845', 'f_830', 'f_43'], ['f_366', 'f_428', 'f_726', 'f_327', 'f_635'], ['f_346', 'f_330', 'f_831', 'f_460', 'f_31'], ['f_3', 'f_836', 'f_511', 'f_466', 'f_725'], ['f_571', 'f_509', 'f_799', 'f_529', 'f_401'], ['f_15', 'f_861', 'f_413', 'f_719', 'f_526'], ['f_308', 'f_616', 'f_768', 'f_722', 'f_455'], ['f_19', 'f_773', 'f_297', 'f_510', 'f_151'], ['f_452', 'f_757', 'f_785', 'f_650', 'f_866'], ['f_406', 'f_791', 'f_788', 'f_27', 'f_118'], ['f_697', 'f_35', 'f_767', 'f_749', 'f_436'], ['f_299', 'f_840', 'f_554', 'f_583', 'f_229'], ['f_614', 'f_587', 'f_729', 'f_47', 'f_675'], ['f_2', 'f_497', 'f_771', 'f_670', 'f_736'], ['f_639', 'f_417', 'f_533', 'f_166', 'f_409'], ['f_420', 'f_815', 'f_782', 'f_214', 'f_262'], ['f_23', 'f_631', 'f_164', 'f_448', 'f_609'], ['f_11', 'f_26', 'f_350', 'f_408', 'f_706'], ['f_380', 'f_820', 'f_764', 'f_388', 'f_518'], ['f_392', 'f_398', 'f_427', 'f_622', 'f_752'], ['f_339', 'f_429', 'f_750', 'f_131', 'f_778'], ['f_287', 'f_195', 'f_167', 'f_129', 'f_46'], ['f_14', 'f_827', 'f_728', 'f_407', 'f_715'], ['f_516', 'f_298', 'f_676', 'f_30', 'f_394'], ['f_696', 'f_474', 'f_813', 'f_207', 'f_522'], ['f_440', 'f_496', 'f_505', 'f_343', 'f_770'], ['f_451', 'f_839', 'f_740', 'f_471', 'f_477'], ['f_393', 'f_242', 'f_568', 'f_653', 'f_461'], ['f_566', 'f_833', 'f_483', 'f_116', 'f_551'], ['f_656', 'f_647', 'f_347', 'f_361', 'f_763'], ['f_37', 'f_159', 'f_132', 'f_575', 'f_419'], ['f_186', 'f_411', 'f_513', 'f_812', 'f_494'], ['f_643', 'f_230', 'f_486', 'f_543', 'f_314'], ['f_617', 'f_759', 'f_508', 'f_742', 'f_456'], ['f_185', 'f_425', 'f_454', 'f_422', 'f_488'], ['f_681', 'f_216', 'f_475', 'f_717', 'f_694'], ['f_143', 'f_738', 'f_558', 'f_721', 'f_115'], ['f_391', 'f_860', 'f_625', 'f_559', 'f_644'], ['f_338', 'f_822', 'f_805', 'f_359', 'f_144'], ['f_390', 'f_803', 'f_473', 'f_215', 'f_160'], ['f_12', 'f_423', 'f_801', 'f_784', 'f_200'], ['f_712', 'f_489', 'f_826', 'f_38', 'f_363'], ['f_146', 'f_588', 'f_780', 'f_336', 'f_367'], ['f_192', 'f_480', 'f_517', 'f_687', 'f_514'], ['f_24', 'f_22', 'f_213', 'f_227', 'f_621'], ['f_405', 'f_467', 'f_206', 'f_395', 'f_465'], ['f_613', 'f_610', 'f_364', 'f_301', 'f_400'], ['f_637', 'f_421', 'f_515', 'f_250', 'f_399'], ['f_181', 'f_157', 'f_457', 'f_605', 'f_713'], ['f_285', 'f_661', 'f_652', 'f_17', 'f_500'], ['f_686', 'f_378', 'f_658', 'f_711', 'f_300'], ['f_462', 'f_547', 'f_305', 'f_761', 'f_716'], ['f_340', 'f_334', 'f_34', 'f_260', 'f_630'], ['f_659', 'f_414', 'f_249', 'f_397', 'f_187'], ['f_537', 'f_499', 'f_532', 'f_544', 'f_734'], ['f_663', 'f_435', 'f_707', 'f_531', 'f_563'], ['f_443', 'f_601', 'f_590', 'f_458', 'f_612'], ['f_335', 'f_503', 'f_624', 'f_824', 'f_586'], ['f_332', 'f_527', 'f_700', 'f_598', 'f_737'], ['f_341', 'f_459', 'f_152', 'f_251', 'f_362'], ['f_528', 'f_337', 'f_438', 'f_501', 'f_800'], ['f_535', 'f_383', 'f_386', 'f_701', 'f_342'], ['f_569', 'f_705', 'f_779', 'f_188', 'f_349'], ['f_611', 'f_819', 'f_673', 'f_385', 'f_591'], ['f_257', 'f_776', 'f_703', 'f_485', 'f_550'], ['f_540', 'f_756', 'f_294', 'f_153', 'f_432'], ['f_579', 'f_572', 'f_735', 'f_412', 'f_615'], ['f_698', 'f_389', 'f_507', 'f_755', 'f_685'], ['f_567', 'f_372', 'f_623', 'f_368', 'f_193'], ['f_592', 'f_693', 'f_243', 'f_632', 'f_353'], ['f_33', 'f_798', 'f_504', 'f_695', 'f_620'], ['f_667', 'f_373', 'f_662', 'f_293', 'f_797'], ['f_10', 'f_13', 'f_493', 'f_690', 'f_758'], ['f_684', 'f_484', 'f_199', 'f_565', 'f_21'], ['f_683', 'f_581', 'f_818', 'f_379', 'f_589'], ['f_638', 'f_241', 'f_597', 'f_596', 'f_714'], ['f_439', 'f_248', 'f_150', 'f_626', 'f_445'], ['f_180', 'f_642', 'f_821', 'f_699', 'f_519'], ['f_692', 'f_674', 'f_476', 'f_577', 'f_536'], ['f_646', 'f_604', 'f_487', 'f_671', 'f_261'], ['f_464', 'f_777', 'f_602', 'f_244', 'f_636'], ['f_689', 'f_560', 'f_580', 'f_702', 'f_576'], ['f_682', 'f_553', 'f_491', 'f_542', 'f_593'], ['f_645', 'f_666', 'f_450', 'f_691', 'f_704'], ['f_345', 'f_258', 'f_594', 'f_654', 'f_382'], ['f_16', 'f_606', 'f_447', 'f_688', 'f_377'], ['f_680', 'f_521', 'f_375', 'f_651', 'f_600'], ['f_573', 'f_530', 'f_145', 'f_9', 'f_541'], ['f_18', 'f_357', 'f_381', 'f_546', 'f_259'], ['f_286', 'f_539', 'f_498', 'f_628', 'f_431'], ['f_619', 'f_472', 'f_283', 'f_502', 'f_655'], ['f_365', 'f_523', 'f_641', 'f_665', 'f_574'], ['f_1', 'f_482', 'f_548', 'f_633', 'f_555'], ['f_333', 'f_506', 'f_437', 'f_352', 'f_453'], ['f_351', 'f_403', 'f_709', 'f_585', 'f_538'], ['f_430', 'f_396', 'f_549', 'f_0', 'f_387'], ['f_708', 'f_358', 'f_657', 'f_344', 'f_418'], ['f_710', 'f_442', 'f_495', 'f_284', 'f_256'], ['f_599', 'f_545', 'f_356', 'f_449', 'f_679'], ['f_607', 'f_582', 'f_376', 'f_179', 'f_446'], ['f_434', 'f_255', 'f_178', 'f_618', 'f_416'], ['f_564', 'f_441', 'f_371', 'f_556', 'f_355'], ['f_664', 'f_490', 'f_370', 'f_640', 'f_384'], ['f_678', 'f_570', 'f_578', 'f_524', 'f_603'], ['f_520', 'f_660', 'f_584', 'f_595', 'f_552'], ['f_668', 'f_677', 'f_608', 'f_470', 'f_634']]
XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5700332, HammingLoss: 0.27652, SubsetAccuracy: 0.42424,
pruning: False, include_original_features: with_org, averageAUROC: 0.6121039, HammingLoss: 0.29167, SubsetAccuracy: 0.31818,
pruning: True, include_original_features: no_org, averageAUROC: 0.57443, HammingLoss: 0.27904, SubsetAccuracy: 0.41667,
pruning: False, include_original_features: no_org, averageAUROC: 0.5970197, HammingLoss: 0.31187, SubsetAccuracy: 0.2803,

Fold 5/10 (fingerprint_frequent 9/9)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:28<00:00,  6.13feat/s]

XofN_groups: [['f_374', 'f_768', 'f_31', 'f_202', 'f_834'], ['f_20', 'f_729', 'f_629', 'f_194', 'f_510'], ['f_23', 'f_413', 'f_631', 'f_118', 'f_635'], ['f_308', 'f_616', 'f_789', 'f_785', 'f_27'], ['f_639', 'f_427', 'f_830', 'f_131', 'f_429'], ['f_366', 'f_831', 'f_428', 'f_466', 'f_670'], ['f_346', 'f_726', 'f_568', 'f_460', 'f_799'], ['f_672', 'f_845', 'f_292', 'f_767', 'f_43'], ['f_37', 'f_782', 'f_35', 'f_330', 'f_866'], ['f_287', 'f_408', 'f_166', 'f_47', 'f_529'], ['f_516', 'f_350', 'f_771', 'f_26', 'f_151'], ['f_571', 'f_736', 'f_526', 'f_676', 'f_509'], ['f_452', 'f_25', 'f_650', 'f_722', 'f_327'], ['f_380', 'f_820', 'f_587', 'f_792', 'f_262'], ['f_3', 'f_836', 'f_511', 'f_409', 'f_328'], ['f_440', 'f_791', 'f_388', 'f_725', 'f_773'], ['f_406', 'f_778', 'f_815', 'f_214', 'f_297'], ['f_19', 'f_675', 'f_583', 'f_436', 'f_417'], ['f_299', 'f_861', 'f_554', 'f_229', 'f_764'], ['f_405', 'f_788', 'f_749', 'f_167', 'f_752'], ['f_15', 'f_840', 'f_719', 'f_505', 'f_757'], ['f_393', 'f_622', 'f_839', 'f_486', 'f_715'], ['f_11', 'f_497', 'f_448', 'f_706', 'f_728'], ['f_614', 'f_508', 'f_477', 'f_164', 'f_46'], ['f_696', 'f_474', 'f_298', 'f_407', 'f_394'], ['f_335', 'f_644', 'f_833', 'f_471', 'f_827'], ['f_697', 'f_813', 'f_812', 'f_473', 'f_207'], ['f_617', 'f_750', 'f_455', 'f_522', 'f_195'], ['f_338', 'f_401', 'f_770', 'f_822', 'f_483'], ['f_2', 'f_558', 'f_496', 'f_425', 'f_116'], ['f_392', 'f_361', 'f_398', 'f_763', 'f_513'], ['f_24', 'f_215', 'f_653', 'f_559', 'f_609'], ['f_339', 'f_419', 'f_216', 'f_533', 'f_740'], ['f_12', 'f_518', 'f_551', 'f_543', 'f_132'], ['f_143', 'f_738', 'f_343', 'f_721', 'f_129'], ['f_712', 'f_494', 'f_475', 'f_30', 'f_588'], ['f_186', 'f_461', 'f_115', 'f_625', 'f_314'], ['f_566', 'f_242', 'f_647', 'f_759', 'f_742'], ['f_391', 'f_347', 'f_454', 'f_860', 'f_717'], ['f_420', 'f_456', 'f_467', 'f_230', 'f_488'], ['f_643', 'f_422', 'f_411', 'f_826', 'f_780'], ['f_146', 'f_801', 'f_514', 'f_784', 'f_144'], ['f_686', 'f_489', 'f_38', 'f_187', 'f_336'], ['f_341', 'f_517', 'f_500', 'f_200', 'f_805'], ['f_192', 'f_480', 'f_363', 'f_213', 'f_687'], ['f_659', 'f_465', 'f_575', 'f_711', 'f_423'], ['f_340', 'f_803', 'f_159', 'f_364', 'f_305'], ['f_33', 'f_824', 'f_397', 'f_694', 'f_515'], ['f_535', 'f_621', 'f_367', 'f_421', 'f_737'], ['f_451', 'f_249', 'f_359', 'f_457', 'f_160'], ['f_528', 'f_630', 'f_300', 'f_337', 'f_395'], ['f_681', 'f_414', 'f_301', 'f_17', 'f_707'], ['f_569', 'f_334', 'f_458', 'f_713', 'f_761'], ['f_656', 'f_610', 'f_652', 'f_34', 'f_612'], ['f_185', 'f_227', 'f_22', 'f_378', 'f_716'], ['f_537', 'f_547', 'f_532', 'f_544', 'f_734'], ['f_181', 'f_157', 'f_459', 'f_605', 'f_624'], ['f_14', 'f_206', 'f_260', 'f_531', 'f_705'], ['f_663', 'f_435', 'f_658', 'f_776', 'f_503'], ['f_579', 'f_601', 'f_661', 'f_400', 'f_598'], ['f_613', 'f_563', 'f_250', 'f_152', 'f_591'], ['f_462', 'f_499', 'f_383', 'f_735', 'f_501'], ['f_443', 'f_251', 'f_527', 'f_362', 'f_701'], ['f_390', 'f_700', 'f_399', 'f_550', 'f_586'], ['f_540', 'f_693', 'f_779', 'f_188', 'f_349'], ['f_21', 'f_438', 'f_342', 'f_800', 'f_412'], ['f_257', 'f_703', 'f_485', 'f_432', 'f_507'], ['f_667', 'f_294', 'f_243', 'f_662', 'f_368'], ['f_18', 'f_385', 'f_673', 'f_590', 'f_615'], ['f_567', 'f_372', 'f_756', 'f_293', 'f_758'], ['f_285', 'f_819', 'f_153', 'f_577', 'f_755'], ['f_464', 'f_798', 'f_685', 'f_353', 'f_620'], ['f_698', 'f_389', 'f_623', 'f_199', 'f_690'], ['f_248', 'f_504', 'f_597', 'f_13', 'f_632'], ['f_611', 'f_797', 'f_626', 'f_386', 'f_642'], ['f_638', 'f_818', 'f_484', 'f_695', 'f_589'], ['f_682', 'f_671', 'f_572', 'f_193', 'f_565'], ['f_704', 'f_379', 'f_476', 'f_821', 'f_150'], ['f_180', 'f_581', 'f_714', 'f_487', 'f_553'], ['f_439', 'f_699', 'f_596', 'f_244', 'f_493'], ['f_692', 'f_674', 'f_604', 'f_445', 'f_602'], ['f_345', 'f_261', 'f_777', 'f_580', 'f_636'], ['f_684', 'f_519', 'f_594', 'f_702', 'f_576'], ['f_637', 'f_491', 'f_536', 'f_377', 'f_666'], ['f_332', 'f_258', 'f_691', 'f_646', 'f_241'], ['f_645', 'f_542', 'f_521', 'f_450', 'f_689'], ['f_10', 'f_373', 'f_382', 'f_593', 'f_560'], ['f_333', 'f_447', 'f_651', 'f_654', 'f_600'], ['f_365', 'f_530', 'f_606', 'f_375', 'f_145'], ['f_641', 'f_357', 'f_16', 'f_633', 'f_541'], ['f_573', 'f_472', 'f_9', 'f_259', 'f_381'], ['f_430', 'f_506', 'f_498', 'f_502', 'f_680'], ['f_683', 'f_431', 'f_655', 'f_546', 'f_286'], ['f_619', 'f_482', 'f_283', 'f_665', 'f_555'], ['f_592', 'f_523', 'f_574', 'f_539', 'f_352'], ['f_688', 'f_403', 'f_548', 'f_437', 'f_628'], ['f_549', 'f_396', 'f_709', 'f_0', 'f_538'], ['f_1', 'f_387', 'f_607', 'f_453', 'f_710'], ['f_351', 'f_358', 'f_179', 'f_657', 'f_256'], ['f_599', 'f_442', 'f_585', 'f_708', 'f_418'], ['f_679', 'f_495', 'f_356', 'f_449', 'f_284'], ['f_434', 'f_545', 'f_344', 'f_376', 'f_371'], ['f_446', 'f_618', 'f_178', 'f_582', 'f_370'], ['f_520', 'f_416', 'f_603', 'f_441', 'f_255'], ['f_564', 'f_556', 'f_355', 'f_640', 'f_578'], ['f_664', 'f_490', 'f_384', 'f_524', 'f_677'], ['f_660', 'f_570', 'f_584', 'f_678', 'f_552'], ['f_668', 'f_470', 'f_595', 'f_608', 'f_634']]
XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.555592, HammingLoss: 0.22854, SubsetAccuracy: 0.53788,
pruning: False, include_original_features: with_org, averageAUROC: 0.5970512, HammingLoss: 0.27399, SubsetAccuracy: 0.37121,
pruning: True, include_original_features: no_org, averageAUROC: 0.5457644, HammingLoss: 0.22601, SubsetAccuracy: 0.52273,
pruning: False, include_original_features: no_org, averageAUROC: 0.5849937, HammingLoss: 0.28788, SubsetAccuracy: 0.37879,

Fold 6/10 (fingerprint_frequent 9/9)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:27<00:00,  6.16feat/s]

XofN_groups: [['f_374', 'f_31', 'f_768', 'f_529', 'f_194'], ['f_20', 'f_792', 'f_629', 'f_428', 'f_510'], ['f_308', 'f_616', 'f_789', 'f_409', 'f_25'], ['f_24', 'f_631', 'f_413', 'f_407', 'f_151'], ['f_346', 'f_726', 'f_749', 'f_460', 'f_635'], ['f_366', 'f_831', 'f_836', 'f_417', 'f_466'], ['f_23', 'f_216', 'f_408', 'f_292', 'f_166'], ['f_380', 'f_830', 'f_785', 'f_328', 'f_650'], ['f_3', 'f_834', 'f_767', 'f_131', 'f_455'], ['f_420', 'f_554', 'f_497', 'f_773', 'f_118'], ['f_406', 'f_526', 'f_791', 'f_725', 'f_27'], ['f_452', 'f_729', 'f_757', 'f_722', 'f_866'], ['f_672', 'f_845', 'f_815', 'f_43', 'f_676'], ['f_299', 'f_861', 'f_583', 'f_202', 'f_327'], ['f_571', 'f_736', 'f_752', 'f_427', 'f_330'], ['f_11', 'f_587', 'f_764', 'f_436', 'f_509'], ['f_639', 'f_778', 'f_511', 'f_297', 'f_215'], ['f_287', 'f_35', 'f_653', 'f_47', 'f_799'], ['f_516', 'f_350', 'f_771', 'f_26', 'f_675'], ['f_393', 'f_840', 'f_505', 'f_229', 'f_670'], ['f_392', 'f_214', 'f_827', 'f_622', 'f_398'], ['f_15', 'f_839', 'f_719', 'f_715', 'f_262'], ['f_19', 'f_429', 'f_448', 'f_820', 'f_207'], ['f_2', 'f_788', 'f_401', 'f_298', 'f_486'], ['f_339', 'f_568', 'f_813', 'f_706', 'f_132'], ['f_440', 'f_728', 'f_388', 'f_738', 'f_46'], ['f_566', 'f_833', 'f_477', 'f_551', 'f_116'], ['f_340', 'f_361', 'f_740', 'f_763', 'f_167'], ['f_697', 'f_474', 'f_750', 'f_394', 'f_782'], ['f_656', 'f_242', 'f_518', 'f_812', 'f_625'], ['f_451', 'f_230', 'f_461', 'f_419', 'f_801'], ['f_696', 'f_508', 'f_543', 'f_343', 'f_164'], ['f_405', 'f_609', 'f_488', 'f_588', 'f_471'], ['f_338', 'f_558', 'f_770', 'f_496', 'f_195'], ['f_614', 'f_533', 'f_522', 'f_759', 'f_647'], ['f_686', 'f_378', 'f_129', 'f_780', 'f_456'], ['f_617', 'f_454', 'f_422', 'f_30', 'f_513'], ['f_14', 'f_860', 'f_159', 'f_644', 'f_803'], ['f_146', 'f_575', 'f_115', 'f_822', 'f_483'], ['f_192', 'f_473', 'f_314', 'f_213', 'f_494'], ['f_143', 'f_347', 'f_717', 'f_742', 'f_514'], ['f_643', 'f_397', 'f_826', 'f_144', 'f_721'], ['f_341', 'f_475', 'f_38', 'f_160', 'f_336'], ['f_12', 'f_423', 'f_411', 'f_784', 'f_200'], ['f_37', 'f_527', 'f_395', 'f_425', 'f_605'], ['f_285', 'f_367', 'f_467', 'f_559', 'f_652'], ['f_712', 'f_489', 'f_22', 'f_805', 'f_515'], ['f_391', 'f_465', 'f_610', 'f_694', 'f_364'], ['f_443', 'f_517', 'f_630', 'f_500', 'f_687'], ['f_659', 'f_363', 'f_305', 'f_711', 'f_359'], ['f_33', 'f_707', 'f_713', 'f_621', 'f_337'], ['f_390', 'f_661', 'f_480', 'f_716', 'f_187'], ['f_681', 'f_414', 'f_17', 'f_301', 'f_779'], ['f_535', 'f_457', 'f_206', 'f_300', 'f_421'], ['f_663', 'f_435', 'f_658', 'f_334', 'f_624'], ['f_185', 'f_157', 'f_227', 'f_458', 'f_734'], ['f_332', 'f_260', 'f_761', 'f_34', 'f_737'], ['f_335', 'f_601', 'f_532', 'f_563', 'f_400'], ['f_540', 'f_705', 'f_399', 'f_503', 'f_612'], ['f_186', 'f_673', 'f_349', 'f_544', 'f_598'], ['f_579', 'f_459', 'f_824', 'f_485', 'f_591'], ['f_181', 'f_152', 'f_249', 'f_501', 'f_531'], ['f_528', 'f_776', 'f_362', 'f_188', 'f_499'], ['f_613', 'f_700', 'f_550', 'f_243', 'f_590'], ['f_698', 'f_438', 'f_586', 'f_800', 'f_342'], ['f_365', 'f_537', 'f_547', 'f_383', 'f_735'], ['f_569', 'f_701', 'f_385', 'f_294', 'f_432'], ['f_638', 'f_250', 'f_412', 'f_462', 'f_685'], ['f_667', 'f_615', 'f_251', 'f_372', 'f_693'], ['f_345', 'f_756', 'f_153', 'f_507', 'f_758'], ['f_439', 'f_819', 'f_572', 'f_577', 'f_703'], ['f_567', 'f_368', 'f_821', 'f_623', 'f_389'], ['f_553', 'f_386', 'f_632', 'f_21', 'f_755'], ['f_18', 'f_261', 'f_620', 'f_690', 'f_353'], ['f_637', 'f_504', 'f_199', 'f_293', 'f_493'], ['f_699', 'f_450', 'f_597', 'f_13', 'f_662'], ['f_10', 'f_193', 'f_484', 'f_581', 'f_565'], ['f_333', 'f_596', 'f_798', 'f_695', 'f_642'], ['f_611', 'f_797', 'f_626', 'f_445', 'f_150'], ['f_684', 'f_379', 'f_589', 'f_818', 'f_602'], ['f_683', 'f_714', 'f_674', 'f_671', 'f_244'], ['f_257', 'f_702', 'f_536', 'f_248', 'f_636'], ['f_689', 'f_519', 'f_580', 'f_476', 'f_241'], ['f_692', 'f_487', 'f_604', 'f_258', 'f_646'], ['f_573', 'f_491', 'f_645', 'f_777', 'f_682'], ['f_704', 'f_373', 'f_666', 'f_691', 'f_375'], ['f_180', 'f_542', 'f_145', 'f_377', 'f_447'], ['f_592', 'f_521', 'f_594', 'f_593', 'f_382'], ['f_430', 'f_654', 'f_651', 'f_576', 'f_16'], ['f_641', 'f_560', 'f_530', 'f_688', 'f_546'], ['f_351', 'f_259', 'f_606', 'f_539', 'f_680'], ['f_464', 'f_541', 'f_357', 'f_286', 'f_555'], ['f_1', 'f_431', 'f_381', 'f_600', 'f_403'], ['f_352', 'f_482', 'f_498', 'f_633', 'f_453'], ['f_549', 'f_619', 'f_506', 'f_9', 'f_655'], ['f_709', 'f_472', 'f_574', 'f_502', 'f_523'], ['f_284', 'f_396', 'f_548', 'f_665', 'f_538'], ['f_599', 'f_387', 'f_628', 'f_283', 'f_418'], ['f_708', 'f_358', 'f_437', 'f_0', 'f_256'], ['f_679', 'f_442', 'f_657', 'f_356', 'f_344'], ['f_178', 'f_585', 'f_710', 'f_449', 'f_607'], ['f_434', 'f_495', 'f_582', 'f_545', 'f_179'], ['f_446', 'f_376', 'f_618', 'f_441', 'f_371'], ['f_416', 'f_578', 'f_370', 'f_640', 'f_255'], ['f_664', 'f_556', 'f_355', 'f_660', 'f_384'], ['f_564', 'f_490', 'f_603', 'f_524', 'f_595'], ['f_570', 'f_678', 'f_584', 'f_552', 'f_608'], ['f_520', 'f_668', 'f_677', 'f_634', 'f_470']]
XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5, HammingLoss: 0.24369, SubsetAccuracy: 0.49242,
pruning: False, include_original_features: with_org, averageAUROC: 0.5833059, HammingLoss: 0.29167, SubsetAccuracy: 0.33333,
pruning: True, include_original_features: no_org, averageAUROC: 0.5486108, HammingLoss: 0.26136, SubsetAccuracy: 0.47727,
pruning: False, include_original_features: no_org, averageAUROC: 0.5938374, HammingLoss: 0.29545, SubsetAccuracy: 0.35606,

Fold 7/10 (fingerprint_frequent 9/9)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:27<00:00,  6.16feat/s]

XofN_groups: [['f_374', 'f_726', 'f_834', 'f_25', 'f_194'], ['f_20', 'f_792', 'f_629', 'f_635', 'f_214'], ['f_23', 'f_408', 'f_413', 'f_118', 'f_836'], ['f_366', 'f_789', 'f_428', 'f_616', 'f_297'], ['f_308', 'f_791', 'f_768', 'f_785', 'f_27'], ['f_516', 'f_31', 'f_47', 'f_831', 'f_771'], ['f_346', 'f_788', 'f_460', 'f_749', 'f_511'], ['f_672', 'f_292', 'f_845', 'f_830', 'f_43'], ['f_571', 'f_799', 'f_773', 'f_728', 'f_429'], ['f_639', 'f_778', 'f_166', 'f_417', 'f_508'], ['f_406', 'f_529', 'f_725', 'f_26', 'f_328'], ['f_19', 'f_510', 'f_526', 'f_151', 'f_327'], ['f_287', 'f_631', 'f_35', 'f_736', 'f_330'], ['f_24', 'f_407', 'f_215', 'f_195', 'f_509'], ['f_440', 'f_757', 'f_722', 'f_518', 'f_866'], ['f_3', 'f_131', 'f_729', 'f_401', 'f_46'], ['f_452', 'f_820', 'f_587', 'f_676', 'f_719'], ['f_420', 'f_554', 'f_767', 'f_497', 'f_764'], ['f_15', 'f_861', 'f_782', 'f_583', 'f_675'], ['f_37', 'f_670', 'f_229', 'f_475', 'f_167'], ['f_380', 'f_477', 'f_650', 'f_505', 'f_706'], ['f_656', 'f_427', 'f_436', 'f_202', 'f_350'], ['f_299', 'f_840', 'f_815', 'f_262', 'f_715'], ['f_614', 'f_568', 'f_164', 'f_298', 'f_132'], ['f_451', 'f_839', 'f_752', 'f_622', 'f_812'], ['f_338', 'f_455', 'f_813', 'f_551', 'f_486'], ['f_393', 'f_242', 'f_466', 'f_471', 'f_448'], ['f_2', 'f_409', 'f_394', 'f_474', 'f_759'], ['f_340', 'f_827', 'f_763', 'f_513', 'f_30'], ['f_566', 'f_833', 'f_116', 'f_483', 'f_822'], ['f_11', 'f_207', 'f_343', 'f_388', 'f_522'], ['f_391', 'f_653', 'f_361', 'f_473', 'f_419'], ['f_696', 'f_750', 'f_411', 'f_454', 'f_496'], ['f_617', 'f_644', 'f_770', 'f_533', 'f_115'], ['f_339', 'f_489', 'f_398', 'f_738', 'f_159'], ['f_643', 'f_230', 'f_461', 'f_740', 'f_647'], ['f_186', 'f_129', 'f_609', 'f_543', 'f_347'], ['f_392', 'f_860', 'f_467', 'f_314', 'f_625'], ['f_405', 'f_588', 'f_488', 'f_336', 'f_717'], ['f_14', 'f_144', 'f_160', 'f_721', 'f_425'], ['f_697', 'f_494', 'f_456', 'f_742', 'f_34'], ['f_686', 'f_780', 'f_359', 'f_558', 'f_227'], ['f_12', 'f_423', 'f_801', 'f_784', 'f_559'], ['f_146', 'f_575', 'f_216', 'f_363', 'f_826'], ['f_335', 'f_422', 'f_514', 'f_805', 'f_480'], ['f_659', 'f_465', 'f_711', 'f_38', 'f_364'], ['f_663', 'f_414', 'f_213', 'f_694', 'f_517'], ['f_143', 'f_367', 'f_187', 'f_716', 'f_395'], ['f_681', 'f_457', 'f_17', 'f_301', 'f_707'], ['f_528', 'f_337', 'f_652', 'f_397', 'f_421'], ['f_535', 'f_621', 'f_200', 'f_500', 'f_515'], ['f_185', 'f_157', 'f_803', 'f_305', 'f_612'], ['f_712', 'f_378', 'f_22', 'f_658', 'f_300'], ['f_567', 'f_527', 'f_532', 'f_713', 'f_334'], ['f_181', 'f_687', 'f_605', 'f_458', 'f_737'], ['f_257', 'f_610', 'f_779', 'f_349', 'f_624'], ['f_683', 'f_661', 'f_260', 'f_459', 'f_249'], ['f_390', 'f_563', 'f_250', 'f_152', 'f_503'], ['f_341', 'f_601', 'f_206', 'f_531', 'f_800'], ['f_684', 'f_383', 'f_630', 'f_485', 'f_734'], ['f_698', 'f_438', 'f_586', 'f_761', 'f_598'], ['f_192', 'f_368', 'f_673', 'f_544', 'f_501'], ['f_33', 'f_824', 'f_499', 'f_462', 'f_362'], ['f_569', 'f_705', 'f_399', 'f_251', 'f_591'], ['f_443', 'f_400', 'f_550', 'f_700', 'f_507'], ['f_285', 'f_537', 'f_547', 'f_756', 'f_188'], ['f_667', 'f_243', 'f_342', 'f_662', 'f_412'], ['f_638', 'f_776', 'f_294', 'f_386', 'f_293'], ['f_579', 'f_572', 'f_735', 'f_615', 'f_577'], ['f_540', 'f_693', 'f_385', 'f_153', 'f_703'], ['f_439', 'f_701', 'f_504', 'f_432', 'f_353'], ['f_637', 'f_389', 'f_755', 'f_685', 'f_620'], ['f_18', 'f_261', 'f_819', 'f_435', 'f_690'], ['f_464', 'f_590', 'f_632', 'f_150', 'f_818'], ['f_704', 'f_484', 'f_798', 'f_758', 'f_21'], ['f_248', 'f_379', 'f_597', 'f_13', 'f_691'], ['f_553', 'f_193', 'f_596', 'f_626', 'f_536'], ['f_699', 'f_450', 'f_623', 'f_199', 'f_372'], ['f_613', 'f_797', 'f_674', 'f_642', 'f_589'], ['f_611', 'f_777', 'f_493', 'f_821', 'f_445'], ['f_671', 'f_702', 'f_491', 'f_714', 'f_581'], ['f_692', 'f_519', 'f_565', 'f_580', 'f_244'], ['f_16', 'f_476', 'f_695', 'f_241', 'f_373'], ['f_345', 'f_258', 'f_602', 'f_604', 'f_636'], ['f_365', 'f_576', 'f_682', 'f_594', 'f_593'], ['f_645', 'f_666', 'f_487', 'f_530', 'f_689'], ['f_332', 'f_447', 'f_542', 'f_646', 'f_377'], ['f_688', 'f_560', 'f_382', 'f_357', 'f_180'], ['f_680', 'f_521', 'f_600', 'f_375', 'f_651'], ['f_1', 'f_259', 'f_606', 'f_654', 'f_431'], ['f_592', 'f_482', 'f_541', 'f_145', 'f_641'], ['f_351', 'f_523', 'f_381', 'f_546', 'f_655'], ['f_573', 'f_472', 'f_633', 'f_286', 'f_498'], ['f_10', 'f_506', 'f_574', 'f_502', 'f_555'], ['f_619', 'f_403', 'f_9', 'f_665', 'f_539'], ['f_549', 'f_548', 'f_396', 'f_352', 'f_538'], ['f_628', 'f_283', 'f_387', 'f_709', 'f_453'], ['f_333', 'f_358', 'f_437', 'f_0', 'f_256'], ['f_430', 'f_442', 'f_585', 'f_344', 'f_607'], ['f_708', 'f_418', 'f_657', 'f_284', 'f_356'], ['f_599', 'f_495', 'f_710', 'f_449', 'f_545'], ['f_679', 'f_376', 'f_371', 'f_178', 'f_446'], ['f_434', 'f_255', 'f_582', 'f_179', 'f_370'], ['f_618', 'f_416', 'f_678', 'f_355', 'f_441'], ['f_664', 'f_490', 'f_384', 'f_524', 'f_578'], ['f_564', 'f_556', 'f_603', 'f_640', 'f_570'], ['f_520', 'f_660', 'f_595', 'f_677', 'f_552'], ['f_668', 'f_584', 'f_608', 'f_470', 'f_634']]
XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5606366, HammingLoss: 0.21883, SubsetAccuracy: 0.53435,
pruning: False, include_original_features: with_org, averageAUROC: 0.5890759, HammingLoss: 0.27608, SubsetAccuracy: 0.41221,
pruning: True, include_original_features: no_org, averageAUROC: 0.5923394, HammingLoss: 0.21374, SubsetAccuracy: 0.53435,
pruning: False, include_original_features: no_org, averageAUROC: 0.5967089, HammingLoss: 0.29008, SubsetAccuracy: 0.37405,

Fold 8/10 (fingerprint_frequent 9/9)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:28<00:00,  6.12feat/s]

XofN_groups: [['f_374', 'f_831', 'f_27', 'f_771', 'f_675'], ['f_20', 'f_792', 'f_629', 'f_328', 'f_194'], ['f_308', 'f_616', 'f_785', 'f_726', 'f_327'], ['f_299', 'f_866', 'f_31', 'f_214', 'f_622'], ['f_366', 'f_789', 'f_428', 'f_635', 'f_297'], ['f_23', 'f_413', 'f_631', 'f_118', 'f_47'], ['f_516', 'f_350', 'f_587', 'f_202', 'f_768'], ['f_24', 'f_46', 'f_408', 'f_215', 'f_151'], ['f_406', 'f_791', 'f_836', 'f_26', 'f_788'], ['f_3', 'f_409', 'f_834', 'f_330', 'f_830'], ['f_571', 'f_736', 'f_529', 'f_554', 'f_429'], ['f_672', 'f_292', 'f_845', 'f_767', 'f_298'], ['f_19', 'f_670', 'f_510', 'f_773', 'f_460'], ['f_393', 'f_861', 'f_526', 'f_229', 'f_497'], ['f_639', 'f_417', 'f_750', 'f_511', 'f_568'], ['f_15', 'f_839', 'f_719', 'f_509', 'f_764'], ['f_452', 'f_25', 'f_722', 'f_757', 'f_43'], ['f_287', 'f_35', 'f_799', 'f_740', 'f_609'], ['f_346', 'f_725', 'f_749', 'f_427', 'f_455'], ['f_380', 'f_729', 'f_820', 'f_401', 'f_436'], ['f_440', 'f_728', 'f_813', 'f_388', 'f_715'], ['f_37', 'f_782', 'f_475', 'f_164', 'f_778'], ['f_392', 'f_840', 'f_815', 'f_262', 'f_653'], ['f_614', 'f_166', 'f_466', 'f_131', 'f_361'], ['f_339', 'f_676', 'f_477', 'f_454', 'f_448'], ['f_697', 'f_474', 'f_752', 'f_812', 'f_407'], ['f_617', 'f_644', 'f_583', 'f_833', 'f_471'], ['f_451', 'f_242', 'f_505', 'f_763', 'f_167'], ['f_566', 'f_770', 'f_343', 'f_116', 'f_394'], ['f_338', 'f_558', 'f_827', 'f_486', 'f_30'], ['f_186', 'f_473', 'f_650', 'f_551', 'f_398'], ['f_12', 'f_518', 'f_508', 'f_543', 'f_207'], ['f_659', 'f_706', 'f_522', 'f_115', 'f_822'], ['f_2', 'f_759', 'f_647', 'f_826', 'f_195'], ['f_340', 'f_860', 'f_625', 'f_496', 'f_159'], ['f_391', 'f_483', 'f_347', 'f_419', 'f_721'], ['f_420', 'f_461', 'f_230', 'f_533', 'f_425'], ['f_335', 'f_467', 'f_513', 'f_314', 'f_742'], ['f_405', 'f_588', 'f_488', 'f_717', 'f_456'], ['f_185', 'f_132', 'f_494', 'f_411', 'f_805'], ['f_712', 'f_489', 'f_38', 'f_160', 'f_364'], ['f_681', 'f_465', 'f_216', 'f_422', 'f_694'], ['f_656', 'f_367', 'f_423', 'f_144', 'f_738'], ['f_192', 'f_129', 'f_414', 'f_801', 'f_336'], ['f_14', 'f_803', 'f_517', 'f_780', 'f_514'], ['f_535', 'f_363', 'f_559', 'f_213', 'f_621'], ['f_146', 'f_575', 'f_305', 'f_711', 'f_784'], ['f_341', 'f_359', 'f_687', 'f_227', 'f_457'], ['f_528', 'f_630', 'f_397', 'f_337', 'f_532'], ['f_643', 'f_334', 'f_515', 'f_480', 'f_22'], ['f_686', 'f_378', 'f_500', 'f_200', 'f_300'], ['f_285', 'f_610', 'f_421', 'f_652', 'f_17'], ['f_696', 'f_395', 'f_260', 'f_206', 'f_458'], ['f_143', 'f_250', 'f_713', 'f_301', 'f_157'], ['f_33', 'f_707', 'f_661', 'f_187', 'f_590'], ['f_537', 'f_547', 'f_459', 'f_761', 'f_734'], ['f_443', 'f_601', 'f_34', 'f_249', 'f_503'], ['f_540', 'f_605', 'f_624', 'f_400', 'f_598'], ['f_567', 'f_527', 'f_362', 'f_658', 'f_737'], ['f_613', 'f_563', 'f_716', 'f_544', 'f_531'], ['f_181', 'f_152', 'f_705', 'f_501', 'f_612'], ['f_663', 'f_435', 'f_383', 'f_776', 'f_673'], ['f_257', 'f_462', 'f_349', 'f_779', 'f_188'], ['f_345', 'f_700', 'f_399', 'f_591', 'f_800'], ['f_684', 'f_438', 'f_824', 'f_586', 'f_550'], ['f_569', 'f_701', 'f_385', 'f_342', 'f_412'], ['f_390', 'f_756', 'f_485', 'f_294', 'f_251'], ['f_667', 'f_243', 'f_662', 'f_507', 'f_432'], ['f_698', 'f_499', 'f_703', 'f_353', 'f_755'], ['f_579', 'f_572', 'f_735', 'f_615', 'f_368'], ['f_18', 'f_153', 'f_819', 'f_372', 'f_758'], ['f_637', 'f_504', 'f_199', 'f_623', 'f_293'], ['f_365', 'f_693', 'f_386', 'f_620', 'f_685'], ['f_611', 'f_798', 'f_577', 'f_632', 'f_21'], ['f_553', 'f_13', 'f_389', 'f_565', 'f_690'], ['f_248', 'f_484', 'f_597', 'f_714', 'f_150'], ['f_699', 'f_450', 'f_695', 'f_193', 'f_493'], ['f_638', 'f_818', 'f_379', 'f_821', 'f_589'], ['f_671', 'f_596', 'f_626', 'f_536', 'f_797'], ['f_332', 'f_261', 'f_581', 'f_476', 'f_674'], ['f_646', 'f_604', 'f_519', 'f_642', 'f_241'], ['f_592', 'f_777', 'f_636', 'f_244', 'f_580'], ['f_692', 'f_487', 'f_594', 'f_445', 'f_702'], ['f_375', 'f_666', 'f_602', 'f_258', 'f_704'], ['f_430', 'f_491', 'f_691', 'f_593', 'f_542'], ['f_439', 'f_382', 'f_373', 'f_377', 'f_682'], ['f_645', 'f_651', 'f_521', 'f_180', 'f_689'], ['f_619', 'f_447', 'f_16', 'f_600', 'f_688'], ['f_680', 'f_560', 'f_576', 'f_606', 'f_145'], ['f_464', 'f_541', 'f_654', 'f_357', 'f_709'], ['f_683', 'f_259', 'f_381', 'f_539', 'f_286'], ['f_1', 'f_530', 'f_498', 'f_546', 'f_431'], ['f_641', 'f_506', 'f_633', 'f_352', 'f_555'], ['f_333', 'f_472', 'f_574', 'f_502', 'f_523'], ['f_11', 'f_482', 'f_655', 'f_665', 'f_573'], ['f_351', 'f_403', 'f_548', 'f_628', 'f_710'], ['f_708', 'f_396', 'f_437', 'f_9', 'f_538'], ['f_549', 'f_344', 'f_387', 'f_356', 'f_453'], ['f_10', 'f_358', 'f_607', 'f_657', 'f_179'], ['f_284', 'f_256', 'f_585', 'f_599', 'f_442'], ['f_679', 'f_418', 'f_495', 'f_283', 'f_545'], ['f_0', 'f_376', 'f_371', 'f_449', 'f_582'], ['f_564', 'f_178', 'f_370', 'f_416', 'f_618'], ['f_434', 'f_255', 'f_603', 'f_441', 'f_446'], ['f_664', 'f_490', 'f_355', 'f_640', 'f_384'], ['f_570', 'f_660', 'f_578', 'f_556', 'f_677'], ['f_520', 'f_524', 'f_584', 'f_678', 'f_608'], ['f_470', 'f_595', 'f_634', 'f_552', 'f_668']]
XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.4951189, HammingLoss: 0.23537, SubsetAccuracy: 0.54962,
pruning: False, include_original_features: with_org, averageAUROC: 0.5463235, HammingLoss: 0.27863, SubsetAccuracy: 0.38168,
pruning: True, include_original_features: no_org, averageAUROC: 0.5010392, HammingLoss: 0.24936, SubsetAccuracy: 0.51908,
pruning: False, include_original_features: no_org, averageAUROC: 0.5693926, HammingLoss: 0.25573, SubsetAccuracy: 0.41221,

Fold 9/10 (fingerprint_frequent 9/9)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:28<00:00,  6.13feat/s]

XofN_groups: [['f_374', 'f_834', 'f_768', 'f_31', 'f_202'], ['f_20', 'f_792', 'f_629', 'f_194', 'f_635'], ['f_308', 'f_616', 'f_831', 'f_785', 'f_328'], ['f_346', 'f_726', 'f_428', 'f_799', 'f_297'], ['f_366', 'f_789', 'f_327', 'f_510', 'f_460'], ['f_516', 'f_47', 'f_413', 'f_27', 'f_771'], ['f_23', 'f_687', 'f_43', 'f_736', 'f_529'], ['f_672', 'f_292', 'f_845', 'f_830', 'f_815'], ['f_639', 'f_417', 'f_767', 'f_131', 'f_25'], ['f_440', 'f_791', 'f_788', 'f_722', 'f_118'], ['f_24', 'f_622', 'f_408', 'f_216', 'f_151'], ['f_452', 'f_757', 'f_729', 'f_866', 'f_719'], ['f_3', 'f_676', 'f_836', 'f_511', 'f_215'], ['f_697', 'f_35', 'f_725', 'f_749', 'f_436'], ['f_15', 'f_861', 'f_773', 'f_631', 'f_554'], ['f_571', 'f_526', 'f_820', 'f_454', 'f_214'], ['f_406', 'f_728', 'f_778', 'f_26', 'f_409'], ['f_380', 'f_330', 'f_587', 'f_650', 'f_764'], ['f_299', 'f_840', 'f_229', 'f_670', 'f_583'], ['f_656', 'f_706', 'f_675', 'f_782', 'f_427'], ['f_287', 'f_207', 'f_509', 'f_448', 'f_609'], ['f_393', 'f_839', 'f_752', 'f_715', 'f_262'], ['f_19', 'f_466', 'f_497', 'f_166', 'f_518'], ['f_614', 'f_508', 'f_167', 'f_46', 'f_477'], ['f_451', 'f_361', 'f_505', 'f_388', 'f_298'], ['f_37', 'f_475', 'f_230', 'f_350', 'f_407'], ['f_617', 'f_750', 'f_455', 'f_486', 'f_195'], ['f_339', 'f_429', 'f_813', 'f_132', 'f_738'], ['f_2', 'f_401', 'f_827', 'f_496', 'f_833'], ['f_11', 'f_763', 'f_551', 'f_164', 'f_474'], ['f_659', 'f_343', 'f_394', 'f_647', 'f_116'], ['f_566', 'f_770', 'f_568', 'f_483', 'f_242'], ['f_392', 'f_398', 'f_471', 'f_860', 'f_812'], ['f_185', 'f_129', 'f_419', 'f_494', 'f_653'], ['f_186', 'f_473', 'f_588', 'f_30', 'f_522'], ['f_338', 'f_558', 'f_801', 'f_721', 'f_411'], ['f_12', 'f_461', 'f_740', 'f_115', 'f_533'], ['f_391', 'f_347', 'f_543', 'f_822', 'f_159'], ['f_332', 'f_759', 'f_425', 'f_742', 'f_200'], ['f_14', 'f_625', 'f_314', 'f_717', 'f_826'], ['f_686', 'f_489', 'f_780', 'f_456', 'f_644'], ['f_420', 'f_513', 'f_422', 'f_805', 'f_22'], ['f_643', 'f_517', 'f_705', 'f_488', 'f_187'], ['f_33', 'f_803', 'f_467', 'f_336', 'f_559'], ['f_181', 'f_423', 'f_144', 'f_160', 'f_38'], ['f_192', 'f_480', 'f_514', 'f_784', 'f_213'], ['f_712', 'f_34', 'f_652', 'f_515', 'f_367'], ['f_405', 'f_17', 'f_363', 'f_305', 'f_575'], ['f_528', 'f_630', 'f_397', 'f_337', 'f_421'], ['f_535', 'f_621', 'f_227', 'f_713', 'f_364'], ['f_681', 'f_465', 'f_694', 'f_300', 'f_658'], ['f_143', 'f_250', 'f_395', 'f_734', 'f_157'], ['f_696', 'f_301', 'f_260', 'f_206', 'f_532'], ['f_613', 'f_610', 'f_414', 'f_707', 'f_359'], ['f_340', 'f_605', 'f_457', 'f_152', 'f_761'], ['f_663', 'f_435', 'f_500', 'f_711', 'f_624'], ['f_146', 'f_188', 'f_716', 'f_249', 'f_503'], ['f_611', 'f_334', 'f_458', 'f_544', 'f_612'], ['f_567', 'f_399', 'f_598', 'f_459', 'f_776'], ['f_464', 'f_563', 'f_349', 'f_756', 'f_378'], ['f_698', 'f_601', 'f_586', 'f_661', 'f_737'], ['f_443', 'f_251', 'f_400', 'f_501', 'f_701'], ['f_341', 'f_531', 'f_527', 'f_362', 'f_700'], ['f_335', 'f_438', 'f_824', 'f_412', 'f_591'], ['f_18', 'f_385', 'f_383', 'f_485', 'f_537'], ['f_390', 'f_462', 'f_499', 'f_735', 'f_507'], ['f_579', 'f_572', 'f_550', 'f_800', 'f_590'], ['f_257', 'f_703', 'f_673', 'f_368', 'f_342'], ['f_690', 'f_372', 'f_294', 'f_779', 'f_685'], ['f_345', 'f_819', 'f_547', 'f_615', 'f_758'], ['f_638', 'f_797', 'f_674', 'f_632', 'f_353'], ['f_637', 'f_504', 'f_755', 'f_293', 'f_693'], ['f_667', 'f_243', 'f_620', 'f_432', 'f_646'], ['f_285', 'f_193', 'f_389', 'f_623', 'f_662'], ['f_10', 'f_153', 'f_798', 'f_577', 'f_493'], ['f_569', 'f_699', 'f_386', 'f_597', 'f_21'], ['f_619', 'f_636', 'f_818', 'f_695', 'f_199'], ['f_248', 'f_484', 'f_13', 'f_565', 'f_536'], ['f_180', 'f_581', 'f_150', 'f_821', 'f_714'], ['f_540', 'f_261', 'f_642', 'f_589', 'f_379'], ['f_704', 'f_487', 'f_626', 'f_602', 'f_445'], ['f_592', 'f_777', 'f_596', 'f_580', 'f_244'], ['f_684', 'f_491', 'f_476', 'f_702', 'f_375'], ['f_439', 'f_604', 'f_519', 'f_241', 'f_691'], ['f_645', 'f_258', 'f_666', 'f_671', 'f_450'], ['f_365', 'f_576', 'f_682', 'f_553', 'f_542'], ['f_709', 'f_560', 'f_594', 'f_593', 'f_373'], ['f_689', 'f_654', 'f_530', 'f_382', 'f_377'], ['f_692', 'f_447', 'f_651', 'f_16', 'f_600'], ['f_333', 'f_521', 'f_606', 'f_145', 'f_665'], ['f_688', 'f_357', 'f_381', 'f_502', 'f_259'], ['f_573', 'f_431', 'f_9', 'f_546', 'f_541'], ['f_680', 'f_539', 'f_498', 'f_628', 'f_523'], ['f_641', 'f_506', 'f_633', 'f_286', 'f_555'], ['f_683', 'f_472', 'f_655', 'f_437', 'f_352'], ['f_1', 'f_482', 'f_574', 'f_549', 'f_453'], ['f_430', 'f_403', 'f_548', 'f_585', 'f_283'], ['f_351', 'f_396', 'f_710', 'f_657', 'f_538'], ['f_708', 'f_387', 'f_607', 'f_418', 'f_344'], ['f_284', 'f_358', 'f_356', 'f_495', 'f_256'], ['f_434', 'f_442', 'f_545', 'f_0', 'f_179'], ['f_679', 'f_376', 'f_599', 'f_449', 'f_371'], ['f_416', 'f_618', 'f_582', 'f_370', 'f_178'], ['f_564', 'f_441', 'f_578', 'f_446', 'f_255'], ['f_664', 'f_556', 'f_355', 'f_640', 'f_384'], ['f_570', 'f_660', 'f_603', 'f_490', 'f_524'], ['f_520', 'f_678', 'f_595', 'f_677', 'f_552'], ['f_470', 'f_608', 'f_584', 'f_634', 'f_668']]
XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.6022281, HammingLoss: 0.20738, SubsetAccuracy: 0.49618,
pruning: False, include_original_features: with_org, averageAUROC: 0.6197253, HammingLoss: 0.25445, SubsetAccuracy: 0.35115,
pruning: True, include_original_features: no_org, averageAUROC: 0.6279356, HammingLoss: 0.22392, SubsetAccuracy: 0.47328,
pruning: False, include_original_features: no_org, averageAUROC: 0.6016714, HammingLoss: 0.2888, SubsetAccuracy: 0.34351,

Fold 10/10 (fingerprint_frequent 9/9)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:27<00:00,  6.15feat/s]

XofN_groups: [['f_374', 'f_768', 'f_27', 'f_771', 'f_629'], ['f_20', 'f_792', 'f_194', 'f_497', 'f_214'], ['f_23', 'f_408', 'f_207', 'f_31', 'f_635'], ['f_366', 'f_726', 'f_428', 'f_820', 'f_510'], ['f_346', 'f_789', 'f_749', 'f_460', 'f_799'], ['f_24', 'f_815', 'f_413', 'f_43', 'f_407'], ['f_516', 'f_47', 'f_292', 'f_587', 'f_834'], ['f_308', 'f_616', 'f_831', 'f_722', 'f_25'], ['f_287', 'f_195', 'f_166', 'f_118', 'f_529'], ['f_672', 'f_845', 'f_729', 'f_297', 'f_167'], ['f_15', 'f_866', 'f_836', 'f_719', 'f_436'], ['f_639', 'f_427', 'f_830', 'f_131', 'f_330'], ['f_393', 'f_151', 'f_622', 'f_785', 'f_675'], ['f_452', 'f_757', 'f_773', 'f_518', 'f_466'], ['f_440', 'f_791', 'f_788', 'f_526', 'f_388'], ['f_571', 'f_752', 'f_736', 'f_327', 'f_511'], ['f_614', 'f_767', 'f_26', 'f_350', 'f_328'], ['f_380', 'f_554', 'f_650', 'f_813', 'f_706'], ['f_406', 'f_728', 'f_725', 'f_583', 'f_202'], ['f_299', 'f_861', 'f_764', 'f_229', 'f_670'], ['f_3', 'f_477', 'f_401', 'f_509', 'f_471'], ['f_37', 'f_782', 'f_35', 'f_417', 'f_394'], ['f_19', 'f_676', 'f_448', 'f_298', 'f_770'], ['f_186', 'f_475', 'f_46', 'f_343', 'f_715'], ['f_392', 'f_840', 'f_631', 'f_486', 'f_778'], ['f_451', 'f_839', 'f_505', 'f_262', 'f_812'], ['f_339', 'f_429', 'f_750', 'f_132', 'f_738'], ['f_11', 'f_827', 'f_763', 'f_164', 'f_474'], ['f_643', 'f_461', 'f_230', 'f_551', 'f_833'], ['f_2', 'f_455', 'f_496', 'f_456', 'f_513'], ['f_566', 'f_361', 'f_116', 'f_644', 'f_653'], ['f_617', 'f_483', 'f_568', 'f_759', 'f_30'], ['f_12', 'f_409', 'f_609', 'f_508', 'f_398'], ['f_697', 'f_473', 'f_543', 'f_647', 'f_522'], ['f_338', 'f_454', 'f_314', 'f_721', 'f_801'], ['f_14', 'f_242', 'f_740', 'f_419', 'f_559'], ['f_192', 'f_489', 'f_411', 'f_717', 'f_494'], ['f_143', 'f_588', 'f_425', 'f_780', 'f_533'], ['f_712', 'f_742', 'f_129', 'f_488', 'f_363'], ['f_405', 'f_215', 'f_159', 'f_336', 'f_465'], ['f_656', 'f_347', 'f_558', 'f_115', 'f_422'], ['f_696', 'f_480', 'f_826', 'f_517', 'f_625'], ['f_38', 'f_227', 'f_364', 'f_399', 'f_216'], ['f_185', 'f_423', 'f_784', 'f_200', 'f_421'], ['f_146', 'f_575', 'f_822', 'f_305', 'f_860'], ['f_33', 'f_803', 'f_467', 'f_144', 'f_514'], ['f_340', 'f_367', 'f_711', 'f_359', 'f_457'], ['f_686', 'f_378', 'f_213', 'f_500', 'f_334'], ['f_613', 'f_610', 'f_160', 'f_414', 'f_301'], ['f_391', 'f_458', 'f_805', 'f_687', 'f_249'], ['f_335', 'f_300', 'f_652', 'f_34', 'f_737'], ['f_698', 'f_397', 'f_532', 'f_22', 'f_716'], ['f_420', 'f_621', 'f_395', 'f_206', 'f_515'], ['f_681', 'f_383', 'f_400', 'f_713', 'f_630'], ['f_180', 'f_694', 'f_661', 'f_459', 'f_612'], ['f_257', 'f_605', 'f_624', 'f_157', 'f_658'], ['f_18', 'f_260', 'f_761', 'f_503', 'f_337'], ['f_341', 'f_187', 'f_152', 'f_598', 'f_563'], ['f_535', 'f_601', 'f_734', 'f_531', 'f_544'], ['f_443', 'f_250', 'f_527', 'f_501', 'f_701'], ['f_569', 'f_705', 'f_779', 'f_586', 'f_824'], ['f_181', 'f_17', 'f_462', 'f_707', 'f_412'], ['f_611', 'f_700', 'f_385', 'f_591', 'f_800'], ['f_579', 'f_438', 'f_590', 'f_362', 'f_507'], ['f_659', 'f_776', 'f_673', 'f_386', 'f_550'], ['f_690', 'f_435', 'f_342', 'f_349', 'f_756'], ['f_540', 'f_537', 'f_485', 'f_251', 'f_294'], ['f_663', 'f_372', 'f_432', 'f_368', 'f_615'], ['f_528', 'f_188', 'f_819', 'f_547', 'f_758'], ['f_390', 'f_693', 'f_243', 'f_755', 'f_353'], ['f_21', 'f_620', 'f_499', 'f_818', 'f_293'], ['f_638', 'f_797', 'f_674', 'f_703', 'f_623'], ['f_285', 'f_193', 'f_572', 'f_632', 'f_642'], ['f_683', 'f_735', 'f_153', 'f_493', 'f_504'], ['f_16', 'f_798', 'f_577', 'f_597', 'f_662'], ['f_567', 'f_685', 'f_445', 'f_248', 'f_536'], ['f_553', 'f_13', 'f_389', 'f_565', 'f_821'], ['f_692', 'f_484', 'f_199', 'f_626', 'f_150'], ['f_684', 'f_379', 'f_589', 'f_667', 'f_244'], ['f_332', 'f_261', 'f_581', 'f_476', 'f_636'], ['f_637', 'f_596', 'f_714', 'f_671', 'f_602'], ['f_439', 'f_699', 'f_519', 'f_695', 'f_604'], ['f_365', 'f_777', 'f_258', 'f_580', 'f_702'], ['f_464', 'f_542', 'f_487', 'f_241', 'f_691'], ['f_333', 'f_491', 'f_682', 'f_666', 'f_646'], ['f_592', 'f_373', 'f_594', 'f_704', 'f_450'], ['f_645', 'f_382', 'f_521', 'f_377', 'f_689'], ['f_345', 'f_576', 'f_651', 'f_560', 'f_593'], ['f_680', 'f_447', 'f_600', 'f_654', 'f_606'], ['f_375', 'f_541', 'f_530', 'f_688', 'f_145'], ['f_619', 'f_472', 'f_633', 'f_286', 'f_259'], ['f_430', 'f_357', 'f_381', 'f_502', 'f_555'], ['f_1', 'f_431', 'f_498', 'f_546', 'f_641'], ['f_573', 'f_506', 'f_9', 'f_665', 'f_655'], ['f_709', 'f_482', 'f_574', 'f_437', 'f_539'], ['f_0', 'f_523', 'f_548', 'f_628', 'f_403'], ['f_10', 'f_396', 'f_549', 'f_356', 'f_538'], ['f_442', 'f_179', 'f_352', 'f_585', 'f_387'], ['f_351', 'f_358', 'f_710', 'f_657', 'f_453'], ['f_679', 'f_256', 'f_545', 'f_708', 'f_418'], ['f_178', 'f_495', 'f_607', 'f_599', 'f_449'], ['f_434', 'f_376', 'f_283', 'f_618', 'f_284'], ['f_564', 'f_344', 'f_371', 'f_582', 'f_255'], ['f_660', 'f_355', 'f_446', 'f_603', 'f_416'], ['f_570', 'f_441', 'f_370', 'f_678', 'f_384'], ['f_520', 'f_556', 'f_578', 'f_524', 'f_640'], ['f_664', 'f_490', 'f_552', 'f_595', 'f_677'], ['f_668', 'f_584', 'f_608', 'f_470', 'f_634']]
XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.574455, HammingLoss: 0.24936, SubsetAccuracy: 0.48855,
pruning: False, include_original_features: with_org, averageAUROC: 0.5628788, HammingLoss: 0.29644, SubsetAccuracy: 0.38931,
pruning: True, include_original_features: no_org, averageAUROC: 0.5322692, HammingLoss: 0.24682, SubsetAccuracy: 0.49618,
pruning: False, include_original_features: no_org, averageAUROC: 0.529571, HammingLoss: 0.31425, SubsetAccuracy: 0.32061,
   pruning include_original_features               dataset  averageAUROC  \
0    False                    no_org  fingerprint_frequent      0.575128
1    False                  with_org  fingerprint_frequent      0.573193
2     True                    no_org  fingerprint_frequent      0.550990
3     True                  with_org  fingerprint_frequent      0.541951

   HammingLoss  SubsetAccuracy  nodes  leaves  groups  avg_group_features  \
0     0.286729        0.362462  608.2   304.6   108.0                 5.0
1     0.278743        0.359495  599.0   300.0   108.0                 5.0
2     0.233914        0.500773   39.6    20.3   108.0                 5.0
3     0.226448        0.512931   47.4    24.2   108.0                 5.0

   gen_XofN_time  training_time
0      87.911732       0.727399
1      87.911732       1.488730
2      87.911732       0.727399
3      87.911732       1.488730

In [4]:
# All results
save_path = "XofN_jaccard_min/"
final_grouped_res = pd.DataFrame()
for df in cv_results:
    final_grouped_res = pd.concat([final_grouped_res, df])
final_grouped_res.sort_values(by='dataset', ascending=False, inplace=True)
final_grouped_res = final_grouped_res.reset_index(drop=True)
final_grouped_res.to_csv(save_path + "all_results.csv")
final_grouped_res

,pruning,include_original_features,dataset,averageAUROC,HammingLoss,SubsetAccuracy,nodes,leaves,groups,avg_group_features,gen_XofN_time,training_time
0,True,with_org,fingerprint_frequent,0.541951,0.226448,0.512931,47.4,24.2,108.0,5.000000,87.911732,1.488730
1,True,no_org,fingerprint_frequent,0.550990,0.233914,0.500773,39.6,20.3,108.0,5.000000,87.911732,0.727399
2,False,with_org,fingerprint_frequent,0.573193,0.278743,0.359495,599.0,300.0,108.0,5.000000,87.911732,1.488730
3,False,no_org,fingerprint_frequent,0.575128,0.286729,0.362462,608.2,304.6,108.0,5.000000,87.911732,0.727399
4,True,no_org,fingerprint_diverse,0.500000,0.181567,0.425757,1.0,1.0,108.0,5.000000,87.787998,0.743740
5,False,with_org,fingerprint_diverse,0.567529,0.268308,0.229548,777.8,389.4,108.0,5.000000,87.787998,1.584081
6,False,no_org,fingerprint_diverse,0.562458,0.276895,0.227272,805.4,403.2,108.0,5.000000,87.787998,0.743740
7,True,with_org,fingerprint_diverse,0.516977,0.178788,0.437122,3.6,2.3,108.0,5.000000,87.787998,1.584081
8,True,with_org,fingerprint_all,0.514791,0.198918,0.110685,3.2,2.1,108.0,5.000000,87.712154,1.635671
9,True,no_org,fingerprint_all,0.500000,0.200827,0.104580,1.2,1.1,108.0,5.000000,87.712154,0.745348
10,False,with_org,fingerprint_all,0.570005,0.271311,0.064886,974.2,487.6,108.0,5.000000,87.712154,1.635671
11,False,no_org,fingerprint_all,0.562382,0.283841,0.044275,972.4,486.7,108.0,5.000000,87.712154,0.745348
12,True,with_org,CPI_frequent,0.538310,0.214506,0.538956,19.2,10.1,322.0,4.990683,411.835599,2.906324
13,True,no_org,CPI_frequent,0.507533,0.213889,0.543469,12.0,6.5,322.0,4.990683,411.835599,0.934451
14,False,with_org,CPI_frequent,0.566920,0.264664,0.402420,459.8,230.4,322.0,4.990683,411.835599,2.906324
15,False,no_org,CPI_frequent,0.556542,0.271693,0.379971,449.2,225.1,322.0,4.990683,411.835599,0.934451
16,True,with_org,CPI_diverse,0.558623,0.194753,0.400521,14.0,7.5,322.0,4.990683,411.112626,3.042623
17,True,no_org,CPI_diverse,0.531266,0.191628,0.406757,6.6,3.8,322.0,4.990683,411.112626,0.974546
18,False,no_org,CPI_diverse,0.557792,0.283066,0.227513,685.2,343.1,322.0,4.990683,411.112626,0.974546
19,False,with_org,CPI_diverse,0.581823,0.268961,0.230120,695.2,348.1,322.0,4.990683,411.112626,3.042623
20,True,with_org,CPI_all,0.510092,0.202791,0.102096,4.2,2.6,322.0,4.990683,410.726797,3.165177
21,True,no_org,CPI_all,0.500000,0.203169,0.096666,1.0,1.0,322.0,4.990683,410.726797,1.070584
22,False,with_org,CPI_all,0.569926,0.272108,0.066003,793.2,397.1,322.0,4.990683,410.726797,3.165177
23,False,no_org,CPI_all,0.566489,0.274819,0.053333,773.4,387.2,322.0,4.990683,410.726797,1.070584
24,False,with_org,CPI+fingerprint_frequent,0.572540,0.288835,0.355465,611.2,306.1,430.0,4.993023,624.352621,3.559885
25,True,with_org,CPI+fingerprint_frequent,0.571965,0.241386,0.490236,65.6,33.3,430.0,4.993023,624.352621,3.559885
26,True,no_org,CPI+fingerprint_frequent,0.555939,0.231786,0.501767,48.0,24.5,430.0,4.993023,624.352621,1.243134
27,False,no_org,CPI+fingerprint_frequent,0.572833,0.288268,0.351091,637.4,319.2,430.0,4.993023,624.352621,1.243134
28,True,with_org,CPI+fingerprint_diverse,0.561092,0.175434,0.440923,17.4,9.2,430.0,4.993023,621.025556,4.200009
29,True,no_org,CPI+fingerprint_diverse,0.530556,0.179040,0.430846,9.2,5.1,430.0,4.993023,621.025556,1.349994
30,False,with_org,CPI+fingerprint_diverse,0.568459,0.259875,0.252117,778.2,389.6,430.0,4.993023,621.025556,4.200009
31,False,no_org,CPI+fingerprint_diverse,0.563185,0.269714,0.247102,808.2,404.6,430.0,4.993023,621.025556,1.349994
32,True,no_org,CPI+fingerprint_all,0.501660,0.202283,0.103117,2.0,1.5,430.0,4.993023,616.204196,1.381211
33,False,with_org,CPI+fingerprint_all,0.568000,0.271633,0.051892,1012.8,506.9,430.0,4.993023,616.204196,3.923393
34,True,with_org,CPI+fingerprint_all,0.512881,0.200601,0.108179,3.0,2.0,430.0,4.993023,616.204196,3.923393
35,False,no_org,CPI+fingerprint_all,0.566699,0.277405,0.056225,1024.6,512.8,430.0,4.993023,616.204196,1.381211

In [5]:
# Table ready (with pruning, rounded, compact)
save_path = "XofN_jaccard_min/"
rounded_final_grouped_res = pd.read_csv(save_path + "all_results.csv", index_col=0)
res = pd.read_csv(save_path + "all_results.csv", index_col=0)
table_results = get_table_results(res, get_dataset_paths())
table_results.to_csv(save_path + "table_results.csv")
table_results

,include_original_features,dataset,averageAUROC,HammingLoss,SubsetAccuracy,Nodes; Leaves,#XofN; #Feat/XofN,# Ung. Feats,XofN time (s); PCT tr. time (s)
1,no_org,fingerprint_frequent,0.551,0.234,0.501,39.6; 20.3,108.0; 5.0,0.0,87.9; 0.7
0,with_org,fingerprint_frequent,0.542,0.226,0.513,47.4; 24.2,108.0; 5.0,0.0,87.9; 1.5
4,no_org,fingerprint_diverse,0.500,0.182,0.426,1.0; 1.0,108.0; 5.0,0.0,87.8; 0.7
7,with_org,fingerprint_diverse,0.517,0.179,0.437,3.6; 2.3,108.0; 5.0,0.0,87.8; 1.6
9,no_org,fingerprint_all,0.500,0.201,0.105,1.2; 1.1,108.0; 5.0,0.0,87.7; 0.7
8,with_org,fingerprint_all,0.515,0.199,0.111,3.2; 2.1,108.0; 5.0,0.0,87.7; 1.6
13,no_org,CPI_frequent,0.508,0.214,0.543,12.0; 6.5,322.0; 5.0,0.0,411.8; 0.9
12,with_org,CPI_frequent,0.538,0.215,0.539,19.2; 10.1,322.0; 5.0,0.0,411.8; 2.9
17,no_org,CPI_diverse,0.531,0.192,0.407,6.6; 3.8,322.0; 5.0,0.0,411.1; 1.0
16,with_org,CPI_diverse,0.559,0.195,0.401,14.0; 7.5,322.0; 5.0,0.0,411.1; 3.0
21,no_org,CPI_all,0.500,0.203,0.097,1.0; 1.0,322.0; 5.0,0.0,410.7; 1.1
20,with_org,CPI_all,0.510,0.203,0.102,4.2; 2.6,322.0; 5.0,0.0,410.7; 3.2
26,no_org,CPI+fingerprint_frequent,0.556,0.232,0.502,48.0; 24.5,430.0; 5.0,0.0,624.4; 1.2
25,with_org,CPI+fingerprint_frequent,0.572,0.241,0.490,65.6; 33.3,430.0; 5.0,0.0,624.4; 3.6
29,no_org,CPI+fingerprint_diverse,0.531,0.179,0.431,9.2; 5.1,430.0; 5.0,0.0,621.0; 1.3
28,with_org,CPI+fingerprint_diverse,0.561,0.175,0.441,17.4; 9.2,430.0; 5.0,0.0,621.0; 4.2
32,no_org,CPI+fingerprint_all,0.502,0.202,0.103,2.0; 1.5,430.0; 5.0,0.0,616.2; 1.4
34,with_org,CPI+fingerprint_all,0.513,0.201,0.108,3.0; 2.0,430.0; 5.0,0.0,616.2; 3.9