In [1]:
import sys, os
sys.path.insert(0, os.path.abspath("C:/Users/Voror/Projects/Personal/sep"))

from sklearn.model_selection import KFold
from SIDER_dataset.libraries.XofN_library import *
from SIDER_dataset.libraries.PCT_library import run_PCT
from SIDER_dataset.libraries.feature_evaluation_methods import feature_variance_reduction_scores
from SIDER_dataset.libraries.utils import get_clus_path
%load_ext autoreload
%autoreload 2

In [2]:
# Set ADR to predict and scoring
clus_path = get_clus_path()
paths = get_dataset_paths()
print(len(paths), "datasets")
paths

12 datasets

[{'dataset_path': 'C:\\Users\\Voror\\Projects\\Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/CPI+fingerprint_cardiac.csv',
  'dataset_name': 'CPI+fingerprint_cardiac',
  'label_set': ['se_C0016382',
   'se_C0018799',
   'se_C0003811',
   'se_C0428977',
   'se_C0027051',
   'se_C0018790'],
  'features': 2147},
 {'dataset_path': 'C:\\Users\\Voror\\Projects\\Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/CPI+fingerprint_high_freq.csv',
  'dataset_name': 'CPI+fingerprint_high_freq',
  'label_set': ['se_C0027497',
   'se_C0018681',
   'se_C0011603',
   'se_C0015230',
   'se_C0042963',
   'se_C0012833'],
  'features': 2147},
 {'dataset_path': 'C:\\Users\\Voror\\Projects\\Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/CPI+fingerprint_low_freq.csv',
  'dataset_name': 'CPI+fingerprint_low_freq',
  'label_set': ['se_C0020580',
   'se_C0267792',
   'se_C0018524',
   'se_C0031117',
   'se_C0035078',
   'se_C0011570'],
  'features': 2147},
 {'dataset_path': 'C:\\Users\\Voror\\Projects\\Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/CPI+fingerprint_mid_freq.csv',
  'dataset_name': 'CPI+fingerprint_mid_freq',
  'label_set': ['se_C0020538',
   'se_C0008031',
   'se_C0003467',
   'se_C0036572',
   'se_C0030252',
   'se_C0027769'],
  'features': 2147},
 {'dataset_path': 'C:\\Users\\Voror\\Projects\\Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/CPI_cardiac.csv',
  'dataset_name': 'CPI_cardiac',
  'label_set': ['se_C0016382',
   'se_C0018799',
   'se_C0003811',
   'se_C0428977',
   'se_C0027051',
   'se_C0018790'],
  'features': 1607},
 {'dataset_path': 'C:\\Users\\Voror\\Projects\\Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/CPI_high_freq.csv',
  'dataset_name': 'CPI_high_freq',
  'label_set': ['se_C0027497',
   'se_C0018681',
   'se_C0011603',
   'se_C0015230',
   'se_C0042963',
   'se_C0012833'],
  'features': 1607},
 {'dataset_path': 'C:\\Users\\Voror\\Projects\\Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/CPI_low_freq.csv',
  'dataset_name': 'CPI_low_freq',
  'label_set': ['se_C0020580',
   'se_C0267792',
   'se_C0018524',
   'se_C0031117',
   'se_C0035078',
   'se_C0011570'],
  'features': 1607},
 {'dataset_path': 'C:\\Users\\Voror\\Projects\\Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/CPI_mid_freq.csv',
  'dataset_name': 'CPI_mid_freq',
  'label_set': ['se_C0020538',
   'se_C0008031',
   'se_C0003467',
   'se_C0036572',
   'se_C0030252',
   'se_C0027769'],
  'features': 1607},
 {'dataset_path': 'C:\\Users\\Voror\\Projects\\Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/fingerprint_cardiac.csv',
  'dataset_name': 'fingerprint_cardiac',
  'label_set': ['se_C0016382',
   'se_C0018799',
   'se_C0003811',
   'se_C0428977',
   'se_C0027051',
   'se_C0018790'],
  'features': 540},
 {'dataset_path': 'C:\\Users\\Voror\\Projects\\Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/fingerprint_high_freq.csv',
  'dataset_name': 'fingerprint_high_freq',
  'label_set': ['se_C0027497',
   'se_C0018681',
   'se_C0011603',
   'se_C0015230',
   'se_C0042963',
   'se_C0012833'],
  'features': 540},
 {'dataset_path': 'C:\\Users\\Voror\\Projects\\Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/fingerprint_low_freq.csv',
  'dataset_name': 'fingerprint_low_freq',
  'label_set': ['se_C0020580',
   'se_C0267792',
   'se_C0018524',
   'se_C0031117',
   'se_C0035078',
   'se_C0011570'],
  'features': 540},
 {'dataset_path': 'C:\\Users\\Voror\\Projects\\Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/fingerprint_mid_freq.csv',
  'dataset_name': 'fingerprint_mid_freq',
  'label_set': ['se_C0020538',
   'se_C0008031',
   'se_C0003467',
   'se_C0036572',
   'se_C0030252',
   'se_C0027769'],
  'features': 540}]

In [3]:
k = 10
random_state = 42
performances = []
ranking_criteria = "MDI"  # or "VAR"
include_original_features_options = [True, False]
training_algorithm = "Variance Reduction"
eval_criteria = ["averageAUROC", "HammingLoss", "SubsetAccuracy", "RankingLoss", "MacroPrecision", "MacroRecall",
                 "MacroFOne"]
max_size = 5
cv_results = []

for idx, path in enumerate(paths, start=1):
    run_config = f"\n--- Running with label:'{path["label_set"]}' training_algorithm:'{training_algorithm}' eval_criterion:'{eval_criteria}' max_size:'{max_size}' ---"
    print(run_config)
    run_config_name = "_".join(
        [
            path["dataset_name"],
            training_algorithm,
            "_".join(eval_criteria),
            str(max_size),
        ]
    )
    logging_path = f"XofN_filter_jaccard/logs/{run_config_name}_logs.txt"
    print(f"Logs can be found in {logging_path}.")
    logger = get_logger(logging_path)
    logger.info(run_config_name)

    # Load dataset
    current_df = pd.read_csv(path["dataset_path"])
    features = get_features(current_df, path["label_set"])
    # current_df = current_df[features[:10] + path["label_set"]]
    kf = KFold(n_splits=k, shuffle=True, random_state=random_state)
    for fold, (train_idx, test_idx) in enumerate(kf.split(current_df), start=1):
        print(f"\nFold {fold}/{k} ({path["dataset_name"]} {idx}/{len(paths)})")
        train_dataset = current_df.iloc[train_idx]
        test_dataset = current_df.iloc[test_idx]

        if ranking_criteria == "VAR":
            feature_rankings = feature_variance_reduction_scores(train_dataset[features],
                                                                 train_dataset[path["label_set"]])
        elif ranking_criteria == "MDI":
            feature_rankings = calculate_mdi_multi_rf(train_dataset, path["label_set"])
        else:
            raise NotImplementedError

        XofN_groupings, avg_features, gen_XofN_time = generate_XofN_list_filter_jaccard(
            train_dataset,
            feature_rankings,
            max_size,
            path["label_set"],
            logger
        )
        if len(XofN_groupings) == 0:
            print("no XofN groupings were created")
        else:
            for include_original_features in include_original_features_options:
                current_train_dataset = group_features(
                    train_dataset,
                    path["label_set"],
                    XofN_groupings,
                    include_original_features,
                    verbose=True
                )

                current_test_dataset = group_features(
                    test_dataset,
                    path["label_set"],
                    XofN_groupings,
                    include_original_features,
                    verbose=True
                )

                current_train_dataset.to_csv(f"XofN_filter_jaccard/tmp/train_dataset.csv", index=False)
                current_test_dataset.to_csv(f"XofN_filter_jaccard/tmp/test_dataset.csv", index=False)

                training_start = time.perf_counter()
                original_res, pruned_res, training_time = run_PCT(clus_path,
                                                                  "XofN_filter_jaccard/tmp/train_dataset.csv",
                                                                  path["label_set"],
                                                                  eval_criteria,
                                                                  test_dataset_path=f"XofN_filter_jaccard/tmp/test_dataset.csv")
                pruned_performance = get_fold_results(pruned_res, eval_criteria, True, fold, include_original_features,
                                                      XofN_groupings,
                                                      gen_XofN_time,
                                                      training_time, path["dataset_name"])
                performances.append(pruned_performance)
                performance = get_fold_results(original_res, eval_criteria, False, fold, include_original_features,
                                               XofN_groupings,
                                               gen_XofN_time,
                                               training_time, path["dataset_name"])
                performances.append(performance)

    if len(performances) == 0:
        print("no XofN groupings were created in any fold")
    else:
        final_perf_df = pd.DataFrame(performances)
        averages = final_perf_df.groupby(["pruning", 'include_original_features', 'dataset'])[
            eval_criteria + ['nodes', 'leaves', 'groups',
                             'avg_group_features', 'gen_XofN_time', 'training_time']].mean().reset_index()
        print(averages)
        cv_results.append(averages)
        performances = []
# paths[0] - features[:10] desktop 0.23m
# laptop ??m
# desktop 24h

--- Running with label:'['se_C0016382', 'se_C0018799', 'se_C0003811', 'se_C0428977', 'se_C0027051', 'se_C0018790']' training_algorithm:'Variance Reduction' eval_criterion:'['averageAUROC', 'HammingLoss', 'SubsetAccuracy', 'RankingLoss', 'MacroPrecision', 'MacroRecall', 'MacroFOne']' max_size:'5' ---
Logs can be found in XofN_filter_jaccard/logs/CPI+fingerprint_cardiac_Variance Reduction_averageAUROC_HammingLoss_SubsetAccuracy_RankingLoss_MacroPrecision_MacroRecall_MacroFOne_5_logs.txt.

Fold 1/10 (CPI+fingerprint_cardiac 1/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [19:58<00:00,  1.79feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.6721116, HammingLoss: 0.22542, SubsetAccuracy: 0.4964, RankingLoss: 0.19702, MacroPrecision: 0.49575, MacroRecall: 0.30507, MacroFOne: 0.37602,
pruning: False, include_original_features: with_org, averageAUROC: 0.6463832, HammingLoss: 0.30216, SubsetAccuracy: 0.28777, RankingLoss: 0.20016, MacroPrecision: 0.3723, MacroRecall: 0.5012, MacroFOne: 0.42561,
pruning: True, include_original_features: no_org, averageAUROC: 0.6636196, HammingLoss: 0.20983, SubsetAccuracy: 0.48201, RankingLoss: 0.16573, MacroPrecision: 0.58885, MacroRecall: 0.25431, MacroFOne: 0.35278,
pruning: False, include_original_features: no_org, averageAUROC: 0.6499695, HammingLoss: 0.31535, SubsetAccuracy: 0.31655, RankingLoss: 0.1942, MacroPrecision: 0.35706, MacroRecall: 0.50287, MacroFOne: 0.41424,

Fold 2/10 (CPI+fingerprint_cardiac 1/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [20:16<00:00,  1.77feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.5616517, HammingLoss: 0.29616, SubsetAccuracy: 0.35971, RankingLoss: 0.23973, MacroPrecision: 0.40059, MacroRecall: 0.18563, MacroFOne: 0.2531,
pruning: False, include_original_features: with_org, averageAUROC: 0.5456472, HammingLoss: 0.36211, SubsetAccuracy: 0.20863, RankingLoss: 0.22648, MacroPrecision: 0.32319, MacroRecall: 0.32415, MacroFOne: 0.32355,
pruning: True, include_original_features: no_org, averageAUROC: 0.5222034, HammingLoss: 0.28897, SubsetAccuracy: 0.36691, RankingLoss: 0.23813, MacroPrecision: 0.38989, MacroRecall: 0.10577, MacroFOne: 0.16532,
pruning: False, include_original_features: no_org, averageAUROC: 0.6023176, HammingLoss: 0.32254, SubsetAccuracy: 0.2518, RankingLoss: 0.21904, MacroPrecision: 0.4019, MacroRecall: 0.42468, MacroFOne: 0.4123,

Fold 3/10 (CPI+fingerprint_cardiac 1/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [20:19<00:00,  1.76feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.5446803, HammingLoss: 0.28657, SubsetAccuracy: 0.34532, RankingLoss: 0.24834, MacroPrecision: 0.48889, MacroRecall: 0.11838, MacroFOne: 0.18908,
pruning: False, include_original_features: with_org, averageAUROC: 0.5803069, HammingLoss: 0.36091, SubsetAccuracy: 0.17266, RankingLoss: 0.24041, MacroPrecision: 0.36732, MacroRecall: 0.39716, MacroFOne: 0.37583,
pruning: True, include_original_features: no_org, averageAUROC: 0.5369486, HammingLoss: 0.28897, SubsetAccuracy: 0.32374, RankingLoss: 0.26049, MacroPrecision: 0.47018, MacroRecall: 0.14652, MacroFOne: 0.2222,
pruning: False, include_original_features: no_org, averageAUROC: 0.571205, HammingLoss: 0.3717, SubsetAccuracy: 0.14388, RankingLoss: 0.2255, MacroPrecision: 0.36845, MacroRecall: 0.42749, MacroFOne: 0.39219,

Fold 4/10 (CPI+fingerprint_cardiac 1/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [20:06<00:00,  1.78feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.6177887, HammingLoss: 0.28657, SubsetAccuracy: 0.35252, RankingLoss: 0.22714, MacroPrecision: 0.39581, MacroRecall: 0.21584, MacroFOne: 0.27509,
pruning: False, include_original_features: with_org, averageAUROC: 0.5546205, HammingLoss: 0.36091, SubsetAccuracy: 0.17266, RankingLoss: 0.23096, MacroPrecision: 0.32677, MacroRecall: 0.40103, MacroFOne: 0.35798,
pruning: True, include_original_features: no_org, averageAUROC: 0.5928618, HammingLoss: 0.29496, SubsetAccuracy: 0.35971, RankingLoss: 0.21335, MacroPrecision: 0.33988, MacroRecall: 0.16311, MacroFOne: 0.2186,
pruning: False, include_original_features: no_org, averageAUROC: 0.571966, HammingLoss: 0.34652, SubsetAccuracy: 0.19424, RankingLoss: 0.20422, MacroPrecision: 0.33981, MacroRecall: 0.39407, MacroFOne: 0.36071,

Fold 5/10 (CPI+fingerprint_cardiac 1/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [20:26<00:00,  1.75feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.5995661, HammingLoss: 0.23501, SubsetAccuracy: 0.41727, RankingLoss: 0.20921, MacroPrecision: 0.42226, MacroRecall: 0.27207, MacroFOne: 0.32875,
pruning: False, include_original_features: with_org, averageAUROC: 0.6271857, HammingLoss: 0.31055, SubsetAccuracy: 0.27338, RankingLoss: 0.2241, MacroPrecision: 0.34216, MacroRecall: 0.47278, MacroFOne: 0.39622,
pruning: True, include_original_features: no_org, averageAUROC: 0.598711, HammingLoss: 0.23022, SubsetAccuracy: 0.43165, RankingLoss: 0.20779, MacroPrecision: 0.44057, MacroRecall: 0.23784, MacroFOne: 0.30832,
pruning: False, include_original_features: no_org, averageAUROC: 0.5669386, HammingLoss: 0.33933, SubsetAccuracy: 0.19424, RankingLoss: 0.2197, MacroPrecision: 0.29298, MacroRecall: 0.40928, MacroFOne: 0.34069,

Fold 6/10 (CPI+fingerprint_cardiac 1/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [20:25<00:00,  1.75feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.603222, HammingLoss: 0.27578, SubsetAccuracy: 0.41007, RankingLoss: 0.21703, MacroPrecision: 0.3974, MacroRecall: 0.15756, MacroFOne: 0.21912,
pruning: False, include_original_features: with_org, averageAUROC: 0.5547225, HammingLoss: 0.35492, SubsetAccuracy: 0.23022, RankingLoss: 0.19654, MacroPrecision: 0.30772, MacroRecall: 0.33645, MacroFOne: 0.31923,
pruning: True, include_original_features: no_org, averageAUROC: 0.5691985, HammingLoss: 0.28297, SubsetAccuracy: 0.41727, RankingLoss: 0.20719, MacroPrecision: 0.28994, MacroRecall: 0.090967, MacroFOne: 0.13606,
pruning: False, include_original_features: no_org, averageAUROC: 0.5552809, HammingLoss: 0.36091, SubsetAccuracy: 0.20863, RankingLoss: 0.19321, MacroPrecision: 0.30597, MacroRecall: 0.3508, MacroFOne: 0.32546,

Fold 7/10 (CPI+fingerprint_cardiac 1/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [20:26<00:00,  1.75feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.6199338, HammingLoss: 0.26859, SubsetAccuracy: 0.3741, RankingLoss: 0.23139, MacroPrecision: 0.44911, MacroRecall: 0.20145, MacroFOne: 0.27704,
pruning: False, include_original_features: with_org, averageAUROC: 0.6005779, HammingLoss: 0.33693, SubsetAccuracy: 0.23022, RankingLoss: 0.24173, MacroPrecision: 0.3709, MacroRecall: 0.46147, MacroFOne: 0.40949,
pruning: True, include_original_features: no_org, averageAUROC: 0.6074255, HammingLoss: 0.2506, SubsetAccuracy: 0.38129, RankingLoss: 0.23135, MacroPrecision: 0.51727, MacroRecall: 0.19245, MacroFOne: 0.27767,
pruning: False, include_original_features: no_org, averageAUROC: 0.5988547, HammingLoss: 0.34053, SubsetAccuracy: 0.22302, RankingLoss: 0.22898, MacroPrecision: 0.35441, MacroRecall: 0.42509, MacroFOne: 0.38497,

Fold 8/10 (CPI+fingerprint_cardiac 1/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [20:27<00:00,  1.75feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.540192, HammingLoss: 0.29616, SubsetAccuracy: 0.28777, RankingLoss: 0.22212, MacroPrecision: 0.41253, MacroRecall: 0.13665, MacroFOne: 0.20322,
pruning: False, include_original_features: with_org, averageAUROC: 0.5774712, HammingLoss: 0.3789, SubsetAccuracy: 0.1223, RankingLoss: 0.20629, MacroPrecision: 0.34777, MacroRecall: 0.43038, MacroFOne: 0.38036,
pruning: True, include_original_features: no_org, averageAUROC: 0.5675816, HammingLoss: 0.29017, SubsetAccuracy: 0.29496, RankingLoss: 0.21699, MacroPrecision: 0.43002, MacroRecall: 0.11098, MacroFOne: 0.17487,
pruning: False, include_original_features: no_org, averageAUROC: 0.5492838, HammingLoss: 0.38849, SubsetAccuracy: 0.1295, RankingLoss: 0.23909, MacroPrecision: 0.33179, MacroRecall: 0.39716, MacroFOne: 0.35893,

Fold 9/10 (CPI+fingerprint_cardiac 1/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [20:29<00:00,  1.75feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.5861851, HammingLoss: 0.29496, SubsetAccuracy: 0.28058, RankingLoss: 0.25618, MacroPrecision: 0.37348, MacroRecall: 0.18772, MacroFOne: 0.24718,
pruning: False, include_original_features: with_org, averageAUROC: 0.5857664, HammingLoss: 0.35731, SubsetAccuracy: 0.16547, RankingLoss: 0.2718, MacroPrecision: 0.33831, MacroRecall: 0.40637, MacroFOne: 0.36624,
pruning: True, include_original_features: no_org, averageAUROC: 0.593347, HammingLoss: 0.29017, SubsetAccuracy: 0.27338, RankingLoss: 0.2493, MacroPrecision: 0.37336, MacroRecall: 0.13574, MacroFOne: 0.19533,
pruning: False, include_original_features: no_org, averageAUROC: 0.5849087, HammingLoss: 0.36211, SubsetAccuracy: 0.16547, RankingLoss: 0.26769, MacroPrecision: 0.34174, MacroRecall: 0.42737, MacroFOne: 0.37747,

Fold 10/10 (CPI+fingerprint_cardiac 1/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [20:26<00:00,  1.75feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.6173266, HammingLoss: 0.25121, SubsetAccuracy: 0.34058, RankingLoss: 0.23607, MacroPrecision: 0.45553, MacroRecall: 0.17689, MacroFOne: 0.25397,
pruning: False, include_original_features: with_org, averageAUROC: 0.5982941, HammingLoss: 0.32609, SubsetAccuracy: 0.23913, RankingLoss: 0.22752, MacroPrecision: 0.34536, MacroRecall: 0.40143, MacroFOne: 0.37048,
pruning: True, include_original_features: no_org, averageAUROC: 0.6187942, HammingLoss: 0.25, SubsetAccuracy: 0.35507, RankingLoss: 0.22973, MacroPrecision: 0.45833, MacroRecall: 0.14064, MacroFOne: 0.21395,
pruning: False, include_original_features: no_org, averageAUROC: 0.6084135, HammingLoss: 0.32488, SubsetAccuracy: 0.23188, RankingLoss: 0.21264, MacroPrecision: 0.35453, MacroRecall: 0.4224, MacroFOne: 0.38285,
   pruning include_original_features                  dataset  averageAUROC  \
0    False                    no_org  CPI+fingerprint_cardiac      0.585914
1    False                  with_org  CPI+fingerprint_cardiac      0.587098
2     True                    no_org  CPI+fingerprint_cardiac      0.587069
3     True                  with_org  CPI+fingerprint_cardiac      0.596266

   HammingLoss  SubsetAccuracy  RankingLoss  MacroPrecision  MacroRecall  \
0     0.347236        0.205921     0.220427        0.344864     0.418121
1     0.345079        0.210244     0.226599        0.344180     0.413242
2     0.267686        0.368599     0.222005        0.429829     0.157833
3     0.271643        0.366432     0.228423        0.429135     0.195726

   MacroFOne  nodes  leaves  groups  avg_group_features  gen_XofN_time  \
0   0.374981  844.6   422.8   430.0            4.993023    1220.069503
1   0.372499  827.4   414.2   430.0            4.993023    1220.069503
2   0.226510   65.8    33.4   430.0            4.993023    1220.069503
3   0.262257   85.8    43.4   430.0            4.993023    1220.069503

   training_time
0       1.218612
1       3.839335
2       1.218612
3       3.839335

--- Running with label:'['se_C0027497', 'se_C0018681', 'se_C0011603', 'se_C0015230', 'se_C0042963', 'se_C0012833']' training_algorithm:'Variance Reduction' eval_criterion:'['averageAUROC', 'HammingLoss', 'SubsetAccuracy', 'RankingLoss', 'MacroPrecision', 'MacroRecall', 'MacroFOne']' max_size:'5' ---
Logs can be found in XofN_filter_jaccard/logs/CPI+fingerprint_high_freq_Variance Reduction_averageAUROC_HammingLoss_SubsetAccuracy_RankingLoss_MacroPrecision_MacroRecall_MacroFOne_5_logs.txt.

Fold 1/10 (CPI+fingerprint_high_freq 2/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [20:46<00:00,  1.72feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.6759642, HammingLoss: 0.23381, SubsetAccuracy: 0.52518, RankingLoss: 0.1258, MacroPrecision: 0.77953, MacroRecall: 0.96139, MacroFOne: 0.86052,
pruning: False, include_original_features: with_org, averageAUROC: 0.5786027, HammingLoss: 0.27218, SubsetAccuracy: 0.39568, RankingLoss: 0.1547, MacroPrecision: 0.77757, MacroRecall: 0.89242, MacroFOne: 0.83068,
pruning: True, include_original_features: no_org, averageAUROC: 0.7003008, HammingLoss: 0.23861, SubsetAccuracy: 0.52518, RankingLoss: 0.13241, MacroPrecision: 0.77613, MacroRecall: 0.95964, MacroFOne: 0.8578,
pruning: False, include_original_features: no_org, averageAUROC: 0.6033835, HammingLoss: 0.27938, SubsetAccuracy: 0.35971, RankingLoss: 0.13843, MacroPrecision: 0.77695, MacroRecall: 0.87901, MacroFOne: 0.82453,

Fold 2/10 (CPI+fingerprint_high_freq 2/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [20:45<00:00,  1.72feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.6749476, HammingLoss: 0.22182, SubsetAccuracy: 0.48201, RankingLoss: 0.15845, MacroPrecision: 0.81056, MacroRecall: 0.93381, MacroFOne: 0.8672,
pruning: False, include_original_features: with_org, averageAUROC: 0.5904986, HammingLoss: 0.253, SubsetAccuracy: 0.3741, RankingLoss: 0.1757, MacroPrecision: 0.81167, MacroRecall: 0.87536, MacroFOne: 0.84215,
pruning: True, include_original_features: no_org, averageAUROC: 0.6617237, HammingLoss: 0.21942, SubsetAccuracy: 0.48201, RankingLoss: 0.15819, MacroPrecision: 0.81193, MacroRecall: 0.9355, MacroFOne: 0.86868,
pruning: False, include_original_features: no_org, averageAUROC: 0.5647967, HammingLoss: 0.26499, SubsetAccuracy: 0.36691, RankingLoss: 0.17532, MacroPrecision: 0.80615, MacroRecall: 0.86672, MacroFOne: 0.83496,

Fold 3/10 (CPI+fingerprint_high_freq 2/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [20:46<00:00,  1.72feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.549303, HammingLoss: 0.20384, SubsetAccuracy: 0.55396, RankingLoss: 0.15659, MacroPrecision: 0.85257, MacroRecall: 0.91333, MacroFOne: 0.88153,
pruning: False, include_original_features: with_org, averageAUROC: 0.5838739, HammingLoss: 0.21583, SubsetAccuracy: 0.46043, RankingLoss: 0.14021, MacroPrecision: 0.86193, MacroRecall: 0.88388, MacroFOne: 0.87209,
pruning: True, include_original_features: no_org, averageAUROC: 0.5347518, HammingLoss: 0.20624, SubsetAccuracy: 0.53237, RankingLoss: 0.1503, MacroPrecision: 0.84656, MacroRecall: 0.9194, MacroFOne: 0.88102,
pruning: False, include_original_features: no_org, averageAUROC: 0.5683853, HammingLoss: 0.24341, SubsetAccuracy: 0.41007, RankingLoss: 0.13211, MacroPrecision: 0.86217, MacroRecall: 0.84367, MacroFOne: 0.85217,

Fold 4/10 (CPI+fingerprint_high_freq 2/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [20:45<00:00,  1.72feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.5594548, HammingLoss: 0.27938, SubsetAccuracy: 0.45324, RankingLoss: 0.16449, MacroPrecision: 0.77262, MacroRecall: 0.89767, MacroFOne: 0.83015,
pruning: False, include_original_features: with_org, averageAUROC: 0.5746267, HammingLoss: 0.29976, SubsetAccuracy: 0.35971, RankingLoss: 0.17244, MacroPrecision: 0.78735, MacroRecall: 0.82935, MacroFOne: 0.80744,
pruning: True, include_original_features: no_org, averageAUROC: 0.5228438, HammingLoss: 0.28537, SubsetAccuracy: 0.45324, RankingLoss: 0.17496, MacroPrecision: 0.76478, MacroRecall: 0.90429, MacroFOne: 0.82833,
pruning: False, include_original_features: no_org, averageAUROC: 0.555622, HammingLoss: 0.27698, SubsetAccuracy: 0.40288, RankingLoss: 0.15132, MacroPrecision: 0.79899, MacroRecall: 0.84755, MacroFOne: 0.82205,

Fold 5/10 (CPI+fingerprint_high_freq 2/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [20:38<00:00,  1.73feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.6067456, HammingLoss: 0.26019, SubsetAccuracy: 0.48201, RankingLoss: 0.16583, MacroPrecision: 0.76129, MacroRecall: 0.93943, MacroFOne: 0.84035,
pruning: False, include_original_features: with_org, averageAUROC: 0.6369316, HammingLoss: 0.30695, SubsetAccuracy: 0.33094, RankingLoss: 0.14235, MacroPrecision: 0.76194, MacroRecall: 0.8424, MacroFOne: 0.79902,
pruning: True, include_original_features: no_org, averageAUROC: 0.6221551, HammingLoss: 0.23501, SubsetAccuracy: 0.5036, RankingLoss: 0.15953, MacroPrecision: 0.77834, MacroRecall: 0.94949, MacroFOne: 0.85491,
pruning: False, include_original_features: no_org, averageAUROC: 0.610195, HammingLoss: 0.29736, SubsetAccuracy: 0.38849, RankingLoss: 0.16105, MacroPrecision: 0.77004, MacroRecall: 0.84626, MacroFOne: 0.80582,

Fold 6/10 (CPI+fingerprint_high_freq 2/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [20:51<00:00,  1.72feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.6445906, HammingLoss: 0.23501, SubsetAccuracy: 0.53237, RankingLoss: 0.13078, MacroPrecision: 0.81925, MacroRecall: 0.90108, MacroFOne: 0.85771,
pruning: False, include_original_features: with_org, averageAUROC: 0.6412613, HammingLoss: 0.26859, SubsetAccuracy: 0.38129, RankingLoss: 0.13919, MacroPrecision: 0.83133, MacroRecall: 0.82538, MacroFOne: 0.82812,
pruning: True, include_original_features: no_org, averageAUROC: 0.6459089, HammingLoss: 0.22782, SubsetAccuracy: 0.54676, RankingLoss: 0.12948, MacroPrecision: 0.82478, MacroRecall: 0.90261, MacroFOne: 0.8616,
pruning: False, include_original_features: no_org, averageAUROC: 0.6117643, HammingLoss: 0.24221, SubsetAccuracy: 0.41727, RankingLoss: 0.11085, MacroPrecision: 0.83065, MacroRecall: 0.86579, MacroFOne: 0.8478,

Fold 7/10 (CPI+fingerprint_high_freq 2/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [20:49<00:00,  1.72feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.597117, HammingLoss: 0.2458, SubsetAccuracy: 0.48921, RankingLoss: 0.14065, MacroPrecision: 0.78158, MacroRecall: 0.93841, MacroFOne: 0.8523,
pruning: False, include_original_features: with_org, averageAUROC: 0.6295517, HammingLoss: 0.26019, SubsetAccuracy: 0.38129, RankingLoss: 0.1249, MacroPrecision: 0.80378, MacroRecall: 0.86618, MacroFOne: 0.83371,
pruning: True, include_original_features: no_org, averageAUROC: 0.6030868, HammingLoss: 0.253, SubsetAccuracy: 0.48201, RankingLoss: 0.1473, MacroPrecision: 0.7777, MacroRecall: 0.93363, MacroFOne: 0.84807,
pruning: False, include_original_features: no_org, averageAUROC: 0.6121185, HammingLoss: 0.26499, SubsetAccuracy: 0.43885, RankingLoss: 0.14195, MacroPrecision: 0.79514, MacroRecall: 0.87683, MacroFOne: 0.83365,

Fold 8/10 (CPI+fingerprint_high_freq 2/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [20:52<00:00,  1.71feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.5619159, HammingLoss: 0.21981, SubsetAccuracy: 0.49275, RankingLoss: 0.18313, MacroPrecision: 0.79319, MacroRecall: 0.9738, MacroFOne: 0.87357,
pruning: False, include_original_features: with_org, averageAUROC: 0.6034405, HammingLoss: 0.25, SubsetAccuracy: 0.38406, RankingLoss: 0.16649, MacroPrecision: 0.81828, MacroRecall: 0.86969, MacroFOne: 0.8431,
pruning: True, include_original_features: no_org, averageAUROC: 0.6056012, HammingLoss: 0.21014, SubsetAccuracy: 0.50725, RankingLoss: 0.17045, MacroPrecision: 0.80411, MacroRecall: 0.96736, MacroFOne: 0.87761,
pruning: False, include_original_features: no_org, averageAUROC: 0.6580256, HammingLoss: 0.24275, SubsetAccuracy: 0.39855, RankingLoss: 0.1659, MacroPrecision: 0.81217, MacroRecall: 0.89587, MacroFOne: 0.85152,

Fold 9/10 (CPI+fingerprint_high_freq 2/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [20:52<00:00,  1.71feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.5726727, HammingLoss: 0.21981, SubsetAccuracy: 0.5, RankingLoss: 0.15161, MacroPrecision: 0.79779, MacroRecall: 0.96318, MacroFOne: 0.87189,
pruning: False, include_original_features: with_org, averageAUROC: 0.6050709, HammingLoss: 0.26329, SubsetAccuracy: 0.36232, RankingLoss: 0.14924, MacroPrecision: 0.81833, MacroRecall: 0.84592, MacroFOne: 0.83137,
pruning: True, include_original_features: no_org, averageAUROC: 0.5330505, HammingLoss: 0.22705, SubsetAccuracy: 0.5, RankingLoss: 0.1592, MacroPrecision: 0.79667, MacroRecall: 0.9543, MacroFOne: 0.86732,
pruning: False, include_original_features: no_org, averageAUROC: 0.622473, HammingLoss: 0.24638, SubsetAccuracy: 0.38406, RankingLoss: 0.1468, MacroPrecision: 0.81948, MacroRecall: 0.87583, MacroFOne: 0.84643,

Fold 10/10 (CPI+fingerprint_high_freq 2/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [20:53<00:00,  1.71feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.5738354, HammingLoss: 0.25121, SubsetAccuracy: 0.44203, RankingLoss: 0.19336, MacroPrecision: 0.77563, MacroRecall: 0.93716, MacroFOne: 0.84827,
pruning: False, include_original_features: with_org, averageAUROC: 0.5609859, HammingLoss: 0.29469, SubsetAccuracy: 0.34783, RankingLoss: 0.18943, MacroPrecision: 0.77351, MacroRecall: 0.85526, MacroFOne: 0.81209,
pruning: True, include_original_features: no_org, averageAUROC: 0.5764378, HammingLoss: 0.25242, SubsetAccuracy: 0.44928, RankingLoss: 0.19082, MacroPrecision: 0.77537, MacroRecall: 0.93532, MacroFOne: 0.84735,
pruning: False, include_original_features: no_org, averageAUROC: 0.6251782, HammingLoss: 0.29106, SubsetAccuracy: 0.33333, RankingLoss: 0.18325, MacroPrecision: 0.77871, MacroRecall: 0.85467, MacroFOne: 0.81453,
   pruning include_original_features                    dataset  averageAUROC  \
0    False                    no_org  CPI+fingerprint_high_freq      0.603194
1    False                  with_org  CPI+fingerprint_high_freq      0.600484
2     True                    no_org  CPI+fingerprint_high_freq      0.600586
3     True                  with_org  CPI+fingerprint_high_freq      0.601655

   HammingLoss  SubsetAccuracy  RankingLoss  MacroPrecision  MacroRecall  \
0     0.264951        0.390012     0.150698        0.805045     0.865220
1     0.268448        0.377765     0.155465        0.804569     0.858584
2     0.235508        0.498170     0.157264        0.795637     0.936154
3     0.237068        0.495276     0.157069        0.794401     0.935926

   MacroFOne  nodes  leaves  groups  avg_group_features  gen_XofN_time  \
0   0.833346  609.0   305.0   430.0            4.993023    1248.124692
1   0.829977  601.8   301.4   430.0            4.993023    1248.124692
2   0.859269   72.0    36.5   430.0            4.993023    1248.124692
3   0.858349   72.6    36.8   430.0            4.993023    1248.124692

   training_time
0       1.193662
1       3.526549
2       1.193662
3       3.526549

--- Running with label:'['se_C0020580', 'se_C0267792', 'se_C0018524', 'se_C0031117', 'se_C0035078', 'se_C0011570']' training_algorithm:'Variance Reduction' eval_criterion:'['averageAUROC', 'HammingLoss', 'SubsetAccuracy', 'RankingLoss', 'MacroPrecision', 'MacroRecall', 'MacroFOne']' max_size:'5' ---
Logs can be found in XofN_filter_jaccard/logs/CPI+fingerprint_low_freq_Variance Reduction_averageAUROC_HammingLoss_SubsetAccuracy_RankingLoss_MacroPrecision_MacroRecall_MacroFOne_5_logs.txt.

Fold 1/10 (CPI+fingerprint_low_freq 3/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [20:54<00:00,  1.71feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.5595044, HammingLoss: 0.23261, SubsetAccuracy: 0.41727, RankingLoss: 0.25218, MacroPrecision: 0.31349, MacroRecall: 0.1191, MacroFOne: 0.16809,
pruning: False, include_original_features: with_org, averageAUROC: 0.6062306, HammingLoss: 0.32254, SubsetAccuracy: 0.23741, RankingLoss: 0.24622, MacroPrecision: 0.31234, MacroRecall: 0.48312, MacroFOne: 0.3786,
pruning: True, include_original_features: no_org, averageAUROC: 0.5534181, HammingLoss: 0.20384, SubsetAccuracy: 0.41727, RankingLoss: 0.2701, MacroPrecision: 0.5045, MacroRecall: 0.11898, MacroFOne: 0.18993,
pruning: False, include_original_features: no_org, averageAUROC: 0.6116607, HammingLoss: 0.31535, SubsetAccuracy: 0.20144, RankingLoss: 0.25673, MacroPrecision: 0.30762, MacroRecall: 0.44175, MacroFOne: 0.36118,

Fold 2/10 (CPI+fingerprint_low_freq 3/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [20:55<00:00,  1.71feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.622685, HammingLoss: 0.2542, SubsetAccuracy: 0.36691, RankingLoss: 0.25891, MacroPrecision: 0.39056, MacroRecall: 0.16972, MacroFOne: 0.2334,
pruning: False, include_original_features: with_org, averageAUROC: 0.5737549, HammingLoss: 0.34772, SubsetAccuracy: 0.15827, RankingLoss: 0.23411, MacroPrecision: 0.31265, MacroRecall: 0.3879, MacroFOne: 0.34152,
pruning: True, include_original_features: no_org, averageAUROC: 0.5890623, HammingLoss: 0.23741, SubsetAccuracy: 0.34532, RankingLoss: 0.29388, MacroPrecision: 0.49452, MacroRecall: 0.18865, MacroFOne: 0.27172,
pruning: False, include_original_features: no_org, averageAUROC: 0.5835259, HammingLoss: 0.33573, SubsetAccuracy: 0.15827, RankingLoss: 0.26954, MacroPrecision: 0.33138, MacroRecall: 0.42054, MacroFOne: 0.36773,

Fold 3/10 (CPI+fingerprint_low_freq 3/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [20:56<00:00,  1.71feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.5530272, HammingLoss: 0.26739, SubsetAccuracy: 0.33094, RankingLoss: 0.31461, MacroPrecision: 0.48697, MacroRecall: 0.14275, MacroFOne: 0.21521,
pruning: False, include_original_features: with_org, averageAUROC: 0.6225837, HammingLoss: 0.34173, SubsetAccuracy: 0.18705, RankingLoss: 0.27718, MacroPrecision: 0.37695, MacroRecall: 0.45505, MacroFOne: 0.41067,
pruning: True, include_original_features: no_org, averageAUROC: 0.5747373, HammingLoss: 0.2554, SubsetAccuracy: 0.33094, RankingLoss: 0.31513, MacroPrecision: 0.5609, MacroRecall: 0.13785, MacroFOne: 0.21723,
pruning: False, include_original_features: no_org, averageAUROC: 0.6010098, HammingLoss: 0.35612, SubsetAccuracy: 0.15827, RankingLoss: 0.28925, MacroPrecision: 0.3561, MacroRecall: 0.43855, MacroFOne: 0.38884,

Fold 4/10 (CPI+fingerprint_low_freq 3/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [20:57<00:00,  1.71feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.6413565, HammingLoss: 0.20863, SubsetAccuracy: 0.42446, RankingLoss: 0.23709, MacroPrecision: 0.49585, MacroRecall: 0.17742, MacroFOne: 0.25596,
pruning: False, include_original_features: with_org, averageAUROC: 0.6240619, HammingLoss: 0.31055, SubsetAccuracy: 0.20144, RankingLoss: 0.23591, MacroPrecision: 0.3208, MacroRecall: 0.43863, MacroFOne: 0.36629,
pruning: True, include_original_features: no_org, averageAUROC: 0.6319989, HammingLoss: 0.21103, SubsetAccuracy: 0.42446, RankingLoss: 0.23807, MacroPrecision: 0.48084, MacroRecall: 0.17656, MacroFOne: 0.25037,
pruning: False, include_original_features: no_org, averageAUROC: 0.6077744, HammingLoss: 0.31055, SubsetAccuracy: 0.23022, RankingLoss: 0.2507, MacroPrecision: 0.29079, MacroRecall: 0.35956, MacroFOne: 0.31991,

Fold 5/10 (CPI+fingerprint_low_freq 3/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [20:56<00:00,  1.71feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.6002283, HammingLoss: 0.25779, SubsetAccuracy: 0.35971, RankingLoss: 0.24111, MacroPrecision: 0.42646, MacroRecall: 0.17497, MacroFOne: 0.24519,
pruning: False, include_original_features: with_org, averageAUROC: 0.5579315, HammingLoss: 0.34412, SubsetAccuracy: 0.19424, RankingLoss: 0.26843, MacroPrecision: 0.30768, MacroRecall: 0.32937, MacroFOne: 0.31738,
pruning: True, include_original_features: no_org, averageAUROC: 0.5946098, HammingLoss: 0.253, SubsetAccuracy: 0.35971, RankingLoss: 0.25999, MacroPrecision: 0.44704, MacroRecall: 0.20073, MacroFOne: 0.27301,
pruning: False, include_original_features: no_org, averageAUROC: 0.5846727, HammingLoss: 0.35252, SubsetAccuracy: 0.18705, RankingLoss: 0.27176, MacroPrecision: 0.32773, MacroRecall: 0.41799, MacroFOne: 0.36471,

Fold 6/10 (CPI+fingerprint_low_freq 3/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [20:58<00:00,  1.71feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.6232716, HammingLoss: 0.26499, SubsetAccuracy: 0.27338, RankingLoss: 0.27208, MacroPrecision: 0.49464, MacroRecall: 0.16396, MacroFOne: 0.2427,
pruning: False, include_original_features: with_org, averageAUROC: 0.5712419, HammingLoss: 0.35012, SubsetAccuracy: 0.17986, RankingLoss: 0.29388, MacroPrecision: 0.33889, MacroRecall: 0.33662, MacroFOne: 0.33594,
pruning: True, include_original_features: no_org, averageAUROC: 0.6175827, HammingLoss: 0.27458, SubsetAccuracy: 0.28058, RankingLoss: 0.26293, MacroPrecision: 0.45531, MacroRecall: 0.16038, MacroFOne: 0.23675,
pruning: False, include_original_features: no_org, averageAUROC: 0.5745719, HammingLoss: 0.33333, SubsetAccuracy: 0.22302, RankingLoss: 0.31165, MacroPrecision: 0.38162, MacroRecall: 0.39533, MacroFOne: 0.38719,

Fold 7/10 (CPI+fingerprint_low_freq 3/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [20:57<00:00,  1.71feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.6452355, HammingLoss: 0.22062, SubsetAccuracy: 0.38849, RankingLoss: 0.24061, MacroPrecision: 0.57993, MacroRecall: 0.21324, MacroFOne: 0.30774,
pruning: False, include_original_features: with_org, averageAUROC: 0.5980266, HammingLoss: 0.32254, SubsetAccuracy: 0.23741, RankingLoss: 0.23024, MacroPrecision: 0.34492, MacroRecall: 0.41152, MacroFOne: 0.37241,
pruning: True, include_original_features: no_org, averageAUROC: 0.6089535, HammingLoss: 0.23621, SubsetAccuracy: 0.40288, RankingLoss: 0.25787, MacroPrecision: 0.47619, MacroRecall: 0.10023, MacroFOne: 0.16519,
pruning: False, include_original_features: no_org, averageAUROC: 0.6102811, HammingLoss: 0.29496, SubsetAccuracy: 0.2446, RankingLoss: 0.23939, MacroPrecision: 0.3739, MacroRecall: 0.39857, MacroFOne: 0.38455,

Fold 8/10 (CPI+fingerprint_low_freq 3/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [20:59<00:00,  1.70feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.5829454, HammingLoss: 0.28417, SubsetAccuracy: 0.29496, RankingLoss: 0.32296, MacroPrecision: 0.47292, MacroRecall: 0.14727, MacroFOne: 0.22076,
pruning: False, include_original_features: with_org, averageAUROC: 0.6062831, HammingLoss: 0.33573, SubsetAccuracy: 0.18705, RankingLoss: 0.26811, MacroPrecision: 0.39079, MacroRecall: 0.40718, MacroFOne: 0.39833,
pruning: True, include_original_features: no_org, averageAUROC: 0.6172903, HammingLoss: 0.29856, SubsetAccuracy: 0.29496, RankingLoss: 0.31475, MacroPrecision: 0.39992, MacroRecall: 0.15469, MacroFOne: 0.22111,
pruning: False, include_original_features: no_org, averageAUROC: 0.6111817, HammingLoss: 0.34173, SubsetAccuracy: 0.18705, RankingLoss: 0.2557, MacroPrecision: 0.39378, MacroRecall: 0.45104, MacroFOne: 0.41873,

Fold 9/10 (CPI+fingerprint_low_freq 3/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [20:59<00:00,  1.70feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.5906474, HammingLoss: 0.24396, SubsetAccuracy: 0.34058, RankingLoss: 0.27345, MacroPrecision: 0.48217, MacroRecall: 0.18432, MacroFOne: 0.26332,
pruning: False, include_original_features: with_org, averageAUROC: 0.5996586, HammingLoss: 0.31159, SubsetAccuracy: 0.16667, RankingLoss: 0.25918, MacroPrecision: 0.36289, MacroRecall: 0.40683, MacroFOne: 0.38068,
pruning: True, include_original_features: no_org, averageAUROC: 0.5944968, HammingLoss: 0.2343, SubsetAccuracy: 0.33333, RankingLoss: 0.29124, MacroPrecision: 0.52854, MacroRecall: 0.18779, MacroFOne: 0.2742,
pruning: False, include_original_features: no_org, averageAUROC: 0.6424365, HammingLoss: 0.30072, SubsetAccuracy: 0.14493, RankingLoss: 0.25572, MacroPrecision: 0.39798, MacroRecall: 0.50761, MacroFOne: 0.44059,

Fold 10/10 (CPI+fingerprint_low_freq 3/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [21:00<00:00,  1.70feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.6216943, HammingLoss: 0.23792, SubsetAccuracy: 0.3913, RankingLoss: 0.25215, MacroPrecision: 0.43774, MacroRecall: 0.17091, MacroFOne: 0.23275,
pruning: False, include_original_features: with_org, averageAUROC: 0.5960475, HammingLoss: 0.2971, SubsetAccuracy: 0.19565, RankingLoss: 0.22703, MacroPrecision: 0.37052, MacroRecall: 0.37684, MacroFOne: 0.35934,
pruning: True, include_original_features: no_org, averageAUROC: 0.6099653, HammingLoss: 0.24758, SubsetAccuracy: 0.38406, RankingLoss: 0.23362, MacroPrecision: 0.39866, MacroRecall: 0.17511, MacroFOne: 0.23313,
pruning: False, include_original_features: no_org, averageAUROC: 0.6056656, HammingLoss: 0.3128, SubsetAccuracy: 0.21739, RankingLoss: 0.21701, MacroPrecision: 0.34686, MacroRecall: 0.42094, MacroFOne: 0.37662,
   pruning include_original_features                   dataset  averageAUROC  \
0    False                    no_org  CPI+fingerprint_low_freq      0.603278
1    False                  with_org  CPI+fingerprint_low_freq      0.595582
2     True                    no_org  CPI+fingerprint_low_freq      0.599212
3     True                  with_org  CPI+fingerprint_low_freq      0.604060

   HammingLoss  SubsetAccuracy  RankingLoss  MacroPrecision  MacroRecall  \
0     0.325381        0.195224     0.261745        0.350776     0.425188
1     0.328374        0.194505     0.254029        0.343843     0.403306
2     0.245191        0.357351     0.273758        0.474642     0.160097
3     0.247228        0.358800     0.266515        0.458073     0.166366

   MacroFOne  nodes  leaves  groups  avg_group_features  gen_XofN_time  \
0   0.381005  864.4   432.7   430.0            4.993023    1257.513742
1   0.366116  850.6   425.8   430.0            4.993023    1257.513742
2   0.233264   53.4    27.2   430.0            4.993023    1257.513742
3   0.238512   67.2    34.1   430.0            4.993023    1257.513742

   training_time
0       1.274746
1       3.850259
2       1.274746
3       3.850259

--- Running with label:'['se_C0020538', 'se_C0008031', 'se_C0003467', 'se_C0036572', 'se_C0030252', 'se_C0027769']' training_algorithm:'Variance Reduction' eval_criterion:'['averageAUROC', 'HammingLoss', 'SubsetAccuracy', 'RankingLoss', 'MacroPrecision', 'MacroRecall', 'MacroFOne']' max_size:'5' ---
Logs can be found in XofN_filter_jaccard/logs/CPI+fingerprint_mid_freq_Variance Reduction_averageAUROC_HammingLoss_SubsetAccuracy_RankingLoss_MacroPrecision_MacroRecall_MacroFOne_5_logs.txt.

Fold 1/10 (CPI+fingerprint_mid_freq 4/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [21:00<00:00,  1.70feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.6787239, HammingLoss: 0.27698, SubsetAccuracy: 0.3741, RankingLoss: 0.22644, MacroPrecision: 0.56513, MacroRecall: 0.46033, MacroFOne: 0.5055,
pruning: False, include_original_features: with_org, averageAUROC: 0.614397, HammingLoss: 0.3693, SubsetAccuracy: 0.17986, RankingLoss: 0.23435, MacroPrecision: 0.42975, MacroRecall: 0.57239, MacroFOne: 0.48957,
pruning: True, include_original_features: no_org, averageAUROC: 0.6302866, HammingLoss: 0.29257, SubsetAccuracy: 0.36691, RankingLoss: 0.23871, MacroPrecision: 0.53851, MacroRecall: 0.38976, MacroFOne: 0.45118,
pruning: False, include_original_features: no_org, averageAUROC: 0.6286568, HammingLoss: 0.3705, SubsetAccuracy: 0.18705, RankingLoss: 0.23685, MacroPrecision: 0.42939, MacroRecall: 0.58102, MacroFOne: 0.49169,

Fold 2/10 (CPI+fingerprint_mid_freq 4/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [21:01<00:00,  1.70feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.6049425, HammingLoss: 0.3789, SubsetAccuracy: 0.2446, RankingLoss: 0.25733, MacroPrecision: 0.5393, MacroRecall: 0.42204, MacroFOne: 0.47211,
pruning: False, include_original_features: with_org, averageAUROC: 0.5847954, HammingLoss: 0.40647, SubsetAccuracy: 0.13669, RankingLoss: 0.2467, MacroPrecision: 0.50068, MacroRecall: 0.50507, MacroFOne: 0.5001,
pruning: True, include_original_features: no_org, averageAUROC: 0.5789428, HammingLoss: 0.39928, SubsetAccuracy: 0.23741, RankingLoss: 0.26423, MacroPrecision: 0.51381, MacroRecall: 0.45376, MacroFOne: 0.47821,
pruning: False, include_original_features: no_org, averageAUROC: 0.5619789, HammingLoss: 0.42926, SubsetAccuracy: 0.1295, RankingLoss: 0.24173, MacroPrecision: 0.47097, MacroRecall: 0.5334, MacroFOne: 0.49901,

Fold 3/10 (CPI+fingerprint_mid_freq 4/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [21:01<00:00,  1.70feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.5996186, HammingLoss: 0.38129, SubsetAccuracy: 0.20863, RankingLoss: 0.25532, MacroPrecision: 0.53685, MacroRecall: 0.37516, MacroFOne: 0.4392,
pruning: False, include_original_features: with_org, averageAUROC: 0.5624071, HammingLoss: 0.41966, SubsetAccuracy: 0.14388, RankingLoss: 0.26077, MacroPrecision: 0.47605, MacroRecall: 0.47191, MacroFOne: 0.47247,
pruning: True, include_original_features: no_org, averageAUROC: 0.6533287, HammingLoss: 0.35731, SubsetAccuracy: 0.23022, RankingLoss: 0.2252, MacroPrecision: 0.57514, MacroRecall: 0.43435, MacroFOne: 0.49399,
pruning: False, include_original_features: no_org, averageAUROC: 0.5938394, HammingLoss: 0.41487, SubsetAccuracy: 0.1295, RankingLoss: 0.23004, MacroPrecision: 0.48563, MacroRecall: 0.56367, MacroFOne: 0.52081,

Fold 4/10 (CPI+fingerprint_mid_freq 4/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [21:04<00:00,  1.70feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.5922797, HammingLoss: 0.35971, SubsetAccuracy: 0.2446, RankingLoss: 0.25949, MacroPrecision: 0.4512, MacroRecall: 0.32771, MacroFOne: 0.3779,
pruning: False, include_original_features: with_org, averageAUROC: 0.6144562, HammingLoss: 0.36451, SubsetAccuracy: 0.14388, RankingLoss: 0.23903, MacroPrecision: 0.46364, MacroRecall: 0.55166, MacroFOne: 0.50185,
pruning: True, include_original_features: no_org, averageAUROC: 0.5793642, HammingLoss: 0.34772, SubsetAccuracy: 0.26619, RankingLoss: 0.26863, MacroPrecision: 0.47796, MacroRecall: 0.37939, MacroFOne: 0.42111,
pruning: False, include_original_features: no_org, averageAUROC: 0.6011049, HammingLoss: 0.40048, SubsetAccuracy: 0.1295, RankingLoss: 0.23369, MacroPrecision: 0.41196, MacroRecall: 0.48311, MacroFOne: 0.44389,

Fold 5/10 (CPI+fingerprint_mid_freq 4/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [21:03<00:00,  1.70feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.5917086, HammingLoss: 0.35612, SubsetAccuracy: 0.22302, RankingLoss: 0.30342, MacroPrecision: 0.44767, MacroRecall: 0.34506, MacroFOne: 0.3847,
pruning: False, include_original_features: with_org, averageAUROC: 0.5902236, HammingLoss: 0.38489, SubsetAccuracy: 0.11511, RankingLoss: 0.28749, MacroPrecision: 0.42229, MacroRecall: 0.47038, MacroFOne: 0.44386,
pruning: True, include_original_features: no_org, averageAUROC: 0.6126851, HammingLoss: 0.34412, SubsetAccuracy: 0.2446, RankingLoss: 0.29107, MacroPrecision: 0.46563, MacroRecall: 0.35015, MacroFOne: 0.39723,
pruning: False, include_original_features: no_org, averageAUROC: 0.5868911, HammingLoss: 0.38129, SubsetAccuracy: 0.13669, RankingLoss: 0.30753, MacroPrecision: 0.41748, MacroRecall: 0.45442, MacroFOne: 0.43427,

Fold 6/10 (CPI+fingerprint_mid_freq 4/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [21:06<00:00,  1.69feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.6335445, HammingLoss: 0.34772, SubsetAccuracy: 0.29496, RankingLoss: 0.22584, MacroPrecision: 0.56098, MacroRecall: 0.39108, MacroFOne: 0.46071,
pruning: False, include_original_features: with_org, averageAUROC: 0.6127429, HammingLoss: 0.3789, SubsetAccuracy: 0.20863, RankingLoss: 0.24636, MacroPrecision: 0.5042, MacroRecall: 0.51038, MacroFOne: 0.50613,
pruning: True, include_original_features: no_org, averageAUROC: 0.6733656, HammingLoss: 0.32014, SubsetAccuracy: 0.30216, RankingLoss: 0.23114, MacroPrecision: 0.60476, MacroRecall: 0.46062, MacroFOne: 0.52246,
pruning: False, include_original_features: no_org, averageAUROC: 0.6212637, HammingLoss: 0.38369, SubsetAccuracy: 0.20144, RankingLoss: 0.24051, MacroPrecision: 0.49475, MacroRecall: 0.54217, MacroFOne: 0.51647,

Fold 7/10 (CPI+fingerprint_mid_freq 4/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [21:07<00:00,  1.69feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.5936854, HammingLoss: 0.34053, SubsetAccuracy: 0.27338, RankingLoss: 0.25072, MacroPrecision: 0.51267, MacroRecall: 0.28785, MacroFOne: 0.36844,
pruning: False, include_original_features: with_org, averageAUROC: 0.5799421, HammingLoss: 0.40408, SubsetAccuracy: 0.16547, RankingLoss: 0.24235, MacroPrecision: 0.42246, MacroRecall: 0.44687, MacroFOne: 0.43341,
pruning: True, include_original_features: no_org, averageAUROC: 0.5751518, HammingLoss: 0.34892, SubsetAccuracy: 0.28058, RankingLoss: 0.24357, MacroPrecision: 0.49351, MacroRecall: 0.2884, MacroFOne: 0.3635,
pruning: False, include_original_features: no_org, averageAUROC: 0.5933809, HammingLoss: 0.38609, SubsetAccuracy: 0.13669, RankingLoss: 0.25084, MacroPrecision: 0.43891, MacroRecall: 0.47548, MacroFOne: 0.45549,

Fold 8/10 (CPI+fingerprint_mid_freq 4/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [21:07<00:00,  1.69feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.6107391, HammingLoss: 0.3765, SubsetAccuracy: 0.22302, RankingLoss: 0.26299, MacroPrecision: 0.53719, MacroRecall: 0.37615, MacroFOne: 0.44099,
pruning: False, include_original_features: with_org, averageAUROC: 0.5793815, HammingLoss: 0.42326, SubsetAccuracy: 0.13669, RankingLoss: 0.27782, MacroPrecision: 0.46879, MacroRecall: 0.51482, MacroFOne: 0.48981,
pruning: True, include_original_features: no_org, averageAUROC: 0.5646892, HammingLoss: 0.41007, SubsetAccuracy: 0.19424, RankingLoss: 0.3191, MacroPrecision: 0.47309, MacroRecall: 0.33149, MacroFOne: 0.38867,
pruning: False, include_original_features: no_org, averageAUROC: 0.5553009, HammingLoss: 0.44005, SubsetAccuracy: 0.11511, RankingLoss: 0.2995, MacroPrecision: 0.44266, MacroRecall: 0.44351, MacroFOne: 0.44186,

Fold 9/10 (CPI+fingerprint_mid_freq 4/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [21:09<00:00,  1.69feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.5843622, HammingLoss: 0.39448, SubsetAccuracy: 0.17266, RankingLoss: 0.29129, MacroPrecision: 0.50164, MacroRecall: 0.35003, MacroFOne: 0.40897,
pruning: False, include_original_features: with_org, averageAUROC: 0.6009481, HammingLoss: 0.41247, SubsetAccuracy: 0.13669, RankingLoss: 0.28621, MacroPrecision: 0.47964, MacroRecall: 0.55201, MacroFOne: 0.51253,
pruning: True, include_original_features: no_org, averageAUROC: 0.6362491, HammingLoss: 0.35252, SubsetAccuracy: 0.20144, RankingLoss: 0.29027, MacroPrecision: 0.5774, MacroRecall: 0.38007, MacroFOne: 0.45671,
pruning: False, include_original_features: no_org, averageAUROC: 0.633067, HammingLoss: 0.3753, SubsetAccuracy: 0.093525, RankingLoss: 0.2721, MacroPrecision: 0.51966, MacroRecall: 0.55475, MacroFOne: 0.53604,

Fold 10/10 (CPI+fingerprint_mid_freq 4/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [21:11<00:00,  1.69feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.6057438, HammingLoss: 0.36957, SubsetAccuracy: 0.25362, RankingLoss: 0.24861, MacroPrecision: 0.51242, MacroRecall: 0.31429, MacroFOne: 0.38886,
pruning: False, include_original_features: with_org, averageAUROC: 0.606216, HammingLoss: 0.39493, SubsetAccuracy: 0.15217, RankingLoss: 0.25193, MacroPrecision: 0.47862, MacroRecall: 0.52386, MacroFOne: 0.49836,
pruning: True, include_original_features: no_org, averageAUROC: 0.624636, HammingLoss: 0.3442, SubsetAccuracy: 0.26087, RankingLoss: 0.24847, MacroPrecision: 0.55688, MacroRecall: 0.40399, MacroFOne: 0.46729,
pruning: False, include_original_features: no_org, averageAUROC: 0.6092035, HammingLoss: 0.39493, SubsetAccuracy: 0.10145, RankingLoss: 0.23178, MacroPrecision: 0.47873, MacroRecall: 0.56521, MacroFOne: 0.51702,
   pruning include_original_features                   dataset  averageAUROC  \
0    False                    no_org  CPI+fingerprint_mid_freq      0.598469
1    False                  with_org  CPI+fingerprint_mid_freq      0.594551
2     True                    no_org  CPI+fingerprint_mid_freq      0.612870
3     True                  with_org  CPI+fingerprint_mid_freq      0.609535

   HammingLoss  SubsetAccuracy  RankingLoss  MacroPrecision  MacroRecall  \
0     0.397646        0.136045     0.254457        0.459014     0.519674
1     0.395847        0.151907     0.257301        0.464612     0.511935
2     0.351685        0.258462     0.262039        0.527669     0.387198
3     0.358180        0.251259     0.258145        0.516505     0.364970

   MacroFOne  nodes  leaves  groups  avg_group_features  gen_XofN_time  \
0   0.485655  895.6   448.3   430.0            4.993023    1265.490809
1   0.484809  887.0   444.0   430.0            4.993023    1265.490809
2   0.444035  157.8    79.4   430.0            4.993023    1265.490809
3   0.424738  159.0    80.0   430.0            4.993023    1265.490809

   training_time
0       1.150093
1       3.536142
2       1.150093
3       3.536142

--- Running with label:'['se_C0016382', 'se_C0018799', 'se_C0003811', 'se_C0428977', 'se_C0027051', 'se_C0018790']' training_algorithm:'Variance Reduction' eval_criterion:'['averageAUROC', 'HammingLoss', 'SubsetAccuracy', 'RankingLoss', 'MacroPrecision', 'MacroRecall', 'MacroFOne']' max_size:'5' ---
Logs can be found in XofN_filter_jaccard/logs/CPI_cardiac_Variance Reduction_averageAUROC_HammingLoss_SubsetAccuracy_RankingLoss_MacroPrecision_MacroRecall_MacroFOne_5_logs.txt.

Fold 1/10 (CPI_cardiac 5/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:40<00:00,  1.96feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.5743877, HammingLoss: 0.2753, SubsetAccuracy: 0.375, RankingLoss: 0.22537, MacroPrecision: 0.4787, MacroRecall: 0.1939, MacroFOne: 0.27213,
pruning: False, include_original_features: with_org, averageAUROC: 0.596207, HammingLoss: 0.35565, SubsetAccuracy: 0.22321, RankingLoss: 0.23552, MacroPrecision: 0.36151, MacroRecall: 0.45617, MacroFOne: 0.40053,
pruning: True, include_original_features: no_org, averageAUROC: 0.5783442, HammingLoss: 0.26935, SubsetAccuracy: 0.375, RankingLoss: 0.21476, MacroPrecision: 0.50741, MacroRecall: 0.18013, MacroFOne: 0.2608,
pruning: False, include_original_features: no_org, averageAUROC: 0.6041629, HammingLoss: 0.31548, SubsetAccuracy: 0.25, RankingLoss: 0.23375, MacroPrecision: 0.4116, MacroRecall: 0.44248, MacroFOne: 0.42468,

Fold 2/10 (CPI_cardiac 5/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:40<00:00,  1.96feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.5607813, HammingLoss: 0.28571, SubsetAccuracy: 0.33036, RankingLoss: 0.19568, MacroPrecision: 0.36566, MacroRecall: 0.16316, MacroFOne: 0.22296,
pruning: False, include_original_features: with_org, averageAUROC: 0.571651, HammingLoss: 0.34226, SubsetAccuracy: 0.17857, RankingLoss: 0.22512, MacroPrecision: 0.36468, MacroRecall: 0.43753, MacroFOne: 0.39157,
pruning: True, include_original_features: no_org, averageAUROC: 0.5860837, HammingLoss: 0.27232, SubsetAccuracy: 0.34821, RankingLoss: 0.19301, MacroPrecision: 0.43074, MacroRecall: 0.18735, MacroFOne: 0.25841,
pruning: False, include_original_features: no_org, averageAUROC: 0.596384, HammingLoss: 0.35268, SubsetAccuracy: 0.16071, RankingLoss: 0.22391, MacroPrecision: 0.36046, MacroRecall: 0.49295, MacroFOne: 0.40992,

Fold 3/10 (CPI_cardiac 5/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:40<00:00,  1.96feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.5932108, HammingLoss: 0.28274, SubsetAccuracy: 0.28571, RankingLoss: 0.25553, MacroPrecision: 0.57073, MacroRecall: 0.19711, MacroFOne: 0.29072,
pruning: False, include_original_features: with_org, averageAUROC: 0.6032049, HammingLoss: 0.35268, SubsetAccuracy: 0.16071, RankingLoss: 0.24392, MacroPrecision: 0.3938, MacroRecall: 0.43115, MacroFOne: 0.40708,
pruning: True, include_original_features: no_org, averageAUROC: 0.6058852, HammingLoss: 0.28571, SubsetAccuracy: 0.28571, RankingLoss: 0.24499, MacroPrecision: 0.555, MacroRecall: 0.20869, MacroFOne: 0.29768,
pruning: False, include_original_features: no_org, averageAUROC: 0.5789634, HammingLoss: 0.34821, SubsetAccuracy: 0.14286, RankingLoss: 0.2686, MacroPrecision: 0.40951, MacroRecall: 0.43233, MacroFOne: 0.41796,

Fold 4/10 (CPI_cardiac 5/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:42<00:00,  1.95feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.604801, HammingLoss: 0.24405, SubsetAccuracy: 0.33929, RankingLoss: 0.25841, MacroPrecision: 0.47546, MacroRecall: 0.18692, MacroFOne: 0.26332,
pruning: False, include_original_features: with_org, averageAUROC: 0.5604904, HammingLoss: 0.31399, SubsetAccuracy: 0.26786, RankingLoss: 0.25424, MacroPrecision: 0.34808, MacroRecall: 0.38728, MacroFOne: 0.36522,
pruning: True, include_original_features: no_org, averageAUROC: 0.6073709, HammingLoss: 0.23363, SubsetAccuracy: 0.33929, RankingLoss: 0.23495, MacroPrecision: 0.54762, MacroRecall: 0.23079, MacroFOne: 0.32409,
pruning: False, include_original_features: no_org, averageAUROC: 0.6109237, HammingLoss: 0.3378, SubsetAccuracy: 0.16071, RankingLoss: 0.27463, MacroPrecision: 0.36647, MacroRecall: 0.50357, MacroFOne: 0.41849,

Fold 5/10 (CPI_cardiac 5/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:41<00:00,  1.96feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.58676, HammingLoss: 0.27827, SubsetAccuracy: 0.34821, RankingLoss: 0.22433, MacroPrecision: 0.48697, MacroRecall: 0.19078, MacroFOne: 0.2714,
pruning: False, include_original_features: with_org, averageAUROC: 0.5733316, HammingLoss: 0.36458, SubsetAccuracy: 0.1875, RankingLoss: 0.26257, MacroPrecision: 0.36396, MacroRecall: 0.42254, MacroFOne: 0.38972,
pruning: True, include_original_features: no_org, averageAUROC: 0.6191207, HammingLoss: 0.2753, SubsetAccuracy: 0.35714, RankingLoss: 0.21704, MacroPrecision: 0.49396, MacroRecall: 0.18404, MacroFOne: 0.26742,
pruning: False, include_original_features: no_org, averageAUROC: 0.6016894, HammingLoss: 0.32143, SubsetAccuracy: 0.22321, RankingLoss: 0.23663, MacroPrecision: 0.41165, MacroRecall: 0.42628, MacroFOne: 0.41773,

Fold 6/10 (CPI_cardiac 5/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:43<00:00,  1.95feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.5226016, HammingLoss: 0.31399, SubsetAccuracy: 0.32143, RankingLoss: 0.27376, MacroPrecision: 0.37163, MacroRecall: 0.11845, MacroFOne: 0.17663,
pruning: False, include_original_features: with_org, averageAUROC: 0.5504246, HammingLoss: 0.35417, SubsetAccuracy: 0.1875, RankingLoss: 0.26193, MacroPrecision: 0.37301, MacroRecall: 0.30857, MacroFOne: 0.33347,
pruning: True, include_original_features: no_org, averageAUROC: 0.5161228, HammingLoss: 0.30804, SubsetAccuracy: 0.33036, RankingLoss: 0.2779, MacroPrecision: 0.40741, MacroRecall: 0.14159, MacroFOne: 0.20704,
pruning: False, include_original_features: no_org, averageAUROC: 0.5504984, HammingLoss: 0.35417, SubsetAccuracy: 0.1875, RankingLoss: 0.28209, MacroPrecision: 0.38455, MacroRecall: 0.39959, MacroFOne: 0.38532,

Fold 7/10 (CPI_cardiac 5/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:42<00:00,  1.95feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.608742, HammingLoss: 0.26786, SubsetAccuracy: 0.42857, RankingLoss: 0.2411, MacroPrecision: 0.36656, MacroRecall: 0.24699, MacroFOne: 0.29269,
pruning: False, include_original_features: with_org, averageAUROC: 0.598004, HammingLoss: 0.27232, SubsetAccuracy: 0.34821, RankingLoss: 0.2158, MacroPrecision: 0.41388, MacroRecall: 0.45359, MacroFOne: 0.42803,
pruning: True, include_original_features: no_org, averageAUROC: 0.6082357, HammingLoss: 0.26488, SubsetAccuracy: 0.41964, RankingLoss: 0.25595, MacroPrecision: 0.37607, MacroRecall: 0.25056, MacroFOne: 0.29749,
pruning: False, include_original_features: no_org, averageAUROC: 0.5644374, HammingLoss: 0.34524, SubsetAccuracy: 0.24107, RankingLoss: 0.22577, MacroPrecision: 0.32363, MacroRecall: 0.47963, MacroFOne: 0.38256,

Fold 8/10 (CPI_cardiac 5/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:19<00:00,  2.01feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.5979896, HammingLoss: 0.21875, SubsetAccuracy: 0.42857, RankingLoss: 0.21446, MacroPrecision: 0.53222, MacroRecall: 0.26781, MacroFOne: 0.35253,
pruning: False, include_original_features: with_org, averageAUROC: 0.5786916, HammingLoss: 0.32887, SubsetAccuracy: 0.22321, RankingLoss: 0.22463, MacroPrecision: 0.32333, MacroRecall: 0.44516, MacroFOne: 0.3676,
pruning: True, include_original_features: no_org, averageAUROC: 0.607504, HammingLoss: 0.23065, SubsetAccuracy: 0.42857, RankingLoss: 0.21369, MacroPrecision: 0.45598, MacroRecall: 0.21222, MacroFOne: 0.28714,
pruning: False, include_original_features: no_org, averageAUROC: 0.6090673, HammingLoss: 0.3497, SubsetAccuracy: 0.20536, RankingLoss: 0.18487, MacroPrecision: 0.32867, MacroRecall: 0.5359, MacroFOne: 0.4047,

Fold 9/10 (CPI_cardiac 5/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:32<00:00,  1.98feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.5289156, HammingLoss: 0.29911, SubsetAccuracy: 0.26786, RankingLoss: 0.253, MacroPrecision: 0.35793, MacroRecall: 0.1451, MacroFOne: 0.0,
pruning: False, include_original_features: with_org, averageAUROC: 0.4667227, HammingLoss: 0.3869, SubsetAccuracy: 0.17857, RankingLoss: 0.24876, MacroPrecision: 0.29787, MacroRecall: 0.31716, MacroFOne: 0.30463,
pruning: True, include_original_features: no_org, averageAUROC: 0.5684579, HammingLoss: 0.29911, SubsetAccuracy: 0.26786, RankingLoss: 0.25856, MacroPrecision: 0.3919, MacroRecall: 0.17828, MacroFOne: 0.23624,
pruning: False, include_original_features: no_org, averageAUROC: 0.4943689, HammingLoss: 0.39732, SubsetAccuracy: 0.1875, RankingLoss: 0.27173, MacroPrecision: 0.29255, MacroRecall: 0.33336, MacroFOne: 0.30866,

Fold 10/10 (CPI_cardiac 5/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:47<00:00,  1.94feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.5093273, HammingLoss: 0.34077, SubsetAccuracy: 0.26786, RankingLoss: 0.21037, MacroPrecision: 0.40146, MacroRecall: 0.10726, MacroFOne: 0.0,
pruning: False, include_original_features: with_org, averageAUROC: 0.581809, HammingLoss: 0.38244, SubsetAccuracy: 0.16964, RankingLoss: 0.23271, MacroPrecision: 0.40554, MacroRecall: 0.42761, MacroFOne: 0.41413,
pruning: True, include_original_features: no_org, averageAUROC: 0.5027865, HammingLoss: 0.34524, SubsetAccuracy: 0.26786, RankingLoss: 0.206, MacroPrecision: 0.40366, MacroRecall: 0.10468, MacroFOne: 0.16561,
pruning: False, include_original_features: no_org, averageAUROC: 0.564819, HammingLoss: 0.37649, SubsetAccuracy: 0.16071, RankingLoss: 0.24546, MacroPrecision: 0.42037, MacroRecall: 0.45331, MacroFOne: 0.43208,
   pruning include_original_features      dataset  averageAUROC  HammingLoss  \
0    False                    no_org  CPI_cardiac      0.577531     0.349852
1    False                  with_org  CPI_cardiac      0.568054     0.345386
2     True                    no_org  CPI_cardiac      0.579991     0.278423
3     True                  with_org  CPI_cardiac      0.568752     0.280655

   SubsetAccuracy  RankingLoss  MacroPrecision  MacroRecall  MacroFOne  nodes  \
0        0.191963     0.244744        0.370946     0.449940   0.400210  681.4
1        0.212498     0.240520        0.364566     0.408676   0.380198  691.0
2        0.341964     0.231685        0.456975     0.187833   0.260192   54.8
3        0.339286     0.235201        0.440732     0.181748   0.214238   58.2

   leaves  groups  avg_group_features  gen_XofN_time  training_time
0   341.2   322.0            4.990683     819.026572       0.951930
1   346.0   322.0            4.990683     819.026572       2.733522
2    27.9   322.0            4.990683     819.026572       0.951930
3    29.6   322.0            4.990683     819.026572       2.733522

--- Running with label:'['se_C0027497', 'se_C0018681', 'se_C0011603', 'se_C0015230', 'se_C0042963', 'se_C0012833']' training_algorithm:'Variance Reduction' eval_criterion:'['averageAUROC', 'HammingLoss', 'SubsetAccuracy', 'RankingLoss', 'MacroPrecision', 'MacroRecall', 'MacroFOne']' max_size:'5' ---
Logs can be found in XofN_filter_jaccard/logs/CPI_high_freq_Variance Reduction_averageAUROC_HammingLoss_SubsetAccuracy_RankingLoss_MacroPrecision_MacroRecall_MacroFOne_5_logs.txt.

Fold 1/10 (CPI_high_freq 6/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:46<00:00,  1.95feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.627651, HammingLoss: 0.20387, SubsetAccuracy: 0.59821, RankingLoss: 0.1151, MacroPrecision: 0.80783, MacroRecall: 0.97781, MacroFOne: 0.88374,
pruning: False, include_original_features: with_org, averageAUROC: 0.5690092, HammingLoss: 0.25446, SubsetAccuracy: 0.47321, RankingLoss: 0.13341, MacroPrecision: 0.80531, MacroRecall: 0.89419, MacroFOne: 0.84691,
pruning: True, include_original_features: no_org, averageAUROC: 0.6248753, HammingLoss: 0.20685, SubsetAccuracy: 0.59821, RankingLoss: 0.11689, MacroPrecision: 0.80428, MacroRecall: 0.97972, MacroFOne: 0.88248,
pruning: False, include_original_features: no_org, averageAUROC: 0.6122662, HammingLoss: 0.24702, SubsetAccuracy: 0.4375, RankingLoss: 0.1216, MacroPrecision: 0.81167, MacroRecall: 0.89616, MacroFOne: 0.85122,

Fold 2/10 (CPI_high_freq 6/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:47<00:00,  1.94feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.5, HammingLoss: 0.16667, SubsetAccuracy: 0.57143, RankingLoss: 0.17619, MacroPrecision: 0.83333, MacroRecall: 1.0, MacroFOne: 0.90868,
pruning: False, include_original_features: with_org, averageAUROC: 0.5539546, HammingLoss: 0.21429, SubsetAccuracy: 0.42857, RankingLoss: 0.15833, MacroPrecision: 0.84059, MacroRecall: 0.91267, MacroFOne: 0.87501,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.16667, SubsetAccuracy: 0.57143, RankingLoss: 0.17619, MacroPrecision: 0.83333, MacroRecall: 1.0, MacroFOne: 0.90868,
pruning: False, include_original_features: no_org, averageAUROC: 0.5642012, HammingLoss: 0.20833, SubsetAccuracy: 0.41964, RankingLoss: 0.16376, MacroPrecision: 0.84329, MacroRecall: 0.91854, MacroFOne: 0.87908,

Fold 3/10 (CPI_high_freq 6/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:45<00:00,  1.95feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.623578, HammingLoss: 0.22619, SubsetAccuracy: 0.55357, RankingLoss: 0.15203, MacroPrecision: 0.81624, MacroRecall: 0.93216, MacroFOne: 0.86917,
pruning: False, include_original_features: with_org, averageAUROC: 0.5711619, HammingLoss: 0.25298, SubsetAccuracy: 0.44643, RankingLoss: 0.16481, MacroPrecision: 0.82059, MacroRecall: 0.87417, MacroFOne: 0.84624,
pruning: True, include_original_features: no_org, averageAUROC: 0.5852769, HammingLoss: 0.20982, SubsetAccuracy: 0.57143, RankingLoss: 0.14563, MacroPrecision: 0.81193, MacroRecall: 0.96701, MacroFOne: 0.88133,
pruning: False, include_original_features: no_org, averageAUROC: 0.5818713, HammingLoss: 0.22173, SubsetAccuracy: 0.5, RankingLoss: 0.14591, MacroPrecision: 0.83283, MacroRecall: 0.90392, MacroFOne: 0.86652,

Fold 4/10 (CPI_high_freq 6/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:49<00:00,  1.94feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.6030497, HammingLoss: 0.18619, SubsetAccuracy: 0.57658, RankingLoss: 0.12825, MacroPrecision: 0.82211, MacroRecall: 0.9814, MacroFOne: 0.89395,
pruning: False, include_original_features: with_org, averageAUROC: 0.6357708, HammingLoss: 0.21772, SubsetAccuracy: 0.47748, RankingLoss: 0.1022, MacroPrecision: 0.84486, MacroRecall: 0.89047, MacroFOne: 0.86686,
pruning: True, include_original_features: no_org, averageAUROC: 0.6033985, HammingLoss: 0.18919, SubsetAccuracy: 0.56757, RankingLoss: 0.12668, MacroPrecision: 0.82168, MacroRecall: 0.97783, MacroFOne: 0.89214,
pruning: False, include_original_features: no_org, averageAUROC: 0.6472737, HammingLoss: 0.22823, SubsetAccuracy: 0.43243, RankingLoss: 0.11451, MacroPrecision: 0.84748, MacroRecall: 0.86951, MacroFOne: 0.85795,

Fold 5/10 (CPI_high_freq 6/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:48<00:00,  1.94feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.6213154, HammingLoss: 0.22823, SubsetAccuracy: 0.45946, RankingLoss: 0.20273, MacroPrecision: 0.78222, MacroRecall: 0.98048, MacroFOne: 0.86906,
pruning: False, include_original_features: with_org, averageAUROC: 0.5867241, HammingLoss: 0.26727, SubsetAccuracy: 0.38739, RankingLoss: 0.1994, MacroPrecision: 0.79808, MacroRecall: 0.87943, MacroFOne: 0.8353,
pruning: True, include_original_features: no_org, averageAUROC: 0.6240455, HammingLoss: 0.23123, SubsetAccuracy: 0.45045, RankingLoss: 0.19935, MacroPrecision: 0.78663, MacroRecall: 0.96517, MacroFOne: 0.86571,
pruning: False, include_original_features: no_org, averageAUROC: 0.584572, HammingLoss: 0.26426, SubsetAccuracy: 0.37838, RankingLoss: 0.20773, MacroPrecision: 0.78505, MacroRecall: 0.90594, MacroFOne: 0.8405,

Fold 6/10 (CPI_high_freq 6/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:48<00:00,  1.94feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.5684129, HammingLoss: 0.23724, SubsetAccuracy: 0.47748, RankingLoss: 0.20215, MacroPrecision: 0.7675, MacroRecall: 0.99239, MacroFOne: 0.86482,
pruning: False, include_original_features: with_org, averageAUROC: 0.5690927, HammingLoss: 0.27327, SubsetAccuracy: 0.36937, RankingLoss: 0.18188, MacroPrecision: 0.76851, MacroRecall: 0.91852, MacroFOne: 0.83661,
pruning: True, include_original_features: no_org, averageAUROC: 0.5017333, HammingLoss: 0.23724, SubsetAccuracy: 0.47748, RankingLoss: 0.21096, MacroPrecision: 0.7675, MacroRecall: 0.99239, MacroFOne: 0.86482,
pruning: False, include_original_features: no_org, averageAUROC: 0.5553341, HammingLoss: 0.26727, SubsetAccuracy: 0.37838, RankingLoss: 0.20563, MacroPrecision: 0.77352, MacroRecall: 0.92183, MacroFOne: 0.8406,

Fold 7/10 (CPI_high_freq 6/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:48<00:00,  1.94feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.5693921, HammingLoss: 0.2012, SubsetAccuracy: 0.54054, RankingLoss: 0.17775, MacroPrecision: 0.81518, MacroRecall: 0.97195, MacroFOne: 0.88658,
pruning: False, include_original_features: with_org, averageAUROC: 0.5423967, HammingLoss: 0.23273, SubsetAccuracy: 0.47748, RankingLoss: 0.16409, MacroPrecision: 0.81932, MacroRecall: 0.91481, MacroFOne: 0.86427,
pruning: True, include_original_features: no_org, averageAUROC: 0.5440744, HammingLoss: 0.21622, SubsetAccuracy: 0.53153, RankingLoss: 0.17467, MacroPrecision: 0.80866, MacroRecall: 0.96109, MacroFOne: 0.87797,
pruning: False, include_original_features: no_org, averageAUROC: 0.5814643, HammingLoss: 0.21622, SubsetAccuracy: 0.47748, RankingLoss: 0.14417, MacroPrecision: 0.83838, MacroRecall: 0.90925, MacroFOne: 0.87167,

Fold 8/10 (CPI_high_freq 6/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:48<00:00,  1.94feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.6657623, HammingLoss: 0.24174, SubsetAccuracy: 0.5045, RankingLoss: 0.15283, MacroPrecision: 0.78741, MacroRecall: 0.93247, MacroFOne: 0.85337,
pruning: False, include_original_features: with_org, averageAUROC: 0.5938931, HammingLoss: 0.30781, SubsetAccuracy: 0.36937, RankingLoss: 0.15358, MacroPrecision: 0.7712, MacroRecall: 0.83726, MacroFOne: 0.80255,
pruning: True, include_original_features: no_org, averageAUROC: 0.5518498, HammingLoss: 0.24775, SubsetAccuracy: 0.5045, RankingLoss: 0.15485, MacroPrecision: 0.77412, MacroRecall: 0.95025, MacroFOne: 0.85271,
pruning: False, include_original_features: no_org, averageAUROC: 0.5838221, HammingLoss: 0.2958, SubsetAccuracy: 0.36937, RankingLoss: 0.14387, MacroPrecision: 0.77128, MacroRecall: 0.86413, MacroFOne: 0.8149,

Fold 9/10 (CPI_high_freq 6/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:49<00:00,  1.94feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.6084787, HammingLoss: 0.22222, SubsetAccuracy: 0.52252, RankingLoss: 0.16514, MacroPrecision: 0.79443, MacroRecall: 0.96527, MacroFOne: 0.87095,
pruning: False, include_original_features: with_org, averageAUROC: 0.5944508, HammingLoss: 0.25225, SubsetAccuracy: 0.43243, RankingLoss: 0.18661, MacroPrecision: 0.7982, MacroRecall: 0.90604, MacroFOne: 0.84818,
pruning: True, include_original_features: no_org, averageAUROC: 0.5169691, HammingLoss: 0.23574, SubsetAccuracy: 0.52252, RankingLoss: 0.15936, MacroPrecision: 0.78561, MacroRecall: 0.95898, MacroFOne: 0.86325,
pruning: False, include_original_features: no_org, averageAUROC: 0.597882, HammingLoss: 0.26276, SubsetAccuracy: 0.44144, RankingLoss: 0.20455, MacroPrecision: 0.79743, MacroRecall: 0.88779, MacroFOne: 0.83976,

Fold 10/10 (CPI_high_freq 6/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:48<00:00,  1.94feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.6587065, HammingLoss: 0.22823, SubsetAccuracy: 0.54054, RankingLoss: 0.13829, MacroPrecision: 0.77374, MacroRecall: 0.98173, MacroFOne: 0.86494,
pruning: False, include_original_features: with_org, averageAUROC: 0.6440477, HammingLoss: 0.27778, SubsetAccuracy: 0.43243, RankingLoss: 0.18483, MacroPrecision: 0.76786, MacroRecall: 0.89901, MacroFOne: 0.82807,
pruning: True, include_original_features: no_org, averageAUROC: 0.6423098, HammingLoss: 0.24474, SubsetAccuracy: 0.53153, RankingLoss: 0.13986, MacroPrecision: 0.76706, MacroRecall: 0.96554, MacroFOne: 0.85451,
pruning: False, include_original_features: no_org, averageAUROC: 0.6096006, HammingLoss: 0.2973, SubsetAccuracy: 0.38739, RankingLoss: 0.1738, MacroPrecision: 0.76195, MacroRecall: 0.8751, MacroFOne: 0.81426,
   pruning include_original_features        dataset  averageAUROC  \
0    False                    no_org  CPI_high_freq      0.591829
1    False                  with_org  CPI_high_freq      0.586050
2     True                    no_org  CPI_high_freq      0.569453
3     True                  with_org  CPI_high_freq      0.604635

   HammingLoss  SubsetAccuracy  RankingLoss  MacroPrecision  MacroRecall  \
0     0.250892        0.422201     0.162553        0.806288     0.895217
1     0.255056        0.429416     0.162914        0.803452     0.892657
2     0.218545        0.532665     0.160444        0.796080     0.971798
3     0.214178        0.534483     0.161046        0.799999     0.971566

   MacroFOne  nodes  leaves  groups  avg_group_features  gen_XofN_time  \
0   0.847646  424.2   212.6   322.0            4.990683     828.051776
1   0.845000  442.8   221.9   322.0            4.990683     828.051776
2   0.874360   21.2    11.1   322.0            4.990683     828.051776
3   0.876526   33.0    17.0   322.0            4.990683     828.051776

   training_time
0       0.894655
1       2.588701
2       0.894655
3       2.588701

--- Running with label:'['se_C0020580', 'se_C0267792', 'se_C0018524', 'se_C0031117', 'se_C0035078', 'se_C0011570']' training_algorithm:'Variance Reduction' eval_criterion:'['averageAUROC', 'HammingLoss', 'SubsetAccuracy', 'RankingLoss', 'MacroPrecision', 'MacroRecall', 'MacroFOne']' max_size:'5' ---
Logs can be found in XofN_filter_jaccard/logs/CPI_low_freq_Variance Reduction_averageAUROC_HammingLoss_SubsetAccuracy_RankingLoss_MacroPrecision_MacroRecall_MacroFOne_5_logs.txt.

Fold 1/10 (CPI_low_freq 7/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:49<00:00,  1.94feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.5818091, HammingLoss: 0.28125, SubsetAccuracy: 0.33929, RankingLoss: 0.25506, MacroPrecision: 0.38762, MacroRecall: 0.17034, MacroFOne: 0.22906,
pruning: False, include_original_features: with_org, averageAUROC: 0.6060505, HammingLoss: 0.31101, SubsetAccuracy: 0.16964, RankingLoss: 0.27111, MacroPrecision: 0.39582, MacroRecall: 0.44779, MacroFOne: 0.41656,
pruning: True, include_original_features: no_org, averageAUROC: 0.5646563, HammingLoss: 0.25893, SubsetAccuracy: 0.34821, RankingLoss: 0.27569, MacroPrecision: 0.47077, MacroRecall: 0.13989, MacroFOne: 0.21174,
pruning: False, include_original_features: no_org, averageAUROC: 0.5923379, HammingLoss: 0.31548, SubsetAccuracy: 0.19643, RankingLoss: 0.26394, MacroPrecision: 0.37872, MacroRecall: 0.40604, MacroFOne: 0.38977,

Fold 2/10 (CPI_low_freq 7/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:48<00:00,  1.94feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.5551504, HammingLoss: 0.27679, SubsetAccuracy: 0.35714, RankingLoss: 0.29551, MacroPrecision: 0.36724, MacroRecall: 0.17115, MacroFOne: 0.2311,
pruning: False, include_original_features: with_org, averageAUROC: 0.6170352, HammingLoss: 0.31399, SubsetAccuracy: 0.24107, RankingLoss: 0.24983, MacroPrecision: 0.37091, MacroRecall: 0.41336, MacroFOne: 0.38834,
pruning: True, include_original_features: no_org, averageAUROC: 0.5501036, HammingLoss: 0.28423, SubsetAccuracy: 0.36607, RankingLoss: 0.26912, MacroPrecision: 0.32609, MacroRecall: 0.1342, MacroFOne: 0.0,
pruning: False, include_original_features: no_org, averageAUROC: 0.575802, HammingLoss: 0.33482, SubsetAccuracy: 0.22321, RankingLoss: 0.24469, MacroPrecision: 0.33052, MacroRecall: 0.37893, MacroFOne: 0.35198,

Fold 3/10 (CPI_low_freq 7/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:49<00:00,  1.94feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.5681237, HammingLoss: 0.24702, SubsetAccuracy: 0.33929, RankingLoss: 0.29715, MacroPrecision: 0.33224, MacroRecall: 0.12637, MacroFOne: 0.17992,
pruning: False, include_original_features: with_org, averageAUROC: 0.5426382, HammingLoss: 0.36012, SubsetAccuracy: 0.15179, RankingLoss: 0.2686, MacroPrecision: 0.28006, MacroRecall: 0.40566, MacroFOne: 0.33019,
pruning: True, include_original_features: no_org, averageAUROC: 0.5592675, HammingLoss: 0.25149, SubsetAccuracy: 0.33929, RankingLoss: 0.29878, MacroPrecision: 0.34609, MacroRecall: 0.14709, MacroFOne: 0.0,
pruning: False, include_original_features: no_org, averageAUROC: 0.5910722, HammingLoss: 0.32292, SubsetAccuracy: 0.20536, RankingLoss: 0.21528, MacroPrecision: 0.31312, MacroRecall: 0.41889, MacroFOne: 0.35672,

Fold 4/10 (CPI_low_freq 7/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:49<00:00,  1.94feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.6520963, HammingLoss: 0.23958, SubsetAccuracy: 0.33929, RankingLoss: 0.30015, MacroPrecision: 0.61808, MacroRecall: 0.26706, MacroFOne: 0.37263,
pruning: False, include_original_features: with_org, averageAUROC: 0.6076158, HammingLoss: 0.30952, SubsetAccuracy: 0.16964, RankingLoss: 0.26694, MacroPrecision: 0.42416, MacroRecall: 0.43938, MacroFOne: 0.42856,
pruning: True, include_original_features: no_org, averageAUROC: 0.5788588, HammingLoss: 0.26042, SubsetAccuracy: 0.32143, RankingLoss: 0.31873, MacroPrecision: 0.53519, MacroRecall: 0.14627, MacroFOne: 0.22747,
pruning: False, include_original_features: no_org, averageAUROC: 0.6184981, HammingLoss: 0.29911, SubsetAccuracy: 0.1875, RankingLoss: 0.27351, MacroPrecision: 0.43084, MacroRecall: 0.43127, MacroFOne: 0.42873,

Fold 5/10 (CPI_low_freq 7/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:50<00:00,  1.94feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.6229871, HammingLoss: 0.26786, SubsetAccuracy: 0.27679, RankingLoss: 0.3034, MacroPrecision: 0.54488, MacroRecall: 0.20181, MacroFOne: 0.29335,
pruning: False, include_original_features: with_org, averageAUROC: 0.5828258, HammingLoss: 0.35565, SubsetAccuracy: 0.17857, RankingLoss: 0.31034, MacroPrecision: 0.36673, MacroRecall: 0.41248, MacroFOne: 0.38448,
pruning: True, include_original_features: no_org, averageAUROC: 0.5896263, HammingLoss: 0.27679, SubsetAccuracy: 0.29464, RankingLoss: 0.3315, MacroPrecision: 0.45817, MacroRecall: 0.16407, MacroFOne: 0.23691,
pruning: False, include_original_features: no_org, averageAUROC: 0.556787, HammingLoss: 0.36458, SubsetAccuracy: 0.11607, RankingLoss: 0.31141, MacroPrecision: 0.35534, MacroRecall: 0.39966, MacroFOne: 0.37286,

Fold 6/10 (CPI_low_freq 7/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:51<00:00,  1.93feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.593086, HammingLoss: 0.25149, SubsetAccuracy: 0.35714, RankingLoss: 0.27847, MacroPrecision: 0.60826, MacroRecall: 0.15138, MacroFOne: 0.23712,
pruning: False, include_original_features: with_org, averageAUROC: 0.6024296, HammingLoss: 0.28423, SubsetAccuracy: 0.22321, RankingLoss: 0.24859, MacroPrecision: 0.46544, MacroRecall: 0.47711, MacroFOne: 0.47015,
pruning: True, include_original_features: no_org, averageAUROC: 0.6104099, HammingLoss: 0.24702, SubsetAccuracy: 0.34821, RankingLoss: 0.2563, MacroPrecision: 0.66752, MacroRecall: 0.14647, MacroFOne: 0.23363,
pruning: False, include_original_features: no_org, averageAUROC: 0.6373295, HammingLoss: 0.29762, SubsetAccuracy: 0.19643, RankingLoss: 0.25308, MacroPrecision: 0.43104, MacroRecall: 0.41894, MacroFOne: 0.42371,

Fold 7/10 (CPI_low_freq 7/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:51<00:00,  1.93feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.5674808, HammingLoss: 0.25298, SubsetAccuracy: 0.32143, RankingLoss: 0.29573, MacroPrecision: 0.52205, MacroRecall: 0.19089, MacroFOne: 0.27829,
pruning: False, include_original_features: with_org, averageAUROC: 0.6051994, HammingLoss: 0.3125, SubsetAccuracy: 0.21429, RankingLoss: 0.265, MacroPrecision: 0.39611, MacroRecall: 0.42205, MacroFOne: 0.40823,
pruning: True, include_original_features: no_org, averageAUROC: 0.5564079, HammingLoss: 0.2619, SubsetAccuracy: 0.30357, RankingLoss: 0.27262, MacroPrecision: 0.49444, MacroRecall: 0.064851, MacroFOne: 0.0,
pruning: False, include_original_features: no_org, averageAUROC: 0.6056446, HammingLoss: 0.30655, SubsetAccuracy: 0.19643, RankingLoss: 0.2494, MacroPrecision: 0.40373, MacroRecall: 0.40245, MacroFOne: 0.40227,

Fold 8/10 (CPI_low_freq 7/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:50<00:00,  1.93feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.6528246, HammingLoss: 0.28571, SubsetAccuracy: 0.28571, RankingLoss: 0.28829, MacroPrecision: 0.60295, MacroRecall: 0.2627, MacroFOne: 0.36542,
pruning: False, include_original_features: with_org, averageAUROC: 0.6303854, HammingLoss: 0.33631, SubsetAccuracy: 0.15179, RankingLoss: 0.26141, MacroPrecision: 0.46239, MacroRecall: 0.39883, MacroFOne: 0.42738,
pruning: True, include_original_features: no_org, averageAUROC: 0.5987783, HammingLoss: 0.30506, SubsetAccuracy: 0.25893, RankingLoss: 0.28028, MacroPrecision: 0.55664, MacroRecall: 0.18261, MacroFOne: 0.27059,
pruning: False, include_original_features: no_org, averageAUROC: 0.6097445, HammingLoss: 0.3497, SubsetAccuracy: 0.125, RankingLoss: 0.27078, MacroPrecision: 0.4405, MacroRecall: 0.43547, MacroFOne: 0.43762,

Fold 9/10 (CPI_low_freq 7/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:53<00:00,  1.93feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.6369946, HammingLoss: 0.24324, SubsetAccuracy: 0.34234, RankingLoss: 0.29154, MacroPrecision: 0.56753, MacroRecall: 0.22429, MacroFOne: 0.31965,
pruning: False, include_original_features: with_org, averageAUROC: 0.6172002, HammingLoss: 0.32432, SubsetAccuracy: 0.15315, RankingLoss: 0.25853, MacroPrecision: 0.40035, MacroRecall: 0.48515, MacroFOne: 0.43279,
pruning: True, include_original_features: no_org, averageAUROC: 0.6363993, HammingLoss: 0.25225, SubsetAccuracy: 0.32432, RankingLoss: 0.26824, MacroPrecision: 0.52424, MacroRecall: 0.14632, MacroFOne: 0.22632,
pruning: False, include_original_features: no_org, averageAUROC: 0.6062673, HammingLoss: 0.3033, SubsetAccuracy: 0.21622, RankingLoss: 0.24845, MacroPrecision: 0.42299, MacroRecall: 0.42404, MacroFOne: 0.41956,

Fold 10/10 (CPI_low_freq 7/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:52<00:00,  1.93feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.5732608, HammingLoss: 0.28378, SubsetAccuracy: 0.28829, RankingLoss: 0.27718, MacroPrecision: 0.30873, MacroRecall: 0.12144, MacroFOne: 0.15952,
pruning: False, include_original_features: with_org, averageAUROC: 0.552875, HammingLoss: 0.37688, SubsetAccuracy: 0.15315, RankingLoss: 0.30158, MacroPrecision: 0.34333, MacroRecall: 0.47185, MacroFOne: 0.39586,
pruning: True, include_original_features: no_org, averageAUROC: 0.6010019, HammingLoss: 0.27628, SubsetAccuracy: 0.27928, RankingLoss: 0.26014, MacroPrecision: 0.41471, MacroRecall: 0.21108, MacroFOne: 0.27526,
pruning: False, include_original_features: no_org, averageAUROC: 0.5816969, HammingLoss: 0.32583, SubsetAccuracy: 0.14414, RankingLoss: 0.29449, MacroPrecision: 0.38486, MacroRecall: 0.4041, MacroFOne: 0.39364,
   pruning include_original_features       dataset  averageAUROC  HammingLoss  \
0    False                    no_org  CPI_low_freq      0.597518     0.321991
1    False                  with_org  CPI_low_freq      0.596426     0.328453
2     True                    no_org  CPI_low_freq      0.584551     0.267437
3     True                  with_org  CPI_low_freq      0.600381     0.262970

   SubsetAccuracy  RankingLoss  MacroPrecision  MacroRecall  MacroFOne  nodes  \
0        0.180679     0.262503        0.389166     0.411979   0.397686  702.4
1        0.180630     0.270193        0.390530     0.437366   0.408254  699.2
2        0.318395     0.283140        0.479386     0.148285   0.168192   47.8
3        0.324671     0.288248        0.485958     0.188743   0.266606   60.6

   leaves  groups  avg_group_features  gen_XofN_time  training_time
0   351.7   322.0            4.990683     830.685217       0.950147
1   350.1   322.0            4.990683     830.685217       2.656676
2    24.4   322.0            4.990683     830.685217       0.950147
3    30.8   322.0            4.990683     830.685217       2.656676

--- Running with label:'['se_C0020538', 'se_C0008031', 'se_C0003467', 'se_C0036572', 'se_C0030252', 'se_C0027769']' training_algorithm:'Variance Reduction' eval_criterion:'['averageAUROC', 'HammingLoss', 'SubsetAccuracy', 'RankingLoss', 'MacroPrecision', 'MacroRecall', 'MacroFOne']' max_size:'5' ---
Logs can be found in XofN_filter_jaccard/logs/CPI_mid_freq_Variance Reduction_averageAUROC_HammingLoss_SubsetAccuracy_RankingLoss_MacroPrecision_MacroRecall_MacroFOne_5_logs.txt.

Fold 1/10 (CPI_mid_freq 8/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:54<00:00,  1.92feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.6099005, HammingLoss: 0.35714, SubsetAccuracy: 0.23214, RankingLoss: 0.23698, MacroPrecision: 0.50502, MacroRecall: 0.44344, MacroFOne: 0.47034,
pruning: False, include_original_features: with_org, averageAUROC: 0.5716894, HammingLoss: 0.41815, SubsetAccuracy: 0.16964, RankingLoss: 0.26431, MacroPrecision: 0.43987, MacroRecall: 0.53918, MacroFOne: 0.48415,
pruning: True, include_original_features: no_org, averageAUROC: 0.618585, HammingLoss: 0.35119, SubsetAccuracy: 0.25893, RankingLoss: 0.24802, MacroPrecision: 0.51223, MacroRecall: 0.41646, MacroFOne: 0.4549,
pruning: False, include_original_features: no_org, averageAUROC: 0.5706524, HammingLoss: 0.44643, SubsetAccuracy: 0.13393, RankingLoss: 0.28527, MacroPrecision: 0.41717, MacroRecall: 0.54976, MacroFOne: 0.47311,

Fold 2/10 (CPI_mid_freq 8/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:55<00:00,  1.92feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.5744499, HammingLoss: 0.35863, SubsetAccuracy: 0.30357, RankingLoss: 0.2624, MacroPrecision: 0.51232, MacroRecall: 0.32872, MacroFOne: 0.39771,
pruning: False, include_original_features: with_org, averageAUROC: 0.5512496, HammingLoss: 0.4122, SubsetAccuracy: 0.125, RankingLoss: 0.25962, MacroPrecision: 0.43705, MacroRecall: 0.48631, MacroFOne: 0.45781,
pruning: True, include_original_features: no_org, averageAUROC: 0.5967928, HammingLoss: 0.35863, SubsetAccuracy: 0.25, RankingLoss: 0.25154, MacroPrecision: 0.49326, MacroRecall: 0.32777, MacroFOne: 0.38876,
pruning: False, include_original_features: no_org, averageAUROC: 0.587221, HammingLoss: 0.40625, SubsetAccuracy: 0.15179, RankingLoss: 0.25838, MacroPrecision: 0.45449, MacroRecall: 0.51889, MacroFOne: 0.48071,

Fold 3/10 (CPI_mid_freq 8/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:55<00:00,  1.92feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.5791347, HammingLoss: 0.39583, SubsetAccuracy: 0.21429, RankingLoss: 0.30543, MacroPrecision: 0.52081, MacroRecall: 0.32244, MacroFOne: 0.39684,
pruning: False, include_original_features: with_org, averageAUROC: 0.5466145, HammingLoss: 0.45387, SubsetAccuracy: 0.125, RankingLoss: 0.27996, MacroPrecision: 0.453, MacroRecall: 0.4933, MacroFOne: 0.47123,
pruning: True, include_original_features: no_org, averageAUROC: 0.5913031, HammingLoss: 0.35863, SubsetAccuracy: 0.22321, RankingLoss: 0.32106, MacroPrecision: 0.60278, MacroRecall: 0.37415, MacroFOne: 0.46102,
pruning: False, include_original_features: no_org, averageAUROC: 0.5895961, HammingLoss: 0.42857, SubsetAccuracy: 0.10714, RankingLoss: 0.28559, MacroPrecision: 0.47925, MacroRecall: 0.53099, MacroFOne: 0.50289,

Fold 4/10 (CPI_mid_freq 8/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:56<00:00,  1.92feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.6311409, HammingLoss: 0.38988, SubsetAccuracy: 0.25, RankingLoss: 0.285, MacroPrecision: 0.59684, MacroRecall: 0.34811, MacroFOne: 0.43805,
pruning: False, include_original_features: with_org, averageAUROC: 0.5850509, HammingLoss: 0.42857, SubsetAccuracy: 0.125, RankingLoss: 0.28621, MacroPrecision: 0.50988, MacroRecall: 0.48773, MacroFOne: 0.49785,
pruning: True, include_original_features: no_org, averageAUROC: 0.6428136, HammingLoss: 0.36161, SubsetAccuracy: 0.26786, RankingLoss: 0.26801, MacroPrecision: 0.65747, MacroRecall: 0.36836, MacroFOne: 0.47044,
pruning: False, include_original_features: no_org, averageAUROC: 0.590662, HammingLoss: 0.40327, SubsetAccuracy: 0.14286, RankingLoss: 0.30491, MacroPrecision: 0.54325, MacroRecall: 0.51072, MacroFOne: 0.52541,

Fold 5/10 (CPI_mid_freq 8/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:55<00:00,  1.92feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.5906657, HammingLoss: 0.39039, SubsetAccuracy: 0.23423, RankingLoss: 0.27022, MacroPrecision: 0.47885, MacroRecall: 0.29381, MacroFOne: 0.36222,
pruning: False, include_original_features: with_org, averageAUROC: 0.5595335, HammingLoss: 0.42192, SubsetAccuracy: 0.17117, RankingLoss: 0.25478, MacroPrecision: 0.44336, MacroRecall: 0.43476, MacroFOne: 0.43593,
pruning: True, include_original_features: no_org, averageAUROC: 0.6278643, HammingLoss: 0.34535, SubsetAccuracy: 0.25225, RankingLoss: 0.27082, MacroPrecision: 0.56996, MacroRecall: 0.39228, MacroFOne: 0.46064,
pruning: False, include_original_features: no_org, averageAUROC: 0.6617198, HammingLoss: 0.34084, SubsetAccuracy: 0.16216, RankingLoss: 0.22005, MacroPrecision: 0.55145, MacroRecall: 0.59351, MacroFOne: 0.56739,

Fold 6/10 (CPI_mid_freq 8/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:56<00:00,  1.92feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.5313649, HammingLoss: 0.39189, SubsetAccuracy: 0.27027, RankingLoss: 0.25696, MacroPrecision: 0.39785, MacroRecall: 0.31202, MacroFOne: 0.34649,
pruning: False, include_original_features: with_org, averageAUROC: 0.534487, HammingLoss: 0.43544, SubsetAccuracy: 0.16216, RankingLoss: 0.28161, MacroPrecision: 0.39035, MacroRecall: 0.48571, MacroFOne: 0.4303,
pruning: True, include_original_features: no_org, averageAUROC: 0.5252433, HammingLoss: 0.39489, SubsetAccuracy: 0.22523, RankingLoss: 0.27307, MacroPrecision: 0.39797, MacroRecall: 0.29041, MacroFOne: 0.33323,
pruning: False, include_original_features: no_org, averageAUROC: 0.5154617, HammingLoss: 0.47598, SubsetAccuracy: 0.11712, RankingLoss: 0.2724, MacroPrecision: 0.36148, MacroRecall: 0.518, MacroFOne: 0.42487,

Fold 7/10 (CPI_mid_freq 8/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:56<00:00,  1.92feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.5642192, HammingLoss: 0.41592, SubsetAccuracy: 0.22523, RankingLoss: 0.23013, MacroPrecision: 0.4978, MacroRecall: 0.36116, MacroFOne: 0.41515,
pruning: False, include_original_features: with_org, averageAUROC: 0.5721473, HammingLoss: 0.42943, SubsetAccuracy: 0.12613, RankingLoss: 0.23711, MacroPrecision: 0.48038, MacroRecall: 0.51362, MacroFOne: 0.49425,
pruning: True, include_original_features: no_org, averageAUROC: 0.5199884, HammingLoss: 0.44144, SubsetAccuracy: 0.20721, RankingLoss: 0.26031, MacroPrecision: 0.44263, MacroRecall: 0.26881, MacroFOne: 0.33364,
pruning: False, include_original_features: no_org, averageAUROC: 0.5548328, HammingLoss: 0.42793, SubsetAccuracy: 0.13514, RankingLoss: 0.26597, MacroPrecision: 0.48508, MacroRecall: 0.5717, MacroFOne: 0.52216,

Fold 8/10 (CPI_mid_freq 8/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:56<00:00,  1.92feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.5606996, HammingLoss: 0.3979, SubsetAccuracy: 0.23423, RankingLoss: 0.22215, MacroPrecision: 0.44664, MacroRecall: 0.33509, MacroFOne: 0.37682,
pruning: False, include_original_features: with_org, averageAUROC: 0.5927452, HammingLoss: 0.40841, SubsetAccuracy: 0.13514, RankingLoss: 0.25701, MacroPrecision: 0.46063, MacroRecall: 0.62566, MacroFOne: 0.52671,
pruning: True, include_original_features: no_org, averageAUROC: 0.5921694, HammingLoss: 0.36486, SubsetAccuracy: 0.21622, RankingLoss: 0.21234, MacroPrecision: 0.50949, MacroRecall: 0.35869, MacroFOne: 0.41253,
pruning: False, include_original_features: no_org, averageAUROC: 0.5767355, HammingLoss: 0.42492, SubsetAccuracy: 0.11712, RankingLoss: 0.23303, MacroPrecision: 0.43317, MacroRecall: 0.5144, MacroFOne: 0.46821,

Fold 9/10 (CPI_mid_freq 8/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:57<00:00,  1.92feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.6268746, HammingLoss: 0.38889, SubsetAccuracy: 0.21622, RankingLoss: 0.25591, MacroPrecision: 0.53108, MacroRecall: 0.44338, MacroFOne: 0.48156,
pruning: False, include_original_features: with_org, averageAUROC: 0.5735201, HammingLoss: 0.40841, SubsetAccuracy: 0.14414, RankingLoss: 0.29827, MacroPrecision: 0.50391, MacroRecall: 0.55657, MacroFOne: 0.52796,
pruning: True, include_original_features: no_org, averageAUROC: 0.6511928, HammingLoss: 0.34234, SubsetAccuracy: 0.24324, RankingLoss: 0.25478, MacroPrecision: 0.61834, MacroRecall: 0.42454, MacroFOne: 0.50026,
pruning: False, include_original_features: no_org, averageAUROC: 0.6170889, HammingLoss: 0.3964, SubsetAccuracy: 0.10811, RankingLoss: 0.29314, MacroPrecision: 0.51657, MacroRecall: 0.57883, MacroFOne: 0.54517,

Fold 10/10 (CPI_mid_freq 8/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [13:59<00:00,  1.91feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.6103428, HammingLoss: 0.34384, SubsetAccuracy: 0.25225, RankingLoss: 0.26359, MacroPrecision: 0.61554, MacroRecall: 0.42215, MacroFOne: 0.49642,
pruning: False, include_original_features: with_org, averageAUROC: 0.6546515, HammingLoss: 0.34535, SubsetAccuracy: 0.20721, RankingLoss: 0.23393, MacroPrecision: 0.5651, MacroRecall: 0.61239, MacroFOne: 0.58681,
pruning: True, include_original_features: no_org, averageAUROC: 0.6305395, HammingLoss: 0.36486, SubsetAccuracy: 0.25225, RankingLoss: 0.23684, MacroPrecision: 0.57704, MacroRecall: 0.39859, MacroFOne: 0.46778,
pruning: False, include_original_features: no_org, averageAUROC: 0.6236534, HammingLoss: 0.38589, SubsetAccuracy: 0.15315, RankingLoss: 0.24667, MacroPrecision: 0.51518, MacroRecall: 0.5915, MacroFOne: 0.55032,
   pruning include_original_features       dataset  averageAUROC  HammingLoss  \
0    False                    no_org  CPI_mid_freq      0.588762     0.413648
1    False                  with_org  CPI_mid_freq      0.574169     0.416175
2     True                    no_org  CPI_mid_freq      0.599649     0.368380
3     True                  with_org  CPI_mid_freq      0.587879     0.383031

   SubsetAccuracy  RankingLoss  MacroPrecision  MacroRecall  MacroFOne  nodes  \
0        0.132852     0.266541        0.475709     0.547830   0.506024  709.8
1        0.149059     0.265281        0.468353     0.523523   0.491300  720.0
2        0.239640     0.259679        0.538117     0.362006   0.428320  108.2
3        0.243243     0.258877        0.510275     0.361032   0.418160  116.2

   leaves  groups  avg_group_features  gen_XofN_time  training_time
0   355.4   322.0            4.990683     836.519708       0.975656
1   360.5   322.0            4.990683     836.519708       2.758859
2    54.6   322.0            4.990683     836.519708       0.975656
3    58.6   322.0            4.990683     836.519708       2.758859

--- Running with label:'['se_C0016382', 'se_C0018799', 'se_C0003811', 'se_C0428977', 'se_C0027051', 'se_C0018790']' training_algorithm:'Variance Reduction' eval_criterion:'['averageAUROC', 'HammingLoss', 'SubsetAccuracy', 'RankingLoss', 'MacroPrecision', 'MacroRecall', 'MacroFOne']' max_size:'5' ---
Logs can be found in XofN_filter_jaccard/logs/fingerprint_cardiac_Variance Reduction_averageAUROC_HammingLoss_SubsetAccuracy_RankingLoss_MacroPrecision_MacroRecall_MacroFOne_5_logs.txt.

Fold 1/10 (fingerprint_cardiac 9/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [02:58<00:00,  3.03feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5543348, HammingLoss: 0.28788, SubsetAccuracy: 0.31061, RankingLoss: 0.21239, MacroPrecision: 0.31296, MacroRecall: 0.06351, MacroFOne: 0.10455,
pruning: False, include_original_features: with_org, averageAUROC: 0.5461391, HammingLoss: 0.38258, SubsetAccuracy: 0.15909, RankingLoss: 0.22593, MacroPrecision: 0.31286, MacroRecall: 0.36278, MacroFOne: 0.33204,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.26768, SubsetAccuracy: 0.37121, RankingLoss: 0.22742, MacroPrecision: 0.0, MacroRecall: 0.0, MacroFOne: 0.0,
pruning: False, include_original_features: no_org, averageAUROC: 0.556977, HammingLoss: 0.35732, SubsetAccuracy: 0.16667, RankingLoss: 0.21955, MacroPrecision: 0.33594, MacroRecall: 0.35495, MacroFOne: 0.3426,

Fold 2/10 (fingerprint_cardiac 9/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [02:57<00:00,  3.03feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5575767, HammingLoss: 0.26768, SubsetAccuracy: 0.35606, RankingLoss: 0.20461, MacroPrecision: 0.3063, MacroRecall: 0.14267, MacroFOne: 0.0,
pruning: False, include_original_features: with_org, averageAUROC: 0.5824326, HammingLoss: 0.34217, SubsetAccuracy: 0.2197, RankingLoss: 0.20076, MacroPrecision: 0.31284, MacroRecall: 0.40712, MacroFOne: 0.35048,
pruning: True, include_original_features: no_org, averageAUROC: 0.5863117, HammingLoss: 0.23864, SubsetAccuracy: 0.43939, RankingLoss: 0.20109, MacroPrecision: 0.34722, MacroRecall: 0.047821, MacroFOne: 0.0,
pruning: False, include_original_features: no_org, averageAUROC: 0.5830559, HammingLoss: 0.34848, SubsetAccuracy: 0.22727, RankingLoss: 0.21357, MacroPrecision: 0.32419, MacroRecall: 0.47639, MacroFOne: 0.38433,

Fold 3/10 (fingerprint_cardiac 9/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [02:57<00:00,  3.04feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5168432, HammingLoss: 0.30556, SubsetAccuracy: 0.30303, RankingLoss: 0.27245, MacroPrecision: 0.42812, MacroRecall: 0.12848, MacroFOne: 0.19533,
pruning: False, include_original_features: with_org, averageAUROC: 0.556034, HammingLoss: 0.38636, SubsetAccuracy: 0.16667, RankingLoss: 0.23885, MacroPrecision: 0.35151, MacroRecall: 0.4016, MacroFOne: 0.37343,
pruning: True, include_original_features: no_org, averageAUROC: 0.5062633, HammingLoss: 0.29167, SubsetAccuracy: 0.33333, RankingLoss: 0.25703, MacroPrecision: 0.0, MacroRecall: 0.022981, MacroFOne: 0.0,
pruning: False, include_original_features: no_org, averageAUROC: 0.5700803, HammingLoss: 0.38258, SubsetAccuracy: 0.15152, RankingLoss: 0.24148, MacroPrecision: 0.36744, MacroRecall: 0.44199, MacroFOne: 0.40011,

Fold 4/10 (fingerprint_cardiac 9/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [02:58<00:00,  3.03feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5311455, HammingLoss: 0.27904, SubsetAccuracy: 0.37879, RankingLoss: 0.22012, MacroPrecision: 0.23302, MacroRecall: 0.078736, MacroFOne: 0.0,
pruning: False, include_original_features: with_org, averageAUROC: 0.5364568, HammingLoss: 0.35227, SubsetAccuracy: 0.18939, RankingLoss: 0.21069, MacroPrecision: 0.2993, MacroRecall: 0.38146, MacroFOne: 0.33367,
pruning: True, include_original_features: no_org, averageAUROC: 0.5376676, HammingLoss: 0.26894, SubsetAccuracy: 0.40909, RankingLoss: 0.18935, MacroPrecision: 0.30299, MacroRecall: 0.11918, MacroFOne: 0.0,
pruning: False, include_original_features: no_org, averageAUROC: 0.540522, HammingLoss: 0.3649, SubsetAccuracy: 0.19697, RankingLoss: 0.20097, MacroPrecision: 0.27719, MacroRecall: 0.34653, MacroFOne: 0.30607,

Fold 5/10 (fingerprint_cardiac 9/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [02:58<00:00,  3.03feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5794485, HammingLoss: 0.22854, SubsetAccuracy: 0.43182, RankingLoss: 0.2045, MacroPrecision: 0.30975, MacroRecall: 0.12017, MacroFOne: 0.17224,
pruning: False, include_original_features: with_org, averageAUROC: 0.5978108, HammingLoss: 0.31818, SubsetAccuracy: 0.20455, RankingLoss: 0.13838, MacroPrecision: 0.28379, MacroRecall: 0.40072, MacroFOne: 0.33115,
pruning: True, include_original_features: no_org, averageAUROC: 0.5247031, HammingLoss: 0.19949, SubsetAccuracy: 0.45455, RankingLoss: 0.18203, MacroPrecision: 0.53535, MacroRecall: 0.082735, MacroFOne: 0.13892,
pruning: False, include_original_features: no_org, averageAUROC: 0.6356323, HammingLoss: 0.32197, SubsetAccuracy: 0.2197, RankingLoss: 0.15821, MacroPrecision: 0.3055, MacroRecall: 0.4919, MacroFOne: 0.37456,

Fold 6/10 (fingerprint_cardiac 9/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [02:58<00:00,  3.03feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.6055711, HammingLoss: 0.24874, SubsetAccuracy: 0.40909, RankingLoss: 0.18876, MacroPrecision: 0.44262, MacroRecall: 0.16624, MacroFOne: 0.23669,
pruning: False, include_original_features: with_org, averageAUROC: 0.6228808, HammingLoss: 0.30808, SubsetAccuracy: 0.23485, RankingLoss: 0.1794, MacroPrecision: 0.36698, MacroRecall: 0.45327, MacroFOne: 0.39891,
pruning: True, include_original_features: no_org, averageAUROC: 0.5891307, HammingLoss: 0.26894, SubsetAccuracy: 0.39394, RankingLoss: 0.19367, MacroPrecision: 0.30347, MacroRecall: 0.1076, MacroFOne: 0.0,
pruning: False, include_original_features: no_org, averageAUROC: 0.5553354, HammingLoss: 0.35101, SubsetAccuracy: 0.15909, RankingLoss: 0.22689, MacroPrecision: 0.29242, MacroRecall: 0.3403, MacroFOne: 0.30901,

Fold 7/10 (fingerprint_cardiac 9/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [02:57<00:00,  3.03feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5569076, HammingLoss: 0.28535, SubsetAccuracy: 0.37121, RankingLoss: 0.22864, MacroPrecision: 0.2677, MacroRecall: 0.14655, MacroFOne: 0.18727,
pruning: False, include_original_features: with_org, averageAUROC: 0.5677332, HammingLoss: 0.34975, SubsetAccuracy: 0.21212, RankingLoss: 0.20465, MacroPrecision: 0.30527, MacroRecall: 0.4342, MacroFOne: 0.35741,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.22854, SubsetAccuracy: 0.43182, RankingLoss: 0.22306, MacroPrecision: 0.0, MacroRecall: 0.0, MacroFOne: 0.0,
pruning: False, include_original_features: no_org, averageAUROC: 0.566956, HammingLoss: 0.36364, SubsetAccuracy: 0.17424, RankingLoss: 0.19392, MacroPrecision: 0.29392, MacroRecall: 0.42913, MacroFOne: 0.3446,

Fold 8/10 (fingerprint_cardiac 9/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [02:58<00:00,  3.03feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.561184, HammingLoss: 0.27399, SubsetAccuracy: 0.32576, RankingLoss: 0.26829, MacroPrecision: 0.38052, MacroRecall: 0.16036, MacroFOne: 0.21794,
pruning: False, include_original_features: with_org, averageAUROC: 0.5958988, HammingLoss: 0.37374, SubsetAccuracy: 0.15152, RankingLoss: 0.2259, MacroPrecision: 0.32857, MacroRecall: 0.52506, MacroFOne: 0.4022,
pruning: True, include_original_features: no_org, averageAUROC: 0.5141178, HammingLoss: 0.29672, SubsetAccuracy: 0.31061, RankingLoss: 0.28142, MacroPrecision: 0.27752, MacroRecall: 0.13373, MacroFOne: 0.16629,
pruning: False, include_original_features: no_org, averageAUROC: 0.5527119, HammingLoss: 0.39899, SubsetAccuracy: 0.12879, RankingLoss: 0.25067, MacroPrecision: 0.28851, MacroRecall: 0.44631, MacroFOne: 0.34813,

Fold 9/10 (fingerprint_cardiac 9/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [02:58<00:00,  3.02feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.569523, HammingLoss: 0.32071, SubsetAccuracy: 0.2197, RankingLoss: 0.27016, MacroPrecision: 0.59385, MacroRecall: 0.11807, MacroFOne: 0.18837,
pruning: False, include_original_features: with_org, averageAUROC: 0.558053, HammingLoss: 0.39646, SubsetAccuracy: 0.090909, RankingLoss: 0.2597, MacroPrecision: 0.38359, MacroRecall: 0.36482, MacroFOne: 0.37308,
pruning: True, include_original_features: no_org, averageAUROC: 0.5796052, HammingLoss: 0.31944, SubsetAccuracy: 0.22727, RankingLoss: 0.25097, MacroPrecision: 0.54524, MacroRecall: 0.13193, MacroFOne: 0.21079,
pruning: False, include_original_features: no_org, averageAUROC: 0.5646743, HammingLoss: 0.375, SubsetAccuracy: 0.12121, RankingLoss: 0.24478, MacroPrecision: 0.40767, MacroRecall: 0.36802, MacroFOne: 0.38658,

Fold 10/10 (fingerprint_cardiac 9/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [02:58<00:00,  3.02feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5401639, HammingLoss: 0.29167, SubsetAccuracy: 0.32576, RankingLoss: 0.25972, MacroPrecision: 0.441, MacroRecall: 0.13806, MacroFOne: 0.20688,
pruning: False, include_original_features: with_org, averageAUROC: 0.5874439, HammingLoss: 0.34975, SubsetAccuracy: 0.16667, RankingLoss: 0.22043, MacroPrecision: 0.39261, MacroRecall: 0.38439, MacroFOne: 0.38225,
pruning: True, include_original_features: no_org, averageAUROC: 0.5417386, HammingLoss: 0.29419, SubsetAccuracy: 0.31818, RankingLoss: 0.24436, MacroPrecision: 0.42296, MacroRecall: 0.11576, MacroFOne: 0.18131,
pruning: False, include_original_features: no_org, averageAUROC: 0.6085074, HammingLoss: 0.36364, SubsetAccuracy: 0.18939, RankingLoss: 0.21448, MacroPrecision: 0.38555, MacroRecall: 0.49888, MacroFOne: 0.43488,
   pruning include_original_features              dataset  averageAUROC  \
0    False                    no_org  fingerprint_cardiac      0.573445
1    False                  with_org  fingerprint_cardiac      0.575088
2     True                    no_org  fingerprint_cardiac      0.537954
3     True                  with_org  fingerprint_cardiac      0.557270

   HammingLoss  SubsetAccuracy  RankingLoss  MacroPrecision  MacroRecall  \
0     0.362753        0.173485     0.216452        0.327833     0.419440
1     0.355934        0.179547     0.210469        0.333732     0.411542
2     0.267425        0.368939     0.225040        0.273475     0.076174
3     0.278916        0.343183     0.232964        0.371584     0.126285

   MacroFOne  nodes  leaves  groups  avg_group_features  gen_XofN_time  \
0   0.363087  839.2   420.1   108.0                 5.0     178.227184
1   0.363462  816.2   408.6   108.0                 5.0     178.227184
2   0.069731   29.2    15.1   108.0                 5.0     178.227184
3   0.150927   55.8    28.4   108.0                 5.0     178.227184

   training_time
0        0.68001
1        1.31402
2        0.68001
3        1.31402

--- Running with label:'['se_C0027497', 'se_C0018681', 'se_C0011603', 'se_C0015230', 'se_C0042963', 'se_C0012833']' training_algorithm:'Variance Reduction' eval_criterion:'['averageAUROC', 'HammingLoss', 'SubsetAccuracy', 'RankingLoss', 'MacroPrecision', 'MacroRecall', 'MacroFOne']' max_size:'5' ---
Logs can be found in XofN_filter_jaccard/logs/fingerprint_high_freq_Variance Reduction_averageAUROC_HammingLoss_SubsetAccuracy_RankingLoss_MacroPrecision_MacroRecall_MacroFOne_5_logs.txt.

Fold 1/10 (fingerprint_high_freq 10/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [02:58<00:00,  3.02feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5475723, HammingLoss: 0.19444, SubsetAccuracy: 0.5, RankingLoss: 0.20109, MacroPrecision: 0.82769, MacroRecall: 0.96482, MacroFOne: 0.89075,
pruning: False, include_original_features: with_org, averageAUROC: 0.5654673, HammingLoss: 0.24242, SubsetAccuracy: 0.39394, RankingLoss: 0.18731, MacroPrecision: 0.84037, MacroRecall: 0.87113, MacroFOne: 0.85471,
pruning: True, include_original_features: no_org, averageAUROC: 0.5780341, HammingLoss: 0.17551, SubsetAccuracy: 0.52273, RankingLoss: 0.19985, MacroPrecision: 0.82841, MacroRecall: 0.99208, MacroFOne: 0.90264,
pruning: False, include_original_features: no_org, averageAUROC: 0.5836596, HammingLoss: 0.25884, SubsetAccuracy: 0.40909, RankingLoss: 0.20282, MacroPrecision: 0.84343, MacroRecall: 0.83936, MacroFOne: 0.84118,

Fold 2/10 (fingerprint_high_freq 10/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [02:58<00:00,  3.02feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5869016, HammingLoss: 0.2399, SubsetAccuracy: 0.51515, RankingLoss: 0.15535, MacroPrecision: 0.80229, MacroRecall: 0.92933, MacroFOne: 0.86023,
pruning: False, include_original_features: with_org, averageAUROC: 0.5527394, HammingLoss: 0.28788, SubsetAccuracy: 0.37879, RankingLoss: 0.16387, MacroPrecision: 0.81484, MacroRecall: 0.82286, MacroFOne: 0.81839,
pruning: True, include_original_features: no_org, averageAUROC: 0.5442528, HammingLoss: 0.23359, SubsetAccuracy: 0.51515, RankingLoss: 0.16092, MacroPrecision: 0.80414, MacroRecall: 0.93777, MacroFOne: 0.86457,
pruning: False, include_original_features: no_org, averageAUROC: 0.5531472, HammingLoss: 0.2803, SubsetAccuracy: 0.32576, RankingLoss: 0.17746, MacroPrecision: 0.81626, MacroRecall: 0.83393, MacroFOne: 0.82451,

Fold 3/10 (fingerprint_high_freq 10/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [02:59<00:00,  3.01feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5857616, HammingLoss: 0.22222, SubsetAccuracy: 0.5303, RankingLoss: 0.13241, MacroPrecision: 0.79519, MacroRecall: 0.96692, MacroFOne: 0.87189,
pruning: False, include_original_features: with_org, averageAUROC: 0.5786887, HammingLoss: 0.24874, SubsetAccuracy: 0.39394, RankingLoss: 0.12096, MacroPrecision: 0.80934, MacroRecall: 0.89155, MacroFOne: 0.84814,
pruning: True, include_original_features: no_org, averageAUROC: 0.5883244, HammingLoss: 0.22601, SubsetAccuracy: 0.51515, RankingLoss: 0.12736, MacroPrecision: 0.79912, MacroRecall: 0.9523, MacroFOne: 0.86816,
pruning: False, include_original_features: no_org, averageAUROC: 0.5637755, HammingLoss: 0.25505, SubsetAccuracy: 0.40152, RankingLoss: 0.12279, MacroPrecision: 0.80182, MacroRecall: 0.89196, MacroFOne: 0.84443,

Fold 4/10 (fingerprint_high_freq 10/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [02:58<00:00,  3.02feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5550641, HammingLoss: 0.2702, SubsetAccuracy: 0.40909, RankingLoss: 0.19994, MacroPrecision: 0.75775, MacroRecall: 0.93535, MacroFOne: 0.83647,
pruning: False, include_original_features: with_org, averageAUROC: 0.5201632, HammingLoss: 0.30051, SubsetAccuracy: 0.33333, RankingLoss: 0.19825, MacroPrecision: 0.76421, MacroRecall: 0.85761, MacroFOne: 0.8079,
pruning: True, include_original_features: no_org, averageAUROC: 0.5926928, HammingLoss: 0.25631, SubsetAccuracy: 0.42424, RankingLoss: 0.2025, MacroPrecision: 0.76417, MacroRecall: 0.94671, MacroFOne: 0.84506,
pruning: False, include_original_features: no_org, averageAUROC: 0.5799216, HammingLoss: 0.29798, SubsetAccuracy: 0.28788, RankingLoss: 0.18312, MacroPrecision: 0.76603, MacroRecall: 0.85946, MacroFOne: 0.80939,

Fold 5/10 (fingerprint_high_freq 10/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [02:58<00:00,  3.02feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5943764, HammingLoss: 0.22475, SubsetAccuracy: 0.53788, RankingLoss: 0.16151, MacroPrecision: 0.79449, MacroRecall: 0.96124, MacroFOne: 0.86941,
pruning: False, include_original_features: with_org, averageAUROC: 0.6428458, HammingLoss: 0.25505, SubsetAccuracy: 0.42424, RankingLoss: 0.12925, MacroPrecision: 0.81572, MacroRecall: 0.8684, MacroFOne: 0.84074,
pruning: True, include_original_features: no_org, averageAUROC: 0.5788524, HammingLoss: 0.22727, SubsetAccuracy: 0.5303, RankingLoss: 0.14924, MacroPrecision: 0.79378, MacroRecall: 0.95771, MacroFOne: 0.86765,
pruning: False, include_original_features: no_org, averageAUROC: 0.5627513, HammingLoss: 0.26263, SubsetAccuracy: 0.44697, RankingLoss: 0.1359, MacroPrecision: 0.80705, MacroRecall: 0.86991, MacroFOne: 0.83686,

Fold 6/10 (fingerprint_high_freq 10/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [02:58<00:00,  3.02feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5670983, HammingLoss: 0.2601, SubsetAccuracy: 0.48485, RankingLoss: 0.1818, MacroPrecision: 0.772, MacroRecall: 0.92961, MacroFOne: 0.84296,
pruning: False, include_original_features: with_org, averageAUROC: 0.5956225, HammingLoss: 0.29545, SubsetAccuracy: 0.36364, RankingLoss: 0.18979, MacroPrecision: 0.77668, MacroRecall: 0.84935, MacroFOne: 0.81119,
pruning: True, include_original_features: no_org, averageAUROC: 0.557515, HammingLoss: 0.25379, SubsetAccuracy: 0.48485, RankingLoss: 0.17662, MacroPrecision: 0.77215, MacroRecall: 0.94161, MacroFOne: 0.84792,
pruning: False, include_original_features: no_org, averageAUROC: 0.5689673, HammingLoss: 0.30808, SubsetAccuracy: 0.35606, RankingLoss: 0.17418, MacroPrecision: 0.76175, MacroRecall: 0.85584, MacroFOne: 0.80588,

Fold 7/10 (fingerprint_high_freq 10/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [02:59<00:00,  3.01feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.6224389, HammingLoss: 0.20992, SubsetAccuracy: 0.54198, RankingLoss: 0.1342, MacroPrecision: 0.81772, MacroRecall: 0.94909, MacroFOne: 0.87809,
pruning: False, include_original_features: with_org, averageAUROC: 0.539567, HammingLoss: 0.26081, SubsetAccuracy: 0.45802, RankingLoss: 0.17269, MacroPrecision: 0.81322, MacroRecall: 0.87132, MacroFOne: 0.84121,
pruning: True, include_original_features: no_org, averageAUROC: 0.6283339, HammingLoss: 0.21883, SubsetAccuracy: 0.53435, RankingLoss: 0.13181, MacroPrecision: 0.81579, MacroRecall: 0.93789, MacroFOne: 0.87226,
pruning: False, include_original_features: no_org, averageAUROC: 0.6259578, HammingLoss: 0.24809, SubsetAccuracy: 0.44275, RankingLoss: 0.15469, MacroPrecision: 0.81785, MacroRecall: 0.88652, MacroFOne: 0.85043,

Fold 8/10 (fingerprint_high_freq 10/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [02:58<00:00,  3.02feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5051291, HammingLoss: 0.23919, SubsetAccuracy: 0.52672, RankingLoss: 0.14521, MacroPrecision: 0.77946, MacroRecall: 0.96586, MacroFOne: 0.86206,
pruning: False, include_original_features: with_org, averageAUROC: 0.550881, HammingLoss: 0.27354, SubsetAccuracy: 0.39695, RankingLoss: 0.15865, MacroPrecision: 0.78727, MacroRecall: 0.88627, MacroFOne: 0.83317,
pruning: True, include_original_features: no_org, averageAUROC: 0.511178, HammingLoss: 0.2341, SubsetAccuracy: 0.52672, RankingLoss: 0.14578, MacroPrecision: 0.79164, MacroRecall: 0.94983, MacroFOne: 0.86272,
pruning: False, include_original_features: no_org, averageAUROC: 0.6039796, HammingLoss: 0.25445, SubsetAccuracy: 0.38931, RankingLoss: 0.13249, MacroPrecision: 0.79488, MacroRecall: 0.90646, MacroFOne: 0.8461,

Fold 9/10 (fingerprint_high_freq 10/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [02:59<00:00,  3.01feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5696989, HammingLoss: 0.22519, SubsetAccuracy: 0.48855, RankingLoss: 0.16253, MacroPrecision: 0.79524, MacroRecall: 0.95593, MacroFOne: 0.86765,
pruning: False, include_original_features: with_org, averageAUROC: 0.6354355, HammingLoss: 0.243, SubsetAccuracy: 0.41985, RankingLoss: 0.15221, MacroPrecision: 0.81714, MacroRecall: 0.88286, MacroFOne: 0.84834,
pruning: True, include_original_features: no_org, averageAUROC: 0.5759135, HammingLoss: 0.22901, SubsetAccuracy: 0.48092, RankingLoss: 0.16041, MacroPrecision: 0.7918, MacroRecall: 0.95549, MacroFOne: 0.8655,
pruning: False, include_original_features: no_org, averageAUROC: 0.5797999, HammingLoss: 0.28117, SubsetAccuracy: 0.33588, RankingLoss: 0.15946, MacroPrecision: 0.80306, MacroRecall: 0.83876, MacroFOne: 0.82022,

Fold 10/10 (fingerprint_high_freq 10/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [02:58<00:00,  3.02feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5415075, HammingLoss: 0.25573, SubsetAccuracy: 0.48092, RankingLoss: 0.17615, MacroPrecision: 0.79173, MacroRecall: 0.90739, MacroFOne: 0.8452,
pruning: False, include_original_features: with_org, averageAUROC: 0.5614246, HammingLoss: 0.2888, SubsetAccuracy: 0.37405, RankingLoss: 0.17432, MacroPrecision: 0.79517, MacroRecall: 0.83827, MacroFOne: 0.81603,
pruning: True, include_original_features: no_org, averageAUROC: 0.5587745, HammingLoss: 0.24809, SubsetAccuracy: 0.48092, RankingLoss: 0.17188, MacroPrecision: 0.78573, MacroRecall: 0.93663, MacroFOne: 0.85314,
pruning: False, include_original_features: no_org, averageAUROC: 0.5581193, HammingLoss: 0.31679, SubsetAccuracy: 0.32824, RankingLoss: 0.174, MacroPrecision: 0.78437, MacroRecall: 0.81173, MacroFOne: 0.79741,
   pruning include_original_features                dataset  averageAUROC  \
0    False                    no_org  fingerprint_high_freq      0.578008
1    False                  with_org  fingerprint_high_freq      0.574284
2     True                    no_org  fingerprint_high_freq      0.571387
3     True                  with_org  fingerprint_high_freq      0.567555

   HammingLoss  SubsetAccuracy  RankingLoss  MacroPrecision  MacroRecall  \
0     0.276338        0.372346     0.161691        0.799650     0.859393
1     0.269620        0.393675     0.164730        0.803396     0.863962
2     0.230251        0.501533     0.162637        0.794673     0.950802
3     0.234164        0.501544     0.165019        0.793356     0.946554

   MacroFOne  nodes  leaves  groups  avg_group_features  gen_XofN_time  \
0   0.827641  599.2   300.1   108.0                 5.0     178.951654
1   0.831982  587.6   294.3   108.0                 5.0     178.951654
2   0.864962   44.6    22.8   108.0                 5.0     178.951654
3   0.862471   55.0    28.0   108.0                 5.0     178.951654

   training_time
0       0.688364
1       1.303322
2       0.688364
3       1.303322

--- Running with label:'['se_C0020580', 'se_C0267792', 'se_C0018524', 'se_C0031117', 'se_C0035078', 'se_C0011570']' training_algorithm:'Variance Reduction' eval_criterion:'['averageAUROC', 'HammingLoss', 'SubsetAccuracy', 'RankingLoss', 'MacroPrecision', 'MacroRecall', 'MacroFOne']' max_size:'5' ---
Logs can be found in XofN_filter_jaccard/logs/fingerprint_low_freq_Variance Reduction_averageAUROC_HammingLoss_SubsetAccuracy_RankingLoss_MacroPrecision_MacroRecall_MacroFOne_5_logs.txt.

Fold 1/10 (fingerprint_low_freq 11/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [02:59<00:00,  3.01feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5, HammingLoss: 0.21212, SubsetAccuracy: 0.42424, RankingLoss: 0.28836, MacroPrecision: 0.0, MacroRecall: 0.0, MacroFOne: 0.0,
pruning: False, include_original_features: with_org, averageAUROC: 0.5673428, HammingLoss: 0.37121, SubsetAccuracy: 0.18182, RankingLoss: 0.24792, MacroPrecision: 0.25455, MacroRecall: 0.39243, MacroFOne: 0.30712,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.21212, SubsetAccuracy: 0.42424, RankingLoss: 0.28836, MacroPrecision: 0.0, MacroRecall: 0.0, MacroFOne: 0.0,
pruning: False, include_original_features: no_org, averageAUROC: 0.5878482, HammingLoss: 0.34091, SubsetAccuracy: 0.22727, RankingLoss: 0.25899, MacroPrecision: 0.2943, MacroRecall: 0.40967, MacroFOne: 0.3368,

Fold 2/10 (fingerprint_low_freq 11/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [02:59<00:00,  3.01feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5507504, HammingLoss: 0.24747, SubsetAccuracy: 0.37879, RankingLoss: 0.24045, MacroPrecision: 0.0, MacroRecall: 0.031965, MacroFOne: 0.0,
pruning: False, include_original_features: with_org, averageAUROC: 0.6136699, HammingLoss: 0.30808, SubsetAccuracy: 0.20455, RankingLoss: 0.27818, MacroPrecision: 0.38638, MacroRecall: 0.43378, MacroFOne: 0.40672,
pruning: True, include_original_features: no_org, averageAUROC: 0.5450508, HammingLoss: 0.24874, SubsetAccuracy: 0.37879, RankingLoss: 0.23977, MacroPrecision: 0.0, MacroRecall: 0.021033, MacroFOne: 0.0,
pruning: False, include_original_features: no_org, averageAUROC: 0.6213717, HammingLoss: 0.33586, SubsetAccuracy: 0.16667, RankingLoss: 0.26019, MacroPrecision: 0.35381, MacroRecall: 0.46484, MacroFOne: 0.39925,

Fold 3/10 (fingerprint_low_freq 11/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [02:59<00:00,  3.02feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5, HammingLoss: 0.2298, SubsetAccuracy: 0.40909, RankingLoss: 0.2826, MacroPrecision: 0.0, MacroRecall: 0.0, MacroFOne: 0.0,
pruning: False, include_original_features: with_org, averageAUROC: 0.6044256, HammingLoss: 0.32071, SubsetAccuracy: 0.16667, RankingLoss: 0.23131, MacroPrecision: 0.33222, MacroRecall: 0.3839, MacroFOne: 0.3547,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.2298, SubsetAccuracy: 0.40909, RankingLoss: 0.2826, MacroPrecision: 0.0, MacroRecall: 0.0, MacroFOne: 0.0,
pruning: False, include_original_features: no_org, averageAUROC: 0.6074084, HammingLoss: 0.33081, SubsetAccuracy: 0.17424, RankingLoss: 0.21959, MacroPrecision: 0.34518, MacroRecall: 0.46607, MacroFOne: 0.39395,

Fold 4/10 (fingerprint_low_freq 11/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [02:59<00:00,  3.01feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5235443, HammingLoss: 0.25253, SubsetAccuracy: 0.33333, RankingLoss: 0.28923, MacroPrecision: 0.32361, MacroRecall: 0.07089, MacroFOne: 0.0,
pruning: False, include_original_features: with_org, averageAUROC: 0.5895532, HammingLoss: 0.34091, SubsetAccuracy: 0.19697, RankingLoss: 0.26801, MacroPrecision: 0.32352, MacroRecall: 0.40971, MacroFOne: 0.36116,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.23611, SubsetAccuracy: 0.35606, RankingLoss: 0.29811, MacroPrecision: 0.0, MacroRecall: 0.0, MacroFOne: 0.0,
pruning: False, include_original_features: no_org, averageAUROC: 0.6151801, HammingLoss: 0.31944, SubsetAccuracy: 0.18182, RankingLoss: 0.23782, MacroPrecision: 0.34619, MacroRecall: 0.41358, MacroFOne: 0.37549,

Fold 5/10 (fingerprint_low_freq 11/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [02:59<00:00,  3.01feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5, HammingLoss: 0.26768, SubsetAccuracy: 0.32576, RankingLoss: 0.28011, MacroPrecision: 0.0, MacroRecall: 0.0, MacroFOne: 0.0,
pruning: False, include_original_features: with_org, averageAUROC: 0.6073129, HammingLoss: 0.34722, SubsetAccuracy: 0.21212, RankingLoss: 0.25008, MacroPrecision: 0.36202, MacroRecall: 0.40048, MacroFOne: 0.37896,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.26768, SubsetAccuracy: 0.32576, RankingLoss: 0.28011, MacroPrecision: 0.0, MacroRecall: 0.0, MacroFOne: 0.0,
pruning: False, include_original_features: no_org, averageAUROC: 0.6268515, HammingLoss: 0.34091, SubsetAccuracy: 0.16667, RankingLoss: 0.23607, MacroPrecision: 0.38009, MacroRecall: 0.45073, MacroFOne: 0.41175,

Fold 6/10 (fingerprint_low_freq 11/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [02:58<00:00,  3.02feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5, HammingLoss: 0.24242, SubsetAccuracy: 0.38636, RankingLoss: 0.35412, MacroPrecision: 0.0, MacroRecall: 0.0, MacroFOne: 0.0,
pruning: False, include_original_features: with_org, averageAUROC: 0.5496317, HammingLoss: 0.35732, SubsetAccuracy: 0.20455, RankingLoss: 0.29606, MacroPrecision: 0.29563, MacroRecall: 0.3432, MacroFOne: 0.31183,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.24242, SubsetAccuracy: 0.38636, RankingLoss: 0.35412, MacroPrecision: 0.0, MacroRecall: 0.0, MacroFOne: 0.0,
pruning: False, include_original_features: no_org, averageAUROC: 0.5758009, HammingLoss: 0.35227, SubsetAccuracy: 0.14394, RankingLoss: 0.25537, MacroPrecision: 0.32019, MacroRecall: 0.40125, MacroFOne: 0.35233,

Fold 7/10 (fingerprint_low_freq 11/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [03:01<00:00,  2.97feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5, HammingLoss: 0.28157, SubsetAccuracy: 0.33333, RankingLoss: 0.3436, MacroPrecision: 0.0, MacroRecall: 0.0, MacroFOne: 0.0,
pruning: False, include_original_features: with_org, averageAUROC: 0.5737798, HammingLoss: 0.37753, SubsetAccuracy: 0.14394, RankingLoss: 0.28024, MacroPrecision: 0.34957, MacroRecall: 0.39281, MacroFOne: 0.36797,
pruning: True, include_original_features: no_org, averageAUROC: 0.5463754, HammingLoss: 0.28283, SubsetAccuracy: 0.33333, RankingLoss: 0.33112, MacroPrecision: 0.0, MacroRecall: 0.049392, MacroFOne: 0.0,
pruning: False, include_original_features: no_org, averageAUROC: 0.5923672, HammingLoss: 0.33207, SubsetAccuracy: 0.16667, RankingLoss: 0.25688, MacroPrecision: 0.4152, MacroRecall: 0.42748, MacroFOne: 0.41838,

Fold 8/10 (fingerprint_low_freq 11/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [02:59<00:00,  3.02feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5626373, HammingLoss: 0.22646, SubsetAccuracy: 0.38931, RankingLoss: 0.27769, MacroPrecision: 0.44986, MacroRecall: 0.10647, MacroFOne: 0.16925,
pruning: False, include_original_features: with_org, averageAUROC: 0.5964106, HammingLoss: 0.35369, SubsetAccuracy: 0.19084, RankingLoss: 0.24258, MacroPrecision: 0.3146, MacroRecall: 0.47066, MacroFOne: 0.37463,
pruning: True, include_original_features: no_org, averageAUROC: 0.5799791, HammingLoss: 0.22137, SubsetAccuracy: 0.38168, RankingLoss: 0.28075, MacroPrecision: 0.51751, MacroRecall: 0.12644, MacroFOne: 0.0,
pruning: False, include_original_features: no_org, averageAUROC: 0.5983908, HammingLoss: 0.35496, SubsetAccuracy: 0.16031, RankingLoss: 0.25564, MacroPrecision: 0.30045, MacroRecall: 0.4301, MacroFOne: 0.35146,

Fold 9/10 (fingerprint_low_freq 11/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [03:00<00:00,  3.00feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5, HammingLoss: 0.27354, SubsetAccuracy: 0.32824, RankingLoss: 0.30172, MacroPrecision: 0.0, MacroRecall: 0.0, MacroFOne: 0.0,
pruning: False, include_original_features: with_org, averageAUROC: 0.5877731, HammingLoss: 0.34987, SubsetAccuracy: 0.21374, RankingLoss: 0.26011, MacroPrecision: 0.36482, MacroRecall: 0.37241, MacroFOne: 0.36558,
pruning: True, include_original_features: no_org, averageAUROC: 0.5, HammingLoss: 0.27354, SubsetAccuracy: 0.32824, RankingLoss: 0.30172, MacroPrecision: 0.0, MacroRecall: 0.0, MacroFOne: 0.0,
pruning: False, include_original_features: no_org, averageAUROC: 0.5736281, HammingLoss: 0.35496, SubsetAccuracy: 0.22137, RankingLoss: 0.26616, MacroPrecision: 0.35529, MacroRecall: 0.36742, MacroFOne: 0.36067,

Fold 10/10 (fingerprint_low_freq 11/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [02:59<00:00,  3.01feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5057318, HammingLoss: 0.23155, SubsetAccuracy: 0.38931, RankingLoss: 0.25509, MacroPrecision: 0.29861, MacroRecall: 0.043283, MacroFOne: 0.0,
pruning: False, include_original_features: with_org, averageAUROC: 0.6084065, HammingLoss: 0.3117, SubsetAccuracy: 0.19084, RankingLoss: 0.21781, MacroPrecision: 0.31649, MacroRecall: 0.39154, MacroFOne: 0.34946,
pruning: True, include_original_features: no_org, averageAUROC: 0.4989474, HammingLoss: 0.243, SubsetAccuracy: 0.38168, RankingLoss: 0.26111, MacroPrecision: 0.19491, MacroRecall: 0.046458, MacroFOne: 0.0,
pruning: False, include_original_features: no_org, averageAUROC: 0.5858484, HammingLoss: 0.37405, SubsetAccuracy: 0.14504, RankingLoss: 0.27347, MacroPrecision: 0.27543, MacroRecall: 0.45821, MacroFOne: 0.34182,
   pruning include_original_features               dataset  averageAUROC  \
0    False                    no_org  fingerprint_low_freq      0.598470
1    False                  with_org  fingerprint_low_freq      0.589831
2     True                    no_org  fingerprint_low_freq      0.517035
3     True                  with_org  fingerprint_low_freq      0.514266

   HammingLoss  SubsetAccuracy  RankingLoss  MacroPrecision  MacroRecall  \
0     0.343624        0.175400     0.252018        0.338613     0.428935
1     0.343824        0.190604     0.257230        0.329980     0.399092
2     0.245761        0.370523     0.291777        0.071242     0.024332
3     0.246514        0.369776     0.291297        0.107208     0.025261

   MacroFOne  nodes  leaves  groups  avg_group_features  gen_XofN_time  \
0   0.374190  850.6   425.8   108.0                 5.0     179.298568
1   0.357813  837.2   419.1   108.0                 5.0     179.298568
2   0.000000   13.4     7.2   108.0                 5.0     179.298568
3   0.016925   14.0     7.5   108.0                 5.0     179.298568

   training_time
0       0.660325
1       1.271389
2       0.660325
3       1.271389

--- Running with label:'['se_C0020538', 'se_C0008031', 'se_C0003467', 'se_C0036572', 'se_C0030252', 'se_C0027769']' training_algorithm:'Variance Reduction' eval_criterion:'['averageAUROC', 'HammingLoss', 'SubsetAccuracy', 'RankingLoss', 'MacroPrecision', 'MacroRecall', 'MacroFOne']' max_size:'5' ---
Logs can be found in XofN_filter_jaccard/logs/fingerprint_mid_freq_Variance Reduction_averageAUROC_HammingLoss_SubsetAccuracy_RankingLoss_MacroPrecision_MacroRecall_MacroFOne_5_logs.txt.

Fold 1/10 (fingerprint_mid_freq 12/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [02:59<00:00,  3.00feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.590408, HammingLoss: 0.4154, SubsetAccuracy: 0.15152, RankingLoss: 0.23952, MacroPrecision: 0.44103, MacroRecall: 0.37662, MacroFOne: 0.40067,
pruning: False, include_original_features: with_org, averageAUROC: 0.5797628, HammingLoss: 0.43182, SubsetAccuracy: 0.098485, RankingLoss: 0.23929, MacroPrecision: 0.44052, MacroRecall: 0.5737, MacroFOne: 0.49696,
pruning: True, include_original_features: no_org, averageAUROC: 0.5866383, HammingLoss: 0.41414, SubsetAccuracy: 0.19697, RankingLoss: 0.27203, MacroPrecision: 0.44701, MacroRecall: 0.4071, MacroFOne: 0.42252,
pruning: False, include_original_features: no_org, averageAUROC: 0.6013678, HammingLoss: 0.43687, SubsetAccuracy: 0.098485, RankingLoss: 0.26393, MacroPrecision: 0.4373, MacroRecall: 0.56059, MacroFOne: 0.48799,

Fold 2/10 (fingerprint_mid_freq 12/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [02:58<00:00,  3.02feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5440172, HammingLoss: 0.37753, SubsetAccuracy: 0.27273, RankingLoss: 0.24672, MacroPrecision: 0.40599, MacroRecall: 0.32683, MacroFOne: 0.36101,
pruning: False, include_original_features: with_org, averageAUROC: 0.5697769, HammingLoss: 0.42929, SubsetAccuracy: 0.12121, RankingLoss: 0.25008, MacroPrecision: 0.38271, MacroRecall: 0.49731, MacroFOne: 0.43231,
pruning: True, include_original_features: no_org, averageAUROC: 0.5310059, HammingLoss: 0.39015, SubsetAccuracy: 0.27273, RankingLoss: 0.24621, MacroPrecision: 0.41103, MacroRecall: 0.40654, MacroFOne: 0.40687,
pruning: False, include_original_features: no_org, averageAUROC: 0.5483248, HammingLoss: 0.45455, SubsetAccuracy: 0.10606, RankingLoss: 0.24434, MacroPrecision: 0.36367, MacroRecall: 0.51416, MacroFOne: 0.42532,

Fold 3/10 (fingerprint_mid_freq 12/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [03:00<00:00,  3.00feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5687811, HammingLoss: 0.40025, SubsetAccuracy: 0.16667, RankingLoss: 0.25044, MacroPrecision: 0.46034, MacroRecall: 0.35865, MacroFOne: 0.40012,
pruning: False, include_original_features: with_org, averageAUROC: 0.6051718, HammingLoss: 0.41919, SubsetAccuracy: 0.12879, RankingLoss: 0.23104, MacroPrecision: 0.45614, MacroRecall: 0.5602, MacroFOne: 0.50047,
pruning: True, include_original_features: no_org, averageAUROC: 0.610642, HammingLoss: 0.36237, SubsetAccuracy: 0.26515, RankingLoss: 0.26808, MacroPrecision: 0.53146, MacroRecall: 0.40498, MacroFOne: 0.45616,
pruning: False, include_original_features: no_org, averageAUROC: 0.6100577, HammingLoss: 0.40657, SubsetAccuracy: 0.11364, RankingLoss: 0.24215, MacroPrecision: 0.46582, MacroRecall: 0.57559, MacroFOne: 0.51286,

Fold 4/10 (fingerprint_mid_freq 12/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [02:59<00:00,  3.00feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5413877, HammingLoss: 0.3952, SubsetAccuracy: 0.2197, RankingLoss: 0.25318, MacroPrecision: 0.4647, MacroRecall: 0.3028, MacroFOne: 0.36348,
pruning: False, include_original_features: with_org, averageAUROC: 0.5751321, HammingLoss: 0.42803, SubsetAccuracy: 0.15152, RankingLoss: 0.24863, MacroPrecision: 0.43352, MacroRecall: 0.46283, MacroFOne: 0.4469,
pruning: True, include_original_features: no_org, averageAUROC: 0.6417482, HammingLoss: 0.32323, SubsetAccuracy: 0.26515, RankingLoss: 0.22872, MacroPrecision: 0.60555, MacroRecall: 0.40402, MacroFOne: 0.48229,
pruning: False, include_original_features: no_org, averageAUROC: 0.6743541, HammingLoss: 0.32449, SubsetAccuracy: 0.2197, RankingLoss: 0.2153, MacroPrecision: 0.56655, MacroRecall: 0.5873, MacroFOne: 0.57574,

Fold 5/10 (fingerprint_mid_freq 12/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [03:00<00:00,  3.00feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.577544, HammingLoss: 0.36364, SubsetAccuracy: 0.2803, RankingLoss: 0.29585, MacroPrecision: 0.483, MacroRecall: 0.38989, MacroFOne: 0.43102,
pruning: False, include_original_features: with_org, averageAUROC: 0.6008833, HammingLoss: 0.40404, SubsetAccuracy: 0.19697, RankingLoss: 0.25196, MacroPrecision: 0.44246, MacroRecall: 0.52401, MacroFOne: 0.47869,
pruning: True, include_original_features: no_org, averageAUROC: 0.5351324, HammingLoss: 0.39015, SubsetAccuracy: 0.27273, RankingLoss: 0.30928, MacroPrecision: 0.43745, MacroRecall: 0.36149, MacroFOne: 0.39476,
pruning: False, include_original_features: no_org, averageAUROC: 0.5364756, HammingLoss: 0.45455, SubsetAccuracy: 0.13636, RankingLoss: 0.25391, MacroPrecision: 0.38642, MacroRecall: 0.4706, MacroFOne: 0.4229,

Fold 6/10 (fingerprint_mid_freq 12/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [03:00<00:00,  3.00feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.6012307, HammingLoss: 0.36742, SubsetAccuracy: 0.23485, RankingLoss: 0.2713, MacroPrecision: 0.51698, MacroRecall: 0.34998, MacroFOne: 0.41583,
pruning: False, include_original_features: with_org, averageAUROC: 0.5751217, HammingLoss: 0.42172, SubsetAccuracy: 0.12879, RankingLoss: 0.27294, MacroPrecision: 0.44794, MacroRecall: 0.4833, MacroFOne: 0.46324,
pruning: True, include_original_features: no_org, averageAUROC: 0.6322837, HammingLoss: 0.33207, SubsetAccuracy: 0.2803, RankingLoss: 0.25882, MacroPrecision: 0.57839, MacroRecall: 0.45772, MacroFOne: 0.50879,
pruning: False, include_original_features: no_org, averageAUROC: 0.5864985, HammingLoss: 0.41667, SubsetAccuracy: 0.098485, RankingLoss: 0.25446, MacroPrecision: 0.45791, MacroRecall: 0.52313, MacroFOne: 0.48695,

Fold 7/10 (fingerprint_mid_freq 12/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [03:00<00:00,  3.00feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5805436, HammingLoss: 0.39141, SubsetAccuracy: 0.2803, RankingLoss: 0.28197, MacroPrecision: 0.45479, MacroRecall: 0.323, MacroFOne: 0.37677,
pruning: False, include_original_features: with_org, averageAUROC: 0.6110272, HammingLoss: 0.38005, SubsetAccuracy: 0.21212, RankingLoss: 0.23542, MacroPrecision: 0.48489, MacroRecall: 0.52907, MacroFOne: 0.50429,
pruning: True, include_original_features: no_org, averageAUROC: 0.5962814, HammingLoss: 0.35227, SubsetAccuracy: 0.29545, RankingLoss: 0.25276, MacroPrecision: 0.52808, MacroRecall: 0.38728, MacroFOne: 0.44593,
pruning: False, include_original_features: no_org, averageAUROC: 0.6007672, HammingLoss: 0.39899, SubsetAccuracy: 0.14394, RankingLoss: 0.22401, MacroPrecision: 0.46776, MacroRecall: 0.59361, MacroFOne: 0.52267,

Fold 8/10 (fingerprint_mid_freq 12/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [03:00<00:00,  3.00feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.6008566, HammingLoss: 0.38258, SubsetAccuracy: 0.14394, RankingLoss: 0.28032, MacroPrecision: 0.46737, MacroRecall: 0.37794, MacroFOne: 0.4155,
pruning: False, include_original_features: with_org, averageAUROC: 0.6021439, HammingLoss: 0.4154, SubsetAccuracy: 0.14394, RankingLoss: 0.26359, MacroPrecision: 0.44601, MacroRecall: 0.52384, MacroFOne: 0.48035,
pruning: True, include_original_features: no_org, averageAUROC: 0.5551545, HammingLoss: 0.40909, SubsetAccuracy: 0.15152, RankingLoss: 0.32104, MacroPrecision: 0.41747, MacroRecall: 0.30392, MacroFOne: 0.34974,
pruning: False, include_original_features: no_org, averageAUROC: 0.5770724, HammingLoss: 0.40152, SubsetAccuracy: 0.10606, RankingLoss: 0.28228, MacroPrecision: 0.45456, MacroRecall: 0.51722, MacroFOne: 0.48316,

Fold 9/10 (fingerprint_mid_freq 12/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [02:59<00:00,  3.00feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.568211, HammingLoss: 0.41858, SubsetAccuracy: 0.19084, RankingLoss: 0.27263, MacroPrecision: 0.47959, MacroRecall: 0.37216, MacroFOne: 0.41814,
pruning: False, include_original_features: with_org, averageAUROC: 0.5640815, HammingLoss: 0.43257, SubsetAccuracy: 0.099237, RankingLoss: 0.26402, MacroPrecision: 0.46511, MacroRecall: 0.46679, MacroFOne: 0.46512,
pruning: True, include_original_features: no_org, averageAUROC: 0.5861436, HammingLoss: 0.40712, SubsetAccuracy: 0.16794, RankingLoss: 0.27432, MacroPrecision: 0.49504, MacroRecall: 0.42336, MacroFOne: 0.45457,
pruning: False, include_original_features: no_org, averageAUROC: 0.5857914, HammingLoss: 0.42875, SubsetAccuracy: 0.083969, RankingLoss: 0.26472, MacroPrecision: 0.47059, MacroRecall: 0.52897, MacroFOne: 0.4963,

Fold 10/10 (fingerprint_mid_freq 12/12)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [02:59<00:00,  3.00feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.6210985, HammingLoss: 0.3715, SubsetAccuracy: 0.19847, RankingLoss: 0.23743, MacroPrecision: 0.49241, MacroRecall: 0.40669, MacroFOne: 0.44508,
pruning: False, include_original_features: with_org, averageAUROC: 0.5968646, HammingLoss: 0.39567, SubsetAccuracy: 0.16031, RankingLoss: 0.22966, MacroPrecision: 0.47208, MacroRecall: 0.55767, MacroFOne: 0.5109,
pruning: True, include_original_features: no_org, averageAUROC: 0.6674475, HammingLoss: 0.32188, SubsetAccuracy: 0.22901, RankingLoss: 0.22434, MacroPrecision: 0.57828, MacroRecall: 0.46781, MacroFOne: 0.51473,
pruning: False, include_original_features: no_org, averageAUROC: 0.6285753, HammingLoss: 0.39186, SubsetAccuracy: 0.16031, RankingLoss: 0.25002, MacroPrecision: 0.47165, MacroRecall: 0.54005, MacroFOne: 0.50286,
   pruning include_original_features               dataset  averageAUROC  \
0    False                    no_org  fingerprint_mid_freq      0.594928
1    False                  with_org  fingerprint_mid_freq      0.587997
2     True                    no_org  fingerprint_mid_freq      0.594248
3     True                  with_org  fingerprint_mid_freq      0.579408

   HammingLoss  SubsetAccuracy  RankingLoss  MacroPrecision  MacroRecall  \
0     0.411482        0.126701     0.249512        0.454223     0.541122
1     0.415778        0.144137     0.248663        0.447138     0.517872
2     0.370247        0.239695     0.265560        0.502976     0.402422
3     0.388351        0.213932     0.262936        0.466620     0.358456

   MacroFOne  nodes  leaves  groups  avg_group_features  gen_XofN_time  \
0   0.491675  890.4   445.7   108.0                 5.0     179.886424
1   0.477923  874.4   437.7   108.0                 5.0     179.886424
2   0.443636  156.2    78.6   108.0                 5.0     179.886424
3   0.402762  165.0    83.0   108.0                 5.0     179.886424

   training_time
0       0.687208
1       1.331792
2       0.687208
3       1.331792

In [4]:
# All results
save_path = "XofN_filter_jaccard/"
final_grouped_res = pd.DataFrame()
for df in cv_results:
    final_grouped_res = pd.concat([final_grouped_res, df])
final_grouped_res.sort_values(by='dataset', ascending=False, inplace=True)
final_grouped_res = final_grouped_res.reset_index(drop=True)
final_grouped_res.to_csv(save_path + "all_results.csv")
final_grouped_res

,pruning,include_original_features,dataset,averageAUROC,HammingLoss,SubsetAccuracy,RankingLoss,MacroPrecision,MacroRecall,MacroFOne,nodes,leaves,groups,avg_group_features,gen_XofN_time,training_time
0,True,with_org,fingerprint_mid_freq,0.579408,0.388351,0.213932,0.262936,0.466620,0.358456,0.402762,165.0,83.0,108.0,5.000000,179.886424,1.331792
1,True,no_org,fingerprint_mid_freq,0.594248,0.370247,0.239695,0.265560,0.502976,0.402422,0.443636,156.2,78.6,108.0,5.000000,179.886424,0.687208
2,False,with_org,fingerprint_mid_freq,0.587997,0.415778,0.144137,0.248663,0.447138,0.517872,0.477923,874.4,437.7,108.0,5.000000,179.886424,1.331792
3,False,no_org,fingerprint_mid_freq,0.594928,0.411482,0.126701,0.249512,0.454223,0.541122,0.491675,890.4,445.7,108.0,5.000000,179.886424,0.687208
4,True,with_org,fingerprint_low_freq,0.514266,0.246514,0.369776,0.291297,0.107208,0.025261,0.016925,14.0,7.5,108.0,5.000000,179.298568,1.271389
5,True,no_org,fingerprint_low_freq,0.517035,0.245761,0.370523,0.291777,0.071242,0.024332,0.000000,13.4,7.2,108.0,5.000000,179.298568,0.660325
6,False,with_org,fingerprint_low_freq,0.589831,0.343824,0.190604,0.257230,0.329980,0.399092,0.357813,837.2,419.1,108.0,5.000000,179.298568,1.271389
7,False,no_org,fingerprint_low_freq,0.598470,0.343624,0.175400,0.252018,0.338613,0.428935,0.374190,850.6,425.8,108.0,5.000000,179.298568,0.660325
8,True,no_org,fingerprint_high_freq,0.571387,0.230251,0.501533,0.162637,0.794673,0.950802,0.864962,44.6,22.8,108.0,5.000000,178.951654,0.688364
9,False,no_org,fingerprint_high_freq,0.578008,0.276338,0.372346,0.161691,0.799650,0.859393,0.827641,599.2,300.1,108.0,5.000000,178.951654,0.688364
10,False,with_org,fingerprint_high_freq,0.574284,0.269620,0.393675,0.164730,0.803396,0.863962,0.831982,587.6,294.3,108.0,5.000000,178.951654,1.303322
11,True,with_org,fingerprint_high_freq,0.567555,0.234164,0.501544,0.165019,0.793356,0.946554,0.862471,55.0,28.0,108.0,5.000000,178.951654,1.303322
12,True,with_org,fingerprint_cardiac,0.557270,0.278916,0.343183,0.232964,0.371584,0.126285,0.150927,55.8,28.4,108.0,5.000000,178.227184,1.314020
13,True,no_org,fingerprint_cardiac,0.537954,0.267425,0.368939,0.225040,0.273475,0.076174,0.069731,29.2,15.1,108.0,5.000000,178.227184,0.680010
14,False,with_org,fingerprint_cardiac,0.575088,0.355934,0.179547,0.210469,0.333732,0.411542,0.363462,816.2,408.6,108.0,5.000000,178.227184,1.314020
15,False,no_org,fingerprint_cardiac,0.573445,0.362753,0.173485,0.216452,0.327833,0.419440,0.363087,839.2,420.1,108.0,5.000000,178.227184,0.680010
16,True,with_org,CPI_mid_freq,0.587879,0.383031,0.243243,0.258877,0.510275,0.361032,0.418160,116.2,58.6,322.0,4.990683,836.519708,2.758859
17,True,no_org,CPI_mid_freq,0.599649,0.368380,0.239640,0.259679,0.538117,0.362006,0.428320,108.2,54.6,322.0,4.990683,836.519708,0.975656
18,False,with_org,CPI_mid_freq,0.574169,0.416175,0.149059,0.265281,0.468353,0.523523,0.491300,720.0,360.5,322.0,4.990683,836.519708,2.758859
19,False,no_org,CPI_mid_freq,0.588762,0.413648,0.132852,0.266541,0.475709,0.547830,0.506024,709.8,355.4,322.0,4.990683,836.519708,0.975656
20,False,with_org,CPI_low_freq,0.596426,0.328453,0.180630,0.270193,0.390530,0.437366,0.408254,699.2,350.1,322.0,4.990683,830.685217,2.656676
21,True,with_org,CPI_low_freq,0.600381,0.262970,0.324671,0.288248,0.485958,0.188743,0.266606,60.6,30.8,322.0,4.990683,830.685217,2.656676
22,True,no_org,CPI_low_freq,0.584551,0.267437,0.318395,0.283140,0.479386,0.148285,0.168192,47.8,24.4,322.0,4.990683,830.685217,0.950147
23,False,no_org,CPI_low_freq,0.597518,0.321991,0.180679,0.262503,0.389166,0.411979,0.397686,702.4,351.7,322.0,4.990683,830.685217,0.950147
24,True,no_org,CPI_high_freq,0.569453,0.218545,0.532665,0.160444,0.796080,0.971798,0.874360,21.2,11.1,322.0,4.990683,828.051776,0.894655
25,False,with_org,CPI_high_freq,0.586050,0.255056,0.429416,0.162914,0.803452,0.892657,0.845000,442.8,221.9,322.0,4.990683,828.051776,2.588701
26,False,no_org,CPI_high_freq,0.591829,0.250892,0.422201,0.162553,0.806288,0.895217,0.847646,424.2,212.6,322.0,4.990683,828.051776,0.894655
27,True,with_org,CPI_high_freq,0.604635,0.214178,0.534483,0.161046,0.799999,0.971566,0.876526,33.0,17.0,322.0,4.990683,828.051776,2.588701
28,True,with_org,CPI_cardiac,0.568752,0.280655,0.339286,0.235201,0.440732,0.181748,0.214238,58.2,29.6,322.0,4.990683,819.026572,2.733522
29,True,no_org,CPI_cardiac,0.579991,0.278423,0.341964,0.231685,0.456975,0.187833,0.260192,54.8,27.9,322.0,4.990683,819.026572,0.951930
30,False,with_org,CPI_cardiac,0.568054,0.345386,0.212498,0.240520,0.364566,0.408676,0.380198,691.0,346.0,322.0,4.990683,819.026572,2.733522
31,False,no_org,CPI_cardiac,0.577531,0.349852,0.191963,0.244744,0.370946,0.449940,0.400210,681.4,341.2,322.0,4.990683,819.026572,0.951930
32,False,no_org,CPI+fingerprint_mid_freq,0.598469,0.397646,0.136045,0.254457,0.459014,0.519674,0.485655,895.6,448.3,430.0,4.993023,1265.490809,1.150093
33,False,with_org,CPI+fingerprint_mid_freq,0.594551,0.395847,0.151907,0.257301,0.464612,0.511935,0.484809,887.0,444.0,430.0,4.993023,1265.490809,3.536142
34,True,no_org,CPI+fingerprint_mid_freq,0.612870,0.351685,0.258462,0.262039,0.527669,0.387198,0.444035,157.8,79.4,430.0,4.993023,1265.490809,1.150093
35,True,with_org,CPI+fingerprint_mid_freq,0.609535,0.358180,0.251259,0.258145,0.516505,0.364970,0.424738,159.0,80.0,430.0,4.993023,1265.490809,3.536142
36,True,with_org,CPI+fingerprint_low_freq,0.604060,0.247228,0.358800,0.266515,0.458073,0.166366,0.238512,67.2,34.1,430.0,4.993023,1257.513742,3.850259
37,True,no_org,CPI+fingerprint_low_freq,0.599212,0.245191,0.357351,0.273758,0.474642,0.160097,0.233264,53.4,27.2,430.0,4.993023,1257.513742,1.274746
38,False,with_org,CPI+fingerprint_low_freq,0.595582,0.328374,0.194505,0.254029,0.343843,0.403306,0.366116,850.6,425.8,430.0,4.993023,1257.513742,3.850259
39,False,no_org,CPI+fingerprint_low_freq,0.603278,0.325381,0.195224,0.261745,0.350776,0.425188,0.381005,864.4,432.7,430.0,4.993023,1257.513742,1.274746
40,True,with_org,CPI+fingerprint_high_freq,0.601655,0.237068,0.495276,0.157069,0.794401,0.935926,0.858349,72.6,36.8,430.0,4.993023,1248.124692,3.526549
41,True,no_org,CPI+fingerprint_high_freq,0.600586,0.235508,0.498170,0.157264,0.795637,0.936154,0.859269,72.0,36.5,430.0,4.993023,1248.124692,1.193662
42,False,with_org,CPI+fingerprint_high_freq,0.600484,0.268448,0.377765,0.155465,0.804569,0.858584,0.829977,601.8,301.4,430.0,4.993023,1248.124692,3.526549
43,False,no_org,CPI+fingerprint_high_freq,0.603194,0.264951,0.390012,0.150698,0.805045,0.865220,0.833346,609.0,305.0,430.0,4.993023,1248.124692,1.193662
44,True,no_org,CPI+fingerprint_cardiac,0.587069,0.267686,0.368599,0.222005,0.429829,0.157833,0.226510,65.8,33.4,430.0,4.993023,1220.069503,1.218612
45,False,with_org,CPI+fingerprint_cardiac,0.587098,0.345079,0.210244,0.226599,0.344180,0.413242,0.372499,827.4,414.2,430.0,4.993023,1220.069503,3.839335
46,True,with_org,CPI+fingerprint_cardiac,0.596266,0.271643,0.366432,0.228423,0.429135,0.195726,0.262257,85.8,43.4,430.0,4.993023,1220.069503,3.839335
47,False,no_org,CPI+fingerprint_cardiac,0.585914,0.347236,0.205921,0.220427,0.344864,0.418121,0.374981,844.6,422.8,430.0,4.993023,1220.069503,1.218612

In [5]:
# Table ready (with pruning, rounded, compact)
save_path = "XofN_filter_jaccard/"
rounded_final_grouped_res = pd.read_csv(save_path + "all_results.csv", index_col=0)
res = pd.read_csv(save_path + "all_results.csv", index_col=0)
table_results = get_table_results(res, eval_criteria, get_dataset_paths())
table_results.to_csv(save_path + "table_results.csv")
table_results

,include_original_features,dataset,averageAUROC,HammingLoss,SubsetAccuracy,RankingLoss,MacroPrecision,MacroRecall,MacroFOne,Nodes; Leaves,#XofN; #Feat/XofN,# Ung. Feats,XofN time (s); PCT tr. time (s)
1,no_org,fingerprint_mid_freq,0.594,0.370,0.240,0.266,0.503,0.402,0.444,156.2; 78.6,108.0; 5.0,0.0,179.9; 0.7
0,with_org,fingerprint_mid_freq,0.579,0.388,0.214,0.263,0.467,0.358,0.403,165.0; 83.0,108.0; 5.0,0.0,179.9; 1.3
5,no_org,fingerprint_low_freq,0.517,0.246,0.371,0.292,0.071,0.024,0.000,13.4; 7.2,108.0; 5.0,0.0,179.3; 0.7
4,with_org,fingerprint_low_freq,0.514,0.247,0.370,0.291,0.107,0.025,0.017,14.0; 7.5,108.0; 5.0,0.0,179.3; 1.3
8,no_org,fingerprint_high_freq,0.571,0.230,0.502,0.163,0.795,0.951,0.865,44.6; 22.8,108.0; 5.0,0.0,179.0; 0.7
11,with_org,fingerprint_high_freq,0.568,0.234,0.502,0.165,0.793,0.947,0.862,55.0; 28.0,108.0; 5.0,0.0,179.0; 1.3
13,no_org,fingerprint_cardiac,0.538,0.267,0.369,0.225,0.273,0.076,0.070,29.2; 15.1,108.0; 5.0,0.0,178.2; 0.7
12,with_org,fingerprint_cardiac,0.557,0.279,0.343,0.233,0.372,0.126,0.151,55.8; 28.4,108.0; 5.0,0.0,178.2; 1.3
17,no_org,CPI_mid_freq,0.600,0.368,0.240,0.260,0.538,0.362,0.428,108.2; 54.6,322.0; 5.0,0.0,836.5; 1.0
16,with_org,CPI_mid_freq,0.588,0.383,0.243,0.259,0.510,0.361,0.418,116.2; 58.6,322.0; 5.0,0.0,836.5; 2.8
22,no_org,CPI_low_freq,0.585,0.267,0.318,0.283,0.479,0.148,0.168,47.8; 24.4,322.0; 5.0,0.0,830.7; 1.0
21,with_org,CPI_low_freq,0.600,0.263,0.325,0.288,0.486,0.189,0.267,60.6; 30.8,322.0; 5.0,0.0,830.7; 2.7
24,no_org,CPI_high_freq,0.569,0.219,0.533,0.160,0.796,0.972,0.874,21.2; 11.1,322.0; 5.0,0.0,828.1; 0.9
27,with_org,CPI_high_freq,0.605,0.214,0.534,0.161,0.800,0.972,0.877,33.0; 17.0,322.0; 5.0,0.0,828.1; 2.6
29,no_org,CPI_cardiac,0.580,0.278,0.342,0.232,0.457,0.188,0.260,54.8; 27.9,322.0; 5.0,0.0,819.0; 1.0
28,with_org,CPI_cardiac,0.569,0.281,0.339,0.235,0.441,0.182,0.214,58.2; 29.6,322.0; 5.0,0.0,819.0; 2.7
34,no_org,CPI+fingerprint_mid_freq,0.613,0.352,0.258,0.262,0.528,0.387,0.444,157.8; 79.4,430.0; 5.0,0.0,1265.5; 1.2
35,with_org,CPI+fingerprint_mid_freq,0.610,0.358,0.251,0.258,0.517,0.365,0.425,159.0; 80.0,430.0; 5.0,0.0,1265.5; 3.5
37,no_org,CPI+fingerprint_low_freq,0.599,0.245,0.357,0.274,0.475,0.160,0.233,53.4; 27.2,430.0; 5.0,0.0,1257.5; 1.3
36,with_org,CPI+fingerprint_low_freq,0.604,0.247,0.359,0.267,0.458,0.166,0.239,67.2; 34.1,430.0; 5.0,0.0,1257.5; 3.9
41,no_org,CPI+fingerprint_high_freq,0.601,0.236,0.498,0.157,0.796,0.936,0.859,72.0; 36.5,430.0; 5.0,0.0,1248.1; 1.2
40,with_org,CPI+fingerprint_high_freq,0.602,0.237,0.495,0.157,0.794,0.936,0.858,72.6; 36.8,430.0; 5.0,0.0,1248.1; 3.5
44,no_org,CPI+fingerprint_cardiac,0.587,0.268,0.369,0.222,0.430,0.158,0.227,65.8; 33.4,430.0; 5.0,0.0,1220.1; 1.2
46,with_org,CPI+fingerprint_cardiac,0.596,0.272,0.366,0.228,0.429,0.196,0.262,85.8; 43.4,430.0; 5.0,0.0,1220.1; 3.8